"""Module topics bringing Business Analytics, Web Development,
Cybersecurity, and Cloud Computing up to 20+ lessons per level (C1
through M1)."""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Business Analytics": {
        "C1": [
            ("Spreadsheet Modeling for Business", "Introduces building structured spreadsheet models with formulas, named ranges, and what-if analysis to support everyday business calculations."),
            ("Data Cleaning and Preparation", "Covers identifying missing values, duplicates, and inconsistent formats, and the basic steps analysts take to prepare raw data for analysis."),
            ("Business KPI Design", "Explains how to choose key performance indicators that align with organizational goals and how to distinguish leading from lagging metrics."),
            ("Introduction to SQL for Analysts", "Introduces basic SELECT, WHERE, and JOIN statements used to query relational databases for business reporting."),
            ("Sampling Methods in Business Research", "Covers random, stratified, and convenience sampling techniques and how sample choice affects the reliability of business conclusions."),
            ("Probability Concepts for Analysts", "Introduces basic probability rules, conditional probability, and expected value as tools for reasoning about business uncertainty."),
            ("Effective Business Charts and Graphs", "Covers choosing appropriate chart types such as bar, line, and scatter plots to communicate business data clearly and avoid misleading visuals."),
            ("Introduction to Business Intelligence Platforms", "Surveys the role of BI platforms in connecting to data sources, modeling data, and delivering reports to business users."),
            ("Survey Design and Data Collection", "Explains how to write unbiased survey questions, choose response scales, and collect data suitable for later statistical analysis."),
            ("Measures of Central Tendency and Dispersion", "Covers mean, median, mode, range, variance, and standard deviation as basic tools for summarizing business datasets."),
            ("Pivot Tables and Cross-Tabulation", "Introduces summarizing and cross-tabulating spreadsheet data using pivot tables to reveal patterns across categories."),
            ("Types and Sources of Business Data", "Distinguishes structured, unstructured, internal, and external data sources and how each is typically captured and stored."),
            ("Building Simple Dashboards", "Introduces arranging charts, tables, and KPI tiles into a single-page dashboard that summarizes business performance at a glance."),
            ("Excel Formulas for Analytics", "Covers lookup functions, conditional formulas, and logical functions commonly used to analyze business data in spreadsheets."),
            ("Data Quality and Data Governance Basics", "Introduces the dimensions of data quality, such as accuracy and completeness, and basic policies organizations use to maintain them."),
            ("Correlation Analysis Basics", "Explains how the correlation coefficient measures the strength and direction of a linear relationship between two business variables."),
            ("Introduction to Simple Linear Regression", "Introduces fitting a line to two related variables to estimate how changes in one predictor relate to a business outcome."),
            ("Business Report Writing with Data", "Covers structuring a data-driven business report, including an executive summary, supporting evidence, and clear recommendations."),
        ],
        "C2": [
            ("Multiple Linear Regression for Business", "Extends simple regression to multiple predictors and covers interpreting coefficients, R-squared, and multicollinearity in business models."),
            ("Hypothesis Testing in Business Contexts", "Covers formulating null and alternative hypotheses, p-values, and significance levels to test business claims with sample data."),
            ("Confidence Intervals and Estimation", "Explains how to construct and interpret confidence intervals for means and proportions when estimating business population parameters."),
            ("Time Series Components and Decomposition", "Introduces trend, seasonality, cyclical, and irregular components and how decomposing a time series aids business forecasting."),
            ("Moving Average and Exponential Smoothing Forecasts", "Covers simple and weighted moving averages and exponential smoothing as basic techniques for short-term business forecasting."),
            ("Introduction to Data Warehousing", "Explains how data warehouses consolidate data from multiple operational systems into a structure optimized for business reporting."),
            ("Relational Database Design for Analytics", "Covers normalization, primary and foreign keys, and schema design principles for databases that support analytical queries."),
            ("Data Mining Fundamentals", "Introduces the CRISP-DM process and common data mining tasks such as classification, clustering, and association discovery."),
            ("Cluster Analysis for Segmentation", "Explains k-means and hierarchical clustering as methods for grouping customers or products into segments with similar characteristics."),
            ("Association Rule Mining (Market Basket Analysis)", "Introduces support, confidence, and lift metrics used to discover which products are frequently purchased together."),
            ("Introduction to A/B Testing", "Covers designing a controlled experiment with treatment and control groups to measure the causal effect of a business change."),
            ("Decision Trees for Business Decisions", "Explains how decision trees split data on predictor variables to support classification and structured business decision-making."),
            ("Analysis of Variance (ANOVA)", "Covers comparing means across three or more groups using ANOVA to determine whether observed differences are statistically significant."),
            ("Chi-Square Tests for Categorical Data", "Introduces the chi-square test of independence for examining relationships between two categorical business variables."),
            ("Introduction to Power BI / Tableau Dashboards", "Covers connecting data sources, building visualizations, and publishing interactive dashboards using leading BI visualization tools."),
            ("Business Process Mapping and Analytics", "Explains how flowcharts and process maps document business workflows and identify bottlenecks for data-driven improvement."),
            ("Retail Analytics Fundamentals", "Surveys how retailers use point-of-sale and inventory data to analyze sales trends, stock levels, and store performance."),
            ("Introduction to Big Data for Business", "Introduces the volume, velocity, and variety characteristics of big data and how they differ from traditional business datasets."),
        ],
        "UG1": [
            ("Advanced Forecasting Methods (ARIMA)", "Covers autoregressive integrated moving average models for forecasting time series with trend and autocorrelation structure."),
            ("Logistic Regression for Business Classification", "Explains how logistic regression estimates the probability of a binary business outcome, such as churn or default."),
            ("Customer Lifetime Value Modeling", "Covers estimating the total value a customer is expected to generate over their relationship with a business."),
            ("Churn Prediction Modeling", "Explains how classification models use historical behavior data to predict which customers are likely to stop using a service."),
            ("Recommendation Systems for Business", "Introduces collaborative filtering and content-based recommendation techniques used to suggest products to customers."),
            ("Pricing Analytics and Revenue Management", "Covers demand estimation and price optimization techniques used to set prices that maximize revenue or profit."),
            ("Digital and Web Analytics", "Introduces metrics such as page views, bounce rate, and conversion rate used to analyze website and app user behavior."),
            ("Social Media Analytics", "Covers measuring engagement, reach, and sentiment on social platforms to evaluate marketing campaign performance."),
            ("Text Analytics for Business", "Introduces techniques for extracting structured information, such as topics and keywords, from unstructured business text."),
            ("Sentiment Analysis Techniques", "Covers lexicon-based and machine-learning approaches to classifying text as positive, negative, or neutral for business insight."),
            ("Introduction to Data Storytelling", "Explains how to combine narrative structure, visuals, and data to communicate analytical findings persuasively to stakeholders."),
            ("Business Intelligence Architecture", "Covers how data sources, ETL pipelines, data warehouses, and reporting tools fit together in an enterprise BI system."),
            ("Data Ethics and Privacy in Analytics", "Introduces principles of consent, anonymization, and fairness that guide the responsible use of business data."),
            ("Introduction to Cloud Analytics Platforms", "Surveys how cloud-based analytics services allow organizations to store, process, and analyze data without on-premises infrastructure."),
            ("Sales Analytics and Pipeline Forecasting", "Covers analyzing sales funnel stages and conversion rates to forecast future revenue and prioritize opportunities."),
            ("Marketing Mix Modeling", "Introduces statistical methods for estimating how advertising and pricing decisions across channels affect sales."),
            ("Competitive Intelligence Analytics", "Covers systematically gathering and analyzing public data about competitors to inform business strategy."),
            ("Scenario Planning and Sensitivity Analysis", "Explains how varying key assumptions in a business model reveals how sensitive outcomes are to uncertainty."),
        ],
        "UG2": [
            ("Linear Programming Formulation", "Covers expressing business optimization problems as an objective function and linear constraints solvable by standard methods."),
            ("Integer and Mixed-Integer Programming", "Extends linear programming to problems requiring whole-number decisions, such as scheduling or facility selection."),
            ("Network Optimization Models", "Introduces shortest-path, minimum-spanning-tree, and maximum-flow problems as models for logistics and distribution networks."),
            ("Queuing Theory and Waiting-Line Models", "Covers using arrival and service rate distributions to analyze wait times and staffing needs in service operations."),
            ("Monte Carlo Simulation", "Explains how repeated random sampling estimates the range of outcomes for business decisions under uncertainty."),
            ("Discrete-Event Simulation", "Introduces modeling a business process as a sequence of discrete events to study system behavior, such as queues and throughput."),
            ("Inventory Management Analytics", "Covers economic order quantity, safety stock, and reorder point calculations used to balance holding and stockout costs."),
            ("Demand Planning and Forecasting", "Explains how historical sales data and market signals are combined to forecast future product demand."),
            ("Supply Chain Network Design", "Covers analytical methods for deciding the number and location of facilities in a distribution network."),
            ("Transportation and Logistics Optimization", "Introduces the transportation problem and vehicle routing models used to minimize shipping cost and delivery time."),
            ("Revenue Management Systems", "Covers dynamic pricing and capacity allocation techniques used by airlines, hotels, and similar industries to maximize revenue."),
            ("Credit Risk Scoring Models", "Explains how statistical models estimate the probability that a borrower will default on a loan."),
            ("Fraud Detection Analytics", "Covers using anomaly detection and rule-based methods to flag transactions that deviate from normal patterns."),
            ("Portfolio Analytics and Risk-Return Tradeoffs", "Introduces mean-variance analysis for evaluating the expected return and risk of a portfolio of assets."),
            ("Working Capital Analytics", "Covers analyzing receivables, payables, and inventory turnover to manage a firm's short-term liquidity."),
            ("Cost-Volume-Profit Analysis", "Explains how fixed and variable costs relate to sales volume to determine a business's break-even point and profit."),
            ("Capital Budgeting Analytics", "Covers net present value, internal rate of return, and payback period methods for evaluating long-term investments."),
            ("Break-Even and Sensitivity Analysis", "Introduces analyzing how changes in cost, price, or volume assumptions shift a business's break-even point."),
        ],
        "UG3": [
            ("Workforce Planning Analytics", "Covers forecasting staffing needs and analyzing headcount data to align workforce supply with business demand."),
            ("Talent Acquisition Analytics", "Explains how recruiting funnel metrics and source-of-hire data are analyzed to improve hiring outcomes and efficiency."),
            ("Employee Attrition Modeling", "Covers using historical HR data to build models that predict which employees are at risk of leaving."),
            ("Compensation Analytics", "Introduces methods for benchmarking pay against market data and analyzing internal pay equity."),
            ("Diversity and Inclusion Analytics", "Covers measuring representation and progression metrics to track diversity and inclusion outcomes within an organization."),
            ("Six Sigma and Process Improvement Analytics", "Introduces the DMAIC framework and statistical process control tools used to reduce variation and defects in business processes."),
            ("Balanced Scorecard Design", "Explains how the balanced scorecard links financial, customer, process, and learning metrics to organizational strategy."),
            ("Business Process Mining", "Covers extracting event logs from information systems to reconstruct and analyze how business processes actually execute."),
            ("Healthcare Analytics Applications", "Surveys how hospitals and payers use analytics for patient outcomes, readmission risk, and operational efficiency."),
            ("Sports Analytics Applications", "Covers how statistical analysis of performance and game data informs recruiting, strategy, and fan engagement decisions."),
            ("Real Estate Analytics", "Introduces using comparable sales, hedonic pricing models, and market data to value and analyze property investments."),
            ("Energy and Utilities Analytics", "Covers analyzing consumption data, demand forecasting, and grid performance metrics in the energy sector."),
            ("Nonprofit and Public Sector Analytics", "Surveys how outcome measurement and program evaluation methods are applied to nonprofit and government decision-making."),
            ("Analytics Center of Excellence Design", "Explains how organizations structure a centralized team and standards to scale analytics capability across departments."),
            ("Data Governance Frameworks", "Covers policies, roles, and stewardship processes that ensure data across an organization remains accurate and well controlled."),
            ("Master Data Management", "Introduces creating a single, consistent record of core business entities such as customers and products across systems."),
            ("Analytics Maturity Models", "Covers frameworks for assessing an organization's progression from basic reporting toward predictive and prescriptive analytics."),
            ("Vendor and Tool Selection for Analytics", "Explains criteria such as scalability, cost, and integration used to evaluate analytics software and platform vendors."),
        ],
        "UG4": [
            ("Model Evaluation and Validation Techniques", "Covers metrics such as accuracy, precision, recall, and AUC used to assess how well a predictive business model performs."),
            ("Cross-Validation and Overfitting in Business Models", "Explains how k-fold cross-validation helps detect and mitigate overfitting when building predictive models on business data."),
            ("Feature Engineering for Business Data", "Covers creating, transforming, and selecting input variables to improve the performance of business predictive models."),
            ("Explainable AI for Business Decisions", "Introduces techniques such as feature importance and SHAP values that help explain the predictions of complex models to stakeholders."),
            ("Ensemble Methods for Business Prediction", "Covers bagging, boosting, and random forest techniques that combine multiple models to improve prediction accuracy."),
            ("Naive Bayes Classification for Business", "Explains how the Naive Bayes algorithm uses conditional probability to classify business records, such as spam or sentiment."),
            ("Support Vector Machines for Business Applications", "Introduces how support vector machines find a separating boundary between classes for business classification problems."),
            ("Neural Networks for Business Forecasting", "Covers the basic structure of feedforward neural networks and their use in modeling nonlinear business relationships."),
            ("Natural Language Processing for Business Documents", "Introduces tokenization, part-of-speech tagging, and topic modeling applied to contracts, reviews, and business text."),
            ("Anomaly Detection in Business Data", "Covers statistical and machine-learning methods for identifying unusual transactions or metrics that deviate from expected patterns."),
            ("Real-Time Analytics and Streaming Data", "Explains how analytics systems process continuously arriving data to support near-instant business decisions."),
            ("Analytics for Digital Transformation", "Covers how organizations use data and analytics to redesign products, processes, and customer experiences digitally."),
            ("Design of Experiments for Business", "Introduces factorial designs and randomization principles used to test multiple business variables simultaneously."),
            ("Multi-Criteria Decision Analysis", "Covers methods such as weighted scoring and the analytic hierarchy process for choosing among alternatives with competing objectives."),
            ("Game Theory for Business Strategy", "Introduces basic concepts such as the Nash equilibrium and payoff matrices for analyzing competitive business decisions."),
            ("Behavioral Economics in Analytics", "Covers cognitive biases such as anchoring and loss aversion and how they affect the interpretation of business data."),
            ("Analytics Storytelling and Executive Communication", "Explains techniques for tailoring analytical findings and visualizations to executive audiences and decision contexts."),
            ("Regulatory Compliance in Data Analytics (GDPR/CCPA)", "Introduces core requirements of data protection regulations such as GDPR and CCPA that shape how analytics teams handle personal data."),
        ],
        "M1": [
            ("Bayesian Methods for Business Analytics", "Covers using prior distributions and observed data to update beliefs about business parameters through Bayesian inference."),
            ("Advanced Time Series Forecasting (SARIMA, State-Space Models)", "Extends time series analysis to seasonal ARIMA and state-space formulations for more complex business forecasting problems."),
            ("Causal Inference in Business Analytics", "Introduces methods such as instrumental variables and difference-in-differences for estimating causal effects from observational business data."),
            ("Experimental Design for Causal Impact", "Covers designing randomized controlled experiments and quasi-experiments to rigorously measure the causal impact of business interventions."),
            ("Structural Equation Modeling in Business Research", "Introduces modeling relationships among observed and latent variables to test theoretical models of business behavior."),
            ("Advanced Optimization Under Uncertainty", "Covers stochastic programming and robust optimization techniques for business decisions made under uncertain parameters."),
            ("Stochastic Simulation Modeling", "Extends simulation methods to systems with random inputs, enabling risk analysis of complex business processes."),
            ("Multivariate Statistical Analysis", "Introduces techniques such as principal component analysis and factor analysis for analyzing many correlated business variables together."),
            ("Panel Data Analysis for Business", "Covers fixed-effects and random-effects models for analyzing data that tracks the same business units over multiple time periods."),
            ("Survival Analysis in Business Contexts", "Introduces hazard functions and the Cox proportional hazards model for analyzing time-to-event outcomes such as customer churn."),
            ("Advanced Machine Learning Pipelines for Analytics", "Covers building end-to-end pipelines that automate data preprocessing, model training, and evaluation for business applications."),
            ("MLOps for Business Analytics", "Introduces practices for versioning, deploying, and monitoring predictive models in production business environments."),
            ("Analytics Strategy for Mergers and Acquisitions", "Covers how data and analytics are used to conduct due diligence and evaluate synergies during mergers and acquisitions."),
            ("Enterprise Risk Analytics", "Introduces frameworks for quantifying and aggregating operational, financial, and strategic risks across an organization."),
            ("Advanced Data Visualization Design Principles", "Covers perceptual and cognitive principles that guide the design of clear, accurate, and persuasive advanced data visualizations."),
            ("Analytics Leadership and Organizational Change", "Explains how analytics leaders drive adoption of data-driven decision-making and manage organizational change."),
            ("Research Methods for Business Analytics", "Introduces the design of rigorous applied research studies, including validity, reliability, and methodology selection."),
            ("Advanced Capstone: Predictive Model Deployment", "A capstone project requiring students to build, validate, and deploy a predictive analytics model addressing a real business problem."),
        ],
    },
    "Web Development": {
        "C1": [
            ("Semantic HTML5 Structure", "Covers using elements such as header, nav, main, and article to give web pages meaningful structure beyond generic divs."),
            ("CSS Box Model Fundamentals", "Explains how content, padding, border, and margin combine to determine the size and spacing of elements on a web page."),
            ("CSS Flexbox Layout", "Introduces the flexible box layout model for arranging elements in a single row or column with control over alignment and spacing."),
            ("CSS Grid Layout", "Covers defining two-dimensional row and column layouts using CSS Grid for more complex page arrangements."),
            ("Introduction to Web Accessibility (WCAG)", "Introduces the Web Content Accessibility Guidelines and basic practices, such as alt text and color contrast, for accessible pages."),
            ("Browser Developer Tools Basics", "Covers using browser developer tools to inspect elements, view the DOM, and debug CSS and JavaScript in real time."),
            ("Introduction to Version Control with Git", "Introduces basic Git commands such as commit, add, and status for tracking changes to web project files."),
            ("Basic JavaScript Data Types and Control Flow", "Covers JavaScript's primitive data types, variables, and control structures such as if statements and loops."),
            ("Introduction to Web Forms and Validation", "Covers building HTML forms with input types and using basic client-side validation to check user-entered data."),
            ("CSS Selectors and Specificity", "Explains how CSS selectors target elements and how specificity rules determine which conflicting styles apply."),
            ("Introduction to Web Fonts and Typography", "Covers loading custom web fonts and applying typographic properties such as line height and font weight for readability."),
            ("Introduction to Responsive Images", "Introduces techniques such as the srcset attribute for serving appropriately sized images across different screen widths."),
            ("Introduction to Web Hosting Concepts", "Explains how domain names, DNS, and web servers work together to make a website reachable on the internet."),
            ("Basic HTTP Requests and Responses", "Covers the structure of HTTP requests and responses, including methods, status codes, and headers."),
            ("Introduction to JSON Data Format", "Introduces the JSON data format and how it is used to structure and exchange data between web clients and servers."),
            ("Introduction to Command Line for Developers", "Covers basic command-line navigation and file operations that developers use alongside a code editor."),
            ("Introduction to Code Editors and Extensions", "Introduces configuring a code editor with extensions for syntax highlighting, linting, and productivity in web development."),
            ("Introduction to Web Page Structure and SEO Basics", "Covers how page structure, titles, and meta tags influence how search engines index and rank a web page."),
        ],
        "C2": [
            ("JavaScript Functions and Scope", "Covers declaring functions, understanding parameters and return values, and how variable scope affects function behavior."),
            ("JavaScript Array and Object Methods", "Introduces built-in methods such as map, filter, and reduce for transforming arrays and manipulating objects."),
            ("Asynchronous JavaScript (Promises and Async/Await)", "Covers how promises and the async/await syntax manage asynchronous operations such as network requests without blocking execution."),
            ("CSS Animations and Transitions", "Introduces CSS transition and keyframe animation properties for adding motion to user interface elements."),
            ("CSS Preprocessors (Sass/LESS)", "Covers how preprocessors add variables, nesting, and mixins to CSS before compiling it to standard stylesheets."),
            ("Introduction to TypeScript", "Introduces static typing on top of JavaScript, including type annotations, interfaces, and compile-time error checking."),
            ("Git Branching and Merging Workflows", "Covers creating branches, resolving merge conflicts, and common workflows such as feature branching for team collaboration."),
            ("Introduction to npm and Package Management", "Introduces installing, versioning, and managing third-party JavaScript packages using npm and package.json."),
            ("Introduction to Build Tools (Webpack/Vite)", "Covers how module bundlers transform and combine JavaScript, CSS, and assets into optimized files for the browser."),
            ("Web Storage APIs (LocalStorage, SessionStorage, Cookies)", "Explains how browsers store client-side data using localStorage, sessionStorage, and cookies, and their differing lifetimes and scope."),
            ("Introduction to Fetch API and AJAX", "Covers using the Fetch API to make asynchronous HTTP requests from JavaScript without reloading the page."),
            ("Form Handling and Client-Side Validation", "Extends form basics to cover the Constraint Validation API and custom JavaScript validation logic."),
            ("Introduction to CSS Frameworks (Bootstrap/Tailwind)", "Introduces utility-first and component-based CSS frameworks that speed up building consistent user interfaces."),
            ("Mobile-First Design Principles", "Covers designing layouts starting from small screens and progressively enhancing them for larger viewports using media queries."),
            ("Cross-Browser Compatibility Testing", "Introduces techniques and tools for verifying that a website renders and functions consistently across different browsers."),
            ("Introduction to Web Components", "Covers custom elements, shadow DOM, and templates as browser-native building blocks for reusable UI components."),
            ("Introduction to Single Page Applications", "Explains how single-page applications load once and dynamically update content without full page reloads."),
            ("Debugging JavaScript Applications", "Covers using breakpoints, the call stack, and console tools to locate and fix errors in JavaScript code."),
        ],
        "UG1": [
            ("React Component Lifecycle and Hooks", "Covers how React components mount, update, and unmount, and how hooks such as useState and useEffect manage behavior."),
            ("Vue.js Reactivity and Composition API", "Introduces Vue's reactive data system and the Composition API for organizing component logic."),
            ("Client-Side Routing in SPAs", "Explains how client-side routers map URL paths to components without triggering full-page server requests."),
            ("Component-Based Architecture Patterns", "Covers principles for decomposing a user interface into reusable, composable components with clear responsibilities."),
            ("Introduction to Redux/State Containers", "Introduces centralized state management patterns, including actions, reducers, and a single store, for complex applications."),
            ("Server-Side Rendering Concepts", "Explains how rendering HTML on the server before sending it to the browser improves initial load time and SEO."),
            ("Static Site Generation Concepts", "Covers pre-building HTML pages at build time rather than on each request, for fast and cacheable content delivery."),
            ("Introduction to Node.js Runtime", "Introduces Node.js as a JavaScript runtime for building server-side applications outside the browser."),
            ("Express.js Middleware and Routing", "Covers defining routes and middleware functions in Express to handle incoming HTTP requests on a Node.js server."),
            ("Building RESTful APIs with Express", "Extends Express fundamentals to building CRUD endpoints that follow REST conventions for a backend API."),
            ("Introduction to GraphQL Queries and Mutations", "Introduces the GraphQL query language for requesting exactly the data a client needs, and mutations for making changes."),
            ("API Documentation with OpenAPI/Swagger", "Covers describing REST API endpoints, parameters, and responses using the OpenAPI specification for consumers to reference."),
            ("Introduction to SQL Databases for Web Apps", "Covers connecting a web application to a relational database and performing basic queries to store and retrieve data."),
            ("Introduction to NoSQL Databases (MongoDB)", "Introduces document-oriented databases such as MongoDB and how they differ from relational schemas in structuring web app data."),
            ("Object-Relational Mapping (ORMs)", "Explains how ORMs let developers interact with a database using objects and methods instead of writing raw SQL."),
            ("Session Management in Web Apps", "Covers how servers track logged-in users across requests using sessions, session stores, and cookies."),
            ("Introduction to JWT-Based Authentication", "Introduces JSON Web Tokens as a stateless mechanism for verifying user identity across API requests."),
            ("Introduction to OAuth 2.0 Concepts", "Covers the roles and authorization flows in OAuth 2.0 that let applications access resources on a user's behalf."),
        ],
        "UG2": [
            ("Cross-Site Scripting (XSS) Prevention", "Covers how attackers inject malicious scripts into web pages and the input sanitization and output encoding techniques that prevent it."),
            ("Cross-Site Request Forgery (CSRF) Protection", "Explains how CSRF tricks a logged-in user's browser into making unwanted requests, and how anti-CSRF tokens prevent it."),
            ("SQL Injection Prevention", "Covers how unsanitized input can manipulate database queries and how parameterized queries prevent SQL injection attacks."),
            ("Content Security Policy Implementation", "Introduces configuring the Content-Security-Policy header to restrict which scripts and resources a browser will execute."),
            ("HTTPS and TLS for Web Applications", "Explains how TLS encrypts traffic between browser and server and why HTTPS is essential for protecting web application data."),
            ("Rate Limiting and API Throttling", "Covers techniques for limiting how many requests a client can make in a given period to protect a web API from abuse."),
            ("Web Application Firewalls", "Introduces how a WAF inspects HTTP traffic to detect and block common web application attacks before they reach the server."),
            ("Secure Password Storage and Hashing", "Covers using salted hashing algorithms such as bcrypt to store passwords so plaintext credentials are never persisted."),
            ("CORS and Same-Origin Policy", "Explains the browser's same-origin policy and how Cross-Origin Resource Sharing headers safely relax it for legitimate requests."),
            ("Input Validation and Sanitization", "Covers validating and sanitizing user input on both client and server to prevent malformed or malicious data from being processed."),
            ("Dependency Vulnerability Management", "Introduces tools and practices for identifying and patching known vulnerabilities in third-party web application dependencies."),
            ("Security Headers for Web Applications", "Covers HTTP headers such as X-Frame-Options and Strict-Transport-Security that harden a web application against common attacks."),
            ("Introduction to Penetration Testing for Web Apps", "Introduces the basic process of systematically probing a web application for security weaknesses under authorization."),
            ("Secure Session and Cookie Configuration", "Covers setting cookie attributes such as HttpOnly, Secure, and SameSite to reduce session hijacking risks."),
            ("API Key and Secrets Management", "Explains practices for storing and rotating API keys and credentials without embedding them directly in source code."),
            ("Web Application Threat Modeling", "Introduces systematically identifying potential threats and attack surfaces during the design of a web application."),
            ("Secure File Upload Handling", "Covers validating file types, sizes, and content to prevent malicious file uploads from compromising a web server."),
            ("Introduction to Web Application Firewalling Tools", "Surveys common WAF products and how they are configured with rule sets to filter malicious web traffic."),
        ],
        "UG3": [
            ("Progressive Web App Fundamentals", "Introduces the core technologies, including service workers and manifests, that let web apps behave like installable native apps."),
            ("Service Workers and Offline Caching", "Covers how service workers intercept network requests to cache assets and enable offline functionality for web apps."),
            ("Web App Manifest Configuration", "Explains how a manifest.json file defines a web app's icons, name, and display mode for installation on a device."),
            ("Push Notifications for the Web", "Introduces the Push API and service workers as the mechanism that delivers notifications to users from a web application."),
            ("Lazy Loading and Code Splitting", "Covers deferring the loading of JavaScript modules and images until needed to reduce initial page load time."),
            ("Critical Rendering Path Optimization", "Explains the sequence of steps browsers take to render a page and techniques for shortening that path for faster display."),
            ("Image and Asset Optimization", "Covers compressing images, choosing efficient formats, and minifying assets to reduce page weight."),
            ("Content Delivery Networks (CDNs)", "Introduces how CDNs cache and serve web content from geographically distributed servers to reduce latency."),
            ("Browser Caching Strategies", "Covers HTTP cache headers such as Cache-Control and ETag that control how browsers store and reuse web resources."),
            ("Web Vitals and Performance Metrics", "Introduces Core Web Vitals metrics such as Largest Contentful Paint and Cumulative Layout Shift for measuring user experience."),
            ("Accessibility Auditing Tools", "Covers using automated and manual auditing tools to identify accessibility issues in a web application."),
            ("ARIA Roles and Screen Reader Support", "Introduces ARIA attributes that provide semantic information to assistive technologies when native HTML is insufficient."),
            ("Keyboard Navigation and Focus Management", "Covers designing interactive components so all functionality is reachable and operable using only a keyboard."),
            ("Internationalization and Localization for Web Apps", "Introduces techniques for adapting a web application's text, formats, and layout for different languages and regions."),
            ("Responsive Typography Systems", "Covers scalable type systems using relative units and fluid sizing to maintain readability across screen sizes."),
            ("Design Systems and Component Libraries", "Explains how a shared design system and component library promote visual and functional consistency across a product."),
            ("Micro-Frontend Architecture", "Introduces splitting a large frontend application into independently deployable pieces owned by separate teams."),
            ("Web Animation Performance", "Covers which CSS properties can be animated efficiently by the browser's compositor without causing layout thrashing."),
        ],
        "UG4": [
            ("Unit Testing JavaScript Applications", "Covers writing isolated tests for individual functions and components using frameworks such as Jest."),
            ("Integration Testing for Web APIs", "Introduces testing how multiple components or services of a web API work together correctly."),
            ("End-to-End Testing with Cypress/Playwright", "Covers automating browser interactions to test complete user flows through a web application."),
            ("Test-Driven Development for Web Apps", "Introduces writing failing tests before implementation code as a discipline for driving web application design."),
            ("Continuous Integration for Web Projects", "Covers configuring automated pipelines that build and test a web project on every code change."),
            ("Continuous Deployment Pipelines", "Extends continuous integration to automatically deploy passing builds of a web application to production or staging environments."),
            ("Containerizing Web Applications with Docker", "Introduces packaging a web application and its dependencies into a Docker container for consistent deployment."),
            ("Serverless Functions for Web Backends", "Covers writing backend logic as individual functions that run on demand without managing a persistent server."),
            ("Static Site Hosting and Edge Deployment", "Introduces deploying static web assets to globally distributed edge locations for fast delivery."),
            ("Monitoring and Logging for Web Applications", "Covers collecting application logs and metrics to observe the health and behavior of a running web application."),
            ("Error Tracking and Observability", "Introduces tools that automatically capture and aggregate runtime errors from a deployed web application."),
            ("GraphQL Schema Design", "Covers designing types, queries, and mutations in a GraphQL schema to model an application's data effectively."),
            ("Real-Time Web Apps with WebSockets", "Explains how WebSockets maintain a persistent connection for bidirectional real-time communication between client and server."),
            ("Web Real-Time Communication (WebRTC)", "Introduces the WebRTC APIs that enable direct peer-to-peer audio, video, and data exchange between browsers."),
            ("API Versioning Strategies", "Covers approaches such as URL and header versioning for evolving a web API without breaking existing clients."),
            ("Rate-Limited and Paginated API Design", "Introduces designing APIs that paginate large result sets and limit request rates to protect backend resources."),
            ("Web App Scalability Patterns", "Covers architectural patterns such as load balancing and horizontal scaling for handling growing web traffic."),
            ("Feature Flags and A/B Testing for Web Apps", "Introduces using feature flags to toggle functionality and run controlled experiments on live web applications."),
        ],
        "M1": [
            ("Advanced React Performance Optimization", "Covers techniques such as memoization, virtualization, and profiling to optimize rendering performance in large React applications."),
            ("Server Components and Streaming Rendering", "Introduces server components and streaming techniques that render and send HTML incrementally for faster perceived load times."),
            ("Advanced State Management Patterns (Signals/Atoms)", "Covers fine-grained reactive state primitives, such as signals and atoms, as alternatives to traditional centralized state stores."),
            ("Micro-Frontend Orchestration at Scale", "Extends micro-frontend concepts to shell applications, shared dependencies, and versioning strategies at enterprise scale."),
            ("Advanced GraphQL Federation", "Introduces composing multiple GraphQL services into a single unified graph using schema federation techniques."),
            ("Event-Driven Web Architecture", "Covers designing web systems where services communicate through asynchronous events rather than direct synchronous calls."),
            ("Web Application Observability and Distributed Tracing", "Introduces distributed tracing techniques for following a request across multiple services in a web application's backend."),
            ("Advanced Authentication (Passkeys, WebAuthn)", "Covers passwordless authentication standards such as WebAuthn and passkeys that use public-key cryptography for sign-in."),
            ("Zero-Downtime Deployment Strategies", "Introduces blue-green and rolling deployment techniques that update a web application without interrupting service."),
            ("Advanced Caching Architectures (Edge/CDN Layers)", "Covers layered caching strategies spanning browser, CDN, and application layers to reduce latency at scale."),
            ("Web Performance Budgets and Monitoring", "Introduces setting measurable performance budgets and continuously monitoring metrics to prevent regressions over time."),
            ("Advanced Accessibility Engineering", "Covers building and testing complex accessible components, such as custom widgets, that meet advanced WCAG success criteria."),
            ("Headless CMS Architecture", "Introduces content management systems that expose content via APIs, decoupled from how it is ultimately rendered."),
            ("API Gateway Design for Web Platforms", "Covers how an API gateway centralizes routing, authentication, and rate limiting for a web platform's backend services."),
            ("Advanced Security Auditing for Web Applications", "Extends security testing to comprehensive audits covering authentication, authorization, and data handling across a full application."),
            ("Scalable Database Architecture for Web Apps", "Covers sharding, replication, and read/write splitting strategies for databases supporting high-traffic web applications."),
            ("Advanced DevOps for Web Engineering Teams", "Introduces practices such as infrastructure as code and automated rollback strategies for mature web engineering organizations."),
            ("Advanced Capstone: Production-Grade Web Platform", "A capstone project requiring students to design, build, and deploy a scalable, secure, production-grade web platform."),
        ],
    },
    "Cybersecurity": {
        "C1": [
            ("CIA Triad and Security Principles", "Introduces confidentiality, integrity, and availability as the foundational goals that guide cybersecurity decisions."),
            ("Introduction to Firewalls", "Explains how firewalls filter network traffic based on rules to permit or block connections between networks."),
            ("Introduction to Password Security", "Covers the principles of strong password creation, password managers, and why password reuse creates risk."),
            ("Social Engineering Awareness", "Introduces common social engineering tactics, such as pretexting and baiting, that manipulate people into revealing information."),
            ("Phishing Recognition and Prevention", "Covers how to identify suspicious emails and links designed to trick users into revealing credentials or installing malware."),
            ("Introduction to Malware Types", "Surveys categories of malicious software, including viruses, worms, trojans, and spyware, and how each typically spreads."),
            ("Introduction to Security Policies", "Introduces the role of written security policies in defining acceptable use, access rules, and organizational expectations."),
            ("Physical Security Fundamentals", "Covers controls such as locks, badges, and surveillance that protect physical access to facilities and equipment."),
            ("Introduction to Access Control Models", "Introduces discretionary, mandatory, and role-based access control as approaches for granting system permissions."),
            ("Introduction to Symmetric Encryption", "Explains how symmetric encryption uses a single shared key to both encrypt and decrypt data."),
            ("Introduction to Asymmetric Encryption", "Introduces public and private key pairs and how asymmetric encryption enables secure communication without sharing a secret key."),
            ("Introduction to VPNs", "Covers how virtual private networks create encrypted tunnels to protect data transmitted over untrusted networks."),
            ("Introduction to Wireless Network Security", "Introduces basic Wi-Fi security concepts, including encryption protocols and the risks of open wireless networks."),
            ("Introduction to Security Awareness Training", "Covers the purpose and common components of organizational programs that teach employees to recognize security threats."),
            ("Introduction to Backup and Recovery", "Explains why regular backups are essential and introduces basic backup strategies for recovering from data loss."),
            ("Introduction to Security Frameworks (NIST Overview)", "Introduces the structure and purpose of the NIST Cybersecurity Framework's core functions for managing risk."),
            ("Introduction to Data Classification", "Covers categorizing data by sensitivity, such as public, internal, and confidential, to apply appropriate protections."),
            ("Introduction to Security Incident Reporting", "Explains why and how employees should report suspected security incidents through defined organizational channels."),
        ],
        "C2": [
            ("Intrusion Detection and Prevention Systems", "Covers how IDS and IPS technologies monitor network traffic for malicious activity and respond to detected threats."),
            ("Network Segmentation and DMZ Design", "Introduces dividing a network into isolated zones, including a demilitarized zone, to limit the spread of a breach."),
            ("Hashing Algorithms and Data Integrity", "Explains how cryptographic hash functions produce fixed-size fingerprints used to verify that data has not been altered."),
            ("Public Key Infrastructure (PKI)", "Covers the components of PKI, including certificate authorities and digital certificates, that establish trust in public key cryptography."),
            ("Digital Signatures and Certificates", "Introduces how digital signatures use asymmetric cryptography to verify the authenticity and integrity of a message."),
            ("Endpoint Protection and Antivirus Technologies", "Surveys signature-based and behavior-based detection methods used by antivirus and endpoint protection software."),
            ("Security Information and Event Management (SIEM) Basics", "Introduces how SIEM systems aggregate and correlate log data from across an organization to detect security events."),
            ("Log Analysis for Security Monitoring", "Covers reading and interpreting system, application, and network logs to identify signs of suspicious activity."),
            ("Introduction to Linux Security Hardening", "Introduces basic hardening practices for Linux systems, such as disabling unused services and managing file permissions."),
            ("Introduction to Windows Security Hardening", "Covers basic hardening practices for Windows systems, including group policy settings and disabling unnecessary features."),
            ("Patch Management Fundamentals", "Explains the process of tracking, testing, and deploying software updates to remediate known vulnerabilities."),
            ("Secure Network Protocols (SSH, TLS)", "Introduces how protocols such as SSH and TLS provide encrypted, authenticated communication over networks."),
            ("Introduction to Ethical Hacking Concepts", "Covers the principles that distinguish authorized ethical hacking from malicious hacking, including scope and consent."),
            ("Vulnerability Scanning Fundamentals", "Introduces automated tools that scan systems and networks to identify known security weaknesses."),
            ("Introduction to the OWASP Top 10", "Surveys the OWASP Top 10 list of the most critical web application security risks."),
            ("Wireless Security Protocols (WPA2/WPA3)", "Covers the encryption and authentication mechanisms used in WPA2 and WPA3 to secure Wi-Fi networks."),
            ("Email Security and Anti-Spoofing (SPF/DKIM/DMARC)", "Introduces SPF, DKIM, and DMARC as email authentication mechanisms that help prevent domain spoofing."),
            ("Security Baseline Configuration", "Covers establishing a documented, secure default configuration standard for systems before deployment."),
        ],
        "UG1": [
            ("Penetration Testing Methodology", "Introduces the standard phases of a penetration test, including reconnaissance, scanning, exploitation, and reporting."),
            ("Reconnaissance and Footprinting Techniques", "Covers gathering publicly available information about a target organization to inform a security assessment."),
            ("Network Scanning and Enumeration", "Introduces using tools to identify live hosts, open ports, and running services on a target network."),
            ("Exploitation Techniques and Frameworks", "Covers how exploitation frameworks such as Metasploit are used in authorized testing to validate discovered vulnerabilities."),
            ("Post-Exploitation and Privilege Escalation", "Introduces techniques attackers use after initial access to escalate privileges and maintain persistence on a system."),
            ("Web Application Penetration Testing", "Covers systematically testing a web application for vulnerabilities such as injection flaws and broken authentication."),
            ("Wireless Network Penetration Testing", "Introduces techniques for assessing the security of wireless networks, including encryption and authentication weaknesses."),
            ("Social Engineering Penetration Testing", "Covers conducting authorized simulated phishing and pretexting exercises to test an organization's human security controls."),
            ("Red Team vs Blue Team Concepts", "Explains the distinct roles of offensive red teams and defensive blue teams in testing organizational security."),
            ("Purple Teaming Fundamentals", "Introduces collaborative exercises where red and blue teams work together to improve detection and response capability."),
            ("Capture the Flag (CTF) Methodology", "Covers the structure of cybersecurity CTF competitions and common challenge categories used to build practical skills."),
            ("Bug Bounty Fundamentals", "Introduces how bug bounty programs incentivize researchers to responsibly disclose vulnerabilities to organizations."),
            ("Secure Code Review Practices", "Covers manually reviewing source code to identify security flaws such as improper input handling or insecure logic."),
            ("Static Application Security Testing (SAST)", "Introduces tools that analyze source code without executing it to detect potential security vulnerabilities."),
            ("Dynamic Application Security Testing (DAST)", "Covers tools that test a running application by sending crafted inputs to discover exploitable vulnerabilities."),
            ("API Security Testing", "Introduces techniques for testing APIs for issues such as broken authentication, excessive data exposure, and injection flaws."),
            ("Mobile Application Security Testing", "Covers techniques for assessing the security of mobile apps, including insecure data storage and weak authentication."),
            ("IoT Device Security Fundamentals", "Introduces common security weaknesses in Internet of Things devices, such as default credentials and unencrypted communication."),
        ],
        "UG2": [
            ("Advanced Malware Analysis Techniques", "Covers deeper analysis of malware behavior and code, building on basic classification to understand attack capability."),
            ("Static vs Dynamic Malware Analysis", "Explains the difference between examining malware code without execution and observing its behavior in a controlled environment."),
            ("Reverse Engineering Fundamentals", "Introduces disassembly and decompilation techniques used to understand the internal workings of compiled software."),
            ("Ransomware Analysis and Defense", "Covers how ransomware encrypts victim data for extortion and the defensive and recovery strategies organizations use against it."),
            ("Botnet Detection and Mitigation", "Introduces how networks of compromised devices are controlled remotely and techniques used to detect and disrupt them."),
            ("Rootkit Detection Techniques", "Covers how rootkits hide their presence on a system and the methods used to detect these stealthy compromises."),
            ("Sandboxing and Malware Detonation", "Introduces running suspicious files in an isolated sandbox environment to safely observe their behavior."),
            ("Threat Hunting Fundamentals", "Covers proactively searching networks and systems for signs of compromise that automated tools may have missed."),
            ("Indicators of Compromise (IOCs)", "Introduces artifacts such as file hashes and IP addresses used to identify and share evidence of a security breach."),
            ("MITRE ATT&CK Framework", "Introduces the ATT&CK matrix of adversary tactics and techniques used to describe and analyze real-world attack behavior."),
            ("Cyber Kill Chain Analysis", "Covers the stages of a typical cyberattack, from reconnaissance to actions on objectives, as a model for defense."),
            ("Advanced Persistent Threats (APT) Case Studies", "Examines documented, long-running, sophisticated intrusion campaigns to understand advanced attacker tradecraft."),
            ("Threat Intelligence Platforms", "Introduces tools that aggregate and analyze threat data feeds to help organizations anticipate and respond to attacks."),
            ("Dark Web Monitoring Fundamentals", "Covers how organizations monitor dark web forums and marketplaces for leaked credentials or planned attacks."),
            ("Security Orchestration, Automation and Response (SOAR)", "Introduces platforms that automate repetitive security response tasks by orchestrating tools and playbooks."),
            ("Insider Threat Detection", "Covers behavioral indicators and monitoring approaches used to detect malicious or negligent actions by trusted insiders."),
            ("Supply Chain Security Risks", "Introduces how vulnerabilities introduced through third-party software or vendors can compromise an organization."),
            ("Zero-Day Vulnerability Management", "Covers how organizations detect, mitigate, and respond to previously unknown vulnerabilities without an available patch."),
        ],
        "UG3": [
            ("Zero Trust Architecture Principles", "Introduces the zero trust model of continuously verifying every user and device rather than trusting based on network location."),
            ("Multi-Factor Authentication Design", "Covers combining knowledge, possession, and inherence factors to strengthen authentication beyond passwords alone."),
            ("Single Sign-On (SSO) and Federation", "Introduces how SSO and identity federation let users authenticate once to access multiple connected systems."),
            ("Privileged Access Management", "Covers controls for securing, monitoring, and limiting accounts with elevated administrative privileges."),
            ("Identity Governance and Administration", "Introduces processes for managing user identities and access rights throughout their lifecycle in an organization."),
            ("Network Access Control Systems", "Covers technologies that enforce security policy on devices before allowing them to connect to a network."),
            ("Security Information Sharing Frameworks", "Introduces standards such as STIX and TAXII used by organizations to share threat intelligence with one another."),
            ("Container and Kubernetes Security", "Covers securing container images, runtime environments, and Kubernetes clusters against common attack vectors."),
            ("DevSecOps Practices and Pipelines", "Introduces integrating automated security testing directly into continuous integration and deployment pipelines."),
            ("Secure Software Development Lifecycle (SSDLC)", "Covers embedding security requirements and reviews at every phase of the software development process."),
            ("Cryptographic Protocol Design (TLS Handshake)", "Explains the steps of the TLS handshake that establish an encrypted, authenticated connection between client and server."),
            ("Key Management Systems", "Introduces the lifecycle of cryptographic keys, including generation, storage, rotation, and revocation."),
            ("Data Loss Prevention (DLP) Strategies", "Covers technologies and policies that detect and prevent sensitive data from leaving an organization improperly."),
            ("Database Security Fundamentals", "Introduces access controls, encryption, and auditing practices that protect databases from unauthorized access."),
            ("Secure Remote Access Architectures", "Covers designing VPN, zero trust, and remote desktop solutions that let users connect securely from outside the network."),
            ("Security Metrics and Reporting", "Introduces selecting and communicating meaningful metrics that describe an organization's security posture to leadership."),
            ("Business Continuity Planning", "Covers developing plans that keep critical business functions operating during and after a disruptive incident."),
            ("Disaster Recovery Planning for Security", "Introduces recovery time and recovery point objectives used to plan restoring systems after a security incident or disaster."),
        ],
        "UG4": [
            ("ISO 27001 Information Security Management", "Introduces the ISO 27001 standard's approach to establishing and continually improving an information security management system."),
            ("NIST Cybersecurity Framework Implementation", "Covers applying the NIST Framework's functions and tiers to assess and improve an organization's cybersecurity practices."),
            ("GDPR and Data Privacy Compliance", "Introduces the core principles of the EU's General Data Protection Regulation and their implications for security programs."),
            ("PCI DSS Compliance Fundamentals", "Covers the Payment Card Industry Data Security Standard requirements for organizations that handle cardholder data."),
            ("HIPAA Security Rule Compliance", "Introduces the HIPAA Security Rule's requirements for protecting electronic protected health information."),
            ("Risk Assessment Methodologies (FAIR, Quantitative Risk)", "Covers structured methodologies, including the FAIR model, for quantifying and prioritizing cybersecurity risk."),
            ("Third-Party and Vendor Risk Management", "Introduces processes for assessing and monitoring the security risk that vendors and partners introduce to an organization."),
            ("Security Awareness Program Design", "Covers designing an ongoing training program that measurably improves employee security behavior over time."),
            ("Security Culture and Human Factors", "Introduces how organizational culture and human psychology influence security behavior beyond technical controls."),
            ("Incident Response Playbook Development", "Covers writing structured, step-by-step playbooks that guide responders through handling specific types of incidents."),
            ("Tabletop Exercise Design for Incident Response", "Introduces designing discussion-based simulations that test an organization's incident response plan and team coordination."),
            ("Chain of Custody in Digital Evidence", "Covers the documentation and handling procedures that preserve digital evidence integrity for legal proceedings."),
            ("Memory Forensics Fundamentals", "Introduces techniques for capturing and analyzing a system's volatile memory to uncover evidence of compromise."),
            ("Network Forensics Fundamentals", "Covers capturing and analyzing network traffic to reconstruct events during a security investigation."),
            ("Mobile Device Forensics", "Introduces techniques and tools for extracting and analyzing data from smartphones during an investigation."),
            ("Cloud Forensics Fundamentals", "Covers the unique challenges of collecting and analyzing forensic evidence from cloud-hosted systems and services."),
            ("Legal and Ethical Issues in Cybersecurity", "Introduces laws and ethical considerations governing computer crime, surveillance, and authorized security testing."),
            ("Security Operations Center (SOC) Design", "Covers the structure, staffing, and workflows of a security operations center that monitors and responds to threats."),
        ],
        "M1": [
            ("Advanced Cryptographic Protocols (Zero-Knowledge Proofs)", "Introduces zero-knowledge proofs, which let one party prove a statement is true without revealing the underlying information."),
            ("Post-Quantum Cryptography Fundamentals", "Covers cryptographic algorithms designed to remain secure against attacks from future large-scale quantum computers."),
            ("Advanced Threat Modeling Frameworks (STRIDE, PASTA)", "Introduces structured threat modeling frameworks, including STRIDE and PASTA, for systematically analyzing system risk."),
            ("Advanced Malware Reverse Engineering", "Extends reverse engineering skills to analyzing obfuscated and anti-analysis techniques used by sophisticated malware."),
            ("Advanced Digital Forensics and Anti-Forensics", "Covers advanced evidence recovery techniques alongside the anti-forensic methods attackers use to evade investigation."),
            ("Cyber Threat Intelligence Analysis at Scale", "Introduces analyzing large volumes of threat data to identify patterns and attribute activity to specific threat actors."),
            ("Advanced SOC Analytics and Automation", "Covers applying analytics and automation to reduce alert fatigue and improve detection accuracy in a security operations center."),
            ("Adversarial Machine Learning in Security", "Introduces how attackers can manipulate machine learning models and the defensive techniques used to harden them."),
            ("Security Architecture for Critical Infrastructure", "Covers the unique security requirements of power, water, and other critical infrastructure systems."),
            ("Industrial Control Systems (ICS/SCADA) Security", "Introduces the architecture of ICS and SCADA systems and the specialized controls used to protect them from cyberattacks."),
            ("Advanced Cloud-Native Security Architecture", "Covers designing security controls native to cloud platforms, spanning identity, workloads, and data across services."),
            ("Advanced Identity and Access Governance", "Extends identity governance to enterprise-scale access certification, segregation of duties, and policy automation."),
            ("Cybersecurity Risk Quantification Models", "Introduces quantitative models that express cybersecurity risk in financial terms to support executive decision-making."),
            ("Advanced Incident Response Leadership", "Covers the leadership, communication, and decision-making skills required to manage a major security incident."),
            ("National and International Cybersecurity Policy", "Introduces how governments and international bodies develop policy and regulation to address cybersecurity risk."),
            ("Cyber Warfare and Nation-State Threats", "Surveys documented nation-state cyber operations and how they differ from criminal or hacktivist activity."),
            ("Security Research Methods and Responsible Disclosure", "Introduces rigorous methods for conducting original security research and responsibly disclosing discovered vulnerabilities."),
            ("Advanced Capstone: Enterprise Security Program Design", "A capstone project requiring students to design a comprehensive security program for a realistic enterprise scenario."),
        ],
    },
    "Cloud Computing": {
        "C1": [
            ("Overview of Major Cloud Providers (AWS, Azure, GCP)", "Surveys the core offerings and market position of the leading public cloud providers, AWS, Azure, and Google Cloud."),
            ("Introduction to Public, Private, and Hybrid Clouds", "Explains the differences between public, private, and hybrid cloud deployment models and when each is typically used."),
            ("Introduction to Virtual Machines", "Introduces how a hypervisor allows multiple virtual machines to run on shared physical hardware."),
            ("Introduction to Cloud Regions and Availability Zones", "Covers how cloud providers organize infrastructure into regions and availability zones for redundancy and low latency."),
            ("Introduction to Cloud Pricing Models", "Introduces on-demand, reserved, and pay-as-you-go pricing structures used by cloud providers."),
            ("Introduction to Cloud Identity Basics", "Covers basic concepts of cloud user accounts, roles, and permissions for controlling access to resources."),
            ("Introduction to Object Storage", "Introduces object storage services, such as Amazon S3, for storing unstructured data as objects with metadata."),
            ("Introduction to Block and File Storage", "Covers how block storage volumes and shared file storage differ from object storage and their typical use cases."),
            ("Introduction to Cloud Command Line Tools", "Introduces using a cloud provider's command-line interface to create and manage resources from a terminal."),
            ("Introduction to Cloud Consoles and Dashboards", "Covers navigating a cloud provider's web console to view, configure, and monitor deployed resources."),
            ("Introduction to Cloud Resource Tagging", "Introduces attaching key-value tags to cloud resources to organize them for billing, automation, and management."),
            ("Introduction to Cloud SLAs", "Covers how service level agreements define the uptime and performance guarantees a cloud provider commits to."),
            ("Introduction to Cloud Networking Basics", "Introduces basic cloud networking concepts, such as virtual networks and IP addressing, within a cloud provider."),
            ("Introduction to Cloud Load Balancers", "Covers how load balancers distribute incoming traffic across multiple cloud compute instances."),
            ("Introduction to Cloud DNS Services", "Introduces managed DNS services that route domain names to cloud resources."),
            ("Introduction to Cloud Backup Services", "Covers managed backup services that automate the scheduled protection of cloud-hosted data."),
            ("Introduction to Cloud Shared Responsibility Model", "Explains how security and operational responsibilities are divided between the cloud provider and the customer."),
            ("Introduction to Cloud Migration Concepts", "Introduces the basic considerations involved in moving applications and data from on-premises systems to the cloud."),
        ],
        "C2": [
            ("Docker Fundamentals and Image Building", "Covers writing Dockerfiles and building container images that package an application with its dependencies."),
            ("Docker Compose for Multi-Container Apps", "Introduces defining and running multi-container applications using a single Docker Compose configuration file."),
            ("Container Registries and Image Management", "Covers pushing, pulling, and versioning container images using registries such as Docker Hub or a cloud provider's registry."),
            ("Introduction to Kubernetes Architecture", "Introduces the control plane and worker node components that make up a Kubernetes cluster."),
            ("Kubernetes Pods, Deployments, and Services", "Covers the core Kubernetes objects used to run, scale, and expose containerized applications."),
            ("Kubernetes Namespaces and Resource Quotas", "Introduces using namespaces to logically partition a cluster and quotas to limit resource consumption."),
            ("Introduction to Helm Charts", "Covers using Helm to package, configure, and deploy Kubernetes applications as reusable charts."),
            ("Virtual Private Cloud (VPC) Design", "Introduces designing an isolated virtual network within a cloud provider, including subnets and route tables."),
            ("Subnetting and Cloud Network Segmentation", "Covers dividing a cloud network into subnets to isolate resources and control traffic flow."),
            ("Cloud Firewall and Security Group Configuration", "Introduces configuring security groups and network firewall rules to control inbound and outbound cloud traffic."),
            ("Content Delivery Networks in the Cloud", "Covers configuring a cloud provider's CDN to cache and serve content from edge locations closer to users."),
            ("Cloud Auto-Scaling Policies", "Introduces defining scaling policies that automatically add or remove compute instances based on demand."),
            ("Cloud Compute Instance Types and Sizing", "Covers choosing appropriate virtual machine instance types based on CPU, memory, and workload requirements."),
            ("Cloud Storage Lifecycle Management", "Introduces automated policies that transition or expire cloud storage objects based on age or access patterns."),
            ("Cloud Database Replication and Backup", "Covers configuring replication and automated backups to protect cloud-hosted databases against data loss."),
            ("Introduction to Managed Database Services", "Introduces fully managed relational and NoSQL database services that handle provisioning, patching, and backups."),
            ("Introduction to Cloud Messaging Queues", "Covers using managed message queue services to decouple components and enable asynchronous communication."),
            ("Introduction to Cloud Monitoring Tools", "Introduces a cloud provider's native monitoring service for collecting metrics and setting basic alerts."),
        ],
        "UG1": [
            ("Terraform Fundamentals for Infrastructure as Code", "Introduces declaring cloud infrastructure as code using Terraform configuration files and its plan-and-apply workflow."),
            ("CloudFormation Templates Fundamentals", "Covers defining AWS infrastructure using CloudFormation templates written in JSON or YAML."),
            ("Configuration Management with Ansible", "Introduces using Ansible playbooks to automate the configuration of cloud servers without requiring installed agents."),
            ("GitOps Principles for Cloud Deployments", "Covers using a Git repository as the single source of truth for declaratively managing cloud infrastructure and deployments."),
            ("CI/CD Pipeline Design for Cloud Applications", "Introduces designing pipelines that automatically build, test, and deploy applications to cloud environments."),
            ("Blue-Green and Canary Deployment Strategies", "Covers deployment techniques that reduce risk by gradually or conditionally shifting traffic to a new application version."),
            ("Immutable Infrastructure Principles", "Introduces replacing servers with new versions rather than modifying them in place to improve consistency and reliability."),
            ("Cloud-Native Application Design Principles", "Covers designing applications specifically to take advantage of cloud elasticity, resilience, and managed services."),
            ("Twelve-Factor App Methodology", "Introduces the twelve-factor methodology's principles for building portable, scalable software-as-a-service applications."),
            ("Microservices Architecture on the Cloud", "Covers structuring an application as a set of independently deployable services running on cloud infrastructure."),
            ("Service Mesh Fundamentals (Istio/Linkerd)", "Introduces how a service mesh manages service-to-service communication, including traffic control and observability."),
            ("API Gateway Design for Cloud Services", "Covers using an API gateway to manage routing, authentication, and throttling for cloud-hosted services."),
            ("Event-Driven Architecture in the Cloud", "Introduces designing cloud systems where components react to events published to a queue, topic, or event bus."),
            ("Cloud Function Triggers and Event Sources", "Covers configuring serverless functions to execute in response to events such as file uploads or database changes."),
            ("Cloud-Native Message Brokers (SQS, Pub/Sub)", "Introduces managed messaging services such as SQS and Pub/Sub used to pass messages reliably between cloud components."),
            ("Cloud Data Pipelines and ETL", "Covers building pipelines that extract, transform, and load data between cloud storage and processing systems."),
            ("Cloud Data Lakes and Data Warehousing", "Introduces the difference between cloud data lakes storing raw data and data warehouses optimized for structured analytics."),
            ("Cloud-Based Big Data Processing (Spark on Cloud)", "Covers running distributed data processing frameworks such as Apache Spark on managed cloud compute clusters."),
        ],
        "UG2": [
            ("Identity and Access Management Policies in the Cloud", "Covers writing fine-grained IAM policies that grant the minimum permissions needed for cloud resources and users."),
            ("Role-Based Access Control in Cloud Platforms", "Introduces assigning permissions to roles rather than individuals to simplify managing cloud access at scale."),
            ("Cloud Encryption at Rest and in Transit", "Covers how cloud providers encrypt stored data and data moving across networks to protect confidentiality."),
            ("Cloud Key Management Services", "Introduces managed services for creating, storing, and rotating the cryptographic keys used to encrypt cloud data."),
            ("Cloud Security Posture Management", "Covers tools that continuously assess cloud configurations against security best practices to detect misconfigurations."),
            ("Cloud Compliance Frameworks (SOC 2, FedRAMP)", "Introduces compliance frameworks such as SOC 2 and FedRAMP that cloud providers and customers use to demonstrate security controls."),
            ("Cloud Network Security Architecture", "Covers designing layered network security controls, including segmentation and inspection, within a cloud environment."),
            ("Web Application Firewalls in the Cloud", "Introduces configuring a managed cloud WAF service to filter malicious traffic to web applications."),
            ("DDoS Protection for Cloud Workloads", "Covers cloud-native services and techniques that detect and absorb distributed denial-of-service attacks."),
            ("Cloud Secrets Management", "Introduces managed secrets management services for securely storing and retrieving credentials used by cloud applications."),
            ("Container Security Best Practices", "Covers scanning container images for vulnerabilities and hardening runtime configurations to reduce attack surface."),
            ("Kubernetes Security Hardening", "Introduces securing a Kubernetes cluster through network policies, role-based access control, and pod security standards."),
            ("Cloud Vulnerability Scanning", "Covers using automated tools to scan cloud workloads and configurations for known security vulnerabilities."),
            ("Cloud Audit Logging and Compliance Monitoring", "Introduces services that record API calls and configuration changes across a cloud environment for auditing."),
            ("Cloud Incident Response Procedures", "Covers adapting incident response processes to the shared responsibility model and tooling of cloud environments."),
            ("Zero Trust Networking in the Cloud", "Introduces applying zero trust principles to cloud workloads by verifying every request regardless of network location."),
            ("Cloud Data Sovereignty and Residency", "Covers legal and regulatory requirements governing where cloud data must be physically stored and processed."),
            ("Cloud Governance Policy Design", "Introduces designing organizational policies that control how cloud resources are provisioned and used."),
        ],
        "UG3": [
            ("Cloud Cost Estimation and Budgeting", "Covers using pricing calculators and historical usage data to estimate and budget for cloud spending."),
            ("Reserved Instances and Savings Plans", "Introduces committing to reserved capacity or spending plans in exchange for discounted cloud compute rates."),
            ("Spot Instances and Cost Optimization Strategies", "Covers using discounted spare cloud capacity for interruption-tolerant workloads to reduce compute costs."),
            ("FinOps Principles and Practices", "Introduces the FinOps discipline of bringing engineering, finance, and business teams together to manage cloud costs."),
            ("Cloud Resource Rightsizing", "Covers analyzing utilization data to match cloud resource sizes to actual workload requirements."),
            ("Cloud Chargeback and Showback Models", "Introduces methods for attributing cloud costs back to the teams or business units that incur them."),
            ("Cloud Disaster Recovery Planning", "Covers designing recovery strategies, including backup regions and failover procedures, for cloud-hosted systems."),
            ("Backup and Restore Strategies in the Cloud", "Introduces designing backup schedules and testing restore procedures to meet recovery objectives in the cloud."),
            ("High Availability Architecture Design", "Covers distributing resources across zones and regions to keep cloud applications available despite failures."),
            ("Fault Tolerance and Redundancy Patterns", "Introduces architectural patterns, such as retries and redundant components, that let systems continue operating despite failures."),
            ("Cloud Capacity Planning", "Covers forecasting future resource needs based on growth trends to ensure adequate cloud capacity."),
            ("Cloud Performance Tuning", "Introduces identifying and resolving performance bottlenecks in cloud-hosted applications and infrastructure."),
            ("Cloud Application Log Aggregation", "Covers centralizing logs from distributed cloud services into a single searchable platform."),
            ("Distributed Tracing in Cloud Applications", "Introduces tracing a single request as it flows through multiple cloud services to diagnose latency and errors."),
            ("Cloud Alerting and Incident Notification Systems", "Covers configuring alerting rules and notification channels that inform teams when cloud metrics cross thresholds."),
            ("Site Reliability Engineering (SRE) Fundamentals", "Introduces the SRE discipline of applying software engineering practices to operate reliable, scalable cloud systems."),
            ("Service Level Objectives and Error Budgets", "Covers defining measurable service level objectives and using error budgets to balance reliability and feature velocity."),
            ("Cloud Chaos Engineering Fundamentals", "Introduces deliberately injecting failures into cloud systems to test and improve their resilience."),
        ],
        "UG4": [
            ("Multi-Region Architecture Design", "Covers designing applications that run across multiple cloud regions for lower latency and disaster resilience."),
            ("Cloud Migration Strategies (Rehost, Replatform, Refactor)", "Introduces the common migration approaches, often called the 6 R's, for moving workloads to the cloud."),
            ("Legacy Application Modernization for the Cloud", "Covers strategies for updating older applications to take advantage of cloud-native architecture and services."),
            ("Hybrid Cloud Connectivity (VPN, Direct Connect)", "Introduces establishing secure, reliable connections between on-premises data centers and a cloud provider's network."),
            ("Cloud Interconnect and Peering", "Covers configuring dedicated network connections and peering between cloud networks or cloud and on-premises systems."),
            ("Cloud Data Migration Techniques", "Introduces tools and strategies for transferring large volumes of data into the cloud with minimal downtime."),
            ("Cloud Vendor Lock-In Mitigation", "Covers architectural and contractual strategies that reduce dependency on a single cloud provider's proprietary services."),
            ("Cloud-Native Storage Solutions (Distributed File Systems)", "Introduces distributed file and storage systems designed to scale across many cloud nodes."),
            ("Serverless Application Design Patterns", "Covers common patterns for structuring applications built entirely from serverless functions and managed services."),
            ("Event Sourcing and CQRS in Cloud Systems", "Introduces the event sourcing and command query responsibility segregation patterns for cloud application design."),
            ("Cloud API Design and Versioning", "Covers designing consistent, well-documented APIs for cloud services, including strategies for versioning them over time."),
            ("Cloud Load Testing and Performance Benchmarking", "Introduces simulating realistic traffic loads to measure how cloud applications perform under stress."),
            ("Cloud Environment Management (Dev/Test/Prod)", "Covers structuring separate development, testing, and production cloud environments with appropriate isolation."),
            ("Infrastructure Testing and Validation", "Introduces automated tests that validate infrastructure-as-code definitions before they are applied to cloud environments."),
            ("Policy as Code (OPA, Sentinel)", "Covers expressing organizational policies as code using tools such as Open Policy Agent to automatically enforce compliance."),
            ("Cloud Compliance Automation", "Introduces automating the detection and remediation of cloud configurations that violate compliance requirements."),
            ("Cloud Platform Engineering Fundamentals", "Covers building internal platforms and self-service tooling that let development teams provision cloud resources safely."),
            ("Cloud Center of Excellence Design", "Introduces establishing a centralized team that sets standards and best practices for cloud adoption across an organization."),
        ],
        "M1": [
            ("Edge Computing Architecture", "Covers processing data closer to its source at the network edge to reduce latency for time-sensitive applications."),
            ("Content Delivery at the Edge", "Introduces running compute logic at edge locations to personalize and accelerate content delivery closer to users."),
            ("Advanced Kubernetes Operators and Custom Resources", "Covers extending Kubernetes with custom resource definitions and operators that automate management of complex applications."),
            ("Multi-Cluster Kubernetes Management", "Introduces tools and patterns for managing and coordinating workloads across multiple Kubernetes clusters."),
            ("Advanced Service Mesh Traffic Management", "Covers advanced service mesh capabilities, including traffic splitting, retries, and circuit breaking, across microservices."),
            ("Cloud-Native Observability at Scale (OpenTelemetry)", "Introduces using the OpenTelemetry standard to collect consistent traces, metrics, and logs across large cloud systems."),
            ("Advanced FinOps for Enterprise Cloud Spend", "Extends FinOps practices to enterprise-scale forecasting, unit economics, and cross-team cost accountability."),
            ("Cloud Sustainability and Green Computing", "Introduces measuring and reducing the carbon footprint of cloud workloads through efficient architecture and provider choices."),
            ("Advanced Cloud Security Architecture for Enterprises", "Covers designing comprehensive security architectures spanning identity, network, data, and workload protection at enterprise scale."),
            ("Confidential Computing Fundamentals", "Introduces hardware-based trusted execution environments that keep data encrypted even while it is being processed."),
            ("Advanced Serverless Orchestration (Step Functions/Workflows)", "Covers using managed workflow orchestration services to coordinate multi-step serverless processes reliably."),
            ("Advanced Data Mesh Architecture in the Cloud", "Introduces the data mesh paradigm of decentralized, domain-owned data products built on shared cloud infrastructure."),
            ("Cloud-Native Machine Learning Infrastructure", "Covers the managed compute, storage, and pipeline services cloud providers offer for training and serving machine learning models."),
            ("MLOps Pipelines on Cloud Platforms", "Introduces automating the training, validation, deployment, and monitoring of machine learning models using cloud services."),
            ("Advanced Multi-Cloud Networking Architecture", "Covers designing resilient, secure network architectures that span multiple cloud providers simultaneously."),
            ("Cloud Platform Governance at Enterprise Scale", "Introduces governance structures, guardrails, and automation that manage cloud usage across a large, multi-team enterprise."),
            ("Advanced Cloud Reliability Engineering", "Covers advanced reliability practices, including sophisticated failure injection and dependency analysis, for large-scale cloud systems."),
            ("Advanced Capstone: Enterprise Cloud Migration Program", "A capstone project requiring students to plan and design a complete enterprise-scale cloud migration program."),
        ],
    },
}
