"""Additional UG2 topic modules (wave g23) for 11 subjects.

Each subject contributes 60 new (title, summary) tuples at the UG2 level,
distinct from existing UG2 syllabus topics and from each other. Consumed
by merge_all_subjects_expansion.py.
"""
from __future__ import annotations

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Project Management": {
        "UG2": [
            ("Work Breakdown Structure Development", "Decomposing a project's total scope into hierarchical, manageable work packages for planning and control."),
            ("Critical Path Method Scheduling", "Calculating the longest sequence of dependent tasks to determine minimum project duration and float."),
            ("Program Evaluation and Review Technique (PERT)", "Estimating task durations using optimistic, pessimistic, and most-likely values under uncertainty."),
            ("Resource Leveling and Smoothing", "Adjusting schedules to resolve resource over-allocation while balancing project timelines and cost."),
            ("Earned Value Management Fundamentals", "Using planned value, earned value, and actual cost to measure project schedule and cost performance."),
            ("Cost Variance and Schedule Variance Analysis", "Interpreting EVM variances to diagnose whether a project is ahead, behind, over, or under budget."),
            ("Project Charter Development", "Drafting the formal document that authorizes a project and defines its objectives, scope, and stakeholders."),
            ("Stakeholder Register and Power-Interest Grids", "Identifying stakeholders and mapping their influence and interest to tailor engagement strategies."),
            ("RACI Matrix Construction", "Clarifying roles as Responsible, Accountable, Consulted, or Informed to prevent task ownership confusion."),
            ("Project Risk Register Management", "Systematically logging, scoring, and tracking identified risks throughout a project's lifecycle."),
            ("Qualitative Risk Analysis Techniques", "Ranking risks by probability and impact using scales and probability-impact matrices."),
            ("Quantitative Risk Analysis with Monte Carlo Simulation", "Modeling schedule and cost uncertainty through repeated random sampling of risk variables."),
            ("Risk Response Strategies", "Selecting among avoid, mitigate, transfer, and accept strategies for identified project threats."),
            ("Contingency and Management Reserves", "Allocating budget and schedule buffers separately for known-unknowns and unknown-unknowns."),
            ("Procurement Planning and Contract Types", "Comparing fixed-price, cost-reimbursable, and time-and-materials contracts for vendor engagements."),
            ("Request for Proposal (RFP) Development", "Structuring solicitation documents that clearly communicate requirements to prospective vendors."),
            ("Vendor Selection and Evaluation Criteria", "Designing weighted scoring models to compare competing supplier proposals objectively."),
            ("Change Control Board Processes", "Formalizing how proposed scope, schedule, or cost changes are evaluated, approved, or rejected."),
            ("Integrated Change Control", "Coordinating changes across scope, schedule, cost, and quality baselines to maintain consistency."),
            ("Project Quality Planning", "Defining quality standards, metrics, and acceptance criteria before execution begins."),
            ("Cost of Quality Analysis", "Distinguishing prevention and appraisal costs from internal and external failure costs."),
            ("Statistical Process Control in Project Quality", "Applying control charts to monitor process variation and detect out-of-control conditions."),
            ("Project Communications Management Plan", "Specifying what information stakeholders need, in what format, and how often it is delivered."),
            ("Conflict Resolution Models in Project Teams", "Applying frameworks such as Thomas-Kilmann to navigate interpersonal conflict on project teams."),
            ("Team Development Stages (Tuckman's Model)", "Recognizing forming, storming, norming, performing, and adjourning phases of team maturity."),
            ("Resource Calendars and Capacity Planning", "Mapping team member availability against project demand to avoid scheduling conflicts."),
            ("Project Cost Estimating Techniques", "Comparing analogous, parametric, and bottom-up estimating methods for budget accuracy."),
            ("Three-Point Estimating and Beta Distribution", "Refining single-point estimates using triangular or beta-distribution weighted averages."),
            ("Project Budget Baseline and Funding Requirements", "Establishing a time-phased budget baseline against which actual spending is tracked."),
            ("Scope Creep and Scope Verification", "Identifying uncontrolled scope expansion and formal processes for validating deliverables."),
            ("Requirements Traceability Matrix", "Linking requirements to deliverables and test cases to ensure nothing is dropped during execution."),
            ("Milestone Planning and Tracking", "Using significant checkpoint events to communicate progress at a high level to stakeholders."),
            ("Gantt Chart Construction and Interpretation", "Visualizing task sequences, durations, and dependencies on a horizontal timeline."),
            ("Network Diagramming Techniques (AON, AOA)", "Representing task dependencies graphically using activity-on-node and activity-on-arrow methods."),
            ("Schedule Compression: Crashing and Fast-Tracking", "Shortening project duration by adding resources or overlapping sequential activities."),
            ("Project Closeout and Lessons Learned", "Formally closing contracts, releasing resources, and documenting knowledge for future projects."),
            ("Post-Implementation Review Techniques", "Evaluating whether a completed project delivered its intended business benefits."),
            ("Benefits Realization Management", "Tracking whether promised organizational value materializes after project delivery."),
            ("Program Management vs. Project Management", "Distinguishing the coordinated management of related projects from single-project delivery."),
            ("Portfolio Management and Prioritization", "Selecting and balancing an organization's mix of projects against strategic objectives."),
            ("PMO Structures and Governance Models", "Comparing supportive, controlling, and directive project management office designs."),
            ("Organizational Structures and Project Authority", "Analyzing how functional, matrix, and projectized structures affect a project manager's power."),
            ("Project Management Maturity Models", "Assessing organizational capability using frameworks such as OPM3 or CMMI-adjacent scales."),
            ("Critical Chain Project Management", "Applying theory-of-constraints buffer management to protect schedules from resource contention."),
            ("Agile-Waterfall Hybrid (Wagile) Approaches", "Blending predictive planning phases with iterative execution for mixed-methodology projects."),
            ("Rolling Wave Planning", "Progressively elaborating near-term work in detail while leaving distant work at a high level."),
            ("Project Cash Flow Forecasting", "Projecting periodic inflows and outflows to manage project liquidity and funding drawdowns."),
            ("Net Present Value and IRR in Project Selection", "Applying discounted cash flow techniques to compare and justify candidate projects financially."),
            ("Payback Period and Cost-Benefit Analysis", "Estimating how quickly a project recovers its investment and whether benefits outweigh costs."),
            ("Project Risk Appetite and Tolerance", "Aligning risk response decisions with an organization's willingness to accept uncertainty."),
            ("Issue Logs and Escalation Procedures", "Distinguishing risks from realized issues and defining paths for timely resolution."),
            ("Configuration Management in Projects", "Controlling versions of project deliverables and documentation throughout the lifecycle."),
            ("Cross-Cultural Project Team Management", "Adapting communication and leadership styles for geographically distributed, multicultural teams."),
            ("Virtual Team Collaboration Tools and Practices", "Selecting collaboration platforms and norms that sustain productivity in distributed teams."),
            ("Project Procurement Negotiation Tactics", "Applying principled negotiation techniques to secure favorable vendor and contract terms."),
            ("Ethics and Professional Responsibility in Project Management", "Applying codes of conduct to conflicts of interest, fairness, and stakeholder honesty."),
            ("Sustainability Considerations in Project Planning", "Incorporating environmental and social impact criteria into project scope and decision-making."),
            ("Project Dashboards and Status Reporting", "Designing visual reporting tools that summarize schedule, cost, and risk health at a glance."),
            ("Lessons from Failed Projects: Case Analysis", "Analyzing documented project failures to extract transferable governance and planning lessons."),
            ("Project Governance Frameworks", "Defining decision rights, accountability structures, and escalation paths that guide project oversight."),
        ],
    },
    "Prompt Engineering": {
        "UG2": [
            ("Chain-of-Thought Prompting Fundamentals", "Eliciting intermediate reasoning steps from a model to improve accuracy on multi-step problems."),
            ("Self-Consistency Decoding for Reasoning", "Sampling multiple reasoning paths and selecting the majority answer to boost reliability."),
            ("Least-to-Most Prompting", "Decomposing a complex problem into an ordered sequence of simpler subproblems solved progressively."),
            ("Tree-of-Thought Reasoning Strategies", "Exploring and evaluating multiple branching reasoning paths before committing to a final answer."),
            ("ReAct: Reasoning and Acting Prompting", "Interleaving reasoning traces with tool-calling actions so a model can gather information mid-task."),
            ("Retrieval-Augmented Generation Prompt Design", "Structuring prompts that incorporate retrieved documents to ground responses in external knowledge."),
            ("Prompt Injection Attack Vectors", "Identifying how adversarial input can override a model's original instructions."),
            ("Defensive Prompting Against Injection", "Designing instruction hierarchies and input sanitization to reduce susceptibility to prompt injection."),
            ("Jailbreak Techniques and Model Robustness", "Analyzing common strategies used to bypass safety training and their mitigations."),
            ("Prompt Sensitivity and Variance Analysis", "Measuring how small wording changes affect model output consistency and quality."),
            ("A/B Testing Prompt Variants", "Applying controlled experiments to compare prompt formulations against measurable success metrics."),
            ("Prompt Versioning and Change Management", "Tracking prompt revisions systematically to support rollback and reproducibility in production."),
            ("Temperature and Top-p Sampling Effects", "Understanding how decoding parameters interact with prompt design to shape output diversity."),
            ("Token Budget Optimization in Prompts", "Balancing context length against cost and latency while preserving necessary information."),
            ("Context Window Management Strategies", "Techniques for prioritizing, summarizing, or truncating content to fit within a model's context limit."),
            ("Prompt Compression Techniques", "Reducing prompt length through paraphrasing or symbolic representations without losing meaning."),
            ("Few-Shot Example Selection Strategies", "Choosing representative, diverse in-context examples to maximize few-shot learning performance."),
            ("Dynamic Few-Shot Retrieval", "Selecting in-context examples at runtime based on similarity to the current query."),
            ("Role-Based Prompting Patterns", "Assigning personas or expert roles to a model to steer tone, depth, and perspective of responses."),
            ("Meta-Prompting and Prompt Generation", "Using a model to generate or refine prompts for another downstream task or model."),
            ("Automatic Prompt Optimization Methods", "Applying search or gradient-free optimization to iteratively improve prompt wording."),
            ("Constitutional AI Principles in Prompting", "Encoding a set of guiding principles that a model uses to critique and revise its own outputs."),
            ("Self-Critique and Reflexion Prompting", "Prompting a model to evaluate and iteratively improve its own prior response."),
            ("Multi-Agent Prompt Orchestration", "Designing prompts that coordinate multiple specialized model instances toward a shared goal."),
            ("Tool Use Planning in Agentic Prompts", "Structuring prompts so a model decides when and how to invoke external tools during a task."),
            ("Prompt Chaining for Multi-Step Pipelines", "Passing outputs between sequential prompts to break a complex task into modular stages."),
            ("Prompt Templates and Parameterization", "Building reusable prompt structures with variable slots for scalable application development."),
            ("Instruction Tuning vs. Prompt Engineering", "Distinguishing model fine-tuning on instructions from crafting prompts at inference time."),
            ("Evaluating Prompts with LLM-as-Judge", "Using a separate model call to score or rank candidate outputs against defined criteria."),
            ("Rubric Design for Output Evaluation", "Creating structured scoring criteria to consistently judge subjective model responses."),
            ("Bias Detection in Prompted Outputs", "Systematically probing prompts for outputs that reflect demographic or ideological skew."),
            ("Hallucination Mitigation Techniques", "Applying grounding, citation requirements, and verification prompts to reduce fabricated content."),
            ("Calibration and Confidence Elicitation", "Prompting models to express calibrated uncertainty alongside their answers."),
            ("Prompting for Multilingual Tasks", "Adapting prompt structure and examples to maintain quality across different languages."),
            ("Cross-Lingual Prompt Transfer", "Reusing prompt strategies developed in one language effectively in another."),
            ("Prompting for Code Generation Tasks", "Structuring prompts with signatures, tests, and constraints to improve generated code correctness."),
            ("Prompting for Data Analysis and SQL Generation", "Crafting prompts that translate natural language questions into accurate query logic."),
            ("Prompting for Summarization Fidelity", "Designing prompts that constrain summaries to remain faithful to source material."),
            ("Extractive vs. Abstractive Summarization Prompts", "Comparing prompt strategies that quote source text directly against those that paraphrase."),
            ("Prompting for Sentiment and Emotion Analysis", "Structuring prompts to reliably classify nuanced emotional tone in text."),
            ("Prompting for Classification Tasks", "Designing prompts with clear label definitions and examples for consistent text categorization."),
            ("Zero-Shot Classification Prompt Design", "Crafting prompts that classify text into categories without providing labeled examples."),
            ("Prompt Engineering for Vision-Language Models", "Adapting textual prompting strategies to models that jointly process images and text."),
            ("Multimodal Prompt Design Principles", "Structuring prompts that combine text, images, or audio inputs coherently for a single task."),
            ("Prompting for Structured Reasoning in Math", "Designing prompts that scaffold step-by-step arithmetic and symbolic problem solving."),
            ("Prompt Engineering for Conversational Agents", "Balancing persona consistency, memory, and turn-taking in dialogue-oriented prompts."),
            ("Persona Consistency Across Long Conversations", "Maintaining stable character traits and tone across extended multi-turn interactions."),
            ("Prompting for Content Moderation Pipelines", "Designing classification prompts that flag policy-violating content with clear thresholds."),
            ("Red Teaming Prompts for Safety Evaluation", "Systematically probing a model with adversarial prompts to surface failure modes before deployment."),
            ("Prompt Engineering Cost-Latency Tradeoffs", "Balancing prompt complexity and length against inference cost and response time in production."),
            ("Caching Strategies for Repeated Prompts", "Reducing cost and latency by reusing prior computations for identical or similar prompt prefixes."),
            ("Prompt Engineering for Retrieval Query Rewriting", "Reformulating user queries via prompting to improve downstream document retrieval quality."),
            ("Grounding Responses with Citations", "Designing prompts that require models to reference and attribute claims to source documents."),
            ("Prompt Engineering for Data Extraction Pipelines", "Structuring prompts to reliably pull structured fields from unstructured documents at scale."),
            ("Ensembling Multiple Prompt Strategies", "Combining outputs from differently phrased prompts to improve robustness and accuracy."),
            ("Prompt Engineering Documentation Practices", "Recording prompt intent, assumptions, and test cases to support team collaboration and audits."),
            ("Regression Testing for Prompt Changes", "Building test suites that catch quality degradation when prompts are modified over time."),
            ("Prompt Engineering for Long-Document Question Answering", "Designing prompts that handle chunking, retrieval, and synthesis across lengthy source documents."),
            ("Ethics of Persuasive Prompt Design", "Examining the responsibilities involved in crafting prompts intended to influence user behavior."),
            ("Prompt Engineering Career Practices and Tooling", "Surveying professional workflows, frameworks, and evaluation platforms used in applied prompt engineering."),
        ],
    },
    "Python": {
        "UG2": [
            ("Abstract Base Classes with the abc Module", "Defining interfaces in Python that enforce method implementation in concrete subclasses."),
            ("Metaclasses and Custom Class Creation", "Understanding how type() and __new__ control the construction of Python classes themselves."),
            ("Descriptors and Attribute Access Protocols", "Implementing __get__, __set__, and __delete__ to customize attribute behavior across classes."),
            ("Context Managers with __enter__ and __exit__", "Building custom resource-management objects that integrate with the with statement."),
            ("The contextlib Module for Context Managers", "Simplifying context manager creation using contextmanager decorators and utility classes."),
            ("Multiple Inheritance and the Method Resolution Order", "Understanding C3 linearization and how Python resolves attribute lookup across parent classes."),
            ("Operator Overloading with Dunder Methods", "Implementing __add__, __eq__, and related methods to customize operator behavior for custom types."),
            ("Data Classes and the dataclasses Module", "Reducing boilerplate for classes that primarily store structured data using decorators."),
            ("Named Tuples and Structural Typing", "Using collections.namedtuple and typing.NamedTuple for lightweight, immutable record types."),
            ("Enumerations with the enum Module", "Defining symbolic constant sets using Enum, IntEnum, and Flag for readable, type-safe code."),
            ("Static Typing with Type Hints", "Annotating function signatures and variables to enable static analysis and improved tooling."),
            ("Generic Types and TypeVar Usage", "Writing reusable, type-parameterized functions and classes with the typing module."),
            ("Static Type Checking with mypy", "Integrating a static type checker into a development workflow to catch type errors before runtime."),
            ("Structural Pattern Matching with match-case", "Using Python's match statement to destructure and branch on complex data shapes."),
            ("Multithreading and the Global Interpreter Lock", "Understanding GIL constraints and when threading benefits I/O-bound versus CPU-bound tasks."),
            ("Multiprocessing for CPU-Bound Parallelism", "Using separate processes to bypass the GIL and achieve true parallel computation."),
            ("Asyncio Event Loop Fundamentals", "Understanding cooperative multitasking through Python's asynchronous programming model."),
            ("Async/Await Syntax and Coroutines", "Writing non-blocking asynchronous functions using async def and await expressions."),
            ("Concurrent Futures and Thread/Process Pools", "Managing pools of workers for parallel task execution with a unified high-level API."),
            ("Synchronization Primitives: Locks, Semaphores, Events", "Coordinating access to shared resources safely across concurrent threads or tasks."),
            ("Queue-Based Producer-Consumer Patterns", "Implementing thread-safe data pipelines using the queue module for concurrent workflows."),
            ("Memory Management and Reference Counting", "Understanding how CPython allocates, tracks, and reclaims memory for objects."),
            ("Garbage Collection and Cyclic References", "Examining how Python's cyclic garbage collector detects and cleans up reference cycles."),
            ("Profiling Python Code for Performance", "Using cProfile and related tools to identify bottlenecks in program execution."),
            ("Memory Profiling and Optimization Techniques", "Diagnosing excessive memory usage and applying strategies to reduce a program's footprint."),
            ("Writing and Using C Extensions", "Extending Python performance-critical code paths by interfacing with compiled C modules."),
            ("Just-In-Time Compilation with Numba", "Accelerating numerical Python code by compiling functions to machine code at runtime."),
            ("Cython for Performance-Critical Code", "Compiling Python-like code to C to achieve near-native execution speed for hot paths."),
            ("Unit Testing with pytest Fixtures", "Structuring reusable test setup and teardown logic using pytest's fixture system."),
            ("Parametrized Testing Strategies", "Running the same test logic across multiple input combinations to increase coverage efficiently."),
            ("Mocking and Patching in Tests", "Isolating units under test by replacing dependencies with controlled mock objects."),
            ("Test Coverage Analysis", "Measuring which lines and branches of code are exercised by an automated test suite."),
            ("Property-Based Testing with Hypothesis", "Generating randomized test inputs automatically to uncover edge-case failures."),
            ("Continuous Integration for Python Projects", "Automating test execution and quality checks on every code change using CI pipelines."),
            ("Linting and Static Analysis Tools", "Using tools such as flake8, pylint, and ruff to enforce code quality and style standards."),
            ("Code Formatting with Black and isort", "Automating consistent code formatting and import ordering across a Python codebase."),
            ("Logging Best Practices in Python", "Configuring the logging module with handlers, formatters, and levels for production applications."),
            ("Exception Chaining and Custom Exception Hierarchies", "Designing meaningful exception classes and preserving error context across raise statements."),
            ("Working with itertools for Efficient Iteration", "Applying combinatoric and lazy iteration tools to process sequences memory-efficiently."),
            ("The functools Module: reduce, partial, lru_cache", "Applying functional programming utilities to simplify and optimize Python code."),
            ("Serialization with pickle and Its Security Risks", "Understanding object serialization mechanics and the dangers of deserializing untrusted data."),
            ("Working with dataclasses and JSON Serialization", "Converting structured Python objects to and from JSON for interoperability."),
            ("Regular Expressions: Advanced Patterns", "Using lookaheads, named groups, and backreferences for complex text-matching tasks."),
            ("Working with Dates and Times (datetime, zoneinfo)", "Handling timezone-aware timestamps and date arithmetic correctly across regions."),
            ("File I/O and Pathlib for Filesystem Operations", "Using the pathlib module for cross-platform, object-oriented filesystem path handling."),
            ("Working with Binary Data and struct", "Packing and unpacking binary data formats using Python's struct module."),
            ("Building Command-Line Interfaces with argparse", "Designing user-friendly CLI tools with argument parsing, subcommands, and help text."),
            ("Building CLIs with Click and Typer", "Using modern frameworks to simplify command-line interface development with decorators."),
            ("Introduction to Design Patterns in Python", "Applying object-oriented patterns such as Singleton, Factory, and Observer idiomatically in Python."),
            ("SOLID Principles Applied to Python Code", "Applying object-oriented design principles to build maintainable, extensible Python software."),
            ("Dependency Injection in Python Applications", "Decoupling components by supplying dependencies externally rather than hardcoding them."),
            ("Working with Databases Using SQLAlchemy ORM", "Mapping Python classes to relational database tables using an object-relational mapper."),
            ("Database Migrations with Alembic", "Managing incremental, version-controlled changes to a database schema over time."),
            ("Building REST APIs with FastAPI", "Creating asynchronous, type-validated web APIs using a modern Python web framework."),
            ("Data Validation with Pydantic Models", "Enforcing runtime type validation and parsing for structured data using Pydantic."),
            ("Working with NumPy Arrays and Broadcasting", "Performing efficient vectorized numerical computation using NumPy's array operations."),
            ("Data Analysis Workflows with pandas", "Cleaning, transforming, and aggregating tabular data using the pandas library."),
            ("Packaging Python Applications with Docker", "Containerizing Python applications for consistent deployment across environments."),
            ("Python Application Deployment Strategies", "Comparing approaches for deploying Python services including WSGI, ASGI, and serverless options."),
            ("Weak References and the weakref Module", "Using weak references to track object lifetimes without preventing garbage collection."),
        ],
    },
    "R": {
        "UG2": [
            ("Vectors and Vector Recycling Rules", "Understanding how R applies element-wise operations and recycles shorter vectors during arithmetic."),
            ("Data Frames vs. Tibbles", "Comparing base R data frames with tidyverse tibbles for consistent, predictable data handling."),
            ("Factors and Categorical Data Encoding", "Representing nominal and ordinal variables efficiently using R's factor data type."),
            ("Lists and Nested Data Structures", "Storing heterogeneous and hierarchical data using R's flexible list objects."),
            ("Matrix Algebra Operations in R", "Performing matrix multiplication, transposition, and inversion using base R functions."),
            ("The Apply Family: sapply, lapply, vapply, mapply", "Applying functions over data structures without explicit loops for concise, vectorized code."),
            ("Writing Custom Functions with purrr::map", "Using purrr's functional programming tools to iterate predictably over lists and vectors."),
            ("Data Manipulation with dplyr Verbs", "Filtering, selecting, mutating, and arranging data using dplyr's core grammar of data manipulation."),
            ("Reshaping Data with tidyr (pivot_longer/pivot_wider)", "Converting data between wide and long formats to suit analysis and visualization needs."),
            ("String Manipulation with stringr", "Performing consistent string operations such as detection, extraction, and replacement using stringr."),
            ("Regular Expressions in R", "Applying pattern matching to extract and validate text data within R scripts."),
            ("Joining Datasets with dplyr Joins", "Combining multiple data frames using inner, left, right, and full join operations."),
            ("Grouped Summaries with group_by and summarize", "Computing aggregate statistics across subgroups of a dataset using dplyr's grouping functions."),
            ("Data Visualization Grammar with ggplot2", "Building layered visualizations by mapping data variables to aesthetic and geometric elements."),
            ("Customizing ggplot2 Themes and Scales", "Adjusting color scales, axis formatting, and theme elements to refine plot appearance."),
            ("Faceting for Multi-Panel Visualizations", "Splitting a single plot into multiple panels conditioned on categorical variables."),
            ("Importing Data from CSV, Excel, and JSON", "Reading structured data into R from common file formats using readr and related packages."),
            ("Connecting to Databases with DBI and odbc", "Querying relational databases directly from R using standardized database interface packages."),
            ("Web Scraping with rvest", "Extracting structured data from HTML pages using R's rvest package."),
            ("Accessing APIs with httr and jsonlite", "Making HTTP requests and parsing JSON responses to pull external data into R."),
            ("Handling Missing Data (NA) Strategies", "Detecting, summarizing, and addressing missing values through removal or imputation."),
            ("Data Cleaning and Validation Workflows", "Establishing repeatable processes to detect and correct errors in raw datasets."),
            ("Introduction to the tidyverse Ecosystem", "Surveying how core tidyverse packages interoperate for consistent data science workflows."),
            ("S3 Object-Oriented Programming in R", "Implementing R's informal object system using generic functions and class attributes."),
            ("S4 Classes and Formal Methods", "Defining structured object classes with formal validation using R's S4 system."),
            ("R6 Classes for Reference Semantics", "Building mutable, reference-based objects in R using the R6 package."),
            ("Closures and Function Factories in R", "Creating functions that generate other functions with enclosed, persistent state."),
            ("Environments as First-Class Objects", "Understanding how R environments store variable bindings and enable mutable state."),
            ("Non-Standard Evaluation and Tidy Evaluation", "Understanding how tidyverse functions capture and manipulate unevaluated expressions."),
            ("Writing Unit Tests with testthat", "Structuring automated tests for R functions to catch regressions during development."),
            ("Building an R Package Structure", "Organizing R code, documentation, and data into a properly structured installable package."),
            ("Documenting Functions with roxygen2", "Generating package documentation automatically from structured comments above function definitions."),
            ("Submitting a Package to CRAN", "Understanding the checks, standards, and submission process required for CRAN acceptance."),
            ("Version Control Integration with Git in RStudio", "Managing R project history and collaboration using Git integrated into the RStudio IDE."),
            ("Benchmarking Code with microbenchmark", "Measuring and comparing the execution speed of alternative R implementations."),
            ("Profiling R Code with profvis", "Visualizing where R code spends execution time to identify performance bottlenecks."),
            ("Parallel Computing with the parallel Package", "Distributing computational work across multiple cores to speed up R workloads."),
            ("Speeding Up R with Rcpp", "Integrating compiled C++ code into R functions for performance-critical operations."),
            ("Introduction to data.table for Large Datasets", "Using data.table's optimized syntax for fast manipulation of large tabular datasets."),
            ("Building Interactive Dashboards with Shiny", "Creating web-based interactive applications directly from R code using the Shiny framework."),
            ("Reactive Programming in Shiny", "Understanding how Shiny's reactive expressions automatically update outputs when inputs change."),
            ("Deploying Shiny Applications", "Publishing interactive R applications to hosting platforms for public or internal access."),
            ("Hypothesis Testing: t-tests and Chi-Square Tests", "Applying classical statistical tests in R to compare means and categorical distributions."),
            ("Analysis of Variance (ANOVA) in R", "Comparing means across three or more groups using R's aov and related functions."),
            ("Post-Hoc Multiple Comparison Tests", "Applying Tukey and Bonferroni corrections to control error rates after ANOVA."),
            ("Non-Parametric Statistical Tests in R", "Applying Wilcoxon, Kruskal-Wallis, and related tests when parametric assumptions are violated."),
            ("Correlation and Covariance Analysis", "Quantifying and interpreting linear relationships between numeric variables in R."),
            ("Principal Component Analysis in R", "Reducing dimensionality of correlated numeric data while preserving explained variance."),
            ("Cluster Analysis: K-Means and Hierarchical Clustering", "Grouping observations into clusters based on similarity using unsupervised methods."),
            ("Bootstrapping and Resampling Methods", "Estimating sampling distributions and confidence intervals through repeated resampling."),
            ("Time Series Decomposition in R", "Separating a time series into trend, seasonal, and residual components for analysis."),
            ("ARIMA Forecasting Models", "Fitting autoregressive integrated moving average models to forecast future time series values."),
            ("Survival Analysis with the survival Package", "Modeling time-to-event data while accounting for censored observations."),
            ("Mixed-Effects Models with lme4", "Fitting models with both fixed and random effects to account for hierarchical data structure."),
            ("Bayesian Modeling with brms", "Fitting Bayesian regression models in R using an accessible formula-based interface."),
            ("Decision Trees and Random Forests in R", "Building interpretable and ensemble tree-based models for classification and regression."),
            ("Cross-Validation with the caret Package", "Evaluating predictive model performance using resampling techniques within a unified framework."),
            ("Introduction to tidymodels for Machine Learning", "Building reproducible modeling workflows using the tidymodels collection of packages."),
            ("Spatial Data Analysis with the sf Package", "Working with geographic vector data and coordinate reference systems in R."),
            ("Text Mining with tidytext", "Applying tidy data principles to tokenize, analyze, and visualize textual data."),
        ],
    },
    "Science": {
        "UG2": [
            ("Newton's Laws of Motion and Applications", "Applying the three laws of motion to analyze forces and predict the behavior of physical systems."),
            ("Conservation of Energy and Momentum", "Using conservation principles to solve problems in collisions and mechanical systems."),
            ("Thermodynamics: Laws and Entropy", "Examining how energy transfer, work, and entropy govern physical and chemical processes."),
            ("Wave Properties: Interference and Diffraction", "Analyzing how waves combine and bend around obstacles to produce interference patterns."),
            ("Electromagnetic Spectrum and Radiation", "Surveying the range of electromagnetic radiation from radio waves to gamma rays and their properties."),
            ("Basic Circuit Analysis: Ohm's and Kirchhoff's Laws", "Applying fundamental laws to calculate current, voltage, and resistance in electrical circuits."),
            ("Atomic Structure and Electron Configuration", "Describing how electrons occupy orbitals and shells to determine an atom's chemical behavior."),
            ("Periodic Trends and the Periodic Table", "Explaining patterns in atomic radius, ionization energy, and electronegativity across the periodic table."),
            ("Chemical Bonding: Ionic, Covalent, and Metallic", "Comparing how different bonding types arise from electron sharing or transfer between atoms."),
            ("Stoichiometry and Chemical Equations", "Using balanced equations to calculate reactant and product quantities in chemical reactions."),
            ("Acid-Base Chemistry and pH", "Explaining proton transfer reactions and calculating pH for acidic and basic solutions."),
            ("Reaction Kinetics and Rate Laws", "Determining how concentration, temperature, and catalysts affect the speed of chemical reactions."),
            ("Chemical Equilibrium and Le Chatelier's Principle", "Predicting how systems at equilibrium respond to changes in concentration, pressure, or temperature."),
            ("Thermochemistry and Enthalpy", "Calculating heat changes associated with chemical reactions using enthalpy and calorimetry."),
            ("Organic Chemistry: Functional Groups", "Identifying characteristic functional groups that determine the reactivity of organic molecules."),
            ("Cell Structure and Organelle Function", "Describing the roles of organelles in maintaining cellular structure and metabolic activity."),
            ("Cellular Respiration and Photosynthesis", "Comparing how cells extract energy from glucose and how plants convert light into chemical energy."),
            ("Mendelian Genetics and Inheritance Patterns", "Applying principles of dominant and recessive inheritance to predict offspring traits."),
            ("DNA Replication and Protein Synthesis", "Explaining how genetic information is copied and translated into functional proteins."),
            ("Mutation and Genetic Variation", "Examining how changes in DNA sequence contribute to genetic diversity within populations."),
            ("Evolution by Natural Selection", "Explaining how differential survival and reproduction drive adaptation within populations."),
            ("Population Genetics Fundamentals", "Applying allele frequency models such as Hardy-Weinberg equilibrium to study population change."),
            ("Ecosystem Structure and Energy Flow", "Tracing how energy moves through trophic levels within a given ecosystem."),
            ("Biogeochemical Cycles (Carbon, Nitrogen)", "Describing how essential elements cycle between living organisms and the physical environment."),
            ("Human Anatomy: Organ Systems Overview", "Surveying the structure and interrelated function of major human organ systems."),
            ("Homeostasis and Feedback Mechanisms in Physiology", "Explaining how negative and positive feedback loops maintain internal physiological stability."),
            ("Microbiology: Bacteria, Viruses, and Fungi", "Comparing the structure, reproduction, and impact of major classes of microorganisms."),
            ("Immune System Function and Response", "Describing innate and adaptive immune mechanisms that defend the body against pathogens."),
            ("Plate Tectonics and Continental Drift", "Explaining how moving lithospheric plates shape earthquakes, volcanoes, and continental geography."),
            ("Rock Cycle and Mineral Classification", "Classifying igneous, sedimentary, and metamorphic rocks according to their formation processes."),
            ("Weather Systems and Atmospheric Circulation", "Explaining how pressure gradients and global circulation patterns generate weather phenomena."),
            ("Ocean Currents and Marine Ecosystems", "Describing how thermohaline and wind-driven currents shape marine biological productivity."),
            ("Earth's Layers and Seismology", "Analyzing seismic wave behavior to infer the composition and structure of Earth's interior."),
            ("Solar System Formation and Planetary Science", "Explaining current models of how the solar system's planets and bodies formed and evolved."),
            ("Stellar Life Cycles and Nucleosynthesis", "Tracing how stars form, evolve, and synthesize heavier elements over their life cycles."),
            ("Cosmology and the Big Bang Theory", "Surveying the observational evidence and models describing the universe's origin and expansion."),
            ("Light and Optics: Refraction and Lenses", "Explaining how light bends and focuses through lenses and optical systems."),
            ("Nuclear Physics: Fission and Fusion", "Comparing the energy release mechanisms of nuclear fission and fusion reactions."),
            ("Quantum Mechanics: Basic Principles", "Introducing wave-particle duality and probabilistic behavior at the subatomic scale."),
            ("Fluid Mechanics and Bernoulli's Principle", "Applying pressure-velocity relationships to explain fluid flow in pipes and around objects."),
            ("Biotechnology and Genetic Engineering Techniques", "Surveying methods for manipulating organismal DNA for research and applied purposes."),
            ("CRISPR Gene Editing Fundamentals", "Explaining how CRISPR-Cas systems enable targeted editing of genomic sequences."),
            ("Renewable Energy Technologies", "Comparing solar, wind, and other renewable technologies in terms of efficiency and scalability."),
            ("Climate Change Science and Modeling", "Examining the physical mechanisms and modeling approaches used to project climate change."),
            ("Biodiversity and Conservation Biology", "Analyzing threats to species diversity and strategies for habitat and species conservation."),
            ("Toxicology and Dose-Response Relationships", "Explaining how the magnitude and duration of exposure determine toxic effects on organisms."),
            ("Epidemiology and Disease Transmission Models", "Applying mathematical models to describe how infectious diseases spread through populations."),
            ("The Scientific Peer Review Process", "Examining how scientific findings are evaluated and validated before formal publication."),
            ("Reproducibility and the Replication Crisis", "Analyzing why independent replication of results has become a major concern in modern science."),
            ("Science Ethics and Research Integrity", "Surveying ethical standards governing honest conduct and reporting in scientific research."),
            ("Measurement Uncertainty and Error Analysis", "Quantifying and propagating uncertainty in experimental measurements."),
            ("Dimensional Analysis in Scientific Problem Solving", "Using unit consistency to check calculations and derive relationships between physical quantities."),
            ("Introduction to Astrobiology", "Surveying the scientific search for conditions supporting life beyond Earth."),
            ("Materials Science: Properties of Matter", "Relating the microscopic structure of materials to their macroscopic mechanical and physical properties."),
            ("Polymer Chemistry Fundamentals", "Explaining how monomer units combine to form polymers with distinct material properties."),
            ("Environmental Toxicants and Bioaccumulation", "Explaining how persistent pollutants concentrate through food chains and affect ecosystems."),
            ("Soil Science and Nutrient Cycling", "Examining soil composition and processes that regulate nutrient availability for plant growth."),
            ("Renewable vs. Nonrenewable Resource Systems", "Comparing the sustainability and environmental tradeoffs of different resource extraction systems."),
            ("Scientific Data Visualization Practices", "Applying principles for presenting quantitative scientific data clearly and honestly."),
            ("History and Philosophy of Scientific Revolutions", "Examining how major paradigm shifts have historically transformed scientific understanding."),
        ],
    },
    "Social Studies": {
        "UG2": [
            ("Foundations of Political Science", "Surveying core concepts of power, authority, and legitimacy that structure political systems."),
            ("Comparative Government Systems", "Comparing parliamentary, presidential, and hybrid systems of national governance."),
            ("Theories of the State and Sovereignty", "Examining classical and modern theories explaining the origin and authority of the state."),
            ("Democratic Institutions and Electoral Systems", "Comparing majoritarian and proportional electoral systems and their effects on representation."),
            ("Political Ideologies: Liberalism, Conservatism, Socialism", "Comparing the core values and policy implications of major political ideologies."),
            ("Public Policy Analysis Frameworks", "Applying structured frameworks to evaluate the design and impact of public policies."),
            ("International Relations Theory: Realism and Liberalism", "Comparing major theoretical lenses used to explain state behavior in the international system."),
            ("The United Nations and Global Governance", "Examining the structure and function of international institutions coordinating global cooperation."),
            ("Human Rights Frameworks and Enforcement", "Surveying international human rights instruments and mechanisms for their enforcement."),
            ("Civil Liberties and Constitutional Law Basics", "Introducing foundational constitutional protections for individual rights and freedoms."),
            ("Federalism and Distribution of Power", "Comparing how federal and unitary systems divide authority between central and regional governments."),
            ("Public Administration and Bureaucracy", "Examining how administrative agencies implement policy and exercise discretionary authority."),
            ("Political Economy Fundamentals", "Analyzing the interaction between political institutions and economic outcomes."),
            ("Comparative Economic Systems", "Comparing market, command, and mixed economic systems across different countries."),
            ("Introduction to Macroeconomic Policy", "Surveying fiscal and monetary tools governments use to influence national economic conditions."),
            ("Introduction to Microeconomic Behavior", "Examining how individual and firm decision-making responds to incentives and constraints."),
            ("Labor Markets and Wage Determination", "Analyzing supply and demand forces that shape employment levels and compensation."),
            ("Poverty and Social Welfare Policy", "Evaluating policy approaches to reducing poverty and providing social safety nets."),
            ("Social Stratification and Class Structure", "Examining how societies organize unequal access to wealth, status, and power."),
            ("Cultural Anthropology: Fieldwork Methods", "Surveying participant observation and interview techniques used in ethnographic fieldwork."),
            ("Kinship and Family Systems Across Cultures", "Comparing how different societies structure descent, marriage, and family obligation."),
            ("Anthropological Theories of Ritual and Religion", "Analyzing frameworks used to interpret the social functions of ritual and religious practice."),
            ("Human Geography: Population Distribution", "Examining the factors that shape where and how human populations settle across space."),
            ("Urbanization and City Planning Concepts", "Analyzing patterns of urban growth and the principles guiding land use and infrastructure planning."),
            ("Migration Patterns and Push-Pull Factors", "Explaining the economic, political, and environmental drivers of human migration."),
            ("Environmental Geography and Land Use", "Examining how human activity interacts with and transforms natural landscapes."),
            ("Geopolitics and Territorial Conflict", "Analyzing how geography shapes strategic competition and territorial disputes between states."),
            ("Civic Engagement and Voter Behavior", "Examining factors that influence political participation and voting decisions."),
            ("Social Contract Theory", "Comparing classical theories explaining the origin of political obligation and legitimate authority."),
            ("Theories of Justice and Distributive Fairness", "Surveying philosophical frameworks for evaluating the fairness of social and economic arrangements."),
            ("Comparative Legal Systems", "Comparing common law, civil law, and other legal traditions across different nations."),
            ("Constitutional Design and Amendment Processes", "Examining how constitutions are structured and formally changed over time."),
            ("Nationalism and National Identity Formation", "Analyzing the social and historical processes that construct shared national identity."),
            ("Globalization's Political Dimensions", "Examining how economic and cultural globalization reshape state sovereignty and policy."),
            ("Nongovernmental Organizations and Civil Society", "Surveying the role NGOs play in advocacy, service delivery, and governance."),
            ("Social Capital and Community Networks", "Examining how trust and social networks affect civic participation and collective outcomes."),
            ("Public Opinion Formation and Polling Methods", "Analyzing how public attitudes are measured and how they shape political behavior."),
            ("Media Effects on Political Behavior", "Examining how news and social media consumption influence political attitudes and participation."),
            ("Propaganda and Political Communication", "Analyzing techniques used to shape public perception through strategic political messaging."),
            ("Social Movements: Theories of Mobilization", "Comparing frameworks explaining why and how collective action movements emerge and grow."),
            ("Collective Action and the Free-Rider Problem", "Examining incentive structures that complicate cooperation in group-based political action."),
            ("Comparative Welfare State Models", "Comparing liberal, conservative, and social-democratic approaches to social welfare provision."),
            ("Immigration Policy and Integration Debates", "Examining policy approaches to immigration control and the social integration of newcomers."),
            ("Human Trafficking and Forced Migration", "Analyzing the causes, patterns, and policy responses to human trafficking and displacement."),
            ("Conflict Resolution and Peacebuilding Theory", "Surveying frameworks used to negotiate settlements and rebuild trust after violent conflict."),
            ("War and Political Violence: Causes and Patterns", "Examining theories explaining the outbreak and escalation of organized political violence."),
            ("Terrorism Studies: Definitions and Root Causes", "Analyzing definitional debates and underlying conditions associated with political terrorism."),
            ("Environmental Policy and Governance", "Examining institutional approaches to regulating environmental harms and resource use."),
            ("Indigenous Rights and Self-Determination", "Surveying legal and political movements advancing indigenous sovereignty and recognition."),
            ("Social Justice Movements: Comparative Case Studies", "Comparing strategies and outcomes across different historical social justice movements."),
            ("Ethics in Public Policy Decision-Making", "Examining normative considerations that guide fair and accountable policy choices."),
            ("Comparative Education Systems", "Comparing how different countries structure access to and governance of education."),
            ("Social Institutions: Marriage and Family Change", "Examining how shifting norms have transformed marriage and family structures over time."),
            ("Aging Societies and Social Policy", "Analyzing policy challenges posed by demographic aging and shifting dependency ratios."),
            ("Disability Studies and Social Inclusion", "Examining social and institutional barriers to inclusion for people with disabilities."),
            ("Comparative Health Policy Systems", "Comparing how different nations organize and finance access to healthcare."),
            ("Food Security and Agricultural Policy", "Examining policy responses to ensuring stable access to adequate food supplies."),
            ("Urban Poverty and Housing Policy", "Analyzing causes of concentrated urban poverty and policy responses in housing provision."),
            ("Civic Education and Democratic Participation", "Examining how education systems cultivate informed and engaged democratic citizens."),
            ("Social Research Ethics and Institutional Review", "Surveying ethical standards and review processes governing research involving human subjects."),
        ],
    },
    "Survival Skills": {
        "UG2": [
            ("Land Navigation with Map and Compass", "Using topographic maps and a compass together to determine position and plan a route."),
            ("GPS Navigation Fundamentals and Limitations", "Understanding satellite-based positioning and the circumstances where GPS devices can fail."),
            ("Knot Tying for Outdoor Applications", "Learning essential knots for securing shelter, gear, and rescue lines in field conditions."),
            ("Fire-Starting Techniques Without Matches", "Comparing friction, spark, and lens-based methods for igniting fire without conventional matches."),
            ("Water Purification Methods Compared", "Evaluating boiling, filtration, and chemical treatment for making water safe to drink."),
            ("Edible and Poisonous Plant Identification", "Learning safe identification practices to distinguish edible plants from toxic look-alikes."),
            ("Wilderness First Aid: Wound Management", "Applying cleaning, dressing, and infection-prevention techniques for injuries in remote settings."),
            ("Recognizing and Treating Hypothermia", "Identifying early symptoms of hypothermia and applying appropriate field rewarming procedures."),
            ("Recognizing and Treating Heat Exhaustion", "Distinguishing heat exhaustion from heat stroke and applying correct emergency responses."),
            ("Building Emergency Shelters from Natural Materials", "Constructing insulating shelters using available natural materials for short-term protection."),
            ("Tarp Shelter Configurations", "Comparing common tarp setups for weatherproofing and quick shelter deployment."),
            ("Layering Systems for Cold-Weather Clothing", "Applying base, insulating, and shell layering principles to regulate body temperature."),
            ("Backpack Load Planning and Weight Distribution", "Organizing gear placement to balance load and reduce strain during extended travel."),
            ("Trip Planning and Route Assessment", "Evaluating terrain, distance, and hazards when planning a multi-day outdoor route."),
            ("Reading Weather Signs in the Field", "Interpreting cloud formations, wind shifts, and pressure changes to anticipate weather changes."),
            ("Avalanche Awareness and Terrain Assessment", "Recognizing slope angles and snowpack conditions associated with elevated avalanche risk."),
            ("River Crossing Techniques and Hazards", "Assessing current strength and depth to safely cross moving water on foot."),
            ("Wildlife Encounter Safety Protocols", "Applying species-appropriate behavior to reduce risk during unexpected wildlife encounters."),
            ("Venomous Snake and Insect Bite Response", "Applying correct first-response steps following venomous bites or stings in the field."),
            ("Signal Methods for Rescue (Mirror, Whistle, Fire)", "Using visual and auditory signaling techniques to attract the attention of rescuers."),
            ("Emergency Communication Devices (PLB, Satellite Messenger)", "Comparing personal locator beacons and satellite messengers for remote emergency communication."),
            ("Trapping and Fishing for Sustenance", "Learning basic passive trapping and fishing techniques for emergency food procurement."),
            ("Food Preservation Techniques in the Field", "Applying drying, smoking, and salting methods to preserve food without refrigeration."),
            ("Foraging Ethics and Sustainable Harvesting", "Balancing food procurement needs against ecological impact and legal harvesting limits."),
            ("Basic Rope Rescue Techniques", "Applying fundamental rope systems for assisting an injured person over difficult terrain."),
            ("Improvised Tool Making from Natural Materials", "Constructing basic cutting, digging, and carrying tools from available natural resources."),
            ("Urban Survival: Power Outage Preparedness", "Planning for extended power loss in urban settings including lighting, food, and communication."),
            ("Building a Home Emergency Supply Kit", "Assembling essential supplies to sustain a household during a multi-day emergency."),
            ("Earthquake Preparedness and Response", "Applying drop-cover-hold procedures and post-earthquake safety assessment techniques."),
            ("Flood Preparedness and Evacuation Planning", "Planning evacuation routes and protective measures ahead of anticipated flooding events."),
            ("Wildfire Evacuation and Defensible Space", "Creating defensible space around structures and planning timely wildfire evacuation."),
            ("Severe Storm Sheltering Procedures", "Identifying safe sheltering locations and procedures during tornadoes and severe storms."),
            ("Personal Risk Assessment in Outdoor Activities", "Evaluating personal skill, gear, and environmental factors before undertaking outdoor activities."),
            ("Group Dynamics in Survival Situations", "Examining how group decision-making and leadership affect outcomes during emergencies."),
            ("Psychological Resilience Under Stress", "Applying mental strategies to maintain composure and effective decision-making under duress."),
            ("Decision-Making Under Uncertainty in Emergencies", "Applying structured decision frameworks when information is incomplete during emergencies."),
            ("Basic Orienteering Competition Skills", "Applying map-reading and route-choice skills in a timed orienteering course format."),
            ("Cold Water Immersion Survival", "Applying survival techniques to maximize survival time following sudden cold water immersion."),
            ("Desert Survival Water Management", "Planning water conservation and procurement strategies specific to arid desert environments."),
            ("High-Altitude Acclimatization Basics", "Understanding physiological adaptation and pacing strategies to reduce altitude sickness risk."),
            ("Wilderness Navigation Without Instruments", "Using natural indicators such as the sun and stars to maintain direction without tools."),
            ("First Aid for Fractures and Sprains", "Applying immobilization and support techniques for suspected fractures and sprains in the field."),
            ("CPR and Basic Life Support Techniques", "Applying chest compressions and rescue breathing procedures for cardiac emergencies."),
            ("Improvised Splinting and Immobilization", "Constructing splints from available materials to stabilize an injured limb."),
            ("Field Sanitation and Hygiene Practices", "Applying waste disposal and hygiene practices to prevent illness during extended field time."),
            ("Backcountry Camp Site Selection", "Evaluating terrain, drainage, and hazards when choosing a safe overnight camp location."),
            ("Leave No Trace Principles", "Applying minimal-impact practices to reduce environmental disturbance during outdoor recreation."),
            ("Bear Safety and Food Storage Techniques", "Applying proper food storage and encounter-avoidance techniques in bear country."),
            ("Insect and Pest Management in the Field", "Applying protective measures against biting insects and disease-carrying pests outdoors."),
            ("Solar Still Construction for Water Collection", "Building a solar still to condense and collect drinkable water in survival situations."),
            ("Emergency Ration Planning and Caloric Needs", "Estimating caloric requirements and planning lightweight emergency food rations."),
            ("Improvised Cordage from Natural Fibers", "Constructing usable cordage from plant fibers for shelter and equipment needs."),
            ("Basic Knife and Tool Safety", "Applying safe handling and maintenance practices for cutting tools in outdoor settings."),
            ("Situational Awareness and Threat Assessment", "Developing habits of environmental observation to anticipate and avoid emerging hazards."),
            ("Building a Bug-Out Bag", "Assembling a portable emergency kit designed for rapid evacuation."),
            ("Family Emergency Planning and Communication Trees", "Establishing communication and meeting plans for families during a disaster."),
            ("Long-Term Food Storage Principles", "Applying storage conditions and rotation practices to preserve food for extended periods."),
            ("Off-Grid Power Basics for Emergencies", "Comparing portable power sources for maintaining essential devices during outages."),
            ("Basic Vehicle Emergency Preparedness", "Assembling supplies and knowledge for surviving a roadside emergency in a vehicle."),
            ("After-Action Review for Survival Training", "Applying structured debriefing methods to improve preparedness after training exercises."),
        ],
    },
    "UI/UX Design": {
        "UG2": [
            ("Design Thinking Process Overview", "Surveying the empathize, define, ideate, prototype, and test stages of the design thinking cycle."),
            ("User Research Methods Overview", "Comparing qualitative and quantitative research methods used to understand user needs."),
            ("Creating User Personas", "Synthesizing research findings into representative archetypes that guide design decisions."),
            ("Empathy Mapping Techniques", "Organizing user research into what users say, think, feel, and do to build shared understanding."),
            ("User Journey Mapping", "Visualizing a user's end-to-end experience to identify pain points and opportunities."),
            ("Information Architecture Fundamentals", "Structuring content and navigation so users can find information intuitively."),
            ("Card Sorting for IA Validation", "Using open and closed card sorting exercises to validate content grouping decisions."),
            ("Site Mapping and Navigation Structures", "Designing hierarchical structures that organize a product's pages and navigation paths."),
            ("Wireframing Fundamentals", "Creating low-fidelity layout sketches that define structure before visual design begins."),
            ("Low-Fidelity vs. High-Fidelity Prototyping", "Comparing the speed and detail tradeoffs between rough sketches and polished interactive prototypes."),
            ("Visual Hierarchy Principles", "Using size, contrast, and placement to guide a viewer's attention through an interface."),
            ("Typography Fundamentals for Interfaces", "Applying type scale, spacing, and pairing principles to improve interface readability."),
            ("Color Theory in UI Design", "Applying color relationships and psychology to create effective and accessible interfaces."),
            ("Grid Systems and Layout Design", "Using structured grids to create consistent, aligned layouts across screen sizes."),
            ("Design Systems and Component Libraries", "Building reusable component libraries that ensure visual and functional consistency."),
            ("Atomic Design Methodology", "Structuring design systems using atoms, molecules, organisms, templates, and pages."),
            ("Accessibility Standards: WCAG Guidelines", "Applying Web Content Accessibility Guidelines to ensure interfaces are usable by people with disabilities."),
            ("Designing for Screen Readers", "Structuring interface markup and labels so assistive screen reader technology functions correctly."),
            ("Color Contrast and Accessible Palettes", "Selecting color combinations that meet contrast ratio requirements for readability."),
            ("Inclusive Design Principles", "Designing products that accommodate a broad range of abilities, contexts, and identities."),
            ("Responsive Design Principles for UX", "Adapting layout and interaction patterns to function across varying screen sizes."),
            ("Mobile-First Design Strategy", "Designing core experiences for small screens first before scaling up to larger displays."),
            ("Cross-Platform Design Consistency", "Maintaining coherent user experience across web, mobile, and native platform conventions."),
            ("UX Writing and Microcopy", "Crafting concise interface text that guides users and reduces confusion at decision points."),
            ("Design Critique and Feedback Methods", "Applying structured critique frameworks to give and receive constructive design feedback."),
            ("Heuristic Evaluation Using Nielsen's Heuristics", "Applying established usability heuristics to systematically evaluate an interface."),
            ("Cognitive Load Theory in Interface Design", "Applying principles that minimize the mental effort required to use an interface."),
            ("Gestalt Principles Applied to UI Design", "Using proximity, similarity, and closure principles to organize visual interface elements."),
            ("Affordances and Signifiers in Design", "Designing interface elements that clearly communicate how they can be used."),
            ("Mental Models and User Expectations", "Aligning interface behavior with users' existing expectations formed from prior experience."),
            ("Competitive Analysis for Product Design", "Evaluating competitor products to identify design patterns, gaps, and opportunities."),
            ("Design Sprints and Rapid Iteration", "Applying a time-boxed process for rapidly prototyping and testing design solutions."),
            ("A/B Testing for Interface Decisions", "Using controlled experiments to compare the effectiveness of alternative design variants."),
            ("Analytics-Informed Design Decisions", "Using behavioral usage data to identify friction points and prioritize design changes."),
            ("Conversion Rate Optimization Basics", "Applying design and testing techniques to improve the rate of desired user actions."),
            ("Designing Dashboards and Data Visualization UI", "Structuring interfaces that present complex data clearly for quick interpretation."),
            ("E-Commerce UX Patterns", "Applying established interaction patterns for browsing, cart, and checkout experiences."),
            ("Designing for Voice Interfaces", "Adapting design principles for interactions driven by speech rather than visual controls."),
            ("Designing for Wearable Devices", "Adapting interface design to the constraints of small screens and glanceable interactions."),
            ("Motion Design and Microinteractions", "Using small animated responses to provide feedback and enhance interface usability."),
            ("Animation Principles for UI Transitions", "Applying timing, easing, and continuity principles to create purposeful interface animation."),
            ("Design Tool Proficiency: Figma Fundamentals", "Building interfaces and prototypes using Figma's core design and component tools."),
            ("Collaborative Design Workflows in Figma", "Applying shared file structures and commenting practices to support team-based design work."),
            ("Handoff from Design to Development", "Preparing design specifications and assets so developers can implement designs accurately."),
            ("Design Tokens and Style Guides", "Defining reusable design values such as color and spacing to maintain consistency at scale."),
            ("Branding and Visual Identity in Product Design", "Applying brand guidelines consistently across a digital product's visual language."),
            ("Landing Page Design Principles", "Structuring page layout and messaging to maximize clarity and conversion on landing pages."),
            ("Designing Forms for Usability", "Applying layout, validation, and labeling practices that reduce form completion errors."),
            ("Search and Filter UX Patterns", "Designing interfaces that help users narrow large datasets efficiently."),
            ("Navigation Pattern Design (Tabs, Menus, Breadcrumbs)", "Comparing common navigation patterns and when each is most appropriate."),
            ("Dark Mode and Theming Design Considerations", "Designing interfaces that support alternate color themes without sacrificing usability."),
            ("Designing for Internationalization and Localization", "Adapting layouts and content to support multiple languages and cultural contexts."),
            ("Ethical Design and Dark Patterns", "Identifying manipulative interface patterns and applying ethical alternatives."),
            ("Privacy-Centered Design Practices", "Designing interfaces that give users clear control and visibility over their personal data."),
            ("Service Design and Blueprinting", "Mapping the front-stage and back-stage processes that shape an end-to-end service experience."),
            ("Designing Multi-Step Onboarding Flows", "Structuring sequential onboarding steps that introduce a product without overwhelming new users."),
            ("Content Strategy for Digital Products", "Planning how content is created, structured, and maintained to support product goals."),
            ("Design Portfolio Development", "Structuring case studies that communicate design process and impact to potential employers."),
            ("Stakeholder Presentation of Design Work", "Structuring presentations that communicate design rationale effectively to non-designers."),
            ("UX Metrics and KPIs for Product Teams", "Selecting quantitative measures that track the usability and business impact of design decisions."),
        ],
    },
    "Web Development": {
        "UG2": [
            ("Semantic HTML5 Structure", "Using meaningful HTML elements to improve accessibility, SEO, and code maintainability."),
            ("CSS Flexbox Layout Fundamentals", "Arranging elements along a single axis using flexible box layout properties."),
            ("CSS Grid Layout Fundamentals", "Building two-dimensional page layouts using CSS Grid's row and column system."),
            ("Responsive Design with Media Queries", "Adapting page layout and styling to different viewport sizes using CSS media queries."),
            ("CSS Preprocessors: Sass and Less", "Extending CSS with variables, nesting, and mixins to write more maintainable stylesheets."),
            ("JavaScript DOM Manipulation Basics", "Selecting and modifying page elements dynamically using core DOM APIs."),
            ("Event Handling in JavaScript", "Attaching and managing event listeners to respond to user interactions."),
            ("Asynchronous JavaScript: Promises and Async/Await", "Managing asynchronous operations cleanly using promises and async/await syntax."),
            ("Fetch API and AJAX Requests", "Making asynchronous HTTP requests from the browser to retrieve and send data without page reloads."),
            ("JavaScript Modules and Bundling", "Organizing code into reusable modules and combining them for production using bundlers."),
            ("Introduction to TypeScript for Web Development", "Adding static typing to JavaScript to catch errors earlier and improve tooling."),
            ("Component-Based Architecture with React", "Structuring user interfaces as composable, reusable components in React."),
            ("State Management in React Applications", "Comparing local component state and global state management approaches in React."),
            ("React Hooks: useState and useEffect", "Managing component state and side effects using React's hook-based API."),
            ("Routing in Single-Page Applications", "Implementing client-side navigation without full page reloads in SPAs."),
            ("Introduction to Vue.js Fundamentals", "Surveying Vue's reactive data binding and component system for building interfaces."),
            ("Introduction to Angular Fundamentals", "Surveying Angular's component, module, and dependency injection architecture."),
            ("Server-Side Rendering vs. Client-Side Rendering", "Comparing rendering strategies for performance, SEO, and interactivity tradeoffs."),
            ("Static Site Generation Concepts", "Pre-building pages at compile time to improve performance and reduce server load."),
            ("RESTful API Design Principles", "Applying resource-oriented conventions and HTTP methods to design consistent web APIs."),
            ("GraphQL Fundamentals for Web APIs", "Comparing GraphQL's query-based data fetching model to traditional REST endpoints."),
            ("Building APIs with Node.js and Express", "Creating server-side routes and middleware using a minimal Node.js web framework."),
            ("Middleware Patterns in Web Frameworks", "Structuring reusable request-processing logic that runs before route handlers."),
            ("Working with Relational Databases in Web Apps", "Integrating SQL databases into web applications for structured data persistence."),
            ("Working with NoSQL Databases in Web Apps", "Integrating document-oriented databases into web applications for flexible schemas."),
            ("Database Schema Design for Web Applications", "Structuring normalized and denormalized data models to support application requirements."),
            ("Caching Strategies for Web Performance", "Applying browser, server, and CDN caching to reduce latency and server load."),
            ("Content Delivery Networks and Edge Caching", "Distributing static assets geographically to reduce load times for global users."),
            ("Web Performance Optimization Techniques", "Applying techniques such as minification and image optimization to speed up page loads."),
            ("Lighthouse Audits and Core Web Vitals", "Measuring and interpreting performance, accessibility, and SEO metrics for web pages."),
            ("Lazy Loading and Code Splitting", "Deferring the loading of non-critical resources to improve initial page load time."),
            ("Progressive Web App Fundamentals", "Building web applications with offline support and installable, app-like behavior."),
            ("Service Workers and Offline Functionality", "Using background scripts to cache assets and enable offline web experiences."),
            ("WebSockets for Real-Time Communication", "Establishing persistent bidirectional connections for real-time web application features."),
            ("Server-Sent Events for Live Updates", "Streaming one-way real-time updates from server to client over a persistent connection."),
            ("Authentication Flows: Session vs. Token-Based", "Comparing cookie-session and token-based approaches to authenticating web users."),
            ("OAuth 2.0 and Social Login Integration", "Implementing delegated authorization to allow third-party login on web applications."),
            ("JSON Web Tokens (JWT) Fundamentals", "Understanding the structure and use of JWTs for stateless authentication."),
            ("Web Accessibility (WCAG) for Developers", "Implementing markup and interaction patterns that meet web accessibility standards."),
            ("ARIA Roles and Accessible Markup", "Using ARIA attributes to improve accessibility for custom interactive components."),
            ("Cross-Browser Compatibility Testing", "Verifying consistent behavior of web applications across different browsers and engines."),
            ("Version Control Workflows with Git for Teams", "Applying branching and merge strategies to support collaborative web development."),
            ("Continuous Integration and Deployment for Web Apps", "Automating build, test, and deployment pipelines for web application delivery."),
            ("Containerizing Web Applications with Docker", "Packaging web applications and dependencies into portable, consistent containers."),
            ("Deploying Web Applications to Cloud Platforms", "Comparing common cloud hosting options for deploying production web applications."),
            ("Environment Configuration and Secrets Management", "Managing environment-specific settings and sensitive credentials securely."),
            ("Monitoring and Logging for Web Applications", "Instrumenting applications to track errors, performance, and usage in production."),
            ("Load Balancing and Horizontal Scaling", "Distributing traffic across multiple servers to handle increased application load."),
            ("Microservices Architecture for Web Systems", "Decomposing a web application into independently deployable services."),
            ("API Versioning Strategies", "Comparing approaches for evolving web APIs without breaking existing client integrations."),
            ("Unit Testing JavaScript with Jest", "Writing automated tests to verify the correctness of individual JavaScript functions."),
            ("End-to-End Testing with Cypress or Playwright", "Automating browser-based tests that simulate real user interactions with a web app."),
            ("Test-Driven Development for Web Applications", "Writing tests before implementation to guide the design of web application code."),
            ("Web Application Architecture Patterns (MVC, MVVM)", "Comparing structural patterns that separate concerns within a web application."),
            ("Building Design Systems for Web Products", "Creating reusable UI component libraries to ensure consistency across a web product."),
            ("Internationalization and Localization for Web Apps", "Adapting web applications to support multiple languages and regional formats."),
            ("SEO Fundamentals for Web Developers", "Applying technical practices that improve a site's discoverability in search engines."),
            ("Web Analytics Integration", "Instrumenting web applications to capture and interpret user behavior data."),
            ("Building Accessible Forms", "Structuring form markup and validation feedback to be usable with assistive technology."),
            ("Headless CMS Integration for Web Projects", "Connecting a decoupled content management system to a custom web front end."),
        ],
    },
    "World History": {
        "UG2": [
            ("Prehistoric Societies and the Neolithic Revolution", "Examining how the transition to agriculture transformed human social organization."),
            ("Mesopotamian Civilizations and Law Codes", "Analyzing how early Mesopotamian states developed writing, cities, and codified law."),
            ("Ancient Egypt: State Formation and Religion", "Examining how religious ideology and centralized authority shaped ancient Egyptian civilization."),
            ("The Indus Valley Civilization", "Surveying urban planning and material culture evidence from Harappan settlements."),
            ("Shang and Zhou Dynasty China", "Examining the political and religious foundations of early Chinese dynastic rule."),
            ("Classical Greece: Democracy and Philosophy", "Analyzing the political innovations and intellectual traditions of classical Athenian society."),
            ("The Hellenistic World After Alexander", "Examining how Alexander's conquests spread Greek culture across a diverse empire."),
            ("The Roman Republic's Political Institutions", "Analyzing the balance of power among Rome's consuls, senate, and popular assemblies."),
            ("The Fall of the Western Roman Empire", "Evaluating political, economic, and military explanations for Rome's western collapse."),
            ("The Byzantine Empire and Justinian's Legal Reforms", "Examining how Byzantine legal codification shaped later European law."),
            ("The Rise of Islam and Early Caliphates", "Tracing the political and religious expansion of the early Islamic caliphates."),
            ("The Crusades: Causes and Consequences", "Analyzing the religious, political, and economic motivations behind the Crusades."),
            ("Feudalism and Manorialism in Medieval Europe", "Examining the social and economic obligations structuring medieval European society."),
            ("The Black Death and Its Social Impact", "Analyzing how the plague reshaped labor systems and social structures in medieval Europe."),
            ("The Mali Empire and Mansa Musa", "Examining the wealth, trade networks, and scholarship of the medieval Mali Empire."),
            ("Great Zimbabwe and Southern African Trade Networks", "Analyzing archaeological evidence of state formation and trade in southern Africa."),
            ("The Aztec Empire: Society and Statecraft", "Examining the political organization and tributary system of the Aztec Empire."),
            ("The Inca Empire and Andean Administration", "Analyzing how the Inca administered a vast empire across diverse Andean terrain."),
            ("The Italian Renaissance and Humanism", "Examining how humanist thought and patronage transformed Italian art and scholarship."),
            ("The Protestant Reformation", "Analyzing the theological disputes and political consequences of the Reformation."),
            ("The Age of Exploration and Early Globalization", "Examining how European maritime expansion connected previously separate world regions."),
            ("The Columbian Exchange", "Analyzing the transfer of crops, animals, and disease between the Old and New Worlds."),
            ("The Enlightenment and Political Philosophy", "Examining how Enlightenment thinkers reshaped ideas of reason, rights, and governance."),
            ("The French Revolution and the Terror", "Analyzing the causes and radicalization of the French Revolution."),
            ("The Napoleonic Wars and Their Legacy", "Examining how Napoleon's campaigns reshaped European political boundaries and law."),
            ("Latin American Wars of Independence", "Analyzing the movements that ended Spanish and Portuguese colonial rule in Latin America."),
            ("The Congress of Vienna and European Balance of Power", "Examining how post-Napoleonic diplomacy sought to restore European stability."),
            ("The Scramble for Africa", "Analyzing the causes and consequences of European territorial partition of Africa."),
            ("The Meiji Restoration and Japanese Modernization", "Examining how Japan rapidly modernized its institutions in the late nineteenth century."),
            ("The Opium Wars and Qing Dynasty Decline", "Analyzing how conflict with Western powers accelerated the decline of Qing authority."),
            ("Nationalism and Unification Movements in 19th-Century Europe", "Examining the political processes that unified Italy and Germany as nation-states."),
            ("The Origins of World War I", "Analyzing the alliance systems and crises that led to the outbreak of World War I."),
            ("The Treaty of Versailles and Its Consequences", "Examining how postwar settlement terms shaped interwar European politics."),
            ("The Interwar Period: Economic Crisis and Extremism", "Analyzing how economic instability contributed to the rise of political extremism."),
            ("The Rise of Fascism in Europe", "Examining the ideological and social conditions that enabled fascist movements to gain power."),
            ("The Spanish Civil War", "Analyzing the conflict's role as an ideological battleground within interwar Europe."),
            ("World War II: The Pacific Theater", "Examining the major campaigns and turning points of the Pacific war."),
            ("World War II: The European Theater", "Examining the major campaigns and turning points of the European war."),
            ("The Yalta and Potsdam Conferences", "Analyzing how wartime diplomacy shaped the postwar division of Europe."),
            ("The Chinese Communist Revolution", "Examining the causes and consequences of the Communist victory in the Chinese Civil War."),
            ("The Partition of India and Pakistan", "Analyzing the political process and human consequences of South Asian partition."),
            ("The Cuban Revolution and Cold War Latin America", "Examining how the Cuban Revolution reshaped Cold War dynamics in Latin America."),
            ("The Cold War in Europe: Blockades and Alliances", "Analyzing how competing alliance systems divided Cold War Europe."),
            ("The Cuban Missile Crisis", "Examining the diplomatic standoff that brought the Cold War to the brink of nuclear conflict."),
            ("African Independence Movements", "Analyzing the political processes through which African nations achieved independence."),
            ("The Vietnam War: Origins and Escalation", "Examining the political and military factors that escalated the Vietnam conflict."),
            ("The Iranian Revolution of 1979", "Analyzing the causes and regional consequences of Iran's 1979 revolution."),
            ("The Fall of the Berlin Wall", "Examining the political events that led to German reunification."),
            ("The Collapse of the Soviet Union", "Analyzing the internal and external pressures that ended Soviet rule."),
            ("Apartheid and the South African Transition", "Examining the establishment and eventual dismantling of South Africa's apartheid system."),
            ("The Rwandan Genocide", "Analyzing the political and historical factors that led to the 1994 genocide."),
            ("The Yugoslav Wars and Balkan Fragmentation", "Examining the ethnic and political conflicts that fragmented former Yugoslavia."),
            ("The Arab Spring and Its Aftermath", "Analyzing the causes and varied outcomes of the 2011 regional uprisings."),
            ("The Rise of China as a Global Power", "Examining the economic and political developments behind China's global rise."),
            ("The European Union's Formation and Expansion", "Analyzing the historical process of European economic and political integration."),
            ("Global Migration Patterns in the 20th and 21st Centuries", "Examining major waves of international migration and their historical drivers."),
            ("The History of International Human Rights Law", "Tracing the development of international legal frameworks protecting human rights."),
            ("Comparative Genocide Studies", "Comparing historical cases of genocide to identify common warning signs and patterns."),
            ("The History of Global Trade Institutions", "Examining the historical development of institutions governing international trade."),
            ("Contemporary Geopolitical Conflicts: A Historical Lens", "Applying historical context to analyze the roots of ongoing global conflicts."),
        ],
    },
    "World Literature": {
        "UG2": [
            ("Homeric Epics and Oral Tradition", "Examining how the Iliad and Odyssey encode oral-formulaic composition and heroic values."),
            ("Greek Tragedy: Sophocles and the Tragic Hero", "Analyzing how Sophoclean drama constructs fate, hubris, and moral conflict."),
            ("Euripides and the Questioning of Convention", "Studying how Euripides' plays challenge Athenian social and religious norms."),
            ("Virgil's Aeneid and Roman National Epic", "Considering how Virgil's epic constructs Roman identity and imperial destiny."),
            ("Dante's Divine Comedy and Medieval Cosmology", "Exploring how Dante structures the afterlife to reflect medieval theology and politics."),
            ("The Thousand and One Nights and Frame Narrative", "Analyzing the nested storytelling structure of this Arabic literary tradition."),
            ("Ferdowsi's Shahnameh and Persian National Identity", "Examining how this epic preserves pre-Islamic Persian myth and history."),
            ("The Poetry of Rumi and Sufi Mysticism", "Studying how Rumi's verse expresses mystical union through metaphor and allegory."),
            ("Murasaki Shikibu's Tale of Genji", "Considering this work's role as an early psychological novel in Heian-era Japan."),
            ("Journey to the West and Chinese Allegorical Fiction", "Analyzing how this classical novel blends religious allegory with adventure narrative."),
            ("Cao Xueqin's Dream of the Red Chamber", "Studying this novel's portrayal of family decline and social realism in Qing China."),
            ("The Mahabharata and Ramayana as Foundational Epics", "Comparing how these Sanskrit epics shape South Asian ethical and cultural traditions."),
            ("Cervantes' Don Quixote and the Birth of the Novel", "Examining how this work parodies chivalric romance while founding modern narrative fiction."),
            ("Shakespearean Tragedy and Character Complexity", "Analyzing psychological depth and moral ambiguity in Shakespeare's major tragedies."),
            ("Goethe's Faust and the Bildungsroman Tradition", "Studying how Goethe's work shapes the genre of self-formation narratives."),
            ("Romanticism as a Literary Movement", "Surveying how Romantic writers emphasized emotion, nature, and individualism against Enlightenment rationalism."),
            ("Realism and the Depiction of Everyday Life", "Examining how nineteenth-century Realist authors sought objective representation of ordinary experience."),
            ("Naturalism and Literary Determinism", "Studying how Naturalist writers applied deterministic, scientific frameworks to human behavior in fiction."),
            ("Leo Tolstoy and the Panoramic Russian Novel", "Analyzing how Tolstoy's fiction integrates historical scope with individual psychology."),
            ("Fyodor Dostoevsky and Existential Crisis in Fiction", "Examining how Dostoevsky's novels dramatize moral and spiritual conflict."),
            ("Anton Chekhov and the Modern Short Story Form", "Studying how Chekhov's understated style shaped short fiction and drama."),
            ("Symbolism and Poetic Suggestion", "Exploring how Symbolist poets used indirect imagery to evoke mood over explicit meaning."),
            ("Charles Baudelaire and Modern Urban Poetry", "Analyzing how Baudelaire's verse captures alienation in the modern city."),
            ("Marcel Proust and Involuntary Memory", "Studying how Proust's narrative technique reconstructs time through sensory recollection."),
            ("Franz Kafka and the Literature of Alienation", "Examining how Kafka's fiction depicts bureaucratic absurdity and existential dread."),
            ("Thomas Mann and the Novel of Ideas", "Studying how Mann's fiction explores intellectual and cultural conflict in European society."),
            ("James Joyce and Stream of Consciousness Technique", "Analyzing how Joyce's narrative innovations represent interior consciousness."),
            ("Virginia Woolf and Modernist Narrative Form", "Examining how Woolf's fiction experiments with time, perspective, and inner life."),
            ("Surrealism in Literature", "Studying how Surrealist writers used automatic writing and dream logic to bypass rational control."),
            ("Existentialist Literature: Sartre and Camus", "Analyzing how existentialist fiction dramatizes freedom, absurdity, and authentic choice."),
            ("Theatre of the Absurd: Beckett and Ionesco", "Examining how absurdist drama abandons conventional plot to express meaninglessness."),
            ("Frantz Fanon and Anticolonial Literary Theory", "Studying how Fanon's writing frames colonialism's psychological and political effects."),
            ("Chinua Achebe and the African Novel in English", "Analyzing how Achebe's fiction reclaims African narrative from colonial depiction."),
            ("Wole Soyinka and African Drama", "Studying how Soyinka's plays fuse Yoruba tradition with modern theatrical form."),
            ("Naguib Mahfouz and the Modern Arabic Novel", "Examining how Mahfouz's fiction chronicles social change in twentieth-century Egypt."),
            ("Rabindranath Tagore and Bengali Literary Modernism", "Studying how Tagore's poetry and fiction bridge Indian tradition and modern humanism."),
            ("Gabriel Garcia Marquez and Magical Realism", "Analyzing how Garcia Marquez blends the fantastical with the historical in Latin American fiction."),
            ("Jorge Luis Borges and the Literature of Ideas", "Studying how Borges' short fiction explores infinity, labyrinths, and metafiction."),
            ("Pablo Neruda and Political Poetry", "Examining how Neruda's verse merges personal lyricism with social and political commitment."),
            ("The Latin American Boom's Narrative Techniques", "Analyzing shared stylistic innovations across the mid-century Latin American novel."),
            ("Isabel Allende and Feminist Magical Realism", "Studying how Allende's fiction adapts magical realism to explore gender and family history."),
            ("Toni Morrison's Narrative Structure and Memory", "Examining how Morrison's fiction represents historical trauma through nonlinear form."),
            ("Caribbean Literature and Creole Identity", "Studying how Caribbean writers negotiate language, colonialism, and hybrid identity."),
            ("Derek Walcott and Postcolonial Epic Poetry", "Analyzing how Walcott's poetry reimagines epic form for a Caribbean context."),
            ("Jamaica Kincaid and Postcolonial Voice", "Studying how Kincaid's prose confronts colonial legacy and mother-daughter relationships."),
            ("Holocaust Literature: Testimony and Memory", "Examining how survivor narratives grapple with representing atrocity."),
            ("Primo Levi and the Literature of Witness", "Studying how Levi's writing documents and reflects on the Holocaust experience."),
            ("Dystopian Fiction: Orwell, Huxley, and Zamyatin", "Comparing how these authors critique totalitarianism and social control through speculative fiction."),
            ("Irish Literary Revival: Yeats and National Identity", "Studying how the Irish Literary Revival reclaimed myth and language for cultural nationalism."),
            ("Scandinavian Drama: Ibsen and Social Critique", "Analyzing how Ibsen's plays challenge bourgeois social conventions."),
            ("The Bildungsroman as a Global Genre", "Comparing coming-of-age narrative structures across different literary traditions."),
            ("Epistolary Fiction and Narrative Intimacy", "Studying how the letter-novel form shapes reader perspective and characterization."),
            ("Literature of Exile and Displacement", "Examining recurring themes of homeland loss across diasporic and exile writing."),
            ("Oral Epic Traditions in Africa", "Studying griot storytelling and oral epic performance across West African cultures."),
            ("Classical Sanskrit Drama and Rasa Theory", "Examining how Sanskrit dramatic theory frames aesthetic emotion in performance."),
            ("Noh Theatre and Japanese Dramatic Tradition", "Studying the stylized conventions and spiritual themes of classical Noh performance."),
            ("Postmodern Metafiction and Narrative Play", "Analyzing how postmodern authors foreground the constructed nature of storytelling."),
            ("World Literature and Translation Theory", "Examining debates over fidelity, adaptation, and loss in literary translation."),
            ("The Nobel Prize in Literature and Canon Formation", "Studying how prize culture shapes global perceptions of literary merit."),
            ("Graphic Narrative as Literary Form", "Examining how graphic novels combine visual and textual storytelling to achieve literary complexity."),
        ],
    },
}
