"""Top-up topic batch (group 41) for UG2 subjects that fell short of the
80-lesson minimum after title collisions were skipped by the merge script.

Each subject lists NEW (title, summary) tuples only -- verified against the
existing UG2 lesson titles in backend/syllabus/level_ug2.json to avoid
duplication, and written to be specific enough to avoid colliding with
topics already present at other levels (C1, C2, UG1, UG3, UG4, M1, M2).
"""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "ICT & Computer Science": {
        "UG2": [
            ("Software-Defined Networking Principles", "Explains how SDN separates the network control plane from the data plane to enable centralized, programmable network management."),
            ("Edge Computing Architectures for ICT Systems", "Surveys how processing and storage are pushed closer to data sources to reduce latency and bandwidth use in distributed ICT systems."),
            ("Digital Forensics Fundamentals", "Introduces the principles and tools used to identify, preserve, and analyze digital evidence following a security incident."),
            ("Green Computing and Energy-Efficient Systems", "Examines strategies for reducing the energy footprint of computing infrastructure, from hardware design to data center operations."),
            ("Quantum Computing: Foundational Concepts", "Introduces qubits, superposition, and entanglement as the basis for understanding quantum computing's potential impact on ICT."),
            ("ICT Standards and Interoperability Frameworks", "Explores how technical standards bodies enable different systems and vendors to exchange data and work together reliably."),
            ("Data Center Design and Cooling Systems", "Covers the physical and engineering considerations behind building and cooling large-scale data center facilities."),
            ("Cyber-Physical Systems in ICT", "Studies the integration of computation, networking, and physical processes in systems such as smart grids and industrial control."),
            ("Digital Twins in Enterprise ICT", "Explains how virtual replicas of physical assets and processes are used for monitoring, simulation, and optimization in organizations."),
        ],
    },
    "Islamic Studies": {
        "UG2": [
            ("Al-Andalus: Islamic Civilization in Medieval Spain", "Surveys the political, intellectual, and cultural achievements of Muslim rule in the Iberian Peninsula."),
            ("The Almoravid and Almohad Dynasties in North Africa", "Examines the rise, reform movements, and territorial reach of these Berber Muslim dynasties across the Maghreb and Iberia."),
            ("Islamic Astronomy and the Science of Timekeeping", "Explores how Muslim astronomers advanced observational astronomy to determine prayer times, the lunar calendar, and the qibla direction."),
            ("Al-Azhar and the Institution of Islamic Higher Learning", "Traces the development of Al-Azhar as a center of religious scholarship and its role in shaping Islamic education."),
            ("Islamic Legal Maxims (Qawa'id Fiqhiyyah)", "Introduces the concise general principles jurists use to derive and apply rulings consistently across diverse legal cases."),
            ("Sukuk and Contemporary Islamic Finance Instruments", "Examines how Sharia-compliant financial certificates are structured to avoid interest while enabling investment and capital raising."),
            ("The Hajj: Ritual Structure and Historical Development", "Studies the origins, rites, and historical evolution of the annual pilgrimage to Mecca."),
            ("Islamic Bioethics and Modern Medical Dilemmas", "Considers how classical Islamic legal and ethical reasoning has been applied to issues such as organ donation and end-of-life care."),
            ("Muslim Minorities in the West: Identity and Integration", "Examines the social, religious, and identity questions facing Muslim communities living as minorities in Western societies."),
            ("Ibn Khaldun and the Science of Society", "Introduces Ibn Khaldun's Muqaddimah and his pioneering theories of social cohesion, cyclical history, and the rise and fall of dynasties."),
        ],
    },
    "JavaScript": {
        "UG2": [
            ("TypeScript Integration with JavaScript Projects", "Explains how gradual typing with TypeScript can be layered onto existing JavaScript codebases to catch errors earlier."),
            ("The Temporal API for Date and Time Handling", "Introduces the modern Temporal proposal for representing and manipulating dates, times, and time zones in JavaScript."),
            ("Web Components and Custom Elements", "Covers how to define reusable, framework-agnostic UI elements using the native Custom Elements specification."),
            ("Shadow DOM Encapsulation Techniques", "Explains how Shadow DOM isolates a component's markup and styles from the rest of the page."),
            ("Intersection Observer and Resize Observer APIs", "Covers browser APIs for efficiently detecting element visibility and size changes without expensive polling."),
            ("WebAssembly Interoperability with JavaScript", "Explores how WebAssembly modules are loaded and called from JavaScript to run near-native-speed code in the browser."),
            ("Server-Sent Events for Real-Time Updates", "Introduces the EventSource API for pushing one-way real-time updates from server to browser over HTTP."),
            ("The Intl API for Internationalization", "Covers using the built-in Intl object to format numbers, dates, and strings according to locale conventions."),
            ("Structured Clone and Deep Copying Techniques", "Compares approaches to deep-copying JavaScript values, including the structuredClone API and its limitations."),
            ("Module Federation for Micro-Frontends", "Explains how Module Federation allows independently built JavaScript applications to share code at runtime."),
            ("Optional Chaining and Nullish Coalescing Operators", "Covers how these operators simplify safe property access and default-value assignment in modern JavaScript."),
        ],
    },
    "MBA": {
        "UG2": [
            ("Blue Ocean Strategy and Value Innovation", "Introduces the framework for creating uncontested market space rather than competing head-to-head in existing industries."),
            ("Scenario Planning for Strategic Foresight", "Covers how organizations construct and use multiple plausible future scenarios to stress-test strategic decisions."),
            ("Balanced Scorecard Implementation", "Explains how the balanced scorecard translates strategy into measurable objectives across financial and non-financial perspectives."),
            ("Family Business Governance and Succession Planning", "Examines the governance structures and succession challenges unique to family-owned enterprises."),
            ("Nonprofit and Social Enterprise Management", "Covers the distinctive management, funding, and mission challenges facing nonprofit and social enterprise organizations."),
            ("Franchising Strategy and Operations", "Explains how franchising agreements structure the relationship between franchisor and franchisee to scale a business model."),
            ("Business Model Canvas and Lean Startup Methodology", "Introduces frameworks for rapidly designing, testing, and iterating on new business models."),
            ("Employee Engagement and Motivation Theory", "Surveys theories of workplace motivation and their application to improving employee engagement and retention."),
            ("Talent Acquisition and Workforce Planning", "Covers strategies for forecasting workforce needs and attracting the right talent to meet organizational goals."),
            ("Corporate Social Responsibility Strategy", "Examines how firms integrate social and environmental responsibility into core business strategy."),
            ("Global Supply Chain Finance", "Explains financial instruments and practices used to optimize working capital across international supply chains."),
            ("Real Options Analysis in Capital Budgeting", "Introduces how option-pricing concepts are applied to value managerial flexibility in capital investment decisions."),
            ("Behavioral Economics for Managers", "Explores how cognitive biases and heuristics affect managerial and consumer decision-making."),
            ("Digital Transformation Leadership", "Examines the leadership practices needed to guide organizations through large-scale digital and technological change."),
            ("Customer Lifetime Value Modeling", "Covers methods for estimating the long-term value of a customer relationship to guide marketing and retention investment."),
            ("Board Committee Structures and Executive Oversight", "Explains how board committees are organized to oversee audit, compensation, and risk functions in corporate governance."),
            ("Mergers and Acquisitions Integration Planning", "Covers the post-deal challenges of combining operations, cultures, and systems after a merger or acquisition."),
        ],
    },
    "Machine Learning": {
        "UG2": [
            ("Random Forest Algorithms", "Explains how ensembles of decorrelated decision trees improve predictive accuracy and reduce overfitting."),
            ("AdaBoost and Boosting Fundamentals", "Introduces the core idea of adaptive boosting, where sequential weak learners focus on previously misclassified examples."),
            ("Gradient Boosting Machines: Theory and Implementation", "Covers how gradient boosting builds an ensemble by fitting new models to the residual errors of prior models."),
            ("Naive Bayes Classifiers", "Explains the probabilistic reasoning behind Naive Bayes classification and its conditional independence assumption."),
            ("Hidden Markov Models for Sequential Data", "Introduces how hidden Markov models represent latent state sequences underlying observed data."),
            ("Gaussian Processes for Regression", "Covers how Gaussian processes provide a probabilistic, non-parametric approach to regression with uncertainty estimates."),
            ("Kernel Methods and the Kernel Trick", "Explains how kernel functions allow linear algorithms to model nonlinear relationships without explicit feature mapping."),
            ("Bayesian Optimization for Hyperparameter Tuning", "Introduces how probabilistic surrogate models guide efficient search over expensive-to-evaluate hyperparameter spaces."),
            ("Cross-Validation Strategies and Model Selection", "Covers techniques such as k-fold and stratified cross-validation for reliably estimating model generalization performance."),
            ("Bias-Variance Tradeoff and Learning Curves", "Explains how model complexity affects bias and variance, and how learning curves diagnose underfitting and overfitting."),
            ("Transfer Learning Fundamentals", "Introduces how knowledge learned on one task or dataset can be reused to improve learning on a related task."),
            ("Domain Adaptation Techniques", "Covers methods for adapting a model trained on one data distribution to perform well on a related but different distribution."),
            ("Multi-Task Learning Architectures", "Explains how models trained jointly on multiple related tasks can share representations to improve overall performance."),
            ("Contrastive Learning Methods", "Introduces how models learn representations by pulling similar examples together and pushing dissimilar ones apart."),
            ("Knowledge Distillation for Model Compression", "Covers how a smaller student model is trained to mimic a larger teacher model's outputs to reduce inference cost."),
            ("Curriculum Learning Strategies", "Explains how presenting training examples in a structured order of increasing difficulty can improve learning."),
            ("Federated Learning Fundamentals", "Introduces how models are trained collaboratively across decentralized devices without centralizing raw data."),
            ("Recommender Systems: Collaborative Filtering", "Covers how user-item interaction patterns are used to predict preferences and generate recommendations."),
            ("Content-Based Recommendation Techniques", "Explains how item features and user profiles are used to recommend items similar to those a user has liked before."),
            ("Association Rule Mining and Market Basket Analysis", "Introduces algorithms such as Apriori for discovering frequent itemsets and co-occurrence patterns in transactional data."),
            ("Multi-Armed Bandit Algorithms", "Covers strategies for balancing exploration and exploitation when sequentially choosing among uncertain reward options."),
            ("Genetic Algorithms and Evolutionary Computation", "Introduces optimization methods inspired by natural selection, including selection, crossover, and mutation operators."),
            ("Data Augmentation Techniques for Machine Learning", "Surveys methods for artificially expanding training data to improve model robustness and generalization."),
            ("Continual Learning and Catastrophic Forgetting", "Examines the challenge of training models on sequential tasks without losing performance on previously learned ones."),
        ],
    },
    "Math": {
        "UG2": [
            ("Group Theory: Groups, Subgroups, and Homomorphisms", "Introduces the algebraic structure of groups and how homomorphisms preserve group operations between them."),
            ("Ring Theory and Ideal Structures", "Covers rings, ideals, and quotient rings as foundational objects in abstract algebra."),
            ("Real Analysis: Sequences and Series Convergence", "Studies rigorous criteria for the convergence of sequences and series of real numbers."),
            ("Functional Analysis: Banach and Hilbert Spaces", "Introduces infinite-dimensional vector spaces equipped with norms and inner products and their key properties."),
            ("Game Theory: Nash Equilibrium and Strategic Games", "Covers how strategic interactions between rational agents are modeled and analyzed for equilibrium outcomes."),
            ("Linear Programming and the Simplex Method", "Explains how linear optimization problems with constraints are solved using the simplex algorithm."),
            ("Knot Theory Fundamentals", "Introduces the mathematical study of knots as embeddings of circles in three-dimensional space and their invariants."),
            ("Algebraic Topology: Fundamental Groups", "Covers how the fundamental group captures information about the loops and holes in a topological space."),
            ("Information Theory and Entropy", "Introduces Shannon entropy and its role in quantifying information content and channel capacity."),
            ("Mathematical Finance: The Black-Scholes Model", "Explains the partial differential equation approach to pricing European options in continuous time."),
            ("Diophantine Equations and Integer Solutions", "Studies polynomial equations for which only integer or rational solutions are sought."),
        ],
    },
    "Music": {
        "UG2": [
            ("Renaissance Polyphony and Vocal Counterpoint", "Examines the interweaving independent vocal lines characteristic of Renaissance sacred and secular polyphony."),
            ("Gregorian Chant and Medieval Liturgical Music", "Surveys the modal melodic tradition of unaccompanied chant used in medieval Christian liturgy."),
            ("Orff and Kodaly Methods in Music Pedagogy", "Compares two influential approaches to teaching music through movement, singing, and structured sequencing."),
            ("Live Sound Reinforcement and Concert Audio Engineering", "Covers the equipment and techniques used to amplify and mix audio for live musical performances."),
        ],
    },
    "Natural Language Processing": {
        "UG2": [
            ("Dependency Parsing Techniques", "Covers algorithms for identifying grammatical relationships between words as a directed dependency tree."),
            ("Constituency Parsing and Treebanks", "Introduces phrase-structure parsing and the annotated treebanks used to train and evaluate parsers."),
            ("Semantic Role Labeling", "Explains how sentences are analyzed to identify predicate-argument structures such as agent and patient roles."),
            ("Word Sense Disambiguation", "Covers methods for determining which meaning of an ambiguous word is intended in a given context."),
            ("Discourse Parsing and Coherence Structure", "Introduces how relationships between clauses and sentences are analyzed to model discourse coherence."),
            ("Topic Modeling with Latent Dirichlet Allocation", "Explains how LDA discovers latent thematic structure in a collection of documents."),
            ("BERT and Masked Language Modeling", "Covers how bidirectional transformer models are pretrained by predicting masked tokens in text."),
            ("Transformer Architecture Fundamentals", "Introduces the encoder-decoder transformer architecture and its self-attention mechanism underlying modern NLP models."),
            ("Byte-Pair Encoding and Subword Tokenization", "Explains how subword tokenization algorithms balance vocabulary size and coverage of rare words."),
            ("Question Answering System Design", "Covers architectures for building systems that extract or generate answers to natural language questions."),
            ("Reading Comprehension Datasets and Models", "Surveys benchmark datasets and models used to evaluate a system's ability to answer questions about a passage."),
            ("Dialogue State Tracking", "Introduces methods for maintaining a structured representation of user goals across a multi-turn conversation."),
            ("Task-Oriented Dialogue Systems", "Covers the components of dialogue systems designed to help users complete specific goals such as booking a flight."),
            ("Open-Domain Dialogue Systems", "Examines the design of conversational agents capable of engaging in unrestricted, general-purpose conversation."),
            ("Text-to-Speech Synthesis Fundamentals", "Introduces the pipeline for converting written text into natural-sounding spoken audio."),
            ("Speaker Diarization Techniques", "Covers methods for determining who spoke when in an audio recording containing multiple speakers."),
            ("Sarcasm and Irony Detection", "Explores computational approaches to detecting sarcastic or ironic intent in text."),
            ("Emotion Detection in Text", "Covers methods for classifying fine-grained emotional states expressed in written language."),
            ("Authorship Attribution and Stylometry", "Introduces statistical techniques for identifying the likely author of a text based on writing style."),
            ("Text Clustering and Document Similarity", "Covers unsupervised methods for grouping documents by content similarity."),
            ("Semantic Textual Similarity Measures", "Explains methods for quantifying how similar in meaning two pieces of text are."),
            ("Knowledge Graph Construction from Text", "Covers techniques for extracting entities and relations from text to populate a structured knowledge graph."),
            ("Event Extraction from Text", "Introduces methods for identifying events, their participants, and their attributes described in text."),
            ("Temporal Expression Extraction and Normalization", "Covers how dates, times, and durations mentioned in text are identified and normalized to a standard format."),
            ("Code-Switching in Multilingual NLP", "Examines the challenges of processing text that mixes multiple languages within a single utterance or document."),
            ("NLP for Low-Resource Languages", "Surveys strategies for building NLP systems for languages with limited annotated data and tooling."),
            ("Prompting and In-Context Learning for NLP Tasks", "Covers how large language models are guided to perform NLP tasks through prompt design rather than fine-tuning."),
            ("Retrieval-Augmented Generation for NLP", "Explains how retrieving external documents at inference time improves the factual grounding of generated text."),
            ("Bias and Fairness in NLP Models", "Examines how NLP models can encode and amplify social biases present in training data, and methods to mitigate them."),
        ],
    },
    "Operations Management": {
        "UG2": [
            ("Total Productive Maintenance (TPM)", "Explains the TPM philosophy of involving all employees in maximizing equipment effectiveness through proactive maintenance."),
            ("Statistical Control Charts: X-bar and R Charts", "Covers how control charts are used to monitor process mean and variability over time to detect special-cause variation."),
            ("Design of Experiments in Process Improvement", "Introduces how structured experiments identify which process factors most affect quality and performance outcomes."),
            ("Facility Layout Design Strategies", "Compares process, product, and cellular layout strategies for arranging production facilities efficiently."),
            ("Assembly Line Balancing", "Covers methods for distributing tasks across workstations to minimize idle time and maximize line efficiency."),
            ("Make-or-Buy Decision Analysis", "Explains the cost, capability, and strategic factors organizations weigh when deciding to produce internally or outsource."),
            ("The Bullwhip Effect in Supply Chains", "Examines how small demand fluctuations amplify into larger swings in orders and inventory upstream in a supply chain."),
            ("Sales and Operations Planning (S&OP)", "Covers the cross-functional process for aligning demand forecasts with production, inventory, and financial plans."),
            ("Six Sigma DMAIC Methodology", "Introduces the Define-Measure-Analyze-Improve-Control cycle used to systematically reduce process defects."),
            ("Warehouse Slotting and Pick Path Optimization", "Explains how product placement and pick routing are optimized to minimize travel time and improve fulfillment speed."),
        ],
    },
    "Philosophy": {
        "UG2": [
            ("Aesthetics: Theories of Beauty and Artistic Value", "Surveys philosophical accounts of what makes something beautiful and how artistic value is judged."),
            ("The Problem of Evil and Theodicy", "Examines the philosophical challenge posed by the existence of suffering to belief in an all-good, all-powerful deity."),
            ("Religious Pluralism and Exclusivism", "Compares philosophical positions on whether multiple religious traditions can offer equally valid paths to truth."),
            ("American Pragmatism: Peirce, James, and Dewey", "Introduces the pragmatist tradition's emphasis on the practical consequences of beliefs as a criterion of meaning and truth."),
            ("Foucault and the Analysis of Power", "Examines Michel Foucault's account of how power operates through institutions, knowledge, and discourse."),
            ("Derrida and Deconstruction", "Introduces Jacques Derrida's method of deconstruction and its critique of stable meaning in texts."),
            ("Animal Ethics and Moral Status", "Examines philosophical arguments about whether and why animals deserve moral consideration."),
            ("Just War Theory", "Surveys the criteria traditionally used to evaluate the moral justification for entering and conducting war."),
            ("Bioethics: Autonomy, Beneficence, and Informed Consent", "Introduces core principles used to reason through ethical dilemmas in medical practice and research."),
            ("Advaita Vedanta and Non-Dualism", "Introduces the Hindu philosophical school teaching the fundamental non-duality of the individual self and ultimate reality."),
            ("Daoism: Wu Wei and the Dao De Jing", "Examines the classical Chinese philosophical tradition centered on effortless action and alignment with the Dao."),
            ("Legalism in Classical Chinese Political Thought", "Surveys the Legalist school's emphasis on strict law, statecraft, and centralized authority in governance."),
            ("Ubuntu Philosophy and African Communitarian Ethics", "Introduces the African philosophical concept emphasizing personhood as constituted through community relationships."),
            ("Philosophy of Economics: Rational Choice Theory", "Examines the assumptions and critiques of modeling human decision-making as rational utility maximization."),
            ("Informal Logical Fallacies", "Surveys common patterns of flawed reasoning in everyday argument, such as ad hominem and false dilemma."),
        ],
    },
    "Physical Education & Self-Defense": {
        "UG2": [
            ("Olympic Weightlifting Technique and Programming", "Covers the technical execution and periodized training of the snatch and clean-and-jerk lifts."),
            ("Long-Term Athlete Development Models", "Introduces frameworks for structuring athletic training appropriately across different stages of physical maturation."),
            ("Krav Maga Principles for Practical Self-Defense", "Examines the core principles of this reality-based self-defense system focused on efficient threat neutralization."),
            ("Yoga and Mind-Body Integration in Fitness", "Explores how yoga practice contributes to flexibility, strength, and stress regulation within a fitness program."),
            ("Aquatic Exercise and Swimming Pedagogy", "Covers principles of teaching swimming skills and designing water-based exercise programs."),
        ],
    },
    "Physics": {
        "UG2": [
            ("General Relativity: Einstein's Field Equations", "Introduces how mass and energy curve spacetime according to Einstein's field equations."),
            ("Gravitational Waves and Their Detection", "Explains the origin of ripples in spacetime and the interferometric methods used to detect them."),
            ("Dark Matter and Dark Energy", "Surveys the observational evidence for unseen matter and the accelerating expansion of the universe."),
            ("Cosmological Inflation Theory", "Introduces the proposed period of rapid exponential expansion in the early universe and its observational support."),
            ("Superconductivity: Theory and Applications", "Covers the phenomenon of zero electrical resistance below a critical temperature and its practical applications."),
            ("Neutrino Physics and Oscillations", "Explains the properties of neutrinos and how flavor oscillation reveals that neutrinos have mass."),
            ("Introduction to String Theory", "Introduces the theoretical framework modeling fundamental particles as vibrating one-dimensional strings."),
            ("Crystal Structure and X-ray Diffraction", "Covers how the periodic arrangement of atoms in crystals is determined using X-ray diffraction patterns."),
            ("Topological Insulators and Quantum Materials", "Introduces materials that conduct electricity on their surface while insulating in their interior."),
            ("The Three-Body Problem in Celestial Mechanics", "Examines the chaotic dynamics that arise when three gravitating bodies interact, defying a general closed-form solution."),
            ("Non-Equilibrium Statistical Mechanics", "Extends statistical mechanics to systems that are not in thermodynamic equilibrium, including transport phenomena."),
        ],
    },
    "Project Management": {
        "UG2": [
            ("PRINCE2 Methodology Fundamentals", "Introduces the process-based PRINCE2 project management framework and its defined stages and roles."),
            ("Critical Chain Project Management", "Covers how this scheduling method manages resource constraints and buffers to protect project completion dates."),
            ("Scaling Agile: SAFe and LeSS Frameworks", "Compares frameworks for coordinating agile practices across multiple teams in large organizations."),
            ("Project Charter Development", "Explains how a project charter formally authorizes a project and defines its objectives, scope, and sponsor."),
            ("Scope Statement and Deliverables Definition", "Covers how a detailed scope statement clarifies project boundaries and expected deliverables."),
            ("Milestone Planning and Tracking", "Introduces how key milestones are identified and tracked to monitor overall project progress."),
            ("Schedule Compression: Fast Tracking and Crashing", "Compares techniques for shortening a project schedule by overlapping activities or adding resources."),
            ("Vendor Performance Management", "Covers how organizations monitor and evaluate supplier and contractor performance throughout a project."),
            ("Contract Closeout Procedures", "Explains the formal steps for verifying deliverables and completing contractual obligations at project end."),
            ("Project Governance Frameworks", "Introduces the structures and decision rights that guide oversight and accountability throughout a project's lifecycle."),
            ("Benefits Realization Management", "Covers how organizations track whether a project's intended business benefits are actually achieved after delivery."),
            ("Stakeholder Engagement Assessment Matrix", "Explains how stakeholders' current and desired engagement levels are mapped to guide communication strategy."),
            ("Project Management Software Tools and Selection", "Surveys criteria for evaluating and selecting software platforms to support project planning and tracking."),
            ("Design Thinking Applications in Project Management", "Explores how human-centered design thinking techniques can be applied to project scoping and problem-solving."),
            ("DevOps Integration in Project Delivery", "Examines how continuous integration and delivery practices are incorporated into modern project management."),
            ("Ethics and Professional Responsibility in Project Management", "Covers the ethical obligations project managers have toward stakeholders, sponsors, and the profession."),
            ("Knowledge Transfer and Documentation Management", "Explains practices for capturing and transferring project knowledge to avoid loss when team members change."),
            ("Project Team Motivation Theories", "Surveys motivation theories and their application to keeping project teams engaged and productive."),
            ("Configuration Management in Projects", "Covers how project deliverables and technical baselines are controlled and tracked as they evolve."),
        ],
    },
    "Prompt Engineering": {
        "UG2": [
            ("Prompt Engineering for Text-to-Image Generation", "Covers techniques for crafting prompts that guide diffusion and other text-to-image models toward desired visual outputs."),
            ("Negative Prompting Techniques", "Explains how specifying undesired elements in a prompt steers generative models away from unwanted outputs."),
            ("Prompt Compression Techniques", "Covers methods for shortening prompts while preserving task-relevant information to reduce token usage."),
            ("Synthetic Data Generation via Prompting", "Explores how prompts are designed to generate labeled synthetic training data for downstream model development."),
            ("Prompt Engineering for Voice Assistant Interfaces", "Examines how prompt design adapts for spoken, turn-based interactions with voice-driven AI assistants."),
            ("Prompt Engineering for Legal and Compliance Document Review", "Covers prompt strategies for guiding models to accurately review and flag issues in legal and compliance documents."),
        ],
    },
    "Python": {
        "UG2": [
            ("Abstract Base Classes and the abc Module", "Explains how abstract base classes define required interfaces that subclasses must implement."),
            ("Descriptors and the Descriptor Protocol", "Covers how the __get__, __set__, and __delete__ methods let objects customize attribute access."),
            ("Using __slots__ for Memory Optimization", "Explains how __slots__ reduces per-instance memory overhead by restricting dynamic attribute creation."),
            ("Typing Protocols and Structural Subtyping", "Covers how typing.Protocol enables structural, duck-typing-friendly static type checks in Python."),
            ("Socket Programming Fundamentals in Python", "Introduces the socket module for building low-level network client and server applications."),
            ("Working with XML Using ElementTree", "Covers parsing, navigating, and generating XML documents with Python's ElementTree module."),
            ("Scientific Computing with SciPy", "Introduces SciPy's tools for optimization, integration, interpolation, and linear algebra built on NumPy."),
        ],
    },
    "R": {
        "UG2": [
            ("Principal Component Analysis in R", "Covers how to perform and interpret dimensionality reduction using PCA in R."),
            ("Random Forests with the randomForest Package", "Explains how to train and evaluate random forest models for classification and regression in R."),
            ("Network Analysis with igraph", "Introduces graph and network data structures and analysis using the igraph package in R."),
            ("Reproducible Environments with renv", "Covers how the renv package manages project-specific package dependencies for reproducible R analyses."),
            ("Interactive Visualization with plotly in R", "Explains how to build interactive, web-ready charts in R using the plotly package."),
            ("Web Scraping with rvest", "Covers how to extract data from web pages into R data structures using the rvest package."),
            ("Multivariate Statistical Analysis in R", "Introduces techniques such as multivariate ANOVA and factor analysis for analyzing multiple related variables in R."),
        ],
    },
    "Science": {
        "UG2": [
            ("Atomic Structure and Periodic Trends", "Covers electron configuration and how periodic trends such as atomic radius and electronegativity arise from it."),
            ("Chemical Bonding: Ionic and Covalent", "Explains how atoms form ionic and covalent bonds and how bond type influences compound properties."),
            ("Acid-Base Chemistry and pH", "Introduces acid-base theories and how pH quantifies the concentration of hydrogen ions in solution."),
            ("Organic Chemistry: Functional Groups", "Surveys the major functional groups in organic molecules and how they determine chemical reactivity."),
            ("Thermochemistry and Enthalpy", "Covers how energy changes in chemical reactions are measured and predicted using enthalpy."),
            ("Electrochemistry and Redox Reactions", "Explains oxidation-reduction reactions and their application in batteries and electrolysis."),
            ("Population Ecology and Carrying Capacity", "Introduces models of population growth and the environmental limits that constrain population size."),
            ("Ecosystem Energy Flow and Food Webs", "Covers how energy moves through trophic levels in an ecosystem and how food webs represent these relationships."),
            ("Biodiversity and Conservation Biology", "Surveys the science of measuring biodiversity and the strategies used to conserve threatened species and habitats."),
            ("Photosynthesis and Plant Physiology", "Explains the biochemical process by which plants convert light energy into chemical energy."),
            ("Animal Behavior and Ethology", "Introduces the scientific study of animal behavior, including instinct, learning, and social behavior."),
            ("Mendelian Genetics and Inheritance Patterns", "Covers the principles of dominant and recessive inheritance established through Mendel's experiments."),
            ("Microbiology: Bacteria and Viruses", "Surveys the structure, classification, and reproduction of bacteria and viruses."),
            ("Forensic Science Methods and Techniques", "Introduces scientific methods used to analyze physical evidence in criminal investigations."),
            ("Sleep Science and Circadian Rhythms", "Explores the biological mechanisms regulating sleep cycles and the effects of circadian disruption on health."),
        ],
    },
    "Social Studies": {
        "UG2": [
            ("Sociology of Sport and Athletic Institutions", "Examines how sport reflects and shapes social structures such as class, gender, and national identity."),
            ("Digital Society and Internet Culture", "Explores how digital technology and online communities are reshaping social interaction and identity."),
            ("Rural Sociology and Agrarian Communities", "Studies the social structures, economies, and change processes characteristic of rural and agrarian communities."),
            ("Consumer Culture and Consumption Studies", "Examines how consumption patterns reflect and construct identity, status, and social meaning."),
        ],
    },
    "Survival Skills": {
        "UG2": [
            ("Edible and Poisonous Plant Identification for Foraging", "Covers how to distinguish safe wild edible plants from toxic look-alikes using key botanical identification features."),
            ("Earthquake Preparedness and Structural Safety Response", "Explains how to assess structural collapse risk and respond safely during and immediately after seismic events."),
            ("Tsunami Warning Systems and Coastal Evacuation", "Covers how tsunami detection and warning systems work and how coastal communities plan rapid evacuation routes."),
            ("Maritime Survival: Life Raft Procedures and Open-Water Rescue", "Introduces the procedures for abandoning ship, deploying life rafts, and surviving until rescue in open water."),
            ("Cave and Karst Environment Safety Practices", "Covers the hazards specific to caving, including navigation, air quality, and rope safety in subterranean environments."),
            ("Self-Rescue Techniques for Falling Through Ice", "Explains the specific techniques for self-extraction and preventing hypothermia after breaking through ice on a frozen body of water."),
            ("Volcanic Hazard Awareness and Ashfall Safety", "Surveys the risks posed by volcanic eruptions, including pyroclastic flows and ashfall, and appropriate protective responses."),
        ],
    },
    "UI/UX Design": {
        "UG2": [
            ("Contextual Inquiry and Ethnographic Field Research", "Covers how designers observe and interview users in their natural environment to uncover unarticulated needs."),
            ("Persona Development and Empathy Mapping", "Explains how research data is synthesized into representative user personas and empathy maps to guide design decisions."),
            ("Affinity Diagramming for Qualitative Research Synthesis", "Introduces the technique of clustering qualitative research notes into themes to surface design insights."),
            ("Tree Testing for Information Architecture Validation", "Covers how tree testing evaluates whether users can find content within a proposed navigation hierarchy."),
            ("Service Blueprinting for End-to-End Experience Design", "Explains how service blueprints map front-stage user actions to back-stage processes across a complete service experience."),
            ("A/B Testing Methodology for Interface Optimization", "Introduces the statistical design and interpretation of controlled experiments comparing interface variants."),
            ("UX Writing and Microcopy Principles", "Covers how concise, purposeful interface text guides users and reduces confusion at key decision points."),
            ("DesignOps: Scaling Design Practice in Organizations", "Examines how design operations coordinate tools, processes, and staffing to scale design work across an organization."),
            ("Emotional Design: Visceral, Behavioral, and Reflective Levels", "Introduces Don Norman's model for how products evoke emotional responses at immediate, functional, and reflective levels."),
            ("Designing for Neurodiversity and Cognitive Accessibility", "Explores interface design considerations that support users with ADHD, dyslexia, autism, and other cognitive differences."),
            ("Gamification and Behavioral Design Patterns", "Covers how game-like elements such as points, badges, and progress indicators are used to motivate user behavior."),
            ("Augmented Reality and Spatial Interface Design", "Introduces the design considerations for interfaces overlaid on physical space in augmented reality applications."),
            ("Growth Design and Retention-Focused UX Patterns", "Examines interface patterns aimed at improving user activation, retention, and long-term product engagement."),
            ("Usability Benchmarking Across Product Versions", "Covers how standardized usability metrics are tracked over successive product releases to measure improvement."),
            ("Design Research Repository and Insight Management", "Explains how organizations organize and archive past research findings to make design insights reusable across teams."),
        ],
    },
    "Web Development": {
        "UG2": [
            ("Vue.js Fundamentals for Web Applications", "Introduces the Vue.js framework's reactive data binding and component model for building web interfaces."),
            ("Progressive Web Apps and Service Worker Architecture", "Covers how service workers enable offline functionality, caching, and installability for progressive web apps."),
            ("WebSockets for Real-Time Bidirectional Communication", "Explains how the WebSocket protocol maintains a persistent, full-duplex connection between browser and server."),
            ("Core Web Vitals and Web Performance Metrics", "Introduces the standardized metrics used to measure loading, interactivity, and visual stability of web pages."),
            ("Responsive Image Optimization Techniques", "Covers how srcset, picture elements, and modern formats deliver appropriately sized images across devices."),
            ("Static Site Generators and JAMstack Architecture", "Explains how pre-built static sites paired with APIs and client-side JavaScript improve performance and security."),
            ("Containerizing Web Applications with Docker", "Introduces how Docker packages a web application and its dependencies into a portable, reproducible container."),
            ("WebRTC for Peer-to-Peer Communication", "Covers how WebRTC enables direct browser-to-browser audio, video, and data communication without a relay server."),
            ("Internationalization (i18n) for Web Applications", "Explains how web applications are structured to support multiple languages, locales, and text directions."),
            ("CSS Animations and Transitions", "Covers how CSS keyframes and transition properties are used to animate interface elements without JavaScript."),
            ("Web Workers for Background Script Execution", "Introduces how Web Workers run JavaScript on background threads to keep the main UI thread responsive."),
            ("The Critical Rendering Path and Browser Performance", "Explains the sequence of steps browsers take to convert HTML, CSS, and JavaScript into rendered pixels."),
            ("API Versioning Strategies for Web Services", "Covers approaches for evolving a web API over time without breaking existing client integrations."),
            ("HTTP/2 and HTTP/3 Protocol Fundamentals", "Introduces the performance improvements that multiplexing and QUIC bring over the original HTTP/1.1 protocol."),
            ("DNS Fundamentals for Web Application Deployment", "Explains how domain name resolution routes requests to a deployed web application's hosting infrastructure."),
            ("Web3 and Blockchain-Based Application Fundamentals", "Introduces how decentralized applications interact with blockchain networks through wallets and smart contracts."),
        ],
    },
    "World History": {
        "UG2": [
            ("Ancient Egypt: Old, Middle, and New Kingdoms", "Surveys the political and cultural development of ancient Egyptian civilization across its major dynastic periods."),
            ("Classical Athens and the Origins of Democracy", "Examines the political institutions and civic practices that gave rise to direct democracy in ancient Athens."),
            ("The Achaemenid Persian Empire", "Studies the administrative and cultural achievements of the first Persian Empire under rulers such as Cyrus and Darius."),
            ("The Punic Wars and Roman Expansion", "Covers the series of wars between Rome and Carthage that established Roman dominance in the western Mediterranean."),
            ("The Roman Empire: Pax Romana and Imperial Administration", "Examines the governance structures that sustained two centuries of relative peace and stability across the Roman Empire."),
            ("The Viking Age and Norse Expansion", "Surveys Norse seafaring, raiding, and settlement across Europe and the North Atlantic during the Viking Age."),
            ("The Crusades: Causes and Consequences", "Examines the religious, political, and economic motivations behind the Crusades and their lasting effects on Europe and the Middle East."),
            ("The Ottoman Empire: Rise and Imperial Administration", "Covers the expansion and governing institutions of the Ottoman Empire across three continents."),
            ("The Mughal Empire in South Asia", "Studies the political consolidation, culture, and architecture of Mughal rule on the Indian subcontinent."),
            ("The Ming and Qing Dynasties: Chinese Imperial Governance", "Surveys the bureaucratic and cultural institutions that sustained centuries of dynastic rule in late imperial China."),
            ("The Protestant Reformation and Religious War in Europe", "Examines the religious schism initiated by reformers such as Luther and its consequences for European political order."),
            ("The Thirty Years' War and the Peace of Westphalia", "Covers the devastating pan-European conflict and the treaty that established the modern concept of state sovereignty."),
            ("The American Revolution and Its Global Repercussions", "Examines the causes of the American Revolution and its influence on subsequent revolutionary movements worldwide."),
            ("The Haitian Revolution and the End of Slavery", "Studies the only successful large-scale slave revolt that established Haiti as an independent nation."),
            ("Simon Bolivar and Latin American Wars of Independence", "Surveys the movements led by figures such as Bolivar that ended Spanish colonial rule across South America."),
            ("The Scramble for Africa and the Berlin Conference", "Examines how European powers partitioned African territory in the late nineteenth century with little regard for existing societies."),
            ("The Chinese Communist Revolution and Mao Zedong", "Covers the political and social forces that brought the Chinese Communist Party to power in 1949."),
            ("The Space Race and Cold War Technological Competition", "Examines how superpower rivalry drove competing space programs as a symbol of Cold War prestige and capability."),
            ("The End of the Cold War and the Fall of the Berlin Wall", "Studies the political and economic pressures that led to the collapse of Soviet influence in Eastern Europe."),
        ],
    },
    "World Literature": {
        "UG2": [
            ("Beowulf and the Old English Heroic Epic Tradition", "Examines the themes of heroism, fate, and monstrous adversaries in the foundational Old English epic poem."),
            ("Alexander Pushkin and the Founding of Modern Russian Literature", "Introduces how Pushkin's poetry and prose established a literary language and tradition for later Russian writers."),
            ("Naguib Mahfouz and the Modern Arabic Novel", "Surveys how Mahfouz's fiction chronicles the social transformation of twentieth-century Cairo and Egyptian society."),
            ("Chinua Achebe and the African Novel of Colonial Encounter", "Examines how Achebe's fiction portrays the disruption of traditional African society under colonial pressure."),
            ("Milan Kundera and Central European Literature of Exile and Totalitarianism", "Explores how Kundera's fiction examines memory, identity, and personal freedom under totalitarian political systems."),
            ("Haruki Murakami and Contemporary Japanese Fiction", "Surveys how Murakami's novels blend everyday realism with surreal and dreamlike narrative elements."),
        ],
    },
}
