MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "ICT & Computer Science": {
        "UG3": [
            ("Formal Methods: Model Checking and Verification", "Introduces model checking techniques used to formally verify that software and hardware systems satisfy specified correctness properties."),
            ("Static Program Analysis Techniques", "Covers compile-time analysis methods for detecting bugs, security flaws, and code quality issues without executing a program."),
            ("Software-Defined Storage Systems", "Examines how storage infrastructure is abstracted and managed through software independent of underlying hardware."),
            ("Federated Learning Systems Architecture", "Explores the distributed system design behind training machine learning models across decentralized devices without centralizing raw data."),
            ("Digital Twin Technology in ICT Systems", "Studies how virtual replicas of physical systems are built and synchronized in real time for monitoring and simulation."),
            ("Zero Trust Network Architecture Principles", "Covers the security model that requires continuous verification of every user and device rather than assuming trust within a network perimeter."),
            ("Data Deduplication and Storage Compression Techniques", "Explains algorithms used to eliminate redundant data and reduce storage footprint in enterprise systems."),
            ("Bioinformatics Database Systems", "Introduces specialized database structures used to store, query, and manage large-scale biological and genomic datasets."),
            ("Green Computing and Energy-Efficient System Design", "Examines strategies for reducing the energy consumption and environmental impact of computing hardware and data centers."),
        ],
    },
    "Islamic Studies": {
        "UG3": [
            ("The Barelvi-Deobandi Divide in South Asian Islam", "Examines the theological and social origins of two major reformist movements within South Asian Sunni Islam."),
            ("Zaydi Shia Tradition in Yemen", "Surveys the distinct legal and theological positions of Zaydism as practiced historically and today in Yemen."),
            ("Ibadi Islam and Omani Religious Identity", "Explores the history and doctrines of the Ibadi school and its enduring role in Omani religious life."),
            ("The Almohad and Almoravid Dynasties of North Africa", "Studies the rise, religious ideology, and governance of these two Berber Islamic dynasties in medieval North Africa and Iberia."),
            ("Sokoto Caliphate and Islamic Reform in West Africa", "Covers the founding of the Sokoto Caliphate and its role in Islamic revivalist movements in West Africa."),
            ("The Barmakid Family and Abbasid Court Administration", "Examines the influential Barmakid viziers and their role in shaping early Abbasid statecraft and patronage."),
            ("Islamic Numismatics and Coinage History", "Studies the development of Islamic coinage as a source for understanding political authority and economic history."),
            ("The Cairo Genizah Documents and Jewish-Muslim Interactions", "Explores how a cache of medieval documents illuminates everyday relations between Jewish and Muslim communities."),
            ("Islamic Legal Maxims (Al-Qawa'id al-Fiqhiyyah)", "Introduces the concise legal principles jurists use to derive rulings across diverse cases in Islamic law."),
            ("The Hanbali School of Jurisprudence", "Surveys the origins, methodology, and geographic spread of the Hanbali legal school."),
            ("The Maliki School of Jurisprudence in North and West Africa", "Examines the distinctive sources and regional development of Maliki law across North and West Africa."),
            ("Islamic Codicology and Manuscript Preservation", "Covers the study of physical manuscript production and the techniques used to preserve historic Islamic texts."),
            ("Sufi Metaphysics: Ibn Arabi's Wahdat al-Wujud", "Introduces the doctrine of the oneness of being as articulated by the influential mystic Ibn Arabi."),
            ("Andalusian Muslim Intellectual Networks", "Studies the scholarly exchange and institutions that connected Muslim thinkers across Islamic Spain."),
            ("Da'wah Methodology in Contemporary Contexts", "Examines modern approaches to religious outreach and their adaptation to diverse global audiences."),
        ],
    },
    "JavaScript": {
        "UG3": [
            ("Currying and Partial Application in JavaScript", "Explores techniques for transforming functions into sequences of single-argument calls to improve reuse and composition."),
            ("The Temporal API for Date and Time Handling", "Introduces the modern JavaScript API designed to replace the legacy Date object for precise date and time manipulation."),
            ("JavaScript Symbol Type and Well-Known Symbols", "Covers the unique primitive type and the built-in symbols that customize object behavior in JavaScript."),
            ("Tagged Template Literals", "Explains how functions can process template literals to build custom string processing utilities."),
            ("Structured Clone Algorithm and Deep Copying", "Examines how the browser's structured clone algorithm enables deep copying of complex JavaScript values."),
            ("Intersection Observer API for Lazy Rendering", "Covers how to efficiently detect element visibility to implement lazy loading and scroll-based effects."),
            ("Mutation Observer API for DOM Change Detection", "Explores how to observe and react to changes in the DOM tree without manual polling."),
            ("AbortController and Cancellable Fetch Requests", "Explains how to cancel in-flight network requests and other asynchronous operations using the AbortController interface."),
            ("BigInt and Arbitrary-Precision Arithmetic in JavaScript", "Introduces the BigInt primitive for performing precise calculations on integers beyond the safe number range."),
            ("Import Maps and Native Module Resolution", "Covers how import maps let browsers resolve bare module specifiers without a bundler."),
        ],
    },
    "MBA": {
        "UG3": [
            ("Zero-Based Budgeting for Corporate Cost Control", "Examines a budgeting approach that requires every expense to be justified from a zero base each period."),
            ("Balanced Scorecard Strategy Implementation", "Covers the framework managers use to translate strategy into measurable objectives across financial and non-financial perspectives."),
            ("Strategic Portfolio Analysis: BCG and GE Matrices", "Introduces classic portfolio planning tools used to allocate resources across a firm's business units."),
            ("Leveraged Buyouts and Private Equity Strategy", "Explores how private equity firms structure debt-financed acquisitions to generate investment returns."),
            ("Venture Capital Deal Structuring", "Examines how venture financing rounds are negotiated, valued, and structured between founders and investors."),
            ("Corporate Turnaround and Restructuring Strategy", "Covers the diagnostic and strategic steps managers use to revive underperforming or distressed companies."),
            ("Knowledge Economy Workforce Transition Strategy", "Studies how organizations manage workforce shifts from industrial to knowledge-based roles."),
            ("Executive Compensation Design and Say-on-Pay", "Examines how boards structure executive pay packages and respond to shareholder votes on compensation."),
            ("International Joint Ventures and Equity Alliances", "Covers the strategic and governance considerations of forming cross-border equity partnerships."),
            ("Nonmarket Strategy and Corporate Political Activity", "Explores how firms manage relationships with regulators, governments, and public stakeholders."),
            ("Behavioral Operations and Managerial Biases", "Examines how cognitive biases affect operational decision-making in forecasting, inventory, and scheduling."),
            ("Customer Lifetime Value Modeling for Strategic Planning", "Covers quantitative approaches to estimating long-term customer value to guide strategic investment decisions."),
            ("Scenario Planning for Strategic Foresight", "Introduces structured techniques for envisioning multiple plausible futures to inform long-range strategy."),
        ],
    },
    "Machine Learning": {
        "UG3": [
            ("Variational Autoencoders for Generative Modeling", "Introduces a probabilistic neural architecture that learns compressed latent representations for generating new data."),
            ("Normalizing Flows for Density Estimation", "Covers invertible transformations that model complex probability distributions from simple base densities."),
            ("Diffusion Models for Image Generation", "Explores generative models that learn to reverse a gradual noising process to synthesize realistic images."),
            ("Graph Neural Networks Fundamentals", "Introduces neural architectures designed to learn representations directly from graph-structured data."),
            ("Graph Convolutional Networks for Node Classification", "Examines how convolutional operations are adapted to graphs to classify nodes using neighborhood information."),
            ("Spectral Clustering Techniques", "Covers clustering methods that use eigenvalues of similarity matrices to identify structure in data."),
            ("Gaussian Processes for Regression", "Introduces a probabilistic, non-parametric approach to regression that models distributions over functions."),
            ("Kernel Methods and the Kernel Trick", "Explores how kernel functions allow linear algorithms to model nonlinear relationships without explicit feature mapping."),
            ("Online Learning and Regret Minimization", "Covers algorithms that update models incrementally and are evaluated by their cumulative regret over time."),
            ("Multi-Armed Bandit Algorithms", "Introduces strategies for balancing exploration and exploitation when sequentially choosing among uncertain options."),
            ("Contextual Bandits for Personalization", "Extends bandit algorithms with contextual features to support personalized recommendation and decision systems."),
            ("Actor-Critic Methods in Reinforcement Learning", "Examines reinforcement learning algorithms that combine value estimation and policy optimization."),
            ("Model-Based Reinforcement Learning", "Covers approaches where agents learn an internal model of the environment to plan future actions."),
            ("Inverse Reinforcement Learning", "Introduces techniques for inferring an agent's reward function by observing expert behavior."),
            ("Imitation Learning and Behavioral Cloning", "Explores methods for training agents to mimic demonstrated behavior instead of learning from reward signals alone."),
            ("Anomaly Detection Techniques", "Covers statistical and machine learning methods for identifying rare or unusual patterns in data."),
            ("One-Class Classification for Outlier Detection", "Examines classification methods trained on a single class to flag deviations as outliers."),
            ("Time Series Forecasting with Machine Learning", "Introduces machine learning approaches for predicting future values in sequential and temporal data."),
            ("Survival Analysis in Machine Learning", "Covers techniques for modeling time-to-event data and censored observations using machine learning."),
            ("Semi-Supervised Learning Methods", "Explores techniques that combine small labeled datasets with larger unlabeled datasets to improve model performance."),
            ("Active Learning Query Strategies", "Examines methods for selecting the most informative unlabeled examples to label in order to improve models efficiently."),
            ("Federated Learning Fundamentals", "Introduces a distributed training paradigm where models learn across decentralized devices without sharing raw data."),
            ("Differential Privacy in Machine Learning", "Covers mathematical guarantees and techniques for protecting individual data privacy during model training."),
            ("Adversarial Robustness and Adversarial Training", "Explores methods for defending machine learning models against inputs deliberately crafted to cause errors."),
            ("Neural Ordinary Differential Equations", "Introduces a class of models that parameterize the continuous dynamics of hidden states using differential equations."),
            ("Capsule Networks", "Covers a neural architecture designed to preserve hierarchical spatial relationships between features."),
            ("Siamese Networks for Similarity Learning", "Examines twin neural network architectures trained to measure similarity between paired inputs."),
            ("Multi-Modal Representation Learning", "Explores techniques for learning joint representations across different data modalities such as text and images."),
            ("Ranking and Learning-to-Rank Algorithms", "Introduces machine learning approaches specifically designed to order items by relevance, as used in search and recommendation."),
        ],
    },
    "Math": {
        "UG3": [
            ("Galois Theory and Solvability of Polynomials", "Introduces the correspondence between field extensions and group theory used to determine when polynomial equations are solvable by radicals."),
            ("Algebraic Topology: Fundamental Groups", "Covers how algebraic invariants like the fundamental group classify topological spaces up to continuous deformation."),
            ("Homology and Cohomology Theory", "Introduces algebraic tools that assign sequences of groups to topological spaces to detect holes and structure."),
            ("Functional Analysis: Banach and Hilbert Spaces", "Examines infinite-dimensional vector spaces equipped with norms and inner products central to modern analysis."),
            ("Spectral Theory of Operators", "Covers the generalization of eigenvalues and eigenvectors to linear operators on infinite-dimensional spaces."),
            ("Stochastic Calculus and Ito's Lemma", "Introduces calculus for stochastic processes and the key formula used to differentiate functions of random paths."),
            ("Markov Chains: Steady-State Analysis", "Examines how transition probabilities determine the long-run stationary behavior of Markov chains."),
            ("Variational Calculus and Euler-Lagrange Equations", "Covers methods for finding functions that extremize integral quantities, foundational to physics and optimization."),
            ("Numerical Linear Algebra: Iterative Solvers", "Introduces iterative methods for solving large sparse systems of linear equations efficiently."),
            ("Combinatorial Design Theory", "Explores the construction and properties of balanced arrangements such as block designs and Latin squares."),
            ("Ramsey Theory Fundamentals", "Introduces the study of conditions under which order must appear within sufficiently large mathematical structures."),
            ("Diophantine Equations", "Covers techniques for finding integer solutions to polynomial equations."),
            ("Algebraic Geometry: Varieties and Schemes", "Introduces the study of geometric objects defined by polynomial equations and their modern scheme-theoretic generalization."),
            ("Mathematical Statistics: Sufficient Statistics and Estimation Theory", "Examines the theoretical foundations of statistical estimation, including sufficiency, efficiency, and optimality criteria."),
        ],
    },
    "Music": {
        "UG3": [
            ("Twelve-Tone Serialism and Schoenberg's Method", "Introduces the compositional technique that organizes pitch using ordered rows of the twelve chromatic tones."),
            ("Minimalism in Music: Reich, Glass, and Riley", "Examines the repetitive, phase-based compositional techniques that defined the American minimalist movement."),
            ("Spectral Music and Timbre-Based Composition", "Explores a compositional approach that treats the acoustic properties of sound itself as the basis for musical structure."),
            ("Gamelan Music of Indonesia", "Surveys the ensemble traditions, tuning systems, and cultural functions of Indonesian gamelan music."),
            ("West African Drumming Traditions", "Examines the rhythmic structures, instruments, and social roles of drumming traditions across West Africa."),
            ("Flamenco Music: Structure and Cultural Roots", "Studies the musical forms, guitar technique, and cultural history of Andalusian flamenco."),
            ("Klezmer Music and Jewish Musical Traditions", "Introduces the instrumental folk music tradition of Ashkenazi Jewish communities and its revival."),
            ("Choral Conducting Techniques", "Covers the gestural, rehearsal, and interpretive skills specific to leading vocal ensembles."),
            ("Improvisation Pedagogy in Music Education", "Examines methods for teaching musical improvisation skills across instrumental and vocal contexts."),
            ("Film Sound Design Beyond Score", "Explores how sound effects, ambience, and mixing work alongside music to shape cinematic storytelling."),
            ("Electroacoustic Music Composition", "Introduces compositional techniques that combine acoustic instruments with electronically generated or processed sound."),
            ("Music Cognition and Perception", "Examines how the human brain processes pitch, rhythm, and musical structure."),
            ("Historical Temperament and Tuning Systems", "Covers the evolution of tuning systems from just intonation to equal temperament and their musical implications."),
            ("Ethnomusicology of Diaspora Communities", "Studies how musical traditions transform and persist among migrant and diaspora populations."),
        ],
    },
    "Natural Language Processing": {
        "UG3": [
            ("Discourse Parsing and Rhetorical Structure Theory", "Introduces methods for analyzing how sentences and clauses combine into coherent discourse structures."),
            ("Text Summarization: Extractive Methods", "Covers algorithms that generate summaries by selecting and combining representative sentences from source text."),
            ("Abstractive Summarization with Sequence Models", "Examines neural sequence-to-sequence approaches that generate novel summary text rather than copying source sentences."),
            ("Dialogue State Tracking in Conversational Systems", "Explores techniques for maintaining an accurate representation of user intent and context across a conversation."),
            ("Sarcasm and Irony Detection in Text", "Introduces computational approaches for identifying sarcastic or ironic intent in written language."),
            ("Code-Switching in Multilingual NLP", "Covers the challenges and techniques for processing text that alternates between multiple languages."),
            ("Morphological Analysis and Finite-State Transducers", "Examines how finite-state methods model word formation and inflection across languages."),
            ("Word Sense Disambiguation Techniques", "Introduces methods for determining which meaning of an ambiguous word is intended in context."),
            ("Semantic Role Labeling", "Covers techniques for identifying the predicate-argument structure that describes who did what to whom in a sentence."),
            ("Text Simplification for Accessibility", "Explores automated methods for rewriting complex text to improve readability and accessibility."),
            ("Low-Resource Language NLP Techniques", "Examines strategies for building effective NLP systems for languages with limited training data."),
            ("Speech Emotion Recognition", "Introduces methods for detecting emotional states from acoustic and prosodic features of spoken language."),
            ("NLP for Historical and Archival Text Analysis", "Covers techniques adapted for processing noisy, non-standardized historical documents and manuscripts."),
        ],
    },
    "Operations Management": {
        "UG3": [
            ("Theory of Constraints and Drum-Buffer-Rope Scheduling", "Introduces a management philosophy that focuses improvement efforts on a system's limiting bottleneck resource."),
            ("Cellular Manufacturing Layout Design", "Covers how machines and workstations are grouped into cells to streamline production of similar parts."),
            ("Cross-Docking Strategies in Distribution", "Examines how goods are transferred directly between inbound and outbound transport with minimal storage."),
            ("Milk-Run Logistics and Route Consolidation", "Introduces a distribution strategy that consolidates multiple pickups or deliveries into a single efficient route."),
            ("Kanban Card Systems in Pull Production", "Covers the visual signaling method used to trigger replenishment and control work-in-process inventory."),
            ("Overall Equipment Effectiveness (OEE) Measurement", "Examines the metric used to assess availability, performance, and quality of manufacturing equipment."),
            ("Statistical Process Control Charts", "Introduces control charts used to monitor process stability and detect variation over time."),
            ("Process Capability Analysis (Cp, Cpk)", "Covers statistical indices used to determine whether a process can consistently meet specification limits."),
            ("Bullwhip Effect in Supply Chains", "Explores how demand variability amplifies upstream through a supply chain and strategies to mitigate it."),
            ("Supply Chain Risk Pooling Strategies", "Examines how aggregating inventory or demand across locations reduces overall supply chain risk."),
            ("Postponement Strategy in Supply Chain Design", "Covers how delaying product differentiation improves flexibility and reduces inventory risk."),
            ("Yield Management in Perishable Goods Industries", "Introduces pricing and capacity strategies for maximizing revenue from perishable inventory."),
            ("Warehouse Slotting and Pick-Path Optimization", "Examines how product placement and picking routes are optimized to improve warehouse efficiency."),
            ("Cold Chain Logistics Management", "Covers the specialized handling and monitoring required to maintain temperature-sensitive products through distribution."),
            ("Total Productive Maintenance (TPM)", "Introduces a maintenance philosophy that engages all employees in maximizing equipment reliability and uptime."),
            ("Line Balancing in Assembly Operations", "Examines techniques for distributing tasks evenly across workstations to optimize assembly line throughput."),
            ("Batch Sizing and Lot-for-Lot Production Planning", "Covers approaches for determining production batch sizes to balance setup costs and inventory holding costs."),
            ("Operations Due Diligence in Mergers and Acquisitions", "Introduces how operational capabilities and risks are assessed during merger and acquisition evaluations."),
            ("Service Blueprinting for Process Design", "Examines a visual technique for mapping service processes to identify improvement opportunities."),
            ("Nearshoring and Reshoring Strategy Decisions", "Covers the strategic and economic factors driving decisions to relocate production closer to end markets."),
        ],
    },
    "Philosophy": {
        "UG3": [
            ("Philosophy of Language: Reference and Meaning", "Examines theories of how words and sentences come to refer to and mean things in the world."),
            ("Speech Act Theory: Austin and Searle", "Introduces the philosophical analysis of how utterances perform actions beyond conveying information."),
            ("Philosophy of Perception: Direct and Indirect Realism", "Explores competing accounts of whether perception gives us unmediated access to the external world."),
            ("Personal Identity and the Problem of Persons", "Examines philosophical theories of what makes a person the same individual over time."),
            ("Compatibilism and the Consequence Argument", "Covers the debate over whether free will and moral responsibility can coexist with determinism."),
            ("Moral Realism versus Anti-Realism", "Introduces the metaethical debate over whether moral facts exist independently of human attitudes."),
            ("Error Theory and Moral Nihilism", "Examines the view that moral claims are systematically false because they presuppose objective values that do not exist."),
            ("Trolley Problem and Doctrine of Double Effect", "Explores classic thought experiments used to analyze the moral distinction between intending and foreseeing harm."),
            ("Kierkegaard and the Leap of Faith", "Introduces Kierkegaard's account of subjective truth and the existential commitment required for religious faith."),
            ("Nietzsche's Genealogy of Morals", "Examines Nietzsche's historical and psychological critique of the origins of moral values."),
            ("Hegel's Dialectic and the Phenomenology of Spirit", "Introduces Hegel's dialectical method and its account of the development of self-consciousness."),
            ("Spinoza's Ethics and Substance Monism", "Covers Spinoza's geometric argument for a single infinite substance and its ethical implications."),
            ("Leibniz's Monadology and Theodicy", "Examines Leibniz's metaphysics of simple substances and his argument that this is the best of all possible worlds."),
            ("Philosophy of Law: Legal Positivism versus Natural Law", "Explores the jurisprudential debate over whether law's validity depends on morality or social facts alone."),
            ("Epicurean Philosophy and the Pursuit of Ataraxia", "Introduces the Epicurean school's ethics of pleasure, tranquility, and the removal of unnecessary fear."),
        ],
    },
    "Physical Education & Self-Defense": {
        "UG3": [
            ("Capoeira: History and Movement Principles", "Introduces the Afro-Brazilian martial art's history, music, and characteristic acrobatic movement vocabulary."),
            ("Wrestling Takedowns and Mat Control Fundamentals", "Covers fundamental wrestling techniques for taking an opponent down and controlling position on the mat."),
            ("Tactical Breathing and Arousal Control in Combat Sports", "Examines breathing and physiological regulation techniques used to manage stress response during confrontation."),
            ("Parkour and Functional Movement Training", "Introduces the discipline of efficient movement over obstacles and its applications to functional fitness."),
            ("Sports Officiating Technology: Video Review Systems", "Examines how video review and sensor-based technologies are changing officiating accuracy in modern sport."),
        ],
    },
    "Physics": {
        "UG3": [
            ("Casimir Effect and Vacuum Energy", "Introduces the quantum phenomenon in which vacuum fluctuations produce a measurable force between closely spaced surfaces."),
            ("Bose-Einstein Condensates", "Examines the quantum state of matter formed when bosonic particles are cooled to near absolute zero."),
            ("Topological Insulators and Quantum Hall Effect", "Covers materials that conduct on their surface while insulating in their interior, and the quantized Hall response."),
            ("Plasma Physics Fundamentals", "Introduces the behavior of ionized gases and their collective electromagnetic interactions."),
            ("Magnetohydrodynamics", "Examines the study of electrically conducting fluids and their interaction with magnetic fields."),
            ("Neutrino Physics and Oscillations", "Covers the properties of neutrinos and the phenomenon by which they change flavor as they propagate."),
            ("Dark Matter and Dark Energy Observational Evidence", "Introduces the astrophysical and cosmological evidence pointing to unseen mass and accelerating expansion."),
            ("Holographic Principle and AdS/CFT Correspondence", "Explores the theoretical conjecture relating gravitational theories to lower-dimensional quantum field theories."),
            ("Acoustics: Room and Architectural Sound Design", "Examines how physical principles of sound propagation inform the design of acoustically effective spaces."),
            ("Cryogenics and Low-Temperature Physics", "Covers the techniques and physical phenomena associated with producing and studying extremely low temperatures."),
            ("Semiconductor Band Theory", "Introduces the quantum mechanical basis of electron energy bands that determine semiconductor behavior."),
            ("Nonlinear Optics and Frequency Conversion", "Examines optical phenomena that occur when light interacts with matter in intensity-dependent ways."),
            ("Ultrafast Laser Spectroscopy", "Covers techniques using extremely short laser pulses to probe fast physical and chemical processes."),
            ("Metamaterials and Negative Refraction", "Introduces engineered materials with properties not found in nature, including negative refractive index behavior."),
        ],
    },
    "Project Management": {
        "UG3": [
            ("Critical Chain Project Management", "Introduces a scheduling method that focuses on resource constraints and buffer management rather than task dependencies alone."),
            ("Requirements Traceability Matrices", "Covers how requirements are tracked from origin through delivery to ensure complete project scope coverage."),
            ("Work Breakdown Structure Development Techniques", "Examines methods for decomposing project scope into manageable, deliverable-oriented work packages."),
            ("Project Procurement Management: Make-or-Buy Analysis", "Introduces the analytical framework for deciding whether to produce deliverables internally or procure them externally."),
            ("Stakeholder Register and RACI Charts", "Covers tools for documenting stakeholders and clarifying roles and responsibilities across project activities."),
            ("Agile Release Planning and Roadmapping", "Examines how agile teams plan and sequence releases to deliver incremental value over time."),
            ("Extreme Programming (XP) Practices in Project Delivery", "Introduces the software engineering practices of Extreme Programming and their role in agile project delivery."),
            ("Lean Project Management Principles", "Covers how lean thinking eliminates waste and maximizes value throughout the project lifecycle."),
            ("Project Management for Construction: Design-Bid-Build", "Examines the traditional construction project delivery method and its sequencing of design, bidding, and construction."),
            ("IT Project Management: Software Development Life Cycle Models", "Covers how different software development lifecycle models shape planning and execution of IT projects."),
            ("Project Risk Simulation with Sensitivity Analysis", "Introduces quantitative techniques for testing how uncertain variables affect project risk and outcomes."),
            ("Benefits Realization Management", "Examines how organizations plan for, track, and confirm that projects deliver their intended business benefits."),
            ("Project Governance Frameworks", "Covers the structures and decision-making processes that oversee project accountability and alignment with strategy."),
            ("Earned Schedule Method", "Introduces an extension of earned value management that provides more accurate schedule performance indicators."),
            ("Hybrid Project Management: Blending Agile and Waterfall", "Examines approaches that combine predictive and adaptive methodologies within a single project framework."),
            ("Project Team Formation: Tuckman's Stages of Group Development", "Covers the stages teams pass through as they form, develop, and mature into high-performing units."),
            ("Digital Twins in Construction Project Management", "Introduces how virtual replicas of construction projects support planning, monitoring, and coordination."),
            ("Global Project Management: Time Zone and Distributed Delivery Challenges", "Examines the coordination challenges of managing projects across dispersed teams and time zones."),
            ("Project Management Software Tools: Selection Criteria", "Covers the criteria organizations use to evaluate and select project management software platforms."),
        ],
    },
    "Prompt Engineering": {
        "UG3": [
            ("Prompt Compression Techniques for Token Efficiency", "Introduces methods for reducing prompt length while preserving essential information to lower cost and latency."),
            ("Multi-Agent Prompt Orchestration", "Examines how multiple specialized language model agents are coordinated through prompting to complete complex tasks."),
            ("Self-Consistency Decoding for Reasoning Prompts", "Covers a technique that samples multiple reasoning paths and selects the most consistent answer to improve accuracy."),
            ("Tree-of-Thought Prompting Strategies", "Introduces a prompting framework that explores multiple branching reasoning paths before converging on a solution."),
            ("Least-to-Most Prompting for Complex Problem Decomposition", "Examines a strategy that breaks complex problems into a sequence of simpler subproblems solved progressively."),
            ("Retrieval Query Expansion Techniques", "Covers methods for reformulating and expanding queries to improve the relevance of retrieved context."),
            ("Prompt Injection Attack Vectors and Defenses", "Introduces how malicious inputs can hijack model behavior through prompts and the defenses used to mitigate them."),
            ("Structured Output Formatting with JSON Mode", "Examines techniques for reliably constraining model outputs to valid structured formats such as JSON."),
            ("Persona Consistency Across Long Conversations", "Covers strategies for maintaining a stable assistant persona and tone across extended multi-turn interactions."),
            ("Temperature and Sampling Parameter Tuning", "Introduces how decoding parameters like temperature and top-p influence the randomness and quality of generated text."),
            ("Prompt Versioning and A/B Testing Workflows", "Examines processes for systematically tracking, comparing, and testing prompt variants in production."),
            ("Domain-Specific Prompt Libraries for Enterprise Use", "Covers how organizations build and maintain reusable prompt collections tailored to specific business domains."),
            ("Cross-Model Prompt Portability and Adaptation", "Introduces strategies for adapting prompts that were designed for one language model to perform well on another."),
        ],
    },
    "Python": {
        "UG3": [
            ("Type Hints and Static Type Checking with mypy", "Introduces Python's optional type annotation system and how static analysis tools catch type errors before runtime."),
            ("The Walrus Operator and Expression Assignment", "Covers the assignment expression syntax introduced to allow assignment within larger expressions."),
            ("Structural Pattern Matching with match-case", "Examines Python's pattern matching syntax for expressing complex conditional logic concisely."),
            ("Descriptors and Attribute Access Customization", "Introduces the descriptor protocol that underlies properties and controls how attribute access is customized."),
            ("Abstract Base Classes and the abc Module", "Covers how abstract base classes define required interfaces that subclasses must implement."),
            ("Multiple Inheritance and the Method Resolution Order", "Examines how Python resolves method lookup across multiple inheritance hierarchies using the C3 linearization algorithm."),
            ("Memory Management and Garbage Collection in CPython", "Introduces how CPython allocates memory and reclaims unused objects through reference counting and cyclic garbage collection."),
            ("Building Python C Extensions", "Covers how performance-critical Python functionality can be implemented in C and exposed to Python code."),
            ("Property-Based Testing with Hypothesis", "Examines a testing approach that generates randomized inputs to discover edge cases automatically."),
            ("Data Validation with Pydantic", "Introduces a library for validating and parsing data using Python type annotations."),
            ("Building gRPC Services in Python", "Covers how to define and implement high-performance remote procedure call services using gRPC in Python."),
            ("Python Packaging with pyproject.toml and Build Backends", "Examines the modern standardized configuration format and build backend ecosystem for packaging Python projects."),
        ],
    },
    "R": {
        "UG3": [
            ("Functional Programming with purrr", "Introduces the tidyverse package for applying functions consistently over lists and vectors in R."),
            ("Meta-Programming and Non-Standard Evaluation in R", "Examines how R functions can capture and manipulate unevaluated expressions to build flexible interfaces."),
            ("Building R Packages with Rcpp for C++ Integration", "Covers how performance-critical R code can be accelerated by integrating compiled C++ functions."),
            ("Spatial Data Analysis with sf in R", "Introduces the simple features standard for representing and analyzing spatial vector data in R."),
            ("Mixed-Effects Models with lme4", "Examines how hierarchical and grouped data are modeled using fixed and random effects in R."),
            ("Generalized Additive Models in R", "Covers flexible regression models that allow nonlinear relationships through smooth functions of predictors."),
            ("Structural Equation Modeling in R", "Introduces techniques for modeling relationships among observed and latent variables in R."),
            ("Text Analysis with the quanteda Package", "Examines a quantitative text analysis workflow for tokenizing, analyzing, and modeling textual corpora in R."),
            ("Building REST APIs in R with plumber", "Covers how R functions can be exposed as web API endpoints using the plumber package."),
            ("R for Geospatial Mapping with leaflet", "Introduces interactive map creation in R using the leaflet package."),
            ("Meta-Analysis in R with the metafor Package", "Examines how effect sizes from multiple studies are statistically combined using the metafor package."),
            ("Causal Inference Methods in R", "Covers techniques such as propensity score matching and instrumental variables for estimating causal effects in R."),
        ],
    },
    "Science": {
        "UG3": [
            ("History of the Scientific Revolution: Copernicus to Newton", "Traces the intellectual transformation from geocentric cosmology to classical mechanics during the Scientific Revolution."),
            ("Citizen Science and Crowdsourced Data Collection", "Examines how volunteer participation contributes to large-scale scientific data collection and analysis."),
            ("The Philosophy of Experimentation and Instrumentation", "Explores how scientific instruments shape what can be observed and how experimental knowledge is produced."),
            ("Science Funding Systems and Peer Review", "Introduces how research funding is allocated and how peer review shapes the direction of scientific inquiry."),
        ],
    },
    "Social Studies": {
        "UG3": [
            ("Symbolic Interactionism in Sociological Theory", "Introduces the theoretical perspective that examines how meaning is created through everyday social interaction."),
            ("Structural Functionalism and Its Critics", "Examines the theory that views society as an interconnected system of functions, alongside major critiques."),
            ("Conflict Theory and Marxist Sociology", "Introduces the theoretical tradition that analyzes society through the lens of class struggle and power inequality."),
            ("Postcolonial Theory in Social Science", "Explores how postcolonial thought critiques power, knowledge, and identity in the aftermath of colonialism."),
            ("Intersectionality Theory and Social Analysis", "Introduces the framework for analyzing how overlapping social identities shape experiences of inequality."),
            ("Social Capital Theory: Bourdieu and Putnam", "Examines competing theoretical accounts of how social networks and trust generate collective and individual value."),
            ("Panel Data Methods in Social Research", "Covers statistical techniques for analyzing data collected from the same subjects over multiple time points."),
            ("Ethnographic Fieldwork Methodology", "Introduces the participant-observation methods researchers use to study communities and cultures firsthand."),
            ("Survey Sampling Design and Bias", "Examines how sampling strategies affect the validity of survey research and the sources of common biases."),
            ("Comparative Electoral Systems", "Surveys how different electoral rules shape political representation and party systems across countries."),
            ("Think Tanks and Policy Influence Networks", "Explores the role of policy research organizations in shaping public debate and government decisions."),
            ("Urban Gentrification and Displacement Studies", "Examines the social and economic processes driving neighborhood change and resident displacement in cities."),
            ("Sociology of Sport and Leisure", "Introduces how sport and leisure activities reflect and reproduce broader social structures and inequalities."),
        ],
    },
    "Survival Skills": {
        "UG3": [
            ("Bushcraft Camp Kitchen Design and Fire-Cooking Methods", "Covers practical techniques for setting up an efficient outdoor cooking area and preparing food over open fire."),
            ("Emergency Vehicle Preparedness and Roadside Survival Kits", "Introduces essential supplies and strategies for surviving a vehicle breakdown or roadside emergency."),
            ("Wilderness Navigation Without Instruments Using Natural Signs", "Examines how natural indicators such as sun position, vegetation, and stars can be used to navigate without tools."),
            ("Survival Psychology: The Will to Live Factor", "Explores the psychological determinants that influence a person's ability to persevere in life-threatening situations."),
        ],
    },
    "UI/UX Design": {
        "UG3": [
            ("Voice User Interface (VUI) Design Principles", "Introduces the principles of designing conversational interfaces controlled primarily through speech."),
            ("Motion Design and Micro-Interactions", "Examines how small animated feedback moments enhance usability and delight within digital products."),
            ("Card Sorting for Information Architecture", "Covers the research method used to understand how users mentally group and categorize content."),
            ("Usability Benchmarking Across Product Versions", "Introduces methods for tracking usability metrics over time to measure design improvement across releases."),
            ("Design for Wearable Device Interfaces", "Explores the constraints and patterns specific to designing interfaces for small, body-worn devices."),
            ("Onboarding Flow Design Patterns", "Examines patterns used to introduce new users to a product's core value and functionality."),
            ("Form Design Best Practices and Validation Patterns", "Covers techniques for designing clear, error-tolerant input forms and effective validation feedback."),
            ("Atomic Design Methodology", "Introduces a systematic approach to building interfaces from small reusable components up to full templates."),
            ("Design Localization for Right-to-Left Languages", "Examines the layout and interaction adjustments required to support right-to-left reading languages."),
            ("Emotional Design and Delight in Interfaces", "Explores how visual and interaction details create positive emotional responses in users."),
            ("Progressive Disclosure in Interface Design", "Covers the technique of revealing information gradually to reduce cognitive load and interface complexity."),
            ("UX Research Ethics and Informed Consent", "Introduces ethical considerations and consent practices required when conducting research with human participants."),
            ("Competitive Analysis and Benchmarking in UX", "Examines methods for systematically evaluating competitor products to inform design strategy."),
            ("Design for Trust: Privacy and Transparency Patterns", "Explores interface patterns that build user trust through clear privacy communication and transparency."),
            ("Multimodal Interaction Design (Voice, Touch, Gesture)", "Introduces design approaches for interfaces that combine multiple input modalities such as voice, touch, and gesture."),
        ],
    },
    "Web Development": {
        "UG3": [
            ("HTTP/2 and HTTP/3 Protocol Features", "Examines the performance improvements and architectural changes introduced by modern HTTP protocol versions."),
            ("Server-Timing and Resource Hints for Performance", "Covers browser and server mechanisms used to communicate and optimize resource loading performance."),
            ("Web Components and the Shadow DOM", "Introduces the standards for building encapsulated, reusable custom elements with isolated styling and markup."),
            ("Custom Elements API for Reusable Components", "Examines how developers define new HTML elements with custom behavior using the Custom Elements API."),
            ("Headless CMS Architecture for Web Projects", "Explores how content management systems decoupled from presentation layers support flexible web architectures."),
            ("API Gateway Patterns for Web Backends", "Covers how API gateways centralize routing, authentication, and rate limiting for backend services."),
            ("Web Security: Clickjacking Prevention", "Introduces techniques for protecting web applications against clickjacking attacks that hijack user clicks."),
            ("Subresource Integrity and Supply Chain Security for Web Assets", "Examines how integrity checks protect against tampered third-party scripts and assets."),
            ("Static Analysis and Type Checking for Web Codebases", "Covers tools and practices for catching errors in web application code before runtime through static analysis."),
            ("Multi-Tenant SaaS Web Architecture", "Introduces architectural patterns for serving multiple customer organizations from a shared web application codebase."),
            ("Web Internationalized Domain Names and Unicode Handling", "Examines how domain names and URLs handle non-ASCII characters and Unicode encoding."),
        ],
    },
    "World History": {
        "UG3": [
            ("The Assyrian Empire and Ancient Near Eastern Warfare", "Examines the military organization and imperial administration of the ancient Assyrian Empire."),
            ("The Persian Achaemenid Empire and Administration", "Surveys the governance systems that allowed the Achaemenid Empire to rule a vast multiethnic territory."),
            ("The Indus Valley Civilization", "Introduces the urban planning, trade, and largely undeciphered script of the Bronze Age Indus Valley civilization."),
            ("The Maurya Empire and Ashoka's Dharma", "Examines the unification of ancient India under the Maurya dynasty and Ashoka's ethical governance policies."),
            ("The Gupta Empire and India's Classical Age", "Surveys the cultural, scientific, and artistic achievements of India's Gupta-era golden age."),
            ("The Kingdom of Aksum and Red Sea Trade", "Introduces the ancient African kingdom's role in Red Sea and Indian Ocean trade networks."),
            ("The Inca Empire: Administration and Road Systems", "Examines the administrative and infrastructural systems that unified the Inca Empire across the Andes."),
            ("The Aztec Empire: Tribute and Warfare", "Surveys the tribute-based economy and military expansion that sustained the Aztec imperial system."),
            ("The Hanseatic League and Northern European Trade", "Introduces the medieval commercial confederation that dominated trade across Northern Europe."),
            ("The Thirty Years' War and the Peace of Westphalia", "Examines the causes and consequences of a major European conflict and the treaty that reshaped state sovereignty."),
            ("The Haitian Revolution", "Surveys the successful slave uprising that led to the establishment of the first free Black republic."),
            ("The Meiji Restoration and Japan's Modernization", "Examines how Japan rapidly transformed its political and economic institutions in the late nineteenth century."),
            ("The Boxer Rebellion and Foreign Intervention in China", "Introduces the anti-foreign uprising in China and the international response it provoked."),
            ("The Armenian Genocide", "Examines the historical events and consequences of the mass killing of Armenians in the early twentieth century."),
            ("The Non-Aligned Movement During the Cold War", "Surveys how newly independent states organized to avoid alignment with either Cold War superpower bloc."),
            ("The Rwandan Genocide and International Response", "Examines the causes of the 1994 genocide and the failures and lessons of the international response."),
            ("The Arab Spring and Its Aftermath", "Surveys the wave of pro-democracy uprisings across the Arab world and their varied long-term outcomes."),
        ],
    },
    "World Literature": {
        "UG3": [
            ("German Bildung Tradition: Goethe's Faust", "Introduces the German tradition of formative literature through Goethe's exploration of ambition and moral compromise."),
            ("Portuguese Literature: Pessoa and Heteronyms", "Examines Fernando Pessoa's distinctive use of invented literary personas to explore fragmented identity."),
            ("Turkish Literature: Pamuk and Istanbul's Literary Identity", "Surveys how modern Turkish literature engages with cultural memory and the identity of Istanbul."),
            ("Yiddish Literature and the Shtetl Tradition", "Introduces the literary tradition depicting Eastern European Jewish life and culture in the Yiddish language."),
            ("Australian and New Zealand Postcolonial Fiction", "Examines how settler-colonial literatures grapple with land, identity, and indigenous relations."),
            ("Vietnamese and Southeast Asian War Literature", "Surveys literary responses to conflict and its aftermath across Vietnam and Southeast Asia."),
        ],
    },
}
