"""Module topics bringing Digital Marketing, UI/UX Design, Project
Management, and Finance up to 20+ lessons per level (C1 through M1)."""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Digital Marketing": {
        "C1": [
            ("Understanding the Marketing Funnel", "Explains the awareness, consideration, and conversion stages that guide how customers move toward a purchase decision."),
            ("Buyer Personas and Target Audience Research", "Covers how to research and build semi-fictional buyer personas from demographic, behavioral, and psychographic data."),
            ("Customer Journey Mapping Basics", "Introduces how to chart the touchpoints a customer experiences from first awareness through post-purchase support."),
            ("Digital Marketing Channels Overview", "Surveys the major digital channels -- search, social, email, display, and content -- and how they fit together in a marketing plan."),
            ("On-Page SEO Optimization", "Covers optimizing title tags, headers, meta descriptions, and body content so individual web pages rank better in search results."),
            ("Keyword Research Fundamentals", "Teaches how to find and prioritize search terms using tools that reveal search volume, competition, and user intent."),
            ("Website Usability for Marketers", "Explains core usability concepts, such as navigation clarity and page load speed, that affect how visitors experience a marketing website."),
            ("Introduction to Content Formats", "Surveys blog posts, videos, infographics, and other content formats and when each is most effective for a marketing goal."),
            ("Social Media Platform Landscape", "Compares the audience demographics and content norms of major social platforms to help marketers choose where to invest."),
            ("Basics of Online Advertising Models", "Introduces pricing models such as CPC, CPM, and CPA used across digital advertising platforms."),
            ("Mobile Marketing Fundamentals", "Covers how marketers reach users on smartphones through mobile-optimized sites, apps, and location-based tactics."),
            ("Marketing KPIs and Metrics Basics", "Introduces common marketing metrics, including reach, engagement, and conversion rate, and how they indicate campaign performance."),
            ("Brand Identity Basics", "Covers the foundational elements of a brand, including logo, color palette, and tone of voice, and why consistency matters."),
            ("Introduction to Marketing Calendars", "Explains how marketers plan and schedule campaigns, content, and promotions across a calendar year."),
            ("Digital PR Fundamentals", "Introduces how marketers earn media coverage and backlinks through press outreach and newsworthy content."),
            ("Community Management Basics", "Covers how brands build and moderate online communities to foster engagement and customer loyalty."),
            ("Marketing Ethics Overview", "Introduces honesty, transparency, and consumer protection considerations that shape responsible marketing practice."),
            ("Competitive Marketing Analysis Basics", "Teaches how to research competitors' messaging, channels, and offers to identify gaps and opportunities."),
        ],
        "C2": [
            ("Content Calendar Planning", "Covers how to plan, schedule, and coordinate content publication across channels to support marketing goals."),
            ("Storytelling in Brand Content", "Explores narrative techniques marketers use to make brand content more memorable and emotionally resonant."),
            ("Content Distribution Channels", "Covers how content is shared and promoted across owned, earned, and paid channels to reach a wider audience."),
            ("Facebook & Instagram Marketing", "Covers organic posting strategy and paid advertising tools specific to the Meta platforms."),
            ("LinkedIn Marketing for B2B", "Explains how B2B marketers use LinkedIn content, groups, and ads to reach professional audiences."),
            ("TikTok Marketing Strategy", "Covers short-form video trends, sounds, and creator collaborations used to market on TikTok."),
            ("Social Listening and Sentiment Analysis", "Teaches how marketers monitor social conversations to gauge brand sentiment and spot emerging issues."),
            ("Visual Content Creation for Social Media", "Covers principles for creating graphics, photos, and short videos optimized for social feeds."),
            ("Off-Page SEO and Link Building", "Covers how backlinks, guest posts, and outreach build a site's authority in search rankings."),
            ("Local SEO Strategy", "Covers optimizing Google Business Profile listings, local citations, and reviews to rank in local search results."),
            ("Technical SEO Basics", "Introduces crawlability, indexability, site speed, and structured data as technical factors affecting search visibility."),
            ("Landing Page Design Principles", "Covers layout, copywriting, and call-to-action placement that help landing pages convert visitors."),
            ("Introduction to A/B Testing", "Explains how marketers test two versions of a page or message to see which performs better."),
            ("Email List Building Basics", "Covers lead magnets, opt-in forms, and list hygiene practices used to grow a permission-based email list."),
            ("Newsletter Strategy and Design", "Covers planning content and layout for recurring email newsletters that keep subscribers engaged."),
            ("Podcast Marketing Basics", "Introduces how brands use podcasts and podcast advertising to reach niche, engaged audiences."),
            ("YouTube Channel Strategy", "Covers planning content, optimizing video titles and thumbnails, and building a subscriber base on YouTube."),
            ("Marketing Budget Planning Basics", "Introduces how marketers allocate spend across channels and justify budgets with expected returns."),
        ],
        "UG1": [
            ("Email Segmentation and Personalization", "Covers dividing an email list into segments and tailoring message content to each segment's behavior and preferences."),
            ("Email Automation Workflows", "Covers building triggered email sequences, such as welcome series and abandoned cart reminders, based on subscriber actions."),
            ("Email Deliverability and Compliance", "Covers sender reputation, authentication protocols, and laws such as CAN-SPAM that affect whether email reaches the inbox."),
            ("Google Ads Campaign Structure", "Covers organizing campaigns, ad groups, and keywords to structure an effective Google Ads account."),
            ("Display Advertising Strategy", "Covers designing and targeting banner and rich-media ads served across a publisher network."),
            ("Retargeting and Remarketing Campaigns", "Covers showing ads to people who previously visited a site or app to bring them back to complete a purchase."),
            ("Native Advertising Strategy", "Covers designing paid content that matches the look and feel of the platform it appears on."),
            ("Shopping Ads and Product Feed Optimization", "Covers structuring product data feeds so e-commerce listings appear correctly in shopping ad placements."),
            ("Programmatic Advertising Basics", "Introduces how ad inventory is bought and sold automatically through real-time bidding exchanges."),
            ("Bid Strategy and Budget Optimization", "Covers manual and automated bidding approaches marketers use to control ad spend and maximize returns."),
            ("Ad Copywriting and Creative Testing", "Covers writing persuasive ad headlines and descriptions and testing creative variations for performance."),
            ("Conversion Tracking Setup", "Covers installing and configuring tracking pixels and tags so advertising platforms can measure conversions."),
            ("UTM Tracking and Campaign Tagging", "Covers using UTM parameters to tag links so analytics tools can attribute traffic to specific campaigns."),
            ("CRM Integration for Marketing", "Covers connecting marketing platforms with customer relationship management systems to unify customer data."),
            ("SMS and Push Notification Marketing", "Covers sending timely text and app notifications as a direct channel for promotions and reminders."),
            ("Mobile App Store Optimization (ASO)", "Covers optimizing app titles, descriptions, and screenshots to improve visibility in app store search."),
            ("Affiliate Program Management", "Covers recruiting, tracking, and paying affiliate partners who promote a business in exchange for commission."),
            ("Influencer Outreach and Vetting", "Covers identifying, evaluating, and negotiating with content creators for brand partnerships."),
        ],
        "UG2": [
            ("Web Analytics Fundamentals (GA4)", "Covers setting up and reading reports in Google Analytics 4 to understand website traffic and user behavior."),
            ("Attribution Modeling", "Covers different models for crediting marketing touchpoints with contributing to a conversion."),
            ("Marketing Dashboards and Reporting", "Covers building dashboards that summarize key marketing metrics for stakeholders."),
            ("Customer Lifetime Value Analysis", "Covers estimating the total revenue a business can expect from a customer relationship over time."),
            ("Marketing Mix Modeling", "Covers statistical techniques for estimating how much each marketing channel contributes to overall sales."),
            ("Predictive Analytics in Marketing", "Covers using historical data and models to forecast customer behavior such as churn or purchase likelihood."),
            ("A/B Testing Methodology", "Covers designing statistically sound experiments, including sample size and test duration considerations."),
            ("Landing Page Optimization", "Covers iterating on landing page elements using data and testing to improve conversion rates."),
            ("Personalization and Dynamic Content", "Covers tailoring website or email content in real time based on visitor data and behavior."),
            ("Lead Scoring and Nurturing", "Covers ranking leads by readiness to buy and guiding them through automated nurture campaigns."),
            ("Onboarding and Retention Marketing", "Covers campaigns that help new customers succeed with a product and reduce churn over time."),
            ("Cart Abandonment Recovery", "Covers using email, retargeting, and incentives to bring back shoppers who left items in their cart."),
            ("Heatmaps and Session Recording Analysis", "Covers using visual tools that show where visitors click and scroll to diagnose usability and conversion issues."),
            ("Multivariate Testing Techniques", "Covers testing multiple page elements simultaneously to find the best-performing combination."),
            ("Marketing Data Visualization", "Covers choosing charts and visual formats that make marketing data easier to interpret and act on."),
            ("Customer Segmentation Analytics", "Covers grouping customers by shared characteristics or behaviors to target marketing more precisely."),
            ("Funnel Analysis and Drop-off Diagnosis", "Covers identifying where in a conversion funnel users disengage and why."),
            ("Statistical Significance in Marketing Tests", "Covers interpreting p-values and confidence intervals so marketers can trust test results before acting on them."),
        ],
        "UG3": [
            ("Brand Identity Design", "Covers developing the visual and verbal elements, such as logo, palette, and tagline, that make up a brand's identity."),
            ("Brand Voice and Messaging Guidelines", "Covers documenting tone, vocabulary, and messaging pillars so a brand communicates consistently."),
            ("Rebranding Strategy", "Covers the process and risks of updating a brand's identity or positioning, including audience research and rollout planning."),
            ("Employer Branding", "Covers marketing a company as an employer of choice to attract job candidates."),
            ("Crisis Communication in Digital Channels", "Covers planning and executing brand communication during a public relations crisis on social and digital media."),
            ("Creator Economy Trends", "Covers how independent content creators monetize audiences and how brands partner within this ecosystem."),
            ("Micro-Influencer Strategy", "Covers working with smaller-audience creators who often deliver higher engagement and niche relevance than celebrities."),
            ("Influencer Contract Negotiation", "Covers structuring deliverables, usage rights, and payment terms in influencer partnership agreements."),
            ("Affiliate Network Management", "Covers running an affiliate program through third-party networks that connect merchants with publishers."),
            ("Co-Branding and Partnership Marketing", "Covers structuring joint marketing initiatives between two or more brands to reach shared audiences."),
            ("Brand Reputation Management", "Covers monitoring and responding to reviews, mentions, and public sentiment to protect a brand's reputation."),
            ("Competitive Positioning Analysis", "Covers mapping how a brand's offering compares to competitors on attributes that matter to customers."),
            ("Visual Identity Systems for Brands", "Covers building a coherent system of logos, colors, and imagery that scales across marketing materials."),
            ("Sponsorship and Event Marketing", "Covers using sponsorships and branded events to build visibility and engage audiences in person and online."),
            ("Word-of-Mouth Marketing Strategy", "Covers designing products and experiences that encourage customers to recommend a brand to others."),
            ("Brand Storytelling Frameworks", "Covers structured approaches, such as the hero's journey, applied to brand narratives."),
            ("Loyalty Program Design", "Covers structuring rewards and incentive programs that encourage repeat purchases."),
            ("Cause Marketing and Social Impact Campaigns", "Covers aligning a brand with a social or environmental cause in a way that is authentic and mutually beneficial."),
        ],
        "UG4": [
            ("Marketing Technology Stack Selection", "Covers evaluating and selecting the combination of software tools that support a marketing team's workflows."),
            ("Chatbots and Conversational Marketing", "Covers using automated chat tools to engage website visitors and qualify leads in real time."),
            ("AI Tools in Marketing Workflows", "Covers how marketers use AI-assisted tools for content generation, personalization, and campaign optimization."),
            ("Workflow Triggers and Behavioral Automation", "Covers setting up automated marketing actions that fire based on specific user behaviors or events."),
            ("Marketplace Marketing (Amazon, Etsy)", "Covers optimizing product listings and advertising within third-party e-commerce marketplaces."),
            ("Subscription and Loyalty Commerce Marketing", "Covers marketing strategies specific to subscription boxes and recurring-revenue commerce models."),
            ("Cross-Sell and Upsell Campaign Design", "Covers designing offers that encourage existing customers to buy complementary or higher-value products."),
            ("Product Feed Management for E-commerce", "Covers maintaining accurate, well-structured product data feeds that power shopping ads and marketplace listings."),
            ("Marketing for Direct-to-Consumer (DTC) Brands", "Covers marketing tactics distinct to brands that sell directly to consumers without traditional retail intermediaries."),
            ("Checkout Optimization and Cart Recovery", "Covers reducing friction in the checkout process to lower cart abandonment rates."),
            ("Customer Data Platforms (CDPs)", "Covers how CDPs unify customer data from multiple sources into a single profile for marketing use."),
            ("Lifecycle Marketing Automation", "Covers automating communications tailored to each stage of the customer lifecycle, from acquisition to win-back."),
            ("Dynamic Product Retargeting", "Covers showing ads featuring specific products a user previously viewed to encourage return visits."),
            ("E-commerce SEO Strategy", "Covers optimizing product and category pages so online stores rank well in search results."),
            ("Marketplace Advertising (Amazon Ads)", "Covers sponsored product and brand advertising options available within online marketplaces."),
            ("International E-commerce Marketing", "Covers adapting online store marketing for cross-border shoppers, including currency, shipping, and trust signals."),
            ("Automated Reporting and Alerting", "Covers setting up automated dashboards and alerts that flag marketing performance changes without manual checking."),
            ("Marketing Operations (MOps) Fundamentals", "Covers the processes, data, and technology management that keep a marketing organization running efficiently."),
        ],
        "M1": [
            ("Video Ad Production for Social Platforms", "Covers planning, shooting, and editing short video ads tailored to social media placements."),
            ("Livestream and Webinar Marketing", "Covers using live video formats to engage audiences in real time for product launches and education."),
            ("Short-Form Video Strategy (Reels/Shorts)", "Covers producing short vertical video content optimized for platforms like Instagram Reels and YouTube Shorts."),
            ("YouTube Advertising Strategy", "Covers formats and targeting options for running paid advertising campaigns on YouTube."),
            ("Interactive and Shoppable Video", "Covers adding clickable product tags and interactive elements to video content to drive direct purchases."),
            ("GDPR and Global Data Privacy Compliance", "Covers how marketers collect and use consumer data in compliance with GDPR and other regional privacy laws."),
            ("Cookie-less Tracking and Privacy-First Marketing", "Covers alternative measurement approaches as third-party cookies are phased out of major browsers."),
            ("Ethical Advertising and Dark Patterns", "Covers identifying and avoiding manipulative design and messaging tactics that mislead consumers."),
            ("Data Governance in Marketing Organizations", "Covers policies and processes that ensure customer data is collected, stored, and used responsibly across a marketing team."),
            ("International Marketing Strategy", "Covers adapting marketing plans for different countries' markets, regulations, and consumer expectations."),
            ("Localization and Cultural Adaptation", "Covers translating and culturally adapting marketing content so it resonates with local audiences."),
            ("Global SEO and Multilingual Content", "Covers technical and content strategies for ranking a website across multiple languages and countries."),
            ("Marketing Team Structure and Operations", "Covers how marketing departments are organized by function, channel, or product line."),
            ("B2B vs B2C Digital Strategy", "Covers how digital marketing tactics differ between business and consumer audiences, including sales cycle and messaging."),
            ("Marketing for Startups and Limited Budgets", "Covers prioritizing high-impact, low-cost marketing tactics appropriate for early-stage companies."),
            ("Growth Hacking Frameworks (AARRR)", "Covers the Acquisition-Activation-Retention-Referral-Revenue framework used to structure growth experiments."),
            ("Viral Marketing Mechanics", "Covers the design principles behind content and offers that spread rapidly through sharing."),
            ("Digital Marketing Capstone Campaign Design", "Applies course concepts to design and justify a complete, multi-channel digital marketing campaign from strategy through measurement."),
        ],
    },
    "UI/UX Design": {
        "C1": [
            ("The Double Diamond Design Process", "Introduces the four-phase discover-define-develop-deliver framework used to structure design projects."),
            ("Understanding User Needs and Pain Points", "Covers techniques for identifying what users are trying to accomplish and where they struggle."),
            ("Basics of Usability Heuristics", "Introduces Nielsen's ten usability heuristics as a quick way to spot common interface problems."),
            ("Introduction to Personas", "Covers building simplified user archetypes from research data to guide design decisions."),
            ("User Journey Mapping Basics", "Introduces charting the steps and emotions a user experiences while completing a task with a product."),
            ("Sketching and Ideation Techniques", "Covers quick hand-drawn sketching methods designers use to generate and compare interface ideas rapidly."),
            ("Basics of Grid Systems and Layout", "Introduces how grids create consistent structure and alignment across screens."),
            ("Introduction to Design Critique", "Covers giving and receiving structured, constructive feedback on design work."),
            ("Low-Fidelity Prototyping", "Covers building rough, quick prototypes such as paper sketches or simple click-throughs to test early concepts."),
            ("Introduction to User Flows", "Covers diagramming the path a user takes through a product to complete a specific task."),
            ("Basics of Iconography", "Introduces principles for designing and choosing icons that communicate meaning clearly."),
            ("Introduction to Design Terminology and Roles", "Covers common vocabulary and the distinct responsibilities of UX researchers, UX designers, and UI designers."),
            ("Understanding Affordances and Signifiers", "Covers how interface elements suggest their function through visual and interactive cues."),
            ("Introduction to Content Hierarchy", "Covers organizing text and visual elements by importance to guide a viewer's attention."),
            ("Basics of Form Design", "Covers structuring input fields, labels, and validation to make forms easier to complete."),
            ("Introduction to Empathy Mapping", "Covers a collaborative exercise for capturing what users say, think, feel, and do around a problem."),
            ("Basics of Competitive UX Audits", "Covers reviewing competitor products to identify UX strengths, weaknesses, and opportunities."),
            ("Introduction to Design Ethics", "Covers how design decisions can support or undermine user well-being, autonomy, and trust."),
        ],
        "C2": [
            ("Card Sorting Techniques", "Covers a research method where participants group content into categories to reveal how they expect information to be organized."),
            ("Tree Testing for Navigation", "Covers testing a text-only version of a site's navigation structure to see if users can find items."),
            ("Sitemap Development", "Covers diagramming the hierarchy of pages and sections that make up a product or website."),
            ("Navigation Pattern Design", "Covers common navigation structures, such as tab bars and hamburger menus, and when to use each."),
            ("Mid-Fidelity Wireframing", "Covers building wireframes with enough detail to represent layout and content without visual styling."),
            ("High-Fidelity Prototyping Tools", "Covers using design software to build realistic, interactive prototypes close to the final product."),
            ("Clickable Prototype Testing", "Covers testing interactive prototypes with users before development begins."),
            ("Content Modeling for IA", "Covers defining the structured content types and fields that populate a product's information architecture."),
            ("Taxonomy and Labeling Systems", "Covers creating consistent naming and categorization schemes so users can predict where content lives."),
            ("Search Design and Findability", "Covers designing search functionality, filters, and autocomplete to help users locate content."),
            ("Prototyping for Mobile Apps", "Covers building interactive prototypes specific to mobile app gestures and navigation patterns."),
            ("Storyboarding for UX", "Covers illustrating a sequence of frames that show how a user interacts with a product over time."),
            ("Paper Prototyping Methods", "Covers testing interface concepts using hand-drawn screens before any digital design work begins."),
            ("Design Documentation Practices", "Covers writing specifications and rationale that communicate design decisions to a broader team."),
            ("Annotating Wireframes for Developers", "Covers adding notes to wireframes that clarify behavior, states, and edge cases for engineering handoff."),
            ("Responsive Wireframe Layouts", "Covers wireframing how a layout adapts across different screen sizes."),
            ("Prototyping Micro-flows", "Covers prototyping small, self-contained interactions such as a single form submission or toggle."),
            ("Design Handoff Fundamentals", "Covers preparing design files, specs, and assets so engineers can implement a design accurately."),
        ],
        "UG1": [
            ("Grid Systems and Layout Composition", "Covers using columns, gutters, and margins to create balanced, scalable interface layouts."),
            ("Color Accessibility and Contrast", "Covers choosing color combinations that meet contrast standards for users with low vision or color blindness."),
            ("Type Pairing and Hierarchy", "Covers combining typefaces and sizes to establish clear visual hierarchy in an interface."),
            ("Iconography and Illustration Style", "Covers developing a consistent visual style for icons and illustrations across a product."),
            ("Design Tokens for Visual Consistency", "Covers using named variables for color, spacing, and type so visual styles stay consistent and easy to update."),
            ("Whitespace and Visual Balance", "Covers using negative space deliberately to improve readability and visual comfort."),
            ("Branding Application in UI", "Covers translating brand guidelines, such as color and voice, into consistent interface design decisions."),
            ("Dark Mode Design Considerations", "Covers adapting color palettes and contrast for interfaces viewed in low-light color schemes."),
            ("Imagery and Photography Direction", "Covers selecting and art-directing photography and imagery that reinforces a product's visual identity."),
            ("Visual Consistency Across Platforms", "Covers maintaining a coherent look and feel for a product across web, iOS, and Android."),
            ("Skeuomorphism vs Flat Design History", "Covers the evolution of interface visual styles from realistic textures to flat and minimal design."),
            ("Gestalt Principles in Interface Design", "Covers how principles like proximity, similarity, and closure explain how users perceive grouped elements."),
            ("Emotional Design and Aesthetics", "Covers how visual and interactive choices affect a user's emotional response to a product."),
            ("Data Visualization Design Basics", "Covers choosing chart types and visual encodings that represent data clearly and accurately."),
            ("Design for Print vs Digital", "Covers key differences in color, resolution, and layout between print and digital design."),
            ("Motion and Visual Rhythm", "Covers using consistent timing and easing in animation to create a coherent sense of motion across an interface."),
            ("Cultural Considerations in Visual Design", "Covers how color, imagery, and symbols carry different meanings across cultures."),
            ("Design Critique and Feedback Frameworks", "Covers structured methods, such as the sandwich method or design critique rubrics, for giving actionable feedback."),
        ],
        "UG2": [
            ("Interaction Design Patterns Library", "Covers reusable solutions to common interaction problems, such as modals, carousels, and accordions."),
            ("Feedback and System Status Design", "Covers giving users clear signals about what the system is doing, such as loading indicators and confirmations."),
            ("Error Prevention and Recovery Design", "Covers designing interfaces that prevent mistakes and help users recover easily when errors occur."),
            ("Gesture-Based Interaction Design", "Covers designing touch gestures like swipe, pinch, and long-press for mobile interfaces."),
            ("Moderated Usability Testing Methods", "Covers running usability sessions where a facilitator guides participants through tasks in real time."),
            ("Unmoderated Remote Usability Testing", "Covers running usability tests where participants complete tasks independently using remote testing tools."),
            ("Think-Aloud Protocol Techniques", "Covers a research method where participants verbalize their thoughts while completing tasks."),
            ("Task Success Metrics and SUS Scoring", "Covers measuring usability outcomes with task completion rates and the System Usability Scale."),
            ("Recruiting Participants for Usability Studies", "Covers screening and recruiting representative participants for user research studies."),
            ("Prototyping Interactive States", "Covers designing hover, active, disabled, and other interface states within a prototype."),
            ("Form Interaction and Validation Design", "Covers designing real-time validation and error messaging that helps users complete forms correctly."),
            ("Notification and Alert Design", "Covers designing in-app notifications and system alerts that inform without overwhelming users."),
            ("Keyboard and Focus Interaction Design", "Covers designing visible focus states and logical tab order for keyboard-driven navigation."),
            ("Cross-Device Interaction Consistency", "Covers maintaining coherent interaction patterns as users move between phone, tablet, and desktop."),
            ("Progressive Disclosure Techniques", "Covers revealing information and options gradually to avoid overwhelming users with complexity."),
            ("Interaction Cost and Effort Reduction", "Covers minimizing the physical and cognitive effort required to complete a task in an interface."),
            ("Onboarding Flow Design", "Covers designing the first-run experience that introduces new users to a product's core value."),
            ("Empty State and Error State Design", "Covers designing helpful, informative screens for when there is no data or something has gone wrong."),
        ],
        "UG3": [
            ("Component Library Governance", "Covers processes for proposing, reviewing, and maintaining components in a shared design system."),
            ("Design Tokens and Theming", "Covers structuring design tokens to support multiple visual themes, such as light, dark, or brand variants."),
            ("Pattern Libraries vs Style Guides", "Covers the distinction between documenting reusable UI patterns and documenting visual brand standards."),
            ("Versioning Design Systems", "Covers managing updates and breaking changes in a design system without disrupting product teams."),
            ("Cross-Team Design System Adoption", "Covers strategies for encouraging multiple product teams to adopt and contribute to a shared design system."),
            ("WCAG Guidelines Deep Dive", "Covers the Web Content Accessibility Guidelines' principles, success criteria, and conformance levels."),
            ("Screen Reader Compatible Design", "Covers designing interfaces that convey meaning and structure correctly to screen reader users."),
            ("Keyboard Navigation Accessibility", "Covers ensuring all interactive elements are reachable and operable using only a keyboard."),
            ("Color Blindness and Visual Accessibility", "Covers designing interfaces that remain usable for people with various forms of color vision deficiency."),
            ("Accessible Form Design", "Covers labeling, grouping, and error-handling practices that make forms usable with assistive technology."),
            ("Inclusive Design for Cognitive Disabilities", "Covers simplifying language, layout, and interaction to support users with cognitive and learning disabilities."),
            ("Accessibility Auditing Tools and Methods", "Covers automated and manual techniques for evaluating a product's accessibility compliance."),
            ("ARIA Roles and Semantic Markup for Designers", "Covers how designers can specify semantic structure and ARIA attributes that support assistive technology."),
            ("Designing for Aging and Low-Vision Users", "Covers adapting text size, contrast, and interaction targets for older adults and users with low vision."),
            ("Accessible Data Tables and Charts", "Covers structuring tabular and visual data so it remains understandable to assistive technology users."),
            ("Legal Standards for Digital Accessibility (ADA/Section 508)", "Covers the legal requirements that govern digital accessibility for organizations in the United States."),
            ("Universal Design Principles", "Covers designing products usable by the widest range of people without the need for adaptation."),
            ("Assistive Technology Compatibility Testing", "Covers testing designs directly with screen readers, switch devices, and other assistive technologies."),
        ],
        "UG4": [
            ("Native iOS Design Guidelines (Human Interface Guidelines)", "Covers Apple's design conventions for spacing, navigation, and controls on iOS."),
            ("Native Android Design Guidelines (Material Design)", "Covers Google's Material Design system for components, motion, and layout on Android."),
            ("Cross-Platform Design Considerations", "Covers deciding when to follow platform-specific conventions versus a unified cross-platform design."),
            ("Breakpoint Strategy for Responsive Layouts", "Covers choosing screen-width breakpoints where a layout should adapt to different devices."),
            ("Touch Target Sizing and Ergonomics", "Covers sizing and spacing interactive elements for accurate, comfortable touch interaction."),
            ("Offline and Low-Connectivity UX", "Covers designing feedback and functionality for users with intermittent or no internet connection."),
            ("Design Collaboration in Figma-Style Tools", "Covers using shared, cloud-based design tools for real-time collaboration among design teams."),
            ("Version Control for Design Files", "Covers managing file versions and branching for design work, similar to source control in software."),
            ("Design-to-Code Handoff Workflows", "Covers tools and practices that translate design specifications directly into front-end code."),
            ("Plugin and Automation Use in Design Tools", "Covers using plugins and scripts to automate repetitive tasks within design software."),
            ("Prototyping with Real Data", "Covers connecting prototypes to real or realistic content and data instead of placeholder text."),
            ("Design QA and Implementation Review", "Covers reviewing a shipped feature against its design specification to catch visual and functional discrepancies."),
            ("Component-Driven Design Workflows", "Covers designing and building interfaces from a library of reusable components rather than one-off screens."),
            ("Design Ops Fundamentals", "Covers the processes, tooling, and staffing practices that help design teams operate efficiently at scale."),
            ("Remote Design Collaboration Practices", "Covers facilitating design reviews, workshops, and critiques with distributed teams."),
            ("Design File Organization and Naming Conventions", "Covers structuring design files and layers so teams can navigate and maintain them consistently."),
            ("Rapid Prototyping Sprints", "Covers running short, focused sprints to quickly prototype and validate a design concept."),
            ("Cross-Functional Design Reviews", "Covers structuring review sessions that include product, engineering, and business stakeholders alongside designers."),
        ],
        "M1": [
            ("Voice and Tone Guidelines for Products", "Covers documenting how a product should sound across different contexts, from onboarding to error messages."),
            ("Error Message Writing Best Practices", "Covers writing clear, actionable error messages that explain what happened and how to fix it."),
            ("Conversational UI and Chatbot Writing", "Covers writing dialogue and prompts for chat-based and voice interfaces."),
            ("Localization of UX Content", "Covers adapting interface text for different languages and locales, including length and cultural nuance."),
            ("Writing for Onboarding and Empty States", "Covers crafting concise, encouraging copy for first-run experiences and screens with no content yet."),
            ("Brainstorming and Ideation Facilitation", "Covers techniques for facilitating group ideation sessions that generate a wide range of design solutions."),
            ("Design Sprints (Google Ventures Method)", "Covers running a structured five-day process to rapidly prototype and test a solution to a business problem."),
            ("How Might We Framing Techniques", "Covers reframing problem statements as open-ended questions that invite creative solutions."),
            ("Co-Design and Participatory Design Methods", "Covers involving users directly as collaborators in the design process rather than only as research subjects."),
            ("Design for Voice and Conversational Interfaces", "Covers designing interaction flows for voice assistants and other conversational, screen-free interfaces."),
            ("A/B Testing for UX Decisions", "Covers using controlled experiments to decide between competing design solutions based on user behavior."),
            ("Heuristic Evaluation Frameworks", "Covers systematically reviewing an interface against established usability principles to find issues without user testing."),
            ("Diary Studies and Longitudinal Research", "Covers research methods that track user behavior and attitudes over an extended period."),
            ("Ethnographic Research Methods in UX", "Covers observing users in their natural context to understand behavior that interviews alone might miss."),
            ("Service Design and Blueprinting", "Covers mapping the front-stage and back-stage processes that together deliver a complete service experience."),
            ("Design Leadership and Critique Culture", "Covers building a healthy team culture around feedback, mentorship, and design decision-making."),
            ("Measuring UX Impact and ROI", "Covers connecting design improvements to business metrics to demonstrate the value of UX work."),
            ("UX Design Portfolio and Case Study Development", "Covers structuring project case studies that communicate a designer's process and impact to potential employers."),
        ],
    },
    "Project Management": {
        "C1": [
            ("Project Charter Development", "Covers drafting the document that formally authorizes a project and defines its objectives and authority."),
            ("Defining Project Objectives and Success Criteria", "Covers writing specific, measurable objectives that define what a project must achieve to be considered successful."),
            ("Project Stakeholder Identification", "Covers identifying everyone who affects or is affected by a project before planning begins."),
            ("Work Breakdown Structure Basics", "Covers decomposing a project's total scope into smaller, manageable work packages."),
            ("Introduction to Gantt Charts", "Covers reading and building basic Gantt charts to visualize task timing and sequence."),
            ("Project Roles and Responsibilities (RACI)", "Covers using a Responsible-Accountable-Consulted-Informed matrix to clarify who does what on a project."),
            ("Basics of Project Constraints (Triple Constraint)", "Covers the trade-offs between scope, time, and cost that constrain every project."),
            ("Introduction to Project Management Software Tools", "Surveys common software used for scheduling, task tracking, and collaboration on projects."),
            ("Project Kickoff Meeting Planning", "Covers planning an effective kickoff meeting that aligns the team and stakeholders at project start."),
            ("Basics of Task Estimation", "Covers simple techniques for estimating how long project tasks will take."),
            ("Introduction to Project Documentation", "Covers the core documents, such as the project plan and status reports, that keep a project organized."),
            ("Understanding Project Sponsors and Governance", "Covers the role of the project sponsor and basic governance structures that oversee a project."),
            ("Basics of Milestone Planning", "Covers identifying key milestones that mark significant progress points in a project timeline."),
            ("Introduction to Project Risk Identification", "Covers brainstorming and listing potential risks before they are formally analyzed."),
            ("Project Communication Basics", "Covers choosing appropriate channels and frequency for keeping stakeholders informed."),
            ("Introduction to Project Closure Activities", "Covers the basic steps taken to formally close out a project, including sign-off and documentation."),
            ("Basics of Team Formation (Tuckman's Stages)", "Covers the forming-storming-norming-performing model of how project teams develop over time."),
            ("Ethics in Project Management", "Covers professional conduct standards, such as honesty and fairness, expected of project managers."),
        ],
        "C2": [
            ("Requirements Gathering Techniques", "Covers methods such as interviews and workshops used to elicit and document project requirements."),
            ("Scope Creep Prevention", "Covers techniques for detecting and controlling unauthorized changes that expand a project's scope."),
            ("Work Package Definition", "Covers breaking down deliverables into work packages small enough to estimate and assign reliably."),
            ("Critical Path Method (CPM)", "Covers calculating the longest sequence of dependent tasks that determines a project's minimum duration."),
            ("Critical Chain Project Management", "Covers scheduling with buffers that protect a project from resource contention and task uncertainty."),
            ("Schedule Compression Techniques (Crashing & Fast-Tracking)", "Covers adding resources or overlapping tasks to shorten a project schedule."),
            ("Precedence Diagramming Method", "Covers a network diagramming technique that shows task dependencies and their logical relationships."),
            ("Resource Leveling and Smoothing", "Covers adjusting a schedule to resolve resource over-allocation while minimizing disruption to the project end date."),
            ("Baseline Management for Scope and Schedule", "Covers setting and maintaining approved baselines used to measure project performance."),
            ("Change Control Processes", "Covers the formal process for requesting, evaluating, and approving changes to a project's baseline."),
            ("Scope Verification and Acceptance", "Covers formally confirming that completed deliverables meet the requirements before sign-off."),
            ("Milestone Chart Development", "Covers building a simplified schedule view that highlights only key milestones for stakeholder communication."),
            ("Dependency Mapping Between Tasks", "Covers identifying finish-to-start and other dependency types that determine task sequencing."),
            ("Buffer Management in Scheduling", "Covers sizing and placing time buffers to protect a schedule from variability."),
            ("Rolling Wave Planning", "Covers planning near-term work in detail while leaving distant work at a higher level until more is known."),
            ("Scope Statement Writing", "Covers writing a clear scope statement that defines deliverables, boundaries, and exclusions."),
            ("Schedule Network Diagrams", "Covers building diagrams that show the logical sequence and relationships among project activities."),
            ("Time Tracking and Timesheet Management", "Covers collecting and reviewing time data to monitor effort spent against a project schedule."),
        ],
        "UG1": [
            ("Bottom-Up vs Top-Down Cost Estimating", "Compares estimating costs from detailed work packages upward against estimating from overall project parameters downward."),
            ("Earned Value Management (EVM)", "Covers using planned value, earned value, and actual cost to measure project schedule and cost performance."),
            ("Cost Baseline and Variance Analysis", "Covers comparing actual project spending against the approved budget baseline to identify variances."),
            ("Contingency and Management Reserves", "Covers setting aside funds for known and unknown risks within a project budget."),
            ("Cost-Benefit Analysis for Projects", "Covers comparing a project's expected costs against its expected benefits to support investment decisions."),
            ("Risk Register Development", "Covers building and maintaining a log of identified risks, their owners, and planned responses."),
            ("Qualitative Risk Analysis Techniques", "Covers ranking risks by probability and impact using scales rather than precise numerical estimates."),
            ("Quantitative Risk Analysis (Monte Carlo Simulation)", "Covers using simulation techniques to model the probability of different project cost and schedule outcomes."),
            ("Risk Response Strategies (Avoid, Transfer, Mitigate, Accept)", "Covers the four core strategies for responding to identified project risks."),
            ("Risk Monitoring and Control", "Covers tracking identified risks and watching for new risks throughout a project's life cycle."),
            ("Contract Types and Risk Allocation", "Covers how different contract structures shift financial risk between the buyer and the seller."),
            ("Insurance and Risk Transfer Mechanisms", "Covers using insurance and other contractual tools to transfer specific project risks to a third party."),
            ("Financial Forecasting for Projects", "Covers projecting future project costs and cash flow needs based on current performance data."),
            ("Return on Investment (ROI) Analysis for Projects", "Covers calculating expected financial return to help prioritize and justify project investments."),
            ("Cost Estimation Software Tools", "Surveys software used to build, track, and update detailed project cost estimates."),
            ("Budget Reporting and Forecasting", "Covers preparing budget status reports and forecasts of cost at completion for stakeholders."),
            ("Risk Appetite and Tolerance Frameworks", "Covers how organizations define acceptable levels of risk to guide project decision-making."),
            ("Issue Management vs Risk Management", "Distinguishes managing risks that have not yet occurred from managing issues that have already materialized."),
        ],
        "UG2": [
            ("Scrum Roles Deep Dive (Product Owner, Scrum Master)", "Covers the specific accountabilities of each Scrum role and how they collaborate."),
            ("Sprint Planning and Backlog Refinement", "Covers preparing and prioritizing the product backlog and planning the work for an upcoming sprint."),
            ("Daily Standups and Sprint Reviews", "Covers running effective daily coordination meetings and end-of-sprint demonstration events."),
            ("User Story Writing and Estimation", "Covers writing user stories with acceptance criteria and estimating their relative size."),
            ("Velocity Tracking and Burndown Charts", "Covers measuring a team's throughput over sprints and visualizing remaining work with burndown charts."),
            ("Kanban Board Design and WIP Limits", "Covers structuring a Kanban board's columns and setting work-in-progress limits to manage flow."),
            ("Lean Principles and Waste Reduction", "Covers identifying and eliminating non-value-adding activity in project workflows."),
            ("Value Stream Mapping", "Covers diagramming the end-to-end steps of a process to identify delays and inefficiencies."),
            ("Extreme Programming (XP) Practices", "Covers practices such as pair programming and test-driven development associated with the XP methodology."),
            ("Scrumban Hybrid Approaches", "Covers combining Scrum's cadence with Kanban's flow-based practices."),
            ("Retrospective Facilitation Techniques", "Covers structuring retrospectives so teams can reflect honestly and identify concrete improvements."),
            ("Definition of Done and Acceptance Criteria", "Covers establishing shared standards for when a piece of work is truly complete."),
            ("Agile Estimation Techniques (Planning Poker, T-Shirt Sizing)", "Covers collaborative estimation methods used to size backlog items relative to each other."),
            ("Continuous Improvement (Kaizen) in Projects", "Covers applying incremental, ongoing improvement practices to project processes and teams."),
            ("Agile Metrics and Reporting", "Covers metrics such as cycle time and throughput used to track agile team performance."),
            ("Servant Leadership in Agile Teams", "Covers a leadership style focused on removing obstacles and supporting team members rather than directing them."),
            ("Agile Contracts and Vendor Relationships", "Covers structuring contracts that accommodate iterative, changing scope common in agile engagements."),
            ("Transitioning from Waterfall to Agile", "Covers the organizational and process changes involved in moving a team from sequential to iterative delivery."),
        ],
        "UG3": [
            ("Stakeholder Analysis and Power-Interest Grids", "Covers mapping stakeholders by their level of influence and interest to prioritize engagement efforts."),
            ("Communication Planning and Channels", "Covers designing a communication plan that matches message type and audience to the right channel and frequency."),
            ("Managing Difficult Stakeholders", "Covers strategies for engaging stakeholders who are resistant, disengaged, or in conflict with project goals."),
            ("Negotiation Techniques for Project Managers", "Covers negotiation tactics project managers use with vendors, sponsors, and team members."),
            ("Conflict Resolution Styles and Strategies", "Covers recognizing different conflict-handling styles and choosing an appropriate resolution approach."),
            ("Building High-Performing Teams", "Covers practices that help project teams develop trust, accountability, and strong collaborative habits."),
            ("Virtual and Distributed Team Management", "Covers coordinating and motivating project teams that work across locations and time zones."),
            ("Emotional Intelligence for Project Leaders", "Covers self-awareness and empathy skills that help project managers lead teams effectively."),
            ("Motivation Theories Applied to Project Teams", "Covers applying theories of motivation to keep project team members engaged and productive."),
            ("Facilitation Skills for Meetings", "Covers running focused, productive meetings that reach clear decisions and action items."),
            ("Cross-Cultural Communication in Projects", "Covers adapting communication style for project teams and stakeholders from different cultural backgrounds."),
            ("Delegation and Empowerment Techniques", "Covers assigning ownership of tasks in a way that builds team capability and accountability."),
            ("Performance Management for Project Teams", "Covers giving feedback and evaluating contribution within a temporary project team structure."),
            ("Managing Team Burnout and Well-Being", "Covers recognizing signs of overwork and adjusting workload to sustain team health."),
            ("Executive Reporting and Status Updates", "Covers summarizing project status concisely for senior leadership audiences."),
            ("Influence Without Authority", "Covers persuading and aligning stakeholders when a project manager lacks direct authority over them."),
            ("Trust Building in Project Teams", "Covers practices that establish psychological safety and reliability within a project team."),
            ("Managing Organizational Change Resistance", "Covers techniques for addressing resistance when a project introduces significant organizational change."),
        ],
        "UG4": [
            ("Quality Planning and Standards (ISO 9001)", "Covers defining quality requirements and referencing standards such as ISO 9001 in project planning."),
            ("Quality Assurance vs Quality Control", "Distinguishes process-focused quality assurance from product-focused quality control activities."),
            ("Six Sigma Fundamentals for Projects", "Covers the DMAIC framework and statistical tools used to reduce defects in project processes."),
            ("Statistical Process Control Basics", "Covers using control charts to monitor whether a process is operating within expected variation."),
            ("Root Cause Analysis Techniques (Fishbone, 5 Whys)", "Covers structured techniques for tracing a quality problem back to its underlying cause."),
            ("Quality Audits and Inspections", "Covers conducting formal reviews to verify that project work complies with quality requirements."),
            ("Continuous Quality Improvement Frameworks", "Covers frameworks such as Plan-Do-Check-Act used to iteratively improve project quality."),
            ("Procurement Planning and Make-or-Buy Decisions", "Covers deciding which project work should be performed internally versus purchased from external vendors."),
            ("Request for Proposal (RFP) Development", "Covers writing a document that solicits competitive proposals from potential vendors."),
            ("Vendor Selection and Evaluation Criteria", "Covers defining criteria and scoring methods used to select among competing vendors."),
            ("Contract Negotiation Fundamentals", "Covers preparing for and conducting negotiations to reach favorable, workable contract terms."),
            ("Contract Types (Fixed-Price, Cost-Reimbursable, Time & Materials)", "Covers the major contract structures and the risk trade-offs each presents to buyer and seller."),
            ("Vendor Performance Management", "Covers monitoring vendor deliverables against contractual commitments throughout a project."),
            ("Procurement Risk Management", "Covers identifying and mitigating risks specific to sourcing goods and services from external parties."),
            ("Outsourcing vs In-House Delivery Decisions", "Covers evaluating the trade-offs between outsourcing project work and delivering it with internal teams."),
            ("Supply Chain Considerations in Projects", "Covers how upstream supply chain dependencies can affect project schedule and cost."),
            ("Contract Closeout Procedures", "Covers the steps required to formally close a contract, including final payment and documentation."),
            ("Ethics in Vendor Relationships", "Covers fair dealing, conflict-of-interest avoidance, and transparency in managing vendor relationships."),
        ],
        "M1": [
            ("Portfolio Prioritization Frameworks", "Covers scoring models and frameworks used to rank and select projects within a portfolio."),
            ("Portfolio Balancing and Resource Allocation", "Covers allocating limited organizational resources across a portfolio of competing projects."),
            ("Benefits Realization Management", "Covers tracking whether a project's intended business benefits are actually achieved after completion."),
            ("Program Governance Structures", "Covers the oversight bodies and decision rights that govern a program of related projects."),
            ("Program Roadmap Development", "Covers sequencing related projects within a program into a coherent, time-phased roadmap."),
            ("Managing Interdependencies Across Projects", "Covers identifying and coordinating dependencies between projects that share a program."),
            ("PMO Structures and Functions", "Covers the different models a Project Management Office can take, from supportive to directive."),
            ("PMO Maturity Models", "Covers frameworks for assessing and improving how well a PMO's practices are established across an organization."),
            ("Organizational Project Management Maturity", "Covers models used to assess how consistently an organization applies project management practices."),
            ("Strategic Alignment of Projects to Business Goals", "Covers ensuring individual projects contribute measurably to broader organizational strategy."),
            ("Business Case Development", "Covers writing the justification document that supports a decision to invest in a project."),
            ("Project Management Software Tool Selection (Enterprise)", "Covers evaluating enterprise-scale project and portfolio management software for organization-wide use."),
            ("AI and Automation in Project Management", "Covers how AI-assisted tools support scheduling, risk forecasting, and status reporting in modern project management."),
            ("Data-Driven Decision Making in Project Portfolios", "Covers using performance data and analytics to guide decisions about which projects to fund or stop."),
            ("Managing Multi-Vendor Programs", "Covers coordinating deliverables and accountability across programs involving several external vendors."),
            ("Global and Multi-Site Program Management", "Covers managing programs that span multiple countries, time zones, and regulatory environments."),
            ("Project Management Career Certification Paths (PMP, PRINCE2)", "Surveys major professional certifications and the career paths they support in project management."),
            ("Capstone Program Simulation: Multi-Project Delivery", "Applies course concepts to a simulated program requiring coordination of scope, schedule, risk, and stakeholders across multiple projects."),
        ],
    },
    "Finance": {
        "C1": [
            ("Budgeting and Cash Flow Management", "Covers building a personal budget and tracking cash inflows and outflows to stay financially organized."),
            ("Saving Strategies and Emergency Funds", "Covers building savings habits and sizing an emergency fund to cover unexpected expenses."),
            ("Understanding Credit Scores and Reports", "Covers how credit scores are calculated and how to read a credit report for accuracy."),
            ("Basics of Bank Accounts and Financial Institutions", "Covers the differences between checking, savings, and other common accounts offered by banks and credit unions."),
            ("Introduction to Taxes and Tax Filing", "Covers the basics of income tax brackets, deductions, and the process of filing a tax return."),
            ("Understanding Interest Rates (Simple vs Compound)", "Covers how simple and compound interest are calculated and why the difference matters for savers and borrowers."),
            ("Basics of Insurance Products", "Covers common personal insurance types, including health, auto, and life insurance, and how they manage risk."),
            ("Introduction to Retirement Accounts", "Covers common retirement savings vehicles and the basic tax advantages each offers."),
            ("Reading the Balance Sheet", "Covers interpreting assets, liabilities, and equity as reported on a company's balance sheet."),
            ("Reading the Income Statement", "Covers interpreting revenue, expenses, and profit as reported on a company's income statement."),
            ("Reading the Cash Flow Statement", "Covers interpreting operating, investing, and financing cash flows reported by a company."),
            ("Basics of Financial Ratios", "Covers common ratios, such as current ratio and debt-to-equity, used to assess financial health."),
            ("Introduction to Debt Management", "Covers strategies for managing and paying down personal debt, including credit cards and loans."),
            ("Understanding Inflation and Purchasing Power", "Covers how inflation erodes the purchasing power of money over time."),
            ("Basics of Financial Goal Setting", "Covers setting specific, time-bound financial goals and building a plan to reach them."),
            ("Introduction to Financial Fraud and Scams", "Covers common types of financial fraud and basic practices for protecting personal finances."),
            ("Basics of Consumer Loans and Mortgages", "Covers how installment loans and mortgages work, including principal, interest, and amortization."),
            ("Introduction to Financial Literacy Tools", "Surveys budgeting apps, calculators, and other tools that support everyday personal finance decisions."),
        ],
        "C2": [
            ("Present Value and Future Value Calculations", "Covers calculating what a sum of money today is worth in the future, and vice versa, given an interest rate."),
            ("Annuities and Perpetuities", "Covers valuing streams of equal periodic payments, including those that continue indefinitely."),
            ("Loan Amortization Schedules", "Covers building a schedule that shows how each loan payment splits between principal and interest over time."),
            ("Net Present Value (NPV) Basics", "Covers calculating the present value of a project's future cash flows minus its initial investment."),
            ("Internal Rate of Return (IRR) Basics", "Covers the discount rate at which a project's net present value equals zero, and how it is used to evaluate investments."),
            ("Discounting Cash Flow Streams", "Covers applying a discount rate to a series of future cash flows to express them in present-day terms."),
            ("Risk Measurement (Standard Deviation, Variance)", "Covers using statistical measures to quantify the volatility of an investment's returns."),
            ("Risk-Free Rate and Risk Premiums", "Covers how the risk-free rate serves as a baseline and how risk premiums compensate investors for additional risk."),
            ("Diversifiable vs Non-Diversifiable Risk", "Distinguishes risk that can be reduced through diversification from market-wide risk that cannot."),
            ("Introduction to the Capital Asset Pricing Model (CAPM)", "Covers the CAPM formula relating expected return to systematic risk."),
            ("Beta and Systematic Risk", "Covers how beta measures an asset's sensitivity to overall market movements."),
            ("Expected Return Calculations", "Covers calculating the probability-weighted average of possible investment returns."),
            ("Real vs Nominal Interest Rates", "Distinguishes stated interest rates from those adjusted for inflation."),
            ("Compounding Frequency Effects", "Covers how compounding annually, monthly, or daily changes the effective return on an investment."),
            ("Bond Pricing Basics Using Present Value", "Covers pricing a bond as the present value of its coupon payments and face value."),
            ("Risk Aversion and Utility Theory", "Covers how investor risk preferences are modeled using utility functions."),
            ("Time Value Applications in Retirement Planning", "Covers applying present and future value calculations to project retirement savings needs."),
            ("Sensitivity Analysis in Financial Decisions", "Covers testing how changes in key assumptions affect the outcome of a financial calculation."),
        ],
        "UG1": [
            ("Capital Structure Basics (Debt vs Equity)", "Covers the trade-offs firms weigh when choosing between debt and equity financing."),
            ("Working Capital Management", "Covers managing a firm's short-term assets and liabilities to maintain liquidity."),
            ("Payback Period and Discounted Payback Analysis", "Covers estimating how long it takes an investment to recover its initial cost, with and without discounting."),
            ("Profitability Index Method", "Covers a capital budgeting metric that compares the present value of returns to the initial investment."),
            ("Capital Rationing Decisions", "Covers selecting among competing projects when a firm has a limited capital budget."),
            ("Sunk Costs and Opportunity Costs in Capital Decisions", "Covers why sunk costs should be ignored and opportunity costs included in investment decisions."),
            ("Incremental Cash Flow Analysis", "Covers isolating the additional cash flows a project causes compared to not undertaking it."),
            ("Replacement Analysis for Capital Projects", "Covers evaluating whether to replace an existing asset with a newer one based on incremental costs and benefits."),
            ("Break-Even Analysis for Investment Decisions", "Covers calculating the sales or output level at which a project's revenues equal its costs."),
            ("Financial Planning and Pro Forma Statements", "Covers building forward-looking financial statements to plan for a company's future performance."),
            ("Dividend Policy Fundamentals", "Covers how firms decide whether and how much of earnings to distribute to shareholders."),
            ("Sources of Short-Term Financing", "Covers financing options such as trade credit and short-term loans used to fund working capital needs."),
            ("Sources of Long-Term Financing", "Covers financing options such as bonds, term loans, and equity issuance used to fund long-term investments."),
            ("Leasing vs Buying Decisions", "Covers comparing the financial implications of leasing an asset versus purchasing it outright."),
            ("Capital Budgeting Under Uncertainty", "Covers adjusting capital budgeting analysis to account for uncertain future cash flows."),
            ("Real Options in Capital Budgeting", "Covers valuing the flexibility to expand, delay, or abandon a project as conditions change."),
            ("Corporate Financial Distress Basics", "Covers early indicators and financial consequences of a firm approaching insolvency."),
            ("Agency Theory in Corporate Finance", "Covers conflicts of interest between managers and shareholders and mechanisms used to align them."),
        ],
        "UG2": [
            ("Weighted Average Cost of Capital (WACC) Calculation", "Covers combining the cost of debt and equity, weighted by capital structure, into a single discount rate."),
            ("Cost of Debt Estimation", "Covers estimating a firm's after-tax cost of borrowing using yields or credit spreads."),
            ("Cost of Equity Estimation (CAPM, Dividend Growth Model)", "Covers two common approaches for estimating the return equity investors require."),
            ("Marginal Cost of Capital Schedule", "Covers how a firm's cost of capital changes as it raises additional financing."),
            ("Optimal Capital Structure Theories (Modigliani-Miller)", "Covers the Modigliani-Miller propositions on capital structure irrelevance and their real-world assumptions."),
            ("Trade-Off Theory of Capital Structure", "Covers how firms balance the tax benefits of debt against the costs of financial distress."),
            ("Pecking Order Theory", "Covers the theory that firms prefer internal financing, then debt, then equity, based on information asymmetry."),
            ("Stock Market Mechanics and Order Types", "Covers how stock exchanges match buyers and sellers and the different order types investors use."),
            ("Initial Public Offerings (IPOs)", "Covers the process by which a private company offers shares to the public for the first time."),
            ("Secondary Market Trading", "Covers how securities are bought and sold among investors after their initial issuance."),
            ("Market Efficiency and the Efficient Market Hypothesis", "Covers the theory that asset prices reflect available information and its implications for investors."),
            ("Stock Valuation Using Dividend Discount Models", "Covers valuing a stock as the present value of its expected future dividends."),
            ("Price-to-Earnings and Other Valuation Multiples", "Covers using ratios such as P/E to compare a company's valuation against peers."),
            ("Equity Research Fundamentals", "Covers how analysts research companies and industries to form investment recommendations."),
            ("Stock Indices and Benchmarking", "Covers how market indices are constructed and used to benchmark investment performance."),
            ("Short Selling and Margin Trading", "Covers borrowing shares to bet on price declines and using borrowed funds to amplify investment positions."),
            ("Corporate Actions (Splits, Buybacks, Spin-offs)", "Covers how corporate actions change a company's share structure and what they signal to investors."),
            ("Equity Crowdfunding", "Covers how startups raise small amounts of equity capital from a large number of investors online."),
        ],
        "UG3": [
            ("Bond Types and Features (Government, Corporate, Municipal)", "Surveys the major categories of bonds and the features, such as tax treatment, that distinguish them."),
            ("Yield to Maturity Calculations", "Covers calculating the total return an investor earns by holding a bond until it matures."),
            ("Bond Duration and Convexity", "Covers measures of a bond's price sensitivity to changes in interest rates."),
            ("Credit Ratings and Default Risk", "Covers how rating agencies assess the likelihood a bond issuer will fail to make payments."),
            ("Term Structure of Interest Rates (Yield Curve)", "Covers how interest rates vary across bond maturities and what different yield curve shapes indicate."),
            ("Callable and Convertible Bonds", "Covers bonds with embedded options that let the issuer redeem early or the holder convert to equity."),
            ("Bond Portfolio Immunization Strategies", "Covers matching bond portfolio duration to a liability to protect against interest rate risk."),
            ("Modern Portfolio Theory and the Efficient Frontier", "Covers combining assets to maximize expected return for a given level of risk."),
            ("Diversification and Correlation Effects", "Covers how combining assets with low or negative correlation reduces overall portfolio risk."),
            ("Capital Market Line and Security Market Line", "Covers two graphical models relating risk and expected return for efficient portfolios and individual securities."),
            ("Portfolio Rebalancing Strategies", "Covers periodically adjusting portfolio holdings back to target asset allocation weights."),
            ("Asset Allocation Strategies", "Covers dividing an investment portfolio among asset classes based on goals, risk tolerance, and time horizon."),
            ("Sharpe Ratio and Risk-Adjusted Performance", "Covers measuring investment returns relative to the risk taken to achieve them."),
            ("Factor Investing Models", "Covers investment approaches that target factors such as value, size, and momentum to explain returns."),
            ("Passive vs Active Portfolio Management", "Compares index-tracking investment strategies against strategies that seek to outperform the market."),
            ("Exchange-Traded Funds (ETFs) and Index Investing", "Covers how ETFs work and their role in low-cost, diversified index investing."),
            ("International Portfolio Diversification", "Covers the benefits and risks of adding foreign assets to an investment portfolio."),
            ("Alternative Investments (Real Estate, Commodities)", "Surveys non-traditional asset classes and their role in a diversified portfolio."),
        ],
        "UG4": [
            ("Forward and Futures Contracts", "Covers agreements to buy or sell an asset at a set price on a future date, and how forwards differ from futures."),
            ("Options Basics (Calls and Puts)", "Covers the rights and obligations created by call and put options and basic payoff diagrams."),
            ("Option Pricing Models (Black-Scholes Overview)", "Introduces the inputs and intuition behind the Black-Scholes model for pricing options."),
            ("Hedging Strategies with Derivatives", "Covers using derivatives to offset exposure to price, interest rate, or currency risk."),
            ("Swaps and Interest Rate Derivatives", "Covers how interest rate and currency swaps let parties exchange cash flow streams."),
            ("Speculation vs Hedging with Derivatives", "Distinguishes using derivatives to bet on price movements from using them to reduce existing risk."),
            ("Commercial Banking Functions and Regulation", "Covers how commercial banks take deposits, extend credit, and operate under regulatory oversight."),
            ("Central Banks and Monetary Policy", "Covers how central banks use interest rates and other tools to influence the economy."),
            ("Investment Banking Services Overview", "Surveys underwriting, M&A advisory, and other core services investment banks provide."),
            ("Money Market Instruments", "Covers short-term, highly liquid instruments such as Treasury bills and commercial paper."),
            ("Shadow Banking and Non-Bank Financial Institutions", "Covers credit intermediation that occurs outside the traditional regulated banking system."),
            ("Financial Regulation and Compliance Basics", "Surveys the regulatory bodies and major rules that govern financial institutions and markets."),
            ("Payment Systems and Clearing Houses", "Covers how transactions are settled and cleared between financial institutions."),
            ("Credit Unions and Community Banking", "Covers how member-owned credit unions and community banks differ from large commercial banks."),
            ("Insurance Companies as Financial Intermediaries", "Covers how insurers pool risk and invest premiums, functioning as major institutional investors."),
            ("Pension Funds and Institutional Investors", "Covers how pension funds and other large institutional investors manage long-term liabilities."),
            ("Financial Market Crises and Systemic Risk", "Covers how risk can spread across interconnected institutions to threaten the broader financial system."),
            ("Cryptocurrency and Digital Asset Markets", "Covers how cryptocurrencies and digital assets are traded and the risks distinct to these markets."),
        ],
        "M1": [
            ("Discounted Cash Flow (DCF) Valuation Modeling", "Covers building a DCF model that projects and discounts a company's future free cash flows to estimate value."),
            ("Comparable Company Analysis", "Covers valuing a company by comparing its multiples to those of similar publicly traded companies."),
            ("Precedent Transaction Analysis", "Covers valuing a company based on multiples paid in comparable past mergers and acquisitions."),
            ("Sum-of-the-Parts Valuation", "Covers valuing a diversified company by separately valuing each of its business segments."),
            ("Valuing Private Companies", "Covers adjustments, such as illiquidity discounts, used when valuing companies without a public market price."),
            ("Merger and Acquisition Valuation Techniques", "Covers valuation methods and synergy considerations specific to evaluating a potential acquisition."),
            ("Leveraged Buyout (LBO) Basics", "Covers how acquisitions financed largely with debt are structured and modeled."),
            ("Synergy Valuation in M&A", "Covers estimating and valuing the cost savings and revenue gains expected from combining two companies."),
            ("Behavioral Biases: Overconfidence and Anchoring", "Covers how overconfidence and anchoring biases distort investor judgment and decision-making."),
            ("Loss Aversion and Prospect Theory", "Covers how investors weigh losses more heavily than equivalent gains, and its effect on decisions."),
            ("Herding Behavior in Financial Markets", "Covers why investors sometimes follow the crowd rather than act on independent analysis."),
            ("Market Anomalies and Bubbles", "Covers patterns in asset prices that are difficult to explain with traditional efficient market theory."),
            ("Corporate Governance and Agency Costs", "Covers how boards, ownership structure, and incentives affect the costs arising from manager-shareholder conflicts."),
            ("International Finance and Exchange Rate Risk", "Covers how currency fluctuations affect multinational firms and how that risk can be managed."),
            ("Private Equity and Venture Capital Fundamentals", "Covers how private equity and venture capital firms raise, invest, and exit capital in private companies."),
            ("Fintech and Digital Finance Innovations", "Covers how technology-driven innovation is reshaping payments, lending, and investment services."),
            ("Environmental, Social, and Governance (ESG) Investing", "Covers incorporating environmental, social, and governance factors into investment analysis and decisions."),
            ("Capstone Financial Analysis and Valuation Project", "Applies course concepts to a comprehensive financial analysis and valuation of a real or simulated company."),
        ],
    },
}
