"""Module topics bringing English, Science, Geography, and World History
up to 20+ lessons per level (C1 through M1)."""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "English": {
        "C1": [
            ("Understanding the Rhetorical Situation", "Introduces audience, purpose, and occasion as the core factors that shape any written text."),
            ("The Building Blocks of the Argumentative Essay", "Covers claim, evidence, counterargument, and warrant as the basic parts of a persuasive essay."),
            ("Close Reading: Annotating for Meaning", "Teaches how to mark up a text to trace tone, diction, and imagery while reading closely."),
            ("Sentence Grammar Essentials", "Reviews clauses, phrases, and parts of speech in the context of real sentences."),
            ("Finding Your Voice: An Introduction to Style", "Explores word choice, sentence rhythm, and tone as ingredients of a writer's voice."),
            ("The Research Question and the Thesis Statement", "Shows how to narrow a broad topic into a focused, arguable thesis statement."),
            ("Introduction to Citation: Why We Cite Sources", "Explains why writers cite sources, covering plagiarism and the basics of giving credit."),
            ("Writing Clear Instructions and Emails", "Covers plain-language conventions for everyday professional writing like emails and instructions."),
            ("First Steps in Creative Writing", "Introduces the basics of short fiction and free verse poetry as creative forms."),
            ("What Is Literary Theory? A First Look", "Introduces the idea that a single text can be read through different critical lenses."),
            ("Introducing Shakespeare: Language and Stagecraft", "Covers blank verse, the soliloquy, and Elizabethan theater conventions in Shakespeare's plays."),
            ("What Makes a Novel a Novel?", "Introduces plot, character, and narrative structure as the basic elements of the novel form."),
            ("Reading Poetry Aloud: Rhythm and Rhyme", "Covers meter, rhyme scheme, and sound devices as tools for reading poetry aloud."),
            ("A World of Stories: Introduction to Anglophone Literature", "Surveys English-language literature written outside Britain and the United States."),
            ("Editing Your Own Draft", "Teaches proofreading strategies and how to spot common error patterns in a draft."),
            ("Speaking to a Group: Basics of Public Speaking", "Covers how to organize and deliver a short spoken presentation to an audience."),
            ("Writing for the Screen: Intro to Digital Composition", "Introduces blog posts, captions, and other multimodal texts as forms of composition."),
            ("Where English Came From", "Traces a brief history of the English language from Old English to the present day."),
        ],
        "C2": [
            ("Ethos, Pathos, and Logos in Practice", "Analyzes how persuasive appeals operate in real speeches and advertisements."),
            ("Structuring the Multi-Paragraph Argument", "Covers how to organize claims and evidence across a longer, multi-paragraph essay."),
            ("Close Reading Poetry vs. Prose", "Compares how annotation strategies must adapt when reading poetry versus prose."),
            ("Syntax and Sentence Variety", "Teaches how combining clauses in different ways creates emphasis and flow."),
            ("Tone and Register", "Explores how writers adjust formality and word choice for different audiences."),
            ("Evaluating Sources for Credibility", "Teaches how to distinguish scholarly, journalistic, and unreliable sources."),
            ("MLA Style Basics", "Covers in-text citations and Works Cited formatting under MLA style."),
            ("Writing a Formal Business Letter and Memo", "Covers professional formatting conventions for business letters and memos."),
            ("Elements of Short Fiction", "Covers plot arcs, point of view, and characterization through short-fiction exercises."),
            ("New Criticism and Close Reading as Theory", "Introduces New Criticism's approach of treating the text as a self-contained object."),
            ("Shakespearean Comedy", "Examines mistaken identity, wordplay, and resolution across Shakespeare's comedies."),
            ("Narrative Point of View in the Novel", "Compares first-person, third-person limited, and omniscient narration in novels."),
            ("Introduction to Poetic Form", "Compares the sonnet, the ode, and free verse as distinct poetic forms."),
            ("Post-Colonial Voices in English", "Surveys literature from formerly colonized, English-speaking nations."),
            ("Peer Review and Revision Strategies", "Covers how to give and use peer feedback effectively during revision."),
            ("Organizing a Persuasive Speech", "Covers how to structure a spoken argument that builds toward a call to action."),
            ("Composing with Images and Text", "Introduces captions, infographics, and basic visual rhetoric."),
            ("Dialects and Varieties of English", "Surveys regional and social variation in English vocabulary and grammar."),
        ],
        "UG1": [
            ("Toulmin's Model of Argument", "Introduces claim, data, warrant, backing, and rebuttal as parts of the Toulmin model."),
            ("The Five-Paragraph Essay and Beyond", "Examines moving past the five-paragraph formula toward more flexible essay structures."),
            ("Close Reading for Ambiguity and Irony", "Teaches how to identify multiple or conflicting meanings within a text."),
            ("Syntax Trees and Sentence Diagramming", "Introduces diagramming as a way to visualize grammatical structure."),
            ("Voice and Point of View in Nonfiction", "Compares voice in the personal essay and the reported nonfiction piece."),
            ("Developing a Literature Review", "Covers how to synthesize prior scholarship into a coherent literature review."),
            ("APA Style Fundamentals", "Covers author-date in-text citation and reference list conventions under APA style."),
            ("Technical Writing: Instructions and Reports", "Covers audience analysis for writing instructions and reports for specialized readers."),
            ("Workshop: Writing the Short Story", "Guides students through drafting a complete original short story."),
            ("Structuralism and the Study of Narrative", "Introduces Saussure's sign, binary oppositions, and narrative grammar in structuralist theory."),
            ("Shakespearean Tragedy", "Examines hamartia, catharsis, and the tragic hero in plays such as Hamlet and Macbeth."),
            ("The Bildungsroman and the Coming-of-Age Novel", "Examines the novel of formation as a distinct literary genre."),
            ("Meter and Scansion", "Teaches how to scan lines of poetry for iambic pentameter and other metrical patterns."),
            ("Caribbean and African Anglophone Literature", "Surveys major Caribbean and African writers working in English."),
            ("Line Editing vs. Developmental Editing", "Distinguishes sentence-level line editing from larger-scale developmental editing."),
            ("Rhetoric in Political Speech", "Analyzes rhetorical strategies in campaign and policy speeches."),
            ("Podcasting and Audio Composition", "Covers scripting and structuring a spoken-audio composition."),
            ("Grammatical Change in Middle English", "Traces the shift from Old English inflection toward a more analytic grammar."),
        ],
        "UG2": [
            ("Applying Toulmin Analysis to Editorial Writing", "Applies the Toulmin model to dissect the argument structure of published editorials."),
            ("Counterargument and Refutation Strategies", "Covers how writers anticipate and respond to opposing viewpoints."),
            ("Close Reading Difficult Modernist Prose", "Works through fragmented or nonlinear modernist prose using close-reading strategies."),
            ("Style Through Syntax: Parallelism and Periodic Sentences", "Examines parallelism and periodic sentences as sentence-level stylistic devices."),
            ("Voice Across Genres", "Compares how authorial voice shifts across essay, fiction, and journalism."),
            ("Conducting Primary Source Research", "Covers using archives, interviews, and other firsthand materials in research."),
            ("Chicago Style: Notes and Bibliography", "Covers footnote and endnote citation conventions under Chicago style."),
            ("Writing Grant Proposals and Project Reports", "Covers persuasive technical writing aimed at securing project funding."),
            ("Workshop: Writing Poetry", "Guides students through drafting and revising original poems."),
            ("Feminist Literary Theory", "Introduces feminist literary theory's focus on gender, voice, and power in the canon."),
            ("Shakespeare's History Plays", "Examines the tetralogies and the politics of kingship in Shakespeare's history plays."),
            ("The Epistolary and Frame Narrative Novel", "Examines novels structured as letters or as stories nested within stories."),
            ("Free Verse and the Break from Meter", "Traces the move to free verse from Whitman through modernist poetry."),
            ("South Asian and Australian Anglophone Literature", "Surveys literary traditions in English from South Asia and Australia."),
            ("Editing for Concision and Clarity", "Covers techniques for cutting wordiness while preserving meaning."),
            ("Debate and Rebuttal Techniques", "Covers formal argumentation techniques used in spoken debate."),
            ("Writing for Social Media and Web Platforms", "Covers adapting rhetorical strategy to the constraints of digital platforms."),
            ("Language Contact and Borrowing in English", "Examines loanwords, pidgins, and creoles as products of language contact."),
        ],
        "UG3": [
            ("Rhetorical Analysis of Legal and Judicial Language", "Analyzes argument structure and rhetorical strategy in court opinions."),
            ("Advanced Argument: Rogerian and Dialectical Approaches", "Compares conciliatory Rogerian argument with dialectical argument models."),
            ("Close Reading Postmodern Metafiction", "Examines texts that call attention to their own construction as fiction."),
            ("Advanced Syntax: Ambiguity and Garden-Path Sentences", "Examines how sentence structure creates ambiguity and misreading."),
            ("Authorial Style Analysis", "Compares stylistic fingerprints across different authors' prose."),
            ("Advanced Research Methodology: Synthesis and Meta-Analysis", "Covers methods for combining findings across multiple studies or sources."),
            ("Comparing Citation Systems Across Disciplines", "Examines why academic disciplines differ in their citation norms and systems."),
            ("Usability and Plain Language in Technical Documents", "Covers writing technical documents for comprehension and accessibility."),
            ("Workshop: The Novella and Long-Form Fiction", "Guides students in sustaining plot and character over a longer work of fiction."),
            ("Postcolonial Theory: Said, Spivak, and the Subaltern", "Introduces postcolonial theory's concern with power, representation, and the colonial gaze."),
            ("Shakespeare's Late Romances", "Examines genre-blending in late plays such as The Tempest and The Winter's Tale."),
            ("The Novel of Ideas", "Examines fiction structured around philosophical or ideological debate."),
            ("Prosody and the Sound of Poetry", "Covers assonance, consonance, and enjambment as tools of poetic sound."),
            ("Contemporary Anglophone Fiction", "Surveys twenty-first-century English-language novels from across the globe."),
            ("Editing for Voice Consistency in Long Manuscripts", "Covers maintaining a consistent tone across a full-length manuscript."),
            ("Rhetoric of Social Movements", "Analyzes protest speech and collective persuasion in social movements."),
            ("Podcast and Video Essay Composition", "Covers composing long-form multimedia argumentation for audio and video."),
            ("Language Standardization and Prescriptivism", "Examines dictionaries, style guides, and the idea of correct English."),
        ],
        "UG4": [
            ("Independent Rhetorical Analysis Project", "Guides an independent, in-depth rhetorical analysis of a self-selected persuasive text."),
            ("Capstone Argumentative Essay", "Guides students through writing a fully developed, thesis-driven research argument."),
            ("Close Reading Portfolio", "Compiles a portfolio of annotated close readings drawn from multiple genres."),
            ("Style Guide Development Project", "Guides students in compiling a personal or organizational writing style guide."),
            ("Voice in the Personal Essay", "Guides students through drafting a capstone personal narrative essay."),
            ("Capstone Research Paper: Methodology Design", "Guides students in designing an original research question and methodology."),
            ("Annotated Bibliography Capstone", "Guides students in compiling and evaluating sources in a chosen citation style."),
            ("Professional Portfolio: Technical Writing Samples", "Guides students in assembling a portfolio of workplace-style technical documents."),
            ("Capstone Creative Writing Portfolio", "Guides students in assembling a polished collection of original fiction or poetry."),
            ("Applying Literary Theory: A Comparative Project", "Guides students in applying two theoretical lenses to a single literary text."),
            ("Shakespeare Capstone: A Single-Play Deep Study", "Guides a sustained analysis of one Shakespeare play in both text and performance."),
            ("The Contemporary Novel Seminar", "Provides close study of a recent, critically significant novel."),
            ("Poetry Analysis Capstone", "Guides a sustained explication of a poem or a poet's body of work."),
            ("World Anglophone Literature Capstone", "Guides a comparative study across two regional Anglophone literatures."),
            ("Capstone Revision Project", "Guides a draft through multiple full cycles of revision."),
            ("Capstone Public Speech", "Guides students through researching, drafting, and delivering an original speech."),
            ("Multimedia Capstone Project", "Guides students in composing a piece that integrates text, image, and audio."),
            ("Sociolinguistic Field Project", "Guides students in observing and analyzing real language variation in use."),
        ],
        "M1": [
            ("Graduate Seminar: Rhetorical Theory from Aristotle to the Present", "Surveys the history of rhetorical thought from classical antiquity to modern theory."),
            ("Graduate Seminar: Argumentation Theory", "Examines formal and informal logic as applied to written argument."),
            ("Graduate Close Reading: Theory-Driven Interpretation", "Guides interpretation of a text through a specified critical theoretical lens."),
            ("Graduate Syntax: Generative Grammar Overview", "Introduces transformational-generative approaches to sentence structure."),
            ("Graduate Style Studies: The History of Prose Style", "Traces how English prose style has changed across literary history."),
            ("Graduate Research Methodology: Designing a Thesis", "Guides the planning of a long-form graduate research project."),
            ("Citation and Scholarly Apparatus at the Graduate Level", "Covers advanced source management and citation tools for scholarly writing."),
            ("Graduate Professional and Technical Writing", "Covers writing for publication and specialized professional audiences."),
            ("Graduate Creative Writing Workshop", "Provides advanced manuscript development and critique for creative work."),
            ("Graduate Literary Theory Seminar", "Examines structuralism, poststructuralism, and their critiques in depth."),
            ("Shakespeare in Graduate Study: Textual and Performance Criticism", "Covers editions, adaptation, and stage history in Shakespeare studies."),
            ("Theorizing the Novel", "Introduces Bakhtin's concept of the dialogic and theories of the novel as genre."),
            ("Graduate Prosody: Metrical Theory", "Covers generative and linguistic approaches to the study of poetic meter."),
            ("Graduate Seminar: World Anglophone Literature and Globalization", "Examines literature in a global literary marketplace."),
            ("Scholarly Editing and Textual Criticism", "Covers the methods of preparing a critical edition of a literary text."),
            ("Graduate Rhetoric: Deliberative, Forensic, and Epideictic Oratory", "Revisits the classical genres of rhetoric at an advanced level."),
            ("Graduate Digital Humanities: Text and Media Composition", "Covers computational approaches to composition and textual analysis."),
            ("Capstone Graduate Research Essay in English", "Guides students in producing an original, contribution-level research essay."),
        ],
    },
    "Science": {
        "C1": [
            ("What Is the Scientific Method?", "Introduces observation, hypothesis, experiment, and conclusion as the core steps of scientific inquiry."),
            ("Variables and Controls in Experiments", "Explains independent, dependent, and controlled variables in a simple experiment."),
            ("Why Science Changes: An Introduction to Scientific Revolutions", "Introduces the idea that scientific understanding is revised as new evidence emerges."),
            ("What Is Interdisciplinary Science?", "Introduces how biology, chemistry, and physics overlap in real scientific problems."),
            ("Explaining Science to a General Audience", "Covers the basics of communicating scientific ideas clearly to non-experts."),
            ("Asking a Good Research Question", "Covers how to turn curiosity into a focused, testable research question."),
            ("Reading a Bar Chart and a Line Graph", "Builds basic data literacy for interpreting common scientific graphs."),
            ("Safety Rules in the Science Laboratory", "Covers protective equipment and safe handling of materials in the lab."),
            ("Why Repeating Experiments Matters", "Introduces the concept of replication and why repeating experiments builds confidence in results."),
            ("Honesty in Reporting Data", "Introduces research ethics through the importance of honestly reporting data."),
            ("How Science Shapes Public Policy", "Gives simple examples of how scientific findings inform laws and regulations."),
            ("What Is Citizen Science?", "Introduces how everyday people contribute data to real scientific research."),
            ("Science in the News: Evaluating Claims", "Teaches how to spot oversimplified or exaggerated science reporting."),
            ("New and Emerging Technologies", "Introduces emerging fields such as artificial intelligence and biotechnology."),
            ("What Is Environmental Science?", "Introduces how living things interact with and depend on their surroundings."),
            ("Earth's Climate System: The Basics", "Distinguishes weather from climate and introduces the greenhouse effect."),
            ("How Diseases Spread", "Introduces germs, transmission, and the basics of public health."),
            ("Food and the Body: Basics of Nutrition", "Introduces macronutrients and the components of a balanced diet."),
        ],
        "C2": [
            ("Forming and Testing a Hypothesis", "Guides students in designing a simple experiment step by step, from hypothesis to conclusion."),
            ("Correlation vs. Causation", "Explains why a relationship between two variables is not proof that one causes the other."),
            ("Paradigm Shifts: An Introduction to Kuhn's Idea", "Introduces the concept of a scientific paradigm and how paradigms can shift."),
            ("Biochemistry Basics: Where Biology Meets Chemistry", "Introduces the molecules and chemical reactions that make life possible."),
            ("Writing a Science Report for Non-Experts", "Covers translating technical findings into plain language for general readers."),
            ("Designing a Simple Controlled Experiment", "Guides building a testable experimental procedure from a research question."),
            ("Basic Statistics: Mean, Median, and Variability", "Introduces descriptive statistics used to summarize a data set."),
            ("Proper Handling of Chemicals and Equipment", "Covers safety data sheets and hazard symbols for laboratory chemicals."),
            ("Case Study: A Famous Failed Replication", "Examines one well-documented case where a scientific result could not be replicated."),
            ("Conflicts of Interest in Research", "Examines how funding sources and personal bias can affect research findings."),
            ("Science Policy and Regulation Basics", "Introduces how government agencies use science to set safety and health standards."),
            ("Contributing to a Citizen Science Project", "Examines examples like bird counts and galaxy classification as citizen science."),
            ("Case Studies in Science and Society", "Examines vaccines, pesticides, and public trust as case studies in science and society."),
            ("Introduction to Biotechnology", "Introduces the basics of genetic engineering and its practical applications."),
            ("Ecosystems and Resource Use", "Introduces how environmental science studies the human impact on ecosystems."),
            ("The Greenhouse Effect in Depth", "Explains in detail how greenhouse gases trap heat in Earth's atmosphere."),
            ("Public Health Basics: Prevention and Epidemiology Terms", "Introduces incidence, prevalence, and outbreak as basic epidemiology terms."),
            ("Sleep and the Body: An Introduction", "Introduces sleep cycles and why adequate sleep matters for health."),
        ],
        "UG1": [
            ("The Hypothetico-Deductive Method", "Covers forming falsifiable hypotheses and deducing testable predictions from them."),
            ("Falsifiability and Popper's Philosophy of Science", "Introduces Karl Popper's criterion for demarcating science from non-science."),
            ("Case Study: The Copernican Revolution", "Examines how the heliocentric model replaced the geocentric model of the solar system."),
            ("Biophysics Fundamentals", "Introduces physical principles as applied to the study of biological systems."),
            ("Science Journalism and Public Understanding", "Examines how media coverage translates, and sometimes distorts, scientific findings."),
            ("Peer Review: How Science Is Vetted", "Covers the process academic journals use to evaluate submitted research."),
            ("Inferential Statistics: p-values and Confidence Intervals", "Introduces the logic behind statistical inference in research."),
            ("Standard Laboratory Techniques", "Covers foundational lab skills including pipetting, titration, and microscopy."),
            ("The Replication Crisis in Psychology and Medicine", "Examines documented cases of failed replication and their underlying causes."),
            ("Research Ethics and Institutional Review Boards", "Covers how review boards protect human and animal research subjects."),
            ("Science Advising in Government", "Examines how scientists inform policymakers on technical issues."),
            ("Open Science and Data Sharing", "Introduces preprints, open access publishing, and open data practices."),
            ("Science and Society: The Nuclear Power Debate", "Weighs risk, benefit, and public perception in the nuclear power debate."),
            ("CRISPR and Gene Editing: An Overview", "Explains the mechanism and applications of CRISPR gene-editing technology."),
            ("Human Impact on Ecosystems", "Examines pollution, land use change, and biodiversity loss as human impacts."),
            ("Climate Models and Predictions", "Introduces how scientists build models to project future climate scenarios."),
            ("Epidemiology of Pandemics", "Introduces reproduction number, herd immunity, and transmission dynamics."),
            ("Macronutrients and Metabolism", "Explains how the body processes carbohydrates, fats, and proteins."),
        ],
        "UG2": [
            ("Designing a Multi-Variable Experiment", "Covers controlling for confounding factors when an experiment has more than one variable."),
            ("Applying Falsifiability to Modern Debates", "Applies the concept of falsifiability to distinguish pseudoscience from testable claims."),
            ("Case Study: The Discovery of DNA's Structure", "Examines the contributions of Watson, Crick, Franklin, and Wilkins to discovering DNA's double helix."),
            ("Applied Biochemistry: Enzymes and Metabolic Pathways", "Examines how enzymes regulate biochemical reactions in metabolic pathways."),
            ("Crafting a Science Communication Piece", "Guides writing a press release or explainer article aimed at a general audience."),
            ("Research Design: Experimental vs. Observational Studies", "Covers matching study design to the research question being asked."),
            ("Statistical Power and Sample Size", "Explains why underpowered studies can fail to detect real effects."),
            ("Advanced Lab Technique: Spectroscopy and Chromatography", "Covers methods for separating and identifying chemical compounds."),
            ("Preregistration as a Replication Solution", "Examines how committing to a study's methods in advance can reduce bias."),
            ("Data Fabrication and Research Misconduct", "Examines documented cases of ethical violations in scientific research."),
            ("Comparative Science Policy", "Compares how different countries regulate emerging scientific technologies."),
            ("Building a Citizen Science Tool", "Guides designing a simple data-collection protocol for volunteer participants."),
            ("Science and Society: Genetically Modified Organisms", "Evaluates the science, benefits, and controversies surrounding genetically modified organisms."),
            ("Artificial Intelligence in Scientific Research", "Examines machine learning as a tool used in modern scientific research."),
            ("Environmental Monitoring Methods", "Covers sensors, sampling methods, and long-term ecological data collection."),
            ("Feedback Loops in the Climate System", "Examines ice-albedo, water vapor, and carbon cycle feedbacks in the climate system."),
            ("Vaccines and Herd Immunity", "Explains the immunological mechanisms of vaccination and population-level protection."),
            ("Nutrition Research Methods", "Examines the methodological challenges of studying diet and long-term health outcomes."),
        ],
        "UG3": [
            ("Advanced Experimental Design: Factorial Experiments", "Covers testing multiple factors and their interactions within a single experiment."),
            ("Thomas Kuhn's Structure of Scientific Revolutions", "Examines normal science, anomaly, and paradigm change in depth."),
            ("Case Study: The Development of Quantum Mechanics", "Examines quantum mechanics as a major scientific revolution in twentieth-century physics."),
            ("Systems Biology: Integrating Biology, Chemistry, and Computation", "Introduces modeling of whole biological systems across disciplines."),
            ("Science Communication in Controversial Topics", "Examines strategies for communicating science around politically charged issues."),
            ("Meta-Analysis: Combining Results Across Studies", "Covers systematic-review methods for combining findings across multiple studies."),
            ("Bayesian vs. Frequentist Statistics", "Compares two contrasting philosophies of statistical inference."),
            ("Research Reproducibility: Protocols and Open Lab Notebooks", "Covers documentation standards that make research more reliably repeatable."),
            ("Structural Reforms to Address the Replication Crisis", "Examines registered reports and journal policy changes aimed at improving reliability."),
            ("Dual-Use Research and Ethical Gray Areas", "Examines research that carries both beneficial and potentially harmful applications."),
            ("The Precautionary Principle in Science Policy", "Examines how policymakers decide under conditions of scientific uncertainty."),
            ("Open Science Infrastructure", "Covers repositories, version control, and reproducible computational pipelines."),
            ("Science and Society: Artificial Intelligence and Automation", "Examines the societal effects of AI and automation as an emerging technology."),
            ("Emerging Technology Case Study: Synthetic Biology", "Examines the engineering of biological systems for new applications."),
            ("Environmental Policy and Resource Management", "Examines the balance between conservation and economic resource use."),
            ("Climate Sensitivity and Uncertainty", "Examines how scientists estimate ranges of future warming and the uncertainty involved."),
            ("Public Health Responses to Pandemics", "Examines surveillance and intervention strategies through real pandemic case studies."),
            ("The Gut Microbiome and Nutrition Science", "Examines emerging research linking diet to the gut microbiome."),
        ],
        "UG4": [
            ("Capstone: Designing an Original Experiment", "Guides students from a research question through a full original experimental protocol."),
            ("Capstone Essay: A Philosophy of Science Position Paper", "Guides students in arguing for a position on the nature of scientific method."),
            ("Capstone Case Study: A Scientific Revolution of the Student's Choosing", "Guides an independent historical analysis of a chosen scientific revolution."),
            ("Interdisciplinary Capstone Project", "Guides a project that spans two or more scientific disciplines."),
            ("Capstone Science Communication Product", "Guides producing a video, article, or podcast that explains research to the public."),
            ("Capstone: Writing a Full Research Design", "Guides writing a complete, peer-reviewable research methods section."),
            ("Capstone Statistical Analysis Project", "Guides analyzing a real data set using appropriate statistical tests."),
            ("Capstone Laboratory Project", "Guides an independent hands-on investigation using standard laboratory techniques."),
            ("Capstone Reflection: Auditing a Published Study for Replicability", "Guides evaluating the methodological rigor of a real published study."),
            ("Capstone Ethics Case Analysis", "Guides producing a full written analysis of an ethical dilemma in research."),
            ("Capstone Policy Brief", "Guides writing a science policy recommendation aimed at decision-makers."),
            ("Capstone Citizen Science Initiative", "Guides designing and piloting an original public data-collection project."),
            ("Capstone Case Study in Science and Society", "Guides an in-depth look at one real science-and-society controversy."),
            ("Capstone Emerging Technology Report", "Guides assessing the promise and risk of one chosen emerging technology."),
            ("Capstone Environmental Science Field Study", "Guides collecting and analyzing local environmental data."),
            ("Capstone Climate Report", "Guides synthesizing climate science findings for a chosen region or sector."),
            ("Capstone Public Health Investigation", "Guides modeling or analyzing a disease outbreak scenario."),
            ("Capstone Nutrition and Sleep Case Study", "Guides analyzing lifestyle factors using the scientific literature on nutrition and sleep."),
        ],
        "M1": [
            ("Graduate Seminar: Philosophy of Scientific Method", "Compares Popper, Kuhn, Lakatos, and Feyerabend on the nature of scientific method."),
            ("Graduate Philosophy of Science: Realism vs. Anti-Realism", "Examines debates over what scientific theories tell us about underlying reality."),
            ("Graduate History of Science Seminar", "Compares major scientific revolutions from a graduate-level historiographical perspective."),
            ("Graduate Interdisciplinary Research Design", "Covers integrating methods across biology, chemistry, and physics at an advanced level."),
            ("Graduate Science Communication and Public Engagement", "Covers advanced strategies for engaging non-expert audiences with scientific findings."),
            ("Graduate Research Design and Peer Review Practicum", "Guides serving as a reviewer and understanding editorial decision-making."),
            ("Graduate Statistics for Research", "Covers multivariate statistical methods and model selection for research."),
            ("Advanced Laboratory Methods and Instrumentation", "Covers graduate-level laboratory technique and instrument calibration."),
            ("Graduate Seminar: The Replication Crisis and Metascience", "Introduces metascience as an emerging field studying the practice of research itself."),
            ("Graduate Research Ethics: Governance and Oversight", "Covers advanced treatment of research ethics committees and regulatory oversight."),
            ("Graduate Science Policy Seminar", "Provides advanced analysis of the relationship between science and government."),
            ("Graduate Open Science Movement", "Provides advanced examination of incentives and reform in scholarly publishing."),
            ("Graduate Seminar: Science and Society Case Studies", "Provides advanced ethical and social analysis of contested scientific issues."),
            ("Graduate Seminar: Governance of Emerging Technologies", "Examines regulatory and ethical frameworks for governing new scientific technologies."),
            ("Graduate Environmental Science Seminar", "Provides advanced synthesis of ecological research and environmental policy."),
            ("Graduate Climate Science Seminar", "Covers advanced climate modeling and attribution studies."),
            ("Graduate Seminar: Pandemic Preparedness and Public Health Policy", "Provides advanced epidemiological and policy analysis of pandemic preparedness."),
            ("Capstone Graduate Research Proposal in Science", "Guides producing a full original research proposal ready for review."),
        ],
    },
    "Geography": {
        "C1": [
            ("Earth's Major Landforms", "Introduces mountains, plains, and plateaus and how each type of landform forms."),
            ("The Water Cycle and Earth's Hydrosphere", "Covers evaporation, precipitation, and runoff as stages of the water cycle."),
            ("Introduction to World Population Patterns", "Introduces where people live around the world and the factors that explain why."),
            ("What Is Migration?", "Introduces push and pull factors that drive human migration."),
            ("Introduction to Borders and Nations", "Introduces how political boundaries between countries are drawn."),
            ("Trade Around the World: A First Look", "Introduces why countries exchange goods and services with one another."),
            ("Cultural Landscapes: How People Shape Places", "Examines how clothing, architecture, and language mark a cultural landscape."),
            ("What Is a Map? Introduction to Cartography", "Introduces scale, legend, and orientation as basic elements of a map."),
            ("Reading Satellite Images: An Introduction", "Introduces how remote sensing captures images of Earth from above."),
            ("Introduction to GIS: Layers of Information on a Map", "Introduces the basic idea of combining data layers in a geographic information system."),
            ("How Cities Are Planned", "Introduces streets, zoning, and public space as basics of city planning."),
            ("Natural Resources and Where They Are Found", "Introduces minerals, water, and energy resources and their global distribution."),
            ("A Region in Focus: Southeast Asia", "Surveys the climate, culture, and geography of Southeast Asia."),
            ("Rich and Poor Places: An Introduction to Global Inequality", "Introduces basic measures used to compare development between places."),
            ("Natural Hazards: Earthquakes, Volcanoes, and Storms", "Introduces where and why major natural hazards occur."),
            ("Why People Travel: Introduction to Tourism Geography", "Introduces the factors that draw visitors to particular places."),
            ("Farming Around the World", "Introduces how climate and soil shape agricultural practices worldwide."),
            ("How Goods Move: An Introduction to Transportation Geography", "Introduces roads, ports, and rail networks that move goods between places."),
        ],
        "C2": [
            ("Climate Zones and Biomes", "Covers the Koppen climate classification system and the major world biomes."),
            ("Urbanization Patterns Worldwide", "Examines the growth of cities and megacities around the world."),
            ("Case Study: A Territorial Dispute", "Examines one real contested border or region in detail."),
            ("Globalization and Supply Chains", "Examines how goods are produced and distributed across international borders."),
            ("Language and Religion on the Map", "Covers mapping cultural diversity through language and religion."),
            ("Map Projections: Mercator, Robinson, and Their Distortions", "Compares how different map projections distort the globe in different ways."),
            ("Introduction to Remote Sensing Satellites", "Introduces Landsat and other basic types of satellite imagery."),
            ("Building a Simple GIS Map", "Guides combining data layers in a GIS to answer a spatial question."),
            ("Urban Sprawl and Suburbanization", "Examines how cities expand outward into surrounding areas over time."),
            ("Managing Shared Resources", "Introduces water rights and resource conflict as shared-resource management issues."),
            ("A Region in Focus: Sub-Saharan Africa", "Surveys the physical and human geography of Sub-Saharan Africa."),
            ("Measuring Development: GDP, HDI, and Beyond", "Compares indicators used to measure well-being and development across countries."),
            ("Political Boundaries and Enclaves", "Examines unusual and contested border and enclave arrangements."),
            ("Case Study: A Major Earthquake or Hurricane", "Examines the geographic factors involved in a real historical natural disaster."),
            ("Ecotourism and Its Impacts", "Examines the balance between tourism revenue and environmental protection."),
            ("The Green Revolution in Agriculture", "Examines how agricultural technology transformed global food production."),
            ("Ports, Railways, and Global Trade Routes", "Examines the infrastructure that moves goods along global trade routes."),
            ("Historical Geography: How Borders Have Shifted", "Traces how political borders have shifted over time."),
        ],
        "UG1": [
            ("Plate Tectonics and Landform Evolution", "Introduces plate tectonic theory as the driver of mountain building and earthquakes."),
            ("Demographic Transition Theory", "Explains how population growth patterns change as countries develop."),
            ("Geopolitical Theory: Heartland and Rimland", "Introduces classical geopolitical theories of global power and territory."),
            ("Comparative Advantage and Economic Geography", "Explains why regions specialize in producing different goods."),
            ("Cultural Diffusion and Cultural Regions", "Examines how customs and ideas spread across space to form cultural regions."),
            ("Coordinate Systems and Map Projections in Depth", "Covers geodetic datums, the UTM system, and projection trade-offs."),
            ("Remote Sensing Data Types", "Compares multispectral, thermal, and radar satellite imagery."),
            ("GIS Data Models: Vector and Raster", "Explains how spatial data is structured using vector and raster models."),
            ("Urban Planning Theories", "Introduces the Garden City movement, New Urbanism, and zoning models."),
            ("Resource Management and Sustainability", "Compares renewable and non-renewable approaches to resource use."),
            ("A Region in Focus: Latin America", "Surveys the physical and human geography of Latin America."),
            ("Theories of Uneven Development", "Introduces core-periphery models used to explain global inequality."),
            ("Political Geography: Sovereignty and Statehood", "Examines what defines a sovereign state in geographic terms."),
            ("Vulnerability and Resilience to Natural Hazards", "Examines why the same hazard can affect different places very differently."),
            ("Tourism's Economic and Environmental Footprint", "Covers cost-benefit analysis of tourism development."),
            ("Agricultural Land Use Models", "Introduces von Thunen's model of agricultural land use and its modern relevance."),
            ("Transportation Networks and Accessibility", "Covers methods for measuring connectivity between places."),
            ("Historical Geography of Empire", "Examines how colonial-era mapping shaped many modern political borders."),
        ],
        "UG2": [
            ("Fieldwork in Physical Geography", "Covers methods for measuring landforms and hydrology directly in the field."),
            ("Analyzing Migration Data", "Covers reading census and refugee movement statistics to study migration."),
            ("Case Study: A Modern Geopolitical Conflict", "Applies geopolitical theory to analyze a current territorial dispute."),
            ("Mapping Global Trade Flows", "Covers visualizing import and export networks between countries."),
            ("Ethnographic Approaches to Cultural Geography", "Covers fieldwork methods for studying place and cultural identity."),
            ("Applied Cartographic Design", "Covers symbolization, color, and layout principles in map design."),
            ("Change Detection with Satellite Imagery", "Covers comparing satellite images over time to track land-cover change."),
            ("Spatial Analysis in GIS", "Covers buffering, overlay, and proximity analysis techniques in GIS."),
            ("Applied Urban Planning: A Zoning Case Study", "Evaluates a real city's zoning and land-use plan."),
            ("Water Resource Management Case Study", "Examines the allocation challenges of a real river basin."),
            ("A Region in Focus: The Middle East", "Surveys the physical and human geography of the Middle East."),
            ("Applied Development Geography: A Country Case Study", "Uses development indicators to assess one nation's progress."),
            ("Border Disputes and International Law", "Examines how international bodies address contested territorial claims."),
            ("Hazard Mapping and Risk Assessment", "Covers using GIS to model exposure to natural hazards."),
            ("Tourism Planning for a Real Destination", "Applies geographic analysis to a real destination management plan."),
            ("Food Systems and Supply Chains", "Traces how food moves from field to table through global supply chains."),
            ("Transportation Planning Case Study", "Evaluates a real transit or highway system's design and impact."),
            ("Mapping Historical Change: A GIS Timeline Project", "Guides reconstructing past landscapes using modern GIS tools."),
        ],
        "UG3": [
            ("Advanced Climatology: Atmospheric Circulation Patterns", "Examines Hadley cells, jet streams, and monsoon systems."),
            ("Advanced Population Geography: Aging and Fertility Decline", "Examines demographic challenges facing aging, developed nations."),
            ("Critical Geopolitics", "Examines how geopolitical narratives are constructed and contested."),
            ("Global Value Chains and Economic Geography", "Examines where different stages of production occur across the globe."),
            ("Cultural Geography of Globalization", "Examines the tension between cultural homogenization and hybridity worldwide."),
            ("Advanced GIS Modeling", "Covers network analysis and spatial statistics in advanced GIS work."),
            ("Remote Sensing for Environmental Monitoring", "Covers tracking deforestation, ice melt, and land degradation via satellite."),
            ("Cartographic Storytelling and Data Visualization", "Covers designing maps that communicate complex spatial arguments."),
            ("Advanced Urban Geography: The Global City", "Examines the command-and-control functions of major world cities."),
            ("Environmental Governance and Resource Conflict", "Provides advanced case studies of conflicts over shared natural resources."),
            ("A Region in Focus: East Asia", "Surveys the physical and human geography of East Asia."),
            ("Advanced Development Geography: Dependency Theory", "Examines critiques of core-periphery models through dependency theory."),
            ("Advanced Political Geography: Secession and Self-Determination", "Examines case studies of independence and secession movements."),
            ("Climate Change and Compound Hazards", "Examines how climate warming intensifies and combines natural hazards."),
            ("Dark Tourism and Heritage Tourism", "Examines the geography of memory and contested tourist sites."),
            ("Advanced Agricultural Geography: Land Grabs and Food Security", "Examines global land acquisition and its effects on food security."),
            ("Advanced Transportation Geography: Logistics and Global Shipping", "Examines container ports and logistics networks in global shipping."),
            ("Historical GIS: Reconstructing Past Landscapes", "Covers using archival data within a modern spatial analysis framework."),
        ],
        "UG4": [
            ("Capstone Physical Geography Field Study", "Guides an independent investigation of a local landform or watershed."),
            ("Capstone Human Geography Research Project", "Guides an original study of a population or migration pattern."),
            ("Capstone Geopolitical Analysis", "Guides an in-depth original analysis of one geopolitical dispute."),
            ("Capstone Economic Geography Report", "Guides analyzing a real regional economy's place in global trade."),
            ("Capstone Cultural Geography Ethnography", "Guides a fieldwork-based study of a cultural landscape."),
            ("Capstone GIS Project", "Guides a full spatial analysis project using real geographic data."),
            ("Capstone Remote Sensing Analysis", "Guides an original satellite-imagery-based investigation."),
            ("Capstone Cartographic Design Project", "Guides producing a publication-quality original map."),
            ("Capstone Urban Planning Proposal", "Guides designing a land-use plan for a real or hypothetical area."),
            ("Capstone Resource Management Plan", "Guides proposing a sustainable-use plan for a shared natural resource."),
            ("Capstone Regional Geography Study", "Guides a deep, original case study of a chosen world region."),
            ("Capstone Development Geography Report", "Guides assessing inequality and development in a chosen country."),
            ("Capstone Political Geography Case Study", "Guides an original analysis of a border or sovereignty question."),
            ("Capstone Hazard Risk Assessment", "Guides modeling risk and resilience for a chosen hazard-prone area."),
            ("Capstone Tourism Geography Plan", "Guides producing a sustainable tourism development proposal."),
            ("Capstone Agricultural Geography Study", "Guides analyzing a real food system's underlying geography."),
            ("Capstone Transportation Geography Analysis", "Guides evaluating and proposing improvements to a real transport network."),
            ("Capstone Geographic Field Study Project", "Guides a comprehensive original field research project integrating multiple methods."),
        ],
        "M1": [
            ("Graduate Seminar: Earth Systems Science", "Provides advanced integration of climate, hydrology, and geomorphology."),
            ("Graduate Seminar: Population and Migration Theory", "Covers advanced demographic and migration modeling."),
            ("Graduate Seminar: Geopolitics and Global Power", "Covers advanced theoretical frameworks in geopolitics."),
            ("Graduate Seminar: Economic Geography and Globalization", "Covers advanced theory of global production networks."),
            ("Graduate Seminar: Cultural Geography and Identity", "Covers advanced theory of place, space, and belonging."),
            ("Graduate GIS: Spatial Statistics and Modeling", "Covers advanced quantitative spatial analysis methods."),
            ("Graduate Remote Sensing: Advanced Image Analysis", "Covers classification algorithms and accuracy assessment in remote sensing."),
            ("Graduate Cartography: The Theory of Map Design", "Covers advanced semiotics and cognitive mapping principles."),
            ("Graduate Urban Studies Seminar", "Covers advanced theory of urbanization and the built environment."),
            ("Graduate Seminar: Environmental Geography and Policy", "Covers advanced resource governance frameworks."),
            ("Graduate Regional Studies Seminar", "Covers advanced comparative regional geography."),
            ("Graduate Seminar: Geographies of Development and Inequality", "Covers advanced critical development theory."),
            ("Graduate Seminar: Political Geography and Sovereignty", "Covers advanced border and state theory."),
            ("Graduate Seminar: Hazards, Risk, and Vulnerability", "Covers advanced disaster geography theory."),
            ("Graduate Seminar: Tourism Geography and Political Economy", "Covers advanced critical tourism studies."),
            ("Graduate Seminar: Agricultural Geography and Food Security", "Covers advanced global food systems theory."),
            ("Graduate Seminar: Transportation and Logistics Geography", "Covers advanced network and mobility theory."),
            ("Capstone Graduate Geographic Field Study Project", "Guides an original graduate-level field research project."),
        ],
    },
    "World History": {
        "C1": [
            ("Cradles of Civilization: Mesopotamia and Egypt", "Introduces early cities, writing, and irrigation-based states in Mesopotamia and Egypt."),
            ("Ancient China and the Mandate of Heaven", "Introduces early Chinese dynasties and the political philosophy behind the Mandate of Heaven."),
            ("Ancient India: The Indus Valley and Vedic Age", "Introduces early urbanism in the Indus Valley and the religious traditions of the Vedic Age."),
            ("The Rise of Rome: From Village to Republic", "Traces Rome's early political institutions from a small village to a republic."),
            ("The Han Dynasty and Imperial China", "Covers bureaucracy and territorial expansion under the Han Dynasty."),
            ("The Maurya and Gupta Empires of India", "Covers Ashoka, the spread of Buddhism, and India's classical Gupta age."),
            ("Introduction to the Medieval World", "Introduces feudalism, faith, and trade in the centuries after Rome's fall."),
            ("The Islamic Golden Age: Science and Scholarship", "Introduces Baghdad's House of Wisdom and the scholarly achievements of the Islamic Golden Age."),
            ("West African Empires: Ghana, Mali, and Songhai", "Introduces trans-Saharan trade and the scholarship of Timbuktu in West African empires."),
            ("The Mongol Empire: Rise of Genghis Khan", "Covers the Mongol conquests and the era of relative stability known as the Pax Mongolica."),
            ("European Voyages of Exploration", "Introduces Columbus, da Gama, and the opening of new European sea routes."),
            ("Introduction to the Atlantic Slave Trade", "Introduces the forced transport of enslaved Africans to the Americas."),
            ("The Scientific Revolution: A New View of Nature", "Introduces Copernicus, Galileo, and changing early modern ideas about the universe."),
            ("The Enlightenment and New Ideas About Government", "Introduces reason, rights, and social contract theory in Enlightenment thought."),
            ("The Industrial Revolution Begins", "Introduces steam power and the rise of the factory system in Britain."),
            ("Nationalism and the Unification of Italy and Germany", "Introduces the building of the Italian and German nation-states in the nineteenth century."),
            ("Introduction to Imperialism", "Introduces European colonization of Africa and Asia in the nineteenth century."),
            ("The Path to World War I", "Introduces alliances, militarism, and the assassination that triggered the First World War."),
        ],
        "C2": [
            ("Comparing Early River Valley Civilizations", "Compares Mesopotamia, Egypt, the Indus Valley, and early China as river valley civilizations."),
            ("Roman Law and Governance", "Covers the Twelve Tables, the Senate, and the concept of Roman citizenship."),
            ("Silk Road Exchange Between Rome, Han China, and India", "Examines trade and cultural contact across Eurasia along the Silk Road."),
            ("The Byzantine Empire", "Covers Rome's continuation in the East and Justinian's legal code."),
            ("The Crusades in Global Context", "Examines religious warfare and exchange between Christendom and the Islamic world."),
            ("Trade Networks of the Islamic Golden Age", "Covers Indian Ocean and trans-Saharan trade routes during the Islamic Golden Age."),
            ("Great Zimbabwe and East African Trade", "Covers Swahili coast city-states and their role in Indian Ocean commerce."),
            ("The Mongol Empire's Impact on Eurasia", "Examines administration, trade, and cultural exchange under Mongol rule."),
            ("The Columbian Exchange", "Examines the exchange of plants, animals, and diseases across the Atlantic."),
            ("The Middle Passage and Plantation Economies", "Examines the human and economic realities of the transatlantic slave trade."),
            ("Newton and the Mechanical Universe", "Covers Isaac Newton's work as the culmination of the Scientific Revolution."),
            ("The American and French Revolutions", "Examines how Enlightenment ideas were put into political practice in two revolutions."),
            ("The Industrial Revolution Spreads", "Traces industrialization as it spread to continental Europe and the United States."),
            ("Nationalist Movements in the Balkans and Eastern Europe", "Examines ethnic identity and imperial decline in nineteenth-century Eastern Europe."),
            ("The Scramble for Africa", "Covers the Berlin Conference and the European partition of Africa."),
            ("World War I: The War Itself", "Covers trench warfare and the global scope of the First World War."),
            ("The Treaty of Versailles and Its Consequences", "Examines the peace terms of Versailles and their long-term effects."),
            ("The Russian Revolution of 1917", "Covers the fall of the tsar and the rise of Bolshevik rule in Russia."),
        ],
        "UG1": [
            ("Comparative Empire: Rome and Han China", "Compares administrative structures across the Roman and Han Chinese empires."),
            ("Buddhism's Spread from Gupta India Across Asia", "Traces the diffusion of Buddhism along trade routes from Gupta India across Asia."),
            ("Feudalism in Comparative Perspective", "Compares feudal systems in medieval Europe and Japan."),
            ("The Abbasid Caliphate and Islamic Intellectual Life", "Covers philosophy, medicine, and mathematics under the Abbasid Caliphate."),
            ("Mansa Musa and the Mali Empire's Golden Age", "Covers wealth, pilgrimage, and scholarship under Mansa Musa's Mali Empire."),
            ("The Mongol Successor Khanates", "Examines the division and lasting legacy of the Mongol Empire's successor states."),
            ("Mercantilism and the Age of Exploration", "Covers the economic theory of mercantilism behind European overseas expansion."),
            ("Abolition Movements and the End of the Slave Trade", "Covers the political movements that fought to end the slave trade and slavery."),
            ("The Enlightenment's Political Philosophers", "Compares the political philosophies of Locke, Rousseau, and Montesquieu."),
            ("Labor and Social Class in the Industrial Revolution", "Examines factory conditions and the rise of an industrial working class."),
            ("Unification Movements Beyond Europe", "Covers Meiji Japan's modernization as a nation-building movement outside Europe."),
            ("Theories of Imperialism", "Compares economic, strategic, and ideological explanations for European colonization."),
            ("Causes of World War I: A Structural Analysis", "Examines alliance systems and the breakdown of the European balance of power."),
            ("Lenin, Trotsky, and the Bolshevik Consolidation of Power", "Covers the civil war period and the consolidation of the early Soviet state."),
            ("The Rise of Fascism and Militarism", "Covers the rise of fascist and militarist governments in interwar Italy, Germany, and Japan."),
            ("World War II: The European Theater", "Covers key military campaigns in Europe from 1939 to 1945."),
            ("World War II: The Pacific Theater", "Covers the war fought between Japan and the Allied powers in the Pacific."),
            ("The Origins of the Cold War", "Examines how wartime alliances broke down after 1945 into the Cold War."),
        ],
        "UG2": [
            ("Analyzing Primary Sources from Ancient Civilizations", "Guides critically reading law codes and inscriptions from ancient civilizations."),
            ("Case Study: Roman Frontier Policy and the Han Frontier", "Compares how Rome and Han China each managed their imperial frontiers."),
            ("The Medieval World Economy", "Examines trade networks linking Europe, Africa, and Asia before 1500."),
            ("Islamic Golden Age Scholars: Ibn Sina and Al-Khwarizmi", "Covers the contributions of Ibn Sina and Al-Khwarizmi to medicine and mathematics."),
            ("Songhai Empire and the Fall of Timbuktu", "Covers the political decline of the Songhai Empire and the Moroccan conquest of Timbuktu."),
            ("The Pax Mongolica and Trans-Eurasian Trade", "Examines how Mongol rule facilitated trade and exchange across Eurasia."),
            ("Case Study: The Portuguese and Spanish Colonial Empires", "Compares the Portuguese and Spanish colonial empires of the exploration era."),
            ("Economic Impact of the Atlantic Slave Trade", "Examines the triangular trade system and its economic effects."),
            ("The Scientific Revolution's Institutions", "Covers the Royal Society and the rise of formal scientific academies."),
            ("Industrialization and Urbanization", "Examines the growth of industrial cities and the social problems they created."),
            ("Case Study: German Unification Under Bismarck", "Examines realpolitik and the wars that led to German unification."),
            ("Case Study: The British Raj in India", "Examines colonial administration and its economic effects under the British Raj."),
            ("World War I: The Homefront and Total War", "Examines how economies and societies were mobilized for total war."),
            ("The Russian Civil War and War Communism", "Covers economic policy during the Bolshevik consolidation of power."),
            ("The Holocaust: History and Memory", "Covers the systematic persecution and murder of Jews and other groups by Nazi Germany."),
            ("Decolonization in South Asia", "Covers Indian independence and the 1947 Partition."),
            ("The Cold War in Asia: Korea and Vietnam", "Examines the Korean and Vietnam Wars as proxy conflicts of the Cold War."),
            ("Globalization's Institutions", "Covers the founding of the United Nations, IMF, and World Bank after 1945."),
        ],
        "UG3": [
            ("Comparative Collapse: Why Classical Empires Fell", "Compares the decline of Rome, Han China, and Gupta India."),
            ("The Global Middle Ages: Afro-Eurasian Connections", "Reassesses the medieval period as a globally interconnected era."),
            ("Advanced Islamic History: Sunni-Shia Divergence and Its Political Consequences", "Examines the historical roots and political consequences of the Sunni-Shia split."),
            ("Great Zimbabwe, Aksum, and African State Formation", "Compares state formation across Great Zimbabwe and the Kingdom of Aksum."),
            ("The Mongol Empire's Long-Term Legacy", "Examines the administrative and cultural effects of Mongol rule on Eurasia after its fall."),
            ("The Global Impact of the Columbian Exchange", "Examines demographic collapse and ecological transformation across the Americas."),
            ("Historiography of the Atlantic Slave Trade", "Examines how historians' interpretations of the slave trade have changed over time."),
            ("The Enlightenment's Global Reach", "Examines the spread of Enlightenment ideas beyond Europe, including in Latin America."),
            ("Comparative Industrialization: Britain, Japan, and Russia", "Compares different national paths toward industrial economies."),
            ("Nationalism as an Ideology", "Introduces Benedict Anderson's concept of imagined communities in the study of nationalism."),
            ("Comparative Colonialism: French, British, and Belgian Models", "Compares different administrative approaches used across European colonial empires."),
            ("Advanced Analysis: The July Crisis of 1914", "Examines the diplomatic decisions during the July Crisis that triggered world war."),
            ("Stalin's Soviet Union: Collectivization and Purges", "Covers the consolidation of Stalinist rule through collectivization and political purges."),
            ("The Holocaust and Genocide Studies", "Introduces comparative frameworks used in genocide studies."),
            ("Decolonization in Africa", "Examines case studies of independence movements across the African continent."),
            ("The Cuban Missile Crisis and Nuclear Brinkmanship", "Examines the crisis that brought the Cold War closest to nuclear conflict."),
            ("Late-20th-Century Globalization", "Examines trade liberalization and the growth of multinational institutions."),
            ("The Fall of the Soviet Union", "Covers glasnost, perestroika, and the end of the Cold War."),
        ],
        "UG4": [
            ("Capstone Comparative Study: Two Ancient Civilizations", "Guides an original comparative research paper on two ancient civilizations."),
            ("Capstone Research Project: A Classical Empire in Depth", "Guides an independent study of Rome, Han China, or Gupta India."),
            ("Capstone Research: The Medieval World in Global Perspective", "Guides an original synthesis project on the medieval world in global context."),
            ("Capstone Study: The Islamic Golden Age's Legacy", "Guides assessing the long-term intellectual contributions of the Islamic Golden Age."),
            ("Capstone Research: An African Empire's Rise and Fall", "Guides an original historical research paper on a chosen African empire."),
            ("Capstone Study: The Mongol Empire's Global Impact", "Guides a research project on Mongol-era exchange and its global impact."),
            ("Capstone Research: The Age of Exploration's Consequences", "Guides an original analysis of the global consequences of European exploration."),
            ("Capstone Research: The Atlantic Slave Trade's Legacy", "Guides an original historical research paper on the slave trade's long-term impact."),
            ("Capstone Study: The Scientific Revolution and Enlightenment's Legacy", "Guides assessing the influence of the Scientific Revolution and Enlightenment on the modern world."),
            ("Capstone Research: Industrialization's Global Spread", "Guides a comparative research project on industrialization's spread worldwide."),
            ("Capstone Study: Nationalism and Unification Movements", "Guides an original comparative analysis of nationalist and unification movements."),
            ("Capstone Research: A Colonial Empire Case Study", "Guides an independent research project on a chosen colonial empire."),
            ("Capstone Research: World War I's Causes and Consequences", "Guides an original research paper on the causes and consequences of World War I."),
            ("Capstone Study: The Russian Revolution's Legacy", "Guides assessing the long-term global impact of the Russian Revolution."),
            ("Capstone Research: World War II in Global Perspective", "Guides an independent research project on World War II in global perspective."),
            ("Capstone Study: Decolonization Movements Compared", "Guides an original comparative research paper on decolonization movements."),
            ("Capstone Research: The Cold War's Global Reach", "Guides an independent research project on the Cold War in a chosen region."),
            ("Capstone Historical Research Project", "Guides a full original research paper on a self-selected historical question."),
        ],
        "M1": [
            ("Graduate Seminar: Comparative Ancient Civilizations", "Covers advanced comparative methodology across early ancient states."),
            ("Graduate Seminar: Classical Empires and State Formation Theory", "Covers advanced theoretical frameworks for the study of empire."),
            ("Graduate Seminar: The Global Middle Ages", "Covers advanced historiography of medieval global interconnection."),
            ("Graduate Seminar: The Islamic Golden Age in World History", "Covers advanced intellectual history methods applied to the Islamic Golden Age."),
            ("Graduate Seminar: African History and Historiography", "Covers advanced sources and methods for studying African empires."),
            ("Graduate Seminar: Mongol Studies", "Covers advanced primary-source analysis of Mongol rule."),
            ("Graduate Seminar: The Age of Exploration and Global Encounter", "Covers advanced historiography of contact and exchange during the Age of Exploration."),
            ("Graduate Seminar: Slavery and the Atlantic World", "Covers advanced historiographical debates on the Atlantic slave trade."),
            ("Graduate Seminar: The Scientific Revolution and Enlightenment", "Covers advanced intellectual history methods applied to this period."),
            ("Graduate Seminar: Comparative Industrialization", "Covers advanced economic history methodology applied to industrialization."),
            ("Graduate Seminar: Nationalism and Nation-Building", "Covers advanced theoretical approaches to the study of nationalism."),
            ("Graduate Seminar: Empire and Colonialism", "Covers advanced postcolonial historiography of empire."),
            ("Graduate Seminar: The First World War", "Covers advanced historiographical debates on the origins of World War I."),
            ("Graduate Seminar: The Russian Revolution and Soviet History", "Covers advanced archival and historiographical methods applied to Soviet history."),
            ("Graduate Seminar: The Second World War in Global Perspective", "Covers advanced comparative historiography of the Second World War."),
            ("Graduate Seminar: Decolonization and Postcolonial Studies", "Covers advanced theoretical frameworks in postcolonial studies."),
            ("Graduate Seminar: The Cold War as Global History", "Covers advanced multi-archival historiography of the Cold War."),
            ("Capstone Graduate Historical Research Project", "Guides an original graduate-level research paper contributing new historical analysis."),
        ],
    },
}
