"""New UG3 (Undergraduate Year 3) topic tuples for 11 subjects.

Each subject maps to 60 NEW (title, summary) tuples that do not overlap with
topics already present in backend/syllabus/level_ug3.json for that subject.
Consumed by backend/scripts/merge_all_subjects_expansion.py, which builds full
lesson objects from these (title, summary) pairs.
"""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Project Management": {
        "UG3": [
            ("Project Charter Development and Approval", "Drafting and securing sign-off on the document that formally authorizes a project and names its manager."),
            ("Business Case Analysis for Project Selection", "Evaluating proposed projects against strategic value, cost, and expected benefit before funding is committed."),
            ("Work Breakdown Structure (WBS) Construction", "Decomposing project scope into a hierarchy of manageable, deliverable-oriented work packages."),
            ("Scope Definition and Scope Statements", "Writing precise statements of what is and is not included in a project's deliverables."),
            ("Requirements Elicitation Techniques", "Gathering stakeholder needs through interviews, workshops, surveys, and observation."),
            ("Scope Creep and Change Control", "Recognizing uncontrolled scope expansion and applying formal processes to evaluate proposed changes."),
            ("Integrated Change Control Processes", "Coordinating changes across scope, schedule, cost, and quality baselines in a unified review process."),
            ("Critical Path Method (CPM) Scheduling", "Identifying the longest sequence of dependent tasks that determines a project's minimum duration."),
            ("Program Evaluation and Review Technique (PERT)", "Using three-point time estimates to model schedule uncertainty for project activities."),
            ("Schedule Compression: Crashing and Fast-Tracking", "Shortening project duration by adding resources or overlapping sequential activities."),
            ("Resource Leveling and Resource Smoothing", "Adjusting schedules to resolve resource over-allocation while respecting project constraints."),
            ("Critical Chain Project Management", "Scheduling with buffers that protect against resource contention and estimation bias rather than task-level padding."),
            ("Cost Estimating Techniques (Analogous, Parametric, Bottom-Up)", "Comparing estimating approaches that trade off speed, accuracy, and required project detail."),
            ("Cost Budgeting and Cost Baselines", "Aggregating approved cost estimates into a time-phased budget used to measure performance."),
            ("Earned Value Management Fundamentals", "Integrating scope, schedule, and cost data to objectively measure project performance."),
            ("Schedule Performance Index and Cost Performance Index", "Calculating and interpreting the ratios that indicate whether a project is ahead or behind plan."),
            ("Variance Analysis and Forecasting (EAC, ETC)", "Using earned value data to forecast a project's likely final cost and remaining spend."),
            ("Quality Planning and Quality Metrics", "Defining measurable quality standards and the metrics used to verify they are met."),
            ("Quality Assurance versus Quality Control", "Distinguishing process-focused prevention activities from product-focused inspection activities."),
            ("Cost of Quality in Project Management", "Categorizing prevention, appraisal, and failure costs to justify investment in quality processes."),
            ("Six Sigma and DMAIC in Project Contexts", "Applying the Define-Measure-Analyze-Improve-Control cycle to reduce process defects on projects."),
            ("Total Quality Management Principles", "Embedding continuous improvement and customer focus across all project processes."),
            ("Risk Identification Techniques", "Using brainstorming, checklists, and expert judgment to surface potential project risks early."),
            ("Qualitative Risk Analysis and Probability-Impact Matrices", "Ranking identified risks by combining their likelihood and potential effect on objectives."),
            ("Quantitative Risk Analysis and Monte Carlo Simulation", "Modeling combined risk effects on schedule and cost using probabilistic simulation techniques."),
            ("Risk Response Strategies (Avoid, Mitigate, Transfer, Accept)", "Selecting appropriate strategies for addressing threats and opportunities identified in a project."),
            ("Risk Registers and Risk Owners", "Maintaining a living log of risks with assigned owners responsible for monitoring and response."),
            ("Decision Tree Analysis in Project Risk", "Using expected monetary value calculations to compare alternative courses of action under uncertainty."),
            ("Procurement Planning and Make-or-Buy Analysis", "Deciding which project work to perform internally versus source from external vendors."),
            ("Contract Types: Fixed-Price, Cost-Reimbursable, Time and Materials", "Comparing how different contract structures allocate financial risk between buyer and seller."),
            ("Vendor Selection and Source Selection Criteria", "Designing weighted criteria to evaluate and choose among competing suppliers."),
            ("Procurement Negotiation Strategies", "Applying negotiation tactics specific to contract terms, pricing, and deliverable commitments."),
            ("Contract Administration and Closeout", "Managing supplier performance against contract terms through to formal contract completion."),
            ("RACI Matrix and Responsibility Assignment", "Clarifying who is Responsible, Accountable, Consulted, and Informed for each project activity."),
            ("Organizational Structures: Functional, Matrix, Projectized", "Comparing how different organizational designs affect project authority and resource access."),
            ("Project Management Office (PMO) Functions and Types", "Distinguishing supportive, controlling, and directive PMOs and their organizational roles."),
            ("Program Management versus Project Management", "Differentiating the coordinated management of related projects from single-project delivery."),
            ("Portfolio Management and Project Prioritization", "Selecting and balancing a mix of projects and programs to meet strategic objectives."),
            ("Benefits Realization Management", "Tracking whether a project's intended business benefits are actually achieved after delivery."),
            ("Project Governance Frameworks", "Establishing decision rights, oversight bodies, and escalation paths for project delivery."),
            ("PMI Code of Ethics and Professional Responsibility", "Applying professional standards of honesty, fairness, and responsibility in project practice."),
            ("PRINCE2 Methodology Overview", "Surveying the process-based project management method built around defined stages and roles."),
            ("ISO 21500 Project Management Standard", "Reviewing the international guidance standard for project management concepts and processes."),
            ("Project Management Maturity Models (CMMI, OPM3)", "Assessing organizational project management capability against staged maturity frameworks."),
            ("Scrum Framework: Roles, Events, and Artifacts", "Examining the Scrum Master, Product Owner, and Development Team roles alongside sprint ceremonies."),
            ("Kanban Systems and Work-in-Progress Limits", "Visualizing workflow and constraining in-progress work to improve throughput and flow."),
            ("Scaled Agile Framework (SAFe) Fundamentals", "Coordinating agile practices across multiple teams and programs in large organizations."),
            ("Hybrid Project Management Approaches", "Combining predictive and agile elements to fit a project's specific delivery context."),
            ("Sprint Planning and Backlog Refinement", "Preparing and prioritizing user stories so a development team can commit to a sprint goal."),
            ("Velocity Tracking and Burndown Charts", "Using historical throughput data to forecast agile team capacity and progress."),
            ("Agile Estimation Techniques (Story Points, Planning Poker)", "Estimating relative effort for backlog items using consensus-based techniques."),
            ("Lean Project Management Principles", "Applying waste elimination and value-stream thinking drawn from lean manufacturing to projects."),
            ("Project Baselines and Configuration Management", "Controlling approved versions of scope, schedule, and cost documents throughout a project."),
            ("S-Curve Analysis for Project Tracking", "Interpreting cumulative cost or progress curves to assess project pace over time."),
            ("Milestone Planning and Integrated Master Schedules", "Structuring high-level milestones that synchronize detailed schedules across a complex program."),
            ("Project Closure and Lessons Learned Documentation", "Formally closing out project activities and capturing knowledge for future initiatives."),
            ("Project Audits and Health Checks", "Conducting independent reviews to assess project performance and process compliance."),
            ("Sustainability and Green Project Management", "Incorporating environmental and social impact criteria into project planning and execution."),
            ("Digital Transformation Project Management", "Managing the organizational and technical complexity unique to digital transformation initiatives."),
            ("Crisis Management and Project Recovery Planning", "Diagnosing troubled projects and designing recovery plans to restore them to viability."),
        ],
    },
    "Prompt Engineering": {
        "UG3": [
            ("Zero-Shot Prompting Strategies", "Designing prompts that elicit correct task performance without any worked examples."),
            ("Few-Shot Prompting and Example Selection", "Choosing and ordering demonstration examples to steer a model's output format and behavior."),
            ("Chain-of-Thought Reasoning Prompts", "Eliciting intermediate reasoning steps from a model to improve accuracy on multi-step problems."),
            ("Tree-of-Thought Prompting", "Exploring and evaluating multiple branching reasoning paths before selecting a final answer."),
            ("Self-Consistency Decoding for Reasoning Prompts", "Sampling multiple reasoning chains and selecting the most consistent final answer."),
            ("ReAct: Reasoning and Acting Prompting Pattern", "Interleaving reasoning traces with tool calls so a model can act on and observe its environment."),
            ("Function Calling and Tool Use in Prompts", "Structuring prompts so a model can invoke external functions with correctly formatted arguments."),
            ("System Prompt Design Principles", "Writing persistent instructions that establish a model's role, constraints, and behavior across a session."),
            ("Role and Persona Prompting", "Assigning a model a specific voice or expertise to shape tone and framing of its responses."),
            ("Structured Output Generation (JSON Mode)", "Constraining model output to valid, parseable structured formats for downstream systems."),
            ("Output Schema Validation for LLM Responses", "Verifying generated structured output against a defined schema before it is consumed by an application."),
            ("Prompt Injection Attacks and Defenses", "Recognizing how untrusted input can hijack a model's instructions and designing mitigations."),
            ("Jailbreak Techniques and Mitigation", "Studying methods used to bypass model safety constraints and the defenses that counter them."),
            ("Red-Teaming Prompts for Safety", "Systematically probing a model with adversarial prompts to uncover unsafe or unwanted behavior."),
            ("LLM-as-a-Judge Evaluation Methods", "Using a language model to score or compare the quality of other models' generated outputs."),
            ("Prompt Versioning and Change Management", "Tracking prompt revisions over time to manage regressions and reproducibility in production systems."),
            ("A/B Testing Prompt Variants", "Comparing competing prompt designs against real usage metrics to select the better performer."),
            ("Temperature and Top-p Sampling Effects", "Understanding how decoding parameters influence the randomness and diversity of generated text."),
            ("Token Budgeting and Context Window Management", "Allocating limited context space among instructions, examples, and retrieved content."),
            ("Prompt Compression Techniques", "Reducing prompt length while preserving task-relevant information to save tokens and cost."),
            ("In-Context Learning Mechanics", "Examining how models adapt behavior from examples provided within a single prompt, without weight updates."),
            ("Constitutional AI and Rule-Based Prompting", "Guiding model behavior using a written set of principles the model critiques its own output against."),
            ("Guardrails and Output Filtering", "Applying post-generation checks and constraints to catch unsafe or malformed model output."),
            ("Content Moderation Prompt Design", "Writing prompts and classifiers that detect harmful or policy-violating content."),
            ("Prompt Templates and Variable Substitution", "Building reusable prompt templates that inject dynamic content into a fixed instructional structure."),
            ("Meta-Prompting: Prompts That Generate Prompts", "Using a model to draft, critique, or refine prompts for another task or model."),
            ("Self-Refine and Reflection Prompting", "Having a model critique and iteratively improve its own prior output."),
            ("Debate-Style Multi-Prompt Reasoning", "Using multiple model instances arguing opposing positions to surface stronger reasoning."),
            ("Multi-Agent Prompt Orchestration", "Coordinating several specialized model agents that communicate to complete a shared task."),
            ("Agentic Loops and Task Planning", "Designing repeated observe-plan-act cycles that let a model pursue a goal across multiple steps."),
            ("Sub-Task Decomposition for Complex Prompts", "Breaking an ambiguous high-level request into smaller, independently solvable prompt steps."),
            ("Memory Management in Conversational Agents", "Deciding what conversational history or facts to retain, summarize, or discard across turns."),
            ("Prompt Engineering for Code Generation", "Structuring prompts that reliably produce correct, runnable code in a target language."),
            ("Prompt Engineering for Structured Data Extraction", "Designing prompts that pull specific fields from unstructured text into structured records."),
            ("Prompt Engineering for Machine Translation", "Crafting prompts and context that improve fluency and accuracy of model-based translation."),
            ("Controlling Summarization Style and Length", "Using prompt instructions to shape the length, tone, and focus of generated summaries."),
            ("Style Transfer Through Prompting", "Rewriting text into a different tone, register, or voice using targeted prompt instructions."),
            ("Negative Prompting and Exclusion Constraints", "Instructing a model on what to avoid, omit, or exclude from its generated response."),
            ("Constraint Satisfaction in Prompt Design", "Writing prompts that enforce multiple simultaneous formatting, length, or content constraints."),
            ("Handling Personally Identifiable Information in Prompts", "Designing prompts and pipelines that detect, redact, or safely handle sensitive personal data."),
            ("Bias Detection and Mitigation in Prompt Outputs", "Identifying systematic skew in model responses and adjusting prompts to reduce it."),
            ("Cultural Sensitivity in Cross-Lingual Prompting", "Accounting for cultural and linguistic context when prompting models across languages."),
            ("Prompting Multi-Modal Vision-Language Models", "Combining image and text inputs in prompts to elicit grounded multi-modal responses."),
            ("Prompt Engineering for Voice and Audio Interfaces", "Adapting prompt design for spoken input and output constraints in voice assistants."),
            ("Cost Optimization for LLM API Calls", "Reducing token usage and call frequency to control the operating cost of an LLM application."),
            ("Latency Optimization in Prompt Pipelines", "Restructuring prompts and calls to reduce end-to-end response time in production systems."),
            ("Batching and Parallelizing LLM Requests", "Grouping and concurrently issuing model calls to improve throughput in high-volume pipelines."),
            ("Fine-Tuning versus Prompting Trade-offs", "Weighing when task customization is better achieved through prompting versus model fine-tuning."),
            ("Example Ordering Effects in Few-Shot Prompts", "Examining how the sequence of demonstration examples influences model output quality."),
            ("Ethics of Prompt Engineering Practice", "Considering the responsibilities of prompt designers regarding manipulation, deception, and harm."),
            ("Evaluation Metrics for Generated Text (BLEU, ROUGE, Perplexity)", "Applying automated metrics to quantitatively assess the quality of model-generated text."),
            ("Human-in-the-Loop Prompt Refinement", "Incorporating human feedback cycles to iteratively improve prompt performance over time."),
            ("Conversational Design for Chatbot Prompts", "Structuring multi-turn prompt flows that maintain coherent, goal-directed dialogue."),
            ("Disambiguation Strategies in Ambiguous Prompts", "Designing prompts that detect and resolve unclear or underspecified user requests."),
            ("Prompt Engineering for Text Classification", "Framing classification tasks as prompts that reliably map input text to a fixed label set."),
            ("Structured Data-to-Text Generation Prompts", "Converting tables or structured records into fluent natural language descriptions via prompting."),
            ("Adversarial Robustness Testing for Prompts", "Stress-testing prompts against edge cases and adversarial inputs to ensure stable behavior."),
            ("Reproducibility and Documentation of Prompt Experiments", "Recording prompt versions, parameters, and results so experiments can be reliably repeated."),
            ("Prompt Engineering for Long-Context Models", "Adapting prompt structure to take advantage of very large context windows without quality loss."),
            ("Instruction Following and Instruction Hierarchies", "Understanding how models prioritize competing instructions from system, developer, and user sources."),
        ],
    },
    "Python": {
        "UG3": [
            ("Python Decorators and Higher-Order Functions", "Writing functions that wrap and extend the behavior of other functions without modifying them."),
            ("Generators and the yield Keyword", "Producing lazy sequences of values that compute items on demand instead of storing them all in memory."),
            ("Iterators and the Iterator Protocol", "Implementing the __iter__ and __next__ methods that let custom objects support for-loops."),
            ("Context Managers and the with Statement", "Managing setup and teardown of resources such as files and locks using the context manager protocol."),
            ("Custom Context Managers with contextlib", "Building reusable context managers concisely using contextlib decorators and classes."),
            ("Metaclasses and Class Customization", "Controlling how classes themselves are constructed by writing custom metaclasses."),
            ("Descriptors and Attribute Access Control", "Customizing attribute get, set, and delete behavior using the descriptor protocol."),
            ("Abstract Base Classes with the abc Module", "Defining interfaces that require subclasses to implement specific methods."),
            ("Operator Overloading and Dunder Methods", "Implementing special methods so custom objects support operators like +, ==, and len()."),
            ("Custom Exception Hierarchies", "Designing a structured tree of exception classes for clear, catchable error handling."),
            ("Asynchronous Programming with async/await", "Writing coroutines that suspend and resume execution to handle concurrent I/O efficiently."),
            ("The asyncio Event Loop", "Understanding how asyncio schedules and runs coroutines, tasks, and callbacks."),
            ("Concurrent Programming with concurrent.futures", "Using thread and process pool executors to run tasks concurrently with a simple high-level API."),
            ("Multiprocessing for CPU-Bound Tasks", "Distributing computationally heavy work across separate processes to bypass the GIL."),
            ("Threading and the Global Interpreter Lock", "Explaining how the GIL affects threaded Python programs and when threading is still useful."),
            ("Functional Programming with map, filter, and reduce", "Applying functional-style transformations to iterables without explicit loops."),
            ("The functools Module (lru_cache, partial, reduce)", "Using functools utilities to memoize calls, pre-fill arguments, and fold sequences."),
            ("The itertools Module for Efficient Iteration", "Combining building-block iterator functions to construct memory-efficient data pipelines."),
            ("The collections Module (defaultdict, Counter, deque)", "Using specialized container types that simplify common data-processing patterns."),
            ("Type Hints and Static Type Checking with mypy", "Annotating function signatures with types and catching type errors before runtime."),
            ("Dataclasses for Structured Data", "Reducing boilerplate when defining classes that primarily store structured data."),
            ("Enum Classes for Named Constants", "Defining a fixed, self-documenting set of related constant values."),
            ("Working with Files and Paths Using pathlib", "Manipulating filesystem paths with an object-oriented, cross-platform API."),
            ("Regular Expressions with the re Module", "Matching, searching, and transforming text using pattern-based regular expressions."),
            ("Logging Best Practices in Python Applications", "Structuring log levels, handlers, and formatters for maintainable application diagnostics."),
            ("Managing Virtual Environments (venv, pipenv, poetry)", "Isolating project dependencies using Python's virtual environment tooling."),
            ("Packaging and Distributing Python Projects to PyPI", "Preparing a project's metadata and build artifacts for public distribution."),
            ("Building Web Applications with Flask", "Creating lightweight web applications and APIs using the Flask microframework."),
            ("Building Web Applications with Django", "Structuring full-featured web applications using Django's models, views, and templates."),
            ("Building APIs with FastAPI", "Creating typed, high-performance asynchronous APIs with automatic documentation generation."),
            ("Web Scraping with Requests and BeautifulSoup", "Fetching and parsing HTML content to extract structured data from web pages."),
            ("Web Scraping at Scale with Scrapy", "Building crawling pipelines that handle pagination, throttling, and structured data export."),
            ("Consuming REST APIs from Python Clients", "Writing Python clients that authenticate, request, and parse responses from external REST APIs."),
            ("Parsing and Generating JSON and XML", "Reading and writing structured document formats using Python's standard libraries."),
            ("Working with Dates and Times Using datetime", "Handling timezones, formatting, and arithmetic on date and time values."),
            ("Object-Oriented Design Patterns in Python", "Applying classic design patterns such as Factory, Observer, and Strategy in Python code."),
            ("Serialization with Pickle and Alternatives", "Comparing binary and text-based serialization formats for persisting Python objects."),
            ("Working with Binary Data Using the struct Module", "Packing and unpacking binary data according to a defined byte layout."),
            ("Network Programming with Sockets", "Building simple client-server applications using Python's low-level socket API."),
            ("Database ORMs with SQLAlchemy", "Mapping Python classes to relational database tables using an object-relational mapper."),
            ("Working with NoSQL Databases Using PyMongo", "Connecting to and querying a document-oriented database from Python."),
            ("Scientific Computing with SciPy", "Using SciPy's numerical routines for optimization, integration, and statistics."),
            ("Introduction to Machine Learning with scikit-learn", "Training and evaluating basic supervised learning models using scikit-learn's API."),
            ("Image Processing with Pillow", "Loading, transforming, and saving raster images programmatically with the Pillow library."),
            ("GUI Development with Tkinter", "Building simple desktop graphical interfaces using Python's built-in GUI toolkit."),
            ("Game Development Basics with Pygame", "Creating simple 2D games using Pygame's rendering and event-handling primitives."),
            ("Task Queues and Background Jobs with Celery", "Offloading long-running work to asynchronous task queues processed outside the request cycle."),
            ("Caching Strategies in Python Applications", "Applying in-memory and external caching to reduce redundant computation or I/O."),
            ("Configuration Management with YAML and TOML", "Externalizing application settings into structured, human-readable configuration files."),
            ("Managing Environment Variables Securely", "Loading secrets and configuration from environment variables without hardcoding them."),
            ("Cryptographic Hashing and the hashlib Module", "Using hash functions for data integrity checks and secure password storage."),
            ("Code Style and Linting with PEP 8, Black, and Flake8", "Enforcing consistent code formatting and catching style issues automatically."),
            ("Writing Documentation with Docstrings and Sphinx", "Documenting Python code inline and generating polished reference documentation."),
            ("Jupyter Notebook Best Practices for Reproducible Analysis", "Structuring notebooks so analyses remain readable, reproducible, and version-control friendly."),
            ("Named Tuples versus Dataclasses", "Comparing lightweight immutable records with the more flexible dataclass alternative."),
            ("Advanced String Formatting with f-strings", "Using f-string expressions, format specifiers, and debugging syntax for readable text output."),
            ("Mocking and Fixtures in Unit Testing", "Isolating code under test by simulating dependencies with mocks and reusable pytest fixtures."),
            ("Property-Based Testing with Hypothesis", "Generating randomized test inputs automatically to uncover edge-case failures."),
            ("Building Command-Line Tools with Typer", "Creating type-hint-driven command-line interfaces with automatic help and validation."),
            ("Working with Environment-Specific Configuration Files", "Managing separate configuration profiles for development, testing, and production environments."),
        ],
    },
    "R": {
        "UG3": [
            ("R Data Structures: Vectors, Lists, and Matrices", "Comparing R's core data structures and when each is appropriate for a task."),
            ("Data Frames and Factors in R", "Representing tabular data and categorical variables using R's built-in data structures."),
            ("Control Flow and Custom Functions in R", "Writing conditional logic, loops, and reusable functions in R."),
            ("The Apply Family: sapply, lapply, vapply, mapply", "Replacing explicit loops with vectorized apply functions for cleaner, faster R code."),
            ("Introduction to the Tidyverse Ecosystem", "Surveying the collection of R packages designed around a shared grammar of data manipulation."),
            ("Data Wrangling with dplyr", "Filtering, selecting, mutating, and summarizing data frames using dplyr's verb-based syntax."),
            ("Reshaping Data with tidyr", "Converting data between wide and long formats for analysis and visualization."),
            ("Functional Programming with purrr", "Applying functional iteration patterns over lists and vectors using the purrr package."),
            ("String Manipulation with stringr", "Performing consistent, readable string operations using the stringr package's functions."),
            ("Working with Categorical Data Using forcats", "Reordering, recoding, and cleaning factor levels for analysis and plotting."),
            ("Grammar of Graphics with ggplot2", "Building layered statistical graphics by mapping data to aesthetics and geometric objects."),
            ("Faceting and Theming in ggplot2", "Splitting plots into small multiples and customizing their visual appearance."),
            ("Building Interactive Plots with plotly in R", "Converting static ggplot2 graphics into interactive, explorable visualizations."),
            ("Linear Regression Modeling in R", "Fitting and interpreting ordinary least squares regression models using lm()."),
            ("Generalized Linear Models in R", "Extending linear models to non-normal response distributions using glm()."),
            ("Logistic Regression for Binary Outcomes in R", "Modeling binary classification outcomes and interpreting odds ratios in R."),
            ("Analysis of Variance (ANOVA) in R", "Testing for differences among group means using one-way and factorial ANOVA."),
            ("Post-Hoc Tests and Multiple Comparisons in R", "Applying corrections such as Tukey HSD after a significant ANOVA result."),
            ("Chi-Square and Non-Parametric Tests in R", "Testing categorical associations and rank-based hypotheses when normality assumptions fail."),
            ("Time Series Analysis with the forecast Package", "Decomposing, modeling, and forecasting time-dependent data in R."),
            ("ARIMA and Exponential Smoothing Models in R", "Fitting autoregressive and smoothing models to forecast future time series values."),
            ("Survival Analysis in R", "Modeling time-to-event data with censoring using the survival package."),
            ("Mixed-Effects Models with lme4", "Modeling nested or hierarchical data with both fixed and random effects."),
            ("Bayesian Modeling with brms and rstan", "Fitting Bayesian regression models and interpreting posterior distributions in R."),
            ("Multivariate Analysis: MANOVA and Factor Analysis", "Analyzing multiple dependent variables simultaneously and uncovering latent factors."),
            ("Resampling Methods: Bootstrap and Permutation Tests", "Estimating sampling variability and testing hypotheses without relying on parametric assumptions."),
            ("Statistical Power Analysis in R", "Determining the sample size needed to detect an effect of a given size."),
            ("Missing Data Imputation Techniques in R", "Handling missing values using multiple imputation and related methods."),
            ("Correlation and Covariance Analysis in R", "Quantifying and visualizing linear relationships between numeric variables."),
            ("Building Interactive Web Apps with Shiny", "Creating browser-based interactive applications directly from R code."),
            ("Reactive Programming Concepts in Shiny", "Understanding how Shiny's reactive expressions automatically propagate data changes."),
            ("Reproducible Reports with R Markdown", "Combining narrative text, code, and output into a single reproducible document."),
            ("Dynamic Report Generation with knitr", "Weaving R code chunks into formatted output documents automatically."),
            ("Building Dashboards with flexdashboard", "Assembling multi-panel interactive dashboards from R Markdown documents."),
            ("S3 Object System Fundamentals", "Implementing R's simplest and most widely used object-oriented system."),
            ("S4 Classes and Formal Methods in R", "Defining classes with formal validity checks and method dispatch in R."),
            ("R6 Classes for Encapsulated Object-Oriented Programming", "Using reference-semantics classes to model mutable, encapsulated objects in R."),
            ("Environments and Variable Scoping in R", "Understanding how R resolves variable names through lexical scoping and environments."),
            ("Error Handling with tryCatch and Conditions", "Catching and responding to errors, warnings, and custom conditions in R code."),
            ("Debugging R Code with browser() and traceback()", "Stepping through R code interactively to locate the source of a bug."),
            ("Profiling and Benchmarking R Code", "Measuring execution time and memory use to find performance bottlenecks in R scripts."),
            ("Parallel Computing in R with the parallel Package", "Distributing independent computations across multiple CPU cores in R."),
            ("Parallel Loops with foreach and doParallel", "Writing parallelizable loop constructs that scale across available cores."),
            ("High-Performance Data Handling with data.table", "Manipulating large datasets efficiently using data.table's concise syntax."),
            ("Lazy Evaluation with dtplyr", "Translating dplyr syntax into data.table operations for improved performance."),
            ("Spatial Data Analysis with the sf Package", "Working with geospatial vector data and coordinate reference systems in R."),
            ("Network Analysis with igraph", "Constructing, analyzing, and visualizing graph and network structures in R."),
            ("Date and Time Handling with lubridate", "Parsing, arithmetic, and formatting of dates and times using lubridate."),
            ("Regular Expressions in R", "Matching and manipulating text patterns using R's regex functions."),
            ("Vectorization versus Explicit Loops in R", "Understanding why vectorized operations typically outperform explicit R loops."),
            ("Writing and Documenting Custom R Packages", "Structuring, documenting, and building an installable R package."),
            ("Unit Testing R Code with testthat", "Writing automated tests to verify R function behavior and prevent regressions."),
            ("Version Control Workflows for R Projects", "Integrating Git-based version control into collaborative R data science projects."),
            ("Introduction to Bioconductor for Genomics", "Surveying the R package ecosystem for analyzing high-throughput genomic data."),
            ("Financial Time Series Analysis with quantmod", "Retrieving and analyzing financial market data using the quantmod package."),
            ("Cluster Validation and Choosing k", "Evaluating clustering quality and selecting the number of clusters using validity indices."),
            ("Dimensionality Reduction Beyond PCA (t-SNE, UMAP in R)", "Applying nonlinear dimensionality reduction techniques for visualizing high-dimensional data."),
            ("Ensemble Methods: Bagging and Boosting in R", "Combining multiple weak models to improve predictive performance in R."),
            ("Cross-Validation Strategies for Model Selection in R", "Comparing k-fold, leave-one-out, and repeated cross-validation for model tuning."),
            ("Building Custom ggplot2 Themes", "Designing reusable, branded visual themes for consistent ggplot2 output."),
        ],
    },
    "Science": {
        "UG3": [
            ("Thermodynamics: Laws and Applications", "Applying the laws governing energy transfer, entropy, and equilibrium in physical systems."),
            ("Statistical Mechanics Fundamentals", "Connecting microscopic particle behavior to macroscopic thermodynamic properties."),
            ("Quantum Mechanics: Wave-Particle Duality and the Schrodinger Equation", "Introducing the mathematical framework describing quantum behavior of particles and waves."),
            ("Special Relativity and Spacetime", "Examining how the constancy of the speed of light reshapes concepts of space and time."),
            ("Electromagnetism and Maxwell's Equations", "Unifying electricity, magnetism, and light through a compact set of field equations."),
            ("Nuclear Physics and Radioactive Decay", "Studying nuclear structure, decay modes, and the physics of radioactivity."),
            ("Introduction to Particle Physics and the Standard Model", "Surveying the fundamental particles and forces described by the Standard Model."),
            ("Fluid Dynamics Principles", "Modeling the flow of liquids and gases using conservation of mass, momentum, and energy."),
            ("Optics and Wave Phenomena", "Explaining reflection, refraction, diffraction, and interference of light waves."),
            ("Organic Chemistry Reaction Mechanisms", "Tracing electron movement to explain how organic reactions proceed step by step."),
            ("Physical Chemistry: Reaction Kinetics", "Quantifying reaction rates and the factors that influence how fast reactions occur."),
            ("Inorganic Chemistry and Coordination Compounds", "Studying the structure and bonding of metal complexes and their ligands."),
            ("Analytical Chemistry Techniques (Spectroscopy, Chromatography)", "Using instrumental methods to identify and quantify chemical compounds."),
            ("Biochemistry: Enzyme Kinetics and Metabolic Pathways", "Modeling how enzymes catalyze the reactions that drive cellular metabolism."),
            ("Molecular Biology: Gene Expression and Regulation", "Explaining how genetic information is transcribed, translated, and controlled."),
            ("CRISPR and Genome Editing Techniques", "Examining the molecular tools used to make precise, targeted edits to DNA."),
            ("Cell Biology: Organelles and Cellular Signaling", "Describing the structures within cells and how they communicate and coordinate function."),
            ("Evolutionary Biology: Mechanisms of Natural Selection", "Explaining how selection, drift, and mutation drive changes in populations over time."),
            ("Population Genetics Fundamentals", "Modeling how allele frequencies change within populations across generations."),
            ("Ecology: Ecosystem Dynamics and Energy Flow", "Analyzing how energy and nutrients move through trophic levels in ecosystems."),
            ("Conservation Biology and Biodiversity Loss", "Studying causes of species decline and strategies to protect biological diversity."),
            ("Microbiology: Bacterial Growth and Pathogenesis", "Examining how bacteria grow, reproduce, and cause disease in hosts."),
            ("Virology: Viral Replication and Emerging Diseases", "Studying how viruses hijack host cells to replicate and the drivers of disease emergence."),
            ("Immunology: Innate and Adaptive Immune Responses", "Describing how the body detects and responds to pathogens through layered immune defenses."),
            ("Neuroscience: Neuron Structure and Synaptic Transmission", "Explaining how neurons generate and transmit electrical and chemical signals."),
            ("Human Physiology: The Cardiovascular System", "Studying the structure and regulation of the heart and circulatory system."),
            ("Human Physiology: The Endocrine System", "Examining how hormones regulate metabolism, growth, and homeostasis."),
            ("Pharmacology: Drug Mechanisms and Pharmacokinetics", "Studying how drugs act on biological targets and how the body processes them."),
            ("Plant Biology and Photosynthesis Mechanisms", "Explaining how plants convert light energy into chemical energy at the molecular level."),
            ("Animal Behavior and Ethology", "Studying the evolutionary and physiological basis of animal behavior patterns."),
            ("Astrophysics: Stellar Evolution", "Modeling the life cycle of stars from formation through their eventual end states."),
            ("Astrophysics: Cosmology and the Big Bang Model", "Examining evidence for the universe's origin, expansion, and large-scale structure."),
            ("Planetary Science and Comparative Planetology", "Comparing the formation and characteristics of planets within and beyond the solar system."),
            ("Geology: Plate Tectonics and Structural Geology", "Explaining how tectonic plate motion shapes Earth's crust and geological features."),
            ("Mineralogy and Petrology", "Classifying minerals and rocks based on composition and formation processes."),
            ("Paleontology and the Fossil Record", "Interpreting fossil evidence to reconstruct the history of life on Earth."),
            ("Meteorology: Atmospheric Circulation Patterns", "Studying the physical processes that drive weather systems and global wind patterns."),
            ("Oceanography: Ocean Currents and Circulation", "Examining how ocean currents distribute heat, nutrients, and marine life globally."),
            ("Atmospheric Chemistry and Air Pollution", "Studying chemical reactions in the atmosphere and their role in pollution and climate."),
            ("Geochemistry and Biogeochemical Cycles", "Tracing how elements cycle through the Earth's crust, oceans, atmosphere, and biosphere."),
            ("Materials Science: Structure-Property Relationships", "Relating the atomic structure of materials to their mechanical and physical properties."),
            ("Biophysics: Protein Folding and Structure", "Applying physical principles to explain how proteins fold into functional shapes."),
            ("Computational Biology and Bioinformatics Methods", "Using computational tools to analyze biological sequences and large-scale datasets."),
            ("Epidemiology: Study Design and Causal Inference", "Designing studies that identify disease risk factors while accounting for confounding."),
            ("Biostatistics: Hypothesis Testing in Life Sciences", "Applying statistical inference methods specifically to biological and medical data."),
            ("Forensic Science: Trace Evidence Analysis", "Applying scientific methods to analyze physical evidence recovered from crime scenes."),
            ("Renewable Energy Technologies and Physics", "Examining the physical principles behind solar, wind, and other renewable energy systems."),
            ("Environmental Toxicology", "Studying how pollutants affect living organisms and ecosystems."),
            ("Comparative Genomics", "Comparing genome sequences across species to understand evolution and gene function."),
            ("Endocrinology and Hormonal Regulation", "Examining the glands, hormones, and feedback loops that regulate body systems."),
            ("Developmental Biology: Embryogenesis", "Studying how a single fertilized cell develops into a complex multicellular organism."),
            ("Genetics: Mendelian and Non-Mendelian Inheritance", "Comparing classical inheritance patterns with more complex genetic phenomena."),
            ("Biotechnology Applications in Agriculture", "Examining how genetic and biological tools are applied to improve crops and livestock."),
            ("Astrobiology and the Search for Extraterrestrial Life", "Exploring the conditions necessary for life and methods used to search for it beyond Earth."),
            ("Seismology and Earthquake Science", "Studying how seismic waves reveal Earth's interior structure and earthquake mechanics."),
            ("Volcanology and Igneous Processes", "Examining magma generation, eruption dynamics, and volcanic hazard assessment."),
            ("Marine Biology and Coral Reef Ecosystems", "Studying the biodiversity and ecological dynamics of marine and coral reef environments."),
            ("Climate Modeling Techniques", "Examining how computational models simulate and project future climate behavior."),
            ("Nanotechnology Fundamentals", "Studying the unique physical and chemical properties of matter at the nanoscale."),
            ("History and Philosophy of the Periodic Table", "Tracing how the periodic table was developed and how it organizes chemical knowledge."),
        ],
    },
    "Social Studies": {
        "UG3": [
            ("Comparative Political Systems", "Analyzing how different countries structure executive, legislative, and judicial power."),
            ("Political Ideologies: Liberalism, Conservatism, and Socialism", "Comparing the core assumptions and policy implications of major political ideologies."),
            ("Electoral Systems and Voting Behavior", "Examining how different voting rules shape representation and voter decision-making."),
            ("Public Opinion and Polling Methodology", "Studying how surveys are designed and interpreted to measure public attitudes."),
            ("Federalism and Multi-Level Governance", "Comparing how power is divided between national, regional, and local governments."),
            ("Judicial Systems and Comparative Law", "Comparing how different legal traditions structure courts and judicial review."),
            ("Constitutional Law Fundamentals", "Studying the principles that define government authority and protect individual rights."),
            ("Public Administration and Bureaucracy", "Examining how government agencies implement policy and are held accountable."),
            ("International Relations Theory: Realism and Liberalism", "Comparing major theoretical frameworks explaining state behavior in the international system."),
            ("Diplomacy and Foreign Policy Analysis", "Studying how states formulate and pursue objectives in their relations with other states."),
            ("International Law and Global Governance", "Examining the treaties, institutions, and norms that regulate relations between states."),
            ("Human Rights Frameworks and Enforcement", "Studying international human rights instruments and mechanisms for their enforcement."),
            ("War, Conflict, and Peacebuilding Studies", "Analyzing the causes of armed conflict and strategies for post-conflict reconstruction."),
            ("Microeconomics: Supply, Demand, and Market Equilibrium", "Modeling how prices and quantities are determined in competitive markets."),
            ("Macroeconomics: GDP, Inflation, and Unemployment", "Studying the indicators and models used to analyze national economic performance."),
            ("Market Structures: Competition and Monopoly", "Comparing how firm behavior and pricing differ across competitive and monopolistic markets."),
            ("Fiscal Policy and Government Budgeting", "Examining how government spending and taxation decisions affect the economy."),
            ("Monetary Policy and Central Banking", "Studying how central banks use interest rates and money supply to manage the economy."),
            ("International Trade Theory and Comparative Advantage", "Explaining why countries trade and how comparative advantage shapes trade patterns."),
            ("Development Economics and Global Poverty", "Studying the causes of underdevelopment and strategies for economic growth in poor countries."),
            ("Labor Economics and Wage Determination", "Analyzing how supply, demand, and institutions shape wages and employment."),
            ("Behavioral Economics and Decision-Making", "Examining how psychological factors cause deviations from rational economic models."),
            ("Economic Inequality and Redistribution Policy", "Studying the causes of income and wealth inequality and policies that address it."),
            ("Human Geography and Spatial Patterns", "Analyzing how human activity and population are distributed across space."),
            ("Economic Geography and Regional Development", "Studying why economic activity clusters in particular regions and how it evolves."),
            ("Political Geography and Territorial Boundaries", "Examining how borders, territory, and geopolitics shape political relationships."),
            ("Urban Planning and Land Use Policy", "Studying how cities regulate land use, zoning, and infrastructure development."),
            ("Demographic Transition Theory", "Modeling how birth and death rates change as societies industrialize and develop."),
            ("Migration Studies and Diaspora Communities", "Examining the causes and social effects of human migration across borders."),
            ("Linguistic Anthropology and Language in Society", "Studying how language use reflects and shapes social identity and power."),
            ("Archaeological Methods and Material Culture", "Examining how archaeologists interpret past societies through material remains."),
            ("Kinship Systems in Comparative Anthropology", "Comparing how different societies organize family relationships and descent."),
            ("Ritual, Symbolism, and Religion in Anthropology", "Analyzing the social functions of ritual practice and symbolic meaning across cultures."),
            ("Criminology: Theories of Crime Causation", "Comparing sociological, biological, and psychological explanations of criminal behavior."),
            ("Law and Justice Systems Comparative Study", "Comparing how different societies define and administer criminal and civil justice."),
            ("Civil Society and Non-Governmental Organizations", "Studying the role of NGOs and civic associations in shaping public life."),
            ("Social Movements Theory and Activism", "Analyzing how collective action emerges, organizes, and achieves social change."),
            ("Environmental Sociology and Human-Nature Relations", "Studying how social structures shape and are shaped by environmental conditions."),
            ("Science and Technology Studies (STS)", "Examining how scientific knowledge and technology are socially constructed and contested."),
            ("Disability Studies and Social Inclusion", "Analyzing how societies construct disability and structure inclusion or exclusion."),
            ("Immigration Policy and Integration Models", "Comparing national approaches to immigration control and immigrant integration."),
            ("Welfare State Models: Comparative Social Policy", "Comparing how different countries structure social insurance and public welfare programs."),
            ("Global Inequality and World-Systems Theory", "Examining theories that explain persistent inequality between core and peripheral nations."),
            ("Indigenous Studies and Self-Determination", "Studying indigenous peoples' rights, sovereignty claims, and self-governance movements."),
            ("Political Economy of Development", "Analyzing how political institutions shape economic development outcomes."),
            ("Comparative Federal versus Unitary States", "Contrasting how federal and unitary systems distribute governmental authority."),
            ("Public Policy Analysis and Evaluation", "Applying frameworks to assess the design, implementation, and impact of public policies."),
            ("Political Participation and Civic Engagement", "Studying the forms and determinants of citizen involvement in political life."),
            ("Nationalism and National Identity Formation", "Examining how national identities are constructed and mobilized politically."),
            ("Comparative Welfare Capitalism", "Comparing varieties of capitalism and their differing social welfare arrangements."),
            ("Sociology of Health and Illness", "Studying how social factors shape health outcomes, illness experience, and healthcare access."),
            ("Sociology of Sport", "Analyzing how sport reflects and reproduces broader social structures and identities."),
            ("Sociology of Emotions", "Studying how emotions are socially shaped, expressed, and regulated."),
            ("The Sociology of Consumption", "Examining how consumer behavior reflects social status, identity, and culture."),
            ("Social Network Analysis Methods", "Applying graph-based methods to study relationships and influence within social groups."),
            ("Environmental Justice and Policy", "Studying how environmental harms and benefits are distributed unequally across populations."),
            ("Comparative Criminal Justice Systems", "Comparing policing, sentencing, and corrections practices across different countries."),
            ("Political Economy of Natural Resources", "Examining how resource wealth shapes governance, conflict, and development outcomes."),
            ("Theories of Social Stratification", "Comparing frameworks explaining how societies rank and divide individuals by status."),
            ("Comparative Study of Democratic Backsliding", "Analyzing the processes and warning signs of democracies eroding into authoritarianism."),
        ],
    },
    "Survival Skills": {
        "UG3": [
            ("Map and Compass Navigation Fundamentals", "Using topographic maps and a compass together to determine position and direction of travel."),
            ("GPS and GNSS Land Navigation Systems", "Applying satellite-based positioning technology for accurate wilderness navigation."),
            ("Orienteering Techniques and Competition Skills", "Applying route-finding and pacing skills used in competitive orienteering."),
            ("Knot Tying and Rope Work for Survival", "Selecting and tying knots appropriate for shelter building, hauling, and securing gear."),
            ("Rope Rescue Systems and Technical Rigging", "Building mechanical advantage systems for raising, lowering, and rescue operations."),
            ("Edible and Poisonous Plant Identification", "Distinguishing safe wild plants from toxic look-alikes using reliable identification features."),
            ("Sustainable Foraging Ethics and Practices", "Balancing wild food gathering with conservation of plant populations and habitats."),
            ("Trapping Techniques for Sustenance", "Understanding the mechanics and ethics of small-game trapping for emergency food."),
            ("Fishing Techniques in Survival Contexts", "Applying improvised fishing methods to obtain food in a survival situation."),
            ("Animal Tracking and Sign Interpretation", "Reading footprints, scat, and other signs to identify nearby wildlife."),
            ("Wildlife Hazard Awareness (Bears, Snakes, Large Predators)", "Recognizing and mitigating risks from dangerous wildlife encountered in the field."),
            ("Venomous Bite and Sting Field Treatment", "Applying first-response protocols for venomous snake, insect, and marine stings."),
            ("Cold Water Immersion Physiology and Response", "Understanding the body's physiological response to sudden cold water immersion."),
            ("Avalanche Safety and Snow Science", "Assessing snowpack stability and applying avalanche avoidance and rescue techniques."),
            ("Desert Survival Techniques", "Managing water, heat, and shelter needs specific to arid desert environments."),
            ("Tropical and Jungle Survival Techniques", "Managing humidity, disease vectors, and dense vegetation in tropical survival scenarios."),
            ("Maritime and Open-Water Survival Skills", "Applying survival techniques for open water, life raft use, and signaling at sea."),
            ("Aircraft Crash Survival Protocols", "Following immediate-action procedures for surviving and signaling after an aircraft incident."),
            ("Urban Survival and Bug-Out Planning", "Preparing evacuation plans and resource strategies for urban emergency scenarios."),
            ("Food Preservation Techniques for Long-Term Storage", "Applying drying, smoking, and fermenting methods to extend food shelf life."),
            ("Water Purification Technologies (Filtration, Chemical, UV)", "Comparing methods for making field water sources safe to drink."),
            ("Friction Fire-Starting Methods", "Practicing bow drill and hand drill techniques for generating fire without matches."),
            ("Ferro Rod and Modern Fire-Starting Tools", "Using modern fire-starting devices reliably under adverse field conditions."),
            ("Debris Hut and Natural Shelter Construction", "Building insulated emergency shelters from available natural materials."),
            ("Snow Cave and Quinzhee Construction", "Constructing insulated snow shelters for cold-weather survival."),
            ("Tarp Configurations for Emergency Shelter", "Selecting tarp setups suited to varying weather and terrain conditions."),
            ("Psychological First Aid in Crisis Situations", "Applying initial supportive interventions to reduce acute distress after a crisis."),
            ("Stress Inoculation Training for High-Stakes Environments", "Building resilience to perform effectively under high-pressure survival conditions."),
            ("Group Dynamics and Leadership in Survival Situations", "Managing decision-making and cohesion within a group under survival stress."),
            ("Bushcraft Tool Use: Knife, Axe, and Saw Skills", "Applying safe and effective techniques for core bushcraft cutting tools."),
            ("Cordage-Making from Natural Materials", "Producing usable rope and cord from plant fibers and other natural sources."),
            ("Primitive Technology and Tool-Making", "Fabricating basic tools and implements using primitive techniques and materials."),
            ("Signal Fires and Visual Signaling Techniques", "Using fire, mirrors, and ground markers to attract the attention of rescuers."),
            ("Amateur Radio Licensing for Emergency Communications", "Understanding licensing requirements and practices for emergency radio communication."),
            ("Satellite Communication Devices for Remote Travel", "Evaluating personal locator beacons and satellite messengers for remote expeditions."),
            ("Wilderness First Aid for Fractures and Wounds", "Applying splinting, wound care, and evacuation decision-making in remote settings."),
            ("Layering Systems for Hypothermia Prevention", "Designing clothing layering strategies that manage moisture and insulation in the cold."),
            ("Heat Acclimatization Strategies", "Applying physiological adaptation techniques to improve tolerance of hot environments."),
            ("Altitude Sickness Physiology and Prevention", "Understanding the causes of altitude illness and strategies to prevent it."),
            ("Arctic and Extreme Cold Survival Techniques", "Applying specialized survival strategies for prolonged exposure to extreme cold."),
            ("Extreme Heat Survival Strategies", "Managing hydration, exertion, and shelter to survive extreme heat conditions."),
            ("Earthquake Preparedness and Immediate Response", "Applying protective actions before, during, and after seismic events."),
            ("Flood Survival Strategies", "Planning evacuation and safety measures for flash flood and rising water scenarios."),
            ("Wildfire Evacuation Planning", "Developing evacuation triggers and routes for wildfire-prone areas."),
            ("Hurricane and Tornado Preparedness", "Planning shelter, supplies, and evacuation for severe storm events."),
            ("Household Pandemic Preparedness Planning", "Preparing supplies and protocols for extended household isolation during outbreaks."),
            ("Long-Term Food Storage Systems", "Designing rotation and storage systems for multi-month emergency food supplies."),
            ("Water Storage and Rotation Practices", "Maintaining safe, rotated emergency water reserves for households."),
            ("Situational Awareness Training", "Developing habits of observation that identify threats before they escalate."),
            ("Personal Security and Self-Defense Basics", "Applying foundational awareness and physical techniques for personal safety."),
            ("Land Navigation with Pace Counting and Dead Reckoning", "Estimating distance traveled without GPS using pace counts and directional bearing."),
            ("Leave No Trace Wilderness Ethics", "Applying principles that minimize human impact on wild and natural areas."),
            ("Legal Considerations in Land Access and Survival Situations", "Understanding property rights, permits, and liability issues in outdoor activity."),
            ("Historical Expedition Case Studies in Survival", "Analyzing historical expeditions to extract lessons in survival decision-making."),
            ("Military SERE (Survival, Evasion, Resistance, Escape) Training Methods", "Surveying the structure and objectives of military survival training programs."),
            ("Human-Wildlife Conflict Mitigation", "Applying strategies to reduce dangerous encounters between people and wildlife."),
            ("Cave and Cavern Survival Considerations", "Addressing the unique hazards and navigation challenges of underground environments."),
            ("High-Altitude Mountaineering Safety Protocols", "Applying acclimatization, route planning, and rescue protocols for high-altitude travel."),
            ("Improvised Tool-Making from Salvaged Materials", "Repurposing available materials into functional survival tools and equipment."),
            ("Survival Photography and Documentation for Rescue", "Documenting location and condition information to assist search and rescue teams."),
        ],
    },
    "UI/UX Design": {
        "UG3": [
            ("Usability Testing Methods and Protocols", "Planning and running moderated and unmoderated sessions to evaluate interface usability."),
            ("Card Sorting for Information Architecture", "Using participant sorting exercises to inform how content should be categorized and labeled."),
            ("Tree Testing for Navigation Validation", "Testing whether users can find content within a proposed navigation structure."),
            ("Contextual Inquiry and Field Research", "Observing users in their natural environment to uncover real workflow needs."),
            ("Diary Studies for Longitudinal UX Research", "Collecting user experiences over time through self-reported diary entries."),
            ("Heuristic Evaluation Using Nielsen's Usability Heuristics", "Applying established usability principles to expert-review an interface."),
            ("Information Architecture Principles", "Structuring content and navigation so users can find information intuitively."),
            ("Interaction Design Fundamentals", "Designing how users interact with system controls and receive feedback."),
            ("Wireframing and Low-Fidelity Prototyping", "Sketching interface layouts quickly to explore structure before visual design."),
            ("High-Fidelity Prototyping with Figma", "Building interactive, near-final prototypes to test realistic user flows."),
            ("The Design Thinking Process", "Applying the empathize-define-ideate-prototype-test framework to design problems."),
            ("Persona Development and User Segmentation", "Synthesizing research into representative user archetypes that guide design decisions."),
            ("User Journey Mapping", "Visualizing the end-to-end experience a user has while accomplishing a goal."),
            ("Service Design and Service Blueprinting", "Mapping front-stage and back-stage processes that together deliver a service experience."),
            ("Typography Systems for Digital Products", "Establishing type scales and hierarchies that support readability and brand consistency."),
            ("Color Theory and Psychology in Interface Design", "Applying color relationships and psychological associations to interface design."),
            ("Grid Systems and Layout Principles", "Using structured grids to create consistent, balanced interface layouts."),
            ("Motion Design and Microinteractions", "Designing small animated feedback moments that clarify state changes and delight users."),
            ("Responsive and Adaptive Design Strategies", "Comparing approaches for making interfaces work across a range of screen sizes."),
            ("Mobile-First Design Principles", "Designing for the constraints of small screens first, then progressively enhancing."),
            ("Voice User Interface (VUI) Design", "Designing conversational flows and prompts for voice-controlled interfaces."),
            ("Conversational UI and Chatbot Design", "Structuring dialogue-based interfaces that guide users toward their goals."),
            ("Gamification Principles in UX Design", "Applying game-like mechanics to increase user motivation and engagement."),
            ("Dark Patterns and Ethical Design Considerations", "Recognizing manipulative design practices and the ethical alternatives to them."),
            ("UX Writing and Microcopy", "Crafting concise interface text that guides, informs, and reassures users."),
            ("Design Critique and Feedback Processes", "Structuring constructive critique sessions that improve design quality collaboratively."),
            ("Design Operations (DesignOps) Practices", "Streamlining tools, workflows, and processes that support design teams at scale."),
            ("Design Sprints: Structure and Facilitation", "Running a time-boxed process to rapidly prototype and validate a design solution."),
            ("Prototyping Fidelity Levels and Trade-offs", "Choosing the appropriate level of prototype detail for a given research question."),
            ("Cognitive Load Theory Applied to Interface Design", "Designing interfaces that minimize unnecessary mental effort for users."),
            ("Gestalt Principles in Visual Design", "Applying perceptual grouping principles such as proximity and similarity to layouts."),
            ("Affordances and Signifiers in Interaction Design", "Designing visual cues that communicate how an interface element should be used."),
            ("Information Scent and Navigation Cues", "Designing cues that help users predict where a link or action will lead."),
            ("Mental Models and User Expectations", "Aligning interface behavior with the expectations users bring from prior experience."),
            ("User Flow Diagrams and Wireflows", "Mapping the sequence of screens and decisions a user takes to complete a task."),
            ("Design-to-Development Handoff Practices", "Preparing specifications and assets that developers can implement accurately."),
            ("Design Quality Assurance Processes", "Reviewing shipped interfaces against design specifications to catch inconsistencies."),
            ("Cross-Platform Design Consistency", "Maintaining coherent design language across web, mobile, and desktop platforms."),
            ("Dark Mode Design Considerations", "Adapting color, contrast, and imagery for low-light interface themes."),
            ("Onboarding Flow Design", "Designing first-time user experiences that build understanding and early engagement."),
            ("Empty States and Error State Design", "Designing informative, helpful screens for states with no data or failures."),
            ("Form Design Best Practices", "Structuring input fields, validation, and error messaging to minimize user friction."),
            ("E-Commerce UX Patterns", "Applying established interface patterns for browsing, cart, and checkout flows."),
            ("Dashboard and Data Visualization UX", "Designing interfaces that help users interpret and act on complex data."),
            ("Designing for Augmented and Virtual Reality Interfaces", "Applying spatial interaction principles unique to immersive AR and VR environments."),
            ("Design Systems Governance for Enterprise Products", "Establishing processes that keep large-scale design systems consistent and maintained."),
            ("UX Metrics: NPS, SUS, and Task Success Rate", "Selecting and interpreting quantitative metrics that measure user experience quality."),
            ("Competitive Analysis in UX Research", "Evaluating competitor products to identify design opportunities and benchmarks."),
            ("Affinity Diagramming for Research Synthesis", "Clustering qualitative research notes into themes that inform design decisions."),
            ("Rapid Prototyping with No-Code Tools", "Building testable prototypes quickly using no-code and low-code platforms."),
            ("Designing for Wearable Devices", "Adapting interface design for the small screens and glanceable interactions of wearables."),
            ("UX Writing Tone and Voice Guidelines", "Establishing consistent tone and voice standards across a product's interface text."),
            ("Stakeholder Management for Design Teams", "Communicating design rationale and decisions effectively to non-design stakeholders."),
            ("Remote User Research Methodologies", "Adapting usability testing and interviews for distributed, remote participants."),
            ("Eye-Tracking and Biometric UX Research", "Using physiological measurement tools to study attention and engagement patterns."),
            ("Information Visualization Principles", "Applying visual encoding principles to represent data accurately and clearly."),
            ("Iconography Design Principles", "Designing simple, recognizable icons that communicate meaning across contexts."),
            ("Progressive Disclosure Techniques", "Revealing interface complexity gradually to avoid overwhelming users."),
            ("Skeuomorphism versus Flat Design History", "Tracing the evolution of interface visual styles and the reasoning behind each approach."),
            ("Designing for Low-Bandwidth and Offline-First Contexts", "Designing interfaces that remain usable under limited or intermittent connectivity."),
        ],
    },
    "Web Development": {
        "UG3": [
            ("GraphQL API Design and Query Language", "Designing flexible APIs that let clients request exactly the data fields they need."),
            ("WebSocket Communication for Real-Time Apps", "Building persistent bidirectional connections for real-time web features."),
            ("Introduction to gRPC for Web Backends", "Using a high-performance RPC framework for efficient service-to-service communication."),
            ("Server-Side Rendering (SSR) Fundamentals", "Rendering page content on the server to improve initial load and SEO."),
            ("Static Site Generation (SSG) and the JAMstack", "Pre-building pages at deploy time for fast, decoupled front-end architectures."),
            ("Building Applications with Next.js", "Combining server rendering, static generation, and routing in a React-based framework."),
            ("State Management Patterns (Redux, Zustand, Vuex)", "Comparing centralized state libraries for managing complex frontend application state."),
            ("React Hooks Deep Dive", "Using hooks to manage state, side effects, and lifecycle behavior in function components."),
            ("Vue Composition API Fundamentals", "Structuring Vue component logic using composable, reusable functions."),
            ("Introduction to Svelte and Compiler-Based Frameworks", "Examining a framework that shifts reactivity work to compile time rather than runtime."),
            ("CSS Architecture: BEM Methodology", "Applying a naming convention that keeps large CSS codebases predictable and maintainable."),
            ("CSS-in-JS Styling Approaches", "Scoping component styles directly within JavaScript for encapsulation and dynamic theming."),
            ("Utility-First CSS with Tailwind", "Composing interface styles from small, reusable utility classes."),
            ("Advanced CSS Grid Layouts", "Building complex two-dimensional page layouts using CSS Grid."),
            ("Advanced Flexbox Layout Patterns", "Solving common one-dimensional layout challenges using flexbox alignment properties."),
            ("Web Components and Custom Elements", "Building framework-agnostic, reusable UI elements using native browser APIs."),
            ("TypeScript for Frontend Development", "Adding static types to JavaScript to catch errors and improve code maintainability."),
            ("Module Bundling with Webpack", "Configuring a bundler to combine, transform, and optimize frontend assets."),
            ("Modern Build Tooling with Vite and esbuild", "Comparing faster, modern alternatives to traditional JavaScript build tools."),
            ("Tree Shaking and Dead Code Elimination", "Reducing bundle size by removing code that is never actually used."),
            ("Unit Testing JavaScript with Jest", "Writing isolated automated tests for JavaScript functions and components."),
            ("End-to-End Testing with Cypress and Playwright", "Automating full browser-based tests that simulate real user interactions."),
            ("Cross-Site Scripting (XSS) Prevention", "Identifying and mitigating vulnerabilities that allow malicious script injection."),
            ("Cross-Site Request Forgery (CSRF) Protection", "Defending web applications against forged requests made on a user's behalf."),
            ("Cross-Origin Resource Sharing (CORS) Configuration", "Configuring server policies that control which origins may access an API."),
            ("Content Security Policy (CSP) Implementation", "Restricting the sources of executable content to reduce injection attack surface."),
            ("SQL Injection Prevention for Web Backends", "Applying parameterized queries and input validation to prevent database injection attacks."),
            ("OAuth 2.0 and OpenID Connect Fundamentals", "Understanding delegated authorization and identity protocols used across the web."),
            ("JSON Web Tokens (JWT) for Authentication", "Using signed tokens to authenticate and authorize requests statelessly."),
            ("Session Management Strategies", "Comparing cookie-based sessions and token-based approaches to maintaining user state."),
            ("API Rate Limiting Techniques", "Protecting backend services from abuse by throttling excessive request rates."),
            ("API Versioning Strategies", "Evolving APIs over time without breaking existing client integrations."),
            ("API Documentation with OpenAPI/Swagger", "Generating interactive, standardized documentation directly from an API specification."),
            ("Microservices Architecture for Web Applications", "Decomposing a web backend into independently deployable, loosely coupled services."),
            ("Containerizing Web Applications with Docker", "Packaging web applications and their dependencies into portable containers."),
            ("CI/CD Pipelines for Web Deployment", "Automating build, test, and deployment stages for web application releases."),
            ("Serverless Functions for Web Backends", "Running backend logic on demand without managing dedicated server infrastructure."),
            ("Edge Computing for Web Applications", "Running code closer to users at the network edge to reduce latency."),
            ("Relational versus NoSQL Database Design for Web Apps", "Comparing data modeling trade-offs between relational and document-based databases."),
            ("Caching Layers with Redis", "Using an in-memory data store to reduce database load and speed up responses."),
            ("Message Queues (RabbitMQ, Kafka) in Web Architectures", "Decoupling services using asynchronous message passing for reliability and scale."),
            ("WebRTC for Peer-to-Peer Communication", "Enabling direct browser-to-browser audio, video, and data communication."),
            ("Server-Sent Events versus WebSockets", "Comparing one-way and bidirectional real-time communication techniques for the web."),
            ("Progressive Enhancement Strategies", "Building a functional baseline experience that layers in enhancements for capable browsers."),
            ("Browser Compatibility and Polyfilling", "Ensuring consistent behavior across browsers using feature detection and polyfills."),
            ("Web Performance Profiling with Lighthouse and DevTools", "Diagnosing performance bottlenecks using browser auditing and profiling tools."),
            ("SEO Fundamentals for Web Developers", "Applying technical practices that help search engines index and rank web content."),
            ("Structured Data and Schema.org Markup", "Annotating page content so search engines can display rich, structured results."),
            ("Headless CMS Architecture", "Decoupling content management from presentation using API-driven content platforms."),
            ("E-Commerce Platform Architecture", "Designing the backend systems supporting product catalogs, carts, and checkout."),
            ("Payment Gateway Integration", "Integrating third-party payment processors securely into a web application."),
            ("Automated Accessibility Testing Pipelines", "Embedding automated accessibility checks into a continuous integration workflow."),
            ("Cookie Consent and GDPR Compliance for Web Apps", "Implementing consent mechanisms and data handling practices required by privacy law."),
            ("Web Analytics Implementation", "Instrumenting web applications to capture and interpret user behavior data."),
            ("Feature Flags and A/B Testing Infrastructure", "Rolling out features gradually and testing variants using flag-driven infrastructure."),
            ("Monorepo Management for Web Projects", "Organizing multiple related packages and applications within a single repository."),
            ("Package Management with npm, Yarn, and pnpm", "Comparing JavaScript package managers and their dependency resolution strategies."),
            ("Deployment Strategies: Blue-Green and Canary Releases", "Comparing release strategies that reduce risk when deploying new web application versions."),
            ("CDN Edge Caching Strategies", "Configuring content delivery networks to cache and serve assets close to users."),
            ("WebAssembly Fundamentals for Web Developers", "Running near-native performance code in the browser using a portable binary format."),
        ],
    },
    "World History": {
        "UG3": [
            ("Ancient Mesopotamia: Law, Writing, and Empire", "Examining the development of early legal codes, cuneiform writing, and imperial rule in Mesopotamia."),
            ("Ancient Egypt: State Formation and Religion", "Studying the political and religious institutions that sustained ancient Egyptian civilization."),
            ("The Indus Valley Civilization", "Examining the urban planning, trade, and undeciphered script of the Indus Valley culture."),
            ("The Qin and Han Dynasties in Ancient China", "Studying imperial unification and the institutions established during early Chinese dynasties."),
            ("Athenian Democracy and Its Limits", "Analyzing the structure of Athenian democratic institutions and who was excluded from them."),
            ("The Peloponnesian War", "Examining the causes and consequences of the conflict between Athens and Sparta."),
            ("The Roman Republic's Transition to Empire", "Tracing the political crises that transformed the Roman Republic into an imperial system."),
            ("The Byzantine Empire and Its Legacy", "Studying how the Eastern Roman Empire preserved and transformed classical traditions."),
            ("The Crusades: Causes and Consequences", "Analyzing the religious, political, and economic motivations behind the Crusades and their aftermath."),
            ("Trans-Saharan Trade Networks", "Examining how gold, salt, and slave trade routes connected West Africa to the Mediterranean world."),
            ("The Silk Road and Cross-Cultural Exchange", "Studying how overland trade routes facilitated the exchange of goods, ideas, and disease."),
            ("The Age of Exploration: Portuguese and Spanish Voyages", "Examining the motivations and consequences of early European maritime expansion."),
            ("The Protestant Reformation", "Analyzing the religious and political upheaval sparked by challenges to Catholic Church authority."),
            ("The Ottoman Empire: Rise and Administration", "Studying the governance systems that sustained the Ottoman Empire across centuries."),
            ("The Mughal Empire in South Asia", "Examining the political and cultural achievements of Mughal rule in the Indian subcontinent."),
            ("Tokugawa Japan and Sakoku Policy", "Studying Japan's period of relative isolation and internal stability under Tokugawa rule."),
            ("The Qing Dynasty and Manchu Rule in China", "Examining how Manchu rulers governed and expanded China's last imperial dynasty."),
            ("The French Revolution: Causes and Radicalization", "Analyzing the social and political forces that drove the French Revolution's escalation."),
            ("The Haitian Revolution", "Studying the successful slave uprising that established the first Black-led republic."),
            ("Latin American Independence Movements", "Examining the leaders and forces that ended Spanish and Portuguese colonial rule in Latin America."),
            ("The Opium Wars and Treaty Ports in China", "Studying how conflict over trade reshaped China's relationship with Western powers."),
            ("The Meiji Restoration and Japanese Modernization", "Analyzing how Japan rapidly modernized its institutions in response to Western pressure."),
            ("The Scramble for Africa and the Berlin Conference", "Examining how European powers partitioned African territory in the late nineteenth century."),
            ("Causes of World War I Beyond the July Crisis", "Analyzing the longer-term alliance systems and militarism that set the stage for war."),
            ("The Russian Revolution of 1917", "Studying the collapse of tsarist rule and the Bolshevik seizure of power."),
            ("The Interwar Period and the Rise of Fascism", "Examining the economic and political conditions that enabled fascist movements to gain power."),
            ("The Spanish Civil War", "Analyzing the ideological conflict and foreign intervention that shaped the Spanish Civil War."),
            ("World War II: The Pacific Theater", "Studying the military campaigns and strategic decisions that shaped the war in the Pacific."),
            ("The Marshall Plan and Postwar Reconstruction", "Examining how American aid shaped the economic recovery of postwar Europe."),
            ("The Non-Aligned Movement", "Studying how newly independent states sought to avoid alignment with Cold War blocs."),
            ("Indian Independence and the Partition of 1947", "Analyzing the process and human consequences of British India's independence and partition."),
            ("The Korean War", "Examining the causes and outcomes of the conflict that divided the Korean peninsula."),
            ("The Vietnam War", "Studying the political and military dimensions of the conflict in Vietnam."),
            ("Origins of the Arab-Israeli Conflict", "Examining the historical roots of the territorial and political disputes in the region."),
            ("The Iranian Revolution of 1979", "Analyzing the forces that overthrew the Shah and established an Islamic republic."),
            ("Apartheid and Its Collapse in South Africa", "Studying the system of racial segregation and the movement that ended it."),
            ("The Rwandan Genocide", "Examining the historical background and international response to the 1994 genocide."),
            ("The Yugoslav Wars and the Breakup of Yugoslavia", "Studying the ethnic and political conflicts that dissolved the former Yugoslav federation."),
            ("The Arab Spring", "Analyzing the causes and varied outcomes of the wave of Middle Eastern protest movements."),
            ("China's Rise as a Global Power", "Examining the economic reforms and policies behind China's modern global influence."),
            ("The Formation of the European Union", "Studying the postwar process of European economic and political integration."),
            ("Cold War Proxy Conflicts in Latin America", "Examining how superpower rivalry shaped conflicts across Latin America."),
            ("The Bandung Conference and Third World Solidarity", "Studying the 1955 conference that launched a movement of newly independent nations."),
            ("Global Women's Suffrage Movements", "Comparing the strategies and timelines of suffrage movements across different countries."),
            ("The Global Protest Movements of the 1960s", "Examining the interconnected social and political upheavals of the 1960s worldwide."),
            ("GATT, the WTO, and the History of Trade Globalization", "Studying the institutions that shaped the postwar liberalization of global trade."),
            ("The Black Death and Its Historical Impact", "Examining how the fourteenth-century pandemic reshaped European society and economy."),
            ("The Great Depression as a Global Phenomenon", "Studying how the 1930s economic crisis spread and was experienced across the world."),
            ("Environmental History and the Anthropocene", "Examining how human activity has reshaped the natural environment across history."),
            ("The Global History of Human Rights Movements", "Studying the development of human rights norms and movements across the twentieth century."),
            ("Indigenous Resistance Movements Across Continents", "Comparing how indigenous peoples resisted colonization across different regions."),
            ("Comparative Revolutions: French, Russian, and Chinese", "Comparing the causes, processes, and outcomes of three major modern revolutions."),
            ("The History of Nuclear Weapons Proliferation", "Examining the development and spread of nuclear weapons technology since 1945."),
            ("The Space Race", "Studying the Cold War competition that drove rapid advances in space exploration."),
            ("Decolonization in Southeast Asia", "Examining the end of colonial rule and its aftermath across Southeast Asian nations."),
            ("The Legacy of Colonial Borders in Africa", "Studying how arbitrary colonial boundaries continue to shape African politics."),
            ("The Congress of Vienna and the Balance of Power", "Examining how European powers redrew borders and restored order after the Napoleonic Wars."),
            ("The Berlin Wall: Construction and Fall", "Studying the symbolism and history of the wall that divided Cold War Berlin."),
            ("The Bretton Woods System", "Examining the postwar international monetary system and its lasting institutions."),
            ("The History of Global Migration Patterns", "Analyzing major waves of human migration and their long-term historical effects."),
        ],
    },
    "World Literature": {
        "UG3": [
            ("Russian Realism: Tolstoy and Dostoevsky", "Examining how nineteenth-century Russian novelists explored morality, society, and the human psyche."),
            ("French Existentialist Literature: Camus and Sartre", "Studying how existentialist writers used fiction to explore freedom, absurdity, and meaning."),
            ("Kafka and the Literature of Alienation", "Examining themes of bureaucracy, isolation, and dehumanization in Kafka's fiction."),
            ("The Gothic Novel Tradition", "Tracing how Gothic fiction uses atmosphere, horror, and the supernatural to explore anxiety."),
            ("European Romanticism in Poetry and Prose", "Examining how Romantic writers emphasized emotion, nature, and individualism."),
            ("The Victorian Novel and Social Reform", "Studying how nineteenth-century British novelists engaged with industrialization and inequality."),
            ("Magical Realism: Garcia Marquez and Latin American Fiction", "Examining how magical realism blends the fantastical with everyday life in Latin American writing."),
            ("The Latin American Boom Generation", "Studying the mid-twentieth-century surge of internationally acclaimed Latin American novelists."),
            ("The Beat Generation and Postwar American Poetry", "Examining how Beat writers challenged conformity through experimental style and voice."),
            ("Absurdist Theatre: Beckett and Ionesco", "Studying how absurdist playwrights depicted meaninglessness through fragmented dramatic form."),
            ("Greek Tragedy: Sophocles and Euripides", "Examining how classical Greek tragedians dramatized fate, hubris, and moral conflict."),
            ("Modern Japanese Literature: Kawabata and Mishima", "Studying how mid-century Japanese novelists engaged tradition, beauty, and modern identity."),
            ("Contemporary Japanese Fiction: Murakami's Literary World", "Examining recurring themes of memory, surrealism, and isolation in contemporary Japanese fiction."),
            ("Modern Chinese Literature: Lu Xun and Social Critique", "Studying how early modern Chinese fiction critiqued tradition and social injustice."),
            ("Arabic Literature and Naguib Mahfouz's Cairo Trilogy", "Examining how a landmark work of modern Arabic fiction chronicles generational change in Cairo."),
            ("Anglophone African Literature: Achebe and Ngugi wa Thiong'o", "Studying how postcolonial African novelists respond to colonial legacy and cultural identity."),
            ("Caribbean Literature: Walcott and Kincaid", "Examining how Caribbean writers address history, language, and identity in the region."),
            ("Scandinavian Drama: Ibsen and Strindberg", "Studying how Scandinavian playwrights pioneered modern realist and psychological drama."),
            ("Spanish Golden Age Literature: Cervantes and Don Quixote", "Examining the foundational work of the modern novel and its exploration of idealism and reality."),
            ("Italian Literature: Dante's Divine Comedy", "Studying the medieval allegorical journey through the afterlife and its literary influence."),
            ("Italian Postmodernism: Calvino's Fictional Worlds", "Examining how playful, self-aware narrative structures characterize Calvino's fiction."),
            ("Irish Literary Modernism: Joyce and Yeats", "Studying how Irish modernists reshaped narrative form and poetic voice in the early twentieth century."),
            ("American Southern Gothic: Faulkner's Fiction", "Examining themes of history, decay, and family in Faulkner's Southern narratives."),
            ("American Literature: Hemingway's Prose Style", "Studying the spare, understated prose style associated with modern American fiction."),
            ("Toni Morrison and African American Literary Tradition", "Examining how Morrison's fiction engages memory, race, and history in American life."),
            ("Feminist Literary Theory and Women's Writing Traditions", "Studying critical frameworks used to analyze gender and voice in literary traditions."),
            ("Postmodern Metafiction and Narrative Experimentation", "Examining fiction that self-consciously draws attention to its own constructed nature."),
            ("The Epistolary Novel Tradition", "Studying novels told through letters and how the form shapes narrative intimacy."),
            ("The Bildungsroman Across National Literatures", "Comparing coming-of-age novel traditions across different literary cultures."),
            ("Literary Naturalism: Zola and Social Determinism", "Examining how naturalist writers depicted characters shaped by heredity and environment."),
            ("The Symbolist Poetry Movement", "Studying how Symbolist poets used suggestive imagery over direct statement."),
            ("Surrealism in Literature", "Examining how Surrealist writers used dream logic and unconscious imagery in their work."),
            ("Holocaust Literature: Wiesel and Levi", "Studying how survivor-authors bore witness to the Holocaust through memoir and narrative."),
            ("World War I Poetry: Owen and Sassoon", "Examining how war poets depicted the disillusionment and horror of trench warfare."),
            ("Literature of Exile and Displacement", "Studying how writers depict the psychological and cultural effects of forced displacement."),
            ("Oral Tradition and Folklore Studies", "Examining how oral storytelling traditions preserve and transmit cultural knowledge."),
            ("Comparative Mythology Across Cultures", "Comparing recurring mythological structures and archetypes across world cultures."),
            ("Sufi Poetry: Rumi and Hafez", "Studying how mystical Persian poetry expresses divine love and spiritual longing."),
            ("Classical Sanskrit Literature and Drama", "Examining foundational works of classical Indian poetry and dramatic tradition."),
            ("Classical Persian Literature Beyond Sufi Poetry", "Studying epic and courtly traditions in classical Persian literary history."),
            ("British Literary Modernism: Woolf and Eliot", "Examining stream-of-consciousness narration and fragmented form in British modernist writing."),
            ("The Picaresque Novel Tradition", "Studying episodic narratives following a roguish protagonist through varied social encounters."),
            ("Satire in World Literature: Swift and Voltaire", "Examining how satirical writers used irony and exaggeration to critique society."),
            ("Utopian and Dystopian Literature: Orwell and Huxley", "Comparing fictional visions of engineered societies and their political warnings."),
            ("Zamyatin's We and the Origins of Dystopian Fiction", "Studying an early dystopian novel's influence on the genre's later development."),
            ("Science Fiction as World Literature", "Examining how speculative fiction traditions developed across different literary cultures."),
            ("Children's Literature in Translation", "Studying how children's texts are adapted and reshaped when translated across languages."),
            ("The Sonnet Tradition Across Languages", "Comparing how the sonnet form has been adapted across different literary traditions."),
            ("Epic Poetry: Homer and Virgil", "Examining foundational epic narratives and their conventions of heroism and fate."),
            ("Verse Drama and Its Modern Revivals", "Studying how playwrights have returned to poetic form in modern theatrical works."),
            ("New Criticism and Close Reading", "Examining a critical approach that focuses on the text itself over historical context."),
            ("Structuralism and Post-Structuralism in Literary Theory", "Comparing frameworks that analyze underlying structures and the instability of meaning in texts."),
            ("Reader-Response and Reception Theory", "Studying how meaning is shaped by the reader's interpretive engagement with a text."),
            ("World Literature Canon Formation Debates", "Examining the debates over which works are included in a global literary canon."),
            ("Translation Theory: Domestication versus Foreignization", "Comparing translation strategies that adapt versus preserve the foreignness of a source text."),
            ("Literature and Nation-Building Narratives", "Studying how literary works have been used to construct and contest national identity."),
            ("Contemporary African Diaspora Writing", "Examining how contemporary diaspora authors address migration, identity, and belonging."),
            ("Fabulism versus Magical Realism: Genre Distinctions", "Comparing related but distinct modes of blending the fantastical with realist narrative."),
            ("The Personal Essay Tradition: Montaigne to Modern Writers", "Tracing the development of the reflective personal essay as a literary form."),
            ("Verse Novels and Hybrid Literary Forms", "Examining narrative works that blend poetic and novelistic conventions."),
        ],
    },
}
