"""
Additional UG1 topic tuples (title, summary) for 11 EduAi_Pro subjects.

Consumed by backend/scripts/merge_all_subjects_expansion.py, which builds
full lesson objects from these (title, summary) pairs. Each subject below
supplies 60 NEW undergraduate-level topics that do not duplicate the
20 topics already present in backend/syllabus/level_ug1.json for that
subject at the UG1 level.
"""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Project Management": {
        "UG1": [
            ("Project Scope Statement Development", "Drafting a clear scope statement that defines project boundaries, deliverables, and exclusions."),
            ("Work Breakdown Structure (WBS) Construction", "Decomposing project deliverables into manageable work packages using a hierarchical WBS."),
            ("Scope Creep and Change Control", "Recognizing uncontrolled scope expansion and applying formal change control procedures to manage it."),
            ("Requirements Elicitation Techniques", "Using interviews, workshops, and surveys to gather accurate stakeholder requirements."),
            ("Project Charter Development", "Authoring a charter that formally authorizes a project and defines its objectives and authority."),
            ("Stakeholder Identification and Analysis", "Mapping stakeholders by power and interest to prioritize engagement efforts."),
            ("Stakeholder Engagement Assessment Matrix", "Tracking stakeholders' current versus desired engagement levels throughout a project's life cycle."),
            ("Communication Planning for Projects", "Designing a communications management plan that specifies audience, content, frequency, and channel."),
            ("RACI Matrix and Responsibility Assignment", "Clarifying roles using a Responsible, Accountable, Consulted, Informed matrix for project tasks."),
            ("Critical Path Method (CPM) Scheduling", "Calculating the longest sequence of dependent tasks that determines a project's minimum duration."),
            ("Precedence Diagramming Method", "Modeling task dependencies as a network diagram to visualize sequencing and logic."),
            ("Gantt Chart Construction and Interpretation", "Building and reading Gantt charts to communicate schedules, dependencies, and progress."),
            ("Schedule Compression: Crashing and Fast-Tracking", "Comparing techniques for shortening a project schedule by adding resources or overlapping activities."),
            ("Resource Leveling and Smoothing", "Adjusting a schedule to resolve resource over-allocation while respecting project constraints."),
            ("Program Evaluation and Review Technique (PERT)", "Estimating task durations probabilistically using optimistic, pessimistic, and most-likely values."),
            ("Milestone Planning and Tracking", "Using milestones as checkpoints to monitor major achievements and decision points in a project."),
            ("Project Quality Planning", "Defining quality standards, metrics, and acceptance criteria before execution begins."),
            ("Quality Assurance vs Quality Control", "Distinguishing process-focused quality assurance from product-focused quality control activities."),
            ("Six Sigma Fundamentals for Project Quality", "Applying DMAIC and statistical thinking to reduce defects and variation in project outputs."),
            ("Statistical Process Control in Projects", "Using control charts to monitor whether a process remains within acceptable variation limits."),
            ("Procurement Planning and Make-or-Buy Analysis", "Deciding whether to produce a deliverable internally or purchase it from an external supplier."),
            ("Request for Proposal (RFP) Development", "Structuring an RFP document that solicits comparable, evaluable vendor proposals."),
            ("Vendor Selection and Evaluation Criteria", "Building weighted scoring models to compare bidders on cost, quality, and capability."),
            ("Contract Negotiation Strategies", "Applying negotiation tactics and BATNA analysis to reach favorable project contract terms."),
            ("Human Resource Planning for Projects", "Forecasting staffing needs and building a resource management plan for a project team."),
            ("Team Development Stages (Tuckman's Model)", "Applying forming, storming, norming, and performing to explain team maturation over time."),
            ("Conflict Resolution Techniques in Project Teams", "Comparing collaboration, compromise, and other conflict-handling modes for project disputes."),
            ("Servant Leadership in Project Management", "Examining a leadership style that prioritizes team support and removal of obstacles."),
            ("Motivation Theories Applied to Project Teams", "Using Maslow, Herzberg, and expectancy theory to explain and improve team motivation."),
            ("Virtual and Distributed Team Management", "Addressing coordination, trust, and communication challenges in geographically dispersed teams."),
            ("Agile Project Management Principles", "Examining the values and principles of the Agile Manifesto as applied to project delivery."),
            ("Scrum Framework: Roles, Events, Artifacts", "Detailing the Scrum Master, Product Owner, and Development Team roles alongside sprint ceremonies."),
            ("Kanban Method for Workflow Management", "Visualizing work-in-progress limits and flow using a Kanban board to improve throughput."),
            ("Sprint Planning and Backlog Grooming", "Prioritizing and refining a product backlog to prepare actionable items for an upcoming sprint."),
            ("Agile Estimation: Story Points and Planning Poker", "Using relative sizing techniques to estimate effort for user stories collaboratively."),
            ("Hybrid Project Management Approaches", "Combining predictive and agile elements to fit projects with mixed certainty and complexity."),
            ("The Waterfall Model and Its Limitations", "Analyzing the sequential phase-gate approach and the conditions under which it underperforms."),
            ("PRINCE2 Methodology Overview", "Surveying the structured PRINCE2 framework of processes, themes, and principles."),
            ("Project Management Office (PMO) Functions", "Describing how a PMO standardizes governance, methodology, and reporting across projects."),
            ("Project Portfolio Management", "Selecting and balancing a set of projects to align with organizational strategy and capacity."),
            ("Program Management vs Project Management", "Differentiating the coordination of related projects for benefits from single-project delivery."),
            ("Project Selection Methods and Scoring Models", "Comparing payback period, NPV, and weighted scoring models for choosing among candidate projects."),
            ("Business Case Development", "Constructing a business case that justifies a project's investment against expected benefits."),
            ("Benefits Realization Management", "Tracking whether a project's intended business benefits are actually achieved post-delivery."),
            ("Project Governance Structures", "Defining decision rights, escalation paths, and oversight bodies for project accountability."),
            ("Change Management in Organizations", "Applying models such as Kotter's eight steps to manage organizational transitions during projects."),
            ("Organizational Change Readiness Assessment", "Evaluating an organization's capacity and willingness to absorb project-driven change."),
            ("Project Closure and Lessons Learned", "Formally closing contracts, releasing resources, and capturing lessons for future projects."),
            ("Post-Implementation Review Techniques", "Assessing a completed project's outcomes against its original objectives and business case."),
            ("Knowledge Management in Projects", "Capturing and transferring tacit and explicit project knowledge across teams and time."),
            ("Project Management Software and Tools Landscape", "Comparing scheduling, collaboration, and tracking tools used across the project life cycle."),
            ("Configuration Management in Projects", "Controlling changes to a product's functional and physical attributes throughout its life cycle."),
            ("Document Control and Version Management", "Establishing procedures to manage project document revisions, approvals, and distribution."),
            ("Ethics and Professional Responsibility in Project Management", "Examining codes of conduct governing honesty, fairness, and conflict of interest for project managers."),
            ("Cross-Cultural Project Management", "Adapting communication and leadership styles for culturally diverse, international project teams."),
            ("Project Management for Construction Industry", "Applying scheduling, cost, and safety practices specific to construction project delivery."),
            ("Project Management for Information Technology", "Addressing the unique risks and methodologies used in software and systems projects."),
            ("Project Management for Event Planning", "Applying project management disciplines to the logistics and timeline of large-scale events."),
            ("Sustainability and Green Project Management", "Incorporating environmental and social impact criteria into project planning and execution."),
            ("Project Recovery Techniques for Troubled Projects", "Diagnosing failing projects and applying corrective strategies to return them to a viable path."),
        ],
    },
    "Prompt Engineering": {
        "UG1": [
            ("Zero-Shot Prompting Techniques", "Crafting instructions that elicit correct model behavior without providing worked examples."),
            ("Few-Shot Prompting and Example Selection", "Choosing and ordering demonstration examples to steer a model's output format and reasoning."),
            ("Chain-of-Thought Prompting", "Eliciting intermediate reasoning steps from a model to improve accuracy on multi-step problems."),
            ("Self-Consistency Decoding for Reasoning Prompts", "Sampling multiple reasoning paths and aggregating answers to improve reliability."),
            ("Tree-of-Thought Prompting", "Structuring prompts to explore and evaluate multiple branching reasoning paths before answering."),
            ("ReAct: Reasoning and Acting Prompts", "Interleaving reasoning traces with tool-invoking actions within a single prompting loop."),
            ("System Prompts and Instruction Hierarchies", "Designing top-level system instructions that set persistent behavior and priority over user turns."),
            ("In-Context Learning: Theoretical Foundations", "Examining hypotheses for why transformer models can learn tasks from prompt examples alone."),
            ("Prompt Sensitivity and Robustness Testing", "Measuring how small wording changes in a prompt affect output quality and consistency."),
            ("Temperature and Sampling Parameter Tuning", "Adjusting temperature and related decoding parameters to control output randomness."),
            ("Top-p (Nucleus) Sampling Explained", "Understanding how nucleus sampling truncates the probability distribution during generation."),
            ("Structured Output Generation (JSON Mode)", "Constraining model responses to valid, schema-conforming structured formats."),
            ("Output Parsing and Validation Strategies", "Building robust parsers and validators for downstream consumption of model responses."),
            ("Function Calling and Tool-Use Prompts", "Designing prompts that let a model select and invoke external functions or APIs."),
            ("Retrieval-Augmented Generation (RAG) Fundamentals", "Combining document retrieval with generation to ground model responses in external knowledge."),
            ("Vector Embeddings for Semantic Search", "Representing text as dense vectors to enable similarity-based retrieval for prompting pipelines."),
            ("Chunking Strategies for Retrieval Systems", "Splitting source documents into retrievable units that balance context and precision."),
            ("Prompt Chaining for Multi-Step Tasks", "Decomposing a complex task into a sequence of dependent prompts passed between calls."),
            ("Agentic Workflow Design with LLMs", "Architecting autonomous loops where a model plans, acts, and observes toward a goal."),
            ("Memory Management in Conversational Agents", "Designing short-term and long-term memory mechanisms for multi-session agent interactions."),
            ("Prompt Compression Techniques", "Reducing prompt token length while preserving task-relevant information and instructions."),
            ("Cost Optimization in LLM API Usage", "Balancing model choice, prompt length, and caching to minimize inference costs."),
            ("Model Selection for Prompting Tasks", "Matching task requirements to model capability, latency, and cost tradeoffs."),
            ("Prompting for Code Generation", "Structuring prompts that produce correct, idiomatic code with appropriate specifications."),
            ("Prompting for Text Summarization", "Designing prompts that control summary length, focus, and abstraction level."),
            ("Prompting for Text Classification", "Framing classification tasks as prompts with clear label definitions and decision boundaries."),
            ("Prompting for Machine Translation", "Crafting prompts that preserve meaning, tone, and idiom across source and target languages."),
            ("Prompt Injection Attacks and Defenses", "Identifying how malicious input can hijack model behavior and mitigating such attacks."),
            ("Jailbreaking Techniques and Mitigations", "Studying methods used to bypass model safety constraints and corresponding countermeasures."),
            ("Guardrails for LLM Output Safety", "Implementing pre- and post-processing filters that enforce safety and policy constraints."),
            ("Bias Detection in Model Outputs", "Identifying systematic unfair patterns in generated content across demographic groups."),
            ("Hallucination: Causes and Mitigation Strategies", "Explaining why models generate false content and techniques to reduce its occurrence."),
            ("Calibration and Confidence Estimation in LLM Outputs", "Assessing whether a model's expressed confidence matches its actual accuracy."),
            ("Adversarial Prompting and Red Teaming", "Systematically probing a model with adversarial inputs to uncover failure modes."),
            ("Constitutional AI Principles", "Examining rule-based self-critique methods used to align model behavior without human labels."),
            ("Reinforcement Learning from Human Feedback (RLHF) Basics", "Describing how human preference data trains reward models that fine-tune LLM behavior."),
            ("Fine-Tuning vs Prompting: Tradeoffs", "Comparing the cost, flexibility, and performance tradeoffs of fine-tuning against prompting."),
            ("Instruction Tuning Fundamentals", "Explaining how training on instruction-response pairs improves a model's prompt-following ability."),
            ("Prompt Evaluation Metrics: BLEU and ROUGE", "Applying automated overlap-based metrics to evaluate generated text quality."),
            ("Human Evaluation Protocols for LLM Outputs", "Designing rubrics and rater workflows for assessing subjective output quality."),
            ("A/B Testing Prompts in Production", "Running controlled experiments to compare prompt variants on live user outcomes."),
            ("Multi-Turn Conversation Design", "Structuring prompts and state across multiple conversational turns for coherence."),
            ("Persona Consistency Across Long Conversations", "Maintaining a stable assistant persona and tone over extended dialogue sessions."),
            ("Ethical Considerations in Prompt Design", "Weighing privacy, consent, and harm-avoidance concerns when designing prompts."),
            ("Prompting for Data Extraction from Unstructured Text", "Designing prompts that reliably pull structured fields from free-form documents."),
            ("Prompting for Question Answering Systems", "Structuring prompts that produce accurate, well-grounded answers to user questions."),
            ("Self-Reflection and Self-Critique Prompting", "Having a model evaluate and revise its own prior output to improve quality."),
            ("Prompt Engineering for Multimodal Models", "Designing prompts that combine text with images, audio, or other modalities."),
            ("Image-to-Text Prompting Techniques", "Crafting prompts that guide vision-language models to describe or reason about images."),
            ("Prompting Strategies for Long-Context Windows", "Structuring prompts to make effective use of very large context windows."),
            ("Token Budgeting and Context Window Management", "Allocating limited token space across instructions, examples, and retrieved content."),
            ("Retrieval Query Reformulation Techniques", "Rewriting user queries to improve retrieval relevance in RAG pipelines."),
            ("Semantic Caching for LLM Applications", "Caching responses based on semantic similarity of prompts to reduce redundant calls."),
            ("Prompt-Based Data Augmentation", "Using LLM prompts to generate synthetic training examples for downstream models."),
            ("Negative Prompting Techniques", "Specifying what a model should avoid producing to refine generation quality."),
            ("Prompting for Named Entity Recognition", "Designing prompts that accurately identify and label entities within text."),
            ("Evaluating Faithfulness in RAG Outputs", "Measuring whether generated answers are actually supported by retrieved source documents."),
            ("Prompt Engineering for Agentic Planning", "Structuring prompts that decompose goals into ordered, executable sub-tasks."),
            ("Debugging and Iterating on Failed Prompts", "Applying systematic methods to diagnose and fix prompts that produce poor outputs."),
            ("Prompt Engineering Career Paths and Industry Applications", "Surveying how prompt engineering skills are applied across product, research, and consulting roles."),
        ],
    },
    "Python": {
        "UG1": [
            ("Classes and Object-Oriented Programming Fundamentals", "Defining classes, instances, and attributes to model data and behavior together."),
            ("Inheritance and Method Resolution Order (MRO)", "Explaining how Python resolves attribute and method lookups across a class hierarchy."),
            ("Multiple Inheritance in Python", "Combining behavior from several parent classes and understanding the resulting MRO."),
            ("Polymorphism and Duck Typing", "Writing code that works with any object exposing the expected interface, regardless of type."),
            ("Magic Methods and Operator Overloading", "Implementing dunder methods to customize how objects respond to built-in operators."),
            ("Properties and the @property Decorator", "Exposing computed or validated attributes through Python's property mechanism."),
            ("Class Methods and Static Methods", "Distinguishing instance, class, and static methods and their appropriate use cases."),
            ("Abstract Base Classes with the abc Module", "Defining interfaces that subclasses must implement using Python's abc module."),
            ("The dataclasses Module", "Reducing boilerplate for classes that primarily store data using the dataclass decorator."),
            ("The enum Module for Enumerated Types", "Defining sets of named constants with the enum module for clearer, safer code."),
            ("Descriptors and Attribute Access Control", "Implementing the descriptor protocol to customize attribute get, set, and delete behavior."),
            ("Metaclasses in Python", "Understanding how classes themselves are instances of metaclasses and how to customize class creation."),
            ("Iterators and the Iterator Protocol", "Implementing __iter__ and __next__ to create custom iterable objects."),
            ("Generators and the yield Keyword", "Writing memory-efficient generator functions that produce values lazily."),
            ("Generator Expressions vs List Comprehensions", "Comparing lazy generator expressions with eagerly evaluated list comprehensions."),
            ("Decorators: Writing Custom Function Decorators", "Wrapping functions to add behavior such as timing, logging, or caching."),
            ("Decorators with Arguments", "Building parameterized decorators that accept configuration options."),
            ("Class Decorators", "Applying decorators to entire classes to modify or extend their behavior."),
            ("Closures and Lexical Scoping", "Explaining how nested functions capture and retain access to enclosing variables."),
            ("Lambda Functions and Functional Programming Idioms", "Using anonymous functions alongside map, filter, and reduce for concise data transformations."),
            ("Recursion and Recursive Algorithm Design", "Designing recursive solutions and analyzing base cases, recursive cases, and stack depth."),
            ("Implementing a Linked List in Python", "Building singly and doubly linked list data structures from scratch."),
            ("Implementing a Stack and Queue in Python", "Constructing stack and queue abstractions and analyzing their operational complexity."),
            ("Implementing a Binary Search Tree in Python", "Building a binary search tree with insertion, search, and traversal operations."),
            ("Sorting Algorithms Implemented in Python", "Implementing and comparing bubble, merge, and quick sort in Python."),
            ("Searching Algorithms Implemented in Python", "Implementing linear and binary search and analyzing their time complexity."),
            ("Big-O Notation and Algorithmic Complexity Analysis", "Analyzing time and space complexity of Python code using asymptotic notation."),
            ("Threading in Python and the Global Interpreter Lock (GIL)", "Explaining how the GIL constrains true parallelism in multi-threaded Python programs."),
            ("The multiprocessing Module for Parallelism", "Achieving true parallel execution across CPU cores using separate processes."),
            ("Asynchronous Programming with asyncio", "Writing non-blocking concurrent code using Python's asyncio event loop."),
            ("async/await Syntax and Coroutines", "Defining and composing coroutines using async def and await expressions."),
            ("The concurrent.futures Module", "Using ThreadPoolExecutor and ProcessPoolExecutor for simplified concurrent task execution."),
            ("Thread Synchronization with Locks and Queues", "Coordinating access to shared resources safely across multiple threads."),
            ("Python Memory Management and Garbage Collection", "Explaining reference counting and cyclic garbage collection in CPython."),
            ("Weak References in Python", "Using the weakref module to reference objects without preventing their garbage collection."),
            ("Structural Typing with Protocol Classes", "Defining structural interfaces using typing.Protocol for duck-typed static checking."),
            ("Generic Types and the typing Module", "Writing type-safe generic functions and classes using Python's typing constructs."),
            ("Virtual Environments with venv", "Isolating project dependencies using Python's built-in virtual environment tooling."),
            ("Dependency Management with pip and requirements.txt", "Managing and pinning third-party package dependencies for reproducible installs."),
            ("Python Packaging with pyproject.toml", "Configuring modern Python package metadata and build systems with pyproject.toml."),
            ("Publishing a Package to PyPI", "Building, tagging, and uploading a distributable Python package to the Python Package Index."),
            ("Profiling Python Code with cProfile", "Identifying performance bottlenecks in Python programs using built-in profiling tools."),
            ("Debugging with pdb", "Using Python's interactive debugger to step through code and inspect program state."),
            ("JSON Serialization and Deserialization", "Converting Python objects to and from JSON using the json module."),
            ("The pickle Module for Object Serialization", "Serializing arbitrary Python objects to bytes for storage or transmission."),
            ("Working with SQLite Databases in Python", "Connecting to and querying SQLite databases using Python's sqlite3 module."),
            ("Introduction to SQLAlchemy ORM", "Mapping Python classes to database tables using the SQLAlchemy object-relational mapper."),
            ("The subprocess Module for External Processes", "Launching and communicating with external processes from within a Python program."),
            ("Socket Programming Basics in Python", "Building simple client-server network applications using Python's socket module."),
            ("Environment Variables and Configuration Management", "Managing application configuration securely using environment variables and config files."),
            ("Web Scraping with Requests and BeautifulSoup", "Fetching and parsing HTML content to extract structured data from web pages."),
            ("Consuming REST APIs with the requests Library", "Making HTTP requests and handling JSON responses from external web services."),
            ("Building GUIs with Tkinter", "Creating simple desktop graphical interfaces using Python's built-in Tkinter library."),
            ("Introduction to NumPy Arrays", "Performing efficient numerical computation using NumPy's array data structure."),
            ("Introduction to Pandas DataFrames", "Loading, cleaning, and analyzing tabular data using the pandas DataFrame."),
            ("Data Visualization with Matplotlib", "Creating basic charts and plots to visualize data using Matplotlib."),
            ("Writing Command-Line Tools with Python", "Building distributable command-line applications with clear interfaces and entry points."),
            ("Code Coverage Analysis with coverage.py", "Measuring which lines of code are exercised by a test suite using coverage.py."),
            ("Parametrized Testing in pytest", "Running the same test logic across multiple input combinations using pytest parametrization."),
            ("Python Design Patterns: Singleton, Factory, and Observer", "Applying classic object-oriented design patterns idiomatically in Python."),
        ],
    },
    "R": {
        "UG1": [
            ("R Data Structures: Vectors, Lists, and Matrices", "Comparing R's core data structures and their appropriate use cases for statistical work."),
            ("Data Frames and Factors in R", "Storing tabular data and categorical variables using data frames and factors."),
            ("Control Flow: Conditionals and Loops in R", "Writing if/else logic and for/while loops to control program execution in R."),
            ("Writing Custom Functions in R", "Defining reusable functions with default arguments and explicit return values in R."),
            ("The apply Family: sapply, lapply, vapply, mapply", "Applying functions over vectors, lists, and matrices without explicit loops."),
            ("Vectorization and Avoiding Explicit Loops", "Rewriting loop-based R code as vectorized operations for clarity and speed."),
            ("Introduction to the tidyverse Ecosystem", "Surveying the family of R packages designed around a consistent data-science grammar."),
            ("Data Visualization with ggplot2: The Grammar of Graphics", "Building layered visualizations by mapping data to aesthetics, geoms, and scales."),
            ("Customizing ggplot2 Themes and Aesthetics", "Adjusting colors, fonts, and layout elements to produce publication-ready ggplot2 figures."),
            ("Faceting and Multi-Panel Plots in ggplot2", "Splitting a plot into small multiples using facet_wrap and facet_grid."),
            ("Reshaping Data with tidyr: pivot_longer and pivot_wider", "Converting between wide and long data formats for analysis and visualization."),
            ("String Manipulation with stringr", "Performing pattern matching, extraction, and text cleaning using stringr functions."),
            ("Working with Dates and Times Using lubridate", "Parsing, arithmetic, and formatting of date-time data using the lubridate package."),
            ("Functional Programming with purrr", "Applying map-family functions from purrr for consistent, type-stable iteration."),
            ("Factor Handling with forcats", "Reordering, recoding, and collapsing factor levels using the forcats package."),
            ("Reading and Writing Data with readr", "Efficiently importing and exporting delimited data files using the readr package."),
            ("Error Handling with tryCatch in R", "Catching and responding to errors, warnings, and conditions in R code."),
            ("R Environments and Scoping Rules", "Explaining how R resolves variable names using lexical scoping and environments."),
            ("Object-Oriented Programming in R: S3 Classes", "Implementing R's informal S3 object system for method dispatch."),
            ("Object-Oriented Programming in R: S4 Classes", "Defining formal classes with validated slots using R's S4 system."),
            ("Object-Oriented Programming in R: R6 Classes", "Implementing reference-semantics object-oriented programming using the R6 package."),
            ("Writing and Structuring an R Package", "Organizing functions, documentation, and tests into an installable R package."),
            ("Unit Testing in R with testthat", "Writing automated tests for R functions using the testthat framework."),
            ("R Markdown for Reproducible Reports", "Combining narrative text, code, and output into a single reproducible document."),
            ("Building Interactive Apps with Shiny", "Creating interactive web applications for data exploration using the Shiny framework."),
            ("Logistic Regression in R", "Modeling binary outcomes using logistic regression and interpreting odds ratios."),
            ("Generalized Linear Models in R", "Extending linear regression to non-normal response distributions using glm()."),
            ("Mixed Effects Models in R", "Modeling data with both fixed and random effects using lme4."),
            ("Model Selection: AIC and BIC in R", "Comparing candidate models using information criteria to balance fit and complexity."),
            ("Stepwise Regression Techniques in R", "Applying forward, backward, and stepwise selection to build regression models."),
            ("Principal Component Analysis (PCA) in R", "Reducing dimensionality of numeric data while preserving variance using PCA."),
            ("K-Means Clustering in R", "Partitioning observations into clusters using the k-means algorithm."),
            ("Hierarchical Clustering in R", "Building nested cluster structures using agglomerative hierarchical clustering."),
            ("Decision Trees in R", "Building interpretable classification and regression trees using rpart."),
            ("Random Forests in R", "Building ensembles of decision trees to improve predictive accuracy in R."),
            ("Cross-Validation Techniques in R", "Estimating model generalization error using k-fold and leave-one-out cross-validation."),
            ("Bootstrapping Methods in R", "Estimating sampling distributions and confidence intervals via resampling with replacement."),
            ("Introduction to Bayesian Statistics in R", "Applying prior and posterior reasoning to statistical inference problems in R."),
            ("Bayesian Regression with brms or rstanarm", "Fitting Bayesian regression models using high-level R interfaces to Stan."),
            ("Time Series Objects and Decomposition in R", "Representing time-indexed data and decomposing it into trend, seasonal, and residual components."),
            ("ARIMA Modeling in R", "Fitting autoregressive integrated moving average models to time series data."),
            ("Forecasting Methods in R", "Applying exponential smoothing and other techniques to forecast future values."),
            ("Survival Analysis and the Kaplan-Meier Estimator in R", "Estimating survival functions from time-to-event data with censoring."),
            ("Cox Proportional Hazards Models in R", "Modeling the effect of covariates on survival time using Cox regression."),
            ("Multivariate Analysis of Variance (MANOVA) in R", "Testing group differences across multiple continuous dependent variables simultaneously."),
            ("Factor Analysis in R", "Identifying latent variables that explain correlation patterns among observed variables."),
            ("Text Mining and Corpus Analysis in R", "Processing and analyzing textual corpora using R's text mining packages."),
            ("Web Scraping with rvest", "Extracting structured data from HTML web pages using the rvest package."),
            ("Connecting R to Databases with DBI", "Querying relational databases directly from R using the DBI interface."),
            ("Parallel Computing in R", "Speeding up computations by distributing work across multiple cores in R."),
            ("Improving R Performance with Rcpp", "Writing compiled C++ code callable from R to accelerate performance-critical sections."),
            ("Missing Data Handling and Imputation in R", "Diagnosing missingness patterns and applying imputation techniques in R."),
            ("Outlier Detection Techniques in R", "Identifying anomalous observations using statistical and visual methods in R."),
            ("Data Validation and Assertions in R", "Enforcing data quality rules programmatically before analysis in R."),
            ("Spatial Data Analysis in R", "Working with geographic and spatial data using R's spatial analysis packages."),
            ("Introduction to the caret Package for Machine Learning", "Using caret's unified interface to train and tune predictive models in R."),
            ("Introduction to the tidymodels Framework", "Building modular machine learning workflows using the tidymodels collection of packages."),
            ("Ensemble Methods in R", "Combining multiple models such as bagging and boosting to improve prediction in R."),
            ("Version Control for R Projects with Git", "Integrating Git version control into RStudio-based data analysis projects."),
            ("Reproducible Research Workflows in R", "Structuring R projects for reproducibility using consistent environments and documented pipelines."),
        ],
    },
    "Science": {
        "UG1": [
            ("Newtonian Mechanics: Laws of Motion", "Applying Newton's three laws to analyze the motion and interaction of physical bodies."),
            ("Conservation of Energy and Momentum", "Using conservation principles to solve problems in collisions and mechanical systems."),
            ("Thermodynamics: The Four Laws", "Explaining energy, entropy, and equilibrium through the zeroth through third laws of thermodynamics."),
            ("Electromagnetism: Maxwell's Equations Overview", "Surveying how Maxwell's equations unify electricity, magnetism, and light."),
            ("Wave Phenomena and Optics", "Explaining interference, diffraction, and refraction through the wave model of light."),
            ("Introduction to Quantum Mechanics", "Introducing wave-particle duality, uncertainty, and quantized energy states."),
            ("Special Relativity Fundamentals", "Explaining time dilation and length contraction from Einstein's postulates."),
            ("Nuclear Physics and Radioactivity", "Describing nuclear structure, decay modes, and half-life calculations."),
            ("Fluid Dynamics Basics", "Applying Bernoulli's principle and continuity to analyze fluid flow."),
            ("Semiconductor Physics and Electronics Fundamentals", "Explaining band theory and how it underlies diodes and transistors."),
            ("Atomic Structure and Electron Configuration", "Describing how electrons occupy orbitals and determine chemical behavior."),
            ("Periodic Trends and the Periodic Table", "Explaining trends in atomic radius, electronegativity, and ionization energy across the periodic table."),
            ("Chemical Bonding: Ionic, Covalent, and Metallic", "Comparing bonding types and predicting molecular properties from bond character."),
            ("Stoichiometry and the Mole Concept", "Using molar relationships to calculate reactant and product quantities in reactions."),
            ("Thermochemistry and Enthalpy", "Quantifying heat absorbed or released during chemical reactions and phase changes."),
            ("Chemical Kinetics and Reaction Rates", "Analyzing how concentration, temperature, and catalysts affect reaction speed."),
            ("Chemical Equilibrium Principles", "Applying Le Chatelier's principle and equilibrium constants to reversible reactions."),
            ("Acid-Base Chemistry and pH", "Explaining acid-base theories and calculating pH in aqueous solutions."),
            ("Oxidation-Reduction Reactions", "Balancing redox reactions and identifying oxidizing and reducing agents."),
            ("Organic Chemistry: Functional Groups", "Classifying organic molecules by their characteristic functional groups and reactivity."),
            ("Introduction to Biochemistry Pathways", "Surveying core metabolic pathways that convert nutrients into cellular energy."),
            ("Electrochemistry and Galvanic Cells", "Explaining how redox reactions generate electrical energy in galvanic cells."),
            ("Cell Structure and Function", "Comparing prokaryotic and eukaryotic cell organelles and their functions."),
            ("Cellular Respiration and Photosynthesis", "Tracing energy transformation through glycolysis, the Krebs cycle, and the light reactions."),
            ("Mendelian Genetics and Inheritance Patterns", "Applying Mendel's laws to predict inheritance patterns using Punnett squares."),
            ("Molecular Genetics: DNA Replication and Transcription", "Describing the enzymatic processes that copy and transcribe genetic information."),
            ("Protein Synthesis and Translation", "Explaining how ribosomes translate mRNA sequences into functional proteins."),
            ("Mechanisms of Evolution by Natural Selection", "Explaining how variation, selection, and heredity drive evolutionary change."),
            ("Population Genetics Fundamentals", "Applying the Hardy-Weinberg principle to model allele frequencies in populations."),
            ("Ecosystem Structure and Energy Flow", "Tracing energy and nutrient flow through trophic levels in an ecosystem."),
            ("Biodiversity and Conservation Biology", "Examining causes of biodiversity loss and strategies for species conservation."),
            ("Human Anatomy and Physiology Overview", "Surveying the major organ systems and how they maintain homeostasis."),
            ("Microbiology: Bacteria, Viruses, and Fungi", "Comparing the structure, reproduction, and ecological roles of microorganisms."),
            ("Immunology Fundamentals", "Describing innate and adaptive immune responses to pathogens."),
            ("Developmental Biology Basics", "Explaining how a single fertilized cell develops into a complex organism."),
            ("Plant Biology and Photosynthetic Pathways", "Comparing C3, C4, and CAM photosynthetic strategies in plants."),
            ("Animal Behavior and Ethology", "Examining innate and learned behaviors and their evolutionary explanations."),
            ("Plate Tectonics Theory", "Explaining how moving lithospheric plates shape earthquakes, volcanoes, and mountain ranges."),
            ("Rock Cycle and Mineralogy", "Classifying igneous, sedimentary, and metamorphic rocks through the rock cycle."),
            ("Weather Systems and Meteorology", "Explaining how pressure systems and fronts produce weather patterns."),
            ("Ocean Circulation and Oceanography", "Describing surface and deep ocean currents and their role in global climate."),
            ("Earth's Atmosphere and Climate Systems", "Explaining atmospheric composition and the greenhouse effect's role in climate."),
            ("Soil Science Fundamentals", "Describing soil formation, composition, and its role in agriculture and ecosystems."),
            ("Hydrology and the Water Cycle", "Tracing water movement through evaporation, precipitation, and groundwater systems."),
            ("Environmental Pollution and Remediation", "Examining sources of pollution and technologies used to mitigate environmental damage."),
            ("Stellar Life Cycles", "Tracing how stars form, evolve, and end their lives based on initial mass."),
            ("Formation of the Solar System", "Explaining the nebular hypothesis and processes that formed planets and moons."),
            ("Introduction to Cosmology and the Big Bang", "Surveying evidence for cosmic expansion and the early universe's evolution."),
            ("Galaxies and Large-Scale Structure", "Classifying galaxy types and describing the universe's large-scale structure."),
            ("Experimental Design and Controlled Variables", "Designing experiments that isolate variables to support valid causal inference."),
            ("Measurement Uncertainty and Error Analysis", "Quantifying and propagating measurement uncertainty in scientific data."),
            ("Scientific Modeling and Simulation", "Using mathematical and computational models to represent natural phenomena."),
            ("The History of Scientific Instrumentation", "Tracing how telescopes, microscopes, and other instruments expanded scientific observation."),
            ("Interdisciplinary Science: Systems Thinking", "Applying systems-level reasoning to problems that span multiple scientific disciplines."),
            ("Science Communication for General Audiences", "Translating technical findings into accessible language for non-expert audiences."),
            ("Citizen Science and Crowdsourced Research", "Examining how public participation contributes to large-scale scientific data collection."),
            ("Data Visualization in Scientific Research", "Designing figures and charts that accurately and clearly represent scientific data."),
            ("Bioethics in Scientific Research", "Examining ethical issues in research involving human subjects and living organisms."),
            ("Science Policy and Regulatory Frameworks", "Explaining how governments regulate and fund scientific research and technology."),
            ("Emerging Technologies: Nanotechnology Fundamentals", "Introducing how manipulating matter at the nanoscale enables novel materials and devices."),
        ],
    },
    "Social Studies": {
        "UG1": [
            ("Introduction to Political Science: Core Concepts", "Surveying foundational concepts of power, authority, and legitimacy in political systems."),
            ("Comparative Political Systems", "Comparing presidential, parliamentary, and hybrid systems of government across countries."),
            ("Democratic Theory and Its Critics", "Examining normative justifications for democracy alongside critiques of its practice."),
            ("Political Ideologies: Liberalism, Conservatism, Socialism", "Comparing major political ideologies and their core assumptions about state and society."),
            ("The Nation-State and Sovereignty", "Examining the historical development and contested meaning of state sovereignty."),
            ("Public Policy Analysis Fundamentals", "Applying frameworks to analyze how policies are formulated, implemented, and evaluated."),
            ("Electoral Systems and Voting Behavior", "Comparing electoral rules and explaining patterns in voter decision-making."),
            ("International Relations: Realism and Liberalism", "Comparing major theoretical traditions used to explain state behavior in world politics."),
            ("Global Governance and International Organizations", "Examining how bodies such as the UN and WTO coordinate cross-border cooperation."),
            ("Political Economy Fundamentals", "Analyzing the interaction between political institutions and economic systems."),
            ("Microeconomics for Social Scientists", "Applying supply, demand, and market analysis to social science questions."),
            ("Macroeconomics for Social Scientists", "Examining national income, inflation, and unemployment through a social science lens."),
            ("Economic Development and Global Inequality", "Comparing theories explaining disparities in wealth and development across nations."),
            ("Labor Markets and Employment Policy", "Analyzing how labor market institutions and policy shape employment outcomes."),
            ("Human Geography: Population and Migration", "Examining spatial patterns of population distribution and human migration."),
            ("Urban Geography and Urbanization Patterns", "Analyzing the growth, structure, and challenges of cities worldwide."),
            ("Cultural Geography and Place Identity", "Examining how culture and identity are shaped by and expressed through place."),
            ("Environmental Social Science", "Studying human-environment interactions through a social science framework."),
            ("Social Psychology: Group Dynamics", "Examining how group membership shapes individual attitudes and behavior."),
            ("Social Psychology: Conformity and Obedience", "Analyzing classic studies on conformity, obedience, and social influence."),
            ("Social Stratification and Class Analysis", "Examining how societies organize unequal access to resources and status."),
            ("Gender and Society", "Analyzing how gender norms and roles are socially constructed and contested."),
            ("Race, Ethnicity, and Intergroup Relations", "Examining the social construction of race and dynamics of intergroup relations."),
            ("Sociology of Work and Organizations", "Analyzing how work is organized, experienced, and changing in modern economies."),
            ("Sociology of Health and Illness", "Examining how social factors shape health outcomes and healthcare access."),
            ("Criminology and the Sociology of Crime", "Analyzing social explanations for criminal behavior and patterns of offending."),
            ("Comparative Criminal Justice Systems", "Comparing policing, courts, and corrections across different national systems."),
            ("Social Policy and the Welfare State", "Comparing how different welfare state models address poverty and social risk."),
            ("Civil Society and Nonprofit Organizations", "Examining the role of voluntary associations in democratic public life."),
            ("Social Capital and Community Networks", "Analyzing how social ties and trust networks affect community outcomes."),
            ("Public Opinion and Political Behavior", "Examining how public opinion is formed, measured, and translated into political action."),
            ("Media, Communication, and Society", "Analyzing how mass and digital media shape public discourse and social norms."),
            ("Globalization and Its Social Impacts", "Examining how economic and cultural globalization reshapes local societies."),
            ("Human Rights: Theory and Practice", "Examining philosophical foundations and real-world enforcement of human rights."),
            ("Comparative Legal Systems", "Comparing common law, civil law, and other legal traditions across societies."),
            ("Public Administration Fundamentals", "Examining how bureaucracies implement policy and deliver public services."),
            ("Local Government and Municipal Policy", "Analyzing governance structures and policymaking at the municipal level."),
            ("Social Movements Case Studies: Civil Rights Movement", "Analyzing the strategies and outcomes of the mid-twentieth-century civil rights movement."),
            ("Social Movements Case Studies: Labor Movements", "Examining the rise of organized labor and its impact on social and economic policy."),
            ("Indigenous Studies and Sovereignty", "Examining Indigenous political sovereignty, land rights, and cultural preservation."),
            ("Postcolonial Studies in the Social Sciences", "Analyzing the lasting social and political effects of colonialism on former colonies."),
            ("Migration and Refugee Studies", "Examining the causes, policies, and social integration challenges of migration and displacement."),
            ("Demography: Population Structure and Change", "Analyzing fertility, mortality, and population age structure trends."),
            ("Quantitative Research Methods in Social Science", "Applying statistical techniques to test hypotheses using social science data."),
            ("Survey Research Design and Sampling", "Designing valid surveys and selecting representative samples for social research."),
            ("Statistical Analysis for Social Science Data", "Applying descriptive and inferential statistics to analyze social science datasets."),
            ("Case Study Methodology in Social Research", "Applying in-depth case study design to generate rich social science insights."),
            ("Comparative-Historical Methods in Social Science", "Using cross-national historical comparison to explain large-scale social outcomes."),
            ("Ethics in Social Science Research", "Examining informed consent, confidentiality, and harm-avoidance in social research."),
            ("Applied Social Research and Program Evaluation", "Applying research methods to assess the effectiveness of social programs."),
            ("Social Network Analysis", "Mapping and analyzing relationships between individuals or organizations as networks."),
            ("Political Socialization and Civic Education", "Examining how individuals develop political beliefs and civic participation habits."),
            ("The Sociology of Childhood and Youth", "Examining how childhood and youth are socially constructed across cultures and eras."),
            ("Aging and Society", "Examining the social, economic, and policy implications of population aging."),
            ("Disability Studies", "Examining disability as a social and political category rather than only a medical one."),
            ("Consumer Culture and Society", "Analyzing how consumption practices shape identity and social structure."),
            ("Social Entrepreneurship", "Examining how market-based ventures are designed to address social problems."),
            ("Sociology of Sport", "Analyzing how sport reflects and reproduces broader social structures and inequalities."),
            ("Sociology of Food Systems", "Examining social, economic, and cultural dimensions of food production and consumption."),
            ("Environmental Justice and Society", "Examining how environmental harms and benefits are unequally distributed across social groups."),
        ],
    },
    "Survival Skills": {
        "UG1": [
            ("Land Navigation with Topographic Maps and Compass", "Using contour interpretation, bearings, and pace counting to navigate without electronic aids."),
            ("GPS Technology and Digital Navigation Tools", "Explaining how satellite positioning systems work and their limitations in the field."),
            ("Backcountry Trip Planning and Logistics", "Planning routes, resupply, and contingencies for extended wilderness expeditions."),
            ("Wilderness First Aid Certification Standards", "Surveying the scope and standards covered by recognized wilderness first aid training."),
            ("Trauma Assessment and Field Triage", "Applying systematic assessment protocols to prioritize care for multiple injured patients."),
            ("Water Purification Methods and Technologies", "Comparing boiling, filtration, and chemical treatment methods for making water safe to drink."),
            ("Food Preservation Techniques for Long-Term Storage", "Comparing drying, canning, and curing methods for extending food shelf life."),
            ("Edible and Poisonous Plant Identification", "Applying identification criteria to distinguish edible plants from toxic look-alikes."),
            ("Foraging Ethics and Sustainable Harvesting", "Balancing subsistence foraging with ecological sustainability and legal regulation."),
            ("Fire-Starting Methods Without Matches", "Comparing friction, spark, and lens-based methods for starting fire without matches."),
            ("Knot Tying and Rope Work Applications", "Applying essential knots and hitches for shelter building, rescue, and load securing."),
            ("Shelter-Building Techniques for Different Climates", "Adapting shelter design principles to insulation, wind, and moisture needs by climate."),
            ("Cold-Weather Survival Strategies", "Managing heat loss, hydration, and movement to survive extended cold exposure."),
            ("Desert Survival Strategies", "Managing water conservation and heat exposure to survive in arid environments."),
            ("Tropical and Jungle Survival Strategies", "Addressing humidity, disease vectors, and dense terrain in tropical survival scenarios."),
            ("Maritime and Open-Water Survival Skills", "Applying flotation, signaling, and hypothermia prevention techniques at sea."),
            ("Avalanche Awareness and Backcountry Safety", "Assessing snowpack stability and terrain to reduce avalanche risk in the backcountry."),
            ("Wildlife Encounter Safety Protocols", "Applying species-specific protocols to reduce risk during dangerous wildlife encounters."),
            ("Venomous Animal and Insect Bite Response", "Applying first-response protocols for bites and stings from venomous animals and insects."),
            ("Signal and Rescue Beacon Technology", "Comparing personal locator beacons and signaling devices used to summon rescue."),
            ("Search and Rescue Team Coordination", "Explaining how search and rescue teams organize search patterns and communication."),
            ("Incident Command System (ICS) Fundamentals", "Describing the standardized ICS structure used to coordinate emergency response."),
            ("Emergency Evacuation Planning", "Designing evacuation routes and procedures for facilities and communities at risk."),
            ("Mass Casualty Incident Response", "Applying triage and resource allocation principles when casualties exceed capacity."),
            ("Disaster Preparedness for Households", "Building household emergency plans, kits, and communication strategies."),
            ("Earthquake Preparedness and Response", "Applying drop-cover-hold and structural safety principles for earthquake response."),
            ("Flood Risk Assessment and Response", "Evaluating flood hazard zones and appropriate evacuation and response measures."),
            ("Wildfire Behavior and Evacuation Planning", "Explaining fire spread dynamics and designing timely evacuation strategies."),
            ("Hurricane and Severe Storm Preparedness", "Planning sheltering and evacuation strategies for hurricanes and severe storms."),
            ("Pandemic Preparedness Planning", "Designing household and community plans for infectious disease outbreaks."),
            ("Supply Chain Disruption and Stockpiling Strategy", "Planning resource stockpiles to withstand extended supply chain interruptions."),
            ("Bushcraft Tool Use and Maintenance", "Applying safe use and maintenance techniques for knives, axes, and saws in the field."),
            ("Primitive Technology and Tool-Making", "Recreating pre-industrial tool-making techniques from natural materials."),
            ("Tracking and Wilderness Observation Skills", "Interpreting animal tracks and environmental sign to understand surroundings."),
            ("Orienteering Competition Techniques", "Applying speed navigation techniques used in competitive orienteering events."),
            ("Backpacking Equipment Selection and Weight Management", "Balancing durability, function, and pack weight when selecting backcountry gear."),
            ("Layered Clothing Systems for Temperature Regulation", "Designing base, insulating, and shell layers to regulate body temperature outdoors."),
            ("Survival Psychology: Stress Inoculation Training", "Applying controlled stress exposure techniques to build resilience for emergencies."),
            ("Group Dynamics in Survival Situations", "Examining how group cohesion and roles affect outcomes in survival scenarios."),
            ("Leadership Under Crisis Conditions", "Applying leadership principles to maintain group function during high-stress emergencies."),
            ("Decision-Making Under Uncertainty in Emergencies", "Applying structured decision frameworks when information is incomplete and stakes are high."),
            ("Wilderness Ethics and Leave No Trace Principles", "Applying minimal-impact principles to reduce environmental damage from outdoor activity."),
            ("Environmental Hazard Recognition", "Identifying terrain, weather, and biological hazards before they become emergencies."),
            ("Lightning Safety and Storm Avoidance", "Applying timing and positioning strategies to reduce lightning strike risk outdoors."),
            ("Rock Climbing and Rappelling Safety Fundamentals", "Applying anchor, belay, and rappel safety principles for vertical terrain."),
            ("Swiftwater Rescue Techniques", "Applying specialized techniques for rescuing people from fast-moving water."),
            ("Cave and Confined Space Survival", "Applying navigation and safety principles specific to caving and confined spaces."),
            ("High-Altitude Physiology and Acclimatization", "Explaining how the body adapts to reduced oxygen at high altitude."),
            ("Emergency Communication Equipment Operation", "Operating radios and satellite communicators for use during field emergencies."),
            ("Amateur Radio for Emergency Preparedness", "Explaining how amateur radio operators support communication during disasters."),
            ("Solar and Alternative Power for Off-Grid Survival", "Comparing off-grid power generation options for extended survival scenarios."),
            ("Water Source Identification in Arid Environments", "Applying terrain and vegetation cues to locate water sources in dry environments."),
            ("Animal Husbandry Basics for Self-Sufficiency", "Introducing livestock care practices relevant to self-sufficient living."),
            ("Sustainable Homesteading Practices", "Integrating gardening, water, and energy systems for self-sufficient living."),
            ("Urban Search and Rescue (USAR) Techniques", "Explaining specialized techniques for locating survivors in collapsed structures."),
            ("Chemical, Biological, Radiological, and Nuclear (CBRN) Preparedness", "Introducing protective measures for CBRN incident response."),
            ("Crisis Leadership and Organizational Continuity Planning", "Designing continuity plans that keep organizations functioning through crises."),
            ("Psychological First Aid After Disasters", "Applying supportive techniques to help survivors cope in a disaster's immediate aftermath."),
            ("Cultural Considerations in International Disaster Relief", "Adapting relief efforts to respect local customs and community structures."),
            ("Survival Skills Instruction and Curriculum Design", "Designing effective curricula for teaching survival skills to diverse learners."),
        ],
    },
    "UI/UX Design": {
        "UG1": [
            ("User Research Methods Overview", "Surveying qualitative and quantitative methods used to understand user needs and behavior."),
            ("Conducting User Interviews", "Designing and facilitating interviews that surface genuine user needs and pain points."),
            ("Contextual Inquiry and Field Studies", "Observing users in their natural environment to uncover unspoken behaviors and constraints."),
            ("Creating User Personas", "Synthesizing research into representative personas that guide design decisions."),
            ("User Journey Mapping", "Visualizing a user's end-to-end experience to identify pain points and opportunities."),
            ("Empathy Mapping Techniques", "Organizing what users say, think, feel, and do to build deeper user understanding."),
            ("Card Sorting for Information Architecture", "Using open and closed card sorting to inform how content should be grouped and labeled."),
            ("Information Architecture Fundamentals", "Structuring content and navigation so users can find information intuitively."),
            ("Site Maps and Content Hierarchies", "Planning the structural relationships between pages and content in a digital product."),
            ("Wireframing Fundamentals", "Sketching low-fidelity layouts that define structure and functionality before visual design."),
            ("Low-Fidelity vs High-Fidelity Prototyping", "Comparing the purpose and tradeoffs of rough sketches versus polished interactive prototypes."),
            ("Interactive Prototyping Tools and Techniques", "Building clickable prototypes to simulate and test product interactions before development."),
            ("Usability Testing Methods", "Planning and running moderated and unmoderated tests to evaluate interface usability."),
            ("Heuristic Evaluation (Nielsen's Ten Heuristics)", "Applying established usability heuristics to systematically identify interface problems."),
            ("A/B Testing for Interface Decisions", "Using controlled experiments to compare interface variants against measurable outcomes."),
            ("Design Thinking Process Overview", "Applying the empathize, define, ideate, prototype, and test framework to design problems."),
            ("Service Design and Blueprinting", "Mapping front-stage and back-stage processes that together deliver a complete service experience."),
            ("Interaction Design Principles", "Applying core principles that govern how users interact with digital interfaces."),
            ("Microinteractions and Feedback Design", "Designing small, purposeful interface responses that provide feedback for user actions."),
            ("Navigation Pattern Design", "Comparing navigation patterns such as tab bars, hamburger menus, and breadcrumbs."),
            ("Form Design Best Practices", "Designing input forms that minimize user error and cognitive load."),
            ("Onboarding Flow Design", "Designing first-use experiences that help new users reach value quickly."),
            ("Empty State and Error State Design", "Designing informative, helpful states for when content is absent or something goes wrong."),
            ("Responsive Web Design Principles", "Designing layouts that adapt gracefully across a range of screen sizes and devices."),
            ("Mobile-First Design Patterns", "Prioritizing constrained mobile contexts when designing interfaces from the ground up."),
            ("Designing for Touch vs Pointer Interfaces", "Adapting target sizes and interaction models for touch versus mouse-driven interfaces."),
            ("Accessibility Standards: WCAG Fundamentals", "Applying Web Content Accessibility Guidelines to make interfaces usable by people with disabilities."),
            ("Designing for Screen Readers and Assistive Technology", "Structuring interfaces so they are correctly interpreted by assistive technologies."),
            ("Inclusive Design Principles", "Designing products that accommodate the widest possible range of human diversity."),
            ("UX Writing and Microcopy", "Crafting concise, clear interface text that guides and reassures users."),
            ("Content Strategy for Digital Products", "Planning how content is created, organized, and maintained across a product."),
            ("Design Systems: Structure and Governance", "Establishing shared rules, components, and processes that keep a design system consistent."),
            ("Atomic Design Methodology", "Building interfaces from atoms, molecules, and organisms to promote consistency and reuse."),
            ("Component Libraries and Reusability", "Building reusable UI component libraries that speed design and development."),
            ("Design Handoff to Developers", "Preparing specifications and assets that allow developers to implement designs accurately."),
            ("Design Critique and Iteration Workflows", "Structuring feedback sessions that lead to actionable design improvements."),
            ("Competitive Analysis in UX Research", "Evaluating competitor products to identify best practices and differentiation opportunities."),
            ("Affinity Mapping and Synthesizing Research Data", "Clustering qualitative research findings into themes that inform design decisions."),
            ("Wireflows for Complex User Tasks", "Combining wireframes and flow diagrams to represent multi-step user tasks."),
            ("Usability Metrics: SUS and Task Success Rate", "Measuring interface usability using the System Usability Scale and task completion data."),
            ("Conversion Rate Optimization Principles", "Applying design and testing techniques to improve the rate at which users complete key actions."),
            ("Voice User Interface (VUI) Design", "Designing conversational flows for voice-controlled and audio-only interfaces."),
            ("Designing for Augmented and Virtual Reality", "Adapting UX principles for spatial, immersive augmented and virtual reality interfaces."),
            ("Gamification Principles in UX Design", "Applying game-design elements to increase engagement in non-game digital products."),
            ("Dark Patterns and Ethical Design", "Identifying manipulative interface patterns and the ethical case against using them."),
            ("Design for Enterprise and B2B Software", "Addressing the complexity and workflow needs unique to enterprise software users."),
            ("Designing Dashboards and Data-Heavy Interfaces", "Organizing dense information into scannable, actionable dashboard layouts."),
            ("Cross-Platform Design Consistency", "Maintaining a coherent experience for a product across web, mobile, and desktop platforms."),
            ("Design Ops and Team Workflow Management", "Establishing processes and tooling that scale design team collaboration and output."),
            ("User Testing with Remote Participants", "Adapting usability testing methods for participants joining from remote locations."),
            ("Eye-Tracking and Behavioral Research Methods", "Using eye-tracking and behavioral data to understand how users visually process interfaces."),
            ("Prototyping with Design-to-Code Tools", "Using tools that translate design files directly into functional front-end code."),
            ("Design for E-Commerce Interfaces", "Applying UX best practices to product listings, checkout, and cart experiences."),
            ("Search and Filter Interface Design", "Designing search and filtering controls that help users narrow large result sets."),
            ("Notification and Alert Design Patterns", "Designing timely, non-intrusive notification systems that respect user attention."),
            ("Personalization and Adaptive Interfaces", "Designing interfaces that adapt content and layout based on individual user behavior."),
            ("Designing for Low-Bandwidth and Offline Use", "Designing resilient experiences for users with limited or intermittent connectivity."),
            ("Localization and Internationalization in UX", "Adapting interfaces for different languages, scripts, and cultural conventions."),
            ("Portfolio Development for UX Designers", "Curating and presenting design case studies that demonstrate process and impact."),
            ("UX Metrics and Analytics for Product Decisions", "Using behavioral analytics to inform and validate ongoing design decisions."),
        ],
    },
    "Web Development": {
        "UG1": [
            ("HTML5 Semantic Elements", "Structuring web pages using meaningful HTML5 elements for accessibility and SEO."),
            ("CSS Box Model and Layout Fundamentals", "Explaining how margin, border, padding, and content determine element sizing."),
            ("Flexbox Layout Techniques", "Building one-dimensional responsive layouts using the CSS flexbox model."),
            ("CSS Grid Layout Techniques", "Building two-dimensional responsive layouts using the CSS grid model."),
            ("CSS Specificity and the Cascade", "Explaining how selector specificity and source order determine which styles apply."),
            ("Responsive Design with Media Queries", "Adapting layouts to different viewport sizes using CSS media queries."),
            ("CSS Preprocessors: Sass and LESS", "Using variables, nesting, and mixins to write more maintainable CSS."),
            ("CSS-in-JS Approaches", "Comparing styling approaches that co-locate CSS with JavaScript components."),
            ("CSS Animations and Transitions", "Creating smooth visual state changes using CSS transitions and keyframe animations."),
            ("Modern JavaScript (ES6+) Features", "Applying arrow functions, destructuring, modules, and other modern JavaScript syntax."),
            ("DOM Manipulation with Vanilla JavaScript", "Selecting, modifying, and creating page elements using native browser APIs."),
            ("Asynchronous JavaScript: Promises and async/await", "Managing asynchronous operations cleanly using promises and async/await syntax."),
            ("TypeScript Fundamentals for Web Development", "Adding static typing to JavaScript projects to catch errors before runtime."),
            ("Web Components and Custom Elements", "Building reusable, framework-agnostic UI elements using the Web Components standard."),
            ("CSS Frameworks: Bootstrap and Tailwind CSS", "Comparing utility-first and component-based approaches to CSS frameworks."),
            ("Build Tools: Webpack Fundamentals", "Configuring Webpack to bundle, transform, and optimize front-end assets."),
            ("Build Tools: Vite and Modern Bundling", "Comparing Vite's development experience and build approach to older bundlers."),
            ("Module Bundling and Code Splitting", "Splitting application code into smaller chunks to improve initial load performance."),
            ("Babel and JavaScript Transpilation", "Transpiling modern JavaScript syntax into broadly compatible code with Babel."),
            ("Web Performance Optimization Fundamentals", "Identifying and addressing common bottlenecks that slow down web page performance."),
            ("Critical Rendering Path and Page Load Performance", "Explaining the browser steps between receiving HTML and rendering pixels."),
            ("Image Optimization for the Web", "Choosing formats, compression, and responsive techniques to reduce image payload."),
            ("Lazy Loading Techniques", "Deferring the loading of off-screen resources to improve initial page performance."),
            ("Content Delivery Networks (CDNs)", "Explaining how CDNs distribute content geographically to reduce latency."),
            ("Core Web Vitals Metrics", "Measuring loading, interactivity, and visual stability using Core Web Vitals."),
            ("Browser Caching Strategies", "Designing caching policies that balance freshness and performance for web resources."),
            ("HTTP Caching Headers", "Using Cache-Control, ETag, and related headers to control resource caching behavior."),
            ("Progressive Web Apps (PWAs) Fundamentals", "Building web apps that offer app-like installability and offline capability."),
            ("Service Workers and Offline Functionality", "Using service workers to intercept requests and enable offline web experiences."),
            ("Web App Manifests", "Configuring manifest files that define how a PWA installs and appears on devices."),
            ("WebSockets for Real-Time Communication", "Establishing persistent, bidirectional connections for real-time web applications."),
            ("Server-Sent Events", "Streaming one-way real-time updates from server to client over HTTP."),
            ("Cross-Origin Resource Sharing (CORS)", "Explaining how CORS policies control cross-origin requests between web origins."),
            ("Cross-Site Scripting (XSS) Prevention", "Identifying XSS vulnerabilities and applying input sanitization to prevent them."),
            ("Cross-Site Request Forgery (CSRF) Protection", "Applying tokens and same-site cookies to prevent forged cross-site requests."),
            ("Content Security Policy (CSP)", "Configuring CSP headers to restrict the sources of executable content on a page."),
            ("HTTPS and TLS Fundamentals for Web Apps", "Explaining how TLS encryption secures data transmitted between browser and server."),
            ("SQL Injection Prevention", "Using parameterized queries and input validation to prevent SQL injection attacks."),
            ("Secure HTTP Headers", "Configuring security-related HTTP headers to harden a web application."),
            ("Web Accessibility: ARIA Roles and Attributes", "Using ARIA attributes to make dynamic web content accessible to assistive technology."),
            ("Automated Accessibility Testing Tools", "Using automated tools to catch common accessibility violations in web projects."),
            ("Unit Testing JavaScript Applications", "Writing isolated unit tests for JavaScript functions and components."),
            ("End-to-End Testing with Cypress or Playwright", "Simulating real user flows to test complete web applications automatically."),
            ("Test-Driven Development for Web Apps", "Writing tests before implementation to drive the design of web application code."),
            ("Continuous Integration and Deployment (CI/CD) for Web Projects", "Automating build, test, and deployment pipelines for web applications."),
            ("Containerizing Web Applications with Docker", "Packaging web applications and their dependencies into portable Docker containers."),
            ("Serverless Functions for Web Backends", "Building backend logic as stateless functions triggered by HTTP or events."),
            ("Web Hosting and Deployment Platforms", "Comparing static hosting, PaaS, and cloud deployment options for web projects."),
            ("DNS and Domain Name Fundamentals", "Explaining how DNS resolves domain names to IP addresses for web requests."),
            ("HTTP Protocol Deep Dive", "Examining HTTP methods, status codes, and headers that govern web communication."),
            ("Browser Rendering Engines Explained", "Explaining how browsers parse HTML and CSS to construct and paint a page."),
            ("Form Validation Techniques", "Combining client-side and server-side validation to ensure correct form data."),
            ("Web Internationalization (i18n)", "Structuring web applications to support multiple languages and locales."),
            ("API Rate Limiting Strategies", "Designing throttling mechanisms that protect APIs from overuse and abuse."),
            ("Webhooks and Event-Driven Integrations", "Using webhooks to notify external systems of events in near real time."),
            ("Message Queues in Web Architectures", "Using message queues to decouple and scale components of a web application."),
            ("Database Indexing for Web Applications", "Applying indexing strategies to speed up common database queries in web apps."),
            ("Full-Text Search Implementation", "Implementing search functionality that ranks results by textual relevance."),
            ("Headless CMS Architecture", "Decoupling content management from presentation using a headless CMS."),
            ("JAMstack Architecture Principles", "Building fast, secure sites using pre-rendered markup, APIs, and JavaScript."),
        ],
    },
    "World History": {
        "UG1": [
            ("Mesopotamian Civilizations and the Rise of Writing", "Examining Sumer, Akkad, and Babylon alongside the invention of cuneiform writing."),
            ("Ancient Egypt: State Formation and Religion", "Examining how kingship, religion, and the Nile shaped ancient Egyptian civilization."),
            ("The Indus Valley Civilization", "Examining the urban planning and trade networks of the Harappan civilization."),
            ("Classical Greece: Democracy and Philosophy", "Examining the political institutions and philosophical traditions of classical Athens."),
            ("The Hellenistic World After Alexander", "Examining the fusion of Greek and local cultures across Alexander's former empire."),
            ("The Roman Republic: Institutions and Expansion", "Examining the political institutions that governed Rome before its transition to empire."),
            ("The Fall of the Western Roman Empire", "Analyzing the political, economic, and military factors behind Rome's western collapse."),
            ("The Byzantine Empire and Justinian's Legacy", "Examining how the Eastern Roman Empire preserved and transformed classical traditions."),
            ("Ancient China: The Qin and Han Dynasties", "Examining the unification of China and the consolidation of imperial bureaucracy."),
            ("The Maurya and Gupta Empires of India", "Examining two classical Indian empires and their administrative and cultural achievements."),
            ("Classical Maya Civilization", "Examining Maya political organization, astronomy, and writing in Mesoamerica."),
            ("The Aksumite Kingdom and Trans-Saharan Trade", "Examining the East African kingdom's role in regional and Indian Ocean trade."),
            ("The Silk Road and Eurasian Exchange", "Tracing how goods, religions, and ideas moved across Eurasian trade routes."),
            ("The Crusades: Causes and Consequences", "Analyzing the religious, political, and economic motivations behind the medieval Crusades."),
            ("Medieval Japan: The Rise of the Samurai", "Examining the emergence of warrior governance and feudal structures in Japan."),
            ("The Song Dynasty and Chinese Technological Innovation", "Examining economic growth and technological advances during China's Song era."),
            ("The Delhi Sultanate", "Examining the establishment and administration of Muslim rule in medieval North India."),
            ("West African Kingdoms: Ghana and Songhai", "Examining the political and economic organization of major medieval West African states."),
            ("The Great Zimbabwe Civilization", "Examining the trade-based stone-building civilization of southeastern Africa."),
            ("The Aztec Empire", "Examining the political structure, religion, and economy of the Mexica Empire."),
            ("The Inca Empire and Andean Statecraft", "Examining how the Inca administered a vast Andean empire without a writing system."),
            ("The Black Death and Its Global Impact", "Analyzing the demographic, economic, and social consequences of the medieval plague."),
            ("The Hanseatic League and Medieval Trade Networks", "Examining the commercial confederation that dominated northern European trade."),
            ("The Ottoman Empire's Rise and Administration", "Examining how the Ottomans built and governed a multi-ethnic, multi-religious empire."),
            ("The Ming Dynasty and Zheng He's Voyages", "Examining Ming China's maritime expeditions and their eventual discontinuation."),
            ("The Columbian Exchange", "Analyzing the transfer of plants, animals, and diseases between the Old and New Worlds."),
            ("The Atlantic Slave Trade: Origins and Scale", "Examining the origins, mechanics, and demographic scale of the transatlantic slave trade."),
            ("The Protestant Reformation", "Analyzing how Luther's challenge to Rome reshaped European religion and politics."),
            ("The Scientific Revolution", "Examining how new methods of inquiry transformed European understanding of nature."),
            ("The Thirty Years' War", "Analyzing the causes and continental consequences of this early modern European conflict."),
            ("The Mughal Empire", "Examining the political and cultural achievements of Mughal rule in South Asia."),
            ("The Tokugawa Shogunate and Japanese Isolation", "Examining Japan's centralized feudal order and policy of restricted foreign contact."),
            ("Absolutism in Early Modern Europe", "Comparing how monarchs centralized state power across early modern European states."),
            ("The Haitian Revolution", "Examining the only successful large-scale slave revolt to establish an independent state."),
            ("Latin American Independence Movements", "Comparing the causes and leaders of early nineteenth-century Latin American independence."),
            ("The Congress of Vienna and the Concert of Europe", "Examining how post-Napoleonic diplomacy sought to restore European balance of power."),
            ("The Opium Wars and China's Century of Humiliation", "Examining how conflicts with Western powers reshaped Qing China's sovereignty."),
            ("The Meiji Restoration", "Examining Japan's rapid modernization and industrialization after 1868."),
            ("The Scramble for Africa", "Analyzing the causes and process of European colonial partition of Africa."),
            ("Nationalism and the Unification of Italy", "Examining the political movements that unified the Italian peninsula in the nineteenth century."),
            ("The Taiping Rebellion", "Examining the causes and devastating consequences of this mid-nineteenth-century Chinese civil war."),
            ("Decolonization in Africa and Asia", "Comparing the processes and legacies of independence movements across former colonies."),
            ("The Partition of India", "Examining the causes and human consequences of the 1947 partition of British India."),
            ("The Chinese Communist Revolution", "Examining the civil war and consolidation that brought the Communist Party to power in China."),
            ("The Korean War", "Examining the causes, course, and Cold War significance of the Korean War."),
            ("The Vietnam War in Global Context", "Examining the Vietnam War as both a Cold War proxy conflict and anti-colonial struggle."),
            ("The Cuban Missile Crisis", "Analyzing the diplomatic crisis that brought the Cold War closest to nuclear conflict."),
            ("The Non-Aligned Movement", "Examining how newly independent states sought to avoid Cold War bloc alignment."),
            ("Apartheid in South Africa", "Examining the system of racial segregation and the movement that dismantled it."),
            ("The Iranian Revolution of 1979", "Analyzing the causes and global consequences of Iran's revolutionary transformation."),
            ("The Fall of the Berlin Wall and End of the Cold War", "Examining the events of 1989-1991 that ended the Cold War division of Europe."),
            ("The Rwandan Genocide", "Examining the historical origins and international response to the 1994 genocide."),
            ("Globalization and Its Historical Roots", "Tracing the long historical processes that produced today's interconnected global economy."),
            ("The Rise of the European Union", "Examining the postwar process of European economic and political integration."),
            ("The Arab Spring", "Examining the causes and varied outcomes of the 2011 wave of Middle Eastern uprisings."),
            ("Post-Colonial Nation-Building Challenges", "Examining the political and economic challenges faced by newly independent states."),
            ("The Global History of Human Rights Movements", "Tracing the development of international human rights norms and advocacy movements."),
            ("Environmental History and Climate Change Over Time", "Examining how human societies have shaped and been shaped by environmental change."),
            ("The History of Global Pandemics", "Comparing how past pandemics shaped societies, economies, and public health institutions."),
            ("Historiographical Debates in World History", "Examining how historians' interpretive frameworks shape competing accounts of the past."),
        ],
    },
    "World Literature": {
        "UG1": [
        ],
    },
}
