"""Top-up UG2 topic batch for subjects that fell short of the 80-lesson minimum.

Each entry is a (title, summary) tuple consumed by merge_all_subjects_expansion.py,
which builds full lesson objects from these pairs. Titles are chosen to be
specific sub-areas that are unlikely to collide with topics already generated
for this subject at other levels (C1, C2, UG1, UG3, UG4, M1, M2).
"""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "AI Tools": {
        "UG2": [
            ("AI Tools for Meeting Transcription and Action-Item Extraction", "Survey AI tools that transcribe meetings and automatically extract action items and decisions for follow-up."),
            ("AI Tools for Accessibility and Assistive Technology", "Explore AI-powered tools that improve accessibility, such as screen readers, captioning, and alternative text generation."),
            ("AI Tools for 3D Asset and Game Level Generation", "Examine AI tools that assist game developers in generating 3D assets, textures, and level layouts."),
            ("AI Tools for Personal Budgeting and Expense Tracking", "Evaluate AI-driven personal finance tools that categorize spending and generate budgeting insights."),
            ("AI Tools for Sustainability and ESG Reporting", "Study how AI tools assist organizations in compiling and analyzing environmental, social, and governance reports."),
            ("AI Tools for Clinical Note Summarization", "Assess AI tools that summarize clinical encounter notes to reduce documentation burden for healthcare providers."),
            ("AI Tools for Architectural Visualization", "Explore AI tools that generate architectural renderings and visualizations from sketches or text descriptions."),
            ("AI Tools for Crisis Communication Drafting", "Examine how AI tools can help draft timely, accurate crisis communication messages for organizations."),
        ],
    },
    "Art": {
        "UG2": [
            ("Batik and Resist-Dye Textile Art", "Practice batik and other resist-dye techniques for creating patterned textile art with wax and fabric dyes."),
            ("Woodcut and Relief Printmaking", "Learn the carving and inking process of woodcut and relief printmaking to produce editioned prints."),
            ("Digital 3D Sculpting Fundamentals", "Introduce digital sculpting software and techniques for creating three-dimensional forms in a virtual environment."),
            ("Diorama and Miniature Model Art", "Explore the construction of dioramas and miniature scenes as a narrative and sculptural art form."),
            ("Origami and Paper-Folding Sculpture", "Study origami and paper-folding techniques as a basis for sculptural and mathematical art forms."),
            ("Ephemeral and Sand Art Practices", "Examine temporary art forms such as sand mandalas and land drawings that embrace impermanence as a concept."),
            ("Tattoo Design Fundamentals", "Cover the principles of designing tattoo artwork, including line weight, placement, and skin-appropriate composition."),
            ("Scientific and Botanical Illustration", "Practice precise observational drawing techniques used to depict plants, anatomy, and natural specimens."),
        ],
    },
    "Art History": {
        "UG2": [
            ("Romanesque Art and Architecture", "Survey the massive stone architecture and narrative relief sculpture of the Romanesque period in Europe."),
            ("Gothic Cathedral Sculpture and Stained Glass", "Study the sculptural programs and stained glass traditions that defined Gothic cathedral architecture."),
            ("Aztec and Mixtec Art Traditions", "Examine the sculpture, codices, and featherwork of Aztec and Mixtec visual culture in Mesoamerica."),
            ("Inca and Andean Visual Culture", "Explore textiles, metalwork, and architecture of the Inca and other Andean civilizations."),
            ("Chinese Landscape Painting Traditions", "Study the philosophy and technique behind classical Chinese landscape painting across dynastic periods."),
            ("Japanese Ukiyo-e Woodblock Prints", "Examine the subjects, printing methods, and cultural context of Japanese ukiyo-e woodblock prints."),
            ("Korean Ceramic Traditions: Celadon and Buncheong", "Survey the technical and aesthetic development of Korean celadon and buncheong ceramics."),
            ("Etruscan Art and Tomb Painting", "Study Etruscan funerary art, tomb painting, and bronze work as precursors to Roman visual culture."),
        ],
    },
    "Artificial Intelligence": {
        "UG2": [
            ("Genetic Algorithms and Evolutionary Computation", "Introduce genetic algorithms and other evolutionary computation methods for search and optimization problems."),
            ("Simulated Annealing for Combinatorial Optimization", "Study simulated annealing as a probabilistic technique for approximating global optima in large search spaces."),
            ("Hill Climbing and Local Search Methods", "Examine hill climbing and other local search algorithms, including their limitations with local optima."),
            ("Constraint Satisfaction Problem Solving", "Cover backtracking, arc consistency, and heuristics for solving constraint satisfaction problems."),
            ("Iterative Deepening and Memory-Bounded Search", "Study iterative deepening search and memory-bounded variants that trade time for reduced memory usage."),
            ("Case-Based Reasoning Systems", "Introduce case-based reasoning as a method for solving new problems by adapting solutions to prior cases."),
            ("Multi-Agent Systems Fundamentals", "Cover the design of systems composed of multiple interacting autonomous agents and their coordination."),
            ("Cooperative Multi-Agent Reinforcement Learning", "Examine reinforcement learning techniques for agents that must learn to cooperate toward a shared goal."),
            ("Model-Based versus Model-Free Reinforcement Learning", "Compare reinforcement learning approaches that build an internal model of the environment against those that do not."),
            ("Actor-Critic Methods in Reinforcement Learning", "Study actor-critic architectures that combine policy-based and value-based reinforcement learning."),
            ("Deep Q-Networks and Value Function Approximation", "Introduce deep Q-networks and how neural networks approximate value functions in reinforcement learning."),
            ("Generative Adversarial Networks Fundamentals", "Cover the generator-discriminator framework of generative adversarial networks and their training dynamics."),
            ("Variational Autoencoders for Generative Modeling", "Study variational autoencoders as a probabilistic approach to learning latent representations for generation."),
            ("Attention Mechanisms and the Transformer Architecture", "Introduce attention mechanisms and how they underpin the transformer architecture used across modern AI systems."),
            ("Self-Supervised Representation Learning", "Examine self-supervised learning techniques that generate training signals from unlabeled data."),
            ("Federated Learning Fundamentals", "Study federated learning as a method for training models across decentralized data sources without centralizing data."),
            ("AI Alignment and Value Specification Problems", "Explore the challenge of specifying objectives so that AI system behavior matches intended human values."),
            ("Sensor Fusion for Robotic Perception", "Cover techniques for combining data from multiple sensors to improve a robot's perception of its environment."),
            ("Path Planning Algorithms for Mobile Robots", "Study algorithms such as A* and RRT that plan collision-free paths for mobile robots."),
            ("Automatic Speech Recognition Systems", "Introduce the components and models used to convert spoken audio into text."),
            ("Cognitive Architectures: SOAR and ACT-R", "Examine cognitive architectures that model human-like reasoning and memory processes in AI systems."),
            ("Neural Architecture Search", "Study automated methods for searching the space of neural network architectures to find high-performing designs."),
        ],
    },
    "Big Data": {
        "UG2": [
            ("Apache NiFi for Automated Data Flow Pipelines", "Introduce Apache NiFi for designing and automating data ingestion and routing pipelines."),
            ("Apache Iceberg and Open Table Formats", "Study Apache Iceberg and other open table formats that bring transactional consistency to data lakes."),
            ("Change Data Capture Techniques for Data Pipelines", "Examine change data capture methods for propagating incremental database changes into downstream systems."),
            ("Apache ZooKeeper for Distributed Coordination", "Cover ZooKeeper's role in coordinating configuration, leader election, and synchronization in distributed systems."),
            ("Apache Druid for Real-Time Analytics", "Introduce Apache Druid as a column-oriented data store optimized for real-time analytical queries."),
            ("Columnar Storage Formats: Parquet and ORC", "Study the design of columnar storage formats and how they improve analytical query performance."),
            ("Approximate Nearest Neighbor Search at Scale", "Examine algorithms for efficient approximate nearest neighbor search over large-scale vector datasets."),
            ("Bloom Filters and Probabilistic Data Structures", "Introduce Bloom filters and other probabilistic data structures used to reduce memory in large-scale systems."),
            ("HyperLogLog and Cardinality Estimation", "Study HyperLogLog and related algorithms for estimating the number of distinct elements in massive datasets."),
            ("Apache Airflow for Workflow Orchestration", "Cover Apache Airflow's role in scheduling, orchestrating, and monitoring big data processing workflows."),
            ("Benchmarking Methodologies for Big Data Systems", "Examine methodologies for benchmarking throughput, latency, and scalability of big data platforms."),
        ],
    },
    "Biology": {
        "UG2": [
            ("Photosynthesis: Light-Dependent and Light-Independent Reactions", "Study the biochemical stages of photosynthesis, from light capture to carbon fixation in the Calvin cycle."),
            ("Plant Reproduction and Pollination Biology", "Examine the reproductive structures of flowering plants and the mechanisms of pollination and seed formation."),
            ("Plant Hormones and Growth Regulation", "Cover the roles of auxins, gibberellins, and other hormones in regulating plant growth and development."),
            ("Mycorrhizal Symbiosis in Plants", "Study the mutualistic relationship between fungi and plant roots that enhances nutrient uptake."),
            ("Parasitology: Life Cycles and Host Specificity", "Examine the life cycles, transmission routes, and host specificity of major parasitic organisms."),
            ("Population Genetics and Hardy-Weinberg Equilibrium", "Introduce the mathematical framework for analyzing allele frequencies in populations at equilibrium."),
            ("Speciation Mechanisms and Reproductive Isolation", "Study the mechanisms, such as geographic and reproductive isolation, that drive the formation of new species."),
            ("Phylogenetics and Cladistic Analysis", "Cover methods for reconstructing evolutionary relationships among organisms using cladistic analysis."),
            ("Cell Signaling Pathways and Second Messengers", "Examine how cells transmit signals internally through receptor activation and second messenger systems."),
            ("Cell Cycle Regulation and Checkpoints", "Study the checkpoints and regulatory proteins that control progression through the cell cycle."),
            ("Apoptosis and Programmed Cell Death", "Introduce the molecular pathways that trigger and execute programmed cell death in multicellular organisms."),
            ("Membrane Transport Mechanisms", "Cover passive and active transport mechanisms that move substances across cellular membranes."),
            ("Enzyme Kinetics and Michaelis-Menten Analysis", "Study the mathematical modeling of enzyme reaction rates using the Michaelis-Menten equation."),
            ("Coevolution and Predator-Prey Dynamics", "Examine reciprocal evolutionary adaptations between predators and prey or hosts and parasites."),
            ("Invasion Biology and Invasive Species Ecology", "Study the ecological mechanisms by which invasive species establish, spread, and impact native ecosystems."),
        ],
    },
    "Business Analytics": {
        "UG2": [
            ("Data Envelopment Analysis for Efficiency Measurement", "Introduce data envelopment analysis as a method for measuring the relative efficiency of comparable business units."),
            ("Analytic Hierarchy Process for Business Decisions", "Study the analytic hierarchy process for structuring and prioritizing complex, multi-criteria business decisions."),
            ("Text Analytics and Mining for Business Insights", "Cover techniques for extracting patterns and insights from unstructured text data such as reviews and support tickets."),
            ("Prescriptive Analytics and Optimization Modeling", "Examine prescriptive analytics methods that recommend optimal actions given business constraints and objectives."),
            ("Organizational Network Analysis", "Study network analysis techniques applied to mapping communication and collaboration patterns within organizations."),
            ("Geospatial Analytics for Business Location Decisions", "Introduce geospatial analytics techniques for site selection, market coverage, and location-based decision-making."),
            ("Predictive Analytics for Employee Attrition", "Examine predictive modeling approaches used to identify employees at risk of leaving an organization."),
            ("Analytics Maturity Model Assessment", "Study frameworks for assessing an organization's analytics capability maturity and planning improvement."),
            ("Healthcare Operations Analytics", "Cover analytics techniques applied to patient flow, scheduling, and resource utilization in healthcare operations."),
            ("Sports Analytics Fundamentals", "Introduce statistical and analytical methods used to evaluate athlete and team performance in sports."),
            ("Public Sector Analytics for Policy Evaluation", "Examine how analytics techniques are applied to evaluate the effectiveness of public policy programs."),
        ],
    },
    "Chemistry": {
        "UG2": [
            ("Catalysis: Homogeneous and Heterogeneous Mechanisms", "Compare homogeneous and heterogeneous catalytic mechanisms and their roles in accelerating chemical reactions."),
            ("Colloid Chemistry and Interfacial Phenomena", "Study the behavior of colloidal systems and the surface phenomena that govern their stability."),
            ("Electrochemical Corrosion Mechanisms", "Examine the electrochemical processes underlying metal corrosion and methods for its prevention."),
            ("Battery Chemistry and Energy Storage Materials", "Cover the chemical principles behind battery technologies and the materials used for energy storage."),
            ("Medicinal Chemistry Fundamentals", "Introduce the principles of designing and optimizing chemical compounds for pharmaceutical activity."),
            ("Chemistry of Natural Products", "Study the structure, biosynthesis, and isolation of naturally occurring organic compounds."),
            ("Organometallic Catalysis and Cross-Coupling Reactions", "Examine organometallic catalysts and their use in cross-coupling reactions for organic synthesis."),
            ("Chemical Process Safety and Hazard Analysis", "Cover systematic methods for identifying and mitigating hazards in chemical processes and industrial plants."),
            ("Ion Exchange Chemistry", "Study the principles of ion exchange reactions and their applications in purification and separation."),
            ("Pyrotechnic Chemistry Fundamentals", "Examine the chemical reactions and compounds responsible for color, light, and propulsion in pyrotechnics."),
            ("Cosmetic Chemistry Fundamentals", "Introduce the formulation chemistry behind common cosmetic and personal care products."),
            ("Isotope Chemistry and Applications", "Study the properties of isotopes and their applications in dating, tracing, and medical imaging."),
        ],
    },
    "Cloud Computing": {
        "UG2": [
            ("Cloud Content Delivery Networks and Edge Caching", "Study how content delivery networks cache and distribute content closer to users to reduce latency."),
            ("Cloud DNS Management and Traffic Routing", "Examine how cloud DNS services manage domain resolution and route traffic across regions."),
            ("Immutable Infrastructure Patterns", "Introduce immutable infrastructure practices where servers are replaced rather than modified in place."),
            ("GitOps for Cloud Deployment Pipelines", "Cover GitOps practices that use version-controlled repositories as the source of truth for cloud deployments."),
            ("Chaos Engineering for Cloud Resilience Testing", "Study chaos engineering practices that intentionally introduce failures to test cloud system resilience."),
            ("Cloud FinOps Practices", "Examine FinOps practices that bring financial accountability to variable cloud spending."),
            ("Cloud Landing Zone Design", "Introduce the design of secure, well-governed landing zones for onboarding workloads to the cloud."),
            ("Multi-Region Active-Active Architecture Patterns", "Study architecture patterns that run active workloads simultaneously across multiple cloud regions."),
            ("Cloud Data Warehousing Services Comparison", "Compare managed cloud data warehousing services and their approaches to scalable analytical storage."),
            ("Cloud Disaster Recovery Planning", "Cover strategies for planning and testing disaster recovery procedures for cloud-hosted workloads."),
        ],
    },
    "Coding": {
        "UG2": [
            ("Regular Expressions and Pattern Matching", "Introduce regular expression syntax and techniques for matching and extracting patterns in text."),
            ("Metaprogramming and Reflection Techniques", "Study metaprogramming and reflection techniques that let programs inspect and modify their own structure."),
            ("Domain-Specific Language Design", "Cover the principles of designing small, specialized languages tailored to a particular problem domain."),
            ("Test-Driven Development Practices", "Introduce the test-driven development cycle of writing tests before implementation code."),
            ("Property-Based Testing Techniques", "Study property-based testing, which generates varied inputs to verify general properties of code behavior."),
            ("Code Smells and Anti-Pattern Recognition", "Examine common code smells and anti-patterns that signal underlying design or maintainability issues."),
            ("Feature Flags and Progressive Rollout Strategies", "Cover the use of feature flags to control and gradually roll out new functionality in production systems."),
            ("Immutable Data Structures and Persistent Collections", "Study immutable data structures and persistent collections and their benefits for predictable program state."),
        ],
    },
    "Computer Science Engineering": {
        "UG2": [
            ("Real-Time Operating Systems Fundamentals", "Introduce the scheduling and timing guarantees that distinguish real-time operating systems from general-purpose ones."),
            ("Embedded Systems Programming", "Cover the principles of writing software for resource-constrained embedded hardware platforms."),
            ("Hardware Description Languages: VHDL and Verilog", "Introduce hardware description languages used to design and simulate digital circuits."),
            ("FPGA Design Fundamentals", "Study the design flow for implementing digital logic on field-programmable gate arrays."),
            ("Parallel Computing Architectures: SIMD and MIMD", "Examine parallel computing architecture classifications and how they exploit different forms of parallelism."),
            ("GPU Computing Fundamentals", "Introduce the architecture and programming model of GPUs for general-purpose parallel computation."),
            ("Software Reliability Engineering", "Cover techniques for measuring, predicting, and improving the reliability of software systems."),
            ("Human-Computer Interaction Principles for Engineers", "Introduce usability and interaction design principles relevant to engineers building user-facing systems."),
        ],
    },
    "Cooking": {
        "UG2": [
            ("Regional Japanese Cuisine Techniques", "Study foundational techniques of regional Japanese cuisine, including knife work, dashi, and rice preparation."),
            ("Regional Thai Cuisine Techniques", "Explore the balance of sweet, sour, salty, and spicy flavors central to regional Thai cooking techniques."),
            ("Sourdough Starter Cultivation and Maintenance", "Cover the cultivation, feeding, and maintenance of a sourdough starter for naturally leavened bread."),
            ("Sous Vide Cooking Techniques", "Introduce sous vide cooking methods that use precise temperature control for consistent results."),
            ("Chocolate Tempering and Confectionery Work", "Study the tempering process for chocolate and foundational techniques for confectionery production."),
            ("Regional American Barbecue Styles", "Compare regional American barbecue styles and the smoking and rub techniques that define each."),
        ],
    },
    "Critical Thinking": {
        "UG2": [
            ("Formal Fallacies: Affirming the Consequent", "Study the formal logical fallacy of affirming the consequent and how it differs from valid deductive inference."),
            ("Formal Fallacies: Denying the Antecedent", "Examine the formal logical fallacy of denying the antecedent and its distinction from valid argument forms."),
            ("Abductive Reasoning and Inference to the Best Explanation", "Introduce abductive reasoning as a method for selecting the most plausible explanation for observed evidence."),
            ("Confirmation Bias and Motivated Reasoning", "Study how confirmation bias and motivated reasoning distort the evaluation of evidence."),
            ("Availability Heuristic and Risk Perception", "Examine how the availability heuristic skews perceptions of risk based on how easily examples come to mind."),
            ("Anchoring Effect in Judgment and Estimation", "Study how initial reference points anchor subsequent numerical judgments and estimates."),
            ("Sunk Cost Fallacy in Decision-Making", "Examine the sunk cost fallacy and how past investments improperly influence future decisions."),
            ("Survivorship Bias in Data Interpretation", "Study survivorship bias and how it distorts conclusions drawn from incomplete or filtered data."),
            ("Correlation-Causation Confusion in Reasoning", "Examine common reasoning errors that mistake correlation between variables for a causal relationship."),
            ("Simpson's Paradox in Statistical Reasoning", "Study Simpson's Paradox, where a trend appears in subgroups but reverses when data is combined."),
            ("Slippery Slope Argument Analysis", "Examine the structure of slippery slope arguments and criteria for distinguishing valid from fallacious ones."),
            ("False Dilemma and Either-Or Thinking", "Study the false dilemma fallacy and techniques for identifying overlooked alternatives in an argument."),
            ("Appeal to Authority Fallacy", "Examine when citing an authority strengthens an argument and when it constitutes a fallacious appeal."),
            ("Circular Reasoning and Begging the Question", "Study circular reasoning, where a conclusion is assumed within its own premises."),
            ("Hasty Generalization Fallacy", "Examine the hasty generalization fallacy and how insufficient samples lead to unreliable conclusions."),
            ("Post Hoc Ergo Propter Hoc Reasoning Errors", "Study the post hoc fallacy, in which sequence in time is mistaken for a causal relationship."),
            ("Steelmanning: Strengthening Opposing Arguments", "Practice steelmanning, the technique of representing opposing arguments in their strongest possible form."),
            ("Socratic Questioning Techniques", "Introduce Socratic questioning as a structured method for probing assumptions and clarifying reasoning."),
            ("Analogical Argument Evaluation", "Study criteria for evaluating the strength and relevance of analogies used in argumentation."),
            ("Cognitive Dissonance and Belief Revision", "Examine how cognitive dissonance influences the process of revising beliefs in light of new evidence."),
            ("Overconfidence Bias in Estimation Tasks", "Study overconfidence bias and its effect on the accuracy of self-assessed judgments and estimates."),
            ("Pre-Mortem Analysis for Decision-Making", "Introduce the pre-mortem technique of imagining failure in advance to surface risks before deciding."),
            ("Inversion as a Problem-Solving Technique", "Study inversion, a technique that approaches problems by considering how to cause the opposite outcome."),
        ],
    },
    "Cybersecurity": {
        "UG2": [
            ("Buffer Overflow Exploitation Techniques", "Study how buffer overflow vulnerabilities are exploited and the defensive coding practices that prevent them."),
            ("Privilege Escalation Techniques", "Examine common methods attackers use to escalate privileges after gaining initial access to a system."),
            ("Lateral Movement Techniques in Compromised Networks", "Study how attackers move laterally across a network after an initial compromise."),
            ("Command and Control Infrastructure Analysis", "Examine how attackers establish and use command and control infrastructure to manage compromised systems."),
            ("Steganography and Covert Channel Detection", "Study techniques for hiding data within other files and methods for detecting such covert channels."),
            ("Digital Forensics: Disk Imaging and Chain of Custody", "Introduce disk imaging procedures and chain-of-custody requirements in digital forensic investigations."),
            ("Mobile Device Forensics Techniques", "Study forensic techniques for extracting and analyzing evidence from smartphones and mobile devices."),
            ("Cloud Forensics Challenges and Techniques", "Examine the unique challenges of conducting forensic investigations within cloud computing environments."),
            ("Security Information and Event Management (SIEM) Systems", "Introduce SIEM platforms that aggregate and correlate security event data for detection and response."),
            ("Honeypots and Deception Technology", "Study how honeypots and deception technology lure and detect attackers within a network."),
            ("Network Intrusion Detection Systems (Snort, Suricata)", "Introduce signature-based and anomaly-based network intrusion detection systems."),
            ("Penetration Testing Methodology (PTES)", "Study the phases of a structured penetration testing methodology from reconnaissance to reporting."),
            ("Red Team versus Blue Team Exercises", "Examine how red team and blue team exercises simulate attacks and defenses to improve security posture."),
            ("Capture the Flag Competition Strategies", "Introduce strategies and skill areas relevant to competing in cybersecurity capture-the-flag competitions."),
            ("Bug Bounty Program Fundamentals", "Study how bug bounty programs incentivize external researchers to responsibly disclose vulnerabilities."),
            ("Secure Software Development Lifecycle", "Introduce the integration of security practices into each phase of the software development lifecycle."),
            ("Threat Modeling with the STRIDE Framework", "Study the STRIDE framework for systematically identifying categories of threats during system design."),
            ("Security Awareness Training Program Design", "Examine how to design effective security awareness training programs for organizational staff."),
            ("Password Cracking Techniques and Defenses", "Study common password cracking techniques and the hashing and policy defenses that mitigate them."),
            ("Multi-Factor Authentication Bypass Techniques", "Examine techniques attackers use to bypass multi-factor authentication and corresponding mitigations."),
            ("Wireless Network Penetration Testing", "Introduce methods for assessing the security of wireless networks through authorized penetration testing."),
            ("VPN Technologies and Protocols", "Study VPN protocols and how they provide secure, encrypted connectivity over untrusted networks."),
            ("Blockchain and Smart Contract Security", "Examine common vulnerabilities in blockchain applications and smart contracts and their mitigations."),
            ("Quantum-Resistant Cryptography Fundamentals", "Introduce cryptographic algorithms designed to remain secure against attacks from quantum computers."),
            ("Data Loss Prevention Systems", "Study data loss prevention systems that monitor and restrict the unauthorized movement of sensitive data."),
            ("Incident Response Playbook Development", "Examine how to develop structured incident response playbooks for handling specific types of security incidents."),
        ],
    },
    "Data Science": {
        "UG2": [
            ("Support Vector Machines for Classification", "Introduce support vector machines and the margin-maximization principle behind their classification decisions."),
            ("Gradient Boosting Machines: XGBoost and LightGBM", "Study gradient boosting frameworks such as XGBoost and LightGBM and their use in predictive modeling."),
            ("Model Interpretability with SHAP and LIME", "Examine SHAP and LIME as techniques for explaining individual predictions of complex machine learning models."),
            ("Cross-Validation Strategies for Model Evaluation", "Study cross-validation techniques used to estimate model performance and reduce overfitting risk."),
            ("Hyperparameter Tuning Techniques", "Introduce grid search, random search, and Bayesian optimization for tuning model hyperparameters."),
            ("Bayesian Statistics for Data Science", "Cover Bayesian inference concepts and their application to updating beliefs given observed data."),
            ("Markov Chain Monte Carlo Methods", "Introduce Markov Chain Monte Carlo sampling methods for approximating complex probability distributions."),
            ("Survival Analysis Techniques", "Study survival analysis methods for modeling time-to-event data such as customer churn or equipment failure."),
            ("Anomaly Detection for Fraud Analytics", "Examine anomaly detection techniques applied to identifying fraudulent transactions and behavior."),
            ("Data Augmentation Techniques", "Study data augmentation methods used to expand and diversify training datasets for machine learning models."),
            ("Graph Neural Networks Fundamentals", "Introduce graph neural networks and how they learn representations over graph-structured data."),
            ("Time Series Decomposition Methods", "Study methods for decomposing time series into trend, seasonal, and residual components."),
            ("ARIMA and Seasonal Forecasting Models", "Introduce ARIMA and seasonal forecasting models for predicting future values in time series data."),
            ("Data Versioning and Reproducibility Practices", "Examine practices and tools for versioning datasets and ensuring reproducible data science experiments."),
            ("Synthetic Data Generation Techniques", "Study techniques for generating synthetic datasets that preserve statistical properties of real data."),
            ("Active Learning for Labeling Efficiency", "Introduce active learning strategies that prioritize which data points are most valuable to label."),
            ("Multi-Armed Bandits for Online Experimentation", "Study multi-armed bandit algorithms as an alternative to traditional A/B testing for online experiments."),
            ("Production Model Monitoring and Drift Detection", "Examine techniques for monitoring deployed models and detecting data or concept drift over time."),
            ("Data Science Ethics Review Processes", "Introduce the structure and purpose of ethics review processes for data science projects involving human data."),
        ],
    },
    "Digital Marketing": {
        "UG2": [
            ("Conversational Marketing and Chatbot Strategy", "Study how conversational marketing and chatbots engage customers in real time across digital channels."),
            ("Voice Search Optimization", "Examine strategies for optimizing digital content to be discoverable through voice search assistants."),
            ("Marketing Automation Workflow Design", "Introduce the design of automated marketing workflows that trigger actions based on customer behavior."),
            ("Content Marketing Strategy and Editorial Calendars", "Study how to plan a content marketing strategy and organize publishing through an editorial calendar."),
            ("Video SEO Optimization", "Examine techniques for optimizing video content and metadata to improve discoverability in search results."),
            ("Online Community Management Strategies", "Study strategies for building and moderating engaged online brand communities."),
            ("Loyalty Program Design", "Introduce the design principles behind effective customer loyalty and rewards programs."),
            ("Account-Based Marketing Strategy", "Examine account-based marketing as a targeted strategy for engaging high-value business accounts."),
            ("B2B Digital Marketing Fundamentals", "Study the distinct channels and buyer journey considerations in business-to-business digital marketing."),
            ("Marketing Technology Stack Selection", "Examine criteria for selecting and integrating tools within an organization's marketing technology stack."),
            ("Customer Journey Mapping", "Introduce customer journey mapping as a method for visualizing touchpoints across the buying process."),
            ("Omnichannel Marketing Strategy", "Study how omnichannel strategies create consistent customer experiences across multiple marketing channels."),
            ("Social Commerce Strategy", "Examine strategies for enabling direct product discovery and purchase within social media platforms."),
            ("Livestream Shopping and Selling", "Study the growing practice of livestream shopping as a real-time, interactive sales channel."),
            ("Gamification in Marketing", "Introduce gamification techniques used to increase engagement and motivation in marketing campaigns."),
            ("Neuromarketing Principles", "Examine neuromarketing concepts that apply findings from neuroscience to understanding consumer response."),
            ("Podcast Advertising Strategy", "Study the strategic considerations and formats involved in advertising through podcast media."),
            ("Digital Marketing for Nonprofit Organizations", "Examine how nonprofit organizations adapt digital marketing strategies for fundraising and awareness goals."),
            ("Employee Advocacy and Social Media Marketing Programs", "Study programs that mobilize employees as authentic brand advocates on social media."),
        ],
    },
    "Economics": {
        "UG2": [
            ("Externalities and the Coase Theorem", "Study how externalities distort market outcomes and the conditions under which the Coase Theorem resolves them."),
            ("Public Goods and the Free-Rider Problem", "Examine the characteristics of public goods and why they lead to the free-rider problem."),
            ("Adverse Selection in Information Asymmetry", "Study how adverse selection arises when one party in a transaction has more information than the other."),
            ("Moral Hazard and Incentive Design", "Examine moral hazard and how contracts and incentives are designed to mitigate it."),
            ("Principal-Agent Theory", "Introduce principal-agent theory and the incentive problems that arise when interests diverge between parties."),
            ("Auction Theory Fundamentals", "Study the major auction formats and the strategic bidding behavior they induce."),
            ("Cournot Competition Model", "Introduce the Cournot model of oligopoly in which firms compete by choosing output quantities."),
            ("Bertrand Competition Model", "Examine the Bertrand model of oligopoly in which firms compete by choosing prices."),
            ("Monopolistic Competition", "Study the market structure of monopolistic competition, characterized by product differentiation and free entry."),
            ("Price Discrimination Strategies", "Examine first-, second-, and third-degree price discrimination strategies used by firms with market power."),
            ("General Equilibrium Theory", "Introduce general equilibrium theory and the conditions for simultaneous equilibrium across multiple markets."),
            ("Welfare Economics and Pareto Efficiency", "Study welfare economics and the concept of Pareto efficiency as a benchmark for resource allocation."),
            ("Social Choice Theory and Arrow's Impossibility Theorem", "Examine social choice theory and Arrow's Impossibility Theorem regarding aggregating individual preferences."),
            ("The IS-LM Model", "Introduce the IS-LM model as a framework for analyzing the interaction between goods and money markets."),
            ("The Phillips Curve and Inflation-Unemployment Tradeoff", "Study the Phillips Curve and the historical debate over the tradeoff between inflation and unemployment."),
            ("Rational Expectations Theory", "Examine rational expectations theory and its implications for the effectiveness of economic policy."),
            ("Real Business Cycle Theory", "Introduce real business cycle theory, which attributes economic fluctuations to real productivity shocks."),
            ("New Keynesian Economics", "Study New Keynesian economics and its microfoundations for price and wage rigidity."),
            ("Money Supply and the Money Multiplier", "Examine how the banking system expands the money supply through the money multiplier process."),
            ("Quantitative Easing and Unconventional Monetary Policy", "Study quantitative easing and other unconventional monetary policy tools used near the zero lower bound."),
            ("Inflation Targeting Frameworks", "Introduce inflation targeting as a monetary policy framework adopted by many central banks."),
            ("Exchange Rate Regimes", "Compare fixed, floating, and managed exchange rate regimes and their macroeconomic implications."),
            ("Balance of Payments Accounting", "Study the structure of the balance of payments and how it records a country's international transactions."),
            ("Trade Policy: Tariffs and Quotas", "Examine the economic effects of tariffs and quotas on domestic and international markets."),
            ("Currency Crises and Speculative Attacks", "Study the dynamics of currency crises and speculative attacks on fixed exchange rate regimes."),
            ("Foreign Direct Investment Theory", "Introduce theories explaining why firms invest directly in production facilities abroad."),
            ("Instrumental Variables Estimation", "Study instrumental variables estimation as a method for addressing endogeneity in econometric models."),
            ("Difference-in-Differences Methodology", "Examine the difference-in-differences method for estimating causal effects using observational data."),
            ("Time Series Econometrics and Stationarity", "Introduce stationarity concepts and their importance for valid time series econometric analysis."),
            ("Agricultural Economics Fundamentals", "Study the economic principles governing agricultural production, markets, and rural development."),
            ("Economics of Education", "Examine economic models of human capital investment and returns to education."),
        ],
    },
    "English": {
        "UG2": [
            ("Beowulf and Old English Literature", "Study Beowulf and other Old English texts within the alliterative verse tradition of early medieval England."),
            ("The Sonnet Form Across Literary Periods", "Trace the development of the sonnet form from its Petrarchan origins through later Shakespearean and modern variants."),
            ("Theatre of the Absurd", "Examine absurdist drama and its rejection of conventional plot and logical dialogue structures."),
            ("Magical Realism in Literature", "Study magical realism as a literary mode that blends fantastical elements with realistic settings."),
            ("Ecocriticism and Environmental Literature", "Introduce ecocriticism as a critical lens for analyzing the representation of nature and environment in literature."),
        ],
    },
    "Finance": {
        "UG2": [
            ("Futures Contracts Fundamentals", "Introduce futures contracts, their standardized terms, and their use in hedging and speculation."),
            ("Forward Contracts and Hedging Strategies", "Study forward contracts and how they are used to hedge against future price or rate movements."),
            ("Interest Rate and Currency Swaps", "Examine the structure and use of interest rate and currency swaps in managing financial risk."),
            ("Options Greeks and Risk Sensitivities", "Study the option Greeks and how they measure an option's sensitivity to underlying market factors."),
            ("Structured Products and Securitization", "Introduce structured financial products and the securitization process that creates them."),
            ("Mortgage-Backed Securities", "Study the structure and risk characteristics of mortgage-backed securities."),
            ("Credit Default Swaps", "Examine credit default swaps as instruments for transferring and hedging credit risk."),
            ("Sovereign Wealth Fund Management", "Introduce the objectives and investment strategies of sovereign wealth funds."),
            ("Islamic Finance Principles", "Study the principles of Islamic finance, including prohibitions on interest and profit-sharing structures."),
            ("Microfinance and Financial Inclusion", "Examine microfinance models and their role in expanding financial access to underserved populations."),
            ("Fintech and Digital Payment Systems", "Study how fintech innovations and digital payment systems are reshaping financial services."),
            ("Cryptocurrency and Blockchain in Finance", "Introduce cryptocurrency assets and blockchain technology as they relate to modern finance."),
            ("Mergers and Acquisitions Valuation Methods", "Study valuation methods used to assess target companies in mergers and acquisitions."),
            ("Private Equity Deal Structuring", "Examine how private equity firms structure deals, financing, and exit strategies."),
            ("ESG Investing and Sustainable Finance", "Introduce environmental, social, and governance criteria as they are integrated into investment decisions."),
        ],
    },
    "First Aid": {
        "UG2": [
            ("Near-Drowning and Water Rescue First Aid", "Study first aid response for near-drowning incidents, including safe rescue and resuscitation priorities."),
            ("Altitude Sickness Recognition and Response", "Examine the recognition and initial management of altitude sickness in high-elevation settings."),
            ("Marine Life Sting and Bite First Aid", "Study first aid procedures for stings and bites from marine organisms such as jellyfish and stingrays."),
            ("Snake Bite First Aid", "Introduce first aid steps for managing suspected venomous snake bites prior to medical care."),
            ("Eye Injury First Aid", "Study first aid procedures for chemical, foreign body, and blunt trauma injuries to the eye."),
            ("Dental Emergency First Aid", "Examine first aid response for dental emergencies such as knocked-out or fractured teeth."),
            ("Crush Injury and Compartment Syndrome Recognition", "Study the recognition of crush injuries and compartment syndrome and appropriate first aid response."),
            ("Lightning Strike Injury Response", "Examine the unique first aid considerations for responding to lightning strike injuries."),
            ("Workplace First Aid Program Basics", "Introduce the components of a workplace first aid program, including kit requirements and responder roles."),
        ],
    },
    "Foreign Languages": {
        "UG2": [
            ("Indonesian Grammar and Vocabulary Fundamentals", "Introduce foundational Indonesian grammar structures and everyday vocabulary for beginning learners."),
            ("Urdu Script and Grammar Fundamentals", "Introduce the Urdu script and foundational grammar structures for beginning learners."),
        ],
    },
    "General Knowledge": {
        "UG2": [
            ("History of Space Exploration", "Survey key milestones in the history of human and robotic space exploration."),
            ("World Sign Languages and Deaf Culture", "Introduce the diversity of sign languages around the world and aspects of Deaf culture and community."),
        ],
    },
    "Geography": {
        "UG2": [
            ("Glacial Geomorphology and Ice Age Landscapes", "Study landforms shaped by glacial processes and the legacy of past ice ages on the landscape."),
            ("Soil Geography and Pedology", "Introduce the classification and spatial distribution of soil types and the processes that form them."),
            ("Medical Geography and Disease Diffusion", "Examine how geographic factors influence the spread and distribution of diseases across populations."),
            ("Geography of Tourism Impacts", "Study the economic, environmental, and cultural impacts of tourism on host regions."),
            ("Geography of Renewable Energy Siting", "Examine the geographic factors influencing the siting of wind, solar, and other renewable energy projects."),
            ("Informal Settlements and Slum Geography", "Study the spatial patterns and socioeconomic conditions associated with informal urban settlements."),
            ("Geography of Forced Migration and Displacement", "Examine the geographic patterns and causes of forced migration and displaced populations."),
            ("Food Deserts and Urban Food Access Geography", "Study the spatial distribution of food deserts and their impact on urban food access."),
            ("Coastal Zone Management", "Introduce the principles and challenges of managing development and resources in coastal zones."),
            ("Agroecology and Sustainable Land Use Geography", "Examine agroecological approaches to sustainable land use and their geographic distribution."),
        ],
    },
    "Health Education": {
        "UG2": [
            ("Vaccine Hesitancy and Health Communication Strategies", "Study the drivers of vaccine hesitancy and communication strategies used to address public concerns."),
            ("School-Based Health Program Design", "Introduce principles for designing health education programs delivered within school settings."),
            ("Workplace Wellness Program Design", "Examine the components of effective employer-sponsored workplace wellness programs."),
            ("Telehealth and Digital Health Education", "Study the role of telehealth and digital tools in delivering health education and services remotely."),
            ("Foodborne Illness Prevention Education", "Introduce educational strategies for preventing foodborne illness through safe handling practices."),
            ("Environmental Tobacco Smoke Education", "Examine the health risks of secondhand smoke and educational approaches to reducing exposure."),
            ("Health Education for Refugee and Immigrant Populations", "Study culturally responsive health education approaches for refugee and immigrant communities."),
            ("Sports Concussion Education and Prevention", "Introduce concussion recognition, prevention strategies, and return-to-play education in sports settings."),
            ("Health Literacy for Older Adult Populations", "Examine strategies for improving health literacy and communication with older adult populations."),
        ],
    },
}
