"""Module topics bringing Artificial Intelligence, Machine Learning,
Natural Language Processing, and Data Science up to 20+ lessons per
level (C1 through M1)."""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Artificial Intelligence": {
        "C1": [
            ("Propositional Logic and Inference", "Introduces propositional logic syntax and semantics, including truth tables and inference rules such as modus ponens and resolution for deriving valid conclusions."),
            ("Constraint Satisfaction Problems", "Covers CSP formulation with variables, domains, and constraints, and introduces basic solving strategies used in scheduling and puzzle-solving tasks."),
            ("Backtracking Search for CSPs", "Explains depth-first backtracking search with constraint checking, and heuristics like minimum remaining values for pruning the search tree."),
            ("Local Search and Optimization (Hill Climbing, Simulated Annealing)", "Presents iterative improvement methods such as hill climbing and simulated annealing for finding good solutions in large search spaces without exhaustive search."),
            ("Rule-Based Expert Systems Design", "Covers the architecture of rule-based expert systems, including knowledge bases, inference engines, and forward and backward chaining."),
            ("Fuzzy Logic Systems", "Introduces fuzzy set theory and fuzzy inference systems for reasoning with degrees of truth rather than binary logic."),
            ("History of AI: Symbolic Era to Deep Learning", "Traces the evolution of AI from early symbolic reasoning and expert systems through connectionism to modern deep learning."),
            ("Turing Test and Machine Intelligence Criteria", "Examines the Turing Test as a criterion for machine intelligence and discusses its philosophical strengths and limitations."),
            ("Case-Based Reasoning", "Covers reasoning by analogy to previously solved cases, including case retrieval, adaptation, and learning from outcomes."),
            ("Recommender Systems Fundamentals", "Introduces the goals and basic architectures of recommender systems that predict user preferences for items."),
            ("Content-Based Recommendation Techniques", "Explains how recommender systems use item features and user profiles to recommend similar content."),
            ("AI in Healthcare Diagnostics", "Surveys applications of AI in diagnostic support, including pattern recognition in medical imaging and clinical decision support."),
            ("AI in Financial Modeling", "Covers applications of AI techniques to credit scoring, fraud detection, and algorithmic trading in finance."),
            ("Robotics Fundamentals and Kinematics", "Introduces robot manipulator kinematics, coordinate frames, and the relationship between joint angles and end-effector position."),
            ("Computer Vision Fundamentals", "Covers the basics of digital image representation, edge detection, and simple feature extraction for visual recognition tasks."),
            ("Speech Recognition Fundamentals", "Introduces the pipeline for converting spoken audio into text, including feature extraction and basic acoustic modeling concepts."),
            ("Human-Robot Interaction", "Examines how robots communicate and collaborate with humans, including safety, trust, and interface design considerations."),
            ("Cognitive Biases in AI Design", "Explores how human cognitive biases can be reflected in or amplified by AI system design and decision-making."),
        ],
        "C2": [
            ("Minimax and Alpha-Beta Pruning Deep Dive", "Provides an in-depth treatment of the minimax algorithm for adversarial games and alpha-beta pruning for reducing search complexity."),
            ("Monte Carlo Tree Search", "Explains the MCTS algorithm that balances exploration and exploitation through random simulations to guide decision-making in large game trees."),
            ("Genetic Algorithms and Evolutionary Computation", "Covers evolutionary search techniques using selection, crossover, and mutation to optimize solutions over successive generations."),
            ("Swarm Intelligence (Ant Colony, Particle Swarm)", "Introduces nature-inspired optimization methods such as ant colony optimization and particle swarm optimization for solving combinatorial problems."),
            ("Arc Consistency and Constraint Propagation", "Explains arc-consistency algorithms like AC-3 that prune inconsistent values from CSP variable domains before or during search."),
            ("First-Order Logic Fundamentals", "Introduces first-order logic syntax including quantifiers, predicates, and functions for representing knowledge more expressively than propositional logic."),
            ("Resolution and Theorem Proving", "Covers resolution-based automated theorem proving, including unification and clause normal form conversion."),
            ("Game Theory Fundamentals for AI", "Introduces strategic-form and extensive-form games, payoff matrices, and dominant strategies as used in multi-agent AI systems."),
            ("Nash Equilibria in Multi-Agent Systems", "Explains Nash equilibrium concepts and how AI agents can compute or approximate equilibria in strategic interactions."),
            ("Multi-Agent Systems Fundamentals", "Covers the design of systems with multiple interacting autonomous agents, including communication and coordination protocols."),
            ("Cooperative and Competitive Agents", "Examines how agents coordinate in cooperative settings or compete in adversarial settings, and the algorithms that support each."),
            ("Image Feature Extraction and Object Detection", "Covers classical and learned feature descriptors and detection pipelines for locating and classifying objects in images."),
            ("Acoustic Modeling for Speech", "Explains how acoustic models map audio features to phonetic units using techniques such as Gaussian mixture and neural network models."),
            ("Sensor Fusion for Autonomous Systems", "Covers combining data from multiple sensors such as lidar, radar, and cameras to build a robust perception of the environment."),
            ("AI in Autonomous Vehicles", "Surveys the perception, planning, and control components of AI systems used in self-driving vehicles."),
            ("Affective Computing", "Introduces systems that recognize, interpret, and simulate human emotions using signals such as facial expression and voice tone."),
            ("AI in Game Playing (AlphaGo-style Systems)", "Examines how deep reinforcement learning combined with tree search enabled superhuman performance in games such as Go and chess."),
            ("Artificial Life and Cellular Automata", "Explores simulated systems like cellular automata that model emergent life-like behavior from simple local rules."),
        ],
        "UG1": [
            ("Knowledge Graphs and Semantic Networks", "Covers representing entities and their relationships as graphs, and how semantic networks support structured knowledge retrieval."),
            ("Ontology Engineering", "Explains the process of designing formal ontologies that define concepts, relationships, and constraints within a domain."),
            ("Description Logics", "Introduces description logics as a formal, decidable fragment of first-order logic used for ontology reasoning."),
            ("Semantic Web Technologies", "Covers standards such as RDF, OWL, and SPARQL that enable machine-readable, linked knowledge representation on the web."),
            ("Answer Set Programming", "Introduces answer set programming as a declarative approach to solving combinatorial search problems via stable model semantics."),
            ("Probabilistic Programming Languages", "Explains how probabilistic programming languages let developers define generative models and perform automated inference."),
            ("Neuro-Symbolic AI", "Covers hybrid approaches that combine neural network learning with symbolic reasoning for improved generalization and interpretability."),
            ("Symbolic vs. Connectionist AI", "Contrasts symbolic AI's rule-based representations with connectionist AI's distributed, learned representations."),
            ("Cognitive Architectures (SOAR, ACT-R)", "Introduces cognitive architectures like SOAR and ACT-R that model human-like reasoning, memory, and learning processes."),
            ("Auction Theory and Resource Allocation", "Covers auction mechanisms such as first-price and Vickrey auctions used by AI agents for allocating scarce resources."),
            ("Distributed Problem Solving", "Explains how tasks can be decomposed and solved cooperatively across multiple distributed agents or processing nodes."),
            ("Mechanism Design Basics", "Introduces mechanism design principles for creating rules that incentivize truthful and efficient agent behavior."),
            ("Constraint Optimization Techniques", "Covers optimizing objective functions subject to constraints, extending CSPs to problems with preferences and costs."),
            ("Natural Language Understanding for AI Agents", "Explains how AI agents parse and interpret natural language instructions to inform their actions."),
            ("Dialogue Management Systems", "Covers the components that track conversation state and decide an agent's next action or utterance in a dialogue."),
            ("Simultaneous Localization and Mapping (SLAM)", "Introduces SLAM algorithms that let a robot build a map of an unknown environment while tracking its own position within it."),
            ("Robot Motion Planning", "Covers algorithms such as rapidly-exploring random trees and configuration-space planning for generating collision-free robot paths."),
            ("Embodied AI and Simulation Environments", "Explores training and evaluating AI agents that act within simulated physical environments to develop embodied skills."),
        ],
        "UG2": [
            ("Markov Decision Processes", "Introduces MDPs as a framework of states, actions, transitions, and rewards for modeling sequential decision-making under uncertainty."),
            ("Value Iteration and Policy Iteration", "Covers dynamic programming algorithms for computing optimal policies in MDPs by iteratively updating value functions."),
            ("Hidden Markov Models", "Introduces HMMs for modeling sequences with hidden states, including the forward-backward and Viterbi algorithms."),
            ("Bayesian Networks Fundamentals", "Explains directed graphical models that represent conditional dependencies among random variables for probabilistic reasoning."),
            ("Bayesian Network Inference Algorithms", "Covers exact and approximate inference methods, such as variable elimination and sampling, for querying Bayesian networks."),
            ("Dynamic Bayesian Networks", "Extends Bayesian networks to model how probabilistic relationships evolve over time in sequential processes."),
            ("Kalman Filters and State Estimation", "Introduces the Kalman filter for estimating the state of a linear dynamic system from noisy sensor measurements."),
            ("Partially Observable MDPs", "Covers POMDPs, which extend MDPs to settings where the agent cannot directly observe the full state and must reason over belief states."),
            ("Planning Under Uncertainty", "Explains planning approaches that account for stochastic outcomes and incomplete information about the world."),
            ("Hierarchical Task Network Planning", "Covers HTN planning, which decomposes complex tasks into simpler subtasks using predefined methods."),
            ("Automated Planning Languages (PDDL)", "Introduces the Planning Domain Definition Language used to formally specify planning problems for automated solvers."),
            ("Temporal and Resource-Constrained Planning", "Covers planning techniques that account for action durations, deadlines, and limited resources."),
            ("Multi-Armed Bandit Problems", "Introduces the multi-armed bandit framework for balancing exploration and exploitation when choosing among uncertain options."),
            ("Exploration vs. Exploitation Strategies", "Covers strategies such as epsilon-greedy and upper confidence bound methods for managing the exploration-exploitation tradeoff."),
            ("Causal Reasoning in AI Systems", "Introduces causal graphical models and interventions that let AI systems reason about cause and effect rather than mere correlation."),
            ("Counterfactual Reasoning", "Explains how AI systems evaluate hypothetical alternative outcomes to support explanation and decision-making."),
            ("AI Planning for Robotics", "Covers integrating task and motion planning to enable robots to achieve high-level goals through sequences of physical actions."),
            ("AI for Scientific Discovery", "Surveys how AI methods assist in hypothesis generation, experiment design, and pattern discovery in scientific research."),
        ],
        "UG3": [
            ("Deep Reinforcement Learning Foundations", "Introduces combining deep neural networks with reinforcement learning to handle high-dimensional state and action spaces."),
            ("Policy Gradient Methods", "Covers algorithms that directly optimize a parameterized policy by following the gradient of expected reward."),
            ("Actor-Critic Architectures", "Explains architectures that combine a policy (actor) with a value function estimator (critic) to reduce variance in policy learning."),
            ("Model-Based Reinforcement Learning", "Covers reinforcement learning approaches that learn a model of environment dynamics to plan or simulate future outcomes."),
            ("Inverse Reinforcement Learning", "Introduces methods for inferring an agent's reward function from observed expert behavior."),
            ("Neural Architecture Search", "Covers automated methods for discovering high-performing neural network architectures using search or optimization algorithms."),
            ("Meta-Learning for AI Systems", "Explains 'learning to learn' approaches that enable models to adapt quickly to new tasks from limited data."),
            ("Continual and Lifelong Learning", "Covers techniques for learning new tasks over time without catastrophically forgetting previously learned knowledge."),
            ("Curriculum Learning Strategies", "Introduces training strategies that present examples in a structured order of increasing difficulty to improve learning efficiency."),
            ("Transformer Architecture Fundamentals", "Explains the encoder-decoder transformer architecture built on self-attention, replacing recurrence for sequence modeling."),
            ("Attention Mechanisms in Neural Networks", "Covers how attention mechanisms let models dynamically weight relevant parts of the input when producing an output."),
            ("Convolutional Neural Networks for Vision", "Introduces convolutional layers, pooling, and feature hierarchies used to process image data efficiently."),
            ("Adversarial Examples and Robustness", "Explores how small, crafted perturbations can fool neural networks, and methods for improving model robustness."),
            ("Emergent Behavior in Complex Systems", "Examines how simple interacting components can produce complex, unpredictable global behavior in multi-agent and learning systems."),
            ("AI Hardware Accelerators (GPUs, TPUs)", "Covers specialized hardware such as GPUs and TPUs that accelerate the matrix computations underlying modern AI models."),
            ("Distributed Training of AI Models", "Explains techniques such as data and model parallelism for training large AI models across multiple machines."),
            ("Energy Efficiency in AI Systems", "Covers the computational and environmental costs of training and deploying large AI models, and techniques to reduce them."),
            ("Program Synthesis", "Introduces methods for automatically generating programs that satisfy given specifications or examples."),
        ],
        "UG4": [
            ("Generative Adversarial Networks", "Explains the GAN framework in which a generator and discriminator are trained adversarially to produce realistic synthetic data."),
            ("Diffusion Models for Generative AI", "Covers generative models that learn to reverse a gradual noising process to synthesize high-quality data such as images."),
            ("Foundation Models and Pretraining", "Introduces large-scale models pretrained on broad data that can be adapted to many downstream tasks."),
            ("Prompt Engineering Fundamentals", "Covers techniques for crafting inputs that effectively elicit desired behavior from large pretrained models."),
            ("Multi-Modal AI Systems", "Explains AI systems that jointly process multiple data modalities such as text, images, and audio."),
            ("Vision-Language Models", "Covers models that learn joint representations of images and text to support tasks like captioning and visual question answering."),
            ("Collaborative Filtering Algorithms", "Introduces recommendation techniques that predict user preferences based on patterns of similarity across many users' behavior."),
            ("AI Agents with Tool Use", "Explains how AI agents can invoke external tools and APIs to extend their capabilities beyond text generation."),
            ("Autonomous Agent Architectures (ReAct, etc.)", "Covers architectures that interleave reasoning and acting, letting agents plan, use tools, and revise their approach."),
            ("AI for Code Generation", "Surveys models trained to generate, complete, and debug source code from natural language or partial code context."),
            ("Automated Machine Learning for AI Pipelines", "Covers automating model selection, feature engineering, and hyperparameter tuning within AI development pipelines."),
            ("Edge AI and On-Device Inference", "Explains techniques for deploying compact AI models to run efficiently on resource-constrained edge devices."),
            ("AI System Deployment Architectures", "Covers architectural patterns for serving AI models reliably at scale, including latency and throughput considerations."),
            ("Standardized AI Benchmarks (ImageNet, GLUE, etc.)", "Surveys widely used benchmark datasets and tasks for evaluating progress in vision and language AI systems."),
            ("Human Evaluation of AI Systems", "Covers methodologies for using human judgment to assess AI system quality where automated metrics fall short."),
            ("Red-Teaming AI Systems", "Explains adversarial testing practices used to proactively uncover failure modes and vulnerabilities in AI systems."),
            ("AI Benchmarking and Evaluation Methodologies", "Covers principles for designing fair, reproducible evaluations that measure AI system capability and limitations."),
            ("Human-AI Collaboration Design", "Explores designing interfaces and workflows where humans and AI systems complement each other's strengths."),
        ],
        "M1": [
            ("AI Alignment Research Foundations", "Introduces the research problem of ensuring AI systems pursue goals that are consistent with human intentions and values."),
            ("Reward Hacking and Specification Gaming", "Examines how AI agents can exploit imperfectly specified reward functions to achieve high reward without the intended behavior."),
            ("AI Safety Engineering Practices", "Covers engineering practices such as testing, monitoring, and fail-safes for building AI systems that behave reliably."),
            ("Value Alignment and Human Feedback (RLHF)", "Explains reinforcement learning from human feedback as a method for aligning model behavior with human preferences."),
            ("Scalable Oversight Techniques", "Covers approaches for supervising AI systems whose behavior may be difficult for humans to directly evaluate."),
            ("Constitutional AI Approaches", "Introduces methods that use a set of guiding principles to shape model behavior with reduced reliance on direct human labeling."),
            ("AI Safety via Interpretability Research", "Explores how understanding a model's internal computations can help identify and mitigate unsafe behaviors."),
            ("Explainable AI (XAI) Fundamentals", "Covers techniques for making AI model decisions understandable and justifiable to human stakeholders."),
            ("Interpretable Model Design", "Explains approaches to building models that are inherently interpretable rather than requiring post-hoc explanation."),
            ("Model Auditing and Bias Detection", "Covers systematic methods for evaluating AI systems for unintended bias, discrimination, or unfair outcomes."),
            ("AGI Concepts and Debates", "Surveys definitions of artificial general intelligence and the ongoing debates about its feasibility and timelines."),
            ("Philosophy of Mind for AI", "Examines philosophical questions about consciousness, understanding, and intentionality as they relate to AI systems."),
            ("Computability and the Limits of AI", "Covers theoretical limits on computation, such as undecidability, and their implications for what AI systems can achieve."),
            ("AI Regulation and Policy Frameworks", "Surveys emerging regulatory approaches and policy frameworks aimed at governing the development and deployment of AI."),
            ("AI Risk Assessment Frameworks", "Introduces structured methods for identifying, categorizing, and mitigating risks posed by AI systems."),
            ("AI in Military and Dual-Use Applications", "Examines the use of AI in defense contexts and the ethical challenges posed by dual-use technologies."),
            ("Algorithmic Accountability", "Covers mechanisms for holding organizations and systems accountable for the decisions made by AI algorithms."),
            ("Frontiers in AI Research", "Surveys current open research directions and unresolved challenges at the frontier of AI research."),
        ],
    },
    "Machine Learning": {
        "C1": [
            ("Naive Bayes Classifiers", "Introduces the Naive Bayes classifier, which applies Bayes' theorem with a conditional independence assumption to classify data efficiently."),
            ("K-Nearest Neighbors Algorithm", "Covers the KNN algorithm, which classifies or predicts values based on the majority label or average of the closest training examples."),
            ("Logistic Regression Deep Dive", "Provides a detailed look at logistic regression for binary classification, including the sigmoid function and maximum likelihood estimation."),
            ("Perceptron and Linear Classifiers", "Introduces the perceptron algorithm and linear decision boundaries as the foundation of many classification methods."),
            ("Decision Tree Algorithms: ID3 and C4.5", "Covers the ID3 and C4.5 algorithms for building decision trees using information gain and gain ratio splitting criteria."),
            ("CART and Regression Trees", "Explains the CART algorithm for building classification and regression trees using Gini impurity or variance reduction."),
            ("Association Rule Mining", "Introduces mining frequent patterns and association rules that describe relationships between items in transactional data."),
            ("Apriori Algorithm", "Covers the Apriori algorithm for efficiently discovering frequent itemsets by pruning candidates that cannot be frequent."),
            ("Market Basket Analysis", "Explains how association rule mining is applied to retail transaction data to uncover items frequently purchased together."),
            ("Time Series Forecasting Fundamentals", "Introduces core concepts of time series data, including trend, seasonality, and the goals of forecasting future values."),
            ("ARIMA and Statistical Forecasting Models", "Covers autoregressive integrated moving average models for forecasting time series based on their own past values."),
            ("Exponential Smoothing Methods", "Explains simple, double, and triple exponential smoothing techniques for forecasting data with trend and seasonal components."),
            ("Cross-Validation Techniques", "Covers k-fold and other cross-validation strategies for estimating how well a model generalizes to unseen data."),
            ("Bias-Variance Tradeoff", "Explains the tradeoff between model bias and variance and its role in underfitting and overfitting."),
            ("Regularization Techniques (L1, L2, Elastic Net)", "Introduces L1, L2, and elastic net regularization for penalizing model complexity and reducing overfitting."),
            ("Recommender Systems: Collaborative Filtering", "Covers collaborative filtering methods that recommend items based on patterns of similarity among users or items."),
            ("Recommender Systems: Content-Based Filtering", "Explains content-based recommendation approaches that match item attributes to a user's historical preferences."),
            ("Matrix Factorization for Recommendations", "Introduces matrix factorization techniques such as singular value decomposition for uncovering latent factors in recommendation data."),
        ],
        "C2": [
            ("Support Vector Machines Fundamentals", "Introduces SVMs, which find the maximum-margin hyperplane separating classes in feature space."),
            ("Kernel Methods and the Kernel Trick", "Explains how the kernel trick allows algorithms like SVMs to operate in high-dimensional feature spaces without explicit transformation."),
            ("Random Forests", "Covers the random forest ensemble method, which aggregates predictions from many decorrelated decision trees."),
            ("Gradient Boosting Fundamentals", "Introduces gradient boosting, which builds an ensemble of weak learners sequentially to correct the errors of previous models."),
            ("XGBoost: Regularized Gradient Boosting", "Covers XGBoost's regularized objective and system optimizations that make gradient boosting fast and accurate at scale."),
            ("LightGBM and Histogram-Based Boosting", "Explains LightGBM's histogram-based split finding and leaf-wise tree growth for efficient gradient boosting."),
            ("CatBoost and Categorical Feature Handling", "Introduces CatBoost's techniques for natively handling categorical features without extensive preprocessing."),
            ("Ensemble Learning: Bagging vs Boosting", "Contrasts bagging, which reduces variance by averaging independent models, with boosting, which reduces bias by combining sequential weak learners."),
            ("Stacking and Blending Models", "Covers meta-learning approaches that combine predictions from multiple base models using a higher-level model."),
            ("Feature Selection Methods", "Introduces techniques for identifying the most relevant input features to improve model performance and interpretability."),
            ("Wrapper vs Filter Feature Selection", "Contrasts filter methods that score features independently of a model with wrapper methods that evaluate feature subsets using model performance."),
            ("Multi-Class Classification Strategies", "Covers approaches such as one-vs-rest and one-vs-one for extending binary classifiers to multi-class problems."),
            ("Multi-Label Classification", "Explains classification settings where each instance can belong to multiple labels simultaneously, and methods to handle them."),
            ("Class Imbalance Evaluation Metrics", "Covers evaluation metrics such as precision, recall, and F1-score that are more informative than accuracy for imbalanced datasets."),
            ("Precision-Recall and ROC Curves", "Explains how precision-recall and ROC curves visualize classifier performance across different decision thresholds."),
            ("Model Calibration Techniques", "Covers methods such as Platt scaling and isotonic regression for aligning predicted probabilities with true outcome frequencies."),
            ("Imbalanced Data Handling Techniques", "Surveys strategies including resampling and algorithmic adjustments for training models on datasets with skewed class distributions."),
            ("SMOTE and Oversampling Methods", "Introduces the Synthetic Minority Oversampling Technique and related methods for generating synthetic examples of minority classes."),
        ],
        "UG1": [
            ("Principal Component Analysis (PCA)", "Explains PCA as a linear dimensionality reduction technique that projects data onto directions of maximum variance."),
            ("t-SNE for Nonlinear Dimensionality Reduction", "Covers t-distributed stochastic neighbor embedding for visualizing high-dimensional data in low-dimensional space while preserving local structure."),
            ("UMAP for Manifold Learning", "Introduces UMAP, a manifold learning technique for dimensionality reduction that preserves both local and global data structure."),
            ("Linear Discriminant Analysis", "Explains LDA as a technique that finds a linear projection maximizing class separability for classification or dimensionality reduction."),
            ("Dimensionality Curse and Its Mitigation", "Covers the challenges that arise as feature dimensionality grows, such as sparsity and distance concentration, and mitigation strategies."),
            ("Cost-Sensitive Learning", "Introduces learning approaches that assign different misclassification costs to different types of errors."),
            ("Multilayer Perceptrons", "Covers the architecture of multilayer perceptrons, including hidden layers and nonlinear activation for learning complex functions."),
            ("Backpropagation Algorithm", "Explains the backpropagation algorithm for computing gradients of the loss with respect to network weights via the chain rule."),
            ("Activation Functions in Neural Networks", "Surveys common activation functions such as ReLU, sigmoid, and tanh and their effect on network training."),
            ("Batch Normalization and Layer Normalization", "Covers normalization techniques that stabilize and accelerate neural network training by normalizing intermediate activations."),
            ("Dropout and Regularization in Deep Learning", "Explains dropout and other regularization techniques used to reduce overfitting in deep neural networks."),
            ("Optimizer Algorithms (Adam, RMSProp)", "Introduces adaptive gradient-based optimizers such as Adam and RMSProp used to train neural networks efficiently."),
            ("Learning Rate Scheduling", "Covers strategies for adjusting the learning rate during training to improve convergence and final model performance."),
            ("Data Augmentation Techniques", "Explains how transforming training examples, such as rotating or cropping images, can improve model generalization."),
            ("Survival Analysis in Machine Learning", "Introduces techniques such as the Kaplan-Meier estimator and Cox proportional hazards model for modeling time-to-event data."),
            ("Gaussian Processes for Regression", "Covers Gaussian processes as a nonparametric Bayesian approach for regression that provides uncertainty estimates."),
            ("Bayesian Linear Regression", "Explains how Bayesian methods place priors over regression coefficients to produce a posterior distribution over predictions."),
            ("Bayesian Machine Learning Fundamentals", "Introduces the Bayesian approach to machine learning, treating model parameters as random variables with prior and posterior distributions."),
        ],
        "UG2": [
            ("DBSCAN and Density-Based Clustering", "Covers DBSCAN, which groups points into clusters based on density connectivity and identifies outliers as noise."),
            ("Hierarchical Clustering Methods", "Explains agglomerative and divisive hierarchical clustering approaches that build nested cluster structures."),
            ("Gaussian Mixture Models", "Introduces Gaussian mixture models, which represent data as a combination of several Gaussian distributions for soft clustering."),
            ("Expectation-Maximization Algorithm", "Covers the EM algorithm for estimating parameters of models with latent variables, such as Gaussian mixtures."),
            ("Clustering Validation Metrics", "Surveys metrics such as silhouette score and Davies-Bouldin index used to evaluate the quality of clustering results."),
            ("Anomaly and Outlier Detection Methods", "Introduces statistical and model-based approaches for identifying data points that deviate significantly from expected patterns."),
            ("Isolation Forests for Anomaly Detection", "Explains the isolation forest algorithm, which detects anomalies by measuring how easily points can be isolated in random trees."),
            ("One-Class SVM for Novelty Detection", "Covers one-class support vector machines used to detect novel or anomalous observations relative to a training distribution."),
            ("Semi-Supervised Learning Techniques", "Introduces methods that leverage both labeled and unlabeled data to improve learning when labels are scarce."),
            ("Label Propagation Algorithms", "Explains graph-based label propagation methods that spread known labels to unlabeled data points through similarity graphs."),
            ("Active Learning Strategies", "Covers approaches where a model selectively queries the most informative unlabeled examples for labeling to improve efficiency."),
            ("Query Strategies for Active Learning", "Surveys specific query strategies such as uncertainty sampling and query-by-committee used in active learning."),
            ("Autoencoders for Representation Learning", "Introduces autoencoders, neural networks trained to reconstruct their input, used for unsupervised representation learning."),
            ("Variational Autoencoders", "Covers variational autoencoders, which learn a probabilistic latent representation enabling generation of new data samples."),
            ("Generative Adversarial Networks for ML", "Explains how GANs use a generator-discriminator framework to learn to produce realistic synthetic data."),
            ("Convolutional Neural Networks Fundamentals", "Introduces convolutional layers, filters, and pooling operations used for processing grid-structured data such as images."),
            ("Recurrent Neural Networks Fundamentals", "Covers recurrent neural networks that maintain hidden state across time steps to process sequential data."),
            ("Long Short-Term Memory Networks", "Explains LSTM networks, which use gating mechanisms to capture long-range dependencies while mitigating vanishing gradients."),
        ],
        "UG3": [
            ("Gated Recurrent Units", "Introduces GRUs as a simplified gating mechanism alternative to LSTMs for modeling sequential data."),
            ("Transfer Learning Fundamentals", "Covers reusing knowledge from a model trained on one task to improve learning performance on a related task."),
            ("Fine-Tuning Pretrained Models", "Explains how pretrained model weights are adapted to a new task by continuing training on task-specific data."),
            ("Transfer Learning in Computer Vision", "Covers using pretrained convolutional networks as feature extractors or starting points for new vision tasks."),
            ("Domain Adaptation Techniques", "Introduces methods for adapting a model trained on a source data distribution to perform well on a different target distribution."),
            ("Self-Supervised Learning Fundamentals", "Explains how models learn useful representations from unlabeled data by solving automatically generated pretext tasks."),
            ("Contrastive Learning Methods", "Covers contrastive learning approaches that train models to pull representations of similar examples together and push dissimilar ones apart."),
            ("Zero-Shot and Few-Shot Learning", "Introduces techniques that enable models to perform new tasks with no or very few labeled examples."),
            ("Meta-Learning Algorithms", "Covers algorithms designed to learn how to learn, enabling rapid adaptation to new tasks from limited data."),
            ("Curriculum Learning in ML", "Explains training strategies that order training examples from easy to hard to improve convergence and generalization."),
            ("Knowledge Distillation", "Covers training a smaller student model to mimic a larger teacher model's outputs to retain performance while reducing size."),
            ("Model Compression and Pruning", "Introduces techniques for removing redundant weights or structures from trained models to reduce their size and computation."),
            ("Quantization for Efficient Inference", "Explains representing model weights and activations with lower numerical precision to speed up inference and reduce memory."),
            ("Explainability for Deep Learning Models", "Surveys techniques for interpreting predictions from deep neural networks, which are otherwise difficult to inspect directly."),
            ("Model Interpretability with SHAP", "Covers SHAP values, which use game-theoretic principles to attribute a prediction's outcome to individual input features."),
            ("Model Interpretability with LIME", "Introduces LIME, which explains individual predictions by fitting a simple interpretable model locally around them."),
            ("Partial Dependence Plots and Feature Importance", "Explains visualization techniques that show how a feature affects model predictions on average across the dataset."),
            ("Multi-Task Learning Fundamentals", "Covers training a single model to perform multiple related tasks simultaneously, sharing representations to improve efficiency."),
        ],
        "UG4": [
            ("Reinforcement Learning Fundamentals for ML", "Introduces the reinforcement learning framework of agents, environments, states, actions, and rewards for sequential decision-making."),
            ("Q-Learning Algorithm", "Covers Q-learning, a model-free reinforcement learning algorithm that learns the value of actions in states through experience."),
            ("Deep Q-Networks", "Explains how deep Q-networks combine Q-learning with neural networks to handle high-dimensional state spaces such as raw pixels."),
            ("Policy Gradient Methods for ML", "Covers methods that directly parameterize and optimize a policy using gradient ascent on expected reward."),
            ("Online Learning Algorithms", "Introduces algorithms that update models incrementally as new data arrives, rather than training on a fixed batch."),
            ("Stochastic Gradient Descent Variants", "Surveys variants of stochastic gradient descent, including momentum and mini-batch approaches, used to train models efficiently."),
            ("Federated Learning Fundamentals", "Covers training models across decentralized devices or servers holding local data samples without exchanging raw data."),
            ("Privacy-Preserving Machine Learning", "Introduces techniques for training and deploying models while protecting the privacy of the underlying training data."),
            ("Differential Privacy in ML", "Explains differential privacy, a formal framework for adding calibrated noise to protect individual data points in model training."),
            ("Adversarial Robustness in ML", "Covers techniques for making models resistant to adversarial perturbations designed to cause misclassification."),
            ("Adversarial Attacks on ML Models", "Surveys methods such as gradient-based perturbations used to craft inputs that deceive machine learning models."),
            ("Fairness Metrics in Machine Learning", "Introduces quantitative metrics for measuring whether a model's predictions are equitable across different demographic groups."),
            ("Algorithmic Bias Mitigation", "Covers techniques applied before, during, or after training to reduce unwanted bias in model predictions."),
            ("Causal Machine Learning Fundamentals", "Introduces methods that combine causal inference principles with machine learning to estimate treatment effects from data."),
            ("Causal Inference: Potential Outcomes Framework", "Explains the potential outcomes framework for defining and estimating causal effects from observational or experimental data."),
            ("Propensity Score Matching", "Covers propensity score methods for balancing covariates between treatment and control groups in observational studies."),
            ("Hyperparameter Tuning Strategies", "Surveys systematic approaches for selecting model hyperparameters to optimize predictive performance."),
            ("Grid Search and Random Search", "Explains grid search and random search as baseline strategies for exploring hyperparameter configurations."),
        ],
        "M1": [
            ("Bayesian Optimization for Hyperparameters", "Covers Bayesian optimization, which models the objective function probabilistically to efficiently search for optimal hyperparameters."),
            ("Automated Machine Learning (AutoML)", "Introduces AutoML systems that automate model selection, feature engineering, and hyperparameter tuning end to end."),
            ("Neural Architecture Search for ML Pipelines", "Covers algorithms that automatically search for high-performing neural network architectures as part of an ML pipeline."),
            ("ML System Design at Scale", "Explains architectural considerations for designing machine learning systems that serve predictions reliably at large scale."),
            ("Distributed Training Strategies for ML", "Covers data parallelism, model parallelism, and other strategies for training large models across multiple compute nodes."),
            ("Model Serving and Inference Optimization", "Introduces techniques for deploying trained models to serve predictions with low latency and high throughput."),
            ("Feature Stores for ML Systems", "Covers feature stores, centralized systems for managing, sharing, and serving features consistently across ML projects."),
            ("Data Versioning for ML Pipelines", "Explains practices for tracking changes to datasets over time to ensure reproducibility of model training."),
            ("Model Monitoring and Drift Detection", "Covers techniques for tracking deployed model performance over time and detecting data or concept drift."),
            ("A/B Testing for ML Model Evaluation", "Introduces using controlled experiments to compare the real-world impact of different model versions."),
            ("Reproducibility in Machine Learning Research", "Covers practices such as fixed seeds, environment tracking, and shared code and data for ensuring ML experiments can be replicated."),
            ("Experiment Tracking and MLOps Tools", "Surveys tools that log experiment parameters, metrics, and artifacts to support systematic model development."),
            ("Continuous Integration for ML Pipelines", "Explains applying continuous integration practices, including automated testing, to machine learning code and pipelines."),
            ("Model Versioning and Rollback Strategies", "Covers managing multiple versions of deployed models and safely rolling back to a previous version when issues arise."),
            ("Edge Deployment of ML Models", "Introduces considerations and techniques for deploying machine learning models on resource-constrained edge devices."),
            ("Real-Time Inference Systems", "Covers designing systems that produce model predictions with minimal latency for time-sensitive applications."),
            ("Large-Scale Distributed Data Processing for ML", "Explains distributed data processing frameworks used to prepare and process large training datasets for machine learning."),
            ("ML Capstone Project Design", "Guides the design of an end-to-end machine learning capstone project, from problem framing through evaluation and deployment."),
        ],
    },
    "Natural Language Processing": {
        "C1": [
            ("Text Normalization Techniques", "Covers standardizing text through case folding, punctuation removal, and other transformations to reduce noise before analysis."),
            ("Stemming vs Lemmatization", "Contrasts stemming, which crudely truncates words, with lemmatization, which reduces words to their proper dictionary base form."),
            ("Regular Expressions for Text Processing", "Introduces regular expressions as a tool for pattern matching and extracting structured information from raw text."),
            ("Spelling Correction Algorithms", "Covers algorithms such as edit-distance-based methods for detecting and correcting misspelled words in text."),
            ("Language Identification", "Explains techniques for automatically determining which natural language a given piece of text is written in."),
            ("Text Similarity Measures", "Surveys measures such as cosine similarity and Jaccard similarity used to quantify how alike two pieces of text are."),
            ("Edit Distance and String Matching", "Introduces edit distance metrics such as Levenshtein distance for measuring the similarity between strings."),
            ("TF-IDF and Vector Space Models", "Covers representing documents as vectors weighted by term frequency and inverse document frequency for information retrieval."),
            ("Bag-of-Words Representations", "Explains the bag-of-words model, which represents text as an unordered collection of word counts, ignoring grammar and order."),
            ("Part-of-Speech Tagging Fundamentals", "Introduces assigning grammatical categories such as noun or verb to each word in a sentence."),
            ("Named Entity Recognition Fundamentals", "Covers identifying and classifying named entities such as people, organizations, and locations within text."),
            ("Text Classification Fundamentals", "Introduces the task of assigning predefined categories to documents based on their textual content."),
            ("Naive Bayes for Text Classification", "Explains applying the Naive Bayes classifier to text categorization tasks such as spam detection."),
            ("Lexicon-Based Sentiment Analysis", "Covers determining sentiment polarity by matching words in text against predefined sentiment lexicons."),
            ("Keyphrase Extraction", "Introduces automatic methods for identifying the most representative words or phrases in a document."),
            ("Text Segmentation Techniques", "Covers dividing continuous text into meaningful units such as sentences, topics, or discourse segments."),
            ("Document Clustering Techniques", "Explains grouping similar documents together based on textual content without predefined labels."),
            ("Query Understanding for Search Engines", "Covers techniques for interpreting user search queries to improve the relevance of retrieved results."),
        ],
        "C2": [
            ("N-Gram Language Models", "Introduces n-gram models, which estimate the probability of a word based on a fixed number of preceding words."),
            ("Perplexity and Language Model Evaluation", "Covers perplexity as a standard metric for evaluating how well a language model predicts held-out text."),
            ("Smoothing Techniques for Language Models", "Explains smoothing methods such as Laplace and Kneser-Ney that handle unseen n-grams in language models."),
            ("Hidden Markov Models for POS Tagging", "Covers using HMMs to model the sequence of part-of-speech tags underlying an observed sequence of words."),
            ("Conditional Random Fields for Sequence Labeling", "Introduces CRFs, discriminative models well suited to sequence labeling tasks like POS tagging and NER."),
            ("Probabilistic Context-Free Grammars", "Covers PCFGs, which extend context-free grammars with probabilities to model syntactic structure and ambiguity."),
            ("Support Vector Machines for Text Classification", "Explains applying SVMs with text features such as TF-IDF vectors to classify documents."),
            ("Topic Modeling with Latent Dirichlet Allocation", "Introduces LDA, a generative probabilistic model that discovers latent topics underlying a collection of documents."),
            ("Latent Semantic Analysis", "Covers LSA, which uses singular value decomposition on term-document matrices to uncover latent semantic structure."),
            ("Non-Negative Matrix Factorization for Topics", "Explains using non-negative matrix factorization as an alternative to LDA for extracting interpretable topics from text."),
            ("Word Sense Disambiguation", "Covers determining which meaning of an ambiguous word is intended based on its surrounding context."),
            ("Semantic Role Labeling", "Introduces identifying the semantic roles, such as agent and patient, that words play with respect to a predicate in a sentence."),
            ("Discourse Analysis and Coherence", "Covers analyzing how sentences relate to one another to form coherent, connected discourse."),
            ("Rhetorical Structure Theory", "Introduces a framework for describing the hierarchical rhetorical relations, such as elaboration and contrast, between text spans."),
            ("Aspect-Based Sentiment Analysis", "Covers identifying sentiment expressed toward specific aspects or attributes of an entity rather than the entity as a whole."),
            ("Emotion Detection in Text", "Explains classifying text according to specific emotions such as joy, anger, or sadness rather than simple polarity."),
            ("Hierarchical Text Classification", "Covers classification tasks where categories are organized in a hierarchy, and predictions must respect that structure."),
            ("Multi-Label Text Classification", "Introduces classification settings where a document may simultaneously belong to multiple non-exclusive categories."),
        ],
        "UG1": [
            ("Constituency Parsing", "Covers parsing sentences into nested phrase-structure trees that represent their hierarchical grammatical constituents."),
            ("Dependency Parsing", "Introduces parsing sentences into trees of binary grammatical relations between head words and their dependents."),
            ("Word2Vec: Skip-Gram and CBOW Models", "Explains the Word2Vec algorithms, which learn dense word vectors by predicting context words or a target word from context."),
            ("GloVe: Global Vectors for Word Representation", "Covers GloVe, which learns word embeddings from global word co-occurrence statistics across a corpus."),
            ("FastText and Subword Embeddings", "Introduces FastText, which represents words as bags of character n-grams to better handle rare and out-of-vocabulary words."),
            ("Contextual Embeddings: ELMo", "Covers ELMo, which produces word representations that vary depending on sentence context using deep bidirectional language models."),
            ("Coreference Resolution Fundamentals", "Introduces identifying all expressions in text that refer to the same real-world entity."),
            ("Mention Detection and Anaphora Resolution", "Covers detecting candidate mentions and resolving anaphoric references such as pronouns to their antecedents."),
            ("Information Extraction Fundamentals", "Introduces automatically extracting structured information, such as facts and relationships, from unstructured text."),
            ("Relation Extraction", "Covers identifying and classifying semantic relationships between entities mentioned in text."),
            ("Event Extraction", "Explains identifying events described in text along with their participants, time, and location."),
            ("Sarcasm and Irony Detection", "Covers computational approaches for detecting sarcastic or ironic intent, which often contradicts literal sentiment."),
            ("Argument Mining", "Introduces identifying argumentative structures in text, including claims, premises, and their relationships."),
            ("Stance Detection", "Covers determining whether a piece of text expresses support, opposition, or neutrality toward a given target or topic."),
            ("Text Mining for Social Media", "Explains techniques adapted to the informal, noisy, and short-form nature of social media text."),
            ("Hashtag and Trend Analysis in NLP", "Covers analyzing hashtags and their usage patterns to identify emerging trends and topics on social platforms."),
            ("Grammatical Error Correction", "Introduces automatically detecting and correcting grammatical mistakes in written text."),
            ("Automatic Text Simplification", "Covers rewriting text to make it easier to read while preserving its original meaning."),
        ],
        "UG2": [
            ("Sequence-to-Sequence Models", "Introduces encoder-decoder models that map an input sequence to an output sequence, such as in translation or summarization."),
            ("Encoder-Decoder Architectures", "Covers the general architecture pairing an encoder that compresses input into a representation with a decoder that generates output."),
            ("Attention Mechanisms in NLP", "Explains how attention lets sequence models focus on relevant parts of the input when generating each output element."),
            ("Self-Attention and Multi-Head Attention", "Covers self-attention, which relates all positions within a sequence to each other, and multi-head attention's parallel attention subspaces."),
            ("Sequence Labeling with BiLSTM-CRF", "Introduces combining bidirectional LSTMs with a CRF output layer for accurate sequence labeling tasks like NER."),
            ("Statistical Machine Translation", "Covers pre-neural machine translation approaches based on statistical alignment models between source and target languages."),
            ("Extractive Text Summarization", "Explains summarization by selecting and concatenating the most important existing sentences from a source document."),
            ("Abstractive Text Summarization", "Covers summarization that generates new sentences paraphrasing the source content rather than copying it verbatim."),
            ("Natural Language Inference", "Introduces the task of determining whether a hypothesis is entailed by, contradicts, or is neutral with respect to a premise."),
            ("Textual Entailment Recognition", "Covers recognizing textual entailment, a foundational task closely related to natural language inference."),
            ("Paraphrase Generation and Detection", "Explains generating alternative phrasings of a sentence and detecting when two sentences express the same meaning."),
            ("Style Transfer in Text", "Covers rewriting text to change its stylistic attributes, such as formality or sentiment, while preserving core content."),
            ("Controllable Text Generation", "Introduces techniques for steering generated text toward desired attributes such as topic, tone, or length."),
            ("Data-to-Text Generation", "Covers generating natural language descriptions automatically from structured data such as tables or records."),
            ("Table-to-Text Generation", "Explains a specific case of data-to-text generation focused on producing coherent text from tabular data."),
            ("Rumor Detection in Social Networks", "Covers identifying unverified or false claims as they propagate through social media networks."),
            ("Hate Speech Detection", "Introduces classifying text as containing hate speech based on target group and severity of language."),
            ("Fact-Checking Systems", "Covers systems that automatically verify claims in text against trusted knowledge sources or evidence."),
        ],
        "UG3": [
            ("BERT: Bidirectional Encoder Representations", "Explains BERT's masked language modeling pretraining objective and bidirectional transformer encoder architecture."),
            ("GPT Architecture and Autoregressive Language Modeling", "Covers the GPT family's decoder-only transformer architecture trained to predict the next token autoregressively."),
            ("Fine-Tuning Pretrained Language Models", "Introduces adapting a pretrained language model to a specific downstream task by continuing training on labeled data."),
            ("Parameter-Efficient Fine-Tuning (LoRA, Adapters)", "Covers techniques such as LoRA and adapter modules that fine-tune large models by updating only a small number of parameters."),
            ("In-Context Learning in Large Language Models", "Explains how large language models can perform new tasks from examples given directly in the prompt without weight updates."),
            ("Instruction Tuning for Language Models", "Covers fine-tuning language models on datasets of instructions and responses to improve their ability to follow user requests."),
            ("Prompt Engineering for Language Models", "Introduces designing effective prompts to elicit accurate and useful responses from large language models."),
            ("Retrieval-Based NLP Systems", "Covers systems that retrieve relevant documents or passages to support downstream NLP tasks such as question answering."),
            ("Dense Passage Retrieval", "Explains retrieval methods that use learned dense vector representations rather than sparse keyword matching to find relevant passages."),
            ("Text Embedding Models for Retrieval", "Covers models trained specifically to produce embeddings optimized for measuring semantic similarity in retrieval tasks."),
            ("Semantic Search Techniques", "Introduces search techniques that match queries and documents based on meaning rather than exact keyword overlap."),
            ("Efficient Transformers for Long Documents", "Covers architectural modifications that let transformer models process long documents more efficiently than standard self-attention allows."),
            ("Transformer-Based Named Entity Recognition", "Explains applying transformer encoder models such as BERT to achieve high-accuracy named entity recognition."),
            ("Cross-Document Coreference Resolution", "Covers resolving references to the same entity across multiple separate documents, extending single-document coreference."),
            ("Interpretability of Language Models", "Introduces methods for understanding what internal representations and mechanisms drive language model predictions."),
            ("Attention Visualization Techniques", "Covers visualizing attention weights within transformer models as one lens for interpreting their behavior."),
            ("Model Distillation for NLP", "Explains training smaller, faster NLP models to approximate the behavior of larger pretrained language models."),
            ("Adversarial Examples in NLP", "Covers crafting inputs that are subtly perturbed to cause NLP models to make incorrect predictions."),
        ],
        "UG4": [
            ("Extractive Question Answering", "Introduces answering questions by identifying and extracting the relevant span of text directly from a source passage."),
            ("Open-Domain Question Answering", "Covers answering questions without a given passage, typically by first retrieving relevant documents from a large corpus."),
            ("Reading Comprehension Models", "Explains models trained and evaluated on the task of answering questions about a given text passage."),
            ("Neural Machine Translation", "Covers translation models trained end to end using neural networks, typically encoder-decoder architectures with attention."),
            ("Evaluation Metrics for Machine Translation (BLEU, METEOR)", "Introduces automated metrics such as BLEU and METEOR used to evaluate translation quality against reference translations."),
            ("Speech Translation Systems", "Covers systems that translate spoken language in one language directly into text or speech in another language."),
            ("Rule-Based Dialogue Systems", "Explains early dialogue system designs that use hand-crafted rules and templates to manage conversation flow."),
            ("Task-Oriented Dialogue Systems", "Covers dialogue systems designed to help users accomplish specific tasks, such as booking a flight, through structured interaction."),
            ("Open-Domain Chatbot Architectures", "Introduces architectures for chatbots designed to engage in open-ended conversation on a wide range of topics."),
            ("Knowledge-Grounded Dialogue Generation", "Covers generating dialogue responses that are grounded in external knowledge sources to improve factual accuracy."),
            ("Persona-Based Dialogue Modeling", "Explains conditioning dialogue generation on a consistent persona to produce more coherent conversational agents."),
            ("Conversational AI Evaluation Methods", "Covers methods, both automated and human, for evaluating the quality and coherence of conversational AI systems."),
            ("Multilingual NLP Fundamentals", "Introduces approaches for building NLP systems and models that work across multiple languages."),
            ("Cross-Lingual Word Embeddings", "Covers learning word embeddings that align vocabularies from different languages into a shared vector space."),
            ("Zero-Shot Cross-Lingual Transfer", "Explains transferring a model trained in one language to perform tasks in another language without additional training data."),
            ("Code-Switching in NLP", "Covers handling text that mixes multiple languages within a single conversation or sentence."),
            ("NLP for Low-Resource Languages", "Introduces techniques for building effective NLP systems for languages with limited annotated data or digital resources."),
            ("Multimodal NLP: Vision and Language", "Covers NLP tasks that jointly reason over both textual and visual information, such as image captioning."),
        ],
        "M1": [
            ("Speech-to-Text Fundamentals", "Introduces the fundamentals of automatic speech recognition, converting spoken audio into written text."),
            ("Acoustic and Language Models for ASR", "Covers the two core components of traditional ASR systems: acoustic models mapping sound to phonemes and language models scoring word sequences."),
            ("End-to-End Speech Recognition Models", "Explains neural architectures that map audio directly to text without separate acoustic, pronunciation, and language model stages."),
            ("Text-to-Speech Synthesis Fundamentals", "Introduces converting written text into natural-sounding synthesized speech."),
            ("Speech Emotion Recognition", "Covers detecting emotional states from vocal characteristics such as pitch, tone, and rhythm in speech."),
            ("Speaker Diarization", "Explains the task of determining who spoke when in an audio recording containing multiple speakers."),
            ("Voice Activity Detection", "Introduces detecting the presence or absence of human speech within an audio signal."),
            ("Bias in NLP Models", "Covers how NLP models can learn and amplify social biases present in their training data."),
            ("Misinformation Detection in Text", "Explains computational approaches for identifying false or misleading claims spread through text-based media."),
            ("Toxic Language Detection", "Covers classifying text as toxic, abusive, or offensive to support content moderation."),
            ("Robustness Testing for NLP Models", "Introduces systematically testing NLP models against distribution shifts, noise, and adversarial inputs."),
            ("Legal NLP Applications", "Covers applying NLP techniques to legal documents for tasks such as contract review and case law analysis."),
            ("Biomedical NLP Applications", "Introduces NLP techniques adapted for biomedical literature, such as extracting drug interactions or gene relationships."),
            ("Clinical Text Mining", "Covers extracting structured, actionable information from unstructured clinical notes and electronic health records."),
            ("Text-Based Recommendation Systems", "Explains recommendation approaches that use natural language content, such as reviews, to inform recommendations."),
            ("Evaluation Metrics for NLG (ROUGE, BLEU)", "Covers automated metrics such as ROUGE and BLEU used to evaluate the quality of natural language generation outputs."),
            ("Human Evaluation of NLP Systems", "Introduces methodologies for using human judges to assess qualities of NLP output, such as fluency and relevance, that automated metrics may miss."),
            ("NLP Capstone Project Design", "Guides the design of an end-to-end NLP capstone project spanning data collection, modeling, and evaluation."),
        ],
    },
    "Data Science": {
        "C1": [
            ("Data Cleaning Techniques for Messy Datasets", "Covers practical techniques for identifying and correcting errors, duplicates, and inconsistencies in raw datasets."),
            ("Handling Missing Data: Imputation Strategies", "Introduces strategies such as mean imputation and model-based imputation for filling in missing values in a dataset."),
            ("Outlier Detection in Data Analysis", "Covers statistical and visual methods for identifying data points that deviate substantially from the rest of the dataset."),
            ("Data Type Conversion and Schema Validation", "Explains ensuring data conforms to expected types and schemas before analysis to prevent downstream errors."),
            ("Data Sampling Techniques", "Introduces methods such as random and stratified sampling for selecting representative subsets of data for analysis."),
            ("Survey Design and Sampling Bias", "Covers principles of designing surveys and recognizing sources of sampling bias that can distort collected data."),
            ("Data Profiling and Summary Statistics", "Introduces computing summary statistics and profiling datasets to understand their structure and quality before analysis."),
            ("Univariate and Bivariate Analysis Techniques", "Covers analyzing single variables and pairs of variables to understand distributions and relationships in data."),
            ("Web Scraping for Data Collection", "Introduces techniques for programmatically extracting data from websites for use in data analysis."),
            ("API Data Integration Techniques", "Covers retrieving and integrating data from external APIs into a data science workflow."),
            ("Jupyter Notebook Best Practices", "Introduces best practices for organizing, documenting, and reproducing analysis within Jupyter notebooks."),
            ("Version Control for Data Science Projects", "Covers using version control systems to track changes to code, data, and analysis artifacts in data science projects."),
            ("Text Data Analysis for Data Science", "Introduces basic techniques for analyzing unstructured text data as part of a broader data science workflow."),
            ("Cohort Analysis Techniques", "Covers grouping users or customers by shared characteristics or start times to analyze behavior over time."),
            ("Customer Segmentation Methods", "Introduces methods for dividing customers into groups with similar characteristics or behaviors for targeted analysis."),
            ("RFM Analysis for Customer Analytics", "Covers segmenting customers based on recency, frequency, and monetary value of their transactions."),
            ("Data-Driven Decision Making Frameworks", "Introduces frameworks for structuring business decisions around data and evidence rather than intuition alone."),
            ("Building Data Science Portfolios", "Covers strategies for assembling projects and case studies that effectively showcase data science skills."),
        ],
        "C2": [
            ("Correlation Analysis and Covariance", "Introduces covariance and correlation coefficients for quantifying the strength and direction of relationships between variables."),
            ("Statistical Distributions for Data Analysis", "Covers common probability distributions such as normal, binomial, and Poisson and their role in modeling data."),
            ("Central Limit Theorem in Practice", "Explains the central limit theorem and its practical implications for statistical inference on sample means."),
            ("Hypothesis Testing Fundamentals", "Introduces the logic of null and alternative hypotheses and using sample data to make statistical decisions."),
            ("Confidence Intervals and p-Values", "Covers constructing confidence intervals and interpreting p-values to quantify uncertainty in statistical estimates."),
            ("Type I and Type II Errors", "Explains the tradeoff between false positive and false negative errors in statistical hypothesis testing."),
            ("Nonparametric Statistical Tests", "Introduces tests such as the Mann-Whitney U and Kruskal-Wallis that do not assume a specific data distribution."),
            ("Resampling Methods (Bootstrap, Jackknife)", "Covers bootstrap and jackknife resampling techniques for estimating the sampling distribution of a statistic."),
            ("Statistical Fallacies and Misinterpretation", "Explains common ways statistical results are misinterpreted, such as confusing correlation with causation."),
            ("Simpson's Paradox in Data Analysis", "Introduces Simpson's paradox, where a trend appears in subgroups of data but reverses when the groups are combined."),
            ("Survivorship Bias in Data Analysis", "Covers how analyzing only surviving or successful cases can lead to systematically misleading conclusions."),
            ("Regression Analysis for Data Science", "Introduces linear regression as a tool for modeling relationships between a dependent variable and one or more predictors."),
            ("Multiple Linear Regression Diagnostics", "Covers diagnostic techniques such as residual analysis and checking for multicollinearity in multiple regression models."),
            ("Logistic Regression for Business Analytics", "Explains applying logistic regression to model binary business outcomes such as customer churn or conversion."),
            ("Model Selection Criteria (AIC, BIC)", "Introduces information criteria such as AIC and BIC used to compare statistical models while penalizing complexity."),
            ("Statistical Process Control", "Covers using statistical methods to monitor and control a process to ensure it operates within expected limits."),
            ("Quality Control Charts", "Introduces control charts such as the Shewhart chart for visually tracking process stability over time."),
            ("Bayesian Statistical Inference", "Explains the Bayesian approach to inference, updating beliefs about parameters using prior distributions and observed data."),
        ],
        "UG1": [
            ("Principles of Effective Chart Design", "Covers principles such as minimizing chartjunk and choosing appropriate scales for creating clear, accurate visualizations."),
            ("Choosing the Right Visualization for Data Types", "Introduces guidelines for matching chart types to the structure and purpose of the underlying data."),
            ("Dashboard Design Principles", "Covers organizing and laying out dashboards so that key metrics are quickly and accurately understood by viewers."),
            ("Interactive Data Visualization Tools", "Introduces tools and libraries that let users explore data dynamically through filtering, zooming, and drill-down."),
            ("SQL Joins and Subqueries", "Covers combining data from multiple tables using SQL joins and nested subqueries for complex queries."),
            ("Window Functions in SQL", "Introduces SQL window functions for performing calculations across sets of rows related to the current row."),
            ("Query Optimization for Analytics", "Covers techniques such as indexing and query restructuring for improving the performance of analytical SQL queries."),
            ("Relational Database Design for Analytics", "Introduces principles of relational schema design, normalization, and keys as they apply to analytical workloads."),
            ("NoSQL Databases for Data Science", "Covers document, key-value, and columnar NoSQL databases and when they are preferable to relational databases."),
            ("Data Storage Formats (Parquet, Avro, ORC)", "Introduces columnar and row-based file formats commonly used for efficiently storing large analytical datasets."),
            ("Columnar vs Row-Based Storage", "Explains the tradeoffs between columnar and row-based storage layouts for different types of analytical queries."),
            ("Data Visualization for Non-Technical Audiences", "Covers adapting visualizations and terminology to effectively communicate insights to non-technical stakeholders."),
            ("Business Intelligence Tool Fundamentals (Tableau, Power BI)", "Introduces core features of business intelligence platforms used to build reports and dashboards from business data."),
            ("KPI Design and Metrics Frameworks", "Covers principles for selecting and defining key performance indicators that meaningfully track business objectives."),
            ("Metric Definition and Semantic Layers", "Introduces semantic layers that provide consistent, shared definitions of business metrics across an organization."),
            ("Funnel Analysis for Product Analytics", "Covers analyzing sequential steps in a user journey to identify where drop-off occurs in a conversion funnel."),
            ("Anomaly Detection in Business Metrics", "Introduces techniques for automatically flagging unusual changes in key business metrics over time."),
            ("Forecasting Model Evaluation Metrics", "Covers metrics such as MAPE and RMSE used to evaluate the accuracy of forecasting models."),
        ],
        "UG2": [
            ("Feature Engineering for Numerical Data", "Covers techniques such as binning, transformation, and scaling for preparing numerical features for modeling."),
            ("Feature Engineering for Categorical Data", "Introduces techniques such as one-hot and target encoding for representing categorical variables in models."),
            ("Feature Scaling and Normalization", "Covers standardizing and normalizing feature ranges so that variables contribute comparably to a model."),
            ("Feature Interaction and Polynomial Features", "Introduces creating interaction and polynomial terms to capture nonlinear relationships between features."),
            ("Apache Spark Fundamentals for Data Science", "Covers the core concepts of Apache Spark, including resilient distributed datasets and DataFrames, for large-scale data processing."),
            ("Hadoop Ecosystem Basics", "Introduces the Hadoop ecosystem, including HDFS and YARN, for distributed storage and processing of large datasets."),
            ("Distributed Data Processing Concepts", "Covers fundamental concepts such as partitioning and parallelism that underlie distributed data processing systems."),
            ("MapReduce Programming Model", "Introduces the MapReduce paradigm for processing large datasets in parallel across a cluster of machines."),
            ("In-Memory Computing for Analytics", "Covers how in-memory computing frameworks speed up analytical workloads compared to disk-based processing."),
            ("Cloud Computing for Data Science (AWS, GCP, Azure)", "Introduces cloud platform services commonly used for data storage, processing, and machine learning workflows."),
            ("Data Mesh Architecture Concepts", "Covers the data mesh paradigm, which decentralizes data ownership to domain teams rather than a central data platform."),
            ("Self-Service Analytics Platforms", "Introduces platforms that let business users perform their own data analysis without deep technical expertise."),
            ("Churn Prediction Modeling", "Covers building predictive models to identify customers likely to stop using a product or service."),
            ("Network Analysis for Data Science", "Introduces representing and analyzing relationships between entities as networks or graphs."),
            ("Graph-Based Data Analysis", "Covers analytical techniques such as centrality and community detection applied to graph-structured data."),
            ("Geospatial Data Analysis Fundamentals", "Introduces core concepts for analyzing data with location or spatial attributes."),
            ("Coordinate Reference Systems and Projections", "Covers how coordinate reference systems and map projections represent locations on the earth's surface."),
            ("Geographic Information Systems (GIS) Basics", "Introduces GIS tools and concepts for storing, analyzing, and visualizing spatial data."),
        ],
        "UG3": [
            ("A/B Testing Design Principles", "Covers principles for designing valid A/B tests, including randomization, sample size, and avoiding confounds."),
            ("Statistical Power Analysis for Experiments", "Introduces power analysis for determining the sample size needed to reliably detect an effect in an experiment."),
            ("Multivariate Testing Methods", "Covers testing multiple variables simultaneously to understand their individual and combined effects on an outcome."),
            ("Sequential Testing in Experimentation", "Introduces methods for continuously monitoring experiment results while controlling the risk of false positives."),
            ("Time Series Decomposition", "Covers decomposing a time series into trend, seasonal, and residual components for analysis."),
            ("Stationarity and Differencing in Time Series", "Introduces the concept of stationarity and using differencing to stabilize a time series' statistical properties."),
            ("Autocorrelation and Partial Autocorrelation", "Covers using autocorrelation and partial autocorrelation functions to identify structure in time series data."),
            ("Seasonal Forecasting Models", "Introduces forecasting models that explicitly account for repeating seasonal patterns in data."),
            ("Causal Inference Fundamentals for Data Science", "Covers foundational concepts for estimating causal effects from data, distinguishing correlation from causation."),
            ("Difference-in-Differences Analysis", "Introduces the difference-in-differences method for estimating causal effects using pre- and post-treatment comparisons."),
            ("Instrumental Variables", "Covers using instrumental variables to estimate causal effects when treatment assignment is confounded."),
            ("Regression Discontinuity Design", "Introduces the regression discontinuity design for estimating causal effects near a treatment assignment threshold."),
            ("Experimental Design for Observational Data", "Covers quasi-experimental techniques for approximating controlled experiments using observational data."),
            ("Longitudinal Data Analysis", "Introduces methods for analyzing data collected repeatedly from the same subjects over time."),
            ("Panel Data Methods", "Covers statistical models such as fixed and random effects for analyzing panel data with both cross-sectional and time dimensions."),
            ("Multiple Comparisons Problem", "Explains how testing many hypotheses simultaneously increases the risk of false positives and how to control for it."),
            ("False Discovery Rate Control", "Introduces methods such as the Benjamini-Hochberg procedure for controlling the false discovery rate in multiple testing."),
            ("Spatial Joins and Geoprocessing", "Covers combining and analyzing spatial datasets using operations such as spatial joins and buffering."),
        ],
        "UG4": [
            ("Data Storytelling Techniques for Executives", "Covers tailoring data narratives and visualizations to effectively inform executive decision-making."),
            ("Narrative Structures for Data Presentations", "Introduces structuring a data presentation with a clear beginning, insight, and call to action."),
            ("Communicating Uncertainty in Data Analysis", "Covers techniques for clearly conveying the confidence and limitations of data-driven conclusions to an audience."),
            ("Data Privacy Regulations (GDPR, CCPA)", "Introduces major data privacy regulations and their implications for how organizations collect and use personal data."),
            ("Anonymization and Pseudonymization Techniques", "Covers techniques for removing or masking identifying information from datasets to protect individual privacy."),
            ("Ethical Considerations in Data Collection", "Introduces ethical principles such as informed consent and minimizing harm in the collection of data."),
            ("Bias in Data Sampling", "Covers how non-representative sampling can introduce systematic bias into data science analyses."),
            ("Data Ethics in Machine Learning Applications", "Introduces ethical considerations specific to applying machine learning models in real-world decision-making."),
            ("Data Anonymization for Public Datasets", "Covers techniques for preparing datasets for public release while minimizing the risk of re-identification."),
            ("Data Governance Frameworks", "Introduces frameworks for establishing policies and standards that govern how data is managed across an organization."),
            ("Data Cataloging and Metadata Management", "Covers organizing metadata about datasets to make them discoverable and understandable across an organization."),
            ("Data Lineage Tracking", "Introduces tracking the origin and transformations of data as it flows through pipelines and systems."),
            ("Master Data Management", "Covers establishing a single, consistent source of truth for core business entities across systems."),
            ("Cross-Functional Collaboration in Data Teams", "Introduces practices for effective collaboration between data scientists, engineers, and business stakeholders."),
            ("Data Science Team Structures and Roles", "Covers common organizational structures and role definitions within data science teams."),
            ("Data Product Development Lifecycle", "Introduces the stages of developing a data product, from ideation through deployment and maintenance."),
            ("Data Science Project Management", "Covers project management practices adapted to the iterative, exploratory nature of data science work."),
            ("Reproducible Research Practices", "Introduces practices such as documented pipelines and environment management that make data science research reproducible."),
        ],
        "M1": [
            ("MLOps Fundamentals for Data Teams", "Introduces MLOps practices that bring engineering discipline to deploying and maintaining machine learning models."),
            ("Model Deployment Pipelines for Data Science", "Covers building automated pipelines that move a trained model from development into production."),
            ("Continuous Integration for Data Science Projects", "Introduces applying continuous integration practices to test and validate data science code and pipelines."),
            ("Model Monitoring in Production", "Covers tracking deployed model performance and data quality to detect degradation over time."),
            ("Data Pipeline Architecture", "Introduces the design of data pipelines that move and transform data reliably from source to destination."),
            ("ETL vs ELT Processes", "Covers the distinction between extract-transform-load and extract-load-transform approaches to data integration."),
            ("Workflow Orchestration Tools (Airflow)", "Introduces workflow orchestration tools used to schedule, monitor, and manage dependencies between data pipeline tasks."),
            ("Data Quality Monitoring in Pipelines", "Covers techniques for continuously validating data quality as it moves through a pipeline."),
            ("Data Warehousing Concepts and Star Schema", "Introduces data warehouse design concepts, including the star schema for organizing facts and dimensions."),
            ("Data Lakes vs Data Warehouses", "Covers the differences between data lakes and data warehouses and when each is appropriate for storing analytical data."),
            ("Dimensional Modeling for Analytics", "Introduces dimensional modeling techniques for structuring data warehouses to support efficient analytical queries."),
            ("Slowly Changing Dimensions", "Covers techniques for handling dimension attributes that change over time within a data warehouse."),
            ("Real-Time Data Streaming Fundamentals", "Introduces the concepts and architecture of processing data continuously as it is generated rather than in batches."),
            ("Apache Kafka for Data Engineering", "Covers Apache Kafka's publish-subscribe model for building scalable, real-time data streaming pipelines."),
            ("Stream Processing Architectures", "Introduces architectures for processing unbounded streams of data with low latency, such as Spark Streaming or Flink."),
            ("Event-Driven Data Systems", "Covers designing systems that react to and process discrete events as they occur across an organization."),
            ("Data Science Capstone Project Design", "Guides the design of a capstone project that integrates data collection, analysis, modeling, and communication."),
            ("Advanced Capstone: End-to-End Data Science Pipeline", "Guides building a complete, production-style data science pipeline from raw data ingestion through deployed insights."),
        ],
    },
}
