"""Additional college-level topics (title, summary) for expanding C1 and C2
lesson counts to a minimum of 60 lessons per subject per level.

Each subject already has 20 introductory lessons at C1 and 20 at C2. This
module supplies 40 further NEW topics per level per subject (no overlap with
the existing 20/level or with each other), covering additional real,
college-appropriate sub-areas of the subject. A merge script builds full
lesson objects from these (title, summary) pairs.
"""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "AI Tools": {
        "C1": [
            ("AI Coding Assistants: An Introduction", "Introduces tools like GitHub Copilot that suggest code completions and explains how they fit into everyday programming workflows."),
            ("Introduction to AI Website Builders", "Covers no-code platforms that use AI to generate website layouts, copy, and images from simple text prompts."),
            ("Introduction to AI Resume and Cover Letter Tools", "Explains how AI resume builders tailor wording, keywords, and formatting to match specific job postings."),
            ("Introduction to Text-to-Speech AI Tools", "Introduces tools that convert written text into natural-sounding spoken audio for narration and accessibility."),
            ("Introduction to AI Video Captioning Tools", "Covers tools that automatically generate captions and subtitles for video content from spoken audio."),
            ("Introduction to AI Music Generation Tools", "Introduces tools that compose original background music and melodies from text prompts or mood descriptions."),
            ("Introduction to AI 3D Model Generators", "Covers tools that generate simple three-dimensional models from text descriptions or reference images."),
            ("Introduction to Browser-Based AI Extensions", "Explains how AI browser extensions summarize web pages, answer questions, and assist users while browsing."),
            ("Introduction to AI Research and Citation Assistants", "Covers tools that help students find, summarize, and properly cite academic sources."),
            ("Introduction to AI Meal Planning Tools", "Covers apps that use AI to generate recipes and weekly meal plans from available ingredients and dietary needs."),
            ("Introduction to AI Legal Document Assistants", "Covers tools that help draft and review basic legal documents such as contracts and non-disclosure agreements."),
            ("Introduction to AI Sales and Lead Generation Tools", "Explains how AI tools identify sales prospects and draft personalized outreach messages."),
            ("Introduction to AI Accessibility Tools", "Covers AI-powered tools such as live captioning and screen-reading aids that improve digital accessibility."),
            ("Introduction to AI Language Learning Apps", "Covers how AI-driven apps personalize vocabulary practice and give feedback on pronunciation."),
            ("Introduction to AI Design Mockup Tools", "Covers tools that turn rough sketches or text prompts into user interface mockups."),
            ("Introduction to AI-Powered Task and Project Trackers", "Covers project management tools that use AI to prioritize tasks and predict deadlines."),
            ("Introduction to AI Photo Editing Tools", "Covers AI-powered background removal, retouching, and object-removal features in modern photo editors."),
            ("Introduction to AI Avatar and Talking-Head Generators", "Covers tools that animate a still photo or generated avatar into a talking video from a script."),
            ("Introduction to AI Handwriting and OCR Tools", "Covers optical character recognition tools that convert handwritten or printed text into digital text."),
            ("Introduction to AI Data Visualization Assistants", "Covers tools that automatically suggest charts and visual summaries from raw spreadsheet data."),
            ("Introduction to AI-Powered Spam and Phishing Filters", "Covers how AI models classify and filter unwanted or malicious email messages."),
            ("Introduction to AI Personal Finance and Budgeting Tools", "Covers apps that use AI to categorize spending, detect trends, and suggest personal budgets."),
            ("Introduction to AI Fitness and Health Coaching Apps", "Covers apps that use AI to generate personalized workout and wellness plans."),
            ("Introduction to AI Travel Planning Tools", "Covers tools that use AI to build itineraries and compare flight, hotel, and activity options."),
            ("Introduction to AI-Assisted Note Organization", "Covers 'second brain' tools that use AI to link, tag, and retrieve personal notes automatically."),
            ("Introduction to AI Podcast Show-Notes Generators", "Covers tools that automatically generate summaries, chapters, and show notes from podcast audio."),
            ("Introduction to AI-Powered Survey and Feedback Analysis", "Covers tools that use AI to summarize themes and sentiment in open-ended survey responses."),
            ("Introduction to AI Interview Preparation Tools", "Covers tools that simulate job interviews and give AI-generated feedback on answers."),
            ("Introduction to AI Tools for Event Planning", "Covers tools that use AI to suggest venues, schedules, and logistics for events."),
            ("Introduction to AI Comparison and Benchmark Sites", "Covers websites and leaderboards that rank and compare AI tools by features, price, and performance."),
            ("Introduction to Custom GPTs and No-Code AI Agents", "Introduces platforms that let users build a customized chatbot or assistant without writing code."),
            ("Introduction to AI Tools for Flashcards and Spaced Repetition", "Covers tools that use AI to auto-generate flashcards and quiz questions from study material."),
            ("Introduction to AI Tools for Presentation Speaker Coaching", "Covers tools that give AI feedback on pacing, filler words, and delivery during a practice talk."),
            ("Introduction to AI Screen Recording and Tutorial Tools", "Covers tools that use AI to auto-generate step-by-step written tutorials from a screen recording."),
            ("Introduction to AI Tools for Job Search Matching", "Covers platforms that use AI to match resumes with relevant job postings and flag skill gaps."),
            ("Introduction to AI Tools for Smart Home Automation", "Covers how AI assistants interpret voice commands and routines to control connected smart home devices."),
            ("Introduction to Choosing the Right AI Tool for a Task", "Provides a framework for evaluating cost, privacy, and accuracy when selecting among competing AI tools."),
            ("Introduction to AI Tools for Image Upscaling and Restoration", "Covers tools that use AI to enlarge, sharpen, and repair damaged or low-resolution images."),
            ("Introduction to AI Video Dubbing and Localization Tools", "Covers tools that translate and re-voice video content into another language while preserving timing."),
            ("Introduction to AI Tools for Basic Web Scraping and Data Collection", "Covers no-code AI tools that extract structured data from websites for simple research tasks."),
        ],
        "C2": [
            ("Retrieval-Augmented Generation (RAG) Tools for Enterprises", "Covers platforms that combine a language model with a company's own documents to produce grounded, sourced answers."),
            ("Vector Databases and Semantic Search Tools", "Explains how vector databases store embeddings and power semantic search across large document collections."),
            ("Building Custom AI Agents with Tool Use", "Covers platforms for building AI agents that can call external tools, APIs, and functions to complete multi-step tasks."),
            ("Multi-Agent AI Orchestration Platforms", "Introduces frameworks that coordinate multiple specialized AI agents working together on a shared goal."),
            ("No-Code AI Model Fine-Tuning Platforms", "Covers services that let users fine-tune a language model on custom data without writing training code."),
            ("Evaluating AI Tools with Benchmarks and Leaderboards", "Explains how to interpret standardized benchmarks and leaderboards when comparing AI tool performance."),
            ("AI API Cost Management and Rate Limiting", "Covers strategies for monitoring, budgeting, and controlling costs when integrating AI APIs into a product."),
            ("Prompt Chaining and Workflow Automation Platforms", "Covers tools that link multiple AI prompts and actions into automated multi-step workflows."),
            ("AI Tools for Automated Code Review and Refactoring", "Covers tools that use AI to flag bugs, suggest refactors, and enforce style in a codebase."),
            ("AI Tools for Test Generation and QA Automation", "Covers tools that use AI to generate unit tests and automate quality-assurance checks."),
            ("AI-Powered Business Intelligence Copilots", "Covers assistants embedded in BI platforms that let users query data and get insights in natural language."),
            ("AI Tools for Contract Analytics at Scale", "Covers enterprise platforms that use AI to extract clauses, risks, and obligations from large volumes of contracts."),
            ("AI Tools for Clinical Documentation", "Covers AI medical scribe tools that draft clinical notes from doctor-patient conversations."),
            ("AI Tools for Financial Forecasting and Modeling", "Covers platforms that use AI to build and stress-test financial forecasts from historical data."),
            ("AI Tools for Automated Market Research", "Covers platforms that use AI to synthesize competitor, consumer, and trend data into research reports."),
            ("AI Governance and Model Risk Management Tools", "Covers platforms organizations use to track, audit, and manage risk across deployed AI systems."),
            ("AI Tools for Synthetic Data Generation", "Covers tools that generate artificial datasets to train or test models when real data is scarce or sensitive."),
            ("AI Tools for Data Labeling and Annotation", "Covers platforms that combine AI pre-labeling with human review to prepare training datasets."),
            ("AI-Assisted Localization and Translation Management", "Covers enterprise systems that use AI to manage large-scale, multi-language content translation."),
            ("AI Tools for Automated Video Production Pipelines", "Covers platforms that chain AI scripting, voice, and editing tools into an end-to-end video production pipeline."),
            ("AI Tools for Real-Time Voice Cloning", "Covers the capabilities, use cases, and ethical safeguards of tools that clone a speaker's voice in real time."),
            ("Generative AI in Game Asset Pipelines", "Covers how studios use generative AI tools to prototype textures, characters, and 3D assets."),
            ("AI Copilot Integration in Enterprise Software Suites", "Covers how AI copilots are embedded into office and enterprise software to assist with everyday tasks."),
            ("AI Tools for Automated SEO Content Auditing", "Covers tools that use AI to audit website content for search-engine optimization gaps and opportunities."),
            ("Prompt Injection Risks in Deployed AI Tools", "Explains how malicious inputs can hijack an AI tool's behavior and surveys mitigation strategies."),
            ("AI Tool Security and Data Governance for Organizations", "Covers policies and controls organizations use to manage data privacy and security when adopting AI tools."),
            ("A/B Testing Prompts and Model Configurations", "Covers methods for systematically comparing prompt variants and model settings to improve AI tool output."),
            ("Building Retrieval Pipelines with Embedding Search", "Covers the technical steps of chunking, embedding, and indexing documents for retrieval-based AI applications."),
            ("AI Tools for Knowledge Base and Documentation Generation", "Covers tools that automatically generate and maintain internal documentation from code and conversations."),
            ("AI Tools for Customer Sentiment Analysis at Scale", "Covers platforms that use AI to analyze sentiment and emerging themes across large volumes of customer feedback."),
            ("AI-Powered Design Systems and Component Generation", "Covers tools that generate reusable interface components consistent with a defined design system."),
            ("AI Tools for Automated Accessibility Auditing", "Covers tools that scan digital products with AI to detect and suggest fixes for accessibility barriers."),
            ("AI Tools for Supply Chain Demand Forecasting", "Covers platforms that apply AI forecasting models to optimize inventory and supply chain decisions."),
            ("AI Tools for Resume Screening and Bias Auditing", "Covers how AI screening tools rank candidates and the auditing methods used to detect and reduce bias."),
            ("AI Tools for Automated Action-Item Extraction", "Covers tools that parse meeting transcripts with AI to extract decisions, owners, and action items."),
            ("Build-versus-Buy Analysis for AI Tool Adoption", "Covers the framework organizations use to decide between building custom AI tooling or buying existing platforms."),
            ("AI Tools for Voice-Based Application Interfaces", "Covers platforms for designing and deploying voice-driven interfaces powered by AI speech models."),
            ("AI Tools for Automated Literature Reviews", "Covers research platforms that use AI to search, cluster, and summarize academic literature on a topic."),
            ("AI Tools for Regulatory Compliance Monitoring", "Covers platforms that use AI to monitor communications and processes for regulatory compliance risks."),
            ("Enterprise Rollout Strategy for AI Tool Adoption", "Covers the change-management steps organizations use to pilot, train for, and scale AI tool adoption."),
        ],
    },
}
