"""Module topics bringing Chemistry, Biology, Critical Thinking, and ICT
& Computer Science up to 20+ lessons per level (C1 through M1)."""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Chemistry": {
        "C1": [
            ("Atomic Structure: Protons, Neutrons, and Electrons", "Introduces the subatomic particles that make up atoms, their charges and locations, and how atomic number and mass number are determined."),
            ("The Periodic Table: Groups, Periods, and Trends", "Explains how elements are organized by atomic number and explores periodic trends in atomic radius, ionization energy, and electronegativity."),
            ("Electron Configuration and Orbital Diagrams", "Covers the Aufbau principle, Pauli exclusion principle, and Hund's rule used to distribute electrons among orbitals."),
            ("Ionic Bonding and Lattice Structures", "Describes how electron transfer between metals and nonmetals forms ions and how oppositely charged ions pack into crystal lattices."),
            ("Covalent Bonding and Lewis Structures", "Introduces electron sharing between atoms and teaches students to draw Lewis structures to represent bonding and lone pairs."),
            ("Molecular Shapes: An Introduction to VSEPR Theory", "Uses valence shell electron pair repulsion theory to predict three-dimensional molecular geometries from Lewis structures."),
            ("The Mole Concept and Avogadro's Number", "Establishes the mole as the chemist's counting unit and shows how to convert between mass, moles, and number of particles."),
            ("Balancing Chemical Equations", "Teaches the conservation of mass principle and systematic methods for balancing coefficients in chemical equations."),
            ("Types of Chemical Reactions", "Classifies reactions into synthesis, decomposition, single replacement, double replacement, and combustion categories with examples."),
            ("States of Matter and Phase Changes", "Examines the particle-level differences between solids, liquids, and gases and the energy changes involved in phase transitions."),
            ("Gas Laws: Boyle's, Charles's, and the Ideal Gas Law", "Derives and applies the relationships between pressure, volume, temperature, and moles of gas, culminating in PV = nRT."),
            ("Solutions, Concentration, and Molarity", "Covers how solutions form and how to calculate concentration using molarity, dilution, and percent composition."),
            ("Introduction to Acids and Bases", "Introduces Arrhenius and Bronsted-Lowry definitions of acids and bases along with the pH scale."),
            ("Introduction to Redox Reactions", "Explains oxidation and reduction in terms of electron transfer and changes in oxidation number."),
            ("Energy Changes in Chemical Reactions", "Distinguishes exothermic and endothermic reactions and introduces simple enthalpy diagrams."),
            ("Reaction Rates: Factors Affecting Speed", "Explores how concentration, temperature, surface area, and catalysts influence how quickly reactions proceed."),
            ("Introduction to Organic Chemistry: Hydrocarbons", "Introduces alkanes, alkenes, and alkynes, along with their structures, naming, and basic reactivity."),
            ("Laboratory Safety and Measurement Techniques", "Covers proper handling of chemicals, use of laboratory equipment, and accurate measurement with significant figures."),
        ],
        "C2": [
            ("Molecular Orbital Theory: Bonding and Antibonding Orbitals", "Introduces molecular orbital theory as an alternative to valence bond theory, explaining bond order through bonding and antibonding orbitals."),
            ("Hybridization of Atomic Orbitals (sp, sp2, sp3)", "Explains how atomic orbitals mix to form hybrid orbitals that account for observed molecular geometries."),
            ("Intermolecular Forces and Their Effects on Properties", "Compares dispersion forces, dipole-dipole interactions, and hydrogen bonding and relates them to boiling point and solubility."),
            ("Thermochemistry: Enthalpy and Hess's Law", "Covers enthalpy of reaction and shows how Hess's law allows enthalpies to be combined for multi-step reactions."),
            ("Calorimetry and Heat Capacity", "Explains how calorimetry experiments measure heat flow and how specific heat capacity is used in energy calculations."),
            ("Chemical Kinetics: Rate Laws and Reaction Order", "Introduces experimentally determined rate laws and how reaction order is found from concentration-time data."),
            ("Reaction Mechanisms and the Rate-Determining Step", "Explains how a multi-step reaction mechanism relates to the observed rate law through its slowest, rate-determining step."),
            ("Catalysis and Activation Energy", "Describes how catalysts speed up reactions by providing an alternative pathway with lower activation energy."),
            ("Chemical Equilibrium: Le Chatelier's Principle", "Covers dynamic equilibrium and predicts how systems respond to changes in concentration, pressure, or temperature."),
            ("The Equilibrium Constant (Kc and Kp)", "Teaches how to write and calculate equilibrium constant expressions in terms of concentrations and partial pressures."),
            ("Acid-Base Equilibria: pH and pOH Calculations", "Applies equilibrium concepts to weak acid and base dissociation, including Ka, Kb, and pH calculations."),
            ("Buffer Solutions and the Henderson-Hasselbalch Equation", "Explains how buffers resist pH change and uses the Henderson-Hasselbalch equation to calculate buffer pH."),
            ("Solubility Equilibria and Ksp", "Covers the solubility product constant and its use in predicting precipitation and dissolution of ionic compounds."),
            ("Entropy and the Second Law of Thermodynamics", "Introduces entropy as a measure of disorder and explains how the second law governs the direction of spontaneous change."),
            ("Gibbs Free Energy and Spontaneity", "Combines enthalpy and entropy into Gibbs free energy to predict whether a reaction is spontaneous at a given temperature."),
            ("Electrochemistry: Galvanic Cells and Cell Potential", "Introduces galvanic cells, standard reduction potentials, and how cell potential is calculated from half-reactions."),
            ("Functional Groups in Organic Chemistry", "Surveys common functional groups, such as alcohols, aldehydes, ketones, and carboxylic acids, and their characteristic reactivity."),
            ("Naming Organic Compounds: IUPAC Nomenclature", "Teaches systematic IUPAC rules for naming organic compounds based on their carbon chain and substituents."),
        ],
        "UG1": [
            ("Advanced VSEPR Theory and Molecular Polarity", "Extends VSEPR theory to more complex molecules and shows how molecular geometry determines overall polarity."),
            ("Crystal Field Theory and Coordination Compounds", "Introduces coordination compounds and uses crystal field theory to explain their color and magnetic properties."),
            ("Stereochemistry: Chirality and Enantiomers", "Explains chirality, stereocenters, and how enantiomers differ in their interaction with polarized light and biological systems."),
            ("Stereochemistry: R/S and E/Z Nomenclature", "Teaches the Cahn-Ingold-Prelog rules for assigning R/S configuration to stereocenters and E/Z configuration to alkenes."),
            ("Nucleophilic Substitution Reactions (SN1 and SN2)", "Compares the mechanisms, kinetics, and stereochemical outcomes of SN1 and SN2 nucleophilic substitution reactions."),
            ("Elimination Reactions (E1 and E2)", "Examines E1 and E2 elimination mechanisms and the factors that determine whether substitution or elimination dominates."),
            ("Addition Reactions of Alkenes and Alkynes", "Covers electrophilic addition mechanisms for alkenes and alkynes, including hydrohalogenation and hydration."),
            ("Aromaticity and Electrophilic Aromatic Substitution", "Defines aromaticity using Huckel's rule and explains the mechanism of electrophilic aromatic substitution on benzene rings."),
            ("Introduction to Infrared (IR) Spectroscopy", "Explains how IR spectroscopy detects characteristic bond vibrations and is used to identify functional groups."),
            ("Introduction to Nuclear Magnetic Resonance (NMR) Spectroscopy", "Introduces how NMR spectroscopy uses nuclear spin behavior in a magnetic field to reveal molecular structure."),
            ("Introduction to Mass Spectrometry", "Describes how mass spectrometry ionizes and fragments molecules to determine molecular mass and structural clues."),
            ("Electrolytic Cells and Faraday's Laws", "Contrasts electrolytic cells with galvanic cells and applies Faraday's laws to calculate quantities produced during electrolysis."),
            ("Corrosion Chemistry and Prevention", "Explains the electrochemical basis of metal corrosion and surveys common prevention methods such as galvanization."),
            ("Colligative Properties of Solutions", "Covers boiling point elevation, freezing point depression, and osmotic pressure as properties that depend on solute concentration."),
            ("Chemical Kinetics: Complex Reaction Mechanisms", "Analyzes multi-step reaction mechanisms involving intermediates and applies the steady-state approximation."),
            ("Enzyme Kinetics: Michaelis-Menten Model", "Introduces the Michaelis-Menten model of enzyme-catalyzed reactions and the meaning of Km and Vmax."),
            ("Introduction to Analytical Chemistry: Titration Methods", "Covers acid-base, redox, and precipitation titrations as quantitative methods for determining unknown concentrations."),
            ("Volumetric and Gravimetric Analysis", "Explains volumetric and gravimetric analytical techniques for precisely quantifying substances in a sample."),
        ],
        "UG2": [
            ("Amino Acids, Peptides, and Protein Structure", "Covers amino acid structure, peptide bond formation, and the primary, secondary, tertiary, and quaternary levels of protein structure."),
            ("Protein Folding and Denaturation", "Explains the forces that drive protein folding into a functional shape and the conditions that cause denaturation."),
            ("Enzyme Inhibition and Regulation", "Covers competitive, noncompetitive, and allosteric enzyme inhibition and how cells regulate enzyme activity."),
            ("Carbohydrate Structure and Function", "Surveys monosaccharide, disaccharide, and polysaccharide structures and their roles in energy storage and structural support."),
            ("Lipid Structure and Membrane Chemistry", "Examines the structure of fatty acids, phospholipids, and cholesterol and their role in forming biological membranes."),
            ("Nucleic Acid Chemistry: DNA and RNA Structure", "Covers the chemical composition and structure of nucleotides and how they polymerize into DNA and RNA."),
            ("Atmospheric Chemistry and Air Pollution", "Examines the chemical reactions behind smog, ozone depletion, and acid rain, and their environmental impact."),
            ("Water Chemistry and Wastewater Treatment", "Covers the chemistry of water quality parameters and the chemical processes used in treating drinking water and wastewater."),
            ("Green Chemistry: The Twelve Principles", "Introduces the twelve principles of green chemistry as a framework for designing safer, more sustainable chemical processes."),
            ("The Haber Process and Industrial Ammonia Synthesis", "Explains the industrial synthesis of ammonia from nitrogen and hydrogen and how equilibrium principles guide its operating conditions."),
            ("The Contact Process and Sulfuric Acid Production", "Covers the catalytic Contact process used to manufacture sulfuric acid, one of the highest-volume industrial chemicals."),
            ("Petrochemical Refining and Cracking", "Explains how crude oil is separated by fractional distillation and how cracking converts heavy fractions into lighter, more useful products."),
            ("Polymer Chemistry: Addition Polymerization", "Covers how addition polymers such as polyethylene form through chain-growth reactions of unsaturated monomers."),
            ("Polymer Chemistry: Condensation Polymerization", "Explains how condensation polymers such as nylon and polyester form with loss of a small molecule like water."),
            ("Materials Chemistry: Ceramics and Composites", "Surveys the composition and properties of ceramic materials and composite materials engineered from multiple components."),
            ("Semiconductor and Nanomaterial Chemistry", "Introduces the chemistry underlying semiconductor materials and nanoscale materials with size-dependent properties."),
            ("Radioactivity and Nuclear Decay", "Covers alpha, beta, and gamma decay, half-life calculations, and the stability of atomic nuclei."),
            ("Nuclear Fission, Fusion, and Applications", "Explains the physical chemistry of nuclear fission and fusion and their applications in energy production."),
        ],
        "UG3": [
            ("Quantum Mechanical Models of the Atom", "Introduces the quantum mechanical model of the atom, including orbitals as probability distributions rather than fixed paths."),
            ("The Schrodinger Equation: A Conceptual Overview", "Provides a conceptual, non-derivational overview of the Schrodinger equation and its role in describing atomic and molecular systems."),
            ("Molecular Orbital Diagrams for Diatomic Molecules", "Builds molecular orbital diagrams for simple diatomic molecules and uses them to predict bond order and magnetic behavior."),
            ("Advanced Thermodynamics: Chemical Potential", "Introduces chemical potential as the driving force for mass transfer and phase and chemical equilibria in multicomponent systems."),
            ("Statistical Thermodynamics: An Introduction", "Connects macroscopic thermodynamic quantities to the statistical behavior of large numbers of particles using the Boltzmann distribution."),
            ("Advanced Chemical Kinetics: Collision and Transition State Theory", "Compares collision theory and transition state theory as models for predicting reaction rates from molecular-level assumptions."),
            ("Photochemistry and Excited States", "Explains how molecules absorb light to reach excited electronic states and the pathways by which they subsequently react or relax."),
            ("Advanced NMR: Coupling Constants and 2D Techniques", "Covers spin-spin coupling patterns and introduces two-dimensional NMR techniques used to solve complex structures."),
            ("Mass Spectrometry Fragmentation Patterns", "Examines characteristic fragmentation pathways in mass spectrometry and how they help deduce molecular structure."),
            ("X-ray Crystallography and Structure Determination", "Introduces how X-ray diffraction from crystals is used to determine precise three-dimensional molecular structures."),
            ("Computational Chemistry: Molecular Modeling Basics", "Introduces molecular mechanics and basic computational approaches for modeling molecular structure and energy."),
            ("Computational Chemistry: Density Functional Theory Overview", "Provides a conceptual overview of density functional theory as a widely used method for computing molecular properties."),
            ("Advanced Electrochemistry: Battery and Fuel Cell Design", "Examines the electrochemical principles underlying battery and fuel cell design, including electrode materials and efficiency."),
            ("Supramolecular Chemistry and Host-Guest Interactions", "Introduces supramolecular chemistry and the noncovalent interactions that govern host-guest binding."),
            ("Organometallic Chemistry Fundamentals", "Covers the bonding and reactivity of compounds containing metal-carbon bonds and their classification."),
            ("Catalytic Cycles in Organometallic Catalysis", "Analyzes representative catalytic cycles, such as those in hydrogenation and cross-coupling, mediated by organometallic complexes."),
            ("Advanced Analytical Techniques: Chromatography", "Covers the principles of gas and liquid chromatography for separating and quantifying components of a mixture."),
            ("Advanced Analytical Techniques: Electrochemical Sensors", "Explains how electrochemical sensors, including ion-selective electrodes, are designed to detect specific analytes."),
        ],
        "UG4": [
            ("Reaction Mechanism Elucidation: Kinetic Isotope Effects", "Explains how kinetic isotope effects are used as experimental evidence to distinguish between proposed reaction mechanisms."),
            ("Asymmetric Synthesis and Chiral Catalysts", "Covers strategies for producing a single enantiomer selectively, including the use of chiral catalysts and reagents."),
            ("Retrosynthetic Analysis in Organic Synthesis", "Introduces retrosynthetic analysis as a systematic method for planning the synthesis of complex organic molecules."),
            ("Total Synthesis Case Studies", "Examines published total synthesis routes for complex natural products to illustrate strategic synthetic planning."),
            ("Green Chemistry Metrics: Atom Economy and E-Factor", "Introduces quantitative metrics, including atom economy and the E-factor, used to evaluate the sustainability of a synthetic route."),
            ("Sustainable and Renewable Chemical Feedstocks", "Surveys renewable feedstocks, such as biomass-derived chemicals, as alternatives to petroleum-based starting materials."),
            ("Environmental Chemistry: Persistent Organic Pollutants", "Examines the chemical properties that make certain pollutants persist, bioaccumulate, and pose long-term environmental risk."),
            ("Toxicology and Chemical Risk Assessment", "Introduces dose-response relationships and the framework used to assess the risk posed by chemical exposure."),
            ("Pharmaceutical Chemistry: Drug Design Principles", "Covers foundational principles of drug design, including target identification and lead compound optimization."),
            ("Structure-Activity Relationships in Medicinal Chemistry", "Explains how systematic modification of a molecule's structure is used to understand and improve its biological activity."),
            ("Biochemistry: Metabolic Pathways Overview", "Surveys major metabolic pathways, including glycolysis and the citric acid cycle, and how they interconnect."),
            ("Bioenergetics and ATP Synthesis", "Explains how cells capture energy from metabolism and use it to drive ATP synthesis via oxidative phosphorylation."),
            ("Advanced Materials: Battery Electrode Chemistry", "Examines the chemistry of electrode materials used in modern rechargeable batteries and factors limiting their performance."),
            ("Advanced Materials: Polymer Composites for Engineering", "Covers how polymer matrices are reinforced with fibers or particles to create composites with tailored mechanical properties."),
            ("Chemical Process Safety and Hazard Analysis", "Introduces systematic hazard analysis methods used to identify and mitigate risks in chemical processes and plants."),
            ("Instrumental Analysis: Quality Control Applications", "Covers how instrumental analytical methods are applied in industrial quality control and regulatory testing."),
            ("Research Methods: Experimental Design in Chemistry", "Covers principles of designing rigorous chemistry experiments, including controls, replication, and data validity."),
            ("Capstone Research Project: Literature Review and Proposal", "Guides students through conducting a chemistry literature review and drafting an original research proposal."),
        ],
        "M1": [
            ("Advanced Quantum Chemistry: Molecular Orbital Computations", "Covers ab initio and semi-empirical computational approaches used to calculate molecular orbitals and energies."),
            ("Group Theory and Molecular Symmetry", "Introduces group theory as a tool for classifying molecular symmetry and predicting spectroscopic selection rules."),
            ("Advanced Spectroscopic Methods: Multinuclear NMR", "Examines NMR experiments beyond proton NMR, including carbon-13 and other nuclei used in structural elucidation."),
            ("Advanced Mass Spectrometry: Tandem MS and Proteomics", "Covers tandem mass spectrometry techniques and their application in identifying and quantifying proteins."),
            ("Reaction Dynamics and Potential Energy Surfaces", "Explores how reaction dynamics are modeled using potential energy surfaces and transition state trajectories."),
            ("Advanced Catalysis: Homogeneous vs Heterogeneous Systems", "Compares the mechanisms, advantages, and industrial applications of homogeneous and heterogeneous catalytic systems."),
            ("Organometallic Mechanisms in Industrial Catalysis", "Analyzes the detailed mechanistic steps of organometallic catalytic cycles used in large-scale industrial processes."),
            ("Advanced Polymer Science: Characterization Techniques", "Covers techniques such as gel permeation chromatography and thermal analysis used to characterize polymer properties."),
            ("Nanochemistry and Self-Assembly", "Examines how nanoscale materials form through self-assembly and how their properties differ from bulk materials."),
            ("Advanced Electrochemistry: Impedance Spectroscopy", "Introduces electrochemical impedance spectroscopy as a technique for probing interfacial and material properties."),
            ("Computational Chemistry: Molecular Dynamics Simulations", "Covers how molecular dynamics simulations model the time-dependent behavior of atoms and molecules."),
            ("Advanced Biochemistry: Signal Transduction Chemistry", "Examines the chemical basis of cell signaling pathways, including receptor binding and second messenger systems."),
            ("Chemical Biology: Probing Biomolecules with Small Molecules", "Covers how chemists design small-molecule probes to study and manipulate biological systems."),
            ("Advanced Nuclear Chemistry: Radiochemistry Applications", "Explores applications of radiochemistry in medicine, dating techniques, and nuclear forensics."),
            ("Advanced Environmental Chemistry: Climate Chemistry", "Examines the atmospheric chemistry underlying the greenhouse effect and climate feedback mechanisms."),
            ("Analytical Method Validation and Chemometrics", "Covers statistical approaches to validating analytical methods and extracting information from complex chemical data."),
            ("Research Ethics and Reproducibility in Chemistry", "Discusses ethical conduct in chemical research, including data integrity, authorship, and reproducibility standards."),
            ("Capstone Research Project: Data Analysis and Defense", "Requires students to analyze original research data and defend their findings in a formal research presentation."),
        ],
    },
    "Biology": {
        "C1": [
            ("Cell Theory and the Discovery of Cells", "Traces the historical development of cell theory and establishes the cell as the basic unit of life."),
            ("Prokaryotic vs Eukaryotic Cell Structure", "Compares the structural differences between prokaryotic and eukaryotic cells, including the presence or absence of a nucleus."),
            ("Cell Membrane Structure and the Fluid Mosaic Model", "Describes the phospholipid bilayer and embedded proteins that make up the fluid mosaic model of the cell membrane."),
            ("Organelles and Their Functions", "Surveys major eukaryotic organelles, including the nucleus, mitochondria, and ribosomes, and their roles within the cell."),
            ("Passive Transport: Diffusion and Osmosis", "Explains how molecules move across membranes without energy input through diffusion, facilitated diffusion, and osmosis."),
            ("Active Transport and Endocytosis/Exocytosis", "Covers how cells use energy to move substances against a concentration gradient and to import or export large materials."),
            ("Enzymes: Structure and Function", "Introduces enzymes as biological catalysts, explaining active sites, substrate specificity, and factors affecting enzyme activity."),
            ("Cellular Respiration: An Overview", "Surveys glycolysis, the citric acid cycle, and oxidative phosphorylation as the stages that convert glucose into usable energy."),
            ("Photosynthesis: An Overview", "Surveys the light-dependent and light-independent reactions that convert light energy into chemical energy in plants."),
            ("Mitosis and the Cell Cycle", "Describes the phases of the cell cycle and the stages of mitosis that produce genetically identical daughter cells."),
            ("Meiosis and Gamete Formation", "Explains how meiosis reduces chromosome number by half and generates genetic variation through crossing over."),
            ("Mendelian Genetics: Dominant and Recessive Traits", "Introduces Gregor Mendel's laws of inheritance and the concepts of dominant and recessive alleles."),
            ("Punnett Squares and Probability in Genetics", "Teaches how Punnett squares are used to predict the probability of offspring genotypes and phenotypes."),
            ("DNA Structure: The Double Helix", "Covers the discovery and structure of the DNA double helix, including base pairing and its role in storing genetic information."),
            ("Introduction to Classification and Taxonomy", "Introduces the hierarchical system used to classify organisms, from domain down to species."),
            ("Introduction to Ecosystems and Energy Flow", "Explains how energy flows through trophic levels in an ecosystem via food chains and food webs."),
            ("Introduction to Human Body Systems", "Surveys the major organ systems of the human body and how they work together to maintain life."),
            ("Scientific Method in Biological Investigation", "Covers how the scientific method is applied to biological questions, from hypothesis formation to controlled experimentation."),
        ],
        "C2": [
            ("DNA Replication: Mechanism and Enzymes", "Details the semiconservative process of DNA replication and the roles of key enzymes such as DNA polymerase and helicase."),
            ("Transcription: From DNA to mRNA", "Explains how RNA polymerase synthesizes messenger RNA from a DNA template during transcription."),
            ("Translation: From mRNA to Protein", "Covers how ribosomes, tRNA, and the genetic code work together to synthesize proteins from mRNA."),
            ("The Genetic Code and Codon Usage", "Examines the properties of the genetic code, including redundancy and universality, and how codons specify amino acids."),
            ("Gene Regulation in Prokaryotes: The Lac Operon", "Uses the lac operon as a model for how prokaryotes regulate gene expression in response to environmental signals."),
            ("Mutations and Their Effects on Proteins", "Classifies types of mutations, including point mutations and frameshifts, and their potential effects on protein function."),
            ("Non-Mendelian Inheritance Patterns", "Covers inheritance patterns beyond simple dominance, including incomplete dominance, codominance, and polygenic traits."),
            ("Sex-Linked Inheritance", "Explains how genes located on sex chromosomes produce inheritance patterns that differ between males and females."),
            ("Pedigree Analysis", "Teaches how family pedigrees are used to trace the inheritance of traits and identify inheritance patterns."),
            ("Natural Selection and Adaptation", "Explains Darwin's theory of natural selection and how differential survival and reproduction lead to adaptation."),
            ("Evidence for Evolution", "Surveys evidence for evolution from the fossil record, comparative anatomy, embryology, and molecular biology."),
            ("Speciation Mechanisms", "Covers how reproductive isolation, through allopatric and sympatric mechanisms, leads to the formation of new species."),
            ("Population Genetics: The Hardy-Weinberg Principle", "Introduces the Hardy-Weinberg equilibrium as a model for predicting allele frequencies in a non-evolving population."),
            ("The Nervous System: Neurons and Synapses", "Describes neuron structure and how electrical and chemical signals are transmitted across synapses."),
            ("The Endocrine System: Hormones and Feedback", "Covers how hormones regulate body processes and how negative feedback loops maintain hormonal balance."),
            ("The Circulatory System: Heart and Blood Vessels", "Explains the structure of the heart and blood vessels and how they work together to circulate blood."),
            ("The Respiratory System: Gas Exchange", "Covers the structures and mechanisms involved in gas exchange between the lungs and the bloodstream."),
            ("The Digestive System: Nutrient Processing", "Traces the path of food through the digestive system and how nutrients are broken down and absorbed."),
        ],
        "UG1": [
            ("The Immune System: Innate Immunity", "Covers the body's first line of defense, including physical barriers, phagocytes, and the inflammatory response."),
            ("The Immune System: Adaptive Immunity and Antibodies", "Explains how B cells and T cells mount a specific, adaptive immune response and how antibodies neutralize pathogens."),
            ("Vaccines and Immunological Memory", "Describes how vaccines stimulate immunological memory to provide long-term protection against specific pathogens."),
            ("Bacterial Structure and Classification", "Surveys bacterial cell structure, including the cell wall and flagella, and common schemes for classifying bacteria."),
            ("Bacterial Growth and Reproduction", "Covers binary fission and the phases of bacterial population growth in culture."),
            ("Viruses: Structure and Replication Cycles", "Explains viral structure and compares the lytic and lysogenic cycles of viral replication."),
            ("Antibiotic Resistance Mechanisms", "Examines how bacteria develop and spread resistance to antibiotics through mutation and gene transfer."),
            ("The Excretory System: Kidney Function", "Describes nephron structure and how the kidneys filter blood and regulate fluid and electrolyte balance."),
            ("The Musculoskeletal System", "Covers the interaction of bones, joints, and muscles in producing movement and providing structural support."),
            ("Homeostasis and Feedback Mechanisms", "Explains how organisms maintain a stable internal environment through negative and positive feedback mechanisms."),
            ("Comparative Physiology Across Animal Groups", "Compares how different animal groups have evolved distinct physiological solutions to similar functional challenges."),
            ("Plant Structure: Roots, Stems, and Leaves", "Surveys the structure and function of the major vegetative organs of vascular plants."),
            ("Plant Physiology: Transport and Transpiration", "Explains how water and nutrients move through plants via xylem and phloem and the role of transpiration."),
            ("Plant Reproduction and Life Cycles", "Covers sexual and asexual reproduction in plants and the alternation of generations in plant life cycles."),
            ("Plant Hormones and Growth Responses", "Examines how plant hormones such as auxin and gibberellin regulate growth and tropic responses."),
            ("Fungal Biology and Ecological Roles", "Surveys fungal structure and reproduction and their ecological roles as decomposers and symbionts."),
            ("Protist Diversity and Classification", "Covers the diverse structural and functional characteristics used to classify protists."),
            ("Microbiology Laboratory Techniques", "Introduces core microbiology techniques, including aseptic technique, culturing, and staining methods."),
        ],
        "UG2": [
            ("Population Ecology: Growth Models", "Covers exponential and logistic population growth models and the concept of carrying capacity."),
            ("Community Ecology: Competition and Predation", "Examines how competition and predation shape the structure and dynamics of ecological communities."),
            ("Ecosystem Ecology: Nutrient Cycling", "Explains how carbon, nitrogen, and other nutrients cycle through ecosystems between living and nonliving components."),
            ("Biomes and Global Distribution of Life", "Surveys major terrestrial and aquatic biomes and the climatic factors that determine their distribution."),
            ("Developmental Biology: Fertilization and Cleavage", "Covers the early stages of animal development, from fertilization through the first cell divisions of cleavage."),
            ("Developmental Biology: Gastrulation and Organogenesis", "Explains how gastrulation establishes germ layers and how organogenesis shapes these layers into organs."),
            ("Stem Cells and Cellular Differentiation", "Introduces stem cell potency and the molecular processes that guide cellular differentiation."),
            ("Animal Behavior: Innate vs Learned Behavior", "Distinguishes innate, instinctive behaviors from behaviors acquired through learning and experience."),
            ("Animal Behavior: Communication and Social Structures", "Examines how animals communicate and how social structures such as hierarchies and cooperation arise."),
            ("Animal Behavior: Foraging and Mating Strategies", "Covers optimal foraging theory and the diversity of mating strategies observed across animal species."),
            ("Conservation Biology: Biodiversity Loss and Causes", "Surveys the major drivers of biodiversity loss, including habitat destruction, invasive species, and climate change."),
            ("Conservation Biology: Habitat Restoration Strategies", "Covers strategies used to restore degraded habitats and reestablish functioning ecosystems."),
            ("Endangered Species Management", "Examines approaches to managing endangered species populations, including captive breeding and protected areas."),
            ("Marine Biology: Ocean Zones and Habitats", "Surveys the physical zonation of the ocean and the distinct habitats and organisms found within each zone."),
            ("Marine Biology: Coral Reef Ecosystems", "Examines the biology of coral reef ecosystems, including symbiosis between corals and zooxanthellae."),
            ("Marine Biology: Marine Food Webs", "Covers the structure of marine food webs, from phytoplankton production to apex predators."),
            ("Biogeography and Species Distribution", "Explains how historical, geological, and ecological factors shape the geographic distribution of species."),
            ("Ecological Field Research Methods", "Introduces field sampling techniques, including quadrats and mark-recapture, used to study populations and communities."),
        ],
        "UG3": [
            ("Recombinant DNA Technology", "Covers the use of restriction enzymes and vectors to combine DNA from different sources into recombinant molecules."),
            ("CRISPR-Cas9 Gene Editing Mechanisms", "Explains the molecular mechanism by which the CRISPR-Cas9 system enables targeted editing of genomic DNA."),
            ("Cloning: Concepts and Techniques", "Surveys molecular, cellular, and reproductive cloning techniques and the biology underlying each."),
            ("Genetic Engineering in Agriculture", "Examines how genetic engineering has been applied to develop crops with improved traits such as pest resistance."),
            ("Stem Cell Therapy Applications", "Covers current and emerging applications of stem cell therapy in regenerative medicine."),
            ("Bioinformatics: Sequence Alignment Basics", "Introduces algorithms used to align DNA and protein sequences to identify similarity and evolutionary relationships."),
            ("Bioinformatics: Genome Databases and Annotation", "Covers how genomic data is stored, searched, and annotated using major public sequence databases."),
            ("Phylogenetics and Tree Construction", "Explains how molecular and morphological data are used to construct phylogenetic trees representing evolutionary relationships."),
            ("Epidemiology: Measures of Disease Frequency", "Introduces core epidemiological measures, including incidence, prevalence, and mortality rate."),
            ("Epidemiology: Modes of Disease Transmission", "Covers how infectious diseases spread through direct contact, vectors, and environmental reservoirs."),
            ("Epidemic Modeling: The SIR Framework", "Introduces the susceptible-infected-recovered model used to predict the course of an infectious disease outbreak."),
            ("Emerging Infectious Diseases", "Examines the biological and ecological factors that contribute to the emergence of new infectious diseases."),
            ("Neuroscience: Neuron Structure and Action Potentials", "Covers the ionic basis of the resting membrane potential and how action potentials propagate along neurons."),
            ("Neuroscience: Synaptic Transmission and Neurotransmitters", "Explains how neurotransmitters are released, bind receptors, and are cleared at chemical synapses."),
            ("Neuroscience: Brain Structure and Function", "Surveys the major structures of the brain and their associated functions."),
            ("Neuroplasticity and Learning", "Examines how synaptic connections change with experience and how this plasticity underlies learning and memory."),
            ("Sensory Systems and Perception", "Covers how sensory receptors transduce physical stimuli into neural signals that the brain interprets as perception."),
            ("Behavioral Neuroscience", "Explores the neural circuits and mechanisms that underlie complex behaviors."),
        ],
        "UG4": [
            ("Experimental Design in Biological Research", "Covers principles of designing valid biological experiments, including controls, replication, and variable isolation."),
            ("Statistical Analysis of Biological Data", "Introduces statistical tests commonly used to analyze biological data and assess the significance of results."),
            ("Model Organisms in Biological Research", "Surveys commonly used model organisms and the reasons each is well suited to particular kinds of research questions."),
            ("Peer Review and Scientific Publishing in Biology", "Explains the peer review process and the norms of scientific publishing within the biological sciences."),
            ("Bioethics: Genetic Testing and Privacy", "Examines ethical questions raised by genetic testing, including informed consent and the privacy of genetic information."),
            ("Bioethics: Human Cloning and Embryo Research", "Explores the ethical debates surrounding human cloning and research involving human embryos."),
            ("Bioethics: Animal Research Ethics", "Covers ethical frameworks and regulatory principles governing the use of animals in biological research."),
            ("Bioethics: Biotechnology and Genetically Modified Organisms", "Examines ethical and societal debates surrounding genetically modified organisms in agriculture and medicine."),
            ("Cancer Biology: Cell Cycle Dysregulation", "Explains how mutations affecting cell cycle checkpoints contribute to uncontrolled cell division in cancer."),
            ("Cancer Biology: Tumor Genetics and Metastasis", "Covers the genetic changes that drive tumor progression and the biological steps involved in metastasis."),
            ("Aging and Senescence at the Cellular Level", "Examines cellular mechanisms of aging, including telomere shortening and cellular senescence."),
            ("Epigenetics: Mechanisms and Inheritance", "Covers how DNA methylation and histone modification regulate gene expression without altering the DNA sequence."),
            ("Comparative Genomics", "Explains how comparing genomes across species reveals evolutionary relationships and conserved functional elements."),
            ("Systems Biology: Networks and Pathways", "Introduces systems biology approaches to modeling gene regulatory and metabolic networks as integrated systems."),
            ("Synthetic Biology: Engineering Biological Systems", "Covers the design principles used to engineer novel biological functions and genetic circuits."),
            ("One Health: Human, Animal, and Environmental Interfaces", "Examines the One Health framework linking human, animal, and environmental health in disease prevention."),
            ("Global Health Challenges and Biological Perspectives", "Surveys major global health challenges through the lens of underlying biological and ecological drivers."),
            ("Capstone Research Project: Proposal Development", "Guides students through developing an original biology research proposal, including background research and methodology."),
        ],
        "M1": [
            ("Advanced Molecular Genetics: Chromatin and Epigenetic Regulation", "Examines how chromatin structure and epigenetic marks regulate gene expression at an advanced mechanistic level."),
            ("Advanced Cell Signaling Pathways", "Covers major intracellular signaling pathways and how they integrate extracellular signals into cellular responses."),
            ("Advanced Immunology: Autoimmunity and Immunotherapy", "Explores the mechanisms behind autoimmune disease and current immunotherapy approaches for treating disease."),
            ("Advanced Virology: Emerging Viral Threats", "Examines the biology of emerging viruses and the factors that influence their potential for pandemic spread."),
            ("Advanced Bioinformatics: Next-Generation Sequencing Analysis", "Covers computational workflows used to process and analyze data generated by next-generation sequencing platforms."),
            ("Structural Biology: Protein Structure Prediction", "Introduces computational methods used to predict three-dimensional protein structure from amino acid sequence."),
            ("Advanced Evolutionary Biology: Molecular Evolution", "Examines the molecular mechanisms and models used to study evolutionary change at the level of DNA and protein sequences."),
            ("Advanced Ecology: Ecosystem Modeling", "Covers mathematical and computational models used to predict ecosystem dynamics under changing conditions."),
            ("Advanced Neuroscience: Cognitive and Computational Models", "Explores computational models used to explain cognitive processes in terms of underlying neural mechanisms."),
            ("Advanced Developmental Biology: Regenerative Medicine", "Examines how developmental biology principles inform regenerative medicine strategies for repairing damaged tissue."),
            ("Advanced Conservation Genetics", "Covers how genetic analysis informs conservation strategies, including assessing population diversity and inbreeding risk."),
            ("Advanced Epidemiology: Outbreak Investigation", "Examines the systematic methods epidemiologists use to investigate and control disease outbreaks."),
            ("Advanced Biotechnology: Synthetic Genomics", "Covers advanced techniques for designing and synthesizing entire genomes or large genomic segments."),
            ("Advanced Cancer Biology: Precision Oncology", "Explores how molecular profiling of tumors informs individualized, precision approaches to cancer treatment."),
            ("Advanced Microbiome Research", "Examines current research methods and findings on the role of the microbiome in health and disease."),
            ("Grant Writing and Research Funding in Biology", "Covers the principles of writing a competitive research grant proposal in the biological sciences."),
            ("Research Ethics and Responsible Conduct of Research", "Covers standards for the responsible conduct of biological research, including data integrity and authorship."),
            ("Capstone Research Project: Data Analysis and Defense", "Requires students to analyze original research data and defend their findings in a formal research presentation."),
        ],
    },
    "Critical Thinking": {
        "C1": [
            ("What Is Critical Thinking? Standards and Habits of Mind", "Introduces critical thinking as a disciplined process and surveys intellectual standards such as clarity, accuracy, and relevance."),
            ("Introduction to Propositional Logic", "Introduces propositions as the basic units of logical analysis and how they combine using logical connectives."),
            ("Truth Tables and Logical Connectives", "Teaches how to construct truth tables to evaluate the truth value of compound statements using AND, OR, and NOT."),
            ("Valid vs Sound Arguments", "Distinguishes a logically valid argument structure from a sound argument that is both valid and has true premises."),
            ("Introduction to Predicate Logic", "Extends propositional logic to predicate logic, introducing quantifiers such as 'all' and 'some' for reasoning about categories."),
            ("Necessary and Sufficient Conditions", "Clarifies the difference between a condition required for an outcome and one that guarantees it."),
            ("Introduction to Epistemology: What Is Knowledge?", "Introduces epistemology as the philosophical study of knowledge and surveys the traditional analysis of knowledge as justified true belief."),
            ("Justified True Belief and the Gettier Problem", "Examines Edmund Gettier's famous counterexamples that challenge the justified-true-belief definition of knowledge."),
            ("Sources of Knowledge: Perception, Reason, and Testimony", "Surveys perception, reasoning, and testimony as distinct sources through which people come to acquire knowledge."),
            ("Introduction to the Toulmin Model of Argument", "Introduces Stephen Toulmin's model for analyzing real-world arguments in terms of claims, grounds, and warrants."),
            ("Claims, Reasons, and Warrants in Argumentation", "Teaches how to identify the claim, supporting reasons, and underlying warrant that connects them in an argument."),
            ("Introduction to Scientific Reasoning", "Introduces the logic of hypothesis testing and how scientific claims are supported or challenged by evidence."),
            ("Correlation vs Causation", "Explains why a statistical correlation between two variables does not by itself establish that one causes the other."),
            ("Introduction to Statistical Reasoning", "Covers basic descriptive statistics, such as mean and variability, and how they are used to summarize data responsibly."),
            ("Reading and Interpreting Data Responsibly", "Teaches how to critically read charts, graphs, and reported statistics to avoid common misinterpretations."),
            ("Socratic Questioning: Origins and Method", "Introduces the Socratic method of probing questions used to examine assumptions and clarify concepts."),
            ("Asking Better Questions to Clarify Thinking", "Develops practical skill in formulating clarifying questions that expose hidden assumptions in an argument."),
            ("Introduction to Systems Thinking", "Introduces systems thinking as an approach to understanding how parts of a system interact to produce overall behavior."),
        ],
        "C2": [
            ("Categorical Logic and Syllogisms", "Covers the structure of categorical statements and how they combine to form classical Aristotelian syllogisms."),
            ("Rules of Valid Syllogistic Reasoning", "Teaches the formal rules used to determine whether a categorical syllogism is logically valid."),
            ("Modal Logic: Necessity and Possibility", "Introduces modal logic and the operators used to reason about what is necessarily or possibly true."),
            ("Epistemic Justification: Foundationalism vs Coherentism", "Compares foundationalist and coherentist theories of how beliefs become epistemically justified."),
            ("Skepticism and Its Challenges to Knowledge", "Examines classical and modern skeptical arguments that challenge the possibility of certain knowledge."),
            ("Toulmin Model: Backing, Qualifiers, and Rebuttals", "Extends the Toulmin model to include backing for warrants, qualifiers on claims, and anticipated rebuttals."),
            ("Constructing Counterarguments", "Teaches how to construct a well-reasoned counterargument that directly engages the strongest version of an opposing claim."),
            ("The Philosophy of Evidence: What Counts as Proof?", "Explores philosophical questions about what qualifies as good evidence across different fields of inquiry."),
            ("Falsifiability and the Demarcation Problem", "Introduces Karl Popper's falsifiability criterion and the problem of distinguishing science from pseudoscience."),
            ("Probability Theory for Everyday Reasoning", "Covers basic probability concepts and common errors people make when reasoning about likelihood and risk."),
            ("Understanding Statistical Significance", "Explains what a statistically significant result does and does not indicate about the strength of a finding."),
            ("Sampling Methods and Their Limitations", "Covers how sampling method and sample size affect the reliability of conclusions drawn from data."),
            ("Socratic Dialogue in Practice", "Applies the Socratic method through guided practice in questioning and examining one's own beliefs and those of others."),
            ("Feedback Loops in Systems Thinking", "Introduces reinforcing and balancing feedback loops and how they shape a system's behavior over time."),
            ("Emergent Properties in Complex Systems", "Explores how complex systems can display emergent properties not predictable from their individual parts alone."),
            ("Introduction to Creative Problem-Solving Frameworks", "Surveys structured frameworks used to generate and evaluate creative solutions to ill-defined problems."),
            ("Design Thinking as a Problem-Solving Process", "Introduces the design thinking process of empathizing, defining, ideating, prototyping, and testing."),
            ("Lateral Thinking Techniques", "Introduces Edward de Bono's lateral thinking techniques for generating solutions outside conventional reasoning patterns."),
        ],
        "UG1": [
            ("Critical Thinking in Legal Reasoning", "Examines how lawyers and judges apply structured reasoning, precedent, and evidentiary standards in legal argument."),
            ("Critical Thinking in Medical Diagnosis", "Covers the reasoning process clinicians use to form and test diagnostic hypotheses from patient evidence."),
            ("Critical Thinking in Business Decision-Making", "Applies critical thinking frameworks to structured business decisions involving incomplete information and risk."),
            ("Root Cause Analysis in Professional Settings", "Teaches systematic root cause analysis techniques used to identify the underlying source of a problem."),
            ("Ethical Reasoning Frameworks: Consequentialism", "Introduces consequentialist ethical reasoning, which evaluates the morality of an action by its outcomes."),
            ("Ethical Reasoning Frameworks: Deontology", "Introduces deontological ethical reasoning, which evaluates actions based on adherence to moral rules or duties."),
            ("Ethical Reasoning Frameworks: Virtue Ethics", "Introduces virtue ethics, which evaluates actions in terms of the character traits they express."),
            ("Applying Ethical Frameworks to Case Studies", "Applies consequentialist, deontological, and virtue ethics frameworks to analyze real-world ethical case studies."),
            ("Critical Media Analysis: Framing and Narrative", "Examines how media framing and narrative choices shape audience interpretation of events."),
            ("Critical Media Analysis: Source Credibility Assessment", "Teaches systematic methods for evaluating the credibility and reliability of a media source."),
            ("Rhetorical Analysis: Ethos, Pathos, and Logos", "Introduces Aristotle's three modes of persuasion and how to identify them in spoken and written argument."),
            ("Persuasion Techniques in Advertising and Politics", "Analyzes common persuasive techniques used in advertising and political messaging."),
            ("Critical Thinking and Misinformation in the Digital Age", "Examines how misinformation spreads online and strategies for critically evaluating digital content."),
            ("Evaluating Algorithmic and AI-Generated Content", "Teaches critical evaluation skills specific to content generated or curated by algorithms and AI systems."),
            ("Filter Bubbles and Epistemic Bubbles", "Explores how personalized information environments can narrow exposure to differing viewpoints."),
            ("Decision Theory: Expected Value and Utility", "Introduces expected value and utility as formal tools for evaluating decisions under uncertainty."),
            ("Decision Trees for Structured Decision-Making", "Teaches how decision trees map out choices, outcomes, and probabilities to support structured decision-making."),
            ("Risk Assessment and Uncertainty in Decisions", "Covers frameworks for assessing risk and making reasoned decisions when outcomes are uncertain."),
        ],
        "UG2": [
            ("Game Theory Fundamentals: Payoff Matrices", "Introduces payoff matrices as a tool for representing strategic interactions between decision-makers."),
            ("The Prisoner's Dilemma and Cooperation", "Uses the prisoner's dilemma to examine the tension between individual incentives and collective cooperation."),
            ("Nash Equilibrium and Strategic Reasoning", "Introduces the concept of Nash equilibrium as a stable outcome in strategic interactions."),
            ("Zero-Sum vs Non-Zero-Sum Games", "Distinguishes zero-sum games, where one party's gain is another's loss, from non-zero-sum games."),
            ("Sequential Games and Backward Induction", "Covers how backward induction is used to analyze optimal strategies in sequential games."),
            ("Bounded Rationality and Satisficing", "Introduces Herbert Simon's concept of bounded rationality and satisficing as an alternative to pure rational optimization."),
            ("Bayesian Reasoning and Updating Beliefs", "Teaches how Bayes' theorem is used to rationally update beliefs in light of new evidence."),
            ("Heuristics in Judgment Under Uncertainty", "Surveys mental shortcuts people use when reasoning under uncertainty and the trade-offs they involve."),
            ("Cross-Cultural Perspectives on Argumentation Styles", "Examines how norms of persuasive argument differ across cultural and rhetorical traditions."),
            ("Comparative Logic Traditions: Western and Non-Western", "Compares classical Western syllogistic logic with other historical logical traditions, such as Indian Nyaya logic."),
            ("Critical Thinking Across Disciplines", "Examines how the standards and methods of critical thinking differ across academic disciplines."),
            ("Interdisciplinary Problem Framing", "Teaches techniques for framing a single problem from the perspectives of multiple disciplines."),
            ("Systems Thinking: Causal Loop Diagrams", "Teaches how to construct causal loop diagrams that map reinforcing and balancing relationships in a system."),
            ("Systems Thinking: Leverage Points for Change", "Introduces the concept of leverage points as places within a system where a small change produces large effects."),
            ("Creative Problem-Solving: Analogical Reasoning", "Covers how reasoning by analogy is used to transfer solutions from a familiar problem to a novel one."),
            ("Creative Problem-Solving: TRIZ Method Basics", "Introduces the basic principles of TRIZ, a structured methodology for systematic inventive problem-solving."),
            ("Brainstorming and Idea Generation Techniques", "Surveys structured brainstorming techniques for generating a wide range of candidate solutions."),
            ("Structured Techniques for Group Decision-Making", "Covers structured methods, such as nominal group technique, used to improve group decision-making quality."),
        ],
        "UG3": [
            ("Designing a Critical Thinking Curriculum: Learning Objectives", "Teaches how to write clear learning objectives for a course designed to build critical thinking skills."),
            ("Instructional Strategies for Teaching Reasoning Skills", "Surveys instructional strategies shown to help students develop transferable reasoning skills."),
            ("Scaffolding Critical Thinking Across Age Groups", "Examines how critical thinking instruction can be scaffolded appropriately across different developmental stages."),
            ("Assessing Critical Thinking: Rubric Design", "Teaches how to design rubrics that validly assess the quality of a student's reasoning and argumentation."),
            ("Standardized Critical Thinking Assessments Overview", "Surveys widely used standardized instruments for assessing critical thinking ability."),
            ("Formative vs Summative Assessment of Reasoning Skills", "Compares formative and summative approaches to assessing the development of reasoning skills over time."),
            ("Philosophy of Argumentation: Informal Logic Traditions", "Introduces the informal logic tradition as a field distinct from formal logic, focused on real-world argument evaluation."),
            ("Pragma-Dialectics and the Rules of Critical Discussion", "Covers the pragma-dialectical theory of argumentation and its rules for conducting a reasonable critical discussion."),
            ("Rhetoric and Argumentation in Classical Philosophy", "Examines classical treatments of rhetoric and argumentation, including Aristotle's Rhetoric."),
            ("Contemporary Theories of Argumentation", "Surveys contemporary theories of argumentation that have developed since the mid-twentieth century."),
            ("The Ethics of Persuasion and Manipulation", "Examines the ethical line between legitimate persuasion and manipulative influence."),
            ("Epistemic Injustice and Whose Knowledge Counts", "Introduces the concept of epistemic injustice and how social position can affect whose testimony is credited."),
            ("Critical Thinking and Cognitive Diversity", "Explores how differences in cognitive style and background can shape reasoning processes and outcomes."),
            ("Critical Thinking in Cross-Cultural Negotiation", "Examines how critical thinking and argumentation strategies must adapt in cross-cultural negotiation settings."),
            ("Advanced Statistical Reasoning: Confounding Variables", "Covers how confounding variables can distort the apparent relationship between two studied variables."),
            ("Advanced Statistical Reasoning: Effect Size and Meta-Analysis", "Introduces effect size as a measure of practical significance and how meta-analysis combines results across studies."),
            ("Evaluating Scientific Studies and Peer Review", "Teaches criteria for critically evaluating the design, evidence, and conclusions of a scientific study."),
            ("Reproducibility and the Replication Crisis in Science", "Examines the causes and implications of the replication crisis affecting several scientific fields."),
        ],
        "UG4": [
            ("Case Study Method: Analyzing Real-World Dilemmas", "Teaches the case study method for applying critical thinking skills to complex, real-world dilemmas."),
            ("Applied Critical Thinking in Public Policy", "Applies critical thinking frameworks to the analysis and evaluation of public policy proposals."),
            ("Applied Critical Thinking in Environmental Debates", "Applies critical thinking skills to evaluate competing claims in environmental policy debates."),
            ("Applied Critical Thinking in Health Communication", "Examines how critical thinking skills support the evaluation of health claims and public health messaging."),
            ("Structured Analytic Techniques Used in Intelligence Analysis", "Surveys structured analytic techniques developed for intelligence analysis to reduce cognitive bias in judgments."),
            ("Red Teaming and Devil's Advocacy", "Introduces red teaming and devil's advocacy as structured techniques for stress-testing a plan or decision."),
            ("Scenario Planning and Forecasting", "Teaches scenario planning as a method for reasoning about multiple plausible futures under uncertainty."),
            ("Critical Thinking in Crisis Decision-Making", "Examines how time pressure and incomplete information affect reasoning quality during crisis decisions."),
            ("Evaluating Expert Testimony and Authority Claims", "Teaches criteria for critically evaluating claims made on the basis of expertise or authority."),
            ("Argument Mapping Software and Visualization Tools", "Introduces software tools used to visually map the structure of complex arguments."),
            ("Constructing a Formal Research Argument", "Teaches how to construct a well-supported formal argument suitable for an academic research paper."),
            ("Peer Critique and Collaborative Argument Refinement", "Covers structured peer critique processes used to refine and strengthen an argument collaboratively."),
            ("Ethics of AI-Assisted Reasoning Tools", "Examines ethical considerations raised by the use of AI tools to assist human reasoning and decision-making."),
            ("Human-AI Collaborative Decision-Making", "Explores frameworks for effective collaboration between human judgment and AI-generated recommendations."),
            ("Cognitive Load and Its Effect on Reasoning Quality", "Examines how cognitive load affects the quality of reasoning and decision-making under pressure."),
            ("Metacognition: Thinking About One's Own Thinking", "Introduces metacognition as the practice of monitoring and regulating one's own thought processes."),
            ("Building a Personal Framework for Lifelong Critical Thinking", "Guides students in synthesizing course concepts into a personal framework for ongoing critical thinking practice."),
            ("Capstone Case Study: Research Design and Proposal", "Requires students to design an original applied critical thinking case study and draft a research proposal."),
        ],
        "M1": [
            ("Advanced Formal Logic: Modal and Deontic Systems", "Explores formal systems of modal and deontic logic used to reason about necessity, possibility, and obligation."),
            ("Advanced Epistemology: Social and Testimonial Knowledge", "Examines advanced epistemological questions about how knowledge is transmitted and justified through testimony."),
            ("Advanced Argumentation Theory: Dialectical Structures", "Covers advanced dialectical models of argumentation that treat argument as a structured exchange between parties."),
            ("Philosophy of Science: Paradigms and Scientific Revolutions", "Examines Thomas Kuhn's account of paradigm shifts and scientific revolutions in the philosophy of science."),
            ("Philosophy of Science: Theory Choice and Underdetermination", "Explores the problem of underdetermination and the criteria scientists use to choose between competing theories."),
            ("Advanced Decision Theory: Multi-Criteria Decision Analysis", "Introduces multi-criteria decision analysis for making structured decisions involving multiple competing objectives."),
            ("Advanced Game Theory: Evolutionary Game Theory", "Covers evolutionary game theory and how strategies evolve in populations through repeated interaction."),
            ("Behavioral Economics and Rational Choice Critiques", "Examines behavioral economics findings that challenge assumptions of purely rational choice in classical decision theory."),
            ("Advanced Systems Thinking: Complex Adaptive Systems", "Explores complex adaptive systems and how adaptation and self-organization emerge from local interactions."),
            ("Advanced Media Analysis: Computational Propaganda", "Examines how automated and algorithmic techniques are used to spread computational propaganda at scale."),
            ("Advanced AI and Misinformation: Deepfakes and Synthetic Media", "Covers the critical thinking challenges posed by AI-generated deepfakes and synthetic media."),
            ("Epistemology of Disagreement", "Examines philosophical questions about how one should rationally respond to disagreement with an epistemic peer."),
            ("Advanced Ethics: Applied Bioethics Reasoning", "Applies advanced ethical reasoning frameworks to complex, contested bioethical case studies."),
            ("Advanced Ethics: Global Justice and Moral Reasoning", "Examines advanced moral reasoning about global justice questions that cross national and cultural boundaries."),
            ("Curriculum Design for Graduate-Level Critical Thinking Programs", "Covers principles for designing rigorous, graduate-level critical thinking curricula and program outcomes."),
            ("Research Methods in Critical Thinking Pedagogy", "Introduces research methods used to study the effectiveness of critical thinking instruction."),
            ("Publishing and Peer Review in Argumentation Studies", "Covers the norms of scholarly publishing and peer review within the field of argumentation studies."),
            ("Capstone Applied Critical Thinking Case Study: Defense and Synthesis", "Requires students to defend and synthesize an original applied critical thinking case study before a review panel."),
        ],
    },
    "ICT & Computer Science": {
        "C1": [
            ("What Is an Information System? Components and Purpose", "Introduces information systems as combinations of people, processes, and technology used to manage organizational data."),
            ("Data, Information, and Knowledge: Key Distinctions", "Clarifies the distinctions between raw data, processed information, and applied knowledge in an ICT context."),
            ("Introduction to Database Concepts: Tables and Records", "Introduces how databases organize data into tables, records, and fields for structured storage and retrieval."),
            ("Introduction to Structured Query Language (SQL)", "Teaches basic SQL commands for retrieving, inserting, and updating data stored in a relational database."),
            ("Introduction to Computer Networks: LAN and WAN", "Introduces local area networks and wide area networks and how they connect computers for communication."),
            ("The OSI Model: An Overview", "Surveys the seven layers of the OSI model as a conceptual framework for understanding network communication."),
            ("Introduction to the Internet and TCP/IP", "Explains how the TCP/IP protocol suite enables data to be routed and delivered across the internet."),
            ("Introduction to Cybersecurity: Threats and Vulnerabilities", "Introduces common categories of cybersecurity threats and the vulnerabilities that attackers exploit."),
            ("Passwords, Authentication, and Basic Security Hygiene", "Covers best practices for password security, multi-factor authentication, and everyday security hygiene."),
            ("Introduction to Systems Analysis: Requirements Gathering", "Introduces techniques used to gather and document business requirements during systems analysis."),
            ("Introduction to Systems Design: From Requirements to Models", "Explains how gathered requirements are translated into system design models and specifications."),
            ("Introduction to IT Project Management: Scope and Timeline", "Introduces core project management concepts, including defining scope, milestones, and a project timeline."),
            ("Introduction to Cloud Computing Concepts", "Introduces the basic concept of cloud computing as on-demand access to computing resources over the internet."),
            ("Introduction to Mobile Computing", "Surveys the basic concepts and constraints of computing on mobile devices, including connectivity and power."),
            ("Introduction to Human-Computer Interaction Principles", "Introduces core principles of human-computer interaction, including usability and user-centered design."),
            ("Introduction to IT Service Management Concepts", "Introduces the basic concept of IT service management as a structured approach to delivering IT services."),
            ("Digital Citizenship and Online Etiquette", "Covers responsible, ethical, and safe behavior expected of individuals participating in online communities."),
            ("ICT Ethics: Privacy and Acceptable Use", "Introduces ethical principles around data privacy and acceptable use of information technology resources."),
        ],
        "C2": [
            ("Relational Database Design: Normalization Basics", "Introduces the process of normalization used to reduce data redundancy and improve relational database design."),
            ("Entity-Relationship Modeling", "Teaches how entity-relationship diagrams are used to model the data requirements of an information system."),
            ("SQL Joins and Aggregate Queries", "Covers how SQL joins combine data across tables and how aggregate functions summarize query results."),
            ("Database Transactions and ACID Properties", "Explains database transactions and the ACID properties that guarantee reliable processing of grouped operations."),
            ("Network Protocols: HTTP, FTP, and DNS", "Surveys key application-layer protocols, including HTTP, FTP, and DNS, and their roles on the internet."),
            ("Network Security Fundamentals: Firewalls and Encryption", "Introduces firewalls and encryption as foundational tools for protecting network traffic and data."),
            ("Wireless Networking Standards and Security", "Covers common wireless networking standards and the security protocols used to protect wireless networks."),
            ("Systems Analysis: Data Flow Diagrams", "Teaches how data flow diagrams are used to model how data moves through an information system."),
            ("Systems Design: Use Case Modeling", "Introduces use case diagrams as a tool for modeling how users interact with a proposed system."),
            ("Structured vs Agile Project Management Approaches", "Compares traditional waterfall project management with agile approaches to managing IT projects."),
            ("Business Process Modeling Notation (BPMN) Basics", "Introduces BPMN as a standard graphical notation for modeling business processes."),
            ("IT Governance: Frameworks and Standards Overview", "Surveys major IT governance frameworks used to align IT activities with organizational objectives."),
            ("Cloud Service Models: IaaS, PaaS, and SaaS", "Distinguishes infrastructure, platform, and software as a service cloud delivery models."),
            ("Mobile App Development: Native vs Cross-Platform", "Compares native and cross-platform approaches to developing applications for mobile devices."),
            ("Usability Testing and User-Centered Design", "Introduces usability testing methods used to evaluate and improve user-centered software design."),
            ("ITIL Framework: Incident and Problem Management", "Covers ITIL processes for managing IT incidents and identifying the root causes of recurring problems."),
            ("Digital Divide and Access to Technology", "Examines the digital divide and the social and economic factors that limit equitable access to technology."),
            ("Intellectual Property and Software Licensing", "Introduces intellectual property concepts and common software licensing models relevant to ICT professionals."),
        ],
        "UG1": [
            ("Advanced Relational Database Design: Higher Normal Forms", "Extends normalization theory to higher normal forms used to further reduce anomalies in database design."),
            ("NoSQL Databases: Document, Key-Value, and Graph Models", "Surveys NoSQL database models, including document, key-value, and graph stores, and when each is appropriate."),
            ("Database Indexing and Query Optimization", "Covers how indexing structures and query optimization techniques improve database performance."),
            ("Routing Protocols and Network Addressing (Subnetting)", "Introduces IP subnetting and the routing protocols used to direct traffic between networks."),
            ("Network Security: Intrusion Detection and Prevention", "Covers how intrusion detection and prevention systems identify and respond to suspicious network activity."),
            ("Cybersecurity Risk Management Frameworks", "Introduces structured frameworks used by organizations to identify, assess, and manage cybersecurity risk."),
            ("Systems Analysis: Object-Oriented Modeling with UML", "Teaches how Unified Modeling Language diagrams are used to model object-oriented system designs."),
            ("Systems Design: Architecture Patterns", "Surveys common software architecture patterns used to structure the design of information systems."),
            ("Enterprise Resource Planning: Core Modules Overview", "Introduces the core functional modules typically found within an enterprise resource planning system."),
            ("ERP Implementation Challenges and Change Management", "Examines common challenges in ERP implementation and the change management strategies used to address them."),
            ("Business Process Reengineering", "Covers the principles of business process reengineering as a method for redesigning organizational workflows."),
            ("Workflow Automation Tools", "Surveys tools and techniques used to automate repetitive business workflows within an organization."),
            ("IT Governance: COBIT and Regulatory Compliance", "Introduces the COBIT framework and its role in supporting IT regulatory compliance efforts."),
            ("Data Privacy Regulations: GDPR and Beyond", "Surveys major data privacy regulations, including the GDPR, and their implications for ICT systems."),
            ("Cloud Computing: Virtualization and Containers", "Explains how virtualization and containerization technologies underpin modern cloud computing platforms."),
            ("Mobile Computing: Location-Based Services", "Covers how mobile applications use location data to provide context-aware, location-based services."),
            ("IT Service Management: Change and Release Management", "Covers ITSM processes for managing changes to IT systems and coordinating software releases."),
            ("IT Service Management: Service Level Agreements", "Introduces service level agreements as formal commitments defining the expected quality of an IT service."),
        ],
        "UG2": [
            ("Digital Transformation Strategy in Organizations", "Examines how organizations develop and execute strategies for adopting digital technologies at scale."),
            ("Legacy System Modernization Approaches", "Surveys strategies used to modernize or replace outdated legacy information systems."),
            ("Emerging Technologies: Internet of Things (IoT) Architectures", "Introduces the layered architecture of IoT systems, from sensors to cloud-based data processing."),
            ("Emerging Technologies: IoT Security Challenges", "Examines the unique security challenges posed by resource-constrained, widely distributed IoT devices."),
            ("Blockchain Fundamentals: Distributed Ledgers", "Introduces blockchain as a distributed ledger technology and explains how consensus mechanisms secure it."),
            ("Blockchain Applications Beyond Cryptocurrency", "Surveys applications of blockchain technology in areas such as supply chain tracking and digital identity."),
            ("Artificial Intelligence in ICT Systems: An Overview", "Introduces how AI techniques are integrated into modern ICT systems to automate and enhance decision-making."),
            ("Machine Learning Applications in Business Intelligence", "Covers how machine learning techniques are applied within business intelligence systems to generate insights."),
            ("ICT for Development: Bridging the Digital Divide", "Examines how ICT initiatives are designed to extend technology access and benefits to underserved regions."),
            ("Mobile Technology for Development in Emerging Markets", "Surveys how mobile technology has been used to deliver services such as banking and education in emerging markets."),
            ("E-Government Systems and Digital Public Services", "Introduces how governments use ICT systems to deliver public services digitally to citizens."),
            ("Telecommunications Infrastructure in Developing Regions", "Examines the challenges and strategies involved in building telecommunications infrastructure in developing regions."),
            ("Data Management: Data Quality Dimensions", "Covers key dimensions of data quality, including accuracy, completeness, and consistency."),
            ("Master Data Management Principles", "Introduces master data management as a discipline for maintaining a single, consistent view of key organizational data."),
            ("Data Governance Frameworks", "Surveys frameworks organizations use to establish accountability and policy over their data assets."),
            ("IT Infrastructure Management: Servers and Storage", "Covers the core components of IT infrastructure, including servers and storage systems, and their management."),
            ("IT Infrastructure Management: Virtualization at Scale", "Examines how virtualization technologies are managed at scale within enterprise IT infrastructure."),
            ("Disaster Recovery and Business Continuity Planning", "Introduces the principles of disaster recovery and business continuity planning for IT systems."),
        ],
        "UG3": [
            ("Advanced Computer Networking: Software-Defined Networking", "Introduces software-defined networking as an approach that separates the network control plane from the data plane."),
            ("Advanced Cybersecurity: Penetration Testing Fundamentals", "Covers the methodology and ethical constraints involved in conducting a penetration test on a system."),
            ("Advanced Cybersecurity: Security Operations Centers", "Examines the role and structure of a security operations center in monitoring and responding to threats."),
            ("Advanced Database Systems: Distributed Databases", "Covers the design challenges and consistency models involved in building distributed database systems."),
            ("Advanced Database Systems: Data Warehousing and OLAP", "Introduces data warehousing architecture and online analytical processing for multidimensional data analysis."),
            ("Big Data Technologies: Hadoop and Spark Overview", "Surveys distributed big data processing frameworks such as Hadoop and Spark and their typical use cases."),
            ("Human-Computer Interaction: Usability Heuristics", "Introduces established usability heuristics used to evaluate the design of interactive systems."),
            ("Human-Computer Interaction: Accessibility Standards", "Covers accessibility standards and guidelines used to ensure ICT systems are usable by people with disabilities."),
            ("Advanced Systems Analysis: Enterprise Architecture Frameworks", "Surveys enterprise architecture frameworks used to align organizational strategy with IT systems design."),
            ("IT Project Management: Risk Management Techniques", "Covers techniques for identifying, assessing, and mitigating risk within an IT project."),
            ("IT Project Management: Agile and Scrum in Practice", "Examines the practical application of agile principles and the Scrum framework in managing IT projects."),
            ("Advanced Cloud Computing: Multi-Cloud Strategies", "Introduces multi-cloud strategies used by organizations to distribute workloads across multiple cloud providers."),
            ("Advanced Cloud Computing: Serverless Architectures", "Covers serverless computing architectures and how they abstract infrastructure management from developers."),
            ("Advanced Mobile Development: Cross-Platform Frameworks", "Surveys cross-platform frameworks used to build mobile applications that run on multiple operating systems."),
            ("Emerging Technologies: Edge Computing", "Introduces edge computing as an approach to processing data closer to its source to reduce latency."),
            ("Emerging Technologies: 5G and Next-Generation Networks", "Surveys the capabilities of 5G networks and their implications for next-generation connected applications."),
            ("IT Governance: Auditing Information Systems", "Introduces the principles and practices involved in auditing information systems for compliance and control."),
            ("Research Methods in Information Systems", "Covers research methodologies commonly used in information systems research, including case studies and surveys."),
        ],
        "UG4": [
            ("Enterprise Systems Integration Approaches", "Surveys approaches used to integrate disparate enterprise systems so they can share data and processes."),
            ("API Design and Management for Enterprise Systems", "Covers principles of designing and managing APIs that expose enterprise system functionality securely."),
            ("Data Analytics for Business Decision Support", "Introduces how data analytics techniques are applied to support evidence-based business decisions."),
            ("Business Intelligence Dashboards and Reporting", "Covers the design of business intelligence dashboards used to communicate key metrics to decision-makers."),
            ("IT Service Management: ITIL Continual Improvement", "Introduces the ITIL continual improvement process for ongoing enhancement of IT service quality."),
            ("Change Management for Digital Transformation Initiatives", "Examines organizational change management strategies used to support digital transformation initiatives."),
            ("Cybersecurity Incident Response Planning", "Covers the structured process organizations use to prepare for and respond to cybersecurity incidents."),
            ("Cybersecurity: Digital Forensics Basics", "Introduces the basic principles and evidentiary standards involved in digital forensic investigation."),
            ("ICT Project Feasibility Studies", "Teaches how feasibility studies assess the technical, economic, and operational viability of an ICT project."),
            ("Cost-Benefit Analysis for IT Investments", "Introduces cost-benefit analysis as a method for evaluating proposed investments in IT systems."),
            ("Vendor Management and IT Outsourcing", "Covers strategies for managing technology vendors and evaluating IT outsourcing arrangements."),
            ("Sustainable ICT: Green Computing Practices", "Surveys green computing practices aimed at reducing the environmental impact of ICT systems."),
            ("ICT for Development: Monitoring and Evaluation", "Introduces monitoring and evaluation frameworks used to assess the impact of ICT for development projects."),
            ("Data Quality Auditing in Enterprise Systems", "Covers methods for auditing data quality within enterprise systems to identify and correct errors."),
            ("Enterprise Architecture: TOGAF Framework Overview", "Introduces TOGAF as a widely used framework for developing enterprise architecture."),
            ("Capstone ICT Systems Project: Requirements and Design", "Guides students through gathering requirements and designing an original capstone ICT systems project."),
            ("Capstone ICT Systems Project: Implementation Planning", "Covers how to plan the implementation phase of a capstone ICT systems project, including resources and timeline."),
            ("Capstone ICT Systems Project: Testing and Evaluation", "Covers how to test and evaluate a capstone ICT systems project against its original requirements."),
        ],
        "M1": [
            ("Advanced Information Systems Strategy", "Examines advanced strategic frameworks for aligning information systems investment with long-term organizational goals."),
            ("Advanced Database Systems: NewSQL and Distributed Consensus", "Covers NewSQL database systems and the distributed consensus algorithms that maintain their consistency."),
            ("Advanced Networking: Network Function Virtualization", "Introduces network function virtualization as an approach to replacing dedicated network hardware with software."),
            ("Advanced Cybersecurity: Threat Intelligence and Modeling", "Covers advanced threat intelligence practices and how organizations model adversary behavior."),
            ("Advanced Cybersecurity: Governance, Risk, and Compliance (GRC)", "Introduces integrated governance, risk, and compliance frameworks used in advanced cybersecurity management."),
            ("Advanced Systems Analysis: Model-Driven Architecture", "Examines model-driven architecture as an approach to systems design centered on formal models."),
            ("Advanced IT Project Management: Portfolio Management", "Covers portfolio management techniques used to prioritize and govern multiple IT projects simultaneously."),
            ("Advanced ERP: Customization and Integration Strategies", "Examines advanced strategies for customizing and integrating ERP systems with other enterprise applications."),
            ("Advanced Business Process Management: Process Mining", "Introduces process mining techniques used to discover and analyze actual business processes from event log data."),
            ("Advanced IT Governance: Enterprise Risk Frameworks", "Covers advanced enterprise risk management frameworks applied specifically to IT governance."),
            ("Advanced Cloud Computing: Cloud-Native Architectures", "Examines cloud-native architectural principles, including microservices and container orchestration."),
            ("Advanced Emerging Technologies: AI-IoT Convergence", "Explores the convergence of AI and IoT technologies and its implications for advanced ICT systems."),
            ("Advanced Emerging Technologies: Blockchain Governance Models", "Covers governance models used to manage decision-making within decentralized blockchain networks."),
            ("Advanced ICT for Development: Policy and Regulation", "Examines the policy and regulatory considerations that shape ICT for development initiatives."),
            ("Advanced Data Management: Data Lakes and Data Mesh", "Introduces data lake and data mesh architectures as advanced approaches to managing organizational data at scale."),
            ("Advanced IT Infrastructure: Hybrid Infrastructure Design", "Covers the design of hybrid IT infrastructure that combines on-premises and cloud-based resources."),
            ("ICT Ethics: Responsible Innovation and AI Governance", "Examines ethical frameworks for responsible technology innovation and the governance of AI systems."),
            ("Capstone ICT Systems Project: Research Defense and Recommendations", "Requires students to defend their capstone ICT systems project and present recommendations to a review panel."),
        ],
    },
}
