"""Module topics bringing Philosophy, Art History, Python, and R up to
20+ lessons per level (C1 through M1)."""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Philosophy": {
        "C1": [
            ("Terms, Propositions, and Truth Values", "Introduces the basic units of logical analysis: terms, propositions, and how truth values are assigned to statements."),
            ("Categorical Syllogisms", "Explains the classical Aristotelian syllogism, its standard forms, and the rules for determining validity."),
            ("Formal Fallacies vs. Informal Fallacies", "Distinguishes errors in an argument's logical structure from errors in its content, such as ad hominem or appeal to authority."),
            ("Necessary and Sufficient Conditions", "Clarifies the difference between conditions that are required for an outcome and conditions that guarantee it, a distinction used throughout philosophical analysis."),
            ("The Pre-Socratic Philosophers", "Surveys early Greek thinkers such as Thales, Heraclitus, and Parmenides who sought a rational account of the natural world before Socrates."),
            ("Socrates and the Examined Life", "Examines Socrates' method of questioning and his claim that an unexamined life is not worth living, as depicted in Plato's early dialogues."),
            ("Plato's Allegory of the Cave", "Analyzes the cave allegory from the Republic as an image of ignorance, enlightenment, and the philosopher's ascent to knowledge of the Forms."),
            ("Aristotle's Nicomachean Ethics: The Golden Mean", "Explores Aristotle's account of virtue as a mean between excess and deficiency, illustrated with examples like courage and generosity."),
            ("What Is Truth? Correspondence and Coherence Theories", "Compares theories that define truth as correspondence to fact with theories that define it as coherence within a system of beliefs."),
            ("Sense Perception and the Problem of Illusion", "Considers how illusions and perceptual errors raise doubts about the reliability of the senses as a source of knowledge."),
            ("The Mind-Body Problem: A First Look", "Introduces the puzzle of how mental states relate to physical states of the brain and body."),
            ("Do Animals Have Minds?", "Examines philosophical debates over animal cognition, consciousness, and whether non-human animals have beliefs or experiences."),
            ("The Problem of Evil", "Presents the challenge that the existence of suffering poses for belief in an all-powerful, all-good God, and surveys classic responses."),
            ("Arguments for the Existence of God", "Surveys the cosmological, teleological, and ontological arguments for God's existence and standard objections to each."),
            ("What Makes an Action Right? An Introduction to Moral Theory", "Introduces the basic question of moral theory and previews the major families of answers: consequentialist, deontological, and virtue-based."),
            ("Cultural Relativism and Moral Objectivity", "Examines the claim that moral standards are relative to culture and considers arguments for and against moral objectivity."),
            ("Aesthetic Experience: What Is Beauty?", "Introduces basic questions about the nature of beauty and aesthetic judgment, and whether beauty is objective or subjective."),
            ("Reading and Writing Philosophical Texts", "Teaches strategies for closely reading primary philosophical texts and constructing a clear, well-supported philosophical essay."),
        ],
        "C2": [
            ("Propositional Logic and Truth Tables", "Introduces the symbols and connectives of propositional logic and shows how truth tables determine the truth value of compound statements."),
            ("Validity, Soundness, and Counterexamples", "Distinguishes a valid argument form from a sound argument and teaches how to construct counterexamples to test validity."),
            ("Presocratic Cosmology: Thales to Democritus", "Traces the development of early Greek theories of the natural world, from Thales' claim that all is water to Democritus's atomism."),
            ("Plato's Republic: Justice in the Soul and the City", "Examines Plato's analogy between justice in the individual soul and justice in the ideal city-state."),
            ("Plato's Theory of Forms and the Problem of Universals", "Explores Plato's account of eternal, unchanging Forms as the reality behind changing particulars, and the problem of explaining shared properties."),
            ("Aristotle's Metaphysics: Substance and Change", "Studies Aristotle's account of substance, form and matter, and his framework for explaining how things persist through change."),
            ("Aristotle's Logic: The Organon and Syllogistic", "Introduces Aristotle's foundational system of syllogistic logic as set out in his logical treatises, the Organon."),
            ("Hellenistic Philosophy: Stoicism and Epicureanism", "Compares Stoic teachings on virtue and acceptance of fate with Epicurean teachings on pleasure and the avoidance of pain."),
            ("Augustine on Time, Memory, and the Will", "Examines Augustine's reflections in the Confessions on the nature of time, the workings of memory, and the freedom of the will."),
            ("Aquinas's Five Ways", "Analyzes Thomas Aquinas's five arguments for the existence of God from motion, causation, contingency, gradation, and design."),
            ("Boethius and the Problem of Fate", "Studies Boethius's Consolation of Philosophy and its treatment of fortune, providence, and human freedom."),
            ("Avicenna and Averroes: Islamic Philosophy and Aristotle", "Examines how Islamic philosophers Avicenna and Averroes preserved, interpreted, and extended Aristotelian philosophy."),
            ("Gettier Problems and the Analysis of Knowledge", "Presents Edmund Gettier's counterexamples to the traditional justified-true-belief account of knowledge."),
            ("Rationalism vs. Empiricism: Descartes and Locke", "Contrasts Descartes' rationalist reliance on reason with Locke's empiricist claim that knowledge originates in experience."),
            ("The Problem of Induction", "Presents Hume's challenge to the rational justification of inductive inference from past to future cases."),
            ("Types of Skepticism: Cartesian and Humean", "Compares Descartes' methodological doubt with Hume's skepticism about induction and causal reasoning."),
            ("Foundationalism vs. Coherentism", "Compares two structural theories of epistemic justification: beliefs justified by basic foundations versus beliefs justified by mutual coherence."),
            ("Testimony and Social Epistemology", "Examines how much of what we know depends on the testimony of others and what conditions make testimony a reliable source of knowledge."),
        ],
        "UG1": [
            ("Descartes' Meditations and the Cogito", "Studies Descartes' method of doubt in the Meditations and his conclusion that the thinking self cannot coherently be doubted."),
            ("Cartesian Dualism and Its Critics", "Examines Descartes' argument that mind and body are distinct substances and surveys objections from Princess Elisabeth onward."),
            ("Locke on Personal Identity and Memory", "Studies Locke's proposal that personal identity consists in continuity of consciousness and memory rather than in an unchanging soul or body."),
            ("Hume's Fork and the Problem of Causation", "Examines Hume's distinction between relations of ideas and matters of fact, and his analysis of causation as constant conjunction."),
            ("Hume's Skepticism about the Self", "Explores Hume's claim that introspection reveals only a bundle of perceptions, not a unified, persisting self."),
            ("Kant's Copernican Revolution in Epistemology", "Explains Kant's claim that the mind actively structures experience through categories and forms of intuition, reversing the traditional relation of mind to world."),
            ("Kant's Categorical Imperative", "Analyzes Kant's formulations of the categorical imperative as a test for the moral permissibility of maxims of action."),
            ("Mill's Utilitarianism: Higher and Lower Pleasures", "Examines Mill's refinement of utilitarianism to distinguish qualitatively higher intellectual pleasures from lower bodily ones."),
            ("Bentham's Hedonic Calculus", "Studies Jeremy Bentham's attempt to quantify pleasure and pain along measurable dimensions to guide moral and legislative decisions."),
            ("Kantian Deontology vs. Rule Consequentialism", "Compares Kant's duty-based ethics with rule-consequentialist theories that evaluate rules by their consequences."),
            ("Contractualism: Rawls, Scanlon, and Fairness", "Examines contractualist theories that ground morality in principles no one could reasonably reject, from Rawls's justice as fairness to Scanlon's contractualism."),
            ("Introduction to Philosophy of Language: Sense and Reference (Frege)", "Introduces Frege's distinction between the sense and reference of an expression and its role in solving puzzles about identity statements."),
            ("Russell's Theory of Descriptions", "Examines Bertrand Russell's analysis of definite descriptions and how it resolves puzzles about reference to non-existent entities."),
            ("Speech Act Theory: Austin and Searle", "Studies J.L. Austin's and John Searle's account of language as action, distinguishing locutionary, illocutionary, and perlocutionary acts."),
            ("Meaning and Use: Wittgenstein's Later Philosophy", "Examines the later Wittgenstein's claim that the meaning of a word is constituted by its use within a language-game."),
            ("The Problem of Personal Identity: Locke to Parfit", "Traces debates about what makes a person the same person over time, from Locke's memory theory to Derek Parfit's reductionist view."),
            ("Compatibilism and Incompatibilism about Free Will", "Compares compatibilist views that free will is consistent with determinism to incompatibilist views that the two cannot coexist."),
            ("Determinism, Indeterminism, and Moral Responsibility", "Examines how theories of determinism and indeterminism bear on whether agents can be held morally responsible for their actions."),
        ],
        "UG2": [
            ("Hobbes's Leviathan and the Social Contract", "Studies Hobbes's argument that fear of the state of nature's war of all against all justifies submission to an absolute sovereign."),
            ("Locke's Second Treatise and Natural Rights", "Examines Locke's account of natural rights to life, liberty, and property, and the limited government needed to protect them."),
            ("Rousseau and the General Will", "Explores Rousseau's concept of the general will as the basis of legitimate political authority in the Social Contract."),
            ("Rawls's Theory of Justice: The Original Position", "Studies Rawls's thought experiment of the original position and veil of ignorance as a device for deriving fair principles of justice."),
            ("Nozick's Libertarian Critique of Rawls", "Examines Robert Nozick's entitlement theory of justice and his libertarian objections to redistributive theories like Rawls's."),
            ("Marx's Critique of Capitalism and Alienation", "Studies Marx's analysis of alienated labor under capitalism and his critique of private ownership of the means of production."),
            ("Communitarianism vs. Liberalism", "Compares communitarian critiques of liberal individualism with liberal responses defending the primacy of individual rights."),
            ("Anscombe and the Revival of Virtue Ethics", "Examines G.E.M. Anscombe's influential critique of modern moral philosophy and her call to revive Aristotelian virtue ethics."),
            ("MacIntyre's After Virtue and the Practice Tradition", "Studies Alasdair MacIntyre's argument that moral language has become fragmented and his proposal to ground virtue in social practices and traditions."),
            ("Functionalism and the Philosophy of Mind", "Introduces functionalism, the view that mental states are defined by their causal roles rather than by their physical substrate."),
            ("The Chinese Room Argument (Searle)", "Presents John Searle's thought experiment challenging the claim that symbol manipulation alone can constitute genuine understanding."),
            ("Qualia and the Hard Problem of Consciousness", "Examines subjective qualitative experience, or qualia, and David Chalmers' distinction between the easy and hard problems of consciousness."),
            ("Introduction to Phenomenology: Husserl's Method", "Introduces Edmund Husserl's method of describing conscious experience through the phenomenological reduction and the concept of intentionality."),
            ("Heidegger's Being and Time: Dasein and Being-in-the-World", "Examines Heidegger's analysis of human existence, or Dasein, as always already situated in a meaningful world."),
            ("Merleau-Ponty and Embodied Perception", "Studies Maurice Merleau-Ponty's account of perception as grounded in the lived, embodied experience of the perceiving subject."),
            ("Feminist Critiques of the Social Contract Tradition", "Examines feminist critiques arguing that classical social contract theory obscures gender-based domination in the private sphere."),
            ("Simone de Beauvoir and The Second Sex", "Studies Beauvoir's analysis of woman as historically constructed 'Other' and her claim that one is not born, but becomes, a woman."),
            ("Care Ethics as an Alternative to Justice-Based Theories", "Introduces care ethics, developed by thinkers like Carol Gilligan and Nel Noddings, as an approach centering relationships and responsiveness to need."),
        ],
        "UG3": [
            ("Externalism vs. Internalism about Justification", "Compares internalist views that justification depends on factors accessible to the believer with externalist views that justification can depend on external factors like reliability."),
            ("Reliabilism and the Sources of Knowledge", "Examines reliabilist theories that define knowledge in terms of belief produced by a reliable cognitive process."),
            ("The Regress Problem and Infinitism", "Presents the epistemic regress problem and examines infinitism, the minority view that justification can rest on an infinite chain of reasons."),
            ("Modal Metaphysics: Possible Worlds", "Introduces possible-worlds semantics as a framework for analyzing necessity, possibility, and counterfactual claims."),
            ("Identity Over Time: The Ship of Theseus", "Uses the classical puzzle of the Ship of Theseus to examine what it takes for an object to remain the same thing through change."),
            ("Universals and Particulars: Realism vs. Nominalism", "Examines the metaphysical dispute over whether general properties, or universals, exist independently of the particular things that have them."),
            ("Causation: Regularity, Counterfactual, and Process Theories", "Compares major theories of causation, including Humean regularity accounts, counterfactual theories, and physical process theories."),
            ("Popper's Falsificationism", "Studies Karl Popper's proposal that falsifiability, rather than verification, is the criterion that distinguishes scientific theories."),
            ("Kuhn's Structure of Scientific Revolutions and Paradigm Shifts", "Examines Thomas Kuhn's account of normal science, anomaly, and revolutionary paradigm shifts in the history of science."),
            ("The Demarcation Problem in Philosophy of Science", "Explores attempts to draw a principled line between science and pseudoscience, and difficulties facing each proposed criterion."),
            ("Scientific Realism vs. Anti-Realism", "Compares realist views that successful theories are approximately true descriptions of an unobservable world with anti-realist alternatives."),
            ("Confucian Ethics and the Cultivation of Virtue", "Introduces Confucius's teachings on ren, li, and the cultivation of virtue through relationships and ritual propriety."),
            ("Daoism: Laozi, Zhuangzi, and the Concept of Wu Wei", "Examines Daoist texts attributed to Laozi and Zhuangzi and the ideal of wu wei, or effortless action in accordance with the Dao."),
            ("Buddhist Philosophy: The Four Noble Truths and Non-Self", "Introduces the Buddha's Four Noble Truths and the doctrine of anatta, or non-self, as central to Buddhist philosophy."),
            ("Nagarjuna and Madhyamaka Buddhism", "Studies Nagarjuna's Madhyamaka philosophy of emptiness (sunyata) and its method of the middle way between existence and non-existence."),
            ("Comparative Philosophy: Confucianism and Aristotelian Ethics", "Compares Confucian virtue cultivation with Aristotelian virtue ethics, examining shared concerns and key differences in method and metaphysics."),
            ("Indian Philosophy: The Nyaya School of Logic", "Introduces the Nyaya school's system of logic and epistemology, including its theory of valid means of knowledge (pramana)."),
            ("Advaita Vedanta and the Concept of Brahman", "Examines Shankara's non-dualist Advaita Vedanta and its claim that the individual self (atman) is ultimately identical with Brahman."),
        ],
        "UG4": [
            ("Kant's Critique of Judgment and the Sublime", "Studies Kant's aesthetic theory of disinterested judgment and his distinction between the beautiful and the sublime."),
            ("Hume on Taste and Aesthetic Standards", "Examines Hume's essay on the standard of taste and his attempt to reconcile aesthetic relativism with genuine critical standards."),
            ("The Institutional Theory of Art (Danto, Dickie)", "Introduces the view that an object's status as art depends on its position within an institutional artworld, as argued by Arthur Danto and George Dickie."),
            ("Formalism vs. Expressionism in Aesthetics", "Compares formalist theories that locate artistic value in formal properties with expressionist theories that locate it in the expression of emotion."),
            ("Wittgenstein's Tractatus and the Picture Theory of Meaning", "Examines the early Wittgenstein's claim that meaningful propositions picture possible states of affairs in the world."),
            ("Kripke's Naming and Necessity: Rigid Designators", "Studies Saul Kripke's argument that proper names are rigid designators and its consequences for theories of reference and necessity."),
            ("The Problem of Vagueness in Language", "Examines the sorites paradox and competing philosophical accounts of vague predicates like 'tall' or 'bald.'"),
            ("Pascal's Wager and Decision-Theoretic Arguments for God", "Analyzes Pascal's pragmatic argument for believing in God based on expected outcomes rather than evidence."),
            ("The Problem of Divine Hiddenness", "Examines the argument that a loving God's hiddenness from reasonable non-believers counts as evidence against God's existence."),
            ("Religious Pluralism and Exclusivism", "Compares exclusivist, inclusivist, and pluralist positions on the relationship between different religious traditions' truth claims."),
            ("Principles of Biomedical Ethics: Autonomy and Beneficence", "Introduces the Beauchamp and Childress framework of autonomy, beneficence, nonmaleficence, and justice used in medical ethics."),
            ("The Ethics of Euthanasia and End-of-Life Care", "Examines arguments for and against physician-assisted death and the moral distinctions drawn between killing and letting die."),
            ("Reproductive Ethics and the Moral Status of the Fetus", "Surveys philosophical positions on the moral status of the fetus and their bearing on debates about abortion."),
            ("Environmental Ethics: Anthropocentrism vs. Ecocentrism", "Compares human-centered ethical frameworks with ecocentric approaches that extend moral consideration to ecosystems."),
            ("Deep Ecology and the Land Ethic", "Examines Arne Naess's deep ecology and Aldo Leopold's land ethic as frameworks for valuing the natural world beyond human interests."),
            ("Animal Ethics: Singer, Regan, and Moral Status", "Compares Peter Singer's utilitarian argument against speciesism with Tom Regan's rights-based case for the moral status of animals."),
            ("Feminist Epistemology and Standpoint Theory", "Examines feminist arguments that knowledge is shaped by social position and that marginalized standpoints can offer epistemic advantages."),
            ("Intersectionality as a Philosophical Framework", "Introduces Kimberlé Crenshaw's concept of intersectionality and its philosophical implications for theorizing overlapping forms of oppression."),
        ],
        "M1": [
            ("Advanced Modal Logic and Possible Worlds Semantics", "Develops the formal semantics of modal logic, including accessibility relations between possible worlds and systems such as S4 and S5."),
            ("Gödel's Incompleteness Theorems and Their Philosophical Implications", "Examines Kurt Gödel's incompleteness theorems and their implications for the limits of formal systems and mathematical knowledge."),
            ("Quine's 'Two Dogmas of Empiricism' and the Analytic-Synthetic Distinction", "Studies W.V.O. Quine's challenge to the analytic-synthetic distinction and to reductionism in empiricist philosophy."),
            ("Sellars and the Myth of the Given", "Examines Wilfrid Sellars's critique of the idea that sensory experience can justify beliefs without conceptual mediation."),
            ("Davidson's Theory of Radical Interpretation", "Studies Donald Davidson's account of how an interpreter could assign meaning to an unknown speaker's utterances from scratch."),
            ("Contemporary Debates in Personal Identity: Parfit's Reductionism", "Examines Derek Parfit's reductionist view that personal identity is not what fundamentally matters in survival."),
            ("The Metaphysics of Time: Presentism vs. Eternalism", "Compares presentist views that only the present moment exists with eternalist 'block universe' views on which past, present, and future are equally real."),
            ("Advanced Philosophy of Mind: The Extended Mind Thesis", "Examines Andy Clark and David Chalmers's argument that cognitive processes can extend beyond the brain into tools and the environment."),
            ("Consciousness and the Explanatory Gap", "Studies Joseph Levine's argument that there remains an explanatory gap between physical brain processes and subjective conscious experience."),
            ("Levinas and the Ethics of the Other", "Examines Emmanuel Levinas's claim that ethics arises from the face-to-face encounter with the irreducible Other."),
            ("Foucault: Power, Knowledge, and Discourse", "Studies Michel Foucault's analysis of how power and knowledge are intertwined in institutions and discursive practices."),
            ("Derrida and Deconstruction", "Introduces Jacques Derrida's deconstructive method of reading texts against their own stated hierarchies and oppositions."),
            ("Habermas and Communicative Rationality", "Examines Jürgen Habermas's theory of communicative action and the ideal of rational consensus reached through undistorted dialogue."),
            ("Contemporary Political Philosophy: Cosmopolitanism vs. Nationalism", "Compares cosmopolitan theories of global obligation with nationalist arguments for the moral priority of compatriots."),
            ("Global Justice and the Ethics of Immigration", "Examines philosophical arguments concerning states' obligations to admit migrants and refugees across borders."),
            ("Advanced Bioethics: Genetic Enhancement and Justice", "Studies debates over genetic enhancement technologies and their implications for equality, justice, and human nature."),
            ("Philosophy of Artificial Intelligence and Machine Consciousness", "Examines whether artificial systems could possess genuine understanding or consciousness, and the philosophical criteria at stake."),
            ("Research Seminar: Constructing an Original Philosophical Argument", "A capstone seminar guiding students through selecting a research question, engaging the literature, and constructing an original, well-defended philosophical argument."),
        ],
    },
    "Art History": {
        "C1": [
            ("Cave Art of Lascaux and Altamira", "Examines the Paleolithic cave paintings at Lascaux and Altamira and theories about their symbolic and ritual functions."),
            ("The Venus Figurines of the Paleolithic", "Studies small carved female figures such as the Venus of Willendorf and debates over their possible fertility or ritual significance."),
            ("Neolithic Megaliths: Stonehenge and Passage Tombs", "Surveys Neolithic monumental architecture, including Stonehenge and passage tombs, and their likely astronomical and ceremonial roles."),
            ("Art of Ancient Mesopotamia: Ziggurats and Cylinder Seals", "Introduces Sumerian and Babylonian art, including ziggurat architecture and the carved cylinder seals used to mark ownership."),
            ("Egyptian Art: Conventions of the Canon", "Explains the stylized conventions of composite perspective, scale, and pose that governed ancient Egyptian representation of the human figure."),
            ("The Pyramids of Giza and Old Kingdom Sculpture", "Examines the construction and function of the Giza pyramids alongside Old Kingdom royal and funerary sculpture."),
            ("Egyptian Funerary Art and the Book of the Dead", "Studies the tomb paintings, sarcophagi, and illustrated Book of the Dead papyri created to guide the deceased through the afterlife."),
            ("Minoan and Mycenaean Art of the Aegean", "Compares the naturalistic frescoes of Minoan Crete with the fortified palaces and gold work of Mycenaean Greece."),
            ("Greek Vase Painting: Black-Figure and Red-Figure Techniques", "Explains the technical processes and stylistic evolution of black-figure and red-figure Greek pottery decoration."),
            ("The Parthenon and Classical Greek Architecture", "Examines the design, proportions, and sculptural program of the Parthenon as the culmination of classical Greek temple architecture."),
            ("Greek Sculpture: From Kouros to Contrapposto", "Traces the development of Greek figural sculpture from the rigid Archaic kouros to the naturalistic weight-shift of contrapposto."),
            ("Hellenistic Sculpture: The Laocoön and Pergamon Altar", "Studies the dramatic emotion and dynamic movement of Hellenistic sculpture through works like the Laocoön group and the Pergamon Altar frieze."),
            ("Etruscan Art and Its Influence on Rome", "Examines Etruscan tomb painting and sculpture and its influence on the artistic traditions of early Rome."),
            ("Roman Portraiture and Realism", "Studies the veristic realism of Roman portrait sculpture and its role in commemorating ancestors and political figures."),
            ("Roman Engineering in Art: The Colosseum and Pantheon", "Examines how Roman advances in concrete and the arch shaped the design of the Colosseum and the Pantheon's coffered dome."),
            ("Pompeii and Roman Wall Painting", "Studies the four styles of Roman wall painting preserved at Pompeii and Herculaneum by the eruption of Vesuvius."),
            ("Formal Analysis: How to Look at a Work of Art", "Teaches the method of formal analysis, describing line, color, composition, and form as a foundation for interpreting any artwork."),
            ("Iconography: Reading Symbols in Visual Art", "Introduces iconographic analysis, the study of subject matter and symbolism, as a tool for decoding meaning in visual art."),
        ],
        "C2": [
            ("Early Christian Art and Catacomb Painting", "Examines the earliest Christian visual art, including symbolic imagery painted in the Roman catacombs."),
            ("Byzantine Mosaics: Ravenna and Hagia Sophia", "Studies the glittering mosaic decoration of Byzantine churches at Ravenna and the Hagia Sophia in Constantinople."),
            ("Iconoclasm and the Byzantine Icon Tradition", "Examines the Byzantine Iconoclastic controversy over religious images and the theology underlying the veneration of icons."),
            ("Carolingian and Ottonian Art", "Surveys the revival of classical and Christian artistic traditions under the Carolingian and Ottonian dynasties in early medieval Europe."),
            ("Romanesque Architecture and Pilgrimage Churches", "Examines the thick walls, rounded arches, and sculptural portals of Romanesque churches built along medieval pilgrimage routes."),
            ("Gothic Cathedrals: Chartres and the Rise of Stained Glass", "Studies the pointed arch, ribbed vault, and flying buttress of Gothic cathedrals like Chartres, and the luminous role of stained glass."),
            ("Gothic Sculpture and the Humanization of Form", "Traces the shift from rigid Romanesque figures to the more naturalistic, humanized sculpture of the Gothic period."),
            ("Illuminated Manuscripts of the Middle Ages", "Examines the production and decoration of illuminated manuscripts, from monastic scriptoria to books of hours."),
            ("Giotto and the Origins of Renaissance Naturalism", "Studies Giotto's Arena Chapel frescoes as a turning point toward greater naturalism and emotional depth in Western painting."),
            ("Brunelleschi and Linear Perspective", "Examines Filippo Brunelleschi's development of linear perspective and its transformative effect on Renaissance pictorial space."),
            ("Masaccio and the Florentine Renaissance", "Studies Masaccio's application of perspective and weighty, sculptural figures in early Florentine Renaissance painting."),
            ("Botticelli and Neoplatonism in Florentine Painting", "Examines Sandro Botticelli's mythological paintings, such as The Birth of Venus, in light of Florentine Neoplatonic philosophy."),
            ("Leonardo da Vinci: Sfumato and Scientific Observation", "Studies Leonardo's sfumato technique and his integration of anatomical and scientific observation into his painting practice."),
            ("Michelangelo: The Sistine Chapel Ceiling", "Examines the design, iconography, and technique of Michelangelo's Sistine Chapel ceiling frescoes."),
            ("Raphael and the High Renaissance School of Athens", "Studies Raphael's School of Athens fresco as a synthesis of classical philosophy and High Renaissance compositional harmony."),
            ("Titian and Venetian Colorito", "Examines Titian's mastery of color and loose brushwork, characteristic of the Venetian colorito tradition, in contrast to Florentine disegno."),
            ("Northern Renaissance: Jan van Eyck and Oil Painting Technique", "Studies Jan van Eyck's pioneering use of oil glazes and meticulous detail in Northern Renaissance panel painting."),
            ("Dürer and the Printmaking Revolution", "Examines Albrecht Dürer's technical mastery of engraving and woodcut and prints' role in spreading Renaissance imagery."),
        ],
        "UG1": [
            ("Caravaggio and Tenebrism", "Studies Caravaggio's dramatic use of tenebrism, extreme light-dark contrast, and his naturalistic, unidealized figures."),
            ("Bernini and Baroque Sculpture", "Examines Gian Lorenzo Bernini's dynamic, theatrical sculpture and its role in defining Roman Baroque art."),
            ("Rubens and the Flemish Baroque", "Studies Peter Paul Rubens's energetic compositions, rich color, and diplomatic role in the Flemish Baroque."),
            ("Velázquez and Spanish Golden Age Painting", "Examines Diego Velázquez's court portraiture and his masterwork Las Meninas within the Spanish Golden Age."),
            ("Rembrandt and Dutch Golden Age Portraiture", "Studies Rembrandt's psychological depth and mastery of light in portraiture and group works like The Night Watch."),
            ("Vermeer and Domestic Genre Painting", "Examines Johannes Vermeer's quiet domestic interiors and his subtle handling of light within Dutch genre painting."),
            ("Watteau and the Fête Galante", "Studies Jean-Antoine Watteau's invention of the fête galante, a genre depicting elegant figures in idyllic outdoor settings."),
            ("Fragonard and Rococo Sensibility", "Examines Jean-Honoré Fragonard's playful, sensuous style as characteristic of the French Rococo."),
            ("Neoclassicism: David and Revolutionary Painting", "Studies Jacques-Louis David's austere Neoclassical style and its use to promote civic virtue during the French Revolution."),
            ("Goya: From Court Painter to Social Critic", "Traces Francisco Goya's career from royal portraitist to the dark social critique of works like The Disasters of War."),
            ("Romanticism: Delacroix and Géricault", "Examines Eugène Delacroix's and Théodore Géricault's dramatic, emotionally charged approach to Romantic painting."),
            ("Turner and the Sublime in Landscape", "Studies J.M.W. Turner's atmospheric landscapes and his evocation of the sublime through light and turbulent weather."),
            ("The Barbizon School and Plein Air Painting", "Examines the Barbizon School's practice of painting rural landscapes directly from nature, anticipating Impressionist methods."),
            ("Courbet and Realism", "Studies Gustave Courbet's Realist commitment to depicting ordinary contemporary life without idealization."),
            ("Manet and the Scandal of Modern Life", "Examines Édouard Manet's controversial paintings, such as Olympia, that challenged academic conventions of subject and style."),
            ("Impressionism: Monet and the Painting of Light", "Studies Claude Monet's technique of capturing fleeting effects of light and atmosphere through broken brushwork and color."),
            ("Degas and Movement in Impressionist Composition", "Examines Edgar Degas's innovative, asymmetrical compositions depicting dancers and modern urban leisure."),
            ("Post-Impressionism: Cézanne's Structural Innovation", "Studies Paul Cézanne's analytical approach to form and structure, which laid groundwork for Cubism."),
        ],
        "UG2": [
            ("Van Gogh and Expressive Color", "Examines Vincent van Gogh's expressive, symbolic use of color and vigorous brushwork in works like The Starry Night."),
            ("Gauguin and Primitivism in Modern Art", "Studies Paul Gauguin's flattened forms and engagement with Tahitian subjects within the problematic frame of primitivism."),
            ("Fauvism: Matisse and the Wild Beasts", "Examines Henri Matisse's Fauvist use of bold, non-naturalistic color, a style that earned the group the label 'wild beasts.'"),
            ("Cubism: Picasso, Braque, and the Fracturing of Form", "Studies how Pablo Picasso and Georges Braque fractured objects into geometric facets viewed from multiple angles simultaneously."),
            ("Futurism and the Aesthetics of Speed", "Examines the Italian Futurists' celebration of speed, technology, and dynamism as depicted in works by Umberto Boccioni."),
            ("German Expressionism: Die Brücke and Der Blaue Reiter", "Compares the two major German Expressionist groups and their use of distorted form and intense color to convey emotion."),
            ("Dada and the Readymade: Duchamp's Fountain", "Examines Marcel Duchamp's readymades, including Fountain, and the Dada movement's challenge to conventional definitions of art."),
            ("Surrealism: Dalí, Magritte, and the Unconscious", "Studies how Salvador Dalí and René Magritte drew on Freudian ideas of the unconscious and dreams to create Surrealist imagery."),
            ("Bauhaus: Art, Design, and Industry", "Examines the Bauhaus school's integration of fine art, craft, and industrial design under a unified functionalist philosophy."),
            ("Abstract Expressionism: Pollock and Action Painting", "Studies Jackson Pollock's drip technique and the gestural, physical process central to Abstract Expressionist action painting."),
            ("Rothko and Color Field Painting", "Examines Mark Rothko's large-scale color field paintings and their aim to evoke intense emotional and spiritual response."),
            ("Pop Art: Warhol and Mass Culture", "Studies Andy Warhol's appropriation of mass media and consumer imagery as central subjects of Pop Art."),
            ("Minimalism: Judd and the Object", "Examines Donald Judd's industrially fabricated, geometric objects and Minimalism's rejection of illusionism and expressive gesture."),
            ("Conceptual Art: Idea over Object", "Studies Conceptual Art's premise that the idea behind a work matters more than its physical execution, as in works by Sol LeWitt and Joseph Kosuth."),
            ("Land Art and Site-Specific Installation", "Examines large-scale earthworks like Robert Smithson's Spiral Jetty that use the landscape itself as artistic medium."),
            ("Postmodernism in Contemporary Art", "Surveys postmodern strategies of appropriation, pastiche, and skepticism toward artistic originality and grand narratives."),
            ("Feminist Art: Judy Chicago and The Dinner Party", "Studies Judy Chicago's The Dinner Party as a landmark feminist artwork reclaiming women's history through craft and symbolism."),
            ("Street Art and Graffiti as Contemporary Practice", "Examines the development of graffiti and street art from subcultural practice to recognized contemporary art form."),
        ],
        "UG3": [
            ("Chinese Landscape Painting and the Literati Tradition", "Studies the brush techniques and philosophical values of Chinese literati landscape painting from the Song dynasty onward."),
            ("Chinese Calligraphy as Visual Art", "Examines Chinese calligraphy as an art form in which brushwork, composition, and character carry aesthetic and expressive meaning."),
            ("Japanese Ukiyo-e and the Floating World", "Studies the woodblock print tradition of ukiyo-e, depicting the 'floating world' of Edo-period urban entertainment."),
            ("Japanese Zen Aesthetics: Wabi-Sabi and the Tea Ceremony", "Examines the Zen-influenced aesthetic of wabi-sabi, valuing imperfection and transience, as expressed in the Japanese tea ceremony."),
            ("Indian Temple Architecture and Sculpture", "Surveys the towering forms and elaborate sculptural programs of Hindu temple architecture in India."),
            ("Mughal Miniature Painting", "Studies the detailed, hybrid style of Mughal miniature painting that blended Persian, Indian, and European influences."),
            ("Buddhist Art of Southeast Asia: Angkor and Borobudur", "Examines the monumental Buddhist and Hindu-Buddhist temple complexes of Angkor in Cambodia and Borobudur in Java."),
            ("African Sculpture and the Benin Bronzes", "Studies the cast bronze plaques and sculptures of the Kingdom of Benin and their historical and ceremonial significance."),
            ("Yoruba Art and Ritual Objects", "Examines Yoruba sculpture, masks, and ritual objects and their role in religious and social life in West Africa."),
            ("Islamic Geometric Pattern and the Arabesque", "Studies the mathematical principles underlying Islamic geometric pattern and the flowing vegetal arabesque."),
            ("The Alhambra and Islamic Architectural Ornament", "Examines the Alhambra palace complex in Granada as a masterwork of Islamic architectural ornament and spatial design."),
            ("Persian Miniature Painting", "Studies the refined color, detail, and narrative technique of Persian manuscript illustration."),
            ("Aztec and Maya Monumental Art", "Surveys the pyramids, stelae, and relief sculpture of Aztec and Maya civilizations and their religious and calendrical functions."),
            ("Inca Textiles and Metalwork", "Examines the technical sophistication and symbolic importance of Inca weaving and precious-metal work."),
            ("Colonial Latin American Art and Casta Painting", "Studies the hybrid religious art of colonial Latin America and casta paintings depicting racial classification under Spanish rule."),
            ("Mexican Muralism: Rivera, Orozco, and Siqueiros", "Examines the large-scale public murals of Diego Rivera, José Clemente Orozco, and David Alfaro Siqueiros as vehicles for social and political messages."),
            ("Frida Kahlo and Latin American Surrealism", "Studies Frida Kahlo's deeply personal, symbolic paintings and her ambivalent relationship to the Surrealist label."),
            ("Oceanic Art: Polynesian and Aboriginal Traditions", "Surveys the carved, woven, and painted traditions of Polynesian and Australian Aboriginal art and their ceremonial functions."),
        ],
        "UG4": [
            ("Formalism and the Legacy of Clement Greenberg", "Examines critic Clement Greenberg's formalist argument that modern art's value lies in exploring the intrinsic properties of its medium."),
            ("Iconology: Erwin Panofsky's Method", "Studies Erwin Panofsky's three-tiered method of iconological analysis, moving from description to deep cultural interpretation."),
            ("Marxist Approaches to Art History", "Examines Marxist art historical methods that analyze artworks in relation to class, economic structure, and ideology."),
            ("Feminist Art History: Linda Nochlin's Question", "Studies Linda Nochlin's essay 'Why Have There Been No Great Women Artists?' and its impact on feminist art historical method."),
            ("Semiotics and the Reading of Images", "Introduces semiotic analysis of images as systems of signs, drawing on the work of theorists like Roland Barthes."),
            ("Postcolonial Theory in Art History", "Examines postcolonial critiques of Western art historical narratives and their treatment of colonized cultures' visual production."),
            ("The Museum as Institution: History and Critique", "Surveys the historical development of the public museum and critical perspectives on its role in shaping cultural authority."),
            ("Curatorial Practice and Exhibition Design", "Introduces the practical and conceptual work of curating exhibitions, including object selection, sequencing, and interpretive design."),
            ("Provenance Research and Restitution Debates", "Examines methods for tracing an artwork's ownership history and the ethical debates surrounding restitution of looted or displaced objects."),
            ("Principles of Art Conservation and Restoration", "Introduces the ethical principles and technical methods used to preserve and restore works of art."),
            ("Technical Art History: X-ray and Infrared Analysis", "Examines how technical imaging methods like X-radiography and infrared reflectography reveal an artwork's underdrawing and history."),
            ("The Invention of Photography: Daguerre and Talbot", "Studies the near-simultaneous invention of photographic processes by Louis Daguerre and William Henry Fox Talbot."),
            ("Photography as Documentary Practice", "Examines the tradition of documentary photography and its role in social reform and historical record."),
            ("Photography and Modernism: Stieglitz and Straight Photography", "Studies Alfred Stieglitz's advocacy for photography as a fine art and the straight photography movement's embrace of the medium's inherent qualities."),
            ("History of Architecture: From Vitruvius to Palladio", "Traces the classical architectural tradition from the Roman writer Vitruvius through the Renaissance work of Andrea Palladio."),
            ("Modernist Architecture: Le Corbusier and Mies van der Rohe", "Examines the functionalist principles of Le Corbusier and Ludwig Mies van der Rohe that defined modernist architecture."),
            ("Postmodern and Contemporary Architecture", "Surveys postmodern architecture's return to historical reference and ornament, and subsequent contemporary architectural directions."),
            ("Digital Humanities Methods in Art Historical Research", "Introduces digital tools such as image databases and spatial analysis used in contemporary art historical research."),
        ],
        "M1": [
            ("Connoisseurship and Its Critics", "Examines connoisseurship, the practice of attributing and dating artworks through close visual expertise, and critiques of its subjectivity."),
            ("The Social History of Art: T.J. Clark and Context", "Studies T.J. Clark's social art historical method, situating artworks within their political and economic context."),
            ("Global Art History: Decentering the Western Canon", "Examines efforts to write art history that decenters the traditional Western canon and incorporates global artistic traditions on equal terms."),
            ("Historiography of Art History as a Discipline", "Surveys the history of art history itself as an academic discipline, from Vasari to contemporary methodological debates."),
            ("The Sublime from Burke to Contemporary Theory", "Traces the concept of the sublime from Edmund Burke's aesthetic treatise through its reinterpretation in contemporary art theory."),
            ("Gender and the Gaze in Visual Culture", "Examines theories of the gendered gaze, including Laura Mulvey's concept of the male gaze, as applied to visual art."),
            ("Object Biography and Material Culture Studies", "Introduces the method of tracing an object's changing meanings and uses over its lifetime within material culture studies."),
            ("Art and Trauma: Memorial and Memory in Visual Culture", "Examines how memorials and artworks engage with collective trauma and the ethics of representing historical violence."),
            ("The Ethics of Repatriation and Cultural Heritage", "Studies contested claims over cultural heritage objects and the ethical and legal frameworks guiding repatriation decisions."),
            ("Digital Reconstruction and Virtual Museums", "Examines the use of 3D modeling and virtual reality to reconstruct lost sites and create accessible virtual museum experiences."),
            ("Archival Research Methods for Art Historians", "Introduces methods for locating, evaluating, and interpreting primary source documents in art historical archival research."),
            ("Patronage Networks in the Early Modern Art Market", "Examines how courts, guilds, and private patrons shaped artistic production and careers in the early modern period."),
            ("Contemporary Art Markets and Auction Economics", "Studies the economic structures of the contemporary art market, including galleries, auction houses, and pricing dynamics."),
            ("Biennials and the Globalization of Contemporary Art", "Examines how international biennials have shaped the global circulation and reception of contemporary art."),
            ("Art and Ecology: Environmental Themes in Contemporary Practice", "Surveys contemporary artists engaging with ecological crisis, sustainability, and the nonhuman environment."),
            ("New Media Art and the Digital Image", "Examines art practices using digital technology, video, and networked media, and questions of the digital image's status as art."),
            ("Writing an Art Historical Thesis: Method and Argument", "Guides the development of an original art historical argument, from research question through evidence-based written thesis."),
            ("Independent Research Project in Art History", "A capstone independent research project in which students investigate a work, artist, or movement in depth using primary and secondary sources."),
        ],
    },
    "Python": {
        "C1": [
            ("Variables, Naming, and Python's Dynamic Typing", "Introduces variable assignment, naming conventions, and how Python's dynamic typing lets a variable's type be determined at runtime."),
            ("Numeric Types and Arithmetic Operators", "Covers Python's integer, float, and complex number types and the arithmetic operators used to manipulate them."),
            ("Strings and String Methods", "Introduces the string type and built-in methods for manipulating text, such as split, join, and replace."),
            ("String Formatting with f-strings", "Explains how to embed expressions inside string literals using f-strings for readable, efficient string formatting."),
            ("Booleans and Comparison Operators", "Covers the Boolean type and the comparison and logical operators used to build conditional expressions."),
            ("if/elif/else Conditional Logic", "Explains how to branch program execution based on conditions using if, elif, and else statements."),
            ("for Loops and the range() Function", "Introduces the for loop for iterating over sequences and the range() function for generating numeric sequences."),
            ("while Loops and Loop Control (break, continue)", "Covers the while loop for condition-based repetition and the break and continue statements for controlling loop flow."),
            ("Writing Your First Functions", "Introduces defining functions with def, passing parameters, and returning values."),
            ("Function Arguments: Positional, Keyword, and Default Values", "Explains the different ways arguments can be passed to a function, including positional, keyword, and default arguments."),
            ("Variable Scope: Local vs. Global", "Explains how variable scope determines where a name is visible within a program, and the global keyword's role."),
            ("Lists: Creation, Indexing, and Slicing", "Covers creating lists, accessing elements by index, and extracting sublists using slice notation."),
            ("Tuples and Immutability", "Introduces the tuple type and explains the significance of immutability for data that should not change."),
            ("Dictionaries: Keys, Values, and Lookup", "Covers the dictionary type for storing key-value pairs and efficient lookup by key."),
            ("Sets and Set Operations", "Introduces the set type and operations such as union, intersection, and difference for working with unique collections."),
            ("Nested Data Structures", "Explains how lists, dictionaries, and tuples can be combined into nested structures to represent complex data."),
            ("Input and Output with print() and input()", "Covers basic console input and output using the print() and input() functions."),
            ("Debugging Basics with print() and the Python Debugger", "Introduces basic debugging techniques, from print statements to using Python's built-in pdb debugger."),
        ],
        "C2": [
            ("List Comprehensions", "Teaches the list comprehension syntax for concisely constructing new lists from existing iterables."),
            ("Dictionary and Set Comprehensions", "Extends comprehension syntax to dictionaries and sets for concise construction of key-value and unique-element collections."),
            ("Iterables and the Iterator Protocol", "Explains the distinction between iterables and iterators and how Python's iterator protocol powers for loops."),
            ("Generators and the yield Keyword", "Introduces generator functions that use yield to produce values lazily, one at a time."),
            ("Classes and Instances in Python", "Covers defining classes with the class keyword and creating instances that hold their own state."),
            ("Instance Attributes vs. Class Attributes", "Distinguishes attributes unique to each instance from attributes shared across all instances of a class."),
            ("Inheritance and Method Overriding", "Explains how subclasses inherit behavior from parent classes and override methods to customize it."),
            ("Polymorphism in Python", "Covers how objects of different types can be used interchangeably through a shared interface or method name."),
            ("Encapsulation and Property Decorators", "Introduces the @property decorator for controlling access to an object's attributes while preserving a simple interface."),
            ("Magic Methods and Operator Overloading", "Explains how dunder methods like __add__ and __str__ let custom classes support built-in operators and functions."),
            ("Composition vs. Inheritance", "Compares building classes by composing other objects versus inheriting from a base class, and when each is preferable."),
            ("Abstract Base Classes", "Introduces the abc module for defining abstract base classes that enforce a common interface across subclasses."),
            ("Working with Modules and Imports", "Explains how to organize code into modules and the different forms of the import statement."),
            ("Organizing Code into Packages", "Covers structuring related modules into packages using __init__.py and relative imports."),
            ("Reading and Writing Text Files", "Introduces the open() function and file modes for reading from and writing to text files."),
            ("Working with CSV Files", "Covers reading and writing comma-separated value files using Python's built-in csv module."),
            ("Working with JSON Data", "Introduces the json module for parsing JSON data into Python objects and serializing Python objects back to JSON."),
            ("Exception Types and the Exception Hierarchy", "Surveys Python's built-in exception classes and how they are organized into an inheritance hierarchy."),
        ],
        "UG1": [
            ("try/except/else/finally in Depth", "Explains the full try statement, including the else and finally clauses and how they structure exception handling."),
            ("Custom Exception Classes", "Covers defining custom exception classes by subclassing Exception to signal domain-specific error conditions."),
            ("Context Managers and the with Statement", "Explains how the with statement uses context managers to guarantee setup and teardown, such as closing a file."),
            ("Writing Your Own Context Managers", "Covers implementing custom context managers using the __enter__/__exit__ methods or the contextlib module."),
            ("The collections Module: Counter, defaultdict, namedtuple", "Introduces specialized container types from the collections module, including Counter, defaultdict, and namedtuple."),
            ("The itertools Module for Efficient Iteration", "Covers itertools functions like chain, product, and groupby for building efficient, memory-conscious iteration pipelines."),
            ("The functools Module: reduce, lru_cache, partial", "Introduces functools utilities including reduce for aggregation, lru_cache for memoization, and partial for pre-filling arguments."),
            ("Working with Dates and Times (datetime module)", "Covers representing, formatting, and performing arithmetic on dates and times with the datetime module."),
            ("Regular Expressions with the re Module", "Introduces pattern matching and text extraction using Python's re module for regular expressions."),
            ("The os and pathlib Modules for File Systems", "Compares the traditional os module with the modern, object-oriented pathlib module for file system operations."),
            ("The argparse Module for Command-Line Arguments", "Covers using argparse to define and parse command-line arguments for a Python script."),
            ("Logging in Python Applications", "Introduces the logging module for recording diagnostic information at different severity levels instead of using print statements."),
            ("Unit Testing Fundamentals with unittest", "Introduces Python's built-in unittest framework for writing and organizing automated test cases."),
            ("Introduction to pytest and Test Discovery", "Covers the pytest framework's simpler syntax and automatic test discovery compared to unittest."),
            ("Writing Assertions and Test Fixtures", "Explains how to write effective test assertions and use pytest fixtures to set up reusable test state."),
            ("Mocking and Patching in Tests", "Introduces the unittest.mock module for replacing dependencies with mock objects during testing."),
            ("Type Hints and Static Type Checking with mypy", "Covers adding type hints to Python code and using mypy to catch type errors before runtime."),
            ("Code Style and Linting (PEP 8, flake8)", "Introduces the PEP 8 style guide and linting tools like flake8 for maintaining consistent, readable code."),
        ],
        "UG2": [
            ("Decorators: Wrapping Functions", "Explains how decorators wrap a function to add behavior before or after it runs, without modifying its source."),
            ("Decorators with Arguments", "Covers writing decorators that themselves accept arguments, requiring an additional layer of function nesting."),
            ("Class Decorators and functools.wraps", "Introduces decorators implemented as classes and explains why functools.wraps preserves a wrapped function's metadata."),
            ("Generator Expressions vs. List Comprehensions", "Compares the lazy evaluation of generator expressions with the eager evaluation of list comprehensions."),
            ("Coroutines and Generator-Based Concurrency", "Introduces generator-based coroutines and how they laid the groundwork for Python's async/await syntax."),
            ("Creating and Managing Virtual Environments with venv", "Covers creating isolated Python environments with venv to manage project-specific dependencies."),
            ("Dependency Management with pip and requirements.txt", "Explains installing packages with pip and pinning dependencies in a requirements.txt file for reproducible environments."),
            ("Introduction to Poetry for Python Packaging", "Introduces Poetry as a modern tool for dependency management and packaging that replaces manual requirements files."),
            ("Structuring a Python Package for Distribution", "Covers the directory layout, pyproject.toml, and metadata needed to structure a Python package for distribution."),
            ("Publishing a Package to PyPI", "Explains the steps for building and uploading a Python package to the Python Package Index."),
            ("Making HTTP Requests with the requests Library", "Introduces the requests library for sending HTTP GET and POST requests and handling responses."),
            ("Working with REST APIs and JSON Responses", "Covers consuming REST APIs, including handling JSON payloads and interpreting HTTP status codes."),
            ("Authentication in API Requests (API Keys, OAuth)", "Explains common API authentication schemes, including API keys and OAuth token flows."),
            ("Rate Limiting and Error Handling for APIs", "Covers handling API rate limits, retries, and errors gracefully when consuming external services."),
            ("Parsing HTML with BeautifulSoup", "Introduces the BeautifulSoup library for parsing HTML and extracting data from web pages."),
            ("Web Scraping Ethics and robots.txt", "Explains the legal and ethical considerations of web scraping, including how to respect a site's robots.txt policy."),
            ("Building a Simple Web Scraper Project", "Guides building an end-to-end web scraper that requests pages, parses content, and stores extracted data."),
            ("Working with Environment Variables and Configuration", "Covers managing application configuration and secrets using environment variables and configuration files."),
        ],
        "UG3": [
            ("Introduction to NumPy Arrays", "Introduces the NumPy ndarray, its creation, and how it differs from a native Python list."),
            ("NumPy Array Broadcasting and Vectorization", "Explains broadcasting rules and vectorized operations that let NumPy avoid explicit Python loops for elementwise computation."),
            ("NumPy Indexing, Slicing, and Boolean Masks", "Covers advanced indexing techniques in NumPy, including slicing and filtering arrays with Boolean masks."),
            ("Linear Algebra Operations with NumPy", "Introduces matrix multiplication, transposition, and other linear algebra operations available in NumPy."),
            ("Introduction to pandas Series and DataFrames", "Introduces the pandas Series and DataFrame as the core one- and two-dimensional labeled data structures."),
            ("Reading and Writing Data with pandas (CSV, Excel, SQL)", "Covers reading and writing tabular data from CSV files, Excel workbooks, and SQL databases using pandas."),
            ("Data Cleaning and Handling Missing Values in pandas", "Explains techniques for detecting and handling missing or malformed data within a pandas DataFrame."),
            ("GroupBy and Aggregation in pandas", "Covers the split-apply-combine pattern using pandas' groupby for computing grouped aggregations."),
            ("Merging and Joining DataFrames", "Explains how to combine multiple pandas DataFrames using merge, join, and concatenation operations."),
            ("Data Visualization with Matplotlib", "Introduces the Matplotlib library for creating line plots, bar charts, and scatter plots from Python data."),
            ("Building a Command-Line Interface with argparse", "Covers designing a structured command-line interface with subcommands and options using argparse."),
            ("Building a CLI with the click Library", "Introduces the click library as a decorator-based alternative to argparse for building command-line tools."),
            ("Packaging a CLI Tool as an Executable", "Explains how to package a Python CLI tool so it can be installed and run as a standalone command."),
            ("Test-Driven Development with pytest", "Introduces the test-driven development cycle of writing a failing test before implementing the corresponding code."),
            ("Parametrized Tests and Test Coverage", "Covers writing parametrized pytest tests to cover multiple input cases and measuring test coverage."),
            ("Continuous Integration for Python Projects", "Introduces setting up continuous integration pipelines that automatically run tests on each code change."),
            ("Profiling and Optimizing Python Code", "Covers identifying performance bottlenecks in Python code using profiling tools and applying targeted optimizations."),
            ("Working with SQLite Databases in Python", "Introduces the sqlite3 module for creating, querying, and updating a lightweight SQLite database from Python."),
        ],
        "UG4": [
            ("Threading in Python and the GIL", "Explains Python's threading module and how the Global Interpreter Lock affects the performance of multithreaded code."),
            ("Multiprocessing for CPU-Bound Tasks", "Covers the multiprocessing module for running CPU-bound work across multiple processes to bypass the GIL."),
            ("Introduction to asyncio and Coroutines", "Introduces the asyncio library and native coroutines for writing single-threaded concurrent I/O-bound code."),
            ("async/await Syntax in Depth", "Explains the async and await keywords in depth, including awaitable objects and the event loop that schedules them."),
            ("Concurrent Futures: ThreadPoolExecutor and ProcessPoolExecutor", "Covers the concurrent.futures module's high-level executor interfaces for thread- and process-based concurrency."),
            ("Queues and Producer-Consumer Patterns", "Introduces thread-safe queues for implementing producer-consumer patterns in concurrent Python programs."),
            ("Automating File System Tasks with Python", "Covers using Python to automate common file system tasks such as renaming, moving, and organizing files."),
            ("Automating Spreadsheet Tasks with openpyxl", "Introduces the openpyxl library for reading, writing, and automating tasks in Excel spreadsheets."),
            ("Automating Emails and Notifications", "Covers sending automated emails and notifications from Python scripts using the smtplib module and related libraries."),
            ("Scheduling Python Scripts with cron and Task Scheduler", "Explains how to schedule recurring execution of Python scripts using cron on Unix systems and Task Scheduler on Windows."),
            ("Web Automation with Selenium", "Introduces the Selenium library for automating interactions with web browsers, such as filling forms and clicking buttons."),
            ("Working with APIs for Automation Pipelines", "Covers chaining API calls together to build automation pipelines that move and transform data between services."),
            ("Building a Simple ETL Pipeline in Python", "Guides building a basic extract-transform-load pipeline that pulls data from a source, cleans it, and loads it into a destination."),
            ("Error Handling and Retry Logic in Automation Scripts", "Covers designing robust automation scripts with structured error handling and retry logic for transient failures."),
            ("Introduction to Flask for Web Applications", "Introduces the Flask microframework for building simple web applications and APIs in Python."),
            ("Introduction to Django's MVT Architecture", "Covers Django's model-view-template architecture and its built-in tools for building full-featured web applications."),
            ("Building REST APIs with FastAPI", "Introduces FastAPI for building modern, type-annotated REST APIs with automatic interactive documentation."),
            ("Database Integration with SQLAlchemy", "Covers using the SQLAlchemy ORM to map Python classes to database tables and query data using Python objects."),
        ],
        "M1": [
            ("Metaclasses and Class Creation in Python", "Explains metaclasses as the 'classes of classes' that control how Python classes themselves are created."),
            ("Descriptors and Attribute Access Protocols", "Introduces the descriptor protocol underlying properties and how it controls attribute access at a low level."),
            ("The Data Model: Dunder Methods in Depth", "Provides an in-depth tour of Python's data model and the dunder methods that let custom objects integrate with built-in syntax."),
            ("Memory Management and Garbage Collection in CPython", "Examines how CPython manages memory through reference counting and cyclic garbage collection."),
            ("Understanding the Global Interpreter Lock in Depth", "Provides a deeper technical examination of why CPython's Global Interpreter Lock exists and its practical performance implications."),
            ("Writing C Extensions for Python Performance", "Introduces writing C extensions to accelerate performance-critical sections of Python code."),
            ("Advanced Type Hints: Generics and Protocols", "Covers advanced typing features including generic types and structural typing with the Protocol class."),
            ("Structural Pattern Matching (match/case)", "Introduces Python's match/case statement for structural pattern matching introduced in Python 3.10."),
            ("Advanced asyncio: Event Loops and Tasks", "Examines the internals of the asyncio event loop and how tasks are scheduled and managed concurrently."),
            ("Building a Plugin Architecture in Python", "Covers designing an extensible application architecture that discovers and loads plugins dynamically."),
            ("Design Patterns in Python (Singleton, Factory, Observer)", "Introduces classic software design patterns, including Singleton, Factory, and Observer, implemented in idiomatic Python."),
            ("Advanced Testing Strategies: Property-Based Testing with Hypothesis", "Introduces property-based testing with the Hypothesis library, which generates test cases to find edge cases automatically."),
            ("Packaging for Multiple Platforms with Wheels", "Covers building platform-specific wheel packages to distribute Python software with compiled dependencies."),
            ("Performance Profiling with cProfile and line_profiler", "Covers detailed performance profiling using cProfile for function-level and line_profiler for line-level analysis."),
            ("Building a Machine Learning Pipeline with scikit-learn", "Introduces building an end-to-end machine learning pipeline for preprocessing, training, and evaluation with scikit-learn."),
            ("Deploying Python Applications with Docker", "Covers containerizing a Python application with Docker for consistent deployment across environments."),
            ("Code Review and Maintainability in Large Python Codebases", "Discusses practices for code review, documentation, and structuring large Python codebases for long-term maintainability."),
            ("Capstone: Designing and Building a Production-Ready Python Application", "A capstone project guiding students through designing, building, testing, and deploying a complete, production-ready Python application."),
        ],
    },
    "R": {
        "C1": [
            ("Installing R and RStudio: The Development Environment", "Covers installing R and RStudio and orienting to the panes and workflow of the RStudio integrated development environment."),
            ("R Syntax Basics: Assignment and Expressions", "Introduces basic R syntax, including the assignment operator and how expressions are evaluated."),
            ("Numeric, Character, and Logical Data Types", "Covers R's fundamental data types, including numeric, character, and logical values."),
            ("Vectors: Creation and Vectorized Operations", "Introduces the vector as R's core data structure and how operations are applied element-wise across a vector."),
            ("Indexing and Subsetting Vectors", "Covers accessing and extracting elements of a vector using positive, negative, and logical indexing."),
            ("Factors and Categorical Data in R", "Introduces the factor type for representing categorical data with a fixed set of levels."),
            ("Lists in R: Heterogeneous Collections", "Covers the list type, which can hold elements of different types and structures within a single object."),
            ("Matrices and Array Operations", "Introduces matrices and multi-dimensional arrays and the operations used to manipulate them in R."),
            ("Introduction to Data Frames", "Introduces the data frame as R's core structure for representing tabular data with columns of different types."),
            ("Reading Data into R with read.csv()", "Covers importing external data into R using base functions like read.csv()."),
            ("Missing Values and NA Handling in R", "Explains how R represents missing values with NA and how functions handle them by default."),
            ("Basic Arithmetic and Logical Operators in R", "Covers R's arithmetic and logical operators and how they behave when applied to vectors."),
            ("if/else Conditionals in R", "Introduces conditional branching in R using if and else statements."),
            ("for and while Loops in R", "Covers iteration in R using for loops over sequences and while loops based on a condition."),
            ("The apply Family of Functions", "Introduces sapply, lapply, and related apply functions as an alternative to explicit loops in R."),
            ("Writing Basic Functions in R", "Covers defining custom functions in R with the function keyword, including arguments and return values."),
            ("R Scripts vs. the R Console", "Explains the difference between working interactively in the R console and writing reusable R scripts."),
            ("Getting Help in R: Documentation and CRAN Task Views", "Covers using R's built-in help system and CRAN Task Views to find documentation and relevant packages."),
        ],
        "C2": [
            ("The Tidyverse Philosophy: Tidy Data Principles", "Introduces the tidyverse's principles of tidy data, in which each variable is a column and each observation is a row."),
            ("The Pipe Operator: %>% and |>", "Explains how the magrittr pipe and the native pipe chain function calls together for more readable data workflows."),
            ("tibbles vs. Base R Data Frames", "Compares the tibble, the tidyverse's modern data frame variant, with base R's traditional data.frame."),
            ("Introduction to ggplot2: The Grammar of Graphics", "Introduces ggplot2's layered grammar of graphics, building plots from data, aesthetics, and geometric objects."),
            ("Aesthetic Mappings and Geoms in ggplot2", "Covers mapping data variables to visual aesthetics and choosing geoms to represent them in ggplot2."),
            ("Faceting for Small Multiples in ggplot2", "Introduces facet_wrap and facet_grid for splitting a ggplot2 plot into small multiples by a grouping variable."),
            ("Scales, Themes, and Customizing ggplot2 Plots", "Covers customizing axis scales, color palettes, and overall plot appearance using ggplot2 themes."),
            ("Bar Charts, Histograms, and Boxplots in ggplot2", "Covers building common statistical chart types, including bar charts, histograms, and boxplots, using ggplot2."),
            ("Scatter Plots and Trend Lines in ggplot2", "Covers building scatter plots and overlaying fitted trend lines using ggplot2's geom_point and geom_smooth."),
            ("Saving and Exporting ggplot2 Visualizations", "Covers exporting ggplot2 plots to image files at appropriate resolution and size using ggsave()."),
            ("Reading Data with readr", "Introduces the readr package's fast, consistent functions for importing delimited text data into R."),
            ("Tidying Data with tidyr: Pivoting Wide and Long", "Covers reshaping data between wide and long formats using tidyr's pivot_longer and pivot_wider functions."),
            ("String Manipulation with stringr", "Introduces the stringr package's consistent functions for detecting, extracting, and modifying text strings."),
            ("Working with Factors Using forcats", "Covers the forcats package's tools for reordering, recoding, and managing categorical factor levels."),
            ("Iteration with purrr", "Introduces the purrr package's map functions as a tidyverse-consistent alternative to loops and the apply family."),
            ("Combining Data Frames: Joins in dplyr", "Covers combining related data frames using dplyr's join functions, including inner, left, and full joins."),
            ("Grouped Summaries with dplyr's group_by and summarize", "Introduces computing grouped summary statistics using dplyr's group_by and summarize verbs."),
            ("Filtering and Arranging Data with dplyr", "Covers selecting rows with filter and reordering rows with arrange using dplyr's core verbs."),
        ],
        "UG1": [
            ("Advanced Filtering with dplyr: Logical Conditions", "Covers building complex filtering conditions in dplyr using combinations of logical and comparison operators."),
            ("Mutating and Creating New Variables with dplyr", "Introduces dplyr's mutate verb for creating and transforming columns within a data frame."),
            ("Window Functions in dplyr", "Covers window functions such as row_number, lag, and lead for calculations that depend on row order within groups."),
            ("Descriptive Statistics in R: Mean, Median, Variance", "Introduces computing measures of central tendency and spread, such as mean, median, and variance, in R."),
            ("Probability Distributions in R", "Covers generating and evaluating common probability distributions in R using functions like dnorm, pnorm, and rnorm."),
            ("The Normal Distribution and qnorm/pnorm Functions", "Focuses on the normal distribution and R's d/p/q/r function family for its density, cumulative probability, and quantiles."),
            ("Sampling and the Central Limit Theorem in R", "Uses simulation in R to illustrate the central limit theorem and the behavior of sampling distributions."),
            ("Confidence Intervals in R", "Covers constructing and interpreting confidence intervals for population parameters using R."),
            ("Hypothesis Testing: The t-test in R", "Introduces conducting and interpreting one-sample and two-sample t-tests using R's t.test() function."),
            ("Chi-Squared Tests in R", "Covers conducting chi-squared tests of independence and goodness of fit using R's chisq.test() function."),
            ("ANOVA in R", "Introduces analysis of variance for comparing means across multiple groups using R's aov() function."),
            ("Correlation Analysis in R", "Covers measuring and testing the strength of linear association between variables using R's cor() and cor.test()."),
            ("Simple Linear Regression in R", "Introduces fitting and interpreting a simple linear regression model using R's lm() function."),
            ("Multiple Linear Regression in R", "Extends linear regression to multiple predictors and covers interpreting coefficients in a multiple regression model."),
            ("Regression Diagnostics in R", "Covers checking linear regression assumptions using residual plots, leverage, and influence diagnostics in R."),
            ("Nonparametric Tests in R", "Introduces nonparametric alternatives to standard tests, such as the Wilcoxon and Kruskal-Wallis tests, in R."),
            ("Power Analysis in R", "Covers computing statistical power and required sample size for a study design using R's pwr package."),
            ("Data Import from Excel and Other Formats", "Covers importing data into R from Excel, SPSS, and other common file formats using dedicated packages."),
        ],
        "UG2": [
            ("R Markdown Document Structure and YAML Headers", "Introduces the structure of an R Markdown document, including the YAML header that controls output settings."),
            ("Code Chunks and Chunk Options in R Markdown", "Covers embedding executable R code chunks in R Markdown and controlling their behavior with chunk options."),
            ("Parameterized Reports with R Markdown", "Introduces parameterized R Markdown reports that can be re-rendered with different input values."),
            ("Creating Presentations with R Markdown (ioslides/xaringan)", "Covers building slide presentations directly from R Markdown using formats like ioslides and xaringan."),
            ("Generating PDF and Word Reports from R Markdown", "Covers rendering R Markdown documents to PDF and Word output formats for sharing reproducible reports."),
            ("Writing Functions with Default and Variadic Arguments", "Covers writing R functions with default argument values and variadic arguments using the ... construct."),
            ("Anonymous Functions and Lambda Syntax in R", "Introduces anonymous functions in R, including the shorthand backslash lambda syntax introduced in recent R versions."),
            ("Recursion in R", "Covers writing recursive functions in R and the considerations involved in recursive versus iterative solutions."),
            ("Error Handling with tryCatch", "Introduces structured error handling in R using tryCatch to catch and respond to conditions and errors."),
            ("Debugging with browser() and traceback()", "Covers interactive debugging in R using the browser() function and diagnosing errors with traceback()."),
            ("Vectorization vs. Loops: Performance Considerations", "Compares the performance of vectorized operations against explicit loops in R and when each approach is appropriate."),
            ("Logistic Regression in R", "Introduces fitting and interpreting logistic regression models for binary outcomes using R's glm() function."),
            ("Generalized Linear Models in R", "Covers the generalized linear model framework in R, extending regression to non-normal response distributions."),
            ("Model Selection and AIC/BIC in R", "Introduces using information criteria such as AIC and BIC to compare and select among candidate statistical models in R."),
            ("Interaction Effects in Regression Models", "Covers specifying and interpreting interaction terms between predictors in an R regression model."),
            ("Working with Dates Using lubridate", "Introduces the lubridate package's functions for parsing, manipulating, and computing with dates and times."),
            ("Environment and Scoping Rules in R", "Explains R's environment model and lexical scoping rules that determine how variables are looked up."),
            ("Writing Modular R Scripts", "Covers organizing R code into modular, reusable scripts and functions rather than long monolithic files."),
        ],
        "UG3": [
            ("Finding and Evaluating Packages on CRAN", "Covers strategies for searching CRAN for relevant packages and evaluating their quality and maintenance status."),
            ("Installing Packages from GitHub with devtools", "Introduces installing R packages directly from GitHub repositories using the devtools package."),
            ("Package Dependencies and renv for Reproducibility", "Covers using the renv package to create reproducible, project-specific package environments in R."),
            ("Introduction to the caret Package", "Introduces the caret package's unified interface for training and evaluating machine learning models in R."),
            ("The tidymodels Framework for Modeling", "Covers the tidymodels collection of packages as a tidyverse-consistent framework for modeling workflows."),
            ("Train/Test Splits and Cross-Validation in R", "Introduces splitting data into training and test sets and using cross-validation to evaluate model performance in R."),
            ("Decision Trees and Random Forests in R", "Covers fitting decision tree and random forest models in R using packages like rpart and randomForest."),
            ("Support Vector Machines in R", "Introduces fitting support vector machine classifiers in R using the e1071 or kernlab packages."),
            ("k-Nearest Neighbors Classification in R", "Covers implementing k-nearest neighbors classification in R and choosing an appropriate value of k."),
            ("Clustering with k-means in R", "Introduces unsupervised k-means clustering in R and methods for choosing the number of clusters."),
            ("Principal Component Analysis in R", "Covers dimensionality reduction using principal component analysis in R and interpreting the resulting components."),
            ("Regularization: Ridge and Lasso Regression in R", "Introduces ridge and lasso regression as regularized alternatives to ordinary least squares, fit using R's glmnet package."),
            ("Model Evaluation Metrics in R (ROC, AUC, Confusion Matrix)", "Covers evaluating classification model performance in R using confusion matrices, ROC curves, and AUC."),
            ("Exporting Data to CSV, Excel, and Databases", "Covers writing R data frames out to CSV files, Excel workbooks, and relational databases."),
            ("Connecting R to SQL Databases with DBI", "Introduces the DBI package's standard interface for connecting R to and querying SQL databases."),
            ("Working with JSON and APIs in R (jsonlite, httr)", "Covers parsing JSON data with jsonlite and making HTTP requests to web APIs from R using httr."),
            ("Text Mining Basics in R", "Introduces basic text mining techniques in R, including tokenization and term-frequency analysis using the tidytext package."),
            ("Reproducible Research Workflows in R", "Covers practices and tools for building fully reproducible research workflows in R, from data to final report."),
        ],
        "UG4": [
            ("Time Series Objects in R (ts, xts, zoo)", "Introduces R's specialized time series classes, including ts, xts, and zoo, for representing time-indexed data."),
            ("Decomposing Time Series: Trend, Seasonality, Noise", "Covers decomposing a time series into trend, seasonal, and residual noise components in R."),
            ("ARIMA Models in R", "Introduces fitting autoregressive integrated moving average (ARIMA) models to time series data in R."),
            ("Forecasting with the forecast Package", "Covers generating and evaluating forecasts from fitted time series models using R's forecast package."),
            ("Exponential Smoothing Methods in R", "Introduces exponential smoothing methods, including Holt-Winters, for forecasting time series in R."),
            ("Introduction to Shiny: UI and Server Logic", "Introduces the Shiny framework's separation of user interface code from reactive server-side logic."),
            ("Reactive Programming in Shiny", "Covers Shiny's reactive programming model, in which outputs automatically update when their reactive inputs change."),
            ("Shiny Widgets and Input Controls", "Introduces the range of input widgets available in Shiny for collecting user input in an interactive application."),
            ("Deploying Shiny Applications", "Covers options for deploying a Shiny application, including shinyapps.io and self-hosted Shiny Server."),
            ("Building Dashboards with shinydashboard", "Introduces the shinydashboard package for building structured, dashboard-style layouts for Shiny applications."),
            ("R for Bioinformatics: Bioconductor Basics", "Introduces the Bioconductor project and its R packages for analyzing genomic and biological data."),
            ("Sequence Analysis in R", "Covers basic DNA and protein sequence analysis in R using Bioconductor packages like Biostrings."),
            ("R for Spatial Data and GIS (sf package)", "Introduces the sf package for representing and analyzing spatial vector data within R."),
            ("Mapping with leaflet in R", "Covers creating interactive web maps in R using the leaflet package."),
            ("R for Econometrics: Panel Data Models", "Introduces fitting panel data models, such as fixed and random effects, in R using the plm package."),
            ("R for Social Science Survey Analysis", "Covers analyzing complex survey data, including weighting, in R using the survey package."),
            ("Bayesian Statistics Basics in R", "Introduces basic Bayesian inference in R, including prior and posterior distributions and simple conjugate models."),
            ("Simulation Studies in R", "Covers designing and running Monte Carlo simulation studies in R to evaluate statistical methods."),
        ],
        "M1": [
            ("Advanced R: Environments and Closures", "Examines R's environment system in depth and how closures capture and retain access to enclosing variables."),
            ("Functional Programming Principles in R", "Introduces functional programming concepts in R, including first-class functions and avoiding side effects."),
            ("Writing Vectorized Custom Functions", "Covers designing custom R functions that operate efficiently on whole vectors rather than looping element by element."),
            ("Object-Oriented Programming in R: S3 Classes", "Introduces R's informal S3 object system and its method dispatch based on class attributes."),
            ("Object-Oriented Programming in R: S4 and R6 Classes", "Covers R's more formal S4 class system and the encapsulated, mutable R6 class system."),
            ("Unit Testing in R with testthat", "Introduces writing automated unit tests for R code using the testthat package."),
            ("Continuous Integration for R Packages", "Covers setting up continuous integration to automatically check and test an R package on each change."),
            ("Building and Documenting an R Package", "Guides the process of structuring, documenting, and building a complete R package using devtools and roxygen2."),
            ("Writing Package Vignettes", "Covers writing long-form vignette documentation that demonstrates how to use an R package."),
            ("Profiling R Code for Performance", "Introduces profiling tools such as profvis for identifying performance bottlenecks in R code."),
            ("Rcpp: Calling C++ from R", "Introduces the Rcpp package for writing performance-critical code in C++ and calling it seamlessly from R."),
            ("Parallel Computing in R (parallel, future)", "Covers parallelizing R computations across multiple cores using the parallel and future packages."),
            ("Memory Management and Large Datasets in R", "Examines strategies for working with datasets too large to fit comfortably in memory within R."),
            ("Debugging Complex R Programs", "Covers advanced debugging strategies for diagnosing errors in complex, multi-function R programs."),
            ("Version Control for R Projects with Git", "Introduces using Git for version control of R projects, including integration with RStudio."),
            ("Advanced Bayesian Modeling with Stan/brms", "Introduces fitting more advanced Bayesian models in R using the Stan probabilistic programming language via the brms package."),
            ("Reproducibility and the R Project Lifecycle", "Covers practices for managing an R project's full lifecycle to ensure long-term reproducibility of its results."),
            ("Capstone: An End-to-End R Data Analysis Report", "A capstone project guiding students through an end-to-end R data analysis, from data import to a polished reproducible report."),
        ],
    },
}
