"""Module topics for the college-subject expansion (batch A).

MODULES[subject][level] = list of 8 (title, summary) tuples.
Levels: C1, C2, UG1, UG2, UG3, UG4, M1, M2 (College 1-2, Undergrad 1-4, Masters 1-2).
"""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Environmental Science": {
        "C1": [
            ("Introduction to Environmental Science", "Surveys how the natural sciences combine to study the environment, and introduces the concepts of systems, sustainability, and human impact on the planet."),
            ("Ecosystems and Ecology Basics", "Explains how organisms interact with one another and their physical surroundings, covering food chains, food webs, and energy flow through trophic levels."),
            ("Biodiversity and Its Importance", "Introduces the concept of biological diversity at genetic, species, and ecosystem levels, and why it matters for ecological stability and human wellbeing."),
            ("The Water Cycle and Freshwater Resources", "Describes how water moves through evaporation, condensation, and precipitation, and outlines the distribution and importance of freshwater on Earth."),
            ("The Carbon Cycle", "Traces how carbon moves among the atmosphere, oceans, living organisms, and rocks, and how photosynthesis and respiration drive the cycle."),
            ("Introduction to Pollution", "Defines air, water, and soil pollution, identifies common pollutants and their sources, and describes basic effects on health and ecosystems."),
            ("Earth's Climate System Basics", "Introduces the components of the climate system, including the atmosphere, oceans, and land, and how solar energy and the greenhouse effect regulate temperature."),
            ("Natural Resources and Human Use", "Distinguishes renewable from nonrenewable resources and examines how human societies extract and consume materials and energy."),
        ],
        "C2": [
            ("Biogeochemical Cycles", "Examines the nitrogen, phosphorus, and sulfur cycles alongside carbon, showing how nutrients move between living and nonliving compartments of the biosphere."),
            ("Population Ecology and Growth", "Covers exponential and logistic growth models, carrying capacity, and the factors that regulate populations of organisms including humans."),
            ("Soil Science Fundamentals", "Introduces soil formation, horizons, texture, and fertility, and explains the role of soil in supporting plant life and filtering water."),
            ("Energy Resources and Fossil Fuels", "Surveys coal, oil, and natural gas formation and use, and introduces the environmental consequences of fossil fuel combustion."),
            ("Types and Sources of Pollution", "Distinguishes point and nonpoint sources and examines specific pollutants in air, water, and land along with their pathways and impacts."),
            ("Biomes of the World", "Describes major terrestrial and aquatic biomes, their climates, characteristic vegetation, and the organisms adapted to each."),
            ("Ecological Succession", "Explains how communities change over time through primary and secondary succession following disturbance, toward more stable configurations."),
            ("Human Population and the Environment", "Analyzes global population trends, demographic transition, and the pressures that a growing population places on natural systems."),
        ],
        "UG1": [
            ("Climate Change Science", "Examines the physical evidence for anthropogenic climate change, radiative forcing, greenhouse gas emissions, and observed impacts on the Earth system."),
            ("Atmospheric Chemistry", "Studies the composition and chemical reactions of the atmosphere, including ozone formation and depletion, smog, and aerosol processes."),
            ("Conservation Biology", "Introduces the scientific study of biodiversity loss and the strategies used to protect species, habitats, and genetic diversity."),
            ("Hydrology and Watersheds", "Covers the movement, distribution, and quality of water within watersheds, including runoff, groundwater, and streamflow processes."),
            ("Environmental Toxicology", "Studies how chemical pollutants affect living organisms, covering dose-response relationships, bioaccumulation, and biomagnification."),
            ("Ecological Field Methods", "Introduces techniques for sampling populations and communities, including quadrats, transects, mark-recapture, and biodiversity indices."),
            ("Environmental Economics", "Applies economic concepts such as externalities, public goods, and valuation to environmental problems and resource management."),
            ("Environmental Ethics and Policy", "Surveys ethical frameworks for human-environment relations and introduces how laws and institutions shape environmental decisions."),
        ],
        "UG2": [
            ("Environmental Impact Assessment", "Teaches the methods for predicting and evaluating the environmental consequences of proposed projects and the structure of an EIA process."),
            ("GIS and Remote Sensing", "Introduces geographic information systems and satellite-based remote sensing for mapping and analyzing environmental data across space and time."),
            ("Oceanography", "Examines the physical, chemical, and biological processes of the oceans, including currents, ocean chemistry, and marine ecosystems."),
            ("Waste Management and Engineering", "Covers the collection, treatment, and disposal of solid and hazardous waste, including landfills, recycling, and waste-to-energy systems."),
            ("Water and Wastewater Treatment", "Describes the physical, chemical, and biological processes used to purify drinking water and treat municipal and industrial wastewater."),
            ("Landscape Ecology", "Studies spatial patterns of ecosystems and how landscape structure, fragmentation, and connectivity influence ecological processes."),
            ("Air Quality and Management", "Examines the sources, dispersion, and control of air pollutants, ambient air quality standards, and monitoring approaches."),
            ("Environmental Microbiology", "Explores the roles of microorganisms in nutrient cycling, bioremediation, and the degradation of pollutants in soil and water."),
        ],
        "UG3": [
            ("Renewable Energy Systems", "Analyzes solar, wind, hydro, geothermal, and bioenergy technologies, including their engineering principles and environmental tradeoffs."),
            ("Environmental Modeling", "Introduces the construction and use of mathematical models to simulate ecological, hydrological, and atmospheric processes."),
            ("Wetland and Aquatic Ecology", "Studies the structure and function of wetland, river, and lake ecosystems and their roles in water storage, filtration, and habitat."),
            ("Soil and Water Conservation", "Covers the causes of erosion and degradation and the engineering and management practices used to conserve soil and water resources."),
            ("Environmental Biotechnology", "Examines the use of biological systems and organisms to address pollution, including bioremediation and biological treatment processes."),
            ("Global Biogeochemistry", "Analyzes the coupling of global carbon, nitrogen, and other element cycles and how human activity perturbs them at planetary scale."),
            ("Sustainable Agriculture and Food Systems", "Studies the environmental impacts of food production and the practices that reduce inputs, protect soil, and improve resilience."),
            ("Natural Resource Management", "Covers the principles and institutions for managing forests, fisheries, and other common-pool resources sustainably."),
        ],
        "UG4": [
            ("Climate Adaptation and Resilience", "Examines strategies for reducing vulnerability to climate impacts across sectors, communities, and infrastructure systems."),
            ("Environmental Law and Regulation", "Surveys major environmental statutes, regulatory institutions, and the legal mechanisms used to control pollution and protect resources."),
            ("Industrial Ecology", "Studies material and energy flows through industrial systems and strategies such as life-cycle assessment and closing resource loops."),
            ("Ecotoxicology and Risk Assessment", "Combines toxicology with ecology to assess the risks that contaminants pose to populations, communities, and ecosystems."),
            ("Urban Environmental Systems", "Analyzes the environmental dynamics of cities, including heat islands, stormwater, air quality, and green infrastructure."),
            ("Biodiversity Conservation Planning", "Applies systematic conservation planning, reserve design, and prioritization methods to protect biodiversity effectively."),
            ("Environmental Data Analysis", "Teaches statistical and computational methods for analyzing environmental datasets, including regression and time-series techniques."),
            ("Marine and Coastal Management", "Examines the science and governance of coastal zones, fisheries, and marine protected areas under multiple pressures."),
        ],
        "M1": [
            ("Climate Modeling", "Studies the theory and application of general circulation and Earth system models used to simulate and project climate change."),
            ("Carbon Accounting and Markets", "Examines methods for measuring greenhouse gas emissions and the design of carbon pricing, offsets, and trading systems."),
            ("Environmental Policy Analysis", "Applies analytical frameworks to evaluate the design, implementation, and effectiveness of environmental policies and instruments."),
            ("Ecosystem Services Valuation", "Covers the conceptual and economic methods for identifying and valuing the benefits that ecosystems provide to society."),
            ("Sustainability Science Research Methods", "Introduces interdisciplinary and systems-based research approaches for studying coupled human-natural systems."),
            ("Environmental Justice", "Analyzes the unequal distribution of environmental burdens and benefits across social groups and the movements that address it."),
            ("Planetary Boundaries", "Examines the framework of biophysical thresholds that define a safe operating space for humanity and the science behind each boundary."),
            ("Restoration Ecology at Scale", "Studies the theory and practice of restoring degraded ecosystems, including landscape-scale and process-based approaches."),
        ],
        "M2": [
            ("Advanced Climate Dynamics", "Examines the physical mechanisms governing climate variability and feedbacks, including ocean-atmosphere coupling and abrupt change."),
            ("Integrated Assessment Modeling", "Studies models that couple economic, energy, and climate systems to explore policy pathways and mitigation scenarios."),
            ("Global Environmental Governance", "Analyzes international regimes, treaties, and institutions that address transboundary environmental problems."),
            ("Biodiversity and Global Change", "Investigates how climate change, land use, and invasive species drive biodiversity change and the responses that follow."),
            ("Water Resources Systems Analysis", "Applies optimization and systems methods to allocate and manage water under competing demands and uncertainty."),
            ("Energy Transitions and Decarbonization", "Examines the technological, economic, and social dimensions of transforming energy systems toward net-zero emissions."),
            ("Remote Sensing for Global Monitoring", "Covers advanced satellite and sensor methods for monitoring land cover, emissions, and ecosystem change at global scale."),
            ("Environmental Research Design and Thesis", "Guides the formulation of research questions, study design, and analysis for an original environmental science investigation."),
        ],
    },
    "World Politics": {
        "C1": [
            ("Introduction to World Politics", "Surveys the actors, structures, and issues of international relations and introduces how states and other actors interact on the global stage."),
            ("States and Sovereignty", "Explains the concept of the sovereign state, the origins of the modern state system, and the meaning of territorial authority and recognition."),
            ("The United Nations System", "Introduces the structure and functions of the UN, including the General Assembly, Security Council, and specialized agencies."),
            ("Introduction to IR Theory", "Presents the core traditions of realism, liberalism, and constructivism and how each explains state behavior and world order."),
            ("Forms of Government", "Compares major forms of government such as democracies, authoritarian regimes, and hybrid systems and how power is organized within them."),
            ("Foreign Policy Basics", "Explains what foreign policy is, who makes it, and the goals, instruments, and constraints that shape state behavior abroad."),
            ("Introduction to International Law", "Introduces the sources, subjects, and functions of international law and how it differs from domestic legal systems."),
            ("Global Security Basics", "Introduces core concepts of security, threat, and the use of force, and distinguishes traditional military from broader security concerns."),
        ],
        "C2": [
            ("NGOs and IGOs", "Examines the roles of nongovernmental and intergovernmental organizations as actors that shape global cooperation and policy."),
            ("Nationalism and Identity", "Explores how national identity, ethnicity, and nationalism influence state formation, conflict, and international politics."),
            ("The Global Economy and Politics", "Introduces how trade, finance, and economic interdependence connect states and shape political relations among them."),
            ("Human Rights: An Introduction", "Surveys the concept of universal human rights, key declarations and treaties, and the institutions that promote and protect them."),
            ("War and Peace", "Introduces the causes of war, types of armed conflict, and the concepts and mechanisms involved in building and keeping peace."),
            ("Regional Politics and Cooperation", "Examines how states within regions cooperate and compete, using examples of regional organizations and shared challenges."),
            ("Diplomacy and Statecraft", "Introduces diplomacy as the practice of managing relations between states through negotiation, representation, and communication."),
            ("Globalization and Its Effects", "Analyzes how flows of goods, people, information, and ideas across borders reshape politics, economies, and societies."),
        ],
        "UG1": [
            ("Realism and the Balance of Power", "Examines realist theory in depth, including anarchy, self-help, and how states seek security through balancing power."),
            ("Liberalism and International Cooperation", "Studies liberal theories of institutions, interdependence, and democracy and how they explain cooperation among states."),
            ("Constructivism and Norms", "Explores how identities, ideas, and norms shape state interests and behavior according to constructivist approaches."),
            ("International Political Economy", "Introduces the interaction of politics and economics in trade, finance, and development at the international level."),
            ("Nuclear Weapons and Deterrence", "Analyzes the strategy of nuclear deterrence, arms control, and the challenges of proliferation and stability."),
            ("International Organizations in Depth", "Examines how international organizations are designed, why states create them, and how they affect cooperation and compliance."),
            ("Comparative Politics Foundations", "Introduces the systematic comparison of political systems, institutions, and regime types across countries."),
            ("International Security Studies", "Surveys the major theories and issues in security studies, including the causes of war, alliances, and the security dilemma."),
        ],
        "UG2": [
            ("Trade Regimes and the WTO", "Examines the rules and institutions governing international trade, including the GATT/WTO system and disputes over liberalization."),
            ("Regional Organizations", "Compares the aims, structures, and effectiveness of regional bodies such as the EU, ASEAN, and the African Union."),
            ("Conflict and Peace Studies", "Studies the dynamics of violent conflict and the theory and practice of peacekeeping, mediation, and peacebuilding."),
            ("Human Rights Regimes", "Analyzes the international and regional institutions, treaties, and enforcement mechanisms that constitute the human rights system."),
            ("Diplomacy and Negotiation", "Examines the theory and practice of negotiation and bargaining among states, including strategies and the role of mediators."),
            ("Terrorism and Asymmetric Conflict", "Studies the causes, tactics, and effects of terrorism and insurgency and the challenges they pose to states and security."),
            ("International Development Politics", "Examines the politics of economic development, foreign aid, and the debates over how poor countries can grow and reform."),
            ("Ethnic Conflict and Civil War", "Analyzes the causes and dynamics of civil wars and ethnic violence and the conditions for their resolution."),
        ],
        "UG3": [
            ("International Political Economy of Finance", "Examines the politics of global money and finance, including exchange rates, capital flows, and financial crises."),
            ("Energy Geopolitics", "Studies how the production, trade, and control of energy resources shape power, conflict, and cooperation among states."),
            ("Migration Politics", "Analyzes the causes of international migration and the politics of borders, refugees, asylum, and immigration policy."),
            ("Environmental Politics and Climate Diplomacy", "Examines international efforts to address transboundary environmental problems and the negotiation of climate agreements."),
            ("Comparative Foreign Policy", "Compares how different states make and conduct foreign policy, examining domestic sources and decision-making processes."),
            ("International Law in Practice", "Studies how international law operates in areas such as the use of force, the law of the sea, and international humanitarian law."),
            ("Great Power Politics", "Analyzes the behavior and rivalries of major powers and the theories that explain competition and order among them."),
            ("Global Civil Society and Social Movements", "Examines transnational activism, advocacy networks, and how nonstate movements influence global politics."),
        ],
        "UG4": [
            ("United States Foreign Policy", "Examines the institutions, traditions, and debates that shape American foreign policy and its role in world affairs."),
            ("The Politics of the European Union", "Analyzes the institutions, integration, and policy-making of the EU and the debates over its future and legitimacy."),
            ("Middle East Politics", "Surveys the political systems, conflicts, and international relations of the Middle East region."),
            ("Asian Security and Politics", "Examines the security dynamics, rising powers, and regional order of the Asia-Pacific region."),
            ("Peacekeeping and Intervention", "Studies the norms, practices, and controversies of humanitarian intervention and international peace operations."),
            ("Cybersecurity and Statecraft", "Analyzes how cyber capabilities affect security, deterrence, and the conduct of statecraft among states."),
            ("Global Governance", "Examines the institutions, rules, and networks through which states and other actors manage shared global problems."),
            ("Political Violence and Insurgency", "Studies the theory and practice of insurgency, counterinsurgency, and the strategic logic of political violence."),
        ],
        "M1": [
            ("Game Theory in International Relations", "Applies formal models of strategic interaction to explain cooperation, conflict, and bargaining among states."),
            ("Quantitative Methods in Political Science", "Introduces statistical and research design methods for testing hypotheses about political and international phenomena."),
            ("Grand Strategy", "Examines how states integrate military, economic, and diplomatic means to pursue long-term security objectives."),
            ("Climate Geopolitics", "Analyzes how climate change reshapes power, security, and cooperation among states and regions."),
            ("Global Governance Reform", "Examines proposals and pressures to reform international institutions to address contemporary global challenges."),
            ("Foreign Policy Analysis", "Studies the theories and methods used to explain how states and leaders make foreign policy decisions."),
            ("International Security Theory", "Examines advanced theoretical debates on the causes of war, deterrence, alliances, and the changing nature of security."),
            ("International Political Economy Theory", "Analyzes competing theoretical approaches to the politics of global trade, finance, and production."),
        ],
        "M2": [
            ("Contemporary Great-Power Competition", "Examines the strategic rivalry among leading powers and its implications for the international order."),
            ("Qualitative and Case-Study Methods", "Teaches case selection, process tracing, and comparative methods for rigorous qualitative research in politics."),
            ("Nuclear Strategy and Arms Control", "Analyzes advanced debates on deterrence stability, proliferation, and the design of arms control regimes."),
            ("International Institutions and Law Research", "Examines how international institutions and legal regimes are studied theoretically and empirically."),
            ("Cyber Conflict and Emerging Technologies", "Studies the strategic and governance challenges posed by cyber operations, artificial intelligence, and autonomous systems."),
            ("Political Economy of Global Order", "Analyzes how economic power and institutions underpin and reshape the structure of the international system."),
            ("Human Security and Global Justice", "Examines normative and empirical debates on protecting individuals and pursuing justice beyond the state."),
            ("Research Design and Thesis in Political Science", "Guides the formulation of a research question, theory, and methodology for an original thesis in political science."),
        ],
    },
    "World Religion": {
        "C1": [
            ("What Is Religion?", "Introduces scholarly definitions and approaches to studying religion, distinguishing academic, comparative study from devotional practice."),
            ("Hinduism: An Overview", "Surveys the diverse traditions, texts, deities, and practices grouped under Hinduism and its historical development in South Asia."),
            ("Buddhism: An Overview", "Introduces the life of the Buddha, the core teachings of the Four Noble Truths, and the major branches of the Buddhist tradition."),
            ("Judaism: An Overview", "Surveys the beliefs, texts, history, and practices of Judaism, including the Torah, covenant, and major movements."),
            ("Christianity: An Overview", "Introduces the origins, beliefs, scriptures, and major branches of Christianity and its historical spread."),
            ("Islam: An Overview", "Surveys the foundations of Islam, including the Quran, the Five Pillars, the life of Muhammad, and the major traditions."),
            ("Sikhism and Jainism: An Overview", "Introduces the teachings, founders, and practices of Sikhism and Jainism and their place among South Asian religions."),
            ("Indigenous and Folk Traditions", "Surveys the diversity of indigenous and folk religious traditions and the challenges of studying oral and localized practices."),
        ],
        "C2": [
            ("Sacred Texts and Scripture", "Introduces the concept of scripture across traditions and how sacred texts are composed, transmitted, and interpreted."),
            ("Myth and Symbol", "Examines the role of myth, symbol, and story in religious traditions and how scholars interpret their meanings."),
            ("Ritual and Worship", "Surveys the forms and functions of ritual, prayer, and worship across a range of religious traditions."),
            ("Religious Festivals and Calendars", "Examines how religious traditions mark sacred time through festivals, holy days, and liturgical or lunar calendars."),
            ("Death and the Afterlife", "Compares beliefs about death, the soul, and the afterlife across religious traditions and their associated practices."),
            ("Religion and the Life Cycle", "Examines rites of passage such as birth, initiation, marriage, and death across different religious traditions."),
            ("Founders and Prophets", "Compares the roles of founders, prophets, and charismatic figures in shaping religious traditions."),
            ("Comparing Religious Traditions", "Introduces the comparative method for identifying similarities and differences among the world's religions."),
        ],
        "UG1": [
            ("East Asian Traditions", "Surveys Confucianism, Daoism, and Shinto, examining their teachings, practices, and roles in East Asian societies."),
            ("Scripture and Hermeneutics", "Studies the methods of interpreting sacred texts and the philosophical questions involved in reading scripture."),
            ("Sociology of Religion", "Introduces sociological theories of how religion functions in society, including its roles in solidarity, authority, and change."),
            ("Philosophy of Religion", "Examines philosophical questions about the existence and nature of the divine, faith and reason, and the problem of evil."),
            ("Mysticism Across Traditions", "Compares mystical experience and contemplative practice in various religious traditions and how scholars interpret them."),
            ("Religious Art and Architecture", "Studies how religious ideas are expressed through visual art, iconography, and sacred architecture across traditions."),
            ("Religion and Ethics", "Examines how religious traditions articulate moral teachings and how these relate to broader ethical thought."),
            ("History of the Study of Religion", "Traces the development of religious studies as an academic discipline and its major thinkers and approaches."),
        ],
        "UG2": [
            ("Ritual Studies", "Examines theories of ritual and their application to understanding the structure, function, and meaning of religious rites."),
            ("Religion and Science", "Explores the historical and philosophical relationship between religious traditions and scientific knowledge."),
            ("Secularism and Modernity", "Analyzes theories of secularization and the changing place of religion in modern societies."),
            ("New Religious Movements", "Studies the emergence, beliefs, and dynamics of new religious movements and the scholarly debates surrounding them."),
            ("Comparative Ethics", "Compares the moral frameworks of different religious traditions and the methods for studying ethics across cultures."),
            ("Pilgrimage and Sacred Space", "Examines the concept of sacred space and the practice of pilgrimage across religious traditions."),
            ("Gender and Religion", "Analyzes how religious traditions shape and are shaped by ideas of gender, authority, and the roles of women and men."),
            ("Religion and Colonialism", "Examines how colonial encounters transformed religious traditions and the study of religion itself."),
        ],
        "UG3": [
            ("Religion and Society", "Examines the interplay between religious institutions and social structures, including community, power, and identity."),
            ("Theology and Religious Thought", "Surveys how traditions develop systematic reflection on the divine, revelation, and doctrine."),
            ("Religion and Violence", "Analyzes the complex relationships between religion, conflict, and peace, avoiding simplistic causal claims."),
            ("Religion and Politics", "Examines how religious traditions and institutions engage with political authority, law, and public life."),
            ("Comparative Scriptural Traditions", "Compares the formation, canon, and interpretation of scriptures across major religious traditions."),
            ("Popular and Lived Religion", "Studies religion as practiced in everyday life, beyond official doctrine, including devotion, healing, and material culture."),
            ("Religion and Migration", "Examines how migration transforms religious communities and how faith shapes the experience of diaspora."),
            ("Esotericism and Alternative Spiritualities", "Surveys esoteric, occult, and alternative spiritual movements and their place in the study of religion."),
        ],
        "UG4": [
            ("Interfaith Dialogue", "Examines the theory and practice of dialogue among religious traditions and the frameworks used to foster understanding."),
            ("Religion and Human Rights", "Analyzes the relationship between religious traditions and modern conceptions of human rights and freedom of belief."),
            ("Religion and the Environment", "Examines how religious traditions understand nature and contribute to environmental thought and activism."),
            ("Religion and Economics", "Explores how religious ideas shape economic behavior, ethics, and institutions across traditions."),
            ("Contemporary Islam", "Studies the diversity of modern Muslim thought, movements, and practices in a globalized world."),
            ("Contemporary Christianity", "Examines the major movements, debates, and global transformations within modern Christianity."),
            ("Buddhism in the Modern World", "Analyzes how Buddhist traditions have adapted, spread, and engaged with modernity and globalization."),
            ("Religion and Media", "Examines how religious traditions use and are represented in print, broadcast, and digital media."),
        ],
        "M1": [
            ("Method and Theory in Religious Studies", "Examines the major theoretical frameworks and methodological debates that define the academic study of religion."),
            ("Anthropology of Religion", "Studies ethnographic approaches to religion and anthropological theories of ritual, belief, and the sacred."),
            ("Religion and Politics: Advanced Study", "Analyzes advanced theories of the relationship between religion, the state, secularism, and public life."),
            ("Interfaith Dialogue Frameworks", "Examines theoretical models and institutional practices for structured dialogue among religious traditions."),
            ("Religion and Globalization", "Studies how global flows of people, media, and capital transform religious traditions and their spread."),
            ("Psychology of Religion", "Examines psychological theories and research on religious experience, belief, cognition, and behavior."),
            ("Religion in the Digital Age", "Analyzes how digital technologies and online communities reshape religious practice, authority, and community."),
            ("Comparative Theology and Philosophy", "Examines advanced comparison of theological and philosophical ideas across religious traditions."),
        ],
        "M2": [
            ("Critical Theory and Religion", "Examines how critical theory, including postcolonial and feminist approaches, reshapes the study of religion."),
            ("Cognitive Science of Religion", "Studies the cognitive and evolutionary theories that seek to explain the origins and persistence of religious belief."),
            ("Religion, Law, and the State", "Analyzes how legal systems regulate religion and how religious traditions engage with law and governance."),
            ("Material Religion and Embodiment", "Examines the study of religion through objects, bodies, senses, and material culture."),
            ("Religion and Conflict Resolution", "Studies the roles that religious actors and ideas play in peacebuilding and reconciliation."),
            ("Global Ethics and Religious Traditions", "Examines how religious traditions contribute to debates on global ethics, justice, and shared human concerns."),
            ("Advanced Comparative Religion", "Engages advanced theoretical and methodological problems in comparing religious traditions across cultures and eras."),
            ("Research Methods and Thesis Design", "Guides the design of an original research project in religious studies, from question formulation to methodology."),
        ],
    },
}
