"""Module topics for the college-subject expansion (batch B).

MODULES[subject][level] = list of 8 (title, summary) tuples.
Levels: C1, C2, UG1, UG2, UG3, UG4, M1, M2 (College 1-2, Undergrad 1-4, Masters 1-2).
"""

MODULES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Economics": {
        "C1": [
            ("Economic Thinking & Models", "Introduces how economists use simplifying models, assumptions, and the distinction between positive and normative analysis to study human decision-making."),
            ("Comparative Advantage & Specialization", "Explains why individuals and nations gain from specializing according to comparative advantage, using production possibilities and opportunity-cost reasoning."),
            ("Prices as Signals & Incentives", "Examines how market prices communicate information about relative scarcity and coordinate the decisions of buyers and sellers without central direction."),
            ("Consumer & Producer Surplus", "Develops surplus as a measure of gains from trade and uses it to evaluate the efficiency of market outcomes and the deadweight loss from price controls."),
            ("Costs of Production", "Covers fixed, variable, average, and marginal costs, and how economies of scale shape a firm's cost structure in the short and long run."),
            ("Money & Banking Basics", "Surveys the functions of money, how commercial banks create deposits through lending, and the basic structure of a modern banking system."),
            ("Measuring the Cost of Living", "Explains how price indexes such as the CPI are constructed, their known biases, and how they are used to compare purchasing power over time."),
            ("Personal Finance & Economic Decisions", "Applies economic reasoning to budgeting, saving, compound interest, credit, and insurance decisions faced by households."),
        ],
        "C2": [
            ("Budget Constraints & Indifference Curves", "Introduces the graphical model of consumer choice, showing how budget lines and indifference curves determine a consumer's optimal bundle."),
            ("Producer Theory & Cost Curves", "Studies how firms choose inputs and output, deriving short-run and long-run cost curves from production technology and input prices."),
            ("Labor Markets & Wage Determination", "Analyzes labor supply and demand, human capital, and why wages differ across occupations, skills, and regions."),
            ("Environmental Economics Basics", "Introduces pollution as an external cost and compares policy tools such as emissions taxes, tradable permits, and direct regulation."),
            ("Aggregate Demand & Aggregate Supply", "Builds the AD-AS framework to explain short-run fluctuations in output and the price level and the economy's adjustment to shocks."),
            ("Saving, Investment & the Financial System", "Explains how financial markets and intermediaries channel household saving into business investment, and the role of interest rates in the loanable funds market."),
            ("Poverty & Income Inequality", "Surveys how poverty lines, income quintiles, and the Gini coefficient describe the distribution of income and the debates over redistribution."),
            ("Economic History: Industrialization to Globalization", "Traces major transformations in the world economy from the Industrial Revolution through twentieth-century globalization and their lasting institutional legacies."),
        ],
        "UG1": [
            ("Preferences, Utility & Demand", "Develops intermediate consumer theory formally, deriving demand functions from utility maximization and decomposing price effects into income and substitution effects."),
            ("Choice under Uncertainty", "Introduces expected utility theory, risk aversion, and applications to insurance and portfolio choice."),
            ("Production & Cost Minimization", "Uses isoquants and isocost lines to derive conditional input demands and cost functions, connecting technology to firm supply behavior."),
            ("General Equilibrium & Exchange", "Analyzes how all markets clear simultaneously, using the Edgeworth box and Walrasian equilibrium to study allocation in an exchange economy."),
            ("Welfare Economics & the Fundamental Theorems", "States the first and second welfare theorems, defines Pareto efficiency, and examines the conditions under which competitive markets are efficient."),
            ("The Solow Growth Model", "Builds the neoclassical growth model with capital accumulation and technological progress, and uses it to interpret cross-country income differences."),
            ("IS-LM & Short-Run Fluctuations", "Develops the IS-LM model of goods and money market equilibrium to analyze the short-run effects of demand shocks and stabilization policy."),
            ("Probability & Statistics for Economists", "Covers random variables, distributions, estimation, and hypothesis testing as the statistical foundation for later econometrics coursework."),
        ],
        "UG2": [
            ("Labor Economics", "Studies labor supply and demand, human capital investment, wage inequality, discrimination, and the effects of minimum wages and unions on employment."),
            ("Industrial Organization", "Examines firm strategy and market power, covering oligopoly models, entry deterrence, product differentiation, and the economics of antitrust policy."),
            ("Health Economics", "Applies economic tools to health care markets, analyzing insurance, moral hazard, adverse selection, and the demand for medical care."),
            ("Urban & Regional Economics", "Explores why cities exist and grow, covering agglomeration economies, land and housing markets, transportation, and local public goods."),
            ("Environmental & Resource Economics", "Analyzes optimal management of pollution and natural resources, valuation of environmental goods, and the design of market-based environmental policy."),
            ("Financial Economics & Asset Pricing", "Introduces present value, risk and return, portfolio theory, and the Capital Asset Pricing Model as foundations for valuing financial assets."),
            ("Open-Economy Macroeconomics", "Extends macroeconomic analysis to open economies, studying capital flows, the Mundell-Fleming model, and policy under fixed versus floating regimes."),
            ("Causal Inference & Natural Experiments", "Introduces the potential outcomes framework and research designs, including randomized trials, difference-in-differences, and instrumental variables, for estimating causal effects."),
        ],
        "UG3": [
            ("Information Economics: Adverse Selection & Moral Hazard", "Studies markets with asymmetric information, covering signaling, screening, and the design of incentive contracts under hidden actions and hidden types."),
            ("Auction Theory", "Analyzes first-price, second-price, and ascending auctions, bidding strategies, the revenue equivalence theorem, and applications such as spectrum sales."),
            ("Matching Markets & Market Design", "Covers two-sided matching theory, the deferred acceptance algorithm, and real-world designs for school choice, medical residencies, and kidney exchange."),
            ("Political Economy", "Applies economic modeling to politics, including the median voter theorem, electoral competition, lobbying, and the political causes of inefficient policy."),
            ("Business Cycle Theory", "Compares real business cycle and New Keynesian explanations of economic fluctuations, emphasizing the role of shocks, price rigidities, and expectations."),
            ("Endogenous Growth Theory", "Studies models in which innovation and human capital accumulation are chosen by agents, including AK, Romer, and Schumpeterian frameworks."),
            ("Panel Data Methods", "Covers fixed effects, random effects, and difference estimators for data that follow the same units over time, along with dynamic panel techniques."),
            ("Time Series Econometrics", "Introduces stationarity, ARMA models, unit roots, cointegration, and vector autoregressions for analyzing macroeconomic and financial time series."),
        ],
        "UG4": [
            ("Mechanism Design", "Studies how to design rules and institutions that achieve desired outcomes when participants hold private information, including incentive compatibility and the revelation principle."),
            ("Institutional Economics", "Examines how property rights, contracts, and political institutions shape transaction costs and long-run economic performance, drawing on the work of Coase and North."),
            ("Experimental Economics", "Covers laboratory and field experimental methods for testing economic theory, including design of incentives, common games, and replication issues."),
            ("Poverty & Inequality Measurement", "Develops formal measurement tools, including poverty indices, Lorenz curves, and inequality decompositions, and applies them to household survey data."),
            ("Economics of Education", "Analyzes education as human capital investment, evaluating evidence on returns to schooling, class size, teacher quality, and school choice policies."),
            ("Economics of Innovation & Technological Change", "Studies the incentives for R&D, patent policy, technology diffusion, and the effects of automation on productivity and labor markets."),
            ("Financial Crises & Macroprudential Policy", "Examines bank runs, leverage cycles, and systemic risk through historical crises, and evaluates regulatory tools designed to preserve financial stability."),
            ("Applied Microeconometrics Workshop", "A research-oriented course in which students design and execute an empirical project, applying causal inference methods to an original economic question."),
        ],
        "M1": [
            ("Microeconomic Theory I: Choice & General Equilibrium", "Graduate treatment of preference axioms, demand theory, and existence and welfare properties of competitive equilibrium in the Arrow-Debreu framework."),
            ("Macroeconomic Theory I: Dynamic Optimization & Growth", "Develops dynamic programming and the Ramsey-Cass-Koopmans and overlapping-generations models as the workhorse tools of modern macroeconomics."),
            ("Econometrics I: Asymptotics & GMM", "Rigorous coverage of large-sample theory, maximum likelihood, and generalized method of moments estimation and inference."),
            ("Contract Theory", "Formal analysis of moral hazard, adverse selection, and incomplete contracts, with applications to employment, procurement, and the theory of the firm."),
            ("Repeated Games & Bargaining", "Advanced study of dynamic strategic interaction, covering folk theorems, reputation, and the Nash and Rubinstein models of bargaining."),
            ("Search & Matching in Labor Markets", "Develops the Diamond-Mortensen-Pissarides framework to explain equilibrium unemployment, vacancies, and the effects of labor market policy."),
            ("Optimal Taxation & Public Finance", "Graduate public finance covering the Ramsey and Mirrlees approaches to optimal commodity and income taxation and the equity-efficiency trade-off."),
            ("Structural Econometrics & Discrete Choice", "Covers estimation of structural economic models, including logit and probit families, the BLP demand model, and simulation-based methods."),
        ],
        "M2": [
            ("DSGE Models & Quantitative Macroeconomics", "Builds and estimates dynamic stochastic general equilibrium models, covering solution methods, calibration, and Bayesian estimation for policy analysis."),
            ("Heterogeneous-Agent Macroeconomics", "Studies incomplete-markets models in the Bewley-Aiyagari-HANK tradition, linking wealth inequality to consumption behavior and the transmission of macroeconomic policy."),
            ("Empirical Industrial Organization", "Covers structural estimation of demand and supply in imperfectly competitive markets, including merger simulation, entry models, and dynamic games."),
            ("Field Experiments & RCT Design", "Trains students to design, power, and analyze randomized controlled trials in applied settings, addressing ethics, attrition, spillovers, and external validity."),
            ("Networks in Economics", "Examines how social and economic networks form and how network structure shapes diffusion, peer effects, financial contagion, and trade."),
            ("Machine Learning for Economists", "Covers prediction methods such as regularization and tree ensembles and their integration with causal inference, including double machine learning."),
            ("Climate Economics & Integrated Assessment", "Analyzes the economics of climate change using integrated assessment models, the social cost of carbon, discounting debates, and carbon pricing design."),
            ("Behavioral Finance", "Studies how limits to arbitrage and investor psychology, including overconfidence and loss aversion, help explain asset pricing anomalies and market bubbles."),
        ],
    },
    "Health Education": {
        "C1": [
            ("Human Body Systems Review", "Reviews the structure and function of major body systems, including cardiovascular, respiratory, digestive, nervous, and endocrine, as the biological basis for health decisions."),
            ("Nutrition Science Fundamentals", "Covers macronutrients, micronutrients, energy balance, and evidence-based dietary guidelines for building healthy eating patterns."),
            ("Physical Activity & Fitness Science", "Explains the components of fitness, aerobic and resistance training principles, and current physical activity recommendations for health."),
            ("Mental Health Literacy", "Builds understanding of common mental health conditions, warning signs, stigma reduction, and how to seek and offer help."),
            ("Sleep Science & Health", "Examines sleep architecture, circadian rhythms, the consequences of sleep deprivation, and evidence-based sleep hygiene practices."),
            ("Substance Use & Misuse Awareness", "Covers the effects of alcohol, nicotine, and other drugs on the body and brain, the development of dependence, and refusal and harm-reduction skills."),
            ("Sexual & Reproductive Health", "Provides medically accurate education on reproductive anatomy, contraception, sexually transmitted infections, and consent within a clinical and educational framing."),
            ("Injury Prevention & First Aid Basics", "Teaches prevention of common unintentional injuries and foundational first aid skills, including CPR awareness and emergency response steps."),
        ],
        "C2": [
            ("Health Behavior & Goal Setting", "Applies goal-setting and self-monitoring strategies to personal health behavior change, introducing habit formation and relapse-prevention concepts."),
            ("Consumer Health & Information Literacy", "Develops skills to evaluate health claims, advertising, supplements, and online information using scientific evidence standards."),
            ("Community & Environmental Health Basics", "Introduces how air and water quality, sanitation, and the built environment influence the health of communities."),
            ("Communicable & Noncommunicable Diseases", "Compares infectious and chronic diseases, covering transmission, major risk factors, and basic strategies for prevention of each."),
            ("Stress & Coping", "Explains the physiology of the stress response and evaluates healthy coping strategies, including relaxation techniques and social support."),
            ("Healthy Relationships & Communication", "Covers characteristics of healthy versus unhealthy relationships, boundary setting, conflict resolution, and recognizing abuse."),
            ("Adolescent Growth & Development", "Surveys the physical, cognitive, and social-emotional changes of adolescence and their implications for health behavior."),
            ("Health Careers & Health Systems Overview", "Introduces the range of health professions and the basic organization of public health and health care delivery systems."),
        ],
        "UG1": [
            ("Introduction to Epidemiology", "Introduces the distribution and determinants of disease in populations, covering measures of frequency and association and the basics of outbreak investigation."),
            ("Introduction to Biostatistics", "Covers descriptive statistics, probability, confidence intervals, and hypothesis testing applied to health and medical data."),
            ("Social Determinants of Health", "Examines how income, education, housing, and social context shape health outcomes across populations."),
            ("Health Behavior Theories", "Surveys major theories of health behavior, including the Health Belief Model, Theory of Planned Behavior, Social Cognitive Theory, and the Transtheoretical Model."),
            ("Foundations of Global Health", "Introduces the global burden of disease, health metrics such as DALYs, and the major actors and challenges in international health."),
            ("Nutrition Through the Lifespan", "Studies nutritional needs and common deficiencies from pregnancy and infancy through childhood, adulthood, and older age."),
            ("Health Communication Fundamentals", "Covers principles of designing clear, audience-appropriate health messages and campaigns, including health literacy considerations."),
            ("Health Systems & Health Care Delivery", "Compares how health systems are organized, financed, and evaluated, introducing concepts of access, quality, and cost."),
        ],
        "UG2": [
            ("Chronic Disease Epidemiology & Prevention", "Examines the epidemiology and modifiable risk factors of cardiovascular disease, cancer, and diabetes, and population strategies for their prevention."),
            ("Infectious Disease & Immunization", "Covers transmission dynamics, herd immunity, vaccine science, and the design of immunization programs and outbreak control measures."),
            ("Environmental Health", "Studies how chemical, biological, and physical hazards in air, water, food, and the built environment affect human health, and how they are assessed and regulated."),
            ("Occupational Health & Safety", "Introduces workplace hazards, exposure assessment, injury surveillance, and the regulatory frameworks that protect worker health."),
            ("Maternal & Child Health", "Surveys the health needs of women, infants, and children, covering prenatal care, birth outcomes, breastfeeding, and early childhood development programs."),
            ("Health Disparities & Health Equity", "Analyzes systematic differences in health outcomes across racial, socioeconomic, and geographic groups and frameworks for advancing health equity."),
            ("Research Methods in Public Health", "Covers study design, sampling, survey construction, measurement validity, and ethical review as applied to public health research questions."),
            ("Injury & Violence Prevention", "Applies the public health approach to unintentional injury and violence, covering surveillance, risk factors, and evidence-based prevention programs."),
        ],
        "UG3": [
            ("Health Program Planning & Evaluation", "Teaches systematic program planning using frameworks such as PRECEDE-PROCEED and logic models, along with process, impact, and outcome evaluation."),
            ("Community Health Assessment", "Covers methods for assessing community health needs and assets, including secondary data analysis, surveys, focus groups, and stakeholder engagement."),
            ("Epidemiology II: Study Design & Bias", "Deepens epidemiologic methods with cohort, case-control, and cross-sectional designs, and the identification of confounding, selection, and information bias."),
            ("Biostatistics II: Regression Methods", "Covers linear and logistic regression, confounding adjustment, and interaction, with interpretation of multivariable models in health research."),
            ("Health Education Pedagogy & Curriculum Design", "Prepares students to design, deliver, and assess health education curricula aligned with national health education standards."),
            ("Public Mental Health", "Examines the population burden of mental and behavioral health conditions, prevention and early-intervention programs, and mental health service systems."),
            ("Aging & Gerontological Health", "Studies the biology and epidemiology of aging, chronic disease management in older adults, and programs supporting healthy aging."),
            ("Health Informatics Basics", "Introduces electronic health records, public health surveillance systems, and data standards used to manage and exchange health information."),
        ],
        "UG4": [
            ("Health Policy & Advocacy", "Analyzes how health policy is made and teaches advocacy skills, including policy briefs, coalition building, and legislative testimony."),
            ("Public Health Ethics", "Examines ethical frameworks for balancing individual liberty and collective welfare in areas such as vaccination mandates, screening, and resource allocation."),
            ("Emergency Preparedness & Disaster Response", "Covers public health roles in preparing for and responding to natural disasters, pandemics, and mass casualty events, including incident command systems."),
            ("Substance Use Epidemiology & Harm Reduction", "Studies patterns of substance use disorders and evaluates harm-reduction interventions such as naloxone distribution and syringe service programs."),
            ("One Health & Emerging Zoonoses", "Explores the interdependence of human, animal, and environmental health and the drivers of emerging zoonotic disease threats."),
            ("Digital Health Interventions", "Evaluates mobile health apps, wearables, telehealth, and social media campaigns as tools for health behavior change and care delivery."),
            ("Health Promotion in Schools & Workplaces", "Covers the design of setting-based health promotion programs, including the Whole School, Whole Community, Whole Child model and workplace wellness."),
            ("Field Practicum in Health Education", "A supervised field placement in which students apply program planning, delivery, and evaluation skills in a community, clinical, or school setting."),
        ],
        "M1": [
            ("Advanced Epidemiologic Methods", "Graduate coverage of causal diagrams, effect modification, misclassification, and advanced designs such as case-crossover and nested case-control studies."),
            ("Advanced Biostatistics: Survival & Longitudinal Analysis", "Covers Kaplan-Meier estimation, Cox proportional hazards models, and mixed-effects models for repeated measures in health studies."),
            ("Health Policy Analysis", "Trains students to define policy problems, compare alternatives against explicit criteria, and communicate recommendations to decision-makers."),
            ("Health Economics & Financing", "Applies economic analysis to health insurance design, provider payment, and cost-effectiveness analysis of health interventions."),
            ("Implementation Science", "Studies frameworks and strategies, such as RE-AIM and CFIR, for moving evidence-based health interventions into routine practice at scale."),
            ("Qualitative & Mixed Methods Research", "Covers interview, focus group, and ethnographic methods, qualitative coding and analysis, and the integration of qualitative and quantitative designs."),
            ("Global Health Governance", "Examines the institutions that govern global health, including the WHO, the International Health Regulations, and financing mechanisms such as the Global Fund and Gavi."),
            ("Theory-Based Intervention Design", "Applies behavioral and social science theory to the systematic design of health interventions, including intervention mapping and behavior change techniques."),
        ],
        "M2": [
            ("Health Data Science", "Covers management and analysis of large health datasets, including data wrangling, visualization, and introductory machine learning for prediction in public health."),
            ("Systematic Reviews & Meta-Analysis", "Teaches protocol registration, systematic search strategies, risk-of-bias assessment, and quantitative synthesis of study results."),
            ("Public Health Leadership & Management", "Develops competencies in strategic planning, workforce management, budgeting, and leading public health organizations through change."),
            ("Monitoring & Evaluation of Health Programs", "Covers indicator development, evaluation designs, data quality assurance, and reporting frameworks used by health agencies and global donors."),
            ("Research Ethics & Responsible Conduct", "Examines human subjects protections, informed consent, IRB review, data integrity, and authorship standards in health research."),
            ("Grant Writing & Research Proposal Development", "Guides students through specific aims, significance and innovation sections, budgets, and the peer review criteria of major health funders."),
            ("Community-Based Participatory Research", "Studies partnership approaches in which communities share power throughout the research process, including trust building and equitable dissemination."),
            ("Master's Capstone in Health Education", "An integrative culminating project in which students design, conduct, and defend an applied research or program development project in health education."),
        ],
    },
    "Business Studies": {
        "C1": [
            ("Introduction to Business & Its Environment", "Surveys the types of business organizations and the economic, legal, and social environments in which firms operate."),
            ("Principles of Management", "Introduces planning, organizing, leading, and controlling as the core functions of management, along with foundational management theories."),
            ("Marketing Fundamentals", "Covers the marketing concept, market segmentation, targeting and positioning, and the four Ps of the marketing mix."),
            ("Accounting Basics: The Language of Business", "Introduces the accounting equation, double-entry bookkeeping, and the purpose of the income statement and balance sheet."),
            ("Business Communication", "Develops professional writing, presentation, and interpersonal communication skills for workplace contexts, including emails, reports, and meetings."),
            ("Introduction to Entrepreneurship", "Explores how entrepreneurs identify opportunities, assess feasibility, and take the first steps toward launching a new venture."),
            ("Personal & Business Finance Basics", "Covers budgeting, interest, credit, and basic financial planning concepts relevant to both households and small businesses."),
            ("Sales & Customer Service Fundamentals", "Introduces the selling process, relationship building, handling objections, and the role of customer service in retention and reputation."),
        ],
        "C2": [
            ("Business Law Basics", "Introduces contracts, torts, agency, and the legal forms of business organization, emphasizing how law shapes everyday commercial decisions."),
            ("Introduction to Human Resource Management", "Covers recruitment, selection, training, compensation, and performance appraisal as the core activities of managing people at work."),
            ("Operations & Production Basics", "Introduces how goods and services are produced, covering process design, capacity, inventory, and productivity measurement."),
            ("Small Business Management", "Examines the practical challenges of running a small firm, including cash flow management, local marketing, staffing, and regulatory compliance."),
            ("E-Commerce & Digital Business", "Surveys online business models, digital storefronts, electronic payments, and the basics of reaching customers through digital channels."),
            ("Business Statistics Foundations", "Covers descriptive statistics, probability, and introductory inference with applications to quality control, forecasting, and market data."),
            ("Business Plan Development", "Guides students through writing a complete business plan, including market analysis, operations, and financial projections."),
            ("Introduction to Business Finance", "Introduces time value of money, sources of financing, and how firms balance debt and equity to fund operations and growth."),
        ],
        "UG1": [
            ("Financial Accounting", "In-depth study of the accounting cycle and preparation and interpretation of financial statements under generally accepted accounting principles."),
            ("Managerial Accounting", "Covers cost behavior, cost-volume-profit analysis, budgeting, and variance analysis as tools for internal planning and control."),
            ("Organizational Behavior", "Examines motivation, perception, group dynamics, and organizational culture, applying psychological research to management practice."),
            ("Business Statistics & Data Analysis", "Develops regression, sampling, and statistical inference skills with spreadsheet and statistical software applied to business problems."),
            ("Marketing Management", "Builds on marketing fundamentals with product, pricing, distribution, and promotion strategy, and the development of integrated marketing plans."),
            ("Management Information Systems", "Studies how databases, enterprise systems, and information technology support business processes and managerial decision-making."),
            ("Business Ethics & Corporate Social Responsibility", "Applies ethical frameworks to business dilemmas and examines stakeholder theory, sustainability reporting, and corporate citizenship."),
            ("Commercial & Contract Law", "Deepens legal knowledge for business, covering contract formation and remedies, sales law, negotiable instruments, and employment law basics."),
        ],
        "UG2": [
            ("Corporate Finance", "Covers capital budgeting, valuation, cost of capital, capital structure, and dividend policy as the core financial decisions of the firm."),
            ("Marketing Research", "Teaches the design and execution of marketing research, including survey and experimental design, sampling, and analysis of consumer data."),
            ("Operations Management", "Studies process analysis, forecasting, inventory models, scheduling, and quality management for both manufacturing and service operations."),
            ("Human Resource Management", "Advanced treatment of talent acquisition, development, compensation design, labor relations, and the legal environment of employment."),
            ("Consumer Behavior", "Examines the psychological and social influences on consumer decision-making and their implications for marketing strategy."),
            ("Financial Markets & Institutions", "Surveys money and capital markets, banks and other intermediaries, interest rate determination, and the role of central banks and regulators."),
            ("Project Management", "Covers project scoping, work breakdown structures, scheduling with critical path analysis, risk management, and agile approaches."),
            ("Auditing & Assurance Fundamentals", "Introduces the audit process, internal controls, audit evidence, and the professional standards and independence rules governing auditors."),
        ],
        "UG3": [
            ("Strategic Management", "Integrates functional knowledge to analyze industries and competitive advantage using frameworks such as Porter's five forces and the resource-based view."),
            ("Supply Chain Management", "Studies sourcing, logistics, distribution network design, and coordination across supply chain partners, including the bullwhip effect."),
            ("International Business", "Examines how firms enter and compete in foreign markets, covering trade and investment environments, entry modes, and managing across cultures."),
            ("Investments & Portfolio Management", "Covers security analysis, diversification, asset allocation, market efficiency, and performance evaluation of investment portfolios."),
            ("Digital Marketing", "Studies search, social media, content, and email marketing, along with web analytics and conversion optimization."),
            ("Negotiation & Conflict Resolution", "Develops negotiation skills through theory and simulations, covering distributive and integrative bargaining, BATNA, and multiparty negotiations."),
            ("Innovation Management", "Examines how firms generate, select, and commercialize innovations, covering disruptive innovation, R&D management, and open innovation."),
            ("Quality Management & Lean Operations", "Covers total quality management, Six Sigma, statistical process control, and lean principles for eliminating waste in processes."),
        ],
        "UG4": [
            ("Business Policy & Strategy Capstone", "A capstone integrating finance, marketing, and operations through case analysis or competitive simulation, culminating in a comprehensive strategic plan."),
            ("New Venture Creation", "An applied entrepreneurship course in which students validate a business concept with customer discovery and develop a launch-ready venture pitch."),
            ("Risk Management & Insurance", "Covers identification, measurement, and treatment of business risks, including enterprise risk management frameworks and insurance products."),
            ("Business Intelligence & Data Visualization", "Teaches dashboard design, data storytelling, and the use of BI tools to turn organizational data into decision-ready insights."),
            ("Brand Management", "Studies brand equity, positioning, brand architecture, and the measurement and long-term stewardship of brands."),
            ("Cross-Cultural Management", "Examines how national culture affects leadership, communication, and organizational practices, drawing on frameworks such as Hofstede's dimensions."),
            ("Business Forecasting & Decision Models", "Applies time series forecasting, optimization, simulation, and decision analysis to managerial planning problems."),
            ("Sustainability & Green Business Strategy", "Analyzes how firms integrate environmental and social sustainability into strategy, operations, and reporting, including circular economy models."),
        ],
        "M1": [
            ("Advanced Corporate Strategy", "Graduate analysis of corporate scope decisions, including diversification, vertical integration, alliances, and the management of multi-business firms."),
            ("Leadership & Change Management", "Studies evidence-based leadership models and the design and execution of organizational change initiatives, including overcoming resistance."),
            ("Business Analytics for Decision Making", "Covers predictive modeling, optimization, and A/B experimentation as rigorous inputs to managerial decisions, with emphasis on framing problems analytically."),
            ("Managerial Economics", "Applies microeconomic analysis to management decisions, including pricing strategy, demand estimation, and competitive positioning under different market conditions."),
            ("Advanced Corporate Finance", "Deepens valuation and financing theory with real options, payout policy, financial distress, and empirical evidence on capital structure choices."),
            ("Strategic Marketing Management", "Takes a general-manager perspective on marketing strategy, covering customer lifetime value, go-to-market design, and marketing resource allocation."),
            ("Operations Strategy", "Analyzes how operations capabilities, capacity, and sourcing choices create competitive advantage, including global network and outsourcing decisions."),
            ("Strategic Human Resource Management", "Examines how talent systems, incentive design, and people analytics align human capital with organizational strategy."),
        ],
        "M2": [
            ("Mergers & Acquisitions", "Covers deal rationale, target valuation, due diligence, deal structuring, and the drivers of post-merger integration success and failure."),
            ("Venture Capital & Startup Finance", "Studies the venture financing cycle, term sheets, staged investment, startup valuation methods, and exit strategies."),
            ("Global Strategy", "Examines how multinational firms configure activities worldwide, balancing global integration with local responsiveness and managing geopolitical risk."),
            ("Corporate Governance", "Analyzes board structure, executive compensation, shareholder rights, and agency conflicts, drawing on governance codes and empirical research."),
            ("Digital Transformation Strategy", "Studies how established firms respond to digital disruption, covering platform business models, ecosystems, and data-driven competitive advantage."),
            ("Corporate Restructuring & Turnarounds", "Covers financial and operational restructuring, bankruptcy processes, divestitures, and the management of distressed companies."),
            ("Behavioral Strategy & Managerial Decision-Making", "Applies research on cognitive biases, heuristics, and group decision pathologies to improve strategic decision processes in organizations."),
            ("Capstone Consulting Project Design", "Students scope and deliver a consulting engagement for a real client organization, producing a structured problem diagnosis and implementable recommendations."),
        ],
    },
    "Civics": {
        "C1": [
            ("Foundations of Citizenship", "Explores what it means to be a citizen, including the rights, responsibilities, and civic virtues that sustain democratic communities."),
            ("Constitutions & the Rule of Law", "Explains the purpose of constitutions, how they limit government power, and why the rule of law requires that laws apply equally to everyone."),
            ("Branches of Government & Separation of Powers", "Examines the legislative, executive, and judicial branches and how checks and balances prevent the concentration of power."),
            ("Elections & Voting Systems", "Covers how elections are conducted, voter registration and eligibility, and basic differences among voting systems such as plurality and proportional rules."),
            ("Local Government & Community Governance", "Studies how municipalities, counties, and school boards make decisions that affect daily life, and how residents can participate."),
            ("Civil Liberties & Civil Rights", "Distinguishes liberties that protect individuals from government from rights guaranteeing equal treatment, using landmark legal milestones as illustrations."),
            ("Media Literacy for Citizens", "Builds skills for evaluating news sources, identifying misinformation and bias, and distinguishing reporting from opinion and advertising."),
            ("Civic Participation Basics", "Surveys the ways citizens can engage beyond voting, including petitions, public meetings, volunteering, and contacting elected officials."),
        ],
        "C2": [
            ("The Legislative Process", "Follows how a bill becomes law, including committees, debate, amendment, and executive approval or veto, and the role of compromise in lawmaking."),
            ("Courts & the Justice System", "Explains the structure of trial and appellate courts, criminal versus civil proceedings, and due process protections for the accused."),
            ("Political Ideologies & the Political Spectrum", "Introduces major political ideologies, including liberalism, conservatism, and socialism, and how they map onto contemporary policy debates."),
            ("Public Opinion & Polling", "Covers how public opinion forms and is measured, including sampling, margin of error, and the limits and uses of polls in a democracy."),
            ("Government Budgets & Public Services", "Explains how governments raise revenue through taxation and allocate spending on services such as education, infrastructure, and defense."),
            ("Global Citizenship & International Organizations", "Introduces the United Nations and other international bodies and examines the responsibilities of citizenship in an interconnected world."),
            ("Digital Citizenship & Online Civic Life", "Examines responsible participation in online civic spaces, including privacy, digital footprints, and the effects of social media on public discourse."),
            ("Service Learning & Community Action", "An applied unit in which students identify a local issue, research it, and design and carry out a community action or service project."),
        ],
        "UG1": [
            ("Comparative Constitutional Design", "Compares presidential and parliamentary systems, unitary and federal arrangements, and how constitutional choices shape political stability."),
            ("Federalism & Multilevel Governance", "Analyzes the division of authority among national, regional, and local governments and the fiscal and political dynamics between levels."),
            ("The Public Policy Process", "Studies agenda setting, policy formulation, adoption, implementation, and evaluation using established models of the policy cycle."),
            ("Political Parties & Party Systems", "Examines how parties organize competition and government, and how electoral rules shape two-party versus multiparty systems."),
            ("Interest Groups & Lobbying", "Analyzes how organized interests form, overcome collective action problems, and seek influence through lobbying, litigation, and campaigns."),
            ("Introduction to Public Administration", "Covers bureaucratic organization, the politics-administration relationship, and the core functions of managing public agencies."),
            ("Foundations of Political Philosophy", "Surveys key thinkers from Plato and Aristotle through Locke, Rousseau, and Mill on justice, authority, liberty, and the social contract."),
            ("Research Methods in Political Science", "Introduces research design, hypothesis testing, and basic quantitative and qualitative methods for studying politics and governance."),
        ],
        "UG2": [
            ("Judicial Review & Constitutional Courts", "Studies the origins and practice of judicial review, comparing constitutional courts across countries and debates over judicial power."),
            ("Civil Society & Social Movements", "Examines how voluntary associations and social movements mobilize, frame grievances, and influence policy and social change."),
            ("Human Rights Law", "Covers the international human rights framework, including the Universal Declaration, core treaties, and regional and domestic enforcement mechanisms."),
            ("Public Budgeting", "Studies budget cycles, revenue forecasting, budget formats, and the political bargaining that shapes government spending decisions."),
            ("Electoral System Design", "Analyzes majoritarian, proportional, and mixed electoral systems and their consequences for representation, accountability, and party competition."),
            ("Legislative Politics & Representation", "Examines how legislatures organize through committees and parties, and theories of how representatives relate to their constituents."),
            ("Comparative Political Institutions", "Compares executives, legislatures, and courts across democracies, assessing how institutional variation affects governance outcomes."),
            ("Local Governance & Urban Politics", "Studies city government structures, metropolitan fragmentation, community power debates, and citizen participation in urban decision-making."),
        ],
        "UG3": [
            ("Deliberative Democracy & Public Participation", "Examines the theory and practice of deliberation, including citizens' assemblies, participatory budgeting, and design principles for public engagement."),
            ("Administrative Law", "Covers the legal framework governing agencies, including delegation, rulemaking procedures, adjudication, and judicial review of agency action."),
            ("Political Communication & Media Politics", "Analyzes how media systems, framing, and campaign communication shape public opinion and electoral outcomes in the digital era."),
            ("Political Behavior & Voter Turnout", "Studies why citizens vote or abstain, how partisanship and identity shape political choices, and interventions that increase participation."),
            ("Nonprofit Organizations & NGO Management", "Examines the role of nonprofits in civic life and covers their governance, funding, accountability, and relationships with government."),
            ("Citizenship & Immigration Policy", "Analyzes how states define membership, comparing naturalization regimes, immigration policy debates, and the rights of noncitizens."),
            ("Civic Education & Pedagogy", "Studies research on how civic knowledge, skills, and dispositions are taught, and prepares students to design effective civic learning experiences."),
            ("Legislative Oversight & Government Accountability", "Covers the tools by which legislatures and auditors monitor the executive, including hearings, inspectors general, and freedom of information laws."),
        ],
        "UG4": [
            ("Democratic Theory Seminar", "An advanced seminar on competing conceptions of democracy, including liberal, republican, participatory, and deliberative traditions and their critics."),
            ("International Law & Global Governance", "Examines the sources of international law, treaty regimes, and how international institutions govern trade, security, and the global commons."),
            ("Election Administration & Electoral Integrity", "Studies how elections are run in practice, covering voter registration systems, ballot security, observation, and threats to electoral integrity."),
            ("Public Policy Evaluation", "Covers designs for evaluating whether public programs work, including experiments, quasi-experiments, and cost-benefit analysis."),
            ("Environmental Politics & Governance", "Analyzes the political challenges of environmental protection, including climate policy, commons governance, and multilevel environmental regulation."),
            ("Conflict Resolution & Peacebuilding", "Studies negotiation, mediation, and post-conflict institutional design, including power-sharing arrangements and transitional justice."),
            ("Technology Policy & Internet Governance", "Examines how governments and multistakeholder bodies regulate digital platforms, data privacy, and speech online."),
            ("Senior Capstone: Applied Civic Research", "Students design and complete an original research or applied project on a governance question, producing a thesis-length paper or policy report."),
        ],
        "M1": [
            ("Policy Analysis Methods", "Graduate training in structuring policy problems, constructing alternatives, applying evaluative criteria, and writing decision-focused policy analysis."),
            ("Regulatory Governance", "Analyzes the design and performance of regulatory agencies and instruments, including cost-benefit review, regulatory capture, and risk regulation."),
            ("Comparative Democratization", "Examines transitions to and from democracy, covering theories of democratization, authoritarian resilience, and democratic backsliding."),
            ("Advanced Public Management", "Studies performance management, contracting and collaborative governance, and organizational reform in public agencies."),
            ("Quantitative Methods for Policy Research", "Covers regression analysis, causal inference designs, and the interpretation of quantitative evidence for policy audiences."),
            ("Institutional Analysis & Design", "Applies frameworks such as Ostrom's IAD to analyze how rules-in-use shape collective action, commons management, and institutional change."),
            ("Ethics in Public Service", "Examines ethical obligations of public officials, including integrity, impartiality, discretion, whistleblowing, and managing conflicts of interest."),
            ("Governance & Development", "Analyzes the relationship between state capacity, institutions, and development outcomes, and evaluates governance-focused aid and reform programs."),
        ],
        "M2": [
            ("Anti-Corruption & Transparency", "Studies the causes and measurement of corruption and evaluates anti-corruption tools, including transparency laws, asset disclosure, and independent agencies."),
            ("Digital Democracy & Civic Technology", "Examines e-government, online participation platforms, open data, and the promises and risks of technology for democratic governance."),
            ("Public Sector Reform", "Analyzes major reform movements, including New Public Management and post-NPM approaches, and the political economy of implementing reform."),
            ("Comparative Public Policy", "Compares how different countries address shared problems such as health, welfare, and environment, and explains cross-national policy variation and diffusion."),
            ("Qualitative & Case Study Methods", "Covers case selection, process tracing, comparative case designs, and interview and archival methods for governance research."),
            ("Participatory Governance & Democratic Innovations", "Evaluates institutional innovations such as citizens' assemblies, sortition, and co-production, drawing on empirical evidence of their effects."),
            ("Crisis Governance & Emergency Management", "Studies how governments prepare for and respond to crises, covering coordination across agencies, risk communication, and post-crisis learning."),
            ("Capstone Research in Governance", "A culminating research project in which students apply theory and methods to an original governance question and defend their findings."),
        ],
    },
}
