#!/usr/bin/env python3
"""Expand every Survival Skills category to 50 lessons, and add a new
"Rope Knots & Advanced Survival Skills" category with at least 50 lessons.

Each category's TOPICS list holds 50 real, distinct, well-established
survival/safety-skill tuples of the form:

    (name, grade_range, adult_supervision_required, learning_objectives,
     key_steps, practice_activities, quiz, important_note)

  - name: short lesson name
  - grade_range: e.g. "1-4", "5-8", "9-12", "Adult"
  - adult_supervision_required: bool
  - learning_objectives: list of 2-3 short strings
  - key_steps: list of 3-5 short, accurate step strings
  - practice_activities: list of 1-2 short strings
  - quiz: list of 1-2 (question, answer) tuples
  - important_note: one safety/context note string

build_skill() turns each tuple into the exact JSON schema already used by
existing entries in survival_skills.json (see SurvivalSkills.jsx), adding
resource-search links (YouTube/text-guide/Wikipedia search links -- not
guessed direct URLs, consistent with this project's no-fabrication rule).

Re-run after editing:
    python3 backend/scripts/generate_survival_skills_expansion.py
"""
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import quote_plus

BASE_DIR = Path(__file__).resolve().parent.parent
SURVIVAL_PATH = BASE_DIR / "data" / "survival_skills" / "survival_skills.json"

NEW_CATEGORY_ID = "rope_knots_advanced_survival"


def yt_search(q: str) -> str:
    return "https://www.youtube.com/results?search_query=" + quote_plus(q)


def wikihow_search(q: str) -> str:
    return "https://www.wikihow.com/wikiHowTo?search=" + quote_plus(q)


def wikipedia_search(q: str) -> str:
    return "https://en.wikipedia.org/w/index.php?search=" + quote_plus(q)


# TOPICS[category_id] = list of 50 tuples:
#   (name, grade_range, adult_supervision_required, learning_objectives,
#    key_steps, practice_activities, quiz, important_note)
TOPICS: dict[str, list[tuple]] = {}

TOPICS["personal_safety"] = [
    ("Playground Safety and Awareness", "1-4", True,
     ["Recognize safe versus unsafe playground behavior", "Know what to do if separated from an adult"],
     ["Stay where a supervising adult can see you", "Use equipment the way it was designed to be used",
      "Tell an adult right away if a stranger talks to you", "Stay near a friend or sibling"],
     ["Role-play what to do if you get separated from your adult at the playground"],
     [("What should you do if a stranger talks to you at the playground?", "Move away and tell a trusted adult right away")],
     "Young children should always be supervised by a trusted adult at playgrounds."),
    ("Safe Walking to and from School", "1-4", True,
     ["Learn safe routes and crossing habits", "Know who to ask for help along the way"],
     ["Always walk with a buddy or group when possible", "Cross streets only at marked crossings with an adult or crossing guard",
      "Know your route and stick to it", "Never accept rides from someone you do not know"],
     ["Walk the school route once with a parent and point out safe stopping places"],
     [("Where should you cross the street?", "At a marked crosswalk or with a crossing guard")],
     "Children should practice routes with a parent before walking independently."),
    ("Bicycle Safety Basics", "1-4", True,
     ["Understand helmet and gear safety", "Learn basic road and path rules for young riders"],
     ["Always wear a properly fitted helmet", "Ride on sidewalks or paths approved for children, not busy roads",
      "Stop and look both ways before crossing", "Ride with an adult until skills and judgment are ready"],
     ["Practice a helmet fit check before every ride"],
     [("What should you always wear when biking?", "A properly fitted helmet")],
     "Adult supervision is recommended until a child can reliably follow traffic rules."),
    ("School Bus Safety Rules", "1-4", True,
     ["Learn safe boarding and riding behavior", "Know the danger zone around a bus"],
     ["Wait for the bus a safe distance from the curb", "Never walk behind a bus",
      "Stay seated with a seatbelt if provided", "Wait for the driver's signal before crossing in front of the bus"],
     ["Practice identifying the bus danger zone using a picture or diagram"],
     [("Where is it never safe to walk near a bus?", "Behind the bus")],
     "Bus safety rules should be reinforced by parents and school staff regularly."),
    ("Family Safe Word and Check-In Code", "1-4", False,
     ["Understand why families use a secret safe word", "Know when to use the safe word"],
     ["Agree on a private family safe word nobody else knows", "Never go anywhere with someone who cannot say the safe word",
      "Practice saying the safe word out loud together", "Tell a trusted adult if someone asks for the word but seems unfamiliar"],
     ["Create a family safe word together and practice a pretend pickup scenario"],
     [("Why do families use a safe word?", "To confirm that a person picking up a child is truly trusted")],
     "Choose a safe word together as a family and keep it private."),
    ("Meeting New Animals Safely", "1-4", True,
     ["Learn how to approach unfamiliar animals safely", "Recognize warning signs from animals"],
     ["Always ask the owner before petting an animal", "Let the animal sniff your hand first",
      "Avoid running or screaming near strange animals", "Tell an adult if a stray or aggressive animal approaches"],
     ["Practice asking permission with a stuffed animal role-play"],
     [("What should you do before petting a strange dog?", "Ask the owner first")],
     "Adults should supervise young children around any unfamiliar animal."),
    ("Fire Drill and School Safety Routines", "1-4", True,
     ["Understand the purpose of school safety drills", "Know how to follow drill instructions calmly"],
     ["Listen carefully to teacher instructions during drills", "Walk quickly and quietly, do not run",
      "Know your classroom's designated exit and meeting spot", "Never go back inside for belongings"],
     ["Practice walking calmly in a line to a pretend meeting spot"],
     [("What should you never do during a fire drill?", "Go back inside for belongings")],
     "School drills are supervised by teachers and staff for safety."),
    ("Safety at the Pool and Beach with Others", "1-4", True,
     ["Learn buddy-system rules around water", "Know how to signal for help near water"],
     ["Always swim with a buddy and a supervising adult", "Never go near water without permission",
      "Learn to recognize a lifeguard and where they are", "Call for help loudly if someone is struggling in water"],
     ["Practice identifying the lifeguard stand and buddy check-ins during a pool visit"],
     [("Who should always be present when a young child is near water?", "A supervising adult")],
     "Adult supervision is required at all times near pools, beaches, and open water."),
    ("Recognizing Trusted Adults", "1-4", False,
     ["Learn to identify a short list of trusted adults", "Understand the difference between trusted adults and strangers"],
     ["Make a list of trusted adults with a parent", "Know that trusted adults do not ask you to keep secrets from parents",
      "Feel comfortable telling any trusted adult if something feels wrong", "Check with a parent before adding someone new to the list"],
     ["Draw or list five trusted adults together with a parent"],
     [("What is one sign an adult may not be trustworthy?", "Asking you to keep a secret from your parents")],
     "Review and update the trusted adult list periodically with your child."),
    ("Saying No and Telling a Trusted Adult", "1-4", False,
     ["Build confidence to say no to uncomfortable requests", "Understand that telling an adult is never tattling"],
     ["Practice saying \"No\" in a firm, clear voice", "Walk or run away from the uncomfortable situation",
      "Tell a trusted adult as soon as possible", "Keep telling adults until someone listens and helps"],
     ["Role-play saying no firmly to a pretend uncomfortable request"],
     [("Is telling an adult about an uncomfortable situation considered tattling?", "No, it is a safe and important thing to do")],
     "Reassure children that they will never be in trouble for telling the truth about feeling unsafe."),
    ("Stranger Danger at Malls and Public Places", "5-8", True,
     ["Recognize how to stay safe in crowded public places", "Know what to do if lost in a mall or store"],
     ["Agree on a meeting spot with family before entering a crowded place", "If separated, go to a checkout counter or uniformed staff member",
      "Never leave with someone you do not know, even if they claim to know your parent", "Stay in well-lit, busy areas"],
     ["Practice identifying a store employee versus a stranger during a shopping trip"],
     [("If you get lost in a mall, who should you ask for help?", "A uniformed staff member or store employee")],
     "Practice this plan together before visiting busy public places."),
    ("Safety in Elevators and Escalators", "5-8", True,
     ["Learn safe elevator and escalator behavior", "Recognize warning signs of an unsafe situation"],
     ["Stand near the control panel, not the back corner, when alone", "Hold the handrail on escalators and avoid loose clothing near the edges",
      "If someone makes you uncomfortable in an elevator, exit at the next floor", "Avoid elevators with people who seem suspicious when possible"],
     ["Practice locating the emergency button in a building elevator"],
     [("What should you do if you feel unsafe in an elevator?", "Exit at the next floor as soon as possible")],
     "Young children should use elevators and escalators with adult supervision."),
    ("Bullying Awareness and How to Respond", "5-8", False,
     ["Recognize different forms of bullying", "Learn safe ways to respond and seek help"],
     ["Identify bullying behavior such as teasing, exclusion, or hitting", "Use a firm voice and walk away when possible",
      "Tell a trusted adult, such as a teacher or parent", "Support a peer who is being bullied by including them or telling an adult"],
     ["Role-play responding calmly to a teasing scenario"],
     [("What should you do if you see someone being bullied?", "Tell a trusted adult and, if safe, support the person being bullied")],
     "Encourage children to report bullying rather than handle it alone."),
    ("Cyberbullying Awareness and Response", "5-8", False,
     ["Recognize cyberbullying in messages, games, and social media", "Learn how to respond and report it"],
     ["Do not respond to or forward mean messages", "Save or screenshot the evidence", "Block the person and report to the platform",
      "Tell a parent or trusted adult right away"],
     ["Practice using a platform's block and report features with a parent"],
     [("What is the first step if you receive a mean message online?", "Do not respond, save the evidence, and tell a trusted adult")],
     "Talk with a trusted adult before blocking or reporting so they can help document the issue."),
    ("Safe Passwords and Privacy Settings", "5-8", False,
     ["Learn how to create a strong password", "Understand basic privacy settings on apps and devices"],
     ["Use long passwords mixing letters, numbers, and symbols", "Never share passwords with friends, even close ones",
      "Set social media and game profiles to private", "Ask a parent before changing privacy settings"],
     ["Practice creating a strong sample password together with a parent"],
     [("Should you share your password with a close friend?", "No, passwords should never be shared")],
     "Parents should help set up and review privacy settings for children's accounts."),
    ("Safe Gaming and Voice Chat Etiquette", "5-8", True,
     ["Learn safe habits for online gaming and voice chat", "Recognize red flags from strangers in games"],
     ["Never share your real name, school, or address in games", "Mute or block players who make you uncomfortable",
      "Tell a parent if a stranger asks personal questions", "Only add people you know in real life as friends"],
     ["Review privacy and chat settings on a game together with a parent"],
     [("What personal information should never be shared in online games?", "Your real name, school, or address")],
     "Parents should monitor and periodically review children's online gaming interactions."),
    ("Recognizing Grooming Behavior Online", "5-8", False,
     ["Learn to recognize warning signs of grooming", "Understand the importance of telling an adult immediately"],
     ["Be cautious of adults or strangers who give excessive compliments or gifts online", "Notice requests to keep a friendship secret from parents",
      "Never share photos or personal details with online-only contacts", "Tell a trusted adult immediately about any uncomfortable online contact"],
     ["Discuss real examples of grooming red flags with a parent or teacher"],
     [("What is a common grooming red flag?", "An adult asking to keep the relationship secret from parents")],
     "This topic should be discussed openly with a parent, teacher, or counselor."),
    ("Digital Footprint Awareness", "5-8", False,
     ["Understand that online posts can be permanent", "Learn to think before posting"],
     ["Assume anything posted online could be seen by anyone, forever", "Avoid posting your location in real time",
      "Ask a parent before posting photos of yourself or friends", "Search your own name occasionally with a parent to see what is public"],
     ["Do a family search of a sample name to see what information appears publicly"],
     [("Why should you think before posting something online?", "Because it can be permanent and seen by many people")],
     "Review privacy settings with a parent regularly."),
    ("Safety at Sleepovers and Friends' Houses", "5-8", True,
     ["Learn what to check before staying overnight elsewhere", "Know how to handle an uncomfortable situation"],
     ["Make sure a parent knows the address and contact number of the house", "Keep a phone or way to contact a parent if needed",
      "Trust your feelings if something seems wrong and call a parent", "Know the family's fire exits and meeting point"],
     ["Practice calling a parent from a friend's phone as a drill"],
     [("What should a parent know before a sleepover?", "The address and contact number of the host family")],
     "Parents should communicate with host families and confirm supervision plans."),
    ("Public Transport Safety Basics", "5-8", True,
     ["Learn safe habits for buses, trains, and taxis", "Know how to handle getting lost or separated"],
     ["Stay close to a trusted adult and hold hands or bags in crowds", "Know the stop name and route in advance",
      "Sit near the driver or in view of staff when possible", "If separated, stay where you are and ask staff for help"],
     ["Practice reading a transit map with an adult before a trip"],
     [("If you get separated on public transport, what should you do?", "Stay put and ask a uniformed staff member for help")],
     "Children should use public transport with adult supervision until old enough to travel independently."),
    ("Safety at Large Public Events and Crowds", "5-8", True,
     ["Learn crowd safety basics", "Know the family plan if separated in a crowd"],
     ["Agree on a meeting point before entering a crowded event", "Wear bright or easily identifiable clothing",
      "If separated, stay in one place and ask event staff or security for help", "Avoid pushing through tight crowds"],
     ["Pick a meeting point together before your next family outing"],
     [("What should you do first if separated from family in a crowd?", "Stay where you are and find event staff or security")],
     "Review the family meeting plan before every large event."),
    ("Basic Situational Awareness", "5-8", False,
     ["Learn to notice surroundings and possible risks", "Build the habit of planning an exit or response"],
     ["Notice exits and safe adults when entering a new place", "Keep phones and headphones down enough to hear surroundings",
      "Trust uneasy feelings and move to a safer area", "Walk confidently and stay aware, not distracted"],
     ["Practice naming two exits the next time you enter a store or building"],
     [("Why is it useful to notice exits when entering a building?", "So you know how to leave quickly if something feels unsafe")],
     "Situational awareness is a lifelong skill best practiced regularly in everyday settings."),
    ("Trusting Your Instincts and Gut Feelings", "5-8", False,
     ["Understand that feelings of unease are worth listening to", "Learn to act on instincts rather than ignore them"],
     ["Notice physical signs of unease, like a fast heartbeat", "Leave a situation that feels wrong, even without a clear reason",
      "Tell a trusted adult about the feeling right away", "Remember it is okay to be wrong; safety comes first"],
     ["Discuss a time you felt uneasy and what you did about it"],
     [("Is it okay to leave a situation just because it feels wrong?", "Yes, trusting instincts is an important safety skill")],
     "Reassure children that acting on instinct is never wrong, even if the situation turns out to be harmless."),
    ("Peer Pressure and Saying No", "5-8", False,
     ["Recognize peer pressure situations", "Practice confident ways to say no"],
     ["Notice when friends push you to do something unsafe or uncomfortable", "Use a simple, firm \"No, I do not want to\"",
      "Suggest a different activity instead", "Walk away and find a trusted adult if pressure continues"],
     ["Role-play saying no to a peer pressure scenario"],
     [("What is a simple way to respond to peer pressure?", "A firm and clear \"No, I do not want to\"")],
     "Encourage open conversation with a trusted adult about peer pressure experiences."),
    ("Personal ID and Important Documents Awareness", "5-8", False,
     ["Learn why ID and documents matter", "Know where family keeps important papers"],
     ["Know your full name, address, and a parent's phone number", "Understand documents like birth certificates are kept safe at home",
      "Never carry or show ID to strangers who ask", "Ask a parent where family documents are stored in an emergency"],
     ["Memorize a parent's phone number and practice reciting it"],
     [("What personal information should every child memorize?", "Full name, address, and a parent's phone number")],
     "Keep important documents in a safe, fire-resistant location known to trusted adults."),
    ("Safety When Home Alone", "5-8", True,
     ["Learn rules for staying home alone briefly", "Know how to handle common situations like the doorbell or phone"],
     ["Never open the door to strangers", "Do not tell callers or visitors that you are home alone",
      "Know emergency numbers and a trusted neighbor's contact", "Keep doors and windows locked while alone"],
     ["Practice a pretend doorbell scenario with a parent"],
     [("What should you say if a stranger asks if you are home alone?", "Never confirm you are alone; say an adult is unavailable right now")],
     "Only leave children home alone briefly once age, maturity, and local guidelines support it, with clear rules set."),
    ("Reporting Abuse or Unsafe Situations", "5-8", False,
     ["Understand what abuse or neglect can look like", "Learn there are safe adults and hotlines to report to"],
     ["Recognize signs that a situation is not okay, such as being hurt or scared", "Tell a trusted adult, teacher, or counselor",
      "Know that child helplines exist for reporting concerns", "Keep telling adults until someone listens and helps"],
     ["Identify three trusted adults at school who can help with a report"],
     [("What should you do if telling one adult does not help?", "Keep telling other trusted adults until someone helps")],
     "Reporting is always the right choice; children are never at fault for unsafe situations."),
    ("Recognizing and Avoiding Scams Aimed at Kids", "5-8", False,
     ["Learn common scam tactics targeting children", "Understand why offers that sound too good are risky"],
     ["Be suspicious of prize, gift card, or free item offers online", "Never click links or give information for a \"free\" prize",
      "Ask a parent before entering any contest or giveaway", "Report suspicious messages to a parent immediately"],
     ["Look at a sample scam message together and identify the warning signs"],
     [("What is a warning sign of an online scam?", "An offer of a free prize that seems too good to be true")],
     "Review scam examples with a parent regularly as tactics change."),
    ("Basic First Aid for Personal Safety Incidents", "5-8", True,
     ["Learn simple first aid steps for minor injuries from unsafe situations", "Know when to call for adult help"],
     ["Clean and cover minor cuts or scrapes", "Apply a cold compress to bumps or bruises",
      "Call an adult immediately for anything serious", "Know how to dial local emergency services if no adult is available"],
     ["Practice using a basic first aid kit under adult supervision"],
     [("What should you do for a serious injury?", "Call an adult or emergency services immediately")],
     "Basic first aid should be taught and supervised by a trained adult or first aid course."),
    ("Verbal Self-Defense and Assertiveness", "5-8", False,
     ["Build confident, assertive communication", "Learn to set clear verbal boundaries"],
     ["Use a strong, clear voice and direct eye contact", "State boundaries clearly, such as \"Stop, I do not like that\"",
      "Stand tall and confident in body language", "Walk away after stating a boundary if it is not respected"],
     ["Practice assertive phrases in front of a mirror or with a trusted adult"],
     [("What is an example of an assertive boundary statement?", "\"Stop, I do not like that\" said in a clear, firm voice")],
     "Assertiveness training works best alongside real practice with trusted adults."),
    ("Babysitting Safety Basics", "9-12", True,
     ["Learn responsibilities and safety checks before babysitting", "Know how to handle common emergencies while caring for children"],
     ["Get emergency contacts and house rules from parents in advance", "Do a safety walkthrough of the home before parents leave",
      "Know basic first aid and how to reach emergency services", "Never leave young children unsupervised, even briefly"],
     ["Complete a basic babysitting or first aid course before babysitting alone"],
     [("What should a babysitter get from parents before they leave?", "Emergency contacts and house safety rules")],
     "Many communities offer certified babysitting safety courses; taking one is recommended."),
    ("Safe Use of Ride-Sharing and Taxi Apps", "9-12", True,
     ["Learn how to verify a ride-share driver and vehicle", "Know safety steps to take before, during, and after a ride"],
     ["Check the driver's name, photo, and license plate before entering", "Share trip details live with a trusted contact",
      "Sit in the back seat and keep the app's trip tracking on", "Trust your instincts and exit if anything feels wrong"],
     ["Practice checking a sample ride confirmation for matching details"],
     [("What should you check before getting into a ride-share vehicle?", "The driver's name, photo, and license plate match the app")],
     "Teens should use ride-sharing apps with parental knowledge and agreed safety rules."),
    ("Recognizing Phishing and Online Scams", "9-12", False,
     ["Learn to identify phishing emails and messages", "Understand safe responses to suspicious requests"],
     ["Check sender addresses and links carefully before clicking", "Never give passwords or personal information by email or text",
      "Look for urgent or threatening language as a warning sign", "Verify requests directly with the organization through official channels"],
     ["Examine a sample phishing email and identify three warning signs"],
     [("What is a common sign of a phishing message?", "Urgent language pressuring you to click a link or share information quickly")],
     "When in doubt, verify a message independently rather than clicking any links."),
    ("Catfishing and Fake Profile Awareness", "9-12", False,
     ["Recognize signs of a fake online identity", "Learn safe ways to verify who you are talking to"],
     ["Be cautious of profiles with few photos or a short history", "Watch for inconsistent stories or refusal to video chat",
      "Never send money or personal photos to an online-only contact", "Tell a trusted adult about suspicious online relationships"],
     ["Review a sample profile together and list signs it could be fake"],
     [("What is a warning sign of a fake online profile?", "Refusing to video chat or share consistent details")],
     "Discuss any online relationship concerns with a parent or trusted adult."),
    ("Safety in Unfamiliar Neighborhoods", "9-12", True,
     ["Learn how to navigate unfamiliar areas safely", "Know how to plan ahead before visiting a new place"],
     ["Research the area and plan a route before going", "Stay in well-lit, populated areas, especially after dark",
      "Keep a charged phone and share your location with a trusted contact", "Trust instincts and leave if the area feels unsafe"],
     ["Plan a sample safe route to an unfamiliar location using a map app"],
     [("What should you check before visiting an unfamiliar area?", "The route, area reputation, and lighting conditions")],
     "Teens should share travel plans with a parent or guardian when exploring new areas."),
    ("Night-Time Outdoor Safety", "9-12", True,
     ["Learn safety habits for being outside after dark", "Understand visibility and awareness at night"],
     ["Walk in well-lit, populated areas whenever possible", "Wear bright or reflective clothing",
      "Stay aware of surroundings rather than distracted by a phone", "Travel with a friend or let someone know your route and return time"],
     ["Plan a well-lit route for an evening walk with a friend or adult"],
     [("Why is it safer to walk with a friend at night?", "There is safety in numbers and someone can get help if needed")],
     "Younger teens should have adult awareness of any night-time outdoor plans."),
    ("Safety When Meeting Online Friends in Person", "9-12", True,
     ["Learn safe steps before meeting an online contact in real life", "Understand the importance of parental involvement"],
     ["Always tell a parent or trusted adult about the plan first", "Meet only in public, well-lit places with other people around",
      "Bring a friend or have a trusted adult present nearby", "Arrange your own transportation to and from the meeting"],
     ["Practice explaining a meetup plan to a parent for feedback"],
     [("Who should always know before meeting an online friend in person?", "A parent or trusted adult")],
     "Meeting online contacts in person should always involve a parent's knowledge and, ideally, presence."),
    ("Consent and Personal Boundaries in Relationships", "9-12", False,
     ["Understand consent as an ongoing, clear agreement", "Recognize the right to set and respect personal boundaries"],
     ["Understand that consent must be clear and can be withdrawn anytime", "Respect a partner's or friend's stated boundaries",
      "Communicate your own boundaries clearly and confidently", "Talk to a trusted adult if a boundary is not respected"],
     ["Discuss age-appropriate examples of respecting boundaries with a parent or educator"],
     [("Can consent be withdrawn after it is given?", "Yes, consent can be withdrawn at any time")],
     "This topic is best discussed with guidance from a parent, school counselor, or health educator."),
    ("Recognizing Coercive Control and Relationship Red Flags", "9-12", False,
     ["Learn warning signs of controlling or unhealthy relationships", "Know where to get help if needed"],
     ["Notice excessive jealousy, isolation from friends, or constant monitoring", "Recognize pressure or guilt used to control behavior",
      "Talk to a trusted adult or counselor about concerning relationship patterns", "Know that healthy relationships involve respect and trust"],
     ["List qualities of a healthy relationship versus a controlling one"],
     [("What is a red flag in an unhealthy relationship?", "Attempts to isolate you from friends and family or control your actions")],
     "Discuss relationship concerns with a trusted adult, counselor, or helpline."),
    ("Basic Physical Self-Defense Awareness", "9-12", True,
     ["Learn the goal of self-defense is to escape, not fight", "Understand basic principles of personal space and escape"],
     ["Create distance and look for an escape route first", "Use a loud voice to draw attention and deter an attacker",
      "Target vulnerable areas only if truly necessary to escape danger", "Get to a safe, populated place and call for help immediately after"],
     ["Take a basic self-defense class with a certified instructor"],
     [("What is the primary goal of self-defense?", "To escape safely, not to fight")],
     "Physical self-defense techniques should be learned from a certified instructor, with adult involvement for younger teens."),
    ("Personal Safety Devices: Whistles and Alarms", "9-12", False,
     ["Learn how personal alarms and whistles can help in an emergency", "Know when and how to use them effectively"],
     ["Carry a whistle or personal alarm when walking alone", "Use it loudly to attract attention if threatened",
      "Keep the device easily accessible, not buried in a bag", "Combine the device with moving toward people or safety"],
     ["Practice using a whistle or alarm at a safe volume to learn how it sounds"],
     [("Why carry a personal alarm or whistle?", "To attract attention and deter a threat in an emergency")],
     "Personal safety devices are a helpful tool but should be combined with other safety habits."),
    ("Distracted Driving and Passenger Safety", "9-12", True,
     ["Understand the risks of distracted driving", "Learn passenger responsibilities for safety"],
     ["Always wear a seatbelt, as driver or passenger", "Avoid distracting a driver with noise or phone use",
      "Speak up if a driver is distracted, tired, or driving unsafely", "Know how to ask to be dropped off if a ride feels unsafe"],
     ["Practice reminding a driver to buckle up before starting a trip"],
     [("What is a passenger's responsibility if a driver seems unsafe?", "Speak up and ask to stop or be dropped off safely")],
     "Learner drivers should always have a licensed adult supervising practice."),
    ("Campus and School Safety for Teens", "9-12", False,
     ["Learn school safety procedures and resources", "Know how to report safety concerns at school"],
     ["Know the locations of school exits and safety officers", "Follow lockdown and evacuation drill instructions carefully",
      "Report suspicious behavior or threats to school staff immediately", "Know who the school counselor or safety contact is"],
     ["Locate the nearest two exits in each regular classroom"],
     [("Who should you tell if you notice a safety threat at school?", "A teacher, school staff member, or school safety officer")],
     "Follow your school's official safety and emergency procedures."),
    ("Safe Dating Practices for Teens", "9-12", True,
     ["Learn safety habits for dating and social outings", "Understand the value of parental awareness of plans"],
     ["Tell a parent or trusted adult who you are meeting and where", "Meet in public places for early dates",
      "Arrange your own transportation to and from the date", "Trust your instincts and have an exit plan if uncomfortable"],
     ["Plan a sample safe first-date scenario and discuss it with a parent"],
     [("Why is it safer to meet in a public place for an early date?", "There are other people around who could help if needed")],
     "Parents should be aware of dating plans, especially for younger teens."),
    ("Identity Theft Prevention Basics", "9-12", False,
     ["Learn what personal information is sensitive", "Understand basic steps to protect personal identity"],
     ["Never share Social Security or ID numbers online or by phone", "Shred documents with personal information before discarding",
      "Use strong, unique passwords for financial and school accounts", "Check with a parent before sharing personal details on any form"],
     ["Review a sample form together and identify which fields are sensitive"],
     [("What should be done with documents containing personal information?", "Shred them before discarding")],
     "Teens should involve a parent when managing any accounts containing personal information."),
    ("Stalking Awareness and Safety Planning", "Adult", False,
     ["Recognize signs of stalking behavior", "Learn how to build a personal safety plan"],
     ["Document dates, times, and details of concerning contact", "Vary routes and routines if being followed or watched",
      "Inform trusted friends, family, and employers of the situation", "Contact local police or a stalking hotline for support and a safety plan"],
     ["Draft a basic personal safety plan including trusted contacts and documentation habits"],
     [("Why is documenting incidents important in a stalking situation?", "It provides evidence for law enforcement or legal action")],
     "Contact local law enforcement or a victim support hotline for stalking situations; this is informational only."),
    ("Workplace Safety Awareness", "Adult", False,
     ["Learn general workplace safety rights and practices", "Know how to identify and report hazards"],
     ["Learn your workplace's emergency exits and procedures", "Report unsafe equipment or conditions to a supervisor",
      "Know your right to refuse clearly unsafe work in many jurisdictions", "Keep emergency contact information updated with your employer"],
     ["Locate your workplace's posted emergency evacuation plan"],
     [("What should you do if you notice an unsafe workplace condition?", "Report it to a supervisor or safety officer")],
     "Workplace safety rules vary by location and industry; follow your employer's official policies."),
    ("Workplace Harassment Awareness and Reporting", "Adult", False,
     ["Recognize different forms of workplace harassment", "Learn safe, effective ways to report it"],
     ["Document incidents with dates, details, and witnesses if possible", "Review your workplace's harassment reporting policy",
      "Report to Human Resources or a designated safety officer", "Seek support from trusted colleagues, friends, or professional organizations"],
     ["Locate your workplace's harassment policy and reporting contact"],
     [("What is a good first step after experiencing workplace harassment?", "Document the incident and report it through official channels")],
     "Consult your employer's policy or local labor authority for formal guidance."),
    ("Safe Travel Alone: Hotel and Trip Safety", "Adult", False,
     ["Learn safety habits for solo travel", "Know how to choose and secure accommodation"],
     ["Share your itinerary with a trusted contact at home", "Choose reputable accommodations and verify entrances lock securely",
      "Keep valuables secured and avoid displaying them publicly", "Stay aware of surroundings and trust instincts in unfamiliar places"],
     ["Create a simple travel safety checklist before your next trip"],
     [("Why should you share your itinerary with someone at home?", "So someone knows your plans if you cannot be reached")],
     "Research destination-specific safety guidance before traveling."),
    ("Elder Safety, Fraud, and Financial Scam Protection", "Adult", False,
     ["Recognize scams commonly targeting older adults", "Learn protective steps for finances and personal information"],
     ["Never give personal or financial information to unsolicited callers", "Verify requests independently through official phone numbers",
      "Set up trusted contacts on financial accounts where available", "Report suspected fraud to family, the bank, and local authorities promptly"],
     ["Review a sample scam call script and identify red flags together"],
     [("What should you do if an unsolicited caller asks for financial information?", "Hang up and verify independently through an official number")],
     "Encourage older adults to discuss unusual financial requests with a trusted family member before acting."),
]

TOPICS["emergency_preparedness"] = [
    ("Fire Drill Practice at Home", "1-4", True,
     ["Learn what to do when a smoke alarm sounds", "Practice a calm, quick exit from the home"],
     ["Get low and go to the nearest safe exit when the alarm sounds", "Never hide from a fire; go to the family meeting spot outside",
      "Practice two ways out of every room", "Call for help once outside; never go back inside"],
     ["Practice a home fire drill with a parent twice a year"],
     [("What should you do if you hear a smoke alarm?", "Get low, go to the nearest exit, and meet outside at the family spot")],
     "Practice home fire drills regularly with a parent or guardian."),
    ("Knowing Your Home Address and Emergency Numbers", "1-4", False,
     ["Memorize home address and key emergency numbers", "Understand when to use this information"],
     ["Learn your full home address by heart", "Memorize a parent's phone number",
      "Know the local emergency number for your country", "Practice reciting this information clearly and calmly"],
     ["Sing or repeat the address and numbers until memorized"],
     [("What is the local emergency number you should know?", "It varies by country; know your local one, such as 911, 112, or 999")],
     "Emergency numbers vary by country; confirm the correct one for your area."),
    ("What to Do If You Smell Smoke", "1-4", True,
     ["Recognize smoke as a fire warning sign", "Learn the correct immediate response"],
     ["Alert an adult immediately if you smell or see smoke", "Do not investigate the source yourself",
      "Get low and head to the nearest exit if told to leave", "Meet at the family's outside meeting spot"],
     ["Practice describing what to do if smoke is smelled during a pretend scenario"],
     [("Should a child investigate the source of smoke alone?", "No, always alert an adult immediately")],
     "Children should never attempt to locate or fight a fire themselves."),
    ("Stop, Drop, and Roll Basics", "1-4", True,
     ["Learn what to do if clothing catches fire", "Practice the stop, drop, and roll technique"],
     ["Stop moving immediately, do not run", "Drop to the ground right away",
      "Cover your face with your hands", "Roll back and forth until the flames are out"],
     ["Practice the stop, drop, and roll motion on a soft, safe surface"],
     [("What should you do first if your clothing catches fire?", "Stop moving immediately, do not run")],
     "Practice this technique with adult supervision on a soft surface."),
    ("Meeting Point Planning for Families", "1-4", True,
     ["Understand why families choose an outside meeting spot", "Know your family's meeting spot"],
     ["Choose a safe spot outside and a safe distance from the home", "Practice walking to the spot during a drill",
      "Know that everyone should go straight there in an emergency", "Never go back inside once at the meeting spot"],
     ["Walk to your family's meeting spot together and time it"],
     [("Where should everyone go during a home emergency?", "The family's agreed outside meeting spot")],
     "Choose a meeting spot together with the whole family and revisit it yearly."),
    ("Thunderstorm and Lightning Safety", "1-4", True,
     ["Learn safe behavior during thunderstorms", "Understand the danger of lightning outdoors"],
     ["Go inside a sturdy building or hard-topped vehicle when thunder is heard", "Stay away from windows during a storm",
      "Avoid water, tall trees, and metal objects outdoors", "Wait 30 minutes after the last thunder before going back outside"],
     ["Practice the \"when thunder roars, go indoors\" rule during the next storm"],
     [("How long should you wait after the last thunder before going outside?", "About 30 minutes")],
     "Adults should supervise children indoors during thunderstorms."),
    ("Safety During a Power Outage", "1-4", True,
     ["Learn what to do when the lights go out unexpectedly", "Recognize safe light and heat sources"],
     ["Stay calm and use a flashlight, not candles, for light", "Keep the refrigerator closed to keep food cold",
      "Stay away from downed power lines if outside", "Wait with an adult for power to be restored"],
     ["Locate the family flashlight together and check the batteries"],
     [("What should you use for light during a power outage instead of candles?", "A flashlight")],
     "Keep flashlights and batteries in an easy-to-find location for outages."),
    ("Basic Emergency Call Practice", "1-4", True,
     ["Learn when and how to call for emergency help", "Practice speaking clearly to a dispatcher"],
     ["Only call emergency numbers for real emergencies", "State your name, address, and what is happening clearly",
      "Stay on the line and answer the dispatcher's questions", "Do not hang up until told it is okay"],
     ["Practice a pretend emergency call with a parent using a toy phone"],
     [("What information should you give first in an emergency call?", "Your name, address, and what is happening")],
     "Practice this only with a trusted adult using a disconnected or toy phone."),
    ("Tornado Safety Basics", "5-8", True,
     ["Recognize tornado warning signs and alerts", "Learn the safest place to shelter during a tornado"],
     ["Go to a basement or small interior room on the lowest floor", "Stay away from windows and cover your head and neck",
      "Listen to a weather radio or phone alert for updates", "Know the difference between a tornado watch and a tornado warning"],
     ["Practice a tornado drill by moving quickly to the safest room at home"],
     [("What is the safest place to shelter during a tornado?", "A small interior room or basement on the lowest floor, away from windows")],
     "Follow official weather alerts and local emergency guidance during tornado season."),
    ("Wildfire Awareness and Evacuation Basics", "5-8", True,
     ["Recognize wildfire risk signs", "Learn the basics of a wildfire evacuation plan"],
     ["Know your community's evacuation routes and alerts", "Keep a go-bag ready during high wildfire risk seasons",
      "Follow official evacuation orders immediately, do not wait", "Close windows and doors when leaving to slow fire spread"],
     ["Review your family's wildfire evacuation route on a map"],
     [("What should you do when an evacuation order is given?", "Leave immediately following the official route")],
     "Always follow official evacuation orders from local fire and emergency authorities."),
    ("Family Communication Plan During Disasters", "5-8", False,
     ["Learn why families need a communication plan", "Know how to reconnect if separated"],
     ["Choose an out-of-area contact everyone can call", "Memorize or write down key phone numbers",
      "Agree on backup meeting locations if home is not accessible", "Practice texting, since texts may work when calls do not"],
     ["Create a family contact card with numbers and meeting points"],
     [("Why choose an out-of-area contact for a family plan?", "Local lines may be busy, but a distant contact is often easier to reach")],
     "Update the family communication plan yearly or after any address change."),
    ("Evacuation Route Planning", "5-8", True,
     ["Learn how to plan a safe evacuation route", "Understand backup route planning"],
     ["Identify at least two ways out of your neighborhood", "Keep a paper map as backup in case phones lose signal",
      "Practice driving or walking the routes with a family member", "Know where local shelters are along each route"],
     ["Draw a simple map of two evacuation routes from your home"],
     [("Why is it useful to know more than one evacuation route?", "The main route may be blocked or unsafe during an emergency")],
     "Practice evacuation routes with an adult before an emergency occurs."),
    ("Sheltering in Place vs Evacuating", "5-8", False,
     ["Understand the difference between sheltering in place and evacuating", "Learn how to decide which applies to a given emergency"],
     ["Follow official guidance on whether to shelter or evacuate", "Shelter in place by sealing windows and doors if instructed for airborne hazards",
      "Evacuate immediately if told to, taking your emergency kit", "Keep a radio or phone on for updated instructions"],
     ["Discuss with family which emergencies call for sheltering versus evacuating"],
     [("Who decides whether to shelter in place or evacuate?", "Local emergency officials, through official alerts")],
     "Always follow official instructions from local emergency management authorities."),
    ("Disaster Supply Kit for Pets", "5-8", True,
     ["Learn what pets need during an emergency", "Understand how to include pets in a family plan"],
     ["Pack food, water, and medication for pets in the kit", "Include a leash, carrier, and copies of vaccination records",
      "Know which shelters or hotels accept pets in your area", "Update pet identification tags with current contact information"],
     ["Assemble a small pet emergency kit with a parent"],
     [("What documents should be kept for pets in an emergency kit?", "Vaccination records and identification information")],
     "Research pet-friendly shelters in your area ahead of time."),
    ("Basic Emergency Radio Use", "5-8", False,
     ["Learn how a battery or hand-crank radio works", "Understand why radios matter when power or cell service is down"],
     ["Keep a battery or hand-crank emergency radio in your kit", "Know how to tune to local emergency broadcast stations",
      "Change or charge batteries regularly", "Use the radio only for updates, not to drain batteries unnecessarily"],
     ["Practice tuning a hand-crank radio to a local station"],
     [("Why is an emergency radio useful during a power outage?", "It can receive updates when cell service or power is unavailable")],
     "Keep spare batteries or a hand-crank model in your emergency kit."),
    ("Water Purification Methods", "5-8", True,
     ["Learn basic ways to make water safer to drink in an emergency", "Understand when purified water is necessary"],
     ["Boil water for at least one minute to kill most germs", "Use water purification tablets if boiling is not possible",
      "Use a proper water filter rated for removing pathogens", "Never drink untreated water from unknown sources"],
     ["Practice reading the instructions on water purification tablets with an adult"],
     [("How long should water be boiled to make it safer to drink?", "At least one minute (longer at high altitude)")],
     "Water purification should be supervised by an adult, especially boiling water."),
    ("Food Storage for Emergencies", "5-8", False,
     ["Learn what foods store well for emergencies", "Understand basic food safety during outages"],
     ["Store non-perishable foods like canned goods, rice, and dried fruit", "Rotate emergency food supplies before they expire",
      "Keep a manual can opener with the emergency kit", "Throw away perishable food after a long power outage to avoid illness"],
     ["Check expiration dates on the family's emergency food supply"],
     [("Why should emergency food supplies be rotated?", "To make sure the food does not expire before it is needed")],
     "Check and rotate emergency food supplies at least once a year."),
    ("Tsunami Safety Basics", "5-8", True,
     ["Recognize natural warning signs of a tsunami", "Learn the correct response to a tsunami warning"],
     ["Move immediately to high ground after an earthquake near the coast", "Do not wait for an official alert if natural signs like receding water appear",
      "Stay away from the coast until officials say it is safe", "Know your community's tsunami evacuation routes"],
     ["Locate the nearest high ground point from your coastal home or hotel"],
     [("What natural sign can indicate an incoming tsunami?", "Water suddenly receding far from the shore")],
     "Follow official tsunami warnings and evacuation instructions immediately."),
    ("Volcanic Eruption Awareness", "5-8", False,
     ["Learn basic volcanic hazards like ash and lava flows", "Understand safety steps during an eruption warning"],
     ["Follow official evacuation orders near an active volcano", "Wear a mask or cover your mouth and nose to avoid ash inhalation",
      "Stay indoors with windows closed if ashfall is occurring", "Keep goggles or glasses on hand to protect eyes from ash"],
     ["Research whether your region has any volcanic risk and local plans"],
     [("What should you cover during heavy volcanic ashfall?", "Your mouth and nose with a mask or cloth")],
     "Follow guidance from local geological and emergency authorities near active volcanoes."),
    ("Post-Disaster Safety: Checking for Hazards", "5-8", True,
     ["Learn what hazards can remain after a disaster", "Understand how to stay safe when returning home"],
     ["Check for gas leaks, damaged wires, and structural damage before entering", "Avoid floodwater, which can be contaminated or electrically charged",
      "Wear sturdy shoes to avoid debris injuries", "Take photos of damage for insurance before cleaning up"],
     ["Walk through a checklist of hazards to look for after a storm"],
     [("Why should you avoid floodwater after a disaster?", "It can be contaminated or hide electrical or structural hazards")],
     "Let trained adults or professionals inspect for gas, electrical, or structural hazards."),
    ("What to Expect When First Responders Arrive", "5-8", False,
     ["Learn how to interact safely with first responders", "Understand what information to share"],
     ["Stay calm and follow instructions from firefighters, police, or paramedics", "Answer questions clearly and honestly",
      "Point out anyone who is injured or trapped", "Move out of the way to let responders work safely"],
     ["Practice describing an emergency situation clearly and calmly"],
     [("What should you do when first responders arrive?", "Stay calm, follow their instructions, and answer questions clearly")],
     "Cooperating clearly with first responders helps them help you faster."),
    ("Community Emergency Resources: Shelters and Hotlines", "5-8", False,
     ["Learn what community resources exist during emergencies", "Know how to find shelters and helplines"],
     ["Know the location of the nearest emergency shelter", "Save local emergency hotline numbers in a phone or on paper",
      "Understand that shelters provide food, water, and safety information", "Ask local officials or a radio broadcast for shelter locations if unsure"],
     ["Look up your community's nearest designated emergency shelter"],
     [("What kind of help can an emergency shelter provide?", "Food, water, safety information, and a safe place to stay")],
     "Confirm current shelter locations with local emergency management, as they can change."),
    ("School Lockdown and Emergency Drills", "5-8", True,
     ["Understand the purpose of school lockdown drills", "Learn how to follow instructions during a drill"],
     ["Follow teacher instructions quickly and quietly", "Move away from doors and windows as directed",
      "Stay silent and still until told the drill or event is over", "Know your classroom's specific safety procedure"],
     ["Review your school's lockdown procedure with a teacher or parent"],
     [("What should you do during a school lockdown drill?", "Follow the teacher's instructions quickly and stay quiet and still")],
     "School drills are supervised by trained staff for student safety."),
    ("Severe Weather Alerts and Warnings", "5-8", False,
     ["Learn the difference between a watch and a warning", "Know how to receive severe weather alerts"],
     ["A watch means conditions are possible; a warning means it is happening or imminent", "Turn on a weather radio, app, or local news for updates",
      "Follow instructions given with each type of alert", "Keep a phone charged to receive emergency alerts"],
     ["Set up severe weather alerts on a family phone or device"],
     [("What is the difference between a weather watch and a warning?", "A watch means conditions are possible; a warning means it is happening or imminent")],
     "Enable official emergency alert notifications on household devices."),
    ("Safe Use of Flashlights and Emergency Lighting", "5-8", True,
     ["Learn safe habits with flashlights and emergency lights", "Understand battery and light safety"],
     ["Keep a flashlight within reach in every bedroom", "Never use candles as a substitute due to fire risk",
      "Check and replace batteries regularly", "Use glow sticks as a safer alternative for young children if needed"],
     ["Test all household flashlights and replace weak batteries"],
     [("Why are candles not recommended during a power outage?", "They pose a fire risk, especially unsupervised")],
     "Adults should supervise young children when using any emergency lighting."),
    ("Building a Family Emergency Plan Document", "9-12", False,
     ["Learn how to compile a full written family emergency plan", "Understand what information the plan should include"],
     ["List emergency contacts, meeting points, and evacuation routes", "Include medical information and any special needs of family members",
      "Store copies at home, at work or school, and with an out-of-area contact", "Review and update the plan at least once a year"],
     ["Draft a one-page family emergency plan with a parent"],
     [("How often should a family emergency plan be reviewed?", "At least once a year, or after any major life change")],
     "Share copies of the completed plan with all family members and caregivers."),
    ("Chemical Spill and Hazmat Awareness", "9-12", True,
     ["Recognize hazardous material warning signs", "Learn safe response steps to a chemical spill"],
     ["Move upwind and away from the spill area immediately", "Do not touch or attempt to clean up unknown substances",
      "Report the spill to emergency services with location details", "Follow official instructions on shelter-in-place or evacuation"],
     ["Learn to recognize common hazmat placard symbols"],
     [("What should you do if you encounter an unknown chemical spill?", "Move away immediately and report it to emergency services")],
     "Never attempt to handle or clean up hazardous materials yourself; leave it to trained responders."),
    ("Pandemic and Illness Outbreak Preparedness", "9-12", False,
     ["Learn basic steps to prepare for a disease outbreak", "Understand hygiene practices that reduce spread"],
     ["Keep a basic supply of masks, soap, and hand sanitizer", "Follow official public health guidance on precautions",
      "Stock a few weeks of essential supplies during outbreak warnings", "Stay informed through official health authority updates, not rumors"],
     ["Check your household's supply of basic hygiene and health items"],
     [("Where should you get outbreak guidance from?", "Official public health authorities, not rumors or social media")],
     "Follow guidance from recognized public health organizations such as the WHO or your national health agency."),
    ("Financial Emergency Preparedness: Documents and Cash", "9-12", False,
     ["Learn what documents and funds to prepare for emergencies", "Understand why cash and copies matter when systems are down"],
     ["Keep copies of ID, insurance, and medical documents in a waterproof folder", "Store a small amount of emergency cash, since card systems may fail",
      "Keep digital backups of key documents in secure cloud storage", "Update the emergency document folder yearly"],
     ["Assemble a family emergency document folder with a parent"],
     [("Why is emergency cash useful during a disaster?", "Card payment systems and ATMs may not work during power or network outages")],
     "Keep emergency documents and cash somewhere quickly accessible during an evacuation."),
    ("Generator Safety Basics", "9-12", True,
     ["Learn the dangers of improper generator use", "Understand safe generator placement and operation"],
     ["Never run a generator indoors, in a garage, or near windows", "Keep the generator at least 20 feet from the home, exhaust pointed away",
      "Let the generator cool before refueling", "Install carbon monoxide detectors near sleeping areas as a backup precaution"],
     ["Review the household generator's manual and safe placement spot with an adult"],
     [("Why should a generator never run indoors?", "It produces carbon monoxide, which can be deadly in enclosed spaces")],
     "Generators must be operated outdoors by an adult following the manufacturer's instructions."),
    ("Carbon Monoxide Awareness and Detection", "9-12", True,
     ["Learn the dangers of carbon monoxide", "Understand how to detect and respond to it"],
     ["Install carbon monoxide detectors near sleeping areas", "Recognize symptoms like headache, dizziness, and nausea",
      "Get to fresh air immediately if a detector sounds", "Never use grills, generators, or camp stoves indoors"],
     ["Test the household carbon monoxide detector with an adult"],
     [("What should you do if a carbon monoxide detector sounds?", "Get to fresh air immediately and call emergency services")],
     "Carbon monoxide is odorless and colorless; detectors are essential and should be tested regularly."),
    ("Landslide and Mudslide Awareness", "9-12", True,
     ["Recognize warning signs of a landslide or mudslide", "Learn safe evacuation behavior in risk areas"],
     ["Watch for cracking ground, tilting trees, or unusual sounds", "Move away and uphill from the path of a slide immediately",
      "Avoid river valleys and canyons during heavy rain in risk areas", "Follow official evacuation orders in landslide-prone regions"],
     ["Research whether your area has any landslide risk zones"],
     [("What is a warning sign of an incoming landslide?", "Cracking ground, tilting trees, or unusual rumbling sounds")],
     "Follow local geological survey and emergency management guidance in landslide-prone areas."),
    ("Extreme Drought and Water Shortage Preparedness", "9-12", False,
     ["Learn how to prepare for extended water shortages", "Understand basic water conservation steps"],
     ["Store a supply of clean water for drinking and basic hygiene", "Follow local water restriction guidelines during drought",
      "Reduce non-essential water use, like lawn watering, during shortages", "Know where community water distribution points are, if activated"],
     ["Calculate how much stored water your household would need for two weeks"],
     [("How much water is generally recommended per person per day for storage?", "About one gallon (roughly four liters) per person per day")],
     "Follow local authority guidance on water restrictions and storage limits."),
    ("Preparing an Emergency Car Kit", "9-12", True,
     ["Learn what items belong in a vehicle emergency kit", "Understand when and how to use them"],
     ["Include water, blankets, a flashlight, and a first aid kit", "Add jumper cables, a tire gauge, and basic tools",
      "Keep a phone charger and paper map in the car", "Check and refresh the kit every season"],
     ["Assemble or check a car emergency kit with a parent"],
     [("Why should a car emergency kit be checked seasonally?", "Needs change with weather, such as adding blankets in winter")],
     "An adult should assemble and maintain the vehicle emergency kit."),
    ("Safety During Extended Evacuation Shelter Stays", "9-12", False,
     ["Learn what to expect at an emergency shelter", "Understand basic etiquette and safety in shared shelter spaces"],
     ["Bring identification and essential medications to the shelter", "Follow shelter staff instructions and posted rules",
      "Keep track of family members and a shared meeting point inside the shelter", "Report any unsafe conditions to shelter staff"],
     ["List the key items to bring if staying at an emergency shelter"],
     [("What should you bring to an emergency shelter?", "Identification, essential medications, and basic personal supplies")],
     "Follow the specific guidance of shelter staff and local emergency management."),
    ("Basic Wilderness Emergency Signaling for Hikers", "9-12", True,
     ["Learn simple signals to attract rescuer attention outdoors", "Understand the universal distress signal pattern"],
     ["Use three of anything, three whistle blasts, three fires, or three flashes, as a distress signal", "Use a mirror or bright object to signal aircraft on sunny days",
      "Stay in an open area to be visible to search teams", "Stay put once lost rather than wandering further"],
     ["Practice the three-signal distress pattern with a whistle under adult supervision"],
     [("What is the universal distress signal pattern in the wilderness?", "A group of three, such as three whistle blasts or three fires")],
     "Wilderness signaling should be practiced with an experienced adult or guide."),
    ("Home Utility Shutoff Basics: Gas, Water, Electric", "9-12", True,
     ["Learn the location of home utility shutoffs", "Understand when it is safe to shut off utilities"],
     ["Know the location of the main gas, water, and electric shutoffs", "Shut off gas only if you smell gas or are instructed to after an earthquake",
      "Turn off the main water valve if a major pipe bursts", "Never turn gas back on yourself; call the utility company"],
     ["Locate all three main utility shutoffs at home with an adult"],
     [("Who should turn the gas supply back on after it has been shut off?", "The gas utility company or a trained professional, never yourself")],
     "Utility shutoff valves should be identified and used only under adult guidance."),
    ("Preparing for Extended School or Workplace Lockdowns", "9-12", False,
     ["Learn how to prepare for a longer lockdown situation", "Understand personal readiness steps"],
     ["Keep a small personal kit with water, snacks, and any needed medication", "Know your school or workplace's specific lockdown procedures",
      "Stay quiet, follow staff instructions, and avoid using phones loudly", "Know how communication with family will happen during a lockdown"],
     ["Review your school or workplace's lockdown policy"],
     [("What should a personal lockdown kit include?", "Water, a snack, and any necessary medication")],
     "Follow your institution's official lockdown procedures and staff instructions."),
    ("Understanding Emergency Alert Systems", "9-12", False,
     ["Learn how national and local emergency alert systems work", "Understand how to receive and respond to alerts"],
     ["Enable wireless emergency alerts on mobile devices", "Understand the different alert levels used in your country",
      "Follow the specific instructions given in each alert", "Do not ignore repeated or test alerts, as some indicate real events"],
     ["Check that emergency alerts are enabled on household phones"],
     [("What should you do when you receive an emergency alert?", "Read it carefully and follow its specific instructions")],
     "Alert systems vary by country; learn the specific system used in your region."),
    ("Preparing a Go-Bag for Rapid Evacuation", "9-12", True,
     ["Learn what a go-bag is and why it matters", "Understand what to pack for quick evacuation"],
     ["Pack essential documents, medications, and a change of clothes", "Include water, snacks, a flashlight, and a phone charger",
      "Keep the bag in an easily accessible location", "Check and refresh contents every six months"],
     ["Assemble a personal go-bag and review its contents with a parent"],
     [("How often should a go-bag be checked and refreshed?", "Roughly every six months")],
     "Keep the go-bag light enough to carry quickly and store it near an exit."),
    ("Nuclear or Radiological Incident Awareness", "Adult", False,
     ["Learn basic protective actions for a radiological incident", "Understand the concept of shelter, distance, and time"],
     ["Get inside a sturdy building immediately if instructed", "Stay away from windows and seal gaps if advised",
      "Remove and bag outer clothing if contamination is suspected", "Follow official instructions closely; do not rely on assumptions"],
     ["Review official government guidance on radiological emergency response"],
     [("What are the three basic protective concepts in a radiological incident?", "Shelter, distance from the source, and limiting exposure time")],
     "This is informational only; follow official government and emergency management guidance in an actual incident."),
    ("Severe Air Quality and Smoke Preparedness", "Adult", False,
     ["Learn how to protect health during poor air quality events", "Understand when to limit outdoor activity"],
     ["Check local air quality index readings regularly during smoke events", "Keep windows closed and use air filtration if available",
      "Wear a properly rated mask outdoors when air quality is very poor", "Limit strenuous outdoor activity during unhealthy air quality days"],
     ["Check your local air quality index reading and its meaning"],
     [("What should you check before heavy outdoor activity during wildfire season?", "The local air quality index")],
     "Follow local health authority guidance during poor air quality events, especially for at-risk individuals."),
    ("Coordinating Neighborhood Emergency Response", "Adult", False,
     ["Learn the value of neighborhood-level emergency coordination", "Understand basic community preparedness roles"],
     ["Get to know neighbors and any special needs they may have", "Identify neighbors with useful skills, such as first aid training",
      "Establish a simple neighborhood communication method for emergencies", "Participate in or organize a community emergency preparedness meeting"],
     ["Organize or attend a neighborhood emergency preparedness meeting"],
     [("Why is neighborhood coordination valuable in emergencies?", "Neighbors can often provide the fastest help before official responders arrive")],
     "Coordinate with local emergency management offices for community preparedness resources."),
    ("Insurance and Property Documentation for Disasters", "Adult", False,
     ["Learn how to document property for insurance purposes", "Understand what records help after a disaster"],
     ["Photograph or video household belongings and property regularly", "Keep insurance policy numbers and contacts easily accessible",
      "Store documentation copies in cloud storage and offsite", "Update documentation after major purchases or renovations"],
     ["Do a walkthrough video of your home for insurance records"],
     [("Why should property be documented before a disaster occurs?", "It helps support insurance claims for lost or damaged belongings")],
     "Consult your insurance provider for specific documentation requirements."),
    ("Emergency Preparedness for Elderly or Disabled Family Members", "Adult", False,
     ["Learn how to adapt emergency plans for special needs", "Understand additional supplies and considerations needed"],
     ["Include necessary medical equipment, medications, and mobility aids in planning", "Identify accessible evacuation routes and shelters in advance",
      "Register with local registries for people needing evacuation assistance, if available", "Ensure caregivers and neighbors know the specific needs involved"],
     ["Review the emergency plan specifically for any family members with special needs"],
     [("Why should evacuation routes be reviewed for accessibility?", "Standard routes or shelters may not accommodate mobility or medical needs")],
     "Contact local emergency management for registries or resources supporting people with disabilities."),
    ("Workplace Emergency Action Plans", "Adult", False,
     ["Learn the components of a workplace emergency action plan", "Understand employee responsibilities during workplace emergencies"],
     ["Know your workplace's evacuation routes and assembly points", "Understand designated roles, such as floor wardens, if assigned",
      "Participate in scheduled workplace emergency drills", "Report unclear or missing safety information to management"],
     ["Locate your workplace's posted emergency action plan and assembly point"],
     [("What is one component of a workplace emergency action plan?", "Designated evacuation routes and an outdoor assembly point")],
     "Workplace emergency plans should follow local occupational safety regulations."),
    ("Community Disaster Volunteer Basics", "Adult", False,
     ["Learn how community members can support disaster response", "Understand basic volunteer safety and training options"],
     ["Consider joining a local community emergency response team program", "Get trained in basic first aid and CPR before volunteering",
      "Follow the direction of official emergency management during a response", "Avoid self-deploying to disaster areas without coordination"],
     ["Look up local volunteer emergency response training programs"],
     [("Why should volunteers avoid self-deploying to a disaster area?", "Uncoordinated volunteers can strain resources and create additional risks")],
     "Register with recognized volunteer organizations for proper training and coordination."),
    ("Long-Term Food and Water Storage Planning", "Adult", False,
     ["Learn how to plan food and water storage for extended emergencies", "Understand rotation and storage best practices"],
     ["Store at least two weeks of food and water per household member", "Choose foods with long shelf lives and rotate stock regularly",
      "Store water in food-grade containers away from sunlight", "Label supplies with purchase or expiration dates"],
     ["Calculate your household's two-week food and water storage needs"],
     [("How much food and water should a household aim to store for emergencies?", "At least a two-week supply per person")],
     "Adjust storage recommendations based on local emergency management guidance and household needs."),
    ("Preparing for Infrastructure Failure (Grid-Down Scenarios)", "Adult", False,
     ["Learn how to prepare for extended loss of power and utilities", "Understand key backup systems and skills needed"],
     ["Maintain backup power options like batteries, solar chargers, or a generator", "Store manual tools that do not require electricity",
      "Keep a supply of cash, as electronic payment systems may be unavailable", "Build practical skills like manual water purification and basic repairs"],
     ["Test the household's backup power sources and manual tools"],
     [("Why is cash useful during an extended grid-down scenario?", "Electronic payment systems may not function without power or network access")],
     "Grid-down preparedness should complement, not replace, official emergency guidance."),
    ("After-Action Review: Learning From Emergency Events", "Adult", False,
     ["Learn how to review and improve after an emergency event", "Understand the value of updating plans based on experience"],
     ["Discuss what worked well and what did not after any emergency", "Update the family or workplace emergency plan based on lessons learned",
      "Replenish and adjust emergency kits based on actual needs experienced", "Share lessons learned with neighbors or community groups"],
     ["Hold a short family debrief after any emergency drill or real event"],
     [("Why is an after-action review useful following an emergency?", "It helps identify what worked and improve future preparedness plans")],
     "Regularly updating plans based on real experience improves future emergency readiness."),
]



def build_skill(category_id: str, item: tuple) -> dict:
    (name, grade_range, adult_supervision_required, learning_objectives,
     key_steps, practice_activities, quiz, important_note) = item

    return {
        "name": name,
        "grade_range": grade_range,
        "category": category_id,
        "adult_supervision_required": adult_supervision_required,
        "learning_objectives": learning_objectives,
        "key_steps": key_steps,
        "practice_activities": practice_activities,
        "quiz": [{"q": q, "a": a} for q, a in quiz],
        "important_note": important_note,
        "progress_tracking": {"completion_required": True, "min_quiz_score": 70},
        "links": {
            "video_link": yt_search(f"{name} survival safety tutorial"),
            "video_search_general": yt_search(f"{name} {category_id.replace('_', ' ')}"),
            "text_link": wikihow_search(name),
            "resource_link": wikipedia_search(name),
        },
    }


def main() -> None:
    with open(SURVIVAL_PATH, encoding="utf-8") as f:
        data = json.load(f)

    if NEW_CATEGORY_ID not in data["categories"]:
        data["categories"][NEW_CATEGORY_ID] = []

    report = []
    for category_id, topics in TOPICS.items():
        if category_id not in data["categories"]:
            data["categories"][category_id] = []
        existing = data["categories"][category_id]
        existing_names = {s["name"] for s in existing}

        new_topics = [t for t in topics if t[0] not in existing_names]
        new_skills = [build_skill(category_id, item) for item in new_topics]
        data["categories"][category_id] = existing + new_skills
        report.append(f"{category_id}: {len(existing)} existing + {len(new_skills)} new = {len(data['categories'][category_id])} total")

    with open(SURVIVAL_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    for line in report:
        print(line)


if __name__ == "__main__":
    main()
