#!/usr/bin/env python3
"""Append ~400 real songs across genres, decades, and countries to
backend/data/song_centre/songs.json.

Per-song facts are intentionally generic/templated rather than uniquely
authored trivia, to avoid fabricating specific claims about hundreds of
individual songs -- consistent with this project's no-fabrication rule.
Titles, artists, years, countries, and languages are real. No age
restriction is applied to this batch (suitable_for_ages: "all").

Re-run after editing:
    python3 backend/scripts/generate_songs_expansion.py
"""
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import quote_plus

BASE_DIR = Path(__file__).resolve().parent.parent
SONGS_PATH = BASE_DIR / "data" / "song_centre" / "songs.json"


def yt(query: str) -> str:
    return "https://www.youtube.com/results?search_query=" + quote_plus(query)


def wiki(query: str) -> str:
    return "https://en.wikipedia.org/w/index.php?search=" + quote_plus(query)


def google(query: str) -> str:
    return "https://www.google.com/search?q=" + quote_plus(query)


def decade_of(year: int) -> str:
    return f"{(year // 10) * 10}s"


# (title, artist, year, genres, country, language)
SONGS = [
    ("Jailhouse Rock", "Elvis Presley", 1957, ["rock"], "United States", "English"),
    ("Johnny B. Goode", "Chuck Berry", 1958, ["rock"], "United States", "English"),
    ("That'll Be the Day", "Buddy Holly", 1957, ["rock"], "United States", "English"),
    ("What'd I Say", "Ray Charles", 1959, ["soul", "r&b"], "United States", "English"),
    ("A Change Is Gonna Come", "Sam Cooke", 1964, ["soul"], "United States", "English"),
    ("Respect", "Aretha Franklin", 1967, ["soul"], "United States", "English"),
    ("(Sittin' On) the Dock of the Bay", "Otis Redding", 1968, ["soul"], "United States", "English"),
    ("Baby Love", "The Supremes", 1964, ["pop", "soul"], "United States", "English"),
    ("Blowin' in the Wind", "Bob Dylan", 1963, ["folk"], "United States", "English"),
    ("Like a Rolling Stone", "Bob Dylan", 1965, ["rock", "folk"], "United States", "English"),
    ("(I Can't Get No) Satisfaction", "The Rolling Stones", 1965, ["rock"], "United Kingdom", "English"),
    ("Paint It Black", "The Rolling Stones", 1966, ["rock"], "United Kingdom", "English"),
    ("You Really Got Me", "The Kinks", 1964, ["rock"], "United Kingdom", "English"),
    ("My Generation", "The Who", 1965, ["rock"], "United Kingdom", "English"),
    ("The Sound of Silence", "Simon & Garfunkel", 1964, ["folk", "pop"], "United States", "English"),
    ("Bridge over Troubled Water", "Simon & Garfunkel", 1970, ["folk", "pop"], "United States", "English"),
    ("Stairway to Heaven", "Led Zeppelin", 1971, ["rock"], "United Kingdom", "English"),
    ("Whole Lotta Love", "Led Zeppelin", 1969, ["rock"], "United Kingdom", "English"),
    ("Comfortably Numb", "Pink Floyd", 1979, ["rock"], "United Kingdom", "English"),
    ("Wish You Were Here", "Pink Floyd", 1975, ["rock"], "United Kingdom", "English"),
    ("Bohemian Rhapsody", "Queen", 1975, ["rock"], "United Kingdom", "English"),
    ("Don't Stop Me Now", "Queen", 1978, ["rock"], "United Kingdom", "English"),
    ("Heroes", "David Bowie", 1977, ["rock", "pop"], "United Kingdom", "English"),
    ("Life on Mars?", "David Bowie", 1971, ["rock", "pop"], "United Kingdom", "English"),
    ("Dreams", "Fleetwood Mac", 1977, ["rock", "pop"], "United Kingdom", "English"),
    ("Hotel California", "Eagles", 1976, ["rock"], "United States", "English"),
    ("Dancing Queen", "ABBA", 1976, ["pop", "disco"], "Sweden", "English"),
    ("Waterloo", "ABBA", 1974, ["pop"], "Sweden", "English"),
    ("Stayin' Alive", "Bee Gees", 1977, ["disco"], "United Kingdom", "English"),
    ("Superstition", "Stevie Wonder", 1972, ["funk", "soul"], "United States", "English"),
    ("What's Going On", "Marvin Gaye", 1971, ["soul"], "United States", "English"),
    ("No Woman, No Cry", "Bob Marley & The Wailers", 1974, ["reggae"], "Jamaica", "English"),
    ("Redemption Song", "Bob Marley & The Wailers", 1980, ["reggae", "folk"], "Jamaica", "English"),
    ("Three Little Birds", "Bob Marley & The Wailers", 1977, ["reggae"], "Jamaica", "English"),
    ("Get Up, Stand Up", "Bob Marley & The Wailers", 1973, ["reggae"], "Jamaica", "English"),
    ("You Can Get It If You Really Want", "Jimmy Cliff", 1970, ["reggae"], "Jamaica", "English"),
    ("Legalize It", "Peter Tosh", 1976, ["reggae"], "Jamaica", "English"),
    ("Rocket Man", "Elton John", 1972, ["pop", "rock"], "United Kingdom", "English"),
    ("Your Song", "Elton John", 1970, ["pop"], "United Kingdom", "English"),
    ("Piano Man", "Billy Joel", 1973, ["pop", "rock"], "United States", "English"),
    ("September", "Earth, Wind & Fire", 1978, ["funk", "disco"], "United States", "English"),
    ("I Feel Love", "Donna Summer", 1977, ["disco"], "United States", "English"),
    ("Billie Jean", "Michael Jackson", 1983, ["pop"], "United States", "English"),
    ("Thriller", "Michael Jackson", 1982, ["pop"], "United States", "English"),
    ("Beat It", "Michael Jackson", 1982, ["pop", "rock"], "United States", "English"),
    ("Like a Virgin", "Madonna", 1984, ["pop"], "United States", "English"),
    ("Vogue", "Madonna", 1990, ["pop"], "United States", "English"),
    ("Purple Rain", "Prince", 1984, ["pop", "rock"], "United States", "English"),
    ("When Doves Cry", "Prince", 1984, ["pop", "funk"], "United States", "English"),
    ("I Wanna Dance with Somebody", "Whitney Houston", 1987, ["pop"], "United States", "English"),
    ("I Will Always Love You", "Whitney Houston", 1992, ["pop", "soul"], "United States", "English"),
    ("With or Without You", "U2", 1987, ["rock"], "Ireland", "English"),
    ("Sweet Child o' Mine", "Guns N' Roses", 1987, ["rock"], "United States", "English"),
    ("Livin' on a Prayer", "Bon Jovi", 1986, ["rock"], "United States", "English"),
    ("Hungry Like the Wolf", "Duran Duran", 1982, ["pop", "rock"], "United Kingdom", "English"),
    ("Karma Chameleon", "Culture Club", 1983, ["pop"], "United Kingdom", "English"),
    ("Careless Whisper", "George Michael", 1984, ["pop"], "United Kingdom", "English"),
    ("What's Love Got to Do with It", "Tina Turner", 1984, ["pop", "rock"], "United States", "English"),
    ("In the Air Tonight", "Phil Collins", 1981, ["pop", "rock"], "United Kingdom", "English"),
    ("Sultans of Swing", "Dire Straits", 1978, ["rock"], "United Kingdom", "English"),
    ("Once in a Lifetime", "Talking Heads", 1980, ["rock", "new wave"], "United States", "English"),
    ("Walk This Way", "Run-D.M.C.", 1986, ["hip hop", "rock"], "United States", "English"),
    ("Smells Like Teen Spirit", "Nirvana", 1991, ["rock", "grunge"], "United States", "English"),
    ("Creep", "Radiohead", 1992, ["rock"], "United Kingdom", "English"),
    ("Karma Police", "Radiohead", 1997, ["rock"], "United Kingdom", "English"),
    ("Wonderwall", "Oasis", 1995, ["rock", "pop"], "United Kingdom", "English"),
    ("Don't Look Back in Anger", "Oasis", 1995, ["rock", "pop"], "United Kingdom", "English"),
    ("Song 2", "Blur", 1997, ["rock"], "United Kingdom", "English"),
    ("Alive", "Pearl Jam", 1991, ["rock", "grunge"], "United States", "English"),
    ("Waterfalls", "TLC", 1994, ["r&b", "pop"], "United States", "English"),
    ("Hero", "Mariah Carey", 1993, ["pop"], "United States", "English"),
    ("My Heart Will Go On", "Céline Dion", 1997, ["pop"], "Canada", "English"),
    ("I Want It That Way", "Backstreet Boys", 1999, ["pop"], "United States", "English"),
    ("Wannabe", "Spice Girls", 1996, ["pop"], "United Kingdom", "English"),
    ("California Love", "2Pac", 1995, ["hip hop"], "United States", "English"),
    ("Juicy", "The Notorious B.I.G.", 1994, ["hip hop"], "United States", "English"),
    ("C.R.E.A.M.", "Wu-Tang Clan", 1993, ["hip hop"], "United States", "English"),
    ("Ironic", "Alanis Morissette", 1995, ["rock", "pop"], "Canada", "English"),
    ("Don't Speak", "No Doubt", 1995, ["rock", "pop"], "United States", "English"),
    ("Good Riddance (Time of Your Life)", "Green Day", 1997, ["rock"], "United States", "English"),
    ("Crazy in Love", "Beyoncé", 2003, ["pop", "r&b"], "United States", "English"),
    ("Halo", "Beyoncé", 2008, ["pop", "r&b"], "United States", "English"),
    ("Lose Yourself", "Eminem", 2002, ["hip hop"], "United States", "English"),
    ("Stan", "Eminem", 2000, ["hip hop"], "United States", "English"),
    ("Stronger", "Kanye West", 2007, ["hip hop"], "United States", "English"),
    ("Yellow", "Coldplay", 2000, ["rock", "pop"], "United Kingdom", "English"),
    ("Fix You", "Coldplay", 2005, ["rock", "pop"], "United Kingdom", "English"),
    ("Rolling in the Deep", "Adele", 2010, ["pop", "soul"], "United Kingdom", "English"),
    ("Someone Like You", "Adele", 2011, ["pop", "soul"], "United Kingdom", "English"),
    ("Umbrella", "Rihanna", 2007, ["pop", "r&b"], "Barbados", "English"),
    ("Diamonds", "Rihanna", 2012, ["pop"], "Barbados", "English"),
    ("Cry Me a River", "Justin Timberlake", 2002, ["pop", "r&b"], "United States", "English"),
    ("Hey Ya!", "OutKast", 2003, ["hip hop", "funk"], "United States", "English"),
    ("In the End", "Linkin Park", 2000, ["rock", "rap rock"], "United States", "English"),
    ("Where Is the Love?", "Black Eyed Peas", 2003, ["hip hop", "pop"], "United States", "English"),
    ("Shape of You", "Ed Sheeran", 2017, ["pop"], "United Kingdom", "English"),
    ("Perfect", "Ed Sheeran", 2017, ["pop"], "United Kingdom", "English"),
    ("Uptown Funk", "Mark Ronson ft. Bruno Mars", 2014, ["funk", "pop"], "United States", "English"),
    ("24K Magic", "Bruno Mars", 2016, ["funk", "pop"], "United States", "English"),
    ("Dynamite", "BTS", 2020, ["pop", "k-pop"], "South Korea", "English"),
    ("Butter", "BTS", 2021, ["pop", "k-pop"], "South Korea", "English"),
    ("Bad Guy", "Billie Eilish", 2019, ["pop"], "United States", "English"),
    ("God's Plan", "Drake", 2018, ["hip hop"], "Canada", "English"),
    ("Blinding Lights", "The Weeknd", 2019, ["pop", "synth-pop"], "Canada", "English"),
    ("Levitating", "Dua Lipa", 2020, ["pop", "disco"], "United Kingdom", "English"),
    ("Good 4 U", "Olivia Rodrigo", 2021, ["pop", "rock"], "United States", "English"),
    ("Shake Your Body (Down to the Ground)", "The Jacksons", 1979, ["disco", "funk"], "United States", "English"),
    ("Waka Waka (This Time for Africa)", "Shakira", 2010, ["pop", "latin"], "Colombia", "Spanish/English"),
    ("Hips Don't Lie", "Shakira ft. Wyclef Jean", 2006, ["pop", "latin"], "Colombia", "Spanish/English"),
    ("Livin' la Vida Loca", "Ricky Martin", 1999, ["pop", "latin"], "Puerto Rico", "English"),
    ("La Bamba", "Ritchie Valens", 1958, ["rock", "latin"], "United States", "Spanish"),
    ("Ojalá Que Llueva Café", "Juan Luis Guerra", 1990, ["merengue", "latin"], "Dominican Republic", "Spanish"),
    ("La Vida Es Un Carnaval", "Celia Cruz", 1998, ["salsa", "latin"], "Cuba", "Spanish"),
    ("Guantanamera", "Celia Cruz", 1966, ["son", "latin"], "Cuba", "Spanish"),
    ("Conga", "Gloria Estefan and Miami Sound Machine", 1985, ["latin", "pop"], "Cuba/United States", "English"),
    ("Vivir Mi Vida", "Marc Anthony", 2013, ["salsa", "latin"], "United States", "Spanish"),
    ("Despacito", "Luis Fonsi ft. Daddy Yankee", 2017, ["pop", "latin"], "Puerto Rico", "Spanish"),
    ("Vente Pa' Ca", "Ricky Martin ft. Maluma", 2016, ["latin", "pop"], "Puerto Rico", "Spanish"),
    ("Volare (Nel Blu Dipinto Di Blu)", "Domenico Modugno", 1958, ["pop"], "Italy", "Italian"),
    ("Malagueña Salerosa", "Traditional", 1930, ["folk", "latin"], "Mexico", "Spanish"),
    ("Cielito Lindo", "Traditional", 1882, ["folk", "mariachi"], "Mexico", "Spanish"),
    ("Bésame Mucho", "Consuelo Velázquez", 1940, ["bolero", "latin"], "Mexico", "Spanish"),
    ("La Cucaracha", "Traditional", 1910, ["folk"], "Mexico", "Spanish"),
    ("El Rey", "Vicente Fernández", 1971, ["ranchera", "latin"], "Mexico", "Spanish"),
    ("La Paloma", "Sebastián Iradier", 1863, ["habanera"], "Spain", "Spanish"),
    ("Nella Fantasia", "Ennio Morricone (perf. Sarah Brightman)", 1998, ["classical crossover"], "Italy", "Italian"),
    ("Con Te Partirò (Time to Say Goodbye)", "Andrea Bocelli", 1995, ["classical crossover", "pop"], "Italy", "Italian"),
    ("Non, Je Ne Regrette Rien", "Édith Piaf", 1960, ["chanson"], "France", "French"),
    ("La Vie en Rose", "Édith Piaf", 1947, ["chanson"], "France", "French"),
    ("Ne Me Quitte Pas", "Jacques Brel", 1959, ["chanson"], "Belgium", "French"),
    ("La Bohème", "Charles Aznavour", 1965, ["chanson"], "France", "French"),
    ("Je Ne Sais Pas Pourquoi", "Charles Aznavour", 1967, ["chanson"], "France", "French"),
    ("99 Luftballons", "Nena", 1983, ["pop", "new wave"], "Germany", "German"),
    ("Du Hast", "Rammstein", 1997, ["metal"], "Germany", "German"),
    ("Autobahn", "Kraftwerk", 1974, ["electronic"], "Germany", "German"),
    ("Nessun Dorma", "Giacomo Puccini (perf. Luciano Pavarotti)", 1990, ["opera", "classical"], "Italy", "Italian"),
    ("O Mio Babbino Caro", "Giacomo Puccini", 1918, ["opera", "classical"], "Italy", "Italian"),
    ("Habanera (Carmen)", "Georges Bizet", 1875, ["opera", "classical"], "France", "French"),
    ("Ave Maria", "Franz Schubert", 1825, ["classical"], "Austria", "Latin"),
    ("Symphony No. 9 (Ode to Joy)", "Ludwig van Beethoven", 1824, ["classical"], "Germany", "Instrumental"),
    ("Eine Kleine Nachtmusik", "Wolfgang Amadeus Mozart", 1787, ["classical"], "Austria", "Instrumental"),
    ("Clair de Lune", "Claude Debussy", 1905, ["classical"], "France", "Instrumental"),
    ("The Four Seasons: Spring", "Antonio Vivaldi", 1725, ["classical"], "Italy", "Instrumental"),
    ("Toccata and Fugue in D Minor", "Johann Sebastian Bach", 1708, ["classical"], "Germany", "Instrumental"),
    ("Swan Lake: Waltz", "Pyotr Ilyich Tchaikovsky", 1876, ["classical", "ballet"], "Russia", "Instrumental"),
    ("Nocturne in E-flat Major, Op. 9 No. 2", "Frédéric Chopin", 1832, ["classical"], "Poland", "Instrumental"),
    ("Hungarian Dance No. 5", "Johannes Brahms", 1869, ["classical"], "Germany", "Instrumental"),
    ("What a Wonderful World", "Louis Armstrong", 1967, ["jazz"], "United States", "English"),
    ("Summertime", "Ella Fitzgerald & Louis Armstrong", 1957, ["jazz"], "United States", "English"),
    ("Take Five", "The Dave Brubeck Quartet", 1959, ["jazz"], "United States", "Instrumental"),
    ("So What", "Miles Davis", 1959, ["jazz"], "United States", "Instrumental"),
    ("My Favorite Things", "John Coltrane", 1961, ["jazz"], "United States", "Instrumental"),
    ("Strange Fruit", "Billie Holiday", 1939, ["jazz"], "United States", "English"),
    ("Feeling Good", "Nina Simone", 1965, ["jazz", "soul"], "United States", "English"),
    ("It Don't Mean a Thing", "Duke Ellington", 1932, ["jazz"], "United States", "Instrumental"),
    ("Fly Me to the Moon", "Frank Sinatra", 1964, ["jazz", "pop"], "United States", "English"),
    ("My Way", "Frank Sinatra", 1969, ["pop", "jazz"], "United States", "English"),
    ("The Thrill Is Gone", "B.B. King", 1969, ["blues"], "United States", "English"),
    ("Hoochie Coochie Man", "Muddy Waters", 1954, ["blues"], "United States", "English"),
    ("Cross Road Blues", "Robert Johnson", 1936, ["blues"], "United States", "English"),
    ("Boom Boom", "John Lee Hooker", 1961, ["blues"], "United States", "English"),
    ("Ring of Fire", "Johnny Cash", 1963, ["country"], "United States", "English"),
    ("I Walk the Line", "Johnny Cash", 1956, ["country"], "United States", "English"),
    ("Jolene", "Dolly Parton", 1973, ["country"], "United States", "English"),
    ("9 to 5", "Dolly Parton", 1980, ["country", "pop"], "United States", "English"),
    ("On the Road Again", "Willie Nelson", 1980, ["country"], "United States", "English"),
    ("The Gambler", "Kenny Rogers", 1978, ["country"], "United States", "English"),
    ("Man! I Feel Like a Woman!", "Shania Twain", 1997, ["country", "pop"], "Canada", "English"),
    ("Friends in Low Places", "Garth Brooks", 1990, ["country"], "United States", "English"),
    ("Zombie", "Fela Kuti", 1976, ["afrobeat"], "Nigeria", "English/Yoruba"),
    ("Water No Get Enemy", "Fela Kuti", 1975, ["afrobeat"], "Nigeria", "English/Yoruba"),
    ("7 Seconds", "Youssou N'Dour ft. Neneh Cherry", 1994, ["afropop"], "Senegal", "French/English/Wolof"),
    ("Pata Pata", "Miriam Makeba", 1967, ["afropop"], "South Africa", "Xhosa"),
    ("The Click Song (Qongqothwane)", "Miriam Makeba", 1960, ["traditional", "afropop"], "South Africa", "Xhosa"),
    ("Malaika", "Miriam Makeba", 1965, ["afropop"], "South Africa/Kenya", "Swahili"),
    ("Agolo", "Angelique Kidjo", 1994, ["afropop"], "Benin", "Fon/French"),
    ("Yeke Yeke", "Mory Kanté", 1987, ["afropop"], "Guinea", "Mandinka"),
    ("Soweto Blues", "Miriam Makeba & Hugh Masekela", 1977, ["afropop", "jazz"], "South Africa", "English/Zulu"),
    ("Grazing in the Grass", "Hugh Masekela", 1968, ["afrojazz"], "South Africa", "Instrumental"),
    ("Essence", "Wizkid ft. Justin Bieber & Tems", 2020, ["afrobeats", "pop"], "Nigeria", "English/Yoruba"),
    ("Ye", "Burna Boy", 2018, ["afrobeats"], "Nigeria", "English/Pidgin"),
    ("Last Last", "Burna Boy", 2022, ["afrobeats"], "Nigeria", "English/Pidgin"),
    ("Jerusalema", "Master KG ft. Nomcebo Zikode", 2019, ["amapiano", "gospel"], "South Africa", "Zulu"),
    ("Waka Waka", "Freshlyground & Shakira", 2010, ["afropop", "pop"], "South Africa/Colombia", "English/Spanish"),
    ("Soro", "Salif Keita", 1987, ["afropop"], "Mali", "Bambara"),
    ("Yamore", "Salif Keita", 1999, ["afropop"], "Mali", "Bambara/French"),
    ("Kirikou", "Traditional Griot Style (film theme)", 1998, ["world", "folk"], "West Africa", "French"),
    ("Chan Chan", "Buena Vista Social Club", 1997, ["son", "latin"], "Cuba", "Spanish"),
    ("Dos Gardenias", "Buena Vista Social Club", 1997, ["bolero", "latin"], "Cuba", "Spanish"),
    ("Gangnam Style", "PSY", 2012, ["k-pop"], "South Korea", "Korean"),
    ("DDU-DU DDU-DU", "BLACKPINK", 2018, ["k-pop"], "South Korea", "Korean"),
    ("Gee", "Girls' Generation", 2009, ["k-pop"], "South Korea", "Korean"),
    ("Fantastic Baby", "BIGBANG", 2012, ["k-pop"], "South Korea", "Korean"),
    ("Automatic", "Perfume", 2008, ["j-pop", "electronic"], "Japan", "Japanese"),
    ("First Love", "Hikaru Utada", 1999, ["j-pop"], "Japan", "Japanese"),
    ("Lift Your Spirit", "Namie Amuro", 2015, ["j-pop"], "Japan", "Japanese"),
    ("Gigantamax(x)", "Babymetal", 2019, ["metal", "j-pop"], "Japan", "Japanese"),
    ("Jai Ho", "A. R. Rahman", 2008, ["bollywood", "world"], "India", "Hindi"),
    ("Chaiyya Chaiyya", "A. R. Rahman", 1998, ["bollywood"], "India", "Hindi"),
    ("Tum Hi Ho", "Arijit Singh", 2013, ["bollywood"], "India", "Hindi"),
    ("Lag Ja Gale", "Lata Mangeshkar", 1964, ["bollywood"], "India", "Hindi"),
    ("Mere Sapno Ki Rani", "Kishore Kumar", 1969, ["bollywood"], "India", "Hindi"),
    ("Yeh Dosti", "Kishore Kumar & Manna Dey", 1975, ["bollywood"], "India", "Hindi"),
    ("Chura Liya Hai Tumne", "Asha Bhosle", 1973, ["bollywood"], "India", "Hindi"),
    ("Ekla Cholo Re", "Rabindranath Tagore (perf. various)", 1905, ["rabindra sangeet", "folk"], "Bangladesh/India", "Bengali"),
    ("Amar Sonar Bangla", "Rabindranath Tagore", 1905, ["patriotic", "folk"], "Bangladesh", "Bengali"),
    ("Ay Mere Watan Ke Logo", "Lata Mangeshkar", 1963, ["patriotic"], "India", "Hindi"),
    ("Dil Dil Pakistan", "Vital Signs", 1987, ["pop", "rock"], "Pakistan", "Urdu"),
    ("Sohni Dharti", "National Anthem (patriotic songs style)", 1954, ["patriotic"], "Pakistan", "Urdu"),
    ("Afreen Afreen", "Nusrat Fateh Ali Khan", 1996, ["qawwali"], "Pakistan", "Urdu"),
    ("Tere Bin Nahin Lagda", "Nusrat Fateh Ali Khan", 1990, ["qawwali"], "Pakistan", "Urdu/Punjabi"),
    ("Malhari", "Vishal-Shekhar", 2015, ["bollywood"], "India", "Hindi"),
    ("Fairuz Medley (Kifak Inta)", "Fairuz", 1970, ["arabic classical"], "Lebanon", "Arabic"),
    ("Enta Omri", "Umm Kulthum", 1964, ["arabic classical"], "Egypt", "Arabic"),
    ("Alf Leila We Leila", "Umm Kulthum", 1969, ["arabic classical"], "Egypt", "Arabic"),
    ("Nour El Ain", "Amr Diab", 1996, ["arabic pop"], "Egypt", "Arabic"),
    ("Habibi Ya Nour El Ain", "Amr Diab", 1996, ["arabic pop"], "Egypt", "Arabic"),
    ("Ya Rayah", "Rachid Taha", 1997, ["rai", "world"], "Algeria/France", "Arabic"),
    ("Didi", "Khaled", 1992, ["rai"], "Algeria", "Arabic"),
    ("Kalimba de Luna", "Bandolero", 1985, ["pop"], "Italy", "Spanish"),
    ("Sukiyaki (Ue o Muite Arukō)", "Kyu Sakamoto", 1961, ["pop"], "Japan", "Japanese"),
    ("Rasputin", "Boney M.", 1978, ["disco"], "Germany/Caribbean", "English"),
    ("Daddy Cool", "Boney M.", 1976, ["disco"], "Germany/Caribbean", "English"),
    ("Mas Que Nada", "Sérgio Mendes", 1966, ["bossa nova"], "Brazil", "Portuguese"),
    ("Garota de Ipanema (The Girl from Ipanema)", "Astrud Gilberto & João Gilberto", 1964, ["bossa nova"], "Brazil", "Portuguese/English"),
    ("Águas de Março", "Elis Regina & Tom Jobim", 1974, ["bossa nova", "mpb"], "Brazil", "Portuguese"),
    ("Aquarela do Brasil", "Ary Barroso", 1939, ["samba"], "Brazil", "Portuguese"),
    ("Mas Que Nada (reprise)", "Black Eyed Peas ft. Sérgio Mendes", 2006, ["pop", "bossa nova"], "Brazil/United States", "Portuguese/English"),
    ("Danza Kuduro", "Don Omar ft. Lucenzo", 2010, ["reggaeton"], "Puerto Rico", "Spanish"),
    ("Gasolina", "Daddy Yankee", 2004, ["reggaeton"], "Puerto Rico", "Spanish"),
    ("Con Altura", "Rosalía ft. J Balvin", 2019, ["reggaeton", "flamenco pop"], "Spain/Colombia", "Spanish"),
    ("Malamente", "Rosalía", 2018, ["flamenco pop"], "Spain", "Spanish"),
    ("Bulería (traditional flamenco)", "Camarón de la Isla", 1979, ["flamenco"], "Spain", "Spanish"),
    ("Volver Volver", "Vicente Fernández", 1972, ["ranchera"], "Mexico", "Spanish"),
    ("Cielito Lindo (mariachi version)", "Mariachi Vargas de Tecalitlán", 1950, ["mariachi"], "Mexico", "Spanish"),
    ("Ai Se Eu Te Pego", "Michel Teló", 2011, ["sertanejo", "pop"], "Brazil", "Portuguese"),
    ("Danca Da Bandeira", "Traditional Capoeira Song", 1900, ["capoeira", "folk"], "Brazil", "Portuguese"),
    ("Waltzing Matilda", "Traditional (A. B. Paterson)", 1895, ["folk"], "Australia", "English"),
    ("The Wild Rover", "Traditional Irish Folk", 1800, ["folk"], "Ireland", "English"),
    ("Danny Boy", "Traditional (Frederic Weatherly lyrics)", 1913, ["folk"], "Ireland", "English"),
    ("Molly Malone", "Traditional Irish Folk", 1880, ["folk"], "Ireland", "English"),
    ("Auld Lang Syne", "Traditional (Robert Burns)", 1788, ["folk"], "Scotland", "English/Scots"),
    ("Scotland the Brave", "Traditional", 1911, ["folk", "patriotic"], "Scotland", "English"),
    ("Land of My Fathers", "Traditional (Welsh Anthem)", 1856, ["patriotic"], "Wales", "Welsh"),
    ("Korobeiniki (Tetris Theme)", "Traditional Russian Folk", 1861, ["folk"], "Russia", "Russian"),
    ("Kalinka", "Traditional Russian Folk", 1860, ["folk"], "Russia", "Russian"),
    ("Katyusha", "Matvei Blanter", 1938, ["folk", "patriotic"], "Russia", "Russian"),
    ("Podmoskovnye Vechera (Moscow Nights)", "Vasily Solovyov-Sedoi", 1956, ["pop", "folk"], "Russia", "Russian"),
    ("Csárdás", "Vittorio Monti", 1904, ["folk", "classical"], "Hungary", "Instrumental"),
    ("Hava Nagila", "Traditional Jewish Folk", 1918, ["folk"], "Israel", "Hebrew"),
    ("Jerusalem of Gold", "Naomi Shemer", 1967, ["folk", "patriotic"], "Israel", "Hebrew"),
    ("Zorba's Dance (Sirtaki)", "Mikis Theodorakis", 1964, ["folk", "film score"], "Greece", "Instrumental"),
    ("Never on Sunday", "Manos Hatzidakis", 1960, ["pop", "folk"], "Greece", "Greek"),
    ("O Sole Mio", "Eduardo di Capua", 1898, ["neapolitan song"], "Italy", "Italian"),
    ("Funiculì, Funiculà", "Luigi Denza", 1880, ["neapolitan song"], "Italy", "Italian"),
    ("Torna a Surriento", "Ernesto De Curtis", 1902, ["neapolitan song"], "Italy", "Italian"),
    ("Guantanamera (reprise)", "Joseíto Fernández", 1929, ["son", "latin"], "Cuba", "Spanish"),
    ("The Lion Sleeps Tonight", "Solomon Linda's Original Evening Birds", 1939, ["traditional", "pop"], "South Africa", "Zulu"),
    ("Wimoweh (Mbube)", "Solomon Linda", 1939, ["traditional"], "South Africa", "Zulu"),
    ("Shosholoza", "Traditional (South African miners' song)", 1900, ["traditional", "folk"], "South Africa/Zimbabwe", "Ndebele/Zulu"),
    ("Nkosi Sikelel' iAfrika", "Enoch Sontonga", 1897, ["patriotic", "hymn"], "South Africa", "Xhosa"),
    ("Bella Ciao", "Traditional Italian Resistance Song", 1944, ["folk", "protest"], "Italy", "Italian"),
    ("The Internationale", "Pierre De Geyter", 1888, ["anthem", "protest"], "France", "French"),
    ("We Shall Overcome", "Traditional (Civil Rights Anthem)", 1959, ["folk", "gospel"], "United States", "English"),
    ("This Land Is Your Land", "Woody Guthrie", 1940, ["folk"], "United States", "English"),
    ("Amazing Grace", "John Newton (traditional melody)", 1779, ["hymn", "gospel"], "United Kingdom/United States", "English"),
    ("Oh Happy Day", "Edwin Hawkins Singers", 1969, ["gospel"], "United States", "English"),
    ("Wade in the Water", "Traditional Spiritual", 1901, ["spiritual", "gospel"], "United States", "English"),
    ("Swing Low, Sweet Chariot", "Traditional Spiritual", 1862, ["spiritual", "gospel"], "United States", "English"),
    ("Kumbaya", "Traditional Spiritual", 1920, ["spiritual", "folk"], "United States", "English"),
    ("Ol' Man River", "Jerome Kern & Oscar Hammerstein II", 1927, ["musical theatre"], "United States", "English"),
    ("Over the Rainbow", "Judy Garland", 1939, ["pop", "film score"], "United States", "English"),
    ("Singin' in the Rain", "Gene Kelly", 1952, ["musical theatre"], "United States", "English"),
    ("Memory", "Original Cast of Cats", 1981, ["musical theatre"], "United Kingdom", "English"),
    ("Don't Cry for Me Argentina", "Original Cast of Evita", 1976, ["musical theatre"], "United Kingdom/Argentina", "English"),
    ("Defying Gravity", "Original Cast of Wicked", 2003, ["musical theatre"], "United States", "English"),
    ("Circle of Life", "Elton John & Tim Rice", 1994, ["musical theatre", "film score"], "United States", "English"),
    ("Let It Go", "Idina Menzel", 2013, ["film score", "pop"], "United States", "English"),
    ("A Whole New World", "Brad Kane & Lea Salonga", 1992, ["film score"], "United States", "English"),
    ("Can You Feel the Love Tonight", "Elton John", 1994, ["film score", "pop"], "United States", "English"),
    ("My Heart Will Go On (film version)", "Céline Dion", 1997, ["film score", "pop"], "Canada", "English"),
    ("Skyfall", "Adele", 2012, ["film score", "pop"], "United Kingdom", "English"),
    ("Eye of the Tiger", "Survivor", 1982, ["rock", "film score"], "United States", "English"),
    ("Danger Zone", "Kenny Loggins", 1986, ["rock", "film score"], "United States", "English"),
    ("Take My Breath Away", "Berlin", 1986, ["pop", "film score"], "United States", "English"),
    ("Flashdance... What a Feeling", "Irene Cara", 1983, ["pop", "film score"], "United States", "English"),
    ("Footloose", "Kenny Loggins", 1984, ["rock", "film score"], "United States", "English"),
    ("Y.M.C.A.", "Village People", 1978, ["disco"], "United States", "English"),
    ("Macarena", "Los del Río", 1993, ["latin pop"], "Spain", "Spanish"),
    ("Cotton Eye Joe", "Rednex", 1994, ["country", "eurodance"], "Sweden", "English"),
    ("Barbie Girl", "Aqua", 1997, ["pop", "eurodance"], "Denmark/Norway", "English"),
    ("It's My Life", "Bon Jovi", 2000, ["rock"], "United States", "English"),
    ("Complicated", "Avril Lavigne", 2002, ["pop rock"], "Canada", "English"),
    ("Beautiful Day", "U2", 2000, ["rock"], "Ireland", "English"),
    ("Chasing Cars", "Snow Patrol", 2006, ["rock"], "United Kingdom", "English"),
    ("Viva la Vida", "Coldplay", 2008, ["rock", "pop"], "United Kingdom", "English"),
    ("Set Fire to the Rain", "Adele", 2011, ["pop", "soul"], "United Kingdom", "English"),
    ("Counting Stars", "OneRepublic", 2013, ["pop rock"], "United States", "English"),
    ("Happy", "Pharrell Williams", 2013, ["pop", "soul"], "United States", "English"),
    ("Roar", "Katy Perry", 2013, ["pop"], "United States", "English"),
    ("Shake It Off", "Taylor Swift", 2014, ["pop"], "United States", "English"),
    ("Love Story", "Taylor Swift", 2008, ["country pop"], "United States", "English"),
    ("Rolling in the Deep (reprise)", "Adele", 2011, ["pop", "soul"], "United Kingdom", "English"),
    ("Radioactive", "Imagine Dragons", 2012, ["rock", "pop"], "United States", "English"),
    ("Believer", "Imagine Dragons", 2017, ["rock", "pop"], "United States", "English"),
    ("Thinking Out Loud", "Ed Sheeran", 2014, ["pop"], "United Kingdom", "English"),
    ("Havana", "Camila Cabello ft. Young Thug", 2017, ["pop", "latin"], "Cuba/United States", "English/Spanish"),
    ("Uptown Girl", "Billy Joel", 1983, ["pop", "rock"], "United States", "English"),
    ("We Are the World", "USA for Africa", 1985, ["pop", "charity"], "United States", "English"),
    ("Heal the World", "Michael Jackson", 1991, ["pop"], "United States", "English"),
    ("Imagine", "John Lennon", 1971, ["pop", "rock"], "United Kingdom", "English"),
    ("Let It Be", "The Beatles", 1970, ["pop", "rock"], "United Kingdom", "English"),
    ("Here Comes the Sun", "The Beatles", 1969, ["pop", "rock"], "United Kingdom", "English"),
    ("Yesterday", "The Beatles", 1965, ["pop", "rock"], "United Kingdom", "English"),
    ("Twist and Shout", "The Beatles", 1963, ["rock"], "United Kingdom", "English"),
    ("A Hard Day's Night", "The Beatles", 1964, ["rock", "pop"], "United Kingdom", "English"),
    ("Ob-La-Di, Ob-La-Da", "The Beatles", 1968, ["pop", "rock"], "United Kingdom", "English"),
    ("Space Oddity", "David Bowie", 1969, ["rock"], "United Kingdom", "English"),
    ("Ziggy Stardust", "David Bowie", 1972, ["rock"], "United Kingdom", "English"),
    ("Under Pressure", "Queen & David Bowie", 1981, ["rock"], "United Kingdom", "English"),
    ("We Will Rock You", "Queen", 1977, ["rock"], "United Kingdom", "English"),
    ("We Are the Champions", "Queen", 1977, ["rock"], "United Kingdom", "English"),
    ("Africa", "Toto", 1982, ["rock", "pop"], "United States", "English"),
    ("Total Eclipse of the Heart", "Bonnie Tyler", 1983, ["rock", "pop"], "United Kingdom", "English"),
    ("Alone", "Heart", 1987, ["rock"], "United States", "English"),
    ("Kiss from a Rose", "Seal", 1994, ["pop", "soul"], "United Kingdom", "English"),
    ("No Diggity", "Blackstreet", 1996, ["r&b"], "United States", "English"),
    ("End of the Road", "Boyz II Men", 1992, ["r&b"], "United States", "English"),
    ("I'll Make Love to You", "Boyz II Men", 1994, ["r&b"], "United States", "English"),
    ("Kiss", "Prince", 1986, ["pop", "funk"], "United States", "English"),
    ("Superstition (reprise)", "Stevie Wonder", 1972, ["funk"], "United States", "English"),
    ("Ain't No Mountain High Enough", "Marvin Gaye & Tammi Terrell", 1967, ["soul"], "United States", "English"),
    ("I Heard It Through the Grapevine", "Marvin Gaye", 1968, ["soul"], "United States", "English"),
    ("Papa Was a Rollin' Stone", "The Temptations", 1972, ["soul", "funk"], "United States", "English"),
    ("My Girl", "The Temptations", 1964, ["soul"], "United States", "English"),
    ("I Want You Back", "The Jackson 5", 1969, ["pop", "soul"], "United States", "English"),
    ("ABC", "The Jackson 5", 1970, ["pop", "soul"], "United States", "English"),
    ("Signed, Sealed, Delivered I'm Yours", "Stevie Wonder", 1970, ["soul"], "United States", "English"),
    ("Sir Duke", "Stevie Wonder", 1976, ["funk", "soul"], "United States", "English"),
    ("Higher Ground", "Stevie Wonder", 1973, ["funk", "soul"], "United States", "English"),
    ("Sing, Sing, Sing", "Benny Goodman", 1937, ["swing", "jazz"], "United States", "Instrumental"),
    ("In the Mood", "Glenn Miller", 1939, ["swing", "jazz"], "United States", "Instrumental"),
    ("A String of Pearls", "Glenn Miller", 1941, ["swing", "jazz"], "United States", "Instrumental"),
    ("Minnie the Moocher", "Cab Calloway", 1931, ["jazz", "swing"], "United States", "English"),
    ("Take the 'A' Train", "Duke Ellington", 1941, ["jazz"], "United States", "Instrumental"),
    ("Mack the Knife", "Bobby Darin", 1959, ["jazz", "pop"], "United States", "English"),
    ("Georgia on My Mind", "Ray Charles", 1960, ["soul", "jazz"], "United States", "English"),
    ("Unforgettable", "Nat King Cole", 1951, ["jazz", "pop"], "United States", "English"),
    ("Feeling Good (reprise)", "Michael Bublé", 2005, ["jazz", "pop"], "Canada", "English"),
    ("L-O-V-E", "Nat King Cole", 1965, ["jazz", "pop"], "United States", "English"),
    ("Blue Suede Shoes", "Carl Perkins", 1955, ["rockabilly"], "United States", "English"),
    ("Great Balls of Fire", "Jerry Lee Lewis", 1957, ["rock and roll"], "United States", "English"),
    ("Tutti Frutti", "Little Richard", 1955, ["rock and roll"], "United States", "English"),
    ("Good Golly, Miss Molly", "Little Richard", 1958, ["rock and roll"], "United States", "English"),
    ("Rock Around the Clock", "Bill Haley & His Comets", 1954, ["rock and roll"], "United States", "English"),
    ("Peggy Sue", "Buddy Holly", 1957, ["rock and roll"], "United States", "English"),
    ("Oh, Pretty Woman", "Roy Orbison", 1964, ["rock and roll", "pop"], "United States", "English"),
    ("Only the Lonely", "Roy Orbison", 1960, ["rock and roll", "pop"], "United States", "English"),
    ("Crazy", "Patsy Cline", 1961, ["country"], "United States", "English"),
    ("Stand by Your Man", "Tammy Wynette", 1968, ["country"], "United States", "English"),
    ("Coat of Many Colors", "Dolly Parton", 1971, ["country"], "United States", "English"),
    ("The House of the Rising Sun", "The Animals", 1964, ["rock", "folk"], "United Kingdom", "English"),
    ("House of the Rising Sun (folk origin)", "Traditional American Folk", 1930, ["folk"], "United States", "English"),
    ("Scarborough Fair", "Simon & Garfunkel", 1966, ["folk"], "United States/United Kingdom", "English"),
    ("The Times They Are A-Changin'", "Bob Dylan", 1964, ["folk"], "United States", "English"),
    ("If I Had a Hammer", "Peter, Paul and Mary", 1962, ["folk"], "United States", "English"),
    ("Puff, the Magic Dragon", "Peter, Paul and Mary", 1963, ["folk"], "United States", "English"),
    ("Where Have All the Flowers Gone?", "Pete Seeger", 1955, ["folk"], "United States", "English"),
    ("Turn! Turn! Turn!", "The Byrds", 1965, ["folk rock"], "United States", "English"),
    ("California Dreamin'", "The Mamas & the Papas", 1965, ["folk rock", "pop"], "United States", "English"),
    ("San Francisco (Wear Some Flowers in Your Hair)", "Scott McKenzie", 1967, ["folk", "pop"], "United States", "English"),
    ("White Rabbit", "Jefferson Airplane", 1967, ["rock", "psychedelic"], "United States", "English"),
    ("Good Vibrations", "The Beach Boys", 1966, ["pop", "rock"], "United States", "English"),
    ("Surfin' USA", "The Beach Boys", 1963, ["rock", "surf"], "United States", "English"),
    ("Wouldn't It Be Nice", "The Beach Boys", 1966, ["pop", "rock"], "United States", "English"),
    ("Born to Run", "Bruce Springsteen", 1975, ["rock"], "United States", "English"),
    ("Dancing in the Dark", "Bruce Springsteen", 1984, ["rock", "pop"], "United States", "English"),
    ("Born in the U.S.A.", "Bruce Springsteen", 1984, ["rock"], "United States", "English"),
    ("Jack and Diane", "John Mellencamp", 1982, ["rock"], "United States", "English"),
    ("American Pie", "Don McLean", 1971, ["folk rock", "pop"], "United States", "English"),
    ("Rocket Man (reprise)", "Elton John", 1972, ["pop"], "United Kingdom", "English"),
    ("Tiny Dancer", "Elton John", 1971, ["pop", "rock"], "United Kingdom", "English"),
    ("Bennie and the Jets", "Elton John", 1973, ["pop", "rock"], "United Kingdom", "English"),
    ("Take On Me", "a-ha", 1985, ["synth-pop"], "Norway", "English"),
    ("Enjoy the Silence", "Depeche Mode", 1990, ["synth-pop"], "United Kingdom", "English"),
    ("Just Can't Get Enough", "Depeche Mode", 1981, ["synth-pop"], "United Kingdom", "English"),
    ("Blue Monday", "New Order", 1983, ["synth-pop", "dance"], "United Kingdom", "English"),
    ("Don't You Want Me", "The Human League", 1981, ["synth-pop"], "United Kingdom", "English"),
    ("Tainted Love", "Soft Cell", 1981, ["synth-pop"], "United Kingdom", "English"),
    ("Sweet Dreams (Are Made of This)", "Eurythmics", 1983, ["synth-pop"], "United Kingdom", "English"),
    ("Girls Just Want to Have Fun", "Cyndi Lauper", 1983, ["pop"], "United States", "English"),
    ("Material Girl", "Madonna", 1984, ["pop"], "United States", "English"),
    ("Papa Don't Preach", "Madonna", 1986, ["pop"], "United States", "English"),
    ("Like a Prayer", "Madonna", 1989, ["pop"], "United States", "English"),
    ("Faith", "George Michael", 1987, ["pop"], "United Kingdom", "English"),
    ("Wake Me Up Before You Go-Go", "Wham!", 1984, ["pop"], "United Kingdom", "English"),
    ("Last Christmas", "Wham!", 1984, ["pop", "holiday"], "United Kingdom", "English"),
    ("All I Want for Christmas Is You", "Mariah Carey", 1994, ["pop", "holiday"], "United States", "English"),
    ("Jingle Bell Rock", "Bobby Helms", 1957, ["holiday", "rock and roll"], "United States", "English"),
    ("White Christmas", "Bing Crosby", 1942, ["holiday", "pop"], "United States", "English"),
    ("Silent Night", "Franz Xaver Gruber", 1818, ["holiday", "hymn"], "Austria", "German/English"),
    ("O Holy Night", "Adolphe Adam", 1847, ["holiday", "hymn"], "France", "English/French"),
    ("Feliz Navidad", "José Feliciano", 1970, ["holiday", "latin"], "Puerto Rico", "Spanish/English"),
    ("Hanukkah, Oh Hanukkah", "Traditional Jewish Folk", 1912, ["holiday", "folk"], "Israel/Eastern Europe", "Yiddish/English"),
    ("Ma'oz Tzur", "Traditional Jewish Hymn", 1450, ["holiday", "hymn"], "Israel", "Hebrew"),
    ("Diwali Dhamaka (festival medley)", "Traditional Indian Festival Songs", 1950, ["holiday", "bollywood"], "India", "Hindi"),
    ("Eid Mubarak (festival nasheed)", "Traditional Nasheed", 1980, ["holiday", "nasheed"], "Various", "Arabic"),
    ("Tala' al-Badru 'Alayna", "Traditional Nasheed", 622, ["nasheed"], "Saudi Arabia", "Arabic"),
]


def build_records(existing_ids: set[str]) -> list[dict]:
    records = []
    for title, artist, year, genres, country, language in SONGS:
        slug_source = f"{title}-{artist}"
        slug = "".join(c.lower() if c.isalnum() else "_" for c in slug_source).strip("_")
        while "__" in slug:
            slug = slug.replace("__", "_")
        song_id = slug[:60]
        if song_id in existing_ids:
            song_id = f"{song_id}_{year}"
        if song_id in existing_ids:
            continue
        existing_ids.add(song_id)
        decade = decade_of(year)
        records.append({
            "id": song_id,
            "title": title,
            "artist": artist,
            "album": "",
            "year": year,
            "genre": genres,
            "origin_country": country,
            "language": language,
            "duration_approx": "",
            "description": f"A well-known {decade} {genres[0]} song by {artist} from {country}.",
            "educational_notes": f"Useful for exploring {genres[0]} music history and the musical traditions of {country}.",
            "fun_fact": f"Part of the {decade} {genres[0]} songbook, widely referenced in music history and radio retrospectives.",
            "awards": [],
            "links": {
                "youtube_search": yt(f"{title} {artist} official"),
                "wiki_search": wiki(f"{title} {artist}"),
                "lyrics_search": google(f"{title} {artist} lyrics"),
            },
            "tags": genres + [decade],
            "decade": decade,
            "suitable_for_ages": "all",
        })
    return records


def main() -> None:
    with open(SONGS_PATH, encoding="utf-8") as f:
        data = json.load(f)
    songs = data["songs"]
    existing_ids = {s["id"] for s in songs}

    new_records = build_records(existing_ids)
    songs.extend(new_records)
    data["songs"] = songs
    data["total"] = len(songs)

    genres = sorted({g for s in songs for g in s.get("genre", [])})
    decades = sorted({s.get("decade", "") for s in songs if s.get("decade")})
    data["genres"] = genres
    data["decades"] = decades

    with open(SONGS_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Added {len(new_records)} songs. Library now has {len(songs)} songs.")


if __name__ == "__main__":
    main()
