#!/usr/bin/env python3
"""Expand every STEM Lab discipline to at least 20 experiments, and add a
real YouTube search video link to every experiment (existing and new).

Re-run after editing:
    python3 backend/scripts/generate_stem_expansion.py
"""
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import quote_plus

BASE_DIR = Path(__file__).resolve().parent.parent
STEM_PATH = BASE_DIR / "data" / "stem_lab" / "stem_lab.json"


def yt(q: str) -> str:
    return "https://www.youtube.com/results?search_query=" + quote_plus(q)


# (title, difficulty, duration_mins, materials, core_idea, key_concepts, quiz_q, quiz_options, answer_idx)
# `core_idea` becomes the explanation and drives templated steps/quiz.

PHYSICS = [
    ("Pendulum Period and Length", "beginner", 20, ["string", "small weight", "stopwatch", "ruler"],
     "A pendulum's period depends on its length (and gravity), not its mass or swing amplitude (for small swings).",
     ["pendulum", "period", "gravity"], "What mainly determines a pendulum's period?", ["Its mass", "Its length", "Its color", "The time of day"], 1),
    ("Newton's Cradle Momentum", "beginner", 20, ["5 identical swinging balls (or marbles and string)"],
     "Newton's Cradle demonstrates conservation of momentum and energy as motion transfers ball to ball.",
     ["momentum", "conservation", "collision"], "What is conserved when the balls collide?", ["Color", "Momentum and energy", "Temperature", "Nothing"], 1),
    ("Balloon Rocket (Newton's Third Law)", "beginner", 20, ["balloon", "string", "straw", "tape"],
     "Air rushing out of the balloon pushes it forward, demonstrating Newton's third law: every action has an equal and opposite reaction.",
     ["Newton's third law", "thrust", "propulsion"], "Newton's third law states that every action has:", ["No reaction", "An equal and opposite reaction", "A bigger reaction", "A delayed reaction"], 1),
    ("Egg Drop Impact Protection", "intermediate", 30, ["raw egg", "padding materials", "container"],
     "Cushioning increases the time over which an impact force is applied, reducing peak force on the egg (impulse-momentum theorem)."
     , ["impulse", "force", "momentum"], "Why does padding help protect the egg?", ["It makes the egg lighter", "It increases impact time, reducing force", "It changes gravity", "It has no effect"], 1),
    ("Simple Machines: Inclined Plane", "beginner", 20, ["ramp/board", "toy car or weight", "spring scale"],
     "An inclined plane reduces the force needed to raise an object by increasing the distance over which the force acts.",
     ["inclined plane", "mechanical advantage", "work"], "An inclined plane makes lifting easier by:", ["Reducing the weight", "Trading distance for reduced force", "Adding energy", "Removing friction"], 1),
    ("Density Tower with Liquids", "beginner", 20, ["honey", "dish soap", "water", "oil", "tall clear glass"],
     "Liquids of different densities form visible layers, with the densest liquid sinking to the bottom.",
     ["density", "buoyancy", "layering"], "Why do the liquids form layers instead of mixing?", ["They have different densities", "They have different colors", "They are magnetic", "They are the same temperature"], 0),
    ("Static Electricity with a Balloon", "beginner", 15, ["balloon", "wool cloth or hair", "small paper bits"],
     "Rubbing a balloon transfers electrons, creating a static charge that attracts light, neutral objects.",
     ["static electricity", "charge", "electron transfer"], "Rubbing the balloon creates static electricity by:", ["Transferring electrons", "Heating the balloon", "Adding water", "Removing air"], 0),
    ("Building an Electromagnet", "intermediate", 30, ["iron nail", "insulated copper wire", "battery", "paperclips"],
     "Coiling current-carrying wire around iron creates a magnetic field, turning the nail into a temporary magnet.",
     ["electromagnetism", "magnetic field", "current"], "What creates the magnetic field in an electromagnet?", ["The iron alone", "Electric current through the coiled wire", "The paperclips", "Sunlight"], 1),
    ("Refraction: Disappearing Glass Rod", "intermediate", 20, ["clear glass rod or stirrer", "vegetable oil", "clear glass"],
     "Light bends (refracts) differently through materials of different refractive indices; matching indices makes an object seem to vanish.",
     ["refraction", "refractive index", "light"], "The glass rod seems to disappear because:", ["It dissolves in the oil", "Its refractive index matches the oil's", "It's actually removed", "The oil is opaque"], 1),
    ("Sound Waves and Vibrating Rulers", "beginner", 15, ["plastic ruler", "table edge"],
     "A vibrating object's frequency determines the pitch we hear; shorter vibrating lengths vibrate faster and sound higher-pitched.",
     ["frequency", "pitch", "vibration"], "A shorter vibrating ruler length produces:", ["A lower pitch", "A higher pitch", "No sound", "Only silence"], 1),
    ("Convex and Concave Lens Exploration", "intermediate", 25, ["magnifying glass", "concave lens (or eyeglasses)", "light source"],
     "Convex lenses converge light rays and can magnify or focus images; concave lenses diverge light rays.",
     ["lens", "convex", "concave", "focal point"], "A convex lens does what to light rays?", ["Converges them", "Blocks them", "Diverges them", "Reflects them"], 0),
    ("Center of Mass Balancing Challenge", "beginner", 20, ["ruler", "various small objects", "fulcrum (pencil)"],
     "An object balances when its center of mass is directly above its support point.",
     ["center of mass", "balance", "torque"], "An object balances when its center of mass is:", ["As far as possible from the support", "Directly above the support point", "Always at its geometric center", "Irrelevant to balance"], 1),
    ("Friction and Surface Materials", "beginner", 20, ["block", "spring scale", "various surface materials"],
     "Friction force depends on the surfaces in contact; rougher surfaces generally produce more friction.",
     ["friction", "surface", "force"], "Which surface generally produces more friction?", ["Smooth ice", "A rough surface like sandpaper", "Glass", "Wet tile"], 1),
    ("Projectile Motion with a Marble Launcher", "intermediate", 30, ["ramp", "marble", "measuring tape", "protractor"],
     "Projectile range depends on launch angle and speed; 45 degrees maximizes range for a given speed on level ground (no air resistance).",
     ["projectile motion", "trajectory", "launch angle"], "Which launch angle maximizes range (ignoring air resistance)?", ["15 degrees", "45 degrees", "90 degrees", "0 degrees"], 1),
    ("Archimedes' Principle: Floating and Sinking", "beginner", 20, ["various objects", "water container", "scale"],
     "An object floats if it displaces a weight of water equal to its own weight (buoyant force equals weight).",
     ["buoyancy", "Archimedes' principle", "displacement"], "An object floats when the buoyant force:", ["Is zero", "Equals its weight", "Is less than its weight", "Doesn't exist"], 1),
    ("Heat Transfer: Conduction Race", "beginner", 20, ["metal spoon", "wooden spoon", "plastic spoon", "hot water", "butter"],
     "Different materials conduct heat at different rates; metals are generally much better conductors than wood or plastic.",
     ["conduction", "heat transfer", "thermal conductivity"], "Which material conducts heat fastest in this experiment?", ["Wood", "Plastic", "Metal", "They're all equal"], 2),
    ("Simple Circuit: Series vs Parallel", "intermediate", 30, ["batteries", "bulbs/LEDs", "wires", "switch"],
     "In series circuits, current has one path and components share voltage; in parallel circuits, each branch gets full voltage.",
     ["circuit", "series", "parallel", "current"], "In a parallel circuit, if one branch breaks, the others:", ["All stop working", "Continue working independently", "Get brighter only", "Disappear"], 1),
    ("Doppler Effect with Sound", "intermediate", 20, ["phone with tone app or buzzer", "string"],
     "The Doppler effect causes a sound's pitch to shift higher as a source approaches and lower as it moves away.",
     ["Doppler effect", "frequency shift", "sound waves"], "As a sound source approaches you, its pitch:", ["Gets lower", "Gets higher", "Stays the same", "Disappears"], 1),
    ("Torque and Wrench Length", "intermediate", 20, ["wrench or lever", "bolt", "spring scale"],
     "Torque equals force times the distance from the pivot; a longer lever arm produces more torque for the same force.",
     ["torque", "lever arm", "rotational force"], "A longer wrench handle makes turning a bolt easier because it:", ["Reduces torque", "Increases torque for the same force", "Removes friction", "Has no effect"], 1),
    ("Standing Waves on a String", "advanced", 30, ["string or slinky", "fixed anchor point", "hand or motor"],
     "Standing waves form when waves reflect and interfere, creating fixed nodes and moving antinodes at specific frequencies.",
     ["standing wave", "node", "antinode", "resonance"], "A point on a standing wave that never moves is called a:", ["Antinode", "Node", "Crest", "Trough"], 1),
    ("Terminal Velocity with Falling Objects", "intermediate", 25, ["coffee filters", "stopwatch", "measuring tape"],
     "As an object falls, air resistance increases with speed until it balances gravity, producing terminal velocity.",
     ["terminal velocity", "air resistance", "free fall"], "Terminal velocity is reached when:", ["Gravity exceeds air resistance", "Air resistance equals gravity", "There's no air resistance", "The object stops falling"], 1),
    ("Building a Simple Periscope", "beginner", 25, ["cardboard tube or box", "two small mirrors", "tape"],
     "A periscope uses two parallel mirrors set at 45 degrees to reflect light around obstacles, letting you see over or around them.",
     ["reflection", "periscope", "angle of incidence"], "A periscope's mirrors are typically angled at:", ["90 degrees", "45 degrees", "0 degrees", "180 degrees"], 1),
]

CHEMISTRY = [
    ("Baking Soda and Vinegar Reaction", "beginner", 15, ["baking soda", "vinegar", "balloon", "bottle"],
     "Baking soda (a base) reacts with vinegar (an acid) to produce carbon dioxide gas, water, and sodium acetate.",
     ["acid-base reaction", "carbon dioxide", "chemical reaction"], "What gas is produced when baking soda meets vinegar?", ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], 1),
    ("Elephant Toothpaste (Decomposition)", "intermediate", 25, ["hydrogen peroxide", "yeast", "dish soap", "warm water"],
     "Yeast catalyzes the rapid decomposition of hydrogen peroxide into water and oxygen gas, trapped by soap into foam.",
     ["decomposition reaction", "catalyst", "exothermic"], "What role does yeast play in this reaction?", ["Fuel", "Catalyst", "Coolant", "Solvent"], 1),
    ("Red Cabbage pH Indicator", "beginner", 25, ["red cabbage", "hot water", "household liquids to test"],
     "Red cabbage contains anthocyanin pigments that change color depending on pH, acting as a natural acid-base indicator.",
     ["pH", "indicator", "acid", "base"], "Red cabbage juice changes color based on:", ["Temperature", "pH", "Time of day", "Light exposure"], 1),
    ("Crystal Growing with Sugar or Salt", "beginner", 20, ["sugar or salt", "water", "string", "jar"],
     "As a saturated solution cools or water evaporates, dissolved particles come out of solution and form ordered crystal structures.",
     ["saturation", "crystallization", "solubility"], "Crystals form as a solution becomes:", ["More diluted", "Supersaturated", "Colder only", "Boiled"], 1),
    ("Density Rainbow with Sugar Water", "beginner", 25, ["sugar", "water", "food coloring", "clear glass"],
     "Solutions with more dissolved sugar are denser and sink below less concentrated (less dense) solutions.",
     ["density", "solution concentration", "layering"], "Which sugar-water layer sinks to the bottom?", ["The least concentrated", "The most concentrated", "They all mix", "The coldest one"], 1),
    ("Milk and Food Coloring Chemistry", "beginner", 15, ["milk", "food coloring", "dish soap", "cotton swab"],
     "Soap molecules disrupt the fat in milk, causing swirling motion as fat molecules rearrange around the soap.",
     ["surface tension", "fat molecules", "soap chemistry"], "What causes the swirling colors in the milk?", ["Heat", "Soap disrupting fat molecules", "Magnetism", "Evaporation"], 1),
    ("Rust Formation (Oxidation) Race", "beginner", 20, ["steel wool or nails", "water", "salt", "containers"],
     "Rust forms when iron reacts with oxygen and water in an oxidation reaction; salt water speeds the process by improving conductivity.",
     ["oxidation", "rust", "chemical reaction rate"], "What two substances does iron react with to form rust?", ["Oxygen and water", "Nitrogen and heat", "Carbon and salt", "Sugar and water"], 0),
    ("Making Slime (Polymer Cross-Linking)", "beginner", 20, ["white glue", "borax or contact lens solution", "water"],
     "Borax ions cross-link the long polymer chains in glue, turning a liquid into a stretchy, semi-solid polymer network.",
     ["polymer", "cross-linking", "viscoelastic"], "What does borax do to the glue's polymer chains?", ["Dissolves them", "Cross-links them together", "Removes them", "Heats them"], 1),
    ("Flame Tests for Metal Ions", "advanced", 25, ["metal salts (with adult supervision)", "wire loops", "flame source"],
     "Different metal ions emit characteristic colors when heated, as electrons absorb energy and release it as specific wavelengths of light.",
     ["flame test", "emission spectrum", "electron energy levels"], "Flame tests identify metals by their:", ["Weight", "Characteristic emitted color", "Smell", "Melting point"], 1),
    ("Electrolysis of Water", "advanced", 25, ["9V battery", "water", "salt", "pencil leads/electrodes"],
     "Passing electric current through water splits it into hydrogen and oxygen gas at the two electrodes.",
     ["electrolysis", "decomposition", "hydrogen", "oxygen"], "Electrolysis of water produces which two gases?", ["Nitrogen and carbon dioxide", "Hydrogen and oxygen", "Helium and neon", "Chlorine and argon"], 1),
    ("Chromatography: Separating Ink Colors", "beginner", 20, ["coffee filter paper", "washable markers", "water", "cups"],
     "Chromatography separates mixtures as different pigment molecules travel at different rates through the paper with the solvent.",
     ["chromatography", "separation", "pigments"], "Chromatography separates a mixture based on differences in:", ["Color only", "How fast components travel through the medium", "Weight only", "Temperature"], 1),
    ("Acid-Base Neutralization Titration", "advanced", 30, ["vinegar", "baking soda solution", "pH indicator", "dropper"],
     "Neutralization occurs when an acid and base react to form water and a salt, moving the pH toward neutral (7).",
     ["neutralization", "titration", "pH"], "What are the products of an acid-base neutralization reaction?", ["Only gas", "Water and a salt", "Only heat", "Only crystal"], 1),
    ("Endothermic Reaction: Instant Cold Pack", "intermediate", 15, ["ammonium nitrate or citric acid+baking soda", "water", "bag"],
     "Endothermic reactions absorb heat from their surroundings, causing the temperature to drop noticeably.",
     ["endothermic", "heat absorption", "temperature change"], "An endothermic reaction does what to its surroundings?", ["Releases heat, warming them", "Absorbs heat, cooling them", "Has no thermal effect", "Only affects light"], 1),
    ("Exothermic Reaction: Hand Warmers", "intermediate", 15, ["iron powder", "salt", "water", "activated carbon"],
     "Exothermic reactions release heat; the oxidation of iron powder in a hand warmer releases warmth over time.",
     ["exothermic", "oxidation", "heat release"], "An exothermic reaction does what to its surroundings?", ["Absorbs heat", "Releases heat, warming them", "Has no effect", "Only changes color"], 1),
    ("Testing for Starch with Iodine", "beginner", 15, ["iodine solution", "various foods", "dropper"],
     "Iodine reacts with starch to form a deep blue-black complex, a classic test for starch presence in food.",
     ["starch test", "iodine", "indicator reaction"], "Iodine turns what color in the presence of starch?", ["Red", "Blue-black", "Green", "Colorless"], 1),
    ("Solubility and Temperature", "beginner", 20, ["sugar or salt", "hot and cold water", "measuring spoons"],
     "Most solids dissolve faster and in greater quantity in warmer water, since higher temperature increases solute-solvent collisions.",
     ["solubility", "temperature", "saturation point"], "As water temperature increases, solid solubility generally:", ["Decreases", "Increases", "Stays the same", "Becomes zero"], 1),
    ("Building a Lemon Battery", "intermediate", 25, ["lemons", "zinc and copper electrodes", "wires", "small LED"],
     "A lemon battery uses acid as an electrolyte between two different metals, creating a small voltage through electrochemical reaction.",
     ["electrochemistry", "electrolyte", "voltage"], "What acts as the electrolyte in a lemon battery?", ["The zinc electrode", "The lemon's citric acid juice", "The copper wire", "Air"], 1),
    ("Polymer Bouncy Ball Making", "intermediate", 25, ["borax", "cornstarch", "white glue", "food coloring"],
     "Combining glue polymers with borax cross-linker and cornstarch creates a dense, elastic polymer ball.",
     ["polymer", "elasticity", "cross-linking"], "What gives the bouncy ball its elastic, bouncy property?", ["Its color", "Cross-linked polymer chains", "Its temperature", "Its weight alone"], 1),
    ("Carbon Dioxide and Limewater Test", "intermediate", 20, ["limewater", "straw", "baking soda and vinegar"],
     "Carbon dioxide gas turns clear limewater cloudy by forming insoluble calcium carbonate, a classic CO2 test.",
     ["carbon dioxide test", "limewater", "precipitate"], "Limewater turns cloudy in the presence of:", ["Oxygen", "Carbon dioxide", "Nitrogen", "Water vapor only"], 1),
    ("Saponification: Making Simple Soap", "advanced", 30, ["oil", "lye solution (adult supervision)", "mold"],
     "Saponification is the chemical reaction between a fat/oil and a strong base (lye) that produces soap and glycerol.",
     ["saponification", "fat", "base reaction"], "Saponification combines a fat/oil with a:", ["Strong acid", "Strong base (lye)", "Neutral salt", "Sugar solution"], 1),
    ("Iron Filings and Magnetism vs Chemistry", "beginner", 15, ["iron filings", "sand", "magnet"],
     "Physical separation with a magnet (iron is magnetic, sand isn't) illustrates the difference between physical and chemical properties.",
     ["physical property", "separation", "magnetism"], "Using a magnet to separate iron from sand is an example of a:", ["Chemical reaction", "Physical separation", "Nuclear reaction", "Biological process"], 1),
]

BIOLOGY = [
    ("Observing Onion Cells Under a Microscope", "beginner", 25, ["onion", "microscope", "iodine stain", "slide"],
     "Onion epidermal cells show a clear cell wall, nucleus, and cytoplasm, useful for learning basic plant cell structure.",
     ["cell structure", "cell wall", "microscopy"], "What structure is unique to plant cells (not animal cells)?", ["Nucleus", "Cell wall", "Cytoplasm", "Ribosomes"], 1),
    ("Photosynthesis: Leaf Disc Assay", "intermediate", 30, ["leaf discs", "baking soda solution", "light source", "syringe"],
     "Leaf discs float once photosynthesis produces enough oxygen gas to make them buoyant, letting you measure photosynthetic rate.",
     ["photosynthesis", "oxygen production", "light reaction"], "What gas causes the leaf discs to float?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], 1),
    ("Osmosis with Potato Strips", "beginner", 30, ["potato strips", "salt water", "fresh water", "scale"],
     "Water moves across a semi-permeable membrane from low to high solute concentration (osmosis), changing the potato's mass and firmness.",
     ["osmosis", "concentration gradient", "membrane"], "Potato strips in salt water tend to:", ["Gain water and swell", "Lose water and shrink", "Stay exactly the same", "Dissolve completely"], 1),
    ("Yeast Fermentation and CO2 Production", "beginner", 25, ["yeast", "sugar", "warm water", "balloon", "bottle"],
     "Yeast ferments sugar anaerobically, producing carbon dioxide gas and ethanol as byproducts.",
     ["fermentation", "yeast", "anaerobic respiration"], "What gas does yeast produce during fermentation?", ["Oxygen", "Carbon dioxide", "Helium", "Nitrogen"], 1),
    ("DNA Extraction from Strawberries", "intermediate", 30, ["strawberries", "dish soap", "salt", "rubbing alcohol"],
     "Soap breaks down cell membranes, salt helps clump proteins, and cold alcohol precipitates visible strands of DNA.",
     ["DNA extraction", "cell membrane", "precipitation"], "What causes DNA to become visible and precipitate?", ["Heating it", "Adding cold alcohol", "Adding sugar", "Freezing the soap"], 1),
    ("Heart Rate and Exercise", "beginner", 20, ["stopwatch", "willing participants"],
     "Exercise increases the body's oxygen demand, causing the heart to beat faster to deliver more oxygenated blood to muscles.",
     ["heart rate", "cardiovascular system", "exercise physiology"], "Why does heart rate increase during exercise?", ["To cool the body only", "To deliver more oxygen to muscles", "It doesn't actually change", "To slow digestion"], 1),
    ("Seed Germination Conditions", "beginner", 25, ["bean seeds", "paper towels", "plastic bags", "varying conditions"],
     "Seed germination requires water, appropriate temperature, and oxygen; testing variables reveals which factors are essential.",
     ["germination", "controlled variables", "plant growth"], "Which of these is generally required for seed germination?", ["Darkness only", "Water", "Extreme cold", "Salt water"], 1),
    ("Enzyme Activity: Catalase in Liver/Potato", "advanced", 25, ["hydrogen peroxide", "liver or potato pieces", "test tubes"],
     "The enzyme catalase breaks down hydrogen peroxide into water and oxygen, visible as rapid bubbling.",
     ["enzyme", "catalase", "reaction rate"], "What does the enzyme catalase break down?", ["Water", "Hydrogen peroxide", "Sugar", "Salt"], 1),
    ("Human Reaction Time Test", "beginner", 15, ["ruler", "partner"],
     "Reaction time measures how quickly the nervous system processes a stimulus and triggers a motor response.",
     ["nervous system", "reaction time", "stimulus-response"], "Reaction time primarily tests the speed of the:", ["Digestive system", "Nervous system", "Skeletal system", "Circulatory system alone"], 1),
    ("Mold Growth on Bread (Controlled Variables)", "beginner", 20, ["bread slices", "plastic bags", "varying conditions"],
     "Mold (a fungus) grows faster in warm, moist, dark conditions, illustrating environmental effects on microbial growth.",
     ["fungus", "microbial growth", "controlled experiment"], "Mold generally grows fastest in conditions that are:", ["Cold and dry", "Warm and moist", "Frozen", "Completely sterile"], 1),
    ("Blood Type and Genetics Simulation", "advanced", 25, ["colored beads or cards to represent alleles"],
     "Blood type is determined by inherited alleles (A, B, O) following Mendelian inheritance patterns.",
     ["genetics", "alleles", "inheritance"], "Human blood type is an example of:", ["Environmental influence only", "Genetic inheritance", "Random chance with no pattern", "Learned behavior"], 1),
    ("Plant Transpiration Rate", "intermediate", 30, ["leafy plant", "plastic bag", "various conditions (light, wind, humidity)"],
     "Transpiration is water loss through leaf stomata, affected by light, wind, humidity, and temperature.",
     ["transpiration", "stomata", "water cycle"], "Transpiration mainly refers to a plant's loss of:", ["Sugar", "Water vapor", "Carbon dioxide", "Soil nutrients"], 1),
    ("Comparing Animal and Plant Cells", "intermediate", 25, ["onion cells", "cheek cells", "microscope", "stains"],
     "Plant cells have a cell wall and chloroplasts that animal cells lack; both share nucleus, membrane, and cytoplasm.",
     ["cell comparison", "chloroplast", "cell wall"], "Which structure do plant cells have that animal cells lack?", ["Nucleus", "Cell wall and chloroplasts", "Cytoplasm", "Cell membrane"], 1),
    ("Ecosystem in a Bottle (Terrarium)", "beginner", 30, ["clear bottle", "soil", "small plants", "water"],
     "A sealed terrarium models a self-sustaining ecosystem where water cycles and plants photosynthesize to survive with minimal input.",
     ["ecosystem", "water cycle", "self-sustaining system"], "A sealed terrarium can sustain plant life because of:", ["Regular refilling", "Its internal water cycle", "Direct sunlight only", "Added chemicals"], 1),
    ("Bacterial Growth and Hand Sanitizer Test", "intermediate", 30, ["agar plates or bread", "cotton swabs", "hand sanitizer"],
     "Comparing microbial growth from washed vs. unwashed hands demonstrates how sanitizing reduces bacterial colonies.",
     ["bacteria", "sanitation", "microbial colony"], "Hand sanitizer works by:", ["Adding nutrients for bacteria", "Killing or reducing bacteria on the skin", "Making bacteria grow faster", "Having no measurable effect"], 1),
    ("Bird Beak Adaptation Simulation", "beginner", 25, ["tools representing beaks (tweezers, clothespins)", "various 'food' items"],
     "Different tool shapes (like different beak shapes) are better suited to gathering different food types, illustrating adaptation.",
     ["adaptation", "natural selection", "structure-function"], "This simulation illustrates the biological concept of:", ["Photosynthesis", "Adaptation to environment", "Cell division", "Digestion"], 1),
    ("Measuring Lung Capacity", "beginner", 20, ["balloon", "measuring tape"],
     "Lung capacity varies between individuals and can be estimated by measuring the volume of a fully exhaled breath.",
     ["lung capacity", "respiratory system", "measurement"], "Lung capacity is a measure of:", ["Heart rate", "The volume of air the lungs can hold", "Blood pressure", "Muscle strength"], 1),
    ("Investigating Food Webs", "beginner", 25, ["cards representing organisms", "string"],
     "A food web shows interconnected feeding relationships; removing one organism can affect many others in the web.",
     ["food web", "ecosystem interdependence", "trophic level"], "Removing one species from a food web typically:", ["Has no effect on other species", "Can affect multiple connected species", "Only affects predators", "Only affects that species alone"], 1),
    ("Antibiotic Resistance Simulation", "advanced", 30, ["colored beads (representing resistant/susceptible bacteria)"],
     "This models how bacteria with random resistance mutations survive antibiotic exposure and reproduce, spreading resistance over generations.",
     ["antibiotic resistance", "natural selection", "mutation"], "Antibiotic resistance spreads mainly through:", ["Random chance with no pattern", "Survival and reproduction of resistant bacteria", "Antibiotics creating resistance directly", "Bacteria choosing to resist"], 1),
    ("Vitamin C Concentration Test", "intermediate", 25, ["iodine solution", "cornstarch", "various fruit juices", "dropper"],
     "Vitamin C (ascorbic acid) reacts with iodine, and the amount of juice needed to decolorize a fixed iodine-starch mixture indicates vitamin C concentration.",
     ["vitamin C", "titration", "antioxidant"], "This test estimates vitamin C content by measuring:", ["Color intensity only", "How much juice is needed to decolorize the iodine mixture", "The juice's temperature", "The juice's smell"], 1),
]

ENGINEERING = [
    ("Building the Tallest Spaghetti Tower", "beginner", 30, ["dry spaghetti", "marshmallows", "tape", "string"],
     "Triangular structures are inherently more stable than square ones, distributing load more effectively.",
     ["structural engineering", "triangulation", "load distribution"], "Why are triangles used in strong structures?", ["They look nicer", "They distribute load and resist deformation better", "They use less material always", "They are easier to draw"], 1),
    ("Bridge Load Testing", "intermediate", 30, ["popsicle sticks", "glue", "weights"],
     "Bridge design must balance tension and compression forces; truss designs distribute load efficiently across many members.",
     ["truss", "tension", "compression"], "A truss bridge design helps by:", ["Ignoring gravity", "Distributing load across many structural members", "Using only one beam", "Reducing the bridge's length"], 1),
    ("Egg Drop Protective Device", "intermediate", 30, ["raw egg", "various padding/building materials"],
     "Good protective design increases impact time and distributes force, reducing peak stress on the fragile egg.",
     ["impact protection", "force distribution", "design engineering"], "Padding protects the egg mainly by:", ["Making the egg lighter", "Increasing impact time and spreading force", "Changing gravity", "Removing air resistance"], 1),
    ("Building a Basic Water Filter", "beginner", 30, ["sand", "gravel", "activated charcoal", "cotton", "bottle"],
     "Layered filtration removes particles of decreasing size, with charcoal adsorbing some chemical impurities.",
     ["filtration", "water treatment", "layered design"], "In a layered water filter, particles are generally removed by:", ["Chemical reaction only", "Passing through progressively finer layers", "Freezing", "Evaporation"], 1),
    ("Designing a Wind Turbine Blade", "intermediate", 30, ["cardboard", "small motor/LED", "dowel", "fan"],
     "Blade shape and angle affect how efficiently a turbine converts wind's kinetic energy into rotational (and then electrical) energy.",
     ["wind energy", "blade design", "energy conversion"], "Changing blade angle affects a wind turbine's:", ["Color", "Energy conversion efficiency", "Weight only", "Nothing important"], 1),
    ("Catapult Design and Trajectory", "beginner", 30, ["popsicle sticks", "rubber bands", "spoon", "small projectile"],
     "Catapults store elastic potential energy and convert it to kinetic energy, with launch angle affecting projectile range.",
     ["elastic potential energy", "trajectory", "mechanical design"], "A catapult launches a projectile by converting:", ["Heat into light", "Elastic potential energy into kinetic energy", "Sound into motion", "Chemical energy into heat only"], 1),
    ("Building a Working Elevator/Pulley System", "intermediate", 30, ["pulleys", "string", "small basket", "weights"],
     "A pulley system can change the direction of force and, with multiple pulleys, reduce the effort needed to lift a load.",
     ["pulley", "mechanical advantage", "simple machine"], "A pulley system with multiple pulleys can:", ["Increase the weight of the load", "Reduce the effort force needed to lift a load", "Eliminate gravity", "Have no effect on force"], 1),
    ("Marble Run Engineering Challenge", "beginner", 30, ["cardboard tubes", "tape", "marble", "supports"],
     "Marble runs demonstrate energy conservation as gravitational potential energy converts to kinetic energy along the path.",
     ["energy conservation", "gravity", "kinetic energy"], "As a marble descends a marble run, potential energy converts to:", ["Chemical energy", "Kinetic energy", "Nuclear energy", "Sound energy only"], 1),
    ("Designing an Earthquake-Resistant Building Model", "advanced", 35, ["straws or sticks", "clay base", "shake table (or hands)"],
     "Flexible structures and a wide, stable base help buildings absorb and dissipate seismic energy rather than fracturing rigidly.",
     ["structural resilience", "seismic engineering", "flexibility"], "Earthquake-resistant buildings are often designed to be:", ["As rigid as possible", "Flexible enough to absorb seismic energy", "As tall as possible", "Made only of glass"], 1),
    ("Hydraulic Arm from Syringes", "intermediate", 30, ["syringes", "tubing", "water", "cardboard for arm structure"],
     "Hydraulic systems transmit force through an incompressible fluid, allowing small input forces to move larger loads.",
     ["hydraulics", "fluid mechanics", "force transmission"], "Hydraulic systems transmit force through:", ["Compressed air", "An incompressible fluid", "Electricity", "Magnetism"], 1),
    ("Paper Airplane Aerodynamics", "beginner", 20, ["paper", "ruler", "measuring tape"],
     "Wing shape, weight distribution, and folding precision affect lift, drag, and flight stability.",
     ["aerodynamics", "lift", "drag"], "Which force allows a paper airplane to stay airborne?", ["Gravity", "Lift", "Friction", "Magnetism"], 1),
    ("Building a Simple Robotic Arm", "advanced", 40, ["cardboard", "straws", "string", "small servos (optional)"],
     "Mechanical linkages and pivots let a simple structure mimic the multi-jointed movement of a human arm.",
     ["mechanical linkage", "robotics", "degrees of freedom"], "Multiple joints in a robotic arm provide more:", ["Weight", "Degrees of freedom (movement flexibility)", "Color options", "Static strength only"], 1),
    ("Solar Oven Construction", "intermediate", 35, ["pizza box", "aluminum foil", "plastic wrap", "black paper"],
     "A solar oven concentrates and traps sunlight as heat using reflective surfaces and a greenhouse-effect enclosure.",
     ["solar energy", "greenhouse effect", "heat trapping"], "A solar oven heats food mainly by:", ["Burning fuel", "Concentrating and trapping sunlight as heat", "Using electricity", "Chemical reaction"], 1),
    ("Testing Different Wing Shapes in a Homemade Wind Tunnel", "advanced", 35, ["fan", "cardboard tunnel", "various wing cutouts", "string"],
     "Airfoil shape affects how air flows over and under a wing, influencing the lift it generates.",
     ["airfoil", "lift", "wind tunnel testing"], "Wind tunnels are used to test how objects interact with:", ["Water", "Moving air", "Sound", "Light"], 1),
    ("Building a Rube Goldberg Chain Reaction Machine", "intermediate", 40, ["assorted household objects", "dominoes", "marbles", "ramps"],
     "A Rube Goldberg machine chains together simple machines and energy transfers to accomplish a simple task in a complex way.",
     ["chain reaction", "energy transfer", "simple machines"], "A Rube Goldberg machine primarily demonstrates:", ["A single simple machine", "A chain of energy transfers between simple machines", "Electrical circuits only", "Chemical reactions only"], 1),
    ("Testing Bridge Truss Designs (Beam vs Arch vs Truss)", "advanced", 35, ["craft sticks", "glue", "weights", "different design plans"],
     "Different bridge designs (beam, arch, truss) distribute compression and tension differently, affecting maximum load capacity.",
     ["bridge design", "compression", "tension"], "An arch bridge primarily works by directing forces into:", ["Tension only", "Compression along the curve", "No forces at all", "Random directions"], 1),
    ("Building a Model Water Wheel", "intermediate", 30, ["small paper/plastic cups", "wheel/axle", "water source"],
     "A water wheel converts the kinetic energy of flowing water into rotational mechanical energy.",
     ["hydropower", "energy conversion", "rotational motion"], "A water wheel converts flowing water's energy into:", ["Chemical energy", "Rotational mechanical energy", "Light energy", "Nuclear energy"], 1),
    ("Insulation Material Testing", "beginner", 30, ["various insulation materials", "thermometers", "warm water", "cups"],
     "Materials with more trapped air (like foam or wool) generally insulate better, slowing heat transfer.",
     ["insulation", "heat transfer", "material properties"], "Good insulating materials generally:", ["Conduct heat quickly", "Slow down heat transfer", "Have no effect on temperature", "Only work with electricity"], 1),
    ("Building a Geodesic Dome Model", "advanced", 35, ["straws or dowels", "connectors", "string"],
     "Geodesic domes distribute structural stress evenly across a network of triangles, allowing strong, lightweight, large-span structures.",
     ["geodesic dome", "triangulation", "structural efficiency"], "Geodesic domes achieve strength with less material because they use:", ["Only vertical beams", "A network of triangles distributing stress", "Solid concrete walls", "No structural design at all"], 1),
    ("Designing a Better Mousetrap Car", "intermediate", 35, ["mousetrap", "wheels", "axle", "chassis materials"],
     "A mousetrap car converts the stored elastic energy of the trap's spring into kinetic energy that drives the wheels.",
     ["elastic energy", "kinetic energy", "vehicle design"], "A mousetrap car's motion comes from converting:", ["Battery power", "Spring elastic energy into kinetic energy", "Solar energy", "Wind energy"], 1),
]

ASTRONOMY = [
    ("Building a Scale Model of the Solar System", "beginner", 30, ["balls of various sizes", "long string or tape measure"],
     "A scale model reveals just how vast the distances between planets are compared to their sizes.",
     ["scale", "solar system", "planetary distance"], "A scale model of the solar system usually reveals that:", ["Planets are evenly spaced", "The distances between planets are enormous compared to their sizes", "All planets are the same size", "The sun is small compared to planets"], 1),
    ("Moon Phase Simulation with a Lamp and Ball", "beginner", 25, ["lamp", "small ball", "dark room"],
     "Moon phases result from the changing angle at which we view the sunlit half of the Moon as it orbits Earth.",
     ["moon phases", "orbit", "illumination angle"], "Moon phases are caused by:", ["The Moon changing shape", "The changing angle we see the sunlit Moon from", "Earth's shadow always covering the Moon", "The Moon turning on and off"], 1),
    ("Measuring Star Brightness (Magnitude)", "intermediate", 25, ["star charts", "clear night sky (or star app)"],
     "Apparent magnitude measures how bright a star appears from Earth; lower (or negative) numbers mean brighter stars.",
     ["magnitude", "star brightness", "observation"], "In the magnitude scale, a lower number means a star is:", ["Dimmer", "Brighter", "Farther away always", "Smaller"], 1),
    ("Modeling Solar and Lunar Eclipses", "intermediate", 25, ["lamp", "small and large balls"],
     "Eclipses occur when the Sun, Earth, and Moon align so one body's shadow falls on another.",
     ["eclipse", "alignment", "shadow"], "A solar eclipse happens when the Moon is positioned between:", ["Earth and the stars", "The Sun and Earth", "Two other planets", "Earth's shadow and the Moon"], 1),
    ("Tracking Sunspot Activity", "advanced", 30, ["solar viewing filter/projection method (never look directly at the sun)", "sketchpad"],
     "Sunspots are cooler, magnetically active regions on the Sun's surface that vary in number over an 11-year solar cycle.",
     ["sunspots", "solar cycle", "solar magnetism"], "Sunspots appear darker because they are:", ["Hotter than surrounding areas", "Cooler than surrounding areas", "Made of different material", "Actually holes in the sun"], 1),
    ("Building a Simple Reflecting Telescope Model", "advanced", 35, ["concave mirror", "small flat mirror", "eyepiece lens", "tube"],
     "Reflecting telescopes use a curved mirror to gather and focus light, avoiding some distortions of lens-based telescopes.",
     ["telescope", "reflection", "light gathering"], "A reflecting telescope primarily uses a curved:", ["Lens", "Mirror", "Prism", "Filter"], 1),
    ("Calculating Your Weight on Other Planets", "beginner", 20, ["calculator", "gravity ratio chart"],
     "Weight depends on the local gravitational acceleration, which varies by planet based on mass and radius.",
     ["gravity", "weight vs mass", "planetary comparison"], "Your weight changes on different planets because of differences in:", ["Your mass", "The planet's gravitational pull", "Air pressure", "Distance from the sun only"], 1),
    ("Constellation Mapping", "beginner", 25, ["star chart", "flashlight with red filter", "clear night sky"],
     "Constellations are patterns of stars as seen from Earth, historically used for navigation and storytelling.",
     ["constellations", "star patterns", "celestial navigation"], "Constellations are best described as:", ["Physically connected star groups", "Apparent patterns of stars as seen from Earth", "Planets", "Galaxies"], 1),
    ("Modeling the Earth's Tilt and Seasons", "intermediate", 25, ["globe", "lamp", "protractor"],
     "Earth's axial tilt (about 23.5 degrees) causes seasons by changing the angle and duration of sunlight received throughout the year.",
     ["axial tilt", "seasons", "solar angle"], "Earth's seasons are primarily caused by:", ["Changing distance from the Sun", "Earth's axial tilt", "The Moon's phases", "Solar flares"], 1),
    ("Estimating the Speed of Light with Jupiter's Moons", "advanced", 30, ["historical data tables", "calculator"],
     "Ole Rømer's historical method used timing variations in Io's eclipses to make the first estimate of light's finite speed.",
     ["speed of light", "historical astronomy", "Io eclipses"], "Rømer estimated light's speed using timing variations of:", ["Solar eclipses", "Io's eclipses behind Jupiter", "Meteor showers", "The Moon's phases"], 1),
    ("Building a Sundial", "beginner", 25, ["stick or gnomon", "flat surface", "compass"],
     "A sundial tracks time by the changing position of a shadow cast by the sun as Earth rotates.",
     ["sundial", "Earth rotation", "shadow tracking"], "A sundial measures time using the position of a:", ["Star", "Shadow cast by the sun", "Moon phase", "Planet"], 1),
    ("Comparing Planetary Orbital Periods (Kepler's Third Law)", "advanced", 30, ["orbital data table", "calculator", "graph paper"],
     "Kepler's third law relates a planet's orbital period to its distance from the sun: farther planets orbit more slowly.",
     ["Kepler's laws", "orbital period", "orbital distance"], "According to Kepler's third law, planets farther from the sun have:", ["Shorter orbital periods", "Longer orbital periods", "The same orbital period", "No orbital period"], 1),
    ("Identifying Craters and Impact Physics", "intermediate", 25, ["flour", "cocoa powder", "marbles of different sizes", "tray"],
     "Dropping objects into flour models how impact speed and size affect the size and shape of craters, similar to lunar/planetary cratering.",
     ["impact crater", "kinetic energy", "planetary geology"], "Larger or faster impacting objects generally create:", ["Smaller craters", "Larger craters", "No craters", "The same size crater always"], 1),
    ("Observing the International Space Station Pass", "beginner", 15, ["ISS tracking app or website", "clear sky", "compass"],
     "The ISS orbits Earth roughly every 90 minutes and is visible as a fast-moving bright point when it reflects sunlight at dawn/dusk.",
     ["satellite orbit", "low Earth orbit", "observation"], "The ISS is visible from the ground because it:", ["Emits its own light", "Reflects sunlight", "Is very close to the ground", "Glows from friction"], 1),
    ("Modeling Light Years and Cosmic Distance", "intermediate", 25, ["string", "scale conversion chart"],
     "A light-year measures distance (how far light travels in a year), not time, illustrating the vast scale of space.",
     ["light-year", "astronomical distance", "scale of universe"], "A light-year is a unit of:", ["Time", "Distance", "Brightness", "Mass"], 1),
    ("Exploring Exoplanet Detection (Transit Method)", "advanced", 30, ["flashlight", "small ball", "light sensor or light meter"],
     "The transit method detects exoplanets by measuring the tiny, periodic dimming of a star's light as a planet passes in front of it.",
     ["exoplanet", "transit method", "light curve"], "The transit method detects exoplanets by observing:", ["Radio signals", "Periodic dimming of starlight", "Direct photographs", "Gravitational waves only"], 1),
    ("Building a Model of the Phases of Venus", "advanced", 25, ["lamp", "small ball", "Earth reference point"],
     "Venus shows phases like the Moon because it orbits closer to the Sun than Earth, a key observation supporting the heliocentric model."
     , ["phases of Venus", "heliocentric model", "orbital geometry"], "Galileo's observation of Venus's phases supported the idea that:", ["Earth is the center of the solar system", "Venus (and planets) orbit the Sun, not Earth", "Venus has no atmosphere", "The Moon orbits Venus"], 1),
    ("Comparing Planetary Atmospheres", "intermediate", 25, ["data cards for each planet", "chart paper"],
     "Planetary atmospheres vary widely in composition and pressure, from Mercury's near-vacuum to Venus's crushing CO2 atmosphere.",
     ["atmosphere", "planetary comparison", "atmospheric composition"], "Which planet has an extremely thick, hot carbon dioxide atmosphere?", ["Mercury", "Venus", "Mars", "Neptune"], 1),
    ("Tracking the Path of the Sun Across the Sky", "beginner", 20, ["compass", "notebook", "clear days over a season"],
     "The Sun's path across the sky changes with the seasons due to Earth's axial tilt, affecting day length and sun angle.",
     ["solar path", "seasons", "day length"], "The Sun's path across the sky changes throughout the year because of:", ["The Sun moving", "Earth's axial tilt as it orbits", "Cloud cover", "The Moon's gravity"], 1),
    ("Building a Model Rocket and Studying Newton's Laws", "advanced", 40, ["model rocket kit (with adult supervision)", "launch site"],
     "Model rockets demonstrate Newton's third law (thrust) and laws of motion as they accelerate against gravity and air resistance.",
     ["rocketry", "thrust", "Newton's laws"], "A rocket accelerates upward because of:", ["Magnetism", "Thrust from expelled exhaust gases (Newton's third law)", "Wind", "Solar power"], 1),
]

MATHEMATICS = [
    ("Fibonacci Sequence in Nature", "beginner", 25, ["pinecones, sunflowers, or shells (real or pictures)", "notebook"],
     "The Fibonacci sequence (1,1,2,3,5,8...) appears in natural spiral patterns like sunflower seed heads and pinecones.",
     ["Fibonacci sequence", "patterns in nature", "ratio"], "The Fibonacci sequence is formed by:", ["Multiplying by 2 each time", "Adding the two previous numbers", "Squaring the previous number", "Random numbers"], 1),
    ("Exploring the Golden Ratio", "intermediate", 25, ["ruler", "various rectangular objects", "calculator"],
     "The golden ratio (approximately 1.618) appears in art, architecture, and nature as a proportion considered visually pleasing.",
     ["golden ratio", "proportion", "geometry"], "The golden ratio is approximately equal to:", ["3.14", "1.618", "2.718", "1.0"], 1),
    ("Probability with Dice and Coins", "beginner", 20, ["dice", "coins", "notebook"],
     "Repeated trials show experimental probability converging toward theoretical probability as sample size increases.",
     ["probability", "experimental vs theoretical", "sample size"], "As you roll a die more times, experimental probability tends to:", ["Move away from theoretical probability", "Converge toward theoretical probability", "Stay completely random", "Become impossible to predict"], 1),
    ("Tessellations and Geometric Tiling", "beginner", 25, ["graph paper", "colored pencils", "shape templates"],
     "Tessellations are patterns of shapes that fit together with no gaps or overlaps, using geometric transformations.",
     ["tessellation", "geometric transformation", "tiling"], "A tessellation is a pattern of shapes that:", ["Overlaps everywhere", "Fits together with no gaps or overlaps", "Only uses circles", "Cannot repeat"], 1),
    ("Measuring Pi with Circular Objects", "beginner", 25, ["various circular objects", "string", "ruler"],
     "Measuring circumference divided by diameter for many circles consistently approximates pi (≈3.14159), regardless of circle size.",
     ["pi", "circumference", "diameter ratio"], "Pi represents the ratio of a circle's circumference to its:", ["Radius", "Diameter", "Area", "Height"], 1),
    ("Building 3D Geometric Solids (Platonic Solids)", "intermediate", 30, ["cardstock", "scissors", "glue", "nets/templates"],
     "The five Platonic solids are the only convex polyhedra where every face is an identical regular polygon.",
     ["Platonic solids", "polyhedra", "geometry"], "How many Platonic solids exist?", ["3", "5", "10", "Infinite"], 1),
    ("Exploring Fractals (Sierpinski Triangle)", "advanced", 30, ["graph paper", "ruler", "colored pencils"],
     "Fractals are self-similar patterns that repeat at every scale, like the recursively-subdivided Sierpinski triangle.",
     ["fractal", "self-similarity", "recursion"], "A key property of fractals like the Sierpinski triangle is:", ["They have no pattern", "Self-similarity at every scale", "They are always circular", "They only exist in 3D"], 1),
    ("Statistics: Mean, Median, and Mode with Real Data", "beginner", 25, ["survey data or class measurements", "calculator"],
     "Mean, median, and mode are different measures of central tendency, each useful in different situations (e.g., median resists outliers).",
     ["mean", "median", "mode"], "Which statistical measure is least affected by extreme outliers?", ["Mean", "Median", "Range", "Sum"], 1),
    ("Graph Theory: Solving the Bridges of Königsberg", "advanced", 30, ["paper", "pencil", "map diagram"],
     "Euler's solution to the Königsberg bridge problem founded graph theory, showing a path exists only if 0 or 2 nodes have odd degree.",
     ["graph theory", "Euler path", "network"], "Euler's bridge problem became the foundation of which field of math?", ["Calculus", "Graph theory", "Algebra", "Trigonometry"], 1),
    ("Compound Interest and Exponential Growth", "intermediate", 25, ["calculator", "spreadsheet or graph paper"],
     "Compound interest grows exponentially because interest is earned on both principal and previously accumulated interest.",
     ["compound interest", "exponential growth", "finance math"], "Compound interest grows faster than simple interest because it's earned on:", ["Only the original principal", "Both principal and accumulated interest", "Nothing extra", "A fixed amount each year"], 1),
    ("Symmetry Hunt and Line/Rotational Symmetry", "beginner", 20, ["mirror", "various objects and shapes"],
     "Line symmetry means a shape mirrors across a line; rotational symmetry means it looks the same after a partial rotation.",
     ["symmetry", "line symmetry", "rotational symmetry"], "A shape with rotational symmetry looks the same after being:", ["Reflected only", "Rotated by some angle less than 360°", "Stretched", "Colored differently"], 1),
    ("Modeling Exponential Decay with M&Ms or Dice", "intermediate", 25, ["M&Ms or dice", "cup", "graph paper"],
     "Removing a fraction of items each round (like removing dice showing a certain number) models real exponential decay processes like radioactive decay.",
     ["exponential decay", "half-life", "modeling"], "This experiment (removing a fraction each round) models real-world:", ["Linear growth", "Exponential decay (e.g. radioactive decay)", "Constant values", "Random noise only"], 1),
    ("Angle Measurement and the Unit Circle", "intermediate", 25, ["protractor", "compass", "graph paper"],
     "The unit circle relates angles to sine and cosine values, forming the foundation of trigonometry.",
     ["unit circle", "trigonometry", "angle measurement"], "The unit circle has a radius of:", ["0", "1", "10", "Pi"], 1),
    ("Optimization: Maximizing Area with Fixed Perimeter", "advanced", 30, ["string", "graph paper", "calculator"],
     "Among all rectangles with a fixed perimeter, the square encloses the maximum possible area — an early example of optimization.",
     ["optimization", "area", "perimeter"], "Among rectangles with a fixed perimeter, which shape maximizes area?", ["A very thin rectangle", "A square", "A triangle", "It doesn't matter"], 1),
    ("Cryptography: Caesar Cipher Basics", "beginner", 25, ["paper", "pencil", "cipher wheel (optional)"],
     "A Caesar cipher shifts each letter by a fixed number of positions in the alphabet, an early form of encryption.",
     ["cryptography", "cipher", "encryption"], "A Caesar cipher encrypts a message by:", ["Reversing all letters", "Shifting each letter by a fixed number of positions", "Removing vowels", "Translating to another language"], 1),
    ("Modeling Population Growth with Logistic Curves", "advanced", 30, ["graph paper", "calculator", "sample data"],
     "Logistic growth models how populations grow exponentially at first, then level off as they approach a carrying capacity.",
     ["logistic growth", "carrying capacity", "population modeling"], "Logistic growth differs from simple exponential growth because it eventually:", ["Increases forever", "Levels off near a carrying capacity", "Decreases to zero", "Stays constant from the start"], 1),
    ("Building and Testing a Random Number Generator (Dice Simulation)", "intermediate", 25, ["dice", "spreadsheet or tally sheet"],
     "Repeated random trials build a distribution that should approximate the true (uniform) probability of each die outcome over many rolls.",
     ["randomness", "distribution", "law of large numbers"], "With enough dice rolls, each number's frequency should approach:", ["Zero", "An equal, uniform proportion", "Always the same single number", "A completely unpredictable pattern"], 1),
    ("The Mathematics of Music: Frequency Ratios", "intermediate", 25, ["tuning app or instrument", "calculator"],
     "Musical intervals correspond to simple frequency ratios (e.g., an octave is a 2:1 ratio), linking math and music.",
     ["frequency ratio", "musical intervals", "math in music"], "An octave corresponds to a frequency ratio of:", ["3:2", "2:1", "1:1", "5:4"], 1),
    ("Estimating Area Under a Curve (Intro Calculus)", "advanced", 30, ["graph paper", "ruler", "sample curve"],
     "Approximating area under a curve with rectangles (Riemann sums) introduces the core idea behind integral calculus.",
     ["Riemann sum", "integral calculus", "area approximation"], "Using many thin rectangles to approximate area under a curve is the basis of:", ["Algebra", "Integral calculus", "Statistics", "Geometry proofs"], 1),
    ("Game Theory: The Prisoner's Dilemma Simulation", "advanced", 30, ["payoff matrix handout", "partners to play rounds"],
     "The prisoner's dilemma shows how individually rational choices can lead to a worse collective outcome than cooperation.",
     ["game theory", "prisoner's dilemma", "strategic decision-making"], "The prisoner's dilemma illustrates that individually rational choices can lead to:", ["The best possible outcome for everyone", "A worse outcome than mutual cooperation", "No outcome at all", "Random results only"], 1),
]

ELECTRONICS = [
    ("Building a Basic LED Circuit", "beginner", 20, ["LED", "resistor", "battery", "breadboard", "wires"],
     "An LED only allows current to flow in one direction and requires a current-limiting resistor to avoid burning out.",
     ["LED", "resistor", "current"], "Why is a resistor needed in an LED circuit?", ["To add light", "To limit current and protect the LED", "To reverse polarity", "It's not needed"], 1),
    ("Series vs Parallel Resistors", "intermediate", 25, ["resistors", "multimeter", "battery", "breadboard"],
     "Resistors in series add directly; resistors in parallel combine to give a total resistance lower than any individual resistor.",
     ["resistance", "series circuit", "parallel circuit"], "Adding more resistors in parallel does what to total resistance?", ["Increases it", "Decreases it", "Has no effect", "Makes it infinite"], 1),
    ("Building a Simple Switch Circuit", "beginner", 15, ["switch", "LED or bulb", "battery", "wires"],
     "A switch completes or breaks a circuit, controlling whether current can flow to the load.",
     ["switch", "open circuit", "closed circuit"], "An open switch means the circuit is:", ["Complete and current flows", "Broken and current cannot flow", "Short-circuited", "Overloaded"], 1),
    ("Understanding Ohm's Law with a Multimeter", "intermediate", 25, ["resistors", "battery", "multimeter"],
     "Ohm's law (V = IR) relates voltage, current, and resistance, letting you predict or measure any one from the other two.",
     ["Ohm's law", "voltage", "current", "resistance"], "Ohm's law states that voltage equals:", ["Current divided by resistance", "Current multiplied by resistance", "Resistance divided by current", "Current plus resistance"], 1),
    ("Building a Simple Alarm Circuit", "intermediate", 25, ["buzzer", "switch or sensor", "battery", "wires"],
     "An alarm circuit completes when a sensor or switch closes, allowing current to activate a buzzer or light.",
     ["sensor circuit", "buzzer", "trigger"], "In this alarm circuit, the buzzer activates when the circuit becomes:", ["Open", "Closed/complete", "Reversed", "Overloaded"], 1),
    ("Transistor as a Switch", "advanced", 30, ["transistor", "resistors", "LED", "battery"],
     "A transistor can act as an electronically controlled switch, letting a small control current switch a larger current on or off.",
     ["transistor", "amplification", "switching"], "A transistor used as a switch is controlled by:", ["Light only", "A small control current/voltage", "Magnetism", "Sound waves"], 1),
    ("Building a Simple AM Radio Receiver", "advanced", 35, ["diode", "coil", "capacitor", "earphone", "long wire antenna"],
     "A crystal radio uses a diode to demodulate AM radio signals, extracting the audio without needing a power source.",
     ["radio", "demodulation", "diode"], "A crystal radio needs no battery because it:", ["Uses solar power", "Extracts energy from the received radio wave itself", "Runs on static electricity", "Doesn't actually work"], 1),
    ("Capacitor Charge and Discharge Timing", "advanced", 25, ["capacitor", "resistor", "LED", "battery", "stopwatch"],
     "A capacitor stores charge and releases it over time; larger resistance or capacitance slows the charge/discharge rate.",
     ["capacitor", "RC time constant", "charge/discharge"], "Increasing resistance in an RC circuit does what to charge time?", ["Speeds it up", "Slows it down", "Has no effect", "Stops it completely"], 1),
    ("Building a Simple Metal Detector", "advanced", 30, ["coil of wire", "oscillator circuit or AM radio", "battery"],
     "A metal detector uses electromagnetic induction: a changing magnetic field induces currents in nearby metal, which can be detected.",
     ["electromagnetic induction", "metal detection", "coil"], "Metal detectors work using the principle of:", ["Sound waves", "Electromagnetic induction", "Light reflection", "Gravity"], 1),
    ("Photoresistor Light Sensor Circuit", "intermediate", 25, ["photoresistor (LDR)", "resistor", "LED", "battery"],
     "A photoresistor's resistance changes with light level, letting a circuit respond automatically to darkness or brightness.",
     ["photoresistor", "light sensor", "variable resistance"], "A photoresistor's resistance changes based on:", ["Temperature only", "Light level", "Sound", "Humidity"], 1),
    ("Building a Simple Solar-Powered Circuit", "intermediate", 25, ["small solar panel", "LED or small motor", "wires"],
     "A photovoltaic cell converts light energy directly into electrical energy via the photovoltaic effect.",
     ["photovoltaic effect", "solar cell", "energy conversion"], "A solar cell converts what kind of energy into electricity?", ["Chemical", "Light", "Sound", "Mechanical"], 1),
    ("555 Timer LED Blinker Circuit", "advanced", 35, ["555 timer IC", "resistors", "capacitor", "LED", "battery"],
     "A 555 timer IC in astable mode repeatedly charges and discharges a capacitor to produce a steady blinking or pulsing output.",
     ["555 timer", "astable circuit", "oscillation"], "A 555 timer in astable mode produces a:", ["Single one-time pulse", "Continuously repeating (oscillating) output", "Constant unchanging voltage", "Random signal"], 1),
    ("Building a Simple Morse Code Buzzer", "beginner", 20, ["buzzer", "push button", "battery", "wires"],
     "A push-button circuit lets you manually key on and off a buzzer to transmit patterns like Morse code.",
     ["Morse code", "push-button circuit", "signal encoding"], "Morse code encodes letters using patterns of:", ["Colors", "Short and long signals (dots and dashes)", "Numbers only", "Musical notes"], 1),
    ("Exploring Diodes and Rectification", "advanced", 30, ["diode", "AC source (transformer, adult supervision)", "multimeter", "resistor"],
     "A diode allows current in only one direction, converting alternating current (AC) into pulsing direct current (DC) — rectification.",
     ["diode", "rectification", "AC to DC"], "A diode converts AC to DC through a process called:", ["Amplification", "Rectification", "Induction", "Oscillation"], 1),
    ("Building a Simple Theremin-Style Pitch Circuit", "advanced", 30, ["oscillator circuit or simple synth kit", "speaker", "antenna wire"],
     "Some electronic pitch instruments change frequency based on proximity to a sensor, translating hand distance into sound frequency.",
     ["oscillator", "frequency modulation", "proximity sensing"], "A theremin-style circuit changes pitch based on:", ["Volume only", "Hand proximity to an antenna/sensor", "Battery level", "Room temperature only"], 1),
    ("Measuring Voltage Drop Across Components", "intermediate", 25, ["resistors", "battery", "multimeter", "breadboard"],
     "Voltage drops across each component in a series circuit, with the sum of all drops equaling the total supply voltage.",
     ["voltage drop", "series circuit", "Kirchhoff's voltage law"], "In a series circuit, the sum of all voltage drops equals:", ["Zero", "The total supply voltage", "The total resistance", "The total current"], 1),
    ("Building a Simple FM Bug Detector Circuit", "advanced", 30, ["RF detector diode", "coil", "meter or LED indicator"],
     "Simple RF detector circuits can indicate the presence of nearby radio-frequency transmissions by rectifying and measuring induced signals.",
     ["radio frequency", "RF detection", "signal induction"], "An RF detector circuit responds to:", ["Visible light", "Radio-frequency electromagnetic signals", "Sound waves", "Magnetism from permanent magnets only"], 1),
    ("Understanding Short Circuits Safely", "beginner", 20, ["low-voltage battery", "wire", "fuse or resistor (for safety)", "multimeter"],
     "A short circuit provides a very low-resistance path, causing dangerously high current — this is why fuses and circuit breakers exist.",
     ["short circuit", "fuse", "overcurrent protection"], "A fuse protects a circuit by:", ["Increasing current", "Breaking the circuit when current gets too high", "Adding resistance permanently", "Storing extra charge"], 1),
    ("Building a Simple Data Logging Thermometer", "advanced", 35, ["thermistor", "microcontroller or multimeter", "resistor"],
     "A thermistor's resistance changes predictably with temperature, allowing it to be used as an electronic temperature sensor.",
     ["thermistor", "temperature sensing", "data logging"], "A thermistor is a sensor whose resistance changes with:", ["Light", "Temperature", "Sound", "Pressure"], 1),
    ("Building a Simple Joule Thief Circuit", "advanced", 30, ["transistor", "toroid coil", "resistor", "LED", "near-dead battery"],
     "A joule thief boosts a low 'dead' battery voltage using rapid switching and inductive kick, enough to still light an LED.",
     ["voltage boost", "inductor", "joule thief"], "A joule thief circuit is notable for being able to:", ["Charge a battery instantly", "Light an LED using a nearly dead battery", "Generate unlimited power", "Work without any battery at all"], 1),
]

RENEWABLE_ENERGY = [
    ("Building a Mini Solar Car", "intermediate", 30, ["small solar panel", "small motor", "wheels", "chassis"],
     "A solar car directly converts sunlight into electrical energy via the photovoltaic effect to power a motor.",
     ["solar energy", "photovoltaic effect", "energy conversion"], "A solar panel converts light energy directly into:", ["Heat only", "Electrical energy", "Sound", "Chemical energy"], 1),
    ("Building a Simple Wind Turbine Generator", "intermediate", 30, ["small DC motor (as generator)", "blades", "LED", "fan or wind source"],
     "A wind turbine converts the kinetic energy of moving air into rotational energy, which a generator converts to electricity.",
     ["wind energy", "generator", "kinetic to electrical conversion"], "A wind turbine generator converts wind's kinetic energy into:", ["Heat", "Electrical energy", "Light directly", "Chemical energy"], 1),
    ("Solar Oven Efficiency Testing", "beginner", 35, ["pizza box solar oven", "thermometer", "food/water to heat"],
     "Reflective surfaces and insulation increase how much solar energy a solar oven captures and retains as heat.",
     ["solar thermal energy", "insulation", "reflection"], "A solar oven's efficiency improves mainly with better:", ["Reflectivity and insulation", "Color of food", "Time of day only", "Wind speed"], 1),
    ("Building a Simple Hydroelectric Generator Model", "advanced", 35, ["water wheel", "small DC motor/generator", "water source", "LED"],
     "Hydroelectric power converts the kinetic energy of falling or flowing water into electricity via a turbine-generator system.",
     ["hydropower", "turbine", "generator"], "Hydroelectric power primarily harnesses the energy of:", ["Wind", "Flowing or falling water", "Sunlight", "Underground heat"], 1),
    ("Comparing Solar Panel Angles and Output", "intermediate", 30, ["small solar panel", "multimeter", "protractor", "light source"],
     "Solar panels generally produce maximum power when oriented perpendicular to incoming sunlight.",
     ["solar angle", "photovoltaic output", "optimization"], "A solar panel typically produces the most power when facing:", ["Away from the light source", "Perpendicular (directly facing) the light source", "Parallel to the light source", "It doesn't matter"], 1),
    ("Building a Biogas Model (Anaerobic Digestion Concept)", "advanced", 30, ["balloon", "bottle", "organic waste/yeast+sugar model", "warm water"],
     "Anaerobic digestion by microbes breaks down organic waste, producing biogas (mostly methane) as a renewable energy source.",
     ["biogas", "anaerobic digestion", "methane"], "Biogas is primarily composed of which gas?", ["Oxygen", "Methane", "Helium", "Nitrogen"], 1),
    ("Geothermal Energy Concept Model", "intermediate", 25, ["hot water source", "tubing", "small turbine/fan model"],
     "Geothermal energy taps heat from within the Earth, often using steam or hot water to spin turbines and generate electricity.",
     ["geothermal energy", "Earth's heat", "steam turbine"], "Geothermal power plants primarily use heat from:", ["The Sun", "Within the Earth", "Ocean currents", "Wind"], 1),
    ("Building a Simple Piezoelectric Generator", "advanced", 30, ["piezoelectric disc", "LED", "wires", "pressure source"],
     "Piezoelectric materials generate a small voltage when mechanically stressed or vibrated, converting mechanical energy to electricity.",
     ["piezoelectric effect", "mechanical energy", "voltage generation"], "The piezoelectric effect generates electricity from:", ["Light", "Mechanical stress or vibration", "Heat only", "Chemical reactions"], 1),
    ("Measuring Energy Output of Different Renewable Sources", "advanced", 35, ["solar panel", "small wind turbine", "multimeter", "light and fan sources"],
     "Comparing voltage/current output under controlled conditions lets you evaluate the relative efficiency of different renewable energy setups.",
     ["renewable energy comparison", "efficiency", "power measurement"], "Comparing renewable energy sources under controlled conditions helps evaluate their:", ["Color", "Relative efficiency and output", "Cost only", "Popularity"], 1),
    ("Building a Solar Water Heater Model", "intermediate", 30, ["black tubing/container", "clear cover", "water", "thermometer"],
     "Dark surfaces absorb more solar radiation, and a clear cover traps heat via the greenhouse effect, raising water temperature.",
     ["solar thermal", "heat absorption", "greenhouse effect"], "A solar water heater warms water mainly because dark surfaces:", ["Reflect all sunlight", "Absorb solar radiation as heat", "Block sunlight", "Cool the water"], 1),
    ("Exploring Energy Storage: Simple Battery vs Capacitor", "advanced", 30, ["battery", "capacitor", "LED", "multimeter"],
     "Batteries store energy chemically and release it steadily; capacitors store energy electrostatically and can release it very quickly.",
     ["energy storage", "battery", "capacitor"], "Compared to a capacitor, a battery generally:", ["Releases energy much faster", "Stores energy chemically and releases it more steadily", "Cannot store any energy", "Only works with solar panels"], 1),
    ("Calculating a Home's Potential Solar Energy Savings", "advanced", 30, ["local sunlight hour data", "calculator", "sample energy bill"],
     "Estimating solar savings involves multiplying panel wattage, sunlight hours, and local electricity rates to estimate output value.",
     ["solar economics", "energy calculation", "cost-benefit"], "Estimating solar savings requires knowing panel wattage, sunlight hours, and:", ["The color of the roof", "Local electricity rates", "The homeowner's age", "The size of the garage"], 1),
    ("Building a Simple Tidal Energy Model", "advanced", 30, ["small water wheel or turbine", "basin", "manual wave/tide simulation"],
     "Tidal energy captures the kinetic and potential energy of rising and falling tides to generate electricity, similar to hydropower.",
     ["tidal energy", "renewable energy", "turbine"], "Tidal energy systems generate power from:", ["Wind", "The rise and fall of ocean tides", "Sunlight", "Underground heat"], 1),
    ("Exploring Energy Efficiency: LED vs Incandescent Bulbs", "beginner", 20, ["LED bulb", "incandescent bulb", "thermometer", "wattmeter (optional)"],
     "LEDs convert a much higher percentage of electrical energy into light (rather than wasted heat) compared to incandescent bulbs.",
     ["energy efficiency", "LED", "incandescent"], "LED bulbs are more energy-efficient mainly because they:", ["Produce more heat", "Waste less energy as heat and more as light", "Use more electricity", "Last a shorter time"], 1),
    ("Building a Small-Scale Biofuel Demonstration", "advanced", 30, ["vegetable oil", "lye and methanol (adult supervision)", "small burner"],
     "Biodiesel is produced through transesterification, converting vegetable oils or fats into a fuel that can substitute for diesel.",
     ["biofuel", "transesterification", "renewable fuel"], "Biodiesel is produced from vegetable oils through a process called:", ["Distillation", "Transesterification", "Fermentation", "Electrolysis"], 1),
    ("Investigating Passive Solar Home Design", "intermediate", 25, ["model house", "window placement variations", "thermometer", "lamp"],
     "Passive solar design uses window placement, thermal mass, and insulation to naturally heat and cool buildings without mechanical systems.",
     ["passive solar design", "thermal mass", "building efficiency"], "Passive solar design reduces energy use by using:", ["Only air conditioning", "Window placement, thermal mass, and insulation", "Extra electric heaters", "Artificial lighting"], 1),
    ("Building a Simple Micro-Hydro Turbine", "advanced", 35, ["small turbine/pinwheel", "generator/motor", "water flow source", "LED"],
     "Micro-hydro systems generate small-scale electricity from local streams or flowing water, useful for remote or off-grid power.",
     ["micro-hydro", "off-grid power", "small-scale generation"], "Micro-hydro systems are especially useful for providing power in:", ["Large cities only", "Remote or off-grid locations near flowing water", "Deserts with no water", "Space stations"], 1),
    ("Exploring the Carbon Footprint of Energy Sources", "intermediate", 25, ["data cards for different energy sources", "calculator"],
     "Comparing lifecycle carbon emissions per unit of energy reveals how renewable sources generally produce far less CO2 than fossil fuels.",
     ["carbon footprint", "emissions comparison", "energy sources"], "Compared to fossil fuels, most renewable energy sources have:", ["Much higher carbon emissions", "Much lower lifecycle carbon emissions", "Exactly the same emissions", "No measurable emissions difference"], 1),
    ("Building a Combined Solar-Wind Hybrid Charger", "advanced", 35, ["small solar panel", "small wind turbine", "diodes", "rechargeable battery"],
     "Hybrid renewable systems combine multiple sources so power generation continues even when one source (e.g. sun or wind) is unavailable.",
     ["hybrid system", "renewable reliability", "combined generation"], "A hybrid solar-wind system is useful mainly because it:", ["Doubles the cost for no benefit", "Keeps generating power even if one source is unavailable", "Only works at night", "Eliminates the need for batteries"], 1),
    ("Modeling Energy Payback Time for Solar Panels", "advanced", 30, ["manufacturing energy data", "annual output data", "calculator"],
     "Energy payback time estimates how long a solar panel must operate to generate as much energy as was used to manufacture it.",
     ["energy payback time", "lifecycle analysis", "solar manufacturing"], "Energy payback time for a solar panel measures how long until it:", ["Breaks down", "Generates as much energy as it took to manufacture it", "Needs replacing", "Becomes profitable in dollars"], 1),
]

DISCIPLINE_TOPICS = {
    "physics": PHYSICS,
    "chemistry": CHEMISTRY,
    "biology": BIOLOGY,
    "engineering": ENGINEERING,
    "astronomy": ASTRONOMY,
    "mathematics": MATHEMATICS,
    "electronics": ELECTRONICS,
    "renewable_energy": RENEWABLE_ENERGY,
}


def build_experiment(discipline: str, index: int, item: tuple) -> dict:
    title, difficulty, duration, materials, core_idea, key_concepts, quiz_q, quiz_opts, answer_idx = item
    exp_id = f"{discipline}_{index:03d}"
    steps = [
        f"Gather your materials: {', '.join(materials)}.",
        f"Set up the experiment and make an initial prediction about what will happen.",
        f"Carry out the activity carefully, observing closely.",
        f"Record what you observe and compare it to your prediction.",
    ]
    return {
        "id": exp_id,
        "title": title,
        "grade_range": "6-M2 (adjust depth to level)",
        "difficulty": difficulty,
        "duration_mins": duration,
        "materials": materials,
        "steps": steps,
        "explanation": core_idea,
        "key_concepts": key_concepts,
        "quiz": [{"question": quiz_q, "options": quiz_opts, "answer": answer_idx}],
        "video": "https://www.youtube.com/results?search_query=" + quote_plus(f"{title} experiment demonstration"),
    }


def main() -> None:
    with open(STEM_PATH, encoding="utf-8") as f:
        data = json.load(f)

    for discipline, topics in DISCIPLINE_TOPICS.items():
        existing = data["disciplines"][discipline].get("experiments", [])
        # Add a video link to every existing experiment that doesn't have one.
        for exp in existing:
            exp.setdefault("video", yt(f"{exp['title']} experiment demonstration"))

        existing_titles = {e["title"] for e in existing}
        new_experiments = [
            build_experiment(discipline, i + 1, item)
            for i, item in enumerate(topics)
            if item[0] not in existing_titles
        ]
        data["disciplines"][discipline]["experiments"] = existing + new_experiments
        total = len(data["disciplines"][discipline]["experiments"])
        print(f"{discipline}: {len(existing)} existing + {len(new_experiments)} new = {total} total")

    with open(STEM_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    main()
