#!/usr/bin/env python3
"""Populate the "Science & Innovation" biography category with real,
verified scientists and inventors. Facts are drawn from well-established
public knowledge (birth/death dates, prizes, discoveries, publications);
see _biography_engine.py for the no-fabrication template approach.

Re-run after editing:
    python3 backend/scripts/generate_biographies_science.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _biography_engine import upsert_section  # noqa: E402

PEOPLE = [
    dict(
        id="marie_curie", name="Marie Curie", years="1867-1934", nationality="Polish-French",
        field="physicist and chemist", wiki_title="Marie Curie",
        significance="she was the first person to win Nobel Prizes in two different sciences, Physics in 1903 and Chemistry in 1911",
        facts=[
            "Marie Curie was born Maria Sklodowska in Warsaw, Poland, in 1867, at a time when Polish universities did not admit women",
            "She moved to Paris in 1891 to study at the Sorbonne, where she earned degrees in physics and mathematics",
            "Together with her husband Pierre Curie, she discovered the elements polonium and radium in 1898",
            "She coined the term radioactivity to describe the phenomenon she and Pierre studied",
            "In 1911 she won a second Nobel Prize, this time in Chemistry, for isolating pure radium",
            "During World War I she developed mobile X-ray units, known as petites Curies, to help treat wounded soldiers",
            "She died in 1934 of aplastic anemia, a condition almost certainly caused by her prolonged exposure to radiation",
        ], related_subjects=["Physics", "Chemistry", "Science"],
    ),
    dict(
        id="albert_einstein", name="Albert Einstein", years="1879-1955", nationality="German-American",
        field="theoretical physicist", wiki_title="Albert Einstein",
        significance="he developed the theory of relativity, one of the two pillars of modern physics, and won the 1921 Nobel Prize in Physics",
        facts=[
            "Albert Einstein was born in Ulm, Germany, in 1879, and showed an early fascination with a compass his father gave him",
            "In 1905, often called his 'miracle year', he published four papers including special relativity and E=mc^2",
            "His 1915 general theory of relativity redefined gravity as the curvature of spacetime",
            "He won the 1921 Nobel Prize in Physics specifically for his explanation of the photoelectric effect",
            "A 1919 solar eclipse expedition led by Arthur Eddington confirmed his prediction that light bends around the sun",
            "He emigrated to the United States in 1933 after the Nazi rise to power in Germany, and joined Princeton's Institute for Advanced Study",
            "He signed the 1939 letter to President Roosevelt warning about the possibility of nuclear weapons, though he never worked on the Manhattan Project",
        ], related_subjects=["Physics", "Science"],
    ),
    dict(
        id="isaac_newton", name="Isaac Newton", years="1643-1727", nationality="English",
        field="physicist and mathematician", wiki_title="Isaac Newton",
        significance="his 1687 book Philosophiae Naturalis Principia Mathematica laid out the laws of motion and universal gravitation that governed physics for over two centuries",
        facts=[
            "Isaac Newton was born in Woolsthorpe, England, in 1643, the same year Galileo died",
            "During 1665-1666, when Cambridge University closed due to plague, he developed early ideas on calculus, optics, and gravitation at home",
            "His 1687 Principia Mathematica formulated the three laws of motion and the law of universal gravitation",
            "He built the first practical reflecting telescope in 1668, which used mirrors instead of lenses",
            "He independently developed calculus around the same time as German mathematician Gottfried Leibniz, leading to a famous priority dispute",
            "He served as Warden and later Master of the Royal Mint, where he pursued counterfeiters",
            "He was president of the Royal Society from 1703 until his death in 1727",
        ], related_subjects=["Physics", "Math", "Science"],
    ),
    dict(
        id="charles_darwin", name="Charles Darwin", years="1809-1882", nationality="English",
        field="naturalist and biologist", wiki_title="Charles Darwin",
        significance="his theory of evolution by natural selection, published in On the Origin of Species in 1859, transformed the study of biology",
        facts=[
            "Charles Darwin was born in Shrewsbury, England, in 1809 into a wealthy, well-connected family",
            "From 1831 to 1836 he served as the naturalist aboard HMS Beagle on a voyage around the world",
            "His observations of finches and tortoises on the Galapagos Islands were key evidence for his later theory",
            "He waited over 20 years after returning from the voyage before publishing his ideas, partly out of caution about the controversy they would cause",
            "He published On the Origin of Species in 1859, introducing natural selection as the mechanism of evolution",
            "He and naturalist Alfred Russel Wallace had independently arrived at similar theories, and jointly presented their ideas in 1858",
            "He is buried in Westminster Abbey in London, near Isaac Newton",
        ], related_subjects=["Biology", "Science"],
    ),
    dict(
        id="nikola_tesla", name="Nikola Tesla", years="1856-1943", nationality="Serbian-American",
        field="inventor and electrical engineer", wiki_title="Nikola Tesla",
        significance="his work on alternating current (AC) electrical systems became the foundation of the modern power grid",
        facts=[
            "Nikola Tesla was born in 1856 in Smiljan, in what is now Croatia, then part of the Austrian Empire",
            "He emigrated to the United States in 1884 and briefly worked for Thomas Edison before the two became rivals",
            "He held patents on the alternating current induction motor and polyphase AC power system, licensed by George Westinghouse",
            "The Westinghouse-Tesla AC system won the 'War of Currents' against Edison's direct current system in the 1890s",
            "He demonstrated wireless transmission of energy and built the Wardenclyffe Tower on Long Island as an ambitious wireless communication project, though it was never completed due to funding problems",
            "The SI unit of magnetic flux density, the tesla, is named in his honor",
            "He died in New York City in 1943, having spent his final years largely in isolation",
        ], related_subjects=["Physics", "ICT & Computer Science", "Science"],
    ),
    dict(
        id="ada_lovelace", name="Ada Lovelace", years="1815-1852", nationality="English",
        field="mathematician and writer", wiki_title="Ada Lovelace",
        significance="her notes on Charles Babbage's proposed Analytical Engine included what is widely regarded as the first published computer algorithm, making her the first computer programmer",
        facts=[
            "Ada Lovelace was born Augusta Ada Byron in 1815, the only legitimate child of the poet Lord Byron",
            "Her mother, Annabella Milbanke, insisted on a rigorous education in mathematics for Ada, unusual for a woman of that era",
            "She began corresponding with mathematician and inventor Charles Babbage about his proposed Analytical Engine in the 1830s",
            "In 1843 she translated an Italian article about the Analytical Engine and added her own extensive notes, three times longer than the original text",
            "Her Note G described a method for the Analytical Engine to compute Bernoulli numbers, now considered the first published algorithm intended for a computing machine",
            "She predicted that such a machine could eventually manipulate more than just numbers, including music and other symbolic content",
            "The Ada programming language, developed for the US Department of Defense in the 1980s, was named in her honor",
        ], related_subjects=["ICT & Computer Science", "Math"],
    ),
    dict(
        id="alan_turing", name="Alan Turing", years="1912-1954", nationality="English",
        field="mathematician and computer scientist", wiki_title="Alan Turing",
        significance="his 1936 concept of a universal computing machine laid the theoretical foundation for modern computer science, and his codebreaking work at Bletchley Park helped shorten World War II",
        facts=[
            "Alan Turing was born in London in 1912 and studied mathematics at King's College, Cambridge",
            "In 1936 he published a paper introducing the concept of a universal computing machine, now called a Turing machine",
            "During World War II he worked at Bletchley Park, where he led efforts to break the German Enigma cipher using an electromechanical device called the Bombe",
            "Historians estimate that the codebreaking work at Bletchley Park shortened the war in Europe by roughly two years",
            "In 1950 he proposed the Turing Test, a way of assessing whether a machine can exhibit intelligent behavior indistinguishable from a human",
            "In 1952 he was prosecuted under British law for homosexual acts, then a criminal offense, and was sentenced to chemical castration rather than prison",
            "He died in 1954, and in 2009 the British government issued a formal apology, followed by a posthumous royal pardon in 2013",
        ], related_subjects=["ICT & Computer Science", "Math"],
    ),
    dict(
        id="galileo_galilei", name="Galileo Galilei", years="1564-1642", nationality="Italian",
        field="astronomer and physicist", wiki_title="Galileo Galilei",
        significance="his telescopic observations provided strong evidence for the Copernican model of a sun-centered solar system, and he is often called the father of observational astronomy",
        facts=[
            "Galileo Galilei was born in Pisa, Italy, in 1564",
            "In 1609 he built one of the first telescopes for astronomical use, improving on earlier Dutch designs",
            "He discovered the four largest moons of Jupiter in 1610, now known as the Galilean moons",
            "He observed that Venus goes through phases like the Moon, evidence that Venus orbits the Sun rather than the Earth",
            "His 1632 book Dialogue Concerning the Two Chief World Systems argued for the Copernican, sun-centered model",
            "In 1633 the Roman Catholic Inquisition tried him for heresy and placed him under house arrest for the rest of his life",
            "In 1992, over 350 years later, the Vatican formally acknowledged that the Church's condemnation of Galileo had been an error",
        ], related_subjects=["Physics", "Science"],
    ),
    dict(
        id="stephen_hawking", name="Stephen Hawking", years="1942-2018", nationality="English",
        field="theoretical physicist", wiki_title="Stephen Hawking",
        significance="his work on black holes and cosmology, especially Hawking radiation, made him one of the most recognized scientists of his generation despite living with a severe motor neuron disease for over 50 years",
        facts=[
            "Stephen Hawking was born in Oxford, England, in 1942",
            "He was diagnosed with a form of motor neuron disease (ALS) at age 21 and doctors initially expected him to live only a few more years",
            "In 1974 he proposed that black holes emit radiation, now called Hawking radiation, showing black holes are not entirely black",
            "He held the Lucasian Professorship of Mathematics at Cambridge from 1979 to 2009, a position once held by Isaac Newton",
            "His 1988 book A Brief History of Time became an international bestseller, selling more than 10 million copies",
            "As his disease progressed, he lost the ability to speak and communicated using a speech-generating device controlled by small muscle movements",
            "He died in 2018, and his ashes were interred at Westminster Abbey between the graves of Isaac Newton and Charles Darwin",
        ], related_subjects=["Physics", "Science"],
    ),
    dict(
        id="jane_goodall", name="Jane Goodall", years="1934-present", nationality="English",
        field="primatologist and conservationist", wiki_title="Jane Goodall",
        significance="her decades-long study of wild chimpanzees at Gombe Stream in Tanzania, beginning in 1960, transformed scientific understanding of primate behavior and human-animal relationships",
        facts=[
            "Jane Goodall was born in London in 1934 and had no formal university degree in science when she first began her fieldwork",
            "In 1960, with support from paleoanthropologist Louis Leakey, she began observing wild chimpanzees at Gombe Stream in what is now Tanzania",
            "She was the first to document that chimpanzees make and use tools, stripping leaves from twigs to fish termites from mounds",
            "This discovery challenged the long-held scientific belief that only humans made and used tools",
            "She later earned a PhD from Cambridge University in 1965, one of very few people admitted without first completing an undergraduate degree",
            "In 1977 she founded the Jane Goodall Institute to support wildlife research, education, and conservation",
            "She has spent much of her later career traveling roughly 300 days a year advocating for conservation and animal welfare",
        ], related_subjects=["Biology", "Environmental Science"],
    ),
    dict(
        id="rosalind_franklin", name="Rosalind Franklin", years="1920-1958", nationality="English",
        field="chemist and X-ray crystallographer", wiki_title="Rosalind Franklin",
        significance="her X-ray diffraction images of DNA, especially the image known as Photo 51, were critical evidence used by James Watson and Francis Crick in determining the double-helix structure of DNA",
        facts=[
            "Rosalind Franklin was born in London in 1920 and studied natural sciences at Cambridge University",
            "She developed expertise in X-ray crystallography while working in Paris in the late 1940s",
            "At King's College London in 1952, she and her student Raymond Gosling produced Photo 51, a clear X-ray diffraction image of DNA",
            "That image was shown to James Watson without her knowledge or permission, and it strongly informed his and Francis Crick's 1953 double-helix model",
            "She also carried out important structural work on the tobacco mosaic virus and on coal and carbon",
            "She died of ovarian cancer in 1958 at age 37, before the 1962 Nobel Prize was awarded to Watson, Crick, and Maurice Wilkins for the DNA structure (Nobel Prizes are not awarded posthumously)",
            "Her contribution to the discovery of DNA's structure has since been widely reassessed and is now much more fully credited by historians of science",
        ], related_subjects=["Chemistry", "Biology", "Science"],
    ),
    dict(
        id="louis_pasteur", name="Louis Pasteur", years="1822-1895", nationality="French",
        field="chemist and microbiologist", wiki_title="Louis Pasteur",
        significance="his germ theory of disease and development of vaccines and pasteurization transformed medicine and food safety",
        facts=[
            "Louis Pasteur was born in Dole, France, in 1822",
            "His experiments in the 1860s disproved the theory of spontaneous generation, showing that microorganisms come from other microorganisms rather than arising spontaneously",
            "He developed the process later named pasteurization, using heat to kill harmful microorganisms in liquids like milk and wine",
            "He created vaccines for anthrax in 1881 and for rabies in 1885",
            "In 1885 he successfully treated a boy bitten by a rabid dog with his experimental rabies vaccine, saving the boy's life",
            "He founded the Pasteur Institute in Paris in 1887, which remains a major center for biomedical research today",
            "He died in 1895 near Paris, and is buried in a crypt beneath the Pasteur Institute",
        ], related_subjects=["Chemistry", "Biology", "Health Education"],
    ),
    dict(
        id="thomas_edison", name="Thomas Edison", years="1847-1931", nationality="American",
        field="inventor and businessman", wiki_title="Thomas Edison",
        significance="he held 1,093 US patents and developed practical technologies including the phonograph, the long-lasting incandescent light bulb, and early motion picture equipment",
        facts=[
            "Thomas Edison was born in Milan, Ohio, in 1847, and had little formal schooling, being largely taught by his mother",
            "He invented the phonograph in 1877, the first device able to both record and reproduce sound",
            "In 1879 he developed a practical, long-lasting incandescent light bulb using a carbonized bamboo filament",
            "He established Menlo Park, New Jersey, as the first industrial research laboratory, employing teams of researchers rather than working alone",
            "He built the Pearl Street Station in New York City in 1882, one of the first commercial electric power plants",
            "He was a strong advocate for direct current (DC) power and clashed publicly with Nikola Tesla and George Westinghouse's alternating current (AC) system in the 'War of Currents'",
            "He founded General Electric, which remains one of the largest companies in the world",
        ], related_subjects=["Physics", "Business Studies", "Science"],
    ),
    dict(
        id="katherine_johnson", name="Katherine Johnson", years="1918-2020", nationality="American",
        field="mathematician", wiki_title="Katherine Johnson",
        significance="her orbital trajectory calculations at NASA were essential to the success of the first American crewed spaceflights, including John Glenn's 1962 orbital mission",
        facts=[
            "Katherine Johnson was born in White Sulphur Springs, West Virginia, in 1918, and showed exceptional mathematical ability from an early age",
            "She graduated summa cum laude from West Virginia State College at age 18 with degrees in mathematics and French",
            "She joined the National Advisory Committee for Aeronautics (NACA), the predecessor of NASA, in 1953 as one of the 'human computers'",
            "She calculated the trajectory for Alan Shepard's 1961 flight, the first American human spaceflight",
            "Before his 1962 orbital flight, astronaut John Glenn specifically asked that Johnson personally verify the trajectory calculations produced by early electronic computers",
            "She also worked on trajectory calculations for the 1969 Apollo 11 mission that first landed astronauts on the Moon",
            "In 2015 President Barack Obama awarded her the Presidential Medal of Freedom, and NASA named a research facility after her in 2017",
        ], related_subjects=["Math", "Physics"],
    ),
    dict(
        id="james_watson_francis_crick", name="James Watson and Francis Crick", years="1928-present / 1916-2004", nationality="American / English",
        field="molecular biologists", wiki_title="Francis Crick",
        significance="in 1953 they proposed the double-helix structure of DNA, a discovery considered one of the most important in the history of biology",
        facts=[
            "James Watson, born in Chicago in 1928, and Francis Crick, born in Northampton, England, in 1916, met at Cambridge University's Cavendish Laboratory in 1951",
            "In 1953 they published a short paper in the journal Nature proposing that DNA has a double-helix structure",
            "Their model relied heavily on X-ray diffraction data, including the famous Photo 51 image produced by Rosalind Franklin and Raymond Gosling",
            "The double-helix structure explained how genetic information could be copied, since each strand serves as a template for a new complementary strand",
            "In 1962 Watson, Crick, and Maurice Wilkins shared the Nobel Prize in Physiology or Medicine for the discovery",
            "Watson later became director of the Cold Spring Harbor Laboratory and led the Human Genome Project in its early years",
            "Crick spent much of his later career at the Salk Institute in California researching the biological basis of consciousness",
        ], related_subjects=["Biology", "Science"],
    ),
    dict(
        id="grace_hopper", name="Grace Hopper", years="1906-1992", nationality="American",
        field="computer scientist and Navy rear admiral", wiki_title="Grace Hopper",
        significance="she pioneered machine-independent programming languages and developed the first compiler, laying groundwork for the COBOL programming language widely used in business computing",
        facts=[
            "Grace Hopper was born in New York City in 1906 and earned a PhD in mathematics from Yale University in 1934",
            "She joined the US Navy Reserve in 1943 during World War II and was assigned to work on the Harvard Mark I computer",
            "In 1952 she developed the first compiler, a program that translates human-readable code into machine code, called the A-0 System",
            "She championed the idea that programming languages should use English-like words rather than pure mathematical notation, an idea that shaped the design of COBOL in 1959",
            "She is often credited with popularizing the term 'debugging' after her team found an actual moth causing a malfunction in the Harvard Mark II computer in 1947",
            "She remained active in the Navy for decades, retiring in 1986 at age 79 as one of the oldest serving officers in the US Armed Forces",
            "In 2016 President Barack Obama posthumously awarded her the Presidential Medal of Freedom",
        ], related_subjects=["ICT & Computer Science", "Math"],
    ),
    dict(
        id="michael_faraday", name="Michael Faraday", years="1791-1867", nationality="English",
        field="physicist and chemist", wiki_title="Michael Faraday",
        significance="his discoveries in electromagnetism, including electromagnetic induction, made possible the electric motors and generators that power the modern world",
        facts=[
            "Michael Faraday was born in London in 1791 to a poor family and had little formal education",
            "He began his scientific career as a bookbinder's apprentice, reading the books he bound, before becoming a laboratory assistant to chemist Humphry Davy in 1813",
            "In 1821 he built the first device to demonstrate electromagnetic rotation, a precursor to the electric motor",
            "In 1831 he discovered electromagnetic induction, the principle that a changing magnetic field can generate an electric current, which underlies electric generators and transformers",
            "He introduced the concept of electric and magnetic fields, visualized using field lines, which became central to physics",
            "He gave the Royal Institution's Christmas Lectures for young people for many years, including his famous lecture series 'The Chemical History of a Candle'",
            "He declined a knighthood and twice declined the presidency of the Royal Society, preferring to remain 'plain Michael Faraday' to the end",
        ], related_subjects=["Physics", "Chemistry", "Science"],
    ),
    dict(
        id="tim_berners_lee", name="Tim Berners-Lee", years="1955-present", nationality="English",
        field="computer scientist", wiki_title="Tim Berners-Lee",
        significance="he invented the World Wide Web in 1989 while working at CERN, creating the system of hyperlinked documents that underlies most of the modern internet experience",
        facts=[
            "Tim Berners-Lee was born in London in 1955 to parents who both worked on the Ferranti Mark 1, one of the world's first commercial computers",
            "In 1989, while working at CERN, the European particle physics laboratory, he proposed a system for sharing information using hypertext",
            "In 1990 he built the first web browser, the first web server, and defined the core technologies HTML, HTTP, and URLs",
            "He insisted that the World Wide Web be given away royalty-free, rather than patented, so it could be adopted freely worldwide",
            "In 1994 he founded the World Wide Web Consortium (W3C) at MIT to develop open standards for the web",
            "He was knighted by Queen Elizabeth II in 2004 for his services to the global development of the internet",
            "In 2017 he won the Turing Award, often called the 'Nobel Prize of computing', for inventing the World Wide Web",
        ], related_subjects=["ICT & Computer Science"],
    ),
    dict(
        id="gregor_mendel", name="Gregor Mendel", years="1822-1884", nationality="Austrian (Moravian)",
        field="friar and botanist", wiki_title="Gregor Mendel",
        significance="his experiments breeding pea plants in a monastery garden established the basic laws of heredity, earning him recognition as the founder of modern genetics",
        facts=[
            "Gregor Mendel was born in 1822 in Heinzendorf, then part of the Austrian Empire, and entered the Augustinian monastery in Brno in 1843",
            "Between 1856 and 1863 he conducted breeding experiments on roughly 28,000 pea plants in the monastery garden",
            "He tracked traits such as seed shape and flower color across generations, identifying consistent numerical ratios",
            "In 1865 he presented his findings, describing what became known as the laws of segregation and independent assortment",
            "His work was largely ignored by the scientific community during his lifetime and was only rediscovered around 1900, 16 years after his death",
            "He later became abbot of his monastery, and administrative duties left him less time for further scientific research",
            "The basic unit of heredity that he studied would later be named the 'gene' by other scientists, building directly on his findings",
        ], related_subjects=["Biology", "Science"],
    ),
    dict(
        id="chien_shiung_wu", name="Chien-Shiung Wu", years="1912-1997", nationality="Chinese-American",
        field="experimental physicist", wiki_title="Chien-Shiung Wu",
        significance="her 1956 experiment disproved the long-held law of conservation of parity in physics, a discovery for which two male theorists who proposed the test, not Wu herself, won the 1957 Nobel Prize",
        facts=[
            "Chien-Shiung Wu was born in Liuhe, near Shanghai, China, in 1912, and moved to the United States in 1936 to pursue graduate study",
            "She earned her PhD in physics at the University of California, Berkeley, in 1940",
            "During World War II she worked on the Manhattan Project at Columbia University, helping develop the process for enriching uranium",
            "In 1956 physicists Tsung-Dao Lee and Chen-Ning Yang proposed that a physical law called conservation of parity might not hold for weak nuclear interactions, and asked Wu to test it experimentally",
            "Her 1956-1957 experiment, using cobalt-60 at extremely low temperatures, confirmed that parity is indeed violated in weak interactions, a landmark result in physics",
            "Lee and Yang won the 1957 Nobel Prize in Physics for the theoretical prediction, while Wu's crucial experimental confirmation was not recognized by the Nobel committee, a decision many physicists have since called an oversight",
            "She was the first woman to serve as president of the American Physical Society, in 1975",
        ], related_subjects=["Physics", "Science"],
    ),
    dict(
        id="charles_babbage", name="Charles Babbage", years="1791-1871", nationality="English",
        field="mathematician and mechanical engineer", wiki_title="Charles Babbage",
        significance="his designs for the Difference Engine and the Analytical Engine are considered early conceptual forerunners of the modern general-purpose computer",
        facts=[
            "Charles Babbage was born in London in 1791 and studied mathematics at Cambridge University",
            "In the 1820s he designed the Difference Engine, a mechanical calculator intended to automatically compute mathematical tables",
            "He never completed a full working Difference Engine in his lifetime due to funding and manufacturing challenges, though a working model was built by the Science Museum in London in 1991 using his original designs",
            "In the 1830s he conceived the Analytical Engine, a far more ambitious design featuring a processing unit, memory, and the ability to be programmed using punched cards",
            "The Analytical Engine's design anticipated key features of modern computers, including conditional branching and looping",
            "Ada Lovelace worked closely with Babbage and wrote extensive notes on the Analytical Engine, including what is considered the first published computer algorithm",
            "He held the Lucasian Professorship of Mathematics at Cambridge, the same chair later held by Stephen Hawking",
        ], related_subjects=["ICT & Computer Science", "Math"],
    ),
    dict(
        id="dmitri_mendeleev", name="Dmitri Mendeleev", years="1834-1907", nationality="Russian",
        field="chemist", wiki_title="Dmitri Mendeleev",
        significance="his 1869 periodic table organized the chemical elements by atomic weight and recurring properties, and correctly predicted the existence of several then-undiscovered elements",
        facts=[
            "Dmitri Mendeleev was born in Tobolsk, Siberia, in 1834, the youngest of a very large family",
            "In 1869 he published a periodic table arranging the 63 known elements by increasing atomic weight and recurring chemical properties",
            "He deliberately left gaps in his table for elements he believed had not yet been discovered",
            "He predicted the properties of these missing elements in advance, and elements such as gallium (1875), scandium (1879), and germanium (1886) were later discovered matching his predictions closely",
            "His table organized elements into groups based on similar chemical behavior, a structural principle still used in the periodic table today",
            "Element 101, mendelevium, was named in his honor by its discoverers in 1955",
            "He also contributed to Russian industry, studying petroleum production and helping establish standards for Russian vodka production",
        ], related_subjects=["Chemistry", "Science"],
    ),
    dict(
        id="carl_sagan", name="Carl Sagan", years="1934-1996", nationality="American",
        field="astronomer and science communicator", wiki_title="Carl Sagan",
        significance="his 1980 television series Cosmos brought astronomy and scientific thinking to hundreds of millions of viewers worldwide, making him one of the most influential science popularizers of the 20th century",
        facts=[
            "Carl Sagan was born in Brooklyn, New York, in 1934, and earned his PhD in astronomy and astrophysics from the University of Chicago in 1960",
            "He worked on NASA's Mariner, Viking, Voyager, and Galileo planetary exploration missions",
            "He helped design the Pioneer plaque and the Voyager Golden Record, physical messages attached to spacecraft intended for any intelligent life that might encounter them",
            "His 1980 television series Cosmos: A Personal Voyage was watched by an estimated 500 million people across 60 countries",
            "His accompanying book Cosmos spent 70 weeks on the New York Times bestseller list",
            "He was a co-founder of the Planetary Society in 1980, an organization promoting space exploration and the search for extraterrestrial life",
            "He was a vocal advocate for scientific skepticism and critical thinking, writing the 1995 book The Demon-Haunted World about distinguishing science from pseudoscience",
        ], related_subjects=["Physics", "Science"],
    ),
    dict(
        id="werner_heisenberg", name="Werner Heisenberg", years="1901-1976", nationality="German",
        field="theoretical physicist", wiki_title="Werner Heisenberg",
        significance="his 1927 uncertainty principle, a foundational result of quantum mechanics, established fundamental limits on how precisely certain pairs of physical properties can be known simultaneously",
        facts=[
            "Werner Heisenberg was born in Wurzburg, Germany, in 1901",
            "In 1925, at age 23, he developed matrix mechanics, one of the first complete formulations of quantum mechanics",
            "In 1927 he formulated the uncertainty principle, showing that the position and momentum of a particle cannot both be measured with arbitrary precision at the same time",
            "He won the Nobel Prize in Physics in 1932 for the creation of quantum mechanics",
            "During World War II he led Nazi Germany's nuclear research program, which ultimately failed to produce a nuclear weapon before the war ended",
            "Historians have debated for decades whether this failure was due to scientific miscalculation, resource shortages, or deliberate delay on Heisenberg's part",
            "After the war he helped rebuild German physics research and directed the Max Planck Institute for Physics",
        ], related_subjects=["Physics", "Science"],
    ),
    dict(
        id="barbara_mcclintock", name="Barbara McClintock", years="1902-1992", nationality="American",
        field="geneticist and cytogeneticist", wiki_title="Barbara McClintock",
        significance="her discovery of 'jumping genes', genetic elements that can move within a genome, won her a sole Nobel Prize in Physiology or Medicine in 1983 after decades of initial skepticism from the scientific community",
        facts=[
            "Barbara McClintock was born in Hartford, Connecticut, in 1902, and earned her PhD in botany from Cornell University in 1927",
            "She pioneered techniques for visualizing and studying maize (corn) chromosomes under a microscope",
            "In the 1940s and 1950s, through detailed study of maize kernel color patterns, she discovered transposable elements, segments of DNA that can move to different positions within a genome",
            "This finding challenged the prevailing view that genes were fixed in place, and was met with considerable skepticism from many geneticists at the time",
            "She largely stopped publishing on the topic in the 1950s after facing a lukewarm reception, though she continued her research quietly for decades",
            "By the 1970s and 1980s, advances in molecular biology confirmed that transposable elements exist across many organisms, including humans, vindicating her earlier work",
            "In 1983 she won the Nobel Prize in Physiology or Medicine alone, making her the first woman to win an unshared Nobel Prize in that category",
        ], related_subjects=["Biology", "Science"],
    ),
    dict(
        id="george_washington_carver", name="George Washington Carver", years="1864-1943", nationality="American",
        field="agricultural scientist and inventor", wiki_title="George Washington Carver",
        significance="his research on crop rotation and alternative uses for peanuts, sweet potatoes, and soybeans helped improve soil health and diversify agriculture across the American South",
        facts=[
            "George Washington Carver was born into slavery in Missouri around 1864, shortly before the end of the Civil War",
            "He became the first Black student, and later the first Black faculty member, at Iowa State Agricultural College",
            "In 1896 he joined the Tuskegee Institute in Alabama, at the invitation of educator Booker T. Washington, to lead its agriculture department",
            "He promoted crop rotation, encouraging farmers to plant nitrogen-fixing crops like peanuts and soybeans alongside cotton to restore depleted soil",
            "He developed hundreds of practical applications for peanuts, sweet potatoes, and other crops, including dyes, plastics, and food products, to help create new markets for Southern farmers",
            "He testified before the US Congress in 1921 on the industrial uses of peanuts, an unusual platform for a Black scientist at the time",
            "He was awarded the Roosevelt Medal in 1939 for his contributions to Southern agriculture",
        ], related_subjects=["Biology", "Environmental Science"],
    ),
    dict(
        id="edwin_hubble", name="Edwin Hubble", years="1889-1953", nationality="American",
        field="astronomer", wiki_title="Edwin Hubble",
        significance="his observations in the 1920s showed that the universe contains many galaxies beyond our own and that it is expanding, fundamentally reshaping cosmology",
        facts=[
            "Edwin Hubble was born in Marshfield, Missouri, in 1889, and initially trained as a lawyer before turning to astronomy",
            "In 1923, using the 100-inch Hooker Telescope at Mount Wilson Observatory, he identified a variable star in the Andromeda Nebula",
            "This observation proved that Andromeda was a separate galaxy far outside the Milky Way, not a nebula within it, vastly expanding the known scale of the universe",
            "In 1929 he formulated what is now called Hubble's Law, showing that distant galaxies are moving away from us at speeds proportional to their distance",
            "This finding provided key observational evidence for an expanding universe, later supporting the Big Bang theory",
            "He worked to classify galaxies by shape, developing a system known as the Hubble sequence still referenced today",
            "The Hubble Space Telescope, launched by NASA in 1990, is named in his honor",
        ], related_subjects=["Physics", "Science"],
    ),
    dict(
        id="jagadish_chandra_bose_science", name="Jagadish Chandra Bose", years="1858-1937", nationality="Indian (Bengali)",
        field="physicist and biologist", wiki_title="Jagadish Chandra Bose",
        significance="he conducted pioneering experiments in millimeter-wave radio technology and demonstrated that plants exhibit measurable responses to stimuli, bridging physics and biology",
        facts=[
            "Jagadish Chandra Bose was born in 1858 in Munshiganj, in the Bikrampur region of what is now Bangladesh",
            "He studied natural science at Cambridge University before returning to teach physics at Presidency College in Calcutta",
            "In 1895, a year before Guglielmo Marconi's public demonstration, Bose gave a public demonstration of wireless signaling using microwaves in Calcutta",
            "He invented the crescograph, a device to measure extremely small movements in plants in response to stimuli, providing early evidence of plant sensitivity",
            "He worked largely without patenting his radio wave research, believing scientific knowledge should be shared freely rather than commercialized",
            "He founded the Bose Institute in Calcutta in 1917, one of the first modern scientific research institutes in India",
            "He is regarded as a pioneer of radio science, and the crater Bose on the Moon is named in his honor",
        ], related_subjects=["Physics", "Biology", "Science"],
    ),
    dict(
        id="satyendra_nath_bose_science", name="Satyendra Nath Bose", years="1894-1974", nationality="Indian (Bengali)",
        field="physicist", wiki_title="Satyendra Nath Bose",
        significance="his 1924 work on the statistical behavior of light particles, developed in collaboration with Albert Einstein, laid the foundation for Bose-Einstein statistics and the class of particles now called bosons",
        facts=[
            "Satyendra Nath Bose was born in Calcutta in 1894 and showed exceptional mathematical talent from childhood",
            "In 1924 he sent Albert Einstein a paper deriving Planck's law of black-body radiation using a new statistical method, after it had been rejected by a European journal",
            "Einstein recognized the significance of the work, translated it into German himself, and helped get it published",
            "Einstein then extended Bose's method to atoms, leading to the prediction of what is now called Bose-Einstein condensate, a state of matter later confirmed experimentally in 1995",
            "The class of subatomic particles that follow this statistical behavior, including photons, were later named 'bosons' in his honor by physicist Paul Dirac",
            "Despite the significance of his contribution, Bose was never awarded a Nobel Prize, a fact many physicists and historians consider a notable oversight",
            "He remained largely based in India throughout his career, teaching at the University of Dhaka and later the University of Calcutta",
        ], related_subjects=["Physics", "Science"],
    ),
    dict(
        id="richard_feynman", name="Richard Feynman", years="1918-1988", nationality="American",
        field="theoretical physicist", wiki_title="Richard Feynman",
        significance="he developed Feynman diagrams, a simplified visual method for calculating particle interactions, contributing to quantum electrodynamics work that won him the 1965 Nobel Prize in Physics, and became widely known for his gift for explaining physics to general audiences",
        facts=[
            "Richard Feynman was born in Queens, New York, in 1918, and showed strong mathematical ability from a young age",
            "He worked as a young physicist on the Manhattan Project at Los Alamos during World War II, helping develop the atomic bomb",
            "He developed Feynman diagrams in the late 1940s, a visual shorthand for calculating how subatomic particles interact, which greatly simplified complex calculations in quantum electrodynamics",
            "He shared the 1965 Nobel Prize in Physics with Julian Schwinger and Sin-Itiro Tomonaga for their work on quantum electrodynamics",
            "He was renowned as an unusually gifted teacher, and his recorded 1961-1963 introductory physics lectures at Caltech were later published as The Feynman Lectures on Physics, still widely used today",
            "In 1986 he served on the presidential commission investigating the Space Shuttle Challenger disaster, and famously demonstrated on live television how a rubber O-ring seal became brittle in cold water, identifying the cause of the accident",
            "He died in 1988, and remains widely celebrated both for his scientific contributions and his ability to communicate complex physics to non-specialist audiences",
        ], related_subjects=["Physics", "Science"],
    ),
    dict(
        id="rachel_carson", name="Rachel Carson", years="1907-1964", nationality="American",
        field="marine biologist and writer", wiki_title="Rachel Carson",
        significance="her 1962 book Silent Spring documented the environmental harm caused by synthetic pesticides and is widely credited with helping launch the modern environmental movement",
        facts=[
            "Rachel Carson was born in Springdale, Pennsylvania, in 1907, and studied marine biology, earning a master's degree from Johns Hopkins University",
            "She worked for years as a scientist and editor for the US Bureau of Fisheries, later the US Fish and Wildlife Service",
            "Her earlier books, including The Sea Around Us (1951), were bestsellers that brought marine science to a wide general readership",
            "Her 1962 book Silent Spring presented detailed scientific evidence of the environmental and health harms caused by widespread pesticide use, particularly DDT",
            "The book faced fierce opposition from chemical industry groups, who challenged both her science and her credentials, though her research was later substantially validated",
            "Silent Spring is widely credited with contributing to the 1972 US ban on DDT and helping inspire the creation of the US Environmental Protection Agency in 1970",
            "She died of cancer in 1964, just two years after Silent Spring's publication, but its influence on environmental policy and public awareness continued to grow for decades afterward",
        ], related_subjects=["Environmental Science", "Biology"],
    ),
    dict(
        id="john_von_neumann", name="John von Neumann", years="1903-1957", nationality="Hungarian-American",
        field="mathematician and physicist", wiki_title="John von Neumann",
        significance="a mathematical polymath whose work spanned computer architecture, game theory, and quantum physics, he designed the foundational 'von Neumann architecture' still used in most computers today",
        facts=[
            "John von Neumann was born in Budapest, Hungary, in 1903, and displayed extraordinary mathematical ability from early childhood",
            "He earned a doctorate in mathematics at age 22 and worked across an unusually broad range of fields, including set theory, quantum mechanics, and economics",
            "He worked on the Manhattan Project during World War II, contributing to the mathematical modeling of the implosion mechanism used in the plutonium atomic bomb",
            "He described the 'von Neumann architecture' in 1945, a computer design storing both program instructions and data in the same memory, which remains the basic model used by most computers today",
            "He co-founded the field of game theory with economist Oskar Morgenstern, publishing the influential 1944 book Theory of Games and Economic Behavior",
            "He served on the US Atomic Energy Commission and advised the government on Cold War strategic and technological matters",
            "He died in 1957, and is widely regarded as one of the most versatile and influential mathematicians of the 20th century",
        ], related_subjects=["Math", "ICT & Computer Science", "Physics"],
    ),
    dict(
        id="mae_jemison", name="Mae Jemison", years="1956-present", nationality="American",
        field="physician and astronaut", wiki_title="Mae Jemison",
        significance="in 1992 she became the first Black woman to travel into space, flying aboard the Space Shuttle Endeavour as part of a NASA mission",
        facts=[
            "Mae Jemison was born in Decatur, Alabama, in 1956, and earned degrees in chemical engineering and medicine before joining NASA's astronaut program",
            "She worked as a physician with the Peace Corps in West Africa before being selected for NASA's astronaut training program in 1987",
            "On September 12, 1992, she flew aboard the Space Shuttle Endeavour as a mission specialist, becoming the first Black woman to travel into space",
            "During the eight-day mission she conducted experiments related to weightlessness and motion sickness, among other research",
            "She left NASA in 1993 and founded a technology research company, later also founding a nonprofit focused on science education",
            "She has led the 100 Year Starship project, an initiative studying the long-term challenges of eventual human interstellar travel",
            "She has received numerous honors for her work promoting science education, particularly for young women and students of color",
        ], related_subjects=["Physics", "Health Education", "Science"],
    ),
]


def main() -> None:
    upsert_section(
        "science_innovation",
        "Science & Innovation",
        "🔬",
        "Scientists, inventors, and innovators whose discoveries and inventions changed how we understand and shape the world.",
        PEOPLE,
    )


if __name__ == "__main__":
    main()
