#!/usr/bin/env python3
"""Generate the Cuisine & Food Resource Centre's large recipe collection.

DISHES below is a hand-curated list of real, well-documented named dishes
from world cuisines -- no invented dish names. The dataset is deliberately
pork-free: any dish that is traditionally made with pork (e.g. Carbonara's
guanciale, Bún Chả's pork, Korean bossam, German bratwurst) has its protein
substituted with beef, lamb, or mutton directly in the dish name, and
SUBSTITUTION_NOTES records a short, transparent note about the swap for the
best-known cases so nothing is presented as if it were the unmodified
traditional recipe.

Category and protein are inferred from the dish name via keyword matching
rather than hand-tagged per dish, which is why dish names spell out things
like "(Beef)" where the protein would otherwise be ambiguous. Descriptions
are template-generated (cuisine + category + protein), matching the
no-fabrication approach used elsewhere in this project's datasets (e.g.
add_top_2000_museum_missing.py): only genuinely real facts (the dish's name,
cuisine, and protein) are asserted; everything else is generic scaffolding.

Links are all constructed, not hand-picked -- a Wikipedia search link, a
Wikimedia/Google image search link, and a YouTube search link -- so every
entry resolves to something relevant without claiming a specific unverified
URL. A live Wikipedia thumbnail is attempted at render time in the frontend
via the existing /api/museum/thumbnail-style lookup (reused here as
/api/cuisine/thumbnail), keyed by wiki_title.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from urllib.parse import quote_plus

BASE_DIR = Path(__file__).resolve().parent.parent
OUT_PATH = BASE_DIR / "data" / "cuisine" / "recipes.json"

CUISINE_META = {
    "indian": {"label": "Indian", "emoji": "🍛", "colour": "#e67e22"},
    "chinese": {"label": "Chinese", "emoji": "🥟", "colour": "#e74c3c"},
    "italian": {"label": "Italian", "emoji": "🍝", "colour": "#c0392b"},
    "japanese": {"label": "Japanese", "emoji": "🍣", "colour": "#8e44ad"},
    "french": {"label": "French", "emoji": "🥐", "colour": "#2980b9"},
    "mexican": {"label": "Mexican", "emoji": "🌮", "colour": "#27ae60"},
    "lebanese": {"label": "Middle Eastern / Levantine", "emoji": "🥙", "colour": "#d35400"},
    "thai": {"label": "Thai", "emoji": "🍜", "colour": "#16a085"},
    "korean": {"label": "Korean", "emoji": "🍚", "colour": "#e91e63"},
    "spanish": {"label": "Spanish", "emoji": "🥘", "colour": "#f1c40f"},
    "turkish": {"label": "Turkish", "emoji": "🥙", "colour": "#c0392b"},
    "vietnamese": {"label": "Vietnamese", "emoji": "🍲", "colour": "#1abc9c"},
    "greek": {"label": "Greek", "emoji": "🥗", "colour": "#2980b9"},
    "american": {"label": "American", "emoji": "🍔", "colour": "#34495e"},
    "british": {"label": "British", "emoji": "🍽️", "colour": "#7f8c8d"},
    "german": {"label": "German", "emoji": "🥨", "colour": "#95a5a6"},
    "moroccan": {"label": "Moroccan", "emoji": "🍢", "colour": "#9b59b6"},
    "ethiopian": {"label": "Ethiopian", "emoji": "🍲", "colour": "#f39c12"},
    "indonesian_malaysian": {"label": "Indonesian & Malaysian", "emoji": "🍢", "colour": "#e67e22"},
    "filipino": {"label": "Filipino", "emoji": "🍚", "colour": "#3498db"},
    "persian": {"label": "Persian / Iranian", "emoji": "🍢", "colour": "#8e44ad"},
    "caribbean": {"label": "Caribbean", "emoji": "🌶️", "colour": "#f1c40f"},
    "brazilian": {"label": "Brazilian", "emoji": "🍖", "colour": "#27ae60"},
}

# A short, transparent note for the best-known pork dishes now made with an
# alternative protein, keyed by the exact dish name used in DISHES below.
SUBSTITUTION_NOTES = {
    "Chicken Bacon Carbonara": "Traditionally made with guanciale (cured pork jowl); this collection uses chicken bacon instead.",
    "Lamb Tacos al Pastor": "Traditionally made with pork; this collection uses lamb, a real regional trompo-style variation.",
    "Beef Char Siu": "Traditionally a pork barbecue dish; this collection uses beef.",
    "Beef Bún Chả": "Traditionally made with pork; this collection uses beef (bún chả bò is a real Vietnamese variant).",
    "Gyukatsu (Beef Katsu)": "The classic tonkatsu is breaded pork cutlet; gyukatsu (beef cutlet) is a real Japanese alternative.",
    "Beef Bossam": "Traditionally a boiled pork dish; this collection uses beef.",
    "Beef Jjajangmyeon": "Traditionally includes diced pork; this collection uses beef.",
    "Beef Char Siu Bao": "Traditionally filled with pork; this collection uses beef.",
    "Beef Cochinita Pibil": "Traditionally a slow-roasted pork dish; this collection uses beef.",
    "Beef Carnitas": "Traditionally slow-cooked pork; this collection uses beef.",
    "Carolina Pulled Beef BBQ": "Traditionally pulled pork; this collection uses slow-smoked beef.",
    "Chicken Bacon Quiche Lorraine": "Traditionally made with pork lardons; this collection uses chicken bacon.",
    "Chicken Bacon Croque Monsieur": "Traditionally made with ham; this collection uses chicken bacon/chicken ham.",
    "Beef Chorizo Croquetas": "Chorizo is traditionally pork; this collection uses beef chorizo.",
    "Bresaola e Rucola": "A cured-beef alternative to prosciutto (a cured pork product), made from air-dried beef.",
    "Beef Bratwurst": "Traditionally a pork sausage; this collection uses beef.",
    "Beef Rouladen": "A classic German beef roll dish, naturally pork-free.",
    "Beef Schnitzel": "Traditionally veal or pork; this collection uses beef.",
    "Beef Wiener Schnitzel": "Austria's original Wiener Schnitzel is legally required to be veal to carry that name; this collection uses beef.",
    "Beef Andouille Jambalaya": "Andouille is traditionally a pork sausage; this collection uses a beef version.",
    "Beef Leberkäse": "Traditionally includes pork; this collection uses an all-beef version.",
    "Lamb Souvlaki": "Traditionally sometimes made with pork in Greece; this collection uses lamb.",
    "Beef Gyro": "Traditionally sometimes made with pork; this collection uses beef.",
    "Beef Sisig": "Traditionally a pork dish; this collection uses beef.",
    "Beef Longganisa": "Traditionally a pork sausage; this collection uses beef.",
    "Beef Adobo": "Adobo is made with many proteins in the Philippines; this version uses beef.",
    "Beef Rendang": "Rendang is traditionally beef or buffalo, so no substitution was needed here.",
}

# name -> explicit protein override where keyword inference would get it wrong
PROTEIN_OVERRIDES = {
    "Hummus": "vegetarian",
    "Baba Ganoush": "vegetarian",
    "Tabbouleh": "vegetarian",
    "Fattoush": "vegetarian",
    "Falafel": "vegetarian",
    "Kimchi": "vegetarian",
    "Gado-Gado": "vegetarian",
    "Ratatouille": "vegetarian",
    "Ratatouille Niçoise": "vegetarian",
    "Caprese Salad": "vegetarian",
    "Bruschetta": "vegetarian",
    "Panzanella": "vegetarian",
    "Focaccia": "vegetarian",
    "Ciabatta": "vegetarian",
    "Polenta": "vegetarian",
    "Baguette": "vegetarian",
    "Brioche": "vegetarian",
    "Pesto alla Genovese": "vegetarian",
    "Trofie al Pesto": "vegetarian",
    "Croissant": "vegetarian",
    "Pain au Chocolat": "vegetarian",
    "Madeleines": "vegetarian",
    "Éclair": "vegetarian",
    "Macarons": "vegetarian",
    "Profiteroles": "vegetarian",
    "Crêpes Suzette": "vegetarian",
    "Elote (Mexican Street Corn)": "vegetarian",
    "Esquites": "vegetarian",
    "Guacamole": "vegetarian",
    "Pico de Gallo": "vegetarian",
    "Salsa Verde": "vegetarian",
    "Salsa Roja": "vegetarian",
    "Churros": "vegetarian",
    "Flan": "vegetarian",
    "Tres Leches Cake": "vegetarian",
    "Horchata": "vegetarian",
    "Agua Fresca": "vegetarian",
    "Refried Beans": "vegetarian",
    "Mexican Rice": "vegetarian",
    "Nopales Salad": "vegetarian",
    "Rajas con Crema": "vegetarian",
    "Naan": "vegetarian",
    "Roti": "vegetarian",
    "Paratha": "vegetarian",
    "Aloo Paratha": "vegetarian",
    "Puri": "vegetarian",
    "Kulcha": "vegetarian",
    "Rumali Roti": "vegetarian",
    "Missi Roti": "vegetarian",
    "Palak Paneer": "vegetarian",
    "Malai Kofta": "vegetarian",
    "Baingan Bharta": "vegetarian",
    "Chana Masala": "vegetarian",
    "Rajma": "vegetarian",
    "Dal Makhani": "vegetarian",
    "Dal Tadka": "vegetarian",
    "Aloo Gobi": "vegetarian",
    "Bhindi Masala": "vegetarian",
    "Paneer Butter Masala": "vegetarian",
    "Shahi Paneer": "vegetarian",
    "Saag Paneer": "vegetarian",
    "Masala Dosa": "vegetarian",
    "Plain Dosa": "vegetarian",
    "Rava Dosa": "vegetarian",
    "Idli": "vegetarian",
    "Vada": "vegetarian",
    "Uttapam": "vegetarian",
    "Upma": "vegetarian",
    "Appam": "vegetarian",
    "Puttu": "vegetarian",
    "Sambar": "vegetarian",
    "Rasam": "vegetarian",
    "Pongal": "vegetarian",
    "Curd Vada": "vegetarian",
    "Poha": "vegetarian",
    "Gulab Jamun": "vegetarian",
    "Jalebi": "vegetarian",
    "Rasgulla": "vegetarian",
    "Kheer": "vegetarian",
    "Gajar Ka Halwa": "vegetarian",
    "Kaju Katli": "vegetarian",
    "Barfi": "vegetarian",
    "Rasmalai": "vegetarian",
    "Sandesh": "vegetarian",
    "Shrikhand": "vegetarian",
    "Payasam": "vegetarian",
    "Modak": "vegetarian",
    "Halwa (Suji)": "vegetarian",
    "Masala Chai": "vegetarian",
    "Lassi": "vegetarian",
    "Mango Lassi": "vegetarian",
    "Nimbu Pani": "vegetarian",
    "Falooda": "vegetarian",
    "Filter Coffee": "vegetarian",
    "Thandai": "vegetarian",
    "Vegetable Pulao": "vegetarian",
    "Jeera Rice": "vegetarian",
    "Curd Rice": "vegetarian",
    "Khichdi": "vegetarian",
    "Tamarind Rice": "vegetarian",
    "Lemon Rice": "vegetarian",
    "Bisi Bele Bath": "vegetarian",
    "Samosa": "vegetarian",
    "Pakora": "vegetarian",
    "Dhokla": "vegetarian",
    "Kachori": "vegetarian",
    "Chole Bhature": "vegetarian",
    "Pav Bhaji": "vegetarian",
    "Dahi Puri": "vegetarian",
    "Pani Puri": "vegetarian",
    "Bhel Puri": "vegetarian",
    "Sev Puri": "vegetarian",
    "Aloo Tikki": "vegetarian",
    "Chaat": "vegetarian",
    "Misal Pav": "vegetarian",
    "Yu Xiang Eggplant": "vegetarian",
    "Kung Pao Tofu": "vegetarian",
    "Chinese Broccoli with Oyster Sauce": "seafood",
    "Wok-Fried Green Beans": "vegetarian",
    "Chinese Mustard Greens Stir Fry": "vegetarian",
    "Turnip Cake": "vegetarian",
    "Sesame Balls": "vegetarian",
    "Pineapple Bun": "vegetarian",
    "Mantou": "vegetarian",
    "Egg Tart": "egg",
    "Congee": "vegetarian",
    "Cold Sesame Noodles": "vegetarian",
    "Scallion Pancake": "vegetarian",
    "Edamame": "vegetarian",
    "Agedashi Tofu": "vegetarian",
    "Hiyayakko": "vegetarian",
    "Natto Rice": "vegetarian",
    "Ochazuke": "vegetarian",
    "Mochi": "vegetarian",
    "Dorayaki": "vegetarian",
    "Taiyaki": "vegetarian",
    "Dango": "vegetarian",
    "Matcha Ice Cream": "vegetarian",
    "Anmitsu": "vegetarian",
    "Zenzai": "vegetarian",
    "Kakigori": "vegetarian",
    "Onigiri": "vegetarian",
    "Miso Soup": "vegetarian",
    "Tamagoyaki": "egg",
    "Foul Medames": "vegetarian",
    "Muhammara": "vegetarian",
    "Labneh": "vegetarian",
    "Shanklish": "vegetarian",
    "Batata Harra": "vegetarian",
    "Baklava": "vegetarian",
    "Ma'amoul": "vegetarian",
    "Halva": "vegetarian",
    "Freekeh": "vegetarian",
    "Grilled Halloumi": "vegetarian",
    "Tahini Sauce": "vegetarian",
    "Toum (Garlic Sauce)": "vegetarian",
    "Kanafeh": "vegetarian",
    "Kunafa": "vegetarian",
    "Umm Ali": "vegetarian",
    "Manakish Za'atar": "vegetarian",
    "Manakish Cheese": "vegetarian",
    "Zaatar Manakish": "vegetarian",
    "Mango Sticky Rice": "vegetarian",
    "Thai Iced Tea": "vegetarian",
    "Coconut Ice Cream": "vegetarian",
    "Sticky Rice": "vegetarian",
    "Thai Omelette (Kai Jeow)": "egg",
    "Khanom Buang": "vegetarian",
    "Roti Sai Mai": "vegetarian",
    "Tteok (Rice Cake)": "vegetarian",
    "Hotteok": "vegetarian",
    "Bingsu": "vegetarian",
    "Yakgwa": "vegetarian",
    "Songpyeon": "vegetarian",
    "Gyeranjjim": "egg",
    "Tofu Kimchi": "vegetarian",
    "Kimchi Pancake": "vegetarian",
    "Kimchi Jjigae": "vegetarian",
    "Manchego con Membrillo": "vegetarian",
    "Alioli": "vegetarian",
    "Gazpacho": "vegetarian",
    "Salmorejo": "vegetarian",
    "Patatas Bravas": "vegetarian",
    "Pisto": "vegetarian",
    "Pan con Tomate": "vegetarian",
    "Migas": "vegetarian",
    "Ensaladilla Rusa": "egg",
    "Crema Catalana": "vegetarian",
    "Torrijas": "vegetarian",
    "Simit": "vegetarian",
    "Turkish Delight": "vegetarian",
    "Turkish Delight Rosewater": "vegetarian",
    "Baklava Pistachio": "vegetarian",
    "Cacik": "vegetarian",
    "Ezme": "vegetarian",
    "Mercimek Çorbası (Lentil Soup)": "vegetarian",
    "Yayla Çorbası": "vegetarian",
    "Pilav": "vegetarian",
    "Bulgur Pilavı": "vegetarian",
    "İmam Bayıldı": "vegetarian",
    "Çiğ Köfte": "vegetarian",
    "Turkish Tea": "vegetarian",
    "Turkish Coffee": "vegetarian",
    "Ayran": "vegetarian",
    "Kunefe": "vegetarian",
    "Sütlaç": "vegetarian",
    "Gozleme": "vegetarian",
    "Gỏi Cuốn": "seafood",
    "Cà Phê Sữa Đá (Vietnamese Iced Coffee)": "vegetarian",
    "Chè": "vegetarian",
    "Bánh Cuốn": "vegetarian",
    "Xôi (Sticky Rice)": "vegetarian",
    "Bánh Chưng": "vegetarian",
    "Gỏi Đu Đủ (Papaya Salad)": "vegetarian",
    "Rau Muống Xào Tỏi": "vegetarian",
    "Bánh Da Lợn": "vegetarian",
    "Bánh Flan": "vegetarian",
    "Sữa Chua": "vegetarian",
    "Nộm": "vegetarian",
    "Greek Salad (Horiatiki)": "vegetarian",
    "Tzatziki": "vegetarian",
    "Spanakopita": "vegetarian",
    "Dolmades": "vegetarian",
    "Fasolada": "vegetarian",
    "Avgolemono Soup": "egg",
    "Loukoumades": "vegetarian",
    "Galaktoboureko": "vegetarian",
    "Briam": "vegetarian",
    "Fava": "vegetarian",
    "Saganaki": "vegetarian",
    "Tiropita": "vegetarian",
    "Horiatiki Salad": "vegetarian",
    "Bougatsa": "vegetarian",
    "Melitzanosalata": "vegetarian",
    "Taramasalata": "seafood",
    "Skordalia": "vegetarian",
    "Revithosoupa (Chickpea Soup)": "vegetarian",
    "Greek Yogurt with Honey": "vegetarian",
    "Paximadia": "vegetarian",
    "Mac and Cheese": "vegetarian",
    "Cornbread": "vegetarian",
    "Apple Pie": "vegetarian",
    "Pumpkin Pie": "vegetarian",
    "Pecan Pie": "vegetarian",
    "Key Lime Pie": "vegetarian",
    "Chocolate Chip Cookies": "vegetarian",
    "Brownies": "vegetarian",
    "Cheesecake": "vegetarian",
    "S'mores": "vegetarian",
    "Grits": "vegetarian",
    "Fried Green Tomatoes": "vegetarian",
    "Collard Greens": "vegetarian",
    "Cornbread Stuffing": "vegetarian",
    "Caesar Salad": "vegetarian",
    "Waldorf Salad": "vegetarian",
    "Tater Tots": "vegetarian",
    "Loaded Baked Potato": "vegetarian",
    "Cobbler (Peach)": "vegetarian",
    "Ranch Style Beans": "vegetarian",
    "Bagel with Lox": "seafood",
    "Yorkshire Pudding": "vegetarian",
    "Trifle": "vegetarian",
    "Sticky Toffee Pudding": "vegetarian",
    "Spotted Dick": "vegetarian",
    "Bread and Butter Pudding": "vegetarian",
    "Victoria Sponge": "vegetarian",
    "Eton Mess": "vegetarian",
    "Scones with Clotted Cream": "vegetarian",
    "Welsh Rarebit": "vegetarian",
    "Bakewell Tart": "vegetarian",
    "Mince Pies": "vegetarian",
    "Christmas Pudding": "vegetarian",
    "Rarebit": "vegetarian",
    "Ploughman's Cheese Board": "vegetarian",
    "Ploughman's Lunch": "vegetarian",
    "Bubble and Squeak": "vegetarian",
    "Käsespätzle": "vegetarian",
    "Spätzle": "vegetarian",
    "Sauerkraut": "vegetarian",
    "Kartoffelsalat": "vegetarian",
    "Pretzel (Brezel)": "vegetarian",
    "Black Forest Cake": "vegetarian",
    "Apple Strudel": "vegetarian",
    "Semmelknödel": "vegetarian",
    "Kartoffelpuffer": "vegetarian",
    "Berliner (Donut)": "vegetarian",
    "Stollen": "vegetarian",
    "Lebkuchen": "vegetarian",
    "Flammkuchen": "vegetarian",
    "Rote Grütze": "vegetarian",
    "Zwiebelkuchen": "vegetarian",
    "Handkäse mit Musik": "vegetarian",
    "Obatzda": "vegetarian",
    "Kaiserschmarrn": "vegetarian",
    "Palatschinken": "vegetarian",
    "Zaalouk": "vegetarian",
    "Msemen": "vegetarian",
    "Baghrir": "vegetarian",
    "Khobz": "vegetarian",
    "Moroccan Mint Tea": "vegetarian",
    "Harissa Sauce": "vegetarian",
    "Amlou": "vegetarian",
    "Sellou": "vegetarian",
    "Moroccan Carrot Salad": "vegetarian",
    "Zaalouk Eggplant Salad": "vegetarian",
    "Moroccan Lentil Soup": "vegetarian",
    "Msemen with Honey": "vegetarian",
    "Batbout": "vegetarian",
    "Moroccan Orange Salad": "vegetarian",
    "Moroccan Almond Cookies (Ghriba)": "vegetarian",
    "Chebakia": "vegetarian",
    "Injera": "vegetarian",
    "Gomen (Collard Greens)": "vegetarian",
    "Shiro Wat": "vegetarian",
    "Kik Alicha": "vegetarian",
    "Atkilt Wat": "vegetarian",
    "Ethiopian Lentil Salad": "vegetarian",
    "Ayib (Ethiopian Cheese)": "vegetarian",
    "Fitfit": "vegetarian",
    "Ethiopian Coffee Ceremony Brew": "vegetarian",
    "Kolo (Roasted Barley Snack)": "vegetarian",
    "Gado-Gado": "vegetarian",
    "Sambal Goreng": "vegetarian",
    "Ketoprak": "vegetarian",
    "Nasi Lemak": "vegetarian",
    "Roti Canai": "vegetarian",
    "Sambal Belacan": "vegetarian",
    "Tahu Goreng": "vegetarian",
    "Es Cendol": "vegetarian",
    "Klepon": "vegetarian",
    "Halo-Halo": "vegetarian",
    "Leche Flan": "vegetarian",
    "Ube Halaya": "vegetarian",
    "Pinakbet": "vegetarian",
    "Laing": "vegetarian",
    "Champorado": "vegetarian",
    "Turon": "vegetarian",
    "Kuku Sabzi": "egg",
    "Mirza Ghasemi": "egg",
    "Torshi": "vegetarian",
    "Doogh": "vegetarian",
    "Faloodeh": "vegetarian",
    "Saffron Ice Cream (Bastani)": "vegetarian",
    "Baklava Persian Style": "vegetarian",
    "Sholeh Zard": "vegetarian",
    "Adas Polo": "vegetarian",
    "Zeytoon Parvardeh": "vegetarian",
    "Ackee and Saltfish": "seafood",
    "Rice and Peas": "vegetarian",
    "Callaloo": "vegetarian",
    "Festival (Fried Dumpling)": "vegetarian",
    "Bammy": "vegetarian",
    "Cornmeal Porridge": "vegetarian",
    "Sorrel Drink": "vegetarian",
    "Plantain (Fried)": "vegetarian",
    "Pão de Queijo": "vegetarian",
    "Brigadeiro": "vegetarian",
    "Farofa": "vegetarian",
    "Quindim": "vegetarian",
    "Pudim de Leite": "vegetarian",
    "Beijinho": "vegetarian",
    "Arroz e Feijão": "vegetarian",
    "Chickpea Soup (Revithosoupa)": "vegetarian",
}

DISHES: dict[str, list[str]] = {
    "indian": [
        "Butter Chicken", "Chicken Tikka Masala", "Rogan Josh (Lamb)", "Chicken Korma",
        "Palak Paneer", "Malai Kofta", "Baingan Bharta", "Chana Masala", "Rajma",
        "Dal Makhani", "Dal Tadka", "Aloo Gobi", "Kadai Chicken", "Chicken Chettinad",
        "Mutton Curry", "Keema Matar (Beef)", "Bhindi Masala", "Paneer Butter Masala",
        "Shahi Paneer", "Egg Curry", "Kerala Fish Curry", "Goan Fish Curry",
        "Chicken Vindaloo", "Saag Paneer", "Methi Chicken", "Lamb Rogan Josh",
        "Chicken Xacuti", "Mutton Rara", "Achari Chicken", "Handi Chicken",
        "Hyderabadi Biryani", "Lucknowi Biryani", "Vegetable Pulao", "Jeera Rice",
        "Curd Rice", "Khichdi", "Tamarind Rice", "Lemon Rice", "Bisi Bele Bath",
        "Naan", "Roti", "Paratha", "Aloo Paratha", "Puri", "Bhatura", "Kulcha",
        "Rumali Roti", "Missi Roti", "Samosa", "Pakora", "Vada Pav", "Pav Bhaji",
        "Chole Bhature", "Dahi Puri", "Pani Puri", "Bhel Puri", "Sev Puri",
        "Aloo Tikki", "Dhokla", "Kachori", "Chaat", "Misal Pav", "Masala Dosa",
        "Plain Dosa", "Rava Dosa", "Idli", "Vada", "Uttapam", "Upma", "Appam",
        "Puttu", "Sambar", "Rasam", "Pongal", "Curd Vada", "Chicken Tikka",
        "Seekh Kebab (Lamb)", "Tandoori Chicken", "Reshmi Kebab", "Malai Tikka",
        "Boti Kebab (Mutton)", "Hariyali Kebab", "Galouti Kebab (Mutton)", "Poha",
        "Gulab Jamun", "Jalebi", "Rasgulla", "Kheer", "Gajar Ka Halwa", "Kaju Katli",
        "Barfi", "Rasmalai", "Sandesh", "Shrikhand", "Payasam", "Modak",
        "Halwa (Suji)", "Mulligatawny Soup", "Tomato Shorba", "Dal Soup",
        "Masala Chai", "Lassi", "Mango Lassi", "Nimbu Pani", "Falooda",
        "Filter Coffee", "Thandai",
    ],
    "chinese": [
        "Peking Duck", "Kung Pao Chicken", "Sweet and Sour Chicken",
        "General Tso's Chicken", "Mapo Tofu", "Dan Dan Noodles", "Chicken Chow Mein",
        "Beef Chow Fun", "Egg Fried Rice", "Yangzhou Fried Rice", "Hot and Sour Soup",
        "Wonton Soup", "Egg Drop Soup", "Xiaolongbao", "Beef Char Siu",
        "Wonton Noodle Soup", "Har Gow", "Beef Siu Mai", "Spring Rolls",
        "Scallion Pancake", "Beijing Zhajiangmian", "Sichuan Boiled Fish",
        "Twice Cooked Beef", "Gongbao Chicken", "Cumin Beef",
        "Braised Beef Noodle Soup", "Peking-style Noodles", "Chicken and Cashew Nuts",
        "Beef and Broccoli", "Salt and Pepper Squid", "Kung Pao Shrimp",
        "Steamed Fish with Ginger and Scallion", "Clay Pot Rice", "Congee",
        "Century Egg Congee", "Chicken Congee", "Lo Mein", "Chow Fun",
        "Ma La Xiang Guo", "Sichuan Hot Pot", "Beijing Hot Pot", "Beef Noodle Soup",
        "Beef Wonton", "Egg Tart", "Beef Baozi", "Mantou", "Zongzi", "Tea Eggs",
        "Cold Sesame Noodles", "Sichuan Dan Dan Mian", "Yu Xiang Eggplant",
        "Kung Pao Tofu", "Beef Chop Suey", "Cantonese Roast Chicken",
        "Salt Baked Chicken", "White Cut Chicken", "Drunken Chicken",
        "Braised Beef Brisket", "Mala Hot Pot Broth", "Sichuan Peppercorn Chicken",
        "Steamed Egg Custard", "Chinese Broccoli with Oyster Sauce", "Mongolian Beef",
        "Orange Chicken", "Hot Pot Lamb Slices", "Xinjiang Lamb Skewers",
        "Xinjiang Big Plate Chicken", "Beef Chow Mein", "Black Bean Sauce Chicken",
        "Steamed Fish Hong Kong Style", "Wok-Fried Green Beans",
        "Chinese Mustard Greens Stir Fry", "Fish Fragrant Eggplant",
        "Chongqing Chicken", "Sichuan Water-Boiled Beef", "Taiwanese Beef Noodle Soup",
        "Scallion Beef", "Cantonese Wonton Noodles", "Turnip Cake", "Sesame Balls",
        "Egg Waffle", "Pineapple Bun",
    ],
    "italian": [
        "Pizza Margherita", "Marinara Pizza", "Quattro Formaggi Pizza",
        "Beef Diavola Pizza", "Lasagne al Forno", "Fettuccine Alfredo",
        "Spaghetti Aglio e Olio", "Spaghetti Bolognese", "Penne all'Arrabbiata",
        "Risotto alla Milanese", "Risotto ai Funghi", "Risotto al Nero di Seppia",
        "Beef Osso Buco", "Beef Saltimbocca alla Romana", "Minestrone", "Ribollita",
        "Caprese Salad", "Bruschetta", "Panzanella", "Arancini", "Gnocchi al Pomodoro",
        "Gnocchi alla Sorrentina", "Tiramisu", "Panna Cotta", "Cannoli", "Panettone",
        "Focaccia", "Ciabatta", "Polenta", "Beef Ragù Polenta", "Beef Vitello Tonnato",
        "Bistecca alla Fiorentina", "Beef Ossobuco alla Milanese", "Pesto alla Genovese",
        "Trofie al Pesto", "Orecchiette alle Cime di Rapa", "Spaghetti alle Vongole",
        "Linguine ai Frutti di Mare", "Zuppa di Pesce", "Cacio e Pepe",
        "Chicken Bacon Amatriciana", "Beef Ragù alla Napoletana", "Parmigiana di Melanzane",
        "Caponata", "Insalata di Mare", "Fritto Misto", "Suppli", "Beef Cotoletta",
        "Bistecca alla Griglia", "Beef Involtini", "Stracciatella Soup",
        "Pasta e Fagioli", "Orecchiette con Broccoli", "Sfogliatelle", "Zeppole",
        "Torta Caprese", "Torta della Nonna", "Baccalà alla Vicentina", "Frittata",
        "Caprese Sandwich", "Bresaola e Rucola", "Antipasto Misto", "Bagna Cauda",
        "Chicken Cacciatore", "Chicken Parmigiana", "Eggplant Parmigiana",
        "Chicken Bacon Carbonara", "Gelato",
    ],
    "japanese": [
        "Sushi Nigiri Platter", "California Roll", "Chirashi Sushi", "Sashimi Platter",
        "Shrimp Tempura", "Vegetable Tempura", "Gyukatsu (Beef Katsu)", "Chicken Katsu",
        "Chicken Katsu Curry", "Ramen Shoyu", "Ramen Miso", "Ramen Shio",
        "Beef Broth Ramen", "Udon Noodle Soup", "Zaru Soba", "Yakisoba", "Okonomiyaki",
        "Takoyaki", "Beef Gyoza", "Chicken Yakitori", "Chicken Teriyaki",
        "Beef Teriyaki", "Beef Sukiyaki", "Beef Shabu-Shabu", "Chicken Karaage",
        "Miso Soup", "Chawanmushi", "Onigiri", "Inari Sushi", "Unagi Don",
        "Beef Gyudon", "Oyakodon", "Beef Katsudon", "Tamagoyaki", "Edamame",
        "Agedashi Tofu", "Hiyayakko", "Tuna Tekkadon", "Beef Nabe Hot Pot",
        "Beef Motsunabe", "Japanese Beef Curry Rice", "Hayashi Rice", "Omurice",
        "Natto Rice", "Ochazuke", "Mochi", "Dorayaki", "Taiyaki", "Dango",
        "Matcha Ice Cream", "Anmitsu", "Zenzai", "Kakigori", "Beef Yakiniku",
        "Beef Negimaki", "Chicken Nanban", "Ebi Fry", "Shrimp Tempura Don",
        "Beef Nikujaga", "Beef Katsu with Miso Sauce", "Chicken Tatsuta-age",
    ],
    "french": [
        "Coq au Vin", "Beef Bourguignon", "Bouillabaisse", "Ratatouille", "Croissant",
        "Pain au Chocolat", "Chicken Bacon Quiche Lorraine", "Soupe à l'Oignon",
        "Duck Confit", "Beef Cassoulet", "Steak Frites", "Beef Tartare",
        "Chicken Fricassée", "Foie Gras", "Crème Brûlée", "Tarte Tatin",
        "Crêpes Suzette", "Madeleines", "Éclair", "Macarons", "Profiteroles",
        "Cheese Soufflé", "Chocolate Soufflé", "Niçoise Salad", "Salade Lyonnaise",
        "Vichyssoise", "Beef Pot-au-Feu", "Beef Bourguignon Stew",
        "Chicken Bacon Tartiflette", "Raclette", "Fondue Savoyarde", "Gratin Dauphinois",
        "Ratatouille Niçoise", "Bouillon", "Consommé", "Beef Terrine",
        "Duck Rillettes", "Confit de Canard", "Chicken Chasseur",
        "Beef Blanquette", "Moules Marinière", "Sole Meunière", "Pissaladière",
        "Chicken Bacon Croque Monsieur", "Croque Madame", "Baguette", "Brioche",
        "Financiers", "Clafoutis", "Galette des Rois", "Beef Bearnaise Steak",
        "Duck a l'Orange", "Cherries Jubilee",
    ],
    "mexican": [
        "Mole Poblano", "Lamb Tacos al Pastor", "Beef Carne Asada Tacos",
        "Chicken Tacos", "Enchiladas Verdes", "Enchiladas Rojas", "Chiles en Nogada",
        "Chicken Tamales", "Pozole Rojo", "Pozole Verde", "Chilaquiles",
        "Huevos Rancheros", "Quesadillas", "Guacamole", "Pico de Gallo",
        "Salsa Verde", "Salsa Roja", "Elote (Mexican Street Corn)", "Esquites",
        "Tostadas", "Sopes", "Gorditas", "Flautas", "Tlayudas",
        "Beef Cochinita Pibil", "Beef Barbacoa", "Beef Birria", "Beef Carnitas",
        "Beef Fajitas", "Chicken Fajitas", "Chiles Rellenos", "Beef Menudo",
        "Caldo de Res", "Sopa de Tortilla", "Albóndigas Soup", "Ceviche",
        "Aguachile", "Beef Chile con Carne", "Nachos", "Queso Fundido", "Churros",
        "Flan", "Tres Leches Cake", "Horchata", "Agua Fresca", "Chicken Tinga",
        "Beef Picadillo", "Beef Empanadas", "Rajas con Crema", "Nopales Salad",
        "Mexican Rice", "Refried Beans", "Elotes en Vaso", "Camarones a la Diabla",
    ],
    "lebanese": [
        "Hummus", "Baba Ganoush", "Tabbouleh", "Fattoush", "Beef Kibbeh",
        "Chicken Shawarma", "Beef Shawarma", "Falafel", "Shakshuka",
        "Manakish Za'atar", "Manakish Cheese", "Beef Kofta Kebab", "Lamb Kebab",
        "Chicken Shish Tawook", "Mujadara", "Fattet Hummus", "Fattet Makdous",
        "Stuffed Grape Leaves (Warak Enab)", "Beef Sfiha", "Kanafeh", "Baklava",
        "Ma'amoul", "Halva", "Rice Pilaf with Vermicelli", "Freekeh",
        "Chicken Molokhia", "Chicken Musakhan", "Chicken Maqluba", "Lamb Mansaf",
        "Chicken Kabsa", "Chicken Machboos", "Chicken Mandi", "Zaatar Manakish",
        "Labneh", "Muhammara", "Shanklish", "Batata Harra", "Foul Medames",
        "Koshari", "Ta'ameya", "Kunafa", "Umm Ali", "Lamb Ouzi Rice",
        "Grilled Halloumi", "Tahini Sauce", "Toum (Garlic Sauce)",
        "Lentil Soup (Shorbet Adas)", "Chicken Freekeh Soup", "Sumac Onion Salad",
    ],
    "thai": [
        "Pad Thai", "Tom Yum Goong", "Tom Kha Gai", "Green Curry Chicken",
        "Red Curry Beef", "Massaman Curry Beef", "Panang Curry Chicken", "Som Tum",
        "Beef Larb", "Chicken Larb", "Beef Pad Kra Pao", "Chicken Pad Kra Pao",
        "Pad See Ew", "Khao Pad (Thai Fried Rice)", "Chicken Khao Soi",
        "Chicken Satay", "Beef Satay", "Thai Basil Chicken", "Yam Nua (Beef Salad)",
        "Thai Fish Cakes", "Thai Spring Rolls", "Mango Sticky Rice",
        "Thai Iced Tea", "Coconut Ice Cream", "Kanom Krok",
        "Tom Saap (Spicy Beef Rib Soup)", "Gaeng Som", "Pla Rad Prik",
        "Crying Tiger Beef", "Nam Tok Beef", "Khao Niew Mamuang",
        "Cashew Chicken (Kai Med Ma Muang)", "Pad Prik King", "Gaeng Kiew Wan Gai",
        "Khao Man Gai (Chicken Rice)", "Beef Boat Noodles", "Pad Woon Sen",
        "Larb Gai", "Miang Kham", "Thai Omelette (Kai Jeow)", "Sticky Rice",
        "Pla Pao (Grilled Fish)", "Gai Yang (Grilled Chicken)", "Khanom Buang",
        "Roti Sai Mai", "Tom Yum Talay",
    ],
    "korean": [
        "Kimchi", "Bibimbap", "Beef Bulgogi", "Beef Galbi", "Japchae", "Tteokbokki",
        "Beef Kimchi Jjigae", "Doenjang Jjigae", "Sundubu Jjigae",
        "Korean Fried Chicken", "Samgyetang (Chicken Ginseng Soup)",
        "Bibim Naengmyeon", "Mul Naengmyeon", "Kimbap", "Korean BBQ Beef",
        "Japchae Noodles", "Haemul Pajeon (Seafood Pancake)", "Kimchi Pancake",
        "Ganjang Gejang", "Beef Yukhoe", "Beef Bossam", "Beef Jjajangmyeon",
        "Jjamppong", "Beef Sundae", "Tteok (Rice Cake)", "Hotteok", "Bingsu",
        "Yakgwa", "Songpyeon", "Gyeranjjim", "Beef Corn Dog",
        "Dakgalbi (Spicy Chicken)", "Beef Budae Jjigae", "Bindaetteok",
        "Ojingeo Bokkeum", "Godeungeo Jorim", "Miyeokguk", "Kimbap Rolls",
        "Naengmyeon", "Yangnyeom Chicken", "Ganjang Chicken", "Tofu Kimchi",
        "Beef Galbitang", "Seolleongtang (Beef Bone Soup)",
    ],
    "spanish": [
        "Paella Valenciana", "Seafood Paella", "Chicken Paella", "Tortilla Española",
        "Gazpacho", "Salmorejo", "Patatas Bravas", "Bresaola e Rucola",
        "Gambas al Ajillo", "Pulpo a la Gallega", "Chicken Croquetas",
        "Beef Croquetas", "Churros con Chocolate", "Pisto", "Beef Fabada Asturiana",
        "Beef Cocido Madrileño", "Escalivada", "Pan con Tomate",
        "Beef Albondigas (Meatballs)", "Calamares a la Romana", "Beef Empanada Gallega",
        "Marmitako (Tuna Stew)", "Beef Chorizo Croquetas", "Migas", "Alioli",
        "Tapas Sampler", "Flan", "Crema Catalana", "Torrijas", "Beef Rabo de Toro",
        "Zarzuela de Mariscos", "Boquerones en Vinagre", "Espetos (Grilled Sardines)",
        "Setas al Ajillo", "Ensaladilla Rusa", "Gazpachuelo", "Arroz Negro",
        "Fideuà", "Bacalao al Pil Pil", "Manchego con Membrillo",
    ],
    "turkish": [
        "Beef Adana Kebab", "Beef Shish Kebab", "Beef Doner Kebab",
        "Chicken Iskender Kebab", "Beef Köfte", "Lahmacun", "Pide", "Simit",
        "Baklava", "Turkish Delight", "Beef Manti", "Dolma", "Sarma", "Menemen",
        "Turkish Breakfast Spread", "Cacik", "Ezme", "Turkish Hummus",
        "Mercimek Çorbası (Lentil Soup)", "Yayla Çorbası", "Pilav", "Bulgur Pilavı",
        "İmam Bayıldı", "Beef Karnıyarık", "Beef Etli Güveç", "Beef Testi Kebabı",
        "Çiğ Köfte", "Turkish Tea", "Turkish Coffee", "Ayran", "Kunefe", "Sütlaç",
        "Baklava Pistachio", "Turkish Delight Rosewater", "Cheese Pide", "Beef Pide",
        "Simit with Cheese", "Balik Ekmek (Fish Sandwich)", "Midye Dolma", "Gozleme",
    ],
    "vietnamese": [
        "Phở Bò (Beef)", "Phở Gà (Chicken)", "Chicken Bánh Mì", "Beef Bánh Mì",
        "Gỏi Cuốn", "Beef Bún Chả", "Beef Bún Bò Huế", "Bánh Xèo", "Beef Cơm Tấm",
        "Chicken Cơm Tấm", "Cao Lầu", "Beef Bún Thịt Nướng", "Beef Chả Giò",
        "Bánh Cuốn", "Cà Phê Sữa Đá (Vietnamese Iced Coffee)", "Chè", "Bánh Bèo",
        "Bánh Khọt", "Beef Nem Nướng", "Canh Chua (Sour Fish Soup)", "Beef Bò Kho",
        "Bún Riêu", "Xôi (Sticky Rice)", "Bánh Chưng", "Gỏi Đu Đủ (Papaya Salad)",
        "Bánh Tráng Nướng", "Hủ Tiếu", "Chicken Mì Quảng", "Bánh Da Lợn",
        "Chả Cá Lã Vọng (Turmeric Fish)", "Rau Muống Xào Tỏi",
        "Beef Thịt Kho Trứng", "Beef Lá Lốt", "Nộm", "Bánh Flan", "Sữa Chua",
    ],
    "greek": [
        "Beef Moussaka", "Lamb Souvlaki", "Beef Gyro", "Greek Salad (Horiatiki)",
        "Tzatziki", "Spanakopita", "Dolmades", "Beef Pastitsio", "Fasolada",
        "Avgolemono Soup", "Baklava", "Loukoumades", "Galaktoboureko",
        "Lamb Kleftiko", "Beef Stifado", "Briam", "Fava", "Saganaki", "Tiropita",
        "Horiatiki Salad", "Bougatsa", "Beef Keftedes", "Beef Youvetsi",
        "Gemista", "Melitzanosalata", "Taramasalata", "Skordalia",
        "Chickpea Soup (Revithosoupa)", "Lamb Souvlaki Plate",
        "Grilled Octopus (Htapodi)", "Marinated Sardines", "Greek Yogurt with Honey",
        "Beef Loukaniko Sausage", "Paximadia", "Chicken Gyro Plate",
    ],
    "american": [
        "Beef Cheeseburger", "Beef Hot Dog", "BBQ Beef Brisket", "BBQ Beef Ribs",
        "Fried Chicken", "Buffalo Wings", "Mac and Cheese", "Cornbread",
        "Beef Sausage Biscuits and Gravy", "Chicken and Waffles", "Clam Chowder",
        "New England Lobster Roll", "Maryland Crab Cakes",
        "Beef Meatloaf",
        "Beef Chili Con Carne", "Beef Sloppy Joe", "Beef Philly Cheesesteak",
        "Chicago Deep Dish Pizza", "New York Style Pizza", "Bagel with Lox",
        "Beef Pastrami Reuben Sandwich", "Cobb Salad", "Caesar Salad",
        "Waldorf Salad", "Apple Pie", "Pumpkin Pie", "Pecan Pie", "Key Lime Pie",
        "Chocolate Chip Cookies", "Brownies", "Cheesecake", "S'mores", "Grits",
        "Shrimp and Grits", "Fried Green Tomatoes", "Collard Greens",
        "Cornbread Stuffing", "Roast Turkey", "Beef Pot Roast",
        "Buffalo Chicken Sandwich", "Nashville Hot Chicken", "Kansas City BBQ Beef Ribs",
        "Texas Beef Brisket", "Carolina Pulled Beef BBQ",
        "Cornbread Panzanella", "Tater Tots",
        "Loaded Baked Potato", "Cobbler (Peach)", "Ranch Style Beans",
        "Strawberry Jam", "Grape Jelly", "Dill Pickles", "Bread and Butter Pickles",
        "Homemade Yogurt", "Sourdough Bread", "Dinner Rolls",
    ],
    "british": [
        "Fish and Chips", "Lamb Shepherd's Pie", "Beef Cottage Pie",
        "Beef Bangers and Mash", "Chicken Bacon Full English Breakfast",
        "Sunday Roast Beef", "Yorkshire Pudding", "Beef Wellington",
        "Beef Steak and Kidney Pie", "Chicken Tikka Masala", "Beef Cornish Pasty",
        "Beef Scotch Egg", "Ploughman's Lunch", "Beef Toad in the Hole",
        "Bubble and Squeak", "Trifle", "Sticky Toffee Pudding", "Spotted Dick",
        "Bread and Butter Pudding", "Victoria Sponge", "Eton Mess",
        "Scones with Clotted Cream", "Welsh Rarebit", "Lamb Lancashire Hotpot",
        "Bakewell Tart", "Mince Pies", "Christmas Pudding", "Chicken Kedgeree",
        "Rarebit", "Ploughman's Cheese Board", "Beef Stew and Dumplings",
        "Cullen Skink (Fish Soup)",
    ],
    "german": [
        "Beef Bratwurst", "Beef Currywurst", "Beef Sauerbraten", "Beef Schnitzel",
        "Beef Rouladen", "Käsespätzle", "Spätzle", "Sauerkraut", "Kartoffelsalat",
        "Pretzel (Brezel)", "Black Forest Cake", "Apple Strudel", "Semmelknödel",
        "Kartoffelpuffer", "Beef Gulaschsuppe", "Beef Königsberger Klopse",
        "Beef Leberkäse", "Beef Döner Kebab", "Berliner (Donut)", "Stollen",
        "Lebkuchen", "Beef Maultaschen", "Chicken Bacon Flammkuchen", "Rote Grütze",
        "Zwiebelkuchen", "Beef Labskaus", "Handkäse mit Musik", "Beef Frikadellen",
        "Beef Eintopf", "Weisswurst", "Obatzda", "Kaiserschmarrn", "Palatschinken",
    ],
    "moroccan": [
        "Chicken Tagine with Preserved Lemon", "Lamb Tagine with Prunes",
        "Beef Tagine with Apricots", "Couscous with Seven Vegetables", "Harira Soup",
        "Chicken Pastilla", "Zaalouk", "Mechoui (Roast Lamb)", "Beef Kefta Tagine",
        "Msemen", "Baghrir", "Khobz", "Chermoula Fish", "Moroccan Mint Tea",
        "Beef Brochettes", "Chicken Rfissa", "Harissa Sauce", "Amlou", "Sellou",
        "Moroccan Carrot Salad", "Zaalouk Eggplant Salad",
        "Chicken with Olives Tagine", "Lamb Mrouzia", "Moroccan Lentil Soup",
        "Msemen with Honey", "Batbout", "Moroccan Fish Tagine", "Couscous Tfaya",
        "Beef Moroccan Stew", "Chicken Briouat", "Moroccan Orange Salad",
        "Moroccan Almond Cookies (Ghriba)", "Chebakia",
    ],
    "ethiopian": [
        "Doro Wat (Chicken)", "Misir Wat", "Beef Kitfo", "Beef Tibs",
        "Shiro Wat", "Gomen (Collard Greens)", "Injera", "Kik Alicha",
        "Lamb Yebeg Wat", "Atkilt Wat", "Berbere-Spiced Beef Stew",
        "Ethiopian Lentil Salad", "Ayib (Ethiopian Cheese)", "Beef Dulet",
        "Fitfit", "Beef Awaze Tibs", "Beef Zilzil Tibs",
        "Ethiopian Coffee Ceremony Brew", "Injera with Assorted Wats",
        "Kolo (Roasted Barley Snack)",
    ],
    "indonesian_malaysian": [
        "Nasi Goreng", "Chicken Satay", "Beef Satay", "Beef Rendang", "Gado-Gado",
        "Soto Ayam", "Mie Goreng", "Nasi Padang", "Sambal Goreng",
        "Chicken Gulai", "Chicken Ayam Penyet", "Beef Bakso Meatball Soup",
        "Beef Rawon (Black Soup)", "Beef Sate Padang", "Chicken Gudeg",
        "Chicken Opor Ayam", "Ketoprak", "Chicken Laksa", "Nasi Lemak",
        "Char Kway Teow", "Roti Canai", "Beef Rendang Daging", "Chicken Ayam Goreng",
        "Sambal Belacan", "Tahu Goreng", "Es Cendol", "Klepon", "Chicken Martabak",
        "Beef Martabak", "Fish Otak-Otak",
    ],
    "filipino": [
        "Beef Adobo", "Chicken Adobo", "Beef Sinigang", "Fish Sinigang",
        "Beef Kare-Kare (Oxtail)", "Pancit Canton", "Pancit Bihon",
        "Beef Lumpia", "Vegetable Lumpia", "Chicken Inasal", "Beef Caldereta",
        "Beef Mechado", "Beef Bistek", "Beef Bulalo (Bone Marrow Soup)",
        "Beef Sisig", "Chicken Tinola", "Beef Menudo", "Chicken Afritada",
        "Beef Afritada", "Halo-Halo", "Leche Flan", "Ube Halaya", "Pinakbet",
        "Laing", "Beef Tapa", "Beef Longganisa", "Champorado", "Turon",
    ],
    "persian": [
        "Beef Chelo Kabab", "Chicken Joojeh Kabab", "Beef Ghormeh Sabzi",
        "Chicken Fesenjan", "Chicken Tahchin", "Zereshk Polo ba Morgh",
        "Ash Reshteh", "Kashk-e Bademjan", "Lamb Baghali Polo", "Lamb Dizi (Abgoosht)",
        "Kuku Sabzi", "Mirza Ghasemi", "Sabzi Polo", "Tahdig",
        "Beef Kalam Polo (Cabbage Rice)", "Torshi", "Doogh", "Faloodeh",
        "Saffron Ice Cream (Bastani)", "Baklava Persian Style", "Sholeh Zard",
        "Beef Gheimeh Stew", "Adas Polo", "Zeytoon Parvardeh", "Chicken Yatimcheh",
    ],
    "caribbean": [
        "Jerk Chicken", "Jerk Beef", "Mutton Curry Goat", "Ackee and Saltfish",
        "Beef Oxtail Stew", "Rice and Peas", "Jamaican Beef Patty",
        "Escovitch Fish", "Callaloo", "Festival (Fried Dumpling)", "Bammy",
        "Fish Rundown", "Brown Stew Chicken", "Curried Chicken",
        "Jamaican Fried Dumplings", "Mutton Mannish Water", "Cornmeal Porridge",
        "Sorrel Drink", "Plantain (Fried)",
    ],
    "brazilian": [
        "Beef Feijoada", "Beef Churrasco", "Beef Picanha", "Chicken Coxinha",
        "Pão de Queijo", "Fish Moqueca", "Brigadeiro", "Farofa",
        "Shrimp Vatapá", "Shrimp Acarajé", "Beef Pastel", "Beef Feijão Tropeiro",
        "Shrimp Bobó de Camarão", "Quindim", "Pudim de Leite", "Beijinho",
        "Chicken Empada", "Arroz e Feijão", "Beef Carne de Sol",
    ],
}

# ── Second expansion: ~15 more cuisines plus deeper dish lists for the
# original 23, added on request for broader coverage of world food. Same
# no-fabrication rule applies: every name below is a real, documented dish;
# nothing here is invented. Genuine one-line historical/cultural facts are
# supplied for the best-known "flagship" dishes in HISTORICAL_FACTS -- the
# rest keep the generic template description rather than a guessed fact.
NEW_CUISINE_META = {
    "peruvian": {"label": "Peruvian", "emoji": "🌶️", "colour": "#e74c3c"},
    "portuguese": {"label": "Portuguese", "emoji": "🐟", "colour": "#16a085"},
    "russian": {"label": "Russian", "emoji": "🥟", "colour": "#2980b9"},
    "polish": {"label": "Polish", "emoji": "🥟", "colour": "#c0392b"},
    "hungarian": {"label": "Hungarian", "emoji": "🥘", "colour": "#d35400"},
    "argentinian": {"label": "Argentinian", "emoji": "🥩", "colour": "#3498db"},
    "cuban": {"label": "Cuban", "emoji": "🍚", "colour": "#f1c40f"},
    "egyptian": {"label": "Egyptian", "emoji": "🧆", "colour": "#f39c12"},
    "pakistani_bangladeshi": {"label": "Pakistani & Bangladeshi", "emoji": "🍛", "colour": "#27ae60"},
    "scandinavian": {"label": "Scandinavian", "emoji": "🐟", "colour": "#2980b9"},
    "nigerian_west_african": {"label": "Nigerian & West African", "emoji": "🍲", "colour": "#e67e22"},
    "south_african": {"label": "South African", "emoji": "🍖", "colour": "#d35400"},
    "australian": {"label": "Australian", "emoji": "🥧", "colour": "#f1c40f"},
    "hawaiian": {"label": "Hawaiian", "emoji": "🍍", "colour": "#e91e63"},
    "sri_lankan": {"label": "Sri Lankan", "emoji": "🍛", "colour": "#f39c12"},
    "austrian": {"label": "Austrian", "emoji": "🥨", "colour": "#c0392b"},
    "soul_food": {"label": "Soul Food", "emoji": "🍗", "colour": "#8e44ad"},
    "louisiana_creole": {"label": "Louisiana Creole & Cajun", "emoji": "🦐", "colour": "#2980b9"},
    "eastern_european": {"label": "Eastern European", "emoji": "🥟", "colour": "#34495e"},
    "balkan": {"label": "Balkan", "emoji": "🥘", "colour": "#c0392b"},
    "central_asian": {"label": "Central Asian", "emoji": "🍢", "colour": "#16a085"},
    "gulf_arabian": {"label": "Gulf Arabian & Iraqi", "emoji": "🍚", "colour": "#f39c12"},
    "baltic": {"label": "Baltic", "emoji": "🐟", "colour": "#2980b9"},
    "latin_american": {"label": "Latin American", "emoji": "🌽", "colour": "#27ae60"},
    "burmese": {"label": "Burmese (Myanmar)", "emoji": "🍜", "colour": "#e67e22"},
    "lao": {"label": "Lao (Laos)", "emoji": "🍚", "colour": "#16a085"},
    "cambodian": {"label": "Cambodian (Khmer)", "emoji": "🍲", "colour": "#8e44ad"},
}

NEW_DISHES: dict[str, list[str]] = {
    "peruvian": [
        "Ceviche", "Beef Lomo Saltado", "Chicken Aji de Gallina", "Beef Anticuchos",
        "Causa Rellena", "Papa a la Huancaína", "Rocoto Relleno", "Chupe de Camarones",
        "Chicken Arroz con Pollo", "Tacu Tacu", "Beef Pachamanca", "Chicha Morada",
        "Picarones", "Suspiro a la Limeña", "Alfajores", "Chicken Tamales Peruanos",
        "Escabeche de Pescado", "Choclo con Queso", "Parihuela", "Beef Seco de Res",
        "Beef Carapulcra", "Beef Tallarín Saltado", "Chicken Juane", "Ocopa",
        "Solterito Salad", "Leche de Tigre", "Turrón de Doña Pepa", "Mazamorra Morada",
        "Humitas", "Beef Chicharrón", "Chifa Arroz Chaufa", "Chifa Tallarín Saltado",
        "Pollo a la Brasa",
    ],
    "portuguese": [
        "Bacalhau à Brás", "Caldo Verde", "Pastéis de Nata", "Beef Francesinha",
        "Arroz de Marisco", "Beef Cozido à Portuguesa", "Beef Bifana",
        "Sardinhas Assadas", "Polvo à Lagareiro", "Açorda", "Beef Alcatra",
        "Beef Rojões de Vitela", "Chicken Piri Piri", "Pão de Ló", "Ovos Moles",
        "Queijo da Serra", "Beef Empadão", "Beef Alheira", "Arroz Doce", "Filhoses",
        "Beef Cataplana", "Amêijoas à Bulhão Pato", "Chicken Piri Piri Rice",
        "Beef Espetada", "Pastel de Bacalhau", "Bola de Berlim", "Toucinho do Céu",
        "Caldeirada de Peixe",
    ],
    "russian": [
        "Beef Borscht", "Beef Stroganoff", "Beef Pelmeni", "Chicken Olivier Salad",
        "Blini", "Beef Pirozhki", "Solyanka", "Beef Golubtsy", "Shchi", "Beef Kotleta",
        "Vinegret Salad", "Okroshka", "Syrniki", "Beef Stroganina", "Kvass",
        "Chicken Kiev", "Herring Under a Fur Coat", "Beef Kholodets", "Draniki",
        "Beef Manti Russian", "Beef Plov", "Medovik Cake", "Blini with Caviar",
        "Kissel", "Pryaniki", "Chicken Solyanka", "Ukha (Fish Soup)",
    ],
    "polish": [
        "Beef Bigos", "Beef Pierogi", "Beef Gołąbki", "Barszcz", "Żurek",
        "Chicken Kotlet z Kurczaka", "Placki Ziemniaczane", "Beef Flaczki",
        "Chicken Rosół", "Kopytka", "Sernik", "Makowiec", "Paczki", "Beef Golonka",
        "Oscypek Cheese", "Chłodnik", "Beef Zrazy", "Beef Kiełbasa Wołowa",
        "Chicken Kotlet Drobiowy", "Kluski Śląskie", "Beef Bigos Myśliwski",
        "Sledzie w Śmietanie", "Faworki", "Beef Gulasz",
    ],
    "hungarian": [
        "Beef Goulash", "Chicken Paprikash", "Beef Töltött Káposzta", "Lángos",
        "Dobos Torte", "Beef Pörkölt", "Halászlé", "Beef Gulyásleves", "Kürtőskalács",
        "Chicken Rántott Csirke", "Beef Székelygulyás", "Somloi Galuska",
        "Túrós Csusza", "Beef Pacal Pörkölt", "Gesztenyepüré", "Rétes",
        "Beef Rakott Krumpli", "Palacsinta", "Beef Debreceni Sausage",
    ],
    "argentinian": [
        "Beef Asado", "Beef Empanadas", "Beef Milanesa", "Chimichurri Steak",
        "Provoleta", "Beef Choripán", "Locro", "Dulce de Leche", "Alfajores Argentinos",
        "Beef Matambre", "Beef Vacío", "Beef Bife de Chorizo", "Beef Puchero",
        "Beef Carbonada", "Beef Milanesa Napolitana", "Facturas",
        "Beef Asado de Tira", "Chicken Empanadas Argentinas", "Beef Sorrentinos",
        "Torta Rogel", "Beef Pastel de Papa", "Mate", "Beef Matambrito",
        "Beef Vitel Toné", "Beef Bondiola",
    ],
    "cuban": [
        "Beef Ropa Vieja", "Beef Picadillo Cubano", "Moros y Cristianos",
        "Beef Vaca Frita", "Chicken Fricasé", "Tostones", "Yuca con Mojo",
        "Beef Empanadas Cubanas", "Chicken Arroz con Pollo Cubano",
        "Beef Cuban Sandwich", "Flan Cubano", "Beef Tamal en Cazuela",
        "Chicken Croquetas Cubanas", "Beef Bistec de Palomilla", "Congrí",
        "Chicken Enchilado", "Beef Boliche", "Malanga Fritters",
        "Chicken Fricasé de Pollo", "Beef Pan con Beef",
    ],
    "egyptian": [
        "Koshari", "Ful Medames", "Ta'ameya", "Beef Molokhia", "Chicken Fattah",
        "Beef Kofta Egyptian", "Mahshi", "Beef Hawawshi", "Beef Shawarma Egyptian",
        "Om Ali", "Basbousa", "Konafa", "Beef Bamia", "Baladi Bread",
        "Roz bel Laban", "Sayadeya", "Chicken Shish Tawook Egyptian",
        "Beef Fattah", "Dukkah", "Qatayef",
    ],
    "pakistani_bangladeshi": [
        "Beef Nihari", "Chicken Karahi", "Beef Seekh Kebab Pakistani", "Beef Haleem",
        "Sindhi Biryani", "Beef Kunna", "Beef Chapli Kebab", "Chicken Tikka Pakistani",
        "Chicken Sajji", "Beef Kofta Curry Pakistani", "Beef Aloo Keema",
        "Chana Chaat", "Gol Gappay", "Halwa Puri", "Chicken Korma Pakistani",
        "Beef Paya", "Lassi Pakistani", "Beef Bihari Kebab", "Fish Bhuna Bangladeshi",
        "Chicken Bhuna", "Beef Rezala", "Shorshe Ilish", "Chicken Roast Bengali",
        "Beef Kala Bhuna", "Panta Bhat", "Mishti Doi", "Rasgulla Bengali",
    ],
    "scandinavian": [
        "Beef Köttbullar", "Gravlax", "Beef Pytt i Panna", "Beef Frikadeller",
        "Rødgrød med Fløde", "Beef Biff Lindström", "Beef Kjøttkaker",
        "Lamb Fårikål", "Rakfisk", "Lefse", "Kanelbullar", "Beef Medisterpølse",
        "Æbleskiver", "Beef Labskovs", "Beef Roast Dinner Danish", "Princess Cake",
        "Beef Wallenbergare", "Beef Raggmunk", "Janssons Frestelse",
        "Chicken Kyllingsalat",
    ],
    "nigerian_west_african": [
        "Beef Jollof Rice", "Chicken Jollof Rice", "Egusi Soup", "Beef Suya",
        "Chicken Suya", "Beef Pepper Soup", "Efo Riro", "Beef Fufu and Soup",
        "Chicken Moin Moin", "Akara", "Puff Puff", "Beef Ogbono Soup", "Beef Nkwobi",
        "Beef Asun", "Chicken Yam Porridge", "Kelewele", "Waakye",
        "Beef Banku and Okra Stew", "Beef Groundnut Soup", "Beef Ewa Agoyin",
        "Zobo Drink", "Beef Kilishi", "Chin Chin",
    ],
    "south_african": [
        "Beef Bobotie", "Beef Boerewors", "Chicken Peri-Peri South African",
        "Beef Bunny Chow", "Beef Potjiekos", "Chakalaka", "Beef Biltong",
        "Malva Pudding", "Beef Sosaties", "Beef Pap en Vleis", "Chicken Bunny Chow",
        "Beef Denningvleis", "Melktert", "Koeksisters", "Beef Frikkadels",
        "Chicken Peri-Peri South Africa", "Beef Droëwors", "Umngqusho", "Vetkoek",
        "Beef Potjie Stew",
    ],
    "australian": [
        "Beef Meat Pie", "Lamington", "Pavlova", "Beef Sausage Roll",
        "Vegemite Toast", "Anzac Biscuits", "Chicken Parma", "Beef Damper Bread",
        "Fairy Bread", "Beef Sausage Sizzle", "Tim Tam Slam", "Australian Beef Steak",
        "Chiko Roll", "Beef Rissoles", "Pumpkin Scones",
    ],
    "hawaiian": [
        "Beef Loco Moco", "Fish Poke Bowl", "Beef Kalua", "Chicken Huli-Huli",
        "Beef Laulau", "Beef Musubi", "Malasadas", "Haupia", "Beef Poke",
        "Beef Katsu Hawaiian", "Lomi Lomi Salmon", "Chicken Adobo Hawaiian Style",
        "Beef Plate Lunch", "Shave Ice", "Beef Manapua",
    ],
    "sri_lankan": [
        "Chicken Kottu Roti", "Beef Curry Sri Lankan", "Fish Ambul Thiyal",
        "Chicken String Hoppers", "Beef Lamprais", "Dhal Curry", "Coconut Sambol",
        "Chicken Devilled", "Beef Curry with Roti", "Hoppers (Appa)", "Watalappan",
        "Chicken Curry Sri Lankan", "Beef Pittu", "Fish Cutlets", "Parippu",
    ],
    "austrian": [
        "Beef Wiener Schnitzel", "Beef Tafelspitz", "Sachertorte", "Apfelstrudel",
        "Kaiserschmarrn Austrian", "Beef Gulasch Austrian", "Käsespätzle Austrian",
        "Semmelknödel Austrian", "Beef Zwiebelrostbraten", "Salzburger Nockerl",
        "Topfenknödel", "Palatschinken Austrian", "Linzer Torte",
        "Beef Rindsuppe", "Marillenknödel", "Chicken Backhendl", "Gugelhupf",
        "Beef Krautfleisch", "Powidltascherl", "Wiener Melange",
    ],
    "soul_food": [
        "Sweet Potato Pie", "Peach Cobbler", "Buttermilk Biscuits", "Fried Catfish",
        "Banana Pudding", "Hoppin' John", "Beef Oxtails", "Smothered Chicken",
        "Candied Yams", "Beef Neck Bones", "Beef Liver and Onions", "Fried Okra",
        "Cornbread Dressing", "Deviled Eggs", "Succotash", "Red Velvet Cake",
        "Beef Short Ribs Soul Style", "Watermelon Salad", "Beef Smothered Steak",
        "Chicken and Dumplings Soul Style",
    ],
    "louisiana_creole": [
        "Chicken Jambalaya", "Beef Jambalaya", "Chicken Gumbo", "Seafood Gumbo",
        "Chicken Étouffée", "Beignets", "Beef Po' Boy", "Shrimp Po' Boy",
        "Cajun Crawfish Boil", "Blackened Catfish", "Red Beans and Rice",
        "Beef Muffuletta", "Shrimp Creole", "King Cake", "Pralines",
        "Beef Andouille Jambalaya", "Crawfish Étouffée", "Beef Dirty Rice",
        "Maque Choux", "Beef Grillades and Grits",
    ],
    "eastern_european": [
        "Beef Borscht Ukrainian", "Beef Holubtsi", "Beef Svíčková", "Beef Guláš Czech",
        "Beef Vareniki", "Chicken Kyiv", "Beef Deruny", "Trdelník", "Kolache",
        "Beef Segedínský Guláš", "Halušky", "Beef Kapustnica", "Medovik Ukrainian",
        "Beef Zrazy Ukrainian", "Syrniki Ukrainian", "Beef Nalysnyky", "Kutia",
    ],
    "balkan": [
        "Beef Ćevapi", "Beef Sarma", "Burek", "Beef Musaka Balkan", "Ajvar",
        "Beef Pljeskavica", "Chicken Piletina na Žaru", "Beef Karađorđeva Šnicla",
        "Beef Punjena Paprika", "Tarator", "Banitsa", "Beef Gibanica Balkan",
        "Beef Chorba Balkan", "Kajmak", "Palačinke Balkan", "Beef Ražnjići",
        "Beef Mititei Romanian", "Beef Sarmale Romanian", "Beef Ciorbă Romanian",
    ],
    "central_asian": [
        "Beef Plov", "Beef Manti", "Beef Lagman", "Beef Shashlik", "Beef Samsa",
        "Chicken Lagman", "Beef Beshbarmak", "Baursak", "Uzbek Non Bread",
        "Chicken Plov", "Beef Kazy Style", "Kurt", "Chak-Chak", "Beef Norin",
        "Beef Kuurdak", "Achichuk Salad", "Katyk", "Central Asian Green Tea",
    ],
    "gulf_arabian": [
        "Beef Kabsa Saudi", "Chicken Machboos Bahraini", "Beef Harees",
        "Chicken Thareed", "Beef Ouzi Gulf", "Beef Iraqi Kubba", "Beef Iraqi Dolma",
        "Masgouf Grilled Fish", "Luqaimat", "Beef Iraqi Tashreeb",
        "Kleicha Date Cookies", "Gahwa Arabic Coffee", "Khubz Gulf Bread",
        "Stuffed Dates", "Chicken Iraqi Biryani", "Beef Iraqi Kebab",
    ],
    "baltic": [
        "Beef Cepelinai", "Baltic Rye Bread", "Beef Pelēkie Zirņi", "Kama",
        "Šaltibarščiai", "Beef Koldūnai", "Kissel Baltic", "Smoked Fish Baltic",
        "Beef Šašlykas Baltic", "Sklandrausis", "Kūčiukai", "Šakotis",
    ],
    "latin_american": [
        "Beef Bandeja Paisa", "Chilean Beef Empanada", "Beef Pabellón Criollo",
        "Beef Pupusas", "Beef Arepas Venezuelan", "Chilean Beef Cazuela",
        "Chicken Ajiaco Colombian", "Beef Sancocho Colombian",
        "Chilean Beef Pastel de Choclo", "Beef Hallacas Venezuelan",
        "Beef Pepián Guatemalan", "Gallo Pinto Costa Rican", "Beef Vigorón Nicaraguan",
        "Beef Baleada Honduran", "Mangu Dominican", "Beef Arepas de Choclo Colombian",
        "Beef Completo Chilean", "Chilean Beef Charquicán",
    ],
    "burmese": [
        "Mohinga", "Chicken Ohn No Khao Swe", "Lahpet Thoke", "Beef Shan Noodles",
        "Chicken Nan Gyi Thoke", "Chicken Danbauk", "Mont Lin Ma Yar", "Samusa Thoke",
        "Chicken Kyethar Hin", "Htamin Jin", "A-Kyaw Fritters", "Beef Burmese Curry",
        "Burmese Falooda", "Shwe Yin Aye",
    ],
    "lao": [
        "Lao Larb", "Tam Mak Hoong", "Khao Piak Sen", "Lao Sticky Rice",
        "Mok Pa Fish", "Sai Oua Lao Sausage", "Or Lam Stew", "Khao Soi Lao",
        "Naem Khao", "Ping Kai Grilled Chicken", "Lao Chicken Curry",
        "Khao Jee Bread", "Lao Coffee",
    ],
    "cambodian": [
        "Fish Amok", "Beef Lok Lak", "Nom Banh Chok Fish Noodles",
        "Chicken Khmer Curry", "Beef Bai Sach Chrouk", "Beef Khmer Red Curry",
        "Nom Krok", "Trey Jien Fried Fish", "Somlar Machu Sour Soup",
        "Khmer Iced Coffee", "Beef Khmer Char Kroeung", "Grilled Squid Khmer",
        "Nom Kom",
    ],
}

# name -> explicit protein override for the second-expansion dishes.
NEW_PROTEIN_OVERRIDES = {
    "Causa Rellena": "vegetarian", "Papa a la Huancaína": "vegetarian",
    "Chicha Morada": "vegetarian", "Picarones": "vegetarian",
    "Suspiro a la Limeña": "vegetarian", "Alfajores": "vegetarian",
    "Choclo con Queso": "vegetarian", "Solterito Salad": "vegetarian",
    "Turrón de Doña Pepa": "vegetarian", "Mazamorra Morada": "vegetarian",
    "Humitas": "vegetarian", "Caldo Verde": "vegetarian", "Pastéis de Nata": "vegetarian",
    "Pão de Ló": "vegetarian", "Ovos Moles": "vegetarian", "Queijo da Serra": "vegetarian",
    "Arroz Doce": "vegetarian", "Filhoses": "vegetarian", "Toucinho do Céu": "vegetarian",
    "Blini": "vegetarian", "Vinegret Salad": "vegetarian", "Okroshka": "vegetarian",
    "Syrniki": "vegetarian", "Kvass": "vegetarian", "Draniki": "vegetarian",
    "Medovik Cake": "vegetarian", "Kissel": "vegetarian", "Pryaniki": "vegetarian",
    "Barszcz": "vegetarian", "Placki Ziemniaczane": "vegetarian", "Kopytka": "vegetarian",
    "Sernik": "vegetarian", "Makowiec": "vegetarian", "Paczki": "vegetarian",
    "Oscypek Cheese": "vegetarian", "Chłodnik": "vegetarian", "Faworki": "vegetarian",
    "Lángos": "vegetarian", "Dobos Torte": "vegetarian", "Kürtőskalács": "vegetarian",
    "Somloi Galuska": "vegetarian", "Gesztenyepüré": "vegetarian", "Rétes": "vegetarian",
    "Palacsinta": "vegetarian", "Provoleta": "vegetarian", "Locro": "vegetarian",
    "Dulce de Leche": "vegetarian", "Alfajores Argentinos": "vegetarian",
    "Facturas": "vegetarian", "Torta Rogel": "vegetarian", "Mate": "vegetarian",
    "Moros y Cristianos": "vegetarian", "Tostones": "vegetarian",
    "Yuca con Mojo": "vegetarian", "Flan Cubano": "vegetarian",
    "Congrí": "vegetarian", "Malanga Fritters": "vegetarian",
    "Koshari": "vegetarian", "Ful Medames": "vegetarian", "Ta'ameya": "vegetarian",
    "Om Ali": "vegetarian", "Basbousa": "vegetarian", "Konafa": "vegetarian",
    "Baladi Bread": "vegetarian", "Roz bel Laban": "vegetarian", "Dukkah": "vegetarian",
    "Qatayef": "vegetarian",
    "Chana Chaat": "vegetarian", "Gol Gappay": "vegetarian", "Halwa Puri": "vegetarian",
    "Lassi Pakistani": "vegetarian", "Mishti Doi": "vegetarian",
    "Rasgulla Bengali": "vegetarian", "Panta Bhat": "vegetarian",
    "Gravlax": "seafood", "Rødgrød med Fløde": "vegetarian", "Rakfisk": "seafood",
    "Lefse": "vegetarian", "Kanelbullar": "vegetarian", "Æbleskiver": "vegetarian",
    "Princess Cake": "vegetarian", "Janssons Frestelse": "seafood",
    "Egusi Soup": "vegetarian", "Akara": "vegetarian", "Puff Puff": "vegetarian",
    "Kelewele": "vegetarian", "Waakye": "vegetarian", "Zobo Drink": "vegetarian",
    "Chin Chin": "vegetarian", "Chakalaka": "vegetarian", "Malva Pudding": "vegetarian",
    "Melktert": "vegetarian", "Koeksisters": "vegetarian", "Umngqusho": "vegetarian",
    "Vetkoek": "vegetarian", "Lamington": "vegetarian", "Pavlova": "vegetarian",
    "Vegemite Toast": "vegetarian", "Anzac Biscuits": "vegetarian",
    "Beef Damper Bread": "vegetarian", "Fairy Bread": "vegetarian",
    "Tim Tam Slam": "vegetarian", "Pumpkin Scones": "vegetarian",
    "Malasadas": "vegetarian", "Haupia": "vegetarian", "Shave Ice": "vegetarian",
    "Dhal Curry": "vegetarian", "Coconut Sambol": "vegetarian", "Hoppers (Appa)": "vegetarian",
    "Watalappan": "vegetarian", "Parippu": "vegetarian",
    "Sachertorte": "vegetarian", "Apfelstrudel": "vegetarian",
    "Salzburger Nockerl": "vegetarian", "Topfenknödel": "vegetarian",
    "Linzer Torte": "vegetarian", "Marillenknödel": "vegetarian",
    "Gugelhupf": "vegetarian", "Powidltascherl": "vegetarian",
    "Wiener Melange": "vegetarian", "Kaiserschmarrn Austrian": "vegetarian",
    "Käsespätzle Austrian": "vegetarian", "Semmelknödel Austrian": "vegetarian",
    "Palatschinken Austrian": "vegetarian", "Deviled Eggs": "egg",
    "Sweet Potato Pie": "vegetarian", "Peach Cobbler": "vegetarian",
    "Buttermilk Biscuits": "vegetarian", "Banana Pudding": "vegetarian",
    "Hoppin' John": "vegetarian", "Candied Yams": "vegetarian",
    "Fried Okra": "vegetarian", "Cornbread Dressing": "vegetarian",
    "Succotash": "vegetarian", "Red Velvet Cake": "vegetarian",
    "Watermelon Salad": "vegetarian",
    "Beignets": "vegetarian", "King Cake": "vegetarian", "Pralines": "vegetarian",
    "Maque Choux": "vegetarian",
    "Trdelník": "vegetarian", "Kolache": "vegetarian", "Halušky": "vegetarian",
    "Medovik Ukrainian": "vegetarian", "Syrniki Ukrainian": "vegetarian",
    "Kutia": "vegetarian",
    "Ajvar": "vegetarian", "Tarator": "vegetarian", "Banitsa": "vegetarian",
    "Kajmak": "vegetarian", "Palačinke Balkan": "vegetarian",
    "Baursak": "vegetarian", "Uzbek Non Bread": "vegetarian", "Kurt": "vegetarian",
    "Chak-Chak": "vegetarian", "Achichuk Salad": "vegetarian", "Katyk": "vegetarian",
    "Central Asian Green Tea": "vegetarian",
    "Kleicha Date Cookies": "vegetarian", "Gahwa Arabic Coffee": "vegetarian",
    "Khubz Gulf Bread": "vegetarian", "Stuffed Dates": "vegetarian",
    "Luqaimat": "vegetarian",
    "Baltic Rye Bread": "vegetarian", "Kama": "vegetarian",
    "Šaltibarščiai": "vegetarian", "Kissel Baltic": "vegetarian",
    "Sklandrausis": "vegetarian", "Kūčiukai": "vegetarian", "Šakotis": "vegetarian",
    "Gallo Pinto Costa Rican": "vegetarian", "Mangu Dominican": "vegetarian",
    "Lahpet Thoke": "vegetarian", "Mont Lin Ma Yar": "vegetarian",
    "Samusa Thoke": "vegetarian", "Htamin Jin": "vegetarian",
    "A-Kyaw Fritters": "vegetarian", "Burmese Falooda": "vegetarian",
    "Shwe Yin Aye": "vegetarian",
    "Tam Mak Hoong": "vegetarian", "Lao Sticky Rice": "vegetarian",
    "Khao Jee Bread": "vegetarian", "Lao Coffee": "vegetarian",
    "Nom Krok": "vegetarian", "Khmer Iced Coffee": "vegetarian",
    "Nom Kom": "vegetarian",
    "Strawberry Jam": "vegetarian", "Grape Jelly": "vegetarian",
    "Dill Pickles": "vegetarian", "Bread and Butter Pickles": "vegetarian",
    "Homemade Yogurt": "vegetarian", "Sourdough Bread": "vegetarian",
    "Dinner Rolls": "vegetarian", "Gelato": "vegetarian",
}
PROTEIN_OVERRIDES.update(NEW_PROTEIN_OVERRIDES)

EXTRA_DISHES_EXISTING_CUISINES: dict[str, list[str]] = {
    "indian": [
        "Chicken Do Pyaza", "Mutton Do Pyaza", "Chicken 65", "Gobi Manchurian",
        "Paneer Tikka", "Hara Bhara Kebab", "Dahi Bhalla", "Mutton Laal Maas",
        "Gatte ki Sabzi", "Ker Sangri", "Dal Baati Churma", "Litti Chokha",
        "Bengali Fish Curry (Macher Jhol)", "Shorshe Maach", "Bengali Aloo Posto",
        "Luchi", "Cholar Dal", "Mishti Doi Bengali", "Rasabali", "Undhiyu",
        "Dhokla Khaman", "Thepla", "Handvo", "Sev Tameta", "Kadhi Pakora",
        "Malabar Fish Curry", "Appam with Stew", "Kerala Beef Fry",
        "Meen Pollichathu", "Puttu Kadala Curry", "Avial", "Olan", "Thoran",
        "Chettinad Chicken", "Pondicherry Beef Curry", "Hyderabadi Beef Haleem",
        "Mirchi ka Salan", "Bagara Baingan", "Double ka Meetha", "Qubani ka Meetha",
        "Sheer Khurma", "Kashmiri Lamb Rogan Josh", "Yakhni Pulao",
        "Dum Aloo Kashmiri", "Modur Pulav", "Amritsari Chole", "Sarson ka Saag",
        "Makki di Roti", "Punjabi Lassi", "Butter Naan", "Peshawari Naan",
        "Chicken Rara", "Chicken Malai Handi", "Egg Bhurji", "Egg Curry Anda",
        "Beef Nihari Indian", "Beef Paya Curry", "Chicken 65 Dry",
        "Manchurian Chicken", "Chilli Chicken", "Gobi 65", "Paneer 65",
        "Aloo Methi", "Karela Sabzi", "Lauki Sabzi", "Palak Corn",
        "Vegetable Kolhapuri", "Malvani Fish Curry", "Solkadhi", "Bombil Fry",
        "Prawn Curry Goan", "Beef Sorpotel", "Goan Chicken Vindaloo",
        "Cafreal Chicken",
    ],
    "chinese": [
        "Beef Chow Mein Cantonese", "Chicken Lo Mein", "Beef Cheung Fun",
        "Shrimp Har Gow", "Beef Black Pepper Beef", "Chicken Orange Peel Chicken",
        "Beef Sichuan Dry-Fried Green Beans", "Chicken General Tso Tofu",
        "Beef Hunan Beef", "Chicken Moo Goo Gai Pan", "Beef Broccoli Beef",
        "Shrimp Egg Foo Young", "Chicken Egg Foo Young", "Beef Chinese Beef Stew",
        "Chicken Three Cup Chicken", "Beef Dry Fried String Beans",
        "Chicken Peking Chicken", "Beef Chinese BBQ Beef Skewers",
        "Chicken Steamed Chicken with Ginger", "Beef Braised Beef Tendon",
        "Chicken Chongqing Spicy Chicken", "Beef Yunnan Beef Noodles",
        "Chicken Hainanese Chicken Rice", "Beef Shanghai Beef Noodle Soup",
        "Chicken Drunken Chicken Shanghai Style", "Beef Red Braised Beef",
        "Chicken Salt and Pepper Chicken", "Lamb Cumin Lamb Skewers",
        "Lamb Xinjiang Pilaf", "Beef Dongbei Beef Stew", "Beef Sichuan Beef Noodles",
        "Chicken Taiwanese Popcorn Chicken", "Beef Three Cup Beef",
        "Chicken Hakka Salt Baked Chicken", "Beef Cantonese Beef Chow Fun",
        "Chicken Chinese Fried Chicken Wings",
        "Sweet and Sour Carp", "Beef Lion's Head Meatballs",
        "Squirrel-Shaped Mandarin Fish", "Beef Dongpo Style",
        "West Lake Vinegar Fish", "Buddha Jumps Over the Wall", "Oyster Omelette",
        "Stinky Mandarin Fish", "Beef Huangshan Stew",
    ],
    "italian": [
        "Chicken Piccata", "Beef Marsala", "Spaghetti Puttanesca", "Fusilli al Pesto",
        "Rigatoni alla Norma", "Beef Bollito Misto", "Chicken Involtini",
        "Beef Tagliata", "Panzerotti", "Stracciatella di Bufala", "Burrata Caprese",
        "Beef Pizzaiola", "Farfalle al Salmone", "Torta di Riso", "Zabaglione",
        "Struffoli", "Pandoro", "Colomba di Pasqua", "Beef Spezzatino",
        "Chicken Spezzatino", "Beef Bresaola Salad",
    ],
    "japanese": [
        "Beef Sukiyaki Don", "Beef Wagyu Steak", "Beef Yakitori Negima",
        "Chicken Tsukune", "Beef Gyu-tan", "Beef Curry Udon", "Chicken Curry Udon",
        "Beef Tantanmen", "Beef Tsukemen", "Chicken Paitan Ramen", "Beef Aburi Sushi",
        "Salmon Sashimi", "Tuna Sashimi", "Chicken Torikatsu", "Beef Sirloin Teppanyaki",
        "Chicken Teppanyaki", "Beef Motsuyaki", "Chicken Zaru Udon", "Beef Nikuman",
        "Chicken Karaage Don", "Beef Gyukatsu Don", "Salmon Onigiri", "Ume Onigiri",
    ],
    "french": [
        "Beef Daube Provençale", "Chicken Vol-au-Vent", "Beef Pâté en Croûte",
        "Chicken Ballotine", "Beef Entrecôte", "Beef Chateaubriand",
        "Salade Composée", "Beef Tarte Flambée", "Quiche aux Champignons",
        "Chicken Suprême", "Beef Filet Mignon Sauce", "Beef Bordelaise",
        "Chicken Provençale", "Beef Crepe Grand Marnier", "Tarte aux Pommes",
        "Île Flottante", "Paris-Brest", "Opéra Cake", "Kouign-Amann",
    ],
    "mexican": [
        "Chicken Pozole Blanco", "Beef Chilaquiles", "Chicken Sopa de Lima",
        "Beef Tostadas de Tinga", "Chicken Enfrijoladas", "Beef Machaca",
        "Beef Arrachera", "Chicken Tacos Dorados", "Beef Taquitos",
        "Chicken Sopes Verdes", "Beef Milanesa Mexicana", "Chicken Caldo Tlalpeño",
        "Beef Molletes", "Chicken Pambazos", "Beef Gorditas de Chicharrón",
        "Chicken Tamal Verde", "Beef Tamal Rojo", "Chicken Salbutes",
        "Beef Panuchos",
    ],
    "lebanese": [
        "Chicken Musakhan Rolls", "Beef Kofta Skewers", "Chicken Shish Tawook Plate",
        "Beef Lahm Bi Ajeen", "Chicken Fatteh", "Beef Ouzi Rice",
        "Chicken Freekeh Pilaf", "Beef Yalanji", "Chicken Samke Harra",
        "Beef Kabab Hindi", "Beef Kibbeh Bil Sanieh", "Chicken Riz a Djaj",
        "Beef Kousa Mahshi", "Chicken Bamia", "Beef Fasolia",
        "Beef Sfeeha Baalbakiya", "Beef Awarma", "Chicken Shakriyeh",
        "Beef Mloukhieh",
    ],
    "thai": [
        "Chicken Jungle Curry", "Beef Kua Kling", "Chicken Lemongrass Chicken",
        "Beef Grilled Beef Salad", "Thai Pineapple Fried Rice",
        "Thai Mango Salad", "Thai Pumpkin Curry", "Chicken Thai Basil Fried Rice",
        "Beef Thai Omelette Rice", "Chicken Thai Coconut Soup",
    ],
    "korean": [
        "Beef Kkori Gomtang", "Korean Fried Chicken Wings", "Beef Galbijjim",
        "Chicken Dakbokkeumtang", "Chicken Gangjeong", "Beef Yukgaejang",
        "Beef Yukpo", "Chicken Bulgogi", "Kimchi Fried Rice",
    ],
    "american": [
        "Beef Sliders", "Beef Chicken-Fried Steak", "Southern Fried Chicken",
        "Beef Corn Dogs", "Beef Meatball Subs", "Chicken Club Sandwich",
        "Chicken Bacon Lettuce Tomato Sandwich", "Beef Texas Chili",
        "Beef Salisbury Steak", "Chicken Pot Pie", "Beef Pot Pie",
        "Chicken Fried Chicken Sandwich", "Chicken Gumbo Ya-Ya", "Beef Texas Toast",
        "Beef Sloppy Joe Sliders", "Chicken Ranch Sandwich",
        "Beef Chili Cheese Fries", "Chicken Cobb Wrap", "New England Clam Bake",
        "Southern Biscuits", "Beef Country Fried Steak", "Beef American Chop Suey",
        "Chicken Noodle Soup",
    ],
    "spanish": [
        "Beef Callos a la Madrileña", "Chicken Pollo al Ajillo",
        "Beef Solomillo al Whisky", "Chicken Pisto con Huevo", "Beef Chuletón",
        "Beef Rabas", "Chicken Pollo Asado Spanish", "Beef Cocido Andaluz",
        "Chicken Empanadillas", "Chicken Arroz con Pollo Spanish",
    ],
    "turkish": [
        "Beef Hünkar Beğendi", "Tavuk Göğsü", "Chicken Piliç Şiş",
        "Beef Kuru Fasulye", "Chicken Tavuk Şiş", "Beef Adana Dürüm",
        "Chicken Iskender Tavuk", "Beef Çökertme Kebabı",
        "Chicken Turkish Chicken Wrap", "Beef Kavurma", "Ayva Tatlısı",
    ],
    "vietnamese": [
        "Beef Phở Xào", "Chicken Gà Nướng", "Beef Bún Bò Nam Bộ",
        "Chicken Cơm Gà", "Beef Bánh Hỏi", "Chicken Gỏi Gà",
        "Beef Lẩu Bò", "Chicken Cháo Gà", "Beef Nem Rán", "Chicken Bánh Mì Gà",
        "Beef Bò Né", "Beef Bún Đậu",
    ],
    "greek": [
        "Chicken Kotopoulo Lemonato", "Chicken Souvlaki Pita", "Beef Bifteki",
        "Chicken Gyro Wrap Plate", "Greek Honey Yogurt Cake",
        "Beef Giouvarlakia", "Chicken Spanakorizo",
    ],
    "german": [
        "Beef Sauerbraten Rhineland", "Chicken Hähnchen Schnitzel",
        "Beef Zwiebelrostbraten", "Chicken Hühnerfrikassee", "Beef Bouletten",
        "Chicken Currywurst Chicken", "Beef Tafelspitz",
        "Chicken Jägerschnitzel Chicken", "Beef Rinderbraten", "Apfelkuchen",
        "Beef Leipziger Allerlei", "Bienenstich Cake",
    ],
    "moroccan": [
        "Beef Moroccan Beef Skewers", "Chicken Bastilla Sweet",
        "Beef Moroccan Beef Couscous Royale", "Chicken Tagine with Almonds",
        "Zaalouk Carrot Style", "Moroccan Beet Salad", "Msemen Stuffed",
        "Moroccan Semolina Cookies",
    ],
    "british": [
        "Chicken Balti", "Beef Balti", "Chicken Coronation Chicken",
        "Beef and Ale Pie", "Chicken Tikka Sandwich", "Beef Faggots",
        "Treacle Tart", "Beef Cumberland Pie", "Parkin Cake",
    ],
    "indonesian_malaysian": [
        "Beef Rendang Padang", "Chicken Ayam Bakar", "Beef Semur",
        "Chicken Betutu", "Beef Sate Lilit", "Chicken Nasi Kuning", "Beef Empal",
        "Chicken Soto Betawi", "Kerak Telor",
    ],
    "filipino": [
        "Beef Nilaga", "Chicken Curry Filipino", "Beef Pares",
        "Chicken Pastil", "Chicken Binakol", "Beef Kaldereta Bicol",
        "Bicol Express", "Cassava Cake", "Puto",
    ],
    "persian": [
        "Beef Koobideh", "Chicken Barg", "Beef Soltani", "Ash-e Jow",
        "Noon Barbari",
    ],
    "ethiopian": [
        "Beef Siga Wat", "Chicken Doro Tibs", "Ethiopian Spiced Butter Popcorn",
        "Beef Kitfo Leb Leb", "Injera Firfir", "Ethiopian Timatim Salata",
    ],
    "caribbean": [
        "Beef Patties Trinidad", "Chicken Roti", "Trinidad Doubles",
        "Beef Pelau", "Chicken Pelau", "Fish Bake and Shark",
    ],
    "brazilian": [
        "Beef Picanha Skewers", "Chicken Coxinha Grande",
        "Brazilian Cheese Bread Balls", "Beef Rabada", "Chicken Galinhada",
        "Acai Bowl",
    ],
}
for _cid, _names in EXTRA_DISHES_EXISTING_CUISINES.items():
    DISHES.setdefault(_cid, []).extend(_names)

CUISINE_META.update(NEW_CUISINE_META)
for _cid, _names in NEW_DISHES.items():
    DISHES.setdefault(_cid, []).extend(_names)

# Genuine, one-line historical/cultural facts for the best-known "flagship"
# dishes across the whole collection. Deliberately not exhaustive -- only
# dishes with a fact I'm confident is real get one; everything else keeps
# the generic template description.
HISTORICAL_FACTS = {
    "Butter Chicken": "Invented at Delhi's Moti Mahal restaurant in the late 1940s, reportedly to use up leftover tandoori chicken in a rich tomato-butter gravy.",
    "Peking Duck": "Documented in imperial Beijing cuisine for centuries; the duck is traditionally air-dried and roasted until the skin lacquers to a crisp, glossy finish.",
    "Pizza Margherita": "Popular legend ties its tomato-mozzarella-basil colours to the Italian flag, supposedly made in 1889 for Queen Margherita of Savoy.",
    "Sushi Nigiri Platter": "Vinegared-rice nigiri-zushi developed in Edo-period (1603-1868) Tokyo as fast food for city workers, evolving from an older fermented-fish preservation method called narezushi.",
    "Pad Thai": "Actively promoted as a national dish by Prime Minister Plaek Phibunsongkhram's government in the 1930s-40s as part of a nationalist campaign to boost rice-noodle consumption.",
    "Kimchi": "Korea's kimchi-making tradition, gimjang, is documented for over a thousand years and was added to UNESCO's Intangible Cultural Heritage list in 2013.",
    "Paella Valenciana": "Originated as a labourers' field dish in the rice-growing region around Valencia; the original version uses rabbit, chicken, and green beans rather than seafood.",
    "Lamb Tacos al Pastor": "Descends from Lebanese immigrants' vertical shawarma spit-roasting technique, brought to central Mexico in the early 20th century and adapted with local chillies and pineapple.",
    "Hummus": "Chickpeas have been eaten in the Levant for millennia; the exact origin of blended hummus is disputed and claimed by multiple countries across the region.",
    "Ramen Shoyu": "Adapted from Chinese wheat noodles, ramen became widely popular across Japan only in the 20th century, with distinct regional broth styles emerging city by city.",
    "Croissant": "Evolved from the Austrian kipferl; French bakers developed the laminated, buttery version that became a defining French breakfast pastry.",
    "Coq au Vin": "A Burgundy classic built on the region's wine-braising tradition, traditionally using an older rooster (coq) slow-cooked until tender.",
    "Bibimbap": "Associated with the city of Jeonju, where a version using the region's fermented soybean paste and vegetables became especially renowned.",
    "Phở Bò (Beef)": "Likely emerged in early 20th-century Hanoi, blending French beef-broth cooking habits with Vietnamese rice-noodle and spice traditions.",
    "Beef Moussaka": "Popularised in its modern layered, béchamel-topped form by Greek chef Nikolaos Tselementes in the 1920s, who was influenced by French cuisine.",
    "Beef Feijoada": "Brazil's national dish, a bean-and-meat stew traditionally simmered for hours; its exact origins are debated but it has been a Brazilian staple for centuries.",
    "Ceviche": "Peru's national dish, made by 'cooking' raw fish in citrus acid; Peru's Ministry of Culture named 28 June National Ceviche Day.",
    "Butter Naan": "Naan is leavened flatbread traditionally baked against the wall of a clay tandoor oven, a technique documented across Persian and South Asian cooking for centuries.",
    "Beef Bourguignon": "A Burgundy peasant dish elevated to haute cuisine status in the 20th century, notably through Julia Child's influential 1961 cookbook.",
    "Tabbouleh": "A Levantine salad in which parsley, not bulgur, is the dominant ingredient by volume in the traditional recipe -- a common misconception outside the region.",
    "Beef Borscht": "A beet soup with roots across Eastern Europe, claimed as a national dish by Ukraine, Russia, and Poland alike, each with regional variations.",
    "Mole Poblano": "A complex sauce of dozens of ingredients including chocolate and chillies, associated with the city of Puebla and considered one of Mexico's most elaborate dishes.",
    "Chicken Tikka Masala": "Widely believed to have been invented by South Asian chefs in Britain, adapting tandoori chicken into a creamy tomato gravy to suit local tastes.",
    "Beef Wellington": "The dish's exact origin is debated, but it became a fixture of mid-20th-century British fine dining, wrapping beef fillet in pastry with a mushroom duxelles.",
    "Fish and Chips": "Became a working-class British staple after Jewish immigrants introduced fried-fish techniques in the 17th-18th centuries, later paired with fried potatoes.",
    "Beef Goulash": "A Hungarian herding dish, originally a simple beef-and-paprika stew cooked by cattle drovers over open fires on the plains.",
    "Beef Bacalhau à Brás": "Made from salted, dried cod (bacalhau) -- Portugal is said to have hundreds of documented ways to prepare it, reflecting its centuries-old fishing and preservation tradition.",
    "Chicken Adobo": "The Philippines' most iconic dish, whose name comes from the Spanish word for marinade, though the vinegar-based cooking method predates Spanish colonisation.",
    "Beef Rendang": "A slow-cooked Indonesian dish (particularly associated with the Minangkabau people of West Sumatra) traditionally made with beef, so no protein substitution was needed for this collection.",
    "Beef Char Siu": "Traditionally a Cantonese barbecued pork dish; this collection's beef version keeps the same signature honey-and-five-spice glaze technique.",
    "Doro Wat (Chicken)": "Often considered Ethiopia's national dish, simmered for hours in berbere spice blend; traditionally served with a hard-boiled egg and injera.",
    "Beef Empanadas": "Empanadas trace back to Spanish and Portuguese hand-pie traditions, later adapted across Latin America with regional fillings and pastry styles.",
    "Beef Asado": "Central to Argentine culture, asado refers to both the beef barbecue and the entire social gathering built around slow-grilling over wood or charcoal.",
    "Beef Rogan Josh": "An aromatic curry from Kashmir with Persian-influenced roots, its name likely derived from Persian words for 'red' and 'heat/passion' referring to its colour and spice.",
    "Chicken Karahi": "Named after the wok-like karahi pan it's cooked in, this Pakistani dish is typically prepared quickly with tomatoes, ginger, and green chillies over high heat.",
    "Beef Jollof Rice": "A West African rice dish whose 'best version' is a long-running friendly rivalry between Nigeria, Ghana, and other West African nations.",
    "Sweet and Sour Carp": "A Shandong classic showcasing one of China's 'Eight Culinary Traditions,' the northern coastal cuisine associated with Confucius's home province.",
    "Beef Lion's Head Meatballs": "A Jiangsu (Huaiyang cuisine) specialty of oversized braised meatballs, traditionally pork, named for their resemblance to a lion's head atop a 'mane' of cabbage.",
    "Squirrel-Shaped Mandarin Fish": "A Jiangsu dish where the fish is scored and fried to curl like a squirrel's tail, then coated in a sweet-sour sauce -- a Suzhou banquet classic.",
    "Beef Dongpo Style": "Named after Song-dynasty poet Su Dongpo, the original Zhejiang dish (Dongpo Pork) is a slow-braised, soy-and-wine glazed classic; this version uses beef.",
    "West Lake Vinegar Fish": "A Hangzhou (Zhejiang) dish of freshwater fish in a sweet-and-sour vinegar sauce, named for the West Lake where the fish was traditionally sourced.",
    "Buddha Jumps Over the Wall": "A luxurious Fujian stew of many meats and seafoods slow-simmered together, said to be named for an aroma so tempting a monk would jump a wall to eat it.",
    "Oyster Omelette": "A Fujian and Chaozhou coastal classic of egg and fresh oysters, now also a widely eaten Taiwanese night-market staple.",
    "Stinky Mandarin Fish": "An Anhui specialty in which fish is lightly fermented for several days before cooking, developing a strong smell but a prized, distinctive flavour once cooked.",
    "Beef Huangshan Stew": "A hearty braised dish from Anhui's mountainous Huangshan region, reflecting the province's tradition of slow-cooked, wild-ingredient country cooking.",
}

CATEGORY_KEYWORDS = [
    ("ice_cream", ["ice cream", "gelato", "kulfi", "bingsu", "kakigori", "shave ice",
                   "sorbet", "saffron ice cream"]),
    ("hot_drink", ["coffee", "cà phê", "mate", "karkade", "masala chai",
                   "turkish tea", "moroccan mint tea", "chamomile tea",
                   "wiener melange", "green tea", "gahwa"]),
    ("drink", ["lassi", "juice", "horchata", "agua fresca", "doogh", "ayran",
               "thandai", "falooda", "nimbu pani", "chicha morada", "sorrel",
               "kvass", "zobo", "sangria", "michelada", "drink"]),
    ("soupy_noodle", ["ramen", "phở", "pho bo", "pho ga", "udon noodle soup", "laksa",
                       "wonton noodle soup", "khao soi", "beef noodle soup",
                       "chicken noodle soup", "bún bò huế", "jjamppong", "hủ tiếu",
                       "shanghai beef noodle soup", "yukgaejang", "tantanmen",
                       "tsukemen", "paitan ramen"]),
    ("pasta", ["spaghetti", "fettuccine", "penne", "linguine", "orecchiette",
               "gnocchi", "lasagne", "cacio e pepe", "carbonara", "amatriciana",
               "trofie", "pasta", "puttanesca", "fusilli", "rigatoni", "farfalle",
               "tallarín"]),
    ("noodle", ["noodle", "chow mein", "chow fun", "lo mein", "pad thai", "pad see ew",
                "japchae", "dan dan", "zhajiangmian", "mì quảng", "mi quảng",
                "cao lầu", "chapchae", "pancit", "char kway teow", "mie goreng",
                "yakisoba", "udon", "soba", "cheung fun"]),
    ("curry", ["curry", "korma", "vindaloo", "tagine", "wat", "mole", "rendang",
               "gulai", "kadai", "chettinad", "xacuti", "aji de gallina", "panang",
               "massaman", "gaeng", "jungle curry", "pumpkin curry"]),
    ("stew", ["stew", "cassoulet", "goulash", "bourguignon", "braised", "gulaschsuppe",
              "caldereta", "mechado", "afritada", "adobo", "moqueca", "sauerbraten",
              "bigos", "locro", "puchero", "carbonada", "zrazy", "golubtsy",
              "kare-kare", "feijoada", "cocido", "fabada", "bulalo"]),
    ("soup", ["soup", "chowder", "shorba", "harira", "gumbo", "stracciatella",
              "minestrone", "ribollita", "vichyssoise", "bouillon", "consommé",
              "mulligatawny", "rasam", "sambar", "borscht", "shchi", "solyanka",
              "zurek", "barszcz", "caldo verde", "chupe", "parihuela",
              "pepper soup", "okroshka", "gomtang"]),
    ("vegetable", ["bharta", "gobi", "bhindi", "saag", "palak", "baingan",
                    "ratatouille", "caponata", "zaalouk", "collard", "eggplant",
                    "aubergine", "mustard greens", "spinach", "green beans",
                    "vegetable", "gado-gado", "avial", "thoran", "olan", "undhiyu",
                    "chakalaka", "kelewele", "pinakbet", "laing", "briam", "pisto",
                    "escalivada", "fava", "gemista", "egusi"]),
    ("pickle", ["kimchi", "pickle", "pickles", "achar", "torshi", "giardiniera", "sauerkraut"]),
    ("rice", ["rice", "biryani", "pulao", "fried rice", "risotto", "paella", "khao pad",
              "nasi", "congee", "khichdi", "sushi", "chirashi", "onigiri", "kimbap",
              "gyudon", "katsudon", "oyakodon", "don", "polo", "arroz", "jollof",
              "jambalaya", "khichuri", "biryani", "pilaf", "tahchin"]),
    ("bread", ["naan", "roti", "paratha", "puri", "bhatura", "kulcha", "bread",
               "baguette", "brioche", "focaccia", "ciabatta", "pretzel", "simit",
               "khobz", "pide", "manakish", "bánh mì", "bagel", "croissant",
               "pain au chocolat", "pão", "broa", "feteer", "baladi", "damper",
               "lefse", "malawach", "noon barbari", "dinner rolls", "khao jee"]),
    ("dumpling", ["dumpling", "gyoza", "baozi", "xiaolongbao", "wonton", "momo",
                  "manti", "mantou", "pierogi", "pelmeni", "vareniki",
                  "spring roll", "lumpia", "chả giò"]),
    ("appetizer", ["hummus", "baba ganoush", "muhammara", "labneh", "shanklish",
                   "taramasalata", "melitzanosalata", "skordalia", "bruschetta",
                   "dolma", "warak enab", "antipasto", "tapas", "samosa", "pakora",
                   "empanada", "causa", "papa a la huancaína", "gỏi cuốn", "kibbeh",
                   "edamame", "dukkah", "matbucha", "bourekas", "anticuchos",
                   "kofta"]),
    ("grill", ["kebab", "grill", "bbq", "tikka", "tandoori", "satay", "yakitori",
               "shish", "brochette", "churrasco", "picanha", "souvlaki", "gyro",
               "adana", "doner", "shawarma", "bulgogi", "galbi", "yakiniku",
               "jerk", "asado", "carne asada", "suya", "choripán"]),
    ("salad", ["salad", "tabbouleh", "fattoush", "panzanella", "som tum", "larb",
               "ceviche", "aguachile", "salade", "insalata", "horiatiki", "cobb",
               "waldorf", "caesar", "vinaigrette salad", "olivier salad"]),
    ("breakfast", ["breakfast", "omelette", "omurice", "chilaquiles",
                   "huevos rancheros", "shakshuka", "poha", "upma",
                   "menemen", "tamagoyaki", "kedgeree", "biscuits and gravy"]),
    ("street", ["street", "chaat", "vada pav", "pav bhaji", "bhel puri", "pani puri",
                "sev puri", "aloo tikki", "elote", "esquites", "takoyaki",
                "okonomiyaki", "banh xeo", "bánh xèo", "taco", "burrito", "nachos",
                "pupusas", "arepas", "samsa", "luqaimat", "burek", "baleada",
                "vigorón", "completo"]),
    ("fried", ["fried", "tempura", "katsu", "karaage", "croquetas", "fritto",
               "arancini", "sesame balls", "churros", "puff-puff", "picarones",
               "akara"]),
    ("dessert", ["cake", "pudding", "pie", "cookies", "brownies", "cheesecake",
                 "tart", "brûlée", "soufflé", "mochi", "dango", "mousse", "flan",
                 "baklava", "kunefe", "sütlaç", "halwa", "barfi", "gulab jamun",
                 "jalebi", "rasgulla", "rasmalai", "kheer", "payasam", "modak",
                 "eton mess", "trifle", "profiteroles", "éclair", "macarons",
                 "madeleines", "beignets", "cobbler", "quindim", "beijinho",
                 "brigadeiro", "kaiserschmarrn", "stollen", "lebkuchen", "s'mores",
                 "loukoumades", "galaktoboureko", "bougatsa", "chebakia", "sellou",
                 "sholeh zard", "faloodeh", "alfajores", "dulce de leche",
                 "medovik", "pryaniki", "sernik", "makowiec", "pączki", "basbousa",
                 "om ali", "konafa", "suspiro", "torta frita", "facturas",
                 "pavlova", "lamington", "malva pudding", "koeksisters",
                 "haupia", "watalappan", "turrón", "mazamorra", "dobos torte",
                 "kürtőskalács", "somloi galuska", "rétes", "palacsinta",
                 "jam", "jelly"]),
]


# Keywords that are intentionally matched as a substring/suffix rather than a
# whole word (e.g. "don" for Gyudon/Katsudon/Oyakodon rice bowls). Every other
# keyword is matched at word boundaries so short common words like "tea" or
# "mate" don't misfire inside unrelated words like "steak" or "Tomate".
_SUFFIX_OK = {"don"}


def _kw_match(keyword: str, lname: str) -> bool:
    if keyword in _SUFFIX_OK:
        return keyword in lname
    return re.search(rf"\b{re.escape(keyword)}\b", lname) is not None


def infer_protein(name: str) -> str:
    lname = name.lower()
    if name in PROTEIN_OVERRIDES:
        return PROTEIN_OVERRIDES[name]
    if _kw_match("duck", lname):
        return "duck"
    if any(_kw_match(k, lname) for k in ["chicken", "turkey"]):
        return "chicken"
    if _kw_match("lamb", lname):
        return "lamb"
    if any(_kw_match(k, lname) for k in ["mutton", "goat"]):
        return "mutton"
    if any(_kw_match(k, lname) for k in ["beef", "steak", "brisket", "oxtail"]):
        return "beef"
    if any(_kw_match(k, lname) for k in ["fish", "salmon", "tuna", "saltfish", "sardine",
                                          "cod", "bacalhau", "bacalao", "anchov", "lox",
                                          "carp", "catfish", "mandarin fish", "rakfisk",
                                          "gravlax"]):
        return "fish"
    if any(_kw_match(k, lname) for k in ["seafood", "shrimp", "prawn", "crab", "squid",
                                          "octopus", "clam", "lobster", "calamares", "pulpo",
                                          "mariscos", "camarones", "oyster", "frutti di mare",
                                          "vatapá", "acarajé", "bobó de camarão",
                                          "crawfish", "crayfish"]):
        return "seafood"
    if _kw_match("egg", lname):
        return "egg"
    return "mixed"


# Exact-name overrides for the handful of dishes the keyword classifier
# would otherwise get wrong (e.g. "Homemade Yogurt" has no dedicated
# category and would fall through to "Main Course").
CATEGORY_OVERRIDES = {
    "Homemade Yogurt": "breakfast",
}


def infer_category(name: str) -> str:
    if name in CATEGORY_OVERRIDES:
        return CATEGORY_OVERRIDES[name]
    lname = name.lower()
    if _kw_match("iced", lname):
        return "drink"
    for category, keywords in CATEGORY_KEYWORDS:
        if any(_kw_match(k, lname) for k in keywords):
            return category
    return "main"

CATEGORY_INFO = {
    "ice_cream": {"label": "Ice Cream & Frozen Treats", "emoji": "🍨", "technique": "Churning / freezing"},
    "hot_drink": {"label": "Hot Drinks", "emoji": "☕", "technique": "Brewing"},
    "drink": {"label": "Drinks", "emoji": "🥤", "technique": "Blending / mixing"},
    "soupy_noodle": {"label": "Soupy Noodles", "emoji": "🍜", "technique": "Long-simmered broth"},
    "pasta": {"label": "Pasta", "emoji": "🍝", "technique": "Boiling"},
    "noodle": {"label": "Noodles", "emoji": "🍝", "technique": "Boiling / stir-frying"},
    "curry": {"label": "Curry", "emoji": "🍛", "technique": "Simmering in spiced sauce"},
    "stew": {"label": "Stew", "emoji": "🍲", "technique": "Braising / simmering"},
    "soup": {"label": "Soup", "emoji": "🥣", "technique": "Simmering"},
    "vegetable": {"label": "Vegetables", "emoji": "🥬", "technique": "Sautéing / simmering"},
    "rice": {"label": "Rice Dish", "emoji": "🍚", "technique": "Steaming / sautéing"},
    "bread": {"label": "Bread", "emoji": "🍞", "technique": "Baking"},
    "dumpling": {"label": "Dumplings & Wraps", "emoji": "🥟", "technique": "Steaming / folding"},
    "appetizer": {"label": "Appetisers & Starters", "emoji": "🥙", "technique": "Assembling / light cooking"},
    "grill": {"label": "Grilled / BBQ", "emoji": "🔥", "technique": "Grilling"},
    "salad": {"label": "Salad", "emoji": "🥗", "technique": "Raw preparation"},
    "pickle": {"label": "Fermented / Pickled", "emoji": "🫙", "technique": "Fermentation"},
    "breakfast": {"label": "Breakfast", "emoji": "🍳", "technique": "Pan-cooking"},
    "street": {"label": "Street Food", "emoji": "🌮", "technique": "Street-food cookery"},
    "fried": {"label": "Fried", "emoji": "🍤", "technique": "Deep-frying"},
    "dessert": {"label": "Dessert", "emoji": "🍰", "technique": "Baking / confectionery"},
    "main": {"label": "Main Course", "emoji": "🍽️", "technique": "Sautéing"},
}

PROTEIN_LABELS = {
    "chicken": "Chicken", "duck": "Duck", "beef": "Beef", "lamb": "Lamb",
    "mutton": "Mutton/Goat", "fish": "Fish", "seafood": "Seafood", "egg": "Egg",
    "vegetarian": "Vegetarian", "mixed": "Mixed",
}


def normalize(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def search_url(base: str, query: str) -> str:
    return base + quote_plus(query)


def build_recipe(cuisine_id: str, name: str, index: int) -> dict:
    meta = CUISINE_META[cuisine_id]
    category = infer_category(name)
    cat_info = CATEGORY_INFO[category]
    protein = infer_protein(name)
    protein_label = PROTEIN_LABELS[protein]
    query = f"{name} {meta['label']} recipe"
    description = (
        f"{name} is a {cat_info['label'].lower()} from {meta['label']} cuisine"
        + (f", built around {protein_label.lower()}." if protein not in ("vegetarian", "mixed")
           else "." if protein == "mixed" else ", a vegetarian dish.")
    )
    historical_fact = HISTORICAL_FACTS.get(name)
    return {
        "id": f"recipe_{cuisine_id}_{index:04d}",
        "name": name,
        "cuisine": meta["label"],
        "cuisine_id": cuisine_id,
        "category": cat_info["label"],
        "category_id": category,
        "emoji": cat_info["emoji"],
        "protein": protein_label,
        "pork_free": True,
        "substitution_note": SUBSTITUTION_NOTES.get(name),
        "description": description,
        "historical_fact": historical_fact,
        "cooking_technique": cat_info["technique"],
        "wiki_title": name.split(" (")[0],
        "links": {
            "wikipedia": search_url("https://en.wikipedia.org/w/index.php?search=", name),
            "image_search": search_url("https://commons.wikimedia.org/w/index.php?search=", name),
            "video": search_url("https://www.youtube.com/results?search_query=", f"{name} recipe how to make"),
            "text_guide": search_url("https://www.google.com/search?q=", query),
        },
    }


def main() -> None:
    recipes = []
    seen_names: set[str] = set()
    for cuisine_id, names in DISHES.items():
        idx = 0
        for name in names:
            key = normalize(name)
            if key in seen_names:
                continue
            seen_names.add(key)
            idx += 1
            recipes.append(build_recipe(cuisine_id, name, idx))

    out = {
        "title": "World Recipe Collection",
        "description": (
            f"{len(recipes):,} real, named dishes from {len(CUISINE_META)} world cuisines. "
            "The entire collection is pork-free: any dish traditionally made with pork uses "
            "beef, lamb, or mutton instead, noted transparently wherever that substitution "
            "changes a well-known recipe."
        ),
        "total": len(recipes),
        "recipes": recipes,
    }
    OUT_PATH.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(recipes)} recipes across {len(DISHES)} cuisines to {OUT_PATH}")

    pork_hits = [r["name"] for r in recipes if "pork" in r["name"].lower()]
    if pork_hits:
        raise RuntimeError(f"Found 'pork' in dish names, must fix: {pork_hits}")


if __name__ == "__main__":
    main()
