GRADE = 2
MODULES: dict[str, list[tuple[str, str]]] = {
    "Math": [
        ("Skip Counting by 2s, 5s, and 10s", "Children practice counting forward in jumps of 2, 5, and 10 to build number fluency."),
        ("Introduction to Division", "Children learn to share a group of objects equally into smaller groups."),
        ("Telling Time to the Half Hour", "Children read an analog clock to tell time to the hour and half hour."),
        ("Telling Time to the Nearest Five Minutes", "Children practice reading clocks in five-minute intervals."),
        ("Measuring Length with Rulers", "Children use a ruler to measure objects in centimeters and inches."),
        ("Comparing Weight and Mass", "Children compare objects as heavier or lighter using a simple balance scale."),
        ("Comparing Volume and Capacity", "Children compare containers to see which holds more or less liquid."),
        ("2D Shapes and Their Properties", "Children identify flat shapes such as triangles and hexagons by counting their sides and corners."),
        ("3D Shapes and Their Properties", "Children identify solid shapes such as cubes and cones and describe their faces and edges."),
        ("Introduction to Symmetry", "Children find lines of symmetry in shapes and pictures by folding and matching."),
        ("Reading and Making Bar Graphs", "Children collect simple data and display it using a bar graph."),
        ("Reading and Making Pictographs", "Children use pictures to represent and compare amounts of data."),
        ("Odd and Even Numbers", "Children learn to sort numbers into odd and even groups by pairing objects."),
        ("Number Patterns and Sequences", "Children identify and extend simple number patterns that grow or shrink by a rule."),
    ],
    "English": [
        ("Nouns: People, Places, and Things", "Children learn to identify and use nouns that name people, places, animals, and objects."),
        ("Verbs: Action Words", "Children learn to recognize and use verbs that show actions in a sentence."),
        ("Pronouns", "Children learn to use words like he, she, and it in place of nouns."),
        ("Sentence Types: Statements and Questions", "Children learn the difference between telling sentences and asking sentences and the punctuation each uses."),
        ("Capital Letters and Punctuation", "Children practice starting sentences with capital letters and ending them with the correct punctuation mark."),
        ("Reading Comprehension Strategies", "Children practice retelling and asking questions about a story to check their understanding."),
        ("Building Vocabulary with Context Clues", "Children learn to use nearby words in a sentence to figure out an unfamiliar word's meaning."),
        ("Synonyms and Antonyms", "Children learn to identify words that mean the same and words that mean the opposite."),
        ("Compound Words", "Children learn to build and break apart words made from two smaller words, like sunflower."),
        ("Contractions", "Children learn how two words can be joined with an apostrophe to make a shorter word, like don't."),
        ("Writing a Simple Paragraph", "Children practice writing a short paragraph with a main idea and supporting details."),
        ("Writing a Friendly Letter", "Children learn the parts of a friendly letter, including a greeting and closing."),
        ("Story Elements: Character, Setting, Plot", "Children learn to identify who is in a story, where it happens, and what happens."),
        ("Sequencing Events in a Story", "Children practice putting story events in the correct order using words like first, next, and last."),
        ("Rhyming Words and Word Families", "Children explore groups of words that share the same ending sound, like cat, hat, and mat."),
        ("Prefixes and Suffixes", "Children learn how adding word parts like un- or -ful changes the meaning of a word."),
        ("Alphabetical Order and Dictionary Skills", "Children practice putting words in ABC order and learn how to look up a word in a simple dictionary."),
        ("Public Speaking and Listening Skills", "Children practice speaking clearly to a group and listening carefully when others speak."),
    ],
    "Science": [
        ("Living and Non-Living Things", "Children learn to sort things into living and non-living based on whether they grow, breathe, and need food."),
        ("Plant Parts and Their Functions", "Children learn the job of each plant part, including roots, stem, leaves, and flowers."),
        ("Life Cycle of a Plant", "Children learn the stages a plant goes through from seed to fully grown plant."),
        ("Life Cycle of a Butterfly", "Children learn the stages of change a butterfly goes through, from egg to caterpillar to adult."),
        ("Animal Habitats", "Children learn about the different places animals live and how each habitat meets their needs."),
        ("Animal Groups: Mammals, Birds, Fish, Reptiles, Amphibians", "Children learn to sort animals into groups based on shared features."),
        ("Food Chains", "Children learn how energy passes from plants to animals in a simple food chain."),
        ("The Five Senses", "Children learn how sight, hearing, smell, taste, and touch help us learn about the world."),
        ("Human Body: Bones and Muscles", "Children learn how bones give the body its shape and muscles help it move."),
        ("Simple Machines", "Children explore everyday tools like ramps, levers, and wheels that make work easier."),
        ("Magnets and Magnetism", "Children explore how magnets attract and repel certain objects."),
        ("Push and Pull: Forces and Motion", "Children learn how pushes and pulls make objects start, stop, speed up, or change direction."),
        ("Light and Shadows", "Children explore how light travels and how blocking it creates shadows."),
        ("Sound and How We Hear", "Children learn that sound is made by vibrations and travels to our ears."),
        ("Earth's Land, Water, and Air", "Children learn about the different parts of our planet, including land, oceans, and the atmosphere."),
        ("Day and Night", "Children learn how Earth's spinning causes day and night."),
        ("The Seasons", "Children learn about the four seasons and how weather and nature change through the year."),
        ("Introduction to the Solar System", "Children learn about the sun, planets, and moon and how they move in space."),
    ],
    "Geography": [
        ("Maps and Globes", "Children learn how maps and globes represent the world and what symbols on them mean."),
        ("Cardinal Directions", "Children learn to use north, south, east, and west to describe locations on a map."),
        ("Landforms: Mountains, Valleys, and Plains", "Children learn to identify common landforms and describe their shapes."),
        ("Rivers and Lakes", "Children learn how rivers and lakes form and why people and animals depend on them."),
        ("Deserts of the World", "Children learn about the dry, sandy features of deserts and the plants and animals that live there."),
        ("Rainforests of the World", "Children learn about the warm, wet rainforest and the many plants and animals it is home to."),
        ("My Country and Its Capital", "Children learn to locate their own country on a map and name its capital city."),
        ("Cities and Villages", "Children compare life and buildings in a busy city with life in a small village."),
        ("Natural Resources", "Children learn about materials from nature, like water, wood, and soil, that people use every day."),
        ("Types of Homes Around the World", "Children explore how homes look different depending on climate and available materials."),
        ("Transportation Around the World", "Children explore different ways people travel by land, water, and air in different places."),
        ("Community Helpers and Their Roles", "Children learn about workers such as firefighters and doctors who help keep a community safe and healthy."),
        ("Landmarks of the World", "Children learn about famous places, such as tall towers and ancient monuments, found around the world."),
        ("Reading a Simple Map Key", "Children learn to use a map's key or legend to understand what its symbols and colors mean."),
        ("Hot and Cold Climates", "Children compare places that are very hot with places that are very cold and how people live there."),
        ("Islands and Peninsulas", "Children learn how land surrounded by water on all sides or on three sides forms islands and peninsulas."),
        ("Polar Regions", "Children learn about the icy areas at the top and bottom of the Earth and the animals that live there."),
        ("Grid References on a Map", "Children practice using simple rows and columns on a map to find a location."),
    ],
    "World History": [
        ("Ancient Egypt and the Pyramids", "Children learn about the ancient Egyptians and how they built the great pyramids along the Nile River."),
        ("Ancient Mesopotamia", "Children learn about one of the earliest civilisations, built between the Tigris and Euphrates rivers."),
        ("Ancient China and Its Inventions", "Children learn about ancient China and inventions such as paper and the compass."),
        ("Ancient Greece and the Olympics", "Children learn about ancient Greece and how the first Olympic Games began there."),
        ("Ancient Rome and Its Empire", "Children learn about ancient Rome, its roads, and its wide-reaching empire."),
        ("The Indus Valley Civilisation", "Children learn about one of the world's oldest civilisations and its well-planned cities."),
        ("Early Explorers and Their Voyages", "Children learn about explorers who sailed to discover new lands and sea routes."),
        ("Life in the Stone Age", "Children learn how early people lived, hunted, and made tools long before written history."),
        ("The Invention of Writing", "Children learn how early people first began recording ideas using symbols and marks."),
        ("Ancient Trade and Marketplaces", "Children learn how ancient peoples traveled to trade goods like spices, cloth, and pottery."),
        ("Famous Leaders of the Past", "Children learn about a few notable rulers and leaders from history and their achievements."),
        ("Castles and Knights", "Children learn about medieval castles and the knights who lived and trained there."),
        ("Ancient Mayan Civilisation", "Children learn about the ancient Maya, their cities, and their study of the stars."),
        ("Ancient Inca Civilisation", "Children learn about the Inca people of South America and their mountain city of Machu Picchu."),
        ("The History of Timekeeping", "Children learn how people measured time long ago using the sun, sand, and water before clocks existed."),
        ("Early Farming and Agriculture", "Children learn how early humans began growing crops and raising animals instead of only hunting."),
        ("Ancient Africa: The Kingdom of Mali", "Children learn about the historic West African kingdom of Mali and its famous city of Timbuktu."),
        ("How We Learn About the Past: Artifacts and Fossils", "Children learn how old objects and fossils help historians and scientists understand history."),
    ],
    "Islamic Studies": [
        ("Belief in One God (Tawheed)", "Children learn about the core Islamic belief in one God as the foundation of the faith."),
        ("The Prophet Muhammad: A Model of Kindness", "Children learn simple stories about the Prophet Muhammad's kindness and good character."),
        ("The Value of Honesty in Islam", "Children learn why telling the truth is an important value taught in Islam."),
        ("The Importance of Prayer (Salah) in Daily Life", "Children learn how daily prayer helps Muslims remember God throughout the day."),
        ("Giving to Others: The Spirit of Charity (Zakat)", "Children learn about the Islamic value of sharing with people who are in need."),
        ("Fasting and Self-Discipline in Ramadan", "Children learn how the month of Ramadan teaches patience and self-control through fasting."),
        ("The Two Eid Celebrations", "Children learn about Eid al-Fitr and Eid al-Adha and how Muslim families celebrate them."),
        ("Respecting Parents and Elders", "Children learn about the Islamic value of showing respect and kindness to parents and elders."),
        ("Being Kind to Animals", "Children learn about the Islamic teaching of treating animals with gentleness and care."),
        ("The Value of Cleanliness in Islam", "Children learn why keeping the body and surroundings clean is valued in Islam."),
        ("The Mosque as a Place of Worship", "Children learn about the mosque as a special place where Muslims gather to pray."),
        ("The Holy Quran as a Guide", "Children learn that the Quran is the holy book Muslims turn to for guidance."),
        ("Stories of the Prophets: Lessons in Patience", "Children learn simple, age-appropriate stories of earlier prophets and the patience they showed."),
        ("Sharing and Caring for Neighbors", "Children learn about the Islamic value of being a good and caring neighbor."),
        ("Saying Thank You: Gratitude in Islam", "Children learn why expressing gratitude to God and others is an important habit in Islam."),
        ("Good Manners and Speaking Kindly", "Children learn about the Islamic emphasis on polite words and gentle behavior."),
        ("Helping Those in Need", "Children learn about the importance of helping people who are poor, sick, or struggling."),
        ("The Importance of Truthfulness", "Children learn why Islam teaches that a person's words should always match the truth."),
        ("Islamic Greetings and Their Meanings", "Children learn simple Islamic greetings and the meaning of peace behind them."),
    ],
    "Coding": [
        ("What is a Computer Program?", "Children learn that a program is a set of instructions that tells a computer what to do."),
        ("Sequencing: Step-by-Step Instructions", "Children practice putting steps in the correct order to complete a simple task."),
        ("Following Directions: Up, Down, Left, Right", "Children practice giving and following simple movement directions, an early coding skill."),
        ("Loops: Repeating Actions", "Children learn how a loop repeats a set of steps instead of writing them over and over."),
        ("Introduction to Conditionals: If-Then Thinking", "Children learn how a program can make a decision using an if-then rule."),
        ("Debugging: Finding and Fixing Mistakes", "Children learn that a bug is a mistake in instructions and practice finding and fixing simple errors."),
        ("Introduction to Block-Based Coding", "Children learn how colorful blocks can be snapped together to build a simple program."),
        ("Making a Sprite Move", "Children use simple blocks to make an on-screen character move around."),
        ("Creating Simple Animations", "Children learn how changing pictures quickly can make a character appear to move."),
        ("Patterns in Code", "Children learn to notice repeating patterns and use them to build simple programs."),
        ("Introduction to Decomposition: Breaking Down Problems", "Children learn to break a big task into smaller, easier steps."),
        ("Binary Basics: Computers and On-Off Signals", "Children learn that computers store information using only two signals, on and off."),
        ("Introduction to Robots", "Children learn what a robot is and how it follows instructions to do a job."),
        ("Giving Instructions to a Robot", "Children practice writing simple step-by-step instructions to guide a robot to a goal."),
        ("Sorting and Ordering with Code", "Children practice arranging objects or numbers in order using simple coding logic."),
        ("Introduction to Events in Programs", "Children learn how a program can respond when something happens, like a click or a key press."),
        ("Coding a Simple Story", "Children use simple coding blocks to make characters act out a short story."),
        ("Introduction to Variables as Boxes", "Children learn that a variable is like a labeled box that stores a piece of information."),
        ("Everyday Algorithms: Making a Sandwich", "Children learn that an algorithm is a set of steps, like the steps for making a sandwich."),
    ],
    "World Literature": [
        ("Aesop's Fables: Lessons in Wisdom", "Children explore short animal fables from ancient Greece that each teach a simple lesson."),
        ("The Tortoise and the Hare: A Story About Patience", "Children explore this classic fable about how slow and steady effort can win a race."),
        ("Anansi the Spider: West African Trickster Tales", "Children explore trickster tales about Anansi the spider from West African storytelling tradition."),
        ("The Boy Who Cried Wolf: A Story About Honesty", "Children explore this classic fable about why telling the truth matters."),
        ("Cinderella Around the World", "Children explore how many cultures tell their own version of a kind girl who overcomes hardship."),
        ("The Story of the Ugly Duckling", "Children explore this classic tale about patience and discovering one's own true self."),
        ("Little Red Riding Hood: A Classic Fairy Tale", "Children explore this well-known European fairy tale about a girl visiting her grandmother."),
        ("The Three Little Pigs: A Story About Hard Work", "Children explore this classic tale about the value of careful, hard work."),
        ("Goldilocks and the Three Bears", "Children explore this classic tale about a curious girl who visits a family of bears."),
        ("The Tale of Peter Rabbit", "Children explore this classic English story about a curious rabbit and his garden adventure."),
        ("Grimm's Fairy Tales: An Introduction", "Children are introduced to a collection of well-known German fairy tales."),
        ("Hans Christian Andersen's Tales", "Children are introduced to well-known Danish fairy tales and the storyteller who wrote them."),
        ("The Panchatantra: Animal Tales from India", "Children explore ancient Indian animal fables that teach lessons about wisdom and friendship."),
        ("Journey to the West: A Chinese Folk Tale", "Children are introduced to characters from this famous Chinese folk story of an adventurous journey."),
        ("The Arabian Nights: Tales from the Middle East", "Children are introduced to a famous collection of adventure tales from the Middle East."),
        ("Native American Folk Tales", "Children explore traditional stories passed down by Native American communities."),
        ("The Legend of the Monkey King", "Children explore the legend of a clever, adventurous monkey hero from Chinese folklore."),
        ("Momotaro: The Peach Boy of Japan", "Children explore this well-loved Japanese folk tale about a boy born from a giant peach."),
        ("The Fox and the Grapes: A Fable About Wanting What We Can't Have", "Children explore this short fable about a fox who decides he never wanted the grapes anyway."),
    ],
    "Art": [
        ("Primary and Secondary Colours", "Children learn how mixing primary colours creates secondary colours."),
        ("Warm and Cool Colours", "Children learn to sort colours into warm shades and cool shades."),
        ("Drawing Lines and Shapes", "Children practice drawing different types of lines and basic shapes to build simple pictures."),
        ("Introduction to Texture in Art", "Children explore how art can look or feel rough, smooth, bumpy, or soft."),
        ("Painting Techniques for Beginners", "Children practice simple painting techniques such as dabbing, brushing, and blending."),
        ("Introduction to Collage", "Children learn to create a picture by arranging and gluing different paper or material pieces."),
        ("Clay Modeling Basics", "Children practice shaping simple forms out of clay or dough with their hands."),
        ("Printmaking with Everyday Objects", "Children learn to create repeated patterns by pressing objects like sponges or vegetables into paint."),
        ("Self-Portraits", "Children practice observing their own features and drawing a picture of themselves."),
        ("Drawing Animals", "Children practice drawing simple animals using basic shapes."),
        ("Drawing Nature and Landscapes", "Children practice drawing outdoor scenes such as trees, hills, and skies."),
        ("Introduction to Famous Artists", "Children are introduced to a few well-known artists and examples of their artwork."),
        ("Patterns and Shapes in Art", "Children explore how repeating shapes and colours can create a pattern in artwork."),
        ("Paper Folding and Origami Basics", "Children practice simple paper-folding steps to make basic origami shapes."),
        ("Introduction to Perspective: Near and Far", "Children learn a simple way to show that some objects in a picture are closer and some are farther away."),
        ("Using Light and Dark: Shading Basics", "Children practice using lighter and darker marks to add depth to a drawing."),
        ("Creating Art with Recycled Materials", "Children practice making art from reused materials such as boxes and bottle caps."),
        ("Introduction to Sculpture", "Children learn that sculpture is art that has height, width, and depth, and can be viewed from all sides."),
        ("Art from Around the World", "Children explore examples of traditional art styles from different cultures."),
    ],
    "Music": [
        ("High and Low Sounds: Introduction to Pitch", "Children learn to identify sounds as high or low in pitch."),
        ("Loud and Soft: Introduction to Dynamics", "Children learn to identify and create sounds that are loud or soft."),
        ("Fast and Slow: Introduction to Tempo", "Children learn to identify music that moves quickly or slowly."),
        ("Introduction to Musical Instruments", "Children learn to recognize and name common musical instruments by sight and sound."),
        ("The Percussion Family", "Children learn about instruments that are hit, shaken, or scraped to make sound."),
        ("The String Family", "Children learn about instruments that make sound using vibrating strings."),
        ("The Wind Family", "Children learn about instruments that make sound when air is blown through them."),
        ("Singing Simple Songs Together", "Children practice singing simple songs as a group and matching pitch."),
        ("Introduction to Musical Notes", "Children learn that musical notes can be written down to show which sounds to play."),
        ("Clapping Patterns and Rhythm Games", "Children practice clapping simple rhythm patterns and repeating them back."),
        ("Introduction to Melody", "Children learn that a melody is a pattern of musical notes that make a tune."),
        ("Music from Around the World", "Children explore music styles and instruments from different cultures."),
        ("Making Music with Everyday Objects", "Children explore how everyday objects can be used to create rhythm and sound."),
        ("Introduction to the Human Voice", "Children learn how the voice can be used to sing high, low, loud, and soft sounds."),
        ("Following a Simple Beat with Body Percussion", "Children practice keeping a steady beat using claps, taps, and stomps."),
        ("Introduction to Musical Silence: Rests", "Children learn that music can include short moments of silence called rests."),
        ("Call and Response Songs", "Children practice singing songs where one part is sung and then answered by another."),
        ("Introduction to Reading Simple Rhythms", "Children learn to read and clap along with simple rhythm symbols."),
        ("Moving to Music: Introduction to Dance", "Children practice moving their bodies in time with different kinds of music."),
    ],
    "General Knowledge": [
        ("Famous Landmarks of the World", "Children learn about well-known landmarks such as famous towers, monuments, and ancient sites."),
        ("World Currencies", "Children learn that different countries use different money and learn a few examples."),
        ("National Symbols", "Children learn about symbols such as flags, birds, and flowers that represent different countries."),
        ("Famous Inventors and Their Inventions", "Children learn about a few inventors and the helpful inventions they created."),
        ("Space Facts for Kids", "Children learn simple facts about the sun, moon, stars, and planets."),
        ("Ocean Animals and Facts", "Children learn about different animals that live in the ocean and interesting facts about them."),
        ("Animals of the World", "Children learn about a variety of animals from different parts of the world."),
        ("Famous Explorers", "Children learn about a few explorers who traveled to discover new places."),
        ("Introduction to World Languages", "Children learn that people around the world speak many different languages."),
        ("Traditional Foods Around the World", "Children learn about well-known traditional foods from different countries."),
        ("Time Zones: Day and Night Around the World", "Children learn that it can be daytime in one part of the world while it is nighttime in another."),
        ("Famous Festivals Around the World", "Children learn about a few well-known festivals celebrated in different cultures."),
        ("Introduction to Transportation Inventions", "Children learn about inventions such as the airplane, train, and car that changed how people travel."),
        ("World Sports and Games", "Children learn about popular sports and games played in different countries."),
        ("Famous Buildings and Structures", "Children learn about a few notable buildings and structures from around the world."),
        ("Endangered Animals", "Children learn about animals that are at risk of disappearing and why they need protection."),
        ("Introduction to Recycling and Sustainability", "Children learn simple ways people can reuse materials and take care of the planet."),
        ("Community Roles and Jobs", "Children learn about different jobs people do to help their community."),
        ("Fun Facts About the Human Body", "Children learn interesting simple facts about how their body works."),
    ],
    "Foreign Languages": [
        ("Numbers in Spanish", "Children learn to count from one to ten using simple Spanish number words."),
        ("Colours in French", "Children learn the French words for common colours."),
        ("Family Words in Bangla", "Children learn simple Bangla words for family members such as mother and father."),
        ("Numbers in Arabic", "Children learn to count from one to ten using simple Arabic number words."),
        ("Days of the Week in Spanish", "Children learn the Spanish names for the days of the week."),
        ("Greetings in French", "Children learn simple French greetings such as hello and goodbye."),
        ("Animals in Bangla", "Children learn simple Bangla words for common animals."),
        ("Counting to Ten in French", "Children learn to count from one to ten using simple French number words."),
        ("Family Words in Arabic", "Children learn simple Arabic words for family members such as mother and father."),
        ("Common Phrases in Spanish", "Children learn simple everyday Spanish phrases such as please and thank you."),
        ("Colours in Bangla", "Children learn the Bangla words for common colours."),
        ("Basic Greetings in Bangla", "Children learn simple Bangla greetings such as hello and how are you."),
        ("Numbers in French", "Children learn to count from one to ten using simple French number words."),
        ("Simple Words in Urdu", "Children learn a few simple everyday Urdu words such as yes, no, and thank you."),
        ("Greetings in Turkish", "Children learn simple Turkish greetings such as hello and goodbye."),
        ("Family Words in Spanish", "Children learn simple Spanish words for family members such as mother and father."),
        ("Days of the Week in Bangla", "Children learn the Bangla names for the days of the week."),
        ("Colours in Spanish", "Children learn the Spanish words for common colours."),
        ("Common Phrases in Arabic", "Children learn simple everyday Arabic phrases such as please and thank you."),
    ],
    "Social Studies": [
        ("My Family and Family Traditions", "Children learn about their own family structure and special traditions they share."),
        ("Rules and Why We Need Them", "Children learn why rules help keep people safe and communities fair."),
        ("Being a Good Citizen", "Children learn simple ways to be helpful, honest, and responsible members of their community."),
        ("My Community and Its Helpers", "Children learn about the people and places that make up their local community."),
        ("Goods and Services", "Children learn the difference between things people make or grow and the help people provide."),
        ("Producers and Consumers", "Children learn about people who make or grow goods and people who buy and use them."),
        ("Then and Now: How Life Has Changed", "Children compare how daily life, tools, and technology have changed over time."),
        ("Cultural Celebrations Around the World", "Children learn about special celebrations and traditions from different cultures."),
        ("Working Together: Cooperation and Teamwork", "Children learn how working together helps a group accomplish more than working alone."),
        ("Fairness and Respect for Others", "Children learn simple ways to treat others fairly and with respect."),
        ("Voting and Making Group Decisions", "Children learn how groups can vote to make a fair decision together."),
        ("Jobs in My Community", "Children learn about different jobs people do and how those jobs help others."),
        ("Maps of My Neighborhood", "Children practice reading and creating a simple map of their own neighborhood."),
        ("National Symbols and Holidays", "Children learn about symbols and holidays that are important to their country."),
        ("Diversity and Respecting Differences", "Children learn to appreciate that people can look, speak, and live differently from one another."),
        ("Saving and Spending Money Wisely", "Children learn simple ideas about saving money and making thoughtful spending choices."),
        ("How Goods Get to Market", "Children learn the simple journey a product takes from being made to reaching a store."),
        ("Being Responsible at Home and School", "Children learn about simple responsibilities they can take on at home and school."),
        ("Solving Problems Peacefully", "Children learn simple steps for resolving disagreements calmly and fairly."),
    ],
    "Physical Education & Self-Defense": [
        ("Basic Locomotor Skills: Running, Jumping, Hopping", "Children practice fundamental movement skills such as running, jumping, and hopping safely."),
        ("Balance and Coordination Games", "Children play games that build balance and coordination through movement."),
        ("Throwing and Catching Basics", "Children practice the basic skills of throwing and catching a ball."),
        ("Kicking and Striking Skills", "Children practice basic kicking and striking movements used in many sports."),
        ("Introduction to Team Games", "Children learn to play simple games that require cooperating with teammates."),
        ("Stretching and Flexibility", "Children practice simple stretches that help their bodies move more freely."),
        ("Warming Up and Cooling Down", "Children learn why warming up before and cooling down after activity keeps the body safe."),
        ("Personal Space Awareness", "Children learn to move safely around others by being aware of their personal space."),
        ("Introduction to Basic Self-Defense Stances", "Children learn simple, safe standing positions that help them feel balanced and aware."),
        ("Saying No and Setting Boundaries", "Children learn that it is okay to say no and set boundaries to keep themselves safe."),
        ("Stranger Safety Awareness", "Children learn simple, age-appropriate rules for staying safe around unfamiliar people."),
        ("Introduction to Falling Safely", "Children learn simple techniques for falling in a way that reduces the chance of injury."),
        ("Simple Tag and Chasing Games", "Children play simple tag-style games that build speed and quick reactions."),
        ("Jump Rope Basics", "Children practice the basic rhythm and footwork needed to jump rope."),
        ("Introduction to Yoga for Kids", "Children practice simple, calming yoga poses and breathing exercises."),
        ("Building Endurance Through Play", "Children take part in active games that gradually build stamina and energy."),
        ("Following Rules in Physical Games", "Children learn why following the rules keeps physical games safe and fair for everyone."),
        ("Cooperative Games and Sportsmanship", "Children learn to play games with good sportsmanship, whether they win or lose."),
        ("Introduction to Basic Blocking Movements", "Children learn simple, safe arm movements used to block an object in play."),
    ],
    "Health Education": [
        ("Handwashing: When and Why", "Children learn the correct steps for washing hands and the important times to do it."),
        ("Getting Enough Sleep", "Children learn why sleep is important for a growing, healthy body and mind."),
        ("Staying Hydrated: Why Water Matters", "Children learn why drinking enough water each day keeps the body healthy."),
        ("Healthy Snack Choices", "Children learn to choose nutritious snacks like fruits and vegetables over sugary treats."),
        ("Recognizing and Naming Emotions", "Children learn to identify and name feelings such as happy, sad, and frustrated."),
        ("Coping with Big Feelings", "Children learn simple calming strategies for handling strong emotions."),
        ("Personal Hygiene Basics", "Children learn simple daily habits, such as bathing and clean clothes, that keep them healthy."),
        ("Sun Safety and Skin Protection", "Children learn simple ways to protect their skin from the sun, such as wearing hats and sunscreen."),
        ("Introduction to Body Safety", "Children learn simple, age-appropriate rules about their body and personal safety."),
        ("Understanding Allergies", "Children learn what an allergy is and simple ways to stay safe around common allergens."),
        ("Visiting the Doctor and Dentist", "Children learn why regular check-ups with a doctor and dentist help keep them healthy."),
        ("Staying Safe Around Strangers", "Children learn simple safety rules for interacting with people they do not know."),
        ("Introduction to First Aid Basics", "Children learn simple first steps to take for minor scrapes and bumps, like telling an adult."),
        ("Screen Time and Healthy Habits", "Children learn why balancing screen time with other activities supports good health."),
    ],
    "ICT & Computer Science": [
        ("Parts of a Computer", "Children learn to identify basic computer parts such as the screen, keyboard, and mouse."),
        ("Using a Mouse and Keyboard", "Children practice basic skills for clicking, dragging, and typing."),
        ("Introduction to Typing", "Children practice finding letters on a keyboard and typing simple words."),
        ("What is a Tablet?", "Children learn what a tablet is and how it is similar to and different from a computer."),
        ("Staying Safe Online: Basic Rules", "Children learn simple, age-appropriate rules for staying safe while using the internet."),
        ("Introduction to Email", "Children learn what email is and how it is used to send messages."),
        ("Creating a Simple Document", "Children practice typing and saving a short document using a word processing program."),
        ("Introduction to Drawing Programs", "Children practice using a simple drawing program to create pictures on a computer."),
        ("What is a Website?", "Children learn what a website is and how pages are linked together online."),
        ("Introduction to Search Engines", "Children learn how a search engine helps find information online using keywords."),
        ("Digital Citizenship Basics", "Children learn simple rules for being kind and responsible when using technology."),
        ("Understanding Passwords", "Children learn why passwords help keep accounts and information private and safe."),
        ("Introduction to File and Folder Basics", "Children learn how files can be saved and organized inside folders on a computer."),
        ("What is Software?", "Children learn that software is the set of programs that tells a computer what to do."),
        ("Introduction to Cloud Storage", "Children learn that files can be saved online so they can be reached from different devices."),
        ("Recognizing Digital Devices Around Us", "Children learn to identify everyday digital devices, such as phones and smart watches."),
        ("Introduction to Video Calls", "Children learn how video calls let people see and talk to each other from far away."),
        ("Understanding Photos and Digital Images", "Children learn how digital photos are taken, saved, and viewed on a device."),
        ("Introduction to Printers and Scanners", "Children learn how printers turn digital documents into paper copies and scanners do the reverse."),
    ],
}
