GRADE = 8
MODULES: dict[str, list[tuple[str, str]]] = {
    "Math": [
        ("Linear Equations in One Variable", "Learn to set up and solve equations with one unknown using inverse operations."),
        ("Linear Inequalities", "Solve and graph simple inequalities on a number line and understand how solutions form a range."),
        ("Polynomials and Factorisation", "Add, subtract, and multiply polynomials, then factorise simple expressions into products."),
        ("Algebraic Identities", "Use standard identities such as (a+b)^2 to expand and simplify algebraic expressions quickly."),
        ("Exponents and Powers", "Apply the laws of exponents to simplify expressions with positive and negative powers."),
        ("Direct and Inverse Proportion", "Distinguish between quantities that increase together and those that increase as one decreases."),
        ("Advanced Ratio and Proportion", "Solve multi-step problems involving ratios, including dividing quantities in a given ratio."),
        ("Percentage Applications", "Apply percentage calculations to real-life situations like discounts, tax, and tips."),
        ("Profit, Loss and Discount", "Calculate profit, loss, and discount percentages in everyday buying and selling scenarios."),
        ("Simple and Compound Interest", "Compare how simple and compound interest grow money differently over time."),
        ("Rational Numbers", "Perform operations with rational numbers and locate them accurately on a number line."),
        ("Squares and Square Roots", "Find squares and square roots of numbers using estimation and prime factorisation methods."),
        ("Cubes and Cube Roots", "Find cubes and cube roots of numbers and recognise perfect cubes."),
        ("Number Patterns and Playing with Numbers", "Explore patterns in numbers, divisibility rules, and simple number puzzles."),
        ("Area of Plane Figures", "Calculate the area of triangles, parallelograms, trapeziums, and composite shapes."),
        ("Surface Area and Volume of Solids", "Calculate the surface area and volume of cubes, cuboids, cylinders, and cones."),
        ("Introduction to Coordinate Geometry", "Plot points on a coordinate plane and calculate distances between them."),
        ("Graphing Linear Equations", "Draw and interpret graphs of linear equations in two variables."),
        ("Data Handling and Statistics", "Organise, represent, and interpret data using tables, graphs, and charts."),
        ("Introduction to Probability", "Understand the likelihood of simple events and calculate basic probabilities."),
        ("Understanding Quadrilaterals", "Classify quadrilaterals by their properties of sides, angles, and diagonals."),
        ("Congruence of Triangles", "Identify congruent triangles using criteria such as SSS, SAS, and ASA."),
        ("Similarity of Triangles", "Recognise similar triangles and use proportional sides to solve problems."),
        ("Applications of the Pythagorean Theorem", "Use the Pythagorean theorem to solve real-world problems involving right triangles."),
        ("Geometric Constructions", "Use a compass and straightedge to construct triangles, angles, and perpendicular lines."),
        ("Symmetry and Transformations", "Explore line and rotational symmetry and describe reflections, rotations, and translations."),
        ("Sets and Venn Diagrams", "Represent groups of objects as sets and use Venn diagrams to show relationships."),
        ("Introduction to Functions and Relations", "Understand functions as rules that map inputs to outputs and represent them in tables and graphs."),
        ("Sequences and Series", "Identify patterns in number sequences and find rules for arithmetic sequences."),
        ("Taxes, Bills and Financial Literacy", "Understand how taxes and household bills are calculated and budgeted for."),
        ("Speed, Distance and Time", "Solve problems relating speed, distance, and time using formulas and unit conversions."),
        ("Time and Work Problems", "Solve word problems involving rates of work completed by individuals or groups."),
        ("Operations on Algebraic Expressions", "Simplify algebraic expressions by combining like terms and applying the distributive property."),
        ("Slopes and Linear Graphs", "Calculate the slope of a line and relate it to the steepness and direction of a graph."),
        ("Measures of Central Tendency", "Calculate and compare the mean, median, and mode of a data set."),
        ("Introduction to Trigonometric Ratios", "Learn the basic sine, cosine, and tangent ratios in a right-angled triangle."),
        ("Reading and Constructing Statistical Graphs", "Create and interpret bar graphs, histograms, and pie charts from real data."),
    ],
    "English": [
        ("Grammar: Active and Passive Voice", "Learn how to transform sentences between active and passive voice and when to use each."),
        ("Grammar: Direct and Indirect Speech", "Convert spoken words into reported speech, adjusting tense and pronouns correctly."),
        ("Parts of Speech Review", "Review and correctly identify nouns, verbs, adjectives, adverbs, and other word classes."),
        ("Sentence Structure and Clauses", "Distinguish between simple, compound, and complex sentences using independent and dependent clauses."),
        ("Punctuation Mastery", "Use commas, semicolons, colons, and apostrophes accurately in varied writing contexts."),
        ("Vocabulary Building: Synonyms and Antonyms", "Expand vocabulary by learning words with similar and opposite meanings."),
        ("Idioms and Phrases", "Understand and use common English idioms to add expression to speech and writing."),
        ("Figures of Speech", "Identify and use similes, metaphors, personification, and hyperbole in writing."),
        ("Poetry Analysis: Form and Meaning", "Analyse how rhyme, rhythm, and structure contribute to a poem's meaning."),
        ("Narrative Writing Techniques", "Learn techniques for pacing, tension, and structure when writing a story."),
        ("Descriptive Writing", "Use sensory details and precise language to create vivid descriptions."),
        ("Persuasive Writing", "Write to convince a reader using evidence, rhetorical devices, and a clear argument."),
        ("Essay Writing: Structure and Argument", "Structure an essay with a clear introduction, supporting body paragraphs, and conclusion."),
        ("Formal Letter Writing", "Write formal letters with correct tone, layout, and conventions for a stated purpose."),
        ("Informal Letter and Email Writing", "Write friendly letters and emails using an appropriate informal tone and format."),
        ("Report Writing", "Write clear, organised reports that present facts and findings objectively."),
        ("Note-Making and Summarising", "Practise condensing longer texts into concise notes and summaries."),
        ("Reading Comprehension Strategies", "Apply strategies like skimming, scanning, and inference to understand unfamiliar texts."),
        ("Introduction to Shakespeare", "Explore the language, themes, and context of a Shakespeare play appropriate for this age group."),
        ("Introduction to the Novel", "Study the key features of a novel, including plot, character, and setting."),
        ("Short Story Elements", "Identify the elements of a short story such as exposition, conflict, climax, and resolution."),
        ("Drama and Play Scripts", "Read and interpret play scripts, including stage directions and dialogue."),
        ("Public Speaking and Oral Presentation", "Develop confidence and clarity when presenting ideas aloud to an audience."),
        ("Debate Skills", "Learn to construct arguments, use evidence, and respectfully counter opposing views."),
        ("Journalism and News Writing", "Learn the structure of a news article, including headlines and the inverted pyramid style."),
        ("Character Analysis in Fiction", "Analyse how authors develop characters through actions, dialogue, and description."),
        ("Theme and Symbolism in Literature", "Identify recurring themes and symbols and explain their significance in a text."),
        ("Point of View and Narrative Voice", "Compare first-person, third-person limited, and omniscient narration in stories."),
        ("Comparing Texts", "Compare two texts on a similar theme, noting similarities and differences in style and message."),
        ("Creative Writing: Building a Plot", "Plan a story plot using a clear beginning, middle, and end with rising tension."),
        ("Dialogue Writing", "Write realistic dialogue that reveals character and moves a story forward."),
        ("Research Skills and Citing Sources", "Learn to gather information from reliable sources and reference them correctly."),
        ("Media Literacy and Advertising Language", "Examine how language and images are used to persuade in advertisements and media."),
        ("Spelling Patterns and Common Errors", "Study common spelling rules and frequently confused words."),
        ("Modal Verbs and Their Uses", "Use modal verbs such as can, must, and should to express possibility, obligation, and permission."),
        ("Tenses: Advanced Usage", "Practise using perfect and continuous tenses accurately across different contexts."),
        ("Prefixes, Suffixes and Root Words", "Use knowledge of word parts to work out the meaning of unfamiliar words."),
        ("Analysing Author's Purpose and Tone", "Identify why a writer chose particular words and what tone they create."),
        ("Autobiography and Biography Writing", "Explore how life stories are told and write a short autobiographical piece."),
    ],
    "Science": [
        ("Cell Structure and Function", "Study the structure of plant and animal cells and the function of key organelles."),
        ("Photosynthesis and Respiration", "Compare how plants make food through photosynthesis and how cells release energy through respiration."),
        ("The Human Digestive System", "Trace the journey of food through the digestive system and the role of each organ."),
        ("The Human Circulatory System", "Learn how the heart, blood, and blood vessels work together to transport substances around the body."),
        ("The Human Respiratory System", "Understand how the lungs exchange oxygen and carbon dioxide during breathing."),
        ("The Human Nervous System", "Explore how the brain, spinal cord, and nerves coordinate the body's responses."),
        ("The Human Skeletal and Muscular System", "Study how bones and muscles work together to support and move the body."),
        ("Reproduction in Plants", "Learn how flowering plants reproduce through pollination, fertilisation, and seed dispersal."),
        ("Reproduction in Humans", "Understand the basic biology of human reproduction and development in an age-appropriate way."),
        ("Ecosystems and Food Webs", "Explore how organisms interact through food chains and food webs within an ecosystem."),
        ("Biodiversity and Conservation", "Understand why biodiversity matters and how human activity affects it."),
        ("Atoms, Elements and Compounds", "Learn the difference between atoms, elements, and compounds and how they combine."),
        ("The Periodic Table", "Understand how elements are organised in the periodic table by properties and atomic number."),
        ("Chemical Bonding Basics", "Introduce ionic and covalent bonding and how atoms combine to form compounds."),
        ("Acids, Bases and Salts", "Explore the properties of acids and bases and how they react to form salts."),
        ("Chemical Reactions and Equations", "Learn to identify signs of chemical reactions and write simple balanced equations."),
        ("Metals and Non-Metals", "Compare the physical and chemical properties of metals and non-metals."),
        ("Physical and Chemical Changes", "Distinguish between reversible physical changes and irreversible chemical changes."),
        ("Energy: Forms and Transformations", "Identify different forms of energy and how energy transforms from one form to another."),
        ("Work, Power and Energy", "Understand the relationship between work done, power, and energy transfer."),
        ("Force and Pressure", "Explore how forces create pressure and how pressure varies with area."),
        ("Gravitation", "Learn how gravity acts between objects and affects weight and motion."),
        ("Sound and Its Properties", "Study how sound travels as waves and how pitch and loudness are determined."),
        ("Light: Reflection and Refraction", "Explore how light reflects off surfaces and bends when passing between materials."),
        ("Electricity and Circuits", "Build and analyse simple electrical circuits using batteries, wires, and bulbs."),
        ("Magnetism and Electromagnetism", "Understand magnetic fields and how electric current can produce magnetism."),
        ("Heat and Temperature", "Distinguish between heat and temperature and study how heat transfers between objects."),
        ("States of Matter and Changes of State", "Explore solids, liquids, and gases and the processes that change matter between states."),
        ("The Solar System", "Study the Sun, planets, moons, and other bodies that make up our solar system."),
        ("Earth's Structure and Plate Tectonics", "Learn about Earth's internal layers and how moving tectonic plates shape the surface."),
        ("Weather and Climate", "Distinguish between weather and climate and study the factors that influence both."),
        ("The Water Cycle", "Trace the movement of water through evaporation, condensation, and precipitation."),
        ("Natural Resources and Conservation", "Classify natural resources and discuss ways to use them sustainably."),
        ("Pollution and Environmental Issues", "Examine causes and effects of air, water, and land pollution and possible solutions."),
        ("Microorganisms and Disease", "Learn about bacteria, viruses, and how the body defends itself against pathogens."),
        ("Nutrition and Balanced Diet", "Understand the food groups and nutrients needed for a healthy, balanced diet."),
        ("Scientific Method and Lab Safety", "Practise forming hypotheses, designing fair tests, and following lab safety rules."),
        ("Simple Machines", "Explore levers, pulleys, and inclined planes and how they make work easier."),
    ],
    "Geography": [
        ("Map Reading and Interpretation", "Learn to read map symbols, keys, scale, and contour lines to interpret terrain."),
        ("Latitude, Longitude and Time Zones", "Understand how the grid of latitude and longitude is used to locate places and define time zones."),
        ("Landforms and Their Formation", "Study how mountains, valleys, and plains form through geological processes."),
        ("Rivers and River Systems", "Trace the journey of a river from source to mouth and the landforms it creates."),
        ("Mountains and Mountain Building", "Explore how tectonic forces fold and uplift rock to form mountain ranges."),
        ("Volcanoes and Earthquakes", "Learn how volcanic eruptions and earthquakes are caused by movements at plate boundaries."),
        ("Weathering and Erosion", "Compare how weathering breaks down rock and erosion transports the resulting material."),
        ("Climate Zones of the World", "Classify the world's major climate zones and the factors that create them."),
        ("Natural Vegetation and Biomes", "Study how climate shapes major biomes such as rainforests, grasslands, and tundra."),
        ("Deserts and Desertification", "Explore how deserts form and how human activity can accelerate desertification."),
        ("Oceans and Ocean Currents", "Learn how ocean currents circulate heat and influence global climate."),
        ("Urbanisation and City Growth", "Examine the causes and consequences of rapid city growth around the world."),
        ("Rural Settlements and Land Use", "Compare how land is used differently in rural and urban settlements."),
        ("Migration: Causes and Effects", "Explore why people migrate and the effects on the places they leave and arrive."),
        ("Agriculture and Farming Systems", "Compare subsistence and commercial farming systems used around the world."),
        ("Industry and Manufacturing", "Study how raw materials are processed into goods and where industries tend to locate."),
        ("Trade and Globalisation", "Understand how international trade connects countries and drives globalisation."),
        ("Natural Resources and Sustainability", "Examine how natural resources are used and the importance of sustainable management."),
        ("Renewable and Non-Renewable Energy", "Compare energy sources that can be replenished with those that cannot."),
        ("Climate Change and Its Impacts", "Study the causes of climate change and its effects on people and the environment."),
        ("Water Resources and Management", "Explore how freshwater is sourced, distributed, and managed sustainably."),
        ("Deforestation and Its Consequences", "Examine the causes of deforestation and its impact on climate and biodiversity."),
        ("Tourism and Its Impacts", "Study the economic benefits and environmental costs of tourism in different regions."),
        ("Transport and Infrastructure", "Explore how transport networks connect places and support economic development."),
        ("Development and Quality of Life", "Compare indicators used to measure development and quality of life between countries."),
        ("Poverty and Inequality", "Examine the causes and geographic patterns of poverty and inequality."),
        ("Continents and Countries Overview", "Build a working knowledge of the world's continents, regions, and major countries."),
        ("Political Geography and Borders", "Study how political borders are formed and how they can affect people's lives."),
        ("Natural Hazards and Disaster Management", "Learn how communities prepare for and respond to natural hazards."),
        ("Coasts and Coastal Processes", "Study how waves and tides shape coastlines through erosion and deposition."),
        ("Glaciers and Ice Caps", "Explore how glaciers form, move, and shape the landscape."),
        ("Soils and Soil Conservation", "Learn how soil forms and why conserving it matters for agriculture."),
        ("World Population Distribution", "Study the patterns and reasons behind where people live around the world."),
        ("Cultural Geography and Diversity", "Explore how culture, language, and religion vary across different regions."),
        ("Environmental Conservation Efforts", "Study global and local efforts to protect natural environments."),
        ("Map Projections and Scale", "Understand how map projections distort the globe and how scale is used."),
        ("Geographic Information Systems Basics", "Introduce how digital mapping tools like GIS are used to analyse geographic data."),
        ("Case Study: Sustainable Cities", "Examine a real city that has implemented sustainable urban planning solutions."),
    ],
    "World History": [
        ("Ancient Civilisations Overview", "Survey the earliest civilisations and the common features that allowed them to develop."),
        ("Ancient Egypt: Society and Achievements", "Study the society, government, and achievements of ancient Egypt along the Nile."),
        ("Ancient Mesopotamia", "Explore the cities, writing, and laws of the civilisations between the Tigris and Euphrates."),
        ("Ancient Greece: Democracy and Culture", "Study the origins of democracy and cultural achievements of ancient Greek city-states."),
        ("The Roman Empire", "Explore the rise, government, and eventual decline of the Roman Empire."),
        ("Ancient China and the Silk Road", "Study ancient Chinese dynasties and the trade routes that connected East and West."),
        ("Ancient India: The Indus Valley and Mauryan Empire", "Explore the early urban civilisation of the Indus Valley and the later Mauryan Empire."),
        ("The Islamic Golden Age", "Study the scientific, cultural, and intellectual achievements of the early Islamic world."),
        ("The Byzantine Empire", "Learn how the eastern Roman Empire continued and shaped medieval history."),
        ("Medieval Europe and Feudalism", "Study the social and political structure of feudal society in medieval Europe."),
        ("The Crusades", "Examine the causes, course, and consequences of the medieval Crusades."),
        ("The Mongol Empire", "Study how the Mongol Empire became the largest contiguous land empire in history."),
        ("African Kingdoms: Mali, Ghana and Songhai", "Explore the wealth, trade, and learning of major medieval West African kingdoms."),
        ("The Renaissance", "Study the revival of art, science, and learning in Renaissance Europe."),
        ("The Age of Exploration", "Examine how sea voyages connected continents and changed the world."),
        ("The Reformation", "Learn how religious reform movements changed Europe's political and religious landscape."),
        ("The Ottoman Empire", "Study the rise and influence of the Ottoman Empire across three continents."),
        ("The Mughal Empire", "Explore the government, culture, and architecture of the Mughal Empire in South Asia."),
        ("The Scientific Revolution", "Examine how new methods of observation and experiment transformed understanding of nature."),
        ("The Enlightenment", "Study how Enlightenment thinkers shaped ideas about reason, rights, and government."),
        ("The Atlantic Slave Trade", "Examine the causes, scale, and lasting impact of the transatlantic slave trade."),
        ("The American Revolution", "Study the causes and outcomes of the American colonies' fight for independence."),
        ("The French Revolution", "Explore the causes and consequences of the revolution that transformed France."),
        ("The Industrial Revolution", "Study how new technology transformed production, work, and daily life."),
        ("Colonialism and Imperialism", "Examine how European powers established colonies and the impact on colonised peoples."),
        ("The Unification of Italy and Germany", "Study how fragmented states were unified into modern Italy and Germany."),
        ("World War One: Causes and Consequences", "Examine the causes, key events, and aftermath of the First World War."),
        ("The Russian Revolution", "Study how revolution overthrew the Russian monarchy and led to communist rule."),
        ("The Great Depression", "Explore the causes and global impact of the economic crisis of the 1930s."),
        ("World War Two: Causes and Consequences", "Examine the causes, key events, and aftermath of the Second World War."),
        ("The Holocaust", "Learn the history of the Holocaust with sensitivity and understand its lasting significance."),
        ("The Cold War", "Study the political tension and rivalry between the United States and the Soviet Union."),
        ("The United Nations and International Cooperation", "Explore how the United Nations was formed to promote peace and cooperation."),
        ("The Civil Rights Movement", "Study the struggle for racial equality and justice in the mid-20th century."),
        ("The Space Race", "Examine how Cold War rivalry drove rapid advances in space exploration."),
        ("Post-War Reconstruction and the Marshall Plan", "Study how nations rebuilt after World War Two with international assistance."),
        ("The Fall of the Berlin Wall", "Explore the events that ended the division of Europe during the Cold War."),
        ("Modern Conflicts and Peacebuilding", "Survey recent global conflicts and the ongoing efforts to build lasting peace."),
    ],
    "Islamic Studies": [
        ("The Six Articles of Faith", "Learn the core beliefs of Islam, including belief in God, angels, and the Day of Judgement."),
        ("The Five Pillars of Islam Overview", "Introduce the five foundational acts of worship that structure Muslim life."),
        ("The Life of Prophet Muhammad (peace be upon him): Makkan Period", "Study the early life and mission of the Prophet in Makkah."),
        ("The Life of Prophet Muhammad (peace be upon him): Madinan Period", "Study the establishment of the Muslim community after the migration to Madinah."),
        ("The Seerah: Lessons from the Prophet's Character", "Reflect on the values of honesty, patience, and compassion drawn from the Prophet's example."),
        ("The Rightly Guided Caliphs", "Learn about the leadership and legacy of the first four caliphs after the Prophet."),
        ("The Compilation of the Quran", "Understand the historical process by which the Quran was preserved and compiled."),
        ("Themes of the Quran: An Overview", "Survey the major themes found across the Quran, such as guidance, mercy, and justice."),
        ("Introduction to Tafsir (Quranic Exegesis)", "Introduce how scholars interpret and explain the meanings of the Quran."),
        ("Introduction to Hadith Sciences", "Learn how sayings and actions of the Prophet were collected and verified."),
        ("The Sunnah and Its Importance", "Understand the role of the Prophet's example in guiding Muslim daily practice."),
        ("The Concept of Tawheed (Oneness of God)", "Explore the central Islamic belief in the oneness and uniqueness of God."),
        ("The Prophets in Islam: A Shared Heritage", "Learn about the shared tradition of prophets recognised across Abrahamic faiths."),
        ("The Story of Prophet Ibrahim (Abraham)", "Study the life and legacy of Prophet Ibrahim as a model of faith and devotion."),
        ("The Story of Prophet Musa (Moses)", "Study the life and mission of Prophet Musa and the lessons drawn from his story."),
        ("The Story of Prophet Isa (Jesus)", "Study the Islamic account of Prophet Isa and his place among the prophets."),
        ("Islamic Ethics and Akhlaq", "Explore the Islamic emphasis on good character and moral conduct."),
        ("Honesty and Trustworthiness in Islam", "Learn why honesty and trustworthiness are considered essential virtues in Islam."),
        ("Kindness to Parents and Family", "Study the emphasis Islam places on kindness and duty toward parents and family."),
        ("Islamic Etiquette (Adab) in Daily Life", "Learn everyday manners encouraged in Islam, such as greetings and respect for others."),
        ("The Concept of Ummah (Community)", "Understand the idea of a global Muslim community united by shared faith."),
        ("Zakat: Purpose and Practice", "Learn the purpose of obligatory charity and how it supports those in need."),
        ("Sawm: The Practice of Fasting", "Study the practice and purpose of fasting during the month of Ramadan."),
        ("Hajj: The Pilgrimage to Makkah", "Explore the rituals and significance of the annual pilgrimage to Makkah."),
        ("Salah: Structure and Significance", "Learn the structure of the daily prayers and their spiritual significance."),
        ("Wudu and Purification Practices", "Understand the practice of ritual purification before prayer."),
        ("The Islamic Calendar and Important Dates", "Learn how the lunar Islamic calendar works and its key commemorated dates."),
        ("Mosques and Their Role in the Community", "Explore the function of mosques as centres of worship and community life."),
        ("Islamic Art and Architecture", "Study the geometric patterns and architectural styles found in Islamic art."),
        ("Muslim Scholars and Scientists in History", "Learn about influential Muslim scholars who advanced learning across many fields."),
        ("Islamic Contributions to Mathematics and Astronomy", "Explore historical Muslim contributions to algebra, geometry, and astronomy."),
        ("Islamic Contributions to Medicine", "Study historical advances in medicine made by scholars in the Muslim world."),
        ("Women in Islamic History", "Learn about the contributions of notable women in Islamic history."),
        ("Family Life and Values in Islam", "Explore the values Islam places on family relationships and responsibilities."),
        ("Environmental Responsibility in Islam", "Study Islamic teachings on caring for the environment and using resources wisely."),
        ("Justice and Fairness in Islamic Teaching", "Explore the importance placed on justice and fairness in Islamic ethics."),
        ("Interfaith Understanding and Respect", "Learn the value Islam places on respectful relations with people of other faiths."),
        ("Charity and Social Responsibility", "Study the broader Islamic emphasis on generosity and helping the wider community."),
        ("Islamic Perspectives on Knowledge and Education", "Explore why seeking knowledge is highly valued in Islamic tradition."),
    ],
    "Coding": [
        ("Introduction to Python Syntax", "Learn the basic syntax and structure used to write Python programs."),
        ("Variables and Data Types", "Learn to create variables and work with numbers, strings, and booleans."),
        ("Operators and Expressions", "Use arithmetic, comparison, and logical operators to build expressions."),
        ("Input and Output in Python", "Learn to accept user input and display output messages in a program."),
        ("Conditional Statements: If, Elif, Else", "Use conditional logic to make programs respond differently based on conditions."),
        ("Loops: For and While", "Use for and while loops to repeat actions in a program efficiently."),
        ("Lists and List Operations", "Store collections of data in lists and perform common operations on them."),
        ("Tuples and Sets", "Learn how tuples and sets differ from lists and when to use each."),
        ("String Manipulation", "Practise slicing, formatting, and manipulating text strings in code."),
        ("Functions and Parameters", "Write reusable functions that accept parameters and return values."),
        ("Scope and Local vs Global Variables", "Understand how variable scope affects where a variable can be accessed."),
        ("Recursion Basics", "Introduce recursive functions that call themselves to solve problems."),
        ("Error Handling with Try and Except", "Learn to catch and handle errors gracefully using try and except blocks."),
        ("Introduction to Object-Oriented Programming", "Introduce the core idea of organising code around objects and classes."),
        ("Classes and Objects", "Define classes with attributes and methods and create objects from them."),
        ("Inheritance and Polymorphism Basics", "Learn how classes can inherit and extend behaviour from other classes."),
        ("Modules and Libraries", "Learn to import and use built-in and external modules in a program."),
        ("Working with the Math and Random Modules", "Use built-in modules to perform calculations and generate random values."),
        ("Introduction to Algorithms", "Understand what an algorithm is and how to describe steps to solve a problem."),
        ("Searching Algorithms", "Compare linear and binary search algorithms for finding items in a list."),
        ("Sorting Algorithms", "Explore simple sorting algorithms such as bubble sort and selection sort."),
        ("Time Complexity Basics", "Introduce the idea of measuring how an algorithm's run time grows with input size."),
        ("Introduction to Data Structures", "Introduce how data structures organise information for efficient use."),
        ("Stacks and Queues", "Learn the last-in-first-out and first-in-first-out principles behind stacks and queues."),
        ("Debugging Techniques", "Learn systematic strategies to find and fix errors in code."),
        ("Writing Pseudocode and Flowcharts", "Plan a program's logic using pseudocode and flowcharts before coding."),
        ("Introduction to HTML", "Learn to structure a web page's content using HTML tags."),
        ("Introduction to CSS", "Learn to style web pages using CSS selectors and properties."),
        ("Introduction to JavaScript", "Introduce basic JavaScript syntax used to add interactivity to web pages."),
        ("Building a Simple Web Page", "Combine HTML and CSS to build and style a simple web page."),
        ("Introduction to Databases", "Introduce how databases store and organise structured data."),
        ("Basic SQL Queries", "Learn to write simple SQL queries to select and filter data."),
        ("Version Control with Git Basics", "Introduce how Git tracks changes to code over time."),
        ("Introduction to APIs", "Understand how programs use APIs to exchange data with other services."),
        ("Building a Simple Game with Python", "Apply programming concepts to build a simple text-based or graphical game."),
        ("Turtle Graphics and Drawing with Code", "Use Python's turtle module to draw shapes and patterns with code."),
        ("Introduction to Cybersecurity Concepts", "Introduce basic concepts of keeping data and systems safe from threats."),
        ("Ethics in Computing and Digital Citizenship", "Discuss responsible and ethical behaviour when using technology online."),
        ("Introduction to Artificial Intelligence Concepts", "Introduce basic ideas behind how computers can learn from data."),
    ],
    "World Literature": [
        ("Homer's Epics: The Iliad and The Odyssey", "Explore the themes and heroes of Homer's ancient Greek epic poems."),
        ("Greek Mythology and Its Legacy", "Study Greek myths and their lasting influence on literature and culture."),
        ("The Fables of Aesop", "Examine the moral lessons found in Aesop's short animal fables."),
        ("Shakespeare's Comedies: An Introduction", "Explore the humour, mistaken identity, and themes typical of Shakespeare's comedies."),
        ("Shakespeare's Tragedies: An Introduction", "Explore the central conflicts and downfall of the hero in a Shakespearean tragedy."),
        ("The Poetry of William Wordsworth", "Study how Wordsworth's poetry celebrates nature and everyday experience."),
        ("The Novels of Charles Dickens", "Explore how Dickens portrayed Victorian society through memorable characters."),
        ("Jane Austen and the Novel of Manners", "Study how Austen examined social class and relationships in her novels."),
        ("The Adventures of Mark Twain", "Explore Twain's use of humour and regional voice in American literature."),
        ("The Gothic Tradition: Mary Shelley's Frankenstein", "Study the gothic themes and scientific questions raised in Shelley's novel."),
        ("Edgar Allan Poe and the Short Story", "Examine Poe's mastery of suspense and atmosphere in the short story form."),
        ("The Brontë Sisters and Victorian Fiction", "Study the distinctive voices of the Brontë sisters in Victorian literature."),
        ("Leo Tolstoy and Russian Literature", "Introduce the themes and scope of Tolstoy's major contributions to Russian literature."),
        ("Anton Chekhov and the Short Story Form", "Study Chekhov's understated style and psychological insight in short fiction."),
        ("The Poetry of Rabindranath Tagore", "Explore the themes of nature and spirituality in Tagore's poetry."),
        ("The Arabian Nights: Tales and Traditions", "Study the frame narrative and storytelling traditions of the Arabian Nights."),
        ("The Poetry of Rumi", "Explore the themes of love and reflection found in Rumi's poetry."),
        ("Chinua Achebe and African Literature", "Study how Achebe portrayed the impact of colonialism on African society."),
        ("Gabriel García Márquez and Magical Realism", "Introduce the blending of the fantastic and the everyday in magical realism."),
        ("The Poetry of Pablo Neruda", "Explore the vivid imagery and themes found in Neruda's poetry."),
        ("Franz Kafka and Existential Themes", "Introduce Kafka's exploration of alienation and absurdity in his fiction."),
        ("George Orwell: Allegory and Dystopia", "Study how Orwell used allegory to comment on political power and society."),
        ("The Plays of Henrik Ibsen", "Explore how Ibsen's plays examine social issues and individual conscience."),
        ("American Transcendentalism: Thoreau and Emerson", "Study the ideas of self-reliance and nature found in transcendentalist writing."),
        ("The Harlem Renaissance", "Explore the flourishing of African American art and literature in the 1920s."),
        ("Langston Hughes and African American Poetry", "Study the rhythm and themes of identity in Hughes's poetry."),
        ("Toni Morrison and Contemporary American Fiction", "Introduce Morrison's exploration of history and identity in American fiction."),
        ("Folktales from Around the World", "Compare folktales from different cultures and the values they teach."),
        ("The Epic of Gilgamesh", "Explore themes of friendship and mortality in one of the earliest known epics."),
        ("The Panchatantra: Fables from India", "Study the moral animal fables of the classical Indian Panchatantra."),
        ("Journey to the West and Chinese Classical Literature", "Introduce the adventure and allegory of a major Chinese classical novel."),
        ("The Poetry of Matsuo Bashō and Haiku Tradition", "Study the concise imagery and nature focus of the Japanese haiku tradition."),
        ("Fairy Tales of the Brothers Grimm", "Explore the themes and structure of traditional Grimm fairy tales."),
        ("Hans Christian Andersen's Tales", "Study the imaginative themes found in Andersen's classic tales."),
        ("Lewis Carroll and Nonsense Literature", "Explore the wordplay and imagination in Carroll's nonsense literature."),
        ("J.R.R. Tolkien and the Fantasy Genre", "Introduce how Tolkien's world-building shaped the modern fantasy genre."),
        ("Introduction to Science Fiction: Jules Verne", "Explore how Verne imagined future technology and exploration."),
        ("The Diary of Anne Frank", "Study the historical significance and personal voice of Anne Frank's diary."),
        ("Comparative Study: Heroes Across World Literatures", "Compare how different cultures portray heroism in their literary traditions."),
    ],
    "Art": [
        ("Elements of Art: Line, Shape and Form", "Identify the basic visual elements artists use to build a composition."),
        ("Principles of Design: Balance and Contrast", "Explore how balance, contrast, and other design principles organise artwork."),
        ("Color Theory Fundamentals", "Learn the color wheel, complementary colors, and how colors interact."),
        ("Drawing Techniques: Shading and Perspective", "Practise shading and basic perspective to create depth in drawings."),
        ("Still Life Drawing", "Practise observational drawing skills by sketching arranged objects."),
        ("Portrait Drawing Basics", "Learn the basic proportions and techniques for drawing a human face."),
        ("Landscape Painting Techniques", "Explore techniques for capturing depth and atmosphere in landscape painting."),
        ("Watercolor Painting Fundamentals", "Learn basic watercolor techniques such as washes and blending."),
        ("Acrylic Painting Techniques", "Explore layering and blending techniques used in acrylic painting."),
        ("Introduction to Printmaking", "Introduce basic printmaking methods such as stamping and relief printing."),
        ("Sculpture and Three-Dimensional Art", "Explore how artists create form and space in three-dimensional sculpture."),
        ("Ceramics and Pottery Basics", "Introduce basic hand-building techniques used to shape clay."),
        ("Collage and Mixed Media Art", "Explore combining different materials to create a mixed media artwork."),
        ("Introduction to Photography", "Learn the basic elements of composition used in photography."),
        ("Digital Art and Design Tools", "Introduce basic digital tools used to create and edit artwork."),
        ("Art History: Prehistoric and Ancient Art", "Explore the earliest known artworks and their cultural purposes."),
        ("Art History: Classical Greek and Roman Art", "Study the ideals of beauty and proportion in classical Greek and Roman art."),
        ("Art History: The Renaissance", "Explore how Renaissance artists revived classical ideas and techniques."),
        ("Art History: Baroque and Rococo", "Compare the dramatic Baroque style with the lighter Rococo style."),
        ("Art History: Impressionism", "Study how Impressionist artists captured light and fleeting moments."),
        ("Art History: Post-Impressionism", "Explore how Post-Impressionist artists moved beyond Impressionist technique."),
        ("Art History: Cubism", "Study how Cubist artists broke objects into geometric forms."),
        ("Art History: Surrealism", "Explore how Surrealist artists depicted dreams and the unconscious mind."),
        ("Art History: Pop Art", "Study how Pop artists used imagery from popular and consumer culture."),
        ("Art History: Abstract Expressionism", "Explore how Abstract Expressionist artists used gesture and color to convey emotion."),
        ("Islamic Geometric Art and Pattern Design", "Study the mathematical patterns used in traditional Islamic art and design."),
        ("African Art Traditions", "Explore the diverse artistic traditions found across the African continent."),
        ("Asian Art Traditions", "Explore key artistic traditions from across Asia."),
        ("Indigenous Art of the Americas", "Study the artistic traditions of Indigenous peoples of the Americas."),
        ("Graphic Design Basics", "Introduce the principles of arranging text and image for visual communication."),
        ("Typography and Lettering", "Explore how the style and arrangement of lettering communicates meaning."),
        ("Comic Art and Sequential Storytelling", "Learn how comic panels and layout tell a story visually."),
        ("Architecture as Art", "Explore how buildings combine function and artistic design."),
        ("Art Criticism: Analysing a Work of Art", "Practise describing, analysing, and interpreting a work of art."),
        ("Composition and Visual Storytelling", "Learn how the arrangement of elements guides the viewer's eye and tells a story."),
        ("Perspective Drawing: One and Two Point", "Practise drawing objects in one-point and two-point perspective."),
        ("Textile Art and Design", "Explore artistic traditions in weaving, embroidery, and fabric design."),
        ("Public and Street Art", "Explore the role of murals and street art in public spaces."),
        ("Careers in Art and Design", "Survey career paths available to people with skills in art and design."),
    ],
    "Music": [
        ("Elements of Music: Rhythm and Beat", "Explore how rhythm and beat provide the pulse underlying music."),
        ("Elements of Music: Melody and Harmony", "Learn how melody and harmony combine to create musical texture."),
        ("Reading Musical Notation", "Learn to read notes, rests, and staff notation in written music."),
        ("Time Signatures and Rhythm Patterns", "Understand how time signatures organise beats into rhythmic patterns."),
        ("Introduction to Chords and Chord Progressions", "Learn how chords are built and combined into progressions."),
        ("Major and Minor Scales", "Compare the sound and structure of major and minor scales."),
        ("Instruments of the Orchestra: Strings", "Learn about the string family of instruments and how they produce sound."),
        ("Instruments of the Orchestra: Woodwinds", "Learn about the woodwind family of instruments and how they produce sound."),
        ("Instruments of the Orchestra: Brass", "Learn about the brass family of instruments and how they produce sound."),
        ("Instruments of the Orchestra: Percussion", "Learn about percussion instruments and their role in keeping rhythm."),
        ("The Human Voice and Vocal Techniques", "Introduce basic vocal technique and how the voice works as an instrument."),
        ("Introduction to Music History: Baroque Period", "Study the style and key composers of the Baroque period."),
        ("Introduction to Music History: Classical Period", "Study the style and key composers of the Classical period."),
        ("Introduction to Music History: Romantic Period", "Study the style and key composers of the Romantic period."),
        ("Introduction to Music History: 20th Century", "Survey the variety of musical styles that emerged in the 20th century."),
        ("World Music Traditions: African Rhythms", "Explore the rhythmic traditions found in African music."),
        ("World Music Traditions: South Asian Classical Music", "Introduce the ragas and rhythmic cycles of South Asian classical music."),
        ("World Music Traditions: Middle Eastern Music", "Explore the scales and instruments characteristic of Middle Eastern music."),
        ("World Music Traditions: Latin American Music", "Explore the rhythms and instruments found in Latin American music."),
        ("Introduction to Jazz", "Introduce the improvisation and swing rhythm central to jazz music."),
        ("Introduction to Blues", "Explore the origins and structure of blues music."),
        ("The Origins of Rock and Roll", "Study how rock and roll emerged from earlier musical styles."),
        ("Introduction to Hip Hop and Its Elements", "Introduce the musical and cultural elements that make up hip hop."),
        ("Folk Music Traditions", "Explore how folk music preserves and passes down cultural stories."),
        ("Introduction to Music Composition", "Introduce basic techniques for composing a simple original melody."),
        ("Songwriting Basics: Lyrics and Structure", "Learn how verses, choruses, and lyrics come together in a song."),
        ("Introduction to Music Technology and Recording", "Introduce basic concepts of recording and producing music digitally."),
        ("Digital Audio Workstations Basics", "Introduce how digital audio workstations are used to create and edit music."),
        ("Introduction to Conducting", "Learn the basic gestures a conductor uses to lead an ensemble."),
        ("Choral Singing and Ensemble Performance", "Practise singing together as part of a choral ensemble."),
        ("Instrumental Ensemble Performance", "Practise playing together as part of an instrumental ensemble."),
        ("Music and Emotion", "Explore how musical elements can be used to convey different emotions."),
        ("Music Theory: Intervals", "Learn to identify and name the distance between two musical notes."),
        ("Music Theory: Dynamics and Tempo Markings", "Learn how dynamics and tempo markings shape musical expression."),
        ("Famous Composers: Bach and Handel", "Study the life and contributions of Baroque composers Bach and Handel."),
        ("Famous Composers: Mozart and Beethoven", "Study the life and contributions of Classical composers Mozart and Beethoven."),
        ("Music in Film and Media", "Explore how music is used to enhance storytelling in film and media."),
        ("Music and Culture Around the World", "Survey how music reflects and shapes culture in different societies."),
        ("Careers in Music", "Survey career paths available to people with skills and interest in music."),
    ],
    "Survival Skills": [
        ("Basic Navigation with a Map and Compass", "Learn to use a map and compass together to find direction and location."),
        ("Reading Nature for Direction Finding", "Learn natural methods, like the sun's position, to estimate direction outdoors."),
        ("Water Sourcing and Purification", "Learn safe methods to locate and purify water in an outdoor setting."),
        ("Fire Making Techniques", "Learn safe methods for starting and maintaining a fire outdoors."),
        ("Basic Knot Tying", "Practise tying essential knots used for securing and hauling gear."),
        ("Wilderness First Aid Basics", "Learn basic first aid steps to use for injuries in an outdoor setting."),
        ("Identifying Edible and Poisonous Plants", "Learn general caution and identification tips for wild plants."),
        ("Foraging Safely in the Wild", "Learn safe principles for identifying and gathering wild food responsibly."),
        ("Basic Fishing Techniques", "Introduce simple techniques for catching fish as a food source."),
        ("Weather Prediction Using Natural Signs", "Learn to read clouds, wind, and other signs to anticipate weather changes."),
        ("Packing an Emergency Survival Kit", "Learn what essential items belong in a basic emergency survival kit."),
        ("Signaling for Help and Rescue", "Learn methods for signaling location to rescuers in an emergency."),
        ("Understanding Hypothermia and Heat Exhaustion", "Learn to recognise and respond to signs of hypothermia and heat exhaustion."),
        ("Animal Awareness and Safety in the Wild", "Learn how to behave safely around wildlife encountered outdoors."),
        ("Camping Etiquette and Leave No Trace Principles", "Learn responsible camping habits that minimise impact on nature."),
        ("Basic Tool Use and Maintenance", "Learn safe use and care of basic outdoor tools."),
        ("Building a Fire Safely and Responsibly", "Learn how to build, maintain, and fully extinguish a campfire safely."),
        ("Emergency Preparedness at Home", "Learn how to prepare a household emergency plan and supply kit."),
        ("Earthquake Safety and Preparedness", "Learn safety actions to take before, during, and after an earthquake."),
        ("Flood Safety and Preparedness", "Learn safety actions to take before, during, and after a flood."),
        ("Basic Rope and Cordage Skills", "Practise handling rope and cordage for securing loads and shelters."),
        ("Understanding Basic First Aid: Cuts and Wounds", "Learn how to clean and dress minor cuts and wounds."),
        ("Understanding Basic First Aid: Burns", "Learn the correct first response steps for treating minor burns."),
        ("CPR Basics and When to Use It", "Introduce the basic concept and steps of CPR in an emergency."),
        ("Insect and Snake Bite Safety", "Learn safe response steps for insect stings and snake bites."),
        ("Staying Calm and Decision-Making in Emergencies", "Learn strategies for thinking clearly and making decisions under pressure."),
        ("Urban Survival Basics", "Learn practical skills for staying safe during emergencies in a city environment."),
        ("Road and Traffic Safety", "Learn key rules and habits for staying safe near roads and traffic."),
        ("Water Safety and Basic Swimming Survival", "Learn basic techniques to stay safe in and around water."),
        ("Basic Map Symbols and Terrain Reading", "Learn to interpret common map symbols and terrain features."),
        ("Building Emergency Shelters in Different Climates", "Compare shelter-building approaches suited to different climates."),
        ("Food Storage and Preservation Basics", "Learn simple methods for storing and preserving food safely."),
        ("Understanding Search and Rescue Procedures", "Introduce how search and rescue teams organise their efforts."),
        ("Communication Without Technology", "Learn low-tech methods for communicating over distance in an emergency."),
        ("Basic Sewing and Repair Skills", "Learn simple sewing techniques for repairing gear and clothing."),
        ("Personal Safety and Situational Awareness", "Learn habits that build awareness of surroundings and personal safety."),
        ("Introduction to Disaster Risk Reduction", "Introduce the concept of reducing risk before a disaster occurs."),
        ("Star Navigation at Night", "Learn to use stars, like the North Star, to find direction at night."),
        ("Team Survival and Group Decision-Making", "Learn how groups can cooperate and make decisions in survival situations."),
    ],
    "General Knowledge": [
        ("World Geography Facts", "Build broad knowledge of continents, oceans, and major geographic features."),
        ("Major World Landmarks", "Learn about famous landmarks and monuments recognised around the world."),
        ("World Flags and National Symbols", "Learn to recognise national flags and the symbols they represent."),
        ("International Organizations: UN, WHO, UNESCO", "Learn the purpose of major international organizations that promote cooperation."),
        ("World Currencies and Economies", "Build awareness of different world currencies and how economies vary."),
        ("Major World Religions Overview", "Build a respectful overview of the world's major religious traditions."),
        ("World Languages and Linguistic Diversity", "Explore the diversity of languages spoken around the world."),
        ("Famous Inventions and Inventors", "Learn about inventions that changed history and the people behind them."),
        ("Space Exploration Milestones", "Survey key milestones in the history of human space exploration."),
        ("The Human Body: Fun Facts and Systems", "Explore interesting facts about how the human body's systems work."),
        ("Environmental Awareness and Sustainability", "Build awareness of environmental issues and everyday sustainable habits."),
        ("World Sports and the Olympics", "Learn about popular world sports and the history of the Olympic Games."),
        ("Nobel Prize and Its Categories", "Learn what the Nobel Prize recognises and its different award categories."),
        ("Famous Scientists and Their Discoveries", "Learn about scientists whose discoveries changed our understanding of the world."),
        ("World Wonders: Ancient and Modern", "Explore famous ancient and modern wonders of the world."),
        ("Global Time Zones and Their Uses", "Understand how time zones work and why they matter for global communication."),
        ("National Governments and Political Systems", "Compare different systems of government used around the world."),
        ("Understanding Democracy and Elections", "Learn the basic principles behind democratic government and elections."),
        ("Human Rights Basics", "Introduce the concept of universal human rights and why they matter."),
        ("World Trade and Economics Basics", "Introduce basic concepts of how goods and services are traded globally."),
        ("Famous Explorers in History", "Learn about explorers whose journeys expanded knowledge of the world."),
        ("Technology Trends and Innovations", "Survey current technology trends shaping everyday life."),
        ("Renewable Energy Around the World", "Learn how different countries are adopting renewable energy sources."),
        ("Global Health Awareness", "Build awareness of major global health topics and challenges."),
        ("World Cuisines and Food Culture", "Explore how food and cuisine reflect culture around the world."),
        ("Cultural Festivals Around the World", "Learn about festivals celebrated by different cultures worldwide."),
        ("Media and Information Literacy", "Learn to evaluate the reliability of information found in media."),
        ("Famous Artists and Their Masterpieces", "Learn about renowned artists and their most celebrated works."),
        ("Famous Authors and Literary Works", "Learn about influential authors and their major literary works."),
        ("Basic Financial Literacy for Teens", "Introduce basic money management skills relevant to teenagers."),
        ("Career Awareness and Future Pathways", "Explore different career paths and the education they may require."),
        ("Climate Change Awareness", "Build awareness of the causes and effects of climate change globally."),
        ("Wildlife Conservation Around the World", "Learn about efforts to protect endangered species and habitats."),
        ("World History Milestones", "Survey key milestones that shaped world history."),
        ("Basic Legal Awareness for Citizens", "Introduce basic rights and responsibilities of citizens under the law."),
        ("Understanding the News and Media Bias", "Learn to recognise bias and perspective when consuming news media."),
        ("Global Population Trends", "Explore how and why the world's population is changing over time."),
        ("Introduction to Space and Astronomy Facts", "Build broad knowledge of interesting facts about space and astronomy."),
        ("Notable World Leaders in History", "Learn about leaders whose decisions shaped major events in history."),
    ],
    "Cooking": [
        ("Kitchen Safety and Hygiene", "Learn essential safety and hygiene rules for working in a kitchen."),
        ("Basic Knife Skills", "Practise safe and accurate knife techniques for cutting and chopping."),
        ("Measuring Ingredients Accurately", "Learn to measure dry and liquid ingredients accurately for a recipe."),
        ("Understanding Food Groups and Nutrition", "Learn how different food groups contribute to a balanced diet."),
        ("Reading and Following a Recipe", "Learn to interpret recipe instructions, quantities, and terminology."),
        ("Basic Cooking Methods: Boiling and Simmering", "Learn the difference between boiling and simmering and when to use each."),
        ("Basic Cooking Methods: Frying and Sautéing", "Learn safe techniques for frying and sautéing food."),
        ("Basic Cooking Methods: Baking and Roasting", "Learn how dry heat is used to bake and roast different foods."),
        ("Basic Cooking Methods: Steaming and Grilling", "Learn how steaming and grilling cook food using moist and direct heat."),
        ("Understanding Herbs and Spices", "Learn how common herbs and spices are used to flavor dishes."),
        ("Basic Breakfast Recipes", "Practise preparing simple, balanced breakfast recipes."),
        ("Basic Salad Preparation", "Learn to prepare fresh salads with balanced ingredients and dressings."),
        ("Soup Making Basics", "Learn the basic steps for preparing a simple homemade soup."),
        ("Bread Making Basics", "Introduce the basic process of mixing, kneading, and baking bread."),
        ("Basic Baking: Cakes and Cookies", "Learn the basic techniques for baking simple cakes and cookies."),
        ("Basic Pastry Making", "Introduce the basic techniques used to make simple pastry dough."),
        ("Understanding Food Preservation", "Learn basic methods used to preserve food, such as drying and pickling."),
        ("Food Storage and Refrigeration Safety", "Learn safe practices for storing and refrigerating different foods."),
        ("Understanding Food Labels", "Learn to read and interpret nutrition information on food labels."),
        ("Basic Egg Cookery", "Practise preparing eggs using several common cooking methods."),
        ("Basic Rice and Grain Cookery", "Learn the basic technique for cooking rice and other grains properly."),
        ("Basic Pasta Cookery", "Learn the basic technique for cooking pasta and simple sauces."),
        ("Vegetarian Cooking Basics", "Explore preparing balanced, flavorful meals without meat."),
        ("Introduction to World Cuisines", "Explore the ingredients and techniques typical of several world cuisines."),
        ("Basic Sauce Making", "Learn the basic techniques for preparing simple sauces."),
        ("Basic Dessert Preparation", "Practise preparing simple desserts using basic techniques."),
        ("Understanding Portion Sizes", "Learn to estimate appropriate portion sizes for balanced meals."),
        ("Meal Prepping for the Week", "Learn strategies for planning and preparing meals in advance."),
        ("Cooking for Dietary Restrictions", "Learn to adapt recipes for common dietary needs and restrictions."),
        ("Basic Table Setting and Etiquette", "Learn the basics of setting a table and dining etiquette."),
        ("Understanding Kitchen Equipment and Tools", "Learn the names and safe use of common kitchen tools and equipment."),
        ("Food Waste Reduction", "Learn practical strategies for reducing food waste at home."),
        ("Basic Beverage Preparation", "Practise preparing simple non-alcoholic beverages and drinks."),
        ("Seasonal Cooking and Local Ingredients", "Learn the benefits of cooking with seasonal and locally available ingredients."),
        ("Basic Grilling and Barbecue Techniques", "Learn safe basic techniques for grilling and barbecuing food."),
        ("Understanding Fermentation Basics", "Introduce the basic science behind fermenting foods."),
        ("Cooking with Legumes and Beans", "Learn to prepare and cook beans and legumes as a protein source."),
        ("Basic Food Plating and Presentation", "Learn simple techniques for presenting a finished dish attractively."),
        ("Cooking as a Life Skill and Career", "Reflect on cooking as both an everyday life skill and a possible career path."),
    ],
}
