GRADE = 9
MODULES: dict[str, list[tuple[str, str]]] = {
    "Math": [
        ("Linear Equations in One Variable", "Students learn to set up and solve linear equations with a single unknown."),
        ("Linear Equations in Two Variables", "Students explore equations with two variables and represent their solutions as lines on a graph."),
        ("Systems of Linear Equations", "Students solve pairs of linear equations simultaneously using substitution and elimination."),
        ("Systems of Linear Inequalities", "Students graph and interpret regions that satisfy two or more linear inequalities at once."),
        ("Quadratic Equations and Factoring", "Students learn to solve quadratic equations by factoring trinomials into binomial products."),
        ("The Quadratic Formula", "Students use the quadratic formula to find the roots of any quadratic equation."),
        ("Graphing Quadratic Functions", "Students plot parabolas and identify their vertex, axis of symmetry, and intercepts."),
        ("Polynomials: Addition and Subtraction", "Students combine like terms to add and subtract polynomial expressions."),
        ("Polynomials: Multiplication", "Students multiply binomials and polynomials using the distributive property."),
        ("Polynomial Division", "Students divide polynomials using long division and synthetic division methods."),
        ("Exponents and Exponent Rules", "Students apply the laws of exponents to simplify expressions with powers."),
        ("Scientific Notation", "Students write and compute with very large and very small numbers using scientific notation."),
        ("Radicals and Simplifying Square Roots", "Students simplify square roots and perform operations with radical expressions."),
        ("Rational Expressions", "Students simplify, multiply, and divide algebraic fractions."),
        ("Rational Equations", "Students solve equations containing algebraic fractions and check for extraneous solutions."),
        ("Absolute Value Equations and Inequalities", "Students solve equations and inequalities involving absolute value expressions."),
        ("Slope and Rate of Change", "Students calculate slope as a measure of steepness and real-world rate of change."),
        ("Slope-Intercept Form", "Students write and graph linear equations using the slope-intercept form y = mx + b."),
        ("Point-Slope Form", "Students write the equation of a line given a point and its slope."),
        ("Parallel and Perpendicular Lines", "Students identify slope relationships that make two lines parallel or perpendicular."),
        ("Direct and Inverse Variation", "Students model relationships where one quantity varies directly or inversely with another."),
        ("Exponential Functions", "Students explore functions that grow or shrink by a constant multiplicative factor."),
        ("Exponential Growth and Decay", "Students apply exponential models to population growth, radioactive decay, and finance."),
        ("Sequences and Series (Arithmetic)", "Students find patterns and sums in sequences that increase by a constant difference."),
        ("Sequences and Series (Geometric)", "Students find patterns and sums in sequences that increase by a constant ratio."),
        ("Set Theory and Venn Diagrams", "Students use sets and Venn diagrams to organize and compare groups of objects."),
        ("Probability: Independent and Dependent Events", "Students calculate the likelihood of combined events that do or do not affect each other."),
        ("Probability: Combinations and Permutations", "Students count arrangements and selections using combination and permutation formulas."),
        ("Descriptive Statistics: Mean, Median, Mode", "Students calculate and interpret measures of central tendency in data sets."),
        ("Data Displays: Histograms and Box Plots", "Students construct and interpret histograms and box-and-whisker plots."),
        ("Scatter Plots and Line of Best Fit", "Students plot bivariate data and estimate a line of best fit to describe trends."),
        ("Congruence and Similarity of Triangles", "Students prove triangles congruent or similar using side and angle relationships."),
        ("The Pythagorean Theorem", "Students use the Pythagorean theorem to find missing side lengths in right triangles."),
        ("Special Right Triangles", "Students learn the side ratios of 45-45-90 and 30-60-90 triangles."),
        ("Area and Perimeter of Polygons", "Students calculate the area and perimeter of regular and irregular polygons."),
        ("Surface Area of 3D Solids", "Students calculate the surface area of prisms, cylinders, cones, and spheres."),
        ("Volume of 3D Solids", "Students calculate the volume of prisms, cylinders, cones, pyramids, and spheres."),
        ("Circles: Circumference and Area", "Students calculate the circumference and area of circles using radius and diameter."),
        ("Circle Theorems", "Students apply theorems about chords, tangents, and inscribed angles in circles."),
        ("Coordinate Geometry: Distance and Midpoint", "Students use formulas to find the distance and midpoint between two points on a plane."),
        ("Transformations: Translations and Reflections", "Students perform and describe translations and reflections of geometric figures."),
        ("Transformations: Rotations and Dilations", "Students perform and describe rotations and dilations of geometric figures."),
        ("Number Systems: Rational and Irrational Numbers", "Students classify numbers within the real number system, including irrational numbers."),
        ("Solving Word Problems with Systems of Equations", "Students translate real-world scenarios into systems of equations and solve them."),
        ("Matrices: Introduction and Operations", "Students learn to represent data with matrices and perform basic matrix addition and multiplication."),
        ("Financial Math: Simple and Compound Interest", "Students calculate interest earned or owed using simple and compound interest formulas."),
        ("Logic and Mathematical Proof", "Students learn the structure of logical arguments and write simple mathematical proofs."),
    ],
    "English": [
        ("Elements of Narrative Fiction", "Students identify the core building blocks of stories, including character, setting, and plot."),
        ("Poetry: Form and Structure", "Students examine how stanzas, meter, and rhyme scheme shape a poem's meaning."),
        ("Poetic Devices and Imagery", "Students identify metaphor, simile, and imagery and analyze their effect on readers."),
        ("Persuasive Writing Techniques", "Students learn to build persuasive arguments using evidence, appeals, and rhetorical strategy."),
        ("Argumentative Essay Structure", "Students learn to organize a claim, counterclaim, and supporting evidence in an essay."),
        ("Expository Writing", "Students practice writing clear, informative essays that explain a topic or process."),
        ("Narrative Writing: Voice and Perspective", "Students experiment with narrative voice and point of view in their own writing."),
        ("Descriptive Writing Techniques", "Students use sensory detail and precise language to bring a scene or subject to life."),
        ("The Art of the Short Story", "Students study how short stories achieve impact within a compact form."),
        ("Character Development and Analysis", "Students analyze how authors build believable, evolving characters."),
        ("Theme and Symbolism in Literature", "Students identify recurring themes and symbols and interpret their significance."),
        ("Setting and Atmosphere", "Students examine how setting shapes mood and influences a story's events."),
        ("Plot Structure and Conflict", "Students map exposition, rising action, climax, and resolution in narratives."),
        ("Point of View in Fiction", "Students compare first-person, third-person limited, and omniscient narration."),
        ("Introduction to the Novel", "Students study the structure and pacing of longer prose fiction."),
        ("Coming-of-Age Literature", "Students explore stories centered on adolescence and personal growth."),
        ("Dystopian Fiction", "Students analyze how dystopian novels critique society through imagined futures."),
        ("Autobiography and Memoir", "Students study how writers shape true personal experiences into narrative."),
        ("The Essay as a Literary Form", "Students explore the personal and reflective essay as a distinct genre."),
        ("Rhetorical Devices", "Students identify devices such as repetition, parallelism, and rhetorical questions."),
        ("Analyzing Tone and Mood", "Students distinguish an author's tone from the mood created for the reader."),
        ("Figurative Language", "Students identify and interpret metaphor, personification, hyperbole, and symbolism."),
        ("Grammar: Clauses and Sentence Structure", "Students identify independent and dependent clauses to build varied sentences."),
        ("Grammar: Active and Passive Voice", "Students learn to recognize and choose between active and passive voice."),
        ("Punctuation for Clarity and Style", "Students use punctuation deliberately to clarify meaning and control pacing."),
        ("Vocabulary Building: Roots, Prefixes, and Suffixes", "Students use word parts to decode and build unfamiliar vocabulary."),
        ("Formal and Informal Register", "Students learn to adjust language formality for different audiences and purposes."),
        ("Public Speaking and Oratory", "Students practice organizing and delivering a clear, engaging spoken presentation."),
        ("Debate Skills and Techniques", "Students learn to construct arguments and respond to counterarguments in debate."),
        ("Research Skills and Note-Taking", "Students learn to locate reliable sources and take organized notes."),
        ("Citing Sources and Avoiding Plagiarism", "Students learn proper citation practices and why academic honesty matters."),
        ("Writing a Research Report", "Students plan, draft, and revise a structured report based on research."),
        ("Journalism and News Writing", "Students learn the inverted pyramid structure and objective tone of news writing."),
        ("Media Literacy and Bias", "Students learn to evaluate media sources for reliability, purpose, and bias."),
        ("Analyzing Non-Fiction Texts", "Students practice close reading of essays, articles, and speeches for meaning."),
        ("Comparative Literature Analysis", "Students compare two texts to identify shared themes and differing approaches."),
        ("Drama: Structure and Stagecraft", "Students study how dialogue, stage directions, and acts shape a play."),
        ("Reading and Performing Monologues", "Students interpret and perform a monologue to explore character voice."),
        ("Satire and Irony", "Students identify satire and irony and analyze how they critique society."),
        ("Allegory and Fable", "Students examine how allegories and fables convey moral lessons through story."),
        ("Epic Poetry Traditions", "Students study the conventions of epic poetry across different cultures."),
        ("The Sonnet Form", "Students examine the structure and rhyme scheme of the sonnet."),
        ("Free Verse and Modern Poetry", "Students explore how modern poets break from traditional rhyme and meter."),
        ("Editing and Proofreading Strategies", "Students practice systematic strategies for catching errors in their own writing."),
        ("The Writing Process: Drafting and Revision", "Students learn to move through planning, drafting, and revising with purpose."),
        ("Creative Writing: World-Building", "Students practice inventing settings and rules for original fictional worlds."),
        ("Letter and Email Writing Conventions", "Students learn the conventions of formal and informal written correspondence."),
        ("Analyzing Advertising Language", "Students examine how advertisements use language to persuade consumers."),
        ("Book Clubs and Literary Discussion Skills", "Students practice discussing texts respectfully and supporting ideas with evidence."),
    ],
    "Science": [
        ("Cell Structure and Function", "Students identify the parts of plant and animal cells and their functions."),
        ("Cell Division: Mitosis and Meiosis", "Students compare how cells divide for growth versus for reproduction."),
        ("DNA Structure and Replication", "Students learn the double-helix structure of DNA and how it copies itself."),
        ("Genetics and Heredity", "Students learn how traits are passed from parents to offspring."),
        ("Punnett Squares and Inheritance Patterns", "Students use Punnett squares to predict the outcomes of genetic crosses."),
        ("Protein Synthesis", "Students trace how genetic information is used to build proteins in cells."),
        ("Human Body Systems: Circulatory System", "Students learn how the heart and blood vessels transport blood through the body."),
        ("Human Body Systems: Respiratory System", "Students learn how the lungs exchange oxygen and carbon dioxide."),
        ("Human Body Systems: Digestive System", "Students trace how food is broken down and nutrients are absorbed."),
        ("Human Body Systems: Nervous System", "Students learn how the brain, spinal cord, and nerves control the body."),
        ("Homeostasis", "Students learn how organisms maintain a stable internal environment."),
        ("Photosynthesis", "Students learn how plants convert light energy into chemical energy."),
        ("Cellular Respiration", "Students learn how cells release energy stored in glucose."),
        ("Ecosystems and Energy Flow", "Students trace how energy moves through producers, consumers, and decomposers."),
        ("Food Webs and Food Chains", "Students model feeding relationships between organisms in an ecosystem."),
        ("Biodiversity and Conservation", "Students examine the importance of biodiversity and threats facing it."),
        ("Classification of Living Things", "Students learn the taxonomic system used to classify organisms."),
        ("Microorganisms and Disease", "Students learn how bacteria and viruses cause disease and spread."),
        ("The Immune System", "Students learn how the body defends itself against pathogens."),
        ("Atomic Structure", "Students learn the structure of atoms, including protons, neutrons, and electrons."),
        ("The States of Matter", "Students compare the particle arrangement of solids, liquids, and gases."),
        ("Chemical Reactions and Equations", "Students learn to balance chemical equations and identify reaction types."),
        ("Acids, Bases, and pH", "Students learn to classify substances using the pH scale and their properties."),
        ("Solutions and Solubility", "Students explore how solutes dissolve in solvents and factors affecting solubility."),
        ("Chemical Reaction Rates", "Students investigate factors that speed up or slow down chemical reactions."),
        ("Energy Changes in Reactions", "Students distinguish between exothermic and endothermic chemical reactions."),
        ("Organic Chemistry Basics", "Students learn the basic structure of carbon-based compounds."),
        ("Metals and Non-Metals", "Students compare the physical and chemical properties of metals and non-metals."),
        ("Forces and Newton's Laws of Motion", "Students learn Newton's three laws and how they explain motion."),
        ("Motion Graphs: Speed, Velocity, Acceleration", "Students interpret graphs describing an object's speed and changing motion."),
        ("Work, Energy, and Power", "Students learn how work, energy, and power relate to forces and motion."),
        ("Energy Conservation and Transfer", "Students learn the law of conservation of energy and how energy changes form."),
        ("Waves: Properties and Types", "Students learn the properties of waves and the difference between transverse and longitudinal waves."),
        ("Sound Waves and Acoustics", "Students learn how sound waves travel and how pitch and volume are produced."),
        ("Light and Optics", "Students learn how light reflects, refracts, and forms images through lenses."),
        ("Electricity: Circuits and Current", "Students learn how electric circuits work and how to calculate current and voltage."),
        ("Magnetism and Electromagnetism", "Students learn how magnetic fields form and how electricity creates magnetism."),
        ("Density and Buoyancy", "Students learn how density determines whether objects float or sink."),
        ("Earth's Structure and Plate Tectonics", "Students learn about Earth's layers and how moving plates shape the surface."),
        ("Earthquakes and Volcanoes", "Students learn how plate movement causes earthquakes and volcanic eruptions."),
        ("Rocks and the Rock Cycle", "Students classify rocks and trace how they transform through the rock cycle."),
        ("Weather and Climate Systems", "Students distinguish between weather and climate and the factors that shape them."),
        ("Climate Change and Its Impacts", "Students examine the causes and effects of global climate change."),
        ("The Water Cycle", "Students trace how water moves between the atmosphere, land, and oceans."),
        ("The Solar System", "Students learn the structure and features of the sun, planets, and other bodies."),
        ("Stars and Stellar Life Cycles", "Students learn how stars form, evolve, and eventually die."),
        ("Scientific Method and Experimental Design", "Students learn to design controlled experiments to test a hypothesis."),
        ("Laboratory Safety and Measurement", "Students learn safe lab practices and how to use measurement tools accurately."),
    ],
    "Geography": [
        ("Plate Tectonics and Landforms", "Students learn how moving tectonic plates create mountains, ridges, and rift valleys."),
        ("Weathering and Erosion", "Students learn how physical and chemical processes break down and reshape landscapes."),
        ("River Systems and Landforms", "Students study how rivers erode, transport, and deposit material to form landforms."),
        ("Coastal Landforms and Processes", "Students learn how waves and tides shape cliffs, beaches, and coastal features."),
        ("Glaciation and Ice Age Landscapes", "Students learn how glaciers carve valleys and leave distinctive landforms."),
        ("Climate Zones of the World", "Students learn how latitude and geography create distinct global climate zones."),
        ("Weather Patterns and Forecasting", "Students learn how meteorologists read data to predict short-term weather."),
        ("Biomes and Ecosystems", "Students compare major world biomes and the organisms adapted to each."),
        ("Population Growth and Change", "Students examine factors driving population growth and decline over time."),
        ("Population Distribution and Density", "Students learn why populations cluster unevenly across the Earth's surface."),
        ("Migration: Causes and Effects", "Students examine push and pull factors that drive human migration."),
        ("Urbanization and City Growth", "Students study why cities grow and the challenges rapid urbanization creates."),
        ("Rural Land Use", "Students examine how rural land is used for farming, forestry, and settlement."),
        ("Agriculture and Farming Systems", "Students compare subsistence and commercial farming systems around the world."),
        ("Food Security and Sustainability", "Students examine challenges to ensuring reliable access to food globally."),
        ("Water Resources and Scarcity", "Students examine the distribution of freshwater and causes of water scarcity."),
        ("Natural Resource Management", "Students learn strategies for managing renewable and non-renewable resources."),
        ("Deforestation and Land Use Change", "Students examine the causes and consequences of forest loss worldwide."),
        ("Development and Quality of Life", "Students compare indicators used to measure a country's level of development."),
        ("Global Trade and Economic Geography", "Students learn how trade networks connect economies across the world."),
        ("Globalization and Its Impacts", "Students examine how globalization affects culture, economy, and environment."),
        ("Tourism and Its Effects", "Students examine the economic benefits and environmental costs of tourism."),
        ("Transportation and Infrastructure", "Students learn how transport networks shape economic and social development."),
        ("Cultural Geography and Identity", "Students explore how language, religion, and tradition shape regional identity."),
        ("Political Boundaries and Territory", "Students examine how political borders are drawn and sometimes disputed."),
        ("Map Skills and Cartography", "Students practice reading, interpreting, and creating maps at different scales."),
        ("Geographic Information Systems (GIS)", "Students learn how digital mapping tools are used to analyze spatial data."),
        ("Remote Sensing and Satellite Imagery", "Students learn how satellites are used to monitor environmental change."),
        ("Natural Hazards: Earthquakes and Volcanoes", "Students examine the risks and preparedness strategies for seismic and volcanic hazards."),
        ("Natural Hazards: Floods and Droughts", "Students examine the causes and impacts of flooding and prolonged drought."),
        ("Natural Hazards: Tropical Storms", "Students learn how tropical storms form and the damage they can cause."),
        ("Disaster Risk Reduction", "Students learn strategies communities use to reduce the impact of natural disasters."),
        ("Climate Change: Causes and Evidence", "Students examine the scientific evidence behind human-driven climate change."),
        ("Climate Change: Global Responses", "Students examine international efforts and policies to address climate change."),
        ("Renewable Energy Geography", "Students examine where and why renewable energy sources are developed."),
        ("Fossil Fuel Extraction and Impact", "Students examine the geography and environmental impact of fossil fuel extraction."),
        ("Ocean Geography and Marine Resources", "Students study ocean features and the resources they provide."),
        ("Deserts and Desertification", "Students examine desert environments and the spread of desertification."),
        ("Mountain Environments", "Students examine how altitude and terrain shape mountain ecosystems and life."),
        ("Rainforest Ecosystems and Threats", "Students examine the biodiversity of rainforests and threats they face."),
        ("Polar Regions and Their Challenges", "Students examine the unique environments of the Arctic and Antarctic."),
        ("Regional Study: Africa", "Students study the physical and human geography of the African continent."),
        ("Regional Study: Asia", "Students study the physical and human geography of the Asian continent."),
        ("Regional Study: Europe", "Students study the physical and human geography of the European continent."),
        ("Regional Study: The Americas", "Students study the physical and human geography of North and South America."),
        ("International Organizations and Cooperation", "Students learn how organizations like the UN address global challenges."),
        ("Refugees and Displacement", "Students examine the causes and consequences of forced displacement worldwide."),
        ("Sustainable Development Goals", "Students examine the UN's global goals for reducing poverty and protecting the planet."),
    ],
    "World History": [
        ("Early Human Migration and Settlement", "Students learn how early humans spread across continents and formed settlements."),
        ("The Agricultural Revolution", "Students examine how farming transformed human societies from nomadic to settled life."),
        ("Ancient Mesopotamia", "Students study the rise of cities, writing, and law in the Fertile Crescent."),
        ("Ancient Egypt", "Students study the civilization along the Nile, including its pharaohs and monuments."),
        ("The Indus Valley Civilization", "Students study the planned cities and trade of the ancient Indus Valley."),
        ("Ancient China: Dynasties and Philosophy", "Students study early Chinese dynasties and the philosophies of Confucius and Laozi."),
        ("Ancient Greece: City-States and Democracy", "Students study the rise of Greek city-states and the origins of democracy."),
        ("The Persian Empire", "Students study the administration and expansion of the ancient Persian Empire."),
        ("Alexander the Great and Hellenistic Culture", "Students study Alexander's conquests and the spread of Greek culture."),
        ("The Roman Republic", "Students study Rome's early government and the balance of power among its institutions."),
        ("The Roman Empire", "Students study the expansion, achievements, and administration of the Roman Empire."),
        ("The Fall of Rome", "Students examine the factors that contributed to the decline of the Western Roman Empire."),
        ("The Byzantine Empire", "Students study how the Eastern Roman Empire preserved and adapted Roman traditions."),
        ("The Rise of Islam", "Students study the origins and early spread of Islam in the seventh century."),
        ("The Islamic Golden Age", "Students study the scientific and cultural achievements of the medieval Islamic world."),
        ("Feudal Japan", "Students study the samurai class and feudal social structure of medieval Japan."),
        ("Medieval Europe and Feudalism", "Students study the feudal system that organized medieval European society."),
        ("The Crusades", "Students examine the causes, course, and consequences of the medieval Crusades."),
        ("The Mongol Empire", "Students study the rise of the Mongol Empire and its impact on trade and conquest."),
        ("African Kingdoms: Mali and Songhai", "Students study the wealth and scholarship of the medieval West African empires."),
        ("The Silk Road and Trade Networks", "Students examine how trade routes connected distant civilizations and cultures."),
        ("The Black Death", "Students examine the causes and devastating impact of the medieval plague."),
        ("The Renaissance", "Students study the revival of art, learning, and humanism in Europe."),
        ("The Age of Exploration", "Students examine the motivations and consequences of European overseas exploration."),
        ("The Columbian Exchange", "Students examine the global exchange of goods, ideas, and disease after 1492."),
        ("The Reformation", "Students study the religious and political changes sparked by the Protestant Reformation."),
        ("The Aztec and Inca Empires", "Students study the achievements and downfall of the Aztec and Inca civilizations."),
        ("The Atlantic Slave Trade", "Students examine the causes and devastating human impact of the Atlantic slave trade."),
        ("The Scientific Revolution", "Students study how new methods of inquiry transformed understanding of the natural world."),
        ("The Enlightenment", "Students study Enlightenment ideas about reason, government, and individual rights."),
        ("The American Revolution", "Students examine the causes and outcomes of the American colonies' break from Britain."),
        ("The French Revolution", "Students examine the causes and radical political changes of the French Revolution."),
        ("The Industrial Revolution", "Students examine how industrialization transformed economies and daily life."),
        ("Nationalism in 19th Century Europe", "Students examine how nationalist movements reshaped European borders and identity."),
        ("Imperialism in Africa", "Students examine the causes and consequences of European colonization of Africa."),
        ("Imperialism in Asia", "Students examine the causes and consequences of European and Japanese imperialism in Asia."),
        ("The Unification of Italy and Germany", "Students examine how Italy and Germany became unified nation-states."),
        ("Causes of World War I", "Students examine the political and military tensions that led to World War I."),
        ("The Course and Impact of World War I", "Students trace the major events of World War I and its lasting consequences."),
        ("The Russian Revolution", "Students examine the collapse of the tsarist government and rise of Soviet rule."),
        ("The Rise of Totalitarianism", "Students examine the conditions that allowed totalitarian regimes to gain power."),
        ("Causes of World War II", "Students examine the political and economic causes leading to World War II."),
        ("The Holocaust", "Students learn the history of the Holocaust and its lasting significance."),
        ("The Course and Impact of World War II", "Students trace the major events of World War II and its global consequences."),
        ("The Cold War", "Students examine the ideological rivalry between the United States and Soviet Union."),
        ("Decolonization Movements", "Students examine how colonized nations gained independence in the twentieth century."),
        ("The Civil Rights Movement", "Students examine the struggle for racial equality and civil rights in the twentieth century."),
        ("The End of the Cold War and Its Legacy", "Students examine the collapse of the Soviet Union and its lasting global impact."),
    ],
    "Islamic Studies": [
        ("The Life of Prophet Muhammad: Early Years", "Students learn about the early life and upbringing of Prophet Muhammad in Makkah."),
        ("The Life of Prophet Muhammad: Prophethood in Makkah", "Students learn about the beginning of revelation and the early Makkan community."),
        ("The Migration to Madinah (Hijrah)", "Students learn about the significance of the migration from Makkah to Madinah."),
        ("The Establishment of the Madinah Community", "Students learn how the early Muslim community was organized in Madinah."),
        ("The Five Pillars of Islam: An Overview", "Students learn the five foundational acts of worship in Islam."),
        ("The Shahada: Declaration of Faith", "Students learn the meaning and significance of the Islamic declaration of faith."),
        ("Salah: The Practice of Prayer", "Students learn the structure and significance of the five daily prayers."),
        ("Zakat: Charity and Social Responsibility", "Students learn how obligatory almsgiving supports social welfare in Islam."),
        ("Sawm: The Practice of Fasting in Ramadan", "Students learn the purpose and practice of fasting during the month of Ramadan."),
        ("Hajj: The Pilgrimage to Makkah", "Students learn the rituals and significance of the annual pilgrimage to Makkah."),
        ("The Quran: Structure and Compilation", "Students learn how the Quran is organized and how it was compiled historically."),
        ("The Quran: Themes and Guidance", "Students explore the major themes found throughout the Quran's teachings."),
        ("Hadith: Sayings and Traditions of the Prophet", "Students learn how recorded sayings of the Prophet guide Muslim practice."),
        ("The Sunnah and Its Role in Daily Life", "Students learn how the Prophet's example shapes everyday Muslim conduct."),
        ("The Six Articles of Faith", "Students learn the core beliefs that form the foundation of Islamic theology."),
        ("Belief in the Oneness of God (Tawhid)", "Students learn the central Islamic concept of the oneness of God."),
        ("Angels in Islamic Belief", "Students learn the role of angels as described in Islamic tradition."),
        ("The Prophets in Islamic Tradition", "Students learn about the succession of prophets recognized in Islam."),
        ("The Concept of Akhirah (the Afterlife)", "Students learn the Islamic understanding of life after death."),
        ("Qadr: Divine Decree and Free Will", "Students explore the Islamic concept of divine decree alongside human choice."),
        ("The Rightly Guided Caliphs", "Students learn about the leadership of the first four caliphs after the Prophet."),
        ("The Early Muslim Community and Its Challenges", "Students learn how the early Muslim community faced and overcame early challenges."),
        ("The Spread of Islam Across Regions", "Students learn how Islam spread across the Arabian Peninsula and beyond."),
        ("Islamic Law: Sources and Principles", "Students learn the foundational sources used to derive Islamic legal guidance."),
        ("Islamic Ethics and Moral Conduct", "Students explore ethical principles that guide personal behavior in Islam."),
        ("Family Life and Values in Islam", "Students explore the values Islam places on family relationships and responsibility."),
        ("Islamic Perspectives on Community and Brotherhood", "Students explore how Islam emphasizes unity and mutual support among believers."),
        ("Islamic Perspectives on Justice and Fairness", "Students explore how justice and fairness are emphasized in Islamic teaching."),
        ("Islamic Perspectives on Knowledge and Education", "Students explore the value Islam places on seeking knowledge."),
        ("Women in Islamic History", "Students learn about notable women and their contributions in Islamic history."),
        ("Islamic Art and Architecture", "Students explore the geometric patterns and design principles of Islamic art."),
        ("Islamic Calligraphy", "Students explore how calligraphy became a central form of Islamic artistic expression."),
        ("The Development of Mosques", "Students learn how mosque architecture developed across different regions and eras."),
        ("Islamic Contributions to Mathematics", "Students learn about mathematical advances made by scholars in the Islamic world."),
        ("Islamic Contributions to Medicine", "Students learn about medical advances made by physicians in the Islamic world."),
        ("Islamic Contributions to Astronomy", "Students learn about astronomical advances made by scholars in the Islamic world."),
        ("Muslim Scholars and Philosophers", "Students learn about influential scholars who shaped Islamic intellectual history."),
        ("Islamic Banking and Economic Principles", "Students learn the basic principles guiding ethical finance in Islamic tradition."),
        ("Interfaith Relations in Islamic History", "Students explore historical examples of interfaith coexistence in Muslim societies."),
        ("Islam in Andalusia (Muslim Spain)", "Students learn about the cultural flourishing of Muslim rule in medieval Spain."),
        ("The Ottoman Empire and Islamic Governance", "Students learn how the Ottoman Empire governed a vast and diverse territory."),
        ("Sufism: Spiritual Traditions in Islam", "Students learn about the spiritual and mystical dimension of Islamic practice."),
        ("Islamic Festivals: Eid al-Fitr and Eid al-Adha", "Students learn the significance and customs of the two major Islamic festivals."),
        ("Islamic Calendar and Timekeeping", "Students learn how the lunar Islamic calendar structures the religious year."),
        ("Etiquette and Manners in Islamic Teaching", "Students explore the everyday manners and etiquette encouraged in Islamic teaching."),
        ("Environmental Stewardship in Islamic Thought", "Students explore how Islamic teaching encourages care for the natural world."),
        ("Muslim Communities Around the World Today", "Students explore the diversity of Muslim communities across the globe today."),
        ("Islamic Perspectives on Peace and Conflict Resolution", "Students explore principles of peace and conflict resolution in Islamic teaching."),
        ("The Concept of Ummah (Global Muslim Community)", "Students explore the idea of a worldwide community united by shared faith."),
    ],
    "Coding": [
        ("Introduction to Variables and Data Types", "Students learn to declare variables and use common data types like strings and integers."),
        ("Conditional Statements", "Students use if, else, and else-if statements to control program flow."),
        ("Loops: For and While", "Students use for and while loops to repeat actions in a program."),
        ("Functions and Parameters", "Students write reusable functions that accept parameters and return values."),
        ("Arrays and Lists", "Students store and manipulate ordered collections of data."),
        ("String Manipulation", "Students learn to search, slice, and transform text within a program."),
        ("Dictionaries and Key-Value Data", "Students store and retrieve data using key-value pair structures."),
        ("Recursion Basics", "Students learn how a function can call itself to solve a problem."),
        ("Algorithms: Searching", "Students compare linear and binary search algorithms for finding data."),
        ("Algorithms: Sorting", "Students compare common sorting algorithms like bubble sort and merge sort."),
        ("Big O Notation and Efficiency", "Students learn to describe how an algorithm's runtime grows with input size."),
        ("Debugging Techniques", "Students learn systematic strategies for finding and fixing bugs in code."),
        ("Error Handling and Exceptions", "Students learn to anticipate and handle errors gracefully in a program."),
        ("Introduction to Python Syntax", "Students learn the basic syntax and structure of the Python language."),
        ("Introduction to JavaScript Syntax", "Students learn the basic syntax and structure of the JavaScript language."),
        ("Version Control with Git", "Students learn to track changes to code using Git commits and branches."),
        ("Working with Files in Code", "Students learn to read from and write to files within a program."),
        ("Introduction to HTML", "Students learn to structure a webpage using HTML elements and tags."),
        ("Introduction to CSS", "Students learn to style a webpage's layout, color, and typography with CSS."),
        ("Building a Simple Webpage", "Students combine HTML and CSS to build and style a basic webpage."),
        ("Introduction to Databases", "Students learn how databases store and organize structured information."),
        ("SQL Basics: Queries", "Students write simple SQL queries to retrieve data from a database."),
        ("APIs and How They Work", "Students learn how programs use APIs to request and exchange data."),
        ("Introduction to Data Structures", "Students learn how data structures organize information for efficient use."),
        ("Stacks and Queues", "Students learn the last-in-first-out and first-in-first-out data structures."),
        ("Linked Lists", "Students learn how linked lists connect data using nodes and pointers."),
        ("Binary Trees", "Students learn how binary trees organize hierarchical data."),
        ("Hash Tables", "Students learn how hash tables enable fast lookup of key-value data."),
        ("Boolean Logic and Truth Tables", "Students learn how AND, OR, and NOT operators combine to control logic."),
        ("Pseudocode and Flowcharts", "Students learn to plan algorithms using pseudocode and flowchart diagrams."),
        ("Software Development Life Cycle", "Students learn the stages software passes through from planning to release."),
        ("Agile and Iterative Development", "Students learn how iterative development breaks projects into manageable cycles."),
        ("Introduction to App Development", "Students learn the basic concepts behind building a simple mobile app."),
        ("Event-Driven Programming", "Students learn how programs respond to user actions like clicks and key presses."),
        ("Introduction to Game Development", "Students learn the basic building blocks used to create simple games."),
        ("Graphics and Simple Animation Coding", "Students learn to draw shapes and create simple animations with code."),
        ("Introduction to Artificial Intelligence Concepts", "Students learn the basic ideas behind how computers can simulate intelligent behavior."),
        ("Introduction to Machine Learning Concepts", "Students learn how computers can learn patterns from data."),
        ("Cybersecurity Basics", "Students learn foundational practices for keeping data and systems secure."),
        ("Computer Networks Basics", "Students learn how computers connect and communicate over networks."),
        ("How the Internet Works", "Students learn how data travels across the internet between devices."),
        ("Binary Numbers and Data Representation", "Students learn how computers represent numbers and text using binary."),
        ("Introduction to Robotics Programming", "Students learn how code is used to control sensors and motors in robots."),
        ("Testing and Quality Assurance", "Students learn why testing code helps catch bugs before release."),
        ("Code Readability and Documentation", "Students learn to write clear code and comments that others can understand."),
        ("Modular Programming and Libraries", "Students learn to organize code into reusable modules and use external libraries."),
        ("Introduction to Command-Line Tools", "Students learn to navigate and run basic commands in a command-line interface."),
        ("Ethics in Computing and Technology", "Students explore ethical questions raised by technology, privacy, and automation."),
        ("Careers in Computer Science", "Students explore the variety of careers available in computing and technology."),
    ],
    "World Literature": [
        ("Greek Mythology and Epic Traditions", "Students explore the gods, heroes, and themes of ancient Greek mythology."),
        ("Homer's Odyssey: Themes of Journey and Identity", "Students examine themes of homecoming and identity in Homer's epic."),
        ("The Epic of Gilgamesh and Ancient Storytelling", "Students explore themes of mortality and friendship in an ancient Mesopotamian epic."),
        ("One Thousand and One Nights: Frame Narrative", "Students examine how nested storytelling structures a classic collection of tales."),
        ("Dante's Divine Comedy: Allegory and Structure", "Students examine the allegorical journey structure of Dante's medieval epic."),
        ("Miguel de Cervantes and Don Quixote", "Students examine themes of idealism and reality in a foundational Spanish novel."),
        ("Russian Literature: Tolstoy and Moral Themes", "Students examine moral and social themes explored in Tolstoy's writing."),
        ("Russian Literature: Dostoevsky and Psychological Depth", "Students examine psychological complexity in Dostoevsky's characters."),
        ("Franz Kafka and Existential Themes", "Students examine themes of alienation and absurdity in Kafka's fiction."),
        ("Gabriel Garcia Marquez and Magical Realism", "Students examine how magical realism blends the fantastic with the everyday."),
        ("Latin American Literature Overview", "Students survey major movements and voices in Latin American literature."),
        ("Chinua Achebe and African Literature", "Students examine how Achebe's writing portrays colonial impact on African society."),
        ("African Oral Storytelling Traditions", "Students explore the role of oral tradition in preserving African cultural history."),
        ("Japanese Literature: Haiku and Nature", "Students examine how haiku captures fleeting moments in nature."),
        ("Japanese Literature: The Tale of Genji", "Students explore the courtly world portrayed in an early Japanese classic."),
        ("Chinese Classical Literature Traditions", "Students survey major forms and themes in classical Chinese literature."),
        ("Rabindranath Tagore and Bengali Literature", "Students explore themes of nature and spirituality in Tagore's work."),
        ("Indian Epic Traditions: The Ramayana", "Students examine themes of duty and virtue in the Indian epic Ramayana."),
        ("Indian Epic Traditions: The Mahabharata", "Students examine themes of conflict and dharma in the Indian epic Mahabharata."),
        ("Toni Morrison and American Literary Voice", "Students examine how Morrison's fiction explores identity and history."),
        ("Harlem Renaissance Writers", "Students survey writers who shaped the cultural flowering of the Harlem Renaissance."),
        ("Maya Angelou and Autobiographical Writing", "Students examine themes of resilience in Angelou's autobiographical writing."),
        ("George Orwell and Political Allegory", "Students examine how Orwell used allegory to critique political power."),
        ("Dystopian World Literature", "Students compare dystopian visions of society across different literary traditions."),
        ("Virginia Woolf and Modernist Style", "Students examine Woolf's innovative narrative techniques and modernist style."),
        ("James Joyce and Stream of Consciousness", "Students examine how Joyce's stream-of-consciousness style captures inner thought."),
        ("Fyodor Dostoevsky's Crime and Punishment: Moral Conflict", "Students examine the moral conflict at the center of Dostoevsky's novel."),
        ("Victor Hugo and Les Miserables: Social Justice Themes", "Students examine themes of justice and redemption in Hugo's novel."),
        ("Albert Camus and the Theme of the Absurd", "Students examine Camus's exploration of meaning and the absurd."),
        ("Jean-Paul Sartre and Existentialist Literature", "Students examine existentialist themes of freedom and choice in Sartre's writing."),
        ("Anton Chekhov and the Modern Short Story", "Students examine how Chekhov shaped the modern short story form."),
        ("Nordic Literature and Folklore", "Students survey themes and traditions found in Nordic literature and folklore."),
        ("Isabel Allende and Family Sagas", "Students examine multigenerational storytelling in Allende's fiction."),
        ("Chimamanda Ngozi Adichie and Contemporary African Voices", "Students examine contemporary themes of identity in Adichie's work."),
        ("Khaled Hosseini and Afghan Narratives", "Students examine themes of friendship and resilience in Hosseini's novels."),
        ("Literature of the Holocaust: Bearing Witness", "Students examine how survivors used literature to bear witness to history."),
        ("Anne Frank's Diary: A Voice from History", "Students examine the historical significance of a young diarist's perspective."),
        ("World War Literature and the Soldier's Experience", "Students examine how literature portrays the personal experience of war."),
        ("Folk Tales and Fables Across Cultures", "Students compare folk tales and fables from different world cultures."),
        ("Comparative Mythology", "Students compare mythological traditions across different world cultures."),
        ("The Global Rise of the Graphic Novel", "Students examine how graphic novels tell stories through combined text and image."),
        ("Translation and Its Challenges in Literature", "Students explore how meaning can shift when literature is translated."),
        ("Migrant and Diaspora Literature", "Students examine literature that portrays the experience of migration and displacement."),
        ("Indigenous Literature and Storytelling", "Students explore storytelling traditions from Indigenous cultures worldwide."),
        ("Middle Eastern Literature: Voices and Themes", "Students survey themes and voices found in modern Middle Eastern literature."),
        ("Caribbean Literature and Identity", "Students examine how Caribbean writers explore identity and history."),
        ("Literature of Social Protest", "Students examine how literature has been used to protest injustice."),
        ("The Global Novel in the 21st Century", "Students survey trends shaping fiction written for a global readership today."),
        ("Comparing Literary Traditions Across Cultures", "Students compare storytelling conventions across different world literary traditions."),
    ],
    "Art": [
        ("Elements of Art: Line, Shape, and Form", "Students learn the foundational visual elements used to build any artwork."),
        ("Principles of Design: Balance and Contrast", "Students learn how balance and contrast organize a composition."),
        ("Color Theory Basics", "Students learn the color wheel and relationships between primary and secondary colors."),
        ("Color Mixing and Palettes", "Students practice mixing paint to create custom colors and palettes."),
        ("Drawing Fundamentals: Line and Contour", "Students practice observational drawing using line and contour technique."),
        ("Shading and Value Techniques", "Students learn to use shading to create the illusion of depth and light."),
        ("Perspective Drawing: One-Point", "Students learn to draw depth using a single vanishing point."),
        ("Perspective Drawing: Two-Point", "Students learn to draw depth and volume using two vanishing points."),
        ("Figure Drawing Basics", "Students practice drawing basic human proportions and poses."),
        ("Portraiture Techniques", "Students practice techniques for capturing facial features and likeness."),
        ("Still Life Composition", "Students arrange and draw or paint a still life composition."),
        ("Landscape Drawing and Painting", "Students practice capturing natural scenery through drawing and painting."),
        ("Watercolor Painting Techniques", "Students learn wet-on-wet and wet-on-dry watercolor painting techniques."),
        ("Acrylic Painting Techniques", "Students learn layering and blending techniques using acrylic paint."),
        ("Oil Painting Basics", "Students learn the basic properties and handling of oil paint."),
        ("Printmaking Techniques", "Students learn basic relief printmaking techniques to produce repeated images."),
        ("Sculpture: Working in Clay", "Students learn hand-building techniques for creating clay sculptures."),
        ("Sculpture: Assemblage and Found Objects", "Students create sculptures by combining and repurposing found objects."),
        ("Ceramics and Pottery Basics", "Students learn basic pottery forming and glazing techniques."),
        ("Collage and Mixed Media Art", "Students combine varied materials to create layered collage artworks."),
        ("Introduction to Art History", "Students learn how to place artworks within their historical context."),
        ("Ancient Art: Egypt and Mesopotamia", "Students examine the artistic conventions of ancient Egyptian and Mesopotamian art."),
        ("Classical Greek and Roman Art", "Students examine idealized form and realism in classical Greek and Roman art."),
        ("Renaissance Art and Techniques", "Students examine how Renaissance artists developed perspective and realism."),
        ("Baroque Art and Drama", "Students examine dramatic light and movement in Baroque period art."),
        ("Impressionism and Light", "Students examine how Impressionist painters captured fleeting effects of light."),
        ("Post-Impressionism", "Students examine how Post-Impressionist artists pushed beyond Impressionist style."),
        ("Cubism and Abstract Forms", "Students examine how Cubist artists fragmented form into geometric shapes."),
        ("Surrealism and the Subconscious", "Students examine how Surrealist artists depicted dreamlike, subconscious imagery."),
        ("Pop Art Movement", "Students examine how Pop artists drew on popular culture and mass media."),
        ("Abstract Expressionism", "Students examine how Abstract Expressionists used gesture and color to convey emotion."),
        ("Photography Basics: Composition", "Students learn compositional techniques such as the rule of thirds in photography."),
        ("Photography Basics: Light and Exposure", "Students learn how light and exposure settings affect a photograph."),
        ("Digital Art and Illustration", "Students learn the basics of creating illustrations using digital tools."),
        ("Graphic Design Principles", "Students learn how layout, hierarchy, and typography guide graphic design."),
        ("Introduction to Animation", "Students learn the basic principles behind creating the illusion of movement."),
        ("Art Criticism and Analysis", "Students learn a structured method for describing and evaluating artworks."),
        ("Symbolism in Visual Art", "Students learn to identify and interpret symbolic meaning in artworks."),
        ("Cultural and Traditional Art Forms", "Students survey traditional art forms from cultures around the world."),
        ("Street Art and Public Murals", "Students examine how street art and murals engage with public spaces."),
        ("Textile Art and Fiber Arts", "Students explore techniques used in weaving, embroidery, and fiber art."),
        ("Architecture as an Art Form", "Students examine how buildings combine function and artistic design."),
        ("Art of the Islamic World", "Students examine geometric pattern and ornamentation in Islamic art."),
        ("Art of East Asia", "Students examine artistic traditions from China, Japan, and Korea."),
        ("African Art Traditions", "Students examine sculpture, mask-making, and pattern in African art traditions."),
        ("Indigenous Art of the Americas", "Students examine artistic traditions of Indigenous peoples of the Americas."),
        ("Curating an Art Exhibition", "Students learn how curators select and organize artworks for display."),
        ("Building an Art Portfolio", "Students learn how to select and present their best work in a portfolio."),
        ("Careers in the Visual Arts", "Students explore the range of careers available in the visual arts."),
    ],
    "Music": [
        ("Elements of Music: Rhythm and Beat", "Students learn how rhythm and steady beat form the foundation of music."),
        ("Elements of Music: Melody", "Students learn how melodies are built from pitch and phrasing."),
        ("Elements of Music: Harmony", "Students learn how combined pitches create harmony and accompaniment."),
        ("Reading Musical Notation", "Students learn to read notes, rests, and staff notation."),
        ("Understanding Key Signatures", "Students learn how key signatures indicate the sharps and flats used in a piece."),
        ("Scales: Major and Minor", "Students learn to build and recognize major and minor scales."),
        ("Chords and Chord Progressions", "Students learn to build chords and recognize common chord progressions."),
        ("Time Signatures and Meter", "Students learn how time signatures organize beats into measures."),
        ("Dynamics and Musical Expression", "Students learn how dynamic markings shape the loudness and expression of music."),
        ("Tempo and Its Effects", "Students learn how tempo affects the mood and energy of a piece."),
        ("Introduction to Music Theory", "Students learn foundational concepts used to analyze and understand music."),
        ("Ear Training Basics", "Students practice identifying pitches, intervals, and rhythms by ear."),
        ("Sight-Singing Fundamentals", "Students practice singing notated melodies at first sight."),
        ("History of Western Classical Music", "Students survey the major periods of Western classical music history."),
        ("The Baroque Period in Music", "Students examine the ornate style and key composers of the Baroque period."),
        ("The Classical Period in Music", "Students examine the balanced forms and key composers of the Classical period."),
        ("The Romantic Period in Music", "Students examine the emotional expression and key composers of the Romantic period."),
        ("20th Century Classical Music", "Students examine how classical composers experimented with new sounds in the 1900s."),
        ("The Orchestra: Instrument Families", "Students learn how string, woodwind, brass, and percussion instruments form an orchestra."),
        ("String Instruments Overview", "Students learn the characteristics and playing techniques of string instruments."),
        ("Woodwind Instruments Overview", "Students learn the characteristics and playing techniques of woodwind instruments."),
        ("Brass Instruments Overview", "Students learn the characteristics and playing techniques of brass instruments."),
        ("Percussion Instruments Overview", "Students learn the characteristics and playing techniques of percussion instruments."),
        ("The Piano: Basics and Technique", "Students learn basic keyboard technique and simple piano pieces."),
        ("The Guitar: Basics and Technique", "Students learn basic chords and strumming technique on guitar."),
        ("Voice and Vocal Technique", "Students learn healthy vocal technique for singing."),
        ("Choral Singing and Ensemble Skills", "Students practice blending their voice within a choral ensemble."),
        ("Jazz History and Improvisation", "Students learn the origins of jazz and basic principles of improvisation."),
        ("Blues Music Origins", "Students learn the historical roots and structure of blues music."),
        ("The History of Rock Music", "Students survey the origins and evolution of rock music."),
        ("Hip-Hop: History and Culture", "Students learn the origins and cultural significance of hip-hop music."),
        ("Pop Music Production", "Students learn basic concepts behind how popular music is produced."),
        ("Electronic Music and Synthesis", "Students learn how electronic instruments and synthesizers create sound."),
        ("World Music Traditions: Africa", "Students survey musical traditions and instruments from across Africa."),
        ("World Music Traditions: Asia", "Students survey musical traditions and instruments from across Asia."),
        ("World Music Traditions: Latin America", "Students survey musical traditions and instruments from Latin America."),
        ("World Music Traditions: The Middle East", "Students survey musical traditions and instruments from the Middle East."),
        ("Music Technology and Recording Basics", "Students learn basic concepts of recording and editing audio."),
        ("Introduction to Digital Audio Workstations", "Students learn the basics of composing and arranging music using software."),
        ("Film Scoring and Music in Media", "Students learn how music is composed to support film and media storytelling."),
        ("Music and Emotion", "Students explore how musical elements can evoke different emotional responses."),
        ("Analyzing a Musical Piece", "Students practice describing the structure and elements of a piece of music."),
        ("Musical Form: Verse-Chorus Structure", "Students learn how verse-chorus structure organizes many popular songs."),
        ("Musical Form: Sonata and Rondo", "Students learn how sonata and rondo forms organize classical compositions."),
        ("Improvisation Techniques", "Students practice creating spontaneous melodies within a given musical framework."),
        ("Band and Ensemble Performance Skills", "Students practice the listening and coordination skills needed for group performance."),
        ("Music Business Basics", "Students learn the basics of how music is published, distributed, and monetized."),
        ("Careers in Music", "Students explore the range of careers available in the music industry."),
        ("Concert Etiquette and Live Performance Appreciation", "Students learn appropriate audience behavior and how to appreciate live performance."),
    ],
    "Survival Skills": [
        ("Basic First Aid Principles", "Students learn foundational first aid steps for treating common injuries."),
        ("CPR and Emergency Response", "Students learn the basic steps of CPR and how to respond to a medical emergency."),
        ("Wilderness Navigation with Map and Compass", "Students learn to navigate outdoors using a map and compass."),
        ("Navigation Using Natural Signs", "Students learn to estimate direction using the sun, stars, and natural landmarks."),
        ("Building a Emergency Shelter", "Students learn techniques for constructing a basic shelter in an emergency."),
        ("Fire-Starting Techniques", "Students learn safe methods for starting and maintaining a fire."),
        ("Water Purification Methods", "Students learn methods for making water safe to drink in an emergency."),
        ("Foraging Safely for Edible Plants", "Students learn general principles for safely identifying edible wild plants."),
        ("Basic Knot Tying", "Students learn to tie essential knots used in outdoor and emergency situations."),
        ("Signaling for Rescue", "Students learn methods for signaling location to rescuers in an emergency."),
        ("Reading Weather Signs", "Students learn to observe natural signs that indicate changing weather."),
        ("Understanding Hypothermia and Heatstroke", "Students learn to recognize and respond to hypothermia and heatstroke."),
        ("Wilderness Wildlife Safety", "Students learn how to safely avoid and respond to encounters with wildlife."),
        ("Packing an Emergency Kit", "Students learn what essential items belong in a basic emergency preparedness kit."),
        ("Basic Camping Skills", "Students learn foundational skills for safely camping outdoors."),
        ("Trail Safety and Hiking Preparedness", "Students learn how to prepare for and stay safe while hiking on trails."),
        ("Water Safety and Swimming Survival Skills", "Students learn basic water safety and self-rescue swimming skills."),
        ("Basic Self-Defense Awareness", "Students learn basic awareness strategies for personal safety."),
        ("Home Fire Safety", "Students learn how to prevent and respond safely to a fire at home."),
        ("Earthquake Safety Procedures", "Students learn the recommended steps to stay safe during an earthquake."),
        ("Flood Safety Procedures", "Students learn the recommended steps to stay safe during a flood."),
        ("Severe Storm Safety", "Students learn the recommended steps to stay safe during severe storms."),
        ("Urban Emergency Preparedness", "Students learn strategies for preparing for emergencies in a city environment."),
        ("Emergency Communication Planning", "Students learn how to plan reliable communication during an emergency."),
        ("Family Emergency Planning", "Students learn how families can create a shared emergency response plan."),
        ("Food Storage and Preservation Basics", "Students learn basic principles for safely storing food for emergencies."),
        ("Basic Sewing and Repair Skills", "Students learn basic sewing skills useful for repairing gear and clothing."),
        ("Basic Tool Use and Safety", "Students learn to safely use common hand tools."),
        ("Understanding Maps and Terrain", "Students learn to interpret topographic features shown on maps."),
        ("Orienteering Basics", "Students learn to navigate a course using a map and compass under time pressure."),
        ("Cold Weather Survival Skills", "Students learn strategies for staying safe and warm in cold environments."),
        ("Hot Climate Survival Skills", "Students learn strategies for staying safe and hydrated in hot environments."),
        ("Building a Fire Safely", "Students learn safe fire-building practices and fire safety precautions."),
        ("Basic Rope and Cordage Skills", "Students learn practical uses of rope and cordage in outdoor situations."),
        ("Emergency Sanitation and Hygiene", "Students learn how to maintain hygiene and sanitation during an emergency."),
        ("Recognizing and Avoiding Hazardous Situations", "Students learn to identify and avoid common hazardous situations."),
        ("Basic Bicycle and Road Safety", "Students learn safe practices for cycling and navigating roads."),
        ("Basic First Aid for Burns and Cuts", "Students learn appropriate first aid steps for treating burns and cuts."),
        ("Choking Response and the Heimlich Maneuver", "Students learn how to recognize and respond to a choking emergency."),
        ("Understanding Emergency Services", "Students learn how to appropriately contact and work with emergency services."),
        ("Community Emergency Response Teams (CERT)", "Students learn how trained community volunteers assist during disasters."),
        ("Basic Situational Awareness", "Students learn to observe surroundings and anticipate potential risks."),
        ("Stress Management in Crisis Situations", "Students learn techniques for staying calm and focused during a crisis."),
        ("Animal Encounter Safety", "Students learn how to safely respond to encounters with unfamiliar animals."),
        ("Basic Boating and Water Safety", "Students learn foundational safety practices for boating and being near water."),
        ("Power Outage Preparedness", "Students learn how to prepare for and safely manage an extended power outage."),
        ("Evacuation Planning", "Students learn how to plan and practice a safe evacuation route."),
        ("Basic Wilderness First Aid Kit Assembly", "Students learn what to include in a first aid kit for outdoor use."),
        ("Sustainable Living and Self-Reliance Basics", "Students learn foundational skills for sustainable, self-reliant living."),
    ],
    "Cooking": [
        ("Kitchen Safety Fundamentals", "Students learn essential safety practices for working in a kitchen."),
        ("Knife Skills and Safe Cutting Techniques", "Students learn safe and effective knife handling and cutting techniques."),
        ("Understanding Food Hygiene", "Students learn practices that prevent contamination and foodborne illness."),
        ("Reading and Following Recipes", "Students learn to interpret recipe instructions and cooking terminology."),
        ("Measuring Ingredients Accurately", "Students learn to accurately measure both dry and liquid ingredients."),
        ("Basic Cooking Methods: Boiling and Simmering", "Students learn the technique and uses of boiling and simmering."),
        ("Basic Cooking Methods: Sauteing and Frying", "Students learn the technique and uses of sauteing and frying."),
        ("Basic Cooking Methods: Roasting and Baking", "Students learn the technique and uses of roasting and baking."),
        ("Basic Cooking Methods: Grilling", "Students learn the technique and uses of grilling food."),
        ("Understanding Heat and Cooking Times", "Students learn how heat level and time affect the outcome of cooked food."),
        ("Introduction to Baking: Bread", "Students learn the basic process of mixing, proofing, and baking bread."),
        ("Introduction to Baking: Pastries", "Students learn the basic techniques for making simple pastries."),
        ("Cake Baking Basics", "Students learn the basic steps and techniques for baking a cake."),
        ("Understanding Leavening Agents", "Students learn how yeast, baking soda, and baking powder make baked goods rise."),
        ("Sauce Making Basics", "Students learn techniques for preparing basic savory sauces."),
        ("Stock and Broth Preparation", "Students learn how to prepare a basic stock or broth from scratch."),
        ("Soup Preparation Techniques", "Students learn techniques for preparing a variety of soups."),
        ("Salad Preparation and Dressings", "Students learn to prepare salads and basic homemade dressings."),
        ("Egg Cookery Techniques", "Students learn multiple methods for cooking eggs."),
        ("Dairy in Cooking", "Students learn how dairy products are used and behave in cooking."),
        ("Meat Preparation and Cooking Safety", "Students learn safe handling and cooking techniques for meat."),
        ("Poultry Preparation and Cooking Safety", "Students learn safe handling and cooking techniques for poultry."),
        ("Seafood Preparation Basics", "Students learn basic techniques for preparing and cooking seafood."),
        ("Vegetarian Cooking Basics", "Students learn techniques for preparing balanced vegetarian meals."),
        ("Vegan Cooking Principles", "Students learn principles for preparing meals without animal products."),
        ("Grain and Rice Cookery", "Students learn techniques for cooking rice and other grains properly."),
        ("Pasta Making and Cooking", "Students learn the basics of making and properly cooking pasta."),
        ("Herbs and Spices in Cooking", "Students learn how herbs and spices are used to season dishes."),
        ("Flavor Pairing and Balance", "Students learn principles for balancing sweet, salty, sour, and savory flavors."),
        ("Understanding Nutrition Basics", "Students learn the basic food groups and principles of balanced nutrition."),
        ("Meal Planning and Budgeting", "Students learn to plan meals while managing cost and nutrition."),
        ("Understanding Food Labels", "Students learn to read and interpret nutrition labels on packaged food."),
        ("Food Preservation: Canning and Pickling", "Students learn basic techniques for canning and pickling food."),
        ("Food Preservation: Freezing and Drying", "Students learn basic techniques for freezing and drying food for storage."),
        ("Fermentation Basics", "Students learn the basic science and technique behind fermenting foods."),
        ("Global Cuisine: Mediterranean", "Students explore the ingredients and dishes of Mediterranean cuisine."),
        ("Global Cuisine: East Asian", "Students explore the ingredients and dishes of East Asian cuisine."),
        ("Global Cuisine: South Asian", "Students explore the ingredients and dishes of South Asian cuisine."),
        ("Global Cuisine: Middle Eastern", "Students explore the ingredients and dishes of Middle Eastern cuisine."),
        ("Global Cuisine: Latin American", "Students explore the ingredients and dishes of Latin American cuisine."),
        ("Baking with Alternative Flours", "Students learn to bake using flours other than wheat."),
        ("Plating and Food Presentation", "Students learn basic principles for presenting food attractively."),
        ("Reducing Food Waste in the Kitchen", "Students learn practical strategies for minimizing food waste."),
        ("Sustainable and Ethical Food Choices", "Students explore how food choices connect to sustainability and ethics."),
        ("Understanding Food Allergies and Substitutions", "Students learn to recognize common allergens and suitable substitutions."),
        ("Basic Pastry: Doughs and Crusts", "Students learn to prepare basic pastry doughs and crusts."),
        ("Dessert Making Basics", "Students learn foundational techniques for preparing simple desserts."),
        ("Beverage Preparation Basics", "Students learn techniques for preparing basic hot and cold beverages."),
        ("Kitchen Equipment and Tool Care", "Students learn to properly use and maintain common kitchen tools and equipment."),
    ],
    "Foreign Languages": [
        ("Spanish Grammar: Present Tense Verbs", "Students learn to conjugate regular Spanish verbs in the present tense."),
        ("Spanish Grammar: Ser vs Estar", "Students learn to distinguish between the two Spanish verbs meaning 'to be'."),
        ("Spanish Vocabulary: Everyday Conversation", "Students build vocabulary for common everyday conversations in Spanish."),
        ("Spanish Literature: Introduction to Cervantes", "Students learn about the significance of Cervantes in Spanish literary history."),
        ("French Grammar: Articles and Gender", "Students learn how French nouns take gendered articles."),
        ("French Grammar: Present Tense Conjugation", "Students learn to conjugate regular French verbs in the present tense."),
        ("French Vocabulary: Daily Life", "Students build vocabulary for describing daily routines and activities in French."),
        ("French Literature: Introduction to Moliere", "Students learn about the significance of Moliere in French literary history."),
        ("German Grammar: Noun Cases", "Students learn how German nouns change form depending on grammatical case."),
        ("German Grammar: Word Order", "Students learn the rules governing word order in German sentences."),
        ("German Vocabulary: Everyday Expressions", "Students build vocabulary for common everyday expressions in German."),
        ("German Literature: Introduction to Goethe", "Students learn about the significance of Goethe in German literary history."),
        ("Mandarin Chinese: Tones and Pronunciation", "Students learn the four tones used to distinguish meaning in Mandarin."),
        ("Mandarin Chinese: Basic Characters", "Students learn to read and write a set of basic Mandarin characters."),
        ("Mandarin Chinese: Everyday Vocabulary", "Students build vocabulary for everyday conversation in Mandarin."),
        ("Japanese Writing Systems: Hiragana and Katakana", "Students learn to read and write the hiragana and katakana syllabaries."),
        ("Japanese Grammar Basics", "Students learn the basic sentence structure and particles used in Japanese."),
        ("Japanese Vocabulary: Daily Conversation", "Students build vocabulary for everyday conversation in Japanese."),
        ("Korean Writing System: Hangul", "Students learn to read and write using the Korean Hangul alphabet."),
        ("Korean Grammar Basics", "Students learn the basic sentence structure used in Korean."),
        ("Italian Grammar: Verb Conjugation", "Students learn to conjugate regular Italian verbs in the present tense."),
        ("Italian Vocabulary: Everyday Life", "Students build vocabulary for describing everyday life in Italian."),
        ("Italian Literature: Introduction to Dante", "Students learn about the significance of Dante in Italian literary history."),
        ("Portuguese Grammar Basics", "Students learn the basic verb conjugation and sentence structure of Portuguese."),
        ("Portuguese Vocabulary: Daily Conversation", "Students build vocabulary for everyday conversation in Portuguese."),
        ("Russian Alphabet: Cyrillic Script", "Students learn to read and write using the Cyrillic alphabet."),
        ("Russian Grammar Basics", "Students learn the basic grammar and case system of Russian."),
        ("Hindi Grammar Basics", "Students learn the basic sentence structure and verb forms used in Hindi."),
        ("Hindi Vocabulary: Everyday Conversation", "Students build vocabulary for everyday conversation in Hindi."),
        ("Swahili Grammar and Vocabulary Basics", "Students learn foundational grammar and vocabulary in Swahili."),
        ("Arabic Grammar: Root Letter System", "Students learn how Arabic words are built from a system of root letters."),
        ("Arabic Vocabulary: Everyday Conversation", "Students build vocabulary for everyday conversation in Arabic."),
        ("Arabic Calligraphy and Script", "Students learn the basics of reading and writing the Arabic script."),
        ("Turkish Grammar Basics", "Students learn the basic agglutinative grammar structure of Turkish."),
        ("Turkish Vocabulary: Daily Life", "Students build vocabulary for describing daily life in Turkish."),
        ("Language Families and Linguistic Roots", "Students learn how world languages are grouped into related families."),
        ("Cognates and False Friends Across Languages", "Students learn to recognize helpful cognates and misleading false friends."),
        ("Idioms and Expressions in World Languages", "Students explore idiomatic expressions and their meanings across languages."),
        ("Comparative Grammar: Verb Tenses Across Languages", "Students compare how different languages express past, present, and future."),
        ("Sign Language Basics and Deaf Culture", "Students learn basic signs and gain awareness of Deaf culture and community."),
        ("Latin Roots in Modern Languages", "Students learn how Latin roots shape vocabulary in many modern languages."),
        ("Greek Roots in Modern Languages", "Students learn how Greek roots shape vocabulary in many modern languages."),
        ("Cultural Etiquette in Language Learning", "Students learn how cultural context shapes polite and appropriate communication."),
        ("Conversational Practice: Greetings and Introductions", "Students practice greetings and self-introductions in a new language."),
        ("Conversational Practice: Travel and Directions", "Students practice asking for and giving directions in a new language."),
        ("Conversational Practice: Food and Dining", "Students practice ordering food and discussing meals in a new language."),
        ("Reading Comprehension Strategies in a New Language", "Students learn strategies for understanding texts written in a language they are learning."),
        ("Writing Short Compositions in a Foreign Language", "Students practice writing short, structured compositions in a new language."),
        ("Language Learning Strategies and Immersion Techniques", "Students learn strategies, including immersion, for accelerating language acquisition."),
    ],
}
