"""New (title, summary) topics to expand Grade 1 subjects to a minimum
of 20 lessons each. Consumed by merge_grade_topics_expansion.py, which
builds full lesson objects from these pairs and appends them to the
existing lessons in backend/syllabus/grade1.json.
"""

GRADE = 1
MODULES: dict[str, list[tuple[str, str]]] = {
    "Math": [
        ("Counting to 100", "Children practice counting by ones from 1 to 100 using number charts and everyday objects."),
        ("Skip Counting by 2s, 5s, and 10s", "Children learn to count forward in jumps of 2, 5, and 10 to build a foundation for multiplication."),
        ("Comparing Numbers", "Children compare two numbers to say which is more, less, or equal using objects and number lines."),
        ("Ordinal Numbers", "Children learn to use first through tenth to describe the position of people or things in a line."),
        ("Addition to 20", "Children add two numbers with sums up to 20 using counters, fingers, and simple number lines."),
        ("Subtraction to 20", "Children subtract numbers within 20 using objects and number lines to find the difference."),
        ("Number Bonds to 10", "Children explore pairs of numbers that combine to make 10, building a base for mental math."),
        ("Place Value: Tens and Ones", "Children learn that two-digit numbers are made of groups of ten and leftover ones."),
        ("2D Shapes", "Children identify and describe flat shapes such as circles, squares, triangles, and rectangles."),
        ("3D Shapes", "Children identify solid shapes such as cubes, spheres, cones, and cylinders in everyday objects."),
        ("Position Words", "Children use words like above, below, next to, and between to describe where objects are located."),
        ("Money: Recognizing Coins", "Children learn to recognize common coins and understand that money is used to buy things."),
    ],
    "English": [
        ("Phonics: Blending Sounds into Words", "Children practice blending individual letter sounds together to read simple words."),
        ("Phonics: Beginning and Ending Sounds", "Children identify the first and last sounds they hear in short, familiar words."),
        ("Vowels and Consonants", "Children learn to tell the difference between vowel and consonant letters in the alphabet."),
        ("Upper and Lower Case Letters", "Children learn to recognize and match capital and small letters of the alphabet."),
        ("Sight Words: Building Vocabulary", "Children learn to instantly recognize common high-frequency words in simple texts."),
        ("Listening and Following Directions", "Children practice listening carefully and following one- and two-step spoken instructions."),
        ("Speaking and Sharing Ideas", "Children practice speaking clearly in complete sentences to share their thoughts with a group."),
        ("Storytelling: Retelling a Story in Order", "Children retell the beginning, middle, and end of a familiar story in the correct order."),
        ("Grammar: Adjectives and Describing Words", "Children learn to use describing words that tell more about the size, color, or feel of things."),
        ("Grammar: Simple Punctuation", "Children learn to recognize and use a capital letter to start a sentence and a period to end it."),
        ("Handwriting: Letter Formation", "Children practice forming each letter of the alphabet with correct stroke order and shape."),
        ("Writing: Labels and Lists", "Children practice writing simple labels and short lists to name and organize familiar objects."),
        ("Reading Comprehension: Who, What, Where", "Children answer simple who, what, and where questions about a short story they have read."),
        ("Alphabetical Order", "Children learn to put a small group of words in order based on their first letter."),
    ],
    "Science": [
        ("The Five Senses", "Children learn how the eyes, ears, nose, tongue, and skin help them explore and understand the world."),
        ("Weather and Seasons", "Children observe daily weather and learn how the four seasons bring different temperatures and conditions."),
        ("Day and Night", "Children learn that day and night happen because the Earth spins, causing the sun to appear and disappear."),
        ("Our Solar System: The Sun and Moon", "Children learn simple facts about the sun as a source of light and heat and the moon as it changes shape in the sky."),
        ("Animal Babies and Their Parents", "Children learn how baby animals are cared for and how they grow to look like their parents."),
        ("Life Cycle of a Butterfly", "Children learn the stages a butterfly goes through, from egg to caterpillar to chrysalis to butterfly."),
        ("Life Cycle of a Plant", "Children learn how a plant grows from a seed to a sprout to a full-grown plant that makes new seeds."),
        ("Healthy Foods and Nutrition", "Children learn to sort foods into healthy groups and understand why eating a variety of foods keeps them strong."),
        ("My Body: Parts and Functions", "Children learn the names of major body parts and the simple job each one does."),
        ("Water and Its Uses", "Children learn where water comes from and the many ways people, plants, and animals use it every day."),
        ("States of Matter: Solid, Liquid, Gas", "Children explore everyday examples of solids, liquids, and gases and how they feel and behave differently."),
        ("Push and Pull: Simple Forces", "Children explore how pushing and pulling can make objects start, stop, speed up, or change direction."),
        ("Magnets and What They Attract", "Children experiment with magnets to discover which everyday objects they attract and which they do not."),
        ("Floating and Sinking", "Children test different objects in water to explore why some float and others sink."),
        ("Caring for the Environment", "Children learn simple ways to take care of nature, such as recycling, not littering, and saving water."),
        ("Rocks and Soil", "Children explore different types of rocks and soil and learn how they are used by plants and people."),
        ("Simple Machines: Ramps and Wheels", "Children explore how ramps and wheels make it easier to move objects from one place to another."),
    ],
    "Geography": [
        ("Introducing Maps and Globes", "Children learn that maps and globes are pictures that help us find places in the world."),
        ("The Four Directions: North, South, East, West", "Children learn the four main directions and practice using them to describe simple locations."),
        ("Land and Water on Earth", "Children learn that the Earth is made up of land areas and water areas such as oceans and lakes."),
        ("Mountains and Hills", "Children learn what mountains and hills look like and how they are different from flat land."),
        ("Rivers and Lakes", "Children learn how rivers flow and how lakes form, and why people and animals depend on them."),
        ("Oceans of the World", "Children learn the names of the world's major oceans and that they hold most of Earth's water."),
        ("Continents of the World", "Children learn the names and locations of the world's seven continents on a map."),
        ("Countries and Flags", "Children learn that the world is divided into countries, each with its own name and flag."),
        ("My Country and Its Capital", "Children learn the name of their own country and its capital city."),
        ("Cities and Villages", "Children compare busy cities with quieter villages and describe how each place looks and feels."),
        ("Weather Around the World", "Children learn that different places on Earth can have very different weather at the same time."),
        ("Deserts and Their Features", "Children learn that deserts are dry places with little rain and learn about the plants and animals that live there."),
        ("Forests and Their Features", "Children learn that forests are places full of trees and learn about the plants and animals that live there."),
        ("Islands", "Children learn that an island is land completely surrounded by water and can name a few famous islands."),
        ("Seasons Around the World", "Children learn that some parts of the world have different seasons happening at the same time."),
        ("Transportation: Getting from Place to Place", "Children learn about different ways people travel over land, water, and air to reach faraway places."),
        ("Homes Around the World", "Children learn that people build different kinds of homes depending on the climate and materials available."),
        ("Farms and Rural Life", "Children learn what a farm is and how farmers grow food and raise animals in the countryside."),
        ("Community Helpers and Places", "Children learn about important places in a community, such as schools, hospitals, and fire stations, and the people who work there."),
    ],
    "World History": [
        ("What is History? Long Ago and Today", "Children learn that history is the story of things that happened in the past, before they were born."),
        ("How People Lived Long Ago", "Children compare how people found food, built shelter, and traveled long ago with how people live today."),
        ("Cave Paintings and Early Communication", "Children learn that early people drew pictures on cave walls to share stories and ideas before writing existed."),
        ("Ancient Egypt and the Pyramids", "Children learn simple facts about ancient Egypt and the huge stone pyramids its people built long ago."),
        ("Ancient China and Its Inventions", "Children learn about ancient China and simple everyday inventions, such as paper, that came from there."),
        ("Ancient Greece and the First Olympics", "Children learn that the first Olympic Games began in ancient Greece as a friendly sports competition."),
        ("Ancient Rome and Its Great Roads", "Children learn that the ancient Romans built strong roads and buildings that lasted a very long time."),
        ("The First Farmers", "Children learn how early people changed from hunting and gathering to growing their own crops."),
        ("Famous Explorers and Their Journeys", "Children learn about brave explorers from history who traveled to discover new lands."),
        ("Homes of the Past", "Children compare the materials and designs used to build homes long ago with homes built today."),
        ("Clothes of the Past", "Children compare the kinds of clothing people wore long ago with the clothing people wear today."),
        ("Toys and Games of the Past", "Children compare simple toys and games children played with long ago to the toys children enjoy today."),
        ("Transportation Then and Now", "Children compare how people traveled long ago, such as on foot or by horse, with how people travel today."),
        ("Communication Then and Now", "Children compare how people sent messages long ago with how people communicate quickly today."),
        ("Important Inventions That Changed the World", "Children learn about a few simple inventions from history that changed how people live."),
        ("Castles and Kings of Long Ago", "Children learn simple facts about castles and the kings and queens who once lived in them."),
        ("Famous Kind Leaders in History", "Children learn about a few historical leaders remembered for their kindness and fairness."),
        ("Celebrations and Traditions Through Time", "Children learn how some celebrations and traditions have been passed down and changed over many years."),
        ("Timelines: Ordering Events", "Children practice putting a small set of events in the order they happened using a simple timeline."),
    ],
    "Islamic Studies": [
        ("Being Kind to Others", "Children learn that Islam teaches kindness to family, friends, and everyone around them."),
        ("Saying Thank You: Gratitude in Daily Life", "Children learn simple ways to show gratitude for the blessings in their everyday life."),
        ("Simple Duas for Morning and Evening", "Children learn short, simple duas that can be said when waking up and before going to sleep."),
        ("Simple Dua Before and After Eating", "Children learn a short dua to say before and after meals to show thankfulness for food."),
        ("Honesty and Telling the Truth", "Children learn why telling the truth is an important value taught in Islam."),
        ("Sharing with Family and Friends", "Children learn the importance of sharing what they have with family, friends, and those in need."),
        ("Respecting Parents and Elders", "Children learn that showing respect and kindness to parents and elders is an important value in Islam."),
        ("Being Gentle with Animals", "Children learn that Islam teaches people to be gentle and caring toward animals."),
        ("Keeping Ourselves Clean", "Children learn simple habits of personal cleanliness that are encouraged in Islam."),
        ("The Story of Prophet Adam: Our First Family", "Children learn a simple, age-appropriate retelling of the story of Prophet Adam as the first human being."),
        ("The Story of Prophet Nuh: Patience and Trust", "Children learn a simple story of Prophet Nuh that teaches patience and trust during hard times."),
        ("The Story of Prophet Ibrahim: Courage and Faith", "Children learn a simple story of Prophet Ibrahim that teaches courage and strong faith."),
        ("The Story of Prophet Yusuf: Forgiveness", "Children learn a simple story of Prophet Yusuf that teaches the value of forgiveness."),
        ("The Story of Prophet Musa: Standing for What is Right", "Children learn a simple story of Prophet Musa that teaches standing up for what is right."),
        ("Stories of Prophet Muhammad's Kindness as a Child", "Children learn simple, age-appropriate stories about Prophet Muhammad's kindness and good manners as a child."),
        ("Helping Those in Need", "Children learn the value of helping people who are less fortunate in their community."),
        ("Saying Sorry and Forgiving Others", "Children learn the importance of apologizing when they make a mistake and forgiving others."),
        ("Caring for Our Neighbours", "Children learn that Islam teaches kindness and good behavior toward neighbours."),
        ("Being Patient", "Children learn simple ways to practice patience when things are difficult or do not go as planned."),
    ],
    "World Literature": [
        ("Aesop's Fables: Lessons from Ancient Greece", "Children learn how short animal fables from ancient Greece teach simple, memorable life lessons."),
        ("The Tortoise and the Hare", "Children explore this classic fable and its message that being steady and patient can win over rushing carelessly."),
        ("The Boy Who Cried Wolf", "Children explore this classic fable and its message about the importance of always telling the truth."),
        ("Anansi the Spider: West African Trickster Tales", "Children learn about Anansi, a clever spider character from West African folk tales known for outsmarting others."),
        ("Little Red Riding Hood", "Children explore this well-known European folk tale and its lesson about listening to trusted grown-ups."),
        ("The Three Little Pigs", "Children explore this classic tale and its message about the value of hard work and careful planning."),
        ("Goldilocks and the Three Bears", "Children explore this classic tale and its message about respecting other people's belongings."),
        ("Cinderella Tales Around the World", "Children learn that many cultures have their own version of a kind, hardworking girl whose fortune changes."),
        ("The Ugly Duckling", "Children explore this Danish fairy tale and its gentle message about patience and inner worth."),
        ("The Emperor's New Clothes", "Children explore this classic tale and its lesson about honesty and thinking for oneself."),
        ("Panchatantra Animal Tales from India", "Children learn about the Panchatantra, a classic collection of Indian animal tales that teach wise lessons."),
        ("Momotaro: The Peach Boy of Japan", "Children learn about Momotaro, a beloved Japanese folk hero known for bravery and teamwork with animal friends."),
        ("Br'er Rabbit Folk Tales", "Children learn about Br'er Rabbit, a clever trickster character from African American folk storytelling traditions."),
        ("The Frog Prince", "Children explore this German fairy tale and its gentle message about keeping promises."),
        ("Arabian Nights: Tales of Adventure", "Children learn about the Arabian Nights, a famous collection of adventurous tales told across generations."),
        ("Native American Coyote Trickster Tales", "Children learn about Coyote, a clever trickster character found in many Native American storytelling traditions."),
        ("The Little Mermaid", "Children explore this Danish tale about a curious mermaid and its themes of longing and kindness."),
        ("The Nightingale: A Tale from China", "Children explore this tale, set in China, about a small bird whose beautiful song matters more than appearances."),
        ("Journey to the West: A Chinese Adventure Tale", "Children learn about the adventurous characters from this classic Chinese story of a long journey."),
    ],
    "Art": [
        ("Primary and Secondary Colours", "Children learn the three primary colours and how mixing them creates new secondary colours."),
        ("Painting with Watercolours", "Children practice using watercolour paints and brushes to create simple, colourful pictures."),
        ("Drawing Simple Shapes and Objects", "Children practice drawing familiar objects by combining basic shapes like circles and squares."),
        ("Making Collages", "Children create pictures by cutting and gluing paper, fabric, and other materials together."),
        ("Clay Modelling and Sculpture", "Children use soft clay or dough to shape simple three-dimensional forms with their hands."),
        ("Printmaking with Everyday Objects", "Children use sponges, fruit, and other everyday objects dipped in paint to create repeated printed patterns."),
        ("Lines and Patterns in Art", "Children explore different types of lines, such as wavy, straight, and zigzag, to create patterns."),
        ("Textures: Rough and Smooth", "Children explore how art can look and feel rough or smooth using different materials and techniques."),
        ("Drawing Self-Portraits", "Children practice drawing a picture of their own face and features."),
        ("Nature Art: Leaves and Flowers", "Children create art using collected natural materials such as leaves, petals, and twigs."),
        ("Paper Folding and Simple Origami", "Children learn to fold paper into simple shapes and figures following step-by-step instructions."),
        ("Mixing Colours to Make New Ones", "Children experiment with mixing paint colours together to discover the new colours they create."),
        ("Famous Artists for Young Learners", "Children learn about a few famous artists and look at simple examples of their well-known works."),
        ("Art from Different Cultures", "Children explore simple art styles and patterns from different cultures around the world."),
        ("Drawing Animals", "Children practice drawing familiar animals using simple shapes and lines."),
        ("Chalk and Pastel Art", "Children experiment with chalk and pastels to create soft, colourful drawings."),
        ("Making Puppets", "Children create simple puppets from paper bags, socks, or craft materials for imaginative play."),
        ("Warm and Cool Colours", "Children learn to sort colours into warm colours like red and orange and cool colours like blue and green."),
        ("Symmetry in Art", "Children explore symmetry by creating pictures where one half matches the other half."),
    ],
    "Music": [
        ("Loud and Soft Sounds", "Children learn to identify and create sounds that are loud and sounds that are soft."),
        ("High and Low Pitch", "Children learn to tell the difference between high-pitched and low-pitched sounds."),
        ("Fast and Slow Rhythm", "Children learn to identify and clap along to music that moves quickly or slowly."),
        ("Clapping and Keeping a Beat", "Children practice clapping along to a steady beat while listening to simple songs."),
        ("Simple Musical Instruments", "Children learn to identify and name a few simple musical instruments by sight and sound."),
        ("Percussion Instruments", "Children learn about instruments that are hit or shaken, such as drums, tambourines, and shakers."),
        ("String Instruments", "Children learn about instruments that make sound using strings, such as guitars and violins."),
        ("Wind Instruments", "Children learn about instruments that make sound when a player blows air through them, such as flutes."),
        ("Singing Simple Songs", "Children practice singing simple, familiar songs together as a group."),
        ("Nursery Rhymes and Their Rhythms", "Children explore the rhythm and rhyme found in familiar nursery rhymes."),
        ("Music from Around the World", "Children listen to and compare simple examples of music styles from different countries."),
        ("Making Music with Everyday Objects", "Children create simple sounds and rhythms using everyday objects like pots, spoons, and boxes."),
        ("Moving to Music", "Children practice moving their bodies in different ways to match the rhythm and mood of music."),
        ("Animal Sounds in Music", "Children explore songs and music that imitate the sounds different animals make."),
        ("The Orchestra: An Introduction", "Children learn that an orchestra is a large group of musicians playing different instruments together."),
        ("Call and Response Singing", "Children practice a simple singing style where one voice sings a line and others answer back."),
        ("Musical Patterns and Repetition", "Children learn to notice repeated patterns of sound in simple songs and rhythms."),
        ("Introduction to Reading Simple Rhythms", "Children learn to follow and clap simple visual rhythm patterns made of short and long sounds."),
        ("Quiet and Silence in Music", "Children learn that pauses and quiet moments are also an important part of music."),
    ],
    "General Knowledge": [
        ("Days of the Week", "Children learn to name and order the seven days of the week."),
        ("Months of the Year", "Children learn to name and order the twelve months of the year."),
        ("National Symbols: Flags and Anthems", "Children learn what a national flag and anthem are and why countries have them."),
        ("Famous Landmarks Around the World", "Children learn to recognize a few famous landmarks and where they are located in the world."),
        ("Wild Animals and Where They Live", "Children learn about wild animals from around the world and the habitats they live in."),
        ("Pets and How to Care for Them", "Children learn about common pets and the basic care they need, like food, water, and love."),
        ("Fruits and Vegetables We Eat", "Children learn to identify common fruits and vegetables and know that they are healthy to eat."),
        ("Modes of Transport", "Children learn to identify different ways people and goods travel by land, water, and air."),
        ("Community Helpers and Their Jobs", "Children learn about people in the community, such as doctors and firefighters, and the jobs they do."),
        ("Safety Rules at Home", "Children learn simple safety rules to follow to stay safe while at home."),
        ("Safety Rules on the Road", "Children learn simple safety rules to follow when walking near or crossing roads."),
        ("Basic Manners and Etiquette", "Children learn simple polite words and behaviors, such as saying please and thank you."),
        ("Recycling and Caring for the Earth", "Children learn simple ways to recycle and reduce waste to help take care of the planet."),
        ("Simple Technology We Use Every Day", "Children learn to identify everyday technology, such as phones and televisions, and how people use them."),
        ("Sports Around the World", "Children learn about a few popular sports played by children and adults around the world."),
        ("Festivals and Celebrations Around the World", "Children learn about a few festivals and celebrations enjoyed by different cultures around the world."),
        ("Famous Inventors for Young Learners", "Children learn about a few famous inventors and the simple inventions they are known for."),
        ("Emergency Numbers and Getting Help", "Children learn what an emergency is and simple steps to take to get help from a trusted adult."),
        ("Space: Sun, Moon and Stars", "Children learn simple facts about the sun, moon, and stars that they can see in the sky."),
    ],
    "Social Studies": [
        ("Rules and Why We Follow Them", "Children learn why rules exist at home, school, and in the community, and why it is important to follow them."),
        ("Being a Good Friend", "Children learn simple qualities of a good friend, such as sharing, listening, and being kind."),
        ("Feelings and Emotions", "Children learn to name their feelings and simple ways to express them appropriately."),
        ("Working Together and Cooperation", "Children learn how working together with others helps get tasks done and builds friendships."),
        ("Jobs People Do in the Community", "Children learn about different jobs people do to help their community run smoothly."),
        ("My School Community", "Children learn about the people and places that make up their school community."),
        ("Helpers in Our Neighbourhood", "Children learn about the helpful people who work in and around their neighbourhood."),
        ("Diversity: We Are All Different and Special", "Children learn that people look, speak, and live differently, and that these differences are something to celebrate."),
        ("Fairness and Sharing", "Children learn simple ideas about fairness and why sharing with others is important."),
        ("Making Choices and Responsibility", "Children learn that making choices comes with responsibility for the outcome."),
        ("Money and Simple Needs vs Wants", "Children learn the difference between things people need and things people want."),
        ("Celebrating Family Traditions", "Children learn about special traditions and celebrations that families share together."),
        ("Maps of My Neighbourhood", "Children learn to look at and understand a simple map of their own neighbourhood."),
        ("Belonging to a Community", "Children learn that they are part of different communities, such as family, school, and neighbourhood."),
        ("Respecting Others' Property", "Children learn the importance of respecting and taking care of things that belong to other people."),
        ("Solving Problems Peacefully", "Children learn simple, peaceful ways to solve disagreements with friends and classmates."),
        ("Being a Good Citizen", "Children learn simple actions that show they are a good citizen in their community."),
        ("Cultures and Customs Around Me", "Children learn about different cultures and customs practiced by people around them."),
        ("Past and Present in My Community", "Children learn to compare how their community looked and worked in the past compared to today."),
    ],
    "Physical Education & Self-Defense": [
        ("Running and Jumping Skills", "Children practice basic running and jumping movements to build coordination and fitness."),
        ("Throwing and Catching a Ball", "Children practice the basic skills of throwing and catching a ball with control."),
        ("Balance and Coordination", "Children practice simple activities that build balance and body coordination."),
        ("Stretching and Flexibility", "Children learn simple stretches to warm up their muscles and improve flexibility."),
        ("Simple Team Games", "Children participate in simple games that require working together as a team."),
        ("Following Rules in Games", "Children practice listening to and following the rules of simple physical games."),
        ("Warm-Up and Cool-Down Exercises", "Children learn why warming up before and cooling down after exercise keeps their bodies safe."),
        ("Hopping, Skipping, and Galloping", "Children practice different fun ways of moving, such as hopping, skipping, and galloping."),
        ("Personal Space and Safety in Movement", "Children learn to move safely around others by being aware of their own personal space."),
        ("Basic Stranger Safety Awareness", "Children learn simple, age-appropriate rules about staying safe around unfamiliar people."),
        ("Saying No and Telling a Trusted Adult", "Children learn that it is okay to say no if something feels unsafe and to tell a trusted adult right away."),
        ("Simple Self-Defense: Getting Away Safely", "Children learn simple, safe ways to move away and call for help if they ever feel unsafe."),
        ("Road and Playground Safety", "Children learn simple safety rules to follow near roads and while playing on playground equipment."),
        ("Water Safety Basics", "Children learn simple safety rules to follow when near pools, lakes, or the sea."),
        ("Healthy Exercise Habits", "Children learn why regular movement and exercise are important for a healthy body."),
        ("Cooperative Play and Turn-Taking", "Children practice taking turns and playing cooperatively with others during physical activities."),
        ("Basic Yoga Poses for Kids", "Children practice a few simple, gentle yoga poses to build strength, balance, and calm."),
        ("Dance and Rhythmic Movement", "Children practice moving their bodies to music in simple, rhythmic dance patterns."),
        ("Understanding Rules of Fair Play", "Children learn what fair play means and why it matters in games and sports."),
    ],
    "Health Education": [
        ("Understanding My Feelings", "Children learn to recognize and name their own feelings as part of overall wellbeing."),
        ("Caring for My Body", "Children learn simple daily habits that help keep their whole body healthy."),
        ("Healthy Snacks vs Sugary Treats", "Children learn to tell the difference between healthy snacks and sugary treats that should be eaten only sometimes."),
        ("Staying Hydrated: Drinking Water", "Children learn why drinking enough water each day is important for a healthy body."),
        ("Dressing for the Weather", "Children learn to choose appropriate clothing based on hot, cold, rainy, or sunny weather."),
        ("Visiting the Doctor and Dentist", "Children learn why regular check-ups with a doctor and dentist help keep them healthy."),
        ("Germs and How Illness Spreads", "Children learn simple facts about germs and how they can spread from person to person."),
        ("Covering Coughs and Sneezes", "Children learn the proper way to cover their mouth and nose when coughing or sneezing to stop germs from spreading."),
        ("Exercise and an Active Body", "Children learn why daily movement and play help keep their body strong and healthy."),
        ("Recognizing Safe and Unsafe Touch", "Children learn simple, age-appropriate ideas about safe and unsafe touch and telling a trusted adult."),
        ("Road Safety Rules", "Children learn simple rules to stay safe while walking or riding near streets and traffic."),
        ("Fire Safety Basics", "Children learn simple fire safety rules, including what to do if they see smoke or fire."),
        ("Managing Big Emotions", "Children learn simple calming strategies to use when they feel a big emotion like anger or frustration."),
        ("Rest and Relaxation", "Children learn why quiet time and relaxation, alongside sleep, are important for feeling well."),
    ],
    "ICT & Computer Science": [
        ("Parts of a Computer: Keyboard, Mouse, Screen", "Children learn to identify the main parts of a computer, such as the keyboard, mouse, and screen."),
        ("Turning a Computer On and Off Safely", "Children learn the correct, safe steps to turn a computer on and shut it down."),
        ("Using a Mouse and Keyboard", "Children practice basic mouse clicking and dragging along with simple keyboard typing."),
        ("What is the Internet?", "Children learn a simple explanation of what the internet is and how it connects computers together."),
        ("Staying Safe Online: Basic Rules", "Children learn simple, age-appropriate rules for staying safe when using devices online."),
        ("Introduction to Tablets and Apps", "Children learn how tablets work and how tapping icons opens different simple apps."),
        ("Typing Simple Words", "Children practice using a keyboard to type short, familiar words."),
        ("Drawing on a Computer", "Children use a simple drawing program to create pictures using digital tools."),
        ("What is a Robot?", "Children learn a simple explanation of what a robot is and how it follows instructions."),
        ("Following Simple Step-by-Step Instructions (Sequencing)", "Children practice putting a small set of instructions in the correct step-by-step order."),
        ("Introduction to Algorithms Through Games", "Children learn that an algorithm is a set of steps to follow, using simple games and puzzles."),
        ("Digital Devices Around Us", "Children learn to identify common digital devices they see at home and school, such as phones and computers."),
        ("Taking Care of Devices", "Children learn simple ways to take good care of computers and other digital devices."),
        ("Introduction to a Simple Coding Game", "Children use a simple, screen-based coding game to move a character using basic directional commands."),
        ("Sending a Simple Message (Digital Communication Basics)", "Children learn a simple explanation of how people can send messages to each other using digital devices."),
        ("Printers and How They Work", "Children learn a simple explanation of what a printer does and how it turns computer work into paper copies."),
        ("Cameras and Taking Pictures Digitally", "Children learn how digital cameras and devices are used to take and save pictures."),
        ("Sorting and Patterns with Computers", "Children practice simple sorting and pattern activities that build early computational thinking skills."),
        ("Screen Time and Balance", "Children learn why it is healthy to balance time spent on screens with other activities like play and rest."),
    ],
}
