GRADE = 9
MODULES: dict[str, list[tuple[str, str]]] = {
    "General Knowledge": [
        ("World Geography Highlights", "Students survey the world's major landforms, regions, and geographic features."),
        ("Continents and Oceans", "Students learn the names, locations, and key facts about the seven continents and five oceans."),
        ("Major World Rivers", "Students explore the world's longest rivers and their importance to civilizations."),
        ("Mountain Ranges of the World", "Students identify major mountain ranges and how they were formed."),
        ("World Capitals and Countries", "Students learn to match countries with their capital cities across the globe."),
        ("Currencies of the World", "Students explore the different currencies used by countries around the world."),
        ("The United Nations and Its Role", "Students learn how the United Nations promotes peace and cooperation among nations."),
        ("World Religions Overview", "Students survey the major world religions and their core beliefs and practices."),
        ("Major World Languages", "Students explore the most widely spoken languages and their global distribution."),
        ("World Time Zones", "Students learn how time zones work and how to calculate time differences worldwide."),
        ("Famous Explorers in History", "Students learn about explorers who mapped new lands and changed world history."),
        ("Great Inventions and Inventors", "Students explore inventions that transformed daily life and the people who created them."),
        ("Space Exploration Milestones", "Students learn about key achievements in human space exploration."),
        ("The Nobel Prize", "Students learn about the Nobel Prize and its categories honoring global achievement."),
        ("History of the Olympic Games", "Students trace the origins and evolution of the modern and ancient Olympic Games."),
        ("Ancient Wonders of the World", "Students learn about the seven wonders of the ancient world."),
        ("Modern Wonders of the World", "Students explore the modern wonders recognizing remarkable feats of engineering."),
        ("Famous World Landmarks", "Students identify iconic landmarks and monuments from countries around the globe."),
        ("National Flags and Symbols", "Students learn how national flags and symbols represent a country's identity and history."),
        ("National Anthems Around the World", "Students explore the role national anthems play in expressing national pride."),
        ("World Population Trends", "Students examine how global population has grown and shifted over time."),
        ("Great Deserts of the World", "Students learn about the world's major deserts and the life that survives there."),
        ("Volcanoes and Earthquakes", "Students learn why volcanoes and earthquakes occur and where they are most common."),
        ("Climate Zones of the World", "Students explore the major climate zones and the factors that shape them."),
        ("Endangered Species and Conservation", "Students learn about species at risk of extinction and efforts to protect them."),
        ("World Trade Basics", "Students learn how goods and services move between countries through global trade."),
        ("International Days and Observances", "Students explore globally recognized days that raise awareness of important causes."),
        ("Famous Scientists and Their Discoveries", "Students learn about scientists whose discoveries changed our understanding of the world."),
        ("History of Communication", "Students trace how humans have communicated across distance, from letters to the internet."),
        ("History of Transportation", "Students explore how methods of travel have evolved throughout history."),
        ("Overview of Ancient Civilizations", "Students survey early civilizations and their lasting contributions to the world."),
        ("World War I Overview", "Students learn the causes, key events, and consequences of World War I."),
        ("World War II Overview", "Students learn the causes, key events, and consequences of World War II."),
        ("The Cold War Overview", "Students learn about the political tension between world powers after World War II."),
        ("Human Rights Basics", "Students learn about the basic rights all people are entitled to under international law."),
        ("Famous Artists and Artworks", "Students explore renowned artists and the works that shaped art history."),
        ("World Music and Dance Traditions", "Students explore musical and dance traditions from cultures around the world."),
        ("World Cuisines and Food Culture", "Students explore how food traditions reflect the cultures and histories of different regions."),
        ("Sports Around the World", "Students learn about popular sports and their cultural significance in different countries."),
        ("World Festivals and Celebrations", "Students explore festivals celebrated by cultures around the globe."),
        ("Space Agencies and Missions", "Students learn about organizations that lead space exploration and their major missions."),
        ("The Solar System Overview", "Students review the planets, moons, and other bodies that make up our solar system."),
        ("Natural Wonders of the World", "Students explore extraordinary natural sites formed by geological and ecological processes."),
        ("Global Environmental Issues", "Students learn about environmental challenges facing the planet and possible solutions."),
        ("Famous Books and Authors", "Students explore influential books and authors from world literature."),
        ("Major International Sporting Events", "Students learn about global sporting events that bring nations together."),
        ("Global Health Organizations", "Students learn how international organizations work to improve health worldwide."),
        ("Media and News Literacy", "Students learn how to evaluate news sources and understand how media shapes public knowledge."),
        ("Famous Bridges and Engineering Marvels", "Students explore remarkable feats of engineering built around the world."),
    ],
    "Social Studies": [
        ("Forms of Government", "Students compare different systems of government such as democracy, monarchy, and dictatorship."),
        ("Democracy and Citizenship", "Students explore what it means to be an active and informed citizen in a democracy."),
        ("The Constitution and Rule of Law", "Students learn how constitutions establish government structure and protect citizens' rights."),
        ("Human Rights and Civil Liberties", "Students learn about fundamental freedoms and rights protected under law."),
        ("Elections and Voting Systems", "Students learn how elections work and compare different voting systems."),
        ("Political Parties and Ideologies", "Students explore how political parties form around shared beliefs and goals."),
        ("Local Government and Municipalities", "Students learn how local governments provide services and make decisions for communities."),
        ("National Government Structures", "Students compare how national governments are organized into branches and levels."),
        ("International Relations Basics", "Students learn how countries interact through diplomacy, trade, and cooperation."),
        ("The Role of the United Nations", "Students explore how the United Nations addresses global challenges and conflicts."),
        ("Federalism versus Unitary Systems", "Students compare how power is divided between national and regional governments."),
        ("The Judiciary and Courts", "Students learn how courts interpret laws and resolve disputes."),
        ("Separation of Powers", "Students learn why government power is divided among branches to prevent abuse."),
        ("Media's Role in Democracy", "Students explore how a free press informs citizens and holds power accountable."),
        ("Public Policy Basics", "Students learn how governments identify problems and create policies to address them."),
        ("Taxation and Public Finance", "Students learn how governments raise and spend money to fund public services."),
        ("Social Stratification and Class", "Students explore how societies are organized into different social and economic groups."),
        ("Culture and Society", "Students examine how shared beliefs, customs, and values shape a society."),
        ("Urbanization and City Growth", "Students learn why cities grow and the challenges that come with rapid urbanization."),
        ("Migration and Its Causes", "Students explore why people move within and between countries."),
        ("Population Growth and Distribution", "Students learn how and why population size and density vary across the world."),
        ("Natural Resources and Their Distribution", "Students examine how natural resources are distributed and why this shapes economies."),
        ("Environmental Policy", "Students learn how governments create policies to protect the environment."),
        ("Sustainable Development Goals", "Students explore global goals aimed at ending poverty and protecting the planet."),
        ("Colonialism and Its Legacy", "Students learn how colonialism shaped the political and economic history of many nations."),
        ("Decolonization Movements", "Students explore how colonized nations gained independence in the twentieth century."),
        ("The Industrial Revolution and Society", "Students learn how industrialization transformed work, cities, and daily life."),
        ("Civil Rights Movements", "Students learn about movements that fought for equal rights and justice."),
        ("Gender Equality Movements", "Students explore historical and ongoing efforts to achieve equal rights for all genders."),
        ("Labor Rights and Trade Unions", "Students learn how workers have organized to improve wages and working conditions."),
        ("Social Institutions: Family and Education", "Students examine how family and education shape individuals and society."),
        ("Community and Social Change", "Students explore how communities organize to bring about positive change."),
        ("Conflict Resolution and Peacebuilding", "Students learn strategies used to resolve conflicts and build lasting peace."),
        ("Causes and Consequences of War", "Students examine why wars occur and their lasting effects on societies."),
        ("International Trade and Cooperation", "Students learn how countries work together through trade agreements and alliances."),
        ("Human Geography Basics", "Students explore how human activity interacts with and shapes the physical world."),
        ("Map Skills and Geographic Tools", "Students practice reading and interpreting maps and geographic data."),
        ("Climate and Human Settlement Patterns", "Students examine how climate influences where and how people live."),
        ("Cultural Diversity and Pluralism", "Students learn how societies can embrace and benefit from cultural diversity."),
        ("Nationalism and National Identity", "Students explore how shared identity and pride shape nations and their politics."),
        ("Global Inequality", "Students examine differences in wealth and opportunity between and within countries."),
        ("Poverty and Development", "Students learn about the causes of poverty and strategies to promote development."),
        ("NGOs and Civil Society", "Students learn how non-governmental organizations address social and humanitarian needs."),
        ("Consumer Rights and Protection", "Students learn about laws and organizations that protect consumers."),
        ("Public Health and Society", "Students examine how societies organize to protect and promote public health."),
        ("Technology's Impact on Society", "Students explore how technology changes the way societies live and interact."),
        ("Ethics in Public Life", "Students consider the ethical responsibilities of leaders and citizens in public life."),
        ("Refugees and Displacement", "Students learn about the causes and challenges of forced migration and displacement."),
        ("Global Citizenship", "Students explore what it means to be a responsible citizen of the world."),
    ],
    "Physical Education & Self-Defense": [
        ("Components of Physical Fitness", "Students learn the key components of fitness, including strength, endurance, and flexibility."),
        ("Warm-Up and Cool-Down Techniques", "Students learn why warming up and cooling down safely prevents injury."),
        ("Cardiovascular Training Basics", "Students learn how aerobic exercise strengthens the heart and lungs."),
        ("Strength Training Fundamentals", "Students learn safe techniques for building muscular strength."),
        ("Flexibility and Stretching", "Students learn stretching techniques that improve range of motion and prevent injury."),
        ("Sports Nutrition Basics", "Students learn how diet affects athletic performance and recovery."),
        ("Basketball Fundamentals", "Students learn basic basketball skills including dribbling, passing, and shooting."),
        ("Football (Soccer) Fundamentals", "Students learn basic soccer skills including passing, dribbling, and positioning."),
        ("Volleyball Fundamentals", "Students learn basic volleyball skills including serving, setting, and bumping."),
        ("Athletics and Track and Field", "Students learn fundamentals of running, jumping, and throwing events."),
        ("Swimming Basics", "Students learn fundamental swimming strokes and water safety skills."),
        ("Gymnastics Basics", "Students learn basic gymnastics movements emphasizing balance and control."),
        ("Badminton Fundamentals", "Students learn basic badminton strokes, rules, and strategy."),
        ("Table Tennis Fundamentals", "Students learn basic table tennis strokes, rules, and strategy."),
        ("Yoga and Mind-Body Fitness", "Students learn yoga poses that build flexibility, balance, and focus."),
        ("Teamwork and Cooperation in Sports", "Students learn how communication and cooperation lead to success in team sports."),
        ("Sportsmanship and Fair Play", "Students learn the importance of respect and integrity in competitive sports."),
        ("Rules and Officiating in Sports", "Students learn how rules and officials keep sports fair and safe."),
        ("Injury Prevention Basics", "Students learn habits and techniques that reduce the risk of sports injuries."),
        ("First Response to Sports Injuries", "Students learn basic steps to take when a sports injury occurs."),
        ("Self-Defense Fundamentals", "Students learn basic principles for protecting themselves in unsafe situations."),
        ("Situational Awareness and Avoidance", "Students learn how to recognize and avoid potentially dangerous situations."),
        ("Basic Blocking and Evasion Techniques", "Students learn safe techniques for blocking and avoiding an attack."),
        ("Escaping Grabs and Holds", "Students learn safe techniques for escaping common grabs and holds."),
        ("Overview of Martial Arts Styles", "Students explore different martial arts traditions and their core principles."),
        ("Introduction to Judo", "Students learn the basic history and principles of judo."),
        ("Introduction to Karate", "Students learn the basic history and principles of karate."),
        ("Introduction to Taekwondo", "Students learn the basic history and principles of taekwondo."),
        ("Boxing Fundamentals and Safety", "Students learn safe boxing footwork and technique fundamentals."),
        ("Wrestling Basics", "Students learn basic wrestling stances and safe technique fundamentals."),
        ("Personal Safety and Boundaries", "Students learn how to set and respect personal boundaries to stay safe."),
        ("Anti-Bullying Strategies", "Students learn strategies for recognizing, preventing, and responding to bullying."),
        ("Stress Management Through Physical Activity", "Students learn how regular exercise helps manage stress."),
        ("Goal Setting for Fitness", "Students learn how to set realistic and measurable personal fitness goals."),
        ("Heart Rate and Exercise Intensity", "Students learn how to measure heart rate to guide safe exercise intensity."),
        ("The Muscular System and Movement", "Students learn how muscles work together to produce movement."),
        ("The Skeletal System and Movement", "Students learn how bones and joints support movement and posture."),
        ("Posture and Body Mechanics", "Students learn how proper posture and body mechanics prevent injury."),
        ("Hydration and Athletic Performance", "Students learn why proper hydration is essential for safe physical activity."),
        ("Exercising Safely in Extreme Weather", "Students learn precautions for exercising safely in heat and cold."),
        ("Sports Psychology Basics", "Students learn how mindset and mental preparation affect athletic performance."),
        ("Leadership and Communication in Sports", "Students learn how effective leadership and communication build strong teams."),
        ("Recreational Activities for Lifelong Fitness", "Students explore activities that support fitness habits throughout life."),
        ("Dance as Physical Activity", "Students learn how dance builds coordination, rhythm, and cardiovascular fitness."),
        ("Hiking and Outdoor Activity Skills", "Students learn basic skills and safety precautions for hiking and outdoor recreation."),
        ("Cycling Basics and Road Safety", "Students learn safe cycling techniques and road safety rules."),
        ("Water Safety and Basic Lifesaving", "Students learn basic water safety rules and lifesaving awareness."),
        ("Building a Personal Fitness Plan", "Students learn how to design a balanced personal fitness plan."),
        ("Respecting Diversity in Sports", "Students learn the value of inclusion and respect for all participants in sports."),
    ],
    "Economics": [
        ("Scarcity and Choice", "Students learn how limited resources force individuals and societies to make choices."),
        ("Opportunity Cost", "Students learn how every choice involves giving up the next best alternative."),
        ("Factors of Production", "Students learn about land, labor, capital, and entrepreneurship as inputs to production."),
        ("Economic Systems: Capitalism, Socialism, and Mixed Economies", "Students compare how different economic systems answer what, how, and for whom to produce."),
        ("The Law of Supply", "Students learn how the quantity supplied changes as price changes."),
        ("The Law of Demand", "Students learn how the quantity demanded changes as price changes."),
        ("Market Equilibrium", "Students learn how supply and demand interact to determine market price."),
        ("Elasticity of Demand", "Students learn how sensitive demand is to changes in price."),
        ("Types of Market Structures", "Students compare competitive markets, monopolies, and everything in between."),
        ("Perfect Competition", "Students learn the characteristics of markets with many buyers and sellers."),
        ("Monopoly and Market Power", "Students learn how a single seller can influence price and output in a market."),
        ("The Circular Flow of Income", "Students learn how money and resources flow between households and businesses."),
        ("Gross Domestic Product (GDP)", "Students learn how GDP measures the total value of a country's economic output."),
        ("Economic Growth", "Students learn what causes an economy to produce more goods and services over time."),
        ("Inflation and Its Causes", "Students learn why prices rise over time and how inflation is measured."),
        ("Types of Unemployment", "Students learn about different causes of unemployment in an economy."),
        ("Fiscal Policy Basics", "Students learn how government spending and taxation influence the economy."),
        ("Monetary Policy Basics", "Students learn how controlling the money supply influences the economy."),
        ("The Role of Central Banks", "Students learn how central banks manage interest rates and the money supply."),
        ("Taxation Basics", "Students learn the different types of taxes and why governments collect them."),
        ("Government Spending and the Budget", "Students learn how governments plan and allocate public spending."),
        ("Public Goods versus Private Goods", "Students learn the difference between goods provided publicly and privately."),
        ("Externalities and Market Failure", "Students learn how side effects of economic activity can cause markets to fail."),
        ("International Trade Basics", "Students learn why countries trade goods and services with one another."),
        ("Comparative Advantage", "Students learn why countries benefit from specializing in what they produce best."),
        ("Exchange Rates", "Students learn how the value of one currency is measured against another."),
        ("Balance of Payments", "Students learn how countries record transactions with the rest of the world."),
        ("Economic Development", "Students learn what factors help economies grow and improve living standards."),
        ("Developed versus Developing Economies", "Students compare economic characteristics of developed and developing countries."),
        ("Poverty and Income Inequality", "Students learn how income is distributed unevenly and why this matters."),
        ("Labor Markets and Wages", "Students learn how wages are determined by supply and demand for workers."),
        ("Entrepreneurship and Innovation", "Students learn how entrepreneurs create new products and drive economic growth."),
        ("Costs of Production", "Students learn how businesses calculate the costs of making goods and services."),
        ("Economies of Scale", "Students learn how producing more can lower the average cost per unit."),
        ("The Business Cycle", "Students learn how economies move through periods of growth and contraction."),
        ("Recession and Economic Recovery", "Students learn what causes recessions and how economies recover from them."),
        ("Introduction to Stock Markets", "Students learn how stock markets allow people to buy and sell shares of companies."),
        ("Consumer Behavior in Economics", "Students learn how consumers make choices to maximize their satisfaction."),
        ("Producer Behavior and Profit Motive", "Students learn how businesses make decisions to maximize profit."),
        ("Price Ceilings and Price Floors", "Students learn how government price limits affect markets."),
        ("Government Subsidies", "Students learn how subsidies are used to support certain industries or activities."),
        ("Tariffs and Trade Barriers", "Students learn how tariffs and other barriers affect international trade."),
        ("International Trade and Globalization", "Students learn how increasing global trade connects economies around the world."),
        ("Key Economic Indicators", "Students learn how economists use indicators to measure the health of an economy."),
        ("Sustainable Economic Development", "Students learn how economic growth can be balanced with environmental protection."),
        ("Environmental Economics", "Students learn how economics analyzes the costs and benefits of environmental policy."),
        ("Behavioral Economics Basics", "Students learn how psychology influences real-world economic decisions."),
        ("History of Economic Thought", "Students learn about major thinkers who shaped modern economic theory."),
        ("Introduction to Cryptocurrency", "Students learn the basic concept and economic implications of digital currencies."),
    ],
    "Finance": [
        ("Budgeting Basics", "Students learn how to plan income and expenses to manage money wisely."),
        ("Income and Expenses", "Students learn to distinguish between money coming in and money going out."),
        ("Needs versus Wants", "Students learn to prioritize spending by distinguishing essential needs from wants."),
        ("Setting Financial Goals", "Students learn how to set short-term and long-term financial goals."),
        ("Types of Bank Accounts", "Students learn the differences between checking, savings, and other bank accounts."),
        ("How Interest Rates Work", "Students learn how interest is earned on savings and charged on loans."),
        ("Simple versus Compound Interest", "Students learn the difference between simple and compound interest calculations."),
        ("Credit Cards and Debit Cards", "Students learn how credit and debit cards work and their key differences."),
        ("Understanding Credit Scores", "Students learn what a credit score is and why it matters."),
        ("Borrowing and Loans", "Students learn the basics of how loans work and their responsibilities."),
        ("Understanding Debt", "Students learn how debt accumulates and strategies for managing it responsibly."),
        ("Avoiding Debt Traps", "Students learn to recognize and avoid situations that lead to unmanageable debt."),
        ("Saving Strategies", "Students learn practical strategies for building consistent saving habits."),
        ("Building an Emergency Fund", "Students learn why an emergency fund is important and how to build one."),
        ("Introduction to Investing", "Students learn the basic concept of investing money to grow wealth over time."),
        ("Stocks Basics", "Students learn what a stock represents and how stock ownership works."),
        ("Bonds Basics", "Students learn what a bond is and how it functions as a loan to an issuer."),
        ("Mutual Funds Basics", "Students learn how mutual funds pool money to invest in a diversified portfolio."),
        ("Risk and Return in Investing", "Students learn the relationship between investment risk and potential return."),
        ("Diversification in Investing", "Students learn why spreading investments reduces overall risk."),
        ("Retirement Planning Basics", "Students learn why saving early for retirement makes a significant difference."),
        ("Insurance Basics", "Students learn how insurance protects against unexpected financial loss."),
        ("Health, Life, and Auto Insurance", "Students learn the purpose and basic features of common insurance types."),
        ("Taxes and Personal Finance", "Students learn how taxes affect personal income and financial planning."),
        ("Understanding Paychecks and Payroll", "Students learn how to read a paycheck and understand payroll deductions."),
        ("Recognizing Financial Scams and Fraud", "Students learn to identify common financial scams and how to avoid them."),
        ("Protecting Against Identity Theft", "Students learn how to protect personal information from identity theft."),
        ("Digital Payments and E-Wallets", "Students learn how digital payment systems and e-wallets work."),
        ("Cryptocurrency and Digital Assets Basics", "Students learn the basic concept of cryptocurrency as a digital asset."),
        ("Planning for Big Purchases", "Students learn how to plan and save for significant future purchases."),
        ("Renting versus Buying a Home", "Students learn the financial trade-offs between renting and buying housing."),
        ("Student Loans and Education Costs", "Students learn how student loans work and how to plan for education costs."),
        ("Cost of Living", "Students learn how the cost of living varies by location and affects budgeting."),
        ("Inflation's Impact on Personal Finance", "Students learn how inflation affects the purchasing power of money over time."),
        ("Currency Exchange Basics", "Students learn how currency exchange rates affect the value of money abroad."),
        ("Keeping Financial Records", "Students learn why organizing financial records helps with money management."),
        ("Comparison Shopping", "Students learn how comparing prices and options helps get the best value."),
        ("Understanding Consumer Contracts", "Students learn how to read and understand the terms of consumer contracts."),
        ("Interest on Credit Card Debt", "Students learn how unpaid credit card balances accumulate interest over time."),
        ("Financial Independence", "Students learn what it means to manage one's own finances responsibly."),
        ("Philanthropy and Charitable Giving", "Students learn how giving to charitable causes fits into personal finance."),
        ("Entrepreneurship and Personal Finance", "Students learn how starting a business affects personal financial planning."),
        ("Understanding Pay Stubs and Deductions", "Students learn to interpret the deductions listed on a typical pay stub."),
        ("Financial Decision Making", "Students learn a structured approach to making sound financial decisions."),
        ("Opportunity Cost in Personal Choices", "Students learn how every spending choice involves a financial trade-off."),
        ("Negotiating and Bargaining Basics", "Students learn basic strategies for negotiating a better price or deal."),
        ("Filing an Insurance Claim", "Students learn the basic steps involved in filing an insurance claim."),
        ("Peer-to-Peer Payment Apps", "Students learn how peer-to-peer payment apps let people send money digitally."),
        ("Avoiding Impulse Spending", "Students learn strategies to recognize and resist impulsive purchases."),
    ],
    "First Aid": [
        ("Principles of First Aid", "Students learn the basic goals and principles that guide first aid response."),
        ("The Primary Survey (Airway, Breathing, Circulation)", "Students learn how to quickly assess airway, breathing, and circulation in an emergency."),
        ("Calling Emergency Services Effectively", "Students learn what information to provide when calling for emergency help."),
        ("Choking and the Heimlich Maneuver", "Students learn how to recognize choking and perform abdominal thrusts safely."),
        ("Treating Minor Cuts and Wounds", "Students learn how to clean and dress minor cuts and wounds."),
        ("Basic Bandaging Techniques", "Students learn techniques for applying bandages to different types of injuries."),
        ("Controlling Severe Bleeding", "Students learn how to apply pressure and control severe bleeding safely."),
        ("Treating Burns", "Students learn how to assess and provide initial care for different burn severities."),
        ("Recognizing and Treating Shock", "Students learn to recognize the signs of shock and how to respond."),
        ("Managing Fractures", "Students learn how to recognize a possible fracture and stabilize it safely."),
        ("Splinting Techniques", "Students learn basic techniques for splinting an injured limb."),
        ("Treating Sprains and Strains (RICE Method)", "Students learn the Rest, Ice, Compression, and Elevation method for soft tissue injuries."),
        ("Head Injuries and Concussion Signs", "Students learn to recognize warning signs of a concussion or head injury."),
        ("Recognizing Stroke (FAST Test)", "Students learn the FAST test used to quickly identify signs of a stroke."),
        ("Recognizing a Heart Attack", "Students learn to recognize the warning signs of a heart attack."),
        ("Asthma Attacks and Inhaler Use", "Students learn how to help someone experiencing an asthma attack."),
        ("Allergic Reactions and Anaphylaxis", "Students learn to recognize a severe allergic reaction and respond appropriately."),
        ("Using an Epinephrine Auto-Injector", "Students learn the basic steps for using an epinephrine auto-injector in an emergency."),
        ("First Aid for Seizures", "Students learn how to keep someone safe during a seizure."),
        ("Diabetic Emergencies", "Students learn to recognize and respond to signs of a diabetic emergency."),
        ("Hypothermia and Frostbite", "Students learn to recognize and provide initial care for cold-related injuries."),
        ("Heat Exhaustion and Heat Stroke", "Students learn to recognize and respond to heat-related illnesses."),
        ("First Aid for Poisoning", "Students learn the basic steps to take if someone is exposed to poison."),
        ("Treating Insect Bites and Stings", "Students learn how to safely treat common insect bites and stings."),
        ("Treating Animal Bites", "Students learn the basic first aid steps for treating an animal bite."),
        ("Managing Nosebleeds", "Students learn the correct technique for stopping a nosebleed."),
        ("First Aid for Eye Injuries", "Students learn basic safe first aid steps for common eye injuries."),
        ("First Aid for Dental Injuries", "Students learn basic first aid steps for a knocked-out or injured tooth."),
        ("Water Rescue and Drowning Basics", "Students learn basic safety principles for responding to a water emergency."),
        ("Treating Fainting", "Students learn how to recognize and respond when someone faints."),
        ("Recognizing Chest Pain Emergencies", "Students learn to recognize chest pain that may signal a medical emergency."),
        ("Spinal Injury Precautions", "Students learn why an injured person should not be moved if a spinal injury is suspected."),
        ("The Recovery Position", "Students learn how and when to place an unresponsive but breathing person in the recovery position."),
        ("Building a First Aid Kit", "Students learn what essential supplies belong in a well-stocked first aid kit."),
        ("Preventing Wound Infection", "Students learn how to keep a wound clean to prevent infection."),
        ("Treating Blisters", "Students learn how to safely care for a blister."),
        ("Sunburn Treatment", "Students learn how to treat sunburned skin and when to seek medical care."),
        ("First Aid for Food Poisoning", "Students learn the basic signs of food poisoning and appropriate initial care."),
        ("First Aid for Common Sports Injuries", "Students learn initial care steps for common injuries that occur during sports."),
        ("Mental Health First Aid Basics", "Students learn how to support someone experiencing a mental health crisis."),
        ("Helping Someone During a Panic Attack", "Students learn calming strategies to help someone through a panic attack."),
        ("First Aid for Chemical Burns", "Students learn the correct steps for treating a chemical burn safely."),
        ("Electrical Injury Safety", "Students learn safety precautions for responding to an electrical injury."),
        ("Good Samaritan Principles in First Aid", "Students learn the ethical and legal principles that protect those who give first aid help."),
        ("Assessing Scene Safety", "Students learn why checking that a scene is safe comes before helping an injured person."),
        ("Using Personal Protective Equipment", "Students learn why gloves and other protective equipment are used when giving first aid."),
        ("Communicating with Emergency Dispatchers", "Students learn how to clearly communicate details to an emergency dispatcher."),
        ("First Aid Basics for Infants and Young Children", "Students learn how first aid techniques are adapted for infants and young children."),
        ("Treating Muscle Cramps", "Students learn simple techniques for relieving a muscle cramp."),
    ],
    "Physics": [
        ("Physical Quantities and SI Units", "Students learn how physical quantities are measured using standard international units."),
        ("Scalars and Vectors", "Students learn the difference between quantities with only magnitude and those with direction."),
        ("Describing Motion: Speed and Velocity", "Students learn how to calculate and distinguish speed from velocity."),
        ("Acceleration", "Students learn how to calculate the rate at which velocity changes over time."),
        ("Distance-Time Graphs", "Students learn how to interpret and construct graphs showing distance over time."),
        ("Velocity-Time Graphs", "Students learn how to interpret and construct graphs showing velocity over time."),
        ("Newton's First Law of Motion", "Students learn how objects resist changes to their state of motion."),
        ("Newton's Second Law of Motion", "Students learn how force, mass, and acceleration are related."),
        ("Newton's Third Law of Motion", "Students learn that every action produces an equal and opposite reaction."),
        ("Mass versus Weight", "Students learn the difference between an object's mass and its weight."),
        ("Forces and Free Body Diagrams", "Students learn to represent the forces acting on an object using diagrams."),
        ("Friction and Its Effects", "Students learn how friction opposes motion between surfaces."),
        ("Momentum and Collisions", "Students learn how momentum is conserved during collisions between objects."),
        ("Work Done by a Force", "Students learn how to calculate the work done when a force moves an object."),
        ("Kinetic Energy", "Students learn how the energy of motion depends on mass and speed."),
        ("Gravitational Potential Energy", "Students learn how an object's height and mass determine its stored energy."),
        ("Conservation of Energy", "Students learn how energy transforms between forms but is never lost."),
        ("Power in Physics", "Students learn how power measures the rate at which work is done."),
        ("Simple Machines Overview", "Students learn how simple machines make work easier by changing force or distance."),
        ("Levers and Mechanical Advantage", "Students learn how levers multiply force to make tasks easier."),
        ("Pulleys and Their Uses", "Students learn how pulley systems change the direction and amount of force needed."),
        ("Inclined Planes", "Students learn how ramps reduce the force needed to raise an object."),
        ("Gravity and Gravitational Fields", "Students learn how gravity attracts objects with mass toward each other."),
        ("Introduction to Projectile Motion", "Students learn how objects move under the combined influence of gravity and initial velocity."),
        ("Pressure Basics", "Students learn how pressure is calculated as force distributed over an area."),
        ("Pressure in Fluids", "Students learn how pressure changes with depth in liquids and gases."),
        ("Archimedes' Principle and Buoyancy", "Students learn why objects float or sink based on displaced fluid."),
        ("Density and Its Applications", "Students learn how density relates mass and volume in everyday materials."),
        ("Pascal's Principle", "Students learn how pressure applied to a confined fluid is transmitted equally."),
        ("Heat versus Temperature", "Students learn the difference between heat energy and temperature."),
        ("Thermal Expansion", "Students learn how materials expand and contract with temperature changes."),
        ("Conduction, Convection, and Radiation", "Students learn the three main methods by which heat energy transfers."),
        ("Specific Heat Capacity", "Students learn how different materials require different amounts of energy to heat up."),
        ("States of Matter and Changes of State", "Students learn how matter changes between solid, liquid, and gas states."),
        ("Latent Heat", "Students learn how energy is absorbed or released during a change of state without a temperature change."),
        ("Introduction to Waves", "Students learn the basic properties that define a wave."),
        ("Wave Properties: Wavelength, Frequency, and Amplitude", "Students learn how to describe waves using wavelength, frequency, and amplitude."),
        ("Sound Waves and How We Hear", "Students learn how sound travels as a wave and how the ear detects it."),
        ("The Electromagnetic Spectrum", "Students learn about the range of electromagnetic waves from radio to gamma rays."),
        ("Reflection of Light", "Students learn how light bounces off surfaces according to the law of reflection."),
        ("Refraction of Light", "Students learn how light bends as it passes between different materials."),
        ("Lenses and Image Formation", "Students learn how converging and diverging lenses form images."),
        ("The Human Eye as an Optical Instrument", "Students learn how the eye focuses light to form images."),
        ("Static Electricity", "Students learn how electric charge builds up on objects and how it discharges."),
        ("Introduction to Electronics and Semiconductors", "Students learn the basic role semiconductor materials play in electronic devices."),
        ("Electrical Power and Energy Consumption", "Students learn how to calculate electrical energy use and its cost."),
        ("Introduction to Nuclear Energy", "Students learn how nuclear reactions release energy and how it can be harnessed."),
    ],
    "Chemistry": [
        ("Atomic Structure and Subatomic Particles", "Students learn how atoms are built from protons, neutrons, and electrons."),
        ("The Periodic Table", "Students learn how elements are organized by atomic number and properties."),
        ("Periodic Trends", "Students learn how properties like atomic size and reactivity change across the periodic table."),
        ("Introduction to Chemical Bonding", "Students learn why atoms bond together to form compounds."),
        ("Ionic Bonding", "Students learn how ionic bonds form through the transfer of electrons."),
        ("Covalent Bonding", "Students learn how covalent bonds form through the sharing of electrons."),
        ("Metallic Bonding", "Students learn how metallic bonding gives metals their characteristic properties."),
        ("Chemical Formulas and Naming Compounds", "Students learn how to write and name chemical formulas for compounds."),
        ("Balancing Chemical Equations", "Students learn how to balance equations to conserve mass in a reaction."),
        ("Types of Chemical Reactions", "Students learn to classify reactions as synthesis, decomposition, displacement, and more."),
        ("Physical versus Chemical Changes", "Students learn to distinguish changes that alter substances from those that do not."),
        ("The Particle Model of Matter", "Students learn how particles behave differently in solids, liquids, and gases."),
        ("Elements, Compounds, and Mixtures", "Students learn how to classify matter as elements, compounds, or mixtures."),
        ("Techniques for Separating Mixtures", "Students learn methods used to separate the components of a mixture."),
        ("Filtration", "Students learn how filtration separates insoluble solids from liquids."),
        ("Distillation", "Students learn how distillation separates liquids based on boiling point."),
        ("Chromatography", "Students learn how chromatography separates substances within a mixture."),
        ("Solutions and Solubility", "Students learn how solutes dissolve in solvents to form solutions."),
        ("Concentration of Solutions", "Students learn how to describe and calculate the concentration of a solution."),
        ("The pH Scale", "Students learn how the pH scale measures how acidic or basic a substance is."),
        ("Chemical Indicators", "Students learn how indicators change color to reveal a substance's pH."),
        ("Neutralization Reactions", "Students learn how acids and bases react to form water and a salt."),
        ("Oxidation and Reduction Basics", "Students learn the basic concept of electron transfer in redox reactions."),
        ("Introduction to Electrolysis", "Students learn how electricity can be used to drive a chemical reaction."),
        ("The Reactivity Series of Metals", "Students learn how metals are ranked by how readily they react."),
        ("Extracting Metals from Ores", "Students learn how metals are extracted from ores using different methods."),
        ("Corrosion and Rusting", "Students learn why metals corrode and how rusting can be prevented."),
        ("The Carbon Cycle", "Students learn how carbon moves through the atmosphere, oceans, and living things."),
        ("Combustion Reactions", "Students learn how fuels react with oxygen to release energy."),
        ("Catalysts and Reaction Rates", "Students learn how catalysts speed up chemical reactions without being consumed."),
        ("Factors Affecting Reaction Rate", "Students learn how temperature, concentration, and surface area affect reaction speed."),
        ("Exothermic and Endothermic Reactions", "Students learn how reactions can release or absorb energy."),
        ("Energy Changes in Reactions", "Students learn how to represent energy changes during a chemical reaction."),
        ("Crystallization", "Students learn how crystals form as a solution evaporates or cools."),
        ("Water Chemistry and the Water Cycle", "Students learn about the chemical properties of water and its natural cycle."),
        ("Hard Water and Soft Water", "Students learn what causes water hardness and how it can be treated."),
        ("Gases and the Kinetic Theory", "Students learn how the kinetic theory explains the behavior of gas particles."),
        ("Introduction to Avogadro's Law", "Students learn how equal volumes of gas contain equal numbers of particles."),
        ("Chemical Safety and Laboratory Techniques", "Students learn safe practices for handling chemicals and lab equipment."),
        ("History of the Periodic Table", "Students learn how the periodic table was developed and refined over time."),
        ("Isotopes", "Students learn how isotopes of an element differ in their number of neutrons."),
        ("Radioactive Decay in Chemistry", "Students learn how unstable isotopes release particles and energy over time."),
        ("Introduction to Polymers", "Students learn how small molecules link together to form long polymer chains."),
        ("The Chemistry of Fuels", "Students learn how different fuels release energy through chemical reactions."),
        ("Environmental Chemistry and Pollution", "Students learn how chemical processes contribute to environmental pollution."),
        ("Acid Rain Chemistry", "Students learn how pollutants react with water vapor to form acid rain."),
        ("Alloys and Their Uses", "Students learn how combining metals creates alloys with useful properties."),
    ],
    "Biology": [
        ("Cell Structure and Function", "Students learn about the basic structures found in cells and their functions."),
        ("Plant Cells versus Animal Cells", "Students learn to compare the structures found in plant and animal cells."),
        ("Cell Organelles and Their Roles", "Students learn the specific functions of major organelles within a cell."),
        ("Levels of Biological Organization", "Students learn how life is organized from cells to organisms to ecosystems."),
        ("Tissues, Organs, and Organ Systems", "Students learn how cells group together to form tissues, organs, and systems."),
        ("The Digestive System", "Students learn how the digestive system breaks down and absorbs nutrients."),
        ("The Circulatory System", "Students learn how the heart and blood vessels transport blood through the body."),
        ("The Respiratory System", "Students learn how the lungs exchange oxygen and carbon dioxide."),
        ("The Excretory System", "Students learn how the body removes waste products to maintain balance."),
        ("The Nervous System", "Students learn how the brain and nerves control the body's responses."),
        ("The Endocrine System", "Students learn how hormones regulate body processes."),
        ("The Skeletal System", "Students learn how bones provide support, protection, and movement."),
        ("The Muscular System", "Students learn how muscles work with bones to produce movement."),
        ("The Immune System", "Students learn how the body defends itself against pathogens."),
        ("The Reproductive System", "Students learn the basic structure and function of the human reproductive system."),
        ("Human Reproduction and Puberty", "Students learn about the physical changes that occur during puberty."),
        ("Cell Division: Mitosis", "Students learn how cells divide to produce two identical daughter cells."),
        ("Cell Division: Meiosis", "Students learn how cells divide to produce reproductive cells with half the chromosomes."),
        ("DNA Structure and Function", "Students learn how DNA stores the genetic instructions for living things."),
        ("Introduction to Protein Synthesis", "Students learn how genetic information is used to build proteins."),
        ("Photosynthesis", "Students learn how plants convert light energy into chemical energy."),
        ("Cellular Respiration", "Students learn how cells release energy stored in glucose."),
        ("Enzymes and Their Function", "Students learn how enzymes speed up biological reactions."),
        ("Diffusion and Osmosis", "Students learn how substances move across cell membranes."),
        ("Plant Structure and Function", "Students learn how roots, stems, and leaves support a plant's survival."),
        ("Plant Reproduction", "Students learn how plants reproduce through seeds, spores, and pollination."),
        ("Classification of Living Things", "Students learn how organisms are grouped based on shared characteristics."),
        ("Biodiversity", "Students learn why the variety of life on Earth is important to ecosystems."),
        ("Ecosystems and Habitats", "Students learn how living things interact with each other and their environment."),
        ("Food Chains and Food Webs", "Students learn how energy passes between organisms in an ecosystem."),
        ("Energy Flow in Ecosystems", "Students learn how energy moves through an ecosystem and is lost at each level."),
        ("Nutrient Cycles: Carbon and Nitrogen", "Students learn how essential nutrients cycle through ecosystems."),
        ("Population Dynamics in Ecosystems", "Students learn what factors cause populations to grow or shrink."),
        ("Adaptation and Survival", "Students learn how physical and behavioral traits help organisms survive."),
        ("Introduction to Natural Selection and Evolution", "Students learn how natural selection drives change in species over time."),
        ("Microorganisms: Bacteria", "Students learn about the structure and role of bacteria in nature and disease."),
        ("Microorganisms: Viruses", "Students learn how viruses differ from other microorganisms and cause disease."),
        ("Microorganisms: Fungi", "Students learn about the role fungi play in decomposition and disease."),
        ("Disease and Pathogens", "Students learn how pathogens cause disease and spread between hosts."),
        ("The Human Microbiome", "Students learn how beneficial microorganisms living in the body support health."),
        ("Vaccination and Immunity", "Students learn how vaccines help the immune system protect against disease."),
        ("Nutrition and a Balanced Diet", "Students learn how a balanced diet supports healthy growth and function."),
        ("The Skin and Thermoregulation", "Students learn how the skin helps regulate body temperature."),
        ("Senses and Sensory Organs", "Students learn how sensory organs detect information from the environment."),
        ("Lifestyle Diseases and Health", "Students learn how lifestyle choices influence the risk of certain diseases."),
        ("Introduction to Genetic Engineering", "Students learn the basic concept of modifying genes for practical purposes."),
        ("Conservation Biology", "Students learn how scientists work to protect species and ecosystems."),
    ],
    "Philosophy": [
        ("What Is Philosophy?", "Students learn what philosophy is and why humans ask fundamental questions."),
        ("Branches of Philosophy", "Students learn about the major branches of philosophy, including ethics and metaphysics."),
        ("Introduction to Logic", "Students learn the basic building blocks of logical arguments."),
        ("Metaphysics Basics", "Students learn how metaphysics explores the nature of reality and existence."),
        ("Epistemology: How Do We Know What We Know?", "Students learn how philosophers study the nature and limits of knowledge."),
        ("Philosophy of Mind", "Students learn how philosophers explore the relationship between mind and body."),
        ("What Is Truth?", "Students learn different philosophical theories about what makes something true."),
        ("The Problem of Free Will", "Students learn the philosophical debate over whether humans truly choose freely."),
        ("Determinism versus Free Will", "Students learn how determinism challenges the idea of free choice."),
        ("Personal Identity: What Makes You, You?", "Students learn philosophical questions about what makes a person the same over time."),
        ("The Mind-Body Problem", "Students learn how philosophers debate the relationship between mental and physical states."),
        ("Plato and the Theory of Forms", "Students learn Plato's idea that a higher realm of perfect forms exists beyond the physical world."),
        ("Aristotle and Virtue Ethics", "Students learn Aristotle's view that good character develops through practiced virtue."),
        ("Socrates and the Socratic Method", "Students learn how Socrates used questioning to examine beliefs and seek truth."),
        ("Confucius and Eastern Philosophy", "Students learn Confucius's ideas about ethics, family, and social harmony."),
        ("Introduction to Eastern Philosophical Traditions", "Students learn about major philosophical traditions that developed in Asia."),
        ("Stoicism", "Students learn the Stoic view that virtue and reason lead to a good life."),
        ("Introduction to Existentialism", "Students learn how existentialists explore freedom, meaning, and individual choice."),
        ("Utilitarianism", "Students learn the ethical theory that actions are judged by the happiness they produce."),
        ("Deontology and Duty-Based Ethics", "Students learn the ethical theory that some actions are right or wrong regardless of consequences."),
        ("Consequentialism versus Non-Consequentialist Ethics", "Students learn to compare ethical theories that judge actions by outcomes with those that do not."),
        ("Social Contract Theory", "Students learn the idea that governments derive authority from an agreement among citizens."),
        ("Introduction to Political Philosophy", "Students learn how philosophers examine the nature of power, justice, and government."),
        ("What Makes a Society Just?", "Students learn different philosophical views on fairness and justice in society."),
        ("Philosophy of Human Rights", "Students learn philosophical arguments for why humans possess basic rights."),
        ("Philosophy of Happiness", "Students learn different philosophical views on what it means to live a happy life."),
        ("The Trolley Problem and Moral Dilemmas", "Students learn how thought experiments test our moral intuitions."),
        ("Philosophy of Art and Aesthetics", "Students learn how philosophers examine the nature and value of art."),
        ("What Is Beauty?", "Students learn different philosophical theories about what makes something beautiful."),
        ("Philosophy of Science", "Students learn how philosophers examine the methods and assumptions of science."),
        ("Philosophy of Religion", "Students learn how philosophers examine questions about religious belief and faith."),
        ("Arguments About the Existence of God", "Students learn classic philosophical arguments for and against the existence of God."),
        ("Philosophy of Language", "Students learn how philosophers examine the relationship between words and meaning."),
        ("Critical Reasoning in Philosophy", "Students learn how to construct and evaluate philosophical arguments."),
        ("The Allegory of the Cave", "Students learn Plato's allegory illustrating the difference between illusion and knowledge."),
        ("Philosophy of Education", "Students learn philosophical perspectives on the purpose and methods of education."),
        ("Environmental Philosophy", "Students learn philosophical perspectives on humanity's relationship with nature."),
        ("Animal Ethics", "Students learn philosophical debates about the moral status of animals."),
        ("Philosophy of Technology", "Students learn how philosophers examine the impact of technology on human life."),
        ("Ethics of Artificial Intelligence", "Students learn philosophical questions raised by the growing use of artificial intelligence."),
        ("Personal Identity Over Time", "Students learn philosophical puzzles about what makes a person remain the same over time."),
        ("The Nature of Consciousness", "Students learn philosophical questions about the nature of subjective experience."),
        ("Introduction to Skepticism", "Students learn the philosophical position that questions the certainty of knowledge."),
        ("Philosophy of Time", "Students learn philosophical questions about the nature of time and change."),
        ("Philosophy of Death and Mortality", "Students learn how philosophers have reflected on the meaning of mortality."),
        ("Common Logical Fallacies", "Students learn to recognize common errors in reasoning found in everyday arguments."),
        ("Rationalism versus Empiricism", "Students learn to compare knowledge gained through reason with knowledge gained through experience."),
        ("The Value of Wisdom", "Students learn philosophical perspectives on the pursuit and value of wisdom."),
        ("Philosophy in Everyday Life", "Students learn how philosophical thinking can be applied to everyday decisions."),
    ],
    "Critical Thinking": [
        ("What Is Critical Thinking?", "Students learn what critical thinking means and why it matters in daily life."),
        ("Logic and Reasoning Basics", "Students learn the basic building blocks of clear and valid reasoning."),
        ("Deductive Reasoning", "Students learn how to draw specific conclusions from general premises."),
        ("Inductive Reasoning", "Students learn how to form general conclusions from specific observations."),
        ("Arguments: Premises and Conclusions", "Students learn how arguments are built from premises that support a conclusion."),
        ("Identifying Logical Fallacies", "Students learn to recognize common flaws that weaken an argument."),
        ("The Ad Hominem Fallacy", "Students learn to recognize arguments that attack a person instead of their claim."),
        ("The Strawman Fallacy", "Students learn to recognize when an argument is misrepresented to make it easier to attack."),
        ("The False Dilemma Fallacy", "Students learn to recognize when an argument wrongly presents only two options."),
        ("The Slippery Slope Fallacy", "Students learn to recognize arguments that assume one event will lead to extreme outcomes."),
        ("Appeal to Authority Fallacy", "Students learn to recognize when an argument relies too heavily on authority instead of evidence."),
        ("Circular Reasoning", "Students learn to recognize arguments in which the conclusion is used as its own support."),
        ("Correlation versus Causation", "Students learn why two related events do not always mean one causes the other."),
        ("Confirmation Bias", "Students learn how people tend to favor information that confirms existing beliefs."),
        ("Overview of Cognitive Biases", "Students learn about common mental shortcuts that can distort judgment."),
        ("The Availability Heuristic", "Students learn how easily recalled examples can distort our judgment of likelihood."),
        ("Anchoring Bias", "Students learn how initial information can unfairly influence later judgments."),
        ("Groupthink", "Students learn how the desire for harmony in a group can lead to poor decisions."),
        ("Analyzing Arguments", "Students learn how to break down an argument to evaluate its structure and strength."),
        ("Constructing a Sound Argument", "Students learn how to build an argument that is both valid and well-supported."),
        ("Evaluating the Quality of Evidence", "Students learn criteria for judging whether evidence is reliable and relevant."),
        ("Distinguishing Fact from Opinion", "Students learn how to tell the difference between verifiable facts and personal opinions."),
        ("Recognizing Propaganda Techniques", "Students learn to identify common techniques used to influence opinion through propaganda."),
        ("Analyzing Advertisements Critically", "Students learn to evaluate the persuasive techniques used in advertising."),
        ("Statistics and Misleading Data", "Students learn how statistics can be presented in misleading ways."),
        ("Reading Graphs and Charts Critically", "Students learn to spot common ways graphs and charts can distort information."),
        ("Understanding Sampling and Surveys", "Students learn how sample selection can affect the reliability of survey results."),
        ("Probability in Everyday Reasoning", "Students learn how understanding probability improves everyday decision making."),
        ("Problem-Solving Strategies", "Students learn structured strategies for approaching and solving problems."),
        ("Decision-Making Frameworks", "Students learn frameworks that help organize and evaluate difficult decisions."),
        ("Socratic Questioning", "Students learn how asking probing questions can clarify thinking and reveal assumptions."),
        ("Debate and Argumentation Skills", "Students learn how to construct and present a persuasive argument in debate."),
        ("Constructing Counterarguments", "Students learn how to anticipate and respond to opposing viewpoints."),
        ("Analyzing Cause and Effect", "Students learn how to evaluate whether a claimed cause truly explains an effect."),
        ("Introduction to Systems Thinking", "Students learn how to consider how parts of a system interact and influence one another."),
        ("Creative Thinking versus Critical Thinking", "Students learn how generating ideas and evaluating ideas serve different purposes."),
        ("Brainstorming and Idea Evaluation", "Students learn techniques for generating and then critically evaluating ideas."),
        ("Media Literacy and Critical Thinking", "Students learn how to critically evaluate messages from various media sources."),
        ("Evaluating Online Information", "Students learn strategies for judging the credibility of information found online."),
        ("Recognizing Fake News", "Students learn techniques for identifying false or misleading news stories."),
        ("Analyzing News Headlines Critically", "Students learn how headlines can be written to mislead or oversimplify a story."),
        ("Critical Thinking in Science", "Students learn how scientific thinking relies on evidence and careful reasoning."),
        ("The Scientific Method as Critical Thinking", "Students learn how the scientific method embodies structured critical thinking."),
        ("Analogical Reasoning", "Students learn how comparing similar situations can support or weaken an argument."),
        ("Recognizing Emotional Manipulation", "Students learn to identify when arguments rely on emotion rather than evidence."),
        ("Critical Listening Skills", "Students learn how to listen carefully and evaluate what a speaker is claiming."),
        ("Fact-Checking and Peer Review", "Students learn how fact-checking and peer review help verify claims."),
        ("Building a Reasoned Opinion", "Students learn how to form an opinion based on evidence and sound reasoning."),
        ("Reflective Thinking and Self-Examination", "Students learn how reflecting on one's own thinking can improve future decisions."),
    ],
    "Health Education": [
        ("Dimensions of Health: Physical, Mental, and Social", "Students learn how physical, mental, and social wellbeing together define overall health."),
        ("Nutrition Basics and Food Groups", "Students learn about the major food groups and their role in a healthy diet."),
        ("Reading Nutrition Labels", "Students learn how to read and interpret nutrition labels on packaged food."),
        ("Building Healthy Eating Habits", "Students learn practical strategies for developing lifelong healthy eating habits."),
        ("Hydration and Health", "Students learn why staying properly hydrated is essential for good health."),
        ("The Importance of Sleep", "Students learn how sufficient sleep supports physical and mental health."),
        ("Sleep Hygiene Practices", "Students learn habits that improve the quality of sleep."),
        ("Physical Activity Guidelines for Teens", "Students learn recommended levels of physical activity for their age group."),
        ("Body Image and Self-Esteem", "Students learn how body image affects self-esteem and overall wellbeing."),
        ("Puberty and Adolescent Development", "Students learn about the physical and emotional changes that occur during adolescence."),
        ("Understanding Menstrual Health", "Students learn accurate information about the menstrual cycle and menstrual hygiene."),
        ("Reproductive Health Basics", "Students learn basic, age-appropriate facts about human reproductive health."),
        ("Overview of Contraception Methods", "Students learn a basic, factual overview of common contraception methods."),
        ("Sexually Transmitted Infections Overview", "Students learn basic facts about how sexually transmitted infections spread and are prevented."),
        ("Building Healthy Relationships", "Students learn the qualities that make relationships respectful and healthy."),
        ("Communication Skills in Relationships", "Students learn communication skills that support healthy relationships."),
        ("Peer Pressure and Decision Making", "Students learn strategies for making healthy decisions under peer pressure."),
        ("Stress Management Techniques", "Students learn practical techniques for managing everyday stress."),
        ("Coping Strategies for Anxiety", "Students learn healthy strategies for coping with feelings of anxiety."),
        ("Understanding Depression", "Students learn the signs of depression and the importance of seeking help."),
        ("Suicide Prevention Awareness", "Students learn warning signs and how to seek help for themselves or others in crisis."),
        ("Building Resilience", "Students learn skills that help individuals cope with and recover from challenges."),
        ("Mindfulness and Mental Wellbeing", "Students learn how mindfulness practices can support mental wellbeing."),
        ("Effects of Alcohol Use", "Students learn how alcohol affects the body and decision making."),
        ("Effects of Tobacco and Vaping", "Students learn the health risks associated with tobacco and vaping products."),
        ("Effects of Drug Use", "Students learn how drug use affects physical and mental health."),
        ("Pathways to Addiction Recovery", "Students learn how individuals and support systems help people recover from addiction."),
        ("Injury Prevention and Safety", "Students learn everyday habits that help prevent common injuries."),
        ("Road and Pedestrian Safety", "Students learn safety practices for walking, biking, and traveling near traffic."),
        ("Internet Safety and Digital Wellbeing", "Students learn how to stay safe and maintain wellbeing while using the internet."),
        ("Screen Time and Health", "Students learn how excessive screen time can affect physical and mental health."),
        ("Personal Hygiene", "Students learn habits that maintain good personal hygiene."),
        ("Oral Health and Dental Care", "Students learn practices that maintain healthy teeth and gums."),
        ("Skin Health and Sun Safety", "Students learn how to protect skin health, including safe sun exposure practices."),
        ("Understanding Chronic Diseases", "Students learn about common chronic diseases and their risk factors."),
        ("Diabetes Awareness", "Students learn the basic causes, symptoms, and management of diabetes."),
        ("Cardiovascular Health", "Students learn habits that support a healthy heart and circulatory system."),
        ("Cancer Awareness and Prevention", "Students learn basic facts about cancer and lifestyle factors that reduce risk."),
        ("Environmental Health", "Students learn how environmental factors can affect human health."),
        ("Community Health Resources", "Students learn about resources available in a community to support health."),
        ("Healthy Decision-Making Models", "Students learn structured models for making healthy personal decisions."),
        ("Goal Setting for Personal Health", "Students learn how to set realistic and achievable personal health goals."),
        ("Allergies and Food Sensitivities", "Students learn basic facts about allergies and food sensitivities."),
        ("Understanding Eating Disorders", "Students learn to recognize warning signs of eating disorders and the importance of seeking help."),
    ],
    "ICT & Computer Science": [
        ("Introduction to Computer Systems", "Students learn the basic components that make up a computer system."),
        ("Hardware versus Software", "Students learn the difference between a computer's physical parts and its programs."),
        ("Input and Output Devices", "Students learn how devices allow computers to receive and display information."),
        ("How Computers Store Data", "Students learn the basic concepts behind how computers store and retrieve data."),
        ("The Binary Number System", "Students learn how computers represent information using binary digits."),
        ("Introduction to Programming Concepts", "Students learn the fundamental concepts that underlie all programming languages."),
        ("Variables and Data Types", "Students learn how programs use variables to store different types of data."),
        ("Control Structures: Loops", "Students learn how loops allow a program to repeat instructions."),
        ("Control Structures: Conditionals", "Students learn how conditional statements let programs make decisions."),
        ("Functions and Procedures", "Students learn how functions organize code into reusable blocks."),
        ("Introduction to Python Programming", "Students learn the basics of writing simple programs in Python."),
        ("Introduction to Algorithms", "Students learn how algorithms provide step-by-step instructions to solve problems."),
        ("Flowcharts and Pseudocode", "Students learn how to plan a program using flowcharts and pseudocode."),
        ("Debugging and Testing Code", "Students learn strategies for finding and fixing errors in code."),
        ("Introduction to Databases", "Students learn the basic concept of how databases store and organize data."),
        ("Introduction to Spreadsheets", "Students learn how spreadsheets organize data and perform calculations."),
        ("Data Representation: Text and Numbers", "Students learn how computers represent text and numbers internally."),
        ("Data Representation: Images and Sound", "Students learn how computers represent images and sound as digital data."),
        ("Computer Networks Basics", "Students learn how computers connect and communicate over a network."),
        ("How the Internet Works", "Students learn the basic infrastructure that allows the internet to function."),
        ("The World Wide Web", "Students learn how the web organizes and links information using browsers and pages."),
        ("IP Addresses and Domain Names", "Students learn how devices are identified and located on a network."),
        ("Cybersecurity Basics", "Students learn fundamental practices for protecting devices and data from threats."),
        ("Understanding Malware and Viruses", "Students learn how malicious software can harm computers and how to avoid it."),
        ("Safe Password Practices", "Students learn how to create and manage strong, secure passwords."),
        ("Online Privacy", "Students learn strategies for protecting personal privacy while online."),
        ("Understanding Your Digital Footprint", "Students learn how online activity leaves a lasting digital footprint."),
        ("Cyberbullying and Online Safety", "Students learn how to recognize and respond to cyberbullying safely."),
        ("Ethical Use of Technology", "Students learn principles for using technology responsibly and ethically."),
        ("Introduction to Artificial Intelligence", "Students learn the basic concept of how artificial intelligence systems work."),
        ("Machine Learning Basics", "Students learn how machine learning allows computers to improve from data."),
        ("Introduction to Robotics", "Students learn the basic principles behind how robots sense and act in the world."),
        ("Introduction to Computer Vision", "Students learn the basic concept of how computers can interpret visual information."),
        ("Introduction to Cloud Computing", "Students learn how cloud computing allows data and services to be accessed remotely."),
        ("File Systems and File Management", "Students learn how computers organize files and folders."),
        ("Operating Systems Overview", "Students learn the basic role an operating system plays in managing a computer."),
        ("Introduction to Version Control", "Students learn how version control helps track and manage changes to code."),
        ("The Software Development Life Cycle", "Students learn the stages involved in planning, building, and maintaining software."),
        ("Introduction to Object-Oriented Programming", "Students learn the basic concept of organizing code around objects and classes."),
        ("Introduction to HTML", "Students learn how HTML structures the content of a web page."),
        ("Introduction to CSS", "Students learn how CSS is used to style the appearance of a web page."),
        ("Introduction to JavaScript", "Students learn how JavaScript adds interactivity to web pages."),
        ("Mobile App Development Basics", "Students learn the basic concepts involved in building a mobile app."),
        ("Game Development Basics", "Students learn the basic concepts and tools used to create simple video games."),
        ("Introduction to Cryptography", "Students learn the basic concept of encoding information to keep it secure."),
        ("Data Structures: Arrays and Lists", "Students learn how arrays and lists are used to organize collections of data."),
        ("Introduction to Search and Sort Algorithms", "Students learn basic algorithms used to search and sort data."),
        ("Computational Thinking", "Students learn how breaking problems into smaller parts helps in solving them with computers."),
        ("Digital Citizenship", "Students learn the responsibilities and skills needed to participate safely and respectfully online."),
    ],
}
