"""Grade 4 (ages 8-9) topic expansion data.

Each subject maps to a list of (title, summary) tuples describing NEW
lessons to be added on top of the existing lessons already present in
backend/syllabus/grade4.json. A separate merge script builds full lesson
objects from these pairs.
"""

GRADE = 4

MODULES: dict[str, list[tuple[str, str]]] = {
    "Math": [
        ("Place Value and Rounding", "Students learn to identify place value in large numbers and round numbers to a given place."),
        ("Addition and Subtraction with Regrouping", "Students practice adding and subtracting multi-digit numbers using regrouping."),
        ("Division with Remainders", "Students learn to divide whole numbers and interpret remainders in real-world problems."),
        ("Factors and Multiples", "Students identify factors and multiples of numbers and use them to solve problems."),
        ("Prime and Composite Numbers", "Students learn to tell the difference between prime and composite numbers up to 100."),
        ("Equivalent Fractions", "Students learn how different fractions can represent the same amount."),
        ("Adding and Subtracting Fractions with Like Denominators", "Students practice combining and comparing fractions that share the same denominator."),
        ("Decimals: Tenths and Hundredths", "Students learn to read, write, and model decimal numbers to the hundredths place."),
        ("Comparing and Ordering Decimals", "Students compare and order decimal numbers using place value understanding."),
        ("Perimeter and Area", "Students learn to calculate the perimeter and area of rectangles and simple shapes."),
        ("Symmetry and Transformations", "Students explore lines of symmetry and simple shape transformations like flips and slides."),
        ("Classifying Triangles and Quadrilaterals", "Students learn to identify and classify shapes by their sides and angles."),
        ("Measurement: Length, Mass, and Volume", "Students practice measuring and converting units of length, mass, and volume."),
        ("Time: Elapsed Time Problems", "Students solve problems involving calculating elapsed time between events."),
        ("Data: Bar Graphs and Line Plots", "Students learn to read, create, and interpret bar graphs and line plots."),
        ("Word Problems with Multiple Steps", "Students practice solving multi-step word problems using the four operations."),
    ],
    "English": [
        ("Nouns, Pronouns, and Adjectives", "Students learn to identify and use nouns, pronouns, and adjectives correctly in sentences."),
        ("Verbs and Adverbs", "Students learn to identify verbs and adverbs and use them to describe actions clearly."),
        ("Sentence Types: Statements, Questions, Commands, Exclamations", "Students learn the four sentence types and how to punctuate each one correctly."),
        ("Subject-Verb Agreement", "Students practice matching subjects and verbs correctly in singular and plural sentences."),
        ("Punctuation: Commas and Quotation Marks", "Students learn to use commas in lists and quotation marks in dialogue."),
        ("Synonyms and Antonyms", "Students build vocabulary by identifying words with similar and opposite meanings."),
        ("Prefixes and Suffixes", "Students learn how prefixes and suffixes change the meaning of base words."),
        ("Context Clues for Vocabulary", "Students learn to use surrounding words in a sentence to figure out unfamiliar vocabulary."),
        ("Reading Comprehension: Main Idea and Details", "Students practice identifying the main idea and supporting details in a passage."),
        ("Reading Comprehension: Cause and Effect", "Students learn to recognize cause-and-effect relationships in stories and texts."),
        ("Fiction vs. Nonfiction", "Students learn to distinguish between fiction and nonfiction texts and their features."),
        ("Story Elements: Character, Setting, Plot", "Students identify the character, setting, and plot in a story they read."),
        ("Writing: Narrative Stories", "Students learn to write a short narrative story with a clear beginning, middle, and end."),
        ("Writing: Persuasive Letters", "Students practice writing a short letter that persuades the reader using reasons."),
        ("Writing: Informative Reports", "Students learn to write a short informative report on a topic using facts."),
        ("Using a Dictionary and Thesaurus", "Students practice using a dictionary and thesaurus to find word meanings and alternatives."),
        ("Figurative Language: Similes and Metaphors", "Students learn to identify and use similes and metaphors in writing."),
        ("Public Speaking and Oral Presentations", "Students practice organizing and delivering a short oral presentation clearly."),
    ],
    "Science": [
        ("States of Matter", "Students learn about solids, liquids, and gases and how matter can change state."),
        ("The Water Cycle", "Students learn how water moves through evaporation, condensation, and precipitation."),
        ("Simple Machines", "Students explore levers, pulleys, and other simple machines that make work easier."),
        ("Forces and Motion", "Students learn how pushes and pulls affect the motion of objects."),
        ("Plant Life Cycles and Parts", "Students learn the parts of a plant and the stages of a plant's life cycle."),
        ("Animal Life Cycles", "Students learn about the life cycles of different animals, including metamorphosis."),
        ("Food Chains and Food Webs", "Students learn how energy passes between organisms in food chains and food webs."),
        ("Ecosystems and Habitats", "Students learn how living things depend on their habitats and ecosystems to survive."),
        ("Rocks and Minerals", "Students learn to identify common rocks and minerals and how rocks are formed."),
        ("Weather and Climate", "Students learn to describe weather patterns and the difference between weather and climate."),
        ("The Human Body: Skeletal and Muscular Systems", "Students learn how bones and muscles work together to support and move the body."),
        ("The Human Body: Digestive System", "Students learn how the digestive system breaks down food for the body to use."),
        ("Sound and How We Hear", "Students learn how sound is made by vibrations and how our ears detect it."),
        ("Light and Shadows", "Students learn how light travels and how shadows are formed."),
        ("Magnets and Magnetism", "Students explore how magnets attract and repel and their everyday uses."),
        ("Energy: Forms and Uses", "Students learn about different forms of energy and how people use them."),
        ("Adaptations of Animals", "Students learn how animals have special features that help them survive in their environment."),
        ("Scientific Method and Fair Testing", "Students learn the steps of the scientific method and how to design a fair test."),
    ],
    "Geography": [
        ("Reading Maps and Map Keys", "Students learn to read maps and use map keys, symbols, and compass directions."),
        ("Continents and Oceans", "Students learn to identify and locate the world's continents and oceans."),
        ("Latitude and Longitude Basics", "Students learn how lines of latitude and longitude help locate places on a map."),
        ("Landforms and Physical Features", "Students learn to identify landforms such as mountains, valleys, and plains."),
        ("Climate Zones of the World", "Students learn about the world's major climate zones and what makes them different."),
        ("Rivers and Their Importance", "Students learn how rivers form and why they are important to people and nature."),
        ("Deserts of the World", "Students learn about the features of deserts and how living things adapt to them."),
        ("Rainforests and Biodiversity", "Students learn why rainforests have such rich biodiversity and why they matter."),
        ("Mountains and Mountain Ranges", "Students learn how mountains form and locate major mountain ranges of the world."),
        ("Countries and Capitals Overview", "Students learn to locate several countries on a world map and identify their capitals."),
        ("Population and Where People Live", "Students learn why people settle in certain places and how population is distributed."),
        ("Urban and Rural Communities", "Students compare the features of urban and rural communities."),
        ("Time Zones", "Students learn why time zones exist and how to read a simple time zone map."),
        ("Weather vs. Climate", "Students learn the difference between short-term weather and long-term climate."),
        ("Oceans and Marine Life", "Students learn about the world's oceans and the variety of life they support."),
        ("Human Impact on the Environment", "Students learn how human activities can affect land, water, and air."),
        ("Maps: Scale and Direction", "Students practice using map scale and cardinal directions to estimate distance."),
        ("Famous World Landmarks", "Students learn about well-known natural and human-made landmarks around the world."),
    ],
    "World History": [
        ("Ancient Egypt and the Pyramids", "Students learn about ancient Egyptian civilization and the building of the pyramids."),
        ("Ancient Mesopotamia and Writing", "Students learn how early writing developed in ancient Mesopotamia."),
        ("Ancient Greece and Democracy", "Students learn how ancient Greece contributed early ideas of democracy."),
        ("The Roman Empire", "Students learn about the rise of the Roman Empire and its lasting influence."),
        ("Ancient China and the Great Wall", "Students learn about ancient Chinese dynasties and the building of the Great Wall."),
        ("Ancient India and the Indus Valley", "Students learn about the early cities and culture of the Indus Valley civilization."),
        ("The Silk Road Trade Routes", "Students learn how the Silk Road connected cultures through trade of goods and ideas."),
        ("Medieval Europe and Castles", "Students learn about daily life, castles, and society in medieval Europe."),
        ("The Age of Exploration", "Students learn about explorers who sailed to new lands and the impact of their voyages."),
        ("Ancient Civilizations of the Americas", "Students learn about the achievements of the Maya, Aztec, and Inca civilizations."),
        ("Ancient Africa: Kingdoms of Ghana, Mali, and Songhai", "Students learn about the wealth and trade of ancient West African kingdoms."),
        ("The Renaissance", "Students learn about the rebirth of art and learning in Renaissance Europe."),
        ("Vikings and Their Voyages", "Students learn about Viking exploration, ships, and daily life."),
        ("Ancient Japan and the Samurai", "Students learn about ancient Japanese culture and the role of the samurai."),
        ("The Ottoman Empire", "Students learn about the growth and influence of the Ottoman Empire."),
        ("Early Trade and the Spice Routes", "Students learn how spice trade routes connected distant regions of the world."),
        ("Great Inventions of the Ancient World", "Students learn about important inventions from ancient civilizations still used today."),
        ("Timeline Skills: Understanding Historical Eras", "Students practice placing events in order on a timeline to understand historical eras."),
    ],
    "Islamic Studies": [
        ("The Five Pillars of Islam", "Students learn about the five basic acts of worship that form the foundation of Islamic practice."),
        ("The Importance of Salah (Prayer)", "Students learn why daily prayer is important and how it is practiced."),
        ("Learning About Zakat and Giving to Others", "Students learn how giving to those in need is an important part of Islamic life."),
        ("The Meaning of Ramadan and Fasting", "Students learn why Muslims fast during Ramadan and what the month means to them."),
        ("The Journey of Hajj", "Students learn about the pilgrimage to Makkah and its significance for Muslims."),
        ("Good Manners and Akhlaq in Daily Life", "Students learn about good character and manners valued in Islamic teachings."),
        ("Respecting Parents and Elders", "Students learn why showing respect and kindness to parents and elders is important."),
        ("Honesty and Trustworthiness in Islam", "Students learn why honesty and being trustworthy are valued qualities."),
        ("Kindness to Neighbors and Community", "Students learn about the importance of kindness and helping neighbors and the community."),
        ("Caring for Animals and Nature", "Students learn about the responsibility to treat animals and the environment with care."),
        ("The Importance of Cleanliness (Tahara)", "Students learn why cleanliness is valued in daily Islamic life."),
        ("Mosques and Their Role in the Community", "Students learn about the mosque as a place of prayer, learning, and community."),
        ("Islamic Calendar and Important Months", "Students learn about the lunar Islamic calendar and its significant months."),
        ("Celebrating Eid al-Fitr and Eid al-Adha", "Students learn about the traditions and meaning behind the two major Eid celebrations."),
        ("The Value of Knowledge and Learning in Islam", "Students learn why seeking knowledge is encouraged and respected."),
        ("Sharing and Charity in Everyday Life", "Students learn simple ways to practice generosity and charity in daily life."),
        ("Patience and Gratitude", "Students learn about the importance of patience and being thankful in daily life."),
        ("Islamic Art and Geometric Patterns", "Students learn about the geometric patterns and calligraphy found in Islamic art."),
        ("Muslim Scholars and Their Contributions", "Students learn about historical Muslim scholars and their contributions to science and learning."),
    ],
    "Coding": [
        ("Introduction to Sequencing", "Students learn how putting instructions in the correct order makes a program work."),
        ("Loops and Repetition in Scratch", "Students learn how to use loops to repeat actions in a Scratch project."),
        ("Variables in Block-Based Coding", "Students learn how to create and use variables to store and change information."),
        ("Events and Triggers in Scratch", "Students learn how events like key presses or clicks can trigger actions in a program."),
        ("Debugging: Finding and Fixing Errors", "Students learn strategies for finding and fixing mistakes in their code."),
        ("Creating a Simple Animation", "Students learn to use costumes and movement blocks to animate a sprite."),
        ("Building a Simple Quiz Game", "Students learn to combine questions, variables, and conditionals to build a quiz game."),
        ("Introduction to Algorithms", "Students learn that an algorithm is a set of step-by-step instructions to solve a problem."),
        ("Broadcasting Messages Between Sprites", "Students learn how sprites can communicate using broadcast messages."),
        ("Using Coordinates on the Stage", "Students learn how x and y coordinates control where sprites appear and move."),
        ("Costumes and Sprite Movement", "Students learn how changing costumes and using movement blocks brings a sprite to life."),
        ("Introduction to Functions (Custom Blocks)", "Students learn how to create reusable custom blocks to organize their code."),
        ("Random Numbers in Games", "Students learn how random number blocks add unpredictability to games."),
        ("Designing a Maze Game", "Students learn to plan and build a simple maze game using loops and conditionals."),
        ("Introduction to Text-Based Coding Concepts", "Students are introduced to basic text-based coding ideas as a bridge from block coding."),
        ("Logical Thinking and Problem Decomposition", "Students learn to break a big problem into smaller steps before coding a solution."),
        ("Making Music with Code", "Students learn to use sound and music blocks to add audio to their projects."),
        ("Storytelling with Code", "Students learn to combine sprites, dialogue, and backdrops to tell an interactive story."),
        ("Sharing and Presenting a Coding Project", "Students learn how to explain and present their finished coding project to others."),
    ],
    "World Literature": [
        ("Aesop's Fables and Their Morals", "Students explore classic Aesop's fables and discuss the lessons they teach."),
        ("The Arabian Nights: Tales of Adventure", "Students explore themes of adventure and cleverness in classic Arabian Nights tales."),
        ("Grimm Brothers' Fairy Tales", "Students explore themes from well-known German fairy tales collected by the Grimm brothers."),
        ("Hans Christian Andersen's Tales", "Students explore themes of kindness and imagination in Andersen's classic tales."),
        ("Panchatantra: Indian Animal Fables", "Students explore how ancient Indian animal fables teach lessons about wisdom and behavior."),
        ("Anansi the Spider: West African Folk Tales", "Students explore trickster tales about Anansi the spider from West African storytelling traditions."),
        ("Japanese Folk Tales and Legends", "Students explore themes and characters from classic Japanese folk tales."),
        ("Chinese Folk Tales and Legends", "Students explore themes and characters from classic Chinese folk tales."),
        ("Native American Legends and Storytelling", "Students explore themes of nature and community in Native American storytelling traditions."),
        ("Aboriginal Dreamtime Stories", "Students explore how Dreamtime stories explain the natural world in Aboriginal Australian traditions."),
        ("Persian Poetry for Young Readers", "Students explore simple themes of wisdom and beauty found in classic Persian poetry."),
        ("Greek Mythology: Heroes and Gods", "Students explore stories of heroes and gods from ancient Greek mythology."),
        ("Norse Mythology: Legends of the North", "Students explore stories of gods and heroes from ancient Norse mythology."),
        ("Korean Folk Tales", "Students explore themes and characters from classic Korean folk tales."),
        ("Caribbean Folk Tales and Anansi Stories", "Students explore how Anansi stories traveled to and were retold in Caribbean storytelling traditions."),
        ("Russian Folk Tales", "Students explore themes and characters from classic Russian folk tales."),
        ("Latin American Legends and Folklore", "Students explore legends and folklore from various Latin American cultures."),
        ("Cinderella Stories Around the World", "Students compare how different cultures tell their own version of a Cinderella-type story."),
        ("Storytelling Traditions Around the World", "Students explore how oral storytelling has been used across cultures to pass down values and history."),
    ],
    "Art": [
        ("Color Theory: Primary and Secondary Colors", "Students learn how primary colors combine to create secondary colors."),
        ("Warm and Cool Colors", "Students learn to identify warm and cool colors and how they affect a piece of art."),
        ("Introduction to Watercolor Painting", "Students learn basic watercolor techniques such as washes and blending."),
        ("Drawing with Shapes and Lines", "Students learn to build drawings by starting with basic shapes and lines."),
        ("Portrait Drawing Basics", "Students learn simple techniques for drawing facial proportions in a portrait."),
        ("Still Life Drawing", "Students learn to observe and draw a simple arrangement of everyday objects."),
        ("Introduction to Sculpture with Clay", "Students learn basic hand-building techniques for shaping clay."),
        ("Printmaking Basics", "Students learn simple printmaking techniques such as stamping and relief printing."),
        ("Collage Art Techniques", "Students learn to create a collage by arranging and layering different materials."),
        ("Introduction to Perspective Drawing", "Students learn simple techniques for showing depth and distance in a drawing."),
        ("Famous Artists: Van Gogh and Post-Impressionism", "Students learn about Vincent van Gogh's life and his distinctive painting style."),
        ("Famous Artists: Picasso and Cubism", "Students learn about Pablo Picasso and the basics of the Cubist art style."),
        ("Traditional Patterns and Textile Art", "Students explore traditional patterns used in textile art from different cultures."),
        ("Cartooning and Comic Strip Basics", "Students learn to draw simple cartoon characters and create a short comic strip."),
        ("Mixing and Shading with Colored Pencils", "Students learn techniques for blending and shading with colored pencils."),
        ("Introduction to Origami", "Students learn to fold simple origami shapes from paper."),
        ("Art from Recycled Materials", "Students learn to create art projects using recycled and reused materials."),
        ("Mosaic Art Basics", "Students learn to create a simple mosaic design using small pieces of paper or tile."),
        ("Designing a Poster or Illustration", "Students learn to plan and create a poster that combines images and text."),
    ],
    "Music": [
        ("Introduction to Musical Instrument Families", "Students learn about the string, wind, brass, and percussion families of instruments."),
        ("The Percussion Family", "Students learn about percussion instruments and how they create rhythm."),
        ("The String Family", "Students learn about stringed instruments and how they produce sound."),
        ("The Wind Family", "Students learn about wind instruments and how air produces their sound."),
        ("Introduction to Singing and Vocal Warm-Ups", "Students learn simple vocal warm-up exercises for healthy singing."),
        ("Understanding Tempo and Dynamics", "Students learn how tempo and dynamics change the feeling of a piece of music."),
        ("Introduction to Musical Scales", "Students learn what a musical scale is and how to sing or play a simple scale."),
        ("Rhythm Patterns and Clapping Games", "Students learn to clap and repeat simple rhythm patterns."),
        ("Introduction to Reading a Melody", "Students learn to follow the rise and fall of a simple melody on a staff."),
        ("Famous Composers: Mozart and Classical Music", "Students learn about the life of Mozart and the classical music era."),
        ("Famous Composers: Beethoven's Life and Music", "Students learn about the life and music of Ludwig van Beethoven."),
        ("Music from Around the World", "Students explore musical styles and instruments from different cultures."),
        ("Introduction to the Recorder", "Students learn basic fingerings and notes for playing the recorder."),
        ("Introduction to the Keyboard/Piano", "Students learn to identify keys and play simple notes on a keyboard."),
        ("Call and Response in Music", "Students learn the call-and-response pattern found in many musical traditions."),
        ("Introduction to Musical Notation Symbols", "Students learn to recognize basic notation symbols such as notes and rests."),
        ("Creating Simple Rhythms and Compositions", "Students practice creating and performing their own simple rhythm pattern."),
        ("Music and Emotion", "Students explore how music can express and change emotions."),
        ("Introduction to Ensemble Playing", "Students learn the basics of playing or singing together as a group."),
    ],
    "Survival Skills": [
        ("Basic Map and Compass Reading", "Students learn simple skills for reading a map and using a compass to find direction."),
        ("Building a Simple Shelter", "Students learn the basics of building a simple shelter for outdoor safety."),
        ("Water Safety Basics", "Students learn basic rules for staying safe around lakes, pools, and rivers."),
        ("Recognizing Safe Drinking Water", "Students learn why clean drinking water matters and simple ways to identify it."),
        ("Tying Basic Knots", "Students learn to tie a few simple, useful knots."),
        ("Weather Awareness and Staying Safe Outdoors", "Students learn to recognize changing weather signs and stay safe outdoors."),
        ("What to Do If You Get Lost", "Students learn simple steps to stay calm and safe if they become lost."),
        ("Stranger Safety and Trusted Adults", "Students learn how to identify trusted adults and stay safe around strangers."),
        ("Basic Signaling for Help", "Students learn simple ways to signal for help in an emergency."),
        ("Road and Traffic Safety", "Students learn rules for safely crossing streets and being aware of traffic."),
        ("Home Safety: Preventing Accidents", "Students learn how to identify and prevent common accidents at home."),
        ("Earthquake Safety Drills", "Students learn the correct steps to take during an earthquake safety drill."),
        ("Severe Weather Safety (Storms and Floods)", "Students learn how to stay safe during storms and floods."),
        ("Packing an Emergency Kit", "Students learn what basic items belong in a family emergency kit."),
        ("Recognizing Poisonous Plants and Animals", "Students learn to recognize and avoid common poisonous plants and animals."),
        ("Basic Hiking and Trail Safety", "Students learn simple rules for staying safe while hiking on a trail."),
        ("Internet and Online Safety Basics", "Students learn basic rules for staying safe while using the internet."),
        ("Swimming Safety and Water Rescue Basics", "Students learn basic swimming safety rules and simple water rescue awareness."),
        ("Staying Calm in Emergencies", "Students learn simple strategies for staying calm and thinking clearly in an emergency."),
    ],
    "General Knowledge": [
        ("Flags of the World", "Students learn to recognize the flags of several countries around the world."),
        ("Major World Currencies", "Students learn about the currencies used in different countries around the world."),
        ("Wonders of the Ancient World", "Students learn about the famous Seven Wonders of the Ancient World."),
        ("Famous Inventors and Their Inventions", "Students learn about inventors and the inventions that changed daily life."),
        ("Space Exploration Milestones", "Students learn about key milestones in the history of space exploration."),
        ("Famous Explorers in History", "Students learn about explorers who traveled to new and distant places."),
        ("National Symbols and Their Meaning", "Students learn about national symbols such as flags, anthems, and emblems."),
        ("Major International Organizations", "Students learn about the basic purpose of organizations like the United Nations and UNICEF."),
        ("Olympic Games History and Facts", "Students learn about the history and traditions of the Olympic Games."),
        ("World Languages and Where They Are Spoken", "Students learn about some of the world's major languages and where they are spoken."),
        ("Famous Landmarks and Monuments", "Students learn about well-known landmarks and monuments around the world."),
        ("Animals Around the World", "Students learn interesting facts about animals from different regions of the world."),
        ("Important Inventions That Changed the World", "Students learn about inventions that had a major impact on how people live."),
        ("Famous Scientists and Discoveries", "Students learn about scientists and the discoveries that shaped our understanding of the world."),
        ("World Religions Overview", "Students learn basic facts about several major world religions and their traditions."),
        ("Time and Calendars Around the World", "Students learn how different cultures have measured time and created calendars."),
        ("Famous Books and Authors for Children", "Students learn about well-known children's authors and their famous books."),
        ("Current Events for Kids", "Students learn simple age-appropriate ways to follow and understand current events."),
        ("General Trivia: Numbers and Measurements", "Students explore fun facts involving numbers, sizes, and measurements from around the world."),
    ],
    "Cooking": [
        ("Kitchen Safety Basics", "Students learn basic safety rules for working in a kitchen with adult supervision."),
        ("Washing Hands and Food Hygiene", "Students learn why handwashing and food hygiene are important before cooking."),
        ("Understanding Food Groups", "Students learn about the different food groups and why a balanced diet matters."),
        ("Basic Knife Safety with Adult Supervision", "Students learn safe habits for handling kitchen tools with an adult present."),
        ("Simple Breakfast Recipes", "Students learn to prepare a few simple, healthy breakfast recipes."),
        ("Making a Healthy Sandwich", "Students learn to assemble a healthy sandwich using different ingredients."),
        ("Baking Basics: Cookies and Muffins", "Students learn simple baking steps for making cookies or muffins with an adult."),
        ("Understanding Recipes and Ingredient Lists", "Students learn how to read a recipe and understand an ingredient list."),
        ("Setting a Table and Table Manners", "Students learn how to set a table properly and practice good table manners."),
        ("Fruits and Vegetables Around the World", "Students learn about fruits and vegetables grown and eaten in different countries."),
        ("No-Cook Snack Ideas", "Students learn to prepare simple, healthy snacks that do not require cooking."),
        ("Basic Measuring Tools and Units", "Students learn to use measuring cups and spoons correctly in cooking."),
        ("Food Safety and Storage", "Students learn basic rules for storing food safely to prevent spoilage."),
        ("Simple Salads and Dressings", "Students learn to prepare a simple salad and a basic dressing."),
        ("Cooking Around the World: Popular Dishes", "Students learn about popular dishes and cooking styles from different cultures."),
        ("Understanding Where Food Comes From", "Students learn how common foods are grown, raised, or made before reaching the table."),
        ("Reducing Food Waste", "Students learn simple habits for reducing food waste at home."),
        ("Basic Stovetop Safety with an Adult", "Students learn safe habits for using a stovetop only with adult supervision."),
        ("Planning a Balanced Meal", "Students learn to plan a simple, balanced meal using different food groups."),
    ],
    "Foreign Languages": [
        ("Greetings and Introductions in Spanish", "Students learn simple greetings and how to introduce themselves in Spanish."),
        ("Numbers 1-20 in French", "Students learn to count from one to twenty in French."),
        ("Colors and Shapes in Mandarin Chinese", "Students learn simple vocabulary for colors and shapes in Mandarin Chinese."),
        ("Days of the Week in German", "Students learn to say the days of the week in German."),
        ("Animals in Spanish", "Students learn simple vocabulary for common animals in Spanish."),
        ("Common Phrases in Japanese", "Students learn a few common everyday phrases in Japanese."),
        ("Food and Meals in French", "Students learn simple vocabulary for common foods and meals in French."),
        ("Family Members in Urdu", "Students learn simple vocabulary for family members in Urdu."),
        ("Basic Greetings in Swahili", "Students learn simple greetings and polite phrases in Swahili."),
        ("Weather Words in Spanish", "Students learn simple vocabulary for describing the weather in Spanish."),
        ("Numbers 1-20 in Arabic", "Students learn to count from one to twenty in Arabic."),
        ("Common Phrases in Hindi", "Students learn a few common everyday phrases in Hindi."),
        ("Colors in French", "Students learn simple vocabulary for colors in French."),
        ("My School in Spanish", "Students learn simple vocabulary for school items and classroom words in Spanish."),
        ("Basic Greetings in Turkish", "Students learn simple greetings and polite phrases in Turkish."),
        ("Body Parts in French", "Students learn simple vocabulary for parts of the body in French."),
        ("Common Phrases in Bengali", "Students learn a few common everyday phrases in Bengali."),
        ("Animals in German", "Students learn simple vocabulary for common animals in German."),
        ("Simple Conversations in Spanish", "Students practice putting together simple short conversations in Spanish."),
    ],
    "Social Studies": [
        ("Community Helpers and Their Roles", "Students learn about different community helpers and the roles they play."),
        ("Rights and Responsibilities of Citizens", "Students learn about the basic rights and responsibilities citizens have."),
        ("Local, State, and National Government", "Students learn the differences between local, state, and national levels of government."),
        ("How Laws Are Made", "Students learn a simple explanation of how laws are created."),
        ("Economics Basics: Needs and Wants", "Students learn the difference between needs and wants in economics."),
        ("Goods and Services", "Students learn the difference between goods and services in an economy."),
        ("Supply and Demand for Kids", "Students learn a simple introduction to how supply and demand affect prices."),
        ("Money and Saving Basics", "Students learn basic concepts about earning, spending, and saving money."),
        ("Maps of My Community", "Students learn to read and create simple maps of their own community."),
        ("Cultural Diversity and Traditions", "Students learn to appreciate different cultural traditions and celebrations."),
        ("Immigration and Migration Stories", "Students learn simple stories about why people move to new places."),
        ("Voting and Elections Basics", "Students learn a basic introduction to how voting and elections work."),
        ("Historical Landmarks in My Country", "Students learn about important historical landmarks in their own country."),
        ("Community Problem Solving", "Students learn how communities work together to solve local problems."),
        ("Volunteering and Civic Responsibility", "Students learn about the value of volunteering and helping their community."),
        ("Symbols of My Country", "Students learn about important national symbols of their own country."),
        ("Family Trees and Heritage", "Students learn to create a simple family tree and explore their heritage."),
        ("Comparing Rural, Urban, and Suburban Life", "Students compare daily life in rural, urban, and suburban communities."),
        ("Global Citizenship and Cooperation", "Students learn simple ideas about how countries cooperate and share global responsibilities."),
    ],
    "Physical Education & Self-Defense": [
        ("Warm-Up and Stretching Basics", "Students learn simple warm-up and stretching routines before physical activity."),
        ("Basic Running and Agility Drills", "Students practice simple running and agility drills to build coordination."),
        ("Throwing and Catching Skills", "Students practice basic throwing and catching skills used in many sports."),
        ("Jumping and Balance Skills", "Students practice basic jumping and balance exercises."),
        ("Introduction to Basketball Skills", "Students learn basic basketball skills such as dribbling and passing."),
        ("Introduction to Soccer Skills", "Students learn basic soccer skills such as dribbling and passing with the feet."),
        ("Introduction to Volleyball Skills", "Students learn basic volleyball skills such as bumping and setting."),
        ("Basic Gymnastics Movements", "Students practice basic gymnastics movements like rolls and balances."),
        ("Yoga for Kids: Basic Poses", "Students learn a few simple yoga poses and breathing exercises."),
        ("Introduction to Swimming Strokes", "Students learn the basics of common swimming strokes."),
        ("Basic Self-Defense: Awareness and Avoidance", "Students learn simple strategies for staying aware of surroundings and avoiding danger."),
        ("Basic Self-Defense: Safe Distancing and Saying No", "Students learn simple, age-appropriate ways to set boundaries and say no to unsafe situations."),
        ("Cooperative Games and Teamwork", "Students play cooperative games that build teamwork and communication."),
        ("Introduction to Track and Field", "Students learn basic running, jumping, and throwing events found in track and field."),
        ("Jump Rope Skills", "Students practice basic jump rope skills and simple routines."),
        ("Understanding Fair Play and Sportsmanship", "Students learn about the importance of fair play and good sportsmanship."),
        ("Basic Martial Arts Stances and Discipline", "Students learn simple martial arts stances and the value of discipline and respect."),
        ("Fitness and Endurance Basics", "Students learn simple exercises that build fitness and endurance over time."),
        ("Rules and Etiquette in Sports", "Students learn basic rules and etiquette expected when playing sports."),
    ],
    "Health Education": [
        ("Personal Hygiene Basics", "Students learn daily hygiene habits that keep their bodies healthy and clean."),
        ("Dental Health and Care", "Students learn how to properly care for their teeth and gums."),
        ("The Importance of Sleep", "Students learn why getting enough sleep is important for health and growth."),
        ("Germs and How Illness Spreads", "Students learn how germs spread and cause illness."),
        ("Hand Washing and Preventing Illness", "Students learn proper handwashing steps to help prevent the spread of illness."),
        ("Understanding Vaccines and Immunity", "Students learn a simple explanation of how vaccines help protect the body."),
        ("Healthy Eating: Reading Food Labels", "Students learn how to read a simple food label to make healthy choices."),
        ("Staying Active: Benefits of Exercise", "Students learn how regular physical activity benefits the body and mind."),
        ("Emotional Health and Expressing Feelings", "Students learn healthy ways to recognize and express their feelings."),
        ("Understanding Body Systems Overview", "Students learn a simple overview of how major body systems work together."),
        ("Safety Around Medicines", "Students learn basic safety rules about medicines and why only adults should give them."),
        ("Recognizing and Avoiding Harmful Substances", "Students learn to recognize and stay away from harmful substances."),
        ("Building Healthy Friendships", "Students learn qualities of healthy, respectful friendships."),
        ("Understanding Allergies", "Students learn what allergies are and simple ways to stay safe around them."),
    ],
    "ICT & Computer Science": [
        ("Introduction to Computer Hardware", "Students learn to identify basic computer hardware parts such as the monitor, keyboard, and mouse."),
        ("Introduction to Computer Software", "Students learn the difference between hardware and software and give examples of each."),
        ("How the Internet Works", "Students learn a simple explanation of how devices connect to the internet."),
        ("Online Safety and Digital Citizenship", "Students learn basic rules for staying safe and being respectful online."),
        ("Introduction to Word Processing", "Students learn basic skills for typing and formatting text in a word processor."),
        ("Introduction to Spreadsheets", "Students learn basic skills for entering and organizing data in a spreadsheet."),
        ("Introduction to Presentation Software", "Students learn basic skills for creating a simple slide presentation."),
        ("Typing Skills and Keyboarding", "Students practice proper finger placement and basic typing skills."),
        ("Understanding File Types and Storage", "Students learn about common file types and how files are organized and stored."),
        ("Introduction to the World Wide Web and Browsers", "Students learn how web browsers are used to visit websites on the internet."),
        ("Email Basics and Etiquette", "Students learn the basic parts of an email and polite email etiquette."),
        ("Introduction to Search Engines", "Students learn how to use a search engine to find information effectively."),
        ("Understanding Passwords and Account Security", "Students learn why strong passwords matter and how to keep accounts secure."),
        ("Introduction to Coding Concepts Unplugged", "Students learn basic coding concepts through hands-on activities without a computer."),
        ("Introduction to Robots and Automation", "Students learn simple ideas about how robots follow instructions to complete tasks."),
        ("Understanding Computer Networks Basics", "Students learn a simple explanation of how computers connect together in a network."),
        ("Digital Footprint and Privacy", "Students learn what a digital footprint is and simple ways to protect their privacy online."),
        ("Introduction to Artificial Intelligence for Kids", "Students learn a simple, age-appropriate introduction to what artificial intelligence is."),
        ("Evaluating Information Online: Fact vs. Fiction", "Students learn simple strategies for judging whether information found online is reliable."),
    ],
}
