"""Grade 5 (ages 9-10) topic expansion data.

Each subject maps to a list of (title, summary) tuples describing NEW
lessons to be added on top of the existing lessons already present in
backend/syllabus/grade5.json. A separate merge script builds full lesson
objects from these pairs.
"""

GRADE = 5

MODULES: dict[str, list[tuple[str, str]]] = {
    "Math": [
        ("Multiplying Multi-Digit Numbers", "Students learn to multiply multi-digit whole numbers using the standard algorithm."),
        ("Dividing Multi-Digit Numbers", "Students learn to divide multi-digit numbers by one- and two-digit divisors."),
        ("Order of Operations", "Students learn to evaluate numerical expressions correctly using order of operations."),
        ("Adding and Subtracting Fractions with Unlike Denominators", "Students learn to find common denominators to add and subtract fractions."),
        ("Multiplying Fractions", "Students learn to multiply fractions and mixed numbers and interpret the results."),
        ("Dividing Fractions", "Students learn to divide whole numbers and fractions using models and algorithms."),
        ("Multiplying and Dividing Decimals", "Students learn to multiply and divide decimal numbers using place value reasoning."),
        ("Converting Fractions, Decimals, and Percentages", "Students learn to convert between fractions, decimals, and percentages fluently."),
        ("Negative Numbers on a Number Line", "Students learn to locate, compare, and order positive and negative numbers."),
        ("Powers and Exponents", "Students learn to write and evaluate simple expressions using whole-number exponents."),
        ("Volume of Rectangular Prisms", "Students learn to calculate the volume of rectangular prisms using unit cubes and formulas."),
        ("Coordinate Plane Basics", "Students learn to plot and identify points on a coordinate plane using ordered pairs."),
        ("Classifying 2D Shapes by Properties", "Students learn to classify two-dimensional shapes based on their properties."),
        ("Angles: Measuring and Classifying", "Students learn to measure angles with a protractor and classify them by size."),
        ("Circles: Radius, Diameter, and Circumference", "Students learn the parts of a circle and how radius and diameter relate."),
        ("Line Graphs and Interpreting Trends", "Students learn to create and interpret line graphs to show change over time."),
        ("Mean Absolute Deviation Basics", "Students learn a simple way to measure how spread out a set of data is."),
        ("Probability of Simple Events", "Students learn to describe and calculate the probability of simple chance events."),
        ("Algebraic Expressions and Variables", "Students learn to write and evaluate simple algebraic expressions with variables."),
        ("Solving One-Step Equations", "Students learn to solve simple one-step equations using inverse operations."),
        ("Patterns and Sequences", "Students learn to identify and extend numerical and geometric patterns."),
        ("Estimation and Rounding Strategies", "Students learn to estimate sums, differences, products, and quotients to check reasonableness."),
        ("Word Problems with Multiple Operations", "Students solve multi-step word problems that combine several operations."),
        ("Converting Units of Measurement", "Students learn to convert between metric units of length, mass, and capacity."),
        ("Elapsed Time and Time Zones", "Students learn to calculate elapsed time and understand basic time zone differences."),
        ("Financial Literacy: Budgeting Basics", "Students learn to create a simple budget by tracking income and expenses."),
        ("Introduction to Prime Factorization", "Students learn to break numbers down into their prime factors using factor trees."),
    ],
    "English": [
        ("Types of Clauses: Independent and Dependent", "Students learn to identify independent and dependent clauses in sentences."),
        ("Complex and Compound Sentences", "Students learn to build compound and complex sentences using conjunctions."),
        ("Active and Passive Voice", "Students learn to recognize and use active and passive voice in writing."),
        ("Commonly Confused Words", "Students learn to correctly use commonly confused words such as their, there, and they're."),
        ("Root Words and Word Origins", "Students learn how Greek and Latin roots help unlock the meaning of words."),
        ("Idioms and Figurative Expressions", "Students learn to interpret common idioms and figurative expressions in text."),
        ("Analyzing Theme in Literature", "Students learn to identify the theme or central message of a story."),
        ("Comparing Characters Across Texts", "Students learn to compare how different authors develop similar characters."),
        ("Point of View: First, Second, and Third Person", "Students learn to identify and explain the narrator's point of view in a text."),
        ("Analyzing Author's Purpose", "Students learn to determine whether an author's purpose is to inform, persuade, or entertain."),
        ("Summarizing Fiction and Nonfiction Texts", "Students learn to write concise summaries that capture the key ideas of a text."),
        ("Text Structure: Compare and Contrast", "Students learn to identify compare-and-contrast structure in informational text."),
        ("Text Structure: Problem and Solution", "Students learn to identify problem-and-solution structure in informational text."),
        ("Evaluating Evidence and Arguments", "Students learn to evaluate whether an author's claims are supported by evidence."),
        ("Poetry: Rhyme, Rhythm, and Meaning", "Students learn to analyze how rhyme and rhythm contribute to a poem's meaning."),
        ("Writing Persuasive Essays", "Students learn to write a persuasive essay with a clear claim and supporting reasons."),
        ("Writing Research Reports", "Students learn to gather information from sources and organize it into a report."),
        ("Citing Sources and Avoiding Plagiarism", "Students learn the basics of giving credit to sources used in their writing."),
        ("Revising and Editing Writing", "Students learn strategies for revising drafts to improve clarity and correctness."),
        ("Using Transition Words", "Students learn to use transition words to connect ideas smoothly in writing."),
        ("Writing Dialogue Correctly", "Students learn to punctuate and format dialogue correctly in narrative writing."),
        ("Analyzing Poetic Devices", "Students learn to identify alliteration, personification, and onomatopoeia in poems."),
        ("Reading Graphic Organizers and Charts", "Students learn to interpret information presented in charts and graphic organizers within texts."),
        ("Debate and Argumentation Basics", "Students learn to state a position and support it with reasons in a friendly debate."),
        ("Note-Taking Strategies", "Students learn effective strategies for taking notes while reading or listening."),
        ("Understanding Author's Tone", "Students learn to identify the tone of a passage based on word choice and details."),
        ("Reading Fluency and Expression", "Students practice reading aloud with appropriate pace, accuracy, and expression."),
        ("Analyzing Folktales and Fables", "Students learn to identify the lesson or moral conveyed in folktales and fables."),
        ("Formal Letter Writing", "Students learn the structure and tone appropriate for writing a formal letter."),
    ],
    "Science": [
        ("Scientific Investigations and Variables", "Students learn to design an investigation by identifying variables to test and control."),
        ("The Solar System", "Students learn about the planets, their order, and their key features in the solar system."),
        ("Earth's Rotation and Revolution", "Students learn how Earth's rotation causes day and night and revolution causes seasons."),
        ("Phases of the Moon", "Students learn why the moon appears to change shape throughout the month."),
        ("Layers of the Earth", "Students learn about the crust, mantle, outer core, and inner core of the Earth."),
        ("Plate Tectonics and Earthquakes", "Students learn how moving tectonic plates cause earthquakes and shape landforms."),
        ("Volcanoes and How They Form", "Students learn how volcanoes form and how they change the Earth's surface."),
        ("Weathering and Erosion", "Students learn how weathering and erosion gradually change the Earth's surface."),
        ("The Rock Cycle", "Students learn how igneous, sedimentary, and metamorphic rocks form and change over time."),
        ("Ecosystem Interactions and Food Webs", "Students learn how energy and matter move through complex ecosystem food webs."),
        ("Human Impact on Ecosystems", "Students learn how human activity can positively and negatively affect ecosystems."),
        ("Classification of Living Things", "Students learn how scientists classify living things into groups based on shared traits."),
        ("Vertebrates and Invertebrates", "Students learn to distinguish between vertebrate and invertebrate animals."),
        ("The Circulatory System", "Students learn how the heart and blood vessels move blood throughout the body."),
        ("The Respiratory System", "Students learn how the lungs help the body take in oxygen and release carbon dioxide."),
        ("The Nervous System Basics", "Students learn how the brain and nerves send and receive messages in the body."),
        ("Properties of Matter", "Students learn to describe and measure physical properties such as mass and density."),
        ("Mixtures and Solutions", "Students learn the difference between mixtures and solutions and how to separate them."),
        ("Physical and Chemical Changes", "Students learn to distinguish between physical changes and chemical changes in matter."),
        ("Energy Transfer and Transformation", "Students learn how energy can transfer and change form, such as from motion to heat."),
        ("Electric Circuits Basics", "Students learn how simple electric circuits work with a power source and conductors."),
        ("Static Electricity", "Students learn what causes static electricity and how it behaves in everyday life."),
        ("Heat Transfer: Conduction, Convection, Radiation", "Students learn the three ways heat energy can move between objects."),
        ("Sound Waves and Pitch", "Students learn how the properties of sound waves relate to pitch and volume."),
        ("Light: Reflection and Refraction", "Students learn how light reflects off surfaces and bends when passing through materials."),
        ("Gravity and Its Effects", "Students learn how gravity affects objects on Earth and in the solar system."),
        ("Renewable and Nonrenewable Resources", "Students learn to distinguish between renewable and nonrenewable natural resources."),
        ("Engineering Design Process", "Students learn the steps engineers use to design, test, and improve a solution."),
    ],
    "Geography": [
        ("Latitude, Longitude, and the Global Grid", "Students learn to use latitude and longitude to precisely locate places on Earth."),
        ("Time Zones and the International Date Line", "Students learn how time zones are determined and why the date line exists."),
        ("Physical vs. Political Maps", "Students learn to distinguish between physical maps and political maps and their uses."),
        ("Population Density and Distribution", "Students learn how population density varies across regions and why."),
        ("Urbanization and City Growth", "Students learn why cities grow and how urbanization changes land use."),
        ("Natural Resources and Their Distribution", "Students learn how natural resources are distributed unevenly around the world."),
        ("Agriculture and Land Use", "Students learn how climate and soil influence agriculture and land use patterns."),
        ("Rivers, Watersheds, and Water Management", "Students learn how watersheds work and why managing river water matters."),
        ("Deserts and Desertification", "Students learn about desert environments and the causes of desertification."),
        ("Mountain Ranges and Human Settlement", "Students learn how mountain ranges affect where and how people live."),
        ("Oceans and Marine Resources", "Students learn about the world's oceans and the resources they provide."),
        ("Migration: Push and Pull Factors", "Students learn about factors that cause people to migrate from one place to another."),
        ("Cultural Regions of the World", "Students learn how language, religion, and traditions define cultural regions."),
        ("Natural Disasters and Preparedness", "Students learn about types of natural disasters and how communities prepare for them."),
        ("Renewable Energy Around the World", "Students learn how different countries use renewable energy sources based on geography."),
        ("Deforestation and Its Effects", "Students learn the causes of deforestation and its impact on ecosystems and climate."),
        ("Map Projections and Distortion", "Students learn why flat maps distort the true shapes and sizes of continents."),
        ("Economic Geography: Trade Routes", "Students learn how historic and modern trade routes connect regions economically."),
        ("Borders and Political Boundaries", "Students learn how political boundaries are formed and can change over time."),
        ("Biomes of the World", "Students learn to identify the world's major biomes and their characteristic features."),
        ("Coastal Landforms", "Students learn how waves and tides shape coastal landforms such as cliffs and beaches."),
        ("Global Food Security", "Students learn about the geographic factors that affect food security around the world."),
        ("Water Scarcity and Access", "Students learn why some regions face water scarcity and how it affects communities."),
        ("Transportation Networks", "Students learn how roads, railways, and shipping routes connect people and places."),
        ("Indigenous Peoples and Their Lands", "Students learn about indigenous peoples' relationships with their traditional lands."),
        ("Comparing Developed and Developing Regions", "Students learn to compare economic and infrastructure differences between regions."),
        ("Tourism and Its Geographic Impact", "Students learn how tourism affects local economies and environments."),
        ("Reading Topographic Maps", "Students learn to interpret contour lines and elevation on topographic maps."),
    ],
    "World History": [
        ("Early Human Migration", "Students learn how early humans migrated and settled across different continents."),
        ("The Agricultural Revolution", "Students learn how the shift to farming changed early human societies."),
        ("Ancient Mesopotamia", "Students learn about the rise of cities and writing in ancient Mesopotamia."),
        ("Ancient Egypt", "Students learn about the civilization, pharaohs, and achievements of ancient Egypt."),
        ("Ancient Greece: Democracy and Philosophy", "Students learn how ancient Greece contributed early ideas about democracy and philosophy."),
        ("The Roman Empire", "Students learn about the rise, government, and legacy of the Roman Empire."),
        ("Ancient China: Dynasties and Inventions", "Students learn about early Chinese dynasties and their key inventions."),
        ("Ancient India: The Indus Valley", "Students learn about the achievements of the ancient Indus Valley civilization."),
        ("The Silk Road", "Students learn how the Silk Road connected trade and ideas between East and West."),
        ("The Middle Ages in Europe", "Students learn about feudalism, castles, and daily life in medieval Europe."),
        ("The Islamic Golden Age", "Students learn about advances in science, medicine, and mathematics during the Islamic Golden Age."),
        ("Empires of West Africa", "Students learn about the wealth and trade of empires such as Mali and Songhai."),
        ("The Mongol Empire", "Students learn how the Mongol Empire became the largest connected land empire in history."),
        ("Feudal Japan and the Samurai", "Students learn about the social structure and warrior culture of feudal Japan."),
        ("The Maya, Aztec, and Inca Civilizations", "Students learn about the achievements of major early civilizations of the Americas."),
        ("The Printing Press and Its Impact", "Students learn how the invention of the printing press spread ideas and literacy."),
        ("The Reformation", "Students learn about the religious changes in Europe during the Reformation period."),
        ("Global Exploration and Its Consequences", "Students learn how global exploration led to new contact between distant peoples."),
        ("The Columbian Exchange", "Students learn how plants, animals, and diseases were exchanged between hemispheres."),
        ("The Scientific Revolution", "Students learn how new scientific methods changed understanding of the natural world."),
        ("Colonial Empires", "Students learn how European powers established colonies around the world."),
        ("The Atlantic Slave Trade", "Students learn about the history and human impact of the Atlantic slave trade."),
        ("The Enlightenment", "Students learn how Enlightenment thinkers influenced ideas about rights and government."),
        ("The Industrial Revolution", "Students learn how new machines and factories transformed work and daily life."),
        ("Revolutions for Independence", "Students learn about key revolutions in which colonies sought independence."),
        ("The World Wars: An Overview", "Students learn the basic causes and global impact of the twentieth century's world wars."),
        ("The United Nations and Global Cooperation", "Students learn why the United Nations was formed and how nations cooperate today."),
        ("Timelines and Historical Eras", "Students learn to place major historical events in order using a timeline."),
    ],
    "Islamic Studies": [
        ("The Six Articles of Faith", "Students learn about the six foundational articles of belief in Islam."),
        ("The Five Pillars of Islam Overview", "Students learn about the five pillars that form the core practices of Islam."),
        ("The Life of Prophet Muhammad (PBUH): Early Years", "Students learn about the early life and character of Prophet Muhammad before his mission."),
        ("The Life of Prophet Muhammad (PBUH): Prophethood", "Students learn about the key events of Prophet Muhammad's mission as a prophet."),
        ("Stories of the Prophets", "Students learn moral lessons from the stories of earlier prophets mentioned in Islamic tradition."),
        ("The Importance of Salah", "Students learn why daily prayer is important and its role in a Muslim's life."),
        ("The Meaning of Zakat", "Students learn how giving to those in need through zakat supports the community."),
        ("The Significance of Ramadan", "Students learn why Muslims fast during Ramadan and the values it teaches."),
        ("The Journey of Hajj", "Students learn about the pilgrimage to Makkah and its spiritual significance."),
        ("The Quran: Revelation and Preservation", "Students learn how the Quran was revealed and carefully preserved over time."),
        ("Respect for Parents in Islam", "Students learn about the emphasis Islam places on honoring and caring for parents."),
        ("Kindness to Neighbors", "Students learn about the value Islam places on being kind and helpful to neighbors."),
        ("Honesty and Trustworthiness", "Students learn why honesty and trustworthiness are highly valued Islamic character traits."),
        ("Patience and Perseverance", "Students learn how patience is taught and valued as an important virtue in Islam."),
        ("Charity and Helping the Poor", "Students learn about the importance of charity and helping those less fortunate."),
        ("The Concept of Ummah", "Students learn about the idea of a global Muslim community bound by shared faith."),
        ("Mosques and Their Role", "Students learn about the purpose of mosques as places of worship and community."),
        ("Islamic Calendar and Important Dates", "Students learn about the lunar Islamic calendar and its significant months."),
        ("Eid al-Fitr Celebrations", "Students learn about the traditions and meaning behind the celebration of Eid al-Fitr."),
        ("Eid al-Adha Celebrations", "Students learn about the traditions and meaning behind the celebration of Eid al-Adha."),
        ("Islamic Contributions to Science", "Students learn about historical Muslim scholars' contributions to science and mathematics."),
        ("Islamic Art and Architecture", "Students learn about the geometric patterns and design found in Islamic art and architecture."),
        ("Caring for the Environment in Islam", "Students learn about the Islamic teaching of responsible stewardship of the earth."),
        ("Justice and Fairness", "Students learn about the importance placed on justice and fair treatment of others."),
        ("Gratitude in Daily Life", "Students learn about the practice of expressing gratitude as part of daily faith."),
        ("Respecting Elders and Teachers", "Students learn why showing respect to elders and teachers is valued in Islamic teaching."),
        ("The Value of Seeking Knowledge", "Students learn about the encouragement in Islam to seek knowledge throughout life."),
        ("Unity and Brotherhood", "Students learn about the emphasis Islam places on unity and treating others as family."),
        ("Good Manners in Daily Life", "Students learn about everyday manners and etiquette encouraged in Islamic teaching."),
    ],
    "Coding": [
        ("Variables and Data Types", "Students learn to create variables and identify basic Python data types like strings and integers."),
        ("Working with Strings", "Students learn to combine, slice, and format text using Python string operations."),
        ("If-Else Conditional Statements", "Students learn to control program flow using if, elif, and else statements."),
        ("Comparison and Logical Operators", "Students learn to use comparison and logical operators to build conditions."),
        ("For Loops and Iteration", "Students learn to use for loops to repeat actions over a range or list."),
        ("While Loops", "Students learn to use while loops to repeat actions until a condition is met."),
        ("Lists: Creating and Modifying", "Students learn to create, access, and modify items in a Python list."),
        ("List Operations: Append, Remove, Sort", "Students learn common list methods for adding, removing, and sorting items."),
        ("Dictionaries: Key-Value Pairs", "Students learn to store and retrieve data using Python dictionaries."),
        ("Writing Functions", "Students learn to define and call functions to organize and reuse code."),
        ("Function Parameters and Return Values", "Students learn how to pass information into functions and return results."),
        ("Debugging Basics", "Students learn strategies for finding and fixing errors in their code."),
        ("Reading Error Messages", "Students learn to read Python error messages to identify what went wrong."),
        ("Comments and Code Readability", "Students learn to write clear comments that explain what their code does."),
        ("Nested Loops", "Students learn to use loops inside other loops to solve more complex problems."),
        ("Boolean Logic in Programs", "Students learn how True and False values control decisions in a program."),
        ("Random Numbers in Python", "Students learn to generate random numbers to add variety to simple programs."),
        ("Turtle Graphics Basics", "Students learn to draw simple shapes and patterns using Python's turtle module."),
        ("Building a Simple Text Game", "Students apply loops and conditionals to build a simple interactive text game."),
        ("Introduction to Algorithms", "Students learn what an algorithm is and how to describe one in plain steps."),
        ("Sequencing and Flowcharts", "Students learn to represent a sequence of steps using a simple flowchart."),
        ("Introduction to Block-Based to Text Coding", "Students learn how block-based coding concepts translate into text-based Python code."),
        ("Working with User Input", "Students learn to collect and use input typed by the user in a Python program."),
        ("Simple Data Validation", "Students learn to check user input for common mistakes before using it in a program."),
        ("Modular Programs with Multiple Functions", "Students learn to break a larger program into smaller, reusable functions."),
        ("Introduction to Version Control Concepts", "Students learn the basic idea of tracking and saving changes to code over time."),
        ("Coding Ethics and Digital Citizenship", "Students learn about responsible and ethical behavior when writing and sharing code."),
        ("Simple Data Structures: Tuples", "Students learn how tuples store fixed collections of related values."),
        ("Planning a Program Before Coding", "Students learn to plan a program's steps and structure before writing any code."),
    ],
    "World Literature": [
        ("Fables of Aesop", "Students learn how Aesop's fables use animal characters to teach moral lessons."),
        ("Folktales from Around the World", "Students learn how folktales from different cultures share similar themes and lessons."),
        ("The Panchatantra Tales", "Students learn about the ancient Indian collection of animal fables and its wisdom."),
        ("Arabian Nights Tales", "Students learn about the framed storytelling tradition found in the Arabian Nights collection."),
        ("Greek Mythology: Gods and Heroes", "Students learn about key figures and stories from ancient Greek mythology."),
        ("Norse Mythology Basics", "Students learn about the major gods and stories from Norse mythology."),
        ("African Oral Storytelling Traditions", "Students learn how oral storytelling has preserved history and values across generations in Africa."),
        ("Native American Legends", "Students learn about the themes and nature connections found in Native American legends."),
        ("Chinese Folktales", "Students learn about common themes and characters found in traditional Chinese folktales."),
        ("Japanese Folktales", "Students learn about common themes and characters found in traditional Japanese folktales."),
        ("The Brothers Grimm Fairy Tales", "Students learn about the collection and style of fairy tales gathered by the Brothers Grimm."),
        ("Hans Christian Andersen's Stories", "Students learn about the themes found in Hans Christian Andersen's classic fairy tales."),
        ("Classic Adventure Novels", "Students learn about the features that make a story an adventure novel, such as journeys and challenges."),
        ("Introduction to Shakespeare's Stories", "Students learn about the basic plots and themes of a few well-known Shakespeare stories."),
        ("Mark Twain and American Storytelling", "Students learn about Mark Twain's style and his contribution to American literature."),
        ("Latin American Folktales", "Students learn about common themes found in folktales from Latin American cultures."),
        ("Middle Eastern Storytelling Traditions", "Students learn about the rich tradition of storytelling found across the Middle East."),
        ("Poetry from Different Cultures", "Students learn how poets from different cultures use imagery to express shared feelings."),
        ("Haiku and Japanese Poetry Forms", "Students learn about the structure and nature focus of haiku poetry."),
        ("Fables with Animal Characters", "Students learn how different cultures use animal characters to represent human traits."),
        ("Epic Tales and Legendary Heroes", "Students learn about the common features of epic tales and their larger-than-life heroes."),
        ("Comparing Cinderella Stories Worldwide", "Students learn how similar tale types appear with variations across many cultures."),
        ("Trickster Characters in World Folklore", "Students learn about the clever trickster character found in folklore from many cultures."),
        ("Creation Myths from Different Cultures", "Students learn how different cultures explain the origins of the world through myths."),
        ("Introduction to Graphic Novels", "Students learn how graphic novels combine images and text to tell a story."),
        ("Historical Fiction as a Genre", "Students learn how historical fiction blends real events with imagined characters."),
        ("Biography and Autobiography", "Students learn the difference between a biography and an autobiography as literary genres."),
        ("Translated Literature and Its Value", "Students learn why translated books allow readers to experience stories from other languages."),
        ("Comparing Book and Film Adaptations", "Students learn to compare how a story changes when adapted from a book to a film."),
    ],
    "Art": [
        ("Color Theory: Warm and Cool Colors", "Students learn to identify warm and cool colors and their emotional effects."),
        ("Complementary and Analogous Colors", "Students learn to identify complementary and analogous colors on the color wheel."),
        ("Shading and Value", "Students learn to use shading techniques to show light and value in a drawing."),
        ("Texture in Art", "Students learn to create the appearance of texture using different drawing techniques."),
        ("Line, Shape, and Form", "Students learn how line, shape, and form work together as basic elements of art."),
        ("Positive and Negative Space", "Students learn to recognize and use positive and negative space in a composition."),
        ("Introduction to Watercolor Painting", "Students learn basic watercolor techniques such as wet-on-wet and layering."),
        ("Introduction to Sculpture", "Students learn how sculptors create three-dimensional art using different materials."),
        ("Printmaking Basics", "Students learn the basic process of creating a simple print from a carved or stamped design."),
        ("Collage as an Art Form", "Students learn to create a collage by arranging and layering different materials."),
        ("Still Life Drawing", "Students learn to observe and draw a still life arrangement of everyday objects."),
        ("Landscape Art", "Students learn techniques for creating a landscape drawing or painting with depth."),
        ("Portrait Basics: Proportions of the Face", "Students learn the basic proportions used to draw a human face."),
        ("Art of Ancient Egypt", "Students learn about the style and symbolism found in ancient Egyptian art."),
        ("Art of the Renaissance", "Students learn about the techniques and famous artists of the Renaissance period."),
        ("Introduction to Impressionism", "Students learn about the loose brushwork and light-focused style of Impressionist art."),
        ("Abstract Art Basics", "Students learn how abstract art uses shape and color rather than realistic depiction."),
        ("Folk Art Traditions", "Students learn about folk art traditions and how they reflect community culture."),
        ("Ceramics and Pottery Basics", "Students learn the basic process of shaping and decorating clay pottery."),
        ("Mosaic Art", "Students learn how small pieces of material are arranged to form a mosaic image."),
        ("Cartooning and Comic Art", "Students learn basic techniques for drawing simple cartoon characters and comic panels."),
        ("Digital Art Basics", "Students learn the basic tools and concepts used to create art on a digital device."),
        ("Art Criticism: Describing and Interpreting Art", "Students learn a simple process for describing and interpreting a work of art."),
        ("Symbolism in Art", "Students learn how artists use symbols to represent ideas beyond the literal image."),
        ("Architecture as Art", "Students learn how buildings can be studied and appreciated as a form of art."),
        ("Art from Different Cultures", "Students learn to compare artistic styles and materials used across different cultures."),
        ("Creating a Self-Portrait", "Students learn to observe their own features and create a self-portrait drawing."),
        ("Introduction to Perspective Drawing", "Students learn to use a single vanishing point to create the illusion of depth."),
        ("Planning and Sketching an Art Project", "Students learn to plan and sketch ideas before creating a finished art piece."),
    ],
    "Music": [
        ("Reading Rhythm Notation", "Students learn to read and clap basic rhythm notation including quarter and eighth notes."),
        ("The Musical Staff and Note Names", "Students learn to identify notes on the treble clef staff by letter name."),
        ("Time Signatures Basics", "Students learn what a time signature tells performers about counting beats in a measure."),
        ("Melody and Pitch", "Students learn how melody is formed from a sequence of pitches moving up and down."),
        ("Introduction to Scales", "Students learn how a major scale is built from a pattern of whole and half steps."),
        ("Major and Minor Keys", "Students learn to hear and describe the difference between major and minor key sounds."),
        ("Musical Dynamics", "Students learn how dynamic markings show performers how loud or soft to play."),
        ("Tempo and Musical Terms", "Students learn common tempo terms and how they describe the speed of music."),
        ("Instrument Families", "Students learn to classify instruments into string, woodwind, brass, and percussion families."),
        ("The Orchestra and Its Layout", "Students learn how instrument families are arranged and function within an orchestra."),
        ("Introduction to Reading Sheet Music", "Students learn to follow simple sheet music while singing or playing an instrument."),
        ("Call and Response in Music", "Students learn about the call-and-response pattern found in many musical traditions."),
        ("Music from Around the World", "Students learn about distinctive musical instruments and styles from different cultures."),
        ("Folk Music Traditions", "Students learn how folk music reflects the history and culture of a community."),
        ("Introduction to Jazz", "Students learn about the origins and improvisational style of jazz music."),
        ("Introduction to Classical Music Periods", "Students learn to distinguish between major periods of classical music history."),
        ("Percussion Instruments and Rhythm Patterns", "Students learn to play simple rhythm patterns on classroom percussion instruments."),
        ("Singing in Rounds and Harmony", "Students learn to sing simple rounds and layered harmony parts as a group."),
        ("Composing a Simple Melody", "Students learn to compose a short original melody using a limited set of notes."),
        ("Music and Emotion", "Students learn how elements of music can be used to express different emotions."),
        ("Introduction to Music Technology", "Students learn how basic digital tools can be used to record or create music."),
        ("The Recorder: Basic Fingerings", "Students learn to play a few basic notes on the recorder using correct fingering."),
        ("Ukulele Basics", "Students learn to hold the ukulele correctly and play a few simple beginner chords."),
        ("Body Percussion and Rhythm Games", "Students learn to create rhythm patterns using clapping, stomping, and body percussion."),
        ("Musical Form: Verse and Chorus", "Students learn to identify verse and chorus sections in a familiar song."),
        ("Listening Analysis: Identifying Instruments", "Students learn to identify which instruments are playing while listening to a piece of music."),
        ("Music Notation Symbols", "Students learn to recognize common musical symbols such as rests, ties, and repeat signs."),
        ("The Role of a Conductor", "Students learn how a conductor helps guide the tempo and expression of a musical group."),
        ("Preparing for a Music Performance", "Students learn the steps involved in rehearsing and preparing for a music performance."),
    ],
    "Survival Skills": [
        ("Building a Basic Emergency Kit", "Students learn what essential items belong in a family emergency preparedness kit."),
        ("Reading a Compass", "Students learn to use a compass to determine and follow a direction."),
        ("Basic Map Reading for Navigation", "Students learn to read a simple trail map to find their way outdoors."),
        ("Recognizing Severe Weather Warnings", "Students learn to recognize signs of severe weather and appropriate safety responses."),
        ("Earthquake Safety", "Students learn the drop, cover, and hold on response for earthquake safety."),
        ("Fire Safety and Escape Planning", "Students learn how to plan and practice a home fire escape route."),
        ("Basic First Aid for Cuts and Scrapes", "Students learn the basic steps for cleaning and dressing a minor cut or scrape."),
        ("Recognizing and Treating Minor Burns", "Students learn how to safely cool and care for a minor burn."),
        ("How to Call for Emergency Help", "Students learn what information to provide when calling for emergency assistance."),
        ("Basic Knot Tying", "Students learn to tie a few simple, useful knots for outdoor activities."),
        ("Finding and Purifying Water Outdoors", "Students learn basic methods for finding and making outdoor water safer to drink."),
        ("Building a Simple Shelter", "Students learn the basics of building a simple emergency shelter outdoors."),
        ("Fire Safety: Starting and Extinguishing a Campfire Safely", "Students learn safe practices for starting and fully extinguishing a campfire."),
        ("Identifying Poisonous Plants", "Students learn to recognize common poisonous plants to avoid touching or eating."),
        ("Basic Wilderness Signaling", "Students learn simple ways to signal for help if lost outdoors."),
        ("Staying Calm and Thinking Clearly in an Emergency", "Students learn strategies for staying calm and making good decisions during an emergency."),
        ("Road and Traffic Safety", "Students learn safe practices for crossing streets and being visible near traffic."),
        ("Bicycle Safety", "Students learn safe riding practices and the importance of wearing a helmet."),
        ("Stranger Safety and Trusted Adults", "Students learn how to recognize unsafe situations and identify trusted adults to turn to."),
        ("Internet and Online Safety", "Students learn basic practices for staying safe while using the internet."),
        ("Severe Cold and Frostbite Prevention", "Students learn how to recognize and prevent frostbite in cold weather."),
        ("Heat Safety and Preventing Heat Exhaustion", "Students learn how to recognize and prevent heat-related illness in hot weather."),
        ("Basic Choking Response Awareness", "Students learn to recognize signs of choking and know when to get adult help."),
        ("Emergency Communication Plans", "Students learn why families create a plan for reconnecting during an emergency."),
        ("Flood Safety Basics", "Students learn basic safety practices to follow during a flood warning."),
        ("Animal Encounter Safety", "Students learn safe behaviors to use when encountering unfamiliar animals outdoors."),
        ("Basic Outdoor Navigation Without a Compass", "Students learn simple methods for estimating direction using the sun or stars."),
        ("Preparing a Family Emergency Plan", "Students learn the key elements that go into a family's emergency preparedness plan."),
        ("Basic Search and Rescue Awareness", "Students learn what to do and what not to do if they become lost outdoors."),
    ],
    "General Knowledge": [
        ("Wonders of the Ancient World", "Students learn about the seven wonders of the ancient world and their significance."),
        ("Modern Wonders of the World", "Students learn about notable modern structures recognized for their engineering achievement."),
        ("Major World Rivers", "Students learn about the world's longest rivers and the regions they flow through."),
        ("Major World Mountain Peaks", "Students learn about the world's tallest mountain peaks and their locations."),
        ("Flags of the World", "Students learn to recognize flags from a variety of countries and their basic symbolism."),
        ("Currencies of the World", "Students learn about different currencies used by countries around the world."),
        ("National Symbols and Anthems", "Students learn about the purpose of national symbols such as anthems and emblems."),
        ("Inventions That Changed the World", "Students learn about key inventions that had a major impact on daily life."),
        ("Scientists Who Changed History", "Students learn about scientists whose discoveries greatly changed our understanding of the world."),
        ("Explorers and Their Discoveries", "Students learn about historical explorers and the journeys they are known for."),
        ("Famous Landmarks Around the World", "Students learn about well-known landmarks and the countries where they are located."),
        ("International Organizations", "Students learn about the basic purpose of major international organizations."),
        ("The Olympic Games: History and Values", "Students learn about the history and values behind the modern Olympic Games."),
        ("World Records and Achievements", "Students learn about notable human achievements recognized as world records."),
        ("Endangered Animals and Conservation", "Students learn about animals at risk of extinction and efforts to protect them."),
        ("Space Exploration Milestones", "Students learn about key milestones in the history of human space exploration."),
        ("Major World Religions Overview", "Students learn basic facts about several of the world's major religions."),
        ("Traditional Foods Around the World", "Students learn about traditional foods associated with different countries and cultures."),
        ("World Languages and Language Families", "Students learn how languages are grouped into families based on shared origins."),
        ("Global Time and Calendar Systems", "Students learn how different cultures have developed their own calendar systems."),
        ("Famous Inventors and Their Inventions", "Students learn about inventors and the specific inventions they are known for."),
        ("World Capitals Quiz Review", "Students review and practice matching countries with their capital cities."),
        ("International Sports and Games", "Students learn about popular sports and games played in different countries."),
        ("Historic Trade Goods", "Students learn about goods that were historically valuable in international trade."),
        ("Famous Bridges and Engineering Feats", "Students learn about notable bridges and the engineering challenges they solved."),
        ("Global Holidays and Observances", "Students learn about notable holidays and observances celebrated around the world."),
        ("Maps and Geography Trivia", "Students practice applying geography knowledge through map-based trivia questions."),
        ("Notable Museums Around the World", "Students learn about well-known museums and the collections they are famous for."),
        ("Current Events for Kids", "Students learn strategies for following age-appropriate current events responsibly."),
    ],
    "Cooking": [
        ("Kitchen Safety Basics", "Students learn essential safety rules for working in a kitchen with adult supervision."),
        ("Reading a Recipe", "Students learn to read and follow the steps and measurements in a written recipe."),
        ("Measuring Ingredients Accurately", "Students learn to accurately measure liquid and dry ingredients using proper tools."),
        ("Food Groups and MyPlate", "Students learn how the MyPlate model helps balance food groups in a meal."),
        ("Basic Knife Skills for Kids", "Students learn safe, age-appropriate knife handling techniques under supervision."),
        ("Preparing a Simple Salad", "Students learn to wash, prepare, and combine ingredients to make a fresh salad."),
        ("Basic Baking Techniques", "Students learn fundamental baking techniques such as mixing and measuring for baked goods."),
        ("Understanding Food Labels", "Students learn to read and interpret basic information on a food nutrition label."),
        ("Food Safety and Cross-Contamination", "Students learn how to prevent cross-contamination when handling different foods."),
        ("Proper Food Storage", "Students learn safe practices for storing perishable and non-perishable foods."),
        ("Cooking Methods: Boiling, Steaming, Sauteing", "Students learn to distinguish between common moist and dry cooking methods."),
        ("Following Multi-Step Recipes", "Students practice following a recipe with several sequential preparation steps."),
        ("Basic Meal Planning", "Students learn to plan a simple, balanced meal ahead of time."),
        ("Cultural Cuisines Around the World", "Students learn about signature dishes and ingredients from different world cuisines."),
        ("Herbs and Spices Basics", "Students learn to identify common herbs and spices and how they flavor food."),
        ("Breakfast Foods and Nutrition", "Students learn about nutritious breakfast options and why breakfast matters."),
        ("Preparing Simple Snacks", "Students learn to prepare simple, healthy snacks using basic kitchen skills."),
        ("Understanding Portion Sizes", "Students learn to recognize appropriate portion sizes for different types of food."),
        ("Baking Bread Basics", "Students learn the basic ingredients and process involved in baking simple bread."),
        ("Food Allergies and Substitutions", "Students learn about common food allergies and simple ingredient substitutions."),
        ("Setting a Table and Meal Etiquette", "Students learn basic table setting and polite mealtime etiquette."),
        ("Reducing Food Waste", "Students learn practical ways to reduce food waste at home."),
        ("Basic Egg Cookery", "Students learn a few simple, safe methods for cooking eggs."),
        ("Vegetarian and Plant-Based Meals", "Students learn about the basics of preparing balanced vegetarian meals."),
        ("Seasonal and Local Foods", "Students learn the benefits of choosing seasonal and locally grown foods."),
        ("Basic Dessert Preparation", "Students learn to prepare a simple, kid-friendly dessert recipe."),
        ("Cooking Tools and Their Uses", "Students learn to identify common kitchen tools and their proper uses."),
        ("Hosting a Simple Meal for Family", "Students learn the steps involved in planning and serving a simple meal for others."),
        ("Following Kitchen Cleanup Routines", "Students learn proper cleanup routines to keep a kitchen safe and tidy after cooking."),
    ],
    "Foreign Languages": [
        ("Spanish: Greetings and Introductions", "Students learn to greet others and introduce themselves in basic Spanish."),
        ("Spanish: Numbers and Counting", "Students learn to count and use numbers in everyday Spanish phrases."),
        ("Spanish: Family Vocabulary", "Students learn vocabulary for describing family members in Spanish."),
        ("French: Greetings and Introductions", "Students learn to greet others and introduce themselves in basic French."),
        ("French: Colors and Descriptions", "Students learn to describe objects using colors and simple adjectives in French."),
        ("French: Days, Months, and Weather", "Students learn vocabulary for days, months, and weather in French."),
        ("Mandarin: Basic Greetings", "Students learn basic greetings and polite expressions in Mandarin Chinese."),
        ("Mandarin: Numbers and Counting", "Students learn to count using numbers in Mandarin Chinese."),
        ("German: Greetings and Introductions", "Students learn to greet others and introduce themselves in basic German."),
        ("German: Classroom Vocabulary", "Students learn common classroom object and action vocabulary in German."),
        ("Arabic: Numbers and Counting", "Students learn to count and use numbers in Arabic."),
        ("Arabic: Family Vocabulary", "Students learn vocabulary for describing family members in Arabic."),
        ("Arabic: Colors and Descriptions", "Students learn to describe objects using colors in Arabic."),
        ("Japanese: Greetings and Introductions", "Students learn to greet others and introduce themselves in basic Japanese."),
        ("Japanese: Hiragana Basics", "Students learn to recognize and write a first set of hiragana characters."),
        ("Urdu: Greetings and Introductions", "Students learn to greet others and introduce themselves in basic Urdu."),
        ("Bengali: Greetings and Introductions", "Students learn to greet others and introduce themselves in basic Bengali."),
        ("Swahili: Greetings and Introductions", "Students learn to greet others and introduce themselves in basic Swahili."),
        ("Hindi: Numbers and Counting", "Students learn to count and use numbers in Hindi."),
        ("Hindi: Family Vocabulary", "Students learn vocabulary for describing family members in Hindi."),
        ("Spanish: Weather and Seasons", "Students learn vocabulary for describing weather and seasons in Spanish."),
        ("Spanish: Common Verbs and Actions", "Students learn a set of common action verbs used in everyday Spanish sentences."),
        ("French: Food and Mealtime Vocabulary", "Students learn vocabulary for common foods and mealtime phrases in French."),
        ("German: Numbers and Counting", "Students learn to count and use numbers in German."),
        ("Comparing Grammar Across Languages", "Students learn to compare simple grammar rules, such as word order, across different languages."),
        ("Cognates: Words That Look Alike", "Students learn to recognize cognates, words that look similar and share meaning across languages."),
        ("Common Idioms in Other Languages", "Students learn a few common idiomatic expressions and their meanings in other languages."),
        ("Basic Travel Phrases", "Students learn useful basic phrases for travel, such as asking for directions."),
        ("Language Families of the World", "Students learn how many of the world's languages are grouped into related families."),
    ],
    "Social Studies": [
        ("Branches of Government", "Students learn about the roles of the legislative, executive, and judicial branches."),
        ("Rights and Responsibilities of Citizens", "Students learn about the basic rights and responsibilities that come with citizenship."),
        ("How Laws Are Made", "Students learn the basic process by which a proposed law becomes an official law."),
        ("Local, State, and National Government", "Students learn to distinguish the roles of local, state, and national levels of government."),
        ("Voting and Elections", "Students learn why voting matters and the basic process of holding an election."),
        ("Community Helpers and Public Services", "Students learn about the roles of community helpers who provide public services."),
        ("Supply and Demand Basics", "Students learn how supply and demand influence the price of goods."),
        ("Producers and Consumers", "Students learn the roles producers and consumers play in an economy."),
        ("Goods and Services", "Students learn to distinguish between goods and services in an economy."),
        ("Needs vs. Wants", "Students learn to distinguish between needs and wants when making spending decisions."),
        ("Introduction to Taxes", "Students learn the basic idea of taxes and how they help fund public services."),
        ("Global Trade and Interdependence", "Students learn how countries depend on each other through the trade of goods and services."),
        ("Cultural Diversity and Respect", "Students learn to appreciate and respect cultural diversity within communities."),
        ("Immigration and Its Impact", "Students learn how immigration has shaped communities and countries over time."),
        ("Human Rights Basics", "Students learn about basic human rights recognized around the world."),
        ("Conflict Resolution Skills", "Students learn peaceful strategies for resolving disagreements with others."),
        ("Community Organizations and Nonprofits", "Students learn about the role nonprofit organizations play in helping communities."),
        ("Historical Figures Who Advanced Civil Rights", "Students learn about individuals who worked to advance civil rights and equality."),
        ("Comparing Forms of Government", "Students learn to compare democracy with other basic forms of government."),
        ("Symbols of National Identity", "Students learn about symbols such as flags and monuments that represent national identity."),
        ("The Role of the Media", "Students learn about the role media plays in informing the public."),
        ("Understanding Bias in Information", "Students learn basic strategies for recognizing bias in the information they encounter."),
        ("Economic Systems Overview", "Students learn about the basic differences between market and planned economic systems."),
        ("Urban, Suburban, and Rural Communities", "Students learn to compare the features of urban, suburban, and rural communities."),
        ("Historical Timelines and Change Over Time", "Students learn to use timelines to understand how communities change over time."),
        ("Civic Participation and Volunteering", "Students learn how volunteering is a way for citizens to participate in their community."),
        ("Global Citizenship", "Students learn what it means to act responsibly as a member of a global community."),
        ("Comparing Cultures' Traditions", "Students learn to respectfully compare traditions and celebrations across different cultures."),
        ("Map of the World's Regions", "Students learn to identify major world regions used to organize the study of social studies."),
    ],
    "Physical Education & Self-Defense": [
        ("Warming Up and Cooling Down", "Students learn why warming up and cooling down are important parts of exercise."),
        ("Cardiovascular Endurance Basics", "Students learn activities that build cardiovascular endurance over time."),
        ("Muscular Strength and Endurance", "Students learn simple bodyweight exercises that build muscular strength."),
        ("Flexibility and Stretching", "Students learn safe stretching techniques that improve flexibility."),
        ("Sportsmanship and Fair Play", "Students learn the importance of good sportsmanship during games and competition."),
        ("Basic Soccer Skills", "Students learn fundamental soccer skills such as dribbling and passing."),
        ("Basic Basketball Skills", "Students learn fundamental basketball skills such as dribbling and shooting."),
        ("Basic Volleyball Skills", "Students learn fundamental volleyball skills such as bumping and serving."),
        ("Basic Track and Field Skills", "Students learn fundamental running, jumping, and throwing track and field skills."),
        ("Rules of Team Sports", "Students learn the basic rules of several common team sports."),
        ("Balance and Coordination Games", "Students practice activities that build balance and body coordination."),
        ("Jump Rope Skills", "Students learn a variety of jump rope skills and techniques."),
        ("Introduction to Yoga for Kids", "Students learn simple yoga poses and breathing exercises appropriate for children."),
        ("Basic Self-Defense Stances", "Students learn a safe, basic ready stance used in beginner self-defense training."),
        ("Situational Awareness", "Students learn the basics of staying aware of their surroundings for personal safety."),
        ("Avoiding and De-escalating Conflict", "Students learn strategies to avoid and calmly de-escalate a physical confrontation."),
        ("Basic Blocking Techniques", "Students learn simple, safe blocking techniques used in beginner self-defense."),
        ("Setting Personal Fitness Goals", "Students learn to set simple, achievable personal fitness goals."),
        ("Understanding Heart Rate and Exercise", "Students learn how exercise intensity affects heart rate."),
        ("Injury Prevention Basics", "Students learn basic practices that help prevent common exercise injuries."),
        ("Cooperative Games and Teamwork", "Students learn cooperative games that build teamwork and communication skills."),
        ("Introduction to Swimming Strokes", "Students learn the basic form of common swimming strokes."),
        ("Dance and Movement Basics", "Students learn simple choreographed movement sequences set to music."),
        ("Body Awareness in Sport", "Students learn to recognize how their body moves and responds during physical activity."),
        ("Setting Boundaries and Saying No", "Students learn the importance of setting personal boundaries and confidently saying no."),
        ("Introduction to Martial Arts Discipline", "Students learn about the discipline, respect, and focus taught in martial arts training."),
        ("Playground and Recess Safety", "Students learn safe practices for playing on playground equipment and during recess."),
        ("Building Endurance Through Interval Activities", "Students learn how alternating activity and rest builds physical endurance."),
        ("Goal-Setting for Team Success", "Students learn how a team can set and work toward a shared performance goal."),
    ],
    "Health Education": [
        ("Understanding Emotions and Feelings", "Students learn to identify and name a wide range of emotions they experience."),
        ("Coping Strategies for Stress", "Students learn healthy strategies for coping with everyday stress."),
        ("The Importance of Physical Activity", "Students learn how regular physical activity supports overall health."),
        ("Understanding Food Nutrients", "Students learn about the major nutrients the body needs and why each matters."),
        ("Hydration and the Body", "Students learn why drinking enough water is important for the body to function well."),
        ("Personal Hygiene Habits", "Students learn daily hygiene habits that help keep the body healthy."),
        ("Understanding Germs and Illness Prevention", "Students learn how germs spread and simple habits that help prevent illness."),
        ("Recognizing Trusted Adults for Health Concerns", "Students learn to identify trusted adults they can talk to about health concerns."),
        ("Media Influence on Body Image", "Students learn how media messages can influence how people feel about their bodies."),
        ("Healthy Friendships", "Students learn the qualities that make a friendship healthy and supportive."),
        ("Recognizing Bullying and How to Respond", "Students learn to recognize bullying behavior and safe ways to respond."),
        ("Understanding Peer Pressure", "Students learn strategies for recognizing and responding to peer pressure."),
        ("Basics of Mental Health", "Students learn that mental health is an important part of overall health."),
        ("Sleep Hygiene Habits", "Students learn habits that support healthy, restful sleep."),
        ("Understanding Medicines and Safety", "Students learn basic safety rules around medicines, including only taking them from trusted adults."),
        ("First Steps in Managing Emotions", "Students learn simple techniques for calming down when experiencing strong emotions."),
        ("The Endocrine System Basics", "Students learn a simple overview of how hormones help regulate body processes."),
        ("Healthy Screen Time Habits", "Students learn about setting healthy limits and habits around screen time."),
        ("Understanding Consent and Personal Space", "Students learn age-appropriate concepts of personal space and respecting others' boundaries."),
        ("Recognizing Reliable Health Information", "Students learn to identify reliable sources of basic health information."),
        ("Preventing the Spread of Illness", "Students learn practices such as handwashing that help prevent the spread of illness."),
        ("Understanding Allergies", "Students learn what allergies are and basic ways people manage them."),
        ("Building Self-Confidence", "Students learn strategies for building healthy self-confidence and self-worth."),
        ("Setting Healthy Personal Goals", "Students learn to set simple, achievable personal health and wellness goals."),
    ],
    "ICT & Computer Science": [
        ("Computer Hardware Basics", "Students learn to identify basic computer hardware components and their functions."),
        ("Understanding the Internet", "Students learn a simple explanation of how the internet connects computers worldwide."),
        ("Digital Citizenship Basics", "Students learn responsible and respectful behavior when using digital devices."),
        ("Online Privacy and Personal Information", "Students learn why it is important to protect personal information online."),
        ("Recognizing Reliable Websites", "Students learn strategies for judging whether a website is a reliable source."),
        ("Introduction to Word Processing", "Students learn to create and format a simple document using word processing software."),
        ("Introduction to Spreadsheets", "Students learn to enter and organize simple data using spreadsheet software."),
        ("Introduction to Presentation Software", "Students learn to create a simple slideshow presentation with text and images."),
        ("Keyboarding Skills", "Students practice proper finger placement and technique for typing efficiently."),
        ("File Organization and Folders", "Students learn to organize digital files into folders in a logical way."),
        ("Introduction to Databases", "Students learn the basic idea of how a database organizes and stores information."),
        ("Python: Variables and Input", "Students learn to create variables and collect simple input from a user in Python."),
        ("Python: If Statements", "Students learn to use if statements to make simple decisions in a Python program."),
        ("Python: Loops", "Students learn to use loops to repeat actions in a Python program."),
        ("Python: Lists", "Students learn to store and work with a collection of items using Python lists."),
        ("Python: Functions", "Students learn to define simple functions to organize and reuse Python code."),
        ("Introduction to Binary Numbers", "Students learn the basic idea of how computers represent numbers using binary code."),
        ("How Search Engines Work", "Students learn a simple explanation of how search engines find and rank web results."),
        ("Introduction to Robotics Concepts", "Students learn basic concepts behind how simple robots sense and respond to their environment."),
        ("Introduction to Algorithms and Flowcharts", "Students learn to represent a simple algorithm using a flowchart."),
        ("Cyberbullying Awareness", "Students learn to recognize cyberbullying and how to respond safely."),
        ("Password Safety", "Students learn how to create and protect strong, secure passwords."),
        ("Introduction to Computer Networks", "Students learn a simple explanation of how devices connect together in a network."),
        ("Basics of Coding Logic", "Students learn how sequencing, selection, and repetition form the logic of a program."),
        ("Introduction to Artificial Intelligence Concepts", "Students learn a simple, age-appropriate explanation of what artificial intelligence is."),
        ("Digital Footprint Awareness", "Students learn how their online actions can leave a lasting digital footprint."),
        ("Introduction to Web Pages", "Students learn the basic idea of how a simple web page is structured with text and images."),
        ("Copyright and Fair Use Basics", "Students learn a simple introduction to copyright and giving credit for others' work."),
        ("Troubleshooting Common Tech Problems", "Students learn simple steps for troubleshooting common technology problems."),
    ],
}
