"""Grade 6 (ages 10-11) syllabus expansion topics.

Provides (title, summary) tuples for each subject. A separate merge script
(merge_grade_topics_expansion.py) reads MODULES and builds full lesson
objects. Do not duplicate titles already present in syllabus/grade6.json.
"""

GRADE = 6

MODULES: dict[str, list[tuple[str, str]]] = {
    "Math": [
        ("Fractions and Mixed Numbers", "Students learn to represent, compare, and convert between fractions and mixed numbers."),
        ("Adding and Subtracting Fractions", "Students learn to add and subtract fractions with like and unlike denominators."),
        ("Multiplying and Dividing Fractions", "Students learn strategies for multiplying and dividing fractions and mixed numbers."),
        ("Decimals and Place Value", "Students explore place value in decimal numbers up to the thousandths."),
        ("Operations with Decimals", "Students practice adding, subtracting, multiplying, and dividing decimal numbers."),
        ("Ratios and Proportional Relationships", "Students learn to express and compare ratios between two quantities."),
        ("Rates and Unit Rates", "Students learn to calculate and compare unit rates in real-world situations."),
        ("Percentages and Percent Problems", "Students learn to calculate percentages and solve percent-based word problems."),
        ("Converting Between Fractions, Decimals, and Percentages", "Students practice converting numbers fluently between fraction, decimal, and percentage forms."),
        ("Factors, Multiples, and Prime Numbers", "Students learn to identify factors, multiples, and prime numbers."),
        ("Greatest Common Factor and Least Common Multiple", "Students learn to find the GCF and LCM of two or more numbers."),
        ("Order of Operations", "Students learn to correctly apply the order of operations in multi-step expressions."),
        ("Exponents and Powers", "Students learn to read, write, and evaluate expressions with exponents."),
        ("Area of Polygons", "Students learn to calculate the area of triangles, parallelograms, and other polygons."),
        ("Surface Area of 3D Shapes", "Students learn to calculate the surface area of prisms and pyramids."),
        ("Volume of Rectangular Prisms", "Students learn to calculate the volume of rectangular prisms using formulas."),
        ("Perimeter and Circumference", "Students learn to calculate the perimeter of polygons and the circumference of circles."),
        ("Angles and Angle Relationships", "Students learn to identify and measure complementary, supplementary, and vertical angles."),
        ("Classifying Triangles and Quadrilaterals", "Students learn to classify triangles and quadrilaterals by their sides and angles."),
        ("Symmetry and Tessellations", "Students explore line and rotational symmetry and how shapes tile a plane."),
        ("Data Collection and Frequency Tables", "Students learn to collect data and organize it into frequency tables."),
        ("Mean, Median, Mode, and Range", "Students learn to calculate and interpret measures of center and spread."),
        ("Bar Graphs, Line Graphs, and Pie Charts", "Students learn to create and interpret different types of graphs."),
        ("Probability Basics", "Students learn to calculate simple probabilities of everyday events."),
        ("Integers and Absolute Value", "Students learn to compare, order, and find the absolute value of integers."),
        ("Solving One-Step Equations", "Students learn to solve simple algebraic equations using inverse operations."),
        ("Inequalities on a Number Line", "Students learn to represent and solve simple inequalities on a number line."),
    ],
    "English": [
        ("Narrative Writing and Story Structure", "Students learn to write narratives with a clear beginning, middle, and end."),
        ("Descriptive Writing and Sensory Detail", "Students learn to use sensory details to bring descriptive writing to life."),
        ("Expository Writing and Informational Text", "Students learn to write clear, well-organized informational texts."),
        ("Parts of Speech Review", "Students review nouns, verbs, adjectives, adverbs, and other parts of speech."),
        ("Sentence Types and Structure", "Students learn to build simple, compound, and complex sentences."),
        ("Subject-Verb Agreement", "Students practice matching subjects and verbs correctly in their writing."),
        ("Commas and Punctuation Rules", "Students learn key rules for using commas and other punctuation marks."),
        ("Active and Passive Voice", "Students learn to recognize and use active and passive voice in sentences."),
        ("Figurative Language: Metaphor and Simile", "Students learn to identify and use metaphors and similes in writing."),
        ("Idioms and Figures of Speech", "Students learn the meaning and use of common idioms and figures of speech."),
        ("Theme and Central Idea", "Students learn to identify the theme or central idea of a text."),
        ("Character Development and Analysis", "Students learn to analyze how characters change and develop in a story."),
        ("Plot Structure and Conflict", "Students learn to identify the elements of plot, including rising action and conflict."),
        ("Point of View in Fiction", "Students learn to identify first-person, second-person, and third-person narration."),
        ("Poetry Forms and Devices", "Students explore different poetry forms and devices such as rhyme and rhythm."),
        ("Reading Nonfiction: Text Features", "Students learn to use headings, captions, and other text features to understand nonfiction."),
        ("Summarizing and Paraphrasing", "Students learn to summarize and paraphrase texts in their own words."),
        ("Making Inferences While Reading", "Students learn to make logical inferences based on evidence from a text."),
        ("Compare and Contrast Texts", "Students learn to compare and contrast ideas across two or more texts."),
        ("Research Skills and Note-Taking", "Students learn basic strategies for researching topics and taking organized notes."),
        ("Citing Sources and Avoiding Plagiarism", "Students learn why and how to cite sources properly in their writing."),
        ("The Writing Process: Drafting and Revising", "Students learn to draft, revise, and improve their writing through multiple stages."),
        ("Editing and Proofreading Strategies", "Students learn strategies for editing and proofreading their own writing."),
        ("Vocabulary Building and Context Clues", "Students learn to use context clues to determine the meaning of unfamiliar words."),
        ("Prefixes, Suffixes, and Root Words", "Students learn how prefixes, suffixes, and root words build word meaning."),
        ("Public Speaking and Oral Presentations", "Students practice organizing and delivering a clear oral presentation."),
        ("Listening Skills and Note-Taking", "Students practice active listening and taking notes from spoken information."),
        ("Analyzing Author's Purpose", "Students learn to identify whether an author's purpose is to inform, persuade, or entertain."),
        ("Writing Dialogue", "Students learn to write realistic dialogue with correct punctuation."),
    ],
    "Science": [
        ("The Scientific Method", "Students learn the steps of the scientific method through hands-on inquiry."),
        ("States of Matter", "Students learn the properties of solids, liquids, and gases and how they change."),
        ("Physical and Chemical Changes", "Students learn to distinguish between physical and chemical changes in matter."),
        ("Mixtures and Solutions", "Students learn how mixtures and solutions form and how they can be separated."),
        ("Cells: Structure and Function", "Students learn about the basic structures and functions of plant and animal cells."),
        ("Plant Biology and Photosynthesis", "Students learn how plants make food through photosynthesis."),
        ("Ecosystems and Food Webs", "Students learn how organisms in an ecosystem are connected through food webs."),
        ("Classification of Living Things", "Students learn how scientists classify living things into kingdoms and groups."),
        ("Genetics and Heredity Basics", "Students learn how traits are passed from parents to offspring."),
        ("Forces and Motion", "Students learn about force, motion, and how objects interact."),
        ("Newton's Laws of Motion", "Students learn the basics of Newton's three laws of motion."),
        ("Simple Machines", "Students learn how simple machines make work easier."),
        ("Energy Types and Transformations", "Students learn about different forms of energy and how energy changes form."),
        ("Electricity and Circuits", "Students learn how electric circuits work and how to build simple circuits."),
        ("Magnetism", "Students learn about magnetic fields and how magnets attract and repel."),
        ("Sound and Waves", "Students learn how sound travels as a wave and how pitch and volume change."),
        ("Light and Optics", "Students learn how light travels, reflects, and refracts."),
        ("The Solar System", "Students learn about the sun, planets, and other objects in our solar system."),
        ("Earth's Layers and Plate Tectonics", "Students learn about Earth's internal layers and how tectonic plates move."),
        ("Rocks and the Rock Cycle", "Students learn how igneous, sedimentary, and metamorphic rocks form."),
        ("Weathering and Erosion", "Students learn how weathering and erosion shape Earth's surface over time."),
        ("Weather and Climate", "Students learn the difference between weather and climate and what causes them."),
        ("The Water Cycle", "Students learn how water moves through evaporation, condensation, and precipitation."),
        ("Earthquakes and Volcanoes", "Students learn what causes earthquakes and volcanic eruptions."),
        ("Renewable and Nonrenewable Resources", "Students learn to distinguish between renewable and nonrenewable natural resources."),
        ("Environmental Conservation", "Students learn practical ways to conserve natural resources and protect ecosystems."),
        ("Microorganisms and Disease", "Students learn about microorganisms and how some can cause disease."),
        ("Scientific Measurement and Lab Safety", "Students learn to use measurement tools accurately and follow lab safety rules."),
    ],
    "Geography": [
        ("Maps, Scale, and Legends", "Students learn to read maps using scale, legends, and symbols."),
        ("Latitude and Longitude", "Students learn to locate places using lines of latitude and longitude."),
        ("Continents and Oceans", "Students learn to identify the world's continents and oceans."),
        ("Physical Landforms", "Students learn to identify major landforms such as plains, plateaus, and valleys."),
        ("Rivers and Watersheds", "Students learn how rivers form and how watersheds carry water to the sea."),
        ("Mountains and Mountain Ranges", "Students learn how mountains form and identify major mountain ranges."),
        ("Deserts of the World", "Students learn about the world's major deserts and how life adapts there."),
        ("Climate Zones", "Students learn about the world's major climate zones and their characteristics."),
        ("Population Distribution", "Students learn why populations are distributed unevenly across the globe."),
        ("Migration and Human Movement", "Students learn about reasons people migrate and how it shapes regions."),
        ("Natural Resources and Their Uses", "Students learn how natural resources are used and why they matter to economies."),
        ("Agriculture and Land Use", "Students learn how geography influences farming and land use around the world."),
        ("Countries and Capitals: Africa", "Students learn the countries and capital cities of the African continent."),
        ("Countries and Capitals: Asia", "Students learn the countries and capital cities of the Asian continent."),
        ("Countries and Capitals: Europe", "Students learn the countries and capital cities of the European continent."),
        ("Countries and Capitals: The Americas", "Students learn the countries and capital cities of North and South America."),
        ("Political Boundaries and Borders", "Students learn how political borders are formed and sometimes disputed."),
        ("Time Zones", "Students learn how the world is divided into time zones based on longitude."),
        ("Natural Disasters and Geography", "Students learn how geography influences the risk of natural disasters."),
        ("Trade Routes and Globalization", "Students learn how historic and modern trade routes connect the world."),
        ("Cultural Geography and Diversity", "Students learn how geography shapes cultural traditions and diversity."),
        ("Water Resources and Scarcity", "Students learn about global water resources and the challenge of water scarcity."),
        ("Deforestation and Land Change", "Students learn the causes and effects of deforestation around the world."),
        ("Renewable Energy and Geography", "Students learn how geography affects the availability of renewable energy sources."),
        ("Tourism and Its Impact", "Students learn how tourism affects economies and environments around the world."),
        ("Map Projections", "Students learn how different map projections represent the round Earth on a flat surface."),
        ("GPS and Modern Geographic Tools", "Students learn how GPS and digital tools help people navigate and study geography."),
        ("Coastal Geography and Erosion", "Students learn how coastlines form and change due to erosion and tides."),
    ],
    "World History": [
        ("Early Human Migration and Prehistory", "Students learn how early humans migrated and lived before written history."),
        ("Ancient Mesopotamia", "Students learn about the rise of civilization between the Tigris and Euphrates rivers."),
        ("Ancient Egypt", "Students learn about the civilization, pyramids, and pharaohs of ancient Egypt."),
        ("Ancient Greece and Democracy", "Students learn about ancient Greek city-states and the origins of democracy."),
        ("The Roman Empire", "Students learn about the rise, government, and legacy of the Roman Empire."),
        ("Ancient China and the Silk Road", "Students learn about ancient Chinese dynasties and trade along the Silk Road."),
        ("Ancient India", "Students learn about early civilizations and empires of the Indian subcontinent."),
        ("African Kingdoms: Ghana, Mali, and Songhai", "Students learn about the wealth and influence of West Africa's medieval kingdoms."),
        ("The Maya, Aztec, and Inca Civilizations", "Students learn about the achievements of Mesoamerican and Andean civilizations."),
        ("The Byzantine Empire", "Students learn about the Byzantine Empire as the continuation of Rome in the East."),
        ("The Islamic Golden Age", "Students learn about advances in science, medicine, and learning during the Islamic Golden Age."),
        ("Medieval Europe and Feudalism", "Students learn about the social and political system of feudalism in medieval Europe."),
        ("The Crusades", "Students learn about the causes and effects of the medieval Crusades."),
        ("The Mongol Empire", "Students learn how the Mongol Empire became the largest land empire in history."),
        ("The Renaissance", "Students learn about the rebirth of art, science, and learning in the Renaissance."),
        ("The Age of Exploration", "Students learn about voyages of exploration and their global consequences."),
        ("The Reformation", "Students learn about the religious changes brought by the Protestant Reformation."),
        ("Colonialism and Its Global Impact", "Students learn about European colonialism and its lasting effects worldwide."),
        ("The Scientific Revolution", "Students learn how new scientific methods transformed understanding of the natural world."),
        ("The Enlightenment", "Students learn about Enlightenment ideas of reason, liberty, and government."),
        ("The American Revolution", "Students learn about the causes and outcomes of the American Revolution."),
        ("The French Revolution", "Students learn about the causes and impact of the French Revolution."),
        ("World War II", "Students learn about the causes, key events, and consequences of World War II."),
        ("The Cold War", "Students learn about the political tension between the United States and Soviet Union."),
        ("Decolonization Movements", "Students learn how nations gained independence from colonial rule in the 20th century."),
        ("The Civil Rights Movement", "Students learn about the struggle for racial equality and civil rights."),
        ("The United Nations and International Cooperation", "Students learn how the United Nations promotes peace and cooperation among nations."),
        ("Globalization in the Modern World", "Students learn how globalization connects economies and cultures today."),
    ],
    "Islamic Studies": [
        ("The Life of Prophet Muhammad: Early Years", "Students learn about the early life of Prophet Muhammad in Makkah."),
        ("The Life of Prophet Muhammad: The Call to Prophethood", "Students learn about the beginning of the prophetic mission and early message."),
        ("The Five Pillars of Islam", "Students learn about the five foundational acts of worship in Islam."),
        ("The Shahada and Its Meaning", "Students learn the meaning and significance of the declaration of faith."),
        ("Salah: The Practice of Daily Prayer", "Students learn about the purpose and practice of the five daily prayers."),
        ("Zakat: Charity and Wealth Purification", "Students learn about the obligation of giving charity to purify wealth."),
        ("Sawm: Fasting in Ramadan", "Students learn about the practice and purpose of fasting during Ramadan."),
        ("Hajj: The Pilgrimage to Makkah", "Students learn about the pilgrimage to Makkah and its rituals."),
        ("The Six Articles of Faith", "Students learn the six core beliefs of Islamic faith."),
        ("Belief in Allah and Tawheed", "Students learn about the concept of the oneness of God in Islam."),
        ("The Angels in Islamic Belief", "Students learn about the role of angels in Islamic teaching."),
        ("The Prophets of Islam", "Students learn about the shared line of prophets recognized in Islamic tradition."),
        ("The Holy Books in Islamic Tradition", "Students learn about the scriptures recognized in Islamic belief."),
        ("The Day of Judgment", "Students learn about the Islamic belief in accountability and the afterlife."),
        ("Divine Decree and Free Will", "Students learn how Islamic teaching balances divine decree with human choice."),
        ("Islamic Manners and Character (Akhlaq)", "Students learn about the importance of good character in Islamic teaching."),
        ("Honesty and Trustworthiness in Islam", "Students learn why honesty and trustworthiness are valued in Islamic ethics."),
        ("Kindness to Parents and Family", "Students learn about the emphasis on kindness to parents and family in Islam."),
        ("Respect for Neighbors and Community", "Students learn about Islamic teachings on treating neighbors and community with respect."),
        ("Islamic Etiquette of Greeting and Speech", "Students learn about polite greetings and speech encouraged in Islamic tradition."),
        ("The Mosque and Its Role in Community Life", "Students learn about the mosque as a center of worship and community."),
        ("Major Islamic Festivals: Eid al-Fitr and Eid al-Adha", "Students learn about the celebrations and meaning of the two major Eid festivals."),
        ("The Islamic Calendar", "Students learn how the lunar Islamic calendar works and its important months."),
        ("The Companions of the Prophet", "Students learn about notable companions who supported the early Muslim community."),
        ("Early Islamic History: The Rightly Guided Caliphs", "Students learn about the leadership of the first four caliphs after the Prophet."),
        ("Muslim Contributions to Science and Mathematics", "Students learn about Muslim scholars' contributions to science and mathematics."),
        ("Muslim Contributions to Medicine and Astronomy", "Students learn about Muslim scholars' contributions to medicine and astronomy."),
        ("Islamic Art and Architecture", "Students learn about the geometric patterns and architecture of Islamic art."),
        ("Environmental Stewardship in Islamic Teaching", "Students learn about Islamic teachings on caring for the environment."),
    ],
    "Coding": [
        ("Introduction to Programming Concepts", "Students learn the basic concepts behind how computer programs work."),
        ("Variables and Data Types in Python", "Students learn to create variables and use different data types in Python."),
        ("Python Strings and String Methods", "Students learn to work with text using Python strings and string methods."),
        ("Conditional Statements: If, Elif, Else", "Students learn to make decisions in code using conditional statements."),
        ("Python Functions and Parameters", "Students learn to write reusable functions with parameters in Python."),
        ("Python Dictionaries", "Students learn to store and access data using Python dictionaries."),
        ("Python Tuples and Sets", "Students learn to use tuples and sets to organize collections of data."),
        ("Debugging and Reading Error Messages", "Students learn strategies for finding and fixing errors in their code."),
        ("Input and Output in Python", "Students learn to get input from users and display output in Python."),
        ("Working with the Python Turtle Graphics Module", "Students learn to draw shapes and patterns using Python's turtle graphics."),
        ("Introduction to Algorithms", "Students learn what an algorithm is and how to design step-by-step solutions."),
        ("Flowcharts and Pseudocode", "Students learn to plan programs using flowcharts and pseudocode."),
        ("Sorting Algorithms: Bubble Sort Basics", "Students learn how the bubble sort algorithm orders a list of items."),
        ("Searching Algorithms: Linear Search", "Students learn how a linear search finds an item in a list."),
        ("Introduction to Scratch and Block Coding", "Students learn programming concepts using visual block-based coding."),
        ("Event-Driven Programming Basics", "Students learn how programs respond to events like clicks and key presses."),
        ("Building Simple Games with Code", "Students apply coding concepts to build a simple interactive game."),
        ("Introduction to HTML", "Students learn to structure a simple web page using HTML."),
        ("Introduction to CSS", "Students learn to style a web page's appearance using CSS."),
        ("What is the Internet? Basics of Networking", "Students learn the basics of how computers communicate over the internet."),
        ("Binary Numbers and How Computers Count", "Students learn how computers represent numbers using binary code."),
        ("Introduction to Robotics and Sensors", "Students learn how robots use sensors and code to interact with their environment."),
        ("Version Control Basics", "Students learn why programmers track and save changes to their code."),
        ("Python Comments and Code Readability", "Students learn to write clear comments that make code easier to understand."),
        ("Nested Loops and Iteration", "Students learn to use loops inside loops to solve more complex problems."),
        ("List Comprehensions Introduction", "Students learn a concise way to build lists in Python."),
        ("Recursion: A Gentle Introduction", "Students learn the basic idea of a function that calls itself to solve a problem."),
        ("Introduction to APIs", "Students learn how programs use APIs to share and request data."),
        ("Computational Thinking and Problem Decomposition", "Students learn to break big problems into smaller, solvable steps."),
    ],
    "World Literature": [
        ("Homer's Epics: The Odyssey and The Iliad", "Students explore the adventures and themes of Homer's ancient Greek epics."),
        ("Aesop's Fables and Moral Lessons", "Students explore the moral lessons taught through Aesop's classic fables."),
        ("The Arabian Nights: Tales of Adventure", "Students explore the frame story and adventure tales of the Arabian Nights."),
        ("Grimm Brothers' Fairy Tales", "Students explore the themes and characters of classic Grimm fairy tales."),
        ("Hans Christian Andersen's Tales", "Students explore the imaginative tales of Hans Christian Andersen."),
        ("Shakespeare for Young Readers", "Students explore age-appropriate summaries and themes from Shakespeare's plays."),
        ("Mark Twain and American Adventure Stories", "Students explore Mark Twain's contributions to American adventure literature."),
        ("Charles Dickens and Victorian England", "Students explore how Dickens's novels reflect life in Victorian England."),
        ("Jules Verne and Early Science Fiction", "Students explore Jules Verne's role in shaping early science fiction."),
        ("Rudyard Kipling's Jungle Tales", "Students explore the animal characters and themes of Kipling's jungle stories."),
        ("Lewis Carroll and Nonsense Literature", "Students explore the wordplay and imagination of Lewis Carroll's stories."),
        ("Chinese Classical Literature: Journey to the West", "Students explore the adventures and themes of the classic Chinese tale."),
        ("Japanese Folktales and Legends", "Students explore traditional Japanese folktales and their cultural meaning."),
        ("Indian Epics: The Ramayana and Mahabharata", "Students explore the themes and heroes of India's classic epics."),
        ("African Oral Storytelling Traditions", "Students explore the role of oral storytelling in African cultures."),
        ("Greek Mythology and Its Heroes", "Students explore the gods, heroes, and myths of ancient Greece."),
        ("Norse Mythology and Legends", "Students explore the gods and legends of Norse mythology."),
        ("Latin American Folktales", "Students explore traditional folktales from Latin American cultures."),
        ("Poetry Around the World", "Students explore poetic traditions and forms from different world cultures."),
        ("The Novel as a Literary Form", "Students learn how the novel developed as a major form of literature."),
        ("Introduction to Drama and Playwriting", "Students learn the basic elements of drama and how plays are structured."),
        ("Coming-of-Age Stories", "Students explore stories that follow young characters growing and changing."),
        ("Adventure and Survival Literature", "Students explore literature centered on adventure and survival."),
        ("Fantasy Literature and World-Building", "Students explore how authors build imaginative fantasy worlds."),
        ("Historical Fiction as a Genre", "Students explore how historical fiction blends real events with storytelling."),
        ("Biography and Memoir", "Students explore how biographies and memoirs tell the stories of real lives."),
        ("Translated Literature and Its Challenges", "Students explore how literature is translated and what can be gained or lost."),
        ("Caribbean and Island Literature", "Students explore literary traditions from Caribbean and island cultures."),
        ("Modern Children's Literature Around the World", "Students explore contemporary children's literature from different countries."),
    ],
    "Art": [
        ("Elements of Art: Line, Shape, and Form", "Students learn the basic visual elements used in creating art."),
        ("Principles of Design: Balance and Contrast", "Students learn how balance and contrast create effective designs."),
        ("Color Theory and the Color Wheel", "Students learn how colors relate to each other on the color wheel."),
        ("Drawing Techniques: Shading and Perspective", "Students learn to use shading and perspective to create depth in drawings."),
        ("Painting Techniques: Watercolor Basics", "Students learn basic techniques for painting with watercolors."),
        ("Painting Techniques: Acrylic Basics", "Students learn basic techniques for painting with acrylic paint."),
        ("Sculpture and Three-Dimensional Art", "Students learn how sculptors create art in three dimensions."),
        ("Printmaking Basics", "Students learn the basic process of creating printed images."),
        ("Collage and Mixed Media", "Students learn to combine different materials to create collage art."),
        ("Ceramics and Clay Work", "Students learn basic techniques for working with clay."),
        ("Ancient Cave Art and Early Human Expression", "Students explore the earliest known human art found in caves."),
        ("Ancient Egyptian Art", "Students explore the style and symbolism of ancient Egyptian art."),
        ("Classical Greek and Roman Art", "Students explore the sculpture and architecture of ancient Greece and Rome."),
        ("Renaissance Art and Masters", "Students explore the innovations of Renaissance artists and their masterpieces."),
        ("Impressionism and Its Innovators", "Students explore how Impressionist artists changed the way light and color were painted."),
        ("Modern Art Movements", "Students explore key movements that shaped modern art."),
        ("Abstract Art", "Students explore how abstract artists express ideas without realistic imagery."),
        ("Pop Art", "Students explore how Pop Art used everyday imagery and popular culture."),
        ("Islamic Geometric Art and Patterns", "Students explore the geometric patterns found in Islamic art and architecture."),
        ("African Art and Masks", "Students explore the traditions and meanings behind African art and masks."),
        ("Asian Ink Painting and Calligraphy", "Students explore the techniques of East Asian ink painting and calligraphy."),
        ("Indigenous Art of the Americas", "Students explore the art traditions of Indigenous peoples of the Americas."),
        ("Photography as an Art Form", "Students learn how photography is used as a form of artistic expression."),
        ("Architecture as an Art Form", "Students learn how architecture combines function and artistic design."),
        ("Art Criticism: Describing and Interpreting Art", "Students learn a simple process for describing and interpreting artworks."),
        ("Cartooning and Comic Art", "Students learn basic techniques for drawing cartoons and comics."),
        ("Digital Art Basics", "Students learn the basics of creating art using digital tools."),
        ("Textile Art and Weaving", "Students learn the basics of textile art and traditional weaving techniques."),
        ("Street Art and Murals", "Students explore how street art and murals bring art into public spaces."),
    ],
    "Music": [
        ("Elements of Music: Rhythm and Beat", "Students learn how rhythm and beat form the foundation of music."),
        ("Elements of Music: Melody and Harmony", "Students learn how melody and harmony work together in music."),
        ("Reading Basic Music Notation", "Students learn to read simple notes and rhythms on a musical staff."),
        ("Instrument Families: Strings", "Students learn about instruments in the string family and how they produce sound."),
        ("Instrument Families: Woodwinds", "Students learn about instruments in the woodwind family and how they produce sound."),
        ("Instrument Families: Brass", "Students learn about instruments in the brass family and how they produce sound."),
        ("Instrument Families: Percussion", "Students learn about instruments in the percussion family and how they produce sound."),
        ("The Human Voice as an Instrument", "Students learn how the human voice works as a musical instrument."),
        ("Introduction to Music History: Baroque Period", "Students learn about the style and composers of the Baroque period."),
        ("Introduction to Music History: Classical Period", "Students learn about the style and composers of the Classical period."),
        ("Introduction to Music History: Romantic Period", "Students learn about the style and composers of the Romantic period."),
        ("Jazz and Its Origins", "Students learn about the origins and characteristics of jazz music."),
        ("The Blues Tradition", "Students learn about the history and style of blues music."),
        ("Rock and Roll History", "Students learn about the origins and evolution of rock and roll."),
        ("Hip-Hop as a Musical Art Form", "Students learn about the musical elements and history of hip-hop."),
        ("Folk Music Traditions", "Students learn about folk music traditions from around the world."),
        ("Classical Indian Music", "Students learn about the traditions and instruments of classical Indian music."),
        ("West African Drumming Traditions", "Students learn about the rhythms and traditions of West African drumming."),
        ("Latin American Music and Rhythm", "Students learn about the rhythms and styles of Latin American music."),
        ("Introduction to Music Composition", "Students learn basic steps for composing a simple original melody."),
        ("Tempo, Dynamics, and Musical Expression", "Students learn how tempo and dynamics shape musical expression."),
        ("Reading and Writing Simple Rhythms", "Students learn to read and write simple rhythmic patterns."),
        ("Introduction to Playing the Recorder", "Students learn basic fingerings and notes for playing the recorder."),
        ("Introduction to Keyboard and Piano", "Students learn basic notes and hand position for playing keyboard."),
        ("Introduction to Guitar Basics", "Students learn basic chords and technique for playing guitar."),
        ("Singing and Vocal Technique Basics", "Students learn basic breathing and vocal technique for singing."),
        ("Music and Emotion", "Students learn how musical choices can create different emotions in listeners."),
        ("Music Technology and Recording Basics", "Students learn the basics of how music is recorded and produced with technology."),
        ("Famous Composers and Their Contributions", "Students learn about the lives and works of famous composers."),
    ],
    "Survival Skills": [
        ("Building a Basic Shelter", "Students learn basic principles for building a simple outdoor shelter."),
        ("Fire Safety and Fire-Starting Basics", "Students learn safe methods and precautions for starting and managing a fire."),
        ("Water Purification Methods", "Students learn basic methods for making water safe to drink in the outdoors."),
        ("Basic Knot Tying", "Students learn to tie several useful knots for outdoor and everyday use."),
        ("Reading Weather Signs in Nature", "Students learn to observe natural signs that can indicate changing weather."),
        ("Wilderness First Aid Basics", "Students learn basic first aid steps for common outdoor injuries."),
        ("Identifying Edible and Poisonous Plants", "Students learn general caution and identification basics for plants in nature."),
        ("Signaling for Help", "Students learn basic signaling methods to attract help in an emergency."),
        ("Packing an Emergency Kit", "Students learn what essential items belong in a basic emergency kit."),
        ("Understanding Hypothermia and Heatstroke", "Students learn to recognize and respond to signs of hypothermia and heatstroke."),
        ("Basic Map and Compass Skills", "Students learn to use a map and compass to find direction."),
        ("Animal Safety and Avoiding Wildlife Encounters", "Students learn how to stay safe around wildlife in outdoor settings."),
        ("Insect and Snake Bite Safety", "Students learn basic precautions and responses for insect and snake bites."),
        ("Camping Basics and Leave No Trace Principles", "Students learn responsible camping practices that protect the environment."),
        ("Home Fire Safety and Escape Plans", "Students learn how to plan and practice a home fire escape route."),
        ("Earthquake Preparedness", "Students learn how to prepare for and respond safely to an earthquake."),
        ("Flood Safety and Preparedness", "Students learn how to prepare for and stay safe during flooding."),
        ("Basic Swimming and Water Safety", "Students learn fundamental water safety rules and swimming basics."),
        ("Road and Pedestrian Safety", "Students learn safe practices for walking and crossing roads."),
        ("Emergency Communication Basics", "Students learn how to communicate effectively during an emergency."),
        ("Basic Food Preservation for Survival", "Students learn simple methods for preserving food safely."),
        ("Understanding Emergency Services (911 and Beyond)", "Students learn when and how to contact emergency services."),
        ("Preparing a Family Emergency Plan", "Students learn how families can plan ahead for emergencies together."),
        ("Severe Storm Safety", "Students learn how to stay safe during thunderstorms and severe weather."),
        ("Winter Survival Basics", "Students learn basic strategies for staying safe in cold winter conditions."),
        ("Desert Survival Basics", "Students learn basic strategies for staying safe in hot, dry environments."),
        ("Basic Tool Use and Safety", "Students learn to use common outdoor tools safely and effectively."),
        ("Staying Calm Under Pressure: Emergency Mindset", "Students learn strategies for staying calm and thinking clearly in emergencies."),
        ("Community and Team Survival Strategies", "Students learn how working together improves survival outcomes in a group."),
    ],
    "General Knowledge": [
        ("World Landmarks and Wonders", "Students learn about famous landmarks and wonders from around the world."),
        ("Flags and National Symbols", "Students learn about flags and national symbols of countries around the world."),
        ("Currencies of the World", "Students learn about different currencies used by countries around the world."),
        ("Major World Languages", "Students learn about the most widely spoken languages in the world."),
        ("World Capitals Quiz Topics", "Students learn and practice identifying the capital cities of countries around the world."),
        ("Famous Inventors and Inventions", "Students learn about inventors and the inventions that changed the world."),
        ("Space Exploration Milestones", "Students learn about major milestones in the history of space exploration."),
        ("The Olympic Games: History and Values", "Students learn about the history and values behind the Olympic Games."),
        ("World Records and Achievements", "Students learn about notable world records and remarkable achievements."),
        ("Global Holidays and Celebrations", "Students learn about holidays and celebrations from cultures around the world."),
        ("Important International Organizations", "Students learn about the roles of major international organizations."),
        ("Famous Explorers in History", "Students learn about explorers who charted new lands and routes."),
        ("World's Longest Rivers and Tallest Mountains", "Students learn about the world's longest rivers and tallest mountains."),
        ("Endangered Animals Around the World", "Students learn about endangered animals and efforts to protect them."),
        ("Traditional Foods Around the World", "Students learn about traditional foods and dishes from different cultures."),
        ("Famous Scientists and Discoveries", "Students learn about scientists and their important discoveries."),
        ("Historical Timelines: Key World Events", "Students learn to place key world events on a historical timeline."),
        ("Nobel Prize and Its Categories", "Students learn about the purpose and categories of the Nobel Prize."),
        ("World Sports and Their Origins", "Students learn about popular sports and where they originated."),
        ("Iconic Museums of the World", "Students learn about famous museums and the treasures they hold."),
        ("Ancient Wonders of the World", "Students learn about the seven wonders of the ancient world."),
        ("Modern Wonders of Engineering", "Students learn about impressive feats of modern engineering."),
        ("Global Time and Calendars", "Students learn about different calendar systems used around the world."),
        ("Famous Artists Around the World", "Students learn about influential artists from different cultures and eras."),
        ("World Population and Demographics", "Students learn basic facts about world population and demographic trends."),
        ("Global News Literacy Basics", "Students learn basic skills for understanding news from around the world."),
        ("Traditional Games from Around the World", "Students learn about traditional games played in different cultures."),
        ("World Music and Dance Styles", "Students learn about distinctive music and dance styles from around the world."),
        ("Everyday General Knowledge Trivia", "Students build broad general knowledge through everyday trivia topics."),
    ],
    "Cooking": [
        ("Kitchen Safety Basics", "Students learn essential safety rules for working safely in a kitchen."),
        ("Basic Knife Skills", "Students learn safe and proper techniques for basic knife use."),
        ("Measuring Ingredients Accurately", "Students learn to measure ingredients accurately using standard tools."),
        ("Understanding Recipes and Following Steps", "Students learn to read and follow a recipe's steps in order."),
        ("Basic Food Hygiene", "Students learn basic hygiene practices to keep food safe to eat."),
        ("Introduction to Baking", "Students learn the basic principles and techniques of baking."),
        ("Bread Making Basics", "Students learn the basic steps involved in making bread."),
        ("Making Simple Breakfast Dishes", "Students learn to prepare a few simple, healthy breakfast dishes."),
        ("Cooking with Vegetables", "Students learn basic techniques for preparing and cooking vegetables."),
        ("Cooking with Grains and Rice", "Students learn basic techniques for cooking grains and rice."),
        ("Cooking with Eggs", "Students learn several basic methods for cooking eggs."),
        ("Basic Sauces and Dressings", "Students learn to prepare a few basic sauces and salad dressings."),
        ("Soups and Stews Basics", "Students learn the basic steps for making simple soups and stews."),
        ("Basic Nutrition and Balanced Meals", "Students learn how to plan a balanced, nutritious meal."),
        ("Understanding Food Groups", "Students learn about the major food groups and their role in a healthy diet."),
        ("Italian Cuisine Basics", "Students learn about common dishes and ingredients in Italian cooking."),
        ("Mexican Cuisine Basics", "Students learn about common dishes and ingredients in Mexican cooking."),
        ("Indian Cuisine Basics", "Students learn about common dishes and spices used in Indian cooking."),
        ("Chinese Cuisine Basics", "Students learn about common dishes and techniques in Chinese cooking."),
        ("Middle Eastern Cuisine Basics", "Students learn about common dishes and ingredients in Middle Eastern cooking."),
        ("Mediterranean Cuisine Basics", "Students learn about the ingredients and health benefits of Mediterranean cooking."),
        ("Basic Dessert Making", "Students learn to prepare a few simple desserts."),
        ("Food Storage and Preservation", "Students learn safe methods for storing and preserving food."),
        ("Cooking Equipment and Tools", "Students learn to identify and safely use common cooking tools and equipment."),
        ("Reading Food Labels", "Students learn how to read and understand nutrition labels on food packaging."),
        ("Vegetarian and Plant-Based Cooking Basics", "Students learn the basics of preparing vegetarian and plant-based meals."),
        ("Baking with Yeast vs. Baking Soda", "Students learn the difference between yeast and baking soda as leavening agents."),
        ("Table Setting and Meal Presentation", "Students learn basic principles of setting a table and presenting a meal."),
        ("Cooking as a Family and Cultural Tradition", "Students learn how cooking traditions connect families and cultures."),
    ],
    "Foreign Languages": [
        ("Spanish Greetings and Introductions", "Students learn common Spanish greetings and how to introduce themselves."),
        ("Spanish Present Tense Verbs", "Students learn to conjugate common Spanish verbs in the present tense."),
        ("French Greetings and Basic Phrases", "Students learn common French greetings and everyday phrases."),
        ("French Gender and Articles", "Students learn how French nouns have gender and how articles agree with them."),
        ("German Greetings and Basic Grammar", "Students learn common German greetings and basic sentence structure."),
        ("German Noun Cases Introduction", "Students learn the basic idea of noun cases in German grammar."),
        ("Mandarin Chinese Tones and Pronunciation", "Students learn the four tones used in Mandarin Chinese pronunciation."),
        ("Mandarin Chinese Basic Characters", "Students learn to recognize and write a few basic Chinese characters."),
        ("Japanese Hiragana Basics", "Students learn to recognize and write basic hiragana characters."),
        ("Japanese Basic Greetings and Politeness", "Students learn common Japanese greetings and polite expressions."),
        ("Korean Hangul Basics", "Students learn to recognize the basic letters of the Korean Hangul alphabet."),
        ("Italian Basic Vocabulary and Pronunciation", "Students learn basic Italian vocabulary and pronunciation rules."),
        ("Portuguese Basic Vocabulary and Pronunciation", "Students learn basic Portuguese vocabulary and pronunciation rules."),
        ("Russian Cyrillic Alphabet Basics", "Students learn to recognize the letters of the Russian Cyrillic alphabet."),
        ("Arabic Alphabet and Script", "Students learn to recognize the letters of the Arabic alphabet."),
        ("Arabic Basic Vocabulary and Greetings", "Students learn common Arabic greetings and basic vocabulary."),
        ("Hindi Devanagari Script Basics", "Students learn to recognize basic characters of the Hindi Devanagari script."),
        ("Swahili Basic Vocabulary and Greetings", "Students learn common Swahili greetings and basic vocabulary."),
        ("Turkish Basic Vocabulary and Grammar", "Students learn basic Turkish vocabulary and simple grammar patterns."),
        ("Comparing Language Families", "Students learn how languages are grouped into families with shared roots."),
        ("Cognates and False Friends", "Students learn to recognize cognates and false friends between languages."),
        ("Basic Sentence Structure Across Languages", "Students compare basic sentence structure across several world languages."),
        ("Numbers and Counting in Different Languages", "Students learn to count from one to ten in several world languages."),
        ("Family Vocabulary in Different Languages", "Students learn family member vocabulary in several world languages."),
        ("Days, Months, and Seasons in Different Languages", "Students learn the days, months, and seasons in several world languages."),
        ("Food Vocabulary in Different Languages", "Students learn common food vocabulary in several world languages."),
        ("Common Idioms in World Languages", "Students learn interesting idioms from different world languages."),
        ("Sign Language Basics (ASL)", "Students learn basic signs and fingerspelling in American Sign Language."),
        ("Why Learning Languages Matters: Culture and Communication", "Students learn how language connects to culture and effective communication."),
    ],
    "Social Studies": [
        ("What is Government? Forms of Government", "Students learn about different forms of government around the world."),
        ("The Three Branches of Government", "Students learn about the roles of the legislative, executive, and judicial branches."),
        ("Democracy and Citizenship", "Students learn what it means to be an active and responsible citizen in a democracy."),
        ("Rights and Responsibilities of Citizens", "Students learn about the rights and responsibilities that come with citizenship."),
        ("Local, State, and National Government", "Students learn how government is organized at local, state, and national levels."),
        ("Elections and Voting", "Students learn how elections work and why voting matters."),
        ("Laws and the Justice System", "Students learn how laws are made and enforced through the justice system."),
        ("The Constitution and Its Purpose", "Students learn the basic purpose and structure of a constitution."),
        ("Economics Basics: Needs and Wants", "Students learn the difference between needs and wants in economic decisions."),
        ("Supply and Demand", "Students learn how supply and demand affect prices and markets."),
        ("Goods, Services, and Trade", "Students learn the difference between goods and services and how trade works."),
        ("Money and Banking Basics", "Students learn the basic functions of money and banks in an economy."),
        ("Taxes and Public Services", "Students learn how taxes fund public services in a community."),
        ("Producers and Consumers", "Students learn the roles of producers and consumers in an economy."),
        ("Global Trade and Interdependence", "Students learn how countries depend on each other through global trade."),
        ("Cultural Diversity and Identity", "Students learn how culture shapes identity and community life."),
        ("Immigration and Its Impact on Society", "Students learn how immigration has shaped societies throughout history."),
        ("Community Helpers and Public Institutions", "Students learn about the roles of community helpers and public institutions."),
        ("Media Literacy and Information Sources", "Students learn to evaluate the reliability of different information sources."),
        ("Civic Engagement and Volunteering", "Students learn ways individuals can engage in and improve their communities."),
        ("Conflict Resolution and Diplomacy", "Students learn basic strategies for resolving conflicts peacefully."),
        ("Social Justice Movements in History", "Students learn about historic movements that fought for social justice."),
        ("Poverty and Inequality", "Students learn about the causes and effects of poverty and inequality."),
        ("Urban and Rural Life Comparisons", "Students learn to compare daily life in urban and rural communities."),
        ("Family Structures Across Cultures", "Students learn how family structures vary across different cultures."),
        ("Work and Careers in Society", "Students learn about different types of work and careers in society."),
        ("Social Institutions: Family, Education, and Religion", "Students learn how family, education, and religion function as social institutions."),
        ("Globalization and Its Effects on Society", "Students learn how globalization affects societies and daily life."),
        ("Sustainable Development Goals", "Students learn about global goals aimed at improving lives and protecting the planet."),
    ],
    "Physical Education & Self-Defense": [
        ("Warm-Up and Stretching Basics", "Students learn safe warm-up and stretching routines before physical activity."),
        ("Cardiovascular Fitness Basics", "Students learn activities and habits that build cardiovascular fitness."),
        ("Strength and Muscular Endurance", "Students learn safe exercises that build strength and muscular endurance."),
        ("Flexibility and Mobility Training", "Students learn exercises that improve flexibility and joint mobility."),
        ("Team Sports: Basketball Basics", "Students learn basic rules and skills of basketball."),
        ("Team Sports: Soccer Basics", "Students learn basic rules and skills of soccer."),
        ("Team Sports: Volleyball Basics", "Students learn basic rules and skills of volleyball."),
        ("Individual Sports: Swimming Basics", "Students learn basic swimming strokes and water safety skills."),
        ("Individual Sports: Gymnastics Basics", "Students learn basic gymnastics movements and body control."),
        ("Athletics: Jumping Events", "Students learn the basic technique behind track and field jumping events."),
        ("Athletics: Throwing Events", "Students learn the basic technique behind track and field throwing events."),
        ("Basic Self-Defense Principles", "Students learn foundational principles of personal safety and self-defense."),
        ("Situational Awareness and Avoidance", "Students learn to recognize risky situations and how to avoid them."),
        ("Basic Blocking and Evasion Techniques", "Students learn simple techniques for blocking and avoiding contact safely."),
        ("Balance and Core Stability", "Students learn exercises that build balance and core stability."),
        ("Sportsmanship and Fair Play", "Students learn the importance of sportsmanship and fair play in sports."),
        ("Rules and Officiating in Sports", "Students learn how rules and officials keep sports fair and safe."),
        ("Injury Prevention and Safety", "Students learn strategies for preventing common sports injuries."),
        ("Cool-Down and Recovery Techniques", "Students learn the importance of cooling down and recovering after exercise."),
        ("Nutrition for Active Bodies", "Students learn how nutrition supports physical activity and recovery."),
        ("Goal Setting in Fitness", "Students learn to set realistic and achievable personal fitness goals."),
        ("Introduction to Yoga and Mindful Movement", "Students learn basic yoga poses and mindful movement practices."),
        ("Introduction to Martial Arts Traditions", "Students learn about the history and discipline of various martial arts traditions."),
        ("Basic Wrestling and Grappling Safety", "Students learn safe fundamentals of wrestling and grappling under supervision."),
        ("Dance as Physical Activity", "Students learn how dance builds fitness, coordination, and expression."),
        ("Cooperative Games and Teamwork", "Students learn teamwork skills through cooperative games and activities."),
        ("Bullying Prevention and Personal Safety", "Students learn strategies for preventing bullying and staying safe."),
        ("Understanding Body Mechanics and Posture", "Students learn how proper posture and body mechanics support healthy movement."),
        ("Lifelong Fitness Habits", "Students learn habits that support staying active and healthy throughout life."),
    ],
    "Critical Thinking": [
        ("Identifying Facts vs. Opinions", "Students learn to distinguish between factual statements and opinions."),
        ("Recognizing Bias in Information", "Students learn to identify bias in the information they read and hear."),
        ("Logical Reasoning: Deductive vs. Inductive", "Students learn the difference between deductive and inductive reasoning."),
        ("Common Logical Fallacies", "Students learn to recognize common flaws in reasoning known as logical fallacies."),
        ("Evaluating Sources of Information", "Students learn criteria for judging whether a source of information is reliable."),
        ("Cause and Effect Reasoning", "Students learn to identify cause-and-effect relationships in reasoning."),
        ("Making Evidence-Based Arguments", "Students learn to support arguments with clear, relevant evidence."),
        ("Analyzing Arguments for Validity", "Students learn to evaluate whether an argument's conclusion logically follows from its premises."),
        ("Problem-Solving Strategies", "Students learn a variety of strategies for approaching and solving problems."),
        ("Decision-Making Frameworks", "Students learn simple frameworks for making thoughtful decisions."),
        ("Asking Good Questions", "Students learn how to ask clear, purposeful questions to deepen understanding."),
        ("Comparing and Contrasting Ideas", "Students learn to systematically compare and contrast different ideas."),
        ("Identifying Assumptions", "Students learn to recognize unstated assumptions behind an argument."),
        ("Recognizing Propaganda Techniques", "Students learn to identify common propaganda techniques used to persuade."),
        ("Understanding Correlation vs. Causation", "Students learn why correlation between two things does not always mean one causes the other."),
        ("Analogical Reasoning", "Students learn how comparing similar situations can help solve new problems."),
        ("Creative Thinking and Brainstorming", "Students learn techniques for generating creative ideas and solutions."),
        ("Evaluating Credibility of Claims", "Students learn to judge the credibility of claims using evidence and reasoning."),
        ("Structuring a Persuasive Argument", "Students learn to structure a clear and persuasive argument."),
        ("Recognizing Emotional Manipulation in Media", "Students learn to recognize when media uses emotion to manipulate opinion."),
        ("Thinking About Consequences", "Students learn to consider the possible consequences of decisions before acting."),
        ("Perspective-Taking and Empathy in Reasoning", "Students learn to consider other viewpoints when reasoning through an issue."),
        ("Debate Basics: Constructing and Rebutting Arguments", "Students learn basic skills for constructing and responding to arguments in debate."),
        ("Recognizing Patterns and Trends", "Students learn to identify patterns and trends in information and data."),
        ("Risk Assessment and Reasoning", "Students learn basic reasoning skills for assessing risk in decisions."),
        ("Ethical Reasoning and Dilemmas", "Students learn to reason through simple ethical dilemmas."),
        ("Metacognition: Thinking About Thinking", "Students learn to reflect on and monitor their own thinking processes."),
        ("Reasoning with Probability and Uncertainty", "Students learn to reason about situations involving probability and uncertainty."),
        ("Applying Critical Thinking to Everyday Decisions", "Students learn to apply critical thinking skills to everyday decisions."),
    ],
    "Health Education": [
        ("Personal Hygiene Habits", "Students learn daily hygiene habits that support health and wellbeing."),
        ("Understanding the Immune System", "Students learn how the immune system helps protect the body from illness."),
        ("Common Illnesses and Prevention", "Students learn about common illnesses and ways to help prevent them."),
        ("Vaccinations and Public Health", "Students learn how vaccinations help protect individuals and communities."),
        ("Healthy Sleep Habits", "Students learn why sleep matters and habits that support healthy sleep."),
        ("Understanding Puberty and Body Changes", "Students learn about the physical and emotional changes of puberty."),
        ("Digestive System and Healthy Eating", "Students learn how the digestive system works and supports healthy eating."),
        ("Hydration and the Body", "Students learn why water is important and how much the body needs."),
        ("Screen Time and Digital Wellbeing", "Students learn about healthy limits and habits around screen time."),
        ("Understanding Emotions and Self-Regulation", "Students learn to recognize emotions and strategies for self-regulation."),
        ("Building Healthy Friendships", "Students learn qualities of healthy, respectful friendships."),
        ("Peer Pressure and Decision-Making", "Students learn strategies for making good decisions under peer pressure."),
        ("Understanding Consent and Personal Boundaries", "Students learn the importance of respecting personal boundaries and consent."),
        ("Substance Abuse Prevention: Tobacco and Alcohol", "Students learn about the risks of tobacco and alcohol use."),
        ("Understanding Medicines and Safe Use", "Students learn safe practices for using medicines appropriately."),
        ("Dental and Oral Health", "Students learn habits that support good dental and oral health."),
        ("Vision and Hearing Health", "Students learn habits that protect vision and hearing health."),
        ("Healthy Body Image and Self-Esteem", "Students learn to build a healthy body image and self-esteem."),
        ("Understanding Allergies", "Students learn what allergies are and how to manage common reactions safely."),
        ("Environmental Health and Pollution", "Students learn how environmental pollution can affect human health."),
        ("Injury Prevention at Home and School", "Students learn practical ways to prevent common injuries at home and school."),
        ("Understanding Disabilities and Inclusion", "Students learn about different disabilities and the importance of inclusion."),
        ("Healthy Communication in Relationships", "Students learn communication skills that support healthy relationships."),
        ("Setting Personal Health Goals", "Students learn to set achievable personal goals for their health and wellbeing."),
    ],
    "ICT & Computer Science": [
        ("Introduction to Computer Hardware", "Students learn about the basic hardware components of a computer."),
        ("Introduction to Computer Software", "Students learn the difference between software and hardware and how software works."),
        ("Operating Systems Basics", "Students learn the basic role of an operating system in managing a computer."),
        ("File Management and Organization", "Students learn to organize files and folders on a computer."),
        ("Word Processing Skills", "Students learn basic skills for creating and formatting documents."),
        ("Spreadsheet Basics", "Students learn basic skills for entering and organizing data in a spreadsheet."),
        ("Presentation Software Basics", "Students learn basic skills for creating a simple slide presentation."),
        ("Introduction to the Internet and Web Browsers", "Students learn how the internet works and how to use a web browser."),
        ("Search Engines and Effective Searching", "Students learn strategies for searching the internet effectively."),
        ("Email Etiquette and Communication", "Students learn appropriate etiquette for writing and sending emails."),
        ("Digital Citizenship and Online Safety", "Students learn to be safe, responsible, and respectful online."),
        ("Cyberbullying Awareness and Prevention", "Students learn to recognize cyberbullying and how to respond to it."),
        ("Understanding Passwords and Account Security", "Students learn to create strong passwords and protect their accounts."),
        ("Introduction to Cloud Storage", "Students learn what cloud storage is and how it is used to save files."),
        ("Understanding Data and Information", "Students learn the difference between raw data and useful information."),
        ("Introduction to Databases", "Students learn the basic concept of how databases store and organize information."),
        ("How Computers Process Information (Binary Basics)", "Students learn how computers use binary code to process information."),
        ("Introduction to Artificial Intelligence", "Students learn a basic introduction to what artificial intelligence is and how it is used."),
        ("Introduction to Robotics in Computing", "Students learn how computing and programming are used to control robots."),
        ("Digital Footprint and Privacy", "Students learn how their online actions create a digital footprint."),
        ("Copyright and Digital Media Ethics", "Students learn the basics of copyright and ethical use of digital media."),
        ("Introduction to Coding and Computer Science", "Students learn a broad introduction to coding and computer science as a field."),
        ("Touch Typing Skills", "Students learn proper finger placement and technique for touch typing."),
        ("Introduction to Multimedia Editing", "Students learn basic skills for editing images, audio, or video."),
        ("Understanding Computer Networks Basics", "Students learn the basics of how computers connect and communicate in a network."),
        ("Social Media Literacy", "Students learn to use social media thoughtfully and critically evaluate its content."),
        ("Online Research and Source Evaluation", "Students learn to research topics online and evaluate the quality of sources."),
        ("Introduction to 3D Printing and Design", "Students learn the basics of designing objects for 3D printing."),
        ("Emerging Technology Trends", "Students learn about emerging technologies shaping the future."),
    ],
}
