"""Grade 8 topic expansion data (part B - half of Grade 8 subjects).

Each subject maps to a list of (title, one-sentence summary) tuples describing
NEW topics to add on top of the existing lessons already present in
backend/syllabus/grade8.json. A later merge script builds full lesson objects
from these pairs.
"""

GRADE = 8
MODULES: dict[str, list[tuple[str, str]]] = {
    "Foreign Languages": [
        ("Spanish Present Tense Regular Verbs", "Students learn to conjugate regular -ar, -er, and -ir verbs in the Spanish present tense."),
        ("Spanish Ser vs Estar", "Students learn when to use the verbs ser and estar, both of which mean 'to be' in Spanish."),
        ("Spanish Gender and Agreement of Nouns", "Students learn how Spanish nouns are masculine or feminine and how adjectives must agree with them."),
        ("Spanish Everyday Vocabulary: Family and Home", "Students build vocabulary for describing family members and common items found at home."),
        ("Spanish Question Words and Basic Questions", "Students learn to form questions in Spanish using words like qué, quién, dónde, cuándo, and por qué."),
        ("French Definite and Indefinite Articles", "Students learn to use le, la, les, un, une, and des correctly with French nouns."),
        ("French Present Tense of -er Verbs", "Students learn to conjugate regular first-group French verbs ending in -er."),
        ("French Numbers and Telling Time", "Students learn to count in French and express clock time in everyday conversation."),
        ("French Everyday Vocabulary: Food and Dining", "Students learn common French words and phrases used for food, meals, and dining out."),
        ("French Adjective Placement and Agreement", "Students learn where adjectives go in a French sentence and how they change to match gender and number."),
        ("German Noun Genders and Articles", "Students learn that German nouns are masculine, feminine, or neuter and how this affects the articles der, die, and das."),
        ("German Case System: Nominative and Accusative", "Students are introduced to how German nouns and articles change form depending on their grammatical role."),
        ("German Word Order and Verb Position", "Students learn the rule that places the conjugated verb in the second position of a German main clause."),
        ("German Everyday Vocabulary: School and Daily Routine", "Students build vocabulary for describing a typical school day and daily routine in German."),
        ("German Modal Verbs", "Students learn common German modal verbs such as können, müssen, and wollen and how they change sentence meaning."),
        ("Mandarin Chinese Tones and Pinyin", "Students learn the four tones of Mandarin and how the pinyin system represents pronunciation."),
        ("Mandarin Chinese Basic Sentence Structure", "Students learn the subject-verb-object word order used to build simple Mandarin sentences."),
        ("Mandarin Chinese Numbers and Measure Words", "Students learn to count in Mandarin and use basic measure words when counting objects."),
        ("Mandarin Chinese Everyday Vocabulary: Greetings and Introductions", "Students learn common Mandarin greetings and how to introduce themselves."),
        ("Mandarin Chinese Characters: Radicals and Strokes", "Students learn how Chinese characters are built from radicals and written using ordered strokes."),
        ("Japanese Hiragana and Katakana", "Students learn to read and write the two Japanese phonetic syllabaries, hiragana and katakana."),
        ("Japanese Basic Sentence Particles", "Students learn how particles such as wa, ga, o, and ni mark the roles of words in a Japanese sentence."),
        ("Japanese Polite Verb Forms", "Students learn to use the -masu verb form appropriate for polite, everyday Japanese speech."),
        ("Japanese Everyday Vocabulary: Numbers and Counting", "Students learn the Japanese number system and simple counters used for everyday objects."),
        ("Italian Definite Articles and Noun Gender", "Students learn how Italian nouns are masculine or feminine and how this determines the correct article."),
        ("Italian Present Tense of Regular Verbs", "Students learn to conjugate regular -are, -ere, and -ire verbs in the Italian present tense."),
        ("Italian Everyday Vocabulary: Travel and Directions", "Students learn Italian vocabulary and phrases for asking for and giving directions while traveling."),
        ("Russian Cyrillic Alphabet", "Students learn to recognize, read, and write the letters of the Russian Cyrillic alphabet."),
        ("Russian Noun Cases: Nominative and Accusative", "Students are introduced to how Russian nouns change form depending on their grammatical role in a sentence."),
        ("Russian Everyday Vocabulary: Greetings and Numbers", "Students learn common Russian greetings and how to count basic numbers."),
        ("Portuguese Definite and Indefinite Articles", "Students learn to use o, a, os, as, um, and uma correctly with Portuguese nouns."),
        ("Portuguese Present Tense of Regular Verbs", "Students learn to conjugate regular -ar, -er, and -ir verbs in the Portuguese present tense."),
        ("Portuguese Everyday Vocabulary: Weather and Seasons", "Students learn Portuguese vocabulary for describing weather conditions and the seasons of the year."),
        ("Korean Hangul Alphabet", "Students learn the structure of Hangul, the Korean phonetic writing system, and how to read simple syllable blocks."),
        ("Korean Basic Sentence Structure", "Students learn the subject-object-verb word order used to build simple Korean sentences."),
        ("Korean Honorifics and Politeness Levels", "Students learn how Korean speech changes to show respect depending on who is being addressed."),
        ("Hindi Devanagari Script Basics", "Students learn to recognize and write basic characters of the Devanagari script used to write Hindi."),
        ("Hindi Gender and Postpositions", "Students learn how Hindi nouns have grammatical gender and how postpositions are used instead of prepositions."),
        ("Hindi Everyday Vocabulary: Family and Greetings", "Students learn common Hindi words for family members and everyday greetings."),
    ],
    "Social Studies": [
        ("Ancient Civilizations: Mesopotamia", "Students learn how cities, writing, and early law codes developed in the Fertile Crescent."),
        ("Ancient Egypt and the Nile", "Students learn how the Nile River shaped the society, agriculture, and government of ancient Egypt."),
        ("Ancient Greece: Democracy and Philosophy", "Students learn how ancient Greece gave rise to early democratic government and philosophical inquiry."),
        ("The Roman Republic and Empire", "Students learn how Roman government developed and how the empire expanded across Europe and beyond."),
        ("The Silk Road and Global Trade", "Students learn how ancient trade routes connected distant civilizations and exchanged goods and ideas."),
        ("Feudalism in Medieval Europe", "Students learn how land, loyalty, and labor structured medieval European society."),
        ("The Renaissance", "Students learn how renewed interest in art, science, and learning transformed Europe."),
        ("The Age of Exploration", "Students learn about European voyages of discovery and their global consequences."),
        ("The Scientific Revolution", "Students learn how new methods of observation and experimentation changed how people understood the natural world."),
        ("The Enlightenment and Natural Rights", "Students learn about Enlightenment ideas concerning liberty, reason, and individual rights."),
        ("The American Revolution", "Students learn about the causes and consequences of the founding of the United States."),
        ("The French Revolution", "Students learn how the French monarchy was overthrown and how the revolution reshaped France."),
        ("The Industrial Revolution", "Students learn how new technology and factories transformed work and daily life."),
        ("Colonialism and Imperialism", "Students learn about the causes and effects of European colonial expansion overseas."),
        ("World War I: Causes and Consequences", "Students learn about the alliances, events, and outcomes that shaped the First World War."),
        ("World War II: Causes and Consequences", "Students learn about the causes, key events, and lasting impact of the Second World War."),
        ("The Cold War", "Students learn about the political rivalry between the United States and the Soviet Union after World War II."),
        ("Decolonization Movements", "Students learn how many colonized nations gained independence during the twentieth century."),
        ("The United Nations and International Cooperation", "Students learn how nations work together through international organizations to address shared problems."),
        ("Human Rights and the Universal Declaration", "Students learn about the basic rights recognized as belonging to every person."),
        ("Branches of Government", "Students learn the roles of the legislative, executive, and judicial branches of government."),
        ("The Constitution and the Bill of Rights", "Students learn about the foundational document of the U.S. government and its first ten amendments."),
        ("Comparing Forms of Government", "Students compare democracies, monarchies, dictatorships, and other systems of government."),
        ("Citizenship and Civic Responsibility", "Students learn about the rights and responsibilities that come with being a citizen."),
        ("Elections and Voting", "Students learn how democratic elections work and why participating in voting matters."),
        ("Local, State, and National Government", "Students learn how different levels of government share and divide power."),
        ("World Geography: Continents and Oceans", "Students learn to identify the world's major continents and oceans."),
        ("Physical Geography: Landforms and Climate", "Students learn how landforms and climate patterns shape different regions of the world."),
        ("Population and Migration", "Students learn why people move from place to place and how populations are distributed globally."),
        ("Culture and Cultural Diffusion", "Students learn how cultural practices and ideas spread between societies over time."),
        ("World Religions: An Overview", "Students learn the basic beliefs and practices of several major world religions."),
        ("Maps and Geographic Tools", "Students learn to read maps and use tools such as latitude, longitude, and map projections."),
        ("Natural Resources and Their Distribution", "Students learn how the uneven distribution of natural resources affects settlement and trade."),
        ("Urbanization and City Growth", "Students learn why cities grow and what challenges rapid urban growth can create."),
        ("The Civil Rights Movement", "Students learn about the struggle for racial equality in the mid-twentieth century United States."),
        ("Globalization", "Students learn how the world's economies, cultures, and communications have become increasingly interconnected."),
        ("International Organizations and Alliances", "Students learn about the purposes of organizations such as NATO and the World Trade Organization."),
        ("Media and Information Literacy in Society", "Students learn to evaluate news sources and understand the role media plays in society."),
        ("Comparing Political Ideologies", "Students learn the basic differences between political ideologies such as conservatism and liberalism."),
    ],
    "Physical Education & Self-Defense": [
        ("Cardiovascular Endurance Training", "Students learn activities and exercises that build heart and lung fitness."),
        ("Muscular Strength and Conditioning", "Students learn basic bodyweight exercises that build muscular strength safely."),
        ("Flexibility and Stretching Techniques", "Students learn safe stretching methods that improve range of motion."),
        ("Warm-Up and Cool-Down Routines", "Students learn why warming up and cooling down matter and how to perform them properly."),
        ("Basketball Fundamentals", "Students learn the basic skills of dribbling, passing, and shooting in basketball."),
        ("Soccer Fundamentals", "Students learn basic passing, dribbling, and positioning skills in soccer."),
        ("Volleyball Fundamentals", "Students learn basic serving, bumping, and setting techniques in volleyball."),
        ("Track and Field Basics", "Students learn proper running form and introductory sprinting and throwing skills."),
        ("Badminton Skills and Rules", "Students learn basic strokes, serving technique, and scoring rules in badminton."),
        ("Table Tennis Skills and Rules", "Students learn proper grip, basic strokes, and scoring in table tennis."),
        ("Swimming Safety and Basic Strokes", "Students learn water safety rules and fundamental swimming stroke techniques."),
        ("Team Sports and Cooperation", "Students learn how communication and teamwork contribute to success in team sports."),
        ("Sportsmanship and Fair Play", "Students learn to show respect for opponents, teammates, and officials during competition."),
        ("Basic Rules of Officiating", "Students learn how referees and umpires apply the rules of common sports."),
        ("Goal Setting for Fitness", "Students learn to set realistic and measurable personal fitness goals."),
        ("Understanding Heart Rate and Exercise Intensity", "Students learn how to monitor heart rate to gauge the intensity of physical activity."),
        ("Injury Prevention in Sports", "Students learn common causes of sports injuries and practical ways to prevent them."),
        ("Basic First Response to Sports Injuries", "Students learn the RICE method for responding to common minor sports injuries."),
        ("Balance and Coordination Activities", "Students practice exercises designed to improve balance and overall body control."),
        ("Core Strength and Stability", "Students learn exercises that strengthen the abdominal and lower back muscles."),
        ("Self-Defense Stance and Footwork", "Students learn a basic ready stance and footwork for improving personal safety."),
        ("Situational Awareness and Avoidance", "Students learn to recognize and avoid situations that could put their safety at risk."),
        ("Verbal De-escalation Techniques", "Students learn how to use calm, clear communication to defuse a tense situation."),
        ("Basic Escape Techniques from Grabs", "Students learn simple, safe techniques for breaking free from a wrist or arm grab."),
        ("Personal Space and Boundary Setting", "Students learn how to communicate and assertively enforce personal physical boundaries."),
        ("Recognizing and Responding to Bullying", "Students learn to identify bullying behavior and safe ways to respond to it."),
        ("Basic Blocking and Protective Movements", "Students learn how to use arm and body positioning to protect themselves from a strike."),
        ("Fall Safety and Breakfall Techniques", "Students learn how to fall safely to reduce the risk of injury."),
        ("Yoga and Mindful Movement", "Students learn basic yoga poses and breathing techniques for flexibility and relaxation."),
        ("Dance and Rhythmic Movement", "Students learn basic dance steps and rhythm-based movement as a form of exercise."),
        ("Fitness Testing and Self-Assessment", "Students learn to measure and track their own fitness levels over time."),
        ("Nutrition and Hydration for Active Bodies", "Students learn how proper nutrition and hydration support physical performance."),
        ("Rest and Recovery in Training", "Students learn why rest days and adequate sleep are essential to fitness progress."),
        ("Setting Up a Personal Exercise Plan", "Students learn to create a simple, balanced weekly physical activity schedule."),
        ("Outdoor Recreation and Hiking Safety", "Students learn basic skills and precautions for enjoying outdoor activities safely."),
        ("Frisbee and Disc Sports", "Students learn basic throwing and catching techniques used in disc sports."),
        ("Gymnastics Basics: Balance and Body Control", "Students learn fundamental tumbling and balance skills used in gymnastics."),
        ("Understanding Doping and Fair Competition", "Students learn why performance-enhancing substances are banned in organized sport."),
        ("Building Lifelong Healthy Activity Habits", "Students learn strategies for staying physically active throughout their lives."),
    ],
    "Economics": [
        ("Needs versus Wants", "Students learn to distinguish essential needs from desired wants when making economic decisions."),
        ("Scarcity and Choice", "Students learn how limited resources force individuals and societies to make choices."),
        ("Opportunity Cost", "Students learn to identify what is given up when a person chooses one option over another."),
        ("Factors of Production", "Students learn about land, labor, capital, and entrepreneurship as the basic resources of production."),
        ("Supply and Demand", "Students learn how the interaction of supply and demand helps determine market prices."),
        ("Market Equilibrium", "Students learn how prices settle at the point where the quantity supplied equals the quantity demanded."),
        ("Types of Economic Systems", "Students compare traditional, command, market, and mixed economic systems."),
        ("The Role of Government in the Economy", "Students learn how governments influence the economy through taxation, regulation, and public goods."),
        ("Circular Flow of Income", "Students learn how money and resources flow between households and businesses in an economy."),
        ("Types of Markets: Competition and Monopoly", "Students learn how the number of sellers in a market affects prices and choices."),
        ("Price Elasticity", "Students learn how sensitive the quantity demanded of a good is to changes in its price."),
        ("Producers and Consumers", "Students learn the distinct roles that businesses and individuals play in an economy."),
        ("Specialization and Division of Labor", "Students learn how focusing on specific tasks can increase overall efficiency and output."),
        ("Trade and Comparative Advantage", "Students learn why individuals and countries can benefit from specializing and trading with one another."),
        ("Money and Its Functions", "Students learn how money functions as a medium of exchange, a store of value, and a unit of account."),
        ("Barter versus a Money Economy", "Students learn the limitations of direct bartering compared to using money."),
        ("Banks and Financial Institutions", "Students learn the role banks play in accepting savings and providing loans."),
        ("Interest Rates", "Students learn how interest rates influence borrowing and saving decisions."),
        ("Inflation and Deflation", "Students learn how the general level of prices in an economy can rise or fall over time."),
        ("Gross Domestic Product (GDP)", "Students learn how GDP is used to measure the overall size of a country's economy."),
        ("Unemployment and Its Types", "Students learn about frictional, structural, and cyclical unemployment."),
        ("Economic Growth", "Students learn about the factors that cause an economy to expand over time."),
        ("Business Cycles", "Students learn about the recurring pattern of expansion and recession in an economy."),
        ("Taxes and Public Spending", "Students learn how governments collect tax revenue and use it to fund public spending."),
        ("Public Goods and Externalities", "Students learn about goods that benefit everyone and the side effects economic activity can create."),
        ("Entrepreneurship and Innovation", "Students learn how new businesses and inventive ideas contribute to economic growth."),
        ("Types of Business Organizations", "Students learn the differences between sole proprietorships, partnerships, and corporations."),
        ("Labor Markets and Wages", "Students learn how wages are influenced by the supply of and demand for workers."),
        ("International Trade and Tariffs", "Students learn how tariffs and other trade barriers affect the exchange of goods between countries."),
        ("Exchange Rates", "Students learn how currencies are valued relative to one another in international trade."),
        ("Globalization and the Economy", "Students learn how economies around the world have become increasingly interconnected."),
        ("Economic Indicators", "Students learn about key statistics used to measure the health of an economy."),
        ("Poverty and Income Inequality", "Students learn about the causes and consequences of gaps in income and wealth."),
        ("Economic Development", "Students learn what distinguishes developing economies from developed economies."),
        ("Natural Resources and Sustainability in Economics", "Students learn how economies balance using natural resources with preserving them for the future."),
        ("Consumer Rights and Protection", "Students learn about laws and agencies that protect buyers in the marketplace."),
        ("Supply Chains and Production", "Students learn how goods move from raw materials to finished products through a supply chain."),
        ("The Stock Market Basics", "Students learn the basic idea of how shares of companies are bought and sold."),
        ("Behavioral Economics Basics", "Students learn how psychology and human behavior can influence economic decision-making."),
    ],
    "Finance": [
        ("Understanding Income and Wages", "Students learn about different types of earnings and how pay is typically calculated."),
        ("Needs-Based Spending Plans", "Students learn to prioritize essential expenses when creating a personal spending plan."),
        ("Saving Basics", "Students learn why saving money matters and simple strategies for getting started."),
        ("Setting Financial Goals", "Students learn to set short-term and long-term financial savings goals."),
        ("Understanding Bank Accounts", "Students learn the differences between checking accounts and savings accounts."),
        ("How Interest Works", "Students learn the difference between simple interest and compound interest."),
        ("Introduction to Credit", "Students learn what credit is and how it allows people to borrow money."),
        ("Understanding Credit Scores", "Students learn what a credit score measures and why it matters for future borrowing."),
        ("Debt and Borrowing Basics", "Students learn to distinguish between manageable debt and harmful debt."),
        ("Credit Cards versus Debit Cards", "Students learn how credit cards and debit cards work differently as payment methods."),
        ("Loans and Repayment", "Students learn the basics of how loans work and what repaying a loan involves."),
        ("Understanding Interest Rates on Loans", "Students learn how interest rates affect the total cost of borrowing money."),
        ("Introduction to Investing", "Students learn the basic idea of investing money to help it grow over time."),
        ("Stocks and Bonds Basics", "Students learn the difference between owning shares in a company and lending money through a bond."),
        ("Risk and Return in Investing", "Students learn how investments with higher potential returns typically carry higher risk."),
        ("Diversification", "Students learn how spreading money across different investments can help manage risk."),
        ("Introduction to Retirement Savings", "Students learn why starting to save for retirement early can make a big difference."),
        ("Understanding Taxes on Income", "Students learn the basic idea of how income tax is calculated and collected."),
        ("Sales Tax and Consumer Spending", "Students learn how sales tax adds to the price of goods and services."),
        ("Insurance Basics", "Students learn how insurance helps protect people from unexpected financial loss."),
        ("Types of Insurance", "Students learn about common types of insurance, including health, auto, and property insurance."),
        ("Identity Theft and Financial Fraud Prevention", "Students learn to recognize and avoid common financial scams and identity theft."),
        ("Online Banking and Digital Payments", "Students learn how to use banking apps and digital payment tools safely."),
        ("Comparison Shopping", "Students learn to compare price and value before making a purchase."),
        ("Needs versus Wants in Spending Decisions", "Students apply the concept of needs versus wants to real everyday spending choices."),
        ("Emergency Funds", "Students learn why setting aside money for unexpected expenses is an important financial habit."),
        ("Understanding Paychecks and Deductions", "Students learn to read a pay stub and understand common payroll deductions."),
        ("Entrepreneurship and Earning Money", "Students learn about starting a small business or project as a way to earn income."),
        ("The Cost of College and Education Planning", "Students learn about the costs of higher education and basic ways to plan and save for it."),
        ("Understanding Loans for Big Purchases", "Students learn how financing works for major purchases such as a car."),
        ("Renting versus Buying a Home", "Students learn the basic financial differences between renting and owning a home."),
        ("Inflation's Effect on Personal Finance", "Students learn how rising prices affect the purchasing power of personal savings."),
        ("Financial Record Keeping", "Students learn simple methods for tracking personal income and expenses over time."),
        ("Charitable Giving and Financial Planning", "Students learn how charitable donations can be included in a personal spending plan."),
        ("Avoiding Impulse Purchases", "Students learn strategies for making thoughtful spending decisions instead of impulsive ones."),
        ("Understanding Contracts and Financial Agreements", "Students learn the basics of reading and understanding a simple financial agreement."),
        ("Peer-to-Peer Payment Apps", "Students learn how digital payment apps work and what risks to watch for."),
        ("Building Good Financial Habits Early", "Students learn habits that support strong financial health throughout life."),
        ("Financial Decision-Making and Trade-offs", "Students learn to weigh the costs and benefits of everyday financial choices."),
    ],
    "First Aid": [
        ("The Primary Survey: Check, Call, Care", "Students learn the basic three-step approach for assessing and responding to an emergency."),
        ("Calling Emergency Services Effectively", "Students learn what information to provide clearly when calling for emergency help."),
        ("Recovery Position", "Students learn how and when to place an unconscious but breathing person in the recovery position."),
        ("Recognizing an Unresponsive Person", "Students learn how to safely check whether a person is responsive."),
        ("Basic Choking Response", "Students learn to recognize choking and the basic steps for helping someone who is choking."),
        ("Cardiopulmonary Resuscitation (CPR) Basics", "Students learn the general concept and basic steps involved in performing CPR."),
        ("Using an Automated External Defibrillator (AED)", "Students learn the basic purpose and general use of an AED in a cardiac emergency."),
        ("Treating Minor Cuts and Scrapes", "Students learn how to clean and properly dress small wounds."),
        ("Controlling Severe Bleeding", "Students learn to apply direct pressure to help control severe bleeding."),
        ("Recognizing and Treating Burns", "Students learn to identify different degrees of burns and provide basic first aid care."),
        ("Treating Nosebleeds", "Students learn the proper technique for helping someone stop a nosebleed."),
        ("Recognizing Signs of Shock", "Students learn to identify the warning signs of shock in an injured person."),
        ("Basic Splinting for Suspected Fractures", "Students learn simple techniques for immobilizing a suspected broken limb."),
        ("Treating Sprains and Strains", "Students learn the RICE method for caring for minor sprains and strains."),
        ("Recognizing Head Injuries", "Students learn the basic signs of a concussion and when medical help is needed."),
        ("Recognizing and Responding to Seizures", "Students learn how to keep a person safe while they are having a seizure."),
        ("Recognizing and Responding to Fainting", "Students learn appropriate steps to take when someone faints."),
        ("Heat-Related Illness: Heat Exhaustion and Heat Stroke", "Students learn to recognize and respond to illnesses caused by overheating."),
        ("Cold-Related Illness: Hypothermia and Frostbite", "Students learn to recognize and respond to illnesses caused by cold exposure."),
        ("Recognizing an Allergic Reaction", "Students learn to distinguish between mild and severe signs of an allergic reaction."),
        ("Responding to Anaphylaxis", "Students learn to recognize a severe allergic emergency and the basic use of an epinephrine auto-injector."),
        ("Basic Care for Insect Stings and Bites", "Students learn safe first aid steps for common insect stings and bites."),
        ("Recognizing Signs of a Heart Attack", "Students learn the basic warning signs that may indicate a heart attack."),
        ("Recognizing Signs of a Stroke", "Students learn to use the FAST method to help identify the signs of a stroke."),
        ("Poisoning Awareness and Response", "Students learn basic first steps to take when poisoning is suspected."),
        ("Eye Injury First Aid", "Students learn safe basic care for minor eye irritation or injury."),
        ("Dental Emergency Basics", "Students learn basic first aid steps for a knocked-out or injured tooth."),
        ("Building a First Aid Kit", "Students learn the essential items that should be included in a basic first aid kit."),
        ("Assessing Scene Safety Before Helping", "Students learn to check for danger before approaching an injured person."),
        ("Basic Wound Dressing and Bandaging Techniques", "Students learn to apply simple bandages and dressings correctly."),
        ("Recognizing Signs of Dehydration", "Students learn to identify symptoms of dehydration and basic ways to respond."),
        ("First Aid for Muscle Cramps", "Students learn safe steps for responding to a sudden muscle cramp."),
        ("Understanding Consent in First Aid", "Students learn why asking permission before helping an injured person matters."),
        ("Good Samaritan Principles", "Students learn the basic ethical principles that guide helping others in an emergency."),
        ("First Aid for Sports Injuries", "Students learn about common on-field injuries and the appropriate immediate response."),
        ("Recognizing Asthma Attacks and Basic Response", "Students learn to recognize breathing difficulty from asthma and how to assist."),
        ("Basic Care for Blisters", "Students learn safe first aid treatment for friction blisters."),
        ("Water Safety and Drowning Prevention", "Students learn basic precautions that help prevent drowning."),
        ("Creating a Family Emergency Plan", "Students learn how to prepare a home and family for responding to medical emergencies."),
    ],
    "Physics": [
        ("Motion and Speed", "Students learn to describe how objects move using the concepts of speed and velocity."),
        ("Acceleration", "Students learn how the speed or direction of a moving object changes over time."),
        ("Distance-Time and Speed-Time Graphs", "Students learn to interpret graphs that represent an object's motion."),
        ("Gravity and Weight", "Students learn how gravity acts on objects and the difference between mass and weight."),
        ("Friction", "Students learn how friction opposes motion and affects everyday movement."),
        ("Momentum", "Students learn the concept of mass in motion and how it applies to simple collisions."),
        ("Pressure", "Students learn how force distributed over an area creates pressure."),
        ("Pressure in Fluids", "Students learn how pressure behaves within liquids and gases."),
        ("Density", "Students learn the relationship between an object's mass and its volume."),
        ("Simple Machines: Levers and Pulleys", "Students learn how levers and pulleys make work easier to perform."),
        ("Simple Machines: Inclined Planes and Wheels", "Students learn how inclined planes and wheel-and-axle systems reduce the effort needed to do work."),
        ("Power", "Students learn how power measures the rate at which work is done."),
        ("Potential and Kinetic Energy", "Students learn to distinguish between stored energy and the energy of motion."),
        ("Conservation of Energy", "Students learn how energy changes form but is never created or destroyed."),
        ("Heat and Temperature", "Students learn the difference between heat energy and temperature."),
        ("Heat Transfer: Conduction, Convection, and Radiation", "Students learn the three main ways heat energy moves from place to place."),
        ("States of Matter and Physical Changes", "Students learn how matter changes between solid, liquid, and gas states."),
        ("Sound Waves", "Students learn how sound travels as a wave through different types of matter."),
        ("Pitch and Volume", "Students learn what determines the pitch and loudness of a sound."),
        ("The Electromagnetic Spectrum", "Students learn about the range of electromagnetic waves, from radio waves to gamma rays."),
        ("Light and Reflection", "Students learn how light behaves when it bounces off different surfaces."),
        ("Refraction of Light", "Students learn how light bends as it passes from one material into another."),
        ("Lenses and Optical Instruments", "Students learn how lenses form images in simple optical devices."),
        ("Static Electricity", "Students learn how electric charge builds up on objects and how it can be discharged."),
        ("Electric Circuits", "Students learn the basic components needed to build a simple electric circuit."),
        ("Series and Parallel Circuits", "Students learn how circuits behave differently when components are connected in series versus parallel."),
        ("Electric Current and Voltage", "Students learn about the basic quantities used to describe electricity."),
        ("Resistance in Circuits", "Students learn how resistance affects the flow of electric current in a circuit."),
        ("Magnetism", "Students learn about the properties of magnets and the magnetic fields they create."),
        ("Electromagnets", "Students learn how an electric current can be used to create a magnetic field."),
        ("Introduction to Electromagnetic Induction", "Students learn how a changing magnetic field can generate an electric current."),
        ("Energy Resources: Renewable and Non-Renewable", "Students compare different sources of energy and their impact on the environment."),
        ("Work and Machines in Everyday Life", "Students learn how simple machines make everyday physical tasks easier to accomplish."),
        ("Introduction to Space and Gravity", "Students learn how gravity governs the motion of planets, moons, and satellites."),
        ("Projectile Motion Basics", "Students learn the basic principles describing how objects move when launched into the air."),
        ("Measuring Physical Quantities", "Students learn to use appropriate units and tools when measuring physical properties."),
        ("Scientific Models in Physics", "Students learn how physicists use models to explain and predict natural phenomena."),
    ],
    "Chemistry": [
        ("States of Matter", "Students learn the properties of solids, liquids, and gases."),
        ("Physical versus Chemical Changes", "Students learn to distinguish between changes that alter a substance's form and those that create new substances."),
        ("Mixtures and Pure Substances", "Students learn to classify matter as either a pure substance or a mixture."),
        ("Separating Mixtures", "Students learn techniques such as filtration and distillation used to separate mixtures."),
        ("Solutions and Solubility", "Students learn how substances dissolve into one another to form solutions."),
        ("Concentration of Solutions", "Students learn how to describe the amount of solute dissolved in a given solution."),
        ("Acids and Bases", "Students learn the basic properties of acids and bases and where they appear in everyday life."),
        ("The pH Scale", "Students learn how the pH scale is used to measure how acidic or basic a substance is."),
        ("Neutralization Reactions", "Students learn what happens chemically when an acid and a base react with one another."),
        ("Indicators", "Students learn how chemical indicators are used to show whether a substance is acidic or basic."),
        ("Metals and Their Properties", "Students learn the common physical and chemical properties shared by metals."),
        ("Non-Metals and Their Properties", "Students learn the common physical and chemical properties shared by non-metals."),
        ("Metalloids", "Students learn about elements that have properties between those of metals and non-metals."),
        ("The Periodic Table: Groups and Periods", "Students learn how elements are organized into groups and periods based on shared properties."),
        ("Atomic Structure: Protons, Neutrons, and Electrons", "Students learn about the three basic particles that make up an atom."),
        ("Isotopes", "Students learn how isotopes are atoms of the same element with different numbers of neutrons."),
        ("Ions and Ionic Compounds", "Students learn how atoms gain or lose electrons to form ions and ionic compounds."),
        ("Covalent Compounds", "Students learn how atoms share electrons with one another to form molecules."),
        ("Chemical Formulas and Naming Compounds", "Students learn to read and write basic chemical formulas and compound names."),
        ("Balancing Chemical Equations", "Students learn how to balance chemical equations so that atoms are conserved."),
        ("Types of Chemical Reactions", "Students learn to identify synthesis, decomposition, and displacement reactions."),
        ("Exothermic and Endothermic Reactions", "Students learn the difference between reactions that release energy and those that absorb it."),
        ("Catalysts", "Students learn how catalysts can speed up a chemical reaction without being used up."),
        ("Rates of Reaction", "Students learn about the factors that affect how quickly a chemical reaction occurs."),
        ("Conservation of Mass in Reactions", "Students learn why the total mass of substances is conserved during a chemical reaction."),
        ("Oxidation and Combustion", "Students learn about basic chemical reactions that involve oxygen, including burning."),
        ("Rusting and Corrosion", "Students learn how metals react with substances in the environment over time."),
        ("The Water Molecule and Its Properties", "Students learn why water's molecular structure gives it its unique properties."),
        ("Carbon and Its Compounds", "Students learn about carbon's unique ability to form a wide variety of compounds."),
        ("Introduction to Organic Chemistry", "Students are introduced to the basics of chemistry involving carbon-based compounds."),
        ("Polymers and Plastics", "Students learn how small molecules can link together to form large polymer chains."),
        ("Crystals and Crystal Structure", "Students learn how particles can arrange themselves into repeating crystal patterns."),
        ("Chemical Safety in the Laboratory", "Students learn safe practices for handling chemicals and equipment in a laboratory setting."),
        ("Measuring Matter: Mass and Volume", "Students learn laboratory techniques for accurately measuring the mass and volume of substances."),
        ("The Mole Concept: An Introduction", "Students receive a basic introduction to how chemists count particles using the mole."),
        ("Chemical Bonding in Everyday Materials", "Students learn how the type of chemical bonding explains the properties of common materials."),
        ("History of the Periodic Table", "Students learn how scientists gradually developed the modern periodic table of elements."),
    ],
    "Biology": [
        ("Levels of Biological Organization", "Students learn how living things are organized from cells up through organisms and ecosystems."),
        ("Plant Cells versus Animal Cells", "Students learn the key structural differences between plant and animal cells."),
        ("Cell Division: Mitosis", "Students learn how cells divide through mitosis to allow growth and repair."),
        ("Photosynthesis", "Students learn how plants convert light energy into chemical energy stored in food."),
        ("Cellular Respiration", "Students learn how cells release usable energy from food."),
        ("Diffusion and Osmosis", "Students learn how substances move into and out of cells across their membranes."),
        ("Human Digestive System", "Students learn how the human body breaks down and absorbs nutrients from food."),
        ("Human Respiratory System", "Students learn how the human body takes in oxygen and removes carbon dioxide."),
        ("Human Circulatory System", "Students learn how blood transports oxygen, nutrients, and waste around the body."),
        ("The Heart and Blood Vessels", "Students learn the basic structure and function of the human heart and blood vessels."),
        ("Human Skeletal System", "Students learn about the structure and functions of the bones that make up the human skeleton."),
        ("Human Muscular System", "Students learn how muscles work together with bones to produce movement."),
        ("Human Nervous System", "Students learn how the brain, spinal cord, and nerves control the body."),
        ("The Five Senses", "Students learn how the sensory organs detect and respond to the environment."),
        ("Human Reproductive System", "Students learn the basic structure and function of the human reproductive system."),
        ("Puberty and Adolescent Development", "Students learn about the physical and hormonal changes that occur during adolescence."),
        ("The Endocrine System", "Students learn how hormones released by glands help regulate body functions."),
        ("The Immune System", "Students learn how the body defends itself against pathogens and infection."),
        ("Genetics and Heredity", "Students learn how physical traits are passed from parents to their offspring."),
        ("DNA Structure and Function", "Students learn about the structure of DNA and its role in carrying genetic information."),
        ("Genes and Chromosomes", "Students learn how genetic information is organized into genes and chromosomes."),
        ("Dominant and Recessive Traits", "Students learn basic patterns of inheritance involving dominant and recessive traits."),
        ("Introduction to Evolution", "Students are introduced to the concept that species change gradually over time."),
        ("Natural Selection", "Students learn how organisms with favorable traits are more likely to survive and reproduce."),
        ("Classification of Living Things", "Students learn how living organisms are grouped into a system of taxonomic categories."),
        ("Ecosystems and Habitats", "Students learn about the relationships between organisms and the environments in which they live."),
        ("Food Chains and Food Webs", "Students learn how energy flows through an ecosystem via food chains and food webs."),
        ("Producers, Consumers, and Decomposers", "Students learn the different roles organisms play in the flow of energy through an ecosystem."),
        ("Biomes of the World", "Students learn about the major biomes and ecosystems found around the globe."),
        ("Population and Community Ecology", "Students learn how different species interact within an ecological community."),
        ("Human Impact on the Environment", "Students learn how human activities affect ecosystems and natural habitats."),
        ("Biodiversity and Conservation", "Students learn why the variety of living things is important and how it can be protected."),
        ("Microorganisms: Bacteria and Viruses", "Students learn the basic characteristics of bacteria and viruses."),
        ("Plant Structure and Function", "Students learn the roles of roots, stems, and leaves in a plant's survival."),
        ("Plant Reproduction", "Students learn how flowering plants reproduce, including pollination and seed formation."),
        ("Animal Classification", "Students learn the difference between vertebrates and invertebrates and their major groups."),
        ("Homeostasis", "Students learn how organisms maintain a stable internal environment despite outside changes."),
    ],
    "Philosophy": [
        ("What is Knowledge? An Introduction to Epistemology", "Students explore basic philosophical questions about how we know what we know."),
        ("The Nature of Reality: An Introduction to Metaphysics", "Students explore philosophical questions about what truly exists."),
        ("What Makes an Action Right or Wrong?", "Students are introduced to basic ethical thinking about right and wrong actions."),
        ("The Trolley Problem", "Students examine a classic thought experiment that raises difficult questions about moral choices."),
        ("What is Justice?", "Students explore different philosophical ideas about fairness and justice."),
        ("The Allegory of the Cave", "Students examine Plato's famous thought experiment about perception, illusion, and reality."),
        ("Socratic Questioning", "Students practice asking deep, probing questions in the style of Socrates."),
        ("What is Happiness?", "Students explore philosophical perspectives on what it truly means to live a good life."),
        ("Free Will versus Determinism", "Students explore the debate over whether humans truly choose their own actions."),
        ("The Mind-Body Problem", "Students explore philosophical questions about the relationship between the mind and the body."),
        ("Personal Identity Over Time", "Students explore what makes a person the same individual as they change over time."),
        ("The Ship of Theseus", "Students examine a classic thought experiment about identity and change."),
        ("Utilitarianism: The Greatest Good", "Students learn about the ethical theory that right actions maximize overall happiness."),
        ("Deontology: Duty and Rules", "Students learn about the ethical theory that some actions are right or wrong regardless of outcome."),
        ("Virtue Ethics", "Students learn about the ethical theory that good character leads to good actions."),
        ("Introduction to Logic and Arguments", "Students learn the basic structure of a philosophical argument."),
        ("What is Truth?", "Students explore different philosophical theories about what makes a statement true."),
        ("Skepticism", "Students explore philosophical questions about what we can truly be certain of."),
        ("The Problem of Evil", "Students explore the philosophical question of why suffering exists in the world."),
        ("Existentialism: Finding Meaning", "Students learn about the philosophical idea that individuals create their own meaning in life."),
        ("Stoicism: Controlling What You Can", "Students learn ancient Stoic ideas about focusing on what is within one's control."),
        ("Confucian Philosophy", "Students learn about Confucius's ideas concerning ethics, family, and society."),
        ("Buddhist Philosophy: The Four Noble Truths", "Students learn the basic Buddhist teachings about the causes and end of suffering."),
        ("Social Contract Theory", "Students learn the idea that governments derive their authority from the consent of the governed."),
        ("Animal Rights and Moral Consideration", "Students explore philosophical questions about how humans should treat animals."),
        ("Environmental Ethics", "Students explore philosophical questions about human responsibility toward nature."),
        ("The Ethics of Lying", "Students explore philosophical questions about whether and when lying can be justified."),
        ("Thought Experiments in Philosophy", "Students learn how hypothetical scenarios help philosophers test and refine ideas."),
        ("What is Beauty? An Introduction to Aesthetics", "Students explore philosophical questions about art, beauty, and taste."),
        ("Philosophy of Friendship", "Students explore what philosophers have said about the nature and value of friendship."),
        ("The Value of Wisdom", "Students explore what it means to be wise rather than merely knowledgeable."),
        ("Cultural Relativism versus Moral Universalism", "Students explore the debate over whether morality differs across cultures or is universal."),
        ("The Philosophy of Fairness in Games and Rules", "Students apply philosophical ideas about fairness to everyday games and rules."),
        ("Introduction to Political Philosophy", "Students explore basic philosophical questions about power, authority, and governance."),
        ("Philosophy of Science", "Students explore how philosophers think about what counts as genuine scientific knowledge."),
        ("The Examined Life", "Students explore Socrates's idea that self-reflection is essential to living a good life."),
        ("Philosophy and Technology", "Students explore ethical questions raised by new and emerging technologies."),
        ("Comparing Eastern and Western Philosophical Traditions", "Students compare broad differences between Eastern and Western philosophical approaches."),
        ("Constructing Your Own Philosophical Argument", "Students practice building and defending their own reasoned philosophical position."),
    ],
    "Critical Thinking": [
        ("What is Critical Thinking?", "Students are introduced to the practice of thinking clearly, carefully, and rationally."),
        ("Identifying Assumptions", "Students learn to recognize the unstated beliefs that underlie an argument."),
        ("Distinguishing Fact from Opinion", "Students learn to tell verifiable factual claims apart from personal opinions."),
        ("Evaluating Sources of Information", "Students learn to judge how reliable a source of information is."),
        ("Deductive Reasoning", "Students learn how to draw specific, certain conclusions from general premises."),
        ("Inductive Reasoning", "Students learn how to draw general conclusions from specific observations."),
        ("Constructing a Valid Argument", "Students learn how to build an argument with sound logical structure."),
        ("Identifying Premises and Conclusions", "Students learn to break an argument down into its supporting premises and conclusion."),
        ("Correlation versus Causation", "Students learn why two things happening together does not always mean one causes the other."),
        ("Recognizing Bias in Arguments", "Students learn to identify when a source presents a slanted or one-sided point of view."),
        ("Confirmation Bias", "Students learn about the tendency to favor information that confirms what we already believe."),
        ("Evaluating Statistics and Data Claims", "Students learn to question how numerical data was collected and presented."),
        ("Recognizing Misleading Graphs", "Students learn how visuals and graphs can be designed to distort the true meaning of data."),
        ("Analyzing Advertisements Critically", "Students learn to identify persuasive techniques commonly used in advertising."),
        ("Propaganda Techniques", "Students learn to recognize common tactics used to influence public opinion."),
        ("Evaluating Arguments by Authority", "Students learn to critically question claims that are based solely on expert opinion."),
        ("The Difference Between Evidence and Anecdote", "Students learn why a single personal story is not strong evidence for a general claim."),
        ("Recognizing Emotional Appeals", "Students learn to identify when emotion is used in place of sound reasoning."),
        ("Steelmanning versus Strawmanning Arguments", "Students learn the difference between fairly representing an opposing view and unfairly distorting it."),
        ("Asking Good Questions", "Students develop the habit of asking thoughtful, probing questions."),
        ("Problem-Solving Strategies", "Students learn systematic approaches for working through a difficult problem."),
        ("Making Decisions Under Uncertainty", "Students learn strategies for weighing options when outcomes are not fully known."),
        ("Cost-Benefit Thinking", "Students learn to weigh the advantages and disadvantages of a decision before making it."),
        ("Recognizing Groupthink", "Students learn how group pressure can lead individuals to make poor decisions."),
        ("The Socratic Method in Practice", "Students practice using structured questioning to examine and test ideas."),
        ("Evaluating Online Information", "Students learn to spot misinformation and unreliable claims found on the internet."),
        ("Understanding Sample Size and Bias in Surveys", "Students learn why the way data is collected affects how trustworthy a survey is."),
        ("Recognizing False Dilemmas", "Students learn to identify when only two options are unfairly presented as the only choices."),
        ("Slippery Slope Reasoning", "Students learn to recognize when a chain of unlikely consequences is used to argue against an idea."),
        ("Circular Reasoning", "Students learn to recognize arguments that simply assume the very thing they are trying to prove."),
        ("Evaluating Cause-and-Effect Claims", "Students learn to test whether a claimed cause truly explains an observed effect."),
        ("Analogical Reasoning", "Students learn how comparing similar situations can support or weaken an argument."),
        ("Recognizing Loaded Language", "Students learn to notice when word choice is used to sway opinion rather than inform."),
        ("Fact-Checking Strategies", "Students learn practical steps for verifying whether a claim is accurate."),
        ("Thinking About Thinking: Metacognition", "Students learn to reflect on and improve their own thought processes."),
        ("Structured Debate Skills", "Students practice presenting and respectfully defending a position in a structured debate."),
        ("Recognizing Manipulative Persuasion Tactics", "Students learn to identify manipulation techniques used in conversation and media."),
        ("Evaluating Scientific Claims", "Students learn to distinguish well-supported scientific claims from pseudoscience."),
        ("Building a Habit of Reflective Thinking", "Students practice regular reflection as a way to improve their own decision-making."),
    ],
    "Health Education": [
        ("Understanding Mental Health", "Students learn the basics of mental well-being and why it matters alongside physical health."),
        ("Stress Management Techniques", "Students learn healthy strategies for coping with everyday stress."),
        ("Anxiety and Depression Awareness", "Students learn to recognize common signs of anxiety and depression and where to seek help."),
        ("Building Healthy Relationships", "Students learn the qualities that make friendships and relationships respectful and supportive."),
        ("Communication Skills for Healthy Relationships", "Students learn to express their needs and listen effectively in relationships."),
        ("Understanding Peer Pressure", "Students learn to recognize peer pressure and practice healthy ways of responding to it."),
        ("Body Image and Self-Esteem", "Students learn to develop a healthy and realistic view of their own body and worth."),
        ("Sleep and Its Importance", "Students learn how adequate sleep supports physical and mental health."),
        ("Understanding the Food Guide and Balanced Meals", "Students learn how to build balanced, nutritious meals using food group guidelines."),
        ("Reading Nutrition Labels", "Students learn to interpret the nutrition information found on food packaging."),
        ("Understanding Portion Sizes", "Students learn to recognize appropriate serving sizes for different foods."),
        ("Hydration and the Body", "Students learn why adequate water intake is important for overall health."),
        ("Physical Activity Guidelines for Teens", "Students learn the recommended amount and type of physical activity for their age group."),
        ("Understanding Puberty and Body Changes", "Students learn about the physical and emotional changes that occur during adolescence."),
        ("Personal Hygiene Practices", "Students learn daily habits that support cleanliness and personal health."),
        ("Understanding Vaccines and Immunization", "Students learn how vaccines work to help prevent the spread of disease."),
        ("Common Communicable Diseases", "Students learn how common illnesses spread and basic ways to prevent them."),
        ("Understanding Chronic Diseases", "Students learn basic facts about long-term conditions such as diabetes and asthma."),
        ("Tobacco and Vaping Risks", "Students learn about the health risks associated with tobacco and vaping products."),
        ("Alcohol Awareness", "Students learn about the health risks associated with alcohol use."),
        ("Understanding Addiction", "Students learn how addiction affects the brain and influences behavior."),
        ("Making Healthy Decisions", "Students learn a simple framework for thinking through health-related choices."),
        ("Understanding Healthcare Systems", "Students learn the basics of how to access common healthcare services."),
        ("Setting Personal Health Goals", "Students learn to create achievable, personal goals for improving well-being."),
        ("Screen Time and Digital Wellness", "Students learn strategies for balancing technology use with healthy daily habits."),
        ("Online Safety and Digital Citizenship", "Students learn how to stay safe and behave respectfully in online spaces."),
        ("Understanding Consent Beyond Physical Boundaries", "Students learn to apply the concept of consent to everyday interactions and communication."),
        ("Recognizing and Preventing Bullying and Cyberbullying", "Students learn to identify bullying behavior, both in person and online, and how to respond."),
        ("Coping with Grief and Loss", "Students learn healthy ways to process difficult emotions related to grief and loss."),
        ("Understanding Body Systems and Disease Prevention", "Students learn how healthy daily habits help protect the body's major systems."),
        ("Environmental Health", "Students learn how the surrounding environment can affect personal and community health."),
        ("Community Health Resources", "Students learn to identify local resources and services that support health."),
        ("Understanding Health Insurance Basics", "Students receive a simple introduction to how health insurance works."),
        ("Advocacy for Personal and Community Health", "Students learn how to take action to promote health for themselves and their community."),
    ],
    "ICT & Computer Science": [
        ("Introduction to Computer Hardware", "Students learn about the basic physical components that make up a computer."),
        ("Introduction to Computer Software", "Students learn the difference between system software and application software."),
        ("How the Internet Works", "Students learn the basics of how networks, servers, and data transfer make the internet work."),
        ("Introduction to Programming Concepts", "Students learn foundational programming ideas such as variables, loops, and basic logic."),
        ("Introduction to Python Programming", "Students learn to write simple programs using the Python programming language."),
        ("Variables and Data Types", "Students learn how to store and work with different kinds of data in code."),
        ("Conditional Statements", "Students learn to use if/else logic to make decisions within a program."),
        ("Loops in Programming", "Students learn to repeat actions in code using for loops and while loops."),
        ("Functions and Reusable Code", "Students learn to organize code into reusable functions."),
        ("Introduction to Algorithms", "Students learn how algorithms provide step-by-step procedures for solving problems."),
        ("Flowcharts and Pseudocode", "Students learn to plan a program's logic using flowcharts and pseudocode before writing code."),
        ("Debugging Basics", "Students learn basic strategies for finding and fixing errors in their code."),
        ("Introduction to Web Development: HTML", "Students learn to structure a simple web page using HTML."),
        ("Introduction to Web Development: CSS", "Students learn to style a web page's appearance using CSS."),
        ("Introduction to Databases", "Students learn the basics of how data is organized and stored in a database."),
        ("Spreadsheets and Data Analysis", "Students learn to use spreadsheets to organize, calculate, and analyze data."),
        ("Introduction to Cybersecurity", "Students learn basic concepts involved in protecting digital information."),
        ("Password Security and Authentication", "Students learn how to create strong passwords and protect their online accounts."),
        ("Understanding Malware and Viruses", "Students learn how malicious software can affect computers and how to avoid it."),
        ("Safe Internet Browsing Habits", "Students learn to recognize and avoid common risks while browsing online."),
        ("Digital Citizenship", "Students learn about responsible and ethical behavior when using technology and the internet."),
        ("Understanding Cyberbullying and Online Harassment", "Students learn to recognize and respond appropriately to bullying that occurs online."),
        ("Introduction to Cloud Computing", "Students learn the basics of how data and services can be stored and accessed online."),
        ("File Management and Organization", "Students learn strategies for organizing digital files and folders effectively."),
        ("Introduction to Binary Numbers", "Students learn how computers represent information using ones and zeros."),
        ("How Computers Process Information", "Students learn the basics of how a computer fetches and executes instructions."),
        ("Introduction to Networks", "Students learn the basics of how devices connect and communicate with one another."),
        ("Understanding the World Wide Web versus the Internet", "Students learn to distinguish between the internet as infrastructure and the web as a service on it."),
        ("Introduction to Robotics", "Students learn basic principles behind how robots sense their environment and take action."),
        ("Computational Thinking", "Students learn to break complex problems down into smaller, more manageable parts."),
        ("Introduction to Game Design", "Students learn basic principles involved in designing a simple digital game."),
        ("Digital Media Creation", "Students learn to create and edit digital images, audio, or video."),
        ("Introduction to Data Privacy", "Students learn how personal data is collected online and basic ways it can be protected."),
        ("Ethics in Computing", "Students learn about ethical considerations involved in developing and using technology."),
        ("History of Computing", "Students learn about key milestones in the historical development of computers."),
        ("Introduction to Version Control", "Students learn the basic purpose of tracking and managing changes to code over time."),
        ("Understanding Search Engines", "Students learn the basics of how search engines find and rank information."),
        ("Introduction to Wearable and Smart Devices", "Students learn the basics of how everyday smart and wearable devices work."),
        ("Careers in Computer Science and ICT", "Students explore possible career paths and opportunities within computer science and ICT."),
    ],
}
