GRADE = 10
MODULES: dict[str, list[tuple[str, str]]] = {
    "General Knowledge": [
        ("World Geography: Continents and Oceans", "Students learn the names, locations, and key features of Earth's continents and oceans."),
        ("Major World Rivers and Their Basins", "Students explore the world's longest rivers and the regions and economies that depend on them."),
        ("Mountain Ranges of the World", "Students identify major mountain ranges and understand how they form and influence climate and settlement."),
        ("World Capitals and Countries", "Students learn to match countries with their capital cities across every continent."),
        ("International Organizations: United Nations", "Students learn how the United Nations is structured and its role in maintaining global peace and cooperation."),
        ("International Organizations: WHO, UNESCO, and UNICEF", "Students learn the missions of major UN agencies that focus on health, education, and children's welfare."),
        ("Major World Currencies", "Students learn the currencies used by major world economies and how currency names relate to national identity."),
        ("Landmark Inventions That Changed the World", "Students study inventions such as the printing press, electricity, and the internet and their global impact."),
        ("Nobel Prize Categories and Notable Laureates", "Students learn the categories of the Nobel Prize and examples of laureates who shaped their fields."),
        ("World Religions: Beliefs and Practices", "Students gain a respectful overview of the core beliefs and practices of major world religions."),
        ("Ancient Wonders of the World", "Students learn about the Seven Wonders of the Ancient World and their historical significance."),
        ("Modern Wonders and Engineering Marvels", "Students explore modern engineering achievements such as skyscrapers, dams, and long-span bridges."),
        ("World Sporting Events: The Olympics", "Students learn the history, values, and global significance of the Olympic Games."),
        ("World Sporting Events: The FIFA World Cup", "Students learn how the FIFA World Cup unites nations around football every four years."),
        ("Space Exploration Milestones", "Students trace key milestones in space exploration from the first satellite to modern missions."),
        ("Famous Scientists and Their Discoveries", "Students learn about scientists whose discoveries transformed our understanding of the natural world."),
        ("National Symbols: Flags, Anthems, and Emblems", "Students learn how flags, anthems, and emblems represent national identity and history."),
        ("World Time Zones and the International Date Line", "Students learn how the Earth is divided into time zones and why the International Date Line exists."),
        ("Major Deserts of the World", "Students learn about the world's largest deserts and the unique life that survives there."),
        ("Major World Languages and Language Families", "Students explore how languages are grouped into families and which languages are most widely spoken."),
        ("World Population Trends", "Students examine how global population has grown and where people live today."),
        ("Climate Zones of the World", "Students learn how climate zones are classified and how they shape ecosystems and cultures."),
        ("Endangered Species and Conservation", "Students learn about species at risk of extinction and global efforts to protect them."),
        ("Renewable and Non-Renewable Resources", "Students distinguish between resources that can be replenished and those that cannot."),
        ("World Trade and Global Supply Chains", "Students learn how goods move between countries and why global trade matters."),
        ("Global News Literacy and Fact-Checking", "Students learn strategies for evaluating the accuracy of international news reports."),
        ("Famous Explorers and Voyages of Discovery", "Students study explorers whose voyages expanded human knowledge of the globe."),
        ("Historic Treaties and Their Global Impact", "Students learn about treaties that ended wars or reshaped international relations."),
        ("World Art Movements", "Students survey major art movements and the cultural contexts that produced them."),
        ("World Literature: Notable Authors and Works", "Students are introduced to influential authors and literary works from around the globe."),
        ("World Cinema and Film Awards", "Students learn about international film industries and major global film awards."),
        ("Global Cuisines and Food Culture", "Students explore how geography and history shape traditional cuisines around the world."),
        ("World Festivals and Cultural Celebrations", "Students learn about festivals celebrated by different cultures and their meanings."),
        ("Currency Exchange and Global Markets Basics", "Students learn how currency values are compared and why exchange rates fluctuate."),
        ("The United Nations Sustainable Development Goals", "Students learn about the 17 global goals for ending poverty and protecting the planet by 2030."),
        ("Major International Sporting Bodies", "Students learn about organizations that govern global sports such as the IOC and FIFA."),
        ("Space Agencies Around the World", "Students learn about national and international agencies that conduct space research."),
        ("Notable World Leaders in History", "Students study leaders whose decisions shaped the course of world history."),
        ("World Heritage Sites (UNESCO)", "Students learn how UNESCO identifies and protects places of outstanding cultural or natural value."),
        ("Global Health Organizations and Their Roles", "Students learn how international bodies coordinate responses to global health challenges."),
        ("Famous Bridges and Structures of the World", "Students learn about iconic bridges and structures and the engineering behind them."),
        ("World Records and Achievements", "Students explore notable human achievements and records recognized internationally."),
        ("Global Internet and Technology Milestones", "Students trace key developments in the growth of the internet and digital technology worldwide."),
        ("Awards and Honors: Pulitzer, Grammy, and Oscar", "Students learn what these prestigious awards recognize and their cultural significance."),
        ("Major World Newspapers and Media Outlets", "Students learn about influential newspapers and media organizations around the world."),
        ("Comparative World Government Systems", "Students compare how different countries organize their governments and distribute power."),
        ("Global Environmental Agreements", "Students learn about international agreements aimed at addressing climate change and pollution."),
        ("World Population: Most and Least Populous Nations", "Students compare countries by population size and consider the challenges each faces."),
        ("Current Affairs: Reading and Analysing the News", "Students practice following current events and forming informed opinions about them."),
    ],
    "Social Studies": [
        ("The Origins of Democracy", "Students trace the roots of democratic government from ancient Athens to modern states."),
        ("Forms of Government: Monarchy, Republic, and Federation", "Students compare different ways countries organize and exercise political authority."),
        ("The Structure of the United Nations", "Students learn how the UN's main bodies work together to address global issues."),
        ("Human Rights and the Universal Declaration", "Students study the Universal Declaration of Human Rights and its global influence."),
        ("The Industrial Revolution and Its Social Impact", "Students examine how industrialization transformed work, cities, and family life."),
        ("Colonialism and Decolonization", "Students learn how colonial rule spread and how nations gained independence in the 20th century."),
        ("The Cold War: Causes and Consequences", "Students study the ideological rivalry between the US and USSR and its global effects."),
        ("World War I: Causes and Outcomes", "Students examine the causes, major events, and lasting consequences of World War I."),
        ("World War II: Causes and Outcomes", "Students examine the causes, major events, and lasting consequences of World War II."),
        ("The Rise of Nationalism", "Students explore how nationalist movements shaped borders and conflicts across history."),
        ("Civil Rights Movements Around the World", "Students study movements that fought for equal rights and their lasting impact on society."),
        ("The Role of the Judiciary in Society", "Students learn how courts interpret laws and protect citizens' rights."),
        ("Federal vs Unitary Government Systems", "Students compare how power is divided between national and regional governments in different systems."),
        ("Elections and the Electoral Process", "Students learn how elections are organized and why voting matters in a democracy."),
        ("Political Parties and Their Roles", "Students learn how political parties form, compete, and represent different viewpoints."),
        ("Constitutions and the Rule of Law", "Students learn how constitutions establish government structure and limit power."),
        ("Citizenship and Civic Responsibility", "Students explore the rights and responsibilities that come with being a citizen."),
        ("Social Stratification and Class", "Students learn how societies are organized into different social and economic classes."),
        ("Urbanization and Its Social Effects", "Students examine how the growth of cities changes societies and daily life."),
        ("Migration and Its Causes and Effects", "Students study why people migrate and how migration affects both origin and destination communities."),
        ("Globalization and Cultural Exchange", "Students explore how globalization connects economies and cultures around the world."),
        ("Media's Role in Society and Politics", "Students examine how media shapes public opinion and political discourse."),
        ("Public Policy and Decision Making", "Students learn how governments identify problems and design policies to address them."),
        ("Local Government and Community Services", "Students learn how local governments provide services like schools, roads, and utilities."),
        ("International Diplomacy and Treaties", "Students learn how countries negotiate agreements to resolve disputes and cooperate."),
        ("The League of Nations and Its Legacy", "Students study the first international peacekeeping organization and why it ultimately failed."),
        ("Human Geography: Population Distribution", "Students examine why populations concentrate in certain regions and not others."),
        ("Economic Systems: Capitalism, Socialism, and Mixed Economies", "Students compare how different economic systems organize production and distribution."),
        ("Social Movements and Advocacy", "Students study how organized groups campaign for social and political change."),
        ("The History of Slavery and Abolition", "Students learn about the history of slavery and the movements that brought about its abolition."),
        ("Ancient Civilizations: Mesopotamia and Egypt", "Students explore the achievements and social structures of two of the earliest civilizations."),
        ("Ancient Civilizations: Greece and Rome", "Students study the political and cultural legacies of ancient Greece and Rome."),
        ("The Renaissance and Its Social Impact", "Students learn how the Renaissance transformed art, science, and society in Europe."),
        ("The Enlightenment and Political Thought", "Students study Enlightenment thinkers whose ideas shaped modern political systems."),
        ("Revolutions: American and French", "Students compare the causes and outcomes of the American and French Revolutions."),
        ("The United Nations Peacekeeping Role", "Students learn how UN peacekeeping missions attempt to maintain stability in conflict zones."),
        ("Refugees and International Humanitarian Law", "Students learn about the rights of refugees and the laws designed to protect them."),
        ("Gender Equality and Social Change", "Students examine historical and ongoing efforts to achieve gender equality worldwide."),
        ("Indigenous Peoples and Cultural Preservation", "Students learn about the histories and cultural preservation efforts of Indigenous peoples."),
        ("Comparative Cultures and Traditions", "Students compare traditions and customs across different world cultures."),
        ("The Concept of the Nation-State", "Students explore how the modern nation-state developed and what defines it."),
        ("The History of Trade Unions and Labour Rights", "Students learn how trade unions formed to improve working conditions and wages."),
        ("The Political Spectrum: Left, Right, and Centre", "Students learn how political positions are commonly categorized along a spectrum."),
        ("Understanding the Census and Demographic Data", "Students learn how censuses collect population data and why that data matters for policy."),
        ("The Role of Non-Governmental Organizations (NGOs)", "Students learn how NGOs address social, humanitarian, and environmental issues worldwide."),
        ("War and Peace: International Conflict Resolution", "Students study methods used to resolve conflicts between nations peacefully."),
        ("Historical Empires: Rise and Fall", "Students examine patterns in how empires expand, thrive, and eventually decline."),
        ("The Silk Road and Early Globalization", "Students learn how ancient trade routes connected distant civilizations and cultures."),
        ("Social Studies Skills: Analysing Primary and Secondary Sources", "Students practice evaluating historical sources to understand different perspectives on events."),
    ],
    "Physical Education & Self-Defense": [
        ("Principles of Physical Fitness", "Students learn the core principles that guide safe and effective physical training."),
        ("Components of Health-Related Fitness", "Students learn the five components of fitness: strength, endurance, flexibility, and body composition."),
        ("Warm-Up and Cool-Down Techniques", "Students learn how proper warm-ups and cool-downs prevent injury and aid recovery."),
        ("Muscular Strength and Endurance Training", "Students learn methods for safely building muscular strength and endurance."),
        ("Cardiovascular Endurance and Aerobic Training", "Students learn how aerobic exercise improves heart and lung health."),
        ("Flexibility and Stretching Techniques", "Students learn stretching methods that improve flexibility and reduce injury risk."),
        ("Basic Rules of Basketball", "Students learn the fundamental rules and skills needed to play basketball."),
        ("Basic Rules of Football (Soccer)", "Students learn the fundamental rules and skills needed to play football."),
        ("Basic Rules of Volleyball", "Students learn the fundamental rules and skills needed to play volleyball."),
        ("Basic Rules of Badminton", "Students learn the fundamental rules and skills needed to play badminton."),
        ("Basic Rules of Table Tennis", "Students learn the fundamental rules and skills needed to play table tennis."),
        ("Track and Field Events", "Students learn the range of running, jumping, and throwing events in track and field."),
        ("Swimming Techniques and Water Safety", "Students learn basic swimming strokes and essential water safety practices."),
        ("Gymnastics Fundamentals", "Students learn basic gymnastics movements and the importance of balance and control."),
        ("Yoga and Mindfulness for Fitness", "Students learn yoga poses and breathing techniques that support physical and mental wellbeing."),
        ("Team Sports and Cooperative Play", "Students learn how communication and cooperation lead to success in team sports."),
        ("Individual Sports and Personal Goal Setting", "Students learn how to set and track personal performance goals in individual sports."),
        ("Sports Nutrition Basics", "Students learn how diet affects athletic performance and recovery."),
        ("Hydration and Exercise Performance", "Students learn why proper hydration is essential before, during, and after exercise."),
        ("Injury Prevention in Sports", "Students learn strategies to reduce the risk of common sports injuries."),
        ("Common Sports Injuries and First Response", "Students learn to recognize common injuries and respond appropriately until help arrives."),
        ("The Skeletal System and Movement", "Students learn how bones and joints work together to enable movement."),
        ("The Muscular System and Exercise", "Students learn how muscles contract and adapt in response to exercise."),
        ("Principles of Self-Defense", "Students learn the core principles of self-defense, including awareness, avoidance, and response."),
        ("Basic Self-Defense Stances and Movements", "Students learn fundamental stances and movements used in self-defense training."),
        ("Situational Awareness and Personal Safety", "Students learn how to recognize and avoid potentially unsafe situations."),
        ("De-escalation Techniques in Conflict", "Students learn verbal strategies to calm and defuse tense situations before they escalate."),
        ("Martial Arts Fundamentals", "Students are introduced to basic martial arts principles such as balance, control, and discipline."),
        ("Grappling and Escape Techniques Basics", "Students learn basic techniques for escaping holds safely under supervision."),
        ("Self-Defense Against Common Grabs and Holds", "Students learn basic responses to common grabs, taught safely and with supervision."),
        ("Legal and Ethical Aspects of Self-Defense", "Students learn what the law permits in self-defense situations and the importance of proportionate response."),
        ("Building Confidence Through Physical Training", "Students learn how consistent physical training can build confidence and resilience."),
        ("Fitness Testing and Assessment", "Students learn how standard fitness tests measure different aspects of physical health."),
        ("Designing a Personal Fitness Plan", "Students learn to create a fitness plan tailored to their own goals and abilities."),
        ("Effects of Exercise on the Cardiovascular System", "Students learn how regular exercise strengthens the heart and improves circulation."),
        ("Effects of Exercise on Mental Health", "Students learn how physical activity can reduce stress and improve mood."),
        ("Sportsmanship and Fair Play", "Students learn the values of respect, honesty, and fairness in competitive sport."),
        ("Rules and Officiating in Sports", "Students learn how referees and officials enforce rules and maintain fair competition."),
        ("Coaching Principles and Techniques", "Students learn basic principles used by coaches to help athletes improve."),
        ("Recreational and Outdoor Activities", "Students explore activities such as camping and orienteering that build fitness outdoors."),
        ("Hiking and Wilderness Safety", "Students learn essential safety practices for hiking and spending time outdoors."),
        ("Dance as Physical Activity", "Students learn how dance builds coordination, rhythm, and cardiovascular fitness."),
        ("Cycling Safety and Techniques", "Students learn safe cycling practices and basic bike-handling skills."),
        ("Understanding Performance-Enhancing Substances and Their Risks", "Students learn about the health risks and ethical issues surrounding performance-enhancing substances."),
        ("Rest, Recovery, and Overtraining", "Students learn why rest is essential to training and how to recognize overtraining."),
        ("Goal Setting in Athletic Performance", "Students learn to set realistic, measurable goals to improve athletic performance."),
        ("Teamwork and Communication in Sports", "Students learn how effective communication improves performance in team settings."),
        ("History and Evolution of the Olympic Games", "Students learn how the Olympic Games developed from ancient Greece to today."),
        ("Lifelong Fitness and Healthy Habits", "Students learn strategies for maintaining physical activity and healthy habits throughout life."),
    ],
    "Economics": [
        ("Introduction to Economics: Scarcity and Choice", "Students learn how limited resources force individuals and societies to make choices."),
        ("Needs vs Wants in Economic Decision Making", "Students learn to distinguish between needs and wants when making economic decisions."),
        ("Opportunity Cost and Trade-Offs", "Students learn how every choice involves giving up an alternative, known as opportunity cost."),
        ("Factors of Production", "Students learn the four factors of production: land, labour, capital, and entrepreneurship."),
        ("Supply and Demand Basics", "Students learn how supply and demand interact to determine prices in a market."),
        ("Market Equilibrium and Price Determination", "Students learn how markets reach equilibrium where supply equals demand."),
        ("Types of Economic Systems", "Students compare traditional, command, market, and mixed economic systems."),
        ("Microeconomics: The Individual Consumer", "Students learn how consumers make decisions to maximize their satisfaction within a budget."),
        ("Microeconomics: The Firm and Production", "Students learn how firms decide what and how much to produce."),
        ("Elasticity of Demand", "Students learn how sensitive quantity demanded is to changes in price."),
        ("Elasticity of Supply", "Students learn how sensitive quantity supplied is to changes in price."),
        ("Market Structures: Perfect Competition", "Students learn the characteristics of markets with many small competing firms."),
        ("Market Structures: Monopoly", "Students learn how a single dominant firm can affect prices and consumer choice."),
        ("Market Structures: Oligopoly", "Students learn how a small number of large firms can shape competition in a market."),
        ("The Role of Government in the Economy", "Students learn how governments regulate markets and provide public services."),
        ("Taxation: Types and Purposes", "Students learn about different types of taxes and why governments collect them."),
        ("Public Goods and Externalities", "Students learn why some goods are provided publicly and how actions can affect third parties."),
        ("Market Failure and Government Intervention", "Students learn situations where markets fail to allocate resources efficiently."),
        ("International Trade: Comparative Advantage", "Students learn why countries benefit from specializing and trading with each other."),
        ("Tariffs, Quotas, and Trade Barriers", "Students learn how governments use trade barriers to protect domestic industries."),
        ("Exchange Rates and Currency Markets", "Students learn how currency values are determined and how they affect trade."),
        ("The Balance of Payments", "Students learn how countries record their financial transactions with the rest of the world."),
        ("Economic Growth and Development", "Students learn what drives long-term economic growth and improved living standards."),
        ("Measuring Economic Development: HDI", "Students learn how the Human Development Index measures wellbeing beyond income."),
        ("Poverty and Income Inequality", "Students learn how poverty and inequality are measured and their social consequences."),
        ("The Business Cycle", "Students learn how economies move through periods of expansion and contraction."),
        ("Fiscal Policy: Government Spending and Taxation", "Students learn how governments use spending and taxation to influence the economy."),
        ("Monetary Policy and Central Banks", "Students learn how central banks use interest rates to manage the economy."),
        ("Interest Rates and Their Economic Effects", "Students learn how changes in interest rates affect borrowing, saving, and spending."),
        ("Inflation: Causes and Consequences", "Students learn what causes inflation and how it affects purchasing power."),
        ("Deflation and Its Economic Risks", "Students learn how falling prices can create risks for an economy."),
        ("Unemployment: Types and Causes", "Students learn the different types of unemployment and what causes each."),
        ("Labour Markets and Wages", "Students learn how wages are determined by the supply and demand for labour."),
        ("The Role of Banks in the Economy", "Students learn how banks channel savings into loans and investment."),
        ("Money and Its Functions", "Students learn the functions money serves as a medium of exchange, store of value, and unit of account."),
        ("Economic Indicators and Their Uses", "Students learn how indicators like GDP and inflation help track economic health."),
        ("Globalization and the World Economy", "Students learn how globalization has increased economic interdependence between countries."),
        ("Developing vs Developed Economies", "Students compare the characteristics of developing and developed economies."),
        ("Sustainable Development and Economics", "Students learn how economic growth can be balanced with environmental sustainability."),
        ("Environmental Economics Basics", "Students learn how economics analyses environmental costs and benefits."),
        ("Behavioural Economics: How People Really Decide", "Students learn how psychological factors influence economic decision-making."),
        ("Entrepreneurship and Innovation in the Economy", "Students learn how entrepreneurs and innovation drive economic growth."),
        ("Supply Chains and Global Production", "Students learn how products are made and assembled across multiple countries."),
        ("Economic Sectors: Primary, Secondary, and Tertiary", "Students learn how economic activity is grouped into primary, secondary, and tertiary sectors."),
        ("Cooperatives and Alternative Business Models", "Students learn how cooperatives and social enterprises operate differently from traditional firms."),
        ("The Stock Market and Capital Markets", "Students learn how stock markets allow companies to raise capital and investors to trade shares."),
        ("Consumer Protection and Economic Rights", "Students learn about laws that protect consumers in economic transactions."),
        ("Circular Flow of Income Model", "Students learn how money flows between households, firms, and the government in an economy."),
        ("Economic Systems in Comparative Perspective: Case Studies", "Students compare real-world examples of how different countries organize their economies."),
    ],
    "Finance": [
        ("Understanding Money and Its Functions", "Students learn the roles money plays as a medium of exchange, store of value, and unit of account."),
        ("Budgeting Basics", "Students learn how to plan income and expenses using a simple budget."),
        ("Creating a Personal Budget", "Students practice building a realistic personal budget based on sample income and expenses."),
        ("Needs vs Wants in Personal Spending", "Students learn to prioritize essential needs over optional wants when spending money."),
        ("Saving Strategies for Teens", "Students learn practical strategies for setting aside money toward short and long-term goals."),
        ("Understanding Bank Accounts: Checking vs Savings", "Students learn the differences between checking and savings accounts and when to use each."),
        ("How Interest Works: Simple vs Compound", "Students learn the difference between simple and compound interest and how each affects savings."),
        ("Introduction to Credit and Credit Scores", "Students learn what credit is and how credit scores are used to assess financial trustworthiness."),
        ("Understanding Credit Cards and Their Risks", "Students learn how credit cards work and the risks of carrying a balance."),
        ("Debt: Good Debt vs Bad Debt", "Students learn to distinguish between debt that builds value and debt that creates financial strain."),
        ("Loans and How They Work", "Students learn how loans are structured, including principal, interest, and repayment terms."),
        ("Understanding Mortgages Basics", "Students learn the basic concepts behind borrowing money to purchase a home."),
        ("Insurance Basics: Why It Matters", "Students learn how insurance protects against unexpected financial loss."),
        ("Types of Insurance: Health, Auto, and Life", "Students learn the purpose and basic features of common types of insurance."),
        ("Introduction to Taxes and Payroll Deductions", "Students learn how taxes are deducted from income and what they fund."),
        ("Filing Basics: Understanding Tax Forms", "Students learn the basic purpose of common tax forms used when filing taxes."),
        ("Financial Goal Setting", "Students learn to set specific, achievable short-term and long-term financial goals."),
        ("Emergency Funds and Financial Safety Nets", "Students learn why setting aside an emergency fund protects against unexpected expenses."),
        ("Understanding Inflation's Effect on Savings", "Students learn how inflation can reduce the purchasing power of money saved over time."),
        ("Introduction to the Stock Market", "Students learn what stocks are and how the stock market allows people to invest in companies."),
        ("Stocks vs Bonds", "Students learn the key differences between owning stocks and owning bonds."),
        ("Mutual Funds and Index Funds Explained", "Students learn how pooled investment funds spread risk across many assets."),
        ("Risk and Return in Investing", "Students learn the relationship between the risk of an investment and its potential return."),
        ("Diversification as a Risk Management Tool", "Students learn how spreading investments across assets reduces overall risk."),
        ("Retirement Accounts Basics", "Students learn the purpose of retirement savings accounts and why starting early matters."),
        ("Compound Growth Over Time", "Students learn how compound growth can significantly increase savings over long periods."),
        ("Understanding Financial Statements", "Students learn the basic purpose of statements like account balances and transaction histories."),
        ("Identity Theft and Financial Fraud Prevention", "Students learn how to recognize and protect themselves from identity theft and fraud."),
        ("Recognizing Scams and Ponzi Schemes", "Students learn to identify warning signs of financial scams and fraudulent schemes."),
        ("Digital Payments and Mobile Banking", "Students learn how digital payment systems and mobile banking apps work securely."),
        ("Cryptocurrency Basics and Risks", "Students learn what cryptocurrency is and the risks associated with investing in it."),
        ("Financial Contracts and Reading the Fine Print", "Students learn why it is important to carefully read terms before signing financial agreements."),
        ("Consumer Rights in Financial Transactions", "Students learn about protections consumers have when dealing with banks and lenders."),
        ("Comparing Prices and Smart Shopping", "Students learn strategies for comparing prices and value before making purchases."),
        ("The True Cost of Buying on Credit", "Students learn how interest and fees increase the real cost of purchases made on credit."),
        ("Financial Planning for Big Purchases", "Students learn how to plan and save toward significant future purchases."),
        ("Understanding Payslips and Net Income", "Students learn how to read a payslip and understand the difference between gross and net pay."),
        ("Setting Up a Personal Financial Plan", "Students learn to combine budgeting, saving, and goal-setting into a personal financial plan."),
        ("Charitable Giving and Financial Values", "Students learn how personal values can shape decisions about giving and spending."),
        ("Entrepreneurship and Startup Finance Basics", "Students learn the basic financial considerations involved in starting a small business."),
        ("Understanding Business Loans and Capital", "Students learn how businesses raise capital through loans and other financing options."),
        ("Currency Exchange for Travelers", "Students learn how to exchange currency and understand exchange rates when traveling."),
        ("Financial Institutions: Banks, Credit Unions, and Online Banks", "Students learn the differences between various types of financial institutions."),
        ("The Role of the Central Bank in Personal Finance", "Students learn how central bank decisions can affect personal loans, savings, and prices."),
        ("Financial Literacy and Avoiding Lifestyle Inflation", "Students learn how rising spending with rising income can undermine financial goals."),
        ("Understanding Net Worth", "Students learn how to calculate net worth by comparing assets and liabilities."),
        ("Financial Planning for College and Further Education", "Students learn how to plan and save for the costs of continuing education."),
        ("Peer-to-Peer Lending and Alternative Finance", "Students learn how newer lending models connect borrowers and lenders directly."),
        ("Ethical and Sustainable Investing", "Students learn how some investors choose investments based on ethical or environmental criteria."),
    ],
    "First Aid": [
        ("Principles of First Aid: The DRSABCD Action Plan", "Students learn a structured approach for assessing and responding to emergencies safely."),
        ("Assessing an Emergency Scene Safely", "Students learn to check for danger before approaching an injured or ill person."),
        ("Calling for Emergency Help Effectively", "Students learn what information to provide when calling emergency services."),
        ("Basic Life Support Overview", "Students learn the fundamental steps used to sustain life until professional help arrives."),
        ("Cardiopulmonary Resuscitation (CPR) Basics", "Students learn the basic technique of CPR for someone who is not breathing."),
        ("Using an Automated External Defibrillator (AED)", "Students learn the basic steps for using an AED during a cardiac emergency."),
        ("Recovery Position and When to Use It", "Students learn how and when to place an unconscious but breathing person in the recovery position."),
        ("Choking: Recognition and Response", "Students learn to recognize choking and respond with appropriate first aid steps."),
        ("The Heimlich Maneuver", "Students learn the technique used to help clear an obstructed airway in a choking person."),
        ("Managing Severe Bleeding", "Students learn how to apply pressure and control severe bleeding until help arrives."),
        ("Wound Cleaning and Dressing Basics", "Students learn how to clean and dress minor wounds to prevent infection."),
        ("Treating Minor Cuts and Abrasions", "Students learn the correct first aid steps for treating small cuts and scrapes."),
        ("Understanding Shock and How to Respond", "Students learn to recognize the signs of shock and how to help a person experiencing it."),
        ("Head Injuries and Concussion Signs", "Students learn to recognize warning signs of a concussion after a head injury."),
        ("Spinal Injury Precautions", "Students learn why minimizing movement is critical when a spinal injury is suspected."),
        ("Sprains, Strains, and RICE Treatment", "Students learn the RICE method for treating sprains and strains."),
        ("Splinting a Suspected Fracture", "Students learn basic techniques for immobilizing a suspected broken bone."),
        ("Dislocations: Recognition and First Response", "Students learn to recognize a dislocated joint and avoid attempting to relocate it."),
        ("Heat Exhaustion and Heat Stroke", "Students learn to recognize and respond to heat-related illnesses."),
        ("Hypothermia and Cold-Related Emergencies", "Students learn to recognize and respond to dangerously low body temperature."),
        ("Frostbite: Recognition and Treatment", "Students learn to recognize frostbite and provide appropriate initial care."),
        ("Nosebleeds: First Aid Steps", "Students learn the correct steps for helping someone with a nosebleed."),
        ("Burns: Classification and Initial Treatment", "Students learn to classify burns by severity and provide appropriate initial care."),
        ("Chemical Burns and Eye Injuries", "Students learn the correct first aid response to chemical burns and eye injuries."),
        ("Electrical Injuries and Safety Precautions", "Students learn how to safely respond to electrical injuries without becoming a victim."),
        ("Poisoning: Recognition and Response", "Students learn to recognize signs of poisoning and the correct first response."),
        ("Allergic Reactions and Using an Epinephrine Auto-Injector", "Students learn to recognize severe allergic reactions and the basics of using an auto-injector."),
        ("Asthma Attacks: Recognizing and Assisting", "Students learn to recognize an asthma attack and how to help someone use their inhaler."),
        ("Seizures: How to Help Safely", "Students learn how to keep a person safe during a seizure without restraining them."),
        ("Diabetic Emergencies: Hypoglycemia and Hyperglycemia", "Students learn to recognize and respond to blood sugar emergencies."),
        ("Fainting: Causes and First Aid", "Students learn common causes of fainting and how to assist someone who has fainted."),
        ("Heart Attack: Recognizing the Warning Signs", "Students learn to recognize the warning signs of a heart attack and respond quickly."),
        ("Stroke: Recognizing FAST Symptoms", "Students learn the FAST method for recognizing stroke symptoms and acting quickly."),
        ("Bites and Stings: Insects and Animals", "Students learn appropriate first aid for common insect and animal bites and stings."),
        ("Snake Bite First Aid Basics", "Students learn the correct first aid steps to take following a snake bite."),
        ("Drowning and Water Rescue Basics", "Students learn safe ways to assist someone in the water without endangering themselves."),
        ("Preparing a Basic First Aid Kit", "Students learn what essential items belong in a well-stocked first aid kit."),
        ("First Aid for Sports Injuries", "Students learn common first aid responses to injuries that occur during sports."),
        ("Treating Blisters Properly", "Students learn the correct way to care for blisters to prevent infection."),
        ("Foreign Objects in the Eye, Ear, or Nose", "Students learn safe first aid steps for removing or managing foreign objects."),
        ("Managing Nausea and Vomiting Emergencies", "Students learn how to safely assist someone experiencing severe nausea or vomiting."),
        ("Abdominal Injuries: First Response", "Students learn the correct first response to suspected abdominal injuries."),
        ("Chest Injuries and Breathing Difficulties", "Students learn how to recognize and respond to chest injuries affecting breathing."),
        ("Mental Health Crises: Psychological First Aid", "Students learn basic principles for supporting someone experiencing a mental health crisis."),
        ("First Aid Considerations for Infants and Children", "Students learn how first aid techniques differ when caring for infants and young children."),
        ("Moving and Transporting an Injured Person Safely", "Students learn when and how to safely move an injured person."),
        ("Legal and Ethical Duties of a First Aider", "Students learn the basic legal and ethical responsibilities involved in giving first aid."),
        ("Infection Control and Universal Precautions", "Students learn how to protect themselves and others from infection while giving first aid."),
        ("Building a Personal Emergency Action Plan", "Students learn to create a simple plan for responding to emergencies at home or school."),
    ],
    "Physics": [
        ("Kinematics: Describing Motion", "Students learn how to describe motion using concepts of distance, displacement, speed, and velocity."),
        ("Newton's First Law of Motion", "Students learn how objects remain at rest or in motion unless acted on by a force."),
        ("Newton's Second Law of Motion", "Students learn how force, mass, and acceleration are related."),
        ("Newton's Third Law of Motion", "Students learn how every action force has an equal and opposite reaction force."),
        ("Mass, Weight, and Gravity", "Students learn the difference between mass and weight and how gravity affects both."),
        ("Momentum and Its Conservation", "Students learn how momentum is calculated and conserved in collisions."),
        ("Work, Energy, and Power", "Students learn how work, energy, and power are defined and related in physics."),
        ("Kinetic and Potential Energy", "Students learn how energy of motion and stored energy are calculated and transformed."),
        ("Conservation of Energy", "Students learn how energy changes form but is never created or destroyed."),
        ("Simple Machines and Mechanical Advantage", "Students learn how simple machines make work easier by changing force or distance."),
        ("Circular Motion Basics", "Students learn how objects moving in a circle experience centripetal force."),
        ("Projectile Motion", "Students learn how objects launched into the air follow a curved path under gravity."),
        ("Friction and Its Effects", "Students learn how friction opposes motion and affects everyday movement."),
        ("Pressure in Fluids", "Students learn how pressure behaves in liquids and gases."),
        ("Archimedes' Principle and Buoyancy", "Students learn why objects float or sink based on the fluid they displace."),
        ("Density and Its Applications", "Students learn how density is calculated and used to identify and compare materials."),
        ("Waves: Types and Properties", "Students learn the properties that describe waves, including wavelength, frequency, and amplitude."),
        ("Sound Waves and Their Properties", "Students learn how sound travels as a wave and how its properties affect what we hear."),
        ("The Electromagnetic Spectrum", "Students learn how different types of electromagnetic radiation are organized by wavelength."),
        ("Light: Reflection and Refraction", "Students learn how light bends and bounces when it interacts with different surfaces and materials."),
        ("Lenses and Image Formation", "Students learn how lenses bend light to form images in devices like glasses and cameras."),
        ("Colour and the Visible Spectrum", "Students learn how visible light separates into colours and why objects appear coloured."),
        ("Static Electricity", "Students learn how electric charge builds up on objects and how it discharges."),
        ("Electric Circuits: Series and Parallel", "Students learn how components behave differently in series and parallel circuits."),
        ("Ohm's Law", "Students learn the relationship between voltage, current, and resistance in a circuit."),
        ("Electrical Power and Energy Consumption", "Students learn how electrical power is calculated and how it relates to energy bills."),
        ("Magnetism and Magnetic Fields", "Students learn how magnets create fields that exert forces on other magnetic materials."),
        ("Electromagnetic Induction", "Students learn how a changing magnetic field can generate an electric current."),
        ("Introduction to Nuclear Physics", "Students learn the basic structure of the atomic nucleus and forces that hold it together."),
        ("Radioactivity and Types of Decay", "Students learn about alpha, beta, and gamma radioactive decay."),
        ("Nuclear Fission and Fusion Basics", "Students learn the difference between splitting and combining atomic nuclei to release energy."),
        ("Semiconductors and Electronics Basics", "Students learn how semiconductor materials are used in modern electronic devices."),
        ("Renewable Energy Technologies", "Students learn how technologies like solar and wind panels convert natural resources into electricity."),
        ("Non-Renewable Energy Sources", "Students learn how fossil fuels are used to generate energy and their environmental impact."),
        ("Heat Transfer: Conduction, Convection, and Radiation", "Students learn the three main ways heat energy moves between objects."),
        ("States of Matter and Phase Changes", "Students learn how matter changes between solid, liquid, and gas states."),
        ("Measurement and Units in Physics", "Students learn how physical quantities are measured and expressed using standard units."),
        ("Vectors and Scalars", "Students learn the difference between quantities that have direction and those that do not."),
        ("Forces and Free Body Diagrams", "Students learn to represent the forces acting on an object using simple diagrams."),
        ("Rotational Motion and Torque", "Students learn how forces cause objects to rotate around a fixed point."),
        ("Elasticity and Hooke's Law", "Students learn how springs and elastic materials stretch in proportion to applied force."),
        ("The Doppler Effect", "Students learn why the pitch of a sound changes as its source moves toward or away from a listener."),
        ("Introduction to Quantum Physics Concepts", "Students are introduced to basic ideas about how matter and energy behave at very small scales."),
        ("History of Physics: Key Discoveries", "Students learn about landmark discoveries that shaped the development of physics as a science."),
        ("Physics of Everyday Machines", "Students learn how physics principles explain the operation of common household devices."),
        ("Satellites and Orbital Motion", "Students learn how satellites stay in orbit around the Earth."),
        ("Astronomy Basics: The Solar System", "Students learn the structure and key features of our solar system."),
        ("Physics Practical Skills and Data Analysis", "Students learn how to record measurements and analyse experimental data in physics investigations."),
    ],
    "Chemistry": [
        ("Atomic Structure: Protons, Neutrons, and Electrons", "Students learn how atoms are built from subatomic particles and how this determines their properties."),
        ("The Periodic Table: Organization and Trends", "Students learn how elements are arranged and how properties change across the periodic table."),
        ("Chemical Bonding: Ionic Bonds", "Students learn how atoms transfer electrons to form ionic bonds."),
        ("Chemical Bonding: Covalent Bonds", "Students learn how atoms share electrons to form covalent bonds."),
        ("Metallic Bonding and Properties of Metals", "Students learn how metallic bonding explains properties like conductivity and malleability."),
        ("Chemical Formulas and Naming Compounds", "Students learn the rules for writing and naming common chemical compounds."),
        ("Balancing Chemical Equations", "Students learn how to balance chemical equations to satisfy the conservation of mass."),
        ("Types of Chemical Reactions", "Students learn to classify reactions as synthesis, decomposition, displacement, and more."),
        ("Acids, Bases, and the pH Scale", "Students learn how acids and bases are classified and measured using the pH scale."),
        ("Neutralization Reactions", "Students learn how acids and bases react together to form salts and water."),
        ("Salts and Their Formation", "Students learn how salts form and some of their common everyday uses."),
        ("The Mole Concept", "Students learn how the mole is used to count particles in chemistry."),
        ("Molar Mass and Stoichiometry", "Students learn how molar mass is used to calculate quantities in chemical reactions."),
        ("States of Matter and the Kinetic Theory", "Students learn how particle motion explains the properties of solids, liquids, and gases."),
        ("Solutions, Solubility, and Concentration", "Students learn how solutes dissolve in solvents and how concentration is measured."),
        ("Separation Techniques in Chemistry", "Students learn methods such as filtration and distillation for separating mixtures."),
        ("The Periodic Table: Groups and Periods", "Students learn how elements in the same group or period share similar properties."),
        ("Metals and Non-Metals: Properties", "Students learn to compare the physical and chemical properties of metals and non-metals."),
        ("The Reactivity Series of Metals", "Students learn how metals are ranked by their tendency to react."),
        ("Oxidation and Reduction Reactions", "Students learn the basics of electron transfer in oxidation and reduction reactions."),
        ("Introduction to Organic Chemistry", "Students learn the basics of carbon-based compounds and why carbon forms so many compounds."),
        ("Hydrocarbons: Alkanes and Alkenes", "Students learn the structure and properties of simple hydrocarbon molecules."),
        ("Functional Groups in Organic Chemistry", "Students learn how functional groups determine the properties of organic molecules."),
        ("Polymers and Plastics", "Students learn how small molecules join together to form long polymer chains."),
        ("Fossil Fuels and Combustion", "Students learn how fossil fuels burn and release energy through combustion reactions."),
        ("Chemical Energy and Exothermic Reactions", "Students learn how exothermic reactions release energy to their surroundings."),
        ("Endothermic Reactions and Energy Changes", "Students learn how endothermic reactions absorb energy from their surroundings."),
        ("Catalysts and Their Role in Reactions", "Students learn how catalysts speed up reactions without being consumed."),
        ("Gas Laws Basics", "Students learn how pressure, volume, and temperature of gases are related."),
        ("The Water Cycle: A Chemical Perspective", "Students learn how water changes state and moves through the environment."),
        ("Water Treatment and Purification Chemistry", "Students learn the basic chemical processes used to make water safe to drink."),
        ("Chemistry of the Atmosphere", "Students learn about the composition of the atmosphere and the chemical processes within it."),
        ("Environmental Chemistry: Pollution and Its Effects", "Students learn how chemical pollutants affect air, water, and soil."),
        ("Chemical Safety and Laboratory Practices", "Students learn essential safety rules and practices for working in a chemistry laboratory."),
        ("Crystallization and Crystal Structures", "Students learn how solids form ordered crystal structures as they solidify."),
        ("Isotopes and Radioactivity Basics", "Students learn what isotopes are and the basics of radioactive decay."),
        ("Chemical Industry: Fertilizers and Their Production", "Students learn how chemical fertilizers are produced and used in agriculture."),
        ("The Haber Process", "Students learn how the Haber process manufactures ammonia for use in fertilizers."),
        ("Chemistry of Everyday Materials", "Students learn the chemical composition of common materials used in daily life."),
        ("Titration Techniques", "Students learn how titration is used to determine the concentration of a solution."),
        ("Chromatography Techniques", "Students learn how chromatography is used to separate and identify substances in a mixture."),
        ("Chemical Formulae from Experimental Data", "Students learn how experimental data can be used to determine a compound's formula."),
        ("History of the Periodic Table", "Students learn how the periodic table developed from early classification systems to its modern form."),
        ("Alloys and Their Uses", "Students learn how mixing metals creates alloys with improved properties."),
        ("Corrosion and Rusting Prevention", "Students learn what causes metals to corrode and methods used to prevent it."),
        ("Chemistry of Food and Nutrition", "Students learn how chemical processes are involved in cooking, digestion, and nutrition."),
        ("Green Chemistry and Sustainability", "Students learn how chemistry can be practiced in more environmentally sustainable ways."),
        ("Introduction to Biochemistry", "Students learn the basic chemistry of molecules essential to living organisms."),
    ],
    "Biology": [
        ("Cell Structure and Function", "Students learn the structure and function of the organelles found within cells."),
        ("Plant Cells vs Animal Cells", "Students learn to compare the structural differences between plant and animal cells."),
        ("Cell Membrane and Transport", "Students learn how substances move into and out of cells across the cell membrane."),
        ("Mitosis and the Cell Cycle", "Students learn how cells divide to grow and repair tissue through mitosis."),
        ("Meiosis and Genetic Variation", "Students learn how meiosis produces genetic variation in reproductive cells."),
        ("DNA Structure and Replication", "Students learn the structure of DNA and how it copies itself before cell division."),
        ("Genes, Chromosomes, and Heredity", "Students learn how genes on chromosomes are passed from parents to offspring."),
        ("Mendelian Genetics and Punnett Squares", "Students learn how Punnett squares predict the inheritance of traits."),
        ("Genetic Disorders: An Overview", "Students learn about common genetic disorders and how they are inherited."),
        ("Genetic Engineering Basics", "Students learn the basic concepts behind modifying an organism's genetic material."),
        ("Protein Synthesis: Transcription and Translation", "Students learn how genetic information is used to build proteins."),
        ("Enzymes and Their Function", "Students learn how enzymes speed up biochemical reactions in living organisms."),
        ("Photosynthesis: Process and Importance", "Students learn how plants convert light energy into chemical energy."),
        ("Cellular Respiration", "Students learn how cells release energy from glucose through respiration."),
        ("The Human Digestive System", "Students learn how the digestive system breaks down food and absorbs nutrients."),
        ("The Human Circulatory System", "Students learn how the heart and blood vessels transport blood throughout the body."),
        ("The Human Respiratory System", "Students learn how the lungs enable the exchange of oxygen and carbon dioxide."),
        ("The Human Nervous System", "Students learn how the brain, spinal cord, and nerves coordinate body functions."),
        ("The Human Endocrine System", "Students learn how hormones regulate processes throughout the body."),
        ("The Human Excretory System", "Students learn how the kidneys and related organs remove waste from the body."),
        ("The Immune System and Disease Defense", "Students learn how the body defends itself against pathogens."),
        ("Homeostasis and the Body's Balance", "Students learn how the body maintains a stable internal environment."),
        ("The Skeletal and Muscular Systems", "Students learn how bones and muscles work together to support and move the body."),
        ("Plant Structure and Function", "Students learn the functions of roots, stems, and leaves in plants."),
        ("Plant Reproduction", "Students learn how flowering plants reproduce sexually and asexually."),
        ("Transport in Plants: Xylem and Phloem", "Students learn how plants transport water and nutrients through specialized tissues."),
        ("Classification of Living Organisms", "Students learn how organisms are grouped into kingdoms and other taxonomic categories."),
        ("Microorganisms: Bacteria, Viruses, and Fungi", "Students learn the basic structure and roles of common microorganisms."),
        ("Infectious Diseases and Transmission", "Students learn how infectious diseases spread and methods used to prevent transmission."),
        ("Vaccines and Immunity", "Students learn how vaccines help the immune system build protection against disease."),
        ("Ecosystems and Energy Flow", "Students learn how energy flows through producers, consumers, and decomposers in an ecosystem."),
        ("Food Chains and Food Webs", "Students learn how food chains and webs represent feeding relationships in nature."),
        ("Biodiversity and Its Importance", "Students learn why a variety of species is important for healthy ecosystems."),
        ("Human Impact on Ecosystems", "Students learn how human activity affects natural ecosystems and biodiversity."),
        ("Conservation Biology", "Students learn strategies used to protect species and habitats from extinction."),
        ("Adaptations and Survival", "Students learn how physical and behavioural adaptations help organisms survive."),
        ("Population Dynamics in Ecology", "Students learn what factors cause populations of organisms to grow or decline."),
        ("Nutrient Cycles: Carbon and Nitrogen", "Students learn how carbon and nitrogen cycle through ecosystems."),
        ("Animal Behaviour Basics", "Students learn how animals behave in response to their environment and each other."),
        ("Comparative Anatomy Across Species", "Students learn how comparing anatomy across species reveals evolutionary relationships."),
        ("The History of Evolutionary Thought", "Students learn how scientific understanding of evolution developed over time."),
        ("Genetics and Selective Breeding", "Students learn how humans have used selective breeding to change organisms over generations."),
        ("Biotechnology Applications", "Students learn how biotechnology is applied in medicine, agriculture, and industry."),
        ("Stem Cells and Their Potential", "Students learn what stem cells are and their potential medical applications."),
        ("The Human Reproductive System: Structure", "Students learn the basic structure and function of the human reproductive system."),
        ("Puberty and Adolescent Development", "Students learn about the physical and emotional changes that occur during puberty."),
        ("Biology Laboratory Skills and Microscopy", "Students learn how to safely use a microscope and record biological observations."),
        ("Careers in the Biological Sciences", "Students explore career paths available to people who study biology."),
    ],
    "Philosophy": [
        ("What Is Philosophy? An Introduction", "Students learn what philosophy is and the major branches of philosophical inquiry."),
        ("Introduction to Logic and Argumentation", "Students learn the basic structure of logical arguments and how to evaluate them."),
        ("Ethics: What Makes an Action Right or Wrong?", "Students learn different approaches to deciding whether an action is morally right or wrong."),
        ("Introduction to Metaphysics", "Students learn about the philosophical study of the nature of reality and existence."),
        ("Introduction to Epistemology: What Can We Know?", "Students learn how philosophers examine the nature and limits of human knowledge."),
        ("Plato and the Theory of Forms", "Students learn Plato's idea that abstract, perfect Forms represent ultimate reality."),
        ("Aristotle and the Golden Mean", "Students learn Aristotle's idea that virtue lies between two extremes."),
        ("Socratic Method and Questioning", "Students learn how Socrates used probing questions to examine beliefs and ideas."),
        ("Utilitarianism: The Greatest Good", "Students learn the ethical theory that actions should maximize overall happiness."),
        ("Deontology and Duty-Based Ethics", "Students learn the ethical theory that some actions are right or wrong regardless of consequences."),
        ("Virtue Ethics Explained", "Students learn the ethical theory that focuses on developing good character traits."),
        ("Existentialism: Meaning and Choice", "Students learn how existentialist thinkers explore individual freedom and the search for meaning."),
        ("Introduction to Political Philosophy", "Students learn how philosophers have thought about justice, authority, and the state."),
        ("Social Contract Theory", "Students learn the idea that legitimate government arises from an agreement among individuals."),
        ("Philosophy of Justice", "Students learn different philosophical theories about what makes a society just."),
        ("The Trolley Problem and Moral Dilemmas", "Students learn to analyse a classic ethical dilemma involving difficult moral choices."),
        ("The Nature of Happiness", "Students learn how different philosophers have defined and pursued genuine happiness."),
        ("Philosophy of Religion: Arguments for and against God", "Students learn classic philosophical arguments both for and against the existence of God."),
        ("The Problem of Evil", "Students learn the philosophical question of how evil and suffering can exist in the world."),
        ("Eastern Philosophy: An Introduction to Confucianism", "Students learn the core ideas of Confucian thought on ethics and social harmony."),
        ("Eastern Philosophy: An Introduction to Buddhism", "Students learn the core philosophical ideas found in Buddhist thought."),
        ("Stoicism and Its Modern Relevance", "Students learn Stoic ideas about controlling one's reactions to events outside one's control."),
        ("The Nature of Truth", "Students learn different philosophical theories about what makes a statement true."),
        ("Skepticism and Doubt", "Students learn how philosophical skepticism questions the certainty of our beliefs."),
        ("Philosophy of Science: What Makes Something Scientific?", "Students learn how philosophers distinguish scientific claims from non-scientific ones."),
        ("Determinism vs Free Will", "Students learn the philosophical debate over whether human choices are truly free."),
        ("Personal Identity: What Makes You \"You\"?", "Students learn philosophical questions about what makes a person the same over time."),
        ("The Ship of Theseus and Identity Over Time", "Students learn a classic thought experiment about identity and change."),
        ("Philosophy of Beauty: Introduction to Aesthetics", "Students learn how philosophers analyse beauty and the nature of art."),
        ("Environmental Ethics", "Students learn philosophical perspectives on humans' moral responsibilities toward the environment."),
        ("Animal Rights and Moral Consideration", "Students learn different philosophical views on the moral status of animals."),
        ("Philosophy of Law", "Students learn how philosophers examine the nature and justification of laws."),
        ("Rights and Responsibilities", "Students learn how philosophers connect individual rights with corresponding responsibilities."),
        ("Introduction to Formal Logic", "Students learn the basics of symbolic logic and valid reasoning structures."),
        ("Fallacies in Reasoning", "Students learn to identify common errors in reasoning found in everyday arguments."),
        ("Philosophy of Language: Words and Meaning", "Students learn how philosophers examine the relationship between language and meaning."),
        ("Descartes and \"I Think, Therefore I Am\"", "Students learn Descartes' method of doubt and his famous conclusion about certainty."),
        ("Rationalism vs Empiricism", "Students learn the debate over whether knowledge comes primarily from reason or experience."),
        ("Immanuel Kant and the Categorical Imperative", "Students learn Kant's idea that moral rules should apply universally to everyone."),
        ("Confucian Ethics and Social Harmony", "Students learn how Confucian philosophy emphasizes duty, respect, and social order."),
        ("The Allegory of the Cave", "Students learn Plato's allegory about perception, illusion, and the pursuit of knowledge."),
        ("Philosophy of Technology and Ethics", "Students learn how philosophers examine the ethical implications of new technologies."),
        ("Feminist Philosophy: An Introduction", "Students learn key ideas from feminist philosophical thought on equality and justice."),
        ("Philosophy of Human Rights", "Students learn philosophical foundations for the concept of universal human rights."),
        ("The Ethics of Artificial Intelligence", "Students learn philosophical questions raised by the development of artificial intelligence."),
        ("Ancient Greek Philosophy: An Overview", "Students learn about the major thinkers and ideas of ancient Greek philosophy."),
        ("Modern Philosophy: The Enlightenment Thinkers", "Students learn about philosophers whose ideas shaped the Enlightenment era."),
        ("Applying Philosophy to Everyday Life", "Students learn how philosophical thinking can be applied to everyday decisions and problems."),
        ("Constructing a Philosophical Argument", "Students practice building a clear, well-supported philosophical argument of their own."),
    ],
    "Critical Thinking": [
        ("What Is Critical Thinking?", "Students learn what critical thinking means and why it matters for everyday decisions."),
        ("Identifying Arguments and Claims", "Students learn to identify the main claim and supporting reasons in an argument."),
        ("Distinguishing Facts from Opinions", "Students learn how to tell the difference between verifiable facts and personal opinions."),
        ("Recognizing Logical Fallacies", "Students learn to identify common flaws in reasoning that weaken an argument."),
        ("Deductive Reasoning", "Students learn how deductive reasoning moves from general premises to a specific conclusion."),
        ("Inductive Reasoning", "Students learn how inductive reasoning draws general conclusions from specific observations."),
        ("Evaluating Evidence and Sources", "Students learn criteria for judging whether evidence and sources are reliable."),
        ("Bias and Its Effect on Thinking", "Students learn how personal bias can distort judgment and decision-making."),
        ("Confirmation Bias and How to Avoid It", "Students learn how confirmation bias leads people to favor information that supports existing beliefs."),
        ("Analysing Cause and Effect", "Students learn to distinguish genuine causes from coincidental relationships."),
        ("Correlation vs Causation", "Students learn why two things occurring together does not prove one causes the other."),
        ("Evaluating the Credibility of Sources", "Students learn to assess the trustworthiness of different information sources."),
        ("Media Literacy and Misinformation", "Students learn strategies to identify misinformation and misleading media content."),
        ("Recognizing Propaganda Techniques", "Students learn to identify common techniques used in propaganda and persuasive messaging."),
        ("Constructing a Sound Argument", "Students learn how to build an argument that is both logically valid and well-supported."),
        ("Identifying Assumptions in Arguments", "Students learn to uncover the unstated assumptions behind an argument."),
        ("Analysing Statistics and Data Critically", "Students learn how statistics can be misused or misinterpreted and how to evaluate them carefully."),
        ("Recognizing Cognitive Biases", "Students learn about common cognitive biases that affect human judgment."),
        ("The Socratic Method of Questioning", "Students learn how to use structured questioning to examine ideas and assumptions."),
        ("Brainstorming and Creative Thinking Techniques", "Students learn techniques for generating a wide range of creative ideas and solutions."),
        ("Structured Problem-Solving Frameworks", "Students learn step-by-step frameworks for approaching complex problems."),
        ("Root Cause Analysis", "Students learn techniques for identifying the underlying cause of a problem."),
        ("Decision-Making Models", "Students learn structured models that support effective decision-making."),
        ("Weighing Pros and Cons Systematically", "Students learn to systematically evaluate the advantages and disadvantages of a decision."),
        ("Risk Assessment in Decision Making", "Students learn to identify and weigh risks when making important decisions."),
        ("Critical Reading Strategies", "Students learn strategies for reading texts actively and evaluating their arguments."),
        ("Analysing Persuasive Techniques in Advertising", "Students learn to recognize techniques advertisers use to persuade consumers."),
        ("Debate Skills: Constructing and Rebutting Arguments", "Students learn how to construct persuasive arguments and respond to counterarguments."),
        ("Evaluating Online Information and Fake News", "Students learn strategies for verifying the accuracy of information found online."),
        ("Understanding Sampling and Survey Bias", "Students learn how flawed sampling methods can bias survey results."),
        ("Analogical Reasoning", "Students learn how comparing similar situations can help reach conclusions and solve problems."),
        ("Recognizing Emotional Manipulation in Arguments", "Students learn to identify when arguments rely on emotional manipulation rather than sound reasoning."),
        ("The Difference Between Valid and Sound Arguments", "Students learn the distinction between an argument's logical validity and the truth of its premises."),
        ("Analysing Cartoons and Visual Rhetoric", "Students learn to interpret the arguments and messages conveyed through political cartoons and images."),
        ("Group Decision-Making and Groupthink", "Students learn how group dynamics can improve or undermine the quality of decisions."),
        ("Ethical Reasoning in Decision Making", "Students learn to incorporate ethical considerations into the decision-making process."),
        ("Critical Thinking in Scientific Investigation", "Students learn how critical thinking underpins the design and evaluation of scientific investigations."),
        ("Evaluating Conflicting Viewpoints", "Students learn strategies for fairly evaluating arguments on opposing sides of an issue."),
        ("Systems Thinking: Seeing the Bigger Picture", "Students learn to analyse how different parts of a system interact and influence outcomes."),
        ("Lateral Thinking Techniques", "Students learn techniques for approaching problems from unexpected angles."),
        ("Mind Mapping for Problem Solving", "Students learn how mind maps can help organize ideas and identify solutions."),
        ("The Five Whys Technique", "Students learn how repeatedly asking \"why\" can help uncover the root cause of a problem."),
        ("Evaluating Expert Opinions", "Students learn criteria for judging whether an expert's opinion should be trusted."),
        ("Recognizing False Dichotomies", "Students learn to identify arguments that wrongly present only two possible options."),
        ("Critical Thinking About Health Claims", "Students learn to critically evaluate health and wellness claims encountered in daily life."),
        ("Applying Critical Thinking to Personal Finance", "Students learn to apply critical thinking skills to everyday financial decisions."),
        ("Critical Thinking in the Digital Age", "Students learn how critical thinking skills apply to navigating a world of digital information."),
        ("Building a Habit of Reflective Thinking", "Students learn practices that build a lifelong habit of thoughtful reflection."),
        ("Case Studies in Critical Thinking", "Students apply critical thinking skills to analyse real-world case studies."),
    ],
    "Health Education": [
        ("Understanding Nutrition and Balanced Diets", "Students learn the components of a balanced diet and why nutrition matters for health."),
        ("Macronutrients and Micronutrients", "Students learn the roles of carbohydrates, proteins, fats, vitamins, and minerals in the body."),
        ("Reading Food Labels", "Students learn how to interpret nutrition labels to make informed food choices."),
        ("The Effects of Physical Activity on Health", "Students learn how regular physical activity benefits physical and mental health."),
        ("Sleep Hygiene and Its Importance", "Students learn habits that support healthy sleep and why sleep matters for wellbeing."),
        ("Understanding Stress and Coping Strategies", "Students learn healthy strategies for recognizing and managing stress."),
        ("Substance Abuse Prevention: Alcohol", "Students learn about the health risks of alcohol use and strategies to resist peer pressure."),
        ("Substance Abuse Prevention: Tobacco and Vaping", "Students learn about the health risks of tobacco and vaping products."),
        ("Substance Abuse Prevention: Illicit Drugs", "Students learn about the health and legal risks associated with illicit drug use."),
        ("Understanding Addiction", "Students learn how addiction develops and affects the brain and behavior."),
        ("Body Image and Self-Esteem", "Students learn how body image affects self-esteem and strategies for building a positive self-image."),
        ("Understanding Eating Disorders", "Students learn to recognize signs of eating disorders and the importance of seeking help."),
        ("Personal Hygiene Practices", "Students learn hygiene practices that support health and prevent the spread of illness."),
        ("Understanding Vaccinations and Immunization", "Students learn how vaccines work to protect individuals and communities from disease."),
        ("Common Communicable Diseases", "Students learn how common communicable diseases spread and how to prevent transmission."),
        ("Non-Communicable Diseases: An Overview", "Students learn about diseases that are not spread from person to person and their risk factors."),
        ("Understanding Diabetes", "Students learn the basics of diabetes, including its types, risk factors, and management."),
        ("Understanding Cardiovascular Disease", "Students learn about risk factors for heart disease and ways to protect heart health."),
        ("Cancer Awareness and Prevention Basics", "Students learn basic facts about cancer and lifestyle factors that can reduce risk."),
        ("Healthy Relationships and Communication", "Students learn qualities of healthy relationships and effective communication skills."),
        ("Consent and Personal Boundaries", "Students learn the importance of consent and respecting personal boundaries."),
        ("Understanding Puberty and Body Changes", "Students learn about the physical and emotional changes that occur during puberty."),
        ("Sexually Transmitted Infections: Prevention and Awareness", "Students learn how sexually transmitted infections spread and methods of prevention."),
        ("Contraception Methods: An Overview", "Students learn a factual, age-appropriate overview of common contraception methods."),
        ("Understanding Consent in Relationships", "Students learn what informed, ongoing consent means in the context of relationships."),
        ("Recognizing and Responding to Bullying", "Students learn to recognize bullying and strategies for responding safely and effectively."),
        ("Understanding Peer Pressure", "Students learn to recognize peer pressure and strategies for making independent decisions."),
        ("Mental Health Awareness: Anxiety and Depression", "Students learn to recognize signs of anxiety and depression and the importance of seeking support."),
        ("Building Emotional Resilience", "Students learn strategies for building resilience in the face of life's challenges."),
        ("Coping with Grief and Loss", "Students learn healthy ways to process and cope with grief and loss."),
        ("Digital Wellbeing and Screen Time", "Students learn how to balance screen time with other healthy activities."),
        ("Online Safety and Cyberbullying", "Students learn strategies for staying safe online and responding to cyberbullying."),
        ("First Steps in Health Advocacy", "Students learn how individuals can advocate for improved health in their communities."),
        ("Understanding Health Insurance Basics", "Students learn the basic purpose and function of health insurance."),
        ("Environmental Health and Wellbeing", "Students learn how the environment around us can affect physical and mental health."),
        ("Understanding Allergies and Intolerances", "Students learn the difference between allergies and intolerances and how to manage them safely."),
        ("Healthy Habits for Lifelong Wellness", "Students learn habits that support wellness across the lifespan."),
        ("Understanding the Healthcare System", "Students learn how healthcare systems are organized and how to access care."),
        ("Community Health Resources", "Students learn about resources available in their community to support health and wellbeing."),
        ("Health Communication and Doctor Visits", "Students learn skills for communicating effectively with healthcare providers."),
        ("Understanding Chronic Pain Management", "Students learn the basics of how chronic pain is managed and treated."),
        ("Reproductive Health Across the Lifespan", "Students learn how reproductive health needs and considerations change across life stages."),
        ("Understanding Body Systems and Disease Prevention", "Students learn how understanding body systems supports disease prevention."),
        ("Setting Personal Health Goals", "Students learn to set specific, achievable goals to improve their personal health."),
    ],
    "ICT & Computer Science": [
        ("Introduction to Computer Hardware", "Students learn the main physical components that make up a computer system."),
        ("Introduction to Computer Software", "Students learn the difference between system software and application software."),
        ("How the Internet Works", "Students learn the basic infrastructure and protocols that allow the internet to function."),
        ("Introduction to Computer Networks", "Students learn how devices connect and communicate within a network."),
        ("Understanding IP Addresses and Domains", "Students learn how IP addresses and domain names identify devices and websites online."),
        ("Cybersecurity Basics", "Students learn foundational practices for protecting devices and data from cyber threats."),
        ("Understanding Malware and Viruses", "Students learn how malicious software spreads and how to protect against it."),
        ("Safe Password Practices", "Students learn how to create and manage strong, secure passwords."),
        ("Introduction to Programming Concepts", "Students learn foundational programming concepts common to most languages."),
        ("Variables and Data Types", "Students learn how variables store data and the common data types used in programming."),
        ("Control Structures: Loops and Conditionals", "Students learn how loops and conditional statements control program flow."),
        ("Functions and Modular Programming", "Students learn how breaking programs into reusable functions improves code organization."),
        ("Introduction to Python Programming", "Students write simple programs to learn the basics of the Python programming language."),
        ("Introduction to Algorithms", "Students learn what an algorithm is and how to design a simple step-by-step solution."),
        ("Flowcharts and Pseudocode", "Students learn to plan programs using flowcharts and pseudocode before writing code."),
        ("Data Structures: Arrays and Lists", "Students learn how arrays and lists are used to organize and store collections of data."),
        ("Introduction to Databases", "Students learn the basic purpose and structure of databases for storing information."),
        ("SQL Basics: Querying Data", "Students learn basic SQL commands used to retrieve data from a database."),
        ("Introduction to Web Development: HTML", "Students learn how HTML is used to structure content on a webpage."),
        ("Introduction to Web Development: CSS", "Students learn how CSS is used to style and layout webpages."),
        ("Introduction to JavaScript", "Students learn the basics of using JavaScript to add interactivity to webpages."),
        ("Understanding Binary and Number Systems", "Students learn how computers represent data using the binary number system."),
        ("How Computers Store and Process Data", "Students learn the basic principles of how computers store and process information."),
        ("Introduction to Operating Systems", "Students learn the role an operating system plays in managing computer hardware and software."),
        ("File Management and Organization", "Students learn best practices for organizing and managing digital files."),
        ("Cloud Computing Basics", "Students learn how cloud computing allows data and applications to be accessed over the internet."),
        ("Introduction to Artificial Intelligence", "Students learn a basic overview of what artificial intelligence is and how it is used."),
        ("Machine Learning: A Beginner's Overview", "Students learn the basic idea of how machine learning systems learn from data."),
        ("Understanding Big Data", "Students learn what big data is and how large datasets are used to find patterns."),
        ("Introduction to Robotics", "Students learn the basic components and principles behind robotic systems."),
        ("Computer Ethics and Digital Citizenship", "Students learn responsible and ethical behavior when using technology."),
        ("Intellectual Property and Software Licensing", "Students learn the basics of copyright, licensing, and intellectual property in software."),
        ("Understanding the Software Development Life Cycle", "Students learn the stages involved in planning, building, and maintaining software."),
        ("Debugging and Testing Code", "Students learn strategies for finding and fixing errors in computer programs."),
        ("Version Control Basics", "Students learn how version control systems help track and manage changes to code."),
        ("Introduction to Spreadsheets", "Students learn how to use spreadsheets to organize data and perform calculations."),
        ("Data Visualization Basics", "Students learn how charts and graphs are used to represent data clearly."),
        ("Introduction to Computer Graphics", "Students learn the basic principles behind how images are created and displayed digitally."),
        ("Understanding Social Media Platforms and Algorithms", "Students learn how social media algorithms influence the content users see."),
        ("Digital Footprint and Online Privacy", "Students learn how online activity creates a digital footprint and how to protect their privacy."),
        ("Understanding E-Commerce", "Students learn the basic principles behind how online buying and selling works."),
        ("Introduction to Game Development Concepts", "Students learn the basic concepts involved in designing and building simple games."),
        ("Human-Computer Interaction Basics", "Students learn principles for designing technology that is easy and intuitive to use."),
        ("Introduction to Computer Vision", "Students learn a basic overview of how computers can be taught to interpret images."),
        ("Understanding APIs", "Students learn how APIs allow different software applications to communicate with each other."),
        ("Wireless Technology and Bluetooth Basics", "Students learn the basic principles behind common wireless technologies."),
        ("History of Computing", "Students learn key milestones in the history and development of computers."),
        ("Emerging Technologies: An Overview", "Students learn about new and developing technologies shaping the future."),
        ("Careers in Information and Communication Technology", "Students explore career paths available in the field of information and communication technology."),
    ],
}
