"""Grade 7 (ages 11-12) syllabus expansion topics.

Provides (title, summary) tuples for each subject. A separate merge script
(merge_grade_topics_expansion.py) reads MODULES and builds full lesson
objects. Do not duplicate titles already present in syllabus/grade7.json.
"""

GRADE = 7

MODULES: dict[str, list[tuple[str, str]]] = {
    "Math": [
        ("Integers and Absolute Value", "Students learn to compare, order, and find the absolute value of positive and negative integers."),
        ("Operations with Rational Numbers", "Students practice adding, subtracting, multiplying, and dividing rational numbers including fractions and decimals."),
        ("Ratios and Proportional Relationships", "Students learn to express, simplify, and compare ratios between two or more quantities."),
        ("Percentages and Percent Change", "Students learn to calculate percentages, percent increase, and percent decrease in real-world problems."),
        ("Simple and Compound Interest", "Students learn to calculate simple and compound interest on savings and loans."),
        ("Algebraic Expressions and Simplification", "Students learn to write, combine like terms in, and simplify algebraic expressions."),
        ("Solving Two-Step Equations", "Students learn to solve linear equations that require two inverse operations."),
        ("Graphing on the Coordinate Plane", "Students learn to plot and interpret points in all four quadrants of the coordinate plane."),
        ("Direct and Inverse Proportion", "Students learn to recognize and solve problems involving directly and inversely proportional quantities."),
        ("Exponents and Powers", "Students learn to read, write, and evaluate numerical expressions involving exponents."),
        ("Scientific Notation", "Students learn to write very large and very small numbers using scientific notation."),
        ("Square Roots and Cube Roots", "Students learn to find and estimate square roots and cube roots of numbers."),
        ("Number Theory: Primes, Factors and Multiples", "Students learn to identify prime numbers, factors, and multiples of whole numbers."),
        ("Highest Common Factor and Lowest Common Multiple", "Students learn strategies to find the HCF and LCM of two or more numbers."),
        ("Angles and Angle Relationships", "Students learn to identify complementary, supplementary, vertical, and adjacent angles."),
        ("Properties of Triangles", "Students learn to classify triangles by their sides and angles and apply the angle sum property."),
        ("Properties of Quadrilaterals and Polygons", "Students learn to identify and classify quadrilaterals and other polygons by their properties."),
        ("Circles: Circumference and Area", "Students learn to calculate the circumference and area of circles using pi."),
        ("Perimeter and Area of Composite Shapes", "Students learn to calculate the perimeter and area of shapes made from combined simple figures."),
        ("Surface Area of Prisms and Cylinders", "Students learn to calculate the surface area of prisms and cylinders using nets."),
        ("Volume of Prisms and Cylinders", "Students learn to calculate the volume of prisms and cylinders using formulas."),
        ("Nets of Three-Dimensional Shapes", "Students learn to identify and construct nets of common three-dimensional solids."),
        ("Transformations: Translation, Reflection and Rotation", "Students learn to perform and describe translations, reflections, and rotations of shapes."),
        ("Enlargement and Scale Factor", "Students learn to enlarge shapes using a given scale factor and center of enlargement."),
        ("Congruence and Similarity", "Students learn to identify congruent and similar figures and compare their properties."),
        ("Symmetry in Shapes", "Students learn to identify lines of symmetry and rotational symmetry in two-dimensional shapes."),
        ("Constructions with Compass and Straightedge", "Students learn to construct angle bisectors, perpendicular bisectors, and basic shapes using a compass and straightedge."),
        ("Mean, Median, Mode and Range", "Students learn to calculate and compare measures of center and spread in data sets."),
        ("Interpreting Bar Charts and Histograms", "Students learn to read, construct, and interpret bar charts and histograms."),
        ("Interpreting Pie Charts", "Students learn to read, construct, and interpret pie charts representing categorical data."),
        ("Scatter Graphs and Correlation", "Students learn to construct scatter graphs and describe correlation between two variables."),
        ("Probability of Combined Events", "Students learn to calculate the probability of two or more combined events."),
        ("Sequences and Patterns", "Students learn to identify, extend, and describe the rule for number sequences and patterns."),
        ("Linear Graphs and Gradient", "Students learn to plot linear graphs and calculate the gradient of a straight line."),
        ("Unit Rates and Speed, Distance, Time", "Students learn to solve problems involving unit rates and the relationship between speed, distance, and time."),
        ("Simple Budgeting and Financial Literacy", "Students learn to create a simple budget and apply math skills to everyday financial decisions."),
        ("Introduction to Set Theory and Venn Diagrams", "Students learn to represent and interpret sets and their relationships using Venn diagrams."),
    ],
    "English": [
        ("Parts of Speech Review", "Students review and correctly use nouns, verbs, adjectives, adverbs, pronouns, prepositions, and conjunctions."),
        ("Sentence Structure: Simple, Compound and Complex", "Students learn to identify and write simple, compound, and complex sentences."),
        ("Clauses and Phrases", "Students learn to distinguish between independent clauses, dependent clauses, and phrases."),
        ("Active and Passive Voice", "Students learn to identify and use active and passive voice appropriately in writing."),
        ("Punctuation Rules and Common Errors", "Students learn correct use of commas, apostrophes, quotation marks, and other punctuation."),
        ("Common Spelling Patterns", "Students learn common English spelling patterns and rules for tricky words."),
        ("Prefixes, Suffixes and Root Words", "Students learn to use prefixes, suffixes, and root words to determine word meaning."),
        ("Building Academic Vocabulary", "Students learn strategies for expanding and using grade-level academic vocabulary."),
        ("Figurative Language and Imagery", "Students learn to identify and use similes, metaphors, personification, and imagery."),
        ("Literary Devices in Fiction", "Students learn to identify literary devices such as foreshadowing, symbolism, and irony."),
        ("Narrative Writing: Structure and Voice", "Students learn to plan and write narratives with a clear structure and distinct voice."),
        ("Descriptive Writing Techniques", "Students learn to use sensory detail and precise language to write vivid descriptions."),
        ("Persuasive Writing and Rhetorical Appeals", "Students learn to write persuasive texts using ethos, pathos, and logos."),
        ("Expository Writing and Explaining Ideas", "Students learn to write clear expository texts that explain a topic or process."),
        ("Writing a Strong Thesis Statement", "Students learn to write a clear, arguable thesis statement for an essay."),
        ("Paragraph Structure and Topic Sentences", "Students learn to write well-organized paragraphs with clear topic sentences."),
        ("Transition Words and Cohesion", "Students learn to use transition words to connect ideas and improve the flow of writing."),
        ("Editing and Proofreading Strategies", "Students learn strategies for editing and proofreading their own and others' writing."),
        ("Reading Comprehension Strategies", "Students learn strategies such as predicting, questioning, and summarizing to improve comprehension."),
        ("Character Analysis", "Students learn to analyze character traits, motivations, and development in a text."),
        ("Plot Structure and Story Arc", "Students learn to identify the exposition, rising action, climax, falling action, and resolution of a story."),
        ("Theme in Literature", "Students learn to identify and explain the central theme or message of a literary text."),
        ("Tone and Mood", "Students learn to identify how word choice creates tone and mood in a text."),
        ("Point of View in Narratives", "Students learn to identify first-person, second-person, and third-person point of view."),
        ("Non-Fiction Text Features", "Students learn to use headings, captions, and other text features to understand non-fiction texts."),
        ("Note-Taking and Summarising", "Students learn strategies for taking effective notes and summarizing text."),
        ("Research Skills and Source Evaluation", "Students learn to find, evaluate, and use reliable sources for research."),
        ("Citing Sources and Avoiding Plagiarism", "Students learn basic citation methods and why it is important to avoid plagiarism."),
        ("Letter and Email Writing", "Students learn the conventions of formal and informal letter and email writing."),
        ("Introduction to Journalism", "Students learn the basics of writing a news report, including the five Ws."),
        ("Public Speaking Skills", "Students learn techniques for planning and delivering a clear, confident speech."),
        ("Debate and Argumentation", "Students learn to construct and present a logical argument in a structured debate."),
        ("Media Literacy and Bias", "Students learn to identify bias and perspective in media texts."),
        ("Reading and Performing Drama Scripts", "Students learn to read and interpret a script, including stage directions and dialogue."),
        ("Myths and Legends Across Cultures", "Students explore myths and legends from different cultures and their common themes."),
        ("Introduction to Biography and Autobiography", "Students learn the features of biography and autobiography as genres."),
        ("Comparing Texts and Genres", "Students learn to compare themes, styles, and structures across different texts and genres."),
        ("Author's Purpose and Perspective", "Students learn to identify an author's purpose and perspective in a text."),
        ("Peer Review and Constructive Feedback", "Students learn to give and receive constructive feedback on writing."),
    ],
    "Science": [
        ("The Scientific Method and Experimental Design", "Students learn to design a fair test using the steps of the scientific method."),
        ("Cell Structure and Function", "Students learn the structure and function of plant and animal cells."),
        ("Classification of Living Things", "Students learn how living things are classified into kingdoms and other groups."),
        ("Ecosystems and Food Webs", "Students learn how energy flows through ecosystems via food chains and food webs."),
        ("Photosynthesis and Plant Nutrition", "Students learn how plants use photosynthesis to produce energy."),
        ("The Digestive System", "Students learn the structure and function of the human digestive system."),
        ("The Respiratory System", "Students learn the structure and function of the human respiratory system."),
        ("The Circulatory System", "Students learn the structure and function of the human circulatory system."),
        ("Human Reproduction and Growth", "Students learn the basics of human reproduction and stages of growth."),
        ("Genetics and Heredity Basics", "Students learn how traits are inherited from parents to offspring."),
        ("Adaptation and Natural Selection", "Students learn how organisms adapt to their environment through natural selection."),
        ("States of Matter and Changes of State", "Students learn about solids, liquids, gases, and the processes that change matter between states."),
        ("Atoms, Elements and Compounds", "Students learn the basic structure of atoms and the difference between elements and compounds."),
        ("Introduction to the Periodic Table", "Students learn how the periodic table organizes elements by their properties."),
        ("Mixtures, Solutions and Separation Techniques", "Students learn to distinguish mixtures from compounds and separate mixtures using physical methods."),
        ("Acids, Bases and pH", "Students learn to classify substances as acidic, basic, or neutral using the pH scale."),
        ("Forces and Newton's Laws of Motion", "Students learn Newton's three laws of motion and how forces affect movement."),
        ("Gravity and Weight", "Students learn the difference between mass and weight and how gravity affects objects."),
        ("Energy Forms and Transformations", "Students learn to identify different forms of energy and how energy changes from one form to another."),
        ("Electrical Circuits and Components", "Students learn to build simple circuits and identify circuit components."),
        ("Magnetism and Electromagnets", "Students learn the properties of magnets and how electromagnets are made."),
        ("Density and Buoyancy", "Students learn to calculate density and explain why objects float or sink."),
        ("Pressure in Liquids and Gases", "Students learn how pressure behaves in liquids and gases."),
        ("Simple Machines and Mechanical Advantage", "Students learn how simple machines make work easier by providing mechanical advantage."),
        ("Earth's Layers and Structure", "Students learn about the layers of the Earth, from the crust to the core."),
        ("Plate Tectonics and Earthquakes", "Students learn how moving tectonic plates cause earthquakes."),
        ("Volcanoes and Igneous Activity", "Students learn how volcanoes form and the types of igneous activity they produce."),
        ("Rocks and the Rock Cycle", "Students learn how igneous, sedimentary, and metamorphic rocks form through the rock cycle."),
        ("Minerals and Their Properties", "Students learn to identify minerals by their physical properties."),
        ("Weather Patterns and Forecasting", "Students learn how weather forms and how it is forecast."),
        ("The Water Cycle", "Students learn the stages of the water cycle, including evaporation, condensation, and precipitation."),
        ("Climate and Climate Zones", "Students learn about the world's major climate zones and what shapes them."),
        ("The Solar System and Planets", "Students learn about the planets and other bodies that make up our solar system."),
        ("The Moon and Its Phases", "Students learn why the Moon appears to change shape throughout its phases."),
        ("Renewable and Non-Renewable Energy", "Students learn to compare renewable and non-renewable energy sources."),
        ("Environmental Conservation and Biodiversity", "Students learn why biodiversity matters and how conservation efforts protect it."),
        ("Microscopy and Cell Observation", "Students learn to use a microscope to observe and record cell structures."),
        ("Human Skeletal and Muscular Systems", "Students learn how bones and muscles work together to support and move the body."),
    ],
    "Geography": [
        ("Continents and Oceans", "Students learn to locate and name the world's continents and oceans."),
        ("Latitude, Longitude and the Global Grid", "Students learn to use latitude and longitude to locate places on a map."),
        ("Time Zones and the International Date Line", "Students learn how time zones work and the purpose of the International Date Line."),
        ("Landforms: Mountains, Valleys and Plains", "Students learn to identify and describe major landforms."),
        ("Rivers and River Systems", "Students learn how rivers form and shape the landscape."),
        ("Coasts and Coastal Processes", "Students learn how erosion and deposition shape coastlines."),
        ("Weather Versus Climate", "Students learn the difference between short-term weather and long-term climate."),
        ("World Climate Zones", "Students learn about the world's major climate zones and their characteristics."),
        ("Biomes: Rainforests, Deserts and Tundra", "Students learn the features of major world biomes and the life found there."),
        ("The Water Cycle and Water Resources", "Students learn how the water cycle affects the distribution of freshwater resources."),
        ("Population Distribution and Density", "Students learn why population is unevenly distributed across the world."),
        ("Population Growth and Change", "Students learn how and why population size changes over time."),
        ("Migration: Causes and Effects", "Students learn the push and pull factors that cause migration and its effects."),
        ("Urbanisation and City Growth", "Students learn why and how cities grow."),
        ("Rural Life and Land Use", "Students learn how land is used in rural areas for farming and settlement."),
        ("Natural Resources and Their Uses", "Students learn to classify natural resources and how people use them."),
        ("Agriculture and Farming Systems", "Students learn about different farming systems used around the world."),
        ("Industry and Manufacturing", "Students learn how industry and manufacturing have developed and changed over time."),
        ("Global Trade and Trade Routes", "Students learn how goods move around the world through global trade routes."),
        ("Globalisation and Interconnected Economies", "Students learn how globalisation connects economies and cultures."),
        ("Tourism and Its Impacts", "Students learn the positive and negative impacts of tourism on places."),
        ("Energy Resources and Supply", "Students learn about the world's main sources of energy and how supply varies by region."),
        ("Food Security and Distribution", "Students learn about the challenges of ensuring food security around the world."),
        ("Natural Hazards: Earthquakes and Volcanoes", "Students learn how earthquakes and volcanic eruptions affect people and places."),
        ("Natural Hazards: Hurricanes and Floods", "Students learn how hurricanes and floods form and affect communities."),
        ("Climate Change and Its Effects", "Students learn the causes and effects of climate change on people and the environment."),
        ("Environmental Conservation and Protected Areas", "Students learn how protected areas help conserve the environment."),
        ("Deforestation and Land Degradation", "Students learn the causes and consequences of deforestation and land degradation."),
        ("Deserts and Desertification", "Students learn how deserts form and how desertification threatens land."),
        ("Polar Regions and Glaciers", "Students learn about the physical features and challenges of polar regions and glaciers."),
        ("Political Boundaries and Nation-States", "Students learn how political boundaries define nation-states."),
        ("Cultural Geography and Diversity", "Students learn how culture varies across different places and peoples."),
        ("Transportation and Infrastructure Networks", "Students learn how transportation networks connect places and support development."),
        ("Sustainable Development Goals", "Students learn about the United Nations Sustainable Development Goals and their purpose."),
        ("Urban Planning and Smart Cities", "Students learn how urban planning shapes modern and future cities."),
        ("Ocean Currents and Marine Geography", "Students learn how ocean currents affect climate and marine environments."),
        ("Fieldwork and Geographic Enquiry Skills", "Students learn to plan and carry out geographic fieldwork and enquiry."),
        ("Case Study: A Newly Industrialised Country", "Students study a specific newly industrialised country to understand patterns of economic change."),
    ],
    "World History": [
        ("Ancient Mesopotamia and the First Cities", "Students learn how the world's first cities developed in ancient Mesopotamia."),
        ("Ancient Egypt and the Nile Civilisation", "Students learn how the Nile River shaped the civilisation of ancient Egypt."),
        ("Ancient Greece: Democracy and Philosophy", "Students learn how ancient Greece developed early democracy and philosophy."),
        ("The Roman Empire: Rise and Fall", "Students learn the key events in the rise and fall of the Roman Empire."),
        ("The Byzantine Empire", "Students learn how the Byzantine Empire preserved and adapted Roman traditions."),
        ("The Islamic Golden Age", "Students learn about the scientific and cultural achievements of the Islamic Golden Age."),
        ("Medieval Europe and Feudalism", "Students learn how feudalism structured medieval European society."),
        ("The Mongol Empire", "Students learn how the Mongol Empire became the largest contiguous land empire in history."),
        ("Great African Kingdoms: Mali and Songhai", "Students learn about the wealth and influence of the Mali and Songhai empires."),
        ("Dynasties of Ancient and Imperial China", "Students learn about key dynasties that shaped ancient and imperial China."),
        ("The Mughal Empire in India", "Students learn about the culture and rule of the Mughal Empire in India."),
        ("The Renaissance: Art and Ideas", "Students learn how the Renaissance transformed art, science, and ideas in Europe."),
        ("The Age of Exploration", "Students learn about the voyages and consequences of the Age of Exploration."),
        ("The Reformation", "Students learn how the Reformation changed religion and society in Europe."),
        ("The Scientific Revolution", "Students learn how new discoveries during the Scientific Revolution changed understanding of the natural world."),
        ("The Enlightenment and New Ideas", "Students learn how Enlightenment thinkers influenced ideas about government and society."),
        ("The American Revolution", "Students learn the causes and consequences of the American Revolution."),
        ("The French Revolution", "Students learn the causes and consequences of the French Revolution."),
        ("The Industrial Revolution", "Students learn how the Industrial Revolution changed work, technology, and society."),
        ("Colonialism and Imperialism", "Students learn how colonialism and imperialism affected peoples and regions around the world."),
        ("Unification of Italy and Germany", "Students learn how Italy and Germany became unified nations in the nineteenth century."),
        ("World War I: Causes and Consequences", "Students learn the causes and global consequences of World War I."),
        ("The Russian Revolution", "Students learn the causes and outcomes of the Russian Revolution."),
        ("The Rise of Fascism in Europe", "Students learn how fascism rose to power in parts of Europe between the world wars."),
        ("Latin American Independence Movements", "Students learn how Latin American nations gained independence from colonial rule."),
        ("The Formation of the United Nations", "Students learn why and how the United Nations was formed after World War II."),
        ("Decolonisation in Africa and Asia", "Students learn how nations in Africa and Asia gained independence in the twentieth century."),
        ("The Civil Rights Movement", "Students learn about the struggle for civil rights and racial equality in the twentieth century."),
        ("Apartheid in South Africa", "Students learn about the system of apartheid and the movement that ended it."),
        ("The Space Race", "Students learn how competition between nations drove the achievements of the Space Race."),
        ("The Fall of the Berlin Wall", "Students learn the significance of the fall of the Berlin Wall for Europe and the world."),
        ("The End of the Soviet Union", "Students learn the events that led to the end of the Soviet Union."),
        ("Post-War Reconstruction in Europe and Japan", "Students learn how Europe and Japan rebuilt after World War II."),
        ("Genocide and Human Rights After 1945", "Students learn how the world responded to genocide and developed human rights protections after 1945."),
        ("Globalisation in the Late Twentieth Century", "Students learn how globalisation reshaped economies and cultures in the late twentieth century."),
        ("The Non-Aligned Movement", "Students learn how some nations chose not to align with either side during the Cold War."),
        ("Revolutions in Communication and Technology", "Students learn how changes in communication and technology transformed the modern world."),
        ("Turning Points of the Twentieth Century", "Students review and connect key turning points across twentieth-century world history."),
    ],
    "Islamic Studies": [
        ("The Five Pillars of Islam: An Overview", "Students learn about the Five Pillars that form the foundation of Muslim practice."),
        ("The Islamic Calendar and Important Dates", "Students learn how the lunar Islamic calendar works and its key dates."),
        ("Ramadan and the Practice of Fasting", "Students learn the purpose and practice of fasting during the month of Ramadan."),
        ("Zakat and the Value of Charity", "Students learn about Zakat and the importance of charitable giving in Islam."),
        ("The Hajj: Pilgrimage to Makkah", "Students learn about the rituals and significance of the pilgrimage to Makkah."),
        ("The Significance of Daily Prayer", "Students learn the role and structure of daily prayer in Muslim life."),
        ("Life of the Prophet Muhammad: An Overview", "Students learn key events in the life of the Prophet Muhammad and his role in Islamic history."),
        ("The Early Companions of the Prophet", "Students learn about the lives and contributions of the Prophet's early companions."),
        ("The Compilation and Preservation of the Qur'an", "Students learn how the Qur'an was compiled and preserved as a historical process."),
        ("An Introduction to Hadith Literature", "Students learn what Hadith literature is and its role in Islamic scholarship."),
        ("Foundations of Islamic Ethics and Character", "Students learn core ethical values emphasized in Islamic teaching."),
        ("Honesty and Trustworthiness in Islamic Teaching", "Students learn why honesty and trustworthiness are valued character traits in Islam."),
        ("Respect for Parents and Elders", "Students learn how Islamic teaching emphasizes respect for parents and elders."),
        ("The Concept of Ummah: Community in Islam", "Students learn the meaning of Ummah and the importance of community in Islam."),
        ("Charity and Social Responsibility", "Students learn how charity and social responsibility are encouraged in Islamic teaching."),
        ("Environmental Stewardship in Islamic Teaching", "Students learn how Islamic teaching encourages care for the natural environment."),
        ("Animal Welfare in Islamic Tradition", "Students learn how Islamic tradition emphasizes kindness toward animals."),
        ("The Spread of Islam in Its Early Centuries", "Students learn how Islam spread across regions in its early centuries."),
        ("Islamic Civilisation in Andalusia (Spain)", "Students learn about the culture and achievements of Islamic civilisation in Andalusia."),
        ("The House of Wisdom and the Translation Movement", "Students learn how the House of Wisdom advanced learning through translation and scholarship."),
        ("Muslim Contributions to Mathematics", "Students learn about historical Muslim scholars' contributions to mathematics."),
        ("Muslim Contributions to Astronomy", "Students learn about historical Muslim scholars' contributions to astronomy."),
        ("Muslim Contributions to Medicine", "Students learn about historical Muslim scholars' contributions to medicine."),
        ("Notable Women Scholars in Islamic History", "Students learn about notable women scholars and their contributions in Islamic history."),
        ("The Tradition of Islamic Education and Madrasas", "Students learn how madrasas developed as centers of Islamic education."),
        ("An Introduction to Islamic Jurisprudence (Fiqh)", "Students learn what Islamic jurisprudence is and its role in guiding daily life."),
        ("Islamic Festivals: Eid al-Fitr and Eid al-Adha", "Students learn the significance and customs of Eid al-Fitr and Eid al-Adha."),
        ("Mosque Architecture Around the World", "Students learn how mosque architecture reflects regional cultures around the world."),
        ("Islamic Geometric Patterns and Design", "Students learn the mathematical principles behind Islamic geometric art and design."),
        ("The Art of Arabic Calligraphy", "Students learn about the styles and history of Arabic calligraphy as an art form."),
        ("Interfaith Relations in Islamic History", "Students learn examples of interfaith relations and coexistence across Islamic history."),
        ("Basics of Islamic Ethical Finance", "Students learn the basic principles behind Islamic approaches to ethical finance."),
        ("Family Values in Islamic Teaching", "Students learn how Islamic teaching describes the roles and values of family life."),
        ("The Etiquette of Mosque Attendance", "Students learn the customs and etiquette associated with visiting a mosque."),
        ("The Tradition of Qur'an Memorisation", "Students learn about the historical and cultural tradition of memorising the Qur'an."),
        ("Great Libraries of the Islamic World", "Students learn about historic libraries that preserved and advanced knowledge in the Islamic world."),
        ("Muslim Travellers and Explorers", "Students learn about notable Muslim travellers and explorers and their journeys."),
        ("The Geography of the Contemporary Muslim World", "Students learn about the geography and diversity of Muslim-majority regions today."),
        ("Islamic Contributions to Global Trade History", "Students learn how Muslim traders shaped historical global trade networks."),
    ],
    "Coding": [
        ("Variables and Data Types in Python", "Students learn to create variables and use core Python data types such as integers, floats, and strings."),
        ("Input and Output in Python", "Students learn to read user input and display output using Python."),
        ("Conditional Statements: If, Elif and Else", "Students learn to control program flow using conditional statements."),
        ("Boolean Logic and Comparison Operators", "Students learn to use boolean values and comparison operators to test conditions."),
        ("For Loops and Iteration", "Students learn to repeat actions using for loops in Python."),
        ("While Loops and Loop Control", "Students learn to use while loops and control loop execution with break and continue."),
        ("Nested Loops", "Students learn to write and trace loops placed inside other loops."),
        ("Lists and List Operations", "Students learn to create, index, and modify lists in Python."),
        ("Dictionaries and Key-Value Pairs", "Students learn to store and access data using Python dictionaries."),
        ("Tuples and Sets in Python", "Students learn the differences between tuples, sets, and lists and when to use each."),
        ("String Manipulation and Formatting", "Students learn to slice, concatenate, and format strings in Python."),
        ("Working with User Input Validation", "Students learn to check and validate user input in a program."),
        ("Writing Pseudocode and Flowcharts", "Students learn to plan programs using pseudocode and flowcharts before coding."),
        ("Introduction to Algorithms", "Students learn what an algorithm is and how to describe one step by step."),
        ("Searching Algorithms: Linear and Binary Search", "Students learn how linear search and binary search find items in a list."),
        ("Sorting Algorithms: Bubble and Selection Sort", "Students learn how bubble sort and selection sort arrange data in order."),
        ("Introduction to Recursion", "Students learn the basic idea of a function that calls itself to solve a problem."),
        ("Debugging Techniques and Common Errors", "Students learn strategies for finding and fixing common coding errors."),
        ("Exception Handling with Try and Except", "Students learn to handle runtime errors gracefully using try and except blocks."),
        ("Comments and Code Documentation", "Students learn to write clear comments and documentation for their code."),
        ("Introduction to Classes and Objects", "Students learn the basic idea of grouping data and behavior into classes and objects."),
        ("Introduction to Version Control with Git", "Students learn the basic purpose and commands of version control with Git."),
        ("Reading and Writing Files in Python", "Students learn to open, read, and write text files using Python."),
        ("Introduction to Turtle Graphics", "Students learn to draw shapes and patterns using Python's turtle graphics module."),
        ("Building a Simple Text-Based Game", "Students learn to combine loops, conditionals, and input to build a simple game."),
        ("Introduction to HTML Structure", "Students learn the basic tags and structure used to build a web page."),
        ("Introduction to CSS Styling", "Students learn to style web page elements using basic CSS."),
        ("Introduction to JavaScript Basics", "Students learn the basic syntax and purpose of JavaScript in web pages."),
        ("Binary Numbers and How Computers Count", "Students learn how computers represent numbers using the binary system."),
        ("Computer Hardware Basics", "Students learn the function of key computer hardware components."),
        ("How the Internet Works", "Students learn the basic process by which data travels across the internet."),
        ("Introduction to APIs", "Students learn what an API is and how programs use one to exchange data."),
        ("Introduction to Databases", "Students learn the basic purpose and structure of a database."),
        ("Algorithmic Thinking and Problem Decomposition", "Students learn to break a large problem into smaller steps before coding a solution."),
        ("Introduction to Simple GUIs", "Students learn the basics of building a simple graphical user interface."),
        ("Introduction to Game Design Concepts", "Students learn basic concepts used in planning a simple game."),
        ("Ethics in Coding and Digital Citizenship", "Students learn about responsible and ethical behavior when writing and sharing code."),
        ("Project Planning for Software Development", "Students learn to plan a small coding project from idea to finished program."),
        ("Introduction to Cybersecurity Concepts", "Students learn basic concepts of keeping programs and data secure."),
    ],
    "World Literature": [
        ("The Short Story as a Literary Form", "Students learn the defining features of the short story as a literary form."),
        ("Folk Tales and Fables Around the World", "Students explore folk tales and fables from different cultures and their lessons."),
        ("Greek Mythology and Its Heroes", "Students learn about key figures and stories in Greek mythology."),
        ("Norse Mythology and Legends", "Students learn about key figures and stories in Norse mythology."),
        ("Epic Poetry: Gilgamesh and Homer", "Students learn about the tradition of epic poetry through works such as Gilgamesh and Homer's epics."),
        ("An Introduction to Shakespeare", "Students learn about the life, era, and themes found in Shakespeare's plays."),
        ("Fairy Tales Across Cultures", "Students compare fairy tales from different cultures and their common patterns."),
        ("The Fantasy Genre", "Students learn the defining features and conventions of the fantasy genre."),
        ("The Science Fiction Genre", "Students learn the defining features and conventions of the science fiction genre."),
        ("The Mystery and Detective Genre", "Students learn the defining features and conventions of mystery and detective fiction."),
        ("Historical Fiction", "Students learn how historical fiction blends real events with invented stories."),
        ("Coming-of-Age Stories", "Students explore the themes and structure common to coming-of-age stories."),
        ("Introduction to Graphic Novels", "Students learn how graphic novels combine text and images to tell a story."),
        ("Poetry Forms: Haiku and Sonnet", "Students learn the structure and traditions of haiku and sonnet poetry forms."),
        ("Drama and Theatre Traditions", "Students learn about drama and theatre traditions from different cultures."),
        ("Oral Storytelling Traditions", "Students learn how oral storytelling traditions have preserved culture and history."),
        ("Literature in Translation", "Students learn how literature is translated and why translation choices matter."),
        ("An Overview of African Literature", "Students explore themes and notable works from African literature."),
        ("An Overview of Asian Literature", "Students explore themes and notable works from Asian literature."),
        ("Magical Realism in Latin American Literature", "Students learn about the style of magical realism found in Latin American literature."),
        ("An Overview of Middle Eastern Literature", "Students explore themes and notable works from Middle Eastern literature."),
        ("An Overview of European Literature", "Students explore themes and notable works from European literature."),
        ("Dystopian Fiction", "Students learn the defining features and themes of dystopian fiction."),
        ("Adventure and Survival Literature", "Students explore the themes and conventions of adventure and survival stories."),
        ("Memoir and Autobiography", "Students learn how memoir and autobiography share a writer's own experiences."),
        ("Understanding Literary Awards", "Students learn about major literary awards and their significance."),
        ("Classics of Children's Literature", "Students explore well-known classic works of children's literature."),
        ("Allegory in Literature", "Students learn how allegory uses story elements to represent deeper meanings."),
        ("Satire and Its Purpose", "Students learn how satire uses humor and exaggeration to critique society."),
        ("Romanticism as a Literary Movement", "Students learn the key ideas and features of the Romantic literary movement."),
        ("Realism as a Literary Movement", "Students learn the key ideas and features of the Realist literary movement."),
        ("Comparing Novels and Their Film Adaptations", "Students learn to compare a novel with its film adaptation."),
        ("Character Archetypes in World Literature", "Students learn to recognize common character archetypes across world literature."),
        ("Narrative Perspective Across Cultures", "Students compare how narrative perspective is used in stories from different cultures."),
        ("Themes of Courage in Literature", "Students explore how courage is portrayed as a theme across different stories."),
        ("Themes of Friendship in Literature", "Students explore how friendship is portrayed as a theme across different stories."),
        ("The Hero's Journey Across Cultures", "Students learn the pattern of the hero's journey found in stories from many cultures."),
        ("Proverbs and Wisdom Literature", "Students explore proverbs and wisdom literature from different cultures."),
        ("Diversity and Representation in World Literature", "Students learn why diverse voices and perspectives matter in world literature."),
    ],
    "Art": [
        ("Elements of Art: Line, Shape and Form", "Students learn to identify and use line, shape, and form as elements of art."),
        ("Elements of Art: Colour, Value and Texture", "Students learn to identify and use colour, value, and texture as elements of art."),
        ("Principles of Design: Balance and Contrast", "Students learn how balance and contrast are used to organize a work of art."),
        ("Principles of Design: Emphasis and Movement", "Students learn how emphasis and movement guide the viewer's eye in a work of art."),
        ("Principles of Design: Pattern and Rhythm", "Students learn how pattern and rhythm create visual interest in a work of art."),
        ("Colour Theory and the Colour Wheel", "Students learn how the colour wheel explains relationships between colours."),
        ("Drawing Techniques: Shading and Hatching", "Students learn shading and hatching techniques to create depth in drawings."),
        ("Perspective Drawing: One and Two Point", "Students learn to create the illusion of depth using one-point and two-point perspective."),
        ("Still Life Drawing and Composition", "Students learn to arrange and draw a still life composition."),
        ("Portraiture and Facial Proportion", "Students learn the basic proportions used to draw a human face."),
        ("Landscape Art Techniques", "Students learn techniques for representing outdoor scenes in landscape art."),
        ("Watercolour Painting Techniques", "Students learn basic techniques for painting with watercolours."),
        ("Acrylic Painting Techniques", "Students learn basic techniques for painting with acrylic paint."),
        ("Introduction to Sculpture", "Students learn the basic methods and materials used to create sculpture."),
        ("Introduction to Printmaking", "Students learn the basic process of creating a print from a prepared surface."),
        ("Introduction to Ceramics", "Students learn the basic process of shaping and finishing clay in ceramics."),
        ("Collage and Mixed Media Art", "Students learn to combine different materials to create a collage or mixed media piece."),
        ("Introduction to Photography", "Students learn basic composition principles for taking photographs."),
        ("Introduction to Digital Art", "Students learn the basic tools and techniques used to create digital art."),
        ("Introduction to Graphic Design", "Students learn how graphic design communicates ideas through visual layout."),
        ("Typography and Lettering", "Students learn how typeface and lettering choices affect a design's message."),
        ("Introduction to Animation", "Students learn the basic principles behind creating the illusion of movement in animation."),
        ("Mural and Public Art", "Students learn how murals and public art engage communities."),
        ("Textile Art and Design", "Students learn basic techniques and traditions used in textile art."),
        ("Architecture as Visual Art", "Students learn how architecture can be studied and appreciated as a visual art form."),
        ("Comic Art and Sequential Storytelling", "Students learn how comic art tells a story through a sequence of panels."),
        ("Renaissance Art and Its Innovations", "Students learn the artistic innovations that defined the Renaissance period."),
        ("Impressionism and Light in Art", "Students learn how Impressionist artists used light and colour in new ways."),
        ("Cubism and Multiple Perspectives", "Students learn how Cubist artists represented multiple perspectives in one image."),
        ("Surrealism and the Subconscious", "Students learn how Surrealist artists explored dreams and the subconscious mind."),
        ("Pop Art and Popular Culture", "Students learn how Pop artists drew inspiration from popular and consumer culture."),
        ("Art of Ancient Civilisations", "Students explore the art produced by ancient civilisations around the world."),
        ("Indigenous and Folk Art Traditions", "Students explore indigenous and folk art traditions from different cultures."),
        ("Symbolism in Visual Art", "Students learn how artists use symbols to convey meaning in visual art."),
        ("Art Criticism: Describing and Interpreting", "Students learn a structured process for describing and interpreting a work of art."),
        ("Self-Portraiture and Identity in Art", "Students learn how artists use self-portraits to explore identity."),
        ("Environmental and Land Art", "Students learn how some artists use natural materials and landscapes to create art."),
        ("Careers in the Visual Arts", "Students explore different career paths available in the visual arts."),
        ("Building a Personal Art Portfolio", "Students learn how to select and organize their own work into an art portfolio."),
    ],
    "Music": [
        ("Reading Musical Notation", "Students learn to read notes, rests, and staff notation."),
        ("Rhythm and Meter", "Students learn to count and perform rhythms in different meters."),
        ("Time Signatures", "Students learn how time signatures organize beats into measures."),
        ("Major and Minor Scales", "Students learn to build and recognize major and minor scales."),
        ("Key Signatures", "Students learn to read and identify key signatures in written music."),
        ("Intervals in Music", "Students learn to identify and name intervals between two notes."),
        ("Melody Writing Basics", "Students learn basic principles for composing a simple melody."),
        ("Dynamics and Tempo Terms", "Students learn common dynamics and tempo terms used in written music."),
        ("Ear Training Basics", "Students learn to identify pitches, intervals, and rhythms by ear."),
        ("Instrument Families of the Orchestra", "Students learn to identify the string, woodwind, brass, and percussion families."),
        ("String Instruments Basics", "Students learn how string instruments produce sound and their common types."),
        ("Woodwind Instruments Basics", "Students learn how woodwind instruments produce sound and their common types."),
        ("Brass Instruments Basics", "Students learn how brass instruments produce sound and their common types."),
        ("Percussion Instruments Basics", "Students learn how percussion instruments produce sound and their common types."),
        ("Introduction to Piano Technique", "Students learn basic hand position and technique for playing piano."),
        ("Introduction to Guitar Technique", "Students learn basic chord shapes and technique for playing guitar."),
        ("Vocal Technique and Singing", "Students learn basic breathing and vocal technique for singing."),
        ("Improvisation Basics", "Students learn basic strategies for improvising a simple musical phrase."),
        ("Composing a Simple Melody", "Students learn to compose and notate an original short melody."),
        ("Songwriting Basics", "Students learn the basic structure used to write a simple song."),
        ("Music of the Baroque Period", "Students learn the characteristics and composers of the Baroque period."),
        ("Music of the Classical Period", "Students learn the characteristics and composers of the Classical period."),
        ("Music of the Romantic Period", "Students learn the characteristics and composers of the Romantic period."),
        ("Music of the Twentieth Century", "Students learn how music styles diversified during the twentieth century."),
        ("Introduction to Jazz", "Students learn the origins and key characteristics of jazz music."),
        ("Introduction to Blues Music", "Students learn the origins and key characteristics of blues music."),
        ("Introduction to Rock Music", "Students learn the origins and key characteristics of rock music."),
        ("Introduction to Hip Hop Music", "Students learn the origins and key characteristics of hip hop music."),
        ("Introduction to Electronic Music", "Students learn the origins and key characteristics of electronic music."),
        ("Folk Music Traditions", "Students explore folk music traditions from different cultures."),
        ("African Drumming Traditions", "Students learn about the rhythms and traditions of African drumming."),
        ("Indian Classical Music Basics", "Students learn the basic concepts of raga and tala in Indian classical music."),
        ("Latin American Music Traditions", "Students explore music traditions and rhythms from Latin America."),
        ("Middle Eastern Maqam Traditions", "Students learn the basic concept of maqam in Middle Eastern music traditions."),
        ("Music for Film and Media", "Students learn how music is used to support storytelling in film and media."),
        ("Introduction to Music Technology", "Students learn how technology is used to record and produce music."),
        ("Introduction to Music Notation Software", "Students learn the basics of writing music using notation software."),
        ("Playing in Bands and Ensembles", "Students learn the skills needed to play music together in a band or ensemble."),
        ("Music and Cultural Identity", "Students learn how music reflects and shapes cultural identity."),
    ],
    "Survival Skills": [
        ("Map Reading and Compass Navigation", "Students learn to read a map and use a compass to navigate."),
        ("Basic Knot Tying", "Students learn to tie several useful outdoor knots."),
        ("Fire Safety and Controlled Fire Starting", "Students learn safe methods for starting and controlling a fire outdoors."),
        ("Building an Emergency Shelter", "Students learn basic methods for building a simple emergency shelter."),
        ("Water Purification Methods", "Students learn methods for making water safer to drink in an emergency."),
        ("Food Safety in the Outdoors", "Students learn how to store and prepare food safely outdoors."),
        ("Recognising Edible and Non-Edible Plants", "Students learn general caution and identification basics for edible and non-edible plants."),
        ("Reading Weather Signs", "Students learn to recognize natural signs that indicate changing weather."),
        ("Building an Emergency Preparedness Kit", "Students learn what items belong in a basic emergency preparedness kit."),
        ("Wilderness Signaling for Help", "Students learn basic signaling methods to attract help in the wilderness."),
        ("Hiking Safety Basics", "Students learn safety practices to follow before and during a hike."),
        ("Basic Camping Skills", "Students learn basic skills for setting up and staying safe at a campsite."),
        ("Safe Encounters with Wildlife", "Students learn how to respond safely if they encounter wildlife outdoors."),
        ("Outdoor Cooking Basics", "Students learn basic safe methods for cooking food outdoors."),
        ("Recognising Signs of a Medical Emergency", "Students learn to recognize common signs that indicate a medical emergency."),
        ("Basic CPR Awareness", "Students learn the basic concept and steps of CPR at an age-appropriate level."),
        ("Responding to Burns and Cuts", "Students learn basic first response steps for minor burns and cuts."),
        ("Choking Response Awareness", "Students learn to recognize choking and the basic response steps at an age-appropriate level."),
        ("Road and Traffic Safety", "Students learn safe practices for walking, cycling, and crossing roads."),
        ("Home Fire Safety and Escape Plans", "Students learn to plan and practice a home fire escape route."),
        ("Earthquake Preparedness", "Students learn safety steps to take before, during, and after an earthquake."),
        ("Flood Safety and Preparedness", "Students learn safety steps to take before, during, and after a flood."),
        ("Severe Weather Safety: Lightning and Storms", "Students learn safety steps to take during lightning and severe storms."),
        ("Sun Safety and Preventing Heat Illness", "Students learn how to prevent sunburn and heat-related illness."),
        ("Cold Weather Survival Basics", "Students learn basic strategies for staying safe in cold weather."),
        ("Water Safety and Safe Swimming", "Students learn basic rules for staying safe around and in water."),
        ("Personal Safety and Stranger Awareness", "Students learn strategies for staying safe around unfamiliar people."),
        ("Online Safety and Digital Wellbeing", "Students learn strategies for staying safe and healthy online."),
        ("Basic Sewing and Gear Repair", "Students learn basic sewing skills for repairing simple gear."),
        ("Personal Hygiene in the Outdoors", "Students learn how to maintain personal hygiene while outdoors."),
        ("Orienteering Skills", "Students learn to use a map and compass together to navigate a course."),
        ("Basic Tool Safety and Use", "Students learn safe practices for using common outdoor tools."),
        ("Packing an Effective Survival Kit", "Students learn how to select and pack items for an effective survival kit."),
        ("Communication During an Emergency", "Students learn effective ways to communicate during an emergency situation."),
        ("Teamwork in Crisis Situations", "Students learn the value of teamwork when responding to a crisis."),
        ("Building Mental Resilience", "Students learn strategies for staying calm and resilient in difficult situations."),
        ("Situational Awareness Skills", "Students learn to notice and respond to their surroundings for safety."),
        ("Basic Self-Rescue Techniques", "Students learn basic techniques for helping themselves in a minor emergency."),
        ("Urban Survival and Emergency Planning", "Students learn basic emergency planning skills relevant to urban settings."),
    ],
    "General Knowledge": [
        ("World Capitals and Flags", "Students learn to identify major world capitals and national flags."),
        ("Wonders of the Ancient World", "Students learn about the Seven Wonders of the Ancient World."),
        ("New Seven Wonders of the World", "Students learn about the modern New Seven Wonders of the World."),
        ("World Currencies and Exchange", "Students learn about different world currencies and the basic idea of exchange rates."),
        ("An Overview of World Religions", "Students learn basic facts about the world's major religions."),
        ("Famous Explorers in History", "Students learn about explorers who charted new routes and territories in history."),
        ("Milestones in Space Exploration", "Students learn about key milestones in the history of space exploration."),
        ("The History of the Olympic Games", "Students learn how the ancient and modern Olympic Games developed."),
        ("Sports Around the World", "Students learn about popular sports played in different regions of the world."),
        ("World Records and Extraordinary Achievements", "Students learn about notable world records and extraordinary achievements."),
        ("International Organisations: The United Nations", "Students learn the purpose and structure of the United Nations."),
        ("International Organisations: The World Health Organization", "Students learn the purpose and role of the World Health Organization."),
        ("Global Environmental Issues", "Students learn about major environmental issues facing the world today."),
        ("Trends in Modern Technology", "Students learn about current trends shaping modern technology."),
        ("Famous Artists and Their Works", "Students learn about famous artists and notable works of art."),
        ("Famous Composers and Musicians", "Students learn about famous composers and musicians from history."),
        ("Languages of the World", "Students learn facts about the diversity of languages spoken around the world."),
        ("World Festivals and Celebrations", "Students learn about festivals and celebrations from cultures around the world."),
        ("Basics of the Global Economy", "Students learn basic concepts about how the global economy functions."),
        ("Famous Scientists and Their Discoveries", "Students learn about famous scientists and the discoveries they are known for."),
        ("The Animal Kingdom: Amazing Facts", "Students learn interesting facts about animals from around the world."),
        ("Oceans of the World", "Students learn facts about the world's major oceans."),
        ("The World's Longest Rivers", "Students learn about the world's longest rivers and their locations."),
        ("The World's Tallest Mountains", "Students learn about the world's tallest mountains and their locations."),
        ("Famous Bridges and Feats of Engineering", "Students learn about famous bridges and other notable feats of engineering."),
        ("The History of the Internet", "Students learn key milestones in the history and development of the internet."),
        ("Cuisines of the World", "Students learn about distinctive dishes and ingredients from cuisines around the world."),
        ("Calendars and Timekeeping Systems", "Students learn about different calendar systems used around the world."),
        ("Systems of Measurement Around the World", "Students learn about different measurement systems used around the world."),
        ("Milestones in Transportation History", "Students learn about key milestones in the history of transportation."),
        ("National Symbols and Their Meaning", "Students learn about national symbols and what they represent."),
        ("World Population and Demographics", "Students learn basic facts about world population and demographic trends."),
        ("Famous Authors and Their Books", "Students learn about famous authors and notable books they have written."),
        ("Understanding the News and Media Literacy", "Students learn basic skills for understanding and evaluating news media."),
        ("Global Holidays and Their Origins", "Students learn about global holidays and how they originated."),
        ("Famous Architectural Landmarks", "Students learn about famous architectural landmarks around the world."),
        ("The History of Money and Trade", "Students learn how money and trade systems developed throughout history."),
        ("World Time Zones in Everyday Life", "Students learn how world time zones affect travel and daily communication."),
        ("Notable Women in World History", "Students learn about notable women and their contributions throughout world history."),
    ],
    "Cooking": [
        ("Kitchen Safety Essentials", "Students learn essential safety rules for working in a kitchen."),
        ("Knife Skills and Cutting Techniques", "Students learn safe and effective basic knife cutting techniques."),
        ("Measuring Ingredients Accurately", "Students learn to measure ingredients accurately using standard tools."),
        ("Understanding Food Groups and Nutrition", "Students learn about the major food groups and basic nutrition concepts."),
        ("Reading and Following a Recipe", "Students learn to read and follow the steps and terms used in a recipe."),
        ("Meal Planning Basics", "Students learn basic strategies for planning balanced meals."),
        ("Cooking Methods: Boiling and Steaming", "Students learn how boiling and steaming are used to cook food."),
        ("Cooking Methods: Frying and Sautéing", "Students learn how frying and sautéing are used to cook food."),
        ("Cooking Methods: Roasting and Grilling", "Students learn how roasting and grilling are used to cook food."),
        ("Baking Basics", "Students learn basic baking techniques and terminology."),
        ("Introduction to Bread Making", "Students learn the basic steps involved in making bread."),
        ("Herbs and Spices in Cooking", "Students learn how herbs and spices are used to flavor food."),
        ("Building Flavour with Seasoning", "Students learn basic techniques for seasoning food effectively."),
        ("Basic Sauces and Their Uses", "Students learn a few basic sauces and how they are used in cooking."),
        ("Egg Cookery Techniques", "Students learn several basic techniques for cooking eggs."),
        ("Cooking with Dairy Products", "Students learn how dairy products are used in cooking."),
        ("Cooking with Grains and Legumes", "Students learn how to prepare common grains and legumes."),
        ("Preparing Fruits and Vegetables", "Students learn safe and effective methods for preparing fruits and vegetables."),
        ("Making Soups and Stews", "Students learn the basic steps for making a simple soup or stew."),
        ("Building a Balanced Salad", "Students learn how to build a balanced and flavorful salad."),
        ("Introduction to Desserts", "Students learn basic techniques for preparing simple desserts."),
        ("Cake Baking and Decorating Basics", "Students learn basic techniques for baking and decorating a simple cake."),
        ("Food Presentation and Plating", "Students learn basic principles for presenting food attractively on a plate."),
        ("Food Hygiene and Safe Handling", "Students learn practices that keep food safe from contamination."),
        ("Food Storage and Preservation", "Students learn methods for storing and preserving food safely."),
        ("Understanding Food Labels", "Students learn to read and interpret information on food labels."),
        ("Common Kitchen Equipment and Tools", "Students learn the names and uses of common kitchen equipment and tools."),
        ("Vegetarian and Vegan Cooking Basics", "Students learn basic principles of vegetarian and vegan cooking."),
        ("Breakfast Foods Around the World", "Students learn about breakfast foods and traditions from different cultures."),
        ("Healthy Snack Ideas", "Students learn to prepare simple, healthy snack options."),
        ("Introduction to Fermentation", "Students learn the basic concept of fermentation in food preparation."),
        ("Street Foods Around the World", "Students learn about popular street foods from different countries."),
        ("Cuisines of the World: A Survey", "Students learn about distinctive characteristics of several world cuisines."),
        ("Holiday and Festival Foods", "Students learn about foods traditionally prepared for holidays and festivals."),
        ("Farm-to-Table Concepts", "Students learn the basic concept of farm-to-table food sourcing."),
        ("Reducing Food Waste at Home", "Students learn practical strategies for reducing food waste at home."),
        ("Budgeting for Meals", "Students learn basic strategies for planning meals within a budget."),
        ("Food Allergies and Ingredient Substitutions", "Students learn about common food allergies and safe ingredient substitutions."),
        ("Table Setting and Dining Etiquette", "Students learn basic table setting and dining etiquette."),
    ],
    "Foreign Languages": [
        ("Spanish Greetings and Introductions", "Students learn basic Spanish greetings and how to introduce themselves."),
        ("Spanish Numbers and Counting", "Students learn to count and use numbers in Spanish."),
        ("Spanish Present Tense Verb Conjugation", "Students learn to conjugate regular verbs in the Spanish present tense."),
        ("Spanish Family and Everyday Vocabulary", "Students learn Spanish vocabulary for family members and everyday objects."),
        ("French Greetings and Introductions", "Students learn basic French greetings and how to introduce themselves."),
        ("French Numbers and Counting", "Students learn to count and use numbers in French."),
        ("French Present Tense Verb Conjugation", "Students learn to conjugate regular verbs in the French present tense."),
        ("French Food and Dining Vocabulary", "Students learn French vocabulary related to food and dining."),
        ("German Greetings and Introductions", "Students learn basic German greetings and how to introduce themselves."),
        ("German Numbers and Counting", "Students learn to count and use numbers in German."),
        ("German Noun Genders and Articles", "Students learn how German nouns are classified by gender and article."),
        ("German Everyday Phrases", "Students learn common everyday phrases used in German."),
        ("Mandarin Chinese Greetings and Tones", "Students learn basic Mandarin Chinese greetings and the concept of tones."),
        ("Mandarin Chinese Numbers and Counting", "Students learn to count and use numbers in Mandarin Chinese."),
        ("Introduction to Chinese Characters", "Students learn the basic structure and stroke order of Chinese characters."),
        ("Japanese Greetings and Introductions", "Students learn basic Japanese greetings and how to introduce themselves."),
        ("The Japanese Hiragana Syllabary", "Students learn to read and write basic characters of the Japanese hiragana syllabary."),
        ("The Japanese Katakana Syllabary", "Students learn to read and write basic characters of the Japanese katakana syllabary."),
        ("Introduction to Swahili Vocabulary", "Students learn basic greetings and vocabulary in Swahili."),
        ("Introduction to Hindi Vocabulary", "Students learn basic greetings and vocabulary in Hindi."),
        ("Introduction to Urdu Vocabulary", "Students learn basic greetings and vocabulary in Urdu."),
        ("Comparing World Writing Systems", "Students learn to compare alphabetic, syllabic, and logographic writing systems."),
        ("Language Families of the World", "Students learn how languages are grouped into families based on shared origins."),
        ("Cognates and False Friends Across Languages", "Students learn to recognize cognates and false friends between languages."),
        ("Common Idioms in Different Languages", "Students learn examples of idioms and their meanings in different languages."),
        ("Question Formation Across Languages", "Students learn how questions are formed differently across several languages."),
        ("Adjective Agreement in Romance Languages", "Students learn how adjectives agree with nouns in gender and number in Romance languages."),
        ("Basic Phonetics and Pronunciation", "Students learn basic phonetic concepts to improve pronunciation in a new language."),
        ("Numbers and Counting Systems Compared", "Students compare how counting systems work across different languages."),
        ("Travel Phrases for Everyday Situations", "Students learn useful travel phrases for everyday situations in a second language."),
        ("Colours and Descriptive Vocabulary", "Students learn vocabulary for colours and descriptions in a second language."),
        ("Days, Months and Telling Time", "Students learn vocabulary for days, months, and telling time in a second language."),
        ("Weather Vocabulary in a Second Language", "Students learn vocabulary for describing weather in a second language."),
        ("Introduction to American Sign Language", "Students learn basic signs and concepts of American Sign Language."),
        ("The Benefits of Bilingualism", "Students learn about the cognitive and social benefits of speaking more than one language."),
        ("Culture and Customs Through Language", "Students learn how language reflects the culture and customs of its speakers."),
        ("Formal Versus Informal Speech", "Students learn the difference between formal and informal speech in various languages."),
        ("Introduction to Portuguese Vocabulary", "Students learn basic greetings and vocabulary in Portuguese."),
        ("Introduction to Italian Vocabulary", "Students learn basic greetings and vocabulary in Italian."),
    ],
    "Social Studies": [
        ("Types of Government", "Students learn to compare different types of government systems."),
        ("Branches of Government and Separation of Powers", "Students learn how government powers are divided among different branches."),
        ("Democracy and Citizenship", "Students learn the rights and responsibilities that come with democratic citizenship."),
        ("Elections and the Voting Process", "Students learn the basic steps involved in elections and voting."),
        ("Human Rights: An Introduction", "Students learn the basic concept of universal human rights."),
        ("The Rule of Law", "Students learn why the rule of law is important to a fair society."),
        ("Constitutions and Their Purpose", "Students learn the purpose and basic structure of a constitution."),
        ("Local and Community Government", "Students learn how local and community government serves its residents."),
        ("Civic Responsibility and Participation", "Students learn ways individuals can participate responsibly in civic life."),
        ("Introduction to Economics: Supply and Demand", "Students learn how supply and demand influence prices in a market."),
        ("Types of Economic Systems", "Students learn to compare different types of economic systems."),
        ("Markets and Trade", "Students learn how markets allow the exchange of goods and services."),
        ("Taxes and Public Services", "Students learn how taxes fund public services in a community."),
        ("Labour and Workers' Rights", "Students learn about basic workers' rights and labour protections."),
        ("Consumer Rights and Responsibilities", "Students learn about the rights and responsibilities of consumers."),
        ("Poverty and Economic Development", "Students learn about the causes of poverty and strategies for economic development."),
        ("Social Class and Inequality", "Students learn how social class and inequality affect opportunity in society."),
        ("Cultural Diversity and Identity", "Students learn how cultural diversity shapes identity within communities."),
        ("Family Structures Around the World", "Students learn about different family structures found around the world."),
        ("Gender Roles and Equality", "Students learn how gender roles have changed and the importance of equality."),
        ("Religion and Society", "Students learn how religion influences values and traditions in society."),
        ("Education Systems Around the World", "Students learn how education systems differ across countries."),
        ("Social Movements in History", "Students learn about social movements that have driven change throughout history."),
        ("Understanding Propaganda and Persuasion", "Students learn to recognize propaganda and persuasive techniques."),
        ("Media's Role in Society", "Students learn how media influences public opinion and society."),
        ("Technology's Impact on Society", "Students learn how technology has changed the way society functions."),
        ("Globalisation and Its Social Effects", "Students learn how globalisation affects societies and cultures around the world."),
        ("Migration and Its Social Impact", "Students learn how migration affects both origin and destination communities."),
        ("Urbanisation and Community Change", "Students learn how urbanisation changes communities over time."),
        ("Law and Justice Systems", "Students learn the basic structure and purpose of law and justice systems."),
        ("International Law: An Introduction", "Students learn the basic purpose of international law between nations."),
        ("Non-Governmental Organisations and Their Work", "Students learn how non-governmental organisations address social and humanitarian issues."),
        ("International Institutions and Cooperation", "Students learn how international institutions promote cooperation between nations."),
        ("Social Justice and Equity", "Students learn the basic concepts of social justice and equity."),
        ("Communication and Society Over Time", "Students learn how changes in communication have shaped society over time."),
        ("Public Opinion and Society", "Students learn how public opinion forms and influences society."),
        ("Volunteering and Community Service", "Students learn the value of volunteering and community service."),
        ("Understanding Social Contracts", "Students learn the basic idea of a social contract between citizens and government."),
        ("Comparing Political Systems", "Students learn to compare features of different political systems around the world."),
    ],
    "Physical Education & Self-Defense": [
        ("Warm-Up and Cool-Down Routines", "Students learn how to safely warm up before and cool down after exercise."),
        ("Cardiovascular Fitness and Endurance", "Students learn activities that build cardiovascular fitness and endurance."),
        ("Strength Training Basics", "Students learn safe, age-appropriate basics of strength training."),
        ("Flexibility and Stretching Techniques", "Students learn stretching techniques that improve flexibility."),
        ("Muscular Endurance Training", "Students learn exercises that build muscular endurance."),
        ("Balance and Coordination Skills", "Students learn activities that develop balance and coordination."),
        ("Agility Training Drills", "Students learn drills that improve agility and quick movement."),
        ("Basketball Skills and Rules", "Students learn fundamental basketball skills and basic rules of play."),
        ("Soccer Skills and Rules", "Students learn fundamental soccer skills and basic rules of play."),
        ("Volleyball Skills and Rules", "Students learn fundamental volleyball skills and basic rules of play."),
        ("Athletics: Track and Field Events", "Students learn about common track and field events and basic technique."),
        ("Swimming Skills and Safety", "Students learn basic swimming skills and water safety practices."),
        ("Gymnastics Fundamentals", "Students learn fundamental gymnastics movements and safety practices."),
        ("Introduction to Dance as Exercise", "Students learn how dance can be used as a form of physical exercise."),
        ("Introduction to Yoga", "Students learn basic yoga poses and breathing techniques."),
        ("Cycling Safety and Skills", "Students learn safe cycling practices and basic bike handling skills."),
        ("Outdoor and Hiking Fitness", "Students learn how hiking and outdoor activity contribute to fitness."),
        ("Sportsmanship and Fair Play", "Students learn the importance of sportsmanship and fair play in sport."),
        ("Understanding Rules and Officiating", "Students learn the basic role of rules and officials in organized sport."),
        ("Leadership in Team Sports", "Students learn qualities of effective leadership in team sports."),
        ("Injury Prevention in Sport", "Students learn practices that help prevent common sports injuries."),
        ("Basic Injury Response: The RICE Method", "Students learn the Rest, Ice, Compression, Elevation method for minor injuries."),
        ("Nutrition for Young Athletes", "Students learn basic nutrition guidelines that support young athletes."),
        ("Hydration and Performance", "Students learn how proper hydration affects physical performance."),
        ("Rest, Recovery and Sleep", "Students learn why rest, recovery, and sleep matter for physical performance."),
        ("Posture and Body Alignment", "Students learn how good posture and body alignment support health."),
        ("How Exercise Affects the Body's Systems", "Students learn how exercise affects the heart, lungs, and muscles."),
        ("Introduction to Sports Psychology", "Students learn basic concepts of how mindset affects athletic performance."),
        ("Exercise and Mental Health", "Students learn how regular exercise can support mental health."),
        ("Basic Self-Defense Principles", "Students learn basic principles of self-defense, including awareness and avoidance."),
        ("Situational Awareness for Personal Safety", "Students learn to notice their surroundings to help stay safe."),
        ("Introduction to Martial Arts Basics", "Students learn basic stances and movements from martial arts traditions."),
        ("Setting Physical Boundaries Respectfully", "Students learn how to set and respect physical boundaries."),
        ("De-escalating Conflict Safely", "Students learn basic strategies for calming and avoiding physical conflict."),
        ("Recognising and Preventing Bullying", "Students learn to recognize bullying and strategies to help prevent it."),
        ("Emotional Regulation in Competitive Sport", "Students learn strategies for managing emotions during competitive sport."),
        ("Healthy Competition and Resilience", "Students learn how to handle winning and losing with resilience."),
        ("Team Communication and Cooperation", "Students learn how clear communication supports teamwork in sport."),
        ("Building a Personal Fitness Plan", "Students learn to design a simple personal fitness plan with realistic activities."),
    ],
    "Critical Thinking": [
        ("Deductive Reasoning", "Students learn to draw logically certain conclusions from given premises."),
        ("Inductive Reasoning", "Students learn to draw likely conclusions based on patterns and observations."),
        ("Recognising Logical Fallacies", "Students learn to identify common logical fallacies in arguments."),
        ("Evaluating Evidence", "Students learn to judge whether evidence adequately supports a claim."),
        ("Distinguishing Correlation from Causation", "Students learn why a correlation between two things does not always mean one causes the other."),
        ("Cause and Effect Reasoning", "Students learn to identify cause-and-effect relationships in reasoning."),
        ("Understanding Syllogisms", "Students learn the basic structure of a logical syllogism."),
        ("Argument Structure: Claims, Evidence and Reasoning", "Students learn to identify the claim, evidence, and reasoning in an argument."),
        ("Socratic Questioning", "Students learn to use Socratic questioning to examine ideas more deeply."),
        ("Questioning Assumptions", "Students learn to identify and question hidden assumptions in an argument."),
        ("Evaluating Source Credibility", "Students learn criteria for judging whether a source of information is credible."),
        ("Recognising Cognitive Biases", "Students learn to recognize common cognitive biases that affect thinking."),
        ("Recognising Bias in Arguments", "Students learn to identify bias that may affect the reasoning in an argument."),
        ("Understanding Misleading Statistics", "Students learn how statistics can be presented in misleading ways."),
        ("Fact-Checking and Media Literacy", "Students learn basic strategies for fact-checking claims found in media."),
        ("Constructing a Counterargument", "Students learn to construct a logical counterargument to a claim."),
        ("Writing an Effective Rebuttal", "Students learn to write a rebuttal that responds directly to opposing points."),
        ("Debate Techniques", "Students learn techniques for presenting and defending a position in debate."),
        ("Techniques of Persuasion", "Students learn common techniques used to persuade an audience."),
        ("Problem-Solving Strategies", "Students learn structured strategies for approaching a problem."),
        ("Decision-Making Models", "Students learn models that support making well-reasoned decisions."),
        ("Brainstorming Techniques", "Students learn techniques for generating a range of ideas about a topic."),
        ("Creative Thinking Strategies", "Students learn strategies that encourage original and creative thinking."),
        ("Lateral Thinking Puzzles", "Students learn to solve puzzles that require thinking beyond obvious solutions."),
        ("Analogical Reasoning", "Students learn to reason by comparing similarities between two different situations."),
        ("Ethical Reasoning and Dilemmas", "Students learn to reason through simple ethical dilemmas."),
        ("Introduction to Systems Thinking", "Students learn to consider how parts of a system interact and affect each other."),
        ("Mind Mapping for Problem Solving", "Students learn to use mind maps to organize ideas when solving a problem."),
        ("Introduction to SWOT Analysis", "Students learn to use a SWOT analysis to evaluate strengths, weaknesses, opportunities, and threats."),
        ("Assessing and Managing Risk", "Students learn basic strategies for assessing and managing risk in a decision."),
        ("Metacognition: Thinking About Thinking", "Students learn to reflect on and evaluate their own thinking process."),
        ("Open Versus Closed Questions", "Students learn the difference between open and closed questions and when to use each."),
        ("Scientific Reasoning", "Students learn how scientific reasoning uses evidence to test explanations."),
        ("Mathematical and Quantitative Reasoning", "Students learn to reason logically using numbers and quantitative information."),
        ("Logic Puzzles and Games", "Students learn to apply logical reasoning to solve puzzles and games."),
        ("Reasoning Under Uncertainty", "Students learn strategies for making reasoned decisions when information is incomplete."),
        ("Introduction to Game Theory", "Students learn the basic idea of how game theory models strategic decisions."),
        ("Philosophical Thought Experiments", "Students learn to reason through classic philosophical thought experiments."),
        ("Applying Critical Thinking to Everyday Decisions", "Students learn to apply critical thinking skills to decisions in everyday life."),
    ],
    "Health Education": [
        ("Nutrition Basics and the Food Pyramid", "Students learn the basics of balanced nutrition using the food pyramid or plate model."),
        ("Physical Activity Guidelines for Teens", "Students learn recommended guidelines for physical activity at their age."),
        ("Sleep Hygiene and Its Importance", "Students learn habits that support healthy sleep."),
        ("Personal Hygiene Practices", "Students learn everyday personal hygiene practices that support health."),
        ("Understanding Puberty and Body Changes", "Students learn about the physical and emotional changes that occur during puberty."),
        ("Dental and Oral Health", "Students learn habits that support good dental and oral health."),
        ("How Germs Spread and Disease Prevention", "Students learn how germs spread and basic practices that prevent illness."),
        ("Understanding Vaccines and Immunity", "Students learn the basic concept of how vaccines help build immunity."),
        ("The Immune System Basics", "Students learn the basic role of the immune system in fighting illness."),
        ("Managing Stress in Daily Life", "Students learn strategies for recognizing and managing everyday stress."),
        ("Digital Wellbeing and Screen Time", "Students learn strategies for maintaining healthy digital habits and screen time."),
        ("Body Image and Self-Esteem", "Students learn to build a healthy body image and self-esteem."),
        ("Recognising and Responding to Bullying", "Students learn to recognize bullying and how to respond or seek help."),
        ("Understanding Peer Pressure", "Students learn to recognize peer pressure and strategies for responding to it."),
        ("Making Healthy Decisions", "Students learn a decision-making process to support healthy choices."),
        ("Evaluating Health Claims and Advertising", "Students learn to critically evaluate health claims made in advertising."),
        ("Environmental Health and Wellbeing", "Students learn how environmental factors can affect personal health."),
        ("First Aid for Common Injuries", "Students learn basic first-aid responses for common minor injuries."),
        ("Safe and Responsible Use of Medicines", "Students learn safe practices for using over-the-counter and prescribed medicines."),
        ("Understanding Alcohol-Related Health Risks", "Students learn about the health risks associated with alcohol use."),
        ("Understanding Tobacco and Vaping Risks", "Students learn about the health risks associated with tobacco and vaping."),
        ("Reading Nutrition Labels", "Students learn to read and interpret nutrition labels on food packaging."),
        ("Hydration and Health", "Students learn why staying hydrated is important for overall health."),
        ("Eating Healthy on a Budget", "Students learn strategies for eating healthily while managing a budget."),
        ("Reducing Stigma Around Mental Health", "Students learn why reducing stigma around mental health matters."),
        ("Building Emotional Intelligence", "Students learn skills for recognizing and managing their own and others' emotions."),
        ("Setting Personal Health Goals", "Students learn to set realistic and achievable personal health goals."),
        ("Community Health Resources", "Students learn about resources available in their community that support health."),
        ("Introduction to Global Health Issues", "Students learn about health issues and challenges that affect people worldwide."),
        ("Understanding Body Systems and Health", "Students learn how the body's major systems work together to support health."),
        ("Safety Habits Around Water and Roads", "Students learn safety habits for staying safe around water and roads."),
        ("Healthy Screen Habits and Sleep", "Students learn how screen habits before bedtime can affect sleep quality."),
        ("Understanding Allergies and Reactions", "Students learn the basics of allergies and how the body reacts to allergens."),
        ("Building Healthy Friendships", "Students learn qualities that support healthy, respectful friendships."),
    ],
    "ICT & Computer Science": [
        ("Computer Hardware Components", "Students learn the function of key hardware components inside a computer."),
        ("Types of Software", "Students learn to distinguish between system software and application software."),
        ("Operating Systems Overview", "Students learn the basic role an operating system plays in managing a computer."),
        ("File Management and Organisation", "Students learn strategies for organizing files and folders effectively."),
        ("Input and Output Devices", "Students learn to identify common input and output devices and their functions."),
        ("Data Storage Devices", "Students learn about different types of data storage devices."),
        ("Introduction to Computer Networks", "Students learn the basic concept of how computers connect in a network."),
        ("How the Internet Works", "Students learn the basic process by which data travels across the internet."),
        ("The World Wide Web and Browsers", "Students learn the difference between the internet and the World Wide Web, and how browsers work."),
        ("Search Engines and Effective Searching", "Students learn strategies for searching effectively using search engines."),
        ("Introduction to Cybersecurity", "Students learn basic concepts for keeping computer systems and data secure."),
        ("Password Safety and Account Security", "Students learn practices for creating and protecting strong passwords."),
        ("Introduction to Encryption", "Students learn the basic idea of how encryption protects information."),
        ("Digital Citizenship", "Students learn responsible and respectful behavior when using digital technology."),
        ("Managing Your Digital Footprint", "Students learn how online activity creates a digital footprint and how to manage it."),
        ("Social Media Literacy", "Students learn to use social media thoughtfully and critically."),
        ("Using Spreadsheets for Data", "Students learn to enter, organize, and calculate data using spreadsheet software."),
        ("Word Processing Skills", "Students learn to format and organize documents using word processing software."),
        ("Creating Effective Presentations", "Students learn to design and deliver a clear, effective slide presentation."),
        ("Introduction to Databases", "Students learn the basic purpose and structure of a database."),
        ("Algorithms and Flowcharts", "Students learn to represent an algorithm's steps using a flowchart."),
        ("Binary and Data Representation", "Students learn how computers represent data using binary."),
        ("Boolean Logic and Logic Gates", "Students learn the basics of boolean logic and simple logic gates."),
        ("Introduction to Artificial Intelligence", "Students learn the basic concept of artificial intelligence and its everyday uses."),
        ("Introduction to Machine Learning", "Students learn the basic idea of how machine learning systems learn from data."),
        ("Introduction to Robotics", "Students learn basic concepts behind how robots sense and respond to their environment."),
        ("The History of Computing", "Students learn key milestones in the history of computers and computing."),
        ("Ethical Issues in Computing", "Students learn to consider ethical issues raised by computing and technology."),
        ("Intellectual Property and Copyright Online", "Students learn the basics of intellectual property and copyright as they apply online."),
        ("Introduction to Cloud Computing", "Students learn the basic concept of storing and accessing data using cloud computing."),
        ("Introduction to Computer Graphics", "Students learn basic concepts behind how computers generate and display images."),
        ("Basics of Multimedia Editing", "Students learn basic skills for editing images, audio, or video digitally."),
        ("Touch Typing Skills", "Students learn proper finger placement and technique for touch typing."),
        ("Troubleshooting Common Computer Problems", "Students learn a basic process for troubleshooting common computer problems."),
        ("Local and Wide Area Networks", "Students learn the difference between local area networks and wide area networks."),
        ("E-Commerce Basics", "Students learn the basic concepts behind how e-commerce and online shopping work."),
        ("Introduction to Web Page Structure", "Students learn the basic structure used to organize content on a web page."),
        ("Online Safety and Responsible Use", "Students learn practices that support safe and responsible use of the internet."),
        ("Emerging Technology Trends", "Students learn about current trends shaping emerging technology."),
    ],
}
