"""Grade 3 (ages 7-8) topic expansion data.

Each subject maps to a list of (title, summary) tuples. These are merged
by merge_grade_topics_expansion.py, which builds full lesson objects from
just the title and summary.
"""
from __future__ import annotations

GRADE = 3
MODULES: dict[str, list[tuple[str, str]]] = {
    "Math": [
        ("Place Value to 10,000", "Learn to read, write, and compare numbers up to ten thousand using place value charts."),
        ("Rounding Numbers", "Practice rounding whole numbers to the nearest ten, hundred, and thousand."),
        ("Addition with Regrouping", "Add multi-digit numbers using carrying across ones, tens, and hundreds columns."),
        ("Subtraction with Regrouping", "Subtract multi-digit numbers using borrowing across ones, tens, and hundreds columns."),
        ("Telling Time to the Minute", "Read analog and digital clocks to tell time to the nearest minute."),
        ("Elapsed Time", "Calculate how much time has passed between a start time and an end time."),
        ("Money: Counting and Making Change", "Count coins and bills and practice making change for simple purchases."),
        ("Measuring Length and Distance", "Measure objects using rulers and metre sticks in centimetres and metres."),
        ("Measuring Weight and Mass", "Compare and measure the mass of objects using grams and kilograms."),
        ("Measuring Capacity and Volume", "Measure liquids using millilitres and litres with cups and containers."),
        ("Introduction to Graphs and Data", "Collect data and represent it using picture graphs and bar graphs."),
        ("2D Shapes and Their Properties", "Identify and describe polygons by their sides, corners, and angles."),
        ("3D Shapes and Solids", "Identify cubes, spheres, cones, cylinders, and prisms in everyday objects."),
        ("Symmetry", "Recognize lines of symmetry in shapes and everyday objects."),
        ("Patterns and Sequences", "Identify, extend, and create number and shape patterns following a rule."),
    ],
    "English": [
        ("Parts of Speech: Nouns and Verbs", "Identify nouns and verbs and understand how they work together in sentences."),
        ("Parts of Speech: Adjectives and Adverbs", "Learn how adjectives describe nouns and adverbs describe verbs."),
        ("Building Complete Sentences", "Practice writing complete sentences with a subject and a predicate."),
        ("Compound Sentences", "Join two related sentences using conjunctions such as and, but, and or."),
        ("Punctuation Basics", "Use periods, question marks, exclamation points, and commas correctly."),
        ("Capitalization Rules", "Apply capitalization rules for names, places, and the start of sentences."),
        ("Synonyms and Antonyms", "Identify words with similar and opposite meanings to build vocabulary."),
        ("Homophones", "Recognize words that sound alike but have different spellings and meanings."),
        ("Prefixes and Suffixes", "Understand how adding prefixes and suffixes changes the meaning of words."),
        ("Reading Fluency Practice", "Practice reading aloud smoothly with correct pace, tone, and expression."),
        ("Identifying Story Elements", "Recognize character, setting, plot, and problem-solution in a story."),
        ("Main Idea and Details", "Find the main idea of a passage and the details that support it."),
        ("Sequencing Events", "Put story events and instructions in the correct order using sequence words."),
        ("Cause and Effect", "Identify cause-and-effect relationships in stories and informational texts."),
        ("Writing a Personal Narrative", "Write a short true story about a personal experience with a beginning, middle, and end."),
        ("Writing Descriptive Paragraphs", "Use descriptive words to paint a clear picture of a person, place, or thing."),
        ("Writing Friendly Letters", "Learn the parts of a friendly letter and write one to a friend or family member."),
        ("Using a Dictionary and Thesaurus", "Practice looking up word meanings and finding alternative words."),
        ("Poetry Basics", "Explore rhyme, rhythm, and simple poem forms like acrostic and haiku."),
    ],
    "Science": [
        ("Living and Non-Living Things", "Classify objects as living, non-living, or once-living based on their characteristics."),
        ("Plant Life Cycles", "Learn the stages a plant goes through from seed to mature plant."),
        ("Animal Life Cycles", "Compare the life cycles of different animals such as butterflies and frogs."),
        ("Habitats and Ecosystems", "Explore how animals and plants survive in forests, deserts, and oceans."),
        ("Animal Adaptations", "Understand how physical features help animals survive in their environment."),
        ("States of Matter", "Identify solids, liquids, and gases and how matter can change state."),
        ("Properties of Materials", "Compare materials by hardness, flexibility, and whether they float or sink."),
        ("Simple Machines", "Explore levers, pulleys, and ramps and how they make work easier."),
        ("Introduction to Energy", "Learn about different forms of energy such as light, heat, and sound."),
        ("Light and Shadows", "Explore how light travels and how shadows are formed by blocking light."),
        ("Sound and Vibration", "Discover how sound is produced by vibrations and travels through materials."),
        ("Magnets and Magnetism", "Investigate how magnets attract and repel and which materials are magnetic."),
        ("The Water Cycle", "Learn how water evaporates, condenses, and falls as precipitation."),
        ("Weather and Seasons", "Observe and describe weather patterns and the four seasons."),
        ("The Solar System", "Learn about the sun, planets, and moon and their positions in space."),
        ("Day and Night", "Understand how Earth's rotation causes day and night."),
        ("Rocks and Soil", "Explore different types of rocks and how soil is formed."),
        ("Caring for the Environment", "Learn simple ways to reduce waste, recycle, and conserve natural resources."),
    ],
    "Geography": [
        ("Introduction to Maps and Globes", "Learn how maps and globes represent the Earth and its features."),
        ("Continents and Oceans", "Identify and locate the seven continents and five oceans of the world."),
        ("Map Symbols and Legends", "Use map keys and symbols to read and interpret simple maps."),
        ("Compass Directions", "Use north, south, east, and west to describe location and direction."),
        ("Climate Zones", "Explore how climate differs across polar, temperate, and tropical regions."),
        ("Weather vs Climate", "Understand the difference between day-to-day weather and long-term climate."),
        ("Mountains and Volcanoes", "Learn how mountains and volcanoes form and where they are found."),
        ("Deserts of the World", "Explore the characteristics of hot and cold deserts and the life found there."),
        ("Forests of the World", "Compare rainforests, temperate forests, and boreal forests around the globe."),
        ("Islands and Peninsulas", "Learn how islands and peninsulas are surrounded by or connected to water."),
        ("Natural Resources", "Identify resources like water, forests, and minerals that people use from nature."),
        ("Rural and Urban Communities", "Compare life, jobs, and buildings in countryside and city communities."),
        ("Transportation Around the World", "Explore different ways people travel by land, air, and sea in various countries."),
        ("Countries and Capitals: An Introduction", "Begin learning to identify a few major countries and their capital cities."),
        ("Time Zones Basics", "Understand why different places in the world have different local times."),
        ("Human Impact on the Environment", "Learn how human activities can affect land, water, and air."),
        ("Natural Disasters", "Learn about earthquakes, floods, and storms and how communities stay safe."),
        ("Coastlines and Beaches", "Explore how coastlines are shaped by waves, tides, and erosion."),
    ],
    "World History": [
        ("What is History?", "Learn how historians study the past using artifacts, records, and stories."),
        ("Timelines and Chronology", "Practice placing events in order on a timeline using dates and sequence."),
        ("Early Human Communities", "Learn how early people hunted, gathered, and later formed settled communities."),
        ("Ancient Mesopotamia", "Explore the rivers, cities, and inventions of one of the earliest civilizations."),
        ("Ancient China", "Discover early Chinese inventions, dynasties, and the Great Wall."),
        ("Ancient India", "Learn about early cities, rivers, and traditions of the Indus Valley civilization."),
        ("The Silk Road", "Learn how traders connected Asia, the Middle East, and Europe by exchanging goods and ideas."),
        ("Ancient Rome: Daily Life", "Explore how ordinary Roman families lived, worked, and were educated."),
        ("The Great Pyramids", "Learn how and why the ancient Egyptians built the pyramids as royal tombs."),
        ("Ancient Trade and Exploration", "Discover how early sailors and traders explored new lands and seas."),
        ("The Vikings", "Learn about Viking ships, exploration, and daily life in Northern Europe."),
        ("Medieval Castles and Knights", "Explore how castles were built and the role of knights in medieval Europe."),
        ("Ancient African Kingdoms", "Learn about early African kingdoms known for trade, gold, and learning."),
        ("Native American Peoples", "Explore the diverse cultures, homes, and traditions of early Native American peoples."),
        ("Early Inventions That Changed the World", "Learn about ancient inventions like the wheel, writing, and the compass."),
        ("Explorers and New World Journeys", "Learn about early explorers who sailed across oceans to discover new lands."),
        ("Ancient Greek Democracy", "Learn how ancient Athens developed an early form of citizen government."),
        ("Historical Landmarks Around the World", "Explore famous historical sites and what they teach us about the past."),
    ],
    "Islamic Studies": [
        ("The Five Pillars of Islam", "Learn the five foundational acts of worship that guide a Muslim's daily life."),
        ("Introduction to the Quran", "Learn that the Quran is the holy book of Islam and how Muslims care for it respectfully."),
        ("The Importance of Prayer (Salah)", "Understand why and how Muslims pray five times a day."),
        ("Wudu: Preparing for Prayer", "Learn the simple steps of ritual washing before prayer."),
        ("The Month of Ramadan", "Learn why Muslims fast during Ramadan and how families celebrate together."),
        ("Eid al-Fitr Celebrations", "Explore how Muslim families celebrate the holiday marking the end of Ramadan."),
        ("Eid al-Adha Celebrations", "Learn about the holiday of sacrifice and its themes of generosity and sharing."),
        ("Zakat: Giving to Others", "Understand the importance of charity and helping those in need."),
        ("The Kaaba and the Hajj Journey", "Learn about the sacred building in Makkah and the pilgrimage Muslims undertake."),
        ("Stories of the Prophets", "Explore the good character and lessons found in stories of earlier prophets."),
        ("Good Manners in Islam", "Learn Islamic teachings about honesty, kindness, and respect for others."),
        ("Respecting Parents and Elders", "Understand the importance placed on kindness and respect toward family."),
        ("Caring for Neighbors and Community", "Learn Islamic teachings about helping neighbors and the wider community."),
        ("Mosques and Their Purpose", "Learn what a mosque is and how it serves as a place of prayer and community."),
        ("The Call to Prayer (Adhan)", "Learn about the call that reminds Muslims it is time to pray."),
        ("Honesty and Trustworthiness", "Explore Islamic teachings on telling the truth and keeping promises."),
        ("Cleanliness in Daily Life", "Learn the value Islam places on personal and community cleanliness."),
        ("Gratitude and Patience", "Explore the Islamic values of being thankful and staying patient in hard times."),
        ("Caring for Animals and Nature", "Learn Islamic teachings about kindness to animals and caring for the environment."),
    ],
    "Coding": [
        ("What is a Computer Program?", "Learn that a program is a set of step-by-step instructions a computer follows."),
        ("Sequencing in Coding", "Understand how the order of instructions affects what a program does."),
        ("Loops: Repeating Actions", "Learn how loops let a program repeat a set of steps without rewriting them."),
        ("Conditionals: If-Then Thinking", "Explore how programs make decisions using if-then logic."),
        ("Events and Triggers in Scratch", "Learn how programs can respond to clicks, key presses, and other events."),
        ("Creating Sprites and Backgrounds", "Design characters and scenes for a simple animated project."),
        ("Moving and Animating Sprites", "Use blocks to make a sprite move, turn, and glide across the screen."),
        ("Using Variables in Scratch", "Learn how variables store and change information like a score or a name."),
        ("Debugging Basics", "Learn how to find and fix simple mistakes in a program's steps."),
        ("Making a Simple Animation", "Combine sprites, costumes, and loops to create a short animation."),
        ("Making a Simple Interactive Story", "Use dialogue and events to build a short branching story project."),
        ("Introduction to Algorithms", "Learn that an algorithm is a clear set of steps to solve a problem or complete a task."),
        ("Unplugged Coding: Following Instructions", "Practice giving and following precise instructions without a computer."),
        ("Introduction to Block-Based Coding", "Understand how coding blocks snap together to build a working program."),
        ("Building a Simple Game", "Combine movement, scoring, and rules to build a simple Scratch game."),
        ("Sound and Music in Programs", "Add sound effects and music to bring a coding project to life."),
        ("Introduction to Robots and Sensors", "Learn how simple robots use sensors to respond to their surroundings."),
        ("Internet Safety Basics", "Learn simple rules for staying safe and kind while using computers online."),
        ("Sharing and Presenting a Project", "Practice explaining a coding project and how it works to an audience."),
    ],
    "World Literature": [
        ("The Tortoise and the Hare (Greece)", "Explore this Aesop fable's lesson that slow, steady effort can win over overconfidence."),
        ("Anansi the Spider Tales (West Africa)", "Discover trickster stories from West African folklore that teach cleverness and its consequences."),
        ("The Boy Who Cried Wolf (Greece)", "Explore this Aesop fable's lesson about the importance of telling the truth."),
        ("Momotaro, the Peach Boy (Japan)", "Explore this Japanese folk tale about courage, friendship, and teamwork."),
        ("The Three Billy Goats Gruff (Norway)", "Discover this Norwegian folk tale's themes of bravery and cleverness against a threat."),
        ("Cinderella Around the World", "Compare how different cultures, from Europe to Asia, tell their own version of a Cinderella-like story."),
        ("The Ugly Duckling (Denmark)", "Explore this Hans Christian Andersen tale's theme of self-acceptance and growth."),
        ("Br'er Rabbit Tales (United States)", "Discover African American folk tales about a clever rabbit who outwits bigger animals."),
        ("The Emperor's New Clothes (Denmark)", "Explore this Andersen tale's lesson about honesty and the courage to speak up."),
        ("Little Red Riding Hood (Europe)", "Discover this classic European folk tale's lesson about caution and listening to good advice."),
        ("The Panchatantra Animal Tales (India)", "Explore classic Indian animal fables that teach wisdom and clever problem-solving."),
        ("The Nightingale (China, by Andersen)", "Explore this tale's theme that natural beauty is often more valuable than imitation."),
        ("Jack and the Beanstalk (England)", "Discover this English folk tale's themes of curiosity, bravery, and consequences."),
        ("The Legend of the Dreamcatcher (Native American)", "Explore a traditional story explaining the meaning behind the dreamcatcher craft."),
        ("The Grasshopper and the Ants (Greece)", "Explore this Aesop fable's lesson about planning ahead and hard work."),
        ("The Fisherman and His Wife (Germany)", "Discover this Brothers Grimm tale's lesson about gratitude and contentment."),
        ("Journey to the West: Monkey King (China)", "Explore simplified adventures of the clever Monkey King from a beloved Chinese classic."),
        ("The Lion and the Mouse (Greece)", "Explore this Aesop fable's lesson that even small friends can offer great help."),
        ("One Thousand and One Nights: Aladdin (Middle East)", "Explore this classic Middle Eastern tale's themes of wit, wonder, and honesty."),
    ],
    "Art": [
        ("Primary and Secondary Colors", "Learn how mixing primary colors creates secondary colors on the color wheel."),
        ("Warm and Cool Colors", "Explore how warm and cool colors create different moods in artwork."),
        ("Introduction to Shading", "Practice using light and dark tones to make drawings look three-dimensional."),
        ("Line Drawing Basics", "Explore how different types of lines create shape, movement, and emotion in art."),
        ("Shape and Form in Art", "Compare flat shapes and three-dimensional forms in drawing and sculpture."),
        ("Introduction to Watercolor Painting", "Practice basic watercolor techniques like wet-on-wet and blending."),
        ("Collage Art", "Create artwork by cutting, arranging, and gluing different paper and materials."),
        ("Clay Modeling Basics", "Practice shaping simple forms and figures using clay or modeling dough."),
        ("Printmaking Basics", "Explore simple printmaking techniques like stamping and stencil printing."),
        ("Famous Artists: An Introduction", "Learn about the lives and famous works of a few well-known artists."),
        ("Self-Portraits", "Practice observing and drawing facial features to create a self-portrait."),
        ("Landscape Drawing", "Practice drawing simple outdoor scenes with foreground, middle ground, and background."),
        ("Art from Around the World", "Explore traditional art styles and crafts from different cultures."),
        ("Paper Folding and Origami", "Practice simple paper-folding techniques to create origami shapes."),
        ("Drawing with Perspective Basics", "Learn simple tricks to make near objects look bigger than far away objects."),
        ("Mixed Media Art", "Combine drawing, painting, and collage materials in a single art project."),
        ("Nature-Inspired Art", "Create artwork inspired by leaves, flowers, and other natural objects."),
        ("Comic Strip Drawing", "Learn to tell a short story using a sequence of simple drawn panels."),
        ("Recycled Art Projects", "Create art projects using recycled materials like boxes, bottles, and paper."),
    ],
    "Music": [
        ("Rhythm and Beat", "Learn to clap, tap, and identify steady beats and simple rhythmic patterns."),
        ("High and Low Pitch", "Explore how pitch changes and how to recognize high and low sounds."),
        ("Loud and Soft: Dynamics", "Learn musical terms for playing and singing loudly or softly."),
        ("Fast and Slow: Tempo", "Explore how tempo changes the feeling and energy of a piece of music."),
        ("Introduction to Musical Instruments", "Learn to identify and group instruments as string, wind, brass, or percussion."),
        ("Percussion Instruments", "Explore how drums, shakers, and other percussion instruments make sound."),
        ("String Instruments", "Learn how instruments like the violin and guitar produce sound through vibrating strings."),
        ("Wind and Brass Instruments", "Learn how instruments like the flute and trumpet make sound using air."),
        ("Singing and Vocal Basics", "Practice good posture, breathing, and pitch matching while singing."),
        ("Introduction to the Recorder", "Learn basic fingerings and notes to play simple tunes on the recorder."),
        ("Simple Rhythmic Notation", "Practice reading and clapping simple rhythms using quarter and eighth notes."),
        ("Melody and Harmony Basics", "Learn the difference between a melody and simple accompanying harmony."),
        ("Songs From Around the World", "Explore folk songs and musical styles from different cultures."),
        ("Call and Response Singing", "Practice a musical tradition where one singer leads and others answer."),
        ("Introduction to Music Composers", "Learn about the lives and famous music of a few well-known composers."),
        ("Body Percussion", "Create rhythms using clapping, stomping, and snapping instead of instruments."),
        ("Musical Instrument Families", "Group instruments by family and compare how each family makes sound."),
        ("Listening and Responding to Music", "Practice describing how different pieces of music make you feel."),
        ("Simple Group Performance", "Practice performing a short song or rhythm piece together as a class."),
    ],
    "Survival Skills": [
        ("Stranger Danger Awareness", "Learn simple rules for staying safe around unfamiliar people."),
        ("Basic First Aid: Cuts and Scrapes", "Learn simple steps for cleaning and covering a small cut or scrape."),
        ("What to Do in an Emergency", "Practice recognizing an emergency and calling for adult or emergency help."),
        ("Fire Safety at Home", "Learn simple fire safety rules and how to safely exit during a fire drill."),
        ("Road and Traffic Safety", "Practice safe habits for crossing streets and walking near traffic."),
        ("Water Safety Basics", "Learn simple rules for staying safe near pools, lakes, and the ocean."),
        ("Basic Map Reading for Safety", "Practice reading a simple map to find safe routes and landmarks."),
        ("Weather Emergency Basics", "Learn simple safety steps for storms, extreme heat, and other weather events."),
        ("Basic Knot Tying", "Practice tying a few simple, useful knots such as an overhand knot."),
        ("Staying Safe Outdoors", "Learn basic rules for staying safe while hiking or playing outdoors."),
        ("Understanding Emergency Numbers", "Learn when and how to use local emergency phone numbers."),
        ("Basic Home Safety Checklist", "Identify simple hazards at home and how to stay safe around them."),
        ("Introduction to First Aid Kits", "Learn what basic items belong in a first aid kit and their simple uses."),
        ("Recognizing Safe Adults", "Learn how to identify trusted safe adults to ask for help in different places."),
        ("Basic Wilderness Awareness", "Learn simple skills for staying found and safe while exploring nature."),
        ("Bicycle Safety", "Learn safe riding habits and the importance of wearing a helmet."),
        ("Severe Weather Drills", "Practice appropriate actions during earthquake, storm, or fire drills at school."),
        ("Basic Sun Safety", "Learn simple habits for protecting skin and staying safe in the sun."),
        ("Staying Calm in Stressful Situations", "Practice simple breathing and calming strategies for stressful moments."),
    ],
    "General Knowledge": [
        ("Flags of the World", "Learn to recognize flags from a variety of countries around the world."),
        ("Famous Inventors and Inventions", "Learn about a few inventors and the everyday inventions they created."),
        ("Animals of the World", "Explore interesting facts about animals from different habitats and continents."),
        ("Space Facts for Kids", "Explore fun facts about planets, stars, and space exploration."),
        ("Community Helpers", "Learn about the roles of firefighters, doctors, teachers, and other helpers."),
        ("Money Around the World", "Explore how different countries use different currencies and coins."),
        ("Famous Landmarks Quiz Topics", "Review interesting facts about well-known landmarks around the globe."),
        ("Sports Around the World", "Learn about popular sports played in different countries and cultures."),
        ("Fun Facts About the Human Body", "Explore interesting facts about how the human body works."),
        ("Introduction to World Languages", "Learn fun facts about how many languages are spoken around the world."),
        ("Famous Scientists for Kids", "Learn about a few scientists and their important discoveries."),
        ("Holidays Around the World", "Explore how different cultures and countries celebrate special holidays."),
        ("Endangered Animals", "Learn about animals at risk and simple ways people help protect them."),
        ("Fun Geography Facts", "Explore interesting and surprising facts about countries and continents."),
        ("Transportation Inventions", "Learn how cars, trains, and airplanes changed the way people travel."),
        ("Famous Explorers", "Learn about explorers who traveled to new places and what they discovered."),
        ("Introduction to Recycling Facts", "Explore fun facts about how recycling helps protect the environment."),
        ("Fun Facts About Oceans", "Explore interesting facts about ocean life and underwater habitats."),
        ("Weird and Wonderful Nature Facts", "Explore surprising and fun facts about plants and animals in nature."),
    ],
    "Cooking": [
        ("Kitchen Tools and Their Uses", "Learn the names and safe uses of common kitchen tools like measuring cups and spoons."),
        ("Understanding Food Groups", "Learn about the different food groups and why a variety of foods is healthy."),
        ("Measuring Ingredients", "Practice measuring dry and liquid ingredients accurately for a recipe."),
        ("Reading a Simple Recipe", "Learn to follow a recipe's ingredient list and step-by-step instructions."),
        ("Washing Fruits and Vegetables", "Learn why and how to properly wash fresh produce before eating it."),
        ("Making a Healthy Sandwich", "Practice assembling a simple, balanced sandwich with healthy ingredients."),
        ("Making a Fresh Fruit Salad", "Practice safely cutting soft fruits and combining them into a fruit salad."),
        ("Simple No-Bake Snacks", "Practice preparing easy snacks that do not require an oven or stove."),
        ("Introduction to Baking", "Learn basic baking terms and safety steps for helping bake simple treats."),
        ("Setting a Table", "Learn how to properly set a table with plates, utensils, and cups."),
        ("Food from Around the World", "Explore popular foods and dishes enjoyed in different countries."),
        ("Understanding Food Labels", "Learn to read simple food labels to find ingredients and serving sizes."),
        ("Where Food Comes From", "Learn how common foods travel from farms to the grocery store."),
        ("Making Simple Smoothies", "Practice blending fruit and yogurt safely to make a healthy smoothie."),
        ("Basic Baking Measurements", "Practice using cups, teaspoons, and tablespoons correctly in baking."),
        ("Food Safety Basics", "Learn simple rules for keeping food safe, such as washing hands and cold storage."),
        ("Cooking Around the Holidays", "Explore simple traditional foods associated with different holiday celebrations."),
        ("Growing Your Own Herbs", "Learn how simple herbs are grown and used to flavor food."),
        ("Introduction to Baking Bread", "Learn the basic ingredients and simple steps involved in making bread."),
    ],
    "Foreign Languages": [
        ("Greetings in Spanish", "Learn simple everyday greetings and polite phrases in Spanish."),
        ("Numbers 1-20 in French", "Learn to count from one to twenty in French."),
        ("Family Members in Spanish", "Learn simple vocabulary for family members in Spanish."),
        ("Days of the Week in French", "Learn the names of the days of the week in French."),
        ("Colours and Animals in Mandarin", "Learn simple vocabulary for colours and common animals in Mandarin Chinese."),
        ("Greetings in Mandarin", "Learn simple everyday greetings and polite phrases in Mandarin Chinese."),
        ("Numbers 1-20 in Spanish", "Learn to count from one to twenty in Spanish."),
        ("Basic Phrases in German", "Learn simple everyday phrases such as hello, please, and thank you in German."),
        ("Family Members in Arabic", "Learn simple vocabulary for family members in Arabic."),
        ("Greetings in French", "Learn simple everyday greetings and polite phrases in French."),
        ("Numbers 1-20 in Arabic", "Learn to count from one to twenty in Arabic."),
        ("Colours and Animals in Spanish", "Learn simple vocabulary for colours and common animals in Spanish."),
        ("Basic Phrases in Urdu", "Learn simple everyday phrases such as hello, please, and thank you in Urdu."),
        ("Days of the Week in Spanish", "Learn the names of the days of the week in Spanish."),
        ("Greetings in Urdu", "Learn simple everyday greetings and polite phrases in Urdu."),
        ("Numbers 1-20 in Mandarin", "Learn to count from one to twenty in Mandarin Chinese."),
        ("Basic Phrases in Turkish", "Learn simple everyday phrases such as hello, please, and thank you in Turkish."),
        ("Colours and Animals in French", "Learn simple vocabulary for colours and common animals in French."),
        ("Family Members in French", "Learn simple vocabulary for family members in French."),
    ],
    "Social Studies": [
        ("What Makes a Community?", "Learn what a community is and the different people and places within it."),
        ("Rules and Laws", "Understand why communities create rules and laws and why people follow them."),
        ("Rights and Responsibilities", "Learn about basic rights and responsibilities of being part of a community."),
        ("Local Government Basics", "Learn about the roles of local leaders and simple local government services."),
        ("Goods and Services", "Understand the difference between goods and services in a community."),
        ("Needs vs Wants", "Learn to distinguish between things people need and things people want."),
        ("Introduction to Money and Trade", "Explore how money and trade help people exchange goods and services."),
        ("Jobs in the Community", "Learn about different jobs and how they help a community function."),
        ("Family Traditions and Culture", "Explore how families celebrate traditions that reflect their culture."),
        ("Cultural Diversity", "Learn to appreciate differences in customs, food, and traditions across cultures."),
        ("Symbols of a Country", "Learn about flags, anthems, and other symbols that represent a country."),
        ("Being a Good Citizen", "Learn simple ways students can show good citizenship at school and home."),
        ("Then and Now: How Communities Change", "Compare how communities and daily life have changed over time."),
        ("Types of Communities", "Compare rural, suburban, and urban communities and their features."),
        ("Introduction to Voting", "Learn the basic idea of voting as a way groups make fair decisions."),
        ("Historical Community Landmarks", "Learn how local landmarks reflect a community's history and identity."),
        ("Working Together in a Community", "Explore how cooperation among people helps a community thrive."),
        ("Immigration and New Beginnings", "Learn simple, age-appropriate ideas about why families move to new places."),
        ("Conflict Resolution Basics", "Practice simple strategies for resolving disagreements peacefully."),
    ],
    "Physical Education & Self-Defense": [
        ("Warming Up and Stretching", "Learn simple warm-up and stretching exercises to prepare the body for activity."),
        ("Running and Jogging Basics", "Practice proper running form and pacing during physical activities."),
        ("Jumping and Landing Safely", "Practice safe jumping and landing techniques to avoid injury."),
        ("Throwing and Catching Skills", "Practice basic throwing and catching techniques with different sized balls."),
        ("Kicking and Dribbling Skills", "Practice basic kicking and dribbling skills used in games like soccer."),
        ("Balance and Coordination Games", "Practice simple activities that build balance and body coordination."),
        ("Introduction to Basic Stretch-Based Yoga", "Practice simple, child-friendly stretches and poses for flexibility and calm."),
        ("Jump Rope Skills", "Practice basic jump rope techniques and simple rhythm patterns."),
        ("Basic Self-Defense Awareness", "Learn simple, age-appropriate awareness skills for staying safe around strangers."),
        ("Setting Personal Boundaries", "Learn how to say no and set clear personal boundaries respectfully."),
        ("Fitness and Endurance Basics", "Learn simple exercises that build stamina and overall physical fitness."),
        ("Cooperative Team Building Games", "Practice group games that build teamwork and communication skills."),
        ("Basic Gymnastics Movements", "Practice simple, safe gymnastics movements like rolls and balances."),
        ("Introduction to Swimming Safety", "Learn basic water safety habits and simple swimming readiness skills."),
        ("Healthy Competition and Fair Play", "Learn the importance of good sportsmanship whether winning or losing."),
        ("Basic Martial Arts Movements", "Practice simple, safe introductory martial arts stances and movements."),
        ("Playground Safety Rules", "Learn simple safety rules for playing safely on playground equipment."),
        ("Relay Races and Group Activities", "Practice teamwork and coordination through simple relay race games."),
        ("Cool-Down and Recovery", "Learn the importance of cooling down and stretching after physical activity."),
    ],
    "Health Education": [
        ("Germs and How They Spread", "Learn how germs spread and simple habits that help prevent illness."),
        ("Handwashing Habits", "Practice proper handwashing technique and understand when it matters most."),
        ("Sleep and Rest", "Learn why sleep is important for growing bodies and how much rest kids need."),
        ("Exercise and Physical Activity", "Learn why regular physical activity keeps the body healthy and strong."),
        ("Dental Health Basics", "Learn proper brushing and flossing habits for healthy teeth and gums."),
        ("Healthy Snack Choices", "Learn to identify healthy versus less healthy snack options."),
        ("Staying Hydrated", "Learn why drinking enough water each day is important for the body."),
        ("Understanding Allergies", "Learn what allergies are and simple ways people manage common allergies."),
        ("Visiting the Doctor and Dentist", "Learn what to expect during routine doctor and dentist checkups."),
        ("Managing Screen Time", "Learn why balancing screen time with other activities supports good health."),
        ("Coping with Stress", "Learn simple strategies kids can use to manage stress and worry."),
        ("Building Healthy Friendships", "Learn qualities of kind, respectful, and supportive friendships."),
        ("Understanding Medicines Safely", "Learn simple rules about only taking medicine given by a trusted adult."),
        ("Growing Bodies: An Introduction", "Learn simple, age-appropriate facts about how bodies grow and change over time."),
    ],
    "ICT & Computer Science": [
        ("Parts of a Computer", "Learn to identify basic computer hardware such as the monitor, keyboard, and mouse."),
        ("Using a Keyboard and Mouse", "Practice basic typing and mouse skills like clicking and dragging."),
        ("What is the Internet?", "Learn a simple explanation of what the internet is and how it connects computers."),
        ("Staying Safe Online", "Learn simple rules for safe and responsible behavior while using the internet."),
        ("Introduction to Word Processing", "Practice typing, formatting, and saving a simple document."),
        ("Introduction to Digital Drawing", "Practice using simple digital tools to create a drawing on a computer or tablet."),
        ("Organizing Files and Folders", "Learn how to create, name, and organize digital files and folders."),
        ("Introduction to Email Basics", "Learn the basic parts and purpose of an email with adult supervision."),
        ("Using Search Engines Wisely", "Learn how to search for information online safely and effectively."),
        ("Digital Citizenship Basics", "Learn about being respectful, honest, and kind while using technology."),
        ("Introduction to Slideshows", "Practice creating a simple slideshow presentation with text and images."),
        ("Understanding Passwords", "Learn why strong, private passwords help keep accounts and devices safe."),
        ("Introduction to Coding Concepts", "Review basic ideas like sequences and loops as a foundation for programming."),
        ("Using Tablets and Apps Safely", "Learn simple rules for using tablets and apps appropriately and safely."),
        ("Introduction to Robotics", "Explore how simple robots are programmed to complete tasks."),
        ("Understanding Digital Devices", "Learn to identify and compare common digital devices used every day."),
        ("Introduction to Spreadsheets", "Learn the basic idea of organizing simple data into rows and columns."),
        ("Copyright and Sharing Online", "Learn simple, age-appropriate ideas about giving credit and respecting others' work online."),
        ("Typing Practice Basics", "Practice basic finger placement and typing simple words and sentences."),
    ],
}
